### ISSUE TITLE
componentDidMount not getting invoked in phantomJS

### ISSUE THREAD

**Issue by gauravg22068989** [facebook/react#10052]
componentDidMount not getting invoked while opening a page in phantomJS, is there any workaround for this because i need to do some automation stuff,  also i can't change the code to move somewhere else from componentDidMount.

Any help Appreciated.

Node Version v6.11.0
Phantom Version Latest
ReactJs Version Latest

**Comment by nhunzaker** [comment]
Hey @gauravg22068989!

Thanks for filing an issue! It's possible that this is a timing issue, like your PhantomJS script isn't waiting sufficiently for whatever needs to happen in componentDidMount, but it's hard to tell.

It would be really helpful for us if you could write an example test case that demonstrates this behavior. Otherwise, it will be hard to make headway.

**Comment by gauravg22068989** [comment]
Hey thanks for the reply was my mistake sorry for the bother thanks

**Comment by jzz4012650** [comment]
Come with the same problem, even after I added 2000ms delay before calling page.render() in Phantomjs.  

In addition, componentDidUpdate won't fire either.

**Comment by jzz4012650** [comment]
React: v15.5.4
Phantomjs: lastest
