### ISSUE TITLE
why would reordering be slow when passed index to key prop?

### ISSUE THREAD

**Issue by pycraft114** [facebook/react#10102]
https://github.com/facebook/react/issues/8410

there is already a same question in this issue but havent been answered.
ps. i have already read the documentation , but as @bondarewicz said it is a bit indistinct

**Comment by gaearon** [comment]
It's not gonna be slow per se, but there's just not going to be reordering at all. For example instead of moving `1, 2, 3` to `3, 2, 1` it would update 1 to be 3, and 3 to be 1. For deeper component hierarchies, these can be deeper (and potentially more expensive) updates. Keys are the only way React can know that something has moved rather than updated. This is not just important for performance, but also for correctness. In our example earlier local state of 1 would be preserved for 3, although conceptually these are different items. But if we used keys then local state would "move" together with the item.

Hope this helps!

**Comment by pycraft114** [comment]
Thx for the answer. but can you give me an example why React knowing that something has moved rather than updated is  important for performance?

**Comment by gaearon** [comment]
Because just moving a few trees around is usually cheaper than going "deep" into each tree and updating every single thing inside of it.
