### ISSUE TITLE
Base component's context overriden by child context

### ISSUE THREAD

**Issue by omerts** [facebook/react#10136]
**Do you want to request a *feature* or report a *bug*?**
Bug, but might be a feature

**What is the current behavior?**
When a base component defines its own context type, and an extending component also defines its own context, the base component's context is overriden by the child's context.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo 
https://jsfiddle.net/omerts/3Lnphonh/

**What is the expected behavior?**
Each component should have its own defined context

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 Tested in 15.6.1 & 15.5.4, other versions didn't test

**Comment by aweary** [comment]
Hey, @omerts! Thanks for the issue. When you extend a class, properties defined on the extending class will shadow properties defined on the extended class. This makes sense, as classes are just sugar for prototypical inheritance and when you're using `React.Component` you're just using JavaScript classes.

If you want to inherit the `contextTypes` from the base component you can explicitly include them in the extending component's `contextTypes` definition, like so:

```js
ChildA.contextTypes = Object.assign({}, BaseComonent.contextTypes, {
  testA: React.PropTypes.string
})
```

or, if you're using the object spread syntax, you can just do:

```js
Child.contextTypes = {
   ...BaseComponent.contextTypes,
   testA: React.PropTypes.string
}
```

React _could_ automatically do this for you, but that would involve more overhead (walking the prototype chain) and would require a breaking change, since people may already be relying on extending components overwriting base component `contextTypes`

Does that make sense?

**Comment by gaearon** [comment]
I would also add that generally [we don’t recommend using inheritance at all](https://facebook.github.io/react/docs/composition-vs-inheritance.html).
But if you are really confident you prefer to use it, yes, @aweary’s comment is correct.

**Comment by omerts** [comment]
@aweary makes perfect sense. Thank you for the detailed answer.

@gaearon You are right, we could refactor our code to compose + extract some pure functions, but it is a little too late now :)
