### ISSUE TITLE
React.Children.map() Why do you want to add  ‘.$’ to key

### ISSUE THREAD

**Issue by belief-cyf** [facebook/react#10166]
![image](https://user-images.githubusercontent.com/19991842/28148834-cf462dba-67bb-11e7-8301-0a3d7584ed52.png)

when i use the react-css-modules, It for my use of some key components added. $.  

This let me in the use of the key Have to first look at some key components have been added something extra

**Comment by absolutes** [comment]
very good

**Comment by phantom0424** [comment]
nice

**Comment by TheRobertOne** [comment]
the same question

**Comment by phantom0424** [comment]
it's time to close.

**Comment by belief-cyf** [comment]
@phantom0424  yes    you happy is ok

**Comment by gaearon** [comment]
This is because `Children.map` needs to be able to handle nested arrays like `[[<div key="x" />, [<div key="y" />], [[<div key="x" />, [<div key="y" />]]` but produce a flat array out of them. So we need to “prefix” the keys.

In general this is an implementation detail and it shouldn’t be a problem since the keys stack unique. I hope this helps!
