### ISSUE TITLE
Unknown prop `onForceTouchChange` on <div> tag

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#10177]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Notice that in [this document](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html) ontouchforcechange is a valid event on an div. However, when I do that, I get a warning logged out to the console: "Unknown prop `onTouchForceChange` on <div> tag"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

`<div onTouchForceChange={(e) => console.log(e)}>touch me on your iphone!</div>`

**What is the expected behavior?**

No warning

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

v15.6.1 on Chome on MacOS

**Comment by ccorcos** [comment]
Wait! I might be dyslexic -- I mixed the words up.

**Comment by aweary** [comment]
Hey @ccorcos, thanks for the issue. `ontouchforcechange` doesn't appear to be a standardized event type. React's synthetic event system does its best to remain in-spec with the HTML event standard. Historically we don't include platform-specific events that we can't polyfill for all our supported browsers. Since `ontouchforcechange` falls in that camp, we'd have to really consider whether we could include it.

That doesn't mean you can't use it though! It may be a little more verbose, but you can use refs and `componentDidMount` to get a reference to the element and add the event listener yourself with `addEventListener` (and remove it in `componentWillUnmount`)

**Comment by aweary** [comment]
I'm going to close this out, I don't think we can polyfill force change events and it's not standardized at all.
