### ISSUE TITLE
Make Uses of ReactDebugCurrentFrame.getCurrentStack Reentrant

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#10188]
I realized that the refactor to use ReactDebugCurrentFrame as a decoupled stack frame for error messages is not reentrant: https://github.com/facebook/react/pull/10105/files#r127573520

Fiber is not reentrant but other renderers might be. The synchronous server renderer is atm.

We should add tests for warnings between renderers, such as calling a server-render from within a client render, and update the set/reset callsites to use push/pop instead to account for that.

**Comment by gaearon** [comment]
I didn't end up adding push/pop to DebugFrame itself because relying on it would break ReactDOMServer 16.X + React 16.0, for example. We can reconsider this later, but for now I'm keeping track of reentrancy in ReactDOMServer itself, and restore the outer stack implementation on exit from the outermost ReactDOMServer call.

**Comment by Arissablue** [comment]
😎
