### ISSUE TITLE
CloneElement(children, { ref: (dom) => dom }) but dom is null in componentDidMount

### ISSUE THREAD

**Issue by chbdetta** [facebook/react#10183]
**Do you want to request a *feature* or report a *bug*?**
report a bug.

**What is the current behavior?**
CloneElement(children, { ref: (dom) => dom }) but dom is null in componentDidMount.
```js
class App extends React.Component {
  render() {
  	return (
    	<div>
    	  <Test><Children></Children></Test>
    	</div>
    );
  }
}

class Test extends React.Component {
  componentDidMount() {
  	console.log(this.dom); // here, the console show null.
  }

	render() {
  	return (
    	React.cloneElement(React.Children.only(this.props.children), {
      	content: 'Children inside Test',
      	ref: (dom) => {
        	this.dom = dom;
        }
      })
    )
  }
}

const Children = ({content}) => {
	return <div>{content}</div>
}

ReactDOM.render(<App name="world"/>, document.getElementById('container'));
```

However, if I replace `<Test><Children /></Test>` to `<Test><div /></Test>`, the `ref(dom)` gets the dom node correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
https://jsfiddle.net/wpygn0r2/

**What is the expected behavior?**
The `dom` should be the component instance / DOM node instance IMO.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Using React 15.6.1

**Comment by syranide** [comment]
Just to add, `console.log(dom)` inside the ref-callback will only emit `null` once as well.

**Comment by gaearon** [comment]
This is expected because `Children` is a functional component and you can't get a ref to it. If you replace it with a class you'll get a ref to its instance though, not to the DOM node.

I believe "Refs and the DOM" documentation section explains and covers these cases (and alternative approaches). 

We have a new warning for this in master but it hasn't made it into a release yet. So in the future you'll be warned if you add a ref to functional component.
