### ISSUE TITLE
Can we split off SVG property configs to a separate module?

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#10209]
Instead of supporting `<svg>` directly, if we require people to write:

```
const SVG = require('react-dom/svg');

<SVG> ... </SVG>
```

then we could avoid sending down SVGDOMPropertyConfig (and maybe other files? unknown) upfront. It would be good to investigate the potential benefits here.

cc @sebmarkbage @acdlite @gaearon @nhunzaker @jquense @aweary

**Comment by aweary** [comment]
I removed the SVG injection locally and compared build sizes and it looks like it'll save around 2kb gzipped, which is about a 5% size reduction. I don't _think_ there are any other SVG-specific files, but maybe there's SVG-specific config in other files that could be extracted?

**Comment by gaearon** [comment]
The only thing that feels off to me is we would add an API for the sake of those `camelCase` attributes still working. But it is not clear to me that people who use SVG in React get real benefits from this camel casing. With DOM wrapping components, the argument that composites want to read `this.props.someProperty` is compelling. But most SVG wrappers I’ve seen in the wild provide drastically different APIs over raw SVG, so it’s not clear to me how common you would read an SVG-like property in a composite in practice.

**Comment by aweary** [comment]
I agree that it feels like a weird API, and it hurts adoption for those who use third-party libraries with SVG components since they'd have to wait for those dependencies to update and release.

I think the main issue is the namespaced attributes. I don't think there's anything specifically advantageous about the `camelCase` attributes (at least nothing SVG specific). But the namespaced attributes like `xmlns:href` can't be used directly.

If we could handle those separately I think we could still get rid of, or at least significantly reduce, `SVGDOMPropertyConfig`? Either by continuing to special case the namespaced attributes or providing another way to define namespaced attributes.

**Comment by nhunzaker** [comment]
> it’s not clear to me how common you would read an SVG-like property in a composite in practice.

The most common I use are: `x`, `y`, `r`, `fill`, and `stroke`. We never pass down anything like `xlink:href`. It usually comes from a more abstract record for a data point that we might also want to use in table or list or something. I can't speak for everyone, but I would wager the usage is very low (maybe we should ask).

> If we could handle those separately I think we could still get rid of, or at least significantly reduce, SVGDOMPropertyConfig? Either by continuing to special case the namespaced attributes or providing another way to define namespaced attributes.

This seems like a reasonable trade-off. Short of updating the way JSX works, our hands are tied here anyway. I would be in favor of keeping camelcase names for namespaced properties. There also don't appear to be any `xlink` properties that have more than a single word name (`xlink:href`, etc). At least that we support presently.

If we were voting, I'd vote for this approach.

**Comment by trueadm** [comment]
In regards to namespaced properties, JSX already supports this just fine and I know other projects that support this (such as Inferno) so SVG can be used as if it were typed in and the current way it is handled in React. What if instead allowed others to import the current way optionally in React, otherwise we support default behaviour?

**Comment by gaearon** [comment]
I'm not sure what you mean by namespaces being supported. I'm not aware of JSX support for namespaces.

**Comment by trueadm** [comment]
@gaearon They're supported by `babel-plugin-syntax-flow`,  we just need to enable it in the React transform plugin.

**Comment by gaearon** [comment]
Oh, I think I see what you mean: https://github.com/facebook/jsx/issues/13#issuecomment-54373080

**Comment by gaearon** [comment]
We almost got rid of them in 16.
