### ISSUE TITLE
Implement additional async APIs in preparation for v16

### ISSUE THREAD

**Issue by acdlite** [facebook/react#10202]
- [x] `ReactDOM`/`ReactNative.activeUpdates`. Similar to what we currently call `ReactDOM.unstable_syncUpdates` except updates are batched, and flushed at the end of the batch regardless of whether it's nested inside `batchedUpdates`. (#10225)
- [x] Opt-in subtree to async mode
  - [x] Static flag on class components (`unstable_asyncUpdates`)
  - [x] `<React.unstable_Async />` component type

Items we're considering for minor 16 releases, but have decided not to ship in 16.0:

- Commit phase version of `willMount`/`willUpdate` (fires even for any deep set state in the subtree, and replaces the global `prepareForCommit`/`resetAfterCommit` host configs)
- Passive versions of `didMount`/`didUpdate`

**Comment by gaearon** [comment]
>ReactDOM/ReactNative.activeUpdates

Is that a "stable" API? The annoying thing about those APIs has always been that they hang from renderers. So universal components can't use them easily without importing both renderers or dependency injection. Is this something we want to solve?

**Comment by sebmarkbage** [comment]
It would be kind of difficult to implement as an isomorphic API because presumably multiple renderers will all need to add listeners to a growing set and then all flush together.

We talked ourselves into that this won't actually be a problem with `activeUpdates` as it was with `batchedUpdates` because `batchedUpdates` was used to add *more* batching where as `activeUpdates` is used to get less batching. The use case for `activeUpdates` is more about integrating with imperative APIs directly such as animation APIs or controlled components. As such it'll know more about the environment it is being used.

It is actually a bad idea to use this with generic Flux-like libraries because in async mode they're already batched by default. If you want to use `activeUpdates`, it is an indicator that the library doesn't support async mode and should probably be redesigned to support it. So it's more of a legacy thing in that case.

**Comment by sebmarkbage** [comment]
It is "stable" because the activeness is expected to be stable but the asyncness of the subtree (the `unstable_asyncUpdates` flag is expected to be unstable).

**Comment by gaearon** [comment]
That makes a lot of sense, thanks.

So as long as we're in compat mode `activeUpdates` is effectively a no-op, but it takes meaning when you opt into async?

**Comment by acdlite** [comment]
> So as long as we're in compat mode activeUpdates is effectively a no-op?

Almost...

```js
this.setState(A);
this.activeUpdates(() => {
  this.setState(B);
  this.setState(C);
});
this.setState(D);
```

In sync mode, B and C are batched. In async mode, B and C have task priority.

**Comment by sebmarkbage** [comment]
Specifically `activeUpdates` guarantees to fire before it ends.

```js
batchedUpdates(() => {
  this.setState(A);
  activeUpdates(() => {
    this.setState(B);
    this.setState(C);
  }); // flushes A, B, C
  this.setState(D);
}); // flushes D
```

Unlike nested batchedUpdates which doesn't.

**Comment by acdlite** [comment]
Just discussed offline a bit. The ideal behavior is that B and C flush but A does not, which means we need multiple levels of active-ness. Kind of like how we need multiple levels of hidden/offscreen priority.

For now, we'll disallow nested `activeUpdates`, since that's likely an edge case.

**Comment by sebmarkbage** [comment]
@acdlite This example doesn't have nested `activeUpdates`, but it does have a `batchedUpdates` outside the `activeUpdates`. That might be more common.

**Comment by acdlite** [comment]
True... The most common `batchedUpdates` case is event handlers, right? Which are active by default for now, anyway, so `activeUpdates` shouldn't be necessary?

**Comment by sebmarkbage** [comment]
Hm. They're not active right now are they? Maybe add that to the list? I'm not sure all should be. E.g. `load` might not need to be sync by default.

**Comment by acdlite** [comment]
Oh, I thought they were. Yeah we should figure that out before 16.
