### ISSUE TITLE
After integrating with jquery plugin (webui-popover) , dom events are not firing , due to that i'm unable to change the state of component.

### ISSUE THREAD

**Issue by BalakrishnaReddyPolu** [facebook/react#10233]
I'm trying to add this plugin with react component.
In click event of button , I have written the following code to enable popover.

  $("#openPopover").webuiPopover({url:'#popoverContent',trigger:'manual',closeable:true});
   $("#openPopover").webuiPopover('show');

popover is opening and content is showing .
but inside popover  content i have React components , there events are not firing due to this i'm unable to change the state of that particular component.

Can someone please give me some suggestion , How can I  do that?
Thanks.

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

In this case there is not enough information to help you. If you provide a full reproducing example someone might be able to take a look, but in any case the bug tracker is not the best place for this because answers get lost here.
