### ISSUE TITLE
When I visit home page, all of the styles in the project will load too?

### ISSUE THREAD

**Issue by CoderLim** [facebook/react#10242]
```
Routes: 

<Router history={hashHistory}>
 <IndexRoute component={HomePage}/>
 <Route path="/page1" component={Page1}/>
 <Route path="/page2" component={Page2}/>
</Router>

Page1: 

 import './page1style.css';
 export default class Page1 extends React.Component {}

Page2: 
  import './page2style.css';
  export default class Page2 extends React.Component {}
```

Like the code, when I visit 'http://localhost:8080'(i.e. HomePage), `page1style.css` and `page2style.css` will load, but I still not visit page1 and page2, is it normal?

**Comment by MehdiAlouafi** [comment]
Hello there : 

I suppose you are using a module bundler, presumably webpack, that uses the css loader which handles those type of imports.

If so it's normal because webpack-dev-server bundles your whole application and exposes the bundle.js file at /bundle.js so by the time you are visiting any page webpack has already : 

- bundled your code
- triggered the css-loader that extracts all of your css imports and injected them into your page

If I'm not answering your question please provides us with more context (what module-bundler are you using for example)

**Comment by gaearon** [comment]
If you're using Create React App, yes, CSS code from all files will be concatenated into one CSS file in production. Hope this helps!

Other than that this is a question about your module bundler (presumably Webpack) rather than React. We use issue tracker for bugs and feature requests for React itself so I'll close this. I suggest to ask questions like this on StackOveflow where more people can see them.

**Comment by CoderLim** [comment]
Thanks, @MehdiAlouafi I used webpack, your answer is helpful. So, is there any way I can add (or remove) css when I'm visiting (or leaving) the page.
