### ISSUE TITLE
Safari - instanceOf checks fail

### ISSUE THREAD

**Issue by iq-dot** [facebook/react#10263]
I see a bug on Safari 10 where the instanceOf checks incorrectly fail.

I am rendering a Player component that internal renders in JSX a *video* tag.

This is result in Safari:

```js
myVideoElRef instanceof Element // false
myVideoElRef instanceof HTMLVideoElement // false
myVideoElRef.constructor // HTMLVideoElement()
```

So the constructor is correct but the instanceof checks fail.

Expected behaviour is for the first two to return true.

Any tips to work around this safely ? It is breaking my component on a third party library that does a instanceof check on my video element.

**Comment by gaearon** [comment]
This doesn't sound related to React so I would suggest to ask elsewhere (e.g. StackOverflow). I don't think you can work around something like this on React level since the problem is with browser's DOM implementation and the check is in third party component. If anything I would recommend to ask that component to completely remove this check. Because instanceof check is not even expected to work in some cases: for example if your app is working across iframes (which have their own global Element).
