### ISSUE TITLE
Some invariant messages aren't extracted

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10328]
Not sure why but I can see these messages in the beta bundles:

```
ReactDOM.render(): Invalid component element. Instead of passing a string like 'div', pass React.createElement('div') or <div />.
Missing injection for fiber findDOMNode
Missing injection for stack findDOMNode
Element appears to be neither ReactComponent nor DOMNode. Keys: %s
Target container is not a DOM element.
```

I'd like to understand why.

**Comment by gzhappysky** [comment]
Which invariant message aren't extracted, could you provide a jsfiddle demo?

**Comment by iansu** [comment]
Some variations of those error messages are missing from `codes.json` (on `master` anyway). So it looks like the `extract-errors` script wasn't run prior to doing the build. I've verified that running `extract-errors` and then doing a build does remove those error messages.

**Comment by iansu** [comment]
On closer inspection something strange seems to be happening with the `extract-errors` script. As it runs new errors are added to `codes.json`, then the file is reverted. This seems to happen repeatedly (possibly for every build that is produced). The end result is that `codes.json` ends up in the same state it started in with no new errors added.

I believe it worked for me earlier because I had terminated the `extract-errors` script at some point so `codes.json` was not reverted and the new error messages were present when I did a build.
