### ISSUE TITLE
dynamic create child element,the className did not update correct 

### ISSUE THREAD

**Issue by pigracing** [facebook/react#10326]
the code like this:

````
var MyApp = React.createClass({
	getInitialState:function(){
		return {
			ch:['a','b','c','d']
		}
	},
	onClick:function(){
		this.setState({ch:['c']});
	},
	onClick1:function(){
		this.refs.a.className='wuwu';
		this.refs.a.name='1';
		this.refs.a.value='d';
	},
	render:function(){
		return (
			<div>
				<FormItem>
					{
						this.state.ch.map(function(obj,index){
							console.log(index==0?'haha':'wuwu');
							return <input type="text" key={index} value={obj} ref={obj} name={index} className={index==0?'haha':'wuwu'}/>
						})
					}
				</FormItem>
				<div>
						<input type="button" value="redux" ref="b" onClick={this.onClick}/>
				</div>
				<div>
						<input type="button" value="change" ref="c" onClick={this.onClick1}/>
				</div>
			</div>
		)
	}
})

ReactDOM.render(<MyApp/>,document.getElementById('main'));

````

first, click change button, change the second child's className, and then, click redux button, now the FormItem has only one child, and the className must be haha, but the className is wuwu。

I think about that may be a bug for vdom-render compute，or how can I fix this problem?

**Comment by pigracing** [comment]
````
var FormItem = React.createClass({
	componentDidMount:function(){
		console.log(this.refs);
	},
	render:function(){
		return (
			<div>
			{this.props.children}
			</div>
		)
	}
});
````

that is the FormItem's code

**Comment by gaearon** [comment]
React does not support mutating attributes DOM nodes via refs that are already specified by React. For example, changing `className` on a DOM node that already has `className={something}` in `render()` method. So if you do this, things might behave unexpectedly.

In general you should avoid using `refs` for UI logic. They are useful for [imperative operations](https://facebook.github.io/react/docs/refs-and-the-dom.html) (e.g. setting focus) or for [integrating with third party libraries](https://facebook.github.io/react/docs/integrating-with-other-libraries.html).

It’s hard to say more because it is not clear why you were attempting to do this. But I hope this helps.
