### ISSUE TITLE
How to make google chrome devtool play well with reactjs ?

### ISSUE THREAD

**Issue by eromoe** [facebook/react#10365]
Hi,  It is usually difficult to debug reactjs site. I have know how react and redux work, but there are many projects don't follow the official document, they write a bunch code to customize. That make a project difficult to understand(such as https://github.com/react-boilerplate/react-boilerplate).

The easiest way to know the whole working flow is follow debugging. But Chrome devtool doesn't play well with reactjs.

For example:

1. breakpoint didn't hit
    [![enter image description here][1]][1]

    `console.log('anno reducer',state)` did print `anno reducer State {_map: Map}` , but didn't hit any breakpoint. (Here I want to know where the error come from and find out why, not familiar that node package, so need debug.)

2. Some lines can't not set breakpoint:
    [![enter image description here][2]][2]

3. Wrong scope:
    [![enter image description here][3]][3]
    As you see, `action.type` is `CHANGE_LOCALE` now, but scope shows that `action` is `undefined`.

I googled this but nothing helpful.I really want a working debug solution, that would help much.

  [1]: https://i.stack.imgur.com/C7pyz.png
  [2]: https://i.stack.imgur.com/8fKgk.gif
  [3]: https://i.stack.imgur.com/PwUdr.png

**Comment by gaearon** [comment]
The issue with breakpoints is not related to React but to the bundler you're using (Webpack). They've fixed a few such bugs in the past so try updating. It it doesn't help try changing `devtool` Webpack setting to `'cheap-module-source-map'`. As I recall it works well either breakpoints.

In general it looks like you maintain your own Webpack configuration. I don’t recommend this unless you know Webpack really, really well. Caveats like the one I mentioned above are really not obvious and you can spend a lot of time debugging a broken setup. Instead I recommend using a tool like [Create React App](https://github.com/facebookincubator/create-react-app) that manages configuration for you, and ensures you have a working setup. Its README also provides a list of alternatives in case you need a different feature set.

If you can reproduce this problem with Create React App please file an issue there and we will take a look. Otherwise it could be a combination of factors (old Webpack, bad Webpack configuration, etc) that’s causing this, and it is impossible for us to guess what went wrong.
