### ISSUE TITLE
onMouseLeave strange behaver when has disabled child element

### ISSUE THREAD

**Issue by zombieJ** [facebook/react#10396]
Bug report.

Here is the demo: https://jsfiddle.net/qz3fytwe/1/

When `<div>` contains an disabled button. React can trigger `onMouseEnter` correctly in div but `onMouseLeave` not trigger when mouse on the button and move down out of the div.

I tried `15.4.0` & `15.6.1`  in Chrome has the issue. Not sure whether it appear before that.

**Comment by zombieJ** [comment]
hi @gaearon, could you pls take a look?

**Comment by jquense** [comment]
Hi there, yes mouse events don't work on disabled elements generally, this is a browser implementation detail and not something easily addressable (if at all). There are already a few issues about these events and mouse events and some PRs attempting to make the behavior more consistent. 

In all likelihood though, in the future react will defer to the behavior of the native events and their behavior which means they won't fire on disabled elements in some way.

**Comment by aweary** [comment]
@jquense in the example @zombieJ  provided the `leave` and `enter` events are registered on the div containing the disabled button, not the button itself. In this case, I think it should be dispatching the `leave` event, since it dispatches an `enter` event and [it works as expected with regular event listeners](https://jsfiddle.net/jyf1pf7t/)

**Comment by jquense** [comment]
Yeah the enter/leave traversal logic is implemented in terms of from/to elements. So yeah, unlike the native event react will drop events in odd places, because one of the elements being moved to or from is disabled, and so it's pair can't be accurately calculated. In the fiddle leave, works if you exit right from the button then down. It's missing the other directions because the surrounding div has no dimension around the button and so isn't firing mouseover/mouseout events (and the button fires nothing)

I meant to close with some refs to the previous issues: 

https://github.com/facebook/react/issues/10109
https://github.com/facebook/react/issues/4251

The various PRs I have up will at least bring the behavior in line with the native events: 
https://github.com/facebook/react/pull/10247
https://github.com/facebook/react/pull/9824
https://github.com/facebook/react/pull/10269

**Comment by Jony-Y** [comment]
@jquense seems like this will only be solved in 17.0.0 according to [#11972](https://github.com/facebook/react/issues/11972)

Is there some w/a for now for us to use?

**Comment by RNachmanyAnyVision** [comment]
This issue still open.
We create native event listener (with ref) to avoid the problem.
