### ISSUE TITLE
"noshade" attribute not working for <hr> element

### ISSUE THREAD

**Issue by probablyup** [facebook/react#10400]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

passing `noshade` or `noShade` to an `<hr>` element doesn't work - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr#attr-noshade

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal 
demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

https://jsfiddle.net/84v837e9/186/

**What is the expected behavior?**

the attribute should be added to the rendered DOM

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.x

**Comment by syranide** [comment]
@probablyup It's deprecated, don't use it.

**Comment by probablyup** [comment]
It is, but there are plenty of other deprecated properties that React
supports and are still widely available. Not sure how else to get the same
effect as well.

**Comment by aweary** [comment]
I don't recommend using deprecated attributes simply because they still exist, but once https://github.com/facebook/react/pull/10385 is merged you'll be able to set attributes that aren't in the whitelist (including deprecated attributes).

In the meantime, you can just use CSS to get the same effect or use a `ref` to manually set the attribute if you really need to.
