### ISSUE TITLE
dist/react-dom-server.min.js bug

### ISSUE THREAD

**Issue by flyhighy** [facebook/react#10455]
I think it's a bug

when I use react-dom-server like this
``` javasxript
var ReactDOMServer = require('react-dom/dist/react-dom-server.min');
```
TypeError: Cannot read property 'ReactCurrentOwner' of undefined occurs

I find the reason is "react-dom/dist/react-dom-server.min.js" requires react like 'module.exports=e(require("react"))'

it shoule be 'module.exports=e(require("react/dist/react.min.js"))';
I try to change it and it works 

react version 15.6.1
react-dom version 15.6.1

**Comment by gaearon** [comment]
It is not supported to use UMD bundle in a Node environment. Please either use Node entry point or precompile the whole Node app (in which case you can alias both `react` and `react-dom/server` to UMD bundles).

I'm not sure why you're doing this. But if it's because of performance there are some good news: in React 16 everything is a bundle by default so you won't need this hack. There is a 16 beta out that you can try.

I hope this helps!

**Comment by flyhighy** [comment]
Yes，I find react ssr in my project，'process.env.NODE_ENV' executes more than 37375 times，this  takes 10 milliseconds，so I want to optimize it. 
and when the version 16 would release

**Comment by gaearon** [comment]
In a month or so hopefully. You can already try the beta and report any issues: https://github.com/facebook/react/issues/10294

**Comment by flyhighy** [comment]
ok，thank you very much
