### ISSUE TITLE
Image loading failure

### ISSUE THREAD

**Issue by gitfortress** [facebook/react#10485]
```javascript
var imag = require('./roomIcon/jz.jpg');
<img src={imag} alt='Image loading failure' style={{objectFit:'contain'}}/>
```

**Comment by gitfortress** [comment]
![qq20170818-104655](https://user-images.githubusercontent.com/21328401/29442218-caafc83e-8402-11e7-9744-9414c82c3668.png)
this is the directory structure. I don't known why do jz.jpg loading  failure.

**Comment by Necmttn** [comment]
do you have GitHub repo which I can have a look?

**Comment by aweary** [comment]
@gitfortress there isn't enough information here for us to help you at all. If you think this is an issue with React itself, please provide the information that was requested from you in the issue template you deleted.

With that said, this seems like a usage/support question. I would check your build setup and make sure that image loading is setup correctly. Since I don't think this is a bug with React I'm going to close this out. Please check out [one of the many great community support resources](https://facebook.github.io/react/community/support.html) for help with questions like this.
