### ISSUE TITLE
some issue between functional components and classical components

### ISSUE THREAD

**Issue by Lanseria** [facebook/react#10503]
# Problems between functional components and classical components
**detail code as follow:**
[jsbin](http://jsbin.com/guxugijexa/1/edit?js,console,output)
part of Problem code
```js
function UserGreeting(props) {
  return <h1>Welcome back!</h1>;
}

function GuestGreeting(props) {
  return <h1>Please sign up.</h1>;
}
```
this code can run and no error.
but use classical components method will not true to run
```js
class UserGreeting extends React.Component{
  render() {
    return (
      <h1>Welcome Back!</h1>
    )
  }
}
class GuestGreeting extends React.Component{
  render() {
    return (
      <h1>Please sign up!</h1>
    )
  }
}
```
[you can also run this page in jsbin](http://jsbin.com/dosodidoxu/1/edit?js,console,output)

why?
classical component isn't more feature than function component?
but this simple can't run and will report error

please tell me where i am wrong? whatever i am a newer.

**Comment by aweary** [comment]
Hey @Lanseria! It looks like the issue is related to JSBin and how its compiling the JavaScript. Here's [a JSFiddle with your same code](https://jsfiddle.net/gk99gbc3/) and you can see it's running fine. By pausing on exceptions with your JSBin example I found that its failing due to a `_get` utility method that is failing to exit a `while` loop.

So there's nothing wrong with your code! It looks to be an issue with JSBin itself.
