### ISSUE TITLE
OnMouseMove outside window while MouseDown

### ISSUE THREAD

**Issue by upanicon** [facebook/react#10519]
The SyntheticEvent OnMouseMove will stop triggering when the mouse is moved outside the window.
While instead the browser event of Chrome will continue to trigger mousemove when mousedown is active. 
Can this behavior be implemented for the SyntheticEvent?

**Comment by jquense** [comment]
Hi @upanicon , I've never noticed that behavior before, but my hunch is that its actually a Chrome bug. I don't believe any mounts events should keep firing once you are outside the window. I'm honestly a bit surprised tho that React doesn't have this behavior as well since we are using the native events to know when to fire Synthetic events. Maybe @aweary  or @nhunzaker have some insight on this quirk?

playground: https://jsfiddle.net/q7g923cq/4/

**Comment by upanicon** [comment]
i dont see it as a bug of chrome. i guess this behavior is a workaround to not break drag events.
i noticed this by dragging a popup window with a handler inside. 
with the synthetic event the motion will stop when the mouse has been moved too fast, while ...addEventListener('mousemove', ... ) keeps it moving.

**Comment by gaearon** [comment]
I can't reproduce Chrome emitting `mousemove` events outside the window on DOM elements. The only way I can get it working is with a handler at the top level (`window`) but you can't make top-level handlers in React (at least, not currently).

Without more code examples it's hard for me to understand what issue is being discussed.

**Comment by j1mie** [comment]
A good example of this behaviour can be seen in Google maps. More information [here](https://stackoverflow.com/questions/1685326/responding-to-the-onmousemove-event-outside-of-the-browser-window-in-ie).
