### ISSUE TITLE
Performance issue in react

### ISSUE THREAD

**Issue by piu** [facebook/react#10566]
I am currently using reactJS version "15.0.1" in my web application. In one of the feature we need to keep pooling some information continuously after each 2 seconds. So we receive the response which is List of some object(700/1000 items in list) which we update and show in the react web application. 

The Problem is after some time the application becomes unresponsive and takes too much time for any operation. On profiling I found its render, batch updates and dispatch event in react that takes the longest time. 

Is there any recommended way to get away with the performance issue in react. The feature needs to be refreshed every 2 seconds and list size is more than 1000 items each time.

The performance issue is observed in IE and Chrome browser.

**Comment by jquense** [comment]
Hi there @piu, your issue is not an uncommon one and a pretty frustrating performance bottleneck big lists on the web (not just in React). Generally with lists that large you want to save the browser from doing extra work by only actually rendering the lists items that are visible (maybe like 10-20 items at a time) and as the user scrolls render more, and remove the previous ones. This technique is generally called windowing or virtualizing lists. There are few good libraries that exist for building these sorts of lists, including react-virtualized, and react-list.

In addition (or perhaps instead of) you can try and make use of `shouldComponentUpdate` on your list item components so only the ones that change actually update as well as making sure you have `key`s. You'll probably have better luck getting feedback as well using one of the many excellenet support avenues: https://facebook.github.io/react/community/support.html over the issue tracker here which is generally reserved for bug reports and feature requests
