### ISSUE TITLE
[question] state object and setState()

### ISSUE THREAD

**Issue by bhutaninitin** [facebook/react#10636]
Suppose if I have 100 objects and each maps to 100 different DOM components. Which of the following coding practice helps react setState() save work:

**Practice 1:** 
```
this.state={allObj: {"one": true, "two": true, "three": false, "four": true}}

updateState(val,key){
var tmpobj=this.state.allObj;
tmpobj[key]=val;
this.setState({allObj: tmpobj})
}
```

OR

**Practice 2**:
```
this.state ={
one: true,
two: true,
three: false,
four: true
}

updateStateOne(val)
{
this.setState({one: val})
}

updateStateTwo(val)
{
this.setState({Two: val})
}
```

**Comment by jquense** [comment]
In most cases they are equivalent because React batches the setState calls. Technically Practice 1 is  going to be faster, and more memory efficient (probably) because you are mutating the original state object before setting it again. However its also less safe, and not recommended to mutate the state object in-place like that. I wouldn't worry about it unless you are able to measure some noticeable bottleneck there
