### ISSUE TITLE
scrollTop changed on chrome while loading page

### ISSUE THREAD

**Issue by jayenashar** [facebook/react#10717]
**Do you want to request a *feature* or report a *bug*?**

***bug***

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

tried to make a minimal example, but could not: https://jsfiddle.net/kv1r7ea6/7/ .  tried to create a proxy to trap the change to scrollTop (but couldn't figure out how to make a proxy for document or body).  tried to look through react source to find where scrollTop is changed, but didn't find anything that set it, only saved it.

* http://27.32.182.254/v4/
* quickly click on buy or rent
* page scrolls down a little
* quickly click on preferences
* page jumps to top

**What is the expected behavior?**

* http://27.32.182.254/v4/
* quickly click on buy or rent
* page scrolls down a little
* quickly click on preferences
* page scroll does not change

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

15.5.4, 15.6.1

chrome 57 on linux, chrome 60 on android, not firefox 55 on linux

did not test on previous versions of react

**Comment by aweary** [comment]
Hey, @jayenashar!

From what I can tell, this isn't a React-specific issue. React doesn't change the behavior of `window.srollTo`, and it looks like you're just rendering a simple component with a couple `onClick` event handlers registered.

Since we try to reserve this issue tracker for bug reports and feature requests, and there's nothing here indicating that React is contributing to your issue, I'm going to suggest that you refer to our [Where to Get Support](https://facebook.github.io/react/community/support.html) doc page for a list of resources where you can get help with usage questions like this.

Thanks!

**Comment by jayenashar** [comment]
Thanks for having a look @aweary .  Do you have any tips on how I can trap the change to `body.scrollTop`?  It could just be a chrome bug, but it seems to happen after `render()` and before `componentDidUpdate()` so I thought it's in react.  I saw a few lines of code in react that listen to `onscroll` to save `scrollTop`, though I don't know for what purpose.  Saw a few comments that in the future, the scroll position will be restored, but it doesn't seem react is doing that yet.  Will post on StackOverflow as well.

**Comment by jayenashar** [comment]
ah, nevermind!  running under the assumption it's a chrome bug, I found a fix (still can't make a minimum test though).  I change the URL using the history API when I scroll and before the page finishes loading, so chrome restores the position even though the page has scrolled.  Doesn't happen if the user scrolls, only if the scroll is done through js.
