### ISSUE TITLE
Update React license FAQ/update license itself

### ISSUE THREAD

**Issue by thoughtbyte** [facebook/react#10719]
I've read the previous discussions regarding the React (and other Facebook OSS) license, in particular #10191, and I agree with most of the clarificatory remarks (esp. by @gaearon & @sebmarkbage) that Facebook doesn't intend to use this license offensively.

However, after today's [announcement](https://ma.tt/2017/09/on-react-and-wordpress/) by Automattic that WordPress.com's Calypso and WordPress Core's Gutenberg will no longer be using React, I believe that Facebook's efforts in clarifying the React license have clearly fallen short. At the least, the FAQs need to be extended and explained in much greater detail. Ideally, this recent announcement should cause Facebook to rework the license altogether.

Some have said that the issue tracker is not the place for this discussion. I believe that this is untrue (though I apologize for causing noise). The growing apprehension to use React will undoubtedly have effects down the line regarding the React ecosystem. Buy in from the WordPress core community would have been a _huge_ benefit to React (I think? maybe I'm wrong about that). Further, this issue track is where this license issue will have the greatest exposure.

Perhaps, as the Automattic post implies, the problem is not the license itself, but the perception of the license. That problem is an issue for React, and the issue will only get worse without being addressed more genuinely. I know that the developers here can't do that, but I hope that something can be done, or that these concerns can be funneled through the proper channels.

**Comment by cmtt** [comment]
Treating open source in such an abysmal state just underlines how Facebook continues to abuse concepts invented for the public domain. I chose to use [Preact](https://github.com/developit/preact) using [preact-compat](https://github.com/developit/preact-compat) anyway.

**Comment by markwatney87** [comment]
My response is moving to vue.js.  The sooner companies do this, the sooner our worries will be over and this will be a non issue!

**Comment by gaearon** [comment]
Please trust me we are doing all we can in this area but it is very hard to do without legally endangering the company and harming our future ability to open source libraries like React.

[This post](https://code.facebook.com/posts/112130496157735/explaining-react-s-license/) by Adam Wolff (my manager’s manager) is all the clarification we can legally share at the current moment. We also previously worked on publishing [a FAQ](https://code.facebook.com/license-faq) (which I’m sure you read) that addresses several misconceptions. To give you a sense of how hard it is to publish such statements, this took several months of internal discussion.

If you’re interested in third-party posts, I personally found [this analysis](https://medium.com/@ji/the-react-license-for-founders-and-ctos-b38d2538f3e5) to be fair and helpful. But I need to make it clear its author does not represent Facebook (but has some context around how FB picked this license at the time).

>Perhaps, as the Automattic post implies, the problem is not the license itself, but the perception of the license.

That is my understanding as well.

However, please note that you are not the first person to bring it up though. We get bombarded with questions and misunderstandings about the license every day. This is getting to a point where on some days it is actively impeding our technical work. Filing more issues about this is only making it worse.

You can contact [Adam Wolff](https://mobile.twitter.com/dmwlff) if you have specific concerns, and he might be able to help you out. But we will close and lock further GitHub issues about this. You can see what the previous discussions have turned into.

In practice, GitHub issues won’t persuade a company that it doesn’t need extra legal protection when it’s constantly battling meritless lawsuits, with potential costs going up to a billion in the past.

Finally, I would like to highlight that React is not a vanity project. Unlike many other companies, Facebook open sources **core pieces of its infrastructure**. This comes with increased legal risk. At many other companies, we wouldn’t have been able to do that, but at Facebook we can, and mostly thanks to this license. I’m sad that some people can’t use React, whether because their companies engage in offensive patent litigation, or because they’re just scared, but I’m still thankful we can do our part to move the industry forward.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
