### ISSUE TITLE
Attach third-party tools to monitor component state updates

### ISSUE THREAD

**Issue by omerts** [facebook/react#10736]
**Do you want to request a *feature* or report a *bug*?**
feature, that exists in previous releases of react

**What is the current behavior?**
feature is not implemented

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** React 16, worked in previous versions

Hey,
We would really like to be able to use ReactInstrumentation with Fiber. I have found @gaearon 's pull request, but work on it was stopped. Would like to know why? and if we can pick this up and implement it.

https://github.com/facebook/react/pull/8152
(I have also asked why in the pull request, but figured it might get ignored since it is a closed pull request)

Omer

**Comment by gaearon** [comment]
The indirection there was significantly slowing down development builds of React. Which hooks in particular are you missing?

**Comment by omerts** [comment]
> The indirection there was significantly slowing down development builds of React
Could you please explain?

> Which hooks in particular are you missing?
We have added our own custom hook, onStateChanged. 
It has to do with this pull request: https://github.com/facebook/react/pull/6936
We are now working on adding this to V16.
Correct it me if I am wrong, but I think react it self relies on some of the hooks to display different warnings.

I really want to pick this up and work on it, but want to understand why work on it has stopped, and if I should actually work on it.

**Comment by gaearon** [comment]
>Could you please explain?

The extra indirection in hot parts of the code was making the development builds run slower. We made them about 2x faster by removing it.

>I really want to pick this up and work on it, but want to understand why work on it has stopped, and if I should actually work on it.

I don't think we'll be adding ReactInstrumentation back in the same manner it existed. But in general we're interested in *some* way to expose it. Perhaps based on the protocol React DevTools already uses.

The first step for that would probably be to move [React DevTools backend](https://github.com/facebook/react-devtools/blob/e253c663e3668140c58b332ebee08452a02ab9aa/backend/attachRendererFiber.js) into React repo and integrate it with our tests so that we can know when it regresses. But this is only the first step, and even that will require the implementor to dive into how DevTools works which might be a bit overwhelming.
