### ISSUE TITLE
Add an official React FAQ to the docs

### ISSUE THREAD

**Issue by markerikson** [facebook/react#10740]
I wrote the [Redux FAQ](http://redux.js.org/docs/FAQ.html) last year, and it's been pretty helpful for answering actual frequently asked questions.  It'd be great if we could add a similar FAQ directly to the React docs.

Tim Arney already has a standalone "React FAQ" site at https://reactfaq.site/ that would be a great starting point for a lot of the material.  My [React/Redux links list](https://github.com/markerikson/react-redux-links) is also a useful source of info in general.

I'm opening this up as a place to discuss possible formatting for a React FAQ, as well as possible topics and volunteers to help write it.

**Comment by ihtml5** [comment]
This is a very good idea. I like this, as in react-native, to provide learning materials, through faq answer doubts

**Comment by timarney** [comment]
@markerikson outside of Redux, JS syntax + React Router ... what are some common questions that seem to come up on reactiflux?

Looking at 
https://stackoverflow.com/questions/tagged/reactjs?sort=frequent&pageSize=50

There's not too many straight React questions.  

I think an FAQ section could be valuable, just looking to surface the right questions.

**Comment by satiewaltz** [comment]
Would love to see something like this directly in the React documentation - acting as a quick reference for those who need it.

Due to React's highly unopinionated nature: It'd be great to use it as a small reference to the different styles and approaches people have building React apps. From the component level all the way up to philosophies on architecture. 

As well as help people that are new to React accomplish everyday tasks/get over pitfalls be imparted with the full understanding of what is going on behind the scenes.

Here are some ideas on questions that could be apart of a FAQ:

- A section on styling and CSS:
  - What is the difference between inline styles and CSS?
  - What are ways to do JavaScript animation in React?
  - Can I build animations using React's `setState()`?
- A section on common performance issues regarding state updates.
- A section on state and `setState()`:
  - What `setState()` does exactly?
  - How do I do ordered state updates?
  - What is the difference between passing an object or a function in `setState()`?
- A section on architecture:
_(It doesn't need to be comprehensive. Acts as an outline of recent developments the community has found when building with React over the years but without giving a side to a certain style)_:
  - Is there a recommended way to organize a React application's file structure? If not, what are some commonly used strategies? 
  - How can I make the transition to React from other component libraries?
- A section on React's internals:
  - What is the Virtual DOM? What Is the difference between it and the Shadow DOM?
  - What is React's new reconciliation algorithm in React 16?
---
_In foresight to the answers to each FAQ in the future: It'd be best to be cautious of not pointing to one method as being particularly superior to another. Unless it's an anti-pattern of course. Due to the many numbers of ways one can build with React. And the differentiating costs and benefits each way can have.  ("Common Anti-patterns" sounds like it could be a section of its own perhaps?) Though I could be entirely wrong about this thought of mine._

**Comment by markerikson** [comment]
@satiewaltz : yup, totally agree.  That's basically the approach I tried to take with the Redux FAQ - enough info to answer the question and lay out some options, and pointers to more resources.

**Comment by darrenlittlejohn** [comment]
I'm in the LEARN Academy JS/React Bootcamp at the moment. If I can contribute to the writing in some way I'd be happy to. I don't know that I'd have the expertise yet to be knowledgable on the topics but I can certainly edit for clarity and so forth.

**Comment by timarney** [comment]
@darrenlittlejohn it would be great to get your perspective on what you have struggled with learning React.  Anything that looking back or at the moment an FAQ section might cover that would help where there is confusion?

**Comment by gaearon** [comment]
I agree we should do it. We'll be moving the website into its own repo soon. Let's get started after that's done.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄

The documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

If you're willing, please open a new issue in that repository. (Sorry for the inconvenience!) I have been manually moving most issues but this one's a bit long and I don't want to misrepresent it.

**Comment by markerikson** [comment]
Oh, sure, make _me_ do all the work on this one... :)

**Comment by bvaughn** [comment]
Sorry 😅  I've closed and moved 20 or 30 already this morning and my brain is starting to fall asleep.
