### ISSUE TITLE
[Feature request] Create components with Component.create()

### ISSUE THREAD

**Issue by pretodor** [facebook/react#10757]
I propose the `createReactClass()` function from the `'create-react-class'` module be added as a `create()` member to the `Component` constructor.

By using the `Component.create()` syntax the following confusion points are eliminated:
- **`constructor(props) { super(props) }` vs `this.props`.** Developers won't need to add `constructor(props) { 
super(props) }` inside their components. They will only deal with `this.props`.

- **`constructor(props) { this.state = {} }` vs `this.setState({})`.** Developers won't need to remember the special case when to assign to `this.state`. They will only use `this.setState()`. Initialising the state will be done inside the `getInitialState()` method.

- **`constructor(props) { this.m = this.m.bind(this) }`.** Developers won't have to manually bind their methods.

- **`function MyComponent(props) {}` vs `class MyComponent extends Component {}`.** Developers won't have to use 2 syntaxes for defining their components. Stateless components will be transpiled as function declarations for better performance. Moreover, transitioning from a stateless component to a stateful one will be painless.

**Comment by aweary** [comment]
Hey, @pretodor! The `create-react-class` module is actually the old API that used to be included in React as `React.createClass`. It was moved into its own package so people who didn't want to migrate to ES6 classes could still use newer versions of React.

If you prefer the API you get with `create-react-class`, feel free to continue using it! Since it wouldn't make sense to reintegrate an API that was explicitly removed from React, I'm going to close this out. Let me know if you have any questions about this.

Thanks!
