### ISSUE TITLE
Warning for using development build in production

### ISSUE THREAD

**Issue by joker-777** [facebook/react#10768]
Hi, we are seeing this error

![screenshot_20170919_161441](https://user-images.githubusercontent.com/378859/30689628-d46232a2-9ec1-11e7-8fbf-5b81c3b3bcc0.jpeg)

but the React Developer Tools is saying this

![reach_notification](https://user-images.githubusercontent.com/378859/30689654-ebe05864-9ec1-11e7-8000-9fe165cc6f9a.jpg)

We use `NODE_ENV=production` to build our js file (using browserify) and I also tried out `envify` but no luck. The red warning doesn't disappear.

**Comment by gaearon** [comment]
Can you point me to a website reproducing this?

**Comment by joker-777** [comment]
@gaearon Thanks for the quick reply. Here is an example

https://www.kenhub.com/en/atlas/acromion

**Comment by joker-777** [comment]
I had a look at `https://fb.me/react-minification` and saw your suggestion using certain transformations for browserify

```
browserify ./index.js \
  -g [ envify --NODE_ENV production ] \
  -g uglifyify \
  -p bundle-collapser/plugin \
  | uglifyjs --compress --mangle > ./bundle.js
```
our config looked like this (using also `NODE_ENV=production` when running the gulp command)
```coffee
  bundler = browserify(config)
  bundler.transform('browserify-shim')
  bundler.transform('coffeeify', {sourceMap: false})
```
I changed the config like this
```
  bundler = browserify(config)
  bundler.transform(envify(), {global: true})
  bundler.transform('browserify-shim')
  bundler.transform('coffeeify', {sourceMap: false})
  bundler.plugin('bundle-collapser/plugin')
```
I tried to use `bundler.transform('uglifyify', {global: true})` but got an error. I guess it is related to our use of `coffeefy`. Could this be the reason? Do I need to use `uglifyify`?

**Comment by ngyikp** [comment]
Following the troubleshooting steps at https://github.com/facebook/react-devtools/issues/692, the warning in the console is correct, React is not being minified properly `process.env.NODE_ENV` isn't turned into a string:

<img width="490" alt="screen shot 2017-09-24 at 11 38 51 am" src="https://user-images.githubusercontent.com/6135313/30779212-f595b3ba-a11c-11e7-9ff0-d936d2884136.png">

The reason why the browser icon shows the 'production' icon is because another third-party library you are using (Help Scout) also uses React. If you block https://djtflbt20bdde.cloudfront.net or don't load their library, then the extension correctly detects the 'development build'.

The duplicate React issue is discussed/solved at https://github.com/facebook/react-devtools/issues/700 / https://github.com/facebook/react-devtools/pull/714

**Comment by joker-777** [comment]
OK, thanks for investigating. I think we found a solution for us finally.
