### ISSUE TITLE
Monkeypatch Math.random(), new Date() and Date.now() during render() in dev

### ISSUE THREAD

**Issue by petehunt** [facebook/react#1077]
Was talking with Adam Wolff today about rxjs and there are a ton of common bugs with these functions. You're gonna have a bad time if you use these in React `render()` methods too -- if we monkeypatched these to warn in `__DEV__` we could prevent some bugs. @jordwalke seemed to like the idea too.

**Comment by gaearon** [comment]
This has been inactive for over a year, and it doesn’t appear like there any plans to do this. With the explosion of JavaScript build tools and polyfills, we have been trying to be careful to not add surprises or touch the built-ins, and I think it has been the right call. React Native is actually running into some issues right now because of conflicting polyfills, and it’s great we’ve been able to avoid those so far by not touching the built-ins.

I’m closing this but please let me know if I’m making a mistake and we should reopen. Thanks!
