### ISSUE TITLE
Toggle Menu from external button

### ISSUE THREAD

**Issue by vineetkumar19871503** [facebook/react#10770]
I have 2 different components (not related in any manner). One has a button and second one has a menu. I want to open/close menu from other component when I click the button inside it.
Is there any way to add a class directly without setting redux state?

**Comment by ekfn** [comment]
1. It's not stack overflow;
2. No, redux is the best way;

**Comment by aweary** [comment]
> No, redux is the best way;

We don't recommend defaulting to Redux for state management. It's a great library, but React has a built-in state management API that is often sufficient. In this case, you can always move the state up the tree so that a shared parent of the button and menu passes down the open/close state.

But we try to use this issue tracker for bug reports and feature requests only. If you have a usage or support question, I recommend checking out [Where to Get Support](https://facebook.github.io/react/community/support.html). Thanks!

**Comment by bjrmatos** [comment]
> We don't recommend defaulting to Redux for state management. It's a great library, but React has a built-in state management API that is often sufficient. In this case, you can always move the state up the tree so that a shared parent of the button and menu passes down the open/close state.

@vineetkumar19871503 in case you just need a relevant doc that describes this pattern take a look at [this section of react docs](https://facebook.github.io/react/docs/lifting-state-up.html)
