### ISSUE TITLE
Can we write react component life cycle methods using arrow-function syntax? 

### ISSUE THREAD

**Issue by tcm2029** [facebook/react#10810]
Hello React community,

I'm getting myself familiar with React and I have a question that I would like to clarify about React component life cycle method.

Particularly, I see that in all documents about React, when implement React component life cycle methods, for example, with render method, we use this syntax

```
class MyComponent extends React.Component{
     render() {
     }
}
```

My question is: is there any problem or unknown side-effect if I change this method to use functional style method, as follows:

```
class MyComponent extends React.Component{
     render = () => {
     }
}
```

I hope to receive your reply soon. I would like to appreciate in advance for detailed explanation about this issue.

Thank you.

**Comment by Nimelrian** [comment]
This won't make a difference. The examples use standard class methods since class fields (which arrow member function declarations make use of) have not made it into the standard yet.

**Comment by suhaotian** [comment]
It's unnecessary.

**Comment by rohit0803** [comment]
You can't use an arrow function when a dynamic context is required. So it's better not to use arrow-function syntax also it will make debugging hard.

**Comment by Kovensky** [comment]
An important issue when using arrow function properties is that, because they are properties and not methods, they do not exist in the prototype.

This prevents the browser from reusing the same function when rendering multiple copies of the same element (each copy of the element will be running a different render function, instead of the same function with a different `this` every time), which makes optimization by the javascript engine harder to do, or at the very least delays the point where the engine would want to optimize.

Even where arrow function properties are supported (TypeScript, babel with class properties plugin), it is recommended to write everything as methods, so they exist in the prototype. If any of your methods needs to be given as an argument or as JSX element's property, the recommendation is to do `this.methodName = this.methodName.bind(this)` in the constructor, creating a local version of the shared prototype method.

**Comment by gaearon** [comment]
As noted by commenters above, you technically can do it, but it is unnecessary and may also hurt performance a little bit.

**Comment by tcm2029** [comment]
Thank you for everyone's comments :)

**Comment by yakunins** [comment]
Just run this code in console:
```
class Component1 {
     render() {
		return console.log("c1")
     }
}

class Component2 {
     render = () => console.log("c2");
}
const c1 = new Component1;
const c2 = new Component2;

console.log(c1);
console.log(c2);
```
See the difference in prototypes:
![image](https://user-images.githubusercontent.com/2505676/67331561-c3650d80-f4d2-11e9-82ed-0d760c414330.png)

**Comment by sktguha** [comment]
Hi, is there any eslint rule to flag this , and maybe even autofix this, i.e change arrow functions usage in lifecycle methods to normal ones ?
