### ISSUE TITLE
On Safari, input of `type=number` will not invoke `onChange` callback when input is non-numeric character.

### ISSUE THREAD

**Issue by biril** [facebook/react#10829]
**Do you want to request a *feature* or report a *bug*?**
It's a bug.

**What is the current behavior?**
On Safari, an `<input>` with `type=number` will not invoke the `onChange` callback when input through keyboard is a non-numeric character. I.e. it is invoked for input of '1', _not_ invoked for input 'a'.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
Please see [relevant jsfiddle](https://jsfiddle.net/84v837e9/208/).

**What is the expected behavior?**
The `onChange` callback should be invoked for any input which affects the contents of the `<input>` field.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
This is reproducible on Safari Version 10.1.1 (12603.2.4) / MacOS 10.12.5 (16F73).
React version is 15.6.1.

**Comment by nhunzaker** [comment]
Hey @biril, this is intentional. This is a trade-off we must make because number inputs are really frustrating in Chrome and Safari.

**Take a look at [this updated JSFiddle](https://jsfiddle.net/84v837e9/209/)**. Here's the gist of it:

1. Enter "1". Input changes to "1"
2. Press "a" so that the input reads "1a". Input changes to "". 
3. Press backspace to remove the "a". Input changes to "1".

**There are three change events here:**

1. Input changes to `"1"`
2. Input is invalid, reporting "", changing to ""
3. Input is valid, reporting "1"

**The reason why just typing "a" does not fire a change event:**

1. Enter "a", invalid input. Safari reports "", which is the same as an empty input.

**This fires no change event:**

1. "a" is an invalid number. Safari reports "". It looks like nothing has changed.

The struggle, as you'll see in the value included in the alert box, is that **Safari reports an empty string for invalid numbers**. We do not know if this is because the user has backspaced to clear the input, or if they've provided invalid data.

If you need fine grain control over the inputs for user data, I recommend using `<input type="text" />` with a [pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern) attribute.

---

cc @jquense and @aweary I just want to make sure I'm correct here that there's nothing we can do, and that I've provided a good alternative

**Comment by jquense** [comment]
yeah I just did a quick test to confirm. it only fires when the "value" changes, not the text written in the element. It's similar for Date inputs which only fire a change when all parts are entered and a valid date is parsable. I also confirmed that in safari if you enter `1` select it and cahgne it to `a` you do get a change event e.g `1` -> `""`

**Comment by nhunzaker** [comment]
Thanks, @jquense! I've updated the JSFiddle to include the native counterpart, which shows similar behavior.

**Comment by biril** [comment]
Thanks a lot - that makes sense. 

(The reason I was planning to go with `type=number` was to force devices to pop up a numeric keypad on focus, rather than the usual one. Which would better fit my use case. Oh well.)

**Comment by chinguyenvan** [comment]
![1111](https://user-images.githubusercontent.com/22270186/209496650-1ee0a2e7-cac1-4614-85b2-a65a52d179a2.jpg)
