### ISSUE TITLE
How Can I use the returned string in the src tag of an <img src='returnedString' /> ? 

### ISSUE THREAD

**Issue by aziz-boudi4** [facebook/react#10859]
**Do you want to request a *feature* or report a *bug*?**

**feature :**
I want to use the new feature on React v16.0.0 for returning a string, then use that string in  
`<img src="returnedString" > `

**What is the current behavior?**

Well if I render my component in a
 `<div > <MyComponent /> </div> `

 I can see the string displayed on the screen (see attached screenshot), but my goal is to use that string in `<img src="returnedString" />`

here is my code:
```    
// My component that returns strings
class MyComponent extends Component {
 render(){
 
   switch (this.props.type) {
      case 'text':
        return this.props.json.data[this.props.Key]
        break
      case 'image':
        return this.props.json.data[this.props.Key]
        break
      default:
      return null
        break
    }
  }
}

const UserComponent = (props) => {
  return (
    <div>
      {/* this displays the string on the page */}
      <MyComponent type='image' Key='avatar' desc='Abified image'  {...props} />

      {/* If I console.log this line I get <img src={[object object]} /> */}
      <img src={<MyComponent type='image' Key='avatar' desc='Abified image'  {...props} />} />
    </div>
  )
}

// Parent Component
class App extends Component {
  constructor(props){
    super(props)
    this.state = {
      json:[]
    }
  }

  // Fetching data from an api
  componentDidMount(){
    fetch("https://reqres.in/api/users/2")
      .then(response => response.json())
      .then(json => {
        this.setState({json: json })
      })
  }

  render() {
    return (
      <div>
        <UserComponent {...this.state}/>
      </div>
    );
  }
}

export default App;
```

How Can I achieve that 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

**What is the expected behavior?**

I want to use the returned string inside an `<img src="myString" />`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React v16.0.0 /
browser Chrome Version 61.0.3163.100 (Official Build) (64-bit) 

Did this work in previous versions of React? 

No because it's a new feature in React v16.0.0 

![screen shot 2017-09-26 at 7 24 51 pm](https://user-images.githubusercontent.com/7435015/30892974-75b25b32-a2f0-11e7-87fc-bb548ece8052.png)

**Comment by bradchristensen** [comment]
As I understand, this is the expected behaviour, because the DOM renderer doesn't *render* props other than `children` (recall that JSX is simply a data structure until you render it using `ReactDOM.render(...)`).

You would need to explicitly render the component using something like the following:

```jsx
import { renderToStaticMarkup } from 'react-dom/server';

<img src={renderToStaticMarkup(<MyComponent type='image' Key='avatar' desc='Abified image'  {...props} />)} />
```

Note that the only alternative to `renderToStaticMarkup` is ReactDOM's `render`, which must mount to a DOM element, and that doesn't satisfy your use case.

This is kind of acceptable for something you're only rendering server-side, but you should definitely not do this for anything that is rendered in the browser. Most obviously because you would need to bundle in `react-dom/server`, but also because `<MyComponent />` will not be re-rendered if its internal state changes (though this would not be a problem for your exact example above since it has no internal state).

**Comment by OlegLustenko** [comment]
What are you trying to achieve using react component which returning a string, instead of a plain function?

**Comment by gaearon** [comment]
Yeah, this is not a supported use case because you're not rendering a child with it. As others have noted, a plain JS function would be more appropriate than a component here.
