### ISSUE TITLE
<svg tabIndex="2"> doesn't work 

### ISSUE THREAD

**Issue by gaearon** [facebook/react#10987]
See the original report in https://github.com/facebook/react/issues/10772#issuecomment-333242375.

The problem is that SVG is case sensitive, and so naïvely setting `tabIndex` and relying on insensitivity won't work with it.

The good news is it seems like `tabindex` is the only valid [SVG attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) with this problem. We just missed it because it applies both to HTML and SVG.

I think the fix is to add it back to the whitelist.

**Comment by forWorkAtML** [comment]
simple example where tabbing works & doesn't work depending on case

https://github.com/forWorkAtML/svg-bug

Note that the console does not state the error **did you mean `tabindex` not being `tabIndex`**
Not really sure why this is but it does display in our app.

**Comment by waterizzet** [comment]
Thanks for confirming this issue, I've been struggling to identify the reason my svg component stopped working after the update.

A component made of clickable <circles> have lost both focus and blur functionality, because "tabIndex" is rendered in the camelCase style and then ignored by the browser.

I've tried adding the property "tabindex" to the <circle> tag in the jsx, but it was swallow by React and not rendered to the final component.

**Comment by gaearon** [comment]
React `16.1.0-beta` has been released. Please update `react`, `react-dom`, and `react-test-renderer` (if you use it) to this version and let us know if it solved the issue! We’d appreciate if you could test before Monday when we plan to get `16.1.0` out.

**Comment by forWorkAtML** [comment]
apologies  just seeing this message now.
Yes. The issue is resolved with the beta, rc & 16.1
