### ISSUE TITLE
[website] yarn dev throwing error on Node 7.*

### ISSUE THREAD

**Issue by fpoumian** [facebook/react#10995]
The website docs list Node.js version 7.6 or greater as a requirement, however, when I tried to run `yarn dev` using version 7.10 I got the following error, which I'm pretty sure is caused by the fact that Node.js 7.* does not support trailing commas in function parameters, but there are a couple of those in the file `gatsby-node.js`. So, maybe It'd be a good idea to change the required version of Node to 8 in the website docs (either that or remove the trailing commas in `gatsby-node.js`)
```

error UNHANDLED EXCEPTION


  Error: /home/fpoumian/WebStormProjects/react/www/gatsby-node.js:53
    );
    ^
  SyntaxError: Unexpected token )
  
  - module.js:20 require
    internal/module.js:20:19
  
  - api-runner-node.js:80 runAPI
    [www]/[gatsby]/dist/utils/api-runner-node.js:80:20
  
  - api-runner-node.js:176 
    [www]/[gatsby]/dist/utils/api-runner-node.js:176:33
  
  - map.js:27 
    [www]/[gatsby]/[async]/internal/map.js:27:9
  
  - eachOfLimit.js:64 replenish

```

Let me know which solution do you prefer and I'll gladly open a PR.

**Comment by bvaughn** [comment]
Thank you for filing this issue! 😄 

The documentation and source code for reactjs.org now lives in a different repository: https://github.com/reactjs/reactjs.org

The issue you mention was due to a mismatch between the Node versions specified by `package.json` and `.nvmrc` and was actually corrected yesterday. 😅
