### ISSUE TITLE
React.Children.onlyChild throws on text child

### ISSUE THREAD

**Issue by chenglou** [facebook/react#1104]
Text child is a string so `isValidComponent` fails. Would it make sense for it to accept a string? Frankly I'm confused by this API...

**Comment by eipark** [comment]
The error message for this is: `Invariant Violation: onlyChild must be passed a children with exactly one child.` This led me incorrectly down the path of thinking I had passed in multiple children until I dug in and realized it was because I had a string instead of a `ReactElement`. Could this error message a bit more nuanced for cases such as this?

**Comment by spicyj** [comment]
I actually already improved this message in 15.3.1: https://github.com/facebook/react/blob/v15.3.1/src/isomorphic/children/onlyChild.js#L34.

**Comment by eipark** [comment]
Cool - that's a bit more specific. As a next step, it would be nice to actually detect and message what exactly is invalid for the most common cases.
