### ISSUE TITLE
Component does not respect defaultProps when rendered through React Element

### ISSUE THREAD

**Issue by herzaso** [facebook/react#11071]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
A component does not respect the defaultProps if it was rendered through a React Element (JS Object)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template for React 16: https://jsfiddle.net/Luktwrdm/, template for React 15: https://jsfiddle.net/hmbg7e9w/).**
https://jsfiddle.net/r2msp4ts/

**What is the expected behavior?**
defaultProps should be applied.
In the provided example, there should be two identical buttons

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Tested under Chrome with versions 15.6.1 and 16. Both didn't work...

**Comment by gaearon** [comment]
This is by design.

`defaultProps` is taken into account by `React.createElement`. This is what JSX generates. However it has to enumerate all props (and merge them with default props) which means some performance hit. 

The object form is meant to be the target for an optimising compiler. Such a compiler would need to be smart enough to inline default props directly into the object literals, and bail out it it is impossible to determine the default props.

**Comment by gaearon** [comment]
Well, you can always pass the props to `createElement` to have it fill in the `defaultProps` and give you a complete element.
