### ISSUE TITLE
After server render, missing nodes are not re-created with correct className

### ISSUE THREAD

**Issue by dustinsoftware** [facebook/react#11104]
Possible regression - it looks like re-creating missing nodes is not working correctly in React 16. The nodes get re-created, but one of them will copy the className from a sibling node, instead of getting re-created with the correct className.

Here's [a pen](https://codepen.io/dustinsoftware/pen/WZdNWv) demonstrating the issue. It works just fine in React 15.

JSX:
<img width="364" alt="screen shot 2017-10-04 at 10 00 33 pm" src="https://user-images.githubusercontent.com/942358/31211626-79b7f574-a94f-11e7-824c-d4d24dc3b91b.png">

Rendered HTML:
<img width="271" alt="screen shot 2017-10-04 at 10 01 19 pm" src="https://user-images.githubusercontent.com/942358/31211639-954c558c-a94f-11e7-9cb9-84b449586c7a.png">

**Comment by gaearon** [comment]
This sounds like expected behavior in 16.

React 16 doesn't guarantee that the result will be correct if there is a mismatch. It inserts extra nodes but doesn't patch up the attributes because it would be pretty expensive and negate the performance benefits.

It is expected that you will fix mismatches in development so that the app can be fast in production. We plan to document it more prominently in the future.

You can read more in https://github.com/facebook/react/issues/10591.
