### ISSUE TITLE
Make undefined ref message better

### ISSUE THREAD

**Issue by gaearon** [facebook/react#11102]
As reported in https://blog.discordapp.com/lessons-from-migrating-a-large-codebase-to-react-16-e60e49102aa6, it could've been clearer.

**Comment by patrick-mcdougle** [comment]
I tried doing a text search for "reactFiberChild" and I can't seem to find it. Would love to make a first contribution by making warnings more clear. Can anyone point me in the right direction?

Here's the full text from the article to save others time from finding it:
> We ran into an error which took us 2 days to track down to a library, and you may find the same. The console kept telling us that reactFiberChild could not render an element because its ref was undefined. We tore our hair out puzzling through how this could happen, and eventually dug into the React code and saw where the error was being generated. React 16 doesn’t like undefined ref attributes, but null are fine. It took us a while to discover that elements created with a core external library were being set with ref: undefined. Once we forked and fixed it, everything rendered beautifully.

**Comment by HeroProtagonist** [comment]
@patrick-mcdougle I would be interested in taking a look at this issue. Wanted to make sure we are not duplicating the effort.

**Comment by gaearon** [comment]
Pretty sure you're not since @patrick-mcdougle wrote over a month ago. Go ahead please!

**Comment by patrick-mcdougle** [comment]
@HeroProtagonist @gaearon I still am willing to work on it, but I needed some guidance because I didn't see "reactFiberChild" anywhere in the codebase and I was seeking guidance on where to start looking.

**Comment by HeroProtagonist** [comment]
@patrick-mcdougle I am trying to reproduce this issue. It is possible that since the article was written it has been fixed.

**Comment by gaearon** [comment]
It's referring to `ReactChildFiber` file which is not a string but just a filename. The article author meant that there was an error in that file.

To reproduce, I would try to render something with `ref={undefined}` and check what message I would get.

**Comment by HeroProtagonist** [comment]
@gaearon I got some time to look further into this. I believe that setting `ref={undefined}` will not make the ref `undefined` because of [this](https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js#L24) check in `React.createElement`.

However, if one makes an object that matches a react element and then does not set the ref property it will cause the error `Expected ref to be a function or a string.` in 16+
I made [this](https://github.com/HeroProtagonist/undefined-ref/blob/master/src/Ref.js#L16) to summarize what I found.

I believe that this is the error that was described in the blog. I can go ahead and update the message in [`reactChildFiber`](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactChildFiber.js#L141) if that would resolve the issue.

**Comment by gaearon** [comment]
Thanks. Seems like this has since been solved but I'm further improving the message in https://github.com/facebook/react/pull/13408.
