### ISSUE TITLE
input type="number" onChange vs onInput

### ISSUE THREAD

**Issue by tkrotoff** [facebook/react#11142]
With `<input type="number">`, when entering text ("eee"), onChange is not fired, onInput is.
https://codepen.io/tkrotoff/pen/gGvvxw

Tested with React 16 + Chrome 61, Firefox 55, Safari 10.1.1 and Edge 38.14

DOM behavior (no React): https://codepen.io/tkrotoff/pen/RLQQqo

React onChange is not equivalent to DOM input event as it should.

**Comment by aweary** [comment]
Hey, @tkrotoff this is a known limitation for number inputs, see https://github.com/facebook/react/issues/6556. React will only emit a change event when the value of the input has actually changed, and when you enter an invalid number in a number input you get a value of `''` from the DOM, so `123ee` and `123eee` both have a value of `''` and a change event won't be dispatched since React cannot detect the change. Hope that helps!
