### ISSUE TITLE
React16 not compatible with x3dom

### ISSUE THREAD

**Issue by pgruenbacher** [facebook/react#11184]
** This is both bug / feature
https://www.x3dom.org/

I used to be able to use x3dom with React. It was great.

** React ^15 I was able to use the **is** property to generate custom elements and custom attributes that could be picked up by x3dom i.e. <shape is render="true"/>

Now with React16 i get many warning messages for all of the custom x3dom tag elements. Likewise it seems that certain attributes aren't getting rendered either. For instance if I do x3dom elements like so:

`<fontstyle size="0.6"/>` I'll get `<fontstyle/>` output without the size attribute.

I don't think React should have to know what x3dom tags are, nor should they be hard-coded into React. There has got to be a way to have React output custom tags without throwing warning messsages. Why not just re-introduce the **is** attribute to indicate that it's a custom tag with custom attributes?

**Comment by pgruenbacher** [comment]
![screenshot from 2017-10-10 15 30 19](https://user-images.githubusercontent.com/3332598/31406590-fb762b6a-adcf-11e7-996b-97a366cf51c1.png)
![screenshot from 2017-10-10 15 29 54](https://user-images.githubusercontent.com/3332598/31406591-fb85442e-adcf-11e7-8982-bb5ca7ca20a2.png)

Examples images of how size="0.6" is not output by React

**Comment by sebmarkbage** [comment]
There is a general recommendation from w3c not to add custom tags without a dash in them. The dash is the way to define a custom element. The idea is that otherwise there is no safe way for browsers to add new tags to the spec. In fact, some might already be broken because of x3dom.

I'd raise an issue with x3dom asking why they're not following this recommendation. (Likely because it existed before this recommendation was well known.) If they're not planning on changing, I'd like to know why they're not concerned with the same thing the w3c is and whether we can break it under the same rationale.

**Comment by pgruenbacher** [comment]
I see so <fontStyle/> so would need to be something like <x3-fontStyle customAttr="0.3"/> at which point React will not raise warnings for having camelCased attributes or for having a custom element. That seems reasonable. I wasn't clear to me when reading https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html.

**Comment by pgruenbacher** [comment]
I resolved the issue by changing all custom elements from `<customElement is customAttr="0.3"/>` to `<custoElement is="x3d" customAttr="0.3"/>`. I had accidentally thought **is** attribute was deprecated. No need for the dash convention.

**Comment by coderextreme** [comment]
My understanding is that I need to go through all my x3dom code and add is=“x3d”?  This is hopeful!
