### ISSUE TITLE
Is there a way to input before rendering checking strategy in ReactDOM?

### ISSUE THREAD

**Issue by VictorQueiroz** [facebook/react#11218]
I'm not sure if that's the appropriate way to ask this but I'd like to have your opinion. I notice that I have the use of `PureComponent` very often in code, but I'm wondering if there is a way in which you build all pure function components and then apply the logic of shallow comparison before rendering while rendering component using ReactDOM.

Is there a reason not to have something like this? What do you guys think?

**Comment by gaearon** [comment]
I don’t understand what is being asked, sorry.

If you benchmarked interactions in your app and you have evidence that `PureComponent` makes it faster, then use it on those places. Otherwise, don’t.

I’m sorry if this isn’t helpful, but I’m not sure what else you are looking for. Maybe if you can clarify with an example I could give a better answer.
