### ISSUE TITLE
React Test Renderer's Peer dependency keeps getting bumped

### ISSUE THREAD

**Issue by bdwain** [facebook/react#11278]
I noticed that react-test-renderer's peer dependency for React gets bumped with every version update (or at least that's what happens in version 15.  v16 is still 16.0.0). Is this required? Could the peer dependency for version 16 not stay at ^16.0.0 even after the versions of each package get bumped to say 16.1?

I ask because this makes it hard for libraries to pull in react-test-renderer so that their end users (who do not use it directly) don't have to pull in a package they never use directly. 

The specific example I have in mind is enzyme. For version 15, it has a peer dependency on `react@^15.5.0`, and a dependency on `react-test-renderer@^15.5.0`. if I have react 15.5 installed and enzyme tries to install the latest react-test-renderer, then it will pull in 15.6.2, which requires `react@^15.6.2`, which 15.5 does not satisfy.

Until recently, they made the test renderer a peer dependency, which was very annoying as a user of the library because you should not have to manually install a package that you don't use directly. We changed that to be a regular dependency, but are now noticing that the peer dependency the test-renderer has on react gets bumped every version change, which causes the above problem.

Is it not possible to leave the peer dependency within the major version? At least for v16 going forward? Or is there another way a library can pull in the test renderer without forcing the user to do it?

**Comment by gaearon** [comment]
cc @bvaughn 

I would say I'd be fine with leaving it at `^16.0.0` until we *actually* do something that would require a bump. There are just two modules (AFAIK) that we access around public API now so maybe it’s not that hard to keep better compatibility from now on.

**Comment by bvaughn** [comment]
Thanks for bringing this to our attention, @bdwain.

I agree with @gaearon that it's _probably_ okay to leave the peer dependency at `^16.0.0` unless we have made changes that require bumping it.

I worry this may cause a problem in the future though, since our tests and our release process don't step through past versions of peer deps to verify they still work (eg we test the latest test renderer with the latest react). Doing this would require a release manager to know/remember to actively consider peer dep constraints and their implications, which can be a bit hard to do if you don't have context on all of the changes that have gone into a certain release.

**Comment by bdwain** [comment]
I see. Does react test renderer rely on private apis from React? Because if it's only public api's then a non-major bump should be fine right?

**Comment by gaearon** [comment]
All renderers require on a few private APIs from the `react` package but their scope is very limited. If we add Flow types for those I think we can try to safely keep them compatible.

**Comment by bdwain** [comment]
Sweet! Thanks!
