### ISSUE TITLE
Remove warnings for Unsupported Style Properties

### ISSUE THREAD

**Issue by rgbkrk** [facebook/react#11315]
Now that the safelist and blocklist are basically no more, React 16 seemingly allows you to write:

```jsx
ReactDOM.render(
  <h1
    style={{
      color: 'DeepPink',
      'font-weight': 900,
      'background-color': 'black',
      'padding-top': '20px',
      height: '100%',
      width: '100%'
    }}>
    Pink on Black!
  </h1>,
  document.getElementById('root'),
);

```

which renders the style properly, with warnings:

![screen shot 2017-10-21 at 11 58 53 am](https://user-images.githubusercontent.com/836375/31855029-43ebb93e-b657-11e7-9cc3-4b9295172727.png)

Perhaps we could remove the warnings? When writing pure React I'll use the `camelCased` names -- the reason I'm hoping to remove the warnings is to be a bit more lenient with [a little Python wrapper that uses React on Jupyter/nteract frontends](https://github.com/nteract/vdom).

**Comment by aweary** [comment]
Hey @rgbkrk, even though the blacklist behavior is more lenient React still warns when using the non-canonical names for attributes it recognizes. For example, you _can_ use `class` instead of `className`, but you'll still get a warning because `className` is the canonical name of the attribute.

What you're seeing here is consistent with that; the camel-cased names are still canonical names for the style properties, so a warning is issued. Just like attribute names, you can use both property names but it's still recommended to use the camel-cased versions. It's also worth noting that this would have worked [in React 15 as well](https://jsfiddle.net/y0mtzt0g/) so attributes are just now consistent with style properties.

Also, these warnings should be DEV-only, so they shouldn't affect behavior in production.

**Comment by gaearon** [comment]
I agree with @aweary’s answer. This behavior for style properties is indeed not new in 16.

We are trying to encourage consistency so that third party components don’t feel obligated to support all kinds of patterns at the same time. This is better for the ecosystem because people don’t have to argue about conventions. We feel that `camelCase` works best because at some point you’re doing to wrap logic in components, or read props before passing them down, or add your own similarly named props, and `camelCase` is the most natural convention for doing this in JS.

You can always force-silence the warnings by overriding `console.error()`. We might provide some kind of APIs to opt out of warnings in the future too. But we won’t be disabling this particular one to enforce more consistency. If you provide your own wrapper around some non-React code, you can always convert things to `camelCase` as part of that wrapper.

**Comment by rgbkrk** [comment]
This is perfect, thanks for the response. I'll guide people using the python bindings towards using the proper `camelCase` and let the `kabob-case` accidentally work by passing it through.

**Comment by gaearon** [comment]
Is there a specific reason you don't want to make a helper for them to camelCase things?

**Comment by rgbkrk** [comment]
I'm fine with making a helper, I was curious if it was ok to just leave it and let them pass it through. In our [mini-spec we state they need to use `camelCase`](https://github.com/nteract/vdom/blob/master/docs/spec.md#coding-style-and-syntax) and we link back to the React docs and blog.

**Comment by gaearon** [comment]
This is a misunderstanding. Just because we pass those attributes through doesn't mean they are guaranteed work correctly. When you use the wrong casing, React will just pass it through and not apply any special behavior it might have for an attribute (or property). So the behavior can be visibly different with less cross-browser normalization.
