### ISSUE TITLE
JSX alternative for namespaced tags/XML

### ISSUE THREAD

**Issue by DanielRuf** [facebook/react#11321]
We are currently working with a template engine which uses namespaced XML tags but JSX does not support XML and namespaced tags.

Is there an actively maintained alternative or can someone point me to the right place for my question?

**Comment by aweary** [comment]
Hey @DanielRuf, the JSX specification technically does allow for namespaced tags. You can see there is a `JSXNamespacedName` identifier in the [JSX specification](https://github.com/facebook/jsx). The reason it doesn't work is because [the Babel plugin throws for `JSXNamespacedName`](https://github.com/babel/babel/blob/830c527bb7873b29f671a3568b21b4a6af98ceda/packages/babel-helper-builder-react-jsx/src/index.js#L16-L20) since it's not supported in React. 

I would recommend referring to the [JSX repo issue tracker](https://github.com/facebook/jsx/issues) and reading through existing issues on this topic such as [Is JSXNamespacedName needed?](https://github.com/facebook/jsx/issues/13).

In the worst case, you could fork `babel-plugin-transform-react-jsx` and implement a version that allows for namespaced tags, which should be easy since the AST node is already there.

I hope that helps!

**Comment by aweary** [comment]
[Here's an example using ASTExplorer](https://astexplorer.net/#/gist/233d07f305ee5d5de3759279a9e2c372/7db668d6702ca1a7c9ccfbfd7748145e1a754246) that shows that namespaced tags _are_ parsed by Babel.

**Comment by DanielRuf** [comment]
Hm, so there is no usable solution so far? Careless seems unmaintained and I did not find other solutions.

**Comment by paulbjensen** [comment]
I too have stumbled into this issue. We've got an internal project to generate Powerpoint decks with code. Powerpoint files (pptx) are just zip files containing some folders, XML files and any embedded assets. We wanted to use React as a way to generate the XML files, but we can't as there isn't support for XML.

**Comment by DanielRuf** [comment]
@paulbjensen the next Babel version (7) should support namespaced tags. See https://github.com/babel/babel/issues/6535
