### ISSUE TITLE
'npm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Crischr** [facebook/react#11358]
**Do you want to request a *feature* or report a *bug*?**
It's not a bug, but a installation issue because it's my first time to use React.

**What is the current behavior?**
When I create an app refered to the guide, 'npm' is not recognized as an internal or external. I added node to Enviornment Variables (user variables and system variables)
![image](https://user-images.githubusercontent.com/12505696/31995675-fee5279e-b9b7-11e7-9244-1e428c435f3e.png)
 OS: Win 7 64bit
node version:  6.11.2
npm version: 5.5.1

**Comment by gaearon** [comment]
Can you run "npm" in your terminal?

**Comment by gaearon** [comment]
I'll close because it's definitely an issue with your setup, and not with CRA itself. If it can't run `npm` in your shell then there's a problem with how PATH is configured on your system. We are not Node experts and can't help you with this, but you should be able to use Node and npm support forums to resolve this.
