### ISSUE TITLE
What should I do or follow If I want to go with microservice architecture for building a large scale website where I am planning to use Laravel, react js and MySQL initially? Beside this, which type of rendering will be best for me (CSR or SSR) and how to implement all the things prooperly?

### ISSUE THREAD

**Issue by Sazid-Kazi** [facebook/react#11399]

**Comment by gaearon** [comment]
This is a very broad question and it’s not clear how to answer this. (And we are not the best people to do so.)

You can’t directly use React from Laravel on the server because you can’t run JS from PHP code. There are some projects attempting to mitigate that but I can’t speak to their stability. You could also have two server layers (PHP and Node) but this seems more complex. I googled "laravel React server rendering" and found this thread: https://www.reddit.com/r/laravel/comments/4d0vef/how_to_do_server_side_rendering_with_laravel/. I hope you find it useful.

Other than that, I encourage you to turn to community resources with this question: https://reactjs.org/community/support.html
