### ISSUE TITLE
class styles inside javasript styles

### ISSUE THREAD

**Issue by unutoiul** [facebook/react#11425]
Hi,

If I have 
```

const styles = (theme) => {
    return(
        {
            root: {
                borderRadius: theme.spacing.unit,
                boxShadow: theme.shadows[1],
                padding:theme.spacing.unit*3
            }
        }
    )
};
```

how I can insert a style inside another class style like:

```
const styles = (theme) => {
    return(
        {
            root: {
                borderRadius: theme.spacing.unit,
                boxShadow: theme.shadows[1],
                padding:theme.spacing.unit*3,
                
                section:{
                    textAlign:'center'
                }
            }
        }
    )
};
```

**Comment by jquense** [comment]
Hey there, this question doesn't seem like it's React specific, since react has no builtin system for doing inline styles aside from what is provided by html. In otherwords you can use the `style` prop to add an inline style to the html element or `className` to add a css class. In the style cause there is no nesting or processing of the style, its assigned directly to the element you add the prop to. Perhaps you are using a library like jss or glamor? if so you might want to check out their support avenues, thanks!
