### ISSUE TITLE
Need to implement n level expandable listview in react native

### ISSUE THREAD

**Issue by prashantvv** [facebook/react#11459]
I've a basic query in react native. I've a side menu with n level expandable options (categories->subcategories->...) & I've to make it in react native. I've already research a lot but I'm unable to find any significant solution for this thing. Any help will be appreciated as I am new to react native and only have basic knowledge in it. May be, by creating dynamic components it can be done but if already implemented than it will help me a lot as it is something that is very frequently needed in development.

**Comment by clemmy** [comment]
Thanks for posting @prashantvv. There are a lot of awesome resources you can find on React Native you can find in the Awesome React Native [repo](https://github.com/jondot/awesome-react-native), including tutorials and components that may suit your need. If you can't find anything there, feel free to post a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/react-native).

I'm going to close this issue for now since Github Issues is for reporting issues with React.

**Comment by prashantvv** [comment]
Thanks, the stackoverflow reference is below for future ref:
https://stackoverflow.com/questions/47110269/need-to-implement-n-level-expandable-listview-in-react-native
