### ISSUE TITLE
Props set through default parameter not added to component props property

### ISSUE THREAD

**Issue by riwu** [facebook/react#11498]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
https://codesandbox.io/s/y23613p8jz
`Example` is able to render `b` with default value of `a`, but its `props` property does not contain `b` if not explicitly set.

Is this intended?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
V16.0.0, Chrome

**Comment by AnderssonChristian** [comment]
I don't work for facebook, but I'll go ahead and answer this for you since I know the answer.

Yes, this is very much intended. I think you are confusing `b` with `props.b` and how the destructuring assignment works.

Your `Example` component is rendering your local variables `a`and `b`, not `props.a` and `props.b`. Since you are destructuring your props you get new variables!

From the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment):

> The destructuring assignment syntax is a JavaScript expression that makes it possible to unpack values from arrays, or properties from objects, **into distinct variables**.

**Comment by gaearon** [comment]
Right. Compiled, your code looks like:

```js
function Example(props) {
  var a = props.a;
  var b = props.b;
  if (typeof b === 'undefined') {
    b = a;
  }
  return <div>{a}{b}</div>;
}
```

So `props` don't have `b` but a local `b` variable is filled with the value of `a`. It is not possible for React to know that your component is written this way, so it can’t possibly fill in the props when you create the `<Example />` element.
