### ISSUE TITLE
The radio box and check box are disabled and checked ，the DOM structure lacks checked attributes

### ISSUE THREAD

**Issue by gedy** [facebook/react#11642]
**report a *bug***

**The radio box and check box are disabled and checked ，the DOM structure lacks checked attributes**

jsx：
&lt;input type='radio' checked disabled /&gt;

The browser structure after rendering：
&lt;input type="radio" disabled="" value="on" /&gt;

Our css is:
input[checked] { color: blue }

Result:
“checked” is missing，CSS failure

**Comment by jquense** [comment]
Yes changing props on react elements doesn't change the html output of those elements. React, like most frameworks that manipulate the DOM changes the DOM _property_ not the attribute, this means your css attribute selector won't work, since it's not changing. Luckily tho you can change your css to use the `:checked` pseudo selector instead
