### ISSUE TITLE
Usage of React JS

### ISSUE THREAD

**Issue by jt4000** [facebook/react#11712]
Hello,

*I'm new in react js and I got some questions.

1. Is react JS only fitable for static webpage only or is also fitable for dynamic webpage without using the F5 button?

2. Is it commen to combine react JS with another library for instance jQuery?

3. What context is react JS is recommended use? YOu also have different tools for instance jQuery, Angular JS, Bootstrap etc.

Thank you!

**Comment by gaearon** [comment]
>Is react JS only fitable for static webpage only or is also fitable for dynamic webpage without using the F5 button?

React is primarily meant for dynamic apps, although there are solutions like [Gatsby](https://www.gatsbyjs.org/) that make it a good way to create static apps too.

>Is it commen to combine react JS with another library for instance jQuery?

It's common to use React with other libraries. However since it takes care of updating the DOM, jQuery typically becomes less useful in React projects. Here's a guide about integration with other libraries: https://reactjs.org/docs/integrating-with-other-libraries.html.

>What context is react JS is recommended use? YOu also have different tools for instance jQuery, Angular JS, Bootstrap etc.

I don't understand this question.

I hope this helps! Note this is a bugtracker, and there are better places to ask questions: https://reactjs.org/community/support.html
