### ISSUE TITLE
"React.createElement: type is invalid" warning in IE11 when using React.Fragment

### ISSUE THREAD

**Issue by XaveScor** [facebook/react#11759]
https://codesandbox.io/embed/j30o67kpxy
React shows warning in console if I use React.Fragment
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

**Comment by gaearon** [comment]
Yeah, this is a false positive warning. It only appears if you use a `Symbol` polyfill.

I think it happens because we validate types here:

https://github.com/facebook/react/blob/8ce53671eddc8e96a51d87c9b1ad8cd0532ff9d5/packages/react/src/ReactElementValidator.js#L273-L277

`React.Fragment` is a symbol. However, if `Symbol` is polyfilled, then its `typeof` won't be `'symbol'`—it will be just `'object'`. So this condition won't be true.

To get around this, I think we should compare `type` directly to `React.Fragment` before concluding it's invalid.

**Comment by AyWa** [comment]
I would like to work on it, if it is possible :)

**Comment by gaearon** [comment]
Sure, it's yours.

**Comment by gaearon** [comment]
@AyWa We didn't get a PR, so the submitter has fixed the issue.

**Comment by AyWa** [comment]
@gaearon Yeah I saw yesterday that the PR was already made. Sadly I planed to work on it this week. 
Anyway I hope I can find a `good first issue` soon ;)

**Comment by dereklieu** [comment]
Glad this is fixed. Any way this can make it into a release soon?

**Comment by gaearon** [comment]
We'll likely cut a release in a week or so.

**Comment by gaearon** [comment]
In the meantime if this is blocking you, you can `yarn build -- dom` from master and grab the builds from `build/dist`.

**Comment by XaveScor** [comment]
@dereklieu You can use https://www.npmjs.com/package/@xavescor/react package while new version is not released.

**Comment by danwad** [comment]
@gaearon Any update on when we are expecting this fix to land on npm?

**Comment by XaveScor** [comment]
@danwad C'mon build own react package until 16.3 release. It's several lines in your webpack config.

**Comment by gaearon** [comment]
We plan a release within a week or so.
