### ISSUE TITLE
Testing React 16.2.0

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/react#11758]
Hi, I'm using Jest and I'm trying to write a test for JSXFragments

is there something new I need in order for JSXFragments to be testable?

I'm currently getting this issue `You gave us a visitor for the node type JSXFragment but it's not a valid type` this error seems to be coming from babel

**Comment by gaearon** [comment]
As mentioned in https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#support-for-fragment-syntax, different projects will support the syntax as the time goes. At the very least you'll want to wait for Babel 7 to come out of beta (or use the Jest version which supports it—I think the latest beta does).

I'll close since this question is not about React. Please ask individual projects for the JSX fragment support status.
