### ISSUE TITLE
how  to make state  Independent

### ISSUE THREAD

**Issue by zhiqiang21** [facebook/react#11755]
i have a component ,
```javascript
import React, {Component} from 'react';

class InputTest extends Component {
    constructor(props) {
        super(props);

        this.state = {
            fillok: true
        };
    }

    handleChangeFn(e){
        this.props.OnChangeFn(this.state.fillok);
    }

    render() {
        return (
            <input
                onChange={this.props.OnChangeFn} />
        );
    }
}

export default InputTest;

```

i use it in other component  like this

```javascript
import React, {Component} from 'react';
import InputTest from './bbb';

class componentName extends Component {
    constructor(props) {
        super(props);
    }

    handleTestState(value) {
        this.setState({
            fillok: value
        });
    }

    render() {
        return (
            <div>
                <InputTest
                    OnChangeFn={this.handleTestState.bind(this)}
                    {...this.state} />
                <InputTest {...this.state} />
            </div>
        );
    }
}

export default componentName;

```

i use `InputTest` in `componentName`  twice . how can i make every `InputTest`  state is Independent

**Comment by gaearon** [comment]
We use the bug tracker for bugs, not support questions.
Please use the appropriate support resources: https://reactjs.org/community/support.html

This documentation page might be helpful:
https://reactjs.org/docs/lifting-state-up.html

I recommend fully going through each example there.

----

Your code doesn't look right to me. A component should either *control its own state* or *let the parent component manage the state (and receive props)*.

You're trying to do both for the same slice of state which is why it behaves confusingly. You're also not passing down the `value` to inputs at all.

**Comment by zhiqiang21** [comment]
thanks!
