### ISSUE TITLE
Access React Object from within page JS?

### ISSUE THREAD

**Issue by caltv** [facebook/react#11777]
I have a ReactVr object which I am rendering with the code below. After React is initialised I am periodically receiving server updates which I want to pass into React as props, how can I do this? Can props in the React object be set from my "normal" JS?

```js
ReactVR.init(
    './build/index.bundle.js',
    document.body,
    // third argument is a map of initialization options
    {
      initialProps: {
        source: 'world.json',
         userType: "typ1"
        },
      cursorVisibility: 'visible'
    }
  );
```

 Server updates are coming via a Websockets connection, but from within React the messages are not being received, only in the "normal" JS.

In "normal" JS this returns data from the server, if I use the same within React the connection gets opened but the message is never received. However messages can be sent from within React.

```js
socket.addEventListener('message', function (event) {
        console.log('Message from server ', event.data);
  });
````

**Comment by gaearon** [comment]
Please use triple backticks for formatting blocks of code (see my edit to your message).

It's not clear to me what you're asking. React doesn't have anything to do with sockets so there's no way React can prevent your messages from getting received.

It's not clear what `ReactVr.init` is. It's definitely not an API provided by React itself. So I suggest you to ask its maintainers this question. It's not clear to me if this is related to [React VR](https://facebook.github.io/react-vr/) but I don't see this API there either.

Normally, in React, to render something you call `ReactDOM.render`:

```js
ReactDOM.render(<Something someProp={10}, container);
```

then, to update it from the top level, you can call it again:

```js
ReactDOM.render(<Something someProp={20}, container);
```

Or you could make `Something` a stateful component that calls `setState()` when it updates.

I hope this helps! I'll close because this doesn't look like a React issue to me.
