### ISSUE TITLE
smarter autoFocus

### ISSUE THREAD

**Issue by steida** [facebook/react#11773]
I believe autoFocus should be improved for the better DX. Browser-native autoFocus is nice and all but does not work when a component is updated. Sure, that's fine. But it's pretty common to need focus after a component has been updated. Yep, declaratively. How? Immutable data ftw. At least, it works for me.

I use this wrapper component https://github.com/este/este/blob/master/components/AutoFocus.js

Check componentDidUpdate method. I hope it makes sense.

**Comment by gaearon** [comment]
If it works for you then sounds like you’ve already solved it in userland. Not sure what React could do better but given the focus on the bundle size I don’t see us adding more utilities to ReactDOM.

If you have an API proposal please file it here: https://github.com/reactjs/rfcs. Then we can discuss it in detail.

Otherwise it’s not very actionable so I’m closing.
