### ISSUE TITLE
Component unmounts directly after mount

### ISSUE THREAD

**Issue by MMeent** [facebook/react#11781]
Some of my wrapper components get into the state 'mounted=false' directly after mounting. The componentWillUnmount doesn't fire and the components are still mounted into the DOM, but state changes fired in that component's context (e.g. in onClick listeners) result in errors and no unmounting. I cannot reproduce this issue on jsfiddle, possibly due to differences in environment. I currently don't have much time to explain, but here are two gists of the components which together break.

gist of breaking component: https://gist.github.com/MMeent/68f8c06d905969b80552412d38baddbf  
usage: https://gist.github.com/MMeent/d97d3856240d889abb84027b14eac652

One of the issues I've found is that literally directly after mounting (`window.setTimeout(() => console.log(this.updater.isMounted()), 1)` prints false)

Environment:

FF 58 (beta)
React 16.2.0
Babel 6.something, plugins:
 - env (FF >54, chrome last 2 versions, safari last 2 versions)
 - stage-0-without-async,
 - react

using react-hot-loader, but this happens after page reload as well.

**Comment by MMeent** [comment]
updated description to reflect some findings + added environment

**Comment by gaearon** [comment]
Can you create a standalone example in jsbin or jsfiddle please?

**Comment by jmrog** [comment]
I seem to be encountering something like this issue (I'm not _entirely_ sure that they're exactly the same issue, though, or whether they might just have the same root cause, etc.). Unfortunately, it is _very_ hard to reproduce, and I haven't yet got any very good idea about the cause (though I have _some_ weak suspicion that it is related to things that are Fiber-specific, such as a component's having (at most) two fibers associated with it).

First, I had a component on which `componentWillUnmount` was seemingly being called immediately after the component mounted, as the OP describes. Interestingly, this component had methods that were being bound in the constructor to instances of the component class (e.g., `this.someMethod = this.someMethod.bind(this)`), but when I changed that behavior (by using a decorator that binds the methods to the instances on their first access, rather than in the constructor), that particular issue went away.

At that point, however, other issues cropped up. In one example, I had a component that appeared to be mounted, but that printed warnings to the console to the effect that `this.setState` was being called on an _unmounted_ component whenever I clicked on it (there is no other instance of this component created anywhere else by me in the application, so I don't know yet which component React thinks I am interacting with when I click on the button on the component on the screen, but it definitely thinks I'm interacting with an unmounted one -- which leads to my suspicion about this being related in some way to the two fibers associated with a component). I did some brief investigating and did discover that the instance returned by the component's constructor (when the component is created by React's `instantiate` method in `createClassProxy.js`) is different from the instance that is being referenced by React in the component's click handler when I click on its button. That is, the `instance` that React creates when calling the component's constructor is not the same entity referenced by `this` inside of the component's click handler method, although `this` in the latter method is still pointing to some (different) instance of the component class that was created somehow, internally, by React (again, suspecting some Fiber stuff here, but I'm mostly ignorant about all the details). 

I'll keep looking into this and seeing whether I can produce more helpful information, as time allows me to do so. Thanks!

**Comment by jmrog** [comment]
As a quick way of trying to confirm that something with React 16 is going on in my case, I downgraded to React 15 and rebuilt my application. The issue persists, so I think my comment is likely a distraction from the current issue. Apologies for that. (I now suspect my issue may be related to the interaction of some other parts of my stack -- possibly react-redux and react-router or something else; still investigating).

**Comment by MMeent** [comment]
Your behaviour seems very much like what I'm experiencing. My description may not be perfect, but I too am experiencing that an `onClick={() => setState(() => ({}))}` reports the component being unmounted. Next week I'll probably have some time to put up a minimal breaking project.

**Comment by jmrog** [comment]
@MMeent I agree that the issues do sound similar. In my case, I've also discovered that the issue only seems to happen in development builds (all works in production), so my best guess is that my problem is actually related to something I'm using only in development (possibly react-hot-loader). My situation is complicated further still by the fact that my own case involves an Electron application bundled with webpack and using some highly specific build configuration. So, I doubt my problem is directly related to React in any helpful way. I'll likely bow out of this discussion here so that I don't pollute the thread, but good luck!

**Comment by gaearon** [comment]
`react-hot-loader` is not an officially supported or endorsed project. If you're using it, you're taking on experimental tech and everything that comes with that.

**Comment by frankwallis** [comment]
Just to add to this - I had the same issue and removing react-hot-loader resolved it. In addition the issue only happened when outputting the react components as ES6 classes, downcompiling classes to ES5 functions also resolved the issue.

**Comment by gaearon** [comment]
Please file these issues against `react-hot-loader`. Its maintainers won't know about them if you don't let them know.

**Comment by Jeowulf** [comment]
Though the cause of this issue is clearly stated here I will mention that when this issue was bothering me during development I found a workaround for dev- by wrapping the container in a HOC the faulty mounted === false problem disappeared and no longer interrupted my workflow
