### ISSUE TITLE
Lifecycle method to build initial state for classes

### ISSUE THREAD

**Issue by dryganets** [facebook/react#11847]
**Feature request**
We need to have a way to build the initial state of ReactComponent in case of usage of classes.

**What is the current behavior?**
Warning in case this.state modified in willComponentMount.

Access to partially constructed object in case of somewhat complex state building logic in the constructor.

For example, if we have a hierarchy of classes with the _buildState method called in the constructor to generate an initial state.
Derived class overrides the _buildState method to have a richer state. In result, part of the object related to the derived class won't be constructed yet and can't be accessed in the _buildState.

The buildState approach is currently used in ReSub framework:
https://github.com/Microsoft/ReSub

**What is the expected behavior?**
Rather no warning in case of this.state modification or new Lifecycle method which is called right after constructor call which returns the state.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16+ is affected.

**Comment by gaearon** [comment]
If you need to set the state, the supported way to do this is to assign `this.state` in constructor:

```js
constructor(props) {
  super(props);
  this.state = /* ... */
}
```

As mentioned in our documentation we [don't](https://reactjs.org/docs/composition-vs-inheritance.html) encourage using inheritance in React components precisely because of these annoying cascade issues when things depend on each other in weird ways.

However, it is not clear to me what you're asking, and it will take me a lot of time to dig through this library and how it uses React. Perhaps you can rephrase your question in a way that doesn't involve third party libraries? If you showed a few complete isolated components and the problem you encounter with them, that would be helpful.

**Comment by deregtd** [comment]
(one of the ReSub creators here)

We have an automated subscription system that makes developers not need to understand multiple state changes, manual subscriptions, componentWillReceiveProps, etc.  You just have a single _buildState function that builds initial state and any updated state. Think of it as react-style render() function for building your state.  As such, we need to build an initial this.state.  However, if you do it in the constructor for the component (this.state = this._buildState()), then all private member variables of your component aren't initialized (since they won't be initialized until after the super() call comes through), so _buildState causes a bunch of unexpected bugs for people.  As such, for years now we've done this.state = this._buildState() inside of componentWillMount, which has worked great.  Recently, this is now an error/warning in React, which is a huge problem for us, and we're going to end up having to fork react to work around the warning unless something goes into master that allows us to keep using this pattern.

**Comment by deregtd** [comment]
To be more clear, components use a ComponentBase class that they inherit from, which handles all this intermediate buildState handling.  So the component has to call super() in its constructor, even when it has private variables it needs to initialize.

**Comment by gaearon** [comment]
Can you give me a tiny example of inheriting and base classes? Even maybe a grossly simplified version of `ComponentBase`. I'm still struggling to understand the problem because we don't really use inheritance chains in React. It's also not clear if you're talking purely from a TS perspective, or if the problem exists in React as well.

**Comment by gaearon** [comment]
From React's perspective, `this.state` is like a C# `readonly` field: assignable in constructor, but not anywhere else. Of course we can't enforce it in JS but that's the design intention. I hope you can consider it reasonable. If React was written in C#, and you built ReSub on top of that, how would you design its `buildState` API?

**Comment by dryganets** [comment]
Well, simple lifecycle method to build initial state would enable classes usage.

I think the React will only benefit from this.

**Comment by deregtd** [comment]
The ComponentBase itself is fairly simple:
https://github.com/Microsoft/ReSub/blob/master/src/ComponentBase.ts

Fundamentally, it has a pretty empty constructor, and then in componentWillMount, it just has this.state = this._buildState().

The problem is that you can actually change state (and props for that matter) down the line.  So treating it as readonly in the constructor is awkward.  Is there any reason that you need this.state to be immutable before componentWillMount runs?  It feels like after that I very much understand, but before mounting starts, I don't really get it.

This is a nuance of any inheritance-based language, since the idea is that the super class doesn't rely on any state of the subclass.  Typescript happens to give you the nice sugar of any variables you define in your class definition to stuff at the top of the constructor (but after super()), but that still means that anything that happens in the superclass's constructor doesn't apply to your subclass.

When I've solved this in the past, I've always had to do two lines:
auto x = new SomeClass();
x.initState();

There's no workaround, since you always need the complete constructor hierarchy to run, and THEN you can call the state-building function.  React nicely gives you one of those already, componentWillMount, so the pattern mapped over perfectly for our usage.

The problem we're seeing is that if you call this.setState(this._buildState()) in componentWillMount, it sometimes appears to be queuing the setState until later (by design, I'm sure).  As such we end up with multiple lifecycle resolutions.

**Comment by deregtd** [comment]
Example code that's an issue:
```ts
interface MyState {
  someVar: boolean;
}
class MyComponent extends ComponentBase<{}, MyState> {
  private _doneSomethingYet = true;
  protected _buildState(props: {}): Partial<MyState> {
    return { someVar: this._doneSomethingYet };
  }
}
```

In this example, if you switch to putting "this.state = this._buildState()" in the constructor, state will be set to: { someVar: undefined }.  This is obviously a stupid and contrived version, but we had dozens of bugs based around issues like this until we moved the initial _buildState call from the constructor into the componentWillMount function long ago.

**Comment by dryganets** [comment]
@rigdern, pointed me to the existing lifecycle method getInitialState. Though for some reason it doesn't work for typescript/es classes (it is not called and there is a warning to use it with createClass only).

I think It would be ideal if this method will be called to set this.state after class is correctly instantiated. You could remove the recommendation to don't use classes in this case from the doc ;)

You could warn the developer in case he has both state set in the constructor and the method which return not null/undefined value.

What do you think @gaearon?

**Comment by gaearon** [comment]
>The problem is that you can actually change state (and props for that matter) down the line. So treating it as readonly in the constructor is awkward.

React provides a method called `setState()` for changing it down the line. Mutating the object was not intentionally supported.

**Comment by gaearon** [comment]
>it sometimes appears to be queuing the setState until later (by design, I'm sure).

Not quite sure what you mean. `componentWillMount` has some other issues and we might start pointing people to use other methods in the future, but for now calling `setState` in it should be equivalent to setting state in the constructor. Can you provide an example where it behaves differently?

**Comment by dryganets** [comment]
It doesn't work for us that well because we have plenty of places in our codebase where we need that initial state in componentWillMount.

If we use setState instead of assigning it directly this.state is not defined in the componentWillMount of derived classes.

It is possible to fix it by assigning to some nextState class field, but it is a quite confusing pattern.

**Comment by gaearon** [comment]
>Is there any reason that you need this.state to be immutable before componentWillMount runs? It feels like after that I very much understand, but before mounting starts, I don't really get it.

We're working on enabling asynchronous rendering which will likely change some assumptions about how `componentWill*` lifecycles work. In particular if we want to be able to "abort" and "rebase" rendering work, it might fire multiple times. So that's why mutations in it can be problematic. In fact we're trying to soft-deprecate `*Will*` methods in favor of alternatives that are safe for async: https://github.com/reactjs/rfcs/pull/6. I'm sorry this is not a very detailed answer, but we're still figuring how this would work ourselves. In any case the API will likely become more *constrained* about side effects and mutations rather than more *relaxed*, and that's why I don't come across as particularly supportive around this issue—for which I'm sorry.

**Comment by gaearon** [comment]
I'd say that we're unlikely to remove the existing warning about `this.state`.

We might consider adding a separate method to declare the initial state, but it would need to be an RFC so we can review a detailed design proposal. Please create one if you're interested: https://github.com/reactjs/rfcs

I'm sorry I couldn't be of more help.
