### ISSUE TITLE
Consider making <> pure unwrapped fragment

### ISSUE THREAD

**Issue by klimashkin** [facebook/react#11859]
**Feature request**

Currently if we pass Fragment with children to any custom component, this component gets that fragment as a child
```javascript
const App = props => (
  <MyComponent>
    <Fragment>
      <div/>
      <div/>
      <div/>
    </Fragment>
  </MyComponent>
);

const MyComponent = props => {
  Children.count(props.children); // 1

  Children.map(props.children, item => {
    console.log(item.type === Fragment); // true
  });
};
```

That means in all components where children is being altered (cloned) we need to check first that each item is a fragment first, and if it is - take its children instead of itself.

This was a little unexpected, because after reading the documentation the impression was that Fragment is a pure abstraction on the caller side, that Fragment doesn't propagate down to components, but only its children.

In the same time it's understandable because Fragment might have more supported props in the future that receiving component might want to read.

But fragment shortcut `<>` will not have props, it will always mean pure abstraction (to group its children to show them by condition, for instance).
So maybe react could unwrap its children right away when elements are created and pass them down as set of children (merge with another children on the same level)?

**React 16.2**

**Comment by amannn** [comment]
I've stumbled across exactly the same issue.

For this to work I now need a render function like this:

```js
render() {
  const {children} = this.props;

  const resolvedChildren =
    children.type === Fragment
      ? children.props.children
      : children;

  const enhancedChildren = Children.map(resolvedChildren, child =>
    React.cloneElement(child, {onClick: this.onClick})
  );

  render enhancedChildren;
}
```

I'm not sure if that `children.type === Fragment` check is safe. I was also expecting that a fragment is resolved by using `Children.map` and friends, so I wouldn't have to do this check.

**Comment by amannn** [comment]
As far as I understand, this part should be patched to also consider fragments for this to work: https://github.com/facebook/react/blob/cc52e06b490e0dc2482b345aa5d0d65fae931095/packages/react/src/ReactChildren.js#L149-L160

If that's the case, can I submit a PR?

**Comment by gaearon** [comment]
My understanding is this was an intentional decision. Paging @acdlite

**Comment by gaearon** [comment]
Also @clemmy might have context on why this behavior was chosen.

**Comment by clemmy** [comment]
As you mentioned, the children traversal semantics for `<Fragment></Fragment>` treats it as an element. The `<></>` syntax was created to be shorthand for `<Fragment></Fragment>`, so with that as the pretext, the same semantics exist for `<></>` since it’s simply de-sugaring to `<Fragment></Fragment>`. With your proposed changes to the semantics, switching from `<></>` to `<Fragment></Fragment>` will no longer be a non-breaking change. I think it’s an interesting idea, but the fact that it’ll take a different component to implement (leading to more complexity), and breaking compatibility between `<></>` and `<Fragment></Fragment>` is not very compelling to me.

In response to @amannn, that patch will change the semantics for both `<Fragment></Fragment>` and `<></>`, which is a separate behaviour to what @klimashkin is requesting (only behavioural change for `<></>`).

**Comment by gaearon** [comment]
I think changing behavior for *both* might be reasonable.
But we won't get much further in an issue here.
Please submit an RFC with your proposal: https://github.com/reactjs/rfcs

**Comment by arty-name** [comment]
I could not find an existing RFC on this subject so I have created [one](https://github.com/reactjs/rfcs/pull/61) myself
