### ISSUE TITLE
Unexpected token 'function' in jest test if my component has async function expressions

### ISSUE THREAD

**Issue by yiytan92** [facebook/react#11869]
BUG

**What is the current behavior?**
If my React component has async function calls like:
 var getParameter = async function getParameter() { ...
}

I receive an error: 

SyntaxError: Unexpected token function
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)

And the error resolves only if i remove async.

my .babelrc file looks like this:
{"presets": ["es2015", "react"]}

Please advise.

**Comment by nhunzaker** [comment]
Hey! This repo is focused on issues purely related to React, but I think it might be because `async` is in a later standard of JavaScript ([E2017](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)). Jest uses Babel to transform JavaScript code into a format NodeJS understands.

Instead of the `es2015` preset, I recommend giving the [`babel-preset-env` preset a shot](https://github.com/babel/babel/tree/master/packages/babel-preset-env), which keeps up to date with the latest language features. However you may want to consult the documentation for `babel-preset-env` if you hit additional issues or checkout Stack Overflow.
