### ISSUE TITLE
Remove legacy TODOs in ReactElement.createFactory() and ReactElementValidator.createFactoryWithValidation() 

### ISSUE THREAD

**Issue by onstash** [facebook/react#11936]
I came across this line -
 https://github.com/facebook/react/blob/dd8b387b69d73f9e8ed4f995ccb3cd927c0d33e3/packages/react/src/ReactElement.js#L269

I am interested in taking this up as my first pull-request. Please let me know what is required for adding a warning and it's related test/s. Thank you. 😅

**Comment by aweary** [comment]
Hey @onstash! I believe this is actually already implemented `ReactElementValidator`, which is used in place of `ReactElement` in the development build
https://github.com/facebook/react/blob/dd8b387b69d73f9e8ed4f995ccb3cd927c0d33e3/packages/react/src/ReactElementValidator.js#L354-L369

That TODO comment in `ReactElement` and `ReactElementValidator` should probably be removed since it's out of date (assuming that I understood it correctly) :)

**Comment by onstash** [comment]
I think I'll probably raise a tiny pull-request removing those TODOs as they're outdated. Thanks for the quick update, @aweary.

**Comment by onstash** [comment]
I have a doubt - is `createFactory()` directly accessible for a user? If yes, then we might need to replicate the same warning that's present in the snippet you have linked to. That's probably why the TODOs are present in `ReactElement`module. If no, then we might need to remove the TODOs that are outdated. Have I missed anything?

**Comment by aweary** [comment]
@onstash `createFactory` is exposed as `React.createFactory` here: 

https://github.com/facebook/react/blob/dd8b387b69d73f9e8ed4f995ccb3cd927c0d33e3/packages/react/src/React.js#L45

Looking back through the git history, this TODO comment was added in https://github.com/facebook/react/commit/199a7d6903ed2e7c28fb32c6a28ed7f26148e13d, before the current warning was implemented, so I think it's just an outdated comment that needs to be removed 👍

**Comment by onstash** [comment]
Happy New Year, @aweary! Thank you for helping me out with this issue. 😃
