### ISSUE TITLE
Why Marko.js is faster than React? Can React become as fast as Marko.js?

### ISSUE THREAD

**Issue by jvitoroc** [facebook/react#11932]
Resources
[Marko vs React: An In-depth Look](https://hackernoon.com/marko-vs-react-an-in-depth-look-767de0a5f9a6)
[isomorphic-ui-benchmarks](https://github.com/marko-js/isomorphic-ui-benchmarks)

**Comment by gaearon** [comment]
From a quick glance, it seems like they're using development build of React for measurements. It's going to be pretty slow as we state many times in the documentation.

We don't think it's productive for us to spend time reaching out to authors of other libraries that publish inaccurate benchmarks. If they were interested in correct measurements rather than promoting their library they would surely reach out to us first to confirm the benchmark is set up correctly.

**Comment by gaearon** [comment]
We also made some improvements to SSR performance in React 16, and added the streaming mode. So some of the article content is also outdated.

https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67
