### ISSUE TITLE
fiber-triangle fixture is not working

### ISSUE THREAD

**Issue by landvibe** [facebook/react#11937]
I cannot see any difference between async on/off.
I am using Chrome v63 on MacBook Pro.

**Comment by gaearon** [comment]
Yeah it’s not really useful right now. People also started making clones of it with other libraries without really understanding how it works or what it demonstrates. So we’ll probably fix it or better, replace it by examples that are easier to understand, in the future.

For now it doesn’t matter because **async rendering is not ready**. So it wouldn’t show anything useful anyway. The demos we had were done at an early stage but we now still need to finish the feature properly.

**Comment by landvibe** [comment]
I think it would be better to display some comments in the html (with red color)
Anyway I close this issue.
