### ISSUE TITLE
Symbols as keys in children as arrays or iterators

### ISSUE THREAD

**Issue by vectorsize** [facebook/react#11996]
**Do you want to request a *feature* or report a *bug*?**

I want to request a feature

**What is the current behavior?**

Using `Symbols` as element keys throws a type error.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

When using `key={Symbol('myKeySymbol')}` we get the following `TypeError: Cannot convert a Symbol value to a string at Object.ReactElement.createElement`

[codesandbox here](https://codesandbox.io/s/733pypz57j)

**What is the expected behavior?**
Using `Symbols` as keys should work seamlessly, in my opinion element keys are a perfect use-case for `Symbols`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Using React `16.0.0` and the browsers affected are Safari, Chrome and Firefox on OSX, but I'm pretty sure this is not browser dependent but a matter of implementation.

~~~

Thanks.

**Comment by benbraou** [comment]
@gaearon can I work on this issue?
This will be my first contribution to the source code (previous one was about tooling).
I have already crafted something that works locally (+ a very simple test).
I would like to go through the contribution docs first and polish everything (I will have for sure time next weekend but I will try to work on it in the middle of the week)

**Comment by gaearon** [comment]
Can you explain the use case? Why are Symbols useful as keys?

**Comment by vectorsize** [comment]
Well it's kind of simple really, even naïve perhaps. Since keys need to be unique and for the application logic kind of purposeless I thought it would be nice using symbols that are always unique without even have to worry about coming up with unique names.

**Comment by gaearon** [comment]
I think that's a misunderstanding of the purpose of the keys.

Keys don't need to be unique *globally*. They need to be unique *among siblings*. They don't need to be unique just to avoid clashes or something like this — they need to *represent a stable identity* of some data you're iterating over. So typically they would come from your data: such as a customer ID, or username.

See these explanations:

https://reactjs.org/docs/lists-and-keys.html#keys
https://reactjs.org/docs/glossary.html#keys
https://reactjs.org/docs/reconciliation.html#keys

You don’t need to “come up with unique names” — they should already be available in your data. Every time you iterate a list of something (users, rows, items, products, comments, posts), you should be able to use IDs of those items as keys.

So I don’t see a practical use case for allowing Symbols, except a misunderstanding.

**Comment by aweary** [comment]
Another potential problem with using Symbols is that it might obscure issues with unintentional data duplication. Since two symbols are never equal, even if they have the same value (`Symbol('id') !== Symbol('id')` you won't get a useful key warning about duplicate items---even if all the Symbol inputs were identical.

This would also be problematic if users defined Symbols as keys inline

```js
<div key={Symbol('foo') />
```

`key` would be different on every render, which would force React to re-mount the element/component. You'd have to always use `Symbol.for` to avoid these problems, which would be an easy pitfall for most users.

**Comment by dakom** [comment]
Counterpoint: a symbol may already exist on the data and it makes sense to re-purpose it in that case, no?

**Comment by smhg** [comment]
Isn't a Symbol a perfect match for a _temporary id_ (because unique) while you're awaiting receiving one from the server?

```javascript
// ...
handleAdd (item) {
  const collection = new Map(this.state.collection);
  const tmpId = Symbol('mycollection');

  collection.set(tmpId, item);

  this.setState({ collection });

  saveItem(item)
    .then(item => {
      const collection = new Map(this.state.collection);

      collection.delete(tmpId);

      collection.set(item.id, item);

      this.setState({ collection });
    });
}
// ...
```

Currenlty you have to convert the Symbol to a string yourself like this:
```javascirpt
<div key={String(id)}>{...}</div>
```
Not a big hassle of course, but I'd be grateful if @gaearon could validate/invalidate this usage.

**Comment by esanzgar** [comment]
In my opinion, supporting `Symbol` as  could be useful in this situation:

```
import React from 'react';

const TODO = [
  {id: Symbol(), content: 'Wake up'},
  {id: Symbol(), content: 'Go to sleep'},
];

const App = () => {
  return (
    <>
      {TODO.map(({id, content}) => (
        <p key={id}>{content}</p>
      ))}
    </>
  );
};

export default App;
```

So there is no need to rely on `Date` or `uuid` libraries.

**Comment by gopisanto** [comment]
Using Symbols is highly discouraged by me, because imagine there are 3 keys with "one", "two" and "three", assume you are changing or modifying data related to key "three", then if our code is good then it should not touch UI with keys "one" and "two", but in this case it will re-render them as well because, when you build the key using Symbol it will not be same next time even when the values are not changed. hence i will strongly discourage using Symbols. Let me know if some one agrees to me or correct me if something is wrongly perceived by me.

**Comment by jzarzeckis** [comment]
@gopisanto Do I imagine your example correctly?

```ts
const state = [
  { name: 'one', key: Symbol() },
  { name: 'two', key: Symbol() },
  { name: 'three', key: Symbol() }
]

const updatedState = state.map((item, i) =>
  i === 2 ? {...item, name: 'modified three'} : item
)
```

Here the 3rd item has its name changed, but the key remains untouched for all items.

**Comment by gopisanto** [comment]
This is the only object you have defined, but can you please tell me how you are iterating over this object while building some jsx and then how you are giving the key to jsx.

**Comment by angry-dan** [comment]
Say I want to make the simplest todo list (no storage, items stored in state only)
I have a state object holding an array of todos (strings): ```
['buy milk', 'book appointment']```

Now I want to render that list, I could use the string as a key, but my list is user generated content, and for some reason I might well create the same todo twice. So I could use `key={Symbol(str)}` and as long as I follow immutable principles the key would be stable for re-ordering the list and deleting items.

**Comment by ElijahKaftanov** [comment]
@gaearon @bvaughn 
ok, here is an issue
so I have a list of messages in a chat. And I want to add a new message to this list before the message even saved on my server. I don't have an id from db for this message, so my unique key could not be the id field. Thus I need to create a new unique key for each message. Creating and, more importantly, comprising strings is too slow I am starting to think about Symbols

**Comment by bvaughn** [comment]
You're commenting on the closed issue which is not as likely to get feedback.

> Creating and, more importantly, comprising strings is too slow I am starting to think about Symbols

I don't really know what this means.

**Comment by ElijahKaftanov** [comment]
@bvaughn 
it's just a continuation of the talk. Not a real issue, so I decided not to open a new issue.

Let's say I have a thousand messages on a list. To find the exact message I need to traverse through all items and comprise the keys. Isn't symbols were created for these certain tasks?

example thunk:
`
const spawnSendMessage = (message: Message) => async (d, g) => {
  const uid = Symbol.for('chat.message.uid');

  d(spawnPushMessage({uid, sent: false, ...message}));

  const id = await gate.apx({
    action: 'chat.message.send',
    body: message
  });

  const messages = findAndUpdate(
    msg => msg.uid === uid,
    msg => ({...msg, id, sent: true}),
    selectMessages(g())
  )
  
  d(spawnSetMessages(messages));
}
`

**Comment by bvaughn** [comment]
> it's just a continuation of the talk. Not a real issue, so I decided not to open a new one.

My suggestion was not to open a new one, but to comment on the issue that was already open: #19851

Although I'd suggest reading the discussion on that issue first– as using a Symbol for a key has some drawbacks too.

**Comment by Findiglay** [comment]
I think a temporary list of elements is a valid use case here. Symbol would work well for this since it is guaranteed to be unique.

**Comment by pauldraper** [comment]
Angular allows any value to be used as the key.

If you want something like that,

```ts
let key = 0;

const keys = new WeakMap<any, number>();

export function getKey(value: any): string | number {
  switch (typeof value) {
    case "bigint":
      return `bigint:${value}`;
    case "number":
      return value;
    case "string":
      return `string:${value}`;
    case "object":
      if (value === null) {
        return "null";
      }
    case "symbol":
      if (keys.has(value)) {
        return keys.get(value)!;
      }
      const k = key++;
      keys.set(value, k);
      return k;
    case "undefined":
      return "undefined";
  }
  throw new Error(`Unsupported: ${value}`);
}
```

```ts
[Symbol(), Symbol()].map(x => <div>{getKey(x)}</div>)
```

**Comment by tomtheisen** [comment]
@pauldraper This is a pretty elegant workaround, but be aware that as of Firefox 123, this is broken for symbols:

```js
(new WeakMap).set(Symbol(),1) 
```

```
Uncaught TypeError: WeakMap key Symbol() must be an object or an unregistered symbol
```

**Comment by steve-taylor** [comment]
Web apps don't necessarily render only data that comes from serializable data sources, such as APIs. It doesn't make sense for React to be so opinionated as to not allow symbols as keys. Symbols are designed specifically for uniqueness. Checking whether two symbols are equal or not is faster than comparing two strings.

There are also scenarios such as getting an array of data from an API where there's no reliably unique field, but we want them to have `key`s in React, so before rendering those items, we decorate them with symbol-based identifiers.

**Comment by pauldraper** [comment]
Angular figured out how to do this; one of the few things it does better

**Comment by mpawelski** [comment]
Vue also [allows symbols](https://vuejs.org/api/built-in-special-attributes#key) as key, and it makes total sense.

**Comment by n0f** [comment]
In Vue, Symbol-typed keys are allowed.
I frequently use Symbol-typed keys in projects built with Vue.
Having experienced their convenience, I have been eagerly waiting for Symbol-typed keys to be supported in React for the past few years.
Since there has been no progress, I decided to leave this comment in hopes of reigniting the discussion.

Below is the most typical example of using Symbol-typed keys:

```ts
// A Todo with a symbol as its key
interface Todo {
  key: symbol;
  body: string;
}

// A function to create a Todo
const createTodo = (body: string): Todo => {
  return {
    key: Symbol(),
    body,
  };
};

// Create some Todos
const todo1 = createTodo('Todo 1');
const todo2 = createTodo('Todo 2');
const todo3 = createTodo('Todo 3');

// Todo list
const todos: Todo[] = [todo1, todo2, todo3];

// Display the Todo list
function DisplayTodos() {
  return (
    <ul>
      {todos.map((todo) => (
        <li key={todo.key}>{todo.body}</li>
      ))}
    </ul>
  );
}
```

If Symbol-typed keys are not allowed, we would need to use alternatives such as `Date.now()` or UUID for keys. However, Symbol is more performant and, above all, more elegant.

In practice, the most common use case for Symbol keys is as temporary identifiers before sending data to a server. With Symbol, it becomes much easier to avoid unnecessary re-renders caused by new key generation compared to using `string | number`. For instance, you could write something like `key={todo.key || todo.id}`.

Moreover, in web applications that do not involve server communication (which is my most common use case), Symbol can be used as a unique identifier consistently across the application. In such cases, there may be no suitable values left to set as list keys if Symbol is not allowed.

For frontend-only unique IDs, being forced to manage incrementing keys, generate timestamps, or create UUIDs due to the `string | number` constraint is inefficient. Additionally, I often reuse these keys for `Record` or `Map` objects, and as the number of elements grows, comparing and searching through them becomes more time-consuming.

Some argue that not allowing Symbol keys is a safeguard against missing duplicate data. However, the same can be said for `Date.now()` or UUID if used inline, as those would also generate unique values for every invocation.

Considering the very purpose for which Symbol was introduced, I believe it should be allowed as a valid type for keys.

I hope this discussion can be revisited.
