### ISSUE TITLE
Bug: Wrong render output when children has textNode

### ISSUE THREAD

**Issue by Havunen** [facebook/react#12015]
There seems to be bug in React, when child node has textNode it does not render correct output.

Steps to reproduce (JSFiddle):
https://jsfiddle.net/vs6cbqdb/

Expected output is:
Hello 12
Hello 21
Hello 12
But React rendered:
Hello 21
Hello 12
Hello 21

rendered output is not matching console log, however when textNode is removed its working as expected. See this fiddle: https://jsfiddle.net/4yk06xgp/
12
21
12
Adding text node "Hello" before numbers causes unexpected output.

Tested only in React 16.2.0

**Comment by nanomosfet** [comment]
I think this is normal. An array is a mutable object in JavaScript. So each time you create a `Hello` component the `data` array gets reversed.

**Comment by Havunen** [comment]
@nanomosfet Yes that is expected. See console.log or use debugger for incorrect behavior.  The array data does not match rendered output in the first fiddle: https://jsfiddle.net/vs6cbqdb/
but it does match in the second (same code, except text node) https://jsfiddle.net/4yk06xgp/

**Comment by nanomosfet** [comment]
@Havunen Oh okay I see what you are talking about. The extra text makes it render differently.

**Comment by nanomosfet** [comment]
What would the use case of this be?

From the react docs, [link to reference in docs](https://reactjs.org/docs/components-and-props.html#props-are-read-only) it says that props are only supposed to be read only. 

I'm guessing a child of a component is considered a prop because you are accessing it from `this.props`.  Therefore, I think it's a good idea to rethink your approach of handling that `data` array. 

You could make `data` a state and have an observing function that lets the the top components know when `data` has changed. Then when data is changed you can change state accordingly.

**Comment by gaearon** [comment]
From the docs page you linked:

>All React components must act like pure functions with respect to their props.

You are mutating a prop by calling `reverse()` on it so your `render` is not a pure function. In this case the behavior can be anything because React doesn’t make guarantees around when it calls `render` (and thus when your mutations would happen).

If you just want to reverse the child order, you can copy them first by using `Children.toArray()` like in this fiddle: https://jsfiddle.net/kL1t6kkt/. The result of `toArray()` is safe to mutate because it's new every time (and thus even though it's technically a mutation, no other code could break because of it).
