### ISSUE TITLE
"Cannot create property for a non-extensible object" for SyntheticEvent in IE 11

### ISSUE THREAD

**Issue by wbern** [facebook/react#12011]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

An error is thrown in IE 11. The error message states "Cannot create property for a non-extensible object". It originates from the following location:

File "react/packages/events/SyntheticEvent.js"

```
function addEventPoolingTo(EventConstructor) {
  EventConstructor.eventPool = []; // Error: Cannot create property for a non-extensible object
  EventConstructor.getPooled = getPooledEvent;
  EventConstructor.release = releasePooledEvent;
}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
No errors.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The version number is react-dom 16.
Possibly related to #11240

**Comment by wbern** [comment]
I've found the underlying issue, it's the proxy-polyfill that react-dom attempts to use that fails, located here: https://github.com/GoogleChrome/proxy-polyfill/issues/37

**Comment by aweary** [comment]
@wbern just to clarify, React will only use `Proxy` in the development build. Are you developing with IE11, or seeing this in production? If it's in production, you might accidentally be running the dev build in production.

We could try to add a heuristic for detecting bad `Proxy` polyfills, but typically most people develop using a browser that already supports `Proxy`, so I don't think it's a high priority.

**Comment by wbern** [comment]
In this case we want to be able to run tests locally with the development build. And indeed you are right, it's the dev build.

proxy polyfill seems to be a function which is why it can't be assigned properties. Not sure why, but I guess that is something that could be checked, whether it's a function or not?

Thanks for the reply!

**Comment by gaearon** [comment]
It's not because it's a function. It's because they (intentionally) call `Object.seal()`.

I think the conclusion here is that React expects a real Proxy but the polyfill implements a limited subset that's incompatible with how React uses it. There are two possible solutions I can see:

* You can stop using this polyfill together with React (they won't work together)
* We could change our logic to handle this polyfill specifically

I feel like it's not really our responsibility to fix this, but it's also an easy fix so I don't mind it too much. I expect people might start using the polyfill more widely in the future as Proxies become more used by libraries so maybe it's a good compromise.

The "fix" on our side is here: https://github.com/facebook/react/pull/12017. Could you please verify if that solves the issue on your side?

**Comment by wbern** [comment]
That looks exactly to be the way to solve it.

Ok my case, it turned out that I did not want a proxy polyfill that is sealed and for that I need to turn to the babel polyfill which is a little out of shape. But I still think, considering proxy polyfill has a lot more people using it, that you are verifying this.

Thanks so much!
