### ISSUE TITLE
Event Handlers on Fragments

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#12051]
The use case is when an abstraction wants to listen to some event bubbling up and intercept the event somehow.

```js
function Abstraction(props) {
  return <div onClick={() => props.onAction()}>{props.children}</div>;
}
```

Perhaps there is some state and context involved too.

This works fine today as long as you can wrap it in a `<div />`. However, you can't necessarily always do that. I hear that some of this will be relaxed but conceptually I think the constraints will remain in many environment that you don't want a wrapper element around these.

```js
<ul>
  <Abstraction onAction={...}>
    <li>A</li>
    <li>B</li>
  </Abstraction>
</ul>
```

```js
<table>
  <tbody>
    <Abstraction onAction={...}>
      <tr><td>A</td></tr>
      <tr><td>B</td></tr>
    </Abstraction>
    <Abstraction onAction={...}>
      <tr><td>A</td></tr>
      <tr><td>B</td></tr>
    </Abstraction>
  </tbody>
</table>
```

It would be nice to be able to use fragments for this.

```js
function Abstraction(props) {
  return <Fragment onClick={() => props.onAction()}>{props.children}</Fragment>;
}
```

It is easy to implement with the synthetic event system but I suspect it is doable with other approaches too (including just inserting an element called `<fragment />` in the DOM).

To implement this we'd need somewhere to store the "current" props. We can use the `stateNode` on fragment fibers to hold that. We also need to schedule commit phase effects whenever the set of event handlers on a fragment changes. In the commit phase we update the stateNode on both Fibers to hold the "current props".

That way when we bubble up the fiber return pointers, we know that stateNode holds the current set of props and those will be the ones we extract event handlers from.

**Comment by sophiebits** [comment]
We'd need something like `display: contents` in order to actually insert a DOM node. It's not clear that this is really feasible without the synthetic event system AFAICT.

**Comment by sebmarkbage** [comment]
I believe there are plans to allow for more of these forms in browsers, and even if the normal DOM node solution doesn't work, a plausible future addition would be to have first class fragment nodes. @trueadm has been really passionate about this. So I think there's at least a plausible future where this capability just works natively.

However, even without that, it doesn't have to use the full synthetic event system, it can also intercept, and redirect locally. We probably want that anyway for batching/controlled/default priorities. For any local event handler attached on a DOM node, it can also call any parent fragments. Enter/leave would have an extra enter/leave but that's not such a big deal since we've noticed that you typically want a timeout for such uses anyway.

**Comment by clemmy** [comment]
Perhaps I'm missing something, but doesn't inserting an element called `<fragment />` into the DOM mean that we're still adding a wrapper element?

**Comment by gaearon** [comment]
Yes. The post doesn't say it's necessary, just that it's technically possible without a synthetic event system.

**Comment by trueadm** [comment]
I'm not too sure about this idea when it comes to the web. I personally feel fragments should not have any events and users should stick to using elements for when they need events.

I always envisaged (and originally proposed a spec for a native DOM fragment) they were special nodes that had no layout/styling properties – meaning they couldn't have events attached to them. For example, how can mouse events even interact with something that has no positional rectangle? They were meant to act very much like how DocumentFragments and TextNodes do now instead of how Elements do.

**Comment by aweary** [comment]
> For example, how can mouse events even interact with something that has no positional rectangle? 

I would assume that event listeners on fragments should only listen to events dispatched by children, either in the capture or bubble phase, so there would be no concept of an event being dispatched on a fragment directly.

**Comment by trueadm** [comment]
@aweary What if I had nested fragments within fragments or portals within fragments? How would `onResize` work or `onBlur` work with fragments too? I'm generally curious as to how these can be solved in the synthetic event space as it could help create a native fragment polyfil for my implementation idea I had.

**Comment by aweary** [comment]
@trueadm I haven't given this idea a lot of thought, but conceptually fragment events could just be synthetic "aggregates" which let you signal to the synthetic event system that you want to listen to some set of events on the children of the fragments. So if you had a fragment listening for `blur` events it would attach listeners to the appropriate elements rendered in that subtree (maybe by using some ancestor tracking to know which fragment(s) its contained within).

For nested fragments the event would move up/down the tree, and any matching fragments would be triggered, just like how it works now with DOM elements. I think the primary use case is wrapping some direct children, like a `tr` in `tbody`, so nested fragments could potentially be restricted somehow if it causes problems, I'm not sure.

I'm not sure about portals.

**Comment by pyromaniac** [comment]
I really miss this feature while trying to create proper abstractions. In order to listen to events from the inside, I have to wrap everything with additional nodes. To avoid the creation of the nodes I have to invent function children interface, pass event listeners there as arguments and manually assign them to the topmost nodes inside. This is not easily testable or clean interface. I can only imagine how much easier my life will become after events support for `Fragment`.

I can double the implementation proposal: it should call the handler as soon any descendant node emitted the event. As far as I got, it is already implemented this way internally, the Synthetic Events have their own bubbling phase which happens later than the engine one and it bubbles up through all the React components.

**Comment by pyromaniac** [comment]
Hm, unfortunately, this feature is not mentioned in #12152 :(

**Comment by TrySound** [comment]
@pyitphyoaung This is only discussion without decision. Do not expect this behavior will be implemented, maybe won't.

**Comment by pyromaniac** [comment]
Yeah, I realize this but since the feature is mentioned in the official docs (https://reactjs.org/docs/fragments.html#keyed-fragments) I've thought they at least have plans. Btw, you've missed my handle.

**Comment by kyeotic** [comment]
This looks dead. If we are interested in this should we open a new issue to track discussion?

**Comment by pyromaniac** [comment]
Well, too bad :(

**Comment by trueadm** [comment]
This isn’t something we have planned. Longer term, our work into a new experimental event system should allow for event capturing without the need to couple an event to a DOM node (so it would work in a similar way to having event handlers on fragments).

**Comment by kyeotic** [comment]
That's interesting, I would have expected the current event system to be capable. Is this something you would consider an external PR for? I could really use _exactly_ what sebmarkbage showed in the first post, and I would be happy to take a crack at implementing it.

**Comment by bsidelinger912** [comment]
I too would love to have exactly what @sebmarkbage described in the first post.  I have a POC implementation, but my use case for doing this for work changed, so I stalled out on working on it.  The challenge I ran into was that the way a Fragment is represented as a fiber node is pretty different from other nodes, so I had to dig into the guts of fiber more than I had expected.  @kyeotic, if you pick this up, I'm happy to share what I learned.  I'd assume a well done external PR would be considered as long as it didn't clash with other strategic plans for the library, maintainers can correct me though if I'm wrong about that.

**Comment by kyeotic** [comment]
@bsidelinger912 I've finally got some time to work on this and I would love to find out what you've learned/accomplished already. This will be my first time digging into React internals since they switched to Fiber, so anything helps.

**Comment by bsidelinger912** [comment]
@kyeotic, so the big challenge I faced was that Fragments aren't represented the same as other nodes in fiber.  The important difference is they don't have props, just children and a key.  If you're familiar with how events work in react, you'll know that all it's doing is checking the fiber nodes for a prop that matches a list of event props.  In order to make a simple working demo I had to change props validation for a fragment (that was pretty simple), and I had to change the structure of a fragment as a fiber node (not so simple).  Doing this I got onclick working in this branch: https://github.com/bsidelinger912/react/tree/events-on-fragment.  However I broke something like 120 tests and probably did things that would conflict with lots of ongoing work.  I think some coordination with the team would be necessary to realistically merge this type of change, since it really digs deep into the guts of fiber.  Feel free to email me at ben[dot]sidelinger[at]gmail.com if you want more info or clarification.

**Comment by kyeotic** [comment]
@bsidelinger912 Thank you, there is some useful stuff in there. I'm still getting oriented in the code, and there is some very useful stuff in your 2nd commit. I will let you know if I have any questions after I try some of that tomorrow.

**Comment by trueadm** [comment]
We aren't planning on adding event support to fragments for the existing event system (like I mentioned in my previous post above). I'm going to close this rfc for now too, for the same reasons.

**Comment by robatwilliams** [comment]
> We'd need something like display: contents in order to actually insert a DOM node.

This is widely supported by now, but has some issues - a) extra dom elements, b) breaks some existing CSS selectors. In a larger app those are problems.

> Longer term, our work into a new experimental event system should allow for event capturing without the need to couple an event to a DOM node (so it would work in a similar way to having event handlers on fragments).

@trueadm Is this still on the agenda?

**Comment by trueadm** [comment]
@robatwilliams I no longer work on React core, so maybe someone else on the team can better inform you of the future agenda around this particular feature.

**Comment by robatwilliams** [comment]
Thanks. @sebmarkbage, as opener and current core team member, would you be able to comment please?

**Comment by LoganDark** [comment]
> This isn’t something we have planned. Longer term, our work into a new experimental event system should allow for event capturing without the need to couple an event to a DOM node (so it would work in a similar way to having event handlers on fragments).

Is this work complete, or where can I hear about it? Because I'm running into a problem where I want to implement a right click menu, but don't want to spam random wrapper elements around, and also don't want to put a handler on the body because that would mean I couldn't use contexts for right click menu items... it's honestly a whole mess

**Comment by robatwilliams** [comment]
One use case we have is user interaction tracking. This was already implemented some years ago using `findDOMNode()`. We have a component that has no DOM (just renders its children), but tracks clicks etc. from its children, together (recently enhanced) with a breadcrumb of position in the app which is retrieved using the context API.

To do this without `findDOMNode()`, we either have to add an extra wrapper element with `display: contents` (which breaks some CSS selectors which expect a certain DOM structure (yes I know that's good practice, this was not my doing)), or we have to use a much more cumbersome interface (as described [here](https://github.com/facebook/react/issues/12051#issuecomment-368250169) or similarly using hooks).
