### ISSUE TITLE
Characters in String objects are rendered as separate elements

### ISSUE THREAD

**Issue by realmika** [facebook/react#12132]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Characters in String objects (created with "new" keyword) are rendered as separate elements. For English this is not visible for the user, but for Farsi the letters become disconnected (for them it looks like "t h i s")

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/Luktwrdm/79/

`<p>{new String("hello")}</p>`

Five separate text elements are rendered. In Chrome Inspector, it looks like this:
![image](https://user-images.githubusercontent.com/1054229/35676445-1955683c-074c-11e8-8068-a35b9edd68ae.png)

**What is the expected behavior?**
The value represented by the String object to be rendered just like any native string value would.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 1.0.17, tested on Chrome on Ubuntu. Likely unrelated to version or OS.

**Comment by gaearon** [comment]
Don’t use `new String`. It’s [unnecessary](https://stackoverflow.com/a/5750721/458193).

React has no special support for string objects created with `new`. They’re not considered string primitives in JS. Checking for this rare case in hot rendering code paths would be wasteful. We also can’t reliably detect `String` objects coming from another iframe anyway.

The reason this shows up at all is because the String object instance happens to be iterable. So React iterates over it.

I don’t think we need to do anything extra to prevent this. What do you think?

**Comment by realmika** [comment]
String objects [can be useful](https://stackoverflow.com/a/39113022/575796). String natives do not convey important information about the text they contain, such as if is written from right to left.

I agree checking specifically for String objects would be wasteful (and unreliable) as they are like any other object.

Is there some mechanism in which I can inform React how to render this object? Perhaps if it checks the presence of a specific function? Such a feature could be of value in a variety of cases. If not, would you accept a PR?

**Comment by gaearon** [comment]
It's a pretty big change so I think it'll need to be an RFC first: https://github.com/reactjs/rfcs

**Comment by aweary** [comment]
> String objects [can be useful](https://stackoverflow.com/a/39113022/575796).

As far as rendering goes, those advantages listed aren't really relevant. Whether the `String` objects have properties or can be inherited from doesn't matter to React, since the expected behavior in any case would be to just treat them as string literals.

If you're representing some textual data with `String` instances for some of those listed reasons, I would recommend just coercing them to actual strings before rendering:

```jsx
const text = new String("Hello");
<div>{text + ''}</div>
```
