### ISSUE TITLE
Can modify parent component's state through child component's props

### ISSUE THREAD

**Issue by sphuff** [facebook/react#12137]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It is possible to modify the state of a parent component through child props if the prop is an array or object. This seems to be a byproduct of the fact that javascript passes arrays/objects into functions by reference instead of by value. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I have shown what I mean in [this codepen](https://codepen.io/anon/pen/OQyGRz). 

**What is the expected behavior?**

You should not be able to modify parent state in a child component through props, since props are normally assumed to be immutable. It is easy to prevent this behavior by doing a deep clone of array/object before it is passed in as a prop. Just do a `slice()` on the value array in my example to see what I mean. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I've tried React 15.6.1 and 16.2.0.

**Comment by meowtec** [comment]
This is not a bug
`props are immutable` does not means `values of props are immutable`.

**Comment by gaearon** [comment]
Doing a deep clone is very slow and defies any performance optimizations in components below because they can no longer compare values by reference. See “optimizing performance” in docs for details on why this is important.

Ultimately there’s nothing React can do to guarantee you won’t mutate props by accident. You can recursively freeze the objects you’re working with if you’d like stronger guarantees but that comes with a performance penalty so I don’t recommmend doing that in production. You can also use a library like `seamless-immutable` to help you with making immutable updates.
