### ISSUE TITLE
`getDerivedStateFromProps` concern

### ISSUE THREAD

**Issue by bradenhs** [facebook/react#12249]
Just read about `getDerivedStateFromProps` and am concerned the new api won't be flexible enough to cover some common use cases.

For instance, I have a scrolling tabs component. Whenever the `selectedTabId` prop changes I use browser apis to scroll that tab into view. What would be the best way to accomplish this without `componentWillReceiveProps`?

Currently code is something like this:

```js
class Tabs extends React.Component {
  render() {
    return (
      <div className="tabs-container">
        {this.props.tabs.map(tab => (
          <div className="tab" key={tab.id} id={tab.id}>
            {tab.title}
          </div>
        ))}
      </div>
    );
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.selectedTabId !== this.props.selectedTabId) {
      document.querySelector(`#${nextProps.selectedTabId}`).scrollIntoView();
    }
  }
}
```

**Comment by iamdustan** [comment]
For your current example you likely want `componentDidUpdate`. `componentWillRecieveProps` is called _before_ the DOM is actually updated so you have a condition where you may attempt to scroll an item into view prematurely.

```jsx
  componentDidUpdate(prevProps) {
    if (prevProps.selectedTabId !== this.props.selectedTabId) {
      document.querySelector(`#${nextProps.selectedTabId}`).scrollIntoView();
    }
```

Alternatively you could consider a ref rather than DOM APIs in this example:

```jsx
class Tabs extends React.Component {
  render() {
    return (
      <div className="tabs-container">
        {this.props.tabs.map(tab => (
          <div className="tab" key={tab.id} ref={tab.id === this.props.selectedTabId ? this.scrollRef : null}>
            {tab.title}
          </div>
        ))}
      </div>
    );
  }

  scrollRef(ref) {
    if (ref) {
      ref.scrollIntoView();
    }
  }
}
```

**Comment by bradenhs** [comment]
Thanks @iamdustan! I've actually haven't used the `componentDidUpdate` lifecycle method before but can see it's a much better solution than what I have been doing. Deprecating `componentWillReceiveProps` will probably help steer a lot of folks like me in a better direction with use cases like this one.

**Comment by unruffledBeaver** [comment]
I actually have an additional concern similar to this. I often will block re-renders on components that are doing imperative DOM changes, most commonly, canvas elements. Because the only element rendered is `canvas` all my updates happen through a draw method, not the React renders. 

A pattern I use a lot is 
```
    componentWillReceiveProps() {
        this.draw();
    }

    shouldComponentUpdate() {
        return false;
    }
```

So I can still use HOC's to calculate things like mouse movements and drag and pass values in as props without re-rendering my canvas element. 

Other than passing calling `draw` through a ref, which would couple those components, is there another way I can do this?
