### ISSUE TITLE
Input replacement bug/changing a controlled input

### ISSUE THREAD

**Issue by DylanLester** [facebook/react#12273]
**Do you want to request a *feature* or report a *bug*?**
Appears to be a bug.

**What is the current behavior?**
CodeSandbox: https://codesandbox.io/s/q12v934j?expanddevtools=1 
*Quick development solutions are listed in the CodeSandbox README.*

Demo:
![react_input _replacement_bug](https://user-images.githubusercontent.com/12122777/36580695-6db21132-18bd-11e8-9698-6ea1fcf8a356.gif)

Warning:
![react_input _replacement_bug_warning](https://user-images.githubusercontent.com/12122777/36581076-35e5f190-18bf-11e8-8479-42cd9da77c2b.png)

1. Open the debugging console
2. Wait 8 secs for setTimeout (line 65) to change state
3. Observe the warning in console: "Warning: A component is changing a controlled input of type text to be uncontrolled"

This is happening as React is only updating what is necessary on the input elements. React adds the additional properties (placeholder, title, readonly) and changes the existing property "value" of the input that is being replaced rather than replacing the entire input. This results in the controlled status changing (DOM's input element persists it's value too).

**What is the expected behavior?**
The old input element is replaced by the new input (that uses placeholder text). Use case is described in the *origin* section of the CodeSandbox README. Actual desired behavior is unknown.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version: 16.2.0
Chrome version: 64.0.3282.167 (Official Build) (64-bit)

Does not throw the warning (may be production version) and the DOM input value is not persisted.
Codepen: https://codepen.io/anon/pen/gvjgZR?editors=0010
React version: 13 (I think)

**Comment by heyimalex** [comment]
This is expected? You're not supposed to switch between controlled and uncontrolled components.

**Comment by aweary** [comment]
This is expected behavior.

> React adds the additional properties (placeholder, title, readonly) and changes the existing property "value" of the input that is being replaced rather than replacing the entire input.

Even though `nullValueWrapper` returns a different input element, it's identical to the one passed in as `component`. Due to the way React diffs changes, this is considered an update to the existing input element, not a new element.

So what happens is you render the input with a value of `""`, then `"Dummy Text"`, and then `null`. The warning occurs because you cannot use `null` to represent an empty value for a controlled component; you should use `""`.

Check out this section in the docs on this: [Controlled Input Null Value](https://reactjs.org/docs/forms.html#controlled-input-null-value)

Hope that helps!

**Comment by DylanLester** [comment]
I see how this is expected behavior now, thank you very much.

Your clarification is much appreciated, and I apologize if this inconvenienced you.
