### ISSUE TITLE
Strange Behavior in Conditional Rendering

### ISSUE THREAD

**Issue by jyash97** [facebook/react#12286]
**Do you want to request a *feature* or report a *bug*?**
Bug

_**Strange Behavior in Conditional Rendering as follow :**_

```js
render() {
    const data = true;
    return { data ? <h1>True</h1> : <p>False</p >};
  }
```
[https://codesandbox.io/s/lr59oqxm2l](url)
This gives an error and the warning message is not clear about the error. 
And If we wrap the code in a div it works fine ;

```js
render() {
    const data = true;
    return <div>{data ? <h1>True</h1> : <p>False</p>}</div>;
  }
```
[https://codesandbox.io/s/r74noj0qw4](url)

If this is not a `bug`, can we have a `better and clear` error message.

_Thanks!_

**Comment by marvinhagemeister** [comment]
This is not a bug and has nothing to do with react. This is simply invalid JavaScript code.

The curly brackets `{}` in js denote a [block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block). Since a block is not an expression you cannot use the ternary operator directly, without any assignment or something similar.

In the second case you are inside jsx, because the `<div>` starts the jsx "context" for a lack of a better word. Inside jsx the brackets have a different meaning. They translate to "now comes js code".

```js
render() {
  const data = true;
  // Remove the brackets here, because we are not inside jsx
  return data ? <h1>True</h1> : <p>False</p >;
}
```

**Comment by jyash97** [comment]
Thanks @marvinhagemeister  I just Reliazed I have done a very silly mistake, must have seen the code carefully before opening the issue.

**Comment by marvinhagemeister** [comment]
No worries, happens to all of us :)
