### ISSUE TITLE
jsx's close tag name may optional?

### ISSUE THREAD

**Issue by xp44mm** [facebook/react#12340]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
```html
<div>
  <p>some text</p>
  <hr/>
</div>
```

**What is the expected behavior?**
because the html tag always pairs, so if simple write better?
```html
<div>
  <p>some text</>
  <hr/>
</>
```

**Comment by TrySound** [comment]
@xp44mm `</>` already used as a syntax sugar for `</React.Fragment>`

**Comment by cpwr** [comment]
you should definitely try to use IDEs, they solve your problem

**Comment by xp44mm** [comment]
@TrySound 
it's doesn't matter
```html
<><div></></>
```
because it's pair,just like nested `()`,`[]`. one open tag vs one closed tag

**Comment by gaearon** [comment]
If it was optional, there would be no point in using JSX at all—might as well do function calls that also only use the name once. Repeating it twice is intentional so that you can see the nesting from both sides.

In any case, if you feel strongly about it, please suggest it in https://github.com/facebook/jsx instead.
