### ISSUE TITLE
Cloned element using component created in render() doesn't trigger onClick()

### ISSUE THREAD

**Issue by JoshuaJacobowitz** [facebook/react#12348]
**Do you want to request a *feature* or report a *bug*?**
Bug (probably)

**What is the current behavior?**
Rerendering a cloned element, using a component created in it's render(), on any event that is triggered while clicking will cause onClick() to not be triggered.
Simplest implementation that causes this: https://codesandbox.io/s/1o9o6k8mp7

**What is the expected behavior?**
That onClick() gets triggered.
Not cloning the element or not using a component created in render() will fix this.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version 16.2.0 and 15.6.2.

**Comment by cloudever** [comment]
Your example looks like a spagetti code. Did yout notice that writing
```js
const Inner = ({ children }) => {
  const SomeComponent = () => <div>{children}</div>;
  return SomeComponent();
};

did the trick?

**Comment by aweary** [comment]
I don't recommend creating components in in render, but this behavior does seem unexpected. Why are you calling `forceUpdate` on mouse down? It looks like that's causing the problem, since removing the `forceUpdate` call fixes the issue.

**Comment by tobilen** [comment]
@aweary i suppose its just a stand-in for doing something that triggers a rerender (like calling `setState`)

**Comment by aweary** [comment]
@tobilen the problem with that pattern is that you're creating a new component function on every render, which can be problematic. If you need to dynamically create components during the render phase, I recommend implementing some kind of cache so you don't have to keep re-creating the same semantically identical functions over and over.

Here's a version of @JoshuaJacobowitz's demo that does that, and you can see it doesn't have the same issue: https://codesandbox.io/s/2pwl59067n


@JoshuaJacobowitz the root cause of the problem here is that by creating a new component on every render, and _also_ creating a new element by using `cloneElement`, React's reconciliation heuristics identify this as an entirely new component and throw out the old one. Normally React would just update the mounted component, but in this case it has to unmount the old `SomeComponent` component and mount the new one on every render.

Now the reason this breaks the click event is because when `this.forceUpdate()` is called in the `onMouseDown` handler it forces a re-render, which causes the component to be unmounted and re-mounted before the click event would propagate. This means that the component where the click event originated from is unmounted before the click event is processed by the synthetic event system, and it doesn't get processed.

This is expected behavior, which you can see here in an example that doesn't use `cloneElement` or components defined in render: https://jsfiddle.net/w7x4o8wd/

I hope that explains things well enough. I would recommend trying to re-architecture your component to avoid recreating the component in render, or try the caching solution I outlined.
