### ISSUE TITLE
Impossible to change classname

### ISSUE THREAD

**Issue by joeyhub** [facebook/react#12366]
I would like to change a class name to invoke a simple animation effect.

className as an attribute must be a string. When I run render it appears to do more than simply update the class as the animation doesn't run, even with keys set.

I also can't render once and then change the class as props is readonly.

**Comment by jquense** [comment]
Hey there, Please provide a reproduction of the issue your seeing using the template provided in the issue template, you should have seen when you opened the issue. It's not possible to diagnose the problem from your description, especially since all the things you're describing are very possible and common in React

**Comment by aweary** [comment]
No response or reproduction, closing out.
