### ISSUE TITLE
Whitespace kills SVG text

### ISSUE THREAD

**Issue by fforw** [facebook/react#1236]
See this http://jsfiddle.net/XB98M/

Note the spaces around the {"bar"} entry that make it not being rendered as SVG text but as span after the SVG.

**Comment by srcspider** [comment]
@zpao

The bug is actually not limited to just the text element. If you say have something simple like:

```js
<g>
\t{pts}\t{lines}\t{xAxis}
</g>
```
*the character escaping there is intentional since bug involves invisible characters*

...everything will go boom as well. 

Personally I'm not a fan of the magical span insertion. The way react did it previously where whitespace had to manually inserted was actually a nice "feature" since it removed the need for crappy `font-size: 0` hacks and meant everything was always exactly as intended. 

While its more or less harmless for html use cases for svg where text can only really be inserted with `<text>` tags I think React should just disable that magic altogheter; but I guess it's tricky to disable. 

**How about if** the magic span insertion only happens for certain html tags, eg. span, p, h* and in all other cases react will strip out the whitespace and won't inject anything in the code. That *should* work out for all parties, people who want their whitespace just have to properly use html tags, people like me who, for the most part, don't want it ever can stick divs everywhere.

**Comment by natew** [comment]
Just want to comment here and say this is pretty tricky when going with flex box. Without spans your text will flow as it should, but once it's wrapped with a span, you no longer can preserve this at all.

Our default flexbox CSS reset uses `flex-flow: column`. Even when doing `display: inline` for spans, it will break text into lines once you use a variable. Not sure how to get around this, but is a pretty big "weirdness" of using React now.

**Comment by thelambdaparty** [comment]
For anyone searching about this (like i was). Works in 14.0 :smile: 
https://jsbin.com/toluqu/3/edit?html,js,output

**Comment by skcalanderson2** [comment]
Thank you thelamdaparty! I have been trying to get this to work all day. The tspan did the trick.

**Comment by kfix** [comment]
@thelambdaparty @skcalanderson2 : I use that workaround too but its not a solution. I shouldn't have to template everything (ex: ``` <tspan>{`purely static string`}</tspan> ```) to keep my SVG's from getting span'd and broken.

**Comment by spicyj** [comment]
Should be better now due to #5753.
