### ISSUE TITLE
dangerouslySetInnerHTML will wrap on SSR but not client and both are editing invalid HTML

### ISSUE THREAD

**Issue by TimoRuetten** [facebook/react#12415]
Currently we need to use the dangerouslySetInnerHTML tag in a special case. In this case we need to split our string into several and then we need to render them. This could look like this:

```javascript
[
      <div
        key="markup-1"
        dangerouslySetInnerHTML={{ __html: '<div><h1>InnerHtml Test</h1>' }}
      />,
      <div
        key="markup-2"
        dangerouslySetInnerHTML={{ __html: '</div>' }}
      />
    ]
```

This looks dirty - and yes, it is - but in our case we need to do smth like this until we've found a better solution. The Problem is that the SSR does not match with the client. This is the error:

```javascript
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "<div><h1>InnerHtml Test</h1></div><div></div>" Client: "<div><h1>InnerHtml Test</h1></div>"
```

**Problem 1**
It seems that on SSR react is wrapping the dangerouslyInnerHtml - the client does not. In general its a problem that React is wrapping it and we are wondering if we could avoid this somehow. Because our first HTML part is not valid and will just be valid with the second part.

**Problem 2**
The second Problem is that it seems that react is making the part valid. On Server and on Client react is closing the first part with the </div>.

Maybe you are wondering why we are doing this. The Problem is that we load HTML data from a database and we need to replace some special words with real React Components. So our  plan was something like this:

```html
<div>
<h1>Markup</h1>
<p>Some text...</p>
<RenderAComponentHere />
<p>More text ..</p>
</div>
```
Now we split the HTML so we will get an Array with 2 Items.

```javascript
[
'
     <div>
     <h1>Markup</h1>
     <p>Some text...</p>
',
'
     <p>More text ..</p>
    </div>
'
]
```

Now we want to render the first Part with dangerouslySetInnerHTML, then we will render our real React-Component and then again the last part with dangerouslySetInnerHTML.

**Comment by gaearon** [comment]
Can you turn this into a failing test in `ReactDOMServerIntegration*` suite?

**Comment by JoeCortopassi** [comment]
@TimoRuetten I think he's asking if the existing tests (ReactDOMServerIntegration*) can be updated to fail by accurately testing what _should_ be happening (server/client having identical behavior).

@gaearon I can update the tests for that. Do you want a pr for just that before the fix?

**Comment by cari69** [comment]
Yes fix

**Comment by gaearon** [comment]
>I think he's asking if the existing tests (ReactDOMServerIntegration*) can be updated to fail by accurately testing what should be happening (server/client having identical behavior).

Yep 
👍

**Comment by Aliin** [comment]
Hi everyone,

I decided to have a go at this as a first issue, I hope that is fine and I am really happy to take part in a small way!

first of all here is a test that demonstrates how the HTML output looks and that it is indeed a mismatch.

For @TimoRuetten 's array that looks like this on the server side: `<div data-reactroot=""><div><h1>InnerHtml Test</h1></div><div data-reactroot="" /></div>`, which is invalid, and like this on the client side: `<div><div><h1>InnerHtml Test</h1></div></div>`.

I believe there are two problems. First, @TimoRuetten I do not fully understand why you try to insert invalid HTML parts as children into React nodes. I am not sure if it is safe to manipulate the actual HTML tags that are rendered by React with your rendered strings. Since the string is supposed to be "inner" HTML it actually should just contain the child nodes. Why don't you add whatever closing 'div' tags and such are missing as a string and put all of that into a React container? If you need to manipulate it with React you can use Portals.

Please correct me if I'm wrong, I am only want to give constructive criticism.

Secondly, I think then it can be dangerous to try to parse incomplete HTML into React, which is why React tries to use `dangerouslySetInnerHTML` to prevent cross-site attacks. On the client side, it seems the HTML is automatically "cleaned" so that at the end there is no invalid HTML. Does that work safely? Or does it make sense to throw an error if the HTML is not working properly?

On the other hand, the HTML rendered on the serverside seems to not "clean" the inner HTML, which could be a vulnerability for cross-site attacks I guess. So I suggest to either throw a warning or make it safer the same way as in the client rendering.

@gaearon If you can define how the HTML that is generated at the end should look, I will attempt to fix the issue.

Thanks a lot

**Comment by gaearon** [comment]
Ooh. I completely missed that the inserted HTML was invalid. Thank you @Aliin for explaining this! Indeed, this is unsupported because we can't *possibly* support it on the client. The client doesn't construct an HTML tree so this couldn't work even if we wanted it to.

> The Problem is that we load HTML data from a database and we need to replace some special words with real React Components. So our plan was something like this:

Yeah I don't think this plan would work. What you could do instead is to leave special placeholders in your HTML, e.g.

```js
<p>Some content</p>
<!-- replace-me-with-react-node -->
<p>Some other content</p>
```

You'd render *that* with `dangerousSetInnerHTML`, and then do a second pass in `componentDidMount` (client-only) to imperatively `ReactDOM.render` the components into those comment node placeholders. Note that you'd need to be very careful for HTML to never change on the client since otherwise the next client update would wipe them out.

Or you could consider a format different to HTML.

**Comment by vjeka** [comment]
I have a same problem using React with Next.js. 
Currently as a dirty fix implementing two-pass rendering but with the same content for client and server. The presentation is OK however error is still present and of course rendering component twice is not a by the book solution. 
Looking forward to see what will up to.
