### ISSUE TITLE
Functional components with lifecycle methods and state

### ISSUE THREAD

**Issue by Josema** [facebook/react#12436]
What about if we could have functional components that can be turned into components with state.

The problem:
```js
function Button({ value }) {
  return <button>{value}</button>
}
```
If our needs changes and we need to apply local state we must change this function into a class
```js
class Button extends Component {
  constructor(props) { ... }
  shouldComponentUpdate() { ... }
  render() {
       return <button>{this.props.value} {this.state.countdown}</button>
  }
}
```

If we use the prototype of the function we can reuse our function.

```js
function Button({ value }, { countdown }) {
  return <button>{value} {countdown}</button>
}

Button.prototype.constructor = props => { ... }
Button.prototype.shouldComponentUpdate = () => { ... }
```

The benefits of this approach are that we educate people to use functional components in the first place. Also, avoid rewrite too much code when adding features to our app.

Of course there are downsides. This change a lot the style of the code that we all learned in React, and also this is much more verbose `Button.prototype.shouldComponentUpdate = () => { ... }` than `shouldComponentUpdate() { ... }`

But in my opinion, the code is much more elegant and remove the need of using classes which personally I don't like at all.

Any thoughts? Is this too crazy to add as an option/feature?

**Comment by aweary** [comment]
Hey @Josema, this is something that's been considered before (https://github.com/facebook/react/issues/9513#issuecomment-297059274) and may or may not make it's way into a future API. Right now there's no concrete answer whether this will happen, but there are other component API changes being considered.

Since this is a feature request that the team is aware of, and there's nothing actionable right now, I'm going to close this out. Thanks!
