### ISSUE TITLE
Bad cohabitation between a ref and a state in a same component

### ISSUE THREAD

**Issue by Drillan767** [facebook/react#12437]
**Do you want to request a *feature* or report a *bug*?**

I want to report what looks like a bug.

**What is the current behavior?**

For an unknown reason, a `ref` attribute doesn't seem to get well together with a `state`.
For a bit of background, I'm trying to recreate the following [Codepen](https://codepen.io/j_holtslander/pen/KQrWVy?page=1&).

I managed to recreate the "bug", here is the [CodeSandbox link](https://codesandbox.io/s/n767lrv8zj)

For an unknown reason, `this.heightRef` returns null when I want to see it in a console.log(). However, if I remove everything related to `this.state.json` (in the constructor, the `return` or the `<Gmaps>` props, so lines 13, 26, 33 and change the props line 30 by something else), everything works fine and `console.log()`  actually returns the wanted value.

**What is the expected behavior?**

I expect to be able to get my value even though a state has been previously defined and is used

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react@16.2.0, Chrome 65. I don't know if this used to work before because I never had to use it until now.

**Comment by aweary** [comment]
@Drillan767 the problem is that you're only rendering the element which sets the ref when `this.state.json` is non-null. So when your component first renders, the `Landing` component isn't rendered, and the ref is never set. That's why it's undefined in `componentDidMount`.  If you refactor your component to return the fragment even if `json` is `null` you'll see that the ref is set correctly.

The second problem you'll run into is that you're trying to read `clientHeight` from your ref, even though your setting the ref on a component. When you set a ref on a component, that ref will be set to reference the component instance, not the DOM element it renders.

I see that you're trying to forward the ref to the element rendered in `Landing` but React doesn't let components access the `ref` component so this doesn't work. If you want to forward the ref you'll have to use a different prop name like `forwardRef`. There's also a new `React.forwardRef` API coming out in 16.3 that solves this. You can read about it here: https://github.com/facebook/react/pull/12346

For more information on refs in general see: https://reactjs.org/docs/refs-and-the-dom.html

Here's a fork of your CodeSandbox with some of the fixes I've outlined here: https://codesandbox.io/s/9zmk9lpm0p

Finally, we use the issue tracker for bug reports and feature requests. If you have a question in the future, please check our community support resources:
https://facebook.github.io/react/community/support.html

Thanks!

**Comment by jquense** [comment]
I'm not gonna lie i stared at that for a while wondering what was wrong...

**Comment by Drillan767** [comment]
Thank you a lot for taking time to answer me, it's a lot clearer now!
