### ISSUE TITLE
Can `create-subpscription` use `react-lifecycles-compat`?

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/react#12489]
I would like to use `create-subscription` to remove `componentWillReceiveProps` usage in [`react-komposer` library](https://github.com/storybooks/react-komposer/blob/master/src/compose.js#L33). Unfortunately, `create-subscription` has `react@16.3` as peer dependency, as it uses `getDerivedStateFromProps`. I wonder if it can use `react-lifecycles-compat` and specify a wider range as react peer dependency. Ideally, we'd like to keep supporting React 15 for now.

**Comment by bvaughn** [comment]
Hi @Hypnosphi 😄

I had anticipated `create-subscription` being used primarily by application code. I assumed library authors would either fork it or manually implement the subscription techniques described [here](https://gist.github.com/bvaughn/d569177d70b50b58bff69c3c4a5353f3) within their libraries since that would offer finer-grained control. Since your library seems to be specifically aimed at subscriptions, I wonder if this is an option you've considered?

That being said, the idea of some library code using `create-subscription` does not seem unreasonable.

It would complicate the release process slightly, and roughly double the size of the package (although it's not _that_ big). The thing that makes me _slightly_ uneasy about this though, is that it would limit our options for future versions of `create-subscription` (that may want to make use of newer React features that might not be polyfillable).

Maybe for now, you could fork `create-subscription`- (relax the peer dependency, pull in `react-lifecycles-compat`, etc.)- and see how that goes? We can keep an eye on this and direct people to your fork. If enough people request this, then maybe we'll make the change to the main package as well.

**Comment by Hypnosphi** [comment]
Ok I think I got the idea
