### ISSUE TITLE
Add isStatelessFunctionComponent to ReactIs package.

### ISSUE THREAD

**Issue by zheeeng** [facebook/react#12566]
**Do you want to request a *feature* or report a *bug*?**

I want to request a feature.

**What is the current behavior?**

No such an API.

**What is the expected behavior?**

I'm writing a HOC which could forward ref to the wrapped component. According to the React specification, 'ref' is not allowed to be given to a stateless function component. Need an API to tells whether a component is SFC.

Of course, we can add the forwarded ref to a component without check whether it is an SFC, just leave the runtime error, but In typescript language, we can not prevent static analysis warnings. Wish some util API to solve this problem and contribute to the component type narrowing.

New APIs suggestion: 
1. ReactIs.isStatelessFunctionComponent
2. ReactIs.isClassComponent

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React & ReactIs: 16.3.4

**Comment by sebmarkbage** [comment]
Brand checking is generally bad practice and this is going to mess with wrapping. It is a useful property not tell which one it is since it allows wrapping in the first place.

Instead, you can use the new forwardRef API.

```js
MyHoC = function(WrappedComponent) {
  return forwardRef((props, ref) => {
    ...
    return <WrappedComponent ref={ref} />;
  };
};
```

The nice part of this is that it is now up to the consumer of the HoC about how they use it. They can't put a ref on it if it is a functional component and they can if it is a class component. Just like normal.

**Comment by CBDB1LOVE** [comment]
Bug

**Comment by zheeeng** [comment]
@sebmarkbage In TypeScript language, the HOC receive a React.ComponentType<P> which is union of React.ComponentClass<P> and React.StatelessComponent<P>. The latter type doesn't accept 'ref' as its prop.  React.forwardRef doesn't contribute to problem-solving. At present, a workaround is using duck-type checking.
