### ISSUE TITLE
[Question]: Unknown DOM attributes with boolean values

### ISSUE THREAD

**Issue by bishwei** [facebook/react#12649]
**Do you want to request a *feature* or report a *bug*?**
Neither - question

**What is the current behavior?**
Currently, it seems that unknown DOM attributes with boolean values are not passed through, with the exception of data attributes and aria attributes.   Based on the [docs](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html) and looking through the code [here](https://github.com/facebook/react/blob/280acbcb713fe0751c6230b94efb45376eb4af67/packages/react-dom/src/shared/DOMProperty.js#L133) it wasn't 100% clear to me whether this was intentional or a bug. 

I came across this because we're currently server rendering some pages which have `amp` attributes on them.  In React 15.x we were using `injectDOMPropertyConfig` to make this work, so I expected that deleting that would just work.  However, since a lot of these attributes don't have an actual value set and are unknown, they're not being passed through. 

Happy to open a PR to either update the docs or fix this if it is actually a bug, but wanted to verify first.

**Repro**
https://codesandbox.io/s/71624oy286

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.x

**Comment by gaearon** [comment]
The blog post has some details here: https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html#changes-in-detail

It mentions unknown booleans are intentionally *not* passed through. This is because we don't know how to handle them: in some cases people want to leave `"false"` in the DOM and in other cases they want `false` to remove the attribute.

If you want an unknown attribute to appear with a value in the DOM, specify it as a string. For example `amp="true"` or `amp=""`.
