### ISSUE TITLE
Having a context provider as root element causes `renderToString` to omit `data-reactroot` from output

### ISSUE THREAD

**Issue by salzhrani** [facebook/react#12651]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
`data-reactroot` is missing from the generated string, causing existing valid dom to be cleared
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/829oxp48n2

**What is the expected behavior?**
the markup of the root element should have `data-reactroot` but it is missing

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.3.2, not sure

**Comment by gaearon** [comment]
While technically this *is* a bug, using `render()` to hydrate markup is deprecated and won't work in React 17.

Instead, use `hydrate()` to explicitly tell React to hydrate existing HTML. Then it won't depend on whether `data-reactroot` exists or not.

**Comment by gaearon** [comment]
Here is a working example: https://codesandbox.io/s/k0qny27rm5

**Comment by gaearon** [comment]
I don't think we have a neat way of fixing this.

If we have something like `<Provider><div /><p /></Provider>` then we'd put `data-reactroot` on the `<div>`, but only after we reach `<p>` we know that we shouldn't have done that (because there is no single root).

So effectively we can't emit any markup until we know whether it's the only root or not (and we can't know if a subsequent child produces a root or not until we've rendered it deeply).

Maybe there's some other heuristic we could use but I think it would be equally confusing and produce more edge cases. So I'll close this. The suggested migration path is to use `ReactDOM.hydrate()` which completely sidesteps the problem because it doesn't rely on the `data-reactroot` attribute.
