### ISSUE TITLE
Best practice for a meaningful componentStack in production?

### ISSUE THREAD

**Issue by morloy** [facebook/react#12757]
Using Sentry for bug reporting in our production build we often encounter a `componentStack` like:
```
    in b
    in li
    in ul
    in v
    in div
    in div
    in i
    in div
    in Unknown
    in t…
```

Of course, this doesn’t help to locate the problem at all. So I’m wondering, what’s the best practice to get usable information from ErrorBoundaries and the componentStack.
The following options seem to be available:
* Set `mangle: false` in uglify (increases bundle size, but works)
* Set `displayName` manually for all components (usually not feasible)
* Use a [babel plugin](https://github.com/opbeat/babel-plugin-add-react-displayname) (somehow misses the majority of components for me)
* Write a tool, that resolves the names using sourcemaps

I’m curious to hear, what most people are using. For me, only the first option works well, but it doesn’t feel like a very elegant solution.

**Comment by gaearon** [comment]
`mangle: false` sounds like enabling a really bad user experience. I strongly recommend against doing it.

Even a Babel plugin that automatically adds `displayName` would be much better than just disabling mangling. If it didn't work for me, I would look at its tests, and see how the code it's expecting is different from my code. And maybe even send a fix.

At FB we currently include filenames in `displayName` but it's only because we (inefficiently) currently have module names as strings in production. When we fix this, we'll probably change them to IDs, and then write some tool that matches IDs back to readable names.

**Comment by morloy** [comment]
I haven‘t measured the size, but I think it went up from 600 to 700kb, which I guess is all right for any non-FB scale app.
Sounds good to keep parsing time in mind, as well. Right now, meaningful bug reports are more critical than fast page loads. But for the future switching to a babel plugin sounds like a good solution, unless sourcemaps will be supported by the component stack.
