### ISSUE TITLE
defaultChecked prop sets only checked attribute

### ISSUE THREAD

**Issue by klintmane** [facebook/react#12765]
#### Type
`inconsistency` for common use cases.
`bug` for projects relying on correct DOM emissions.

#### Description
It's unclear to me if the following is a known issue or not.
Take in consideration the snippet below:
```jsx
<input type="checkbox" defaultChecked={true} />
```
#### Current Behavior
Setting the `defaultValue` prop on inputs of other types sets both the `value` and `defaultValue` attribute on the DOM element.

When setting the `defaultChecked` prop on inputs of type `checkbox` only the `checked` attribute is correctly set, leaving the `defaultChecked` attribute unchanged.

#### Expected Behaviour
Like mentioned above, the expected behavior would be for the `defaultChecked` prop to set both the `checked` and `defaultChecked` attributes on the corresponding DOM node (like it's the case with the `defaultValue` prop).

**Comment by Checkson** [comment]
I also found the same problem, I am now very distressed, ask how to solve？

**Comment by nhunzaker** [comment]
This does appear to be a bug: https://codesandbox.io/s/1yxpnvknqj

The "checked" attribute is not initially set on the input:

<img width="244" alt="screen shot 2018-06-25 at 8 42 36 am" src="https://user-images.githubusercontent.com/590904/41850747-ba4dfc04-7853-11e8-891d-59bf199fae88.png">

It looks like this has been a bug since 15.0.0. I think we need to add/remove the checked attribute in the post-mount wrapper:
https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOMFiberInput.js#L245-L246

**Comment by nhunzaker** [comment]
Fixed by https://github.com/facebook/react/pull/13114
