### ISSUE TITLE
this.state doesn't  get the current state properly

### ISSUE THREAD

**Issue by MoamenMohamed** [facebook/react#12774]
Related to this issue 
https://github.com/dmtrKovalenko/material-ui-pickers/issues/396#issuecomment-387972773

I found a work around by checking the state out of the onChange. But i can't figure out why it behaves like that in the first place.

Example:
https://codesandbox.io/s/2zrx49zwjj

**Comment by gaearon** [comment]
State changes are put in a queue in React. We don’t re-render immediately because more than one component may call `setState` during an event handler. If first `Child` calls `setState` and then its `Parent` calls `setState`, it would be very wasteful to start re-rendering the child, only to do this work again after parent re-renders. So instead React lets you call `setState` in event handlers, and only applies it as it exits the browser event handler (knowing there are no more `setState` calls to handle).

Hope this helps.

**Comment by gaearon** [comment]
Also, `this.state` *does* get the current state in React. It gets the *current renderered* state.

You’re right it doesn’t give you the pending state, but as I explained above, it’s intentional.

**Comment by MoamenMohamed** [comment]
Thanks a lot for the great explanation.
