### ISSUE TITLE
const { id } = options; error on installing reactjs

### ISSUE THREAD

**Issue by ajiejot** [facebook/react#12855]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** i can't run reactjs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** latest version

node version = v4.4.6
npm version = v2.15.5

![image](https://user-images.githubusercontent.com/36364052/40233602-3d0ddf4c-5ad6-11e8-99e0-b7d0df76c005.png)

All my codes can be found here: https://www.tutorialspoint.com/reactjs/reactjs_environment_setup.htm
I just followed the tutorial

**Comment by nmain** [comment]
You'll need a newer version of node, at least 6.x+, to run that code.

**Comment by gaearon** [comment]
I don't recommend following this tutorial because it doesn't specify any versions (so it will get broken at some point, maybe it already is).

Follow suggested installation steps on our website instead:

https://reactjs.org/docs/try-react.html

or

https://reactjs.org/docs/add-react-to-a-new-app.html

or

https://reactjs.org/docs/add-react-to-an-existing-app.html
