### ISSUE TITLE
Feature: need an error message when state modified because of misuse of spread operator

### ISSUE THREAD

**Issue by arnaudambro** [facebook/react#12854]
**Do you want to request a *feature* or report a *bug*?**
*Feature*

**What is the current behavior?**
See that fiddle : https://jsfiddle.net/Luktwrdm/
Click on the cities. I didn't do any `this.setState()`, but I modified directly the state without knowing it because of a [misuse of the spread operator from my side](https://stackoverflow.com/questions/50391768/a-copy-of-an-array-with-spread-operator-modifies-the-copied-array-how-come). 
Thus no error came to me telling me I was modifying the state directly.

**What is the expected behavior?**
An error like `Do not mutate state directly. Use setState()`, or even maybe a lesson about the spread operator at the same time :)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I use the last version of React, and I expect to have the same in all the previous versions of React.

**Comment by GaryPWhite** [comment]
the fiddle here is a Hello World. Could you post an updated link? :)

**Comment by gaearon** [comment]
React can't warn about a deep mutation in state because there's no way for React to check it. It is also technically allowed to mutate state deeply as an escape hatch. You can use packages like `deep-freeze` to enforce immutability in development, or any of the many immutability helper libraries (e.g. `immer`, `updeep`, `immutability-helper`) that do the updating for you.
