### ISSUE TITLE
Synthetic (keyboard) events don't implement the .code property

### ISSUE THREAD

**Issue by bsmith-cycorp** [facebook/react#12902]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`<event>.code` is undefined

**What is the expected behavior?**
`.code` is a very useful part of the KeyboardEvent spec: https://www.w3.org/TR/uievents/#dom-keyboardevent-code

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am on React 16.3, but I saw no mention of this in today's 16.4 changelog.

**Comment by aweary** [comment]
Hey @bsmith-cycorp! As of now the UI Events spec that you linked is currently a working draft, which means that it is not officially recommended by W3C yet. Since it's a new addition to the suite of event specs, it also [doesn't have great browser support yet](https://caniuse.com/#feat=keyboardevent-code).

This means we'd have to polyfill it, which I don't think we could. We very rarely add support for events or event properties that we can't provide consistently. For now you can try using `event.nativeEvent.code`, which should work in browsers that support it.

**Comment by bsmith-cycorp** [comment]
I did not know about `.nativeEvent`. That's a good escape hatch. Thanks!
