### ISSUE TITLE
Possibly include a field in package.json to indicate dist file?

### ISSUE THREAD

**Issue by tmcw** [facebook/react#12928]
**Do you want to request a *feature* or report a *bug*?**

A feature!

**What is the current behavior?**

Per https://github.com/facebook/react/pull/10759, the react and react-dom don't include an `unpkg` field, but their npm packages do include `dist` directories with production and development UMD builds. The prior discussion concluded that, because the development and production builds are very different and it's not clear whether the unpkg default should be dev or production, React doesn't include a field at all and leaves it up to the consumers.

My bias is: I'm working on [observable](https://beta.observablehq.com/), which uses [d3-require](https://github.com/d3/d3-require) to include modules from `unpkg`. People type `require('d3')` and it resolves to `https://unpkg.com/d3` which then redirects to the d3 web-compatible distribution.

People _can_ type `require('react/umd/react.development.js')`, but it's hard to figure that one out - they have to look at unpkg itself and hunt around for those UMDs. So we're considering:

- Hardcoding workarounds for react & react-dom, because they're very popular modules and few people are figuring out how to require them.
- Creating a react wrapper that sets an `unpkg` field and re-points to react
- Submitting another PR to react re-proposing a default export

**What is the expected behavior?**

React and ReactDOM would provide - if not a default - some indication of where their `dist` files and what their meanings are.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

All?

---

Thanks for all y'all's work on React, it's excellent!

**Comment by gaearon** [comment]
I’m not sure how much more explicit it could get then module format as folder name? “cjs” folder contains CommonJS builds. “umd” folder contains UMD builds. Eventually we’ll add “esm” folder with ES Modules builds. No plans to change this scheme so please feel free to hardcore and choose appropriate dev or prod version depending on the environment 🙂

Does that help?

**Comment by mbostock** [comment]
Adding to this: people often wish to use libraries that depend on React, such as [Semiotic](https://github.com/emeeks/semiotic), not just use React directly. If you load Semiotic via AMD, the library will `require("react")`, and the AMD implementation thus needs to know where to find React. We’d like this to work out of the box, and to do that, we need some convention for library authors to declare where their browser-compatible UMD/AMD bundles live.

[d3-require](https://github.com/d3/d3-require)’s implementation first loads Semotic’s package.json (by default from unpkg), determines the acceptable semver range for React, then loads React’s package.json to find an browser- and AMD-compatible entry point. Currently that list is:

* `unpkg`
* `browser`
* `main`
* index.js

We don’t currently make any assumptions about where a UMD/AMD/CJS bundle resides within the repository, because that seems to vary widely; we’d rather use an entry point in the package.json.

**Comment by gaearon** [comment]
Again, there is no single file to resolve to. There is a development and a production version. Neither can be a reasonable “default”. This decision needs to always be explicit.

I don’t see us doing something to support AMD better specifically. It’s not worth investing effort into it at this point. I understand you may have legacy systems that depend on it but it lost any sort of relevance outside such systems.

**Comment by mbostock** [comment]
If you don’t want to pick one (most packages default to a minified bundle intended for production), how about declaring both entry points in the package.json? Then software that consumes your library could know where your bundles are published, rather than needing to make assumptions about the directory structure.

(It would likewise be great if React included an ES module entry point in the package.json, too. The standard one would be `module`.)

**Comment by gaearon** [comment]
>If you don’t want to pick one (most packages default to a minified bundle intended for production), how about declaring both entry points in the package.json? Then software that consumes your library could know where your bundles are published, rather than needing to make assumptions about the directory structure.

I don't think using an array where tools expect a single string would be very tool-friendly. If anything it's more likely to break tools.

>(It would likewise be great if React included an ES module entry point in the package.json, too. The standard one would be module.)

Sure, there's a few issues tracking this.
