### ISSUE TITLE
Signaling reusable instances

### ISSUE THREAD

**Issue by brigand** [facebook/react#12963]
**Do you want to request a *feature* or report a *bug*?**

Feature

---

There's a common case of having a list of items, keyed by some id, and items can be added/removed over time. For example, say we have a list of users and a button to refresh the list with new data from the server. Here, `User` is a simple function component.

```jsx
users.map((user) => (
  <User key={user.id} data={user} />
)
```

Say this produces the following User elements:

```
key: 1000, data: { name: 'foo' }
key: 1001, data: { name: 'bar' }
key: 1002, data: { name: 'baz' }
```

Later we get the new user list, and these are the resulting elements:

```
key: 1003, data: { name: 'quux' }
key: 1002, data: { name: 'baz' }
key: 1001, data: { name: 'bar' }
```

The operations are:

- remove 1000, destroy instance and dom nodes
- move 1002, update
- create 1003, with instance and dom nodes

Would an option to tell React that it can reuse the instances and dom nodes make sense?

From the list diff, React has this information (as I understand it):

- remove at key: 1000, type: User, index: 0
- create at key: 1003, type: User. index: 0

If we signaled to React that it can reuse elements, and since the 'type' is the same, it could reduce these operations to updating the identity of the underlying instance (key: 1000 -> key: 1003) and then update the instance normally. It could also require a move, but it doesn't here.

When used, it reduces the combined create/destroy operations of instances and dom nodes from `create + destroy` to `Math.abs(create - destroy)`. 

Of course, this has to be opt-in behavior because some components won't clear their internal state, and some DOM nodes can hold uncontrolled state. Also in some cases this could be slower (but I'd wager this is rare).

The syntax is secondary; I mostly want to hear what's thought about the idea of explicitly permitting React to reuse instances, but this is the simplest idea I have.

```jsx
<React.Reusable>
  {users.map(...)}
</React.Reusable>
```

---

**Why do this in core?**

I can't think of a reasonable way to do this in user space, and the less reasonable ways require duplicating the effort of diffing the list.

It's just allowing React to simplify the operations it intends to perform.

**Why do this at all?**

It provides another performance hook for React code, which people can attempt to apply while optimizing their react and react-native apps, if it makes sense in their situation.

**Comment by aweary** [comment]
> Would an option to tell React that it can reuse the instances and dom nodes make sense?

Has this been a performance bottleneck for you? It's been my understanding that this isn't typically a noticeable performance problem.

Generally speaking, performance optimizations should be internal and _implicit_, without imposing additional cognitive load on the user. APIs like `shouldComponentUpdate` and `PureComponent` are the current exceptions, but exists to solve a common and significant performance problems. Even then, they're still escape hatches.

It's not clear to me that this is a significant problem with [React's current reconciliation algorithm](https://reactjs.org/docs/reconciliation.html), which already does significant memoization to avoid work like this.

Putting that aside, letting users control when instances are reused can be problematic. Whether an instance is reused or recreated is an implementation detail that shouldn't leak into user code, and most users probably won't know what it means for a component to be "reusable" either. It also introduces more non-determinism, since you might not know if the part of app you're working on now is marked as "reusable" or not.

If you'd like to elaborate on your proposal I recommend you [open an RFC](https://github.com/reactjs/rfcs), where proposals like this belong.

Thanks!
