### ISSUE TITLE
Prop with circular reference set to state, mutates the prop.

### ISSUE THREAD

**Issue by TomJKlug** [facebook/react#13057]
**Do you want to request a *feature* or report a *bug*?**
*Bug* maybe?
**What is the current behavior?**
If you pass a prop that has circular references and set it to state, when changing state, you mutate the prop.

 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

To Reproduce pass any Tree, with circular references as a prop to the component, then set that to a state variable, and manipulate the state variable, it will in turn manipulate the prop 

**What is the expected behavior?**

I believe props are supposed to be immutable.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
React doesn't do anything special to clone your object or otherwise prevent you from mutating state.
There's no one best way to do it, so this is up to you to decide how to handle it.

If you find it difficult to update nested immutable objects, libraries like [immer](https://github.com/mweststrate/immer) can help.
