### ISSUE TITLE
getDerivedStateFromProps shoud be renamed to getStateFromProps

### ISSUE THREAD

**Issue by liamwang** [facebook/react#13050]
Thanks to this clarification:

[https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops)

Before reading that, I truely thought `getDerivedStateFromProps` was only called if the component was re-rendered by its parent. It's easy to misunderstand.

If `getDerivedStateFromProps` is also executed after `setState`, then the name should be named as `getStateFromProps`. 

In addition, can `getDerivedStateFromProps` and `getStateFromProps` both exist?

**getStateFromProps:** Called every time a component is rendered, regardless of the cause of the update.
**getDerivedStateFromProps:** Only called if the component was re-rendered by its parent.

**Comment by gaearon** [comment]
Please read this blog post too:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

If you think you need this, your code probably already has bugs in it. Any implementation of `getDerivedStateFromProps` that isn't buggy wouldn't change its behavior in React 16.4.

You can learn more about the bugs that occur when you rely on "parent re-render" specifically (with examples) in this section: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#common-bugs-when-using-derived-state

You can learn more about the preferred solutions (most of which don't involve `getDerivedStateFromProps` at all) here: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#preferred-solutions

We don't plan to change the method name. I think the main misunderstanding here is that you attempt to **copy** props from the parent instead of **deriving** them from a props change. Again, the blog post has more details so I hope you'll find it helpful!

Remember that **in most cases you don't need to use `getDerivedStateFromProps` at all**. It exists for rare use cases, and hopefully the recommendations above will guide you to simpler solutions.

**Comment by liamwang** [comment]
I've learned a lot from those articles, related issues and your nice answers.

Thank you.
