### ISSUE TITLE
Do functional components behave like React.Component or React.PureComponent?

### ISSUE THREAD

**Issue by davidbarratt** [facebook/react#13060]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure. :)

**What is the current behavior?**
The docs say that a functional component has the same behavior as [React.Component](https://reactjs.org/docs/react-component.html)
https://reactjs.org/docs/components-and-props.html#functional-and-class-components
shouldn't they have the same behavior as [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent)?
 
**What is the expected behavior?**
I was under the impression that a functional component _already_ has the same behavior as [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent), if that is the case, then the docs should be updated, if that is not the case then one of two things should happen:
- Functional components _should_ have the same behavior as [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent)
- The docs should recommend using [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent) instead of functional components since the performance would be better.

I suppose I do not understand how a functional component could **not** be _pure_, unless you were doing some sort of anti-pattern.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16+

**Comment by gaearon** [comment]
Functional components do not have shallow equality checks by default.

It would not necessarily be "faster" to add shallow equality checks to them. In fact it can make the app slower because even for components that *always* have shallowly different props, you would still perform useless shallow equality checks. This would also make it impossible to convert commonly used components to be functional in apps that rely on mutation.

I'm afraid the cause of the confusion is the word "pure". Functional components are "pure" in the Computer Science sense of the word, but `PureComponent` was named this way because it superseded `PureRenderMixin` which performed shallow equality checks. They're not the same thing. Perhaps `MemoizedComponent` would've been a better name, but it's too hard to spell correctly so we went with `PureComponent`.

**Comment by davidbarratt** [comment]
Thanks for the explanation!
