### ISSUE TITLE
Text input is doubled on any new character (Japanese language)

### ISSUE THREAD

**Issue by YAtOff** [facebook/react#13066]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
This happens in Safari 11.11 on MacOS 10.12.6 with Hiragana and Katakana keyboard layout.
When text is entered in textarea, on any new character the whole current text plus the new
character is appended to the text.

For example:
I enter 12345
The value or the textarea is:
112123123412345

Example: https://codesandbox.io/s/7z8jnxvok1

**Comment by danburzo** [comment]
You're manually (re-)setting the value of the textarea on each change (via the `componentDidUpdate` method in the `Text` component), and this is causing the issue. Doing so can create unexpected results if someone's using IMEs to compose characters in non-Latin scripts.

**Comment by nmain** [comment]
A good rule of thumb to remember with `ref`s is that you need to choose whether to control something through React or through manual DOM manipulation, but not both.  Since your `<textarea>` VDOM element has a `value` provided through props, the DOM element's value property is controlled by React, and so you should not manually change it.

**Comment by YAtOff** [comment]
I see it's my fault.
I'm sorry for taking your time and thanks for the advice.
