### ISSUE TITLE
Navigating to a legacy PHP page outside of React but inside the same domain as the React app

### ISSUE THREAD

**Issue by wuno** [facebook/react#13099]
I have components which I route to using react router dom. I am deploying this application to a existing PHP application and created some links inside of the application that point to the same domain but at a path where the external PHP application lives. When a link is clicked the navigation takes the user to a page that is obviously still inside of the React application. 

I would assume that I should be able to navigate outside of the React application even though I am on the same domain as it so I assume React removing my ability to do so is a bug. 

## Version
"react": "^16.1.0",
"react-router-dom": "^4.2.2",

## Test Case
I am deploying a react application to be part of a existing website. In some cases I need to navigate my users outside of the react application but keep them inside of the domain. 

For example if I am using React Router Dom in my app and I try to do this, 

```
<a role="button" target="_blank" href="https://www.example.com/login.php//">
Login
</a>

```
or this, 

```
<a role="button" onClick={() => (window.location = 'https://www.example.com/financial-products.html/')}>
 Financial Products
</a>
```

## Steps to reproduce

Create react project, and create a link that navigates to a component in the React application. Then make a link that navigates to a php page outside of the react application but in the same domain. 

## Expected Behavior

The link should navigate to the correct page which is not inside of the React application.

## Actual Behavior

The app navigates to a blank react page only showing the header and footer. In other words it will not leave the react application.

**Comment by gaearon** [comment]
React itself doesn’t do anything related to routing so this cannot be a bug in React itself.

My best guess is that something’s wrong with how you set up the client-side routing so that it “takes over” the navigation. But it’s hard to guess what exactly without seeing a **complete** reproducing example.

If you provide one I might be able to help, but probably not otherwise. Feel free to check out these resources for help too: https://reactjs.org/community/support.html
