### ISSUE TITLE
Why the Select HTML Element's Event Target Type is select-one

### ISSUE THREAD

**Issue by edwardchanjw** [facebook/react#13135]
**What is the current behavior?**
Event Target Type is _select-one_ is intended? Why the naming convention?

**What is the expected behavior?**
HTML's Type Convention whenever possible? If HTML is not good follow some other convention like XAML, GTK, and others. Not really familiar on GUI Ecosystem history, good to have constructive opinion how one library work better in this convention better than other, not every library is perfect in convention and specification. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.3.2. The demo code is in [codesandbox](https://codesandbox.io/s/o7ov511kz)

**Comment by nhunzaker** [comment]
Interesting! It looks like this is a standard browser behavior (at least in Firefox, Safari, and Chrome):

```javascript
let select = document.createElement('select')
console.log(select.type) // 'select-one'

let multiselect = document.createElement('select')
multiselect.multiple = true
console.log(multiselect.type) // 'select-multiple'
```

I couldn't find my on this, but I did uncover something over at W3C:
https://www.w3.org/2003/01/dom2-javadoc/org/w3c/dom/html2/HTMLSelectElement.html#getType__

> The type of this form control. This is the string "select-multiple" when the multiple attribute is true and the string "select-one" when false. 

I don't know much about your use case, but if you are trying to access the event type, you could use `event.type`, or if you wanted to know the tag type, you could use `event.target.tagName`.

I'm going to close this out because I don't think there is an issue with React, but I hope this helps!
