### ISSUE TITLE
Test fails when render method is NOT an arrow function

### ISSUE THREAD

**Issue by fhadsheikh** [facebook/react#13182]
Versions

```
react: 16.4.1
react-test-renderer: 16.4.1
@babel/core: ^7.0.0-beta.52
babel-jest": "^23.2.0,
```

Getting `TypeError: this._instance.render is not a function` if running a test on a component that isn't using an arrow function for the render method

### Fails
```
import React, { Component } from 'react';
import { Text } from 'react-native';
import ShallowRenderer from 'react-test-renderer/shallow';

class TestComponent extends Component {
    render() {
        return <Text>Hello</Text>;
    }
}

describe('ConsultMessages', () => {
    let props;
    let renderer;
    const render = () => {
        if (! renderer) {
            renderer = new ShallowRenderer();
            renderer.render(<TestComponent {...props} />);
        }
        return renderer;
    };

    it('renders without crashing', () => {
        const rendered = render().getRenderOutput();
        expect(rendered).toBeTruthy();
    });
});
```

### Passes
```
import React, { Component } from 'react';
import { Text } from 'react-native';
import ShallowRenderer from 'react-test-renderer/shallow';

class TestComponent extends Component {
    render = () => <Text>Hello</Text>
}

describe('ConsultMessages', () => {
    let props;
    let renderer;
    const render = () => {
        if (! renderer) {
            renderer = new ShallowRenderer();
            renderer.render(<TestComponent {...props} />);
        }
        return renderer;
    };

    it('renders without crashing', () => {
        const rendered = render().getRenderOutput();
        expect(rendered).toBeTruthy();
    });
});
```

## Reproducible repo
[Link here](https://github.com/getmaple/TestApp56)

**Comment by jfo84** [comment]
The code in the two examples is identical

**Comment by TryingToImprove** [comment]
@jfo84 The render method on the class are different; https://www.diffchecker.com/nryPAwTV

**Comment by jfo84** [comment]
Ah I see. If it's not related to [this](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/) then I'm not sure

**Comment by fhadsheikh** [comment]
@jfo84 It works fine if I use arrow functions. Doesn't that mean babel-plugin-transform-class-properties is working. 

I only get the error when running tests. The app runs fine otherwise.

```No `render` method found on the returned component instance: you may have forgotten to define `render`.```

**Comment by aweary** [comment]
@fhadsheikh could you create a repo that we can clone to reproduce the issue? Setting up a repo with all the same dependencies is time consuming for us, so we'll be able to help you quicker if we don't have to 🙂

In the meantime can you share your `react-native` version and the full stack trace of the error?

**Comment by fhadsheikh** [comment]
Hi @aweary! I've added the RN version, stack trace and a link to a repo to reproduce bug to the issue

thanks for your help!

**Comment by jfo84** [comment]
Whatever the issue is, it likely isn't React. When the shallow renderer's `render` method receives the element, initializing it with `new` [here](https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactShallowRenderer.js#L86) returns an instance without a `render` method defined

**Comment by quizzy** [comment]
Hi, I'm running a `react-native` project and after doing all the `babel 7` upgrades after updating `react-native` to `0.56` I've run into the same issue as @aweary. 
I just tried converting the component of one of my failing tests' `render` method to an arrow function and as he suggested, fixed the issue.

**Comment by jpaas** [comment]
Also running into this issue on a react native project, but not when running on iOS or Android, but rather when running on web using `react-native-web`

**Comment by TikiTDO** [comment]
This may be related to babel/babel#8392

**Comment by gaearon** [comment]
This is not a React issue.

I see that removing `babel-jest` from dependencies, and then removing `jest` configuration section and `babel.config.js` fixes it. So this must be either a Jest or a Babel issue.

Most likely the advice in https://github.com/babel/babel/issues/8392#issuecomment-408263920 will be relevant to you.

**Comment by gaearon** [comment]
I looked at the reproducing example in https://github.com/getmaple/TestApp56 again.
I was able to fix it by running:

* `yarn remove @babel/core`
* `yarn test --no-cache`

In particular, the issue was that the project mistakingly [pulled in](https://github.com/getmaple/TestApp56/blob/31fd40d28e54e704562faa85b2c7941981335a89/yarn.lock#L37) `@babel/core@^7.0.0-beta.52` **which is incompatible** with React Native 0.56 (which [uses](https://github.com/getmaple/TestApp56/blob/31fd40d28e54e704562faa85b2c7941981335a89/yarn.lock#L3467) `@babel/core@7.0.0-beta.47`). The fix was to **remove** the unnecessary (and wrong) top-level `@babel/core` [dependency](https://github.com/getmaple/TestApp56/blob/31fd40d28e54e704562faa85b2c7941981335a89/package.json#L14).

Check your `package.json` for `@babel/core`. If you see it there, remove it. Or at least ensure it's the same version that Metro depends on. Make sure that in your `yarn.lock` you don't see two `@babel/core` with different versions.

Hope this helps!

**Comment by Praveencena88** [comment]
@gaearon  i'm also facing the same issue after updating all the babel, jest & react-native dependencies
