### ISSUE TITLE
The second argument of the getDerivedStateFromProps lifecycle 

### ISSUE THREAD

**Issue by Ssis53** [facebook/react#13258]
Earlier, I find some problem in my react demo. The second argument of the gDSFP behaves like "nextState". In my previous issue #13255 

After get answer, I checked [react documentation](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops), gDSFP has two arguments, which are props and state. But the source code makes me wonder. 

It's like this: 
 
![image](https://user-images.githubusercontent.com/33656230/43120127-af21a718-8f4b-11e8-8ef8-8458e8b7717e.png)

Why is prevState here?

**Comment by Nutcase511** [comment]
good job

**Comment by jquense** [comment]
Not quite sure what the question is here. Both next props and state are passed to gDSFP, what the variables are named in the source isn't all that important :)

For your interest tho, prevState is called that because it's not yet "committed" on the component, it's the current but pending state, but regardless of the name it's the up to date state value
