### ISSUE TITLE
Conditionally rendered inputs pass values to eachother

### ISSUE THREAD

**Issue by AaronGillBraun** [facebook/react#13275]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When you have inputs, if you conditionally swap them out for another input, the value from the first field is passed into the newly rendered input seemingly as a `defaultValue`. It cannot be overridden with custom `defaultValue` prop.

![react-bug](https://user-images.githubusercontent.com/15055317/43267391-d6400bb6-90bb-11e8-964e-35510949cbf1.gif)

It doesn't seem as though changing `defaultValue` affect it at all. Nothing seems to change this behavior besides wrapping the secondarily rendered input in an aditional div tag.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem:**
https://codesandbox.io/s/j2oyow6jky

See fix here: https://codesandbox.io/s/l2rxp94n17

**What is the expected behavior?**
That the newly rendered input in completely independent and is not rendered with the value of the first input.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version: 16.3.2
Have not tested in previous versions.

**Comment by jquense** [comment]
So what's happening here is that react thinks when you swap the components that the inputs at the first position in the div are the same, and reconciles them to each other instead of creating a new one.

In other words the the `code` input is in the same position in the tree as the `email` input as you swap them. React can't tell that those are supposed to be distinct inputs, because they have the same type. So it updates `email` -> `code` and vis versa. 

You can workaround this by given the inputs a distinct `key` prop, which hints to react that they are not the same
