### ISSUE TITLE
[Question] RE: Rendering arrays of components, should these implementations behave the same?

### ISSUE THREAD

**Issue by MrLeebo** [facebook/react#13331]
**Do you want to request a *feature* or report a *bug*?**
Possible bug, though it is likely this is an expected behavior that I'm misinterpreting.

**What is the current behavior?**
Say I have an array of components I'd like to render, but I also want to weave `<hr>` tags between each item. For example:

```jsx
const Delimited = props => (
  props.items.reduce((a, b) => (
    <React.Fragment>
      {a} <hr /> {b}
    </React.Fragment>
  ))
)

<Delimited items={[<One key="one" />, <Two key="two" />, <Three key="three" />]} />
/*
  <One />
  <hr />
  <Two />
  <hr />
  <Three />
*/
```

This works, however if the components in the array have state, **they forget their state when the parent refreshes**. Seems bad.

If I rewrite the **Delimited** component so that it produces the same result by inserting the `<hr>`'s into the array, the items keep their internal state.

```jsx
// Same render as above, and if the items have 
// state it is retained if the parent refreshes.
const Delimited = props => {
  const results = [...props.items]
  for (let i = results.length - 1; i > 0; i--) {
    results.splice(i, 0, <hr />)
  }

  return results
}
```

Adding a `key` prop to `<React.Fragment>` doesn't change the outcome.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem:**
https://codesandbox.io/s/n9158p8j9p

1. First, click on one or more of the Toggle buttons.
2. Click "Add", the toggled buttons should retain their state.
3. Click "Use Reduce", which renders the buttons using `.reduce()`
4. Repeat steps 1 and 2.
5. This time, all of the Toggle buttons forget their state.

<img width="123" alt="screen shot 2018-08-06 at 12 25 45 pm" src="https://user-images.githubusercontent.com/2754163/43731387-f5afe014-9973-11e8-885f-8fc57f83a56b.png">

**Click Add**

<img width="140" alt="screen shot 2018-08-06 at 12 25 54 pm" src="https://user-images.githubusercontent.com/2754163/43731439-22d11a36-9974-11e8-9167-11e66420b30d.png">

**What is the expected behavior?**
It seems like the component are getting re-mounted using `.reduce()`, but updates the existing component when you use the `for` loop. Shouldn't both implementations update the existing component?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
- React 16.4.2
- Chrome 67
- OSX High Sierra

**Comment by gaearon** [comment]
It doesn’t work because the tree structure changes with your `reduce` example. Every time you add another “layer”, nodes move down the tree and since their types don’t match up, React considers them new mounts.

You could fix this by using `reduceRight` and reversing the order but the innermost item would still lose its state because you’re essentially replacing `Toggle` with a `Fragment`.

So yeah, this is not a bug because your two examples aren’t equivalent. In one, you have a flat list, but in another you have a tree where either outermost parent or the innermost child type (depending on which reduce method you use) will change its type on every “add”.
