### ISSUE TITLE
Suspense fixture/demo: page scrolls to top unnecessarily

### ISSUE THREAD

**Issue by sophiebits** [facebook/react#13436]
https://twitter.com/rauchg/status/1030613789425598464

If you open that demo (which lives in this repo’s fixtures folder) on a small screen, tapping one of the rows at the bottom (ex: my name) causes the page to scroll to the top immediately, which means you don’t see the inline loading indicator.

It should scroll to top after the data loads but not before.

**Comment by hamlim** [comment]
Hi Sophie 👋🏼, I wouldn't mind picking up this issue if thats alright.

I did some local debugging and it seems like this [condition here](https://github.com/facebook/react/blob/master/fixtures/unstable-async/suspense/src/components/App.js#L23) should be checking if `this.state.showDetail` has changed and is now true and then scrolling to the top of the page instead of checking if either showDetail changed or currentId changed.

**Comment by sophiebits** [comment]
Sure, send a PR! I guess if the current ID were to change while showDetail is already true then you would want to scroll to top. I guess that’s not possible in the current UI though.

**Comment by hamlim** [comment]
Seems like this issue can be closed now right?
