### ISSUE TITLE
Question on reconciliation

### ISSUE THREAD

**Issue by giorgi-m** [facebook/react#13489]
I think I understood reconciliation in react however there is one thing I would like to clarify.
Let's say on first render, we render:

```
<ul>
  <li>Duke</li> // key 0
  <li>Villanova</li> // key 1
</ul>
```

And on next render

```
<ul>
  <li>Connecticut</li> // key 0
  <li>Duke</li> // key 1
  <li>Villanova</li> // key 2
</ul>
```

If I understood reconciliation correctly on the second render, react will check that **types (e.g. `<li>`) and keys of first two items from first and second render match**, hence it will add only the new item with key 2 to the new output, hence generate following result:

```
<ul>
  <li>Duke</li> // key 0
  <li>Villanova</li> // key 1
  <li>Villanova</li> // key 2
</ul>
```

However I think this is not what react will generate and it seems then there is some issue with my understanding (especially the bold part in the previous paragraph). Can someone explain what I missed in my understanding?

**Comment by gaearon** [comment]
React won't just ignore the node with keys `0` and `1` because their type is the same. React will treat this as an *update* to them.

So resulting DOM operations in your example would be:

* Change text content of li with `0` key to `Connecticut `
* Change text content of li with `1` key to `Duke`
* Add list item with `2` key and a `Villanova` content

But if you specified keys that were stable (which you didn't), then it would prepend the first item without updating the other two. This is why specifying keys is important.

**Comment by giorgi-m** [comment]
@gaearon ok thanks so as I said in previous comment when docs state that react will only update changed attributes, in this case the changed attributes happen to be the child nodes, right?

**Comment by gaearon** [comment]
No, but it will "recurse on children" (which is the section you're looking at). The children in these case are text nodes, which are updated.
