### ISSUE TITLE
Prevent encoding href attribute

### ISSUE THREAD

**Issue by mir3z** [facebook/react#13494]
**Do you want to request a *feature* or report a *bug*?**
Feature/Question

**What is the current behavior?**
React escapes everything inside href attribute. I belive there are cases when it's undesirable.

I'm using `renderToStaticMarkup` to render emails that are being sent by Sengrid. Sendgrid provides a functionality to inject links to autogenerated preferences and unsubscribe pages. It does that by replacing some placeholders within emails with actual URLs. Placeholders looks like that: `<%asm_preferences_raw_url%>`. The problem is the React encodes `<` and `>` and the placeholder becomes `&lt;%asm_group_unsubscribe_raw_url%&gt;`.

I'm wondering if there is a solution for that or am I am doomed to `dangerouslyInserInnerHTML` hack?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/ko4qzq9415

**What is the expected behavior?**

There should be a way (different than `dangrouslyInsertInnerHTML`) to avoid escaping.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Any

**Comment by mir3z** [comment]
> You could solve your issue by using a different placeholder

I don't have any control over 3rd party library placeholders.

> this would only be safe if your output doesn't include any user-created content

It is not user created content.

**Comment by Yurickh** [comment]
Hello, @mir3z. Let me try to clarify gaeron's suggested approach to you.

The output from `renderToStaticMarkup` is a simple string you feed into sendgrid's templating engine, in order to replace your `<%...%>` tags with the variables you want.

The problem at hand is that you need a `<%...%>` tag inside an `href`, which React encodes. 

What you can do to workaround this issue is to use a different tag (like `$%...%$`) in your React code and after running `renderToStaticMarkup` replace it by `<%...%>` **before** feeding it into sendgrid, so it receives the `<%...%>` tags as expected.

So, just to make myself clear:
1. Use `$%...%$` in your react code;
2. Get a string from `renderToStaticMarkup`;
3. Replace instances of `$%...%$` with `<%...%>` in that string;
4. Feed the resulting string to sendgrid.

That way there's no need to change the 3rd party library placeholder :)~

Feel free to correct me if I misunderstood your suggestion as well, @gaearon.

**Comment by gaearon** [comment]
Yep, that's what I suggested. You should totally be able to do that.

**Comment by mir3z** [comment]
Thanks you guys. Now it makes sense.
