### ISSUE TITLE
If I import same component twice,can I ensure that their life cycle functions are different?

### ISSUE THREAD

**Issue by xlhandsome** [facebook/react#13514]
What is the current behavior?

i import the same component twice in father component ,when i change the visible ,the Popover component's   componentWillReceiveProps will execution 2 twice,but i want to keep them Independent

`<Popover
	visible={popTopVisible}
	placement="left"
	keyName="header"
/>
<Popover
	visible={popBotVisible}
	placement="bottom"
	keyName="footer"
/>`

`componentWillReceiveProps(nextProps){
                console.log(nextProps)              **// it will console twice**
       }
}`

What is the expected behavior?
    import the same component and their life cylce functions is Independent,their functions belong to 
    their own.

**Comment by gaearon** [comment]
React re-renders all children when you call `setState` above. This shouldn't be a problem — if your code breaks because of it your code is brittle in other ways too. It's hard to say more without understanding why this is an issue. Regardless, it's not a bug so it's better suited to discussion forums: https://reactjs.org/community/support.html
