### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by charbelsako** [facebook/react#13527]
**Do you want to request a *feature* or report a *bug*?**
  *bug*
**What is the current behavior?**
  - The app doesn't render at all

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
[Link to broken App](https://react-client-panel-1e6bd.firebaseapp.com/)
**What is the expected behavior?**
  - The app should render

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react v16
chrome

*Notes* I am using firebase. my public directory is `build`. I have had scenarios where It just worked when I wrote `./build/`. I'm frustrated please help.

**Comment by charbelsako** [comment]
It appears that my main.xxx.js file is served as html. What to do.

**Comment by Axnyff** [comment]
Hi, could it be causd by a service worker serving an old version of your html and you updated your js assets ? Does it happens if you unregister service workers ?

**Comment by charbelsako** [comment]
I uncommented the service worker function. Nothing changed.
I did fix it. Which isn't really a fix. I made a new firebase project. SAME CODE and IT WORKED.
only had to fix the redux devtools to make it render on mobile.

You could be right by the way

**Comment by cryptoPickle** [comment]
I have faced the issue before and i realize that it was misconfigured webpack problem. When you get the error please double check the network request of bundle, that has correct url. 

In my case when i tried to diffrent route, request has been made to localhost:400/diffrentroute/bundle, instead of localhost:400/bundle 

If it is your case as well, please double check the webpack's publicPath option.

Hope it will fix your issue.

**Comment by Axnyff** [comment]
@charbelsako Commenting the service worker code won't change anything. The problem is that a service worker is registered in your browser which causes this problem.

However, you won't have this problem anymore as you stopped registering service workers.

To properly register a service workers, you can probably do it in the devtools of your browser ( in Chrome it's in the application tab, I don't know for other browsers)

**Comment by charbelsako** [comment]
So sorry to bother how do you unregister the service worker. I went back to registering the worker and It works

**Comment by Axnyff** [comment]
I know in chrome but this should be doable in other devtools:

Open your dev tools go in Application Tab > Service worker

There's a unregister option:
![image](https://user-images.githubusercontent.com/9498142/44947161-49268500-ae09-11e8-8460-5f05d742443a.png)

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by charbelsako** [comment]
Thanks @gaearon It's fixed for now. Do they have a particular fix for this
