### ISSUE TITLE
Missing UMD variant of react.profiling.min.js

### ISSUE THREAD

**Issue by realityforge** [facebook/react#13634]
The 16.5.0 package released to unpkg currently has the production/profiling variant present for cjs builds but there is no equivalent for umd builds. 

i.e. There is the file https://unpkg.com/react@16.5.0/cjs/react.profiling.min.js but there is no https://unpkg.com/react@16.5.0/umd/react.profiling.min.js

It would be great if a future release had the profiling variant packaged as umd as well.

Also thanks for the awesome framework!

**Comment by gaearon** [comment]
AFAIK it might have been a mistake to provide the profiling build of `react` because it doesn't actually differ from the production build.

Only `ReactDOM` (and `ScheduleTracking` if you use that) need to have a profiling mode.

@bvaughn Please correct if I'm wrong? We should fix it one way or another though.

**Comment by bvaughn** [comment]
I think `cjs/react.profiling.min.js` is an artifact of the way we were initially exposing the scheduling/tracing API through the SECRET object on React. You're right, Dan, that we can safely remove that from `react` because it doesn't do anything.

That being said, we also don't have a `react-dom` production+profiling UMD variant because UMD profiling support seemed like an edge case. If we want to support it, we'll need to add a new `UMD_PROFILING` build type and plug it into the `react-dom` bundle.

**Comment by realityforge** [comment]
Thanks for the clarification. We would be one of the edge cases that use UMD production profiling. Glad to see it make it in.

Thanks again!

**Comment by bvaughn** [comment]
👍
