### ISSUE TITLE
Element attributes be removed silently in frameset tag

### ISSUE THREAD

**Issue by LeonDWong** [facebook/react#13645]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In some historical reason, i am still using obsolete tag `frameset` in my project. And when i render my component which includes `frameset` tag in react, some attributes are ignored, like `rows`, `cols`.
Could anyone tell me why and how to solve it by no hacking way? Thx.

**input**
```javascript
export default class obsoleteElment extends React.Component {

  render() {
    return (
      <html>
      <head>
        <meta httpEquiv="content-type" content="text/html; charset=UTF-8" />
          <title>old page</title>
      </head>
      <frameset id="frame-container" rows='60,*' frameBorder="0" border="0"  cols="180,11,*">
      </frameset>
      </html>
    )
  }
}
```

**output**
```javascript
      <html>
      <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
          <title>old page</title>
      </head>
      <frameset id="frame-container" frameBorder="0" border="0">
      </frameset>
      </html>
```

**expect**
```javascript
      <html>
      <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
          <title>old page</title>
      </head>
      <frameset id="frame-container" rows='60,*' frameBorder="0" border="0"  cols="180,11,*">
      </frameset>
      </html>
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**react version**
![image](https://user-images.githubusercontent.com/17465046/45526873-9b08db00-b80b-11e8-980b-86407da1934c.png)

**node environment**
![image](https://user-images.githubusercontent.com/17465046/45526918-ca1f4c80-b80b-11e8-911d-cf0bb3ab9b32.png)
![image](https://user-images.githubusercontent.com/17465046/45526934-d905ff00-b80b-11e8-87d4-306ca3a998c3.png)

**OS**
![image](https://user-images.githubusercontent.com/17465046/45526979-18cce680-b80c-11e8-8928-ee784a5f0a7d.png)

**Comment by Simek** [comment]
According to HTML specification `frameset` tag is obsolete in HTML5, but `cols` and `rows` are valid optional attributes anyway: https://html.spec.whatwg.org/multipage/obsolete.html#frameset

I don't know if React DOM Server Renderer aims to create valid HTML5 output, but if answer is "yes" it's somewhat expected behaviour, if answer is "no" this seems like a bug to me.

**Comment by LeonDWong** [comment]
@Simek No, the page is to support old version html. As i mention at very beginning, there is some historical reason in this project, and i can't change it too much. Is html5 the only standard for react React DOM Server Renderer to support? If "yes", i think i should do some hacking way....

**Comment by LeonDWong** [comment]
@Simek Get puzzled with it too, if React DOM Server Renderer aims to create valid HTML5 output, why does it output obsolete tag without any warning? Even remove valid attributes silently.
Valid Attributes:
![image](https://user-images.githubusercontent.com/17465046/45662769-ceae7280-bb35-11e8-8a4a-c1148bcb69e6.png)

**Comment by Simek** [comment]
Lines highlighted below are responsible for omitting `cols` and `rows` values. Currently only positive numbers are valid for React as value of that attributes. Since values `180,11,*` or `25%,*,25%` are correct according to HTML spec I think this restriction can be lifted but it's not my decision. This might cause some complications I'm not aware of and/or they are not reflected by tests. PR is on the way but I can't assure you it will be merged.
https://github.com/facebook/react/blob/518812eeb82a524dd264be79ca0573ce39cde945/packages/react-dom/src/shared/DOMProperty.js#L356-L359

**Comment by jsnavarroc** [comment]
How can I help you ?
