### ISSUE TITLE
Root element noop blocking GSAP Draggable

### ISSUE THREAD

**Issue by rhernandog** [facebook/react#13654]
**Do you want to request a *feature* or report a *bug*?**
Honestly I don't know

**What is the current behavior?**
I'm a moderator in the GreenSock forums and the most recent update (16.5.X) is causing some issues with the Draggable tool. By default the Draggable tool ignores clicks on specific elements so by default those are not draggable elements, unless you specify that the element should be draggable. Starting on version 16.5.0 a `noop` function is passed on the `onclick` event of the root element of a react app, which is preventing a simple `<div>` tag from being used by the Draggable tool.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React.
https://codesandbox.io/s/jrkbkxeqy
The blue square is not draggabl(should rotate). If you either uncomment line 24 or change the React and ReactDOM versions to 16.4.2, 

**What is the expected behavior?**
It shouldn't be necessary to add the indication to make the element Draggable, it should work by default just in any regular application or web page.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.5.0 - 16.5.1
Chrome 69 - Firefox 62 - IE11 - Edge 17
Windows 7 64
Also other users have tested in Chrome and Firefox in OSX (don't know specific versions)

**Comment by gaearon** [comment]
So, the reason we do this is to work around an issue with iOS Safari.

I'd say that while the breakage is unfortunate, a React root is generally expected to be under React's control. So what handlers we attach is an implementation detail. In fact the future plan is to move more event handlers to the root instead of the document so even if we "fixed" it now it could break later.

>It shouldn't be necessary to add the indication to make the element Draggable, it should work by default just in any regular application or web page.

If I understand correctly, the decision to use this heuristic ("whether there is an explicit click handler") is on GSAP, not a common convention. Therefore, I'm not sure I see why it "shouldn't" be necessary. To me it looks more like an overly broad heuristic is clashing with an implementation detail.

Do you know if it would be sufficient to change `node.onclick = ...` to `node.addEventListener('click', ...)` to get around the heuristic? I think we could do this. But it seems a bit fragile too. And if that fixed it, it would expose a flaw in the heuristic (why does it consider a property but not the event listeners?) So maybe it's the heuristic that would be better to change.

Hope this makes sense but let me know if I misunderstood.

**Comment by rhernandog** [comment]
Hi Dan, thanks for the detailed and fast response.

In fact the normal behaviour when using GSAP's Draggable is that elements such as: buttons, `<a>` tags, inputs, select and textareas keep the default functionality when are clicked, unless is indicated by the user to hijack that, passing the boolean mentioned in the sandbox sample, or heuristic as you mention. Also the normal behaviour is that a `<div>` tag doesn't need the heuristic to work.

On the other hand, there was a discussion in the forums where Jack Doyle (creator of GSAP) mentions that if a user wants to make a form element, a button or an `<a>` tag Draggable the intention is clear in that matter so the heuristic is kind of redundant. So considering that and the popularity of React, the decision is that starting in the next release of GSAP, the boolean will be true by default, in order to avoid any unexpected behaviour.

I linked this issue in the forums so if any other GSAP users wants to chime in, they come and add their opinion in this matter, so we'd appreciate if you can keep it open for a while.

Best,
Rodrigo.

**Comment by gaearon** [comment]
Thank you, for sure I’ll keep it open. Sorry for inconveniencing you.

**Comment by jackdoyle** [comment]
Hi @gaearon, thanks for addressing this. I think the best way to move forward here is for us to change the default behavior in Draggable to dragClickables:true. That way, you don't need to do anything in React and if people want to disallow dragging clickable elements, they can just set dragClickables:false. 

To answer your question, yes, it should resolve things if you switched from declaring an onclick to addEventListener("click"...) but I totally see your point about the fragility, hence my recommendation to just switch behavior on our end. The down side for us, of course, is that this change could break some legacy code but I doubt it'll be a widespread problem and there's an easy fix (setting dragClickables:false). 

We'll plan on making this change in our next GSAP release. 

Thanks again for your consideration. And thanks, @rhernandog, for reporting this!

**Comment by gaearon** [comment]
I think we ended up changing this back (except for portal roots -- kept a targeted fix) so it probably fixed this anyway.
