### ISSUE TITLE
JSX whitespace not consistent if line starts with an expression

### ISSUE THREAD

**Issue by arturog** [facebook/react#13696]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a JSX content (text) line starts with an expression, the whitespace rules are not followed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codepen.io/anon/pen/JaBLVq

**What is the expected behavior?**
Whitespace JSX rules should be respected always.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.3

**Comment by syranide** [comment]
Working as intended, "unfortunately".

The way to understand it is that JSX has a special-case where it adds a space when there is a newline separating two literal texts. Because this is 99% universally what you want in this case (and otherwise it very obviously breaks your output and is very easy to fix). When there are no adjacent texts then this is very rarely what you want and unintentional occurrences of space are not always clearly visible or simple to work around.

I believe you can just do the following in your case.

```
<Foo>
  Bar {}  <--- the braces here force the space to be added
  {...}
</Foo>
```

**Comment by arturog** [comment]
Hi Andreas,

  Thanks for clarifying this *gotcha*!

I'll close -A.
