### ISSUE TITLE
unmountComponentAtNode works async ?

### ISSUE THREAD

**Issue by qhxin** [facebook/react#13690]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

i tried to use `ReactDOM.unmountComponentAtNode` and `ReactDOM.render` to manage my multi roots. i found that if i use them in sync code, i get an error just like this when i change route pages:
```
Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.
```

```
Warning: render(...): Replacing React-rendered children with a new root component. If you intended to update the children of this node, you should instead have the existing children update their state and render the new components instead of calling ReactDOM.render.
```

i use browserHistory to change route.
my code is written in componentDidMount method of a root React component:

Page1.js
```
  componentDidMount() {
    const a = document.getElementById('root2');
    ReactDOM.unmountComponentAtNode(a);
    ReactDOM.render(
      <A />,
      a
    );
    ReactDOM.render(
      <B />,
      document.getElementById('root3')
    );
  }
```

Page2.js
```
  componentDidMount() {
    const a = document.getElementById('root2');
    ReactDOM.unmountComponentAtNode(a);
    ReactDOM.render(
      <C />,
      a
    );
    ReactDOM.render(
      <B />,
      document.getElementById('root3')
    );
  }
```

And then, if i use `setTimeout` to wrap `ReactDOM.render` after `ReactDOM.unmountComponentAtNode(a);`, the result can be success.

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react 16.5.2
react-dom 16.5.2

**Comment by gaearon** [comment]
Can you please provide a single runnable complete example that reproduces the issue. For example as a fiddle.

**Comment by qhxin** [comment]
@gaearon  this is my demo. thanks.

[![Edit o2p74974z](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o2p74974z)

**Comment by qhxin** [comment]
@gaearon  if i don't use unmountComponentAtNode, React Root can clear the old Component's events/doms/state and sub components by its self? or the old component will unmount automatically ？

**Comment by gaearon** [comment]
If you can send a fix I’d be happy to verify it.

**Comment by qhxin** [comment]
@gaearon Thank u! And, yes, you are right. i have checked the source code of  unmountComponentAtNode, and i think it works relates to fiber in react.16 because my demo works right in react 15  ... maybe its a new changed feature that should be noticed to all.

**Comment by AyWa** [comment]
Little investigate more.
I think the problem come from this behavior: 
```
  if (isRendering) {
    // Prevent reentrancy. Remaining work will be scheduled at the end of
    // the currently rendering batch.
    return;
}
```
at https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberScheduler.js#L2001

That is why when we are testing with timeout it is working -> because we are not in render.
So I believe somehow, when we re-schedule the job after the rendering, order might be inverted ?
For now still don't have clue about that, but will continue to investigate before making a fix :)

**Comment by AyWa** [comment]
@gaearon 
I could reproduce with unit test and tried to find a correct way to fix. (I found multiple way, but not really confident about the quality of those, seems quite hacky)

PR is there https://github.com/facebook/react/pull/13744 any feedback / opinion about the `proposal` to make fix would be appreciated 😃

**Comment by rcalimlim** [comment]
There hasn't been any activity here for ~9 months, can we close this issue for now and reopen if this pops up again?

**Comment by ipip2005** [comment]
Is `unmountComponentAtNode` supposed to be asycn?
I have a legacy code that is integrated with DOM manipulation after react dom is unmounted. (I know it's not recommended, but I want to know when is `unmountComponentAtNode` is finished before I can execute DOM manipulation to quickly fix this legacy code)

The following order of code will have React uncaught exceptions:
1. invoke unmountComponentAtNode on DOM-A
2. clean DOM-A by javascript
3. React throw errors because when it tries to remove node, it's already being removed by step '#2'
![image](https://user-images.githubusercontent.com/7711735/60934592-b271f280-a27b-11e9-807f-70e188d4686c.png)
