### ISSUE TITLE
v16.5.2: Expected subtree parent to be a mounted class component. 

### ISSUE THREAD

**Issue by navono** [facebook/react#13742]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**

I have a [demo](https://codesandbox.io/s/k1m4p0p5q7) to use `react-paper-bindings`, the `react-paper-bindings` use `react-reconciler` for render.

When I add `"react-dom": "16.4.2"`, it's worked, but if change to `"react-dom": "16.5.2"`, generate the error:
>Invariant Violation
Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.

**What is the expected behavior?**
correct render

**Comment by gaearon** [comment]
There are two possible fixes I think:

* `react-paper-bindings` could stop passing `this` as third argument [here](https://github.com/react-paper/react-paper-bindings/blob/87aa1ad78f944b5e9e6b502d044954db2ad5327b/src/View.js#L50), [here](https://github.com/react-paper/react-paper-bindings/blob/87aa1ad78f944b5e9e6b502d044954db2ad5327b/src/View.js#L69) and [here](https://github.com/react-paper/react-paper-bindings/blob/87aa1ad78f944b5e9e6b502d044954db2ad5327b/src/View.js#L80). This would break legacy context propagation, but you shouldn't be using it anyway since it'll get deprecated. However, this would remove the fragile dependency between `react-dom` and `react-reconciler` versions.

* Alternatively, `react-paper-bindings` can update `react-reconciler` dependency to the version that came out together with `react-dom@16.5.2`. I imagine it's `react-reconciler@0.15.0`.

**Comment by navono** [comment]
Thanks you @gaearon. I'll try to fix that.

**Comment by p-somers** [comment]
Was this fixed? I'm still seeing this in React 16.7.22

**Comment by navono** [comment]
It's need to be update the `react-reconciler` and then change the user code, not in `react-reconciler`.
