### ISSUE TITLE
MutationObserver for ReactDOM without polling

### ISSUE THREAD

**Issue by sheerun** [facebook/react#13772]
**Do you want to request a *feature* or report a *bug*?**

feature

**Description**

When [developers](https://github.com/kentcdodds/dom-testing-library) want to watch for mutation of DOM nodes they need to use [MutationObserver](https://github.com/kentcdodds/dom-testing-library/blob/6e56bb0004998a796841f2d017c92fdecac6156c/src/wait-for-element.js#L49) API and it's [polyfill](https://github.com/megawac/MutationObserver.js/tree/master) that checks each observed element 30 times a second, which is not very performant.

Ideally ReactDOM would have API that allows to execute callback each time DOM element is created / updated / removed in DOM) with list of mutations (just like MutationObserver#observe callback). Such observing of elements would be  more lightweight than polling for changes for each observed element.

Feature request: MutationObserver API  for React-controlled DOM that doesn't use polling.

The API could be the same as [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#Example):

```javascript
import { MutationObserver } from 'react-dom';
var observer = new MutationObserver(callback);
observer.observe(ref)
observer.disconnect()
```

**Comment by nmain** [comment]
It depends on what you're trying to accomplish, but for many normal use cases `componentDidMount` and `componentDidUpdate` are your best bet.  They let a component make DOM modifications after a `render` cycle whenever it updates or whenever one of its children updates due to a change it initiated.  They occur synchronously and allow DOM modifications to happen without any unexpected flashes/glitches from asynchronous behavior.  With access to `prevProps` and `prevState` in `componentDidUpdate`, you can smartly change only what you need to change because you know exactly what changed in the React rendering.

**Comment by sheerun** [comment]
The use case is integration testing, and unfortunately you can't use `componentDidMount` or `componentDidUpdate` in this case.
