### ISSUE TITLE
DOM Selector VS React Ref Performance

### ISSUE THREAD

**Issue by hg-pyun** [facebook/react#13770]
Hello. I am heavy react user! 
I have question when developing it as React.

As I develop, sometimes we need to access the elements that exist in the DOM. 
Is there any performance difference between using the `DOM Selector` and using `React Ref`?

For example, When using Ref, Does Virtual-DOM optimize? Is there a physical speed difference between the DOM selector and ref?

[The official document](https://reactjs.org/docs/refs-and-the-dom.html) does't explan react ref performance.
I'd like to hear your ideas on this.
@gaearon 

Thank you :D

**Comment by aweary** [comment]
@hg-pyun refs might be a little faster in some cases, since the component already has a reference to the DOM node. With `document.querySelector` and friends the browser has to parse and walk the tree to find the node, which could be slower.

With that said, the performance difference is probably negligible in almost all cases. If you have a use case where you're doing lots of manual DOM queries and manipulation it might be best to just manage that yourself and not use React at all for that part of the application. Checkout [Integrating with Other Libraries](https://reactjs.org/docs/integrating-with-other-libraries.html) for advice on that.

If performance _isn't_ a problem, then I'd say don't really worry about it. In general, I'd recommend using refs if it makes sense.

**Comment by gaurav5430** [comment]
are there any other benefits of using refs over query selector (or others) ? 
For example, refs may be aware of the react virtual dom or the react component lifecycle because they work inside react, whille query selector would not? does this matter?

**Comment by markerikson** [comment]
@gaurav5430 yes, that's exactly the point.

React will always update a ref with the correct DOM node for the element you put the `ref` on, right after it's done rendering.
