### ISSUE TITLE
Passed in children (Function|Component) to Component are rendered inconsistently

### ISSUE THREAD

**Issue by ArtemX9** [facebook/react#13794]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When passing a function as a child that returns a ReactElement to another component that performs conditional rendering this function gets called before the Render function inside the component that should render children. However, if some another component is passed as a child instead of a function, then everything goes as expected and child component is rendered after the parent component.

Here is an example:
[![Edit 1onxjp7j0j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1onxjp7j0j)

Here is the code:
```javascript
class ConditionalLoader extends Component{
  render() {
    console.log('ConditionalLoader render >>> ', new Date());
    if (false) {
      return this.props.children;
    } else {
      return null;
    }
  }
}

class UndefinedComponent extends Component {
  render() {
    console.log('UndefinedComponent render >>> ', new Date());
    return this.props.someUnexistingObjectFunction.getsCalled();
  }
}

class App extends Component {
  render() {
    console.log('App render >>> ', new Date());
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
        <ConditionalLoader>
          <UndefinedComponent />
          {this.renderUndefined()}
        </ConditionalLoader>
      </div>
    );
  }

  renderUndefined(iDontExist) {
    console.log('renderUndefined >>> ', new Date());
    return iDontExist.butGetCalled();
  }
}
```
**What is the expected behavior?**

I guess there should be some consistency: either both function and component should be rendered or neither function nor component should.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Same behaviour on: "^16.5.2" & "16.3.2"

**Comment by markerikson** [comment]
The description is confusing, but as far as I can tell this is entirely correct behavior by React.

You're attempting to render both `<ConditionalLoader>`, _and_ the components that will eventually become its children, at the same time.  In order for React to know what that component's children will be, it has to call `this.renderUndefined()` first.

This is more clear when you convert that from JSX to the equivalent `React.createElement()` calls:

```js
React.createElement(
  ConditionalLoader,
  null,
  React.createElement(UndefinedComponent, null),
  this.renderUndefined()
);

This is normal JS function call evaluation.  Before we can make the call to `React.createElement(ConditionalLoader)`, we have to know what all the arguments are.  So, it will call `React.createElement(UndefinedComponent)`, and also `this.renderUndefined()`, first.  Then, _after_ the call to `React.createElement(ConditionalLoader)`, React gets the elements and can run `ConditionalLoader.render()`.

So, nothing broken with React here.
```

**Comment by ArtemX9** [comment]
Thank you for your answer @markerikson!
As you said 

> In order for React to know what that component's children will be, it has to call this.renderUndefined() first.

Then, why don't it call a `UndefinedComponent.render()` the same time it calls `this.renderUndefined()`? Shouldn't it be aware of `UndefinedComponent` childrens?

For example, what will happen if I declare a dummy component, like this:

```javascript
const UndefinedDummyComponent = () => {
  return dummyFunctionCall();
}
```

and then try to render it:

```javascript
class App extends Component {
 render() {
  return (
   <div>
    <ConditionalLoader>
           <UndefinedComponent />
           <UndefinedDummyComponent />
     </ConditionalLoader>
   </div>
  );
 }
}
```

I think it's not very obvious what happens and why functions of `App` class are executed before `ConditionalLoader` `render` method.

**Comment by markerikson** [comment]
Because you're still misunderstanding how both Javascript and React work.

For any given parent/child pair, this is the sequence of events:

- React calls `ParentComponent.render()`.  All of the code in the parent's `render` function executes, returning a tree of JS objects called elements (like `{type : ChildComponent, props : {a : 42}, children : [] }` )
- React inspects that tree of elements returned by the parent.  It sees that one of the elements is of type `ChildComponent`
- It then calls `ChildComponent.render()`, and collects its render output as the next level in the tree.

So, React cannot call `ChildComponent.render()` until after the parent component has rendered, and in this example, `this.renderUndefined()` is being called in the parent component's `render` method.

The difference between your first and second examples is that `this.renderUndefined()` is a _function call_ that is executed _immediately_ as part of `ParentComponent.render()`, while `<UndefinedDummyComponent>` is going to end up as an element object that _tells_ React what component to render next.

Again, this is both a misunderstanding of Javascript usage and React behavior, not a bug.

**Comment by ArtemX9** [comment]
Hi @markerikson,
I've been thinking about your answer and now I understand what you've ment.

Thank you for your answers, you've helped me a lot!
