### ISSUE TITLE
useReducer with DOM events

### ISSUE THREAD

**Issue by jacobp100** [facebook/react#13990]
**Do you want to request a *feature* or report a *bug*?**

Possibly a bug, possibly a feature.

**What is the current behavior?**

Create a reducer using `useReducer` where the action is a DOM event.

Attempt to update the value by passing the updater into an event.

The event cannot be accessed, throwing an error about reusing SyntheticEvents. I assume it's the updater not running synchronously.

```jsx
const valueReducer = (current, e) => e.target.value

const Example = () => {
    const [value, updateValue] = useReducer(valueReducer, '')

    return <>
        <p>{value}</p>
        <button type="button" value="test" onPress={updateValue}>Test</button>
    </>
}
```

**What is the expected behavior?**

It'd be nice if it worked

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.7.0-alpha

**Comment by bvaughn** [comment]
This is because the event you're passing around is not a DOM event but a ["synthetic event"](https://reactjs.org/docs/events.html#event-pooling). As the docs mention:
> If you want to access the event properties in an asynchronous way, you should call `event.persist()` on the event, which will remove the synthetic event from the pool and allow references to the event to be retained by user code.

If the reducer is run asynchronously, the synthetic event might have already been returned to the pool by the time it runs– in which case, `target` won't refer to what you want it to.

As the docs say, you can either call `event.persist()` ([like this](https://codesandbox.io/s/64355876n3)) _or_ you can just pass the `event.target.value` to your reducer instead ([like this](https://codesandbox.io/s/3y442orxo5))! 😄 

Btw, you should be seeing an error message with similar text as what I wrote above in the console:
> Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

**Comment by jacobp100** [comment]
So what I'd be interested in is if it's possible to run the reducer synchronously, but apply asynchronously. Then again, I don't know how common this pattern is 🤷‍♂️
