### ISSUE TITLE
iOS 12.0 and above causes strange click/touch-behavior

### ISSUE THREAD

**Issue by folofse** [facebook/react#14018]
Bug in iOS 12.0 and above, both simulator and device.

Im not sure exactly what's causing the problem, but click/touch events gets triggered outside the buttons (red squares) and they trigger the buttons inside the yellow squares, almost like the buttons in the yellow squares are flowing over.

"react": "^16.6.0-alpha.8af6728",
"react-native": "^0.57.4",
"react-navigation": "^2.18.2",

![simulator-screen-shot---iphone-8---2018-10-29-at-11 38 16](https://user-images.githubusercontent.com/16066712/47644904-b89dc400-db6f-11e8-9910-3840e02e93af.jpg)

**Comment by philipp-spiess** [comment]
@folofse Hey 👋 From your screenshot it's unclear what the issue is. Can you verify that this is indeed a bug in React by trying to build a reproduction case that uses `addEventListener`? If you're sure it is a React bug, we'd appreciate a small example (a working CodeSandbox link is enough) - ideally with only one button.

**Comment by philipp-spiess** [comment]
Ohh sorry I didn't see that you're using React Native 😅 This issue tracker is for React Core and React DOM only. You might want to reach out to our friends over at: https://github.com/facebook/react-native/issues

Thanks!

**Comment by folofse** [comment]
Ooops, my bad,
