### ISSUE TITLE
Suspense is delaying initial render of whole application

### ISSUE THREAD

**Issue by kevinwolfcr** [facebook/react#14056]
**Do you want to request a *feature* or report a *bug*?**

Bug? (or maybe I'm doing something wrong)

**What is the current behavior?**
Component with resource.read() wrapped on `
<Suspense />` is causing the whole application to delay initial render (until `maxDuration` exceeds)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://github.com/kevinwolfcr/exchange-rate-cr/blob/master/src/app.js

**What is the expected behavior?**

What I expect is to delay the render of only the code within the `<Content />` component, not the whole `<App />` component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react: `^16.7.0-alpha.0`
react-cache: `2.0.0-alpha.0`
react-dom: `^16.7.0-alpha.0`

**Comment by acdlite** [comment]
I think you're confused by how Suspense works. Suspense *does* delay the entire app. That's the whole point. It waits until everything is consistent before it applies the changes. That way everything appears at once, instead of jankily popping in piece by piece.

Since you wouldn't want to suspend forever, eventually React will give up and switch to rendering a fallback. That's what the `<Suspense />` component is for. If you don't want a particular subtree to block the rest of the app, then decrease its `maxDuration` prop.

But until that that threshold is reached, the app is suspended. That is the expected behavior.

**Comment by kevinwolfcr** [comment]
Ok, understood, thanks for the explanation. So If I wrap the whole App on a `<Suspense maxDuration={0} />` and then the component that I actually want to suspend with a `<Suspense maxDuration={250} />`, should work?

I mean, I am in love with the new Suspense feature, but IMO if the user comes and sees the app initially all white, that can be a bad user experience.

**Comment by acdlite** [comment]
I think your mental model is backwards. You don't use `<Suspense />` to suspend parts of the tree; you use it to *unsuspend* the rest of the tree. It takes a bit of adjustment to get used to.

So start with no `maxDuration`s, then if certain parts of the tree are taking too long, use `maxDuration` to tell React how long you're willing to wait for it. Put `maxDuration={0}` around the stuff you don't want to wait for at all.

**Comment by kevinwolfcr** [comment]
I understand now, thanks!
