### ISSUE TITLE
Cannot see breakdowns for User Timing

### ISSUE THREAD

**Issue by maxshortzp** [facebook/react#14067]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I can't see `Bottom-Up` or `Call Tree` information for the specific components listed in `User Timing` when I profile my React app following the directions described at https://calibreapp.com/blog/2017-11-28-debugging-react/ (this tutorial was recommended by the react docs).

Others have recently reported the same issue on StackOverflow:
* https://stackoverflow.com/questions/52364829/no-timing-breakdown-in-user-timing-section-in-performance-tab-in-chrome-dev-tool
* https://stackoverflow.com/questions/52315796/stats-for-child-components-are-not-always-available-in-user-timing-section-of-ch

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I can reproduce this using a simple repo I found on the internet:
1. Clone https://github.com/larkintuckerllc/react-patterns (The repo contains several examples. The **User Timings `Bottom-Up` and `Call Tree` information do not show up on the `lifecycle` app**. Interestingly, the **User Timings showed up correctly on the `jsx` example app**).
2. After navigating to the lifecycle app folder, run `npm install`.
3. `npm start`
4. Add `?react_perf` to the URL.
5. Open Chrome Performance tools. Press the "Start Profiling and Reload page" 
6. Open the User Timing section
7. Select a specific component. The `Summary` tab shows up as expected. There's nothing in the `Bottom-Up` or `Call Tree` tabs.

**What is the expected behavior?**
The `Bottom-Up` and `Call Tree` tabs show sub call information as described in the tutorial.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
React: ^15.5.4 (For example issue I posted) 15.6.2 (For the production app I was having issues with)
Chrome: 70.0.3538.77 (Official Build) (64-bit)
JavaScript | V8 7.0.276.32
OS: MacOs High Sierra, Version 10.13.1
```

I'm not sure if this was a problem in previous versions major version React or not. [One of the StackOverflow questions](https://stackoverflow.com/questions/52364829/no-timing-breakdown-in-user-timing-section-in-performance-tab-in-chrome-dev-tool) mentioned that they were on React 16 so it sounds like it could be a problem there too.

**Comment by gaearon** [comment]
Please file this against Chrome. We have no control over which tabs Chrome decides to show. Maybe Chrome has a bug.

**Comment by lewisflude** [comment]
@maxshortzp In case you see this, it appears to now be working in Chrome Canary!

**Comment by maxshortzp** [comment]
@lewisflude - Thanks! I can see the timings on chromium 73 too.

I assume that they'll update the chrome bug when they get closer to actually releasing it (I'll bump it if they don't).

**Comment by Arissablue** [comment]
Wat  u mean by that friend


Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: maxshortzp <notifications@github.com> Date: 12/7/18  7:39 PM  (GMT-07:00) To: facebook/react <react@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [facebook/react] Cannot see breakdowns for User Timing (#14067) 
@lewisflude - Thanks! I can see the timings on chromium 73 too.
I assume that they'll update the chrome bug when they get closer to actually releasing it (I'll bump it if they don't).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/facebook/react","title":"facebook/react","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/facebook/react"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maxshortzp in #14067: @lewisflude - Thanks! I can see the timings on chromium 73 too.\r\n\r\nI assume that they'll update the chrome bug when they get closer to actually releasing it (I'll bump it if they don't)."}],"action":{"name":"View Issue","url":"https://github.com/facebook/react/issues/14067#issuecomment-445423358"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/facebook/react/issues/14067#issuecomment-445423358",
"url": "https://github.com/facebook/react/issues/14067#issuecomment-445423358",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [facebook/react] Cannot see breakdowns for User Timing (#14067)",
"sections": [
{
"text": "",
"activityTitle": "**maxshortzp**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@maxshortzp",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"facebook/react\",\n\"issueId\": 14067,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/facebook/react/issues/14067#issuecomment-445423358"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 405250057\n}"
}
],
"themeColor": "26292E"
}
]
