### ISSUE TITLE
<option> element containing component that returns a string is rendered as [object Object]

### ISSUE THREAD

**Issue by PPepperCC** [facebook/react#14064]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If you use a Component that returns a string inside an <option> element, the Component will be rendered as '[object Object]'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://jsfiddle.net/38tz0ym2/

**What is the expected behavior?**

The string returned by the component should be rendered as the <option> elements innerHTML

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This issue started to occur on version 16.5.0 - it did not occur in version 16.4.2 or earlier versions of v16

**Comment by pavinthan** [comment]
@PPepperCC It's not bug `option` element only accept label as string not accept another DOM element you just replace the react functional component with `div` you should see the exact behaviour

**Comment by gaearon** [comment]
Yeah, really sorry about this — it worked accidentally between 16.0 in 16.6 in some cases, but crashed in others. It wasn't intended to work (that's why it was crashing). The bug fix was to always treat it as text, but I understand it's frustrating if you started relying on this. We might eventually properly support this but for now it will behave exactly like `<textarea>`: all children are converted to strings.
