### ISSUE TITLE
Suspense fallback remounts when each child resolves

### ISSUE THREAD

**Issue by adwilk** [facebook/react#14073]
**Do you want to request a *feature* or report a *bug*?**
Not sure if its a bug or a feature request.

**What is the current behavior?**
The component given as a fallback to Suspense is remounted each time a lazy child resolves.

https://codesandbox.io/s/z6v6x3n1np
This example shows how a fallback component, which counts up, is mounted more than once.

**What is the expected behavior?**
The fallback is mounted once and is only unmounted when all lazy children are resolved.
In the example the counter would run up to 9.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react@16.6.0

**Comment by arianon** [comment]
Looks like expected behavior to me, ~~when `LazyText1` resolves, the `Suspense` component tries to render its children once again, but then `LazyText2` throws another promise, so it renders the fallback again, and so on.~~ Nope, all three promises are thrown in parallel, but every time a promise resolves, `Suspense` attempts to re-render the children, but seeing that some children are unresolved, it renders the fallback.

However, [in Concurrent Mode the observed behaviour aligns with your expected behaviour][1], with one apparent bug: the children don't render when `LazyText3`'s delay is over 8000 milliseconds, on my machine at least. I'm not sure what's happening, but I'll try to look into this further.

[1]: https://codesandbox.io/s/4lvn7ror8x

**Comment by adwilk** [comment]
Here is a slightly less contrived example than what I shared above
https://codesandbox.io/s/2v8l3vn67p

Here there is a CSS loading spinner, due to the remounting of the fallback component the animation of the spinner is not smooth.

**Comment by gaearon** [comment]
Seems like a bug.

**Comment by gaearon** [comment]
I added a failing test in https://github.com/facebook/react/pull/14078

**Comment by adwilk** [comment]
Thanks 👍

**Comment by OndeVai** [comment]
Has this been fixed? I'm seeing the same issue now with React 17.0.1

**Comment by gaearon** [comment]
That one was fixed, so you're seeing something different. File a bug with a minimal repro case.

**Comment by OndeVai** [comment]
Actually, in my case, I have a Suspense (call it SuspenseA) nested several levels below another Suspense (call it SuspenseB). For  SuspenseB, SuspenseA renders its fallback UI only if I do not provide a fallback for SuspenseB. In my case I did not want any fallback UI for B at all. So, I ended up providing a null fallback and everything worked as desired. 

Is what I just described by design? If not, I can go ahead and write up another bug...

**Comment by gaearon** [comment]
Hmm. I'm not sure I understand what the expected and the actual behavior was.

**Comment by OndeVai** [comment]
@gaearon - The expected behavior (for me, at least) was to not show the fallback from SuspenseA, since the direct child components of SuspenseA were already loaded.

So (psuedoish React code):

```
<Suspense fallback={<BigPageLoader/>}> //-->SuspenseA
   <AysncComponentA>
       <Suspense> //-->SuspenseB
          <AysncComponentB>..</AysncComponentB> //-->shows the fallback of SuspenseA, unless fallback={null or other} provided in SuspenseB
       </Suspense>
   </AysncComponentA>
</Suspense>
```

In my case, showing SuspenseA's fallback when AysncComponentB was loaded was unexpected. I assumed that since AysncComponentA already loaded there would be no more fallback showing at that level.

(I can create a CodeSandbox if you'd like, just pressed for time today...)

**Comment by gaearon** [comment]
I think the issue here is that `Suspense` without a `fallback` or with `fallback={undefined}` currently gets ignored completely. And you seem to have expected that it acts as a `null` fallback.

We'll need to revisit the behavior (maybe it should always warn and tell you to specify it). But the idea definitely isn't that `fallback={null}` is a good default. It's not because it's "unintentional" — you'll just see your page jumping when the content loads. Ideally you'd provide an intentionally designed loading state.

**Comment by OndeVai** [comment]
@gaearon  - Thanks for the quick reply. 

I would expect SuspenseB to behave like SuspenseA for its child components. So, if I don't provide a fallback, don't show one. IMO, React can't really make too many assumptions on what the best practices for loading states are for individual projects ;)

**Comment by gaearon** [comment]
If that's the behavior you want, you can always pass `fallback={null}`. I am simply saying that there is no "default" fallback, you should always specify one. The fact that not passing it accidentally works seems like an unintentional omission on our side.

**Comment by OndeVai** [comment]
It might be nice to just call out the behavior in the React official docs.

**Comment by gaearon** [comment]
Yeah. The undefined fallback thing seems like it's accidental so we'll revisit that.
