### ISSUE TITLE
Event name different for <button /> then e.g <input />

### ISSUE THREAD

**Issue by namjul** [facebook/react#14121]
**Do you want to request a *feature* or report a *bug*?**
- its more a question but possible something to be adjusted.

**What is the current behavior?**
If you click the button the console outputs `Class` as the event name and if you change the input it outputs `SyntheticEvent`.
https://jsfiddle.net/Luktwrdm/1397/

**What is the expected behavior?**
I expected both to be from `SyntheticEvent`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
We upgraded from React version ^15.6.2 to ^16.6.0.
In ^15.6.2 the button event name was `SyntheticMouseEvent`

**Comment by heyimalex** [comment]
It looks like the name of the constructor is used. Change events are created by calling `SyntheticEvent` directly, but `SyntheticMouseEvent` uses `SyntheticEvent.extend` to create a new constructor, defined [here](https://github.com/facebook/react/blob/affb2b50ca1dfa2b780e94039e98e3bb70faaaab/packages/events/SyntheticEvent.js#L230), and that function is just named `Class`, so that's what you're seeing. Not to say anything about the issue, just why it happens.

It doesn't look like function names are easily set-able, but I found [this](http://2ality.com/2015/09/function-names-es6.html#changing-the-names-of-functions).

**Comment by sophiebits** [comment]
@heyimalex's explanation is correct here.
