### ISSUE TITLE
Cannot read property 'ReactDebugCurrentFrame' of undefined

### ISSUE THREAD

**Issue by btf93** [facebook/react#14137]
Hi, I get the following issue in Chrome developer tools Console after updating to the latest version of React.

It doesn't seem a very common issue? Please let me know if there's any other information I can provide?

Uncaught TypeError: Cannot read property 'ReactDebugCurrentFrame' of undefined
    at eval (webpack-internal:///987:655)
    at eval (webpack-internal:///987:3570)
    at Object.<anonymous> (bundle.js:11919)
    at __webpack_require__ (bundle.js:20)
    at eval (webpack-internal:///478:34)
    at Object.<anonymous> (bundle.js:5811)
    at __webpack_require__ (bundle.js:20)
    at eval (webpack-internal:///597:7)
    at Object.<anonymous> (bundle.js:7239)
    at __webpack_require__ (bundle.js:20)

**Comment by gaearon** [comment]
A full reproducing project would be nice.

**Comment by btf93** [comment]
> A full reproducing project would be nice.

I can't put in any code due to work restrictions, but these are the current React versions from package.json:

devDependencies": {
"react-dom": "^16.6.0",
    "react-test-renderer": "^15.6.2",
    "redux-mock-store": "^1.2.3",
},
"dependencies": {
 "react": "^16.6.0",
    "react-custom-select": "^0.0.2",
    "react-datetime": "^2.16.2",
    "react-input-autosize": "^1.2.0",
    "react-nested-file-tree": "^0.0.4",
    "react-numeric-input": "^2.2.3",
    "react-redux": "^5.1.0",
    "react-router-dom": "^4.3.1",
    "react-simple-accordion": "0.0.1",
    "react-tooltip": "^3.9.0",
},

I wondered if I'm missing something from there?

**Comment by sophiebits** [comment]
It sounds like maybe you are using incompatible versions of `react` and `react-dom`. It's odd that react-dom is not in `dependencies` in your package.json too.

**Comment by btf93** [comment]
> It sounds like maybe you are using incompatible versions of `react` and `react-dom`. It's odd that react-dom is not in `dependencies` in your package.json too.

Thanks for the response. Is there a way to find out which 'react' and 'react-dom' are compatible? Also, I'll move copy 'react-dom' to dependencies.

**Comment by chasestarr** [comment]
@btf93 you should maintain the exact same `react` and `react-dom` versions. 

I like to run `npm ls` to view my local dependency versions. Grep for react to filter the lines `npm ls | grep react`. You may see a variety of react-related npm packages. You're looking specifically for `react` and `react-dom`

**Comment by gaearon** [comment]
You probably have some code that does `React.PropTypes.object` (which doesn't exist in 16). Check by the stack trace where the error happens. If it's a third party package, you can try looking for a new version. As the last workaround, you could do something like `React.PropTypes = PropTypes` before any code runs.

**Comment by pascalwhoop** [comment]
I had this when trying to emulate our current project running react v15 while using the react-hot-reloader based on create-react-app. So I started a new app and set the react version to v15 which caused this I then noted that upgrading react/redux from 15->16/ 3->4 respectively doesn't hurt much so I went for that.

**Comment by LeiZeng** [comment]
I have identified the root cause probably, while trying to use @react-three/fiber, and I don't think it's a version compatible issue. 

**Tltr**: react-reconciler will drive itself into endless error loop when `NODE_ENV=development` and use `production` bundle of `React`. Especially the loop is a `do{}while(true)` synchronous loop, which make the application blocked.

The error is caused at: https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-reconciler/src/ReactCurrentFiber.js#L48
where `ReactDebugCurrentFrame` is `undefined`, which should be injected by `react` __DEV__ version.

The thing is that react bundle and react-reconciler bundle could not always be the same mode, as react-reconciler is usually a dependency of third party tools like @react-three/fiber.

@gaearon please take a look at this one, I can make a PR if possible.
