### ISSUE TITLE
How do I tell if React supports `Class.contextType`?

### ISSUE THREAD

**Issue by simonguo** [facebook/react#14135]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

I am developing a component that wants to use [Class.contextType](https://reactjs.org/docs/context.html#classcontexttype). It also needs to be compatible with the old version.

I can use `if(React.createContext)` to determine if React supports createContext , but how do I tell if React supports Class.contextType ?

**Comment by FredyC** [comment]
Might be somewhat weird, but checking for eg. React.lazy will work too as it was released together. I dont think there is a better way

**Comment by gaearon** [comment]
Yeah that sounds reasonable. Note that `react` package doesn't actually contain the implementation. It's contained in the `react-dom` package. So even that isn't 100% safe.

Personally I'd suggest just cutting a new major version that uses it (and requires React 16.6+), instead of trying to support both. Otherwise you're just going to ship extra code, bloating the bundle.

**Comment by simonguo** [comment]
Thanks
