### ISSUE TITLE
Problem with HTML select

### ISSUE THREAD

**Issue by SilentPick** [facebook/react#14199]
If any thing updates the state - select work weird - looks as if it reload
Try it here: https://codesandbox.io/s/m7yzxl92xj 
I use latest CRA, and test on windows and mac OS

**Comment by SilentPick** [comment]
@khorramk https://codesandbox.io/s/pk80k397x0 
this is how it's should to work

**Comment by vsylvestre** [comment]
Options are selected on the onMouseUp event. The component updates with each update of the timer, which also causes for the Select to return to its previous value, since it has not detected any change with the onMouseDown event. You can try to override this default behavior.

However, if this is an option for you, I would simply put the timer in another component. In your example, the properties "a" and "value" of your state seem unrelated anyway. Here is an updated sandbox with this solution: https://codesandbox.io/s/x7w7x6l4zo.

**Comment by SilentPick** [comment]
I tested this problem again, for now it's work on windows 7, but not on macOS
