### ISSUE TITLE
Hooks are disabled in v16.7.0-alpha.1

### ISSUE THREAD

**Issue by arianon** [facebook/react#14222]
![image](https://user-images.githubusercontent.com/5781517/48439210-1c251580-e75c-11e8-98db-e64938e1fb39.png)

:smile:

**Comment by gaearon** [comment]
Oops. Sorry.

**Comment by brunolemos** [comment]
Maybe unpublish `16.7.0-alpha.1`? I believe most people are using the next version because of hooks.

I got here by installing `react@next` and thinking I was doing something wrong because React.useState was undefined.

**Comment by martinek** [comment]
Heh. Just spent good hour trying to figure out why useState is not defined on React. Will this be changed or should I look for some other version?

**Comment by bvaughn** [comment]
Previous alpha release had incorrect feature flags due to a build script snafu. (I even tested with NPM+CRA but apparently the @next tag hadn't propagated yet) 😳

Fortunately we have some ideas on how to prevent this sort of thing from happening in the future:
https://github.com/facebook/react/issues/14201

Sorry for the inconvenience.
