### ISSUE TITLE
Input of password type causes memory leak

### ISSUE THREAD

**Issue by levinqdl** [facebook/react#14284]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

password input causes memory leak

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I have created a code sandbox for this issue: https://codesandbox.io/s/kwjm18plno

In the app, each click on the button will unmount the previous input, and mount a new input, with a different id.

open the code sandbox, and open chrome DevTools, in Memory tab, perform an Allocation instrumentation on timeline:

- choose Allocation instrumentation on timeline
- start recording
- force GC by click the trash icon
- click the button multiple times, add the counter to 10
- force GC again, so that all detached DOM nodes to be collected
- stop recording & wait for the snapshot loaded
- filter by 'detached', to only show detached DOM nodes
- then we can see the "Detached HTMLInputElement" in the Constructor panel, and their ids are what we generated by clicking the button

<img width="722" alt="screen shot 2018-11-20 at 10 07 51 am" src="https://user-images.githubusercontent.com/6294455/48746890-52a6e700-ecac-11e8-816d-b59c5326fe0c.png">

I have also checked #12420 cases: it does not leak without React, and all nodes are still there even after lots of re-rendering with a force GC, so I believe this is a memory leak for sure.

**What is the expected behavior?**

Unmounted inputs of password type can be GCed after next re-rendering. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

OS: macOS High Sierra 10.13.6
Chrome: 70.0.3538.102
React: 16.5.2
ReactDOM: 16.5.2
I have tested this in React 16.0.0 & ReactDOM 16.0.0, and it had the same problem.

**Comment by gaearon** [comment]
I can't reproduce this outside of CodeSandbox. I see at most two at any given time:

<img width="585" alt="screen shot 2018-11-20 at 1 58 34 pm" src="https://user-images.githubusercontent.com/810438/48778201-7712bb80-eccc-11e8-8e8e-17bf70951bc1.png">

So this is likely some issue with the CodeSandbox environment.

My HTML file:

```html
<html>
  <body>
    <script src="https://unpkg.com/react@16.5.2/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16.5.2/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.js"></script>
    <div id="container"></div>
    <script type="text/babel">


class App extends React.Component {
  state = {
    count: 1
  };
  add = () => {
    this.setState(({ count }) => ({
      count: count + 1
    }));
  };
  render() {
    const { count } = this.state;
    return (
      <div className="App">
        <div>
          <label>
            PW{count}
            <input type="password" key={count} id={`count${count}`} />
          </label>
        </div>
        <button onClick={this.add}>add</button>
      </div>
    );
  }
}


      ReactDOM.render(
        <App />,
        document.getElementById('container')
      );
    </script>
  </body>
</html>
```

**Comment by iericallen** [comment]
Hey @gaearon my colleague @rynbyjn would like to reopen this issue. 

**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

An `<input type="password"/>` causes a memory leak.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

You can recreate the behavior by visiting https://iericallen.github.io/test-react/ and following the steps listed. 

Please view our source code at: https://github.com/iericallen/test-react/tree/source

**What is the expected behavior?**

Unmounted components including `<input type="password" />` can be garbage collected after next re-rendering.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

OS: macOS X Mojave 10.14.2 (18C54)
Chrome: 72.0.3626.109
React: 16.8.3
ReactDOM: 16.8.3

**Comment by cs-NET** [comment]
Hey @gaearon, I second @iericallen request to reopen this. Just ran into this issue myself on Windows 10, Chrome 73.0.3683.75, React/ReactDOM 16.8.4

I happened to have a login form hidden in multiple areas of application and navigating between those areas results in thousands of detached elements.

Simply changing input type from "password" to "text" resolves the issue.

**Comment by Jemt** [comment]
There is a bug in Chrome (and most likely other Blink and WebKit powered browsers) that results in memory leaks for certain types of input elements:
https://bugs.chromium.org/p/chromium/issues/detail?id=967438
It can easily be reproduced with vanilly JavaScript - e.g. using https://jsfiddle.net/vkqfmr4b/
Steps to test:

- Click Add Input and enter text when prompted
- Click Remove All Inputs.
- Now create a snapshot of the heap using Dev Tools - no detached elements.
Now repeat the steps, but enter password when prompted instead.
The heap snapshot will now reveal detached elements.
