### ISSUE TITLE
ReactDom.render() returns null when triggered from setState callback

### ISSUE THREAD

**Issue by duanhuiwen** [facebook/react#14290]
I am not sure if it is bug or not, but the behaviour is kind weird. As the working demo [here](https://stackblitz.com/edit/react-pa27iu?file=index.js)

**What is the current behavior?**

The current behaviour is that when I  render a dialog from onclick setstate callback, like this
```
<div onClick={()=>{
  this.setState({
    a : 1
  }, ()=>{
    this.renderPortal()
  })
}}> click me</div>
```

this.renderPortal() will render the dialog but I cannot close the dialog. But when I do
``` 
<div onClick={()=>{
 this.renderPortal()
}}> click me</div>
```

I can close the dialog.

It seems that react thinks the Dialog rendered from setState callback is stateless, why is that?

**What is the expected behavior?**
Should these two snippets work the same way?

# #

**Comment by gaearon** [comment]
Yeah, that's a known issue that we won't be able to fix because `ReactDOM.render` is no longer synchronous if we’re already in the middle of an update (which is the case in `setState` callbacks). Longer term you can consider `ReactDOM.render` return value to be legacy (as said in the docs).

You should be able to use refs instead though to get a reference, and `ReactDOM.render` offers a callback.
