### ISSUE TITLE
I wonder if there are plans to support tslint for hooks like eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by SwordsmanYao** [facebook/react#14304]

**Comment by gaearon** [comment]
We likely won't make the TSLint plugin ourselves, but the community is very welcome to do it!

**Comment by Gelio** [comment]
I have created a TSLint rule similar to `eslint-plugin-react-hooks`:

https://github.com/Gelio/tslint-react-hooks

It detects many misuses of React Hooks, such as using them inside loops, if statements, ternary and binary conditional expressions, class components and functions that themselves are not hooks or components. Check it out 😄 

Be aware, that due to differences between TSLint and ESLint when it comes to features available in rules, the rule may detect false positives. Take a look at the readme for more information.

**Comment by zheeeng** [comment]
@Gelio Can it detects callback dependencies?

**Comment by Gelio** [comment]
@zheeeng No, unfortunately, it cannot.

I thought about it a few times but due to differences between Eslint and Tslint, the tslint implementation would be non-trivial. I tried to copy Eslint's one, but without success.

If you would like, feel free to implement it yourself and contribute by opening a PR 😄
