### ISSUE TITLE
[Hooks] How useEffects handles arrays comparison when used as a second argument ?

### ISSUE THREAD

**Issue by OBe95** [facebook/react#14324]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
CodeSandbox : https://codesandbox.io/s/nrwq08p9zj (you can see that the console keeps logging into console)

**What is the current behavior?**
Effect re-run endlessly when using an array as a second argument for `useEffect` which is not the case when I use the `array.length` instead

**What is the expected behavior?**
A flexible way to do the comparison to avoid endless (maybe other pointless) effects re-run

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 16.7.0-alpha.2

**Comment by threepointone** [comment]
Hi @OBe95. please provide an example reproducing your issue if you believe this is a bug: https://codesandbox.io/s/new

**Comment by OBe95** [comment]
@threepointone I managed to reproduce with simplified example, please see the updated description above

**Comment by threepointone** [comment]
This is the expected behaviour. the default behaviour of `useEffect`'s second argument is to do a shallow equal check on what's passed in; since you're passing a new array (since getArray returns a new array instance each time) _as the first element of the array_ (ie, it's a nested array), comparing on it will miss the cache and run the effect again. You can work around this by either making sure you pass the same instance of the array, or by passing values that can be compared shallowly in the array. eg - 

```jsx
useEffect(() => {
  /* ... */
}, [someHashingFunction(array)]);
// we could use a hashing function (like murmur3 or md5) to generate a value to compare against 
```

(This also explains why it doesn't rerender when you use `array.length`, since it doesn't change between renders; however *that is buggy*, because it also means your component won't rerender when the array contents change, but with the same length. Don't do this.)

**However**, before doing this so, please be certain you need to do the comparison at all. running the effect every time is usually cheap (like with subscriptions, etc), and you shouldn't look to complicate it with a comparison check if you don't need it. 

Btw, you have a bug in your `App` component, you shouldn't call `setTimeout` directly inside the render function/component, that should be inside a hook as well. 
```jsx 
  useEffect(() => {
    const timeout = setTimeout(() => {
      setArray(getArray());
    }, 500);
    return () => {
      clearTimeout(timeout);
    };
  });
```

Considering this isn't a bug, please check our community support resources for further questions on this: https://facebook.github.io/react/community/support.html

**Comment by OBe95** [comment]
Thanks for your reply @threepointone the `array.length` example was just to make sure I didn't misuse the hook, for the `setTimeout` I actually don't use it, I did it quickly to make a delay so that the hook would run at least one time,

So if we do need to simulate the `componentDidUpdate` using the `effect` hook with immutable nested arrays we need to first come up with a way to identify them

**Comment by threepointone** [comment]
if you're looking to optimize renders for function components based on incoming props, another option is to use `React.memo`, which while defaulting to a shallow equal comparison, also lets you define a custom comparison function, and bails on rerendering on when it returns true. https://reactjs.org/docs/react-api.html#reactmemo

**Comment by OBe95** [comment]
I'll check it, thanks ;)

**Comment by charlax** [comment]
Should this be mentioned in the hooks FAQ btw?
