### ISSUE TITLE
Async useEffect is pretty much unreadable

### ISSUE THREAD

**Issue by linvain** [facebook/react#14326]
![heh](https://user-images.githubusercontent.com/42490556/49019303-ac247f80-f19e-11e8-8ed9-633b4e0628a7.png)

The only alternative is using `then()` chains which aren't very readable at their own.

**Comment by gaearon** [comment]
I think you're making it more complicated than it needs to be.

```js
async function fetchMyAPI() {
  let url = 'http://something';
  let config = {};
  const response = await myFetch(url);
  console.log(response);
}

useEffect(() => {
  fetchMyAPI();
}, []);
```

Longer term we'll discourage this pattern because it encourages race conditions. Such as — anything could happen between your call starts and ends, and you could have gotten new props. Instead, we'll recommend Suspense for data fetching which will look more like

```js
const response = MyAPIResource.read();
```

and no effects. But in the meantime you can move the async stuff to a separate function and call it.

**Comment by lxe** [comment]
What if I need to close over `setSomething(value returned from async)`?

```js 
async function fetchWidgets() {
  return await fetch('./api/widgets').then(r => r.json())
}

// ...
const [widgets, setWidgets] = useState([]);
// Need another async wrapper function to close over `setWidgets`?
useEffect(() => (async () => setWidgets(await fetchWidgets))());
```

**Comment by RiJung** [comment]
@gaearon 
now I should use `useEffect`  instead of `componentDidMount` into a React Component with Hooks.

Scenario "initial unique call to a server":
To accomplished this, DependencyList ( second argument of useEffect) in useEffect should every time an empty array otherwise the application will send every state change a fetch call to the server.

it' means ,  this it the best practise to getData
```typescript
    useEffect(() => {
        console.log("useEffect, fetchData here");
    }, []);
````

Full Code here
<details>

```typescript 
import React, { useState, useEffect } from 'react';

export function CaseAssignDropDown() {
    const [count, setCount] = useState(0);
    useEffect(() => {
        console.log("useEffect, fetchData here");
    }, []);
    /*
    [] -> get data once
    [count] or removed [] -> get data each click
    */
    return (
        <div>
            <p>You clicked {count} times</p>
            <button onClick={() => setCount(count + 1)}>
                Click me
                </button>
        </div>
    );
}
``` 

</details>

**Comment by gaearon** [comment]
Please ask on StackOverflow and feel free to link to your question from here. We don’t use issues for support because answers get lost on GitHub.

**Comment by codeaid** [comment]
`componentDidMount` supports being async so I think useEffect should accept a promise and automatically resolve it to avoid having to `.then` them.

**Comment by gaearon** [comment]
@codeaid It is an intentional design decision. The async/await model is a pitfall for effects in general (and has always been a pitfall in classes!) due to race conditions. In the longer term, Suspense will be the recommended data fetching solution, and you can do `async` / `await` there. But Suspense for data fetching is not ready yet.

**Comment by gaearon** [comment]
@lxe 

As I explained above, `setState(await something()))` is a bad idea because you don't know whether `await something()` is still relevant. For example, if the user starts fetching one profile page but then switches to another profile. Then you're at the mercy of which request arrives first, and can show incorrect data.

This kind of code would handle it correctly:

```js
useEffect(() => {
  let didCancel = false;

  async function fetchMyAPI() {
    let url = 'http://something/' + productId;
    let config = {};
    const response = await myFetch(url);
    if (!didCancel) { // Ignore if we started fetching something else
      console.log(response);
    }
  }  

  fetchMyAPI();
  return () => { didCancel = true; }; // Remember if we start fetching something else
}, [productId]);
```

I'm going to lock this issue as resolved to prevent further confusion. Here's a good article that answers your other questions (e.g. about loading states): https://www.robinwieruch.de/react-hooks-fetch-data/
