### ISSUE TITLE
Knowing when a component has been mounted for the last time

### ISSUE THREAD

**Issue by philip-peterson** [facebook/react#14338]
Hello,

I am writing an application that keeps track of a bunch of component instances. For context, each mounted or could-be-mounted component instance requires reserved memory on a server. In the interest of saving memory, I would like know when a component has been unmounted for the last time (i.e. will never be re-mounted). Is it possible to know this from user-land? And does React even know this information?

Ideally this could be exposed as a "destructor" method call, though I understand why that would be discouraged.

**Comment by aweary** [comment]
> I would like know when a component has been unmounted for the last time (i.e. will never be re-mounted)

This sounds like something you would have to enforce and track yourself. React doesn't know which set of components will be mounted again since that's determined by the your application code and is even potentially non-deterministic.

React doesn't track any information about components which are no longer mounted and it doesn't know which components may be mounted in the future. It only knows what you return from your components.

```jsx
function UserInfo({type}) {
  // React doesn't know about AdminInfo and can't know if it will ever be mounted.
  if (type === "admin") {
     return <AdminInfo />
  }
  return <BasicUserInfo />
}
```

> Ideally this could be exposed as a "destructor" method call, though I understand why that would be discouraged.

`componentWillUnmount` and the cleanup function for `useEffect` could both be considered destructors and serve a similar purpose.

Let me know if I've misunderstood your request here, but I believe the only way to do this would be to enforce those constraints yourself.

**Comment by jquense** [comment]
No components are constructed pretty much one to one with mounting, baring some potentially messy internal things with concurrent mode.

**Comment by jquense** [comment]
I am pretty sure tho once a component is unmounted it's instance is never reused

**Comment by aweary** [comment]
> It seems like React must keep track of components that have been constructed but unmounted which may be re-mounted in the future.

It doesn't, but even if it did this wouldn't let you implement the functionality you wanted. Knowing that a component has been previously mounted doesn't tell you whether a component will be mounted again.

Think about it this way: React has no idea what kind of logic you include in your components. You could be conditionally rendering components based on some non-deterministic value like `Math.random` or something. It only knows what they render, not what they *will* render in the future, so it cannot know whether a component will be mounted again in the future.
