### ISSUE TITLE
Updating provider state does not update consumer

### ISSUE THREAD

**Issue by WhoAteDaCake** [facebook/react#14393]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Consumer does not update together with a provider after the first render

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/wkvww97j7l

**What is the expected behavior?**
Consumer should update after state in provider is modified

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am using react and react-dom 16.5.2

**Comment by markerikson** [comment]
You've got a bug in your example.  You're rendering ``<ResponsiveContext.Provider value={Math.random}>`, which is passing a _reference_ to the function `Math.random`, instead of calling it to create a different value.

Also, when a context provider updates, only the render callback for the consumer is executed.

If I add `console.log("renderChild")`, and fix the provider value, I get this console output:

```
provider 
consumer 
renderChild 
0

provider 
renderChild 
1
```

So, looks good to me.
