### ISSUE TITLE
Strange behaviour with ternary operators and hrefs

### ISSUE THREAD

**Issue by AustinGomez** [facebook/react#14425]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When rendering HTML elements based using a ternary condition, if the element has an onClick method defined, then hrefs do not get removed.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/918pvqz1vw

Click the button, then click the "Click me second" with the blank href. You'll still get directed to the URI specified in the unrendered anchor.

Notice that if you inspect the element you don't see the href in the document tree.
Providing the anchor with a key fixes it.

**What is the expected behavior?**

You should not get redirected to the URI specified in the unrendered anchor.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16, haven't checked other versions yet.

Chrome 70.0.3538.110 64 bit
Safari 12.0.1

**Comment by AustinGomez** [comment]
@heyimalex Right forgot to mention the bit about the key. This is actually how I solved it. Didn't notice the bit about the preventDefault which is actually a better fix!

I haven't checked to see if similar issues happen with other tags yet, but it's possible?

**Comment by heyimalex** [comment]
I think this is expected behavior, even though it's weird on the face. It's consistent with doing the same thing in vanilla js at least, and consistent with how other cascading event handlers work in react.

Re-renders may happen during event handler execution, and subsequent events (or in this case "activation behaviors") will be fired on that same element so long as it's still present in the dom, whether or not it's been updated. You can avoid triggering the subsequent events with `preventDefault` or you can make sure the original target node is unmounted with `key`, like we figured out.

The "surprising" thing here is that the anchor element is re-used, but react's reconciliation is always going to be quirky like this.

**Comment by gaearon** [comment]
>You'll still get directed to the URI specified in the unrendered anchor.

Your link's `onClick` handler flips it back to have a `href` during the click, which is why the link suddenly works.
