### ISSUE TITLE
add for or map directive

### ISSUE THREAD

**Issue by yousefelgoharyx** [facebook/react#14433]
## Adding **map** directive or any others directives would be awesome
instead of making a **js expression** to map an array we could add built in props to the element to apply this features 
i did it but it works only in simple array and i'm trying to find out a way ti make it works on arrays that contains objects

## Snippet
```js
// React.js
function createElement(type, config, children) {
  var propName = void 0;

  // Reserved names are extracted
  var props = {};

  var key = null;
  var map = null;
  var ref = null;
  var self = null;
  var source = null;

  if (config != null) {
    if (hasValidRef(config)) {
      ref = config.ref;
    }
    if (hasValidKey(config)) {
      key = '' + config.key;
    }
    if (config.map){
      map = config.map;
      return map.map((e, i) => {
        return createElement(type, {key: i}, e)
      })
    }

    self = config.__self === undefined ? null : config.__self;
    source = config.__source === undefined ? null : config.__source;
    // Remaining properties are added to a new props object
    for (propName in config) {
      if (hasOwnProperty$1.call(config, propName) && !RESERVED_PROPS.hasOwnProperty(propName)) {
        props[propName] = config[propName];
      }
    }
  }
```
```js
//File.js
const ListMaker = props => {
    let names = ['yousef', 'ahemd', 'mohamed']
    return (
        <div>
            <div map={names}></div>
        </div>
    )
}

const App = () => {
    return (
        <ListMaker />
    )
}


ReactDOM.render(<App/>, document.querySelector('#app'))
```
## At the end
i hope you liked the idea. adding more directives will make react **_easier and prettier_**

**Comment by aweary** [comment]
Thanks for the proposal, but it's unlikely that we'd implement this. One of the advantages of JSX over templating systems is that you can express your logic in code. We don't need a custom DSL for simple logic like mapping. This makes it easy for users who know JavaScript to adopt React, because it uses the knowledge they already have.

While custom directives like `map` might be more terse, they will likely introduce more complexity in the long-term.

Hope that makes sense. Thanks!
