### ISSUE TITLE
Q: When should you NOT use React memo?

### ISSUE THREAD

**Issue by rlesniak** [facebook/react#14463]
I've been playing around with React 16.6.0 recently and I love the idea of React Memo, but I've been unable to find anything regarding scenarios best suited to implement it. The React docs (https://reactjs.org/docs/react-api.html#reactmemo) don't seem to suggest any implications from just throwing it on all of your functional components. Because it does a shallow comparison to figure out if it needs to re-render, **is there ever going to be a situation that negatively impacts performance**?

And second question: as long as everything remains pure, is there ever a situation to not wrap a functional component with React Memo?

Thank you.

**Comment by markerikson** [comment]
I would assume that the same general advice applies for `React.memo` as it does for `shouldComponentUpdate` and `PureComponent`: doing comparisons does have a small cost, and there's scenarios where a component would _never_ memoize properly (especially if it makes use of `props.children`).  So, don't just automatically wrap everything everywhere.  See how your app behaves in production mode, use React's profiling builds and the DevTools profiler to see where bottlenecks are, and strategically use these tools to optimize parts of the component tree that will actually benefit from these optimizations.

**Comment by G-Rath** [comment]
I would also imagine it'd apply to the `useMemo` hook. 

The main thing I'm interested in relating to this question is about the cost of class initialisation (and similar) - It's something that I see just dropped in in couple of places of the React docs by Facebook, without any evidence or references. I'm not challenging Facebook, but I'd love to read more about it, so I can know what they clearly do, and thus optimize my builds.

They do the same with hooks, where they state:

> For example, classes don’t minify very well, and they make hot reloading flaky and unreliable.

Which is the first I've heard of classes messing with hot reloading - in my experience I've not actually ever experienced a working hot reloading system that actually does swap out small chunks of code. That could be b/c I classes everywhere, but I've never in my readings come across anything saying 'classes are screwing up my hot reloading' or 'hey classes cost you ~5kb more than functional components'.

I think a big factor in the answer on when to use `memo` relates to how/when `React` actually does component mounting/initialization. I know that information is on hand in the React docs (and other places), but it's not really mentioned "around" `memo` talks, making it really easy to forget.

From what **I** remember, it's something like "<JSXElement /> does not create a whole new element everytime - thats why mount methods & constructors don't get called every render. Instead, React does some magic to somehow re-use or compare the instance if it exists".

I'm not trying to derail this issue at all (And I do apologize for my ramblings in this comment), but I do feel it'd be nice to have some clear cut examples and discussion about where it's costing you (and saving you) to `memo`. It'd especially be cool to have some extreme examples, with really slow components that are "magically" speed up with memo 😁

**Comment by G-Rath** [comment]
> useMemo has a different use case than React.memo / shouldComponentUpdate / PureComponent. It's not about preventing an entire component from re-rendering, it's about simply memoizing some data. Very unrelated in usage. The only similarity is that React.memo() and useMemo() both involve "if you see the same inputs as last time, don't do any extra work - return what you had before", but React.memo is for wrapping up entire components, and useMemo() is for whatever you want to return from the callback.

You're completely right - that was me being stupid. I've been working too hard lately, and it's left my brain in a muddle 😬 

> I'm not sure what "class initialization" has to do with React.memo

In the hooks FAQ, they have the question [Are Hooks slow because of creating functions in render?
](https://reactjs.org/docs/hooks-faq.html#are-hooks-slow-because-of-creating-functions-in-render), which they state in the answer:

> Hooks avoid a lot of the overhead that classes require, like the cost of creating class instances and binding event handlers in the constructor.

(I do technically mean instancing - sorry about the confusion)

For Facebook to say "the cost of creating class instances" implies to me there is a cost worth mentioning (i.e, compared to the cost of doing something like `const array = []`), but in all my readings about props & cons of classes in JS, I've *never* come across anyone arguing that classes have a 'cost' worth mentioning (which I figured people would jump on, as ES6 classes were a hot topic of debate back when they were introduced).

I'm assuming that the cost is actually one *React* suffers with classes due to how it works, where the cost is only a factor when you're creating lots of class instances in the space of seconds all the time, but again, this isn't something I recall seeing explored or talked about in detail in the rest of the React documents.

Thanks for the links - I've not encountered them before, despite my best efforts 😕 You've given me some good reading to do!

**Comment by markerikson** [comment]
In React 15 and earlier, function components were wrapped in classes internally, so there was no real difference in perf behavior.

In React 16, function components are now handled separately, with no class wrapping them.  This means there's less overhead to rendering a function component overall than for a class component.  References:

[Dominic Gannaway](https://twitter.com/trueadm/status/916706152976707584):

> Functional components should be slightly faster in React 16 as there's no instance created to wrap them (unlike React 15).

[Andrew Clark](https://twitter.com/acdlite/status/964662881529679872): 

> Think of all the features class components have that we can totally skip with functional components. Constructors, refs, lifecycles, error handling. The only reason they were the same performance-wise before Fiber was technical debt in the the Stack implementation.

So, in general, an app that consistently renders N function components should take less total time to render than an app that renders N class components.  How _much_ less, I have no idea - you'd have to benchmark things.

However, all of that is mostly separate from the original question of "when should I use `React.memo()`?"

**Comment by TidyIQ** [comment]
Can someone please explain (like I'm 5) WHY it's a bad idea to wrap all components in React.memo? If the props on a component haven't changed then it shouldn't re-render as it will simply be returning the exact same component as the initial render.

I also don't understand why the [react docs](https://reactjs.org/docs/react-api.html#reactmemo) say `Do not rely on it to “prevent” a render, as this can lead to bugs.` What bugs? Why else would you use React.memo if not prevent an unnecessary re-render?

For example, on my main index page I include a `<Header>` component that takes in `title` and `metaDescription` as props. These props never change for the page so the Header component shouldn't re-render whenever something else is changed. It seems the only way to do this is by wrapping the Header component in React.memo, but apparently the docs imply this is the incorrect use.

**Comment by StoneCypher** [comment]
@markerikson -

> So, in general, an app that consistently renders N function components should take less total time to render than an app that renders N class components. How much less, I have no idea - you'd have to benchmark things.

[Dramatically, it seems](https://www.youtube.com/watch?v=PnpfGy7q96U).

**Comment by lukewlms** [comment]
[Here's the best info I've found on this](https://medium.com/@trekinbami/using-react-memo-and-memoization-1970eb1ed128).  Seems like there are few cases where you _wouldn't_ want to use `React.memo`, theoretically.  Though the significant extra typing in every component seems clunky.

Perhaps your parent component rerenders regularly and your child component does something impure like render the current time or fetch some data... though I'd think hooks would cover both of those well.

**Comment by panzerdp** [comment]
Regarding when to use React.memo(), I wrote [an interesting blog post](https://dmitripavlutin.com/use-react-memo-wisely/). Check it out.

I use the following rule of thumb:

> The more often the pure functional component re-renders with the same props, the heavier and the more computationally expensive the output is, the more chances are that component needs to be wrapped in `React.memo()`

**Comment by mikeaustin** [comment]
I always use PureComponent for class based components. It's easy, and it just works. I've noticed that if I don't wrap basically all my components in memo(), nothing gets optimized. And since children are part of props, I had a rouge non-memoized component that cause everything to re-render().

I'm trying to like hooks, and some of them are useful, but the mental overhead is actually large. Ract.memo(), useCallback(), useState(), useRef(), useMemo(), useContext(), all used together in a < 100 line fine gets a bit hard to read. An example I've created to optimize dragging, which has a hooks version and a class version:

https://github.com/mikeaustin/optimized-drag/tree/master/src

**Comment by fbartho** [comment]
It’d be great if there was a helper to let you diff everything except for children, and have React handle diffing Children.

**Comment by ardok** [comment]
If you really, really want it... You could technically put the children into `useMemo`...

```
const Foo = React.memo(({ children }) => {
  return children;
});

const Hello = () => {
  const childrenTest = useMemo(() => {
    return (
      ...children here...
    );
  }, [...to watch for changes, call it AAA...]);
  return (
      <Foo {...AAA}>{childrenTest}</Foo>
  );
}
```

**Comment by syntaxbliss** [comment]
Let us say that we have a case like this one:

```
const MyComponent = React.memo(({genre, name}) => {
    const someFunction = genre => {
        return (genre === 'male') ? 'Mr.' : 'Ms.';
    }

    return (
        <h1>Hello {someFunction(genre)} {name}!</h1>
    );
});
```

Does it worth to create a memoized functional component when it has an additional function? Does that additional function also get memoized, or in that case I would be slowing down things by creating a new function on every render? In this example, would be better to move on to a class-based component?

**Comment by Bohmaster** [comment]
> Let us say that we have a case like this one:
> 
> ```
> const MyComponent = React.memo(({genre, name}) => {
>     const someFunction = genre => {
>         return (genre === 'male') ? 'Mr.' : 'Ms.';
>     }
> 
>     return (
>         <h1>Hello {someFunction(genre)} {name}!</h1>
>     );
> });
> ```
> 
> Does it worth to create a memoized functional component when it has an additional function? Does that additional function also get memoized, or in that case I would be slowing down things by creating a new function on every render? In this example, would be better to move on to a class-based component?

I think you need to use 'useCallback' to memoize the extra function, pajarito.

**Comment by ajaysaini-sgvu** [comment]
+1

**Comment by ajaysaini-sgvu** [comment]
@Bohmaster I think he is not using someFunction as a callback to the child component. `useMemo` should work here. 

What do you think ?

**Comment by ford04** [comment]
@syntaxbliss `React.memo` will skip re-rendering the component for same props and instead take the previous memoized ReactElement "snapshot". It's like React does not call the `MyComponent` function again for re-render, but take its last result.

Perhaps a bit more clear statement is: the resulting ReactElement/JSX element, to which your inner `someFunction` function contributed something, is memoized.

I would not care about [function creation cost in render](https://reactjs.org/docs/hooks-faq.html#are-hooks-slow-because-of-creating-functions-in-render) for `someFunction`. Also you pass this inline function only  to a primitive DOM node, so there is no need to ask yourself, if memoization gets broken due to creating a new function reference each render.

Maybe [this answer](https://stackoverflow.com/a/61547432/5669456) also helps you to decide, if  `React.memo` is worth it for your case.

**Comment by marcelkalveram** [comment]
> Can someone please explain (like I'm 5) WHY it's a bad idea to wrap all components in React.memo? If the props on a component haven't changed then it shouldn't re-render as it will simply be returning the exact same component as the initial render.

I'm just guessing based on what I know, but since not everyone using React embraces **immutability**, there might be cases where someone passes `data` into a non-memoised `ChildComponent`, then mutates that `data` (an object or array) and expects that component to re-render, ie. because its parent did.

As soon as you memoise that `ChildComponent` using `React.memo`, the mutated `data` won't trigger a re-render because of referential equality, even though its parent did re-render. 

The other potential downside of `React.memo` is the work that goes into shallow comparison, even though for most apps that's probably negligable.

**Comment by MaxmaxmaximusAWS** [comment]
@StoneCypher  @fbartho @mikeaustin @marcelkalveram @gaearon @rlesniak

You should always use `React.memo`ac LITERALLY, as comparing the tree returned by the Component is always more expensive than comparing a pair of props = properties)

So don't listen to anyone and wrap ALL functional components in `React.memo`. React.memo was originally intended to be built into the core of functional components, but it is not used by default due to the loss of backward compatibility. (Since it compares the object superficially, and you MAYBE in the component, use the nested properties of the sub-object) =)

That's it, this is the ONLY REASON why React doesn't use memo Automatically. =)

In fact, they could make version 17.0.0, which would BREAK backward compatibility, and make React.memo the default, and make some kind of function to CANCEL this behavior, for example React.deepProps =)

Stop listening to theorists, guys =) The rule is simple:

If your component USES DEEP COMPARING PROPS then don't use memo, otherwise ALWAYS USE, comparing TWO OBJECTS is ALWAYS CHEAPER than calling React.createElement () and comparing two trees, creating FiberNodes, and so on.

Theorists talk about what they themselves do not know, they have not analyzed the react code and do not understand what they advise =)

Everyone please ^ __ ^

**Comment by MaxmaxmaximusAWS** [comment]
@StoneCypher and @mikeaustin

Prove your arguments, or the whole community will see that you, you could not win the PUBLIC COURT, and cowardly put dislikes. WHAT EXACTLY arguments COULD you counter my arguments?

WE as the whole React community listen to your counterarguments =))

Let's laugh right now =)

**Comment by StoneCypher** [comment]
Please stop tagging me

**Comment by MaxmaxmaximusAWS** [comment]
@StoneCypher @fbartho @mikeaustin @marcelkalveram @gaearon @rlesniak @sunny @panzerdp

But I want to teach you the truth)? I don't want you to live in misconceptions about React.memo, why don't I hear gratitude, but get dislikes? I sat, wrote, explained, tried, did you all GOOD. And he did not A SINGLE EVIL. And you are NOT GRATEFUL to me FOR GOOD, but you are doing EVIL: put dislikes. Why are you FOR GOOD - answer with EVIL? are you **just EVIL** ????

![image](https://user-images.githubusercontent.com/69426460/90287010-a5acce80-de7f-11ea-86bf-f03c86da475f.png)

**Comment by sunny** [comment]
Please stop tagging me too, I was never in the conversation in the first place -_-

**Comment by MaxmaxmaximusAWS** [comment]
@sunny strange, apparently this is a GitHub bug

**Comment by rickhanlonii** [comment]
@MaxmaxmaximusAWS please stop tagging people in this thread.

**Comment by MaxmaxmaximusAWS** [comment]
@richardjrossiii Why shouldn't I be tagging people to whom I communicate?

**Comment by slavafomin** [comment]
To be honest, I would actually like to hear another opinion on what Mr. Maxmaxmaximus wrote in his first message (all trolling and jokes aside). It actually makes sense that comparing couple of props shallowly should consume less resources than executing the render function with all the hooks in it and building the JSX for the component (and all the sub-components). Strong/strict comparison (===) is a very simple operation.

Also, could you explain to me, will React always compare entire virtual DOM trees or only the parts that actually changed? So if I exclude the part of the virtual DOM tree using `React.memo` will it actually be excluded from reconciliation process? Or is it just skips the JSX generation? I guess the second, but I would like to hear a confirmation from someone more knowledgeable.

Thank you!

**Comment by MaxmaxmaximusAWS** [comment]
> I guess the second, but I would like to hear a confirmation from someone more knowledgeable.

1) React call component function
2) React looks what elementts and components returned from function
3) React create FiberNodes for all returned elements and components
4) React call `fiberNode.execute()` for all created fiberNodes
5) What returned from `fiberNode.execute()` function, react will "substitute" this for the fiber node
6) `FiberNode.execute()` has optimisation. if you use `React.memo()` then `fiberNode.execute()` returns previous result (fibers nodes thee), and call `FiberNode.execute()` to all returned fiberNodes

**Comment by sunny** [comment]
Again, please stop mentioning me…

**Comment by MaxmaxmaximusAWS** [comment]
![image](https://user-images.githubusercontent.com/69426460/95571757-9c7c5000-0a31-11eb-830e-97c708d0a7e7.png)

**Comment by sunny** [comment]
Considering that several people have asked you to stop tagging them and that your comments have been tagged as disruptive, I'd wager you are the one with inappropriate, irrational behavior. 

> If you receive notifications, turn them off in the settings

I've blocked you. This is the first time in 12 years of GitHub that've had to do that… Please listen to what people are telling you and [act more professionally](https://github.com/facebook/react/blob/master/CODE_OF_CONDUCT.md).

**Comment by vzaidman** [comment]
I want to point out that from my experience, people often fall into one of the three categories:
1. people who don't have an idea of what `memo` is
2. people who use memo almost everywhere
3. people who try adding it in places that are expected to benefit from it

All of them usually forget some super important components here and there that get rendered again and again-
The website's `Header` is a classic example. Sometimes these places also have logic and side effects. and sometimes they are rendered many times in

I think the biggest benefit of making everything pure is "keeping it simple" and removing this feature altogether even if in some cases it would make the application a little slower.

**Comment by MaxmaxmaximusAWS** [comment]
@vzaidman React.memo actually have second argument for deep comparatiom. for this reason we have to use React.memo everywhere

```js
function MyComponent(props) {
  /* рендер с использованием пропсов */
}
function areEqual(prevProps, nextProps) {
  /*
  возвращает true, если nextProps рендерит
  тот же результат что и prevProps,
  иначе возвращает false
  */
}
export default React.memo(MyComponent, areEqual);
```

**Comment by vzaidman** [comment]
This would be an overkill in 99& of the cases

**Comment by MaxmaxmaximusAWS** [comment]
People should use `useCallback` for callbacks, to become `memo`  works.
Apollo and React native hooks, actually use `useCallback`. This is a problem for bad developers, and it should not drag us back, but it should push them forward. they should think "hmmm, but memo won't work for child components, if there is a memo, you shouldn't be lazy and wrap my callback in useCallback."

**Comment by suraj813** [comment]
Due to violations of our [code of conduct](https://engineering.fb.com/codeofconduct/), we are putting a temporary block on the user @MaxmaxmaximusAWS for two weeks.

**Comment by KurtGokhan** [comment]
Shouldn't `memo` be the default with Function Components, or provide an option to make it the default? Has this ever came up as a plan? IMO, writing `memo` everywhere makes the code verbose and does not behave very well with IDEs and Typescript. I have the same issue with `forwardRef` but at least that is not everywhere.

**Comment by markerikson** [comment]
@KurtGokhan the question has been asked repeatedly, in many places :)  and my answer at the very top of this thread still applies. There are a number of cases where components will _never_ memoize because the inputs are always changing.

Also see my additional thoughts here, with some quotes from Dan:

https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#memoize-everything

**Comment by KurtGokhan** [comment]
Sorry for resurrecting this thread @markerikson. Just wanted to confirm if this is ever planned in the future. To me it seems like not using memo is more prone to performance issues. Especially when you realize that a state change in your root component will cause entire tree to re-render if you don't memo at all. But maybe that just sounds scary and it is actually not that bad.

When asked this question, most people emphasize that it is prone to bugs caused by mutable state (which is arguably not the intended way to use React). I now understand that there can also be performance hits by blindly using memo.

**Comment by pauldraper** [comment]
This answered in [React docs](https://react.dev/reference/react/memo):

> Optimizing with memo  is only valuable when your component re-renders often with the same exact props, and its re-rendering logic is expensive...
>
> There is no benefit to wrapping a component in memo in other cases. There is no significant harm to doing that either, **so some teams choose to not think about individual cases, and memoize as much as possible.**

1. React.memo will sometimes help performance
2. React.memo will sometimes do nothing for performance.
3. In either case, React.memo is essentially free. (Very quick to check props equality.)

The biggest reason IMO React.memo is not enabled by default is that it can break rendering when props are mutable. However, it is best practice to not use mutable props in the first place.

---

React.memo is ineffective if the props change each render, e.g.

1. Callers pass event handlers that aren't created with `useCallback`.
2. Callers pass other non-primitives (objects, arrays) that aren't created with `useMemo`.
3. Callers pass children that aren't created with `useMemo`.

That said, the cost is essentially nothing and it is up the *caller* to change passed props. IMO the callee should always use React.memo, and if the caller wants to take advantage of that, it can.

**Comment by Shay-repos** [comment]
> Due to violations of our [code of conduct](https://engineering.fb.com/codeofconduct/), we are putting a temporary block on the user @MaxmaxmaximusAWS for two weeks.

coward

**Comment by gsathya** [comment]
I've removed the previous comment as it violates our [code of conduct](https://opensource.fb.com/code-of-conduct/). As this thread has seen extensive on-topic discussion and is now becoming outdated, I'm going to lock it.
