### ISSUE TITLE
Expose ReactLink.PropTypes.link

### ISSUE THREAD

**Issue by jgebhardt** [facebook/react#1447]
React.addons only exposes LinkedStateMixin. What's the best way to expose ReactLink.PropTypes.link?
Options I can think of:
- mutate React.PropTypes as a side-effect of including the Mixin
- expose directly on React.addons.PropTypes

**Comment by jimfb** [comment]
ReactLink is getting deprecated as per https://github.com/facebook/react/issues/2302.  Also, proptypes are on their way out in favor of flow.

If this is something you would find useful, I would recommend creating a custom proptype validator and publishing it to npm so other people can use it.  Since this is not something we plan on supporting in the core, I'm going to go ahead and close out the issue.
