### ISSUE TITLE
hoc nested result in infinite loop

### ISSUE THREAD

**Issue by ysyzqq** [facebook/react#14472]
when nest a hoc multiply times with the same variable it occurs
i wrappered the AutoData component twice, but when i use redux to connect a stateless component at second time to overlap the HigherOrderComponent variable , it result in infinite loop
![image](https://user-images.githubusercontent.com/20273940/50270241-e3b7dc00-046b-11e9-8355-13cccfe77de9.png)
but if i use the stateful component it success
![image](https://user-images.githubusercontent.com/20273940/50269913-d8b07c00-046a-11e9-9ac6-7e23ff8a93e9.png)
can someone explain why

**Comment by jquense** [comment]
in the first case the value of `HigherOrderComponent` is changed by the time the render is called, because you are assigning to it via `connect`, what's happening is you are trying to endlessly render itself. A subtle thing to notice here, but how closures work in JavaScript

Change this line: `HigherOrderComponent = connect(...)` to `const ConnectedComponent = = connect(...)` and it will work, as well as give you a hint as to what is ultimately wrong
