### ISSUE TITLE
'setState' error while use 'useEffect'

### ISSUE THREAD

**Issue by ddzy** [facebook/react#14486]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![issue_bug_1](https://user-images.githubusercontent.com/33921398/50380104-ed258c00-0697-11e9-9bd5-c82372dbc3f0.jpg)
![issue_bug_2](https://user-images.githubusercontent.com/33921398/50380106-f57dc700-0697-11e9-9861-96360ed37e04.jpg)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
I want to update state when I componentdidmount, but it can lead to errors, and I don't know what to do.
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
![issue_bug_3](https://user-images.githubusercontent.com/33921398/50380125-8654a280-0698-11e9-8c00-0b727d2f31cc.jpg)

**Comment by markerikson** [comment]
Your current code is calling `setState()` _every_ time the component re-renders.  Since `setState()` queues a re-render, you're creating an infinite update loop.

In order to have this happen _only_ the first time the component renders, you need to pass an empty array as the second argument to `useEffect()`.

I'd encourage you to read the Hooks docs thoroughly to better understand how to use them correctly:

https://reactjs.org/docs/hooks-intro.html

**Comment by ddzy** [comment]
> Your current code is calling `setState()` _every_ time the component re-renders. Since `setState()` queues a re-render, you're creating an infinite update loop.
> 
> In order to have this happen _only_ the first time the component renders, you need to pass an empty array as the second argument to `useEffect()`.
> 
> I'd encourage you to read the Hooks docs thoroughly to better understand how to use them correctly:
> 
> https://reactjs.org/docs/hooks-intro.html
Thks, it has been solved, i think i have to read the docs again....😊
