### ISSUE TITLE
npm install from package.json sets enableHooks false

### ISSUE THREAD

**Issue by talkingtab** [facebook/react#14489]
npm init -y
npm install --save react@16.7.0-alpha.2 
node_modules/react/cjs/react.development.js has enableHooks=true
rm -rf node_modules/react
npm install

node_modules/react/cjs/react.development.js has enableHooks=false

**Comment by beheh** [comment]
This is because `npm install --save react@16.7.0-alpha.2` specifies `^16.7.0-alpha.2` in `package.json`. Note the `^` which indicates you want the latest semver-compatible version.

You can fix this by either changing your dependency from `^16.7.0-alpha.2` to `16.7.0-alpha.2` in your `package.json`, or by running `npm install --save-exact react@16.7.0-alpha.2` instead of `--save`.

**Comment by talkingtab** [comment]
Thanks *very* much! Duh!
