### ISSUE TITLE
Hooks performance problem when passing only event handler into component

### ISSUE THREAD

**Issue by budarin** [facebook/react#14482]
**Do you want to request a *feature* or report a *bug*?**
No.

**What is the current behavior?**
When I pass a eventHandler memoized with useCallback it forces component render every time when a memoization parameter is changed. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Here is link to [sandbox ](https://codesandbox.io/s/l5wrq94y37)
Every time we click on the button the Content is rendered when it should not.

**What is the expected behavior?**
Event handler should not force a component to render every time when a memoize parameter is changed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

OS: any
"react": "^16.7.0-alpha.2",
"react-dom": "^16.7.0-alpha.2",

**Comment by heyimalex** [comment]
> Event handler should not force a component to render every time when a memoize parameter is changed.

Why not? The handler changes, which means that the component needs to be re-rendered to attach the new handler.

**Comment by heyimalex** [comment]
The `togleSideBarButtonHandler` actually changes depending on the value of `isSideBarVisible`. If Content _didn't_ re-render, multiple clicks wouldn't toggle `isSideBarVisible` because the old callback would still be used. Render needs to be called again to update that callback.

In any case, you can use the [functional version of set state](https://reactjs.org/docs/hooks-reference.html#functional-updates) and pass `[]` so that the callback never changes. [Here's a codesandbox with that change.](https://codesandbox.io/s/o9onp0lv6y)

**Comment by budarin** [comment]
thanks!
It helped. 
This should be mentioned in docs - I hav'n caught it inthe docs
