### ISSUE TITLE
Lazy useRef instance variables

### ISSUE THREAD

**Issue by Diokuz** [facebook/react#14490]
I want to save a class instance, not just plain object, with `useRef` hook. And, I dont want to construct it each time hook function is invoked.

Is it possible to do that?

My thoughts were:

```js
const instanceRef = useRef(() => new Instance())
```
But `useRef` does not accept the _initial value_ as a function (`useState` and `useReducer` could do that).
Will that change in _alpha 3_?

**Comment by nikilok** [comment]
@Diokuz useRef does take in an initial state.

https://reactjs.org/docs/hooks-reference.html#useref

In the above link, they just pass `null` as the initial value.

**Comment by Diokuz** [comment]
@nikilok yes, but the question was about how to create lazy initial value (create it only once).

My current solution is:
```js
const [refInitialValue] = useState(() => new Instance)
const instanceRef = useRef(refInitialValue)
```

but that is a bit overhead.

**Comment by TrySound** [comment]
@Diokuz Just check its existence
```js
const instance = React.useRef(null)
if (instance.current == null) {
  instance.current = {
    // whatever you need
  }
}
```

**Comment by jamiewinder** [comment]
I created this custom hook to help with this limitation, someone might find it useful:
```typescript
import { useRef } from 'react';

const SENTINEL = {};

export function useRefFn<T>(init: () => T) {
    const ref = useRef<T | typeof SENTINEL>(SENTINEL);
    if (ref.current === SENTINEL) {
        ref.current = init();
    }
    return ref as React.MutableRefObject<T>;
}
```

**Comment by Kovensky** [comment]
It happens to work in this case because your function is generic and so T is "like {}", but you need to use a Symbol for sentinels to create a `unique symbol` type. Using an empty object's type as an input makes it nearly the same as `any` but without `null | undefined`.

**Comment by jamiewinder** [comment]
Sorry, I'm not following. It would work for null, undefined, or any value as far as I can see. 

I use an empty object as the sentinel as it makes it unique and distinct for the ===  check which sets the ref to the real initial value on the first invocation. It'd work it the sentinel were a symbol too, but I don't think it makes a difference one way or the other?

**Comment by jamiewinder** [comment]
Late realisation: doesn't useMemo (with an empty array as the second parameter) do exactly this?

**Comment by gaearon** [comment]
`useMemo` with `[]` is **not** recommended for this use case. In the future we will likely have use cases where we drop `useMemo` values — to free memory or to reduce how much we retain with e.g. virtual scrolling for hidden items. You shouldn't **rely** on `useMemo` retaining a value.

We talked more about this and settled on this pattern as the recommendation for expensive objects:

```js
function Foo() {
  const instanceRef = useRef(null)

  function getInstance() {
    let instance = instanceRef.current;
    if (instance !== null) {
      return instance;
    }
    // Lazy init
    let newInstance = new Instance()
    instanceRef.current = newInstance;
    return newInstance;
  }

  // Whenever you need it...
  const instance = getInstance();
  // ...
}
```

Note how you can declare `getInstance()` as `: Instance` — it's easy to guarantee it's never `null`.

So you both get type safety and delay creation until the object is *actually* necessary (which may happen conditionally during rendering, or during an effect, etc).

Hope this helps!

**Comment by gaearon** [comment]
https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily

**Comment by ghengeveld** [comment]
How about:

```js
const [myRef] = useState(() => ({ current: calculateInitialValue() }))
```

Is there any reason not to "abuse" `useState` like that?

**Comment by mgtitimoli** [comment]
```
// @flow

import {useRef} from "react";

type HookRef<Value> = {|
  current: Value
|};

const noValue = Symbol("lazyRef.noValue");

const useLazyRef = <Value>(getInitialValue: () => Value): HookRef<Value> => {
  const lazyRef = useRef(noValue);

  if (lazyRef.current === noValue) {
    lazyRef.current = getInitialValue();
  }

  return lazyRef;
};

export default useLazyRef;
```

**Comment by wearhere** [comment]
I second @ghengeveld's question [above](https://github.com/facebook/react/issues/14490#issuecomment-476000536) about "abusing" `setState` for this purpose especially given Dan's comment [here](https://twitter.com/dan_abramov/status/1099842565631819776?s=20) saying that `useRef` is basically `useState` anyway. @gaearon, could you clarify?

**Comment by ghengeveld** [comment]
The benefit of Dan's approach is that the instance is created once, at the point where it's going to be used (if at all), while my solution just instantiates/creates it immediately (also only once). I think my pattern is fine if you know for certain you are going to need the value. Unless there is a reason to avoid this trick, like there is for useMemo?

**Comment by peterjcaulfield** [comment]
You can also just pass a function that mutates a ref to `useMemo` without being at risk of changing semantics WRT retained values:

```
const initialiseRef = (ref: React.mutableRefObject<T>) => {
     if (!ref.current) {
         ref.current = init();
     }
}

// ...
const ref = useRef(null)
useMemo(() => {
    initialiseRef(ref)
}, [])
```

The handy thing about this is that you can also re-run initialisation of the ref if needed by supplying deps.

**Comment by alamothe** [comment]
Usually we want to change `ref.current` (isn't this exactly why refs are for?), so I don't see much practical value in the `getInstance` approach. 

The `useState` solution is very natural and exactly what's needed. 

But ideally, React should just improve `useRef` to accept a lazy init.

**Comment by alii** [comment]
fwiw, published a hook for this under the npm package `alistair` and can be used as `import {useLazyRef} from 'alistair/hooks';`

src: https://github.com/alii/alistair/blob/master/src/hooks/use-lazy-ref.ts

**Comment by panta82** [comment]
Is this still the recommended approach?

I am getting bugs with react-refresh hot updates, when I'm using lazy ref init with a `useEffect()` that clears the data.

Eg.

```javascript
if (!editorRef.current) {
  editorRef.current = new Editor();
}
useEffect(() => {
  return () => {
    if (editorRef.current) {
      editorRef.current.destroy();
      editorRef.current = null;
    }
  };
}, []);
```

During hot reload, `editorRef.current.destroy()` gets called but there is no another render after, so editor doesn't get reinitialized.

**Comment by panta82** [comment]
Thanks @gaearon. I have indeed moved ref initialization into `useEffect`, and that has solved my problem.

In general, the solution with useEffect isn't 100% ideal because you don't have the ref instance available during the initial render. However, I was able to work around that in my use case.

For curiosity's sake, here's a sandbox with the repro of what I think was happening: https://codesandbox.io/s/musing-kowalevski-3omfcs?file=/src/App.js You can trigger hot refresh by adding a comment or similar.

**Comment by gaearon** [comment]
> you don't have the ref instance available during the initial render. 

That’s right. But that’s on purpose.

Renders in React are supposed to be discardable. For example, with Suspense, if a newly mounting part of the tree suspends, React 18 will throw it away and add a placeholder instead. That tree never had a chance to mount so we don’t fire its cleanup. So if your instance _requires_ to be destroyed you would have a memory leak. 

Delaying its creation to effect avoids that problem. Another way to avoid that problem is to split the external thing apart. The part that doesn’t consume resources (which is free to discard) is created during first render. The part that consumes resources (for example, creates a subscription) is created in the effect.

Hope this helps.

**Comment by panta82** [comment]
@gaearon Understood. Thank you.

**Comment by OliverJAsh** [comment]
This seems like a common requirement so is there a reason why we can't update `useRef` to accept a function as suggested in the original post?

**Comment by garretwilson** [comment]
> Delaying its creation to effect avoids that problem.

@gaearon I'm still unclear what "problem" will be caused if we immediately initialize the reference as @TrySound [suggested](https://github.com/facebook/react/issues/14490#issuecomment-449729465):

```javascript
const instance = React.useRef(null)
if (instance.current == null) {
  instance.current = {
    // whatever you need
  }
}
```

Will that cause any potential issues? Or were you comparing the "delay creation until effect" approach with something else?

**Comment by vincerubinetti** [comment]
Since it's sorta only implicitly stated throughout this thread, I wanted to clarify some issues.

The [new React docs suggest one of Dan's methods above](https://18.react.dev/reference/react/useRef#avoiding-recreating-the-ref-content):

```
function Video() {
  const playerRef = useRef(null);

  function getPlayer() {
    if (playerRef.current !== null) {
      return playerRef.current;
    }
    const player = new VideoPlayer();
    playerRef.current = player;
    return player;
  }
```

But then if you use TypeScript, `playerRef` will need to be of type `Ref<VideoPlayer | null>` instead of `Ref<VideoPlayer>` which it really is. I don't think this can be fixed without suppressing type errors or type casting somewhere (not ideal), or by checking if `.current` is null everywhere you use it (very tiresome).

@jamiewinder's `SENTINEL` solution above seems to achieve the same functionality, with type safety (though idk why it's called "sentinel"... "empty"/"nullish"/"nonce" would be more clear?) by creating a singleton object with the same type as the type you want, but "empty" in some sense. This assumes there exists an appropriate "empty" value for the type you want that works for your use case.

**Comment by jantimon** [comment]
@tippfelher
> @everyone_else: Use this when your ref initializers never return null.

Just use an empty object instead of `null` 

It will work for all values as another object will have a different reference (`{} !== {}`)

```tsx
// useLazyRef.ts
import { useRef } from 'react';
const INITIAL = {};
export function useLazyRef<T>(initializer: () => T) {
   const ref = useRef<T>(INITIAL as T);
   if (ref.current === INITIAL) {
     ref.current = initializer();
 }
 return ref;
}
```
 
```tsx
const numberRef1 = useLazyRef(() => 123);
// good: numberRef1 is of type React.RefObject<number>
const numberRef2 = useLazyRef<number>(() => 123);
// good: numberRef2 is of type React.RefObject<number>
const nullable = useLazyRef(() => null);
// good: nullable is of type React.RefObject<null>
const failRef2 = useLazyRef<boolean>(() => 123);
// good: TS error
```

**Comment by gmoniava** [comment]
@gaearon Dan, from your [comment](https://github.com/facebook/react/issues/14490#issuecomment-454973512) above, here:

```
function Foo() {
  const instanceRef = useRef(null)

  function getInstance() {
    let instance = instanceRef.current;
    if (instance !== null) {
      return instance;
    }
    // Lazy init
    let newInstance = new Instance()
    instanceRef.current = newInstance;
    return newInstance;
  }

  // Whenever you need it...
  const instance = getInstance();
  // ...
}
```

Can this part:  `new Instance()` be **impure**?

I can't tell because docs use `new VideoPlayer()` [example](https://react.dev/reference/react/useRef#avoiding-recreating-the-ref-contents) which might imho be _impure_.
