### ISSUE TITLE
Suggestion: useProvider for replacing context.Provider

### ISSUE THREAD

**Issue by rabbitooops** [facebook/react#14534]
```js
function App(props) {
  const [theme] = useState({color: 'white'})
  const [user] = useState({name: 'rabbit'})
  useProvider(themeContext, theme)
  useProvider(userContext, user)

  /* ... */
}
```
is equivalent to
```js
class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      theme: {color: 'white'},
      user: {name: 'rabbit'}
    }
  }
  render() {
    return (
      <themeContext.Provider value={this.state.theme}>
        <userContext.Provider value={this.state.user}>

        </userContext.Provider>
      </themeContext.Provider>
    )
  }
}
```

**Comment by gaearon** [comment]
Providers intentionally don't work this way because the notion of tree structure actually has a meaning (unlike Hooks). Your proposals makes it more difficult to move code between components because any Hook could contain a `useProvider` call inside, invisibly affecting everything below.

**Comment by olee** [comment]
I still think this is a valid suggestion and even considering the issue you described does not outweighs the pros in my opinion.
Even Vue added this to their draft for "hooks": https://github.com/vuejs/rfcs/blob/function-apis/active-rfcs/0000-function-api.md#dependency-injection
Being able to provide context values down the tree using a hook instead of a wrapper component would open soo many more possibilities that this should definitely be evaluated again!

**Comment by nhusher** [comment]
> Providers intentionally don't work this way because the notion of tree structure actually has a meaning (unlike Hooks like `useState`). Your proposal makes it more difficult to move code between components because any Hook could contain a `useProvider` call inside, invisibly affecting everything below.

I don't understand this objection, can you speak further? 

It seems like a `useProvider` hook would be difficult to compose, which is true, but I could say the same about `useEffect`. Any hook that has `useEffect` within it could invisibly affect *any* node in the DOM, which seems like a failure of compositionality akin to `useProvider`. In practice it works fine, because it's clear from the docs that `useEffect` has some dangerous properties.

**Comment by csr632** [comment]
I have created a [state management library](https://github.com/csr632/react-hook-svs) that is better at service composition. [Here is a demo of avoiding provider hell](https://codesandbox.io/s/github/csr632/react-hook-svs/tree/master/src?fontsize=14&hidenavigation=1&module=%2Fdemos%2Fcomposition.tsx&moduleview=1&theme=dark). Feel free to try it or read its source(100 lines of code)!

It introduce a "scope" object to collect the context provider, so that:
- Services can be isolated or composed, depending on whether they are in same scope.
  - Services can consume former services in same scope, despite that they are in the same component.
- All the providers collected by a scope can be provided at onece, avoiding provider hell.
- The "parent scope & child scope" structure will form a "tree" to resolve requests properly.

**Comment by TotooriaHyperion** [comment]
> Providers intentionally don't work this way because the notion of tree structure actually has a meaning (unlike Hooks like `useState`). Your proposal makes it more difficult to move code between components because any Hook could contain a `useProvider` call inside, invisibly affecting everything below.

Yes it's not a good pattern to make provider a hook, but why not attach all the Contexts to the root element of the Component? It don't break the tree structure.

Or make a multiple provider:
```
<Providers contexts={[
  [Context1, value1],
  [Context2, value2],
]}>
  {children}
</Provide>
```

similar to
```
@Module({ Providers: [Context1, Context2]})
class Component {}
```

**Comment by TotooriaHyperion** [comment]
Try react-multi-provide

https://github.com/facebook/react/issues/14534#issuecomment-700510943
