### ISSUE TITLE
suggest key prop can be passed to components

### ISSUE THREAD

**Issue by xp44mm** [facebook/react#14584]
i don't make understand that Keys serve as a hint to React but they don’t get passed to your components. 
this feature in https://reactjs.org/docs/lists-and-keys.html need pass the key two times. this action is not friendly to users. has any difficulty to implement this feature or is there another reason?
```javascript
const content = posts.map((post) =>
  <Post
    key={post.id}
    id={post.id}
    title={post.title} />
);
```

**Comment by markerikson** [comment]
`key` and `ref` are kind of like "reserved pseudo-props".  They don't ever actually get passed to a component - they're an instruction to React for how it should handle working with that component.

**Comment by ivansky** [comment]
It looks right cause you use it for two absolutely different reasons as already said above.
So you have to pass it twice to use `id` inside component.

**Comment by gaearon** [comment]
It actually used to work the way you describe, but we intentionally separated them and made them invisible to components. The rationale is what @jamiewinder described — making them visible in components led to bugs caused by particular assumptions about usage. 

For example you may start with 1:1 mapping between key and ID:

```js
<b>Your comments:</b>
{comments.map(comment =>
  <Comment id={comment.id} text={comment.text} key={comment.id} />
)}
```

 but then might want to show comments with the same ID in one array:

```js
  <b>Comment edit history:</b>
  {comment.versions.map(version => (
    <Comment id={comment.id} text={version.text} key={version.id} />
  )}
```

If `id` and `key` weren't separate this would require a refactoring. React forces you to do it early so you don't run into problems later.
