### ISSUE TITLE
Why can actual reducer not take initial state instead of passing second arg to useReducer

### ISSUE THREAD

**Issue by zaynv** [facebook/react#14624]
**Do you want to request a *feature* or report a *bug*?**

I don't know if this is intentional design or if its a bug. Someone in Reactiflux asked about this so i was curios

**What is the current behavior?**

Reducer passed to `useReducer` cant take initial state. Instead, you need to pass second arg

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Reducers must be created like:

```js
const initialState = {
  ...
}

function reducer(state, action) {
  ...
}

const [state, dispatch] = useReducer(reducer, initialState)
```

**What is the expected behavior?**

Why cant we do:

```js
const initialState = {
  ...
}

function reducer(state = initialState, action) {
  ...
}

const [state, dispatch] = useReducer(reducer)
```

This is how Redux does it.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

v16.8.0-alpha.1

**Comment by gaearon** [comment]
I think the author meant they’d prefer that `useReducer()` *also* respected Redux idiom of setting initial state inside the reducer.

Afaik the main reason it doesn’t is type safety — otherwise you have to treat undefined as always a valid state value.

However we’ve also changed the signature of useReducer in master. Docs not updated yet. Redux signature would work if you did `useReducer(reducer, undefined, reducer)`. Which is kinda weird but figured I’d mention.

**Comment by anyley** [comment]
What about hook reducers sharing between components?

**Comment by gaearon** [comment]
We tweaked the API a bit to allow lazy initialization:

https://reactjs.org/docs/hooks-reference.html#lazy-initialization

We still don't use the Redux API because it makes static typing more difficult. (We don't want to consider `undefined` state valid just to allow lazy init.)

But you can have two separate functions, one for initialization and one as the main reducer: https://reactjs.org/docs/hooks-reference.html#lazy-initialization

You can even make the Redux pattern work with `useReducer(reducer, undefined, reducer)` although we don't encourage this.
