### ISSUE TITLE
get the error Cannot read property 'props' of undefined in getDerivedStateFromProps 

### ISSUE THREAD

**Issue by lisandrolan** [facebook/react#14660]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Im getting the error "Cannot read property 'props' of undefined" in method getDerivedStateFromProps 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
It sounds like you're trying to access `this.props` inside `getDerivedStateFromProps`, which won't work since its a static class method. See [the API documentation](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) for more information.

We also use the issue tracker for bug reports and feature requests. If you have a usage or support question, please check our community support resources: https://facebook.github.io/react/community/support.html

If you believe this is a bug in React, please follow up with more details and I'll be happy to investigate it for you. Thanks!

**Comment by lisandrolan** [comment]
You are correct, 
I was using this method to dispatch a redux action creator. 
Where should i put that code?
Im waiting to the user to be logged and then Im calling the API to get his data.
