### ISSUE TITLE
Calling a function within a function

### ISSUE THREAD

**Issue by ericx2x** [facebook/react#14700]
Anyone know a better way to create call a function within a function? Below I have datagrabber but react doesn't like this way of calling and gives me an error.

```
import React from 'react';
import nav from '../data/navigation';
import navMedicare from '../data/navigationMedicare';
import MegaNavSearch from './MegaNavSearch';

const MegaNavSupportLinks = (props) => {
  const links = props.links ? props.links.top : nav[0].top;

  dataGrabber() {

    return(
      <div>
        {links.map((l, idx) => <a href={l.url} className="mnav-header__nav-link" key={idx}>{l.label}</a>)}
      </div>
    );
  }

  return (
    <nav className={props.sticky ? 'mnav-header__nav mnav-header__nav--hidden' : 'mnav-header__nav'}>

      {this.dataGrabber()}

      <div className="mnav-header__nav-select">
         Español
      </div>

      <MegaNavSearch />
    </nav>
  );
};

export default MegaNavSupportLinks;

```

**Comment by aweary** [comment]
Hey there! We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

With that said, that example isn't valid JavaScript. You're trying to define and use `dataGrabber` as if it were a class method, but your component is just a function so that doesn't work. You should define it as a separate function and call it without using `this`. [Something like this](https://gist.github.com/aweary/4b2398784694e74276847e96c74380bd).
