### ISSUE TITLE
this is undefined in getDerivedStateFromProps

### ISSUE THREAD

**Issue by sanbornhilland** [facebook/react#14730]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`this` is undefined in `getDerivedStateFromProps`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
```javascript
class MyComponent extends Component {
  static sayHello() {
     console.log('Hello')
  }

  static getDerivedStateFromProps() {
     this.sayHello()
  }
}
```

**What is the expected behavior?**
I would expect the above to work. To me it is unexpected that a static method is not getting called on the class.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.5.1

This seems like an easy fix to me, [here](https://github.com/facebook/react/blob/a129259ad6a61790fe1912a87cb45018d942f90c/packages/react-reconciler/src/ReactFiberClassComponent.js#L161)

Is there a reason not to change line 157 and 161?

```javascript
// From this
getDerivedStateFromProps.(nextProps, prevState);

// To this?
getDerivedStateFromProps.call(ctor, nextProps, prevState);
```

**Comment by TrySound** [comment]
@sanbornhilland This is expected. https://github.com/facebook/react/issues/12612#issuecomment-381332338

**Comment by milesj** [comment]
> To me it is unexpected that a static method is not getting called on the class.

Outside of what @TrySound has linked, this is how JS works. Static methods *do not* have access to a class instance's `this`, and IMO, it never should.

**Comment by sanbornhilland** [comment]
It's not even `null` though, which would indicate that it was intentionally set. It's `undefined` which looks like a bug to me. 

I understand wanting to avoid unnecessary confusion in the `React` api but this misses the mark IMO. To me this is unexpected behaviour and at some point it seems reasonable to encourage developers to learn how `this` works instead of being overly protective.

**Comment by jquense** [comment]
this is intended, and yes it does differ from how static methods, work _if_ you call them with the class to the left of the dot `Foo.bar()`. For the reasons noted in the other issue The react team has opted to avoid ambiguity and always make sure it's undefined

**Comment by milesj** [comment]
@sanbornhilland That's how JS works. 

<img width="367" alt="screen shot 2019-01-30 at 10 20 43 am" src="https://user-images.githubusercontent.com/143744/52003193-bbfb6100-2478-11e9-82ed-14e38527faab.png">

**Comment by milesj** [comment]
You can see their usage here: https://github.com/facebook/react/blob/a129259ad6a61790fe1912a87cb45018d942f90c/packages/react-reconciler/src/ReactFiberClassComponent.js#L789 

They are simply calling it as a reference. No bind/call/apply, etc. This is standard JS classes.

**Comment by milesj** [comment]
@sanbornhilland Correct, I was assuming you wanted the instance, not the constructor. Definitely clears up the confusion.

**Comment by mizukami234** [comment]
This works (not recommended though):

```js
static get getDerivedStateFromProps() {
  return (props, state) => {
    console.log("Hello this is ", this);
  };
}
```

**Comment by dolsem** [comment]
This issue should be reopened because `this` is expected to point to the class instance. [See this contrived example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdwAdjFlAXlnAEIQQDWcAN504YuE2QgsALjioYUZgHN64lAFcYAC2hyFSpqroBfBrgA2adLwEBhCBYtZ8wCEzhYAHqyYATdGw8GAA6B3B3LBZhUXEFZBhgXHloGDkACmQ5W34AGjgAI2y+fgBKOABeAD4JDRACtgZ1eNZKmPV1PwSsuABtAF1c2LEzYfkYBKS4ZSwYABE2YAA3LD8AZQnWADFiEAAFYjBUdKZvGAOII7khOChkAHc57rkAQSg7gE8AHhyak3KRB1xLh3Ao4F0Jm1Tj4LkcQndHt0QqhUukdMBUMjUqU1EDbrMNFAPDcIcg4CZcSNTOYrKgbCVUNwPgA5KRcM5RAI8EoOJwuRLudpxTZTFGwNqZYoCfJFbkCcrVFAhSTSOBfQrKtlwAD8cAAtABGOByA30UaWaxy-iMj4vLS6KCeHyc+n2RzOVyCwHCybJMXwCpwSVWmVSsqVGrIELIe3QNUamM6OO6w3GuCm0xAA). TypeScript typechecker is fine with this code because it expects `this` to be defined. This code compiles but fails at runtime. This becomes more of an issue when you create a component intended to be subclassable and so you don't know the exact context beforehand, like in the example above. I have to work around it with a getter like @mizukami234 suggested.
```ts
  static get getDerivedStateFromProps() {
    return this._getDerivedStateFromProps.bind(this);
  }
```
