### ISSUE TITLE
Component doesn't get rerendered when state is changed

### ISSUE THREAD

**Issue by Hisagr** [facebook/react#14788]
I have a simple Clock component, which shows current time. It used to work in 16.8.0-alpha.1 with no issues.
https://codesandbox.io/s/3ywxy8mp0q

As soon as I updated to 16.8.0, it stopped rendering when the time is changed.  In the tick() function I see that the time gets updated, but this doesn't cause rerender for some reason.
https://codesandbox.io/s/m4zqyz0pkp

Any ideas why this happens?
Please let me know if any additional details are required.

Thanks for your help!

**Comment by Alaricus** [comment]
I am having (what seems like) the same problem. My minesweeper game has a recursive function that clears empty spaces. It worked perfectly fine in 16.8.0-alpha.1, nut as soon as I upgraded to 16.8.1 (no code was changed at all) it started only revealing the single cell on which the user clicked. All other cells remained unchanged even though the function ran. Interestingly enough the very first click of the game seems to work correctly in clearing empty space, it's the subsequent ones that bug out.

Repo: https://github.com/Alaricus/dragonsweeper
File: src/Minesweeper.js
Line: 37

`  const clearEmptySpace = (row, col) => {
    const neighbors = getValidNeighbors(row, col);

    if (neighbors.length === 0) { return; }

    neighbors.forEach((item) => {
      const warningNumber = getWarningNumber(item.row, item.col);
      const arr = board;
      const cell = board[item.row][item.col];
      if (!cell.flag) {
        arr[item.row][item.col].number = warningNumber;
        if (warningNumber === 0) {
          clearEmptySpace(item.row, item.col);
        }
        setBoard(arr);
      }
    });
  };`

**Comment by aweary** [comment]
@Hisagr the issue is that `moment` uses a mutable API. When you call `t.add(1, 'seconds')` it doesn't return a new object, it just mutates the previous object and returns it. Since React sees it as the same object, it bails out of the update.

You can verify that yourself:

```js
const tick = () => {
    setTime(t => {
      let nextT = t.add(1)
      console.log(nextT === t)
      return nextT
    })
  }
```

https://codesandbox.io/s/y05jw160lj

@Alaricus it looks like you're using mutation as well, so it's likely the same problem.

You should usually try and avoid using mutation with React state, but as a work around for now you can force an update. See [Is there something like `forceUpdate`?](https://reactjs.org/docs/hooks-faq.html#is-there-something-like-forceupdate) in the React Hooks FAQ.

**Comment by Hisagr** [comment]
Thanks for your help! Changing to t.clone().add(1, 'seconds') does solve the issue. But I guess I should look into immutable library solution like date-fns, since this can become an issue.

**Comment by Alaricus** [comment]
@Hisagr thank you for taking a look! My only question is, why does it work the first time? At game's start, the empty area is being cleared up successfully, all while running the same function.
