### ISSUE TITLE
How to tell if getDerivedStateFromProps is triggered by state change or props change?

### ISSUE THREAD

**Issue by yufangfred** [facebook/react#14817]
The component receives a list of Objects as prop. I want to display it with infinite scroll. It has the state "curNum", which is current number of items to be displayed. "curNum" changes when scroll down so the list of items is sliced based on the "curNum".

The list of object will be updated by the parent component, and "curNum" should be reset to initial value.

With componentWillReceiveProps I can do:
```
componentWillReceiveProps(newProps) {
  this.setState({
    curNum: initNum,
  });
}
```

but how can I rewrite it using  ```getDerivedStateFromProps```? I read that the new method will be triggerged even if the state changes. So how can I know I am recieving new props?

Do I have to mirror a copy of the list to the sate and then deep check if the list of objects are equal every time?

**Comment by gaearon** [comment]
What is your conclusion after reading this post? Is there any similar case there?

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by jojoblaze** [comment]
My conclusion is not using React if possible. :)

**Comment by IMalyugin** [comment]
Okay, I'm not going to create a new issue on "Oh wow, bug, gdsfp is fired upon state change". I've read all the related articles and saw a lot of pain from ordinary users. Infact each time I HAD to use gdsfp (_getDerivedStateFromProps_), it was incredibly painful and i was forced to write ugly code just for the sake of "following method's flow".

Instead I'll just post the real use case and solution here.

**Short story**: I need to react on every change to one single prop called value, which may change either from outside, or inside. If it changes from outside - i have to use external value and if it changes from inside, I have to keep the inner value. That is an ugly way to wrap a component so it looks and feels a lot like stateless machine.

**Long story**: FinalForm is a great library and all, but it has one huge downside, it does not operate in stateless mod, and the only way to make it work stateless - aka being able to manipulate state as an object from outside, while firing onChange on form if it changes from inside - is to wrap it via container that utilizes gdsfp, and works in such a fashion, that when there is an internal change.

**Problem**: It took me quite some time, I had to dig it inside of myself, to answer the question - what is the problem here? I mean why would i care if it reacts to state changes, just keep the design straight and there should be no problems. But there actually is a huge flow in function design.
Let's get back to the above case. Why do I care If gdsfp only fires from props change? Answer lies in the very reason I need gdsfp. I need gdsfp to react upon change in one single prop, `value`. Once value changes i can compare it with the one i have in state:
```
static getDerivedStateFromProps(nextProps, prevState) {
  if (!shallowEqual(nextProps.value, prevState.value)) {
    return {
      value: nextProps.value,
    };

**Comment by IMalyugin** [comment]
Okay, I'm not going to create a new issue on "Oh wow, bug, gdsfp is fired upon state change". I've read all the related articles and saw a lot of pain from ordinary users. Infact each time I HAD to use gdsfp (_getDerivedStateFromProps_), it was incredibly painful and i was forced to write ugly code just for the sake of "following method's flow".

Instead I'll just post the real use case and solution here.

**Short story**: I need to react on every change to one single prop called value, which may change either from outside, or inside. If it changes from outside - i have to use external value and if it changes from inside, I have to keep the inner value. That is an ugly way to wrap a component so it looks and feels a lot like stateless machine.

**Long story**: FinalForm is a great library and all, but it has one huge downside, it does not operate in stateless mod, and the only way to make it work stateless - aka being able to manipulate state as an object from outside, while firing onChange on form if it changes from inside - is to wrap it via container that utilizes gdsfp, and works in such a fashion, that when there is an internal change.

**Problem**: It took me quite some time, I had to dig it inside of myself, to answer the question - what is the problem here? I mean why would i care if it reacts to state changes, just keep the design straight and there should be no problems. But there actually is a huge flow in function design.
Let's get back to the above case. Why do I care If gdsfp only fires from props change? Answer lies in the very reason I need gdsfp. I need gdsfp to react upon change in one single prop, `value`. Once value changes i can compare it with the one i have in state:
```
static getDerivedStateFromProps(nextProps, prevState) {
  if (!shallowEqual(nextProps.value, prevState.value)) {
    return { value: nextProps.value };
  }
  return undefined;
}
```
But how do I tell which value is newer? The one in newProps or in prevState, if gdsfp reacts on state change? Answer is via a train of ugly, useless and super hard to understand code. Either I have to fire out `setState({ value: ..., isSetState: true });`, and then erase isSetState in gdsfp, or I have to keep track of changed value in prevState in another key that is required just by gdsfp to operate, and then compare that other key with nextProps. Each time I have to do that I see clearly that gdsfp design is overly complicated.

Solution: the solution is dumb simple, just store nextProps into one of the state keys, and then only do gdsfp action if that object changed. That logic can be easily separated in a reusable decorator:
```
/**
 * Wrapper around getDerivedStateFromProps to only react on props change and ignore setState calls
 */
export const ignoreState = getDerivedStateFromProps => (nextProps, prevState) => {
  if (prevState[SymbolPrevProps] !== nextProps) {
    return {
      ...getDerivedStateFromProps(nextProps, prevState),
      [SymbolPrevProps]: nextProps,
    };
  }
  return null;
};
```

And then use it to convert this:
```
static getDerivedStateFromProps = (nextProps, prevState) => {
    if (!prevState.isSetState && !shallowEqual(nextProps.values, prevState.values)) {
      return { values: nextProps.values };
    }
    return { isSetState: false };
  };
...
this.setState({
  values,
  isSetState: true, // eslint-disable-line react/no-unused-state
}, () => onChange(values));
```
Into this:
```
static getDerivedStateFromProps = ignoreState((nextProps, prevState) => {
  if (!shallowEqual(nextProps.values, prevState.values)) {
    return { values: nextProps.values };
  }
  return null;
});
...
this.setState({ values }, () => onChange(values));
```
