### ISSUE TITLE
Minified React w/ addons does not expose TestUtils

### ISSUE THREAD

**Issue by yocontra** [facebook/react#1481]
The minification may have over-mangled something. The current 0.10 minified w/ addons on the website will not expose the addons.

**Comment by jasonslyvia** [comment]
Sorry for replying this long-closed issue, but we do have a **TestUtils-in-production** kind of need.

We have a watermark overlay rendered topmost the page, which displays current logged-in user's name, for preventing capture webpage and leaking sensitive data.

For advanced browsers, the watermark overlay has been set to `pointer-events: none;` . But for IE 8, 9, 10, I must simulate the event in order to mimic event pass through.

So if it makes sense, can I have a option when compiling React's source into production to include TestUtils ?

**Comment by jimfb** [comment]
@jasonslyvia TestUtils is intended for internal testing, and is therefore internal API.  We recommend that you do not call into internal APIs (especially in production) as they are not supported/stable/optimized/etc.  We are not going to publish builds that expose internal API, but nothing stops you from checking out the code and building it yourself with any changes/modules.

I'm not super familiar with the browser's event system, but I think you can achieve your goal by temporarily disabling the watermark and emitting a click event:
```
disableWatermark();
document.elementFromPoint(x, y).click();
enableWatermark();
```

If people need a public API for interfacing with the React event system, you might consider creating a task for that API and see if you can rally support, but my guess is that simulating click events is something better left to the browser's existing APIs.

On a side note: It is absolutely trivial to open the chrome tools (or firefox/whatever) and remove the watermark from the DOM (this is trivial, even without the disable/enable functions I proposed).  Anyone who is capable enough to take a capture webpage is almost certainly capable enough to just remove the watermark before capturing.  I'm a little worried that your attempt at 'security' is a bit miss-guided, but that's a different discussion.

**Comment by jasonslyvia** [comment]
Thank you for your kind reply @jimfb . I do know that any security concern implemented in front-end is sort of trivial, after all, all the code runs in the client side. So let's leave alone the usefulness of watermark.

Actually I do use jQuery's `trigger` method to achieve this goal before `TestUtils` comes to mind. But the jQuery way doesn't work in some circumstances, for instance a single `a` tag with no descendant responding to `click` event. 

````
<a onClick={this.handleClick} id="btn">Click Me</a>
````

Using jQuery's trigger:

```
$('#btn').click();
```

doesn't call `handleClick` at all, however `TestUtils.Simulate.click()` do achieve the goal.

Since I haven't dive into React's event system, I'm totally lost for this behaviour so I have to turn to `TestUtils.Simulate`.

Let me know if a demo jsfiddle is needed.

**Comment by jimfb** [comment]
Once you have the element at a point (via jquery), I feel like there is something you can do with it.  For IE, maybe use `fireEvent` instead of jquery click.  Or find another way to trigger the appropriate event on the dom element.  I haven't looked into it too deeply, but I strongly suspect that if you poke around, you should be able to do what you want with the native apis.
