### ISSUE TITLE
Prop reassignment in components

### ISSUE THREAD

**Issue by th3fallen** [facebook/react#14827]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Prop reassignment in components

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

1. Have a parent component that passes a prop to a child
2. Have a child assign the prop to the state default
3. Unpack the state value and use a`.push` to alter it
4. Watch in horror as both the prop and the state changes.

https://codesandbox.io/s/61x9k76v8w
Check child.js

**What is the expected behavior?**
Props should not be reassignable within mounted components

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
All browsers all OS's React: 16.7.0

**Comment by brookslybrand** [comment]
This is because you're passing down an array, which is a pass by reference and a mutable object. When you assign `state = { ids: this.props.ids }` you are merely assigning the reference. You later mutate that array directly. This is why you are getting this behavior. This isn't a bug, it's expected, and isn't good practice because of the issues you pointed out above.

Don't use the `push` method. This will mutate the state, and state should [never be directly mutated in React](https://reactjs.org/docs/react-component.html#state). Instead, you should do `ids.concat(id)` as this will return a new, and the update will get handled `setState`.

**Comment by th3fallen** [comment]
ah, excellent suggestion. i was aware it's an edge case but it shocked me i could mutate props in that way.

**Comment by brookslybrand** [comment]
Glad you were aware. Yeah, React doesn't prevent you from mutating state directly for some reason. A lot of times I'll end up using [Immutable.js](https://facebook.github.io/immutable-js/) for most or all of my state, just to safeguard myself from doing something like this, and also to make state comparisons easier.

**Comment by threepointone** [comment]
Thanks for the assist @brookslybrand! Closing this issue.
