### ISSUE TITLE
Suspense + React v16.8.2

### ISSUE THREAD

**Issue by neoziro** [facebook/react#14860]
Hello,

Running React v16.8.2, Suspense is recreating every components (the instance is recreated).

An example of implementation to understand the problem: https://codesandbox.io/s/3xlj89wx4q

Am I doing something wrong?

Thanks!

**Comment by gaearon** [comment]
Yes, it's expected that suspending will re-create the instance before the first successful mount. (Well, instance isn't the right word, but memo would be thrown out.)

The Suspense data fetching strategy relies on an external cache, not memo or component state. If it was that easy to use, the data fetching story would have been "stable" already.

The only supported use case for Suspense today is code splitting with lazy. Otherwise you're on your own.

https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-mid-2019-the-one-with-suspense-for-data-fetching

**Comment by neoziro** [comment]
Thanks for your answer, I will be patient 😶.

To keep Loadable Components compatible I will implement an external cache. But anyway, nobody should use it with Suspense. The only use case not covered by React.lazy is full dynamic import. Maybe you should implement it in React.lazy.

**Comment by lazeebee** [comment]
@gaearon i'm just curios whats the reason it needs an external cache?

**Comment by gaearon** [comment]
Because it’s been designed that way. You want to be able to hydrate that cache with server rendering and to preserve data in it even if components unmount.
