### ISSUE TITLE
Why moving item to another array fire re-rendering for itself (the item)?

### ISSUE THREAD

**Issue by Steffi3rd** [facebook/react#14896]
Hello,

I have the following problem :

— When I drag/drop item to an another `array()` > it re-renders the item I moved — (Why?)

— When I drag/drop in the **same** `array()` > it's not renders. So it's GOOD !

The problem is my deepest child, I have a little `fetch()` to retrieve some additional data. 
These data are already fetched.
So when I drag/drop **I don't want** another fetch. 
Event `React.memo()` solve the problem.

You can check the console of CodeSandbox to see the problem :

###  [https://codesandbox.io/s/03on3k75xw](https://codesandbox.io/s/03on3k75xw)

**What is the expected behavior?**

No re-render of the item, since React already displays it, I just moved to another array. It's still the same item.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

```
React 16.8.1
MacOS 10.14.2
```

React Beautiful Dnd : https://github.com/atlassian/react-beautiful-dnd

**Comment by threepointone** [comment]
If I understand your code correctly, moving an item into another subtree would rerender the item, since React doesn't support 'reparenting' children. So the dnd library you're using would rerender the component. I'd recommend you use a cache for your fetch calls, so you then can check if the data exists in your cache before triggering a fresh call. 

React can't do much here, so I'm going to close this issue. You could also post in https://github.com/atlassian/react-beautiful-dnd/issues, they might be able to help you more.
