### ISSUE TITLE
React dom dispatches events when it shouldn't

### ISSUE THREAD

**Issue by OshanAbeykoon** [facebook/react#14936]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When we set a value to an input field and set the focus of that element straight after setting its value,
React dom is dispatching event listeners on the focused element.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/oshan/x7at18h4/3/)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version 16.7.0, React dom version 16.7.0
Browsers: Chrome, Edge, Firefox

**Comment by nhunzaker** [comment]
This is a complex sequence of events, but it looks like everything is working as expected. Just to make sure I have this right:

Following your JSFiddle: https://jsfiddle.net/oshan/x7at18h4/3/

1. I click outside of the input, so the input no longer has focus

**Comment by nhunzaker** [comment]
This is a sophisticated sequence of events, but it looks like everything is working as expected. Just to make sure I have this right:

Following your JSFiddle: https://jsfiddle.net/oshan/x7at18h4/3/

1. I click outside of the input, so the input no longer has focus
2. I press the character "a", triggering the document level event captured listener defined in componentDidMount
3. That executes `handleKeys`, which sets the state `isWaiting` to `true` and `key` to `a`
4. Calling setState triggers `componentDidUpdate`
5. Since `isWaiting` is true and `key` is `"a"`, it triggers the if condition where the input is modified
6. Direct DOM manipulation in this condition directly assigns `value` to the input element using `element.value = `${value+key}`;

Here's why I think this is happening:

The document level event listener listens to [`keydown` using event capturing (`true`)](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) is the third argument, focusing the input before the keystroke finishes. So this event actually executes before the keystroke registers on the input itself. You can see this outside of React here:

https://codepen.io/nhunzaker/pen/RvXyVY

So by the time `componentDidUpdate` triggers, the input has already received focus, the keydown event has been applied to the input, and the browser has inserted the keystroke into the input.

Then `element.value = `${value+key}`; runs, which results in `element.value = `${"a" + "a"}`, resulting in what looks like double-key entry.

Closing this out, but let me know if I missed something. Also, it might be worth looking at controlled inputs to handle input text content:

https://reactjs.org/docs/forms.html#controlled-components
