### ISSUE TITLE
Varying number of hook calls

### ISSUE THREAD

**Issue by noobG** [facebook/react#14976]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I understand React relies on call order when using hooks, but I don't understand why I'm not allowed to call an arbitrary number of (some) hooks as long as I preserve call order

I'm making a tooltip component with an "open" prop that also awaits a "target" ref before rendering:

What I tried:
```
export default props => {
	// Set up lifecycle callbacks - makes perfect sense to me that this has to be called before any return statements
	useEffect(...) 

	if (!props.open) return null;
	// I can safely use "props.target" below this point...
	if (!props.target) return null; 

	const { x, y } = props.target.getBoundingClientRect(); 

	const style = useMemo(..., [x, y]);

	return ...
}
```

To avoid an error about "fewer/more hooks called than previous render", I have to refactor the above into the following:
```
export default props => {
	useEffect(...)

	// Now I have to code defensively because I can't guarantee target is defined...
	const { x, y } = props.target ? props.target.getBoundingClientRect() : {};

	// I also have to code defensively in the useMemo handler because now x and y can be undefined
	const style = useMemo(..., [x, y]); 

	// And now my return values are down here, which isn't necessarily where I want them to be if I want to "section" my code a certain way
	if (!props.open) return null;
	if (!props.target) return null;

	return ...
}
```
I understand why I need to declare "lifecycle hooks" like useEffect before any return statements, but I don't understand why certain hooks like useMemo and useCallback have to adhere to the same principle.

**Comment by gaearon** [comment]
Calling `getBoundingClientRect` during rendering is sketchy. Rendering is not supposed to query the DOM and this can cause weird quirks. Instead, you want to be calling that inside `useLayoutEffect` (since you want to read the layout). And set the state based on it.

All Hooks need to adhere to this principle because that's what makes it possible for custom Hooks to have isolated states per call. You'll see why if you try to extract some of this logic to a custom Hook and then call it multiple times.

The easiest way for you to "structure" your code differently is to split the component in two. The outer one provides the early exit and tracks the bounding rect in state. The inner one takes `rect` as a prop and has the memoization logic (but doesn't need defensive coding). Hope that helps.

**Comment by noobG** [comment]
It does help. Thanks :-)
