### ISSUE TITLE
Manipulating child by parent's components

### ISSUE THREAD

**Issue by Hypothesis-github** [facebook/react#15004]
**Do you want to request a *feature* or report a *bug*?**
No,

**What is the current behavior?**
The component rerenders 3 more times than needed 

**What is the expected behavior?**
The component to rerender once 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8

```
import React from "react";
import ReactDOM from "react-dom";
import { Lower } from "./lower";

import "./styles.css";

function App() {
  const [state, setState] = React.useState("nochange");
  const change = () => {
    console.log("runs");
    setState("change");
  };
  return (
    <div className="App">
      <Lower mode={state} />
      <p />
      <button onClick={() => change()}>click to change</button>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

```
import React from "react";

export const Lower = props => {
  const [state, setState] = React.useState(1);
  console.log(props.mode);
  React.useEffect(() => {
    props.mode === "change" && setState(2);
  });
  return state;
};

```

My repo is [https://codesandbox.io/s/kkkl61mrzv](url) and I am trying to send a prop to my child via manipulating the state with the new hooks. the component does work however in my console.log I can see that the component rerenders quite a few times. please help me find a proper way to have this done with rerendering once.

**Comment by KevinKelbie** [comment]
You get get rid of the duplicated rerenders by specifying that it should only rerender when `props.mode` changes by doing the following

    export const Lower = props => {
      const [state, setState] = React.useState(1);
      React.useEffect(
        () => {
          console.log(123, props.mode);
          props.mode === "change" && setState(2);
        },
        [props.mode] // here we tell useEffect not to rerender unless props.mode changes
      );
      return state;
    }; 

You also need to include the `console.log` **inside** the useEffect otherwise its going to print on every rerender including the rerender when you update the incrementor inside the `useEffect`.

I'm no expert but thats so someone else can feel free to correct me but [here is the code with the output I think you are expecting](https://codesandbox.io/s/6xoj9lvron).
