### ISSUE TITLE
Calling `act()` implicitly

### ISSUE THREAD

**Issue by webNeat** [facebook/react#15000]
**Do you want to request a *feature* or report a *bug*?**

a feature

**What is the current behavior?**

Any code causing state change should be wrapped into `act()` during tests.

**What is the expected behavior?**

Offering a module which when imported will alter `React.useState` and `React.useReducer` to make them call `act` automatically on every update. Something like the following would work I guess:

```js
const React = require('react')
const {act} = require('react-dom/test-utils')

const wrap = fn => (...args) => {
  let result
  act(() => {
    result = fn(...args)
  })
  return result
}

const useState = React.useState
const useReducer = React.useReducer

React.useState = (...params) => {
  const result = useState(...params)
  result[1] = wrap(result[1])
  return result
}

React.useReducer = (...params) => {
  const result = useReducer(...params)
  result[1] = wrap(result[1])
  return result
}
```

I made a [small library](https://github.com/webNeat/react-act) offering this after a [story of issues with testing hooks](https://github.com/webNeat/react-act/blob/master/story.md) and it would be awesome if this was part of React DOM itself.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8+ and React DOM 16.8+

**Comment by gaearon** [comment]
I think you went a bit into the woods here. Doing this defeats the whole purpose of act because it doesn’t batch interactions anymore. It makes every change synchronous — which is exactly the pattern act tries to warn you *against*.

Instead, the fix to this is to **add the support for asynchronous functions inside of act**. This is already something we’re working on. You can track that in https://github.com/facebook/react/issues/14769.

**Comment by webNeat** [comment]
I see, thanks for your response. I understand the need for `act` better now :)
