### ISSUE TITLE
Question about React.Children

### ISSUE THREAD

**Issue by rabbitooops** [facebook/react#15015]
Why use `React.Children` to manipulate children? why not `children.map`, `children.forEach` and so on?

**Comment by SwarajG** [comment]
React.Children.forEach and React.Children.map, both work exactly like their array counterparts, except they also work when a function, object or anything is passed as children.

Suppose, if you have used this.props.render.map, it would’ve been a function instead of an array, and we would’ve had an error!
So, React.Children solve these type of problems, where it can expect more than only string type of children.

Hope, this will helps.

**Comment by rabbitooops** [comment]
Thank you.

**Comment by rabbitooops** [comment]
@SwarajG Does it mean React.children is not a good name? Is React.Elements better?

**Comment by SwarajG** [comment]
In my view, React.children is good enough, Because, in the end, we are manipulating the children property only.
