### ISSUE TITLE
Mutliple state hooks resulting in mis-paint

### ISSUE THREAD

**Issue by drKnoxy** [facebook/react#15028]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A paint seems to occur between a state update, and before an effect that is "listening" to that state gets a chance to run it's synchronous state update function.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/x2qnpykl5z

1. run the profiler
2. click the "change mode" button
3. slide through the screenshots from the profile
4. *err* there is a paint with "old" data but in the "new" mode before the "showLoader" boolean is set to true

**What is the expected behavior?**
I would have expected that there would not be a paint of the state update if useEffect had that state listed as a dependency, and that the paint would wait until useEffect had at least done any state changes that weren't async.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.3 chrome latest, fedora (but i think all os)

**Comment by bvaughn** [comment]
> I would have expected that there would not be a paint of the state update if useEffect had that state listed as a dependency, and that the paint would wait until useEffect had at least done any state changes that weren't async.

It looks like there's a few things going on in this repro. Firstly, I think you should move your `updateShowLoader(true)` call (currently in the effect) to be inside of your click handler, so you can avoid the unnecessary second update. [Updated example](https://codesandbox.io/s/xj55w0q25z).

Secondly, regarding the "paint between updates" – the reason for this is that your example is using [`useEffect`](https://reactjs.org/docs/hooks-reference.html#useeffect), which is a "passive" effect– meaning that it is fired asynchronously, after the DOM has been updated and the browser has had a chance to paint.

We encourage using `useEffect` when possible because it doesn't stretch the "commit" phase and delay paint. But in some cases– you need to avoid the temporary flash of inconsistent UI. For that, you can use [`useLayoutEffect`](https://reactjs.org/docs/hooks-reference.html#uselayouteffect).

In this case, I think `useEffect` is actually _fine_, since moving the `updateShowLoader` into your event handler removes the need to update the DOM twice initially.

Hopefully this helps! Please let me know if I misunderstood anything.

**Comment by drKnoxy** [comment]
Thanks for the clarification!
