### ISSUE TITLE
use `displayName` of `useDebugValue`

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [facebook/react#15031]
**Do you want to request a *feature* or report a *bug*?**
> *feature*

**What is the current behavior?**
> I can't find a way to custom the display name of `useDebugValue` hook.

`useDebugValue` seems now only detect the display name from the function name. For the common `Component`, we can used the static `displayName` field to custome the name of the `Component` show in the `React dev tools`, why not let the `useDebugValue` hook works in the same way too?

**Comment by bvaughn** [comment]
`useDebugValue` doesn't have anything to do with `displayName`.  It's used to show a value in DevTools beside a custom hook.

`name` and `displayName` have to do with how we refer to a component in React warning or error messages, as well as in the "Elements" panel of React DevTools.

[The docs show this example](https://reactjs.org/docs/hooks-reference.html#usedebugvalue):
```js
function useFriendStatus(friendID) {
  const [isOnline, setIsOnline] = useState(null);

  // ...

  // Show a label in DevTools next to this Hook
  // e.g. "FriendStatus: Online"
  useDebugValue(isOnline ? 'Online' : 'Offline');

  return isOnline;
}
```

In DevTools, the `useFriendStatus` hook would display something like:
> FriendStatus: "Online"

**Comment by zhengxiaoyao0716** [comment]
Thank you, I  known that it doesn't have anything to do with `displayName` now, but I think it is better to let the `useDebugValue` support that.

In my opinion, as other class like `Component`, `Context` and `Pure-Function Component` support the `displayName`, it is reasonable to make the `useDebugValue` works in the same way.

For a actually case, developers may need to custom the display name of the `useFriendStatus` in `React dev tools`, like this:
```
const builder = (mount, unmount) => (...args) => {
    const [resource, setResource] = useState(null);
    useEffect(() => {
        const resource = mount(...args);
        setResource(resource);
        return () => unmount(resource);
    });
    useDebugValue(resource, resource => resource.toString());
    return resource;
};

const useSth = builder(
    (...args) => new Sth(...args),
    sth => sth.destroy(),
);

const Test = () => {
    useSth();
    return null;
};

class Sth {
    destroy() { }
    toString() { return 'sth'; }
}

```

**Comment by bvaughn** [comment]
The name of custom hooks in DevTools is determined by the name of the functions themselves (e.g. `useDate` will be shown as "Date", `useCurrentUser` as "CurrentUser" etc.) This is done by [parsing the JS callstack](https://github.com/facebook/react/blob/eb6247a9ab7653aac346db08faf0862c58b055df/packages/react-debug-tools/src/ReactDebugHooks.js#L374-L419) and inferring things.

Unlike the classes or functions that make up React components– React does not have a direct reference to custom hooks. Looking at your example above:
```js
const useSth = builder(
    (...args) => new Sth(...args),
    sth => sth.destroy(),
);
useSth.displayName = 'Sth';

const Test = () => {
    useSth();
    return null;
};
```

React has a reference to `Test` because you pass it as a React element (`React.createElement(Test)` or `<Test/>`) so React can check `Test.name || Test.displayName`. React does **not** have a reference to `useSth()` (or any other method call or variable defined inside of your function component).

**Comment by zhengxiaoyao0716** [comment]
Thank you, in that case, I would compromise.
