### ISSUE TITLE
Why not using object spread to provide value and callback in useState and useReducer?

### ISSUE THREAD

**Issue by Stupidism** [facebook/react#15062]
Is there a specific reason/pattern that you guys are putting two return values in an array but not an object?

I can understand below code might look ugly:
```
const { state: open, setState: setOpen } = useState(false);
```

But when it comes to custom hooks, code like this is not healthy, either:
```
const [open, toggleOpen, visible, toggleVisible] = useOpenAndVisibleToggler(false, false);
```

I have some guess about the reason:

### Renaming

If renaming is the only reason not to use object spread, can I say, I can use it in my custom hooks? e.g.

```
const { open, toggleOpen } = useOpenToggler(false);
```

### Value/Callback Separate
 
If there's a concern about separating values and callbacks, I want to write code like this:

```
const [{ open, visible }, { toggleOpen, toggleVisible } ]= useOpenAndVisibleToggler({
  open: false,
  visible: false,
});
```

**Comment by gaearon** [comment]
>But when it comes to custom hooks, code like this is not healthy, either:

Which is why you shouldn’t design custom Hooks to return an array of so many values. There’s nothing in React that forces you to do that.

We recommend returning an array when there’s an obvious pair of values (such as current value and an updating function). If it’s more than that then return an object. In general, it’s a good idea to use common sense when designing an API and not try to copy built-in Hooks 1:1. Hope this helps!
