### ISSUE TITLE
eslint-react-hooks: should we enforce to use React.useMemo if there is no state hooks?

### ISSUE THREAD

**Issue by BigYu** [facebook/react#15081]
1. Regarding the performance optimization, should we always use React.useMemo in case there is no state hooks inside a function component?
2. If the answer is yes, can we use some eslint rules to make sure everyone do it?

**Comment by MonFig** [comment]
In the [latest blog](https://overreacted.io/a-complete-guide-to-useeffect/) of @gaearon wrote 

> I want to emphasize that putting useCallback everywhere is pretty **clunky**. It’s a nice escape hatch and it’s useful when a function is both passed down and called from inside an effect in some children. Or if you’re trying to prevent breaking memoization of a child component. But Hooks lend themselves better to avoiding passing callbacks down altogether.

I always treat `useCallback(fn, arr)` as an alias to `useMemo(() => fn, arr)` btw.

In common we get lower time complexity as an exchange of more space, there are always some losses right?  I don't think it's wise to use useMemo in all cases even they are not CPU-intensive.

I think lint tools shall help us write code with higher efficiency, instead of just a rule to tell you what to do, even decrease your efficiency.

**Comment by threepointone** [comment]
React.memo can be useful even if there are no state hooks used inside the component (for example, if it's a very deep component tree with lots of content. Closing this issue, happy to reopen if you can provide more information.
