### ISSUE TITLE
ReactIs: Add ability to distinguish between elements and components

### ISSUE THREAD

**Issue by ericbiewener** [facebook/react#15095]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Can't distinguish between components and elements.

**What is the expected behavior?**
`ReactIs.isElement()` returns `true` for both `<MyComponent />` and `<div />`. I'd like to be able to distinguish between the two.

**Comment by markerikson** [comment]
Because a React "element" is an object like `{type : MyComponent, props : {}, children : []}`.  This is a different meaning than, say, "component" vs "HTML element".

Both `<MyComponent />` and `<div />` turn into calls to `React.createElement()`.  Therefore, both of those _are_ element, and `ReactIs.isElement()` is working as expected.

**Comment by ericbiewener** [comment]
Perhaps changing `isElement()` isn't the way to go. I'd just like a method to distinguish between the two cases I mentioned. For now, I'm checking `child.type === "string"` to see if it is `<div />`.
