### ISSUE TITLE
[Custom Hook] is my usage of custom hook right? or it's a react bug?

### ISSUE THREAD

**Issue by kkdev163** [facebook/react#15092]
**Do you want to request a *feature* or report a *bug*?**
I want to report a potential bug, or maybe it's just my code has bug?

**What is the current behavior?**
I  followed the official document to create a custom hook demo,  the example is [here](https://codesandbox.io/s/zxmq32464x). In this demo I have 3 reference of custom hook [useFriendStatus], but the state is not identical unless I  add [] as 2nd params of useEffect(as line 70). wait for 10 second, the text  and the followed circle color and picker circle color may be not identical.

**What is the expected behavior?**
use or not use [] as 2nd params will not impact the render behavior, but only the performance.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by gaearon** [comment]
>but the state is not identical 

What state is not identical? Not identical to what?

It would help when a bug report contains the exact *steps* to reproduce, the *expected* result, and the *actual* result. Otherwise it's very difficult to understand what you expected the code to do.

**Comment by gaearon** [comment]
I guess you mean the green indicator doesn't match the "online / offline" label?

**Comment by gaearon** [comment]
Looking at it, there are two issues in the implementation of the event emitter.

The first one is that **`subscribe` call doesn't immediately fire the callback**. This depends on your store implementation (e.g. Rx subscriptions immediately fire it but e.g. Redux doesn't). But if the subscription source changes, it makes sense that you want to query its state immediately.

So you either need to modify the store:

```diff
  subscribeToFriendStatus(id, callback) {
    if (!(this.listeners[id] instanceof Array)) {
      this.listeners[id] = [];
    }
    this.listeners[id].push(callback);
+   callback(this.userList[id]);
  },
```

Or you need to modify the Hook itself to query and set the current state immediately before subscribing.

The second problem (which causes the main issue I'm seeing) is that **this event emitter doesn't invoke a listener if it unsubscribes during a dispatch**. So what happens is that one component receives a state change and re-renders, causing effects of other ones to re-fire, and unsubscribing their callbacks from the last render just before they were supposed to be called.

The fix to this is to make the event emitter *clone* the listeners before dispatching:

```diff
-   const listeners = this.listeners[id];
+   const listeners = this.listeners[id].slice();
    if (listeners && listeners.length > 0) {
      listeners.forEach((callback, i) => {
        callback(this.userList[id]);
      });
    }
```

(This is how, for example, Redux solves a similar problem.) You would see the same problem in classes if a change caused by one event would cause subscription source to swap in another component. This is also why `[]` in the effect prevents this — but it would break the case when `id` changes over time. So the canonical fix is to **clone the listeners, not to specify `[]` as deps**.

With these two fixes, everything appears to work for me: https://codesandbox.io/s/vq73o1yxj7. As a bonus, you can optimize and avoid re-subscribing too often by passing `[friendId]` as effect deps: https://codesandbox.io/s/42j9xnzop9.

In general, subscribing to event emitters based on mutable data can be a bit gnarly if you want to handle all edge cases. (This is [true for classes too](https://github.com/facebook/react/tree/master/packages/create-subscription).) We'll provide a Hook called `useSubscription` that handles those well soon so you'll be able to plug it into your project.

Hope this helps! Let me know if you have more questions.

**Comment by gaearon** [comment]
Here's the version with the [`useSubscription` Hook](https://github.com/facebook/react/pull/15022) btw: https://codesandbox.io/s/zn7kq14k9p

```js
function useFriendStatus(friendId) {
  return useSubscription({
    source: friendId,
    getCurrentValue(id) {
      return ChatAPI.userList[id].isOnline;
    },
    subscribe(id, callback) {
      ChatAPI.subscribeToFriendStatus(id, callback);
      return () => {
        ChatAPI.unsubscribeToFriendStatus(id, callback);
      };
    }
  });
}
```

It handles more edge cases and is generally the recommended way to integrating with event emitters. It does similar things to what React Redux bindings do, for example. (We'll add it to the docs soon.)

**Comment by kkdev163** [comment]
It's amazing to have your so patient explaining, thanks for a lot. I spend a lot of time to understand this explaining:
> The second problem (which causes the main issue I'm seeing) is that this event emitter doesn't invoke a listener if it unsubscribes during a dispatch. So what happens is that one component receives a state change and re-renders, causing effects of other ones to re-fire, and unsubscribing their callbacks from the last render just before they were supposed to be called.

until I write the illustrate demo [here](https://codesandbox.io/s/549k8zj5wn), it will console information of the reason of this bug,  but i'm not very sure my understand is right.
