### ISSUE TITLE
invariant violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. forgot the export your component from the file ti's defined in , or your might have mixed up default and named imports.``

### ISSUE THREAD

**Issue by Shihaburabbi** [facebook/react#15103]
import React, {PureComponent } from 'react';
import {View,StyleSheet} from 'react-native';
import {
    FormInput,
    FormValidationMessage,
    FormLabel} from 'react-native-elements';

class Input extends PureComponent {

    state = {};

    render() {

        return (

            <View style={styles.root}>
                <FormLabel> Box </FormLabel>
                <FormInput />
                <FormValidationMessage>Error</FormValidationMessage>
            </View>

        );
    }
}

const styles = StyleSheet.create({
   root:{
       width: '90%',
       alignSelf:'center'
   }
});

export default Input;

**Comment by gaearon** [comment]
If you read the error message you pasted, you might notice that it suggests you're probably mixing up named and default imports. Try to fix this.

In general, we use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html

**Comment by mschipperheyn** [comment]
@gaeron I would recommend reopening this as a bug. This is one of the most useless error messages I encounter in React. Why? Because it doesn't indicate the import statement that generates the error. If you're not immediately checking for this result and changing multiple files at once, you'll spend a lot of time trying to figure out which of the imports, or exports is the culprit. 

I mean this is hardly a useful error message:
```
Check your code at index.js:67.
    in TheApp (at reactApplication/index.js:113)
    in Context.Provider
    in ChunkExtractorManager
    in RenderPromisesProvider
Error while running `getDataFromTree` { Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at invariant (/Users/mschipperheyn/development/projects/funcional/social-front/packages/server/Users/mschipperheyn/development/projects/funcional/social-front/node_modules/react-dom/cjs/react-dom-server.node.development.js:58:1)
    at ReactDOMServerRenderer.render (/Users/mschipperheyn/development/projects/funcional/social-front/packages/server/build/webpack:/Users/mschipperheyn/development/projects/funcional/social-front/node_modules/react-dom/cjs/react-dom-server.node.development.js:3443:1)
```

TheApp in this case is the entry component. So it's useless. The index.js is the interesting thing. But *which* index.js?

Common reasons for getting this error:
`import SimpleMutation from 'components/apollo' instead of `import SimpleMutation from 'components/apollo/SimpleMutation'

`import { SimpleMutation } from 'components/apollo' instead of `import SimpleMutation from 'components/apollo/SimpleMutation'

`forget to export a function`

`not exporting a function as default`

What I want is the filename plus containing folder and line number where the import failed. In this case, it seems I got everything but the containing folder.
