### ISSUE TITLE
Wrong height calculation of re-render nodes

### ISSUE THREAD

**Issue by tomsoir** [facebook/react#15162]
I have a problem with incorrect calculations of the container scroll height when adding new React nodes inside it.

Repro steps: 
1) open a pen (below)
2) scroll  down a bit
3) press "Prepend" button (to insert new element above)
Expected behavior: the parent container should not scroll when a new Dom element is inserted above.

**Correct behavior** (Jquery real-dom prepend) https://codepen.io/tomsoir/pen/LaJeYM
![2019-03-20 00 38 07](https://user-images.githubusercontent.com/301881/54666998-89e5a300-4aa8-11e9-835e-47f89854249f.gif)

**Incorrect behavior** (React virtual-dom prepend) https://codepen.io/tomsoir/pen/drqZWe
![2019-03-20 00 39 49](https://user-images.githubusercontent.com/301881/54667091-bac5d800-4aa8-11e9-9333-61063df6fda2.gif)

Do you have any ideas about how to fix this problem

**Comment by gaearon** [comment]
If you open the console you'll see that React warns you about missing `key`. Because `key` is missing, React has no way to distinguish *prepending* from *updating*.

Here's a version that works because it supplies a unique key for each new item: https://codepen.io/gaearon/pen/WmabGo

More about keys:

* https://reactjs.org/docs/lists-and-keys.html#keys
* https://reactjs.org/docs/reconciliation.html#keys
* https://overreacted.io/react-as-a-ui-runtime/#lists

Additionally, the code is a bit weird because in React we don't usually keep elements like `<div>` in state. Instead we keep *data* in state, and calculate elements from it during rendering. That's not the root of your issue, but this is why it's a bit difficult to assign meaningful keys in your case. Normally, your keys would be derived from actual data you're displaying.

**Comment by tomsoir** [comment]
@gaearon, Oh, the keeeeys, of course! Last deep night I read everything that could found regarding rendering in react and the `key` was my last hope this morning. Thank you so much, Dan. Awesome!
