### ISSUE TITLE
context value as a default prop?

### ISSUE THREAD

**Issue by bryceosterhaus** [facebook/react#15254]
Just had a general question regarding the "Rules of Hooks"

> Don’t call Hooks inside conditions

I was curious why this wouldn't be allowed for `useContext` for the example below

```jsx
const Icon = ({
	spritemap = React.useContext(IconSpriteContext), // eslint complains about this
	symbol,
	...otherProps
}) => {
	return (
		<svg
			{...otherProps}
			role="presentation"
		>
			<use data-href={`${spritemap}#${symbol}`} />
		</svg>
	);
};
```

We wanted to provide both a way to use a direct `prop` for the spritemap OR allow for context to be created at the top level of the app.

Any feedback is appreciated, thanks!

**Comment by kunukn** [comment]
I believe it warns you, because this a condition `spritemap = React.useContext(IconSpriteContext)`. 
If spritemap is not provided in argument, then apply `useContext`


This is untested and I am not sure about performance. But maybe this is better?

```
const Icon = ({
	spritemap,
	symbol,
	...otherProps
}) => {
        const defaultSpritemap = React.useContext(IconSpriteContext);
	return (
		<svg
			{...otherProps}
			role="presentation"
		>
			<use data-href={`${spritemap || defaultSpritemap}#${symbol}`} />
		</svg>
	);
};
```

**Comment by bryceosterhaus** [comment]
Yeah I'm mostly wondering _why_ its not recommended. I guess it could just be implementation hinderance with hooks, that they never be conditional regardless if its a default argument.

**Comment by kunukn** [comment]
I believe the rules exists because it relies on order https://reactjs.org/docs/hooks-rules.html#explanation

Your current code snippet might be ok now, there is only one hook and maybe the spritemap prop is not going to change. 

But what if you add more conditional hooks where you update the state and the spritemap  prop value can change over time?

To avoid potential buggy code I believe the lints are there to help you. 
But they are only warnings.

**Comment by Jokcy** [comment]
@kunukn Actually useContext does not add index to the hooks chain. It just return the context value.

**Comment by kunukn** [comment]
Interesting

then maybe it should NOT be a linter warning?, maybe the linter needs to be adjusted?

**Comment by gaearon** [comment]
Your example has a conditional call to `useContext` because it depends on the value of `spritemap`. This is why we warn.

We don't want to make the rules different for `useContext` and other Hooks. It also makes it hard to refactor later when you want to change `useContext(MyThing)` to a higher-level `useMyThing()` Hook which might include state or effects.
