### ISSUE TITLE
useEffect call recursively when add functional props as dependency

### ISSUE THREAD

**Issue by pavinthan** [facebook/react#15282]
**What is the current behavior?**
1. Define a component with useEffect and useState
```
const [style, setStyle] = useState({ color: "#000000" });
const [signature, setSignature] = useState("Your Name");

useEffect(() => {
    html2canvas(document.getElementById("signature-container")).then(
     canvasEl => {
       onChange(canvasEl.toDataURL());
      },
   );
}, [signature, style]);
```
2. Pass onChange function as props 
```<Text onChange={handleChange} />```

It's warn need to add `onChange` prop into dependency array of `useEffect` but If I add `onChange` prop into the array, `useEffect` call recursively

**What is the expected behavior?**
Don't need to warn if user don't pass function props as dependency

**Comment by gaearon** [comment]
Please read this, it answers this exact question. Let me know if you still have questions afterwards!

https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies

**Comment by pavinthan** [comment]
Hey @gaearon, 

I just updated the effect like this 

```
useEffect(() => {
    function emitChange() {
      html2canvas(document.getElementById("signature-container")).then(
        canvasEl => {
          onChange(canvasEl.toDataURL());
        },
      );
    }
    emitChange();
  }, [signature, style, onChange]);
```

but still It's call recursively, and here is the resource usage

<img width="1401" alt="Screen Shot 2019-04-01 at 7 21 52 PM" src="https://user-images.githubusercontent.com/13897936/55332813-c0152080-54b3-11e9-979a-93c3857f8a7d.png">

may I know, what I'm missing in this point ?

**Comment by pavinthan** [comment]
@gaearon may I know, How `useEffect` depend on functional props ?

**Comment by gaearon** [comment]
I think you missed the last part about useCallback in that link.

**Comment by gaearon** [comment]
Specifically, I think you want something like this for your onChange. It’s hard to say more without seeing the whole code example as a sandbox. 

![A8F601B0-7E89-4E72-984D-B9DECAC32536](https://user-images.githubusercontent.com/810438/55396537-fd24f580-553b-11e9-84f0-094c3b88c5c9.png)

**Comment by pavinthan** [comment]
Thanks for your explanations, sorry for your time 

This is my working implementation https://codesandbox.io/s/v0lwkokq00
This is broken implementation https://codesandbox.io/s/rl5o6zrx8n I just added `onChange` props into the dependency list to break my implementation 😢 

Implement notes: 
Once the signature and style states change I need to parse signature preview into canvas to get signature input as image 

I just add google font's stylesheet in this component because avoid external resource loading until user need them

calculate image from signature won't work inside input change because component won't render with current value so I pick `useEffect` for this case 


is this wrong implementation ? 😟

**Comment by gaearon** [comment]
OK this is interesting. Normally you'd fix this by passing an `onChange` with a stable identity:

```js
const handleChange = useCallback(() => {
  /* do stuff */
}, [/* its deps */])

<Text onChange={handleChange} />
```

But in your case it wouldn't work because it's *inside* Formik's render prop callback.

I'm not sure what's the idiomatic solution here from Formik's point of view.

But in your case, it seems like it's not actually important to re-run `onChange` if the `onChange` function itself changes. Therefore, you can use a ref to explicitly track its latest value:

```js
  const latestOnChange = useRef(onChange);
  useEffect(() => {
    latestOnChange.current = onChange;
  }, [onChange]);
```

And then you can all `latestOnChange.current` in the effect.

https://codesandbox.io/s/l5z8z3jj3z

**Comment by pavinthan** [comment]
thanks @gaearon to spend your valuable time for this clarification, It's really help understood where I missed and how handle this kind of situation in future, thanks again!

**Comment by gaurav5430** [comment]
This looks like a specific solution to a specific problem, is there a general pattern for this?


From hooks faq, it seems one of the correct ways / last resort is to memoize the function at the point it is defined, which means it is somehow the responsibility of the parent to do the memoization and the child has no explicit control over it. There is no easy way for the parent to even know that the child is expecting a memoized function, and will break (not deoptimized, but actually break) if the function is not memoized at the parent side.

in this case, it was actually not possible to change the usage in the parent, so we had to resort to the useRef hack, which is specific to this use case, but can that be generalized?

I have a shared component library, where some of the components have `useEffects` which are dependent on functions from `props`. Now I somehow need to tell every consumer of this component library that it is their responsibility to pass memoized functions. There is no way to enforce that explicitly. I cannot use the `dispatch` way because I can't expect every parent to be using `useReducer` and also can't expect every parent to listen to the same action type.

**Comment by enrique-ramirez** [comment]
Was there ever a proper answer to @gaurav5430 's question? I'm wondering the same. It feels odd to ask parents to pass functions with stable identity's as props. There's no way to know WHEN you need to do this, and asking them to use `useCallback` everywhere don't seem like a good idea.

I, too, have a shared component library and it seems to me unfeasible to ask consumers to always pass useCallback or else have the component break. I've relied on the useRef hack for a while, but it comes with its own limitations. Sometimes I also just ignore the empty dependency list and be done with it.

Quick sample would be a modal component:

```javascript
const Modal = ({ onClose }) => {
  useEffect(() => {
    const closeOnEscape = (event) => event.key === 'Escape' ? onClose() : null

    document.body.addEventListener('keydown', closeOnEscape)
    return () => document.body.removeEventListener('keydown', closeOnEscape)
  }, [])

  return createPortal(...)
}
```

Is there a best practice for this, @gaearon ?
