### ISSUE TITLE
How to fetch multiple times in single hook?

### ISSUE THREAD

**Issue by MonFig** [facebook/react#15342]
It seems that I can't fetch multiple APIs in a single hooks and use arrays to return values.

Code Sandbox: https://codesandbox.io/s/ykly7w7w9x

Say I have components  which need to fetch data with several APIs,  I would like to abstract the hook into a single `useMultipleFetch`. But the problem is state would not update after fetching finished. I must manually update the state by resize the window to force states update.

expected : 

```
Fetch result (expected 3 `done`)
["done","done","done"]
isLoadings result (expected all `false`)
[false,false,false]
```
but got: 

```
Fetch result (expected 3 `done`)
["","",""]
isLoadings result (expected all `false`)
[true,true,true]
```
for the first time.

BTW use a single fetch hook would avoid this problem, so I guess it could be that React can't handle state as a nested array.

Is this the wrong way I use it and is it not supported by React hooks? Or is there any other thing wrong?

**Comment by ghengeveld** [comment]
I suggest you take a look at [useAsync](https://react-async.dev). It takes a promise, so you can use Promise.all to do multiple fetches.

**Comment by MonFig** [comment]
@ghengeveld  Thanks. I will try that.

**Comment by MonFig** [comment]
@ghengeveld  BTW I've updated the sandbox and move `useEffect` out of the `forEach`.

**Comment by MonFig** [comment]
@ghengeveld  Though I didn't try useAsync, I did try to use `Promise.all` to handle this problem. I've updated the latest code in code sandbox. As you can see in consoles, value of `isLoadings` is updated when `setIsLoadings` is called but nothing happened. BTW I didn't see a clear `Promise.all` method in a glance of the document of react-async.

**Comment by RexSkz** [comment]
The problem is in `useMultipleFetch.js` (which is like redux's `states are equal`), it can be solved by using the following codes in `then`:

```javascript
setIsLoadings([...isLoadings]);
setResults([...results]);
```

BTW, if the `results` and `isLoadings` is really changed, there'll be an infinite loop in your code, because the changes will cause re-render and then fetch/change data again.

**Comment by MonFig** [comment]
@RexSkz Thank you for your help. Stupid me.

**Comment by shafiemukhre** [comment]
@RexSkz @MonFig I am @MonFig 's based code and it is working, however yes, there's infinite loop in my code if I have ids as my dependencies. But if I don't include it, the eslint will warn me that ids should be a dependencies. I think it is best that my custom hook do have dependencies but I don't want the infinite loop. How to prevent the infinite loop or what is a better way to do this to prevent the infinite loop?

`export function useConversation(ids){

    const [names, setNames] = useState(Array(ids.length).fill(''))
    const [dates, setDates] = useState(Array(ids.length).fill(''))
    const [times, setTimes] = useState(Array(ids.length).fill(''))

    useEffect( () => {
        async function fetchData(id, i){
            const response = await fetch(`https://api.symbl.ai/v1/conversations/${id}`, {
                method: 'GET',
                headers: {
                    'x-api-key': auth.accessToken
                }
            })
            const data = await response.json()
            newNames[i] = data.name
            newDates[i] = data.startTime.slice(0,10)
            newTimes[i] = data.startTime.slice(11,19)
        }
        const newNames = []
        const newDates=[]
        const newTimes=[]

        ids.map((id, i) => {
            fetchData(id, i).then(() => {
                setNames([...newNames])
                setDates([...newDates])
                setTimes([...newTimes])
                
            })
        })

    },[ids])

    return [names, dates, times]
}`

**Comment by RexSkz** [comment]
@shafiemukhre 

I guess you'd like to execute the callback in `useEffect` only once (like the `componentDidMount` in class component). In this case, **`// eslint-disable-line react-hooks/exhaustive-deps` seems ok for me**, because the comment will remind me that "this callback won't be executed again, `useConversation` is not a reactive function".

If you'd like to make `useConversation` reactive to `ids` (like `componentDidMount`+`componentDidUpdate` in class component), just keep this code, and check the outer code which calls `useConversation`, make sure the `ids` wont' be changed after `useConversation`. A possible way is: **do not use `[names, dates, times]` to calculate the new `ids`, just keep them in your component and use them in JSX, `ids` should be changed only in necessary**.

P.S. To avoid performance issue, using batch API such as `fetch(url, { params: ids })`, then call `setNames`, `setDates`, `setTimes` only once after `fetch`. Operator `...` has O(N) time complexity, if you execute N times, it'll cost O(N^2), which means if you have 30 items in `ids`, you'll get about 30\*30\*3/2=1350 temp items.
