### ISSUE TITLE
Non existent Else-IF

### ISSUE THREAD

**Issue by jajosheni** [facebook/react#15348]
OMG, and everyone talks about react being smth big. If you dont support Else-If React will be "just another thing"

**Comment by milesj** [comment]
@jajosheni There are many ways to achieve else-if. Do you have an example that you're trying to solve?

**Comment by jajosheni** [comment]
@milesj , thanks for the reply. I have been coding for 5 years now and i know how to get around "else-if" in other ways, but what is programming in the first place? Making a choice based on conditions and else if is just a very useful way to throw away.

**Comment by milesj** [comment]
@jajosheni Right, but there are multiple ways to handle else-if in React. It all depends on context and how the markup is structured. The best solution, in my opinion, is to use composition and encapsulate pieces across multiple components, instead of having so much markup in a component that else-if is required.

**Comment by aweary** [comment]
We use the issue tracker for bug reports and feature requests.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
