### ISSUE TITLE
Support `useState` style lazy state initialization in `useReducer`

### ISSUE THREAD

**Issue by fediev** [facebook/react#15360]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Signatures of `useState` and `useReducer` for lazy state initialization are different and not consistent.

- signature of `useState`
```ts
function useState<S>(initialState: () => S)
```

- signature of `useReducer`
```ts
function useReducer<S, I, A>(
  reducer: (S, A) => S,
  initialArg: I,
  init: I => S,
)
```

**What is the expected behavior?**

Support below signature of `useReducer` for lazy initialization.

```ts
function useReducer<S, A>(
  reducer: (S, A) => S, 
  initialState: () => S
)
```

This will allow lazy initializations like this.

```js
// Lazy initialization example in https://reactjs.org/docs/hooks-reference.html#usereducer 
// will be
function Counter({initialCount}) {
  // previously
  // `const [state, dispatch] = useReducer(reducer, initialCount, init);`
  const [state, dispatch] = useReducer(reducer, () => init(initialCount));
  // ...
}

// To get initial state from `reducer` (redux style)
// `useReducer(reducer, undefined, reducer)` will be
const [state, dispatch] = useReducer(reducer, reducer);
```

**Which versions of React, and which browser / OS are affected by this issue?**

16.8

**Comment by acdlite** [comment]
Thanks for filing an issue!

> Signatures of useState and useReducer for lazy state initialization are different and not consistent.

They are intentional inconsistent. The type of the a reducer is:

```js
type Reducer<S, A> = (prevState: S, action: A) => S
```

With your proposal, the type for `prevState` would have to include `void`:

```js
type Reducer<S, A> = (prevState: S | void, action: A) => S
```

For this, and other reasons, we chose to make the lazy init function separate from the reducer.

Also, `useReducer` is already a stable feature, so this would be a breaking change. We would need a really compelling reason to change it at this point.
