### ISSUE TITLE
In FireFox textarea display error with Chinese IME

### ISSUE THREAD

**Issue by Crayonn** [facebook/react#15380]
What is the current behavior?
Enter 6 Chinese characters in the textarea, textarea content will disappear, however it still in the DOM。 this behavior does not appear in input component or other Browser.  

Demo
This behavior was reproduced in a codepen: [https://codepen.io/anon/pen/VNbKJq](https://codepen.io/anon/pen/VNbKJq)

versions:

React 16.8.6
firefox 66.0.1

Can someone help me?

Many thinks.

**Comment by kunukn** [comment]
The logic of string length and slicing should be adjusted. Chinese signs are longer than e.g. English characters and the string.length will yield a different result.

Instead of Chinese signs you could also test with Emoji signs like this: 🤔

I suspect this is not a React issue and this issue can be reproduced in Vanilla JS.

https://stackoverflow.com/a/54369605/815507

**Comment by Crayonn** [comment]
I solved it。

https://developer.mozilla.org/zh-CN/docs/Web/Events/compositionstart
