### ISSUE TITLE
[Feature Request] Allow components to set their own 'key'

### ISSUE THREAD

**Issue by asbjornh** [facebook/react#15592]
__TLDR__: Specifying keys when mapping from data to components feels wrong to me even after several years. It would be really nice if components could specify their own `key` instead.

This is how you supply keys when rendering a list of components:

```jsx
const User = ({ name, email }) => (
  <div>{name}, {email}</div>
);

const View = ({ users }) => (
  <div>{users.map(user => <User key={user.email} {...user} />)}</div>
); 
```

This has always felt dirty to me because in order to do render a list of `User`, `View` has to know implementation details about `User`. From a separation of concerns standpoint this feels icky. Also, this creates some sort of tight coupling problem between `User` and any component that needs to render a list of it. If you have many lists of `User` in your app and need to refactor it, best case scenario is you have to do a lot of search-replace and in the worst case you get bugs.

I wish there was a way for components to handle the mapping of `props -> key` internally. Maybe something like:

```jsx
const User = ({ name, email }) => (
  <div key={email}>{name}, {email}</div>
);

const View = ({ users }) => (
  <div>{users.map(user => <User {...user} />)}</div>
); 
```

More possible solutions [below](https://github.com/facebook/react/issues/15592#issuecomment-491265016).

If enough people like this idea I hope you'd consider an official API/solution that allowed this. :) 

EDIT: Removed some arrow function related stuff because in hindsight it making my point confusing.
EDIT: Rewrite of entire post based on @malerba118's [comment](https://github.com/facebook/react/issues/15592#issuecomment-491265016)

**Comment by malerba118** [comment]
Hmm, so as you sort of alluded to, I think it's a mistake to think of Comp as a component (Cause react renders "`React.createElement('div')` instead of `React.createElement(Comp)`"). Comp seems not really to be a component but rather a callback disguised as a component. To avoid arrow functions you could do something like this to apply keys. 

```jsx
const applyKey = (Comp, keyName) => {
  return listItem => <Comp key={listItem[keyName]} {...listItem} />;
};

let users = [
  {
    name: "veronica",
    email: "veronica@gmail.com"
  },
  {
    name: "troy",
    email: "troy@gmail.com"
  }
];

const User = ({ name, email }) => {
  return (
    <div>
      <h2>{name}</h2>
      <h4>{email}</h4>
    </div>
  );
};

const View = () => <div>{users.map(applyKey(User, "email"))}</div>;
```
[https://codesandbox.io/s/jzq77274rv](https://codesandbox.io/s/jzq77274rv)

**Comment by asbjornh** [comment]
@malerba118 Yes, I've tried stuff like that :) I've edited my original post because my point isn't primarily of avoiding arrow functions. My point is about being able to render lists of components without having to know stuff about their implementation. :)

**Comment by malerba118** [comment]
@asbjornh 

Ahh, I think I see. So currently the way it's done is like this:
```jsx
const User = ({ name, email }) => {
  return (
    <div>
      <h2>{name}</h2>
      <h4>{email}</h4>
    </div>
  );
};

const View = () => <div>{users.map(user => <User key={user.email} {...user} />)}</div>; 
```
But you don't like this because this means that `View` knows that users have emails. It would be a better separation of concerns for `User` to have the logic indicating `user.email` is the key.

So you're hoping to see this:
```jsx
const User = ({ name, email }) => {
  return (
    <div key={email}>
      <h2>{name}</h2>
      <h4>{email}</h4>
    </div>
  );
};

const View = () => <div>{users.map(user => <User {...user} />)}</div>; 
```
I don't know react's reconciliation algorithm well enough to understand if this is feasible, but I can get behind this because this does make sense to me regarding separation of concerns.

`key` is essentially acting as an `equals` method to determine equality of component instances. It doesn't really make sense for the to parent define the child's `equals` method.

I'd be curious about something like:
```jsx
const User = ({ name, email }) => {
  return (
    <div>
      <h2>{name}</h2>
      <h4>{email}</h4>
    </div>
  );
};
User.keyProp = 'email';

const View = () => <div>{users.map(user => <User {...user} />)}</div>; 
```
This would let the component determine its own equality metric but also would ensure all immediate children of a list could still have a key.

**Comment by asbjornh** [comment]
Yes! Spot on :) Exactly what I mean about separation of concerns. I may have to edit my original post again and use your example instead

As for your last example something like that would be ok (and that pattern is already possible if you create a custom `map` helper), but I think that your second example is the most ergonomic and intuitive one.

**Comment by robertknight** [comment]
The key has to come from the parent because it is the parent that knows what context the component is being rendered in, and thus which set of things the key has to be unique amongst. For example, there is nothing to stop the parent rendering two `User` component siblings with the same `user` prop (a bit pointless perhaps, but perfectly legal), in that case it would have to find a different key.

**Comment by asbjornh** [comment]
@robertknight I'm not proposing to replace the current behavior; I'm proposing to extended it :)

I'm sure there are cases where handling keys in parents makes more sense, but for the type of stuff I do (CMS-backed corporate websites) that has never been the case for me.

**Comment by robertknight** [comment]
Now you have two ways to achieve the same thing, an an extra API to support, and a little bit of extra overhead when rendering everything :) Not a lot of extra added complexity in this case, but you can imagine the tragedy of the commons if the maintainers say yes to too many requests like this.

**Comment by asbjornh** [comment]
Doesn't seem to be much interest in this. Closing 🙂
