### ISSUE TITLE
The react project is developed on IOS system，how to running the project in window10 system？

### ISSUE THREAD

**Issue by Ceeson** [facebook/react#15643]

**Comment by h3rmanj** [comment]
`npm start`

**Comment by threepointone** [comment]
React doesn't have any dependencies on iOS. We have documentation on how to get started with a web project here https://reactjs.org/tutorial/tutorial.html If you're looking for a starter kit, consider create-react-app, which gives an environment and build system for react dom sites. If you're looking to make mobile apps, you maye be interested in react-native https://facebook.github.io/react-native/. If you're looking to build native apps for windows 10, microsoft has a version of react native for windows https://github.com/microsoft/react-native-windows

closing this issue since it isn't a bug or feature request. consider using a community resource like stack overflow for further questions and support https://reactjs.org/community/support.html
