### ISSUE TITLE
Set functional component as state by useState will occur "Do not call Hooks inside" error

### ISSUE THREAD

**Issue by filenwind** [facebook/react#15665]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I set a Functional component where using useState as a state for another functional component, it will occur error **Do not call Hooks inside**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

[https://codesandbox.io/s/2ww0rp5pl0](https://codesandbox.io/s/2ww0rp5pl0)
Open developer tools, error can be find in console.

The interesting is, if I wrapped a hoc like **memo**, the error will gone.
[Wrapped by memo](https://codesandbox.io/s/eloquent-ramanujan-oroul)

**What is the expected behavior?**

I think it shouldn't report error, or is my misunderstood.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.6

**Comment by threepointone** [comment]
replace `setComponent(Test)` with `setComponent(() => Test)` and your code will work. explanation - when you pass a function to a `setState`, it assumes it's the functional update form (https://reactjs.org/docs/hooks-reference.html#functional-updates), and tries to call it immediately. (`memo` doesn't return a function, which is why your code worked when you wrapped it)

closing this issue.

**Comment by filenwind** [comment]
**when you pass a function to a setState, it assumes it's the functional update form** 

Ha ha ha, it's really a stupid mistake, thank you very much!!!!
