### ISSUE TITLE
Question: memo + useState

### ISSUE THREAD

**Issue by python273** [facebook/react#15661]
Does it make sense to use `memo` + `useState`?
```js
const Dunno = memo(({a}) => {
  const [b, setB] = useState(0);
...
```
If it doesn't, why the component updates when `setB` is called? 🤔 

---

https://stackblitz.com/edit/react-dxosdw
https://reactjs.org/docs/react-api.html#reactmemo
> If your function component renders the same result **given the same props**, you can wrap it in a call to React.memo for a performance boost in some cases by memoizing the result. This means that React will **skip rendering the component, and reuse the last rendered result**.

**Comment by threepointone** [comment]
state is internal to a component, so it's allowed to update itself. memo does its memoizing on incoming props, not on state. 

(that said, if you call setB with an unchanged value (for example, in your snippet, if you call `setB(0)`), the component will bail out of rendering since it knows that state hasn't changed)

closing this issue since it isn't a bug or feature request.
