### ISSUE TITLE
Heavy Computation

### ISSUE THREAD

**Issue by nvoisin** [facebook/react#15676]
Hi all,

I'm trying to run an app with some intensive calculations and it freezes the App. I've tried to use async but no to avail. You'll find an example of code I made here:
[https://codesandbox.io/s/heavycalculation-v35yb?fontsize=14](https://codesandbox.io/s/heavycalculation-v35yb?fontsize=14)

In the Main component, replace loop upper bound of 1000 with 100,000 or 1,000,000.

How would I be able to achieve this? It seems to be quite similar as when I'm calling a fetch, and yet it freezes here.

Thanks for your help !

**Comment by kunukn** [comment]
I see you render 10 Main components. Each of those components have a for loop which blocks the main thread. 

Some options:
* look into Web workers
* move the computation server-side and use API to get the result (fetch solution)
* don't block the main thread and amortise the calculation time using setTimeout to allow the browser to be responsive
* google `Heavy Computations in Javascript`

>It seems to be quite similar as when I'm calling a fetch, and yet it freezes here.

Calling fetch does not freeze because that doesn't block the main thread.

**Comment by nvoisin** [comment]
Thanks for your reply. I've looked a bit into Web workers, but will look deeper into it. Don't really like the aspect of a messaging protocol, where everything has to JSONified back and forth.

**Comment by vishalgiri** [comment]
Your codesandbox is no longer available.

Just to add some more details.

Javascript execution is single threaded, learn more about event loop at:
https://www.youtube.com/watch?v=8aGhZQkoFbQ
https://www.youtube.com/watch?v=cCOL7MC4Pl0

Because React, Angular, Vue, all are libraries or frameworks built on top of javascript, so you could run into similar issue in any of those and even with just pure javascript and nodejs.

kunukn is spot on with suggestions to overcome the issue you are facing.

Sometime it is easy to see and debug what is blocking the main thread, in future if you come across any other hard to troubleshoot issue, here is a great article about troubleshooting performance issues with help of Chrome Developer Tools: https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/

However, just to be clear this issue has nothing to do with React.

**Comment by akashkasurde** [comment]
> Thanks for your reply. I've looked a bit into Web workers, but will look deeper into it. Don't really like the aspect of a messaging protocol, where everything has to JSONified back and forth.

https://github.com/GoogleChromeLabs/comlink
