### ISSUE TITLE
Application is not rendering in IE 11

### ISSUE THREAD

**Issue by aniltomar10** [facebook/react#15697]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Application is not rendering in IE 11. Blank page in IE 11.

**What is the expected behavior?**
It should render same as google chrome.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.8.6.
Trying first time React framework.

**Comment by anzome** [comment]
There could be a dozens of the reasons for that. Please add some additional informarmation. What kind of exception do you see in developer tool?

**Comment by aniltomar10** [comment]
I don't see any error in console log of IE 11 developer tool. 

Followed below steps to start with React:

created new project using command npx create-react-app my-app
run project using command npm start
It opens application in IE 11 by default but page is blank. Copy same url (http://localhost:3000) in google chrome and it works.

**Comment by vishalgiri** [comment]
To make your CRA (create-react-app) work with IE 11 you will need to add some polyfills.
Ref: [Supported Browsers and Features - CRA](https://facebook.github.io/create-react-app/docs/supported-browsers-features)

However, Edge, Firefox, Safari (on macOS or iOS), Chrome should work fine, without any polyfill.

Here is one of the way to add polyfill: https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md

More details:
React and CRA are two different projects, CRA internally uses React and many other packages.

If you just use React, then also to make it work with IE 11, you may need to add some polyfills. Because IE 11 has some non-compliant implementation of some specifications.
Ref: [Javascript Environment Requirements - React](https://reactjs.org/docs/javascript-environment-requirements.html)

For React, to me this page does not seem clear about browser support: https://reactjs.org/docs/react-dom.html#browser-support that may have misled you to assume that IE11 is supported without polyfill.

CRA Documentation is pretty clear on which browser and features it supports.

**Comment by mazer-rakham** [comment]
Polyfills should be included in create-react-app IMHO
