### ISSUE TITLE
Dispatch didn't call reducer immediately ?

### ISSUE THREAD

**Issue by yanyu0517** [facebook/react#15743]
I had been working on replacing redux with useReducer

When I call dispatch console.log the store in a row, found the value inside of store had not been changed by the reducer.

I guess maybe the reducer is not called in sync with dispatch.

**Comment by Jokcy** [comment]
Yes, just like setState in ClassComponent

**Comment by yanyu0517** [comment]
That's so sad 😔 . 
The async mechanism has been made a fundamental difference in redux.

**Comment by acdlite** [comment]
> That's so sad 😔 .

You may think you prefer synchronous rendering because it's easier to debug, but it has huge downsides, too. One is that it blocks the main thread, including user interactions, until the render has fully completed. By deferring the render to a later task, the UI can remain responsive. There are lots of other benefits to React's scheduling model, many of which haven't shipped yet. You can read more about our ongoing Concurrent React project here: https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-q2-2019-the-one-with-concurrent-mode

We're brainstorming some ways to make debugging React components easier, e.g. a special version of `console.log` that displays messages according to their position in the component type.
