### ISSUE TITLE
propType validation produces a warning for a component wrapped in React.memo

### ISSUE THREAD

**Issue by dmitriyK1** [facebook/react#15752]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After wrapping a component with React.memo, passing it as a prop and checking a prop type via `PropTypes.oneOfType([PropTypes.func, PropTypes.node]),` I'm getting a warning "Warning: Failed prop type: Invalid prop `Component` supplied to `App`."

Link to example: [https://github.com/dmitriyK1/proptypes-warning](https://github.com/dmitriyK1/proptypes-warning)

**What is the expected behavior?**
There should be no warning if passing a component wrapped in React.memo as a prop and validating it with `PropTypes.oneOfType([PropTypes.func, PropTypes.node]),`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

"prop-types": "15.7.2",
"react": "^16.8.6",
"react-dom": "^16.8.6",

macOS: 10.14.4
Google Chrome: 76.0.3805.0

**Comment by eps1lon** [comment]
How do you use that prop? If you're doing something like 

```jsx
const { Component } = props;
return <Component />
```

Then `PropTypes.node` isn't correct since it would accept e.g. array. What you probably want to use is either `PropTypes.oneOfType([PropTypes.func, PropTypes.object])` for older versions of `prop-types` or `PropTypes.elementType` for the latest version.

`PropTypes.node` is anything that can be passed as a children to host components e.g. `<div>{node}</div>`.

**Comment by acdlite** [comment]
I think you want `PropTypes.elementType`.

But, please file PropTypes issues with the `prop-types` project. https://github.com/facebook/prop-types
