### ISSUE TITLE
Using ref value in useEffect cleanup function

### ISSUE THREAD

**Issue by WilsonCWong** [facebook/react#15841]
I'm currently trying to use the cleanup function of useEffect to remove any setTimeouts remaining to ensure it doesn't run when the component unmounts.
```
  const timers = useRef([]);

  useEffect(() => {
    return () => {
      for (let i = 0; i < timers.current.length; i++) {
        clearTimeout(timers.current[i]);
      }
    }
  }, [])
```

It works, but I get a warning that says
```
The ref value 'timers.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a node rendered by React, copy 'timers.current' to a variable inside the effect, and use that variable in the cleanup function.
```

I'm wondering, is this something I should be concerned about? The ref value is only used during cleanup and it's not linked to any rendering. 

Also, out of curiosity, what is this warning for exactly? I'm not quite sure I get it. Is it because if the ref is referring to a component, that component could be changed by the time the effect cleanup function runs?

**Comment by kunukn** [comment]
>I'm wondering, is this something I should be concerned about? The ref value is only used during cleanup and it's not linked to any rendering.

I wouldn't be concerned about this, if the `timers.current` doesn't relate to DOM elements.


>Also, out of curiosity, what is this warning for exactly? I'm not quite sure I get it. Is it because if the ref is referring to a component, that component could be changed by the time the effect cleanup function runs?

I believe that is correct. 

If you read the console.logs from this example you would notice the difference
https://codesandbox.io/s/react-useeffect-useref-warning-407fj

The first `useEffect` ignores the hooks warning and on unmount, it logs `null`
The second `useEffect` does a variable copy


I can't see the full code you are using. I am uncertain whether using `useRef` would be needed for your case.

**Comment by eeasuper** [comment]
I'm also in a very similar predicament:
I cleared all timeouts in my clean-up function yet I still get this error:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

I though this stackoverflow [link](https://stackoverflow.com/questions/53090432/react-hooks-right-way-to-clear-timeouts-and-intervals) would be the perfect answer for me but it doesn't work for me.

Here is my code. Is something wrong with my code or is it something else?
`
  const [openSb, setOpenSb] = React.useState(false);
  const [sbTimeout, setSbTimeout] = React.useState(null);

  useEffect(()=>{
    let timeO = setTimeout(()=>{
      setOpenSb(false);        
    }, 3000);
    setSbTimeout(timeO); 

    return ()=>{
      clearTimeout(sbTimeout);
    }
  },[openSb])

  function openSnackbar(message){
    setOpenSb(true);
  }
`

It doesn't change when I use a React.useRef() to store my timeout node instead of using useState() like in the code above.

**Comment by ZooTopiaGG** [comment]
> > I'm wondering, is this something I should be concerned about? The ref value is only used during cleanup and it's not linked to any rendering.
> 
> I wouldn't be concerned about this, if the `timers.current` doesn't relate to DOM elements.
> 
> > Also, out of curiosity, what is this warning for exactly? I'm not quite sure I get it. Is it because if the ref is referring to a component, that component could be changed by the time the effect cleanup function runs?
> 
> I believe that is correct.
> 
> If you read the console.logs from this example you would notice the difference
> https://codesandbox.io/s/react-useeffect-useref-warning-407fj
> 
> The first `useEffect` ignores the hooks warning and on unmount, it logs `null`
> The second `useEffect` does a variable copy
> 
> I can't see the full code you are using. I am uncertain whether using `useRef` would be needed for your case.

Perfect

**Comment by Christopher-Warren** [comment]
I'm providing a solution here because this is the first thread that shows when I googled the issue and others may run into this.
> It works, but I get a warning that says
> 
> ```
> The ref value 'timers.current' will likely have changed by the time this effect cleanup function runs. If this ref points to a node rendered by React, copy 'timers.current' to a variable inside the effect, and use that variable in the cleanup function.
> ```
