### ISSUE TITLE
Button onClick firing incorrect event

### ISSUE THREAD

**Issue by wnvuong** [facebook/react#15880]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

- Have a form with a button of type submit and button of type button. 
- Have a state value init to false and show the "submit" button when its true and show the "regular" button when false. 
- Set onClick for the regular button to change state value to true showing the submit button. 
- The submit button will be fired even thought it wasn't clicked. 
See demo here: https://jsfiddle.net/hdgbr473/2/

**What is the expected behavior?**
The event should only be fired on the regular button not the submit button. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
v16.8 / Chrome. unsure

**Comment by RafaelCorreaQuantik** [comment]
Just an addiction, I thought it might be a babel compiler bug, so I changed from JSX to React.createElement and the error still persists.

My guess is that React is only changing the button attributes, so when the state changes, it's the same button that got the click event, thus submitting the form.

**Comment by RafaelCorreaQuantik** [comment]
Funny thing is, that with [hooks](https://jsfiddle.net/1650pujy/), the problem won't happen.

**Comment by abhishek71994** [comment]
Is this issue solved? If not I am interested to try to work on it.

**Comment by RafaelCorreaQuantik** [comment]
@abhishek71994 - I believe it still persists

**Comment by tenkunkyab** [comment]
@RafaelCorreaQuantik I believe it's because you've not specified what **type** of the button is. By default a button, when no type if defined, is considered as a type "**submit**". 
In the JSfiddle that you've shared, if you change the button to an input things are looking good.

That being said, I was able to find a closed Issue raised on similar topic. https://github.com/facebook/react/issues/8554
