### ISSUE TITLE
[react-hooks/exhaustive-deps] False positive for nested dependencies in useEffect hook

### ISSUE THREAD

**Issue by johnloven** [facebook/react#15924]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The following code

```javascript
const callback = useCallback(() => {
    console.log("CALLBACK");
}, []);

const wrapper = { callback };

useEffect(() => {
    wrapper.callback();
}, [wrapper.callback]);
```

gives the following `react-hooks/exhaustive-deps` warning

> React Hook useEffect has a missing dependency: 'wrapper'. Either include it or remove the dependency array

If the `useEffect` is replaced by the following

```javascript
useEffect(() => {
    const callbackReference = wrapper.callback;
    callbackReference();
}, [wrapper.callback]);
```

there are no warnings.

**What is the expected behavior?**
There should be no warnings in either case.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react: 16.8.4
eslint-plugin-react-hooks: 1.6.0

**Comment by bartlangelaan** [comment]
This issue is especially cumbersome for people that are trying out React Hooks for the first time. That's because a context provider that provides a setter would already create a rerender loop.

I've created a CodeSandbox to illustrate the use case here:
[![Edit react-issue-15924](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-issue-15924-yz8uq?fontsize=14)

I've tried to understand how the eslint rule works, but I'm not familiar with the eslint visitors so I've no clue where to look in the [long file](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js).

**Comment by miraage** [comment]
It is not a bug. It is the only thing that is expected. 
You are actually using "wrapper" variable, so it must be added to the deps list.

**Comment by miraage** [comment]
> What is the expected behavior?
There should be no warnings in either case.

Should be warnings in both cases. You are actually using `wrapper` variable, so it must be added to deps list.

**Comment by marceloadsj** [comment]
@miraage I'm not sure about it:

![image](https://user-images.githubusercontent.com/4874089/60454798-1c174e80-9c35-11e9-953a-fc230787f55f.png)

This happen with functions, but not with values.

**Comment by miraage** [comment]
@marceloadsj eslint rule is seeking for variables used. But I totally agree with idea that tools should help people by covering common patterns, e.g. this case. 
Another case we can "complain" about is when we are 100% sure that a certain variable is a constant which will never change, yet eslint rules says "dependency is missing".
My understanding of this situation is the eslint rule would rather be too careful about dependencies rather than we miss it.

**Comment by bartlangelaan** [comment]
Hey @miraage,

You're absolutely right. The eslint rule should report every variable that we use as missing when not included in the dependency array.

However, the `wrapper` variable isn't really used, only a method on that variable. 

If we would do something with `wrapper` directly it should definitely be added to the dependency array. But in this case, we only use `wrapper.callback` and thus adding `wrapper.callback` to the dep array should suffice with being 'careful' enough.

Also, the use cases provided by @johnloven, @marceloadsj and me in this issue thread point out that this is something users can walk into very quickly.

> Another case we can "complain" about is when we are 100% sure that a certain variable is a constant which will never change, yet eslint rules says "dependency is missing".

So, in my understanding, this is not about 'knowing that a variable is constant' but this is about 'knowing that a variable is not used'. 
If a variable is known for being constant, it's fine to be added to the dependency array (it won't trigger extra executions of the effect). 
But adding a variable to the deps array that isn't used will re-trigger the effect while that wasn't needed.

**Comment by miraage** [comment]
@bartlangelaan I totally understand your position. I believe the solution could be achieved by adjusting AST visitor(s) of the eslint rule

**Comment by bartlangelaan** [comment]
I did some research, and found why the ESLint plugin is currently configured like this.

In the code samples shared in this thread, it seems pretty obvious that the function itself should be included in the dependency array instead of the object it comes from. To state another example, see this component:

```js
function MyComponent() {
  const myArray = useArray();
  useEffect(() => {
    myArray.addEntry('item');
  }, [myArray.add]); // Currently triggers a warning, but shouldn't
}
```

However, _if you use the result of the function_ it's more obvious that the object should be included in the dependency array.

For example:

```js
function MyComponent() {
  const myArray = useArray();
  useEffect(() => {
    if (myArray.hasEntry('item') {
      console.log('Whoop!');
    }
  }, []);
}
```

Because the output of `hasEntry()` is probably based on the `myArray` contents, the linting rule should suggest that `myArray` is added as a dependency instead of `myArray.hasEntry`.

The linting rule is currently configured to always add the object to the deps array if a function from it is executed, but I believe it should only do that if the return value of the function is actually used.

I think I found where this logic is located in the ESLint plugin, and I'm currently working on a PR that changes the behaviour to include the function in the deps array as long as its return value isn't used.

Also, the following issue seems related: #15448

**Comment by gaearon** [comment]
No, this is not a bug. The way the rule works is intentional and correct behavior.

These two examples are **not** identical:

```js
const callback = useCallback(() => {
    console.log("CALLBACK");
}, []);

const wrapper = { callback };

useEffect(() => {
    wrapper.callback();
}, [wrapper.callback]);
```

```js
useEffect(() => {
    const callbackReference = wrapper.callback;
    callbackReference();
}, [wrapper.callback]);
```

In the first example, `wrapper.callback()` passes `wrapper` as `this` value to the callback. This is why it needs to be a dependency.

In the second example, `callbackReference` does not pass any `this` value to the callback. This is why `wrapper` does not need to be a dependency.

It's subtle, but if the callback read `this`, you'd get potentially stale values if you didn't follow the lint rule.

----

For the common case, the fix it just to destructure it before calling.

```js
const callback = ...

useEffect(() => {
    callback();
}, [callback]);
```

**Comment by marceloadsj** [comment]
Hey @gaearon tks for your reply!

I think your example have just a small issue, altought the general idea is ok:
```javascript
const callback = useCallback(() => {
    console.log("CALLBACK");
}, []);

const wrapper = { callback };

useEffect(() => {
    wrapper.callback();
}, [wrapper.callback]);
```

The callback is an arrow fn, and it don't bind to `this`, so the `this` won't be the wrapper obj.

**Comment by donaldpipowitch** [comment]
Hi @gaearon,

thank you for your explanation. I just stumbled over this myself. It wasn't obvious to me why the ESLint rule behaves the way it does. I needed your explanation to understand that. I wondered if this rule can be relaxed a little bit? When I think about `prettier` it is very opinionated and formats mostly everything, but sometimes it respects manually added white space for example. I wonder if this rule could behave similar?

E.g. if someone writes this:

```js
useEffect(() => {
    someObj.doSomething();
  }, []);
```

warn and `--fix` it to this (which would be your default recommendation):

```js
useEffect(() => {
    someObj.doSomething();
  }, [someObj]);
```

But if someone writes the next example than allow it:

```js
useEffect(() => {
    someObj.doSomething();
  }, [someObj.doSomething]);

// currently that would be --fix'ed to [someObj, someObj.doSomething]
```

I could also imagine a configuration (similar to the `eqeqeq` rule where you can set `allow-null`.)

**Comment by LeopoldLerch** [comment]
Hi
I have this function: 

`const updateCanAddItems = useCallback((canAdd: boolean) => {
            setCanAddItems(canAdd);
            if (props.onCanAddItems) {
                props.onCanAddItems(canAdd);
            }
        }, [props.onCanAddItems]);`

however, the exhaustive-deps-Rule complains and fixes it with changing to simply "props" in the dependencies, which of course results in updating the function on every render.

However, if i do like this, it is OK for the rule:

` const updateCanAddItems = useCallback((canAdd: boolean) => {
            setCanAddItems(canAdd);
            const x = props.onCanAddItems;
            if (x) {
                x(canAdd);
            }
        }, [props.onCanAddItems]);`

It is technically the same, but the second one is one more declaration of a variable (and in my opinione more difficult to understand why to do so.

Is this a bug or as designed?

**Comment by bartlangelaan** [comment]
Hey @LeopoldLerch,

while your example functions look the same, they are not.

To turn your functions into a runnable example:
```typescript
const updateCanAddItems1 = (canAdd) => { 
  setCanAddItems(canAdd); 
  if (props.onCanAddItems) {
    props.onCanAddItems(canAdd);
  } 
};
const updateCanAddItems2 = (canAdd) => {
  setCanAddItems(canAdd); 
  const x = props.onCanAddItems; 
  if (x) { 
    x(canAdd); 
  } 
};

const props = {
  onCanAddItems: function() {
    console.log(this.someProperty);
  },
  someProperty: 'test',
}

// This logs 'test' to the console
updateCanAddItems1();
// This gives an error
updateCanAddItems2();
```

Because in the second example `props` is not passed to `onCanAddItems` as `this` it also does not have to be in the dependencies array. So, this is as designed.

You can try it out here: https://repl.it/@bartlangelaan/React-15924-example

**Comment by LeopoldLerch** [comment]
well, you are right with "this", but, as this is useful in most cases, in my opinion it is not in regards of the props-object passed to the functional component.

the functions in there won´t be related to the props-object itself in, lets say, most cases, if not all. 

In my opinion there should be at least an exception for this rule in regards of the props-object, as i think the first example is the one, most developers will think of first. and autofix will immediately change the dependency´s to "props", what is far from what is inteded.

**Comment by marceloadsj** [comment]
@bartlangelaan the functions aren't equivalent on your example, but they can be if we go for:

```javascript
const props = {
  onCanAddItems: () => {
    console.log(props.someProperty);
  },
  someProperty: 'test',
}
```

But, of course, eslint cannot know about it!

I think React team choose to be this way to avoid generating problems on those different scenarios, even knowing the downside of writing more boilerplate code to extract attrs from objects or so...

**Comment by yelvert** [comment]
That seems like a very contrived example that is not applicable in most cases. At the very least, there should be a option to specify allowed variable names, just like there is for `additionalHooks`. Something like:
```json
"react-hooks/exhaustive-deps": ["warn", {
  "objectDeps": "(props|foo|bar)"
}]
```

Or even better:
```typescript
useEffect(() => {
  wrapper.callback();
}, [wrapper.callback]); // eslint-disable-line react-hooks/exhaustive-deps(objectDeps: wrapper)
```
or
```typescript
useEffect(() => {
  wrapper.callback();
}, [wrapper.callback]); // eslint-disable-line react-hooks/exhaustive-deps(objectDeps: wrapper.callback)
```

**Comment by florianmartens** [comment]
This will probably trip people up for the next 100 years.

I'm on the side of @yelvert in favoring an config option. Guarding against a stale `this` is noble. But I'm having a hard time finding use-cases where a hook would want to try to access its wrapping objects. I'm sure they exist. But the anger of a stale `this` value seems infinitely smaller than the danger of producing infinite loops or unnecessary re-renders.
