### ISSUE TITLE
default structure of class/function

### ISSUE THREAD

**Issue by indraraj26** [facebook/react#15968]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I am getting function App() structure instead of class App extends React.Component { }. This is command i ran npx create-react-app react-poc. Is there any other parameter do we have to add in order to get class modules like structure.

structure of app.js
````
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
         I have edited
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

````
**What is the expected behavior?**
By default it should be class when we install.

**Question**
How to get the class structure instead of function App()

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 ````
 "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  },
````
````
D:\react\react-poc>npm -v
5.6.0
````

**Comment by dmytro-lymarenko** [comment]
Why do you need class structure instead of function? Personally, I forgot React classes in favor of React hooks ;)

**Comment by xHostx26** [comment]
i learnt angular that's why i am more familiar with class instead function.

**Comment by indraraj26** [comment]
i learnt angular that's why i am more familiar with class instead function

**Comment by dmytro-lymarenko** [comment]
I see. But, I strongly encourage you to start using Functional components with React hooks. Once you get how it works you will not go back to use classes.

**Comment by aweary** [comment]
Hey @indraraj26, we use the issue tracker for bug reports and feature requests for React itself. It looks like you're asking about create-react-app, which is a separate project. In the future you'll want to direct requests or bug reports for create-react-app to [this repo instead](https://github.com/facebook/create-react-app).

While we do encourage you to explore Hooks, you can just manually refactor the root `App` component to a class if you need it. Since many people don't use class components by default, I think that's likely the best solution for the project.

Thanks!

**Comment by indraraj26** [comment]
Hey @aweary , You could have moved this thread to create-react-app instead of closing, anyway i will manually refactor the root app component.

Thank you.
