### ISSUE TITLE
Lifecycle methods not get called when component updating

### ISSUE THREAD

**Issue by yangmingshan** [facebook/react#15996]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Some lifecycle methods are not get called when component updating.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/cool-proskuriakova-pz40f

**What is the expected behavior?**

Alert message after click the `Toggle` button in the first time.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react: 16.8.6
react-dom: 16.8.6
react-scripts: 3.0.1

**Comment by aweary** [comment]
@yangmingshan this is expected behavior because you're changing the `key` on the `Text` component

```jsx
<Text key={info.id} show={show} />
```

When `key` changes React will unmount and re-mount the component completely. So initially `info.id` is `undefined`. Then it's updated to `"1"` which causes it to unmount, so those lifeycles methods don't get called. On the next update the key is still `"1"` so React only updates the `Text` component and calls the lifecycle methods.
