### ISSUE TITLE
[Proposal] Return a Promise from ReactDOM.render()

### ISSUE THREAD

**Issue by simon-robertson** [facebook/react#16021]
**Do you want to request a *feature* or report a *bug*?**

A backward-compatible feature.

**What is the current behavior?**

The `ReactDOM.render()` function only accepts a callback, which is called whenever the component is rendered, and doesn't compliment asynchronous Promise-based programs as well as it could do.

**What is the expected behavior?**

The `ReactDOM.render()` function could return a Promise that resolves after the component has first been rendered.

```js
ReactDOM.render(<Component />, container).then( ... )
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

N/A

**Comment by threepointone** [comment]
ReactDOM.render renders synchronously on first render. This might change in the future though. 

However, I'd ask why you need to 'wait' for render to finish, andw hat it means? For example, it might not have finished fetching data, or in case of subscriptions, might never 'finish'. If you need a granular notification of when something specific 'happened', you could pass a callback to your `<Component/>` and trigger it from inside it. I'd question the need for this though. 

Closing since it's more of a usage issue.

**Comment by gsouf** [comment]
Make it a promise

```
new Promise(res => {
    ReactDOM.render(<Something/>, document.body, res);
})
```

**Comment by nerdess** [comment]
@gsouf when I make it a promise like in your example I get the error

_Methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate._
