### ISSUE TITLE
useContext unexpected behavior in immediate child component

### ISSUE THREAD

**Issue by HosseinAlipour** [facebook/react#16086]
as [hook API](https://reactjs.org/docs/hooks-reference.html#usecontext) states, The current context value is determined by the value prop of the nearest <MyContext.Provider> ***above the calling component in the tree.*** 

but before react new Hooks feature, we could use provider and consumer in the same component and the consumer always points to the nearest component, not nearest above the calling component.

this [sandbox ](https://codesandbox.io/s/gallant-elgamal-23r81) shows that only the useContext has unexpected behavior based on other methods of accessing context value.

I think this is by hook's limit, or isn't it?
so based on what premise useContext doesn't provide the value form the nearest provider? isn't it unexpected?

**Comment by aweary** [comment]
This is expected behavior, and you're right that it does appear to be inconsistent at first. As the Hooks API docs state `useContext` looks above the calling component so that means providers _inside_ the component aren't used. This isn't unique to `useContext` either, `contextType` also works the same. For example, if you have:

```jsx
class ClassComponent extends React.Component {
  render() {
    return (
      <div>
        <NewContext.Provider value="class provider value">
          from class {this.context}
        </NewContext.Provider>
      </div>
    )
  }
}
ClassComponent.contextType = NewContext
```

The `NewContext.Provider` inside `ClassComponent` isn't going to update the value of `this.context`.   This is the same behavior as `useContext` but it _feels_ less confusing because `this.context` is a a static value so it'd be weird if it was different depending on where you accessed it.

```jsx
const value = this.context;
return (
  <NewContext.Provider value="some value">
     {value} and {this.context} aren't the same!?
  </NewContext.Provider>
)
```

You should think of `useContext` as the same. It would be weird if moving the location of the `useContext` call site within a component affected its value.

```jsx
const value = useContext(NewContext);
return (
  <NewContext.Provider value="some value">
     {value} and {useContext(NewContext)} aren't the same!?
  </NewContext.Provider>
)
```

`Context.Consumer` is different because it's lazy. You pass a callback as a child and it lazily evaluates the current context value. `useContext` and `contextType` are eager so they evaluate the context _before_ the component itself is mounted, which means it won't be affected by any providers inside that component.
