### ISSUE TITLE
How does import work in React?

### ISSUE THREAD

**Issue by phakphumi** [facebook/react#16176]
I want to know the deep concept when I’m using import in React.

According to [this article](https://link.medium.com/acpKOqJcxY), it said that 

> In the node world anything start with [A-Za-z0-9@] is considered a node module

In case I want to use [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) to define alias for some path in my project. I may define it as “components” so I can call import in every file in my project like `import A from ‘components/A`.

As I understand react will run node’s resolver for the import path that start with `[A-Za-z0-9@]` if non-exist in node_modules then it will looking for the path in local project or the alias. Am I right?

My question is naming alias like this affects to the performance, doesn’t it?

If the answer for above question is yes. Can I ,naming alias path with the character that doesn’t start with the case, to improve the performance?

Thank you.

**Comment by artuross** [comment]
Hey, I'm not sure If I understood the question, but let's try anyway...

React is not responsible for handling imports. React simply takes components which are already defined (as far as React is aware).

If you have a bundler, for example webpack, it will try to resolve all paths during building and some plugins, such as the one you found may provide custom logic for handling imports. In the case of babel-plugin-module-resolver, you can create an alias to directory `components`. This would allow you to reference this directory, or files within, using shorter paths (`components/A` instead of `../../../components/A`).

As for performance - while technically the answer is yes, because you're adding more code that the bundler must execute, production code will not run any faster as the processed code will be exactly the same.

**Comment by phakphumi** [comment]
Thank you for your answer. @artuross

To clarify the last question, which alias should I name between “components” (may consider as a  node module) or “#components”, “~components” (may not consider as a node module following the article said)? and why?

**Comment by artuross** [comment]
It's up to you and there is no rule. For example, one project that I work on has an alias `app` which resolves to `src/app`. Some people use `@` at the beginning. Choose an alias that works for you. You can have more aliases than one.
