### ISSUE TITLE
<Element> backgroundImage url triggers re-render on all elements where <Img> src does not 

### ISSUE THREAD

**Issue by colemars** [facebook/react#16187]
Possible bug?

When dynamically rendering a list of `<div>` or `<img>` elements - each new addition re-renders the entire list ONLY if just background-image is specified. If `Img.src` is specified normal behavior occurs. 

Example: 
https://codesandbox.io/s/brave-mcnulty-0rrjz

Relevant comments and code are at Preview.js:55

**Comment by threepointone** [comment]
This is a lot of code to debug, could you simplify it down to something with redux and all the bits not relevant to this?

**Comment by colemars** [comment]
I don't have the time, sorry.

**Comment by Dergash** [comment]
Hello @colemars! I don't think it's bug.
You assign "style" property for your image like this:
```jsx
props.images.images.map((imageFile, index) => {
    let objectURL = URL.createObjectURL(imageFile);

    const bugStyles = {
      backgroundImage: `url(${objectURL})`,
      left: `${leftPosition}%`,
      top: `${topPosition}%`
    };
    
    <img style={{ ...style, ...bugStyles }} />
})
```
But URL.createObjectURL(imageFile) creates a different string every time.
The bugStyles object changes every time for every image, and when reconciliation happens React decides it's a different object and element should rerender, because the property have changed.

You probably should create url once, when the image is uploaded.

Here is an example where I moved your URL.createObjectURL(imageFile) from list render to image uploade method (PastImageInput.js): 
https://codesandbox.io/s/funny-http-8vrgv

**Comment by colemars** [comment]
Thank you so much! This is a great overview that helps me understand reconciliation better. And that visual is great - you've added to my trove of tricks to use when playing around with React. 

I'll close this now. Apologies for my misunderstanding!
