### ISSUE TITLE
custom hook with Promise.all causes duplicate network request

### ISSUE THREAD

**Issue by kang-chen** [facebook/react#16200]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

With custom hook with using Promise.all I'm noticing duplicate network requests, the issue occurs when I call the `setState` method of the hook. If I don't setState the call is made once.

The same hook written without Promise.all seems to work fine, ie one fetch request.

This could well be something with my code and happy to know if there's anything missing.

https://gist.github.com/kang-chen/fe9fed2ca1c95a782713f76886a81865

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/hook-test-ndj7s

Open the network tab and view requests going out to test API, there should be only three requests although there are six.

**What is the expected behavior?**

No duplicated network calls using Promise.all in conjunction with custom hook.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8.6

**Comment by otakustay** [comment]
Seems your `dependencies` are changed between renders, and you didn't keep a pending promise state so that you can put a extra condition like `isPending` in `useEffect`

Anyway the first thing we should look at is why `dependencies` are changed between renders, is it stable enough when invoking `useGetAllRequests`?

**Comment by kang-chen** [comment]
thanks, after removing the dependencies from arguments and just hardcoding the empty array `[]` for useEffect there's still the same behaviour, is that what you meant by dependencies? 

Also with the pending promise state, can you edit the relevant part of my gist to provide an example?

**Comment by universse** [comment]
Hello there. Hard-coding dependency array is not an idiomatic solution. In your case, useEffect should depend on fetchArr, which in turn depends on urls. And since urls is an array, it always change whenever App rerenders, causing the effect to re-run.

The solution is to useMemo to memoize urls and fetchArr, making sure their references are the same with each re-render.

Take a look at https://codesandbox.io/s/hook-test-julq8

**Comment by universse** [comment]
I also removed the check if (fetchedData === null) ... since it's not required and introduces unnecessary dependencies.

**Comment by kang-chen** [comment]
@universse awesome, thanks for that I've learnt a bit about hooks and useMemo! Closing issue now as we know it was code in my custom hook.
