### ISSUE TITLE
[Feature Request] useCallback and useMemo with a single argument should behave as if an empty array was given

### ISSUE THREAD

**Issue by goatfryed** [facebook/react#16237]
**This is a feature request with somewhat bc breaking behaviour**

Currently, useCallback and useMemo behave like useEffect, if a single argument is given. This means, they reevaluate on every render. While this makes a lot of sense for useEffect, i can't see use cases, where someone would want that with useCallback or useMemo, given that it's intended use case is to reduce the amount of times the given function is called or result is recreated.

While the 4 digits of unnecssary code are not that much - still unnecessary though -, i'm guessing i'm not the only one who would assume such a standard behaviour just to find out, it's not working.

What do you think?

**Comment by universse** [comment]
wouldn't it potentially confusing due to inconsistent behavior across different hooks?

**Comment by goatfryed** [comment]
I thought about it as well, but if useCallback and useMemo are consistent in regard to it, it should be fine, since useEffect serves a different purpose.
To me, personally, it's much more confusing that a memos default behaviour is to not memorize at all.

**Comment by babangsund** [comment]
I think the current explicit manner is more, well -  *explicit*.  
To your point though - if there are no dependencies, isn't it static?

The consistency of API outweighs this "clever" functionality imo.

**Comment by nattthebear** [comment]
`useCallback` / `useMemo` with `[]` deps is also a niche case.  If it doesn't depend on anything, hoist it out of the component function entirely, and just statically compute it once per app lifetime.  If it does depend on things but you still want `[]`, then you're in the weird situation of having a component that's sensitve to mount/unmount cycles and won't respond to certain things otherwise, which is fine for some use cases, but hardly typical.  Does such a case need a 4 character optimization?

**Comment by goatfryed** [comment]
Well, in my opinion, this has nothing to do with consistency, since it's only consistent with a function that servers an entirely different purpose.
Rather than being consistent, the current behaviour to me is entirely unintuitive. That's actually my bigger concern than the 4 character optimization.

I can see your point though.

**Comment by babangsund** [comment]
@goatfryed The linter knows what it is doing - trust it. 🙂   
The function provided by useState and useReducer are guaranteed static - yes.

**Comment by goatfryed** [comment]
@babangsund That was my assumption and i trust it.
But this also means, that there are use cases, where it depends on other things and still has an empty dependency list.
Know, can you tell me a single use case, where i'd want a memo value to recompute on every render?
If you've worked in the eco system for a long time, the current behaviour might be consistent in some regards, but it also means, you'll never program this case. If you're newer to the hook system, you'd rather not expect the current behaviour. Or is there a corner case i'm missing? 

Now, I see there are quite some concerns against this change. Do you agree, that we could extend the linter and raise a warning as @universse suggested?

**Comment by universse** [comment]
By confusing, i mean it can be the case for beginners. It may not be, but just something to take note.

Also, to clarify, the linter already gives warning when dep array is missing for useCallback & useMemo. What I suggest is that it auto-fixes instead of merely warns.

**Comment by gaearon** [comment]
It is intentional that the default is to be consistent, firing on every render. This ensures you handle updates from the beginning. This can sometimes you get into trouble, but then you learn alternative strategies and understand how the feature works.

The gamble here is that we'd rather you have an obvious bug (and learn how to fix it), rather than live for a long time with non-obvious bugs. This article explains more:

https://overreacted.io/writing-resilient-components/#dont-stop-the-data-flow-in-side-effects
