### ISSUE TITLE
React onChange event triggers the wrong props (when used with `htmlFor`)

### ISSUE THREAD

**Issue by ar-naseef** [facebook/react#16246]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Component triggers the wrong props on the `onChange` event.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
https://codesandbox.io/s/muddy-https-r6w7p
It behaves alright when the default input(file selector) is clicked. But when the div that refers to the input(with `htmlFor`) is clicked, it seems like triggering the old props.

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React v16.8.6

**Comment by ravich11** [comment]
This is not a bug, because you have 2 input elements with the same ID `myInput` when you click the upload label with `htmlFor` in parent, it invokes the upload input in the first child component. The parent upload input is never triggered. I tried using dynamic ID for each component and it's working fine. https://codesandbox.io/s/damp-butterfly-c0nt3
