### ISSUE TITLE
Make `key` available in `props`

### ISSUE THREAD

**Issue by mindplay-dk** [facebook/react#16272]
Why is the value of the `key`-attribute unavailable in `props`?

I'm experimenting with state management abstractions, and I wanted to make `key` required and use the value as the key to a state container - something along the lines of this:

```jsx
<Provider store={store} key="count">
    {count => <h1>Count: {count}</h1>}
</Provider>
```

This would be meaningful, because the `Provider` instance can't actually be reused if the key to the store changes, at least not without adding extra complexity.

Currently, my only recourse is to duplicate this value with a different name:

```jsx
<Provider store={store} key="count" storeKey="count">
    {count => <h1>Count: {count}</h1>}
</Provider>
```

This is rather inelegant and errorprone.

`key` is a prop, so I'd expect it to exist in `props`.

Why this seemingly arbitrary restriction?

**Comment by thoamsy** [comment]
you want read the `key` from React Element. 
```js
const Com = ({children}) => {
  let key = children.key; // it's your key
}
```

**Comment by mayankshubham** [comment]
Why key isn't passed as a prop is because its been used by react internally to optimize on re-renders. Now imagine a case where key was passed as a prop and you try to change the value of key and in the child components `componentDidUpdate `or the `useEffect `hook(depending on whether you use class or component based approach) you try to take and action only to realise that the component is not re-rendered but remounted would confuse you.

 And its safe to not confuse users with such behaviors by imposing a small restriction on not using a name as key.

Such restriction are very common across languages and platform as they may compilation easy. Think about the restriction of naming your variables as `var`, `const` etc.

**Comment by mindplay-dk** [comment]
> Why key isn't passed as a prop is because its been used by react internally to optimize on re-renders

Yes, but I'm interested in `key` precisely *because* it governs the life-cycle.

For my use-case, I *want* the component to get replaced if `key` changes, which is only possible by using `key` - I can't implement something similar using a custom property.

I guess I can use a function instead of a component then:

```jsx
const App = () => (
  <div>
    {store.use("count", count => (
      <h1>Count: {count}</h1>
    )}
  </div>
)
```

And `store.use()` would return the actual JSX component with the `key` and my custom duplicate `storeKey` consistently applied.

It's a bit lumpy though, and this restraint seems rather opinionated and arbitrary to me. 😐

**Comment by gaearon** [comment]
It was actually on the props a long time ago. We found that this leads to bugs because:

1. People supply a key in a list
2. Later their components start reading the key because they assume it’s always there and has a concrete meaning
3. Now you can’t change the key easily without auditing all its use below

Being able to safely change the key without downstream consequences is important. Bugs with keys can be very serious (for example, sending a message to a wrong person, or showing price for a wrong product), and we want to make it easy to correct a wrong key. Hence the change, which makes it opaque to code below.

Regarding the API you’re proposing, nothing prevents you from having two layers. Have an `id` prop, and two component layers. In the outer layer, forward it down both as an `id` prop and as a `key`. This keeps the user able to remount your component with their own `key` if necessary without interfering in whatever you use it for.

Hope this helps.
