### ISSUE TITLE
Problem with useContext hook

### ISSUE THREAD

**Issue by Ryukote** [facebook/react#16286]
useContext hook have a problem. If you for example create a context like this:

```javascript
import React, { createContext, useState } from 'react';

export const DummyContext = createContext();

export const DummyProvider = (props) => {
    const [state1, setState1] = useState('');
    const [state2, setState2] = useState('');
    const [state3, setState3] = useState('');

    return (
        <DummyContext.Provider
            value={[
                [state1, setState1],
                [state2, setState2],
                [state3, setState3]
            ]}
        >
            {props.children}
        </DummyContext.Provider
    )
}
```

Let's say I have also wrote something like this:

```javascript
function App() {
  return (
    <DummyProvider>
      <SomeComponent/>
    </DummyProvider>
  );
}
```

If I want to use that context inside SomeComponent, I will have to call those states and handlers in the exact order I have wrote inside DummyContext, because it seems React is looking for states and handlers by their index, instead of the name. If I don't use those states and handlers in the exact order, values will get mixed.

Other issue with that is that I can't call only handler for that state, but I also have to include that state even tho I might not use that state inside that component, but only that state handler. If I only include handler, it will give me error like 'handler is not a function', if we say that handler is the name of the actual handler.

Wouldn't it be better if it looks for those states by their name (since there can't be duplicate states in the context), so I would be able to include only those states I want from the context? Less code and it would be easier to maintain that code.

**Comment by universse** [comment]
How about doing something like this?

```javascript
<DummyContext.Provider
            value={{
                state1,
                setState1,
                state2,
                setState2,
                state3,
                setState3
            }}
        >
....
```

**Comment by audiolion** [comment]
This looks like a JavaScript issue, not a React one.

Your context is vanilla JS:

```js
const context = [
  [state1, setState1],
  [state2, setState2],
];
```

You can't destructure this by name, it is an array of arrays. If you want to access by key, use a map instead:

```js
const context = {
  state1: [state1, setState1],
  state2: [state2, setState2],
}
```

You might be confusing a JSX expression which is something wrapped in `{ }` with the syntax for a dictionary in JS. It can be clearer to take the inline value out like I am doing above and then pass it to the provider: `value={context}`

If you want to destructure an array tuple and ignore the first element, or only get the first element, this is again just regular old javascript:

```js
const [x] = [1, 2] // x = 1
const [, x] = [1, 2] // x = 2
```

It seems you are having issues due to some misunderstanding of JavaScript. React is very idiomatic, I would recommend sharpening up those skills to improve your React dev skills!

**Comment by threepointone** [comment]
Closing since this isn’t a bug/fr, but feel free to continue if you’d like.
