### ISSUE TITLE
Weird useState/useReducers behavior in seemingly synchronous code

### ISSUE THREAD

**Issue by Igor10k** [facebook/react#16290]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In console:
```
canceled1 false
canceled2 true
canceled3 true
```

https://codesandbox.io/s/youthful-hoover-xixne

**What is the expected behavior?**

In console
```
canceled1 false
canceled2 false
canceled3 false
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.8.6 and `0.0.0-db3ae32b8`
Chrome 76.0.3809.87
macOS 10.14.6

**Comment by Dergash** [comment]
Hello @Igor10k! I don't think it's a bug and I honestly think that code with setTimeout doesn't look  particularly synchronous to me 😸 

You trying to set 'canceled' flag in effect cleanup part (effect return statement), and your console.out lines are inside 100ms-setTimeout  callback.

You also have setState (setTest) inside 99ms-setTimeout in your effect.

Your effect fires, then 100ms-setTimeout started, then your 99ms-setTimeout started, then your  99ms-setTimeout fires it's callback and requests setTest, then 100ms-setTimeout fires it's callback and outputs 'canceled1 false' in console, then your 99ms-setTimeout fires process setTest - effect is depended on that Test, so effect should be run again and before that cleanup callback fires - 'canceled' is set to 'true' and there you get your 'canceled2 true' and 'canceled3 true'. 

The thing is that while you do request setTest before 100ms fired, actual state change and firing effect cleanup took more than 1ms and console.log 'canceled1' in 100ms-setTimeout was there earlier.

You can verify it by changing your 99ms-setTimeout to 90ms-setTimeout, your setTest and effect cleanup then will have time to fire and you get your expected behavior.

I think [useLayoutEffect](https://reactjs.org/docs/hooks-reference.html#uselayouteffect) also might give you your expected behavior at the cost of blocking visual updates

**Comment by Igor10k** [comment]
@Dergash 

>  * then 100ms-setTimeout fires its callback and outputs 'canceled1 false' in console
> * then your 99ms-setTimeout finish processing setTest - effect is depended on that Test, so effect should be run again and before that cleanup callback should be fired, so Test is changed and cleanup effect fires - 'canceled' is set to 'true'

not true. That's a synchronous code in the 100ms timeout callback so all the code in it will be executed in one tick, and that will happen before the 99ms timeout callback is fired.
The only possibility for the `canceled` to become `true` is for `setFetchingMore()` to initiate the effect cleanup somehow and I don't think that should happen in the middle of the synchronous code. Some kind of `setImmediate()` for that cleanup should be used to avoid that.

**Comment by Dergash** [comment]
My bad, totally missed setFetchingMore.

**Comment by Igor10k** [comment]
yeah, looks like it. And looks like there are two workarounds:

1. Use `ReactDOM.unstable_batchedUpdates` but even though I know it's used under the hood it still scares me with the `unstable_` prefix. I wonder why it's still considered unstable. I've asked about that in the issue you mentioned.
2. Use a reducer and dispatch the action at the very end of the callback. (that's actually what I did in my app when encountered the issue)
