### ISSUE TITLE
[ReactUpdateQueue] Why don't we stop processing higher priority update when we skip a low priority update?

### ISSUE THREAD

**Issue by ahungrynoob** [facebook/react#16301]
**Do you want to request a *feature* or report a *bug*?**
A question.
**What is the current behavior?**
The current behavior is described in [ReactUpdateQueue.js](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactUpdateQueue.js#L61)
```
// For example:
//
//   Given a base state of '', and the following queue of updates
//
//     A1 - B2 - C1 - D2
//
//   where the number indicates the priority, and the update is applied to the
//   previous state by appending a letter, React will process these updates as
//   two separate renders, one per distinct priority level:
//
//   First render, at priority 1:
//     Base state: ''
//     Updates: [A1, C1]
//     Result state: 'AC'
//
//   Second render, at priority 2:
//     Base state: 'A'            <-  The base state does not include C1,
//                                    because B2 was skipped.
//     Updates: [B2, C1, D2]      <-  C1 was rebased on top of B2
//     Result state: 'ABCD'
//
```

**What is the expected behavior?**
I think there is no need to process subsequent higher priority updates. It's a waste of cpu.

**Comment by acdlite** [comment]
The reason is so the terminal state is the same regardless of the priority:

![concurrent-viz-1](https://user-images.githubusercontent.com/3624098/62562437-013c8900-b836-11e9-9c64-7f89f75e9d4c.jpg)
![concurrent-viz-2](https://user-images.githubusercontent.com/3624098/62562438-013c8900-b836-11e9-8245-52f116e94be1.jpg)

https://twitter.com/acdlite/status/978412930973687808

Note that this only applies to concurrent mode, which has not yet been released. The current behavior is that all updates have the same priority.

Regarding your concern that it's a waste of CPU, the cost of rebasing updates is very cheap. Negligible, even. Far more costly is performing the render in the first place, which we would still do even in your proposal where we skip rebasing. But the whole point of doing two separate renders is so that the first one can render to the screen immediately without waiting for the second to finish. For example, an autocomplete component, where the input needs to update instantly even if the autocomplete lags behind a bit.

We'll have proper documentation for concurrent rendering before the release.
