### ISSUE TITLE
use-subscription readme

### ISSUE THREAD

**Issue by steida** [facebook/react#16350]
It's not obvious (or I am dumb) why classic `addEventListener` and 'removeEventListener' within useEffect without using useSubscription can be harmful in concurrent mode.

Maybe React should warn about addEventListener usage? What am I missing? Thank you.

**Comment by vkurchatkin** [comment]
What makes you think that `addEventListener` is somehow harmful?

**Comment by steida** [comment]
@vkurchatkin https://github.com/facebook/react/tree/master/packages/use-subscription#subscribing-to-event-dispatchers

**Comment by vkurchatkin** [comment]
This is just an example of how you can use `useSubscription` with `addEventListener`. It doesn't imply that you can't use `addEventListener` without it.

I think the idea is the following. Let's say you need to subscribe to some value using an event emitter:

```js
function Comp() {
   const [val, setVal] = React.useState(value.getCurrent());

   React.useEffect(() => {
       function update() {
          setVal(value.getCurrent())
       }

      value.addEventListener(update);

      return () => {
         value.removeEventListener(update);
     };
   }, []);
}
```

This is safe, but incorrect: the effect can be called much later after render, so you could be miss some updates.


```js
function Comp() {
   const [val, setVal] = React.useState(value.getCurrent());

   const update = React.useRef(function update() {
       setVal(value.getCurrent())
    }).current;

   value.addEventListener(update);

   React.useEffect(() => {
      return () => {
         value.removeEventListener(update);
     };
   }, []);
}
```

This seems to fix the problem, because we subscribe immediately after calling `getCurrent`. But this IS unsafe (and incorrect), since it is possible that the listener is not ever removed.

So this is what you have to do:

```js
function Comp() {
   const [val, setVal] = React.useState(value.getCurrent());

   React.useEffect(() => {
       function update() {
          setVal(value.getCurrent())
       }

      value.addEventListener(update);
      update(); // <--- the value might have changed, so we need to update just in case

      return () => {
         value.removeEventListener(update);
     };
   }, []);
}
```

And that's pretty much what `useSubscription` does. If you ignore the possibility that `getCurrentValue` or `subscribe` could change, it boils down to this:

```js
function useSubscription({
  getCurrentValue,
  subscribe,
}) {
  const [value, setValue] = useState(() => getCurrentValue());

  useEffect(
    () => {
      let didUnsubscribe = false;

      const checkForUpdates = () => {
        if (didUnsubscribe) {
          return;
        }

        setValue(getCurrentValue());
      };
      const unsubscribe = subscribe(checkForUpdates);

      checkForUpdates();

      return () => {
        didUnsubscribe = true;
        unsubscribe();
      };
    },
    [],
  );

  return value;
}
```

**Comment by steida** [comment]
That's how it should be explained in the readme. Thank you!
