### ISSUE TITLE
`act` should yield the value returned from the async function.

### ISSUE THREAD

**Issue by pfgray** [facebook/react#16366]
**Do you want to request a *feature* or report a *bug*?**
Feature

A couple of things have surprised me about the new asynchronous `act` API.

#### 1. Act doesn't return a promise.

Currently the `act` function returns an object with a `then` method that doesn't return a promise.

Recently, I tried to write something like:

```js
act(() => {
  return doSomethingAsynchronous()
})
.then(() => {
  // ...
})
.then(() => {
  // ...
})
```

The second `.then` call throws an error because the value that is returned from `act` isn't a full-fledged `Promise`, but rather just an object that contains a `.then` method that returns `undefined`. This is fine for simple `async`/`await` cases, but definitely caught me by surprise.

#### 2. Act discards the returned value.

Act also throws away the value returned from the async function callback, which makes it harder to use the values generated there. For example, if I wanted to use the value yielded by `doSomethingAsynchronous`, I would need to introduce a mutable variable:

```js
let returnedValue;
await act(async () => {
  returnedValue = await doSomethingAsynchronous()
})

// use returnedValue here
```

If `act` simply propogates the returned value from the asynnchronous callback, this will solve the confusing bits above, allowing for things like:

```
const returnedValue = await act(() => doSomethingAsynchronous())
```

**Comment by threepointone** [comment]
I thought about this, and I empathise that it's not as clean as it could be, but the role of act() is not to represent a value/future, and it doesn't compose like it either. (For example, you can't have 2 async act scopes in parallel) It's to establish a 'scope' within which things happen, so they can be batched and executed as one, and guarantee a side effect (flushing effects and updates) after it exits. In a language like javascript that doesn't have support for "zones", this api is the best we can do. I would not want to make this function return a value just to save some characters. 


The workaround though, is pretty simple - make a helper that does what you want -
```jsx
import TestUtils from 'react-dom/test-utils'

async function act(callback){
  let ret;
  await TestUtils.act(async () => {
    ret = await callback();
  });
  return ret;
}

// ...

const returnedValue = await act(() => doSomethingAsynchronous())
 ```

**Comment by pfgray** [comment]
Thanks for the workaround! I'm already employing something very simliar in my project.

TBF the intent was never to "save a few characters," but rather to decrease the surprising nature of the return value we get back from `act`. I assumed that I could chain `then` calls on the awaitable value I got back from `act`. When that failed, I needed to dive into `ReactTestRendererAct.js` to find out what was happening. So, this change was really just about (hopefully) saving the another person's time. Propagating the return value was less important, IMO, but is a convenient plus, and avoided us having to use our own Promise implementation.

If you think the current behavior is more intuitive, though, then I say we stick with that.

**Comment by threepointone** [comment]
I’m going to close this issue, but I assure you I’d like to make this a little better, and will keep thinking on it

**Comment by jonrimmer** [comment]
@threepointone Your suggestion produces use-before-assignment errors, because there is nothing to prove to the type system that `ret` has been assigned by the time `act()` resolves.

**Comment by threepointone** [comment]
🤷‍♂️ sounds like a problem with the rule’s heuristics, since it otherwise works. It’s a common js idiom.

**Comment by JoshuaKGoldberg** [comment]
@threepointone if you'll pardon my forwardness, I really think this issue should be opened and re-considered.

It's reasonable that some components start up asynchronous behavior via a `useEffect` or similar hook when they're first mounted, such as `react-hook-form`. See https://react-hook-form.com/advanced-usage > _ Resolving act warning during test_. 

> sounds like a problem with the rule’s heuristics, since it otherwise works. It’s a common js idiom.

TypeScript's use-before-assign checks by definition do not support this kind of idiom. There's no way in the type system to indicate that the callback passed to some other function is always run. 

In order to support this pattern in TypeScript and still have type information on the variable, you have to add an explicit type annotation (TypeScript won't infer a type from usage; the variable becomes an [evolving any](https://effectivetypescript.com/2020/03/09/evolving-any/)):

```ts
let result: FancyThing; // or: ReturnType<typeof getFancyThing>

await act(async () => {
  result = getFancyThing();
});
```

> make a helper that does what you want

I can also empathize that we're asking for something that can be written in user land in under 20 lines 😄 , but there are multiple `act`s in play, and per https://github.com/testing-library/dom-testing-library/issues/613, at least one is waiting on this issue to implement a returned value. https://github.com/testing-library/react-hooks-testing-library/issues/516 is an example of multiple `act`s.
