### ISSUE TITLE
DevTools: react-devtools-tutorial.now.sh > editing-props-and-state have a bad state

### ISSUE THREAD

**Issue by asimqt** [facebook/react#16419]
I don't know who's making the bug, so reporting here. I'll move to correct repo if someone helps me debug it.
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Please watch below screencast:
https://drive.google.com/file/d/1KMP44qsZ4y3MwrLLDdnOzPZ8z5mMElFP/view

1. Goto https://react-devtools-tutorial.now.sh/editing-props-and-state
2. Change the last ListItem prop to isComplete from `false` to `true`.
3. Click the checkbox in the view to change the state again from `true` to `false`.
**What is the expected behavior?**
It should just change the state of that ListItem. Instead, it's adding 3 more in the list with duplicate keys.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Latest React.
Mac, Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by bvaughn** [comment]
Interesting! 😁

This isn't really a bug in DevTools so much as a reflection of how I'm managing TODO state in this app.

Editing the prop in DevTools creates a new item `Object`. If you later toggle the "completed" state, the `ListItem` passes the (new) object to the parent, which [splices it out](https://github.com/bvaughn/react-devtools-tutorial/blob/b7b16b6ca1e12bd6da604aa43356509e9225e3a4/public/example-todo-list-app.js#L16-L31) but because of our previous edit- this actually ends up adding a new version (because they don't match).

I can update the demo to compare by ID rather than `indexOf` to make this less confusing. :)

**Comment by bvaughn** [comment]
Fixed with https://github.com/bvaughn/react-devtools-tutorial/commit/2a861f18c2f58d00e427cd673850fec20b7837f8

Tutorial site updated!
