### ISSUE TITLE
New React DevTools can't access immutable.js objects?

### ISSUE THREAD

**Issue by fd-rey** [facebook/react#16424]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the state or props are formed by Immutable.js objects, react devtools cannot expand it nor copy to temporal variable anymore.
![Screenshot from 2019-08-16 16-18-09](https://user-images.githubusercontent.com/28344917/63174215-c90d2580-c041-11e9-847c-7bbd153399f9.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/withered-cherry-h3dfh

**What is the expected behavior?**
Be able to inspect the value of the immutable object or at least, copy it into a temporal variable.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.8.6
Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by bvaughn** [comment]
Note we should also improve display for ES objets like `Map` and `Set` as part of this cleanup also.

**Comment by bvaughn** [comment]
Fixed: https://github.com/bvaughn/react-devtools-experimental/commit/ce65df7092ed69b45aa5787b708c1516b2c07427

Will release sometime soon (probably this afternoon). Want to test a bit more and my battery is low atm.

**Comment by 0xdevalias** [comment]
Redux DevTools had a [similar sort of thing ages back](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.1), and as part of that we had to thread in `serialize: { immutable: Immutable }` when we were creating the store.

But the outcome of that is we got a nicer display in Redux DevTools:
![image](https://user-images.githubusercontent.com/753891/63245582-e6412e80-c2a3-11e9-9926-13ab918113ca.png)

While it is possible to click through all of the fields in an `Immutable.Map` since these changes landed, it's still definitely not as nice of a viewing experience as Redux DevTools gets:
![image](https://user-images.githubusercontent.com/753891/63245639-007b0c80-c2a4-11e9-85a0-1f6bee723ff1.png)

Is there any way we could get a similar experience? (either natively, or by mapping some config like Redux DevTools exposed)
