### ISSUE TITLE
React DevTools: styling overrides global styles

### ISSUE THREAD

**Issue by CompuIves** [facebook/react#16456]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
This is a very specific case - there are some styles leaking from react devtools, if you use it in your own application directly. Specifically these lines: https://github.com/facebook/react/blob/devtools-v4-merge/packages/react-devtools-shared/src/devtools/views/root.css#L174-L178.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

It's funny, I can give a *real* CodeSandbox editor now! You can see the styling on the editor elements here: https://codesandbox.io/s/new.

**What is the expected behavior?**

No leaking styles. Ideally the `* {` would be prefixed by an id or classname specific for the devtools. I think this should be possible with the styling used by the devtools. I can open a PR to fix this if everyone agrees on this fix.

cc @bvaughn

**Comment by bvaughn** [comment]
Ah, interesting. Sorry about that!

> No leaking styles. Ideally the * { would be prefixed by an id or classname specific for the devtools. I think this should be possible with the styling used by the devtools.

I think think this might be trickier than that. I don't think that scoping to a style would effectively override the box sizing of element types _nested within_ DevTools, which is pretty important for layout in some cases.

A PR would be welcome though! :smile:

**Comment by GasimGasimzada** [comment]
I tried to create a simple sample to show if using class name and wildcard selector together works: https://codepen.io/gasim/pen/mdyqEdd. 

Because wildcard is the last item to be applied within a style, I think nesting the styles within `.DevTools + *` is going to work (I will test it out tomorrow by building dev tools from the source). The only issue is if an element above the above DevTools component also has a similar selector (btw this is how CodeSandbox overrides React DevTools wildcard selector styles) :

```jsx
<div className="some-container">
  <div className="DevTools">...</div>
</div>
```

```css
.DevTools {
  box-sizing: border-box;
}

.some-container * {
  box-sizing: content-box;
}
```

Order matters here. If some container's CSS is loaded before .DevTools CSS, everything will be fine. Otherwise, the layout is going to break. However, without scoping the wildcard with a class name will fail anyways, regardless of the load order of selectors.

So, at the very least, scoping the wildcard selector with a class name is going to help prevent bleeding of elements. It is not a perfect solution but it is safer than using open wildcard selector. Here is an output of DevTools in CodeSandbox by playing with CSS in Browser's DevTools:

```css
* {
 // React Dev Tools wildcard styles
 color: red;
}

// added it through the inspector
.DevTools * {
  color: yellow;
}
```

![Screen Shot 2020-01-03 at 2 06 14 AM](https://user-images.githubusercontent.com/807231/71696219-d6973200-2dcd-11ea-8922-6c078fada18e.png)

![Screen Shot 2020-01-03 at 2 06 14 AM](https://user-images.githubusercontent.com/807231/71696534-b320b700-2dce-11ea-9cf8-3e316f666092.png)

> I don't think that scoping to a style would effectively override the box sizing of element types nested within DevTools

What do you mean by "elements types nested within DevTools"? Is there something that I am missing here? If it is okay, can I work on this and test it more thoroughly?

**Comment by bvaughn** [comment]
Hm! I don't remember what I meant by that comment I wrote a few months ago. Sorry :smile:

Hm... I think this general approach would be okay:
```cs
.DevTools  * {
  box-sizing: content-box;
}
```
This type of CSS rule is kind of slow though so it kind of sucks to have to use it for this.

We'd also need to move the `box-sizing` style from `root.css` into `DevTools.css` so the `DevTools` selector would work right with the CSS modules generated class names.

**Comment by GasimGasimzada** [comment]
I created a PR where I added the `.DevTools, .DevTools *` selectors to set DevTools global properties.

**Comment by bvaughn** [comment]
Oops I think PR #17775 addressed this and I just forgot to close the issue.
