### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by anujsinghwd** [facebook/react#16454]
- Already tried with `npm cache clean`
- Removing `node_modules`
- try again installing `npm i`

![Screenshot from 2019-08-19 16-43-12](https://user-images.githubusercontent.com/24680004/63261418-10452180-c2a1-11e9-9d4f-fc9585d9097a.png)

**Comment by bvaughn** [comment]
Looks like this might be related to create-react-app? If so, I suggest filing this issue in that issue:
https://github.com/facebook/create-react-app

I also suggest providing the following with your report:
* Copy the full text (rather than an image) of the command you're running and the error.
* Specify which version of create-react-app you're using
* If possible, share a repro (like the project that triggers this error)

You might also want to give the things listed here a try:
https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle
