### ISSUE TITLE
Add ability to inject "virtual" HTML attributes to React.DOM

### ISSUE THREAD

**Issue by percyhanna** [facebook/react#1648]
Add the ability to define virtual attributes for HTML elements in `React.DOM`. This would allow semantic attributes to be declared that would be applied to modify some other attributes on the element. They could be declared in such a way:

```javascript
/**
 * The callback would be given access to the attribute's value,
 * and allow it to modify the other attributes of the element.
 */
function hiddenAttribute (value, attributes) {
  if (value) {
    attributes.style || (attributes.style = {});
    attributes.style.display = 'none';
  }
}

React.declareAttribute('hidden', hiddenAttribute);
```

Using it in JSX:

```javascript
/**
 * @jsx React.DOM
 * @jsxns {"Core":"Core","Common":"Common"}
 */

var MyComponent = React.createClass({
  render: function () {
    return <div hidden={true}>...</div>;
  }
});
```

Outputs:

```html
<div style="display: none;">...</div>
```

This would only be for `React.DOM` elements, not custom components. However, if one were to use `transferPropsTo` on a `React.DOM` element, then it would inherit the hidden attribute.

While writing this up, I haven't been able to think of any other useful attributes, so perhaps it's not as useful if there's only the single use case.

If there's buy-in for a concept like this, I'd be happy to attempt an implementation of it. Just thought I'd propose to see if it would be beneficial to anyone else for a different kind of attribute.

**Comment by alexbartlow** [comment]
Phantom bump, but I've been trying to do a lot of SVG work with react, and there are a lot of issues like "Please support this SVG attribute." This would be great in being able to define those without having to fork and change React itself. Let me know how I can help make it a reality.

**Comment by gaearon** [comment]
>Phantom bump, but I've been trying to do a lot of SVG work with react, and there are a lot of issues like "Please support this SVG attribute."

This has mostly been solved in v15 RC2. We should support all of the spec implemented by browsers now. Please give it a try.

>This would allow semantic attributes to be declared that would be applied to modify some other attributes on the element.

It sounds like you really want a custom `<Div>` (or `<View>`) component that acts this way, rather than override a native component. This doesn’t require changes in the core and lets you deviate as much as you like, and potentially change the tag you render to later. Because this use case is covered by React well, I don’t think it’s worth adding something as invasive as the original suggestion.

>It would be nice to be able to wrap attributes in general though to do things like autoprefixing.

Yeah, but even in this case it’s best that we take care of this, rather than let the user override arbitrary attributes in arbitrary ways. So autoprefixing could be a part of an integrated style solution, but I don’t see the use case for this particular proposal, so I’m inclined to close.

Please let me know if I’m wrong and we should reopen this. Thanks!
