### ISSUE TITLE
DevTools: Firefox extension fails to recognize React on sites with strict CSP

### ISSUE THREAD

**Issue by tstirrat15** [facebook/react#16514]
When I run react devtools on Chrome on https://www.getmyboat.com, it works just fine, but when I go to the same page with react devtools on Firefox, the icon is greyed out and it says the page doesn't appear to be using React.

The site uses a strict CSP policy - i.e. no unsafe-inline or unsafe-eval - so I'm wondering if it's something where Firefox treats extension code as injected code, where Chrome doesn't.

Is this a known issue? I'm fine if it's a wontfix on account of some behavior of Firefox, but I'd like to know for sure that that's the case.

EDIT: If it is a wontfix, I'll add something to the devtools docs to that effect.

**Comment by bvaughn** [comment]
Can confirm that DevTools in Firefox doesn't seem to connect to the example site you linked. DevTools in Chrome seems okay though.

DevTools does use `devtools.inspectedWindow.eval()` in a few places.

Might be worth reaching out to Firefox and seeing if this is expected behavior or a bug? and if the former, if there's any suggested workaround.

**Comment by tstirrat15** [comment]
Looks like it's a bug, and it looks like there isn't a direct workaround: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027#c48

Is there a good place for me to document this?
