### ISSUE TITLE
Bring back the ability to show props in the tree

### ISSUE THREAD

**Issue by wearhere** [facebook/react#16518]
**Do you want to request a *feature* or report a *bug*?**

Feature. I would like the ability to see props in the component tree, like in React DevTools version 3, not just in the sidebar.

**What is the current behavior?**

As of React DevTools 4.0.5, the component tree does not show a component's props:

![image](https://user-images.githubusercontent.com/110000/63395824-d98f0a00-c379-11e9-94a5-7d7ada53238f.png)

**What is the expected behavior?**

I would like the ability to toggle an interface more similar to React 3.6.0, where the props were shown in the tree. Please excuse the annotations on the following photo, I'm reusing it from https://github.com/facebook/react-devtools/issues/1361.

![image](https://user-images.githubusercontent.com/110000/63395853-f4fa1500-c379-11e9-8f84-580bf2803f5b.png)

--------------

As described in https://github.com/facebook/react-devtools/issues/1361, the problem with showing props in the sidebar, but not in the tree, is that it's common for me to scroll upward through the tree to try to find where an event handler is registered. If I have to click a component to get it to show a function prop like `onSelectValue`, that makes my search for the handler more difficult.

Note that the previous implementation showing props in the tree appeared to be broken in part, as described by https://github.com/facebook/react-devtools/issues/1361.

**Comment by keymastervn** [comment]
Upvote for this, now for expanding `nested props attributes` I have no way other than `$r` in the console or reading a loggerMiddleware.

![image](https://user-images.githubusercontent.com/5253209/63485753-d0fc1800-c4ce-11e9-9193-7f7f3d00e034.png)

**Comment by zinoviev** [comment]
@bvaughn If you consider this feature is viable, I will be happy try to implement

**Comment by bvaughn** [comment]
Removing inline props enabled significant performance improvements because it let us dramatically reduce the amount of messages we sent through our "bridge", which was previously a bottleneck. [You can read more about that here.](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md) It also enabled us to use a windowing library (`react-window`) to more efficiently render the Components tree content, something that would have been possible (but more difficult) if we had multi-line wrapping due to props.

It also enabled a UX improvement by removing the need to horizontally scroll.

I feel pretty strongly that this is, at least, **the right default** for most users and most applications.

"So why not make it a configurable option?"

I don't think it's feasible to add inline props back without a **great deal of effort**, because of how the tree serialization works, and because of the horizontal compression UX. If it was a simple thing, I wouldn't be stubborn about this- but I think it would require a lot of code. Even if you were willing to write that code initially, it would then require someone to maintain all of that code.

Obviously, please feel free to work on this if you are interested, but I want to give context about why it is the way it is, and my concerns about merging it (even assuming someone wanted to spend the time to implement it).

**Comment by zinoviev** [comment]
@bvaughn Understood

**Comment by wearhere** [comment]
@bvaughn thanks for explaining how the current behavior improves performance and UX. I agree, seems like the right default.

Curious—how are you able to totally avoid the need for line wrapping and/or horizontal scrolling with a sufficiently nested tree and/or components with sufficiently long names? Seems like at some point even the component names alone will edge off the right side of the screen.

I'm also curious to hear how you think we might address the use cases that inline props would solve. From the PR description, plus a few more:

* identifying at which level of the tree an event handler is registered
* distinguishing between list items
* comparing style overrides between a parent and its child, without having to toggle to the Elements panel

Perhaps it would be sufficient to add a control that retrieved a _snapshot_ of the inline props for the current tree? The difference between this and what I originally proposed is that it would not _keep_ the inline props visible and continually updated, rather, you would click this to toggle between the live-updated tree and a static snapshot.

I think this would address the use cases above assuming that the props you wanted to inspect were not changing rapidly. It would also be compatible with the new bridge design where the frontend requests elements' props only on-demand.

**Comment by bvaughn** [comment]
> Curious—how are you able to totally avoid the need for line wrapping and/or horizontal scrolling with a sufficiently nested tree and/or components with sufficiently long names? Seems like at some point even the component names alone will edge off the right side of the screen.

DevTools compresses horizontal indentation so that all names fit without scrolling, but if a name is so long that it can't fit on the screen by itself, it will overflow and be truncated. (This seems very unlikely though.)

> identifying at which level of the tree an event handler is registered

Select the element and look at its props.

> distinguishing between list items

Use the `key` attribute, which is visible.

> comparing style overrides between a parent and its child, without having to toggle to the Elements panel

Select the element and look at its props.

> Perhaps it would be sufficient to add a control that retrieved a snapshot of the inline props for the current tree? The difference between this and what I originally proposed is that it would not keep the inline props visible and continually updated, rather, you would click this to toggle between the live-updated tree and a static snapshot.

This does not seem significantly simpler to implement or maintain, to me.

**Comment by wearhere** [comment]
Thanks for the response @bvaughn. As regards your `key` suggestion, the value of the key may not be human-readable. Consider a list of users, where the `key` might be the user ID, something like a hexadecimal string, where you would want to be able to distinguish items based on something like the user's name.

In general, I don't think that selecting the element and looking at its props is equivalent to being able to see the props in the tree, because clicking on each element individually is much slower than being able to take in the tree at a glance, and you can't have compare two sets of props at the same time.

I venture that many people agree with me based on the thumbs-up count on this issue so far! I hope for further exploration in this area, that balances performance with UX.

**Comment by bvaughn** [comment]
You asked how I would approach the use cases. I agree that it would require an additional click. That is the negative trade off to the positives mentioned above.

I'm sure there are people that agree with you on inline props. At the same time, DevTools has two million active users and so far, only a small number have voiced concerns about the inline props change. (Anecdotally) several people have also expressed a positive reaction to the more compact tree and lack of horizontal scrolling.

We'll leave this issue open for more discussion. (Hopefully it won't attract many "+1" comments 😂).
