### ISSUE TITLE
Have useDebugValue return the value it's passed

### ISSUE THREAD

**Issue by TedDriggs** [facebook/react#16558]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** Currently, `useDebugValue` returns nothing. This means the debug value must be extracted to a local variable if it is also to be returned or passed to another function.

**What is the desired behavior?** Change the function to return its first argument, instead of nothing.

```typescript
function useDebugValue<T>(value: T, format?: (value: T) => any): T;
```

This will make it really lightweight for library hooks to provide good debugging experiences.

It's worth noting that the `dbg!` macro in Rust [does the same thing](https://doc.rust-lang.org/std/macro.dbg.html).

**Comment by threepointone** [comment]
The usage is to give a readable label to a hook inside devtools, not as a composition primitive. (For example, I'm not sure it would work always (or even ever?) if it's in a deeply nested function, and would be confusing when the composition changes. 

I'm closing this because I don't think we'll do this, but I appreciate the request. Using a regular shared variable would be our recommendation.
