### ISSUE TITLE
Minified React error #188

### ISSUE THREAD

**Issue by Weipengzhou** [facebook/react#16570]
I have an occasional problem today.
Invariant Violation: Minified React error #188; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
My version of react is 16.2.0, So I want to know if this problem exists in this version.

**Comment by Weipengzhou** [comment]
but I can't upgrade my version for some reason.

**Comment by threepointone** [comment]
The error message at the link says what the issue is “Unable to find node on an unmounted component.”. This usually means some code is, for example, trying to call findDOMNode on a component that’s already been unmounted. 

This message is what you would see in a production environment; if you load the code in development mode it might give you more details. 

This isn’t a React bug, it indicates an error with your product code.

**Comment by Weipengzhou** [comment]
thanks

**Comment by Sasuke0929** [comment]
:)
