### ISSUE TITLE
Developer Tools for idiomatic JavaScript

### ISSUE THREAD

**Issue by i5ar** [facebook/react#16581]
**Do you want to request a *feature* or report a *bug*?**

React Developer Tools ***feature*** request.

**What is the current behavior?**

Consider the following class-based component:

```js
class App extends React.Component {
 render() {
    return e("div", {}, "...");
  }
}
```

Consider the equivalent functional component:
```js
function renderApp() {
  return e("div", {}, "...");
}
```

Consider is common practice name functions with a verb followed by a noun (`doSomething()`).
Consider, most of the time, I'm using React without JSX so I'm not forced to capitalize functional components (e.g. `renderApp()` instead of `RenderApp()`).

Currently, the [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) shows the following tree:

```txt
renderApp
  Context.Provider
    renderList
      renderItem
```

It would be nice if instead, it could hide the lowercase portion `render`.

**What is the expected behavior?**

The tree should look as follows:

```txt
App
  Context.Provider
    List
      Item
```

I propose to strip away `render` from the component name.

Why `render`?

In class-based components, we use the `render()` method so it makes sense to call a functional component `renderComponent()`.

Thank you.

**Comment by gaearon** [comment]
Components aren’t just functions that we encourage calling manually. For example you still want to do `e(List)` rather than `List()`. Otherwise many React features (for example context) won’t work correctly.

This is why even if you don’t use JSX, we still encourage you to use the Capital naming scheme. It helps set components apart. It’s also used by other tools than JSX (for example, the Hooks lint rule).

Using a verb makes it seem like you’re supposed to call those functions directly. As I mentioned it doesn’t quite work and can be confusing. 

You can ignore this convention if you insist so — but we don’t plan to build special affordances for that.

**Comment by i5ar** [comment]
> Using a verb makes it seem like you’re supposed to call those functions directly.

Not always. I think it's a common pattern to pass functions as arguments and let they `doSomething` internally.

Thank you anyway.
