### ISSUE TITLE
Error: "Cannot modify filter preferences while profiling"

### ISSUE THREAD

**Issue by Sargis0101** [facebook/react#16616]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.6-a39d9c3

Call stack: at n.set (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:34098)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:261228
    at Fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:72851)
    at Vi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:74577)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:93355
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)
    at kt (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25093)
    at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:91165)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:79859)
    at M (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:2839)

Component stack: in Ma
    in div
    in div
    in div
    in Ga
    in Xa
    in div
    in lo
    in ir
    in Ir
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Wa
    in ce
    in be
    in So
    in Vl

**Comment by threepointone** [comment]
Please explain what you were doing when the bug occurred, or we cannot investigate this any further

**Comment by bvaughn** [comment]
Closing until more info is provided.

**Comment by bvaughn** [comment]
@Sargis0101  As Sunil mentions, this issue isn't something we can hep with unless you tell us a little more about what you were doing when you saw the error.

**Comment by bvaughn** [comment]
I have no idea how to repro this. The settings button is disabled when you start profiling, so you should be unable to open it to even try to modify filter preferences.

If you open it first, then start recording, the settings dialog is automatically dismissed.

I think the only way I can think of that this could happen would be if you (1) opened settings and changed filter preferences (2) tabbed to the start profiling button in the background (without clicking, as that would dismiss the dialog) (3) start profiling with the keyboard. That isn't really a case I care about supporting since it seems so unlikely to happen.

I'm going to close this issue for now. I'll be happy to re-open it if @Sargis0101 can fill in some missing details though.
