### ISSUE TITLE
add a "always pure" config for react components 

### ISSUE THREAD

**Issue by MHA15** [facebook/react#16624]
**Do you want to request a *feature* or report a *bug*?**
request a *feature* 

**What is the current behavior?**
as default all the components are behave as impure-component

**What is the expected behavior?**
I want react to give a config and then I can tell it I'm always write my components as pure components and then I didn't need `React.memo` before all my components and as you know `React.memo` will only handle props not state (hooks). 

I don't know why default behavior is impure component I had never use them it's so ugly in my mind

**Comment by bvaughn** [comment]
Hi 👋 What you're describing would be a large change. This sort of thing is better requested as an RFC:
https://github.com/reactjs/rfcs/

Here is a related RFC:
https://github.com/reactjs/rfcs/pull/108

And here is a related comment from Sebastian that you might be interested in:
https://github.com/reactjs/rfcs/pull/108#issuecomment-468888951

I'm going to close this issue since this sort of thing belongs in the RFC repo 😄
