### ISSUE TITLE
DevTools don't show components rendered by custom renderers

### ISSUE THREAD

**Issue by RodrigoHamuy** [facebook/react#16666]
**Steps to reproduce**

1. Go to https://bispt.csb.app/ (source code is in https://codesandbox.io/s/react-pixi-example-bispt )
2. Open React Dev Tools and look at the Components tree.

**Expected behaviour**

The Components tree structure should be like this:

```
- App
  - MyStage
    - Stage
       - CustomComponent
          - Sprite
```

**Current behaviour**

The Components tree structure is skipping the components that use custom renderers (**CustomComponent** and **Sprite**), showing only the following:

```
- App
  - MyStage
    - Stage
```

Tested on Chrome (Mac).

**Comment by threepointone** [comment]
You can bring some of it back by removing the filter in the settings
Before:
![image](https://user-images.githubusercontent.com/18808/64328380-3ff46900-cfc5-11e9-9f42-a9f777c28404.png)
![image](https://user-images.githubusercontent.com/18808/64328643-b8f3c080-cfc5-11e9-98ec-317cda89e2cb.png)

After:
![image](https://user-images.githubusercontent.com/18808/64328401-484ca400-cfc5-11e9-862d-6f7f6ad69a93.png)
![image](https://user-images.githubusercontent.com/18808/64328622-af6a5880-cfc5-11e9-9e13-421f97b27d95.png)
![image](https://user-images.githubusercontent.com/18808/64328654-c27d2880-cfc5-11e9-9f32-17e8efecd9b8.png)


That said, it's odd that devtools isn't rendering the child components as expected from your example (Sprite etc). I'll leave this open for @bvaughn's comment.

**Comment by bvaughn** [comment]
Right, this isn't a filtering thing. Displaying nested/interleaved renderers within a single tree has never been supported by DevTools (to my knowledge). Version 3 also terminates at the `Stage`/canvas boundary:

<img width="569" alt="Screen Shot 2019-09-05 at 7 43 56 AM" src="https://user-images.githubusercontent.com/29597/64352463-f00ba700-cfb0-11e9-8030-0a189593033f.png">

**Comment by bvaughn** [comment]
`@inlet/react-pixi` also reports an unexpected version number (1.1.0) to DevTools rather than the  `react-reconciler` version that it's based on. This would likely cause problems for the backend even if it did get connected, since version ranges are used to determine which work tag constants to use:

https://github.com/facebook/react/blob/9ce8711d5a7c84e71587c75d2935966023ee6dbb/packages/react-devtools-shared/src/backend/renderer.js#L211-L292

**Comment by RodrigoHamuy** [comment]
> Right, this isn't a filtering thing. Displaying nested/interleaved renderers within a single tree has never been supported by DevTools (to my knowledge). Version 3 also terminates at the `Stage`/canvas boundary:
> 
> <img alt="Screen Shot 2019-09-05 at 7 43 56 AM" width="569" src="https://user-images.githubusercontent.com/29597/64352463-f00ba700-cfb0-11e9-8030-0a189593033f.png">

Hey, thanks for taking a look. 

I was able to see custom rendered components when using the previous version of the React Dev Tools. Do you know how can I downgrade in the meantime? 

Thanks,

**Comment by RodrigoHamuy** [comment]
Funny thing, it kinda works with the old dev tools (v3) if you save the Pixi app in a state?

Codesandbox: https://xk3d2.csb.app/
Codesandbox source: https://codesandbox.io/s/react-pixi-with-ref-example-xk3d2

![image](https://user-images.githubusercontent.com/2405611/64691019-a8da5600-d489-11e9-9f18-2aa3e919a33f.png)

This is the key difference in the code:

```
class MyStage extends Component {
  render() {
    return (
      <Stage ref={this.getStateRef} options={OPTIONS}>
        <CustomComponent />
      </Stage>
    );
  }
  getStateRef = (ref: any) => {
    this.setState({ app: ref.app });
  };
}
```

So when you save the Application as a state, DevTools v3 will show the inner components :O

Tested using DevTools v3 on Chrome:

Clone https://github.com/facebook/react-devtools
```
git checkout v3
yarn install
yarn build:extension
yarn run test:chrome
```

**Comment by bvaughn** [comment]
It "works" the same way in v4:
![Screen Shot 2019-09-11 at 8 35 57 AM](https://user-images.githubusercontent.com/29597/64711901-352b4f80-d46f-11e9-9322-c2352822ea26.png)

**Comment by RodrigoHamuy** [comment]
> Right, this isn't a filtering thing. Displaying nested/interleaved renderers within a single tree has never been supported by DevTools (to my knowledge).

@bvaughn, any intentions to get this to work with custom renderers? Or what will it require? This will be quite useful for custom renderers like pixi-react, threejs-react, or any other canvas renderer.

**Comment by bvaughn** [comment]
If you'd like to pick this issue up and work on it, PRs would be welcome!

**Comment by RodrigoHamuy** [comment]
@bvaughn , thanks. Do we have what are the right steps to start developing for React DevTools?

Checking the source code for v4, there are lots of folders (react-devtools, react-devtools-core, react-devtools-shared), I tried to install and run some scripts on each one (node v10.16.0) but at the moment I just get different errors.

**Comment by gaearon** [comment]
>@inlet/react-pixi also reports an unexpected version number (1.1.0) to DevTools rather than the react-reconciler version that it's based on

The reconciler version wouldn’t help either, would it? The version checked by DevTools is React 16.x but reconciler is 0.x. You’d have to find ReactDOM release that was the same reconciler version as you’re using, and pass that.

**Comment by bvaughn** [comment]
Good call, Dan. I misspoke.

To clarify for @RodrigoHamuy: DevTools supports a range of React versions. To decide if it's dealing with a legacy renderer or a newer, reconciler based renderer (which it is in your case) it checks for the presence of `findFiberByHostInstance `:
https://github.com/facebook/react/blob/f818af9b03700f681bad0de6041e404cd681319d/packages/react-devtools-shared/src/backend/index.js#L52-L53

`@inlet/react-pixi` would pass this check since it's [injecting with the same methods](https://github.com/inlet/react-pixi/blob/7990bf96048b7206e29a982626930ed59e027a34/src/render/index.js#L42-L49) as React DOM and React Native. However it would "fail" the next check, where DevTools tries to determine which reconciler version it's based on:
https://github.com/facebook/react/blob/f818af9b03700f681bad0de6041e404cd681319d/packages/react-devtools-shared/src/backend/renderer.js#L211-L214

It's kind of hacky, but I think that (for now) `@inlet/react-pixi` would need to specify a version number that aligned with React DOM (like Dan mentioned). Maybe longer term we could expand the injection API to include a new field (reconciler version?) that DevTools could use instead of renderer version>

**Comment by RodrigoHamuy** [comment]
@bvaughn @gaearon thanks for your help. That seems to work. Already sent a PR for react-pixi: https://github.com/inlet/react-pixi/pull/142
