### ISSUE TITLE
Docs nav is too noisy

### ISSUE THREAD

**Issue by petehunt** [facebook/react#1669]
There's a lot of stuff in our left nav of the docs. It would be great if someone could clean this up and make it a little easier to digest.

**Comment by AnSavvides** [comment]
Is this still an issue?

If so, I'd be happy to discuss how we could go about this in order to try and tackle it - easy to digest docs are key to getting people up and running & avoiding them thinking it's more complex than it actually is.

**Comment by syranide** [comment]
@AnSavvides If you ask me the doc is really confusing and cluttered :)

**Comment by syranide** [comment]
I remember there was a planned revamp being worked on though... not sure what happened to that.

**Comment by AnSavvides** [comment]
Ah I see - if there is a revamp in the works then that's great :)

Yeah, I think the hierarchy and structure needs a bit of love. The content itself is good, but knowing how to get to the right place for what you are after can be tricky, which usually means resolving to Google searches.

**Comment by joecritch** [comment]
Resurfacing this.

Here's a WIP diagram — https://coggle.it/diagram/VssL2FD-oEQ8IGQv/3e48c7aa04bffdbc88f610704de6779249eccd8217b5bc460741a8ff7cfc175b

---

**Notes**

- Concise terminology & tone-of-voice, so that developers can "learn" it and speak that same language, e.g. "composition, ecosystem", etc etc. (Taxonomy of web dev in general, not just limited to React)
- Separation of DOM vs. Custom components. From the point of view of a consuming developer, there's a lot of differences, even though they're all components.
- Tips could be in-context to the necessary categories or articles. They're currently unorganised.
- **My next step on this will be matching up all the Jekyll pages precisely to these categories. But I'm pretty confident they'll fit.**
---

Here's a rough outline for the "Guides" section based on the diagram. (I think anything covering the basics belongs in the Getting Started section) —

### DOM components

- Events
  - Synthetics
- Styles
  - Inline styles
- Forms
  - Controlled vs. uncontrolled
- dangerouslyInnerSetHTML?

### Custom components

- Definition
  - ES6 vs. createClass
  - Stateless functions
  - Static methods
  - Autobinding
- State [*Take from "Interactivity and dynamic UIs"?*]
- Lifecycle
  - Rendering
  - Mounting / unmounting
  - getInitialState?
  - ref / key ?
- Composition
  - Abstraction
  - Child components
  - Ownership
- Validation
  - propTypes
  - Flow
- Performance
  - Memoized renders / shallow compare
  - Immutability
  - Measurement API
- Integration
  - DOM / other libraries
  - Web Components

### JSX

- Displaying data
- Conditionals
- Gotchas

### Ecosystem

- Flux
- Relay
- Immutable
- Router
- Flow

**Comment by arirawr** [comment]
Still an issue it seems? Is anyone actively working on updating this?

**Comment by spicyj** [comment]
No.

**Comment by gaearon** [comment]
This was mostly fixed by New Docs (#7864).
https://facebook.github.io/react/
