### ISSUE TITLE
react bundle size is creeping up

### ISSUE THREAD

**Issue by zsolt-dev** [facebook/react#16707]
Hi,

I really love React, especially with the new hooks API, but I have issues with the bundle size.

React 16.9.0 takes 131kB of my bundle. And I also need to ship my code and some other packages.

This makes the time to interactive on older phones slow.

I serve the bundle compressed, but it is still a lot of CPU cycles processing javascript. My point is that 131kB of JS !== 131kB of jpg image.

The bundle size of react is creeping up all the time. Maybe React could benefit from some bundle limit, let's say 70kB?

I know that there is Preact that has only 3kB gzipped, but I am not sure if it is as stable as React.

Is there a plan to work on the bundle size?

<img width="742" alt="react" src="https://user-images.githubusercontent.com/18726534/64520304-253c3000-d2f6-11e9-9b42-3a69c02c032d.png">

thank you

**Comment by threepointone** [comment]
I empathize with your concern. React could be smaller, but that would mean we remove functionality that's critical to its design constraints. Instead, we try to provide a core that makes components lighter, and encourage dynamically loading code on demand. I've personally noticed that appropriate code splitting, and picking smaller dependencies helps alleviate the problem. 

From your screenshot, for example, it appears React is only 20% of your bundle. What are your other dependencies? Are there modules that could be loaded later, either by dynamic `import()`, or `React.lazy()`? Are they all critical/do they have smaller equivalents?

There's a broader discussion to be had about server rendering strategies, for eg: partially hydrating html as it streams in, and adding interactive behaviour before the React bundle loads. We're actively working on some new features for the server renderer that will make this sort of thing possible, but there's nothing we can share today. We will definitely talk about this more in the future. 

I'm going to close this since it isn't a bug or feature request per se, but we will share more information when it's available. Thank you for asking!
