### ISSUE TITLE
Findless Error in react, Error Can only update a mounted or mounting   component.

### ISSUE THREAD

**Issue by ShinyBoy0** [facebook/react#16741]
I know this question has been asked before me, but I need help!

React doesn't detect the exact location that where is going error!

I've been getting this error for the 3 days, but I don't know about this error. even I search a lot, check the original code, but nothing happened!

    `proxyConsole.js:56 Warning: Can only update a mounted or mounting 
     component. This usually means you called setState, replaceState, or 
     forceUpdate on an unmounted component. This is a no-op.

    Please check the code for the _class2 component.`

***ContactData.js***, I believe the error is happing here, because when I trigger the button, so I get that.

        import React, { Component } from 'react';
    
    import Button from '../../../components/UI/Button/Button';
    import axios from '../../../axios-orders';
    import classes from './ContactData.css';
    import Spinner from '../../../components/UI/Spinner/Spinner';
    
    
    class ContactData extends Component {
    
        state = {
            loading: false
        }
    
        orderHandler = (event) => {
            
            event.preventDefault();
    
            // e.preventDefault();
            this.setState( { loading: true } );
    
            const order = {
                // ingredients: this.props.ingredients,
                // price: this.props.price,
                // // customer: {
                // //     name: 'Max Schwarzmüller',
                // //     address: {
                // //         street: 'Teststreet 1',
                // //         zipCode: '41351',
                // //         country: 'Germany'
                // //     },
                // //     email: 'test@test.com'
                // // },
                // deliveryMethod: 'fastest'
            }
            axios.post( '/orders.json', order )
                .then( response => {
                    this.setState( { loading: false } );
                    this.props.history.push('/');
    
                } )
                .catch( error => {
                    this.setState( { loading: false } );
                    this.props.history.push('/');
    
                } );
                console.log('9')
    
        }
    
        render() {
            console.log(this.state);
    
            let form = <Spinner />
            
            if( !this.state.loading )
            {
                form = (
                    <form>
                        <input type="text" placeholder="Enter Your Name" />
                        <input type="text" placeholder="Enter Your Name" />
                        <input type="text" placeholder="Enter Your Name" />
                        <input type="text" placeholder="Enter Your Name" />
                        <input type="text" placeholder="Enter Your Name" />
                        <Button btnType="Success" clicked={this.orderHandler}>Order</Button>
                    </form>
                );
            }
            console.log('10')
    
    
            return (
                <div className={classes.Contact_data}>
                    <h1> Your Contact Data !</h1>
                    {form}
                </div>
            );
        }
    }
    
    export default ContactData;

The Whole Repo is uploaded [here][1]

  [1]: https://github.com/ShinyBoy0/React-error

**Comment by Dergash** [comment]
Hello @ShinyBoy0! I'm not sure if my understanding of your problem is correct because you did not provide exact steps for reproducing and the repo is difficult to work with (node_modules folder really shouldn't go under git control, just use yarn.lock/package-lock.json), and I was not able to catch that specific error you described, but I've caught a similiar one:
![axios-unsubscribe](https://user-images.githubusercontent.com/13132449/64890108-0e506180-d699-11e9-99e5-bd7bb1142e07.PNG)
And I believe they both have the same reason as the warnings are essentially same - calling setState on unmounted component.
Thing is, you wrapping your BurgerBuilder into withErrorHandler wrapper, and that wrapper contains following code in componentWillMount method:
```jsx
componentWillMount () {
    axios.interceptors.request.use(req => {
        this.setState({error: null});
        return req;
    });
}
```
So, you introduced a function that set state for withErrorHandler before every axios request. But you nave actually unsubscribed that function - when you are done with your burger ordering process, you made a this.props.history.push call for a different route, so your BurgerBuilder (and corresponding withErrorHandler) are unmounted and Checkout component is mounted. But, subscription still exist and when axios request have been made, your callback is fired, calling setState for a withErrorHandler, which is already unmounted, which is causing you problem.
I've made a PR that shows [how to unsubscribe](https://github.com/ShinyBoy0/React-error/pull/2/files) in componentWIllUnmount method. It should solve that warning, or at least give you idea what to look for.

**Comment by ShinyBoy0** [comment]
@Dergash ### Woah, You're awesome! You solved my problem, Thank You very much!

Now it's working as I expected. I was confused about this error, but I couldn't and you did it!

I hope you get everything you want in life!

**Comment by IHCoding** [comment]
you have forgotten to add the second argument in the burgerBuilder.js at last line. 
export default withErrorHandler(BurgerBuilder, axios);
