### ISSUE TITLE
[Concurrent Mode] App stops updating/rendering on inactive tab

### ISSUE THREAD

**Issue by brunolemos** [facebook/react#16773]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

1. When Concurrent Mode is enabled
2. and the Chrome tab is inactive
3. and a new render happens inside app
4. the app won't render this update until I open the chrome tab.

This only happens on Concurrent Mode. I noticed this because I update the document title on a react Context, like this:
<img width="140" alt="Screen Shot 2019-09-12 at 23 58 05" src="https://user-images.githubusercontent.com/619186/64834916-5e0c2b80-d5ba-11e9-8d1c-d3581c9c237e.png">

and on Concurrent Mode it was never updating when the tab was inactive. Only when I opened the tab. 

Disabling Concurrent Mode was enough for it to start working as expected.

I believe this is related to the Chrome throttling behavior of inactive tabs. For example, Chrome doesn't resolve neither `requestIdleCallback` neither `requestAnimationFrame` when the tab is inactive. Made this non-react example just to show this Chrome behavior because I believe it's related: https://codesandbox.io/embed/dank-fire-0zjxv

Reproduction using `useEffect` and allow changing between legacy/sync/concurrent modes: https://codesandbox.io/embed/react-bug-inactive-tabs-tnosy

### Incorrect behavior (sync or concurrent mode, it get's completely suspended)

![reproduction-concurrent.gif](https://user-images.githubusercontent.com/619186/64887291-b08f2b80-d63e-11e9-8d17-2ef9c6427881.gif)

**What is the expected behavior?**

Inactive tabs should have the same behavior with or without Concurrent Mode. They should keep updating/rendering things (ok if a little bit throttled), but NOT completely pause doing things until the tab becomes active.

![correct-behavior.gif](https://user-images.githubusercontent.com/619186/64887568-4f1b8c80-d63f-11e9-90df-a990291eac75.gif)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 16.9
Chrome 76
macOS

**Comment by Dergash** [comment]
Hi @brunolemos! If you've read about browser throttling of inactive tabs then you've also probably  read about the reasoning behind that decision - inactive tab should try to minimize js execution to improve performance for tab that is active, and limit power consumption on mobile/laptops.
So the current behavior is expected and I don't see how it is a bug. You should not expect that you application will work the same way when tab is inactive and I don't think developing a way to circumvent it is a good idea - I for example currently have 100+ opened tabs and it would've been a nightmare if every tab continued to work without js limitation.

**Comment by eps1lon** [comment]
The point of this issue was that there is a difference between concurrent and legacy mode not whether throttling of background tabs is useful.

It would be interesting to know how you updated the title previously. I guess you pass this notification to another component and in concurrent mode react/browser won't render components since they're offscreen (which makes sense).

Note: The same issue is observable in the unstable sync mode (`unstable_createSyncRoot`). Changing the title is throttled in chrome anyway for inactive tabs. Even in legacy mode you  won't get updates at e.g. 10fps.

**Comment by Dergash** [comment]
> The point of this issue was that there is a difference between concurrent and legacy mode not whether throttling of background tabs is useful.

That's not what I've see in the issue :) I see 'expected behavior' section with described behavior which does not seems expected to me.
The point is, the initial assumption - that it should work without Concurrent Mode enabled - is wrong. Of course it might have worked, but there were no guarantees for that from browser vendors, so in my opinion when this behavior is broken that is not a React regression type bug, but a signal for unreliable client-side implementation which should be fixed.

**Comment by eps1lon** [comment]
>  I see 'expected behavior' section with described behavior which does not seems expected to me.

It was expected because that's what is happening with the current, stable API of react and with basic DOM API.

> Of course it might have worked, but there were no guarantees for that from browser vendors

Do you have a link to the set of supported DOM APIs for inactive tabs or a list of unsupported ones?

**Comment by Dergash** [comment]
> It was expected because that's what is happening with the current, stable API of react and with basic DOM API.

But that is exactly my point that [it is not what was happening](https://codesandbox.io/s/proud-tree-4etgk). Code sample specifically set to React 15.0.2 without any concurrent mode support, and the problem still there - state updating / rendering for inactive tab does not match updates / rerenders for active tab. The degree and reasoning behind that mismatch - if they are throttled in case of setTimeout/setInterval, or if they are totally suspended until tab became active in case of requestAnimationFrame - is irrelevant in my opinion, they are just do not work the same way and it shouldn't be expected.

> Do you have a link to the set of supported DOM APIs for inactive tabs or a list of unsupported ones?

I'm not sure what you are asking; they are supported, just have no guarantees for execution, only for scheduling. If you asking what regulates that 'no guarantees' passage, then I believe it's
[HTML Timers section](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers) for setTimeout/setInterval:

> This API does not guarantee that timers will run exactly on schedule. Delays due to CPU load, other tasks, etc, are to be expected.

requestAnimationFrame/requestIdleCallback suspending for inactive tabs probably regulated by
[Timing control for script-based animations](https://www.w3.org/TR/animation-timing/#dom-windowanimationtiming-requestanimationframe):

> 5. Processing Model
> Whenever a Document's hidden attribute ([Page Visibility]) **is false** ..., the user agent MUST regularly queue

Is clearly states that there is no 'MUST' when tab is inactive (document hidden attribute). Of course this specific document is obsolete (2015) in favor of [living standard](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animation-frames) which does not specify inactive tab that clearly - or maybe I just don't see it because I am not an expert on standards - I suppose it should follow from DedicatedWorker which refers to [worker processing model](https://html.spec.whatwg.org/?#worker-processing-model) which refers to [Cooperative Scheduling of Background Tasks](https://w3c.github.io/requestidlecallback/) which specifically says:

> When the user agent determines that the web page is not user visible it can throttle idle periods to reduce the power usage of the device, for example, only triggering an idle period every 10 seconds rather than continuously.

Again, sorry if I misunderstand and that was not what you've asked.

**Comment by threepointone** [comment]
I think this is a bug.

**Comment by eps1lon** [comment]
> But that is exactly my point that it is not what was happening.

Oh I'm sorry for the confusion. I totally agree that it's ok to not render something viewable if the tab is inactive. I was referring to the `document.title` issue which works fine with `ReactDOM.render` but not with the `unstable_create(Sync)Root` APIs (this is illustrated in my codesandbox). Basically the html part of the DOM not updating is fine in an inactive tab but other side effects like setting `document.title` should be executed in inactive tabs. This is IMO a perfectly valid use case for desktop applications.

**Comment by brunolemos** [comment]
Some clarifications:

1. I’m not using requestIdleCallback neither requestAnimationFrame on my code
2. I’m assuming concurrent mode does something similar to them because some maintainer commented that in a commit or pull request
3. Chrome throttles inactive tabs, but things keep working and being updated. They update it less often to decrease cpu usage, but don’t pause it completely
4. React stable without concurrent mode render new things at the screen on inactive tabs as expected, just like non-react code
5. On concurrent mode it seems to get completely paused, it doesn’t run effects, don’t render things at the screen, etc. So when I open the tab after a few minutes, it starts doing everything that got in the queue at once (when I open the tab I see the screen is rendering the exact same thing as before, and then it triggers the new renders)

**Comment by brunolemos** [comment]
> https://codesandbox.io/s/inactive-tabs-react-render-smy31

@eps1lon this demo is great, thank you. Updated a little bit (added `mode` to the title) and added the link to the first comment if you don't mind: https://codesandbox.io/s/react-bug-inactive-tabs-tnosy

**Comment by gaearon** [comment]
Does this repro on master?

**Comment by eps1lon** [comment]
> Does this repro on master?

* [using 87eaa90ef8dabd3d557085586d524016cd946d30](https://inspiring-raman-67de31.netlify.com/) ([code](https://github.com/eps1lon/inactive-tabs-react-render/tree/master))
* [using 16.9.0](https://16-9-0--inspiring-raman-67de31.netlify.com/) ([code](https://github.com/eps1lon/inactive-tabs-react-render/tree/16.9.0))

Installing with less than 5 clicks makes this really smooth 👍

**Comment by acdlite** [comment]
Just to confirm, that indicates to me that this is fixed on master, correct?

You can also test by updating React, React DOM, and Scheduler to `0.0.0-45b6443c9`

**Comment by brunolemos** [comment]
> Just to confirm, that indicates to me that this is fixed on master, correct?

Looks like it!

> You can also test by updating React, React DOM, and Scheduler to 0.0.0-45b6443c9

Changing `react-dom` to `0.0.0-45b6443c9` in the codesandbox reproduction fixes it.

I'm curious to see which commit fixed it.

**Comment by gpietro** [comment]
I have a similar problem but on rendering in inactive tabs.
I do render a chart with d3.js and there is an update every ~200ms. On active tabs the chart is rendered fine but when the tab is inactive and I go back to it, I see a squashed line.
**Active tab**
![active tab](https://user-images.githubusercontent.com/7089910/92252656-d4422600-eece-11ea-8b20-5fd4c24c3ff1.png)
**Inactive tab**
![inactive tab](https://user-images.githubusercontent.com/7089910/92252660-d4dabc80-eece-11ea-8448-526c03721e23.png)

**Comment by ansh-FF** [comment]
> I have a similar problem but on rendering in inactive tabs. I do render a chart with d3.js and there is an update every ~200ms. On active tabs the chart is rendered fine but when the tab is inactive and I go back to it, I see a squashed line. **Active tab** ![active tab](https://user-images.githubusercontent.com/7089910/92252656-d4422600-eece-11ea-8b20-5fd4c24c3ff1.png) **Inactive tab** ![inactive tab](https://user-images.githubusercontent.com/7089910/92252660-d4dabc80-eece-11ea-8448-526c03721e23.png)


Hi @gpietro , did you got any solution regarding this issue ?
I am also facing a similar issue.

if I leave the chart tab in the background while focusing on other tabs, or if the tab is active but my system is locked (Windows + L), the live updates eventually pause. When I unlock the system or bring the tab back into focus, the updates resume.
