### ISSUE TITLE
NPM START ERROR - Can't create local server

### ISSUE THREAD

**Issue by DavidRNogueira** [facebook/react#16770]
I am learning React, I created react app, i typed cd davidsapp, but when I run npm install i get warnings and errors, and when I input npm start, I get all the errors posted in this link. What can I do?

https://gist.github.com/DavidRNogueira/da37a599c37ad8661c55bf599b7e0751

**Comment by threepointone** [comment]
Please include the errors/warnings you get when you type "npm install"

**Comment by DavidRNogueira** [comment]
https://gist.github.com/DavidRNogueira/bd26ba2ccbbda8f05fc5f96f5329a411

Here’s what I get with npm install.

**Comment by threepointone** [comment]
I'm going to close this issue because it's not a react issue. I thought I could help, but I just don't have the information to do so. Consider filing your issue at https://github.com/facebook/create-react-app/issues My guess is that your dependencies are not being installed correctly, possibly because of an older node version.
