### ISSUE TITLE
ReactLink does not update input when state changes to null or undefined

### ISSUE THREAD

**Issue by brycekahle** [facebook/react#1678]
http://jsfiddle.net/q8K9A/1/

If you reset a state variable to `null` or `undefined` the input control doesn't change. You have to reset to empty string `''` for it to change.

**Comment by jimfb** [comment]
As per https://github.com/facebook/react/issues/2302 the current plan is to pull linking out of controlled components, which renders this issue no longer applicable.  As per https://github.com/facebook/react/issues/2302 it's easy to create wrappers that expose any behavior (including the undefined/null reset behavior described in this issue).  If you find this behavior useful, I would encourage you to publish a npm module or git repository that provides this functionality as a wrapper component so other people can use it. Since this is not something we plan on supporting in the core, I'm going to go ahead and close out the issue.
