### ISSUE TITLE
bug | useReducer changing payload of action

### ISSUE THREAD

**Issue by BreadAndRoses95** [facebook/react#16793]
I ran into a strange behavior of useReducer. I tried implemeting my own redux and redux thunk for a small project. Here is a small replication of what I try to achieve. https://codesandbox.io/s/delicate-microservice-5qlt5 I do not have the bug here, but on my production build only. When I dispatch this action once, it get triggered three times. The third time, the payload becomes null instead of [] (empty array). 
I tried to find where the action/payload was changed and this is in the updateReducer. 
![image](https://user-images.githubusercontent.com/25157915/64962655-14f8f780-d898-11e9-8f3c-bed07e0166de.png)

![image](https://user-images.githubusercontent.com/25157915/64962685-2510d700-d898-11e9-9fa1-3eaa9bdf3051.png)

I don't have any clue of how this could happen since we juste get the action from the firstRenderPhaseUpdate object. 

Telle me if I missed something, I can give you more information.

**Comment by Dergash** [comment]
Hello @BreadAndRoses95! I'm afraid your codesandbox example doesn't work, StateProvider.js is empty.
I noticed following code in your example though:
```jsx
  useEffect(() => {
    dispatch(thunkAction([]));
  });
```
I believe you need to specify a second argument (empty array if your dispatch is memoized setState function and you you thunkActions is hoisted), otherwise it will fire every rerender - might be the reason why you getting three calls on one dispatch.

**Comment by Dergash** [comment]
Sorry, still empty:  
![issue-16793](https://user-images.githubusercontent.com/13132449/65023200-8a2e0080-d95c-11e9-887b-b59aed32913a.PNG)
