### ISSUE TITLE
React remount hooks when using throw promise and suspence

### ISSUE THREAD

**Issue by hugo972** [facebook/react#16816]
**Do you want to request a *feature* or report a *bug*?** 
Not sure if that is by design or a bug

**What is the current behavior?**
```
function MyComponent() {
    const [state, setState] = useState(() => { console.log("init"); return "some state"; });
    const promise = getOrFetch("/some/api");
    if (!promise.completed /* let imagine you can do this */) { console.log("waiting"); throw promise; }
    console.log('rendering');
}
```
the result in the console is:
init
waiting
init
waiting
init
rendering

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

I expect hooks mounting will happen once even when using throw promise and suspense. looking at the console logs you can see that each time we thrown to suspence the hooks are remounting. I expect the console log be like:
init
waiting
waiting
waiting
rendering

 In order to achivie a hook like behavior I will need to implement it by myself using the __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED (and I would like to keep my job)

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
latest, chrome, windows

**Comment by threepointone** [comment]
This is an internal implementation detail; there shouldn’t be any observable difference in both cases, since you wouldn’t run any side effects in render (like the console.log you have in a state initialiser)

(Also, we haven’t exposed generic suspense apis yet, so your method of throwing promises is unsupported right now. )

Closing since this isn’t a bug or feature request per se, but happy to clarify if you have a usecase.

**Comment by gaearon** [comment]
There technically *is* observable behavior in the sense that your state gets reset (so you can’t store anything there if you kick off a fetch with Suspense). But it is intentional.

Suspense is not really officially supported for data fetching at all right now. If you insist on using it, you need to follow the rules — and one of them is that **you need an external cache** that keeps the data and ensures the same Promise is being thrown every time if the operation is already in progress. Suspense is *not* supposed to be used with React state as a backing mechanism. 

In the future we’ll likely implement an optimisation called “resuming” that would fix the problem you describe. But for now this works as expected. And don’t forget Suspense for data fetching isn’t an officially supported use case today.

**Comment by threepointone** [comment]
> There technically is observable behavior in the sense that your state gets reset (so you can’t store anything there if you kick off a fetch with Suspense). But it is intentional.

iiuc, state _won't_ be reset when suspends happen on updates, isn't that right? But in both cases, there's no observable difference to the component behaviour itself (unless you consider the act of calling the initializers a side effect)

**Comment by hugo972** [comment]
Make sense, thanks for the reply. I did use an extenal cache. Hopfuly this would be supported officually as we loved this approach (over the other options we had)

**Comment by gaearon** [comment]
>iiuc, state won't be reset when suspends happen on updates, isn't that right?

I thought this was about suspending during initial mount.

**Comment by threepointone** [comment]
In the case of initial mount, is it considered a reset if a component didn't finish mounting at all? `Reset` to me would imply that it gained a value, possibly changed after state changes, and then reset back to its initial state. Because there aren't any side effects in render, on initial mount there's no state to reset (or rather, it'll be the same value during all runs, with/without suspending)

Hence, the disclaimer too - If the act of creating state is considered a side effect (for eg, it may be `useState(() => new ObjectWithSideEffectsInConstructor())`, then that might be considered observable behaviour. 

(We're probably talking past each other)
