### ISSUE TITLE
[npm:create-react-class] Support PureComponent & propTypes

### ISSUE THREAD

**Issue by pjebs** [facebook/react#16854]
https://reactjs.org/docs/react-without-es6.html

The "react without es6" page should give explanation on how to use the equivalent of a `PureComponent` using `create-react-class` npm package. I Couldn't figure out how to do it. The page seems to be very outdated with new react features.

If it's not possible to do, this issue should be a feature request.

**Comment by pjebs** [comment]
https://reactjs.org/docs/typechecking-with-proptypes.html

It's also unclear how to set `propTypes`.

**Comment by threepointone** [comment]
Could you tell me why you're not using ES6 in making new components? `create-react-class` was a compatibility layer when we moved to regular javascript classes, and I wouldn't recommend it for new code. (Alternately, you could use function components, which don't require class syntax.)

**Comment by pjebs** [comment]
I maintain this package: https://github.com/rocketlaunchr/react

**Comment by M-Izadmehr** [comment]
It's better not to go for `create-react-class` (I am not 100% sure about some of the following comments):
1. create-react-class is not maintained since two years ago (version 15.6), as a matter of `createClass` was a part of the main react repository up to version 15.5, then it was moved to separate npm package `create-react-class` in version 15.6 (still inside the addons folder in react Github), and when version 16 was released, the addons folder was removed, and nothing was pushed on it anymore. 
2. The latest working version of create-react-class is `15.6.3`.
3. In order to use `PureComponents` with ES5 format, you can use the deprecated plugin [`react-addons-pure-render-mixin`](https://www.npmjs.com/package/react-addons-pure-render-mixin)(15.6.2), in order to use it you have to add a `mixin` object inside your `createClass` with the value of PureRenderMixin:

```js
var createReactClass = require('create-react-class');
var PureRenderMixin = require('react-addons-pure-render-mixin'); 


createReactClass({
  mixins: [PureRenderMixin],

  render: function() {
    return <div className={this.props.className}>foo</div>;
  }
});
```

4. In order to use propTypes, you can add the field `propTypes` inside `createClass`:

```js
var createReactClass = require('create-react-class');


createReactClass({
  propTypes: {
     className: Proptypes.String,
 },

  render: function() {
    return <div className={this.props.className}>foo</div>;
  }
});
```

**Conclusion**: The ES5 versions are no longer maintained, so I don't suggest trying to use it.

Also, I guess that we need to add some notes about `react without es6` page, to tell users not to use it anymore:)

**Comment by pjebs** [comment]
That's a shame because not everyone uses react with JavaScript. The gopherjs project which I rely on doesn't support es6. I rely on create-react-class

**Comment by pjebs** [comment]
@M-Izadmehr Is your suggestion simulating a `PureComponent` or is it actually _implementing_ a `PureComponent`?

**Comment by M-Izadmehr** [comment]
Well, `React.PureComponent` is by nature very simple concept (just a shallow comparison of props). 
But the main problem still remains, your project seems really exciting, but do you want to only support an old version of react with lots of deprecated features?

**Comment by pjebs** [comment]
Of course not. I just don't have a choice.
