### ISSUE TITLE
Proposal of recommended config in `eslint-plugin-react-hooks`

### ISSUE THREAD

**Issue by maximandrews** [facebook/react#16872]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If you are using `eslint-plugin-react-hooks` you need to put rules configuration manually. What if in the next version you will add some more rules?
Should everyone who use it after future release add all the **new** rules to config manually?

**What is the expected behavior?**
I propose instead of instructing on every new rule to create `recommended` [config](https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins) as in `eslint-plugin-react`, as follows:
```
export default {
  rules: {
    'rules-of-hooks': RuleOfHooks,
    'exhaustive-deps': ExhaustiveDeps
  },
  configs: {
    recommended: {
      plugins: [ 'react-hooks' ],
      parserOptions: {
        ecmaFeatures: { jsx: true }
      },
      rules: {
        'react-hooks/rules-of-hooks': 'error',
        'react-hooks/exhaustive-deps': 'warn'
      }
    }
  }
};
```
Also, to instruct to extend instead:
```
extends: [
  'eslint:recommended',
  'plugin:react/recommended',
  'plugin:react-hooks/recommended'
],
```

**Comment by sargant** [comment]
I would also very much like this. Is it a matter of just putting the above in a PR, or would comprehensive tests also be needed?

I'd expect the documentation should also be updated to recommend using this instead of manual rules.

**Comment by einarq** [comment]
Does anyone know why the recommendation is to set exhaustive-deps to warn instead of error?
Won't incorrect deps usually lead to stale props, missed renders, too many renders, etc? 
I'm trying to make sure everyone on my team enable and follow this rule, but "warn" only helps if people actually notice. Why not recommend "error" instead?

**Comment by silvenon** [comment]
I'm also struggling to understand this decision. Also, I find it weird when autofixable rules are warnings instead of errors because I always autofix both in my text editor and on `pre-commit`, so I would like it to be an error instead. Then if I want to exclude a certain situation for whatever reason, I add an `eslint-disable` comment.

**Comment by silvenon** [comment]
@maximandrews since you already know how to do this, maybe you could send this proposition in a form of a PR? Perhaps it will have a higher chance of being accepted.

**Comment by linvain** [comment]
`eslint-plugin-import` does include recommended config as well:
```js
"extends": [
  "eslint:recommended",
  "plugin:import/recommended",
  "plugin:react/recommended",
  "plugin:react-hooks/recommended" // proposal
]
```

**Comment by silvenon** [comment]
Actually I found out why `react-hooks/exhaustive-deps` is recommended as `warn`: because it might not always be right, i.e. might not always correctly detect all the necessary dependencies. This decision makes sense to me now.
