### ISSUE TITLE
Hook params inside functions are not updated (only for event listeners)

### ISSUE THREAD

**Issue by M-Izadmehr** [facebook/react#16887]
**Do you want to request a *feature* or report a *bug*?**
Bug(possibly)

**What is the current behavior?**
Whenever a function is called as the consequence of an `EventListener`, the value of hooks inside that function is not updated.
[Demo Hooks Behaviour](https://jsfiddle.net/Saliz/eqtd8x7g/16/)
[Demo Class Behaviour](https://jsfiddle.net/Saliz/0m3tw9s1/1/)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React.**
If you look at the examples, I created some `changeVal` methods which are responsible for adding +1 to `val` in 3 different cases.

I call this handler on 3 different occasions:
1) button `onClick`
2) the eventListener `mouseMove` added to the `window`
3) `onMouseMove` property of a div element

**changeVal** is a small method like this:
* class definition: 
```js
changeVal = () => {
    console.log("value inside changeVal:", this.state.val);
    this.setState({ val: this.state.val + 1 });
};
```
* functional definition:
```js
const changeVal = () => {
    console.log("value inside changeVal:", val);
    setVal(val => val + 1);
};
```

However, if I try to `console.log` the value of `val` inside this `changeVal` function,
* Class component behaves as expected, and it logs the value of `this.state.val` correctly for all cases
* Functional component shows correct `val` for cases `(1)` and `(2)`, however for `(3)` it shows the initial value (0)

[Somewhere in docs](https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function) I saw that:

> Any function inside a component, including event handlers and effects, “sees” the props and state from the render it was created in.

I guess this is due to that issue, why is it even a case, because `val` exists in the lexical scope of the function. 
Also, this behavior is different from the expected behavior from classes.
Moreover, this statement is not completely right, because `onMouseMove` method of `div` is also an event handler, why does it show the correct value, but not `window.addEventListener` shows the wrong value?

**What is the expected behavior?**
The log inside the function should show the same value in all cases because the scope of the function includes the `val` value

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react = 16.9
react-dom = 16.9
I guess this problem has always existed with hooks.

**Comment by alexrohleder** [comment]
hey,

when you declare a function it will get the variables on its outer scope and "copy" to it's own scope (I might say something misleading here, since I never really read about it).

on classes it works because the variable it copies is the `this`, which will always be the same, and may have it's properties mutated on render (e.g. this.props or this.state), but the variable itself is the same;

on functions it don't work because you are declaring the event inside an useEffect with [] as second parameter, which means it will execute only on the first render, leading to an event declaration using the function with val equals to 0.

you see that the `onMouseMove={changeValOnScroll}` works because the `changeValOnScroll` will be different on every render, it will always have the latest declaration of the change function, that will always have the latest val.

**Comment by gaearon** [comment]
This is why if you write

```js
  React.useEffect(() => {
    window.addEventListener("mousemove", changeValEnventListener);
    return () => window.removeEventListener("scroll", changeValEnventListener);
  }, []);

  const changeValEnventListener = () => {
    console.log("value inside changeVal eventListener:", val);
    setVal(val => val + 1);
  };
```

You'll see a lint warning because you're breaking the rules. You can't use `val` inside `changeValEnventListener` without also declaring it in dependencies. You can see the warning in Problems tab [here](https://codesandbox.io/s/loving-jones-fkjf4) (or in a setup like Create React App that includes the linter).

However, declaring it in dependencies would cause the listener to get re-added and removed every time. If this is not what you want, you can indeed either use a functional form `setVal(v => v + 1)` or a ref.

If you want to understand this deeper, here's a few links:

* https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies
* https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often
* And a few deep dives:
  - https://overreacted.io/how-are-function-components-different-from-classes/
  - https://overreacted.io/a-complete-guide-to-useeffect/

Hope this helps!
