### ISSUE TITLE
Initial State object modified by React, No Warning

### ISSUE THREAD

**Issue by alexandrudanpop** [facebook/react#16940]
**Feature request - Warning for direct state mutation & no mutation on initial state object**

**What is the current behavior?**
When directly mutating an array in the react state instance the intialState object is also mutated. While I know updating the state this way is not the correct way, I see no React Warning to help people see that this is an issue and they should make state updates immutable.

Also I think the intialState object should not be modified under any circumstances by React, since it could be used to reset the state at some point.

Code Sandbox demonstrating the issue:
https://codesandbox.io/s/peaceful-khayyam-duq8f
**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
 react@16.9.0
 react-dom@16.9.0
 Windows 10 Pro 1903
 Chrome 77.0.3865.90, Firefox 69.0.1

**Comment by bvaughn** [comment]
Mutating values like this can cause problems, which is why our docs [suggest not to do it](https://reactjs.org/docs/optimizing-performance.html#the-power-of-not-mutating-data). For example, if you weren't wrapping the mutated array in a new object (`setState({ someArray: newArray })`) React wouldn't even register the need to re-render the component, since the state would not appear to have changed.

> I see no React Warning to help people see that this is an issue and they should make state updates immutable.

React has no way of detecting mutations in data like this.

> Also I think the intialState object should not be modified under any circumstances by React, since it could be used to reset the state at some point.

You're just storing a reference to the underlying array in state. (There's only one array with multiple references.) This is another example of how mutating props/state can cause problems.

I don't think this issue is really actionable, so I'm going to close it. We can chat more if anything above is unclear though! 😄
