### ISSUE TITLE
Why will Suspense for data fetching require a cache?

### ISSUE THREAD

**Issue by ghengeveld** [facebook/react#16954]
I'm [integrating Suspense with React Async](https://github.com/async-library/react-async/pull/153), and I've been reading up on how it's supposed to work. All the resources I found talk about needing `react-cache` or another cache mechanism for Suspense to work properly. However, none of the resources explain WHY Suspense needs a cache. Could someone explain that? I've been able to [make it work without a cache](https://github.com/async-library/react-async/pull/153/files#diff-2d8d9c51cb93c9f7f57c81f6f7f1669a). Am I missing something?

**Comment by Freak613** [comment]
React will destroy local state whenever you throw anything from component:
https://codesandbox.io/s/inspiring-lumiere-70r3z

And caching needs to track your requests outside of destroyed component, somewhere that is stateful and won't be corrupted.

**Comment by ghengeveld** [comment]
Won't `useRef` work? I'm still struggling to understand. It works fine without one. I've come to see the cache as a means to synchronously resolve the data in order to avoid unnecessary rerenders. But personally I don't really care about that, it feels like a premature optimization.

**Comment by rovansteen** [comment]
If your suspended component unmounts as a result of a <Placeholder /> higher up in the tree you will lose your local state and refs. That’s why you need the data in something that lives outside your components: the cache.

**Comment by brainkim** [comment]
Would like to see this issue replied to before it’s marked as stale and locked, maybe with an update by the original author with an update for this issue.

**Comment by gaearon** [comment]
Sorry I didn’t see this issue earlier! This has nothing to do with optimisations. 

Suspense requires a cache because when a tee suspends, we want to be able to throw that render attempt away. None of the just-created components’ state or refs are preserved. If you keep data inside state or refs, it would have to be *above* the closest Suspense boundary from the place that may suspend while mounting. Because it that data/Promise gets thrown away, then you’re going to have an infinite loop of render attempts, each time throwing a different Promise. 

In that sense, yes, keeping it in a ref *is* a form of a “cache”. But this ref would have to be higher than any Suspense boundary wrapping any usage of that data, which presumably is very close to the root. So you can’t just put it inside your Hook that suspends. That’s a rather unintuitive but an important limitation.

Another way to look at it is that *data has a lifetime associated with it*. But rendering has no lifetime. It’s just a render attempt. You need to attach data to something that lives on permanently. That “something” is a cache. It could be local state of a component sufficiently high up the tree. Or it could be an object outside of the component tree. In both cases you then need to decide how and when to invalidate the cache. And how to do this without breaking encapsulation between deep children and the cache owner. 

Our current thinking is that this concept of a cache and how it invalidates is tied to the idea of navigation. That broadly speaking, we can navigate “forward” and “back”, and the intent matters. When we navigate forward, we don’t want to show potentially stale cached data from the cache. Instead, we want to refetch. (To enable faster transitions, however, we’ll want to embed data needed by top-level views of the *next* screen into responses for the *previous* screen.) When we go back, we want to show data from the cache. Unless there was a mutation, in which case we do refetch the data when it happens.

I know this is rather hand wavy at this point but just wanted to explain where we’re going and how we’re thinking about these problems.

**Comment by ghengeveld** [comment]
Thanks for the extensive explanation, this is exactly what I was after. Thanks also for clarifying why a ref typically won't work for this purpose.

**Comment by lazeebee** [comment]
@gaearon Can you explain further why react can't implement that the state and refs of the suspended component aren't thrown away?

**Comment by jezzgoodwin** [comment]
@gaearon Thanks for the explanation. I wondered if you guys have thought about keeping the state alive for suspended components? It feels like it would make working with Suspense easier.
