### ISSUE TITLE
Better docs for `<select multiple/>`

### ISSUE THREAD

**Issue by zpao** [facebook/react#1700]
From #671:

> @zpao The [docs on forms](http://facebook.github.io/react/docs/forms.html) could be clearer by mentioning that you can put an array into the `value` attribute (the usage example is likely to be `<select multiple>`).

cc @sompylasar

**Comment by gaearon** [comment]
Reopening because new docs don't have that info, and it is confusing.
We should re-add it.

**Comment by mtoujiline** [comment]
I am looking to make my first contribution and would like to fix this issue.

**Comment by hawkins** [comment]
I also opened a PR for this on #9539 last week, restoring the original note.

I added notes for discussion on a more thorough example on the PR, like the current `<select>` example has, but have not done much beyond that. Do we think that such an example would be beneficial? I almost think not, since the difference is just treating `value` as an array with `multiple`, but I'm curious to hear everyone else's thoughts on that.

**Comment by hawkins** [comment]
There hasn't been any further discussion in PR #9539 or on this issue in the last two months, so is that PR all we need to do for this? 

cc @gaearon

**Comment by gaearon** [comment]
Sorry. We’ve been busy with a rewrite for React 16, and haven’t been actively reviewing the PRs.

**Comment by gaearon** [comment]
Fixed in https://github.com/facebook/react/pull/9539.

**Comment by hawkins** [comment]
No sweat, I figured as much. React 16 was absolutely worth it, great work! 🎉
