### ISSUE TITLE
[DevTools] show state history like redux devtools does for actions and more

### ISSUE THREAD

**Issue by a-x-** [facebook/react#17029]
_**feature** request_

Nowadays we migrate much of our use-cases from complexes of high order redux actions+ HO selectors + HO reducers (I call it HOXes) to react hooks. Hooks allow us easier to incapsulate blocks of functionality rather it was possible with redux infrastructure, when we had to use our complex complexes to avoid much of copy-paste.

One drawback is lack of history of changes and more poor devtools at all. We creates many `useDebugValue` helpers, loggers and so one now.

**expected behavior?**

- show history of hook state changes with dom and js stack traces, diffs and maybe even history traversing
- allow more precisely editing of values in devtools. Currently I cannot choose number or string or bool or object when I edit prop or state value
- allow copying the state name in devtools (remove css no-action pls)
- add something like $r.state back
- preview complex values brifely like chrome devtools does it for arrays, sets, maps, objects,,,

I [wrote related twit](https://twitter.com/mxtnr/status/1178271362890240001) recently with one my DebugValue helper

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
all are latest

**Comment by bvaughn** [comment]
> allow more precisely editing of values in devtools. Currently I cannot choose number or string or bool or object when I edit prop or state value

This is incorrect. DevTools supports entering any JSON-parsable value.

> add something like $r.state back

`$r.state` is available for components with state, just as `$r.props` and `$r.hooks` are available for components with hooks.

**Comment by bvaughn** [comment]
I've responded before on why I don't think React DevTools can add a Redux-like props/state history, but I'm having trouble finding the post.

Essentially it comes down to the fact that in JavaScript, a lot of state is mutable- so storing a copy of a previous value would not be possible without deeply copying (and even the, some mutable globals can't be copied).

It would also add a lot of memory overhead and storing old closures would require retaining all of their references, preventing things from being garbage collected.

I'm going to close this issue because I don't think it's something we can (or should) take action on. Happy to continue discussing it here though if there are questions.

You may consider opening a new issue for this bullet:
> * preview complex values brifely like chrome devtools does it for arrays, sets, maps, objects,,,

I don't think I will have any time to work on it, but if someone wanted to contribute a PR I can try to find time to review it.

**Comment by a-x-** [comment]
I didn't hear about `$r.hooks` before, and it is not covered in react docs/blog posts as far, as I know
It was not available for because beta devtools had not auto apdated. Currently I update and I got json-like editing and $r.hooks, thank you for news!

**Comment by a-x-** [comment]
History of changes might be allowed for selected hooks (useState and useReducer), for example and only with opened devtools

**Comment by qmg-akara** [comment]
Thanks @bvaughn 
At least, would it be possible to have a history of the changed props? Something similar to [WebStorm debug tool](https://www.jetbrains.com/help/webstorm/debug-tool-window.html), the changed variables are highlighted when a breakpoint is hit for the second time. Something similar to the following table, first row is the component data at initial render and the second row is for the next re-render and so on.

![image](https://user-images.githubusercontent.com/75633942/121716190-a631e800-cad7-11eb-9031-2f8fc9f455e9.png)
