### ISSUE TITLE
Components not correctly displayed

### ISSUE THREAD

**Issue by lbottoni** [facebook/react#17038]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

elements not reconized

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

only use components tab in console of chrome.

**What is the expected behavior?**

see any elements react

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Window 10 64bit
react ^16.8.1

![image](https://user-images.githubusercontent.com/13313/66378070-068f8e80-e9b3-11e9-9956-cd8b98525efb.png)

This is my console component visualizzation, the same page visualizated with linux&chrome not have any issue

**Comment by threepointone** [comment]
What exactly is the problem here? Is it the shortened component names? That seems like you’re viewing the component tree of an app in production mode (probably with minified code). Could you explain what you expected to see?

**Comment by bvaughn** [comment]
Sunil is right. It looks like your screenshot above is showing a [production build](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build) and the component function names have been managed/minified (e.g. `MyComponent` -> `t`). This is generally what you want as it makes the bundle smaller (so it's faster to download and parse).

The DEV build should always show the non-minified component names. If you want to see them in the production build, you could either:
1. Disabling mangling. (How you do this would depend on what your build tooling is.)
1. Use [the `displayName` attribute](https://reactjs.org/docs/react-component.html#displayname).

I wouldn't really recommend doing either though, since both would make your app bundle larger.

**Comment by lbottoni** [comment]
yes correct!!My error work in production!sorry

**Comment by bvaughn** [comment]
No problem. Thanks for clarifying.
