### ISSUE TITLE
Q: should we use useCallback on native HTML elements

### ISSUE THREAD

**Issue by neo** [facebook/react#17055]
**Do you want to request a *feature* or report a *bug*?**

It's a question.

**What is the current behavior?**

According to the docs, this could be useful optimizing callback functions being passed down:

> This is useful when passing callbacks to optimized child components that rely on reference equality to prevent unnecessary renders (e.g. `shouldComponentUpdate`).

My question is: should we use `useCallback` when passing a callback to a native HTML element? e.g. `<button onClick={callback}></button>`

**Comment by markerikson** [comment]
No, there's no benefit for that.

The point of `useCallback` is to create a consistent reference for a callback function.  This primarily matters if you are passing it to a child component that is attempting to optimize re-renders based on whether its props have changed by reference (ie, `PureComponent` and `React.memo()`).  

A plain HTML element does not care if you are passing in a different click handler reference each time, so there's no benefit in this situation.

**Comment by threepointone** [comment]
^ like @markerikson said

**Comment by neo** [comment]
thank you both for clarifying! 🎉

**Comment by Eddie-CooRo** [comment]
Hey @markerikson, Thankyou for the answer. Although, I think I misunderstood something.
First of all, I'm somewhat sure that by "A plain HTML element", @neo means a React HTML host node and not a real DOM HTML element. So tell me if I'm wrong about that.
After that, I'm totally agree with you that using `useCallback` in this scenario, doesn't help much. But what I found misleading, is where you said:

> A plain HTML element does not care if you are passing in a different click handler reference each time

Because I thought that it actually cares. Doesn't React remove the previous listener and assign the new one whenever the reference changes? even if the both handlers are actually doing the same thing?

I'll be grateful if you would correct me if that's not the case. Thanks.

**Comment by markerikson** [comment]
Yeah, I mean "host node" in this case.

Yes, if I do `<div onClick={() => {}}>`, React will ultimately end up swapping the stored event handler on each render.  But, from the div's perspective, it doesn't matter at all.  Per my prior comments, it's only when you're rendering `<SomeMemoizedComponent onClick={() => {}}>` that the changing references makes any difference.

**Comment by neo** [comment]
oh now I think about it, is it because the event listener is never applied to the element but to the synthetic event system instead?

**Comment by markerikson** [comment]
Doesn't really specifically relate, but yes, that's part of what's going on here.  React has its one single event listener at the root of the component tree, and is (I assume) just storing something like `eventListeners[elementKey].onClick = element.props.onClick` (totally fake code).

**Comment by neo** [comment]
makes sense! thank you!

**Comment by corocoto** [comment]
@markerikson, thanks a lot for your answer.

>Yes, if I do `<div onClick={() => {}}>`, React will ultimately end up swapping the stored event handler on each render. But, from the div's perspective, it doesn't matter at all. Per my prior comments, it's only when you're rendering `<SomeMemoizedComponent onClick={() => {}}>` that the changing references makes any difference.

But can you describe this point in more details?  (maybe with links on source code) Because it's very interesting and importnant theme about how React really works under the hood. 

And I think, we can put this information into separate section of React documentation in the future. Becuse it's really missing there.

**Comment by markerikson** [comment]
I actually specifically covered this in my "React Rendering Behavior" post:

- https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#how-new-props-references-affect-render-optimizations

**Comment by corocoto** [comment]
@markerikson, amazing article. Thanks a lot
