### ISSUE TITLE
React Devtools should produce a better error message when integers are present as keys on react elements

### ISSUE THREAD

**Issue by alexkolson** [facebook/react#17134]
Current behavior: React Devtools throws "RangError: Invalid Array Length" when integers are used as keys on react elements. 

Example: 

https://codesandbox.io/s/interesting-violet-v5c5j

https://v5c5j.csb.app/

Using anything but strings as keys is as far as I understand not even correct usage, but it would be great if react devtools checked a little bit earlier and had a nicer error than "RangeError: Invalid Array Length." It takes a long time to figure out from this message that one somehow managed to use integers as keys and needs to correct it.

I've only tested with Chrome and the latest version of react devtools as a chrome extension.

**Comment by DongchengWang** [comment]
According to the example, it seems like if you don't explictly provide a `key` to a element,

```jsx
<ListItem key={0} />
```

it would escape from `hasValidKey` in

```js
// react/packages/react/src/ReactElement.js
export function jsx(type, config, maybeKey) {
  ...
  if (hasValidKey(config)) {
    key = '' + config.key;
  }
}
```

So the `key` was never converted to a string. 

And because of 

```js
Object.assign({}, e, { key: idx })
```

it also escaped from `validateExplicitKey`.

```js
// react/packages/react/src/ReactElementValidator.js
function validateExplicitKey(element, parentType) {
  if (!element._store || element._store.validated || element.key != null) {
    return;
  }
  ...
}
```

Finally, a `NaN` appeared somewhere(needs more info) like this.

```js
// RangError: Invalid Array Length
new Array(NaN)
```

How to deal with it? Should I check if `key` is a string in `validateExplicitKey` and display a warning?

**Comment by alexkolson** [comment]
Im just a React user but I would prefer if React itself didnt try and prevent deveopers like me from doing unintentional silly things but rather if React-Devtools helped point out my mistake better. The example is a bit contrived but is something I encountered in a production codebase and it took forever to figure out that we were generating our keys very wrong and that that was the cause of the RangeError. Also a side effect is that as soon as Devtools encounters this error it stops working for that page (obviously) and you can't use any of the cool functionality devtools offers.

So while you're trying to debug why the RangeError is happening you can't actually even use the devtools which makes the problem even harder to trace. I hope that makes sense somewhat.

**Comment by gaearon** [comment]
1. It is definitely supported to pass numbers as keys
2. DevTools shouldn't ever crash no matter whether there are mistakes in the app or not

So this is probably a bug we need to fix. I suppose we assume here that it's gonna be a string [here](https://github.com/facebook/react/blob/093de5fb43b32c2f587460341d7d35b8947c8fb4/packages/react-devtools-shared/src/backend/renderer.js#L1152) because `createElement` gives us that guarantee. But by `Object.assign`-ing it and copying it, you circumvented that guarantee. Even types inside React itself assume `fiber.key` is a string so this seems like something we'll have to think about more.

**Comment by DongchengWang** [comment]
`fiber.key` is assumed to be a string [here](https://github.com/facebook/react/blob/edc234c730731436fdc4d51bb6cef9de3561facc/packages/react-devtools-shared/src/backend/renderer.js#L1124) but it's not.

`str.length` could be `undefined` and `pendingStringTableLength` could be `NaN`.

The crash happens [here](https://github.com/facebook/react/blob/edc234c730731436fdc4d51bb6cef9de3561facc/packages/react-devtools-shared/src/backend/renderer.js#L1031).

Preventing DevTools from crashing by catching this kind of error would be great.

**Comment by bvaughn** [comment]
The way the keys are being assigned in this example is a bit unusual:
```js
export const genKeys = elements => {
  return elements.map((e, idx) => Object.assign({}, e, { key: idx }));
};
```
This is bypassing the JSX transform (which automatically stringifies non-string values) and modifying the React elements.

DevTools _can_ support this by making our key check more robust, but it technically violates the internal type expectations:
https://github.com/facebook/react/blob/5faf377df5267c4248599e14311a75c2f46050c0/packages/react-reconciler/src/ReactFiber.js#L139-L140
