### ISSUE TITLE
Fast Refresh does full reload if function component is not capitalized

### ISSUE THREAD

**Issue by hudon** [facebook/react#17142]
Currently, if your functional component's name starts with a lowercase letter, fast refresh will execute a *full reload* instead of just reloading that module.

This can be very confusing in applications using higher-order components where a functional component is pieced together in a HOC.
ie.
```
function myHOC(args) {
  var myComponent = (props) => {
    ...
  };
  myComponent.someStaticStuff = () => {
  };
  return myComponent
}
...
export const SubScreen = myHoc(args);
```

Expected behavior would be one of:
- A warning is emitted by `react-refresh` saying it is using the "heuristic" of looking at the first letter of a component to decide whether or not to reload the whole app
- Documentation makes this behavior explicit

Currently observed this bug in RN 0.61

I believe this is the offending line: https://github.com/facebook/react/blob/7082d5a2db5c1e5f49a62aecd90b6858f957da5e/packages/react-refresh/src/ReactFreshRuntime.js#L581

search terms: uppercase capitalize lowercase function component refresh reload

**Comment by gaearon** [comment]
This is intentional. We use PascalCase as convention for components in other places, e.g. JSX `<MyComponent />` will work but `<myComponent />` will not (it will think you want to use a new HTML tag).

The recommendation is to change your HOC instead:

```js
function myHOC(args) {
  var MyComponent = (props) => {
    ...
  };
  MyComponent.someStaticStuff = () => {
  };
  return MyComponent
}
...
export const SubScreen = myHoc(args);
```

That will both solve this problem *and* prevent further issues if you create two components in that HOC and one of them uses another one through JSX.

**Comment by IlanBeloglovsky** [comment]
Will this style also might produce the same issue?
`export default withStyles(appStyle)(App);`
