### ISSUE TITLE
useRef does not persist value when used with createRoot

### ISSUE THREAD

**Issue by sudesh955** [facebook/react#17193]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*.

**What is the current behavior?**

`React.useRef` does not persist value when using with `ReactDOM.createRoot`. It renders child component of main app component twice and does not persist ref value between these renders. 

When we use `React.useRef` with `ReactDOM.render` it renders child component of main app component only once.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://codepen.io/sudesh955/pen/zYYzdrg?editors=1011

**What is the expected behavior?**

It should persist ref across renders. For more details see comments in codepen link. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

version `0.0.0-experimental-f6b8d31a7` on chrome Version 78.0.3904.70 (Official Build) (64-bit) on ubuntu.

**Comment by Flufd** [comment]
I think this is due to the `createRoot` version running the application in strict mode.
Strict mode will run the render function twice as described here https://github.com/facebook/react/issues/15074#issuecomment-471197572

Here's an example where you can see the same output with both the regular render (with the app component wrapped in `<StrictMode/>`) and the concurrent render of just the app component:
https://codesandbox.io/s/immutable-browser-bqwcx

Note that the `useState` calculated value is calculated twice, but the `useEffect` effect is only run once.

I think it could be clearer in the docs that the hook components will be rendered twice in strict mode, and that the new concurrent mode will render the component with the same strict mode double rendering.

**Comment by probablyup** [comment]
@sudesh955 this should be reopened, I think it's an actual bug. It's fine that StrictMode is calling render multiple times, but it is not providing the proper hook backing data to the second render pass... effectively creating the component from scratch twice which is very different than the docs which says render may be called multiple times

**Comment by lostpebble** [comment]
@probablyup yep, this is causing a myriad of issues in my library now as well. It seems that the state in `useRef` is not being persisted properly between renders and its causing component cleanup and no-op issues because of that (certain flags set in `useRef`'s state are not being maintained).

People have opened up 2 issues related to this in the past couple days. It took me a while to figure out that CRA uses React.StrictMode by default, so many people are now running into this issue. Would appreciate some feedback about this and how it can be resolved.

**Comment by gaearon** [comment]
I'm not sure I'm following why your conclusion is that this is a bug in React.

Can you explain the behavior you're expecting? Conceptually, `StrictMode` intentionally completely "throws away" anything from one of the render attempts. That *does* include refs, by design. **Rendering should not be making side effects, so throwing away the ref values during one of the renders should be completely safe.** This would only affect the logic if you're doing something else — for example, subscribing to a store — which you should **not** do while rendering because rendering should not have side effects. This is exactly what `StrictMode` is supposed to catch.

Does this explanation help?

**Comment by bvaughn** [comment]
> for example, subscribing to a store — which you should **not** do while rendering because rendering should not have side effects

Some related background info here if you haven't seen it:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by lostpebble** [comment]
Thanks for the explanation @gaearon . I understand the concept here, but it does make things a little challenging.

Is there now no way for us to have "bare-metal" state associated with a Component in React ? State that exists outside of `useState`?

I can't remember exactly why I went the `useRef` route, but I think part of the challenge when using global-type state stores is that an update might have happened between the render phase and the commit phase. If the listener is only registered in the commit phase, then we will have stale state. Unless I'm mistaken- does the initialization of state inside `useState()` and the running of `useEffect()` run at the same time?

`useRef` allowed us to have a more bare-metal feel when creating hooks. A kind of control over state that is still tied to the component, but we can edit directly like a regular object. This is a very powerful thing to have, and if we can't rely on it its quite a bummer. But perhaps there are ways we can still achieve these things the React™ way.

I'm looking into this more deeply now and will try and find a solution that works within the concurrent React design.

**Comment by lostpebble** [comment]
So I've managed to refactor the basic state hook that my library uses to work in the confines of `useState` and `useEffect` - it seems on the surface that the stale state updates between the render and commit phases is minimal (I was able to reproduce it every once in a while using a `setInterval(updateState, 0)` - which is extreme).

I've landed on something like this now:

```tsx
function useStoreState(store: Store, getSubState?: (state: any) => any, deps?: ReadonlyArray<any>): any {
  const [current, setCurrent] = useState(() => {
    return getSubState ? getSubState(store.getRawState()) : store.getRawState();
  });

  useEffect(() => {
    const effectState = { shouldUpdate: true };

    function update() {
      const nextSubState = getSubState
        ? getSubState(store.getRawState())
        : store.getRawState();
      if (effectState.shouldUpdate && !isEqual(current, nextSubState)) {
        // final check again before actually running state update (might prevent no-op errors with React)
        if (effectState.shouldUpdate) {
          setCurrent(nextSubState);
        }
      }
    }

    const unregister = store._addUpdateListener(update);

    return () => {
      effectState.shouldUpdate = false;
      unregister();
    };
  }, deps ?? []);

  return current;
}
```

My biggest issue now is how would we now be able to have finer grained control over that state that's being returned? Since the store's state only gets registered during the initialization of `useState()` - how would we return a new state, when a user passes in new `deps`.

This is something that's easy to do with `useEffect` but not so much with `useState`. Is there any way for us to have `useState` which gets recalculated according to some `[deps]`?

This is where I would usually use `useRef` and just recalculate it directly in the render cycle and return the new state - being able to control a direct value like this has great benefits (also I wouldn't really classify this a side effect, as its pure function based on the inputs). In order to achieve what I want it seems I might still have to make use of `useRef` - or would have to shoot off a state update inside of `useEffect`, but I assumed that's a big no-no as well?

**Comment by bvaughn** [comment]
> If the listener is only registered in the commit phase, then we will have stale state.

If the listener is registered during render, you'll likely have memory leaks. Listeners should only be added in an effect.

The case you need to handle is: What if state changes between render and commit?

If you haven't already looked at it, I suggest checking out `useSubscription` as a reference for this:
https://github.com/facebook/react/blob/2eb3181eb4247077eafc4df98d06d7a999ecf5d8/packages/use-subscription/src/useSubscription.js#L61-L121

And better still– once we release it to stable, look at using the [new `useMutableSource` hook](https://github.com/reactjs/rfcs/blob/master/text/0147-use-mutable-source.md) for this and let React handle the tricky cases.

> My biggest issue now is how would we now be able to have finer grained control over that state that's being returned? Since the store's state only gets registered during the initialization of useState() - how would we return a new state, when a user passes in new deps.

Sounds like you're asking about how to update state when some props change (aka "derived state"). In most cases, [we recommend against this](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) as there are better patterns. If you need it though, you can store previous props [in state](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops) or [in a ref](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state) (which I think is slightly better).

**Comment by lostpebble** [comment]
Thanks @bvaughn ! That `useSubscription` is very similar to how I've set it up now.

> Sounds like you're asking about how to update state when some props change (aka "derived state"). In most cases, we recommend against this as there are better patterns. If you need it though, you can store previous props in state or in a ref (which I think is slightly better).

Yes, well its more the fact that the state being subscribed to is done using a selection function, which could also change how it pulls that state depending on a variable (much like how `useEffect` can be dependent on variables)- So we'd need to get the instant new state to replace what was previously set depending on what is passed in for that selection function and `[deps]`.

I've managed to achieve this and remove all the warnings in `React.StrictMode` using a combination of what is inside `useSubscription()` there and `useRef` to hold a direct reference to the state. The hook is completely pure now in the way it functions.

Thanks again- appreciate what you guys do and taking the time to help out here! :)
