### ISSUE TITLE
"de-opting to synchronous mode" in use-subscription README

### ISSUE THREAD

**Issue by jamesknelson** [facebook/react#17201]
**Do you want to request a *feature* or report a *bug*?**

Outdated README (maybe?)

**What do the docs currently say?**

> use-subscription is safe to use in concurrent mode. However, [it achieves correctness by sometimes de-opting to synchronous mode](https://github.com/facebook/react/issues/13186#issuecomment-403959161), obviating the benefits of concurrent rendering.

In the linked issue, @bvaughn [explains](https://github.com/facebook/react/issues/13186#issuecomment-403959161) that this is referring to chains of synchronous updates using `componentDidUpdate`. However, the `useSubscription` hook now uses a passive `useEffect()`, as opposed to a synchronous `componentDidUpdate()`.

Would this mean that it's no longer "de-opting to sync mode", and the warning could be removed from the README?

**Comment by jamesknelson** [comment]
Would still love an answer on this one!

**Comment by bvaughn** [comment]
The wording of the README isn't super accurate for `useSubscription`. I kind of copy-pasted that READ (with some tweaks) from `createSubscription`.

That being said, `useSubscription()` still has some downsides (both deopts and potential tearing). The decision to use a passive effect instead of an active one was a tradeoff between lesser bad options essentially.

I took the time this afternoon to create a Gist outlining the de-opt and potential tearing cases for `useSubscription` and a new hook (not yet created but soon to be RFCed) called `useMutableSource`:
https://gist.github.com/bvaughn/054b82781bec875345bd85a5b1344698

If you'd like to send a PR to update the wording on the `use-subscription` README, tag me as a reviewer. Else I will do a pass eventually when I get to implementing this new hook.

**Comment by dai-shi** [comment]
https://github.com/facebook/react/issues/15317#issuecomment-579900797
@kitten Have you seen this issue?
