### ISSUE TITLE
Utilize Suspense to express app init loader

### ISSUE THREAD

**Issue by FredyC** [facebook/react#17205]
With Concurrent mode getting finalized, I went to try to solve an old problem I have.

The app needs to run a series of init steps before it can do anything viable. Each steps depends on the previous one. This is expressed as nested components. The fairly elaborate animated logo is shown for that process, but it's being restarted for each step and the experience is not that nice.

I've prepared a demo with some experiments: https://codesandbox.io/s/react-suspense-loader-experimental-0ww6i

The first one that's active initially is what we currently have. The second is what we would like to have, but with less naive coding of decreasing counter.

The last one is my attempt to use Suspense, but I definitely missing something out here, because it behaves very oddly and I cannot seem to figure out why. I wonder if the new `useTransition` should be used somehow or what's going on here.

**Comment by Eddie-CooRo** [comment]
I think the problem is that when a component suspends while mounting, it doesn't get mounted at all. So none of its effects (like your useTimeoutFn) get called.
The best way to achieve what you're trying to do is to separate the firing of the promises, from throwing them in suspended components, like what React does in the fakeAPI it used in the concurrent mode documentations

**Comment by FredyC** [comment]
@Eddie-CooRo Thanks for the reply. I've adapted the example according to your advice.

https://codesandbox.io/s/react-suspense-loader-experimental-0f0eo

That did not work out how I expected. Suspense is actually remounting that loader as well for each step 😮 I even moved Suspense upper in the tree to be sure it's not a different problem. Perhaps I've misunderstood how is it supposed to work?

**Comment by Eddie-CooRo** [comment]
The flash of the fallback component is because your component doesn't suspend on mount, but it suspends later after setting its state to 'exec.' So at some point, there is one time when none of the components suspend, and there is no need for the fallback to show up.
I think what you are trying to achieve is possible this way: (It's a very simple demonstration)
Demo: https://codesandbox.io/s/react-suspense-loader-experimental-d1271

**Comment by FredyC** [comment]
Hm, I don't follow what's different? It still behaves the same way and remounts the loader.

> component doesn't suspend on mount,

I am confused before you have said it's wrong to suspend while mounting and it's wrong also? My brain is totally suspended from all this 😆

**Comment by Eddie-CooRo** [comment]
Sorry if I wasn't able to explain correctly what is happening in your example.
Let me try one more time. 😅

So, there are two different things to examine,

Firstly, when a component suspends during its mount, none of its effects get called, and neither its state gets persisted. Let's think about that this way, the useEffect documentation says:
>	effects run after every completed render

So when a component suspends, nothing gets rendered; therefore, React doesn't call any of its effects.
But it's not a *Problem* by itself. It's a *Behavior*, and it tells us that when our component suspends, it shouldn't rely on any of its effects, or ref/state s to un-suspend correctly.

Secondly, 
When we first let the component to mount before suspending it, for a short amount of time, the fallback doesn't show up because everything is rendered without suspending (but our component is returning "null" as its children). So this is the order of events, starting with the suspension of the step1 component:

1. Step1 Component suspends and fallback component gets mounted on the screen.
2. Step1 Component finishes suspending and renders its children.
3. Step2 Components render function gets called.
4. Because the initial state of the component step2 is 'pending,' it renders without suspending and returns nothing as it's children.
5. So react unmounts the fallback
6. React mounts the step1 component as well as its children (a.k.a component step2). Now, after committing the virtual DOM, we will see an empty screen. Because step1 renders step2, and step2 renders nothing.
7. Every passive effect gets called (as well as step2 component useEffect hook callback). and as a result, the state of the step2 component will change to 'exec.'
8. Step2 component re-renders duo to the change of the state and this time throws a promise and suspends.
9. React mounts the fallback component again, and we will see the new percent on the screen

So at one point in time(when we are at event number 6), there will be nothing displayed on the screen, and this will result in flashing of the fallback component for a second

But the order of the events for the example I sent in the previous comment, is different:

1. Step1 Component suspends and fallback component gets mounted on the screen.
2. Step1 Component finishes suspending and renders its children.
3. Step2 Components render function gets called.
4. Step2 Component suspends during its render.
5. React forgets everything about the Step2 Component and falls back to the fallback component.

So the fallback component stays mounted on the screen all the time.

**Comment by FredyC** [comment]
Oh, you have changed whole PageLoader implementation, that's what has confused me 🙈 Before I just had a fixed number (seconds portion of time) to be able to see if a component is getting remounted. In reality, there will be an animated gif, so there is no need for re-rendering, but remounting would cause ugly flickering. With percent progress, it's not apparent that it's the same component instance which is just getting re-rendered 💯 

This is amazing. I wish an example like that was in the documentation to clear things out. It's hard to believe other apps don't need an init phase like that. Unfortunately, I tried in the past several times to contribute to docs and never got even a response, so I am not going to bother again there.

So essentially with Suspense I should never block rendering children (or anything), right? Throwing the promise takes care of not continuing further until resolved. That's a huge mindset change we all need to accommodate to I suppose.

The second point of confusion for me was that all demo examples in docs do rely on a global variable. It's kinda suspicious that React would recommend something like that. I think it should be made clear that Context can be still accessed even when suspending. That's hugely important for testing later as global variables are a pain to deal with in tests.

Thanks a lot for taking the time with an explanation. It makes much more sense now.

**Comment by FredyC** [comment]
One thing still bothers me, though. These examples were rather contrived. But in a real app, I have a component that needs to set up Provider and for that, a value should be kept in `useState` as it cannot be lost.

```jsx
export const RootProvider = ({ children }) => {
  const [root, setRoot] = React.useState<TRootModel>()

  React.useEffect(() => {
    const createRoot = RootModel.create()
    createRoot.init().then(() => {
      setRoot(createRoot)
    })
  }, [])

  // I would want to suspend here until the root is ready, but I don't think I can

  return <context.Provider value={root}>{children}</context.Provider>
```

I suppose I have to move this whole thing somewhere outside the component. Set up some sort of "super global Context".

**Comment by Eddie-CooRo** [comment]
I'm glad I was able to explain the problems correctly 😅
But I think there are still several minor issues in your examples.
First of all, your SuspendMe component wouldn't work, because after the thrown promise resolves, React doesn't retry rendering the whole subtree from the <React.Suspense> component to the component which suspended. But it will retry only the SuspendMe component, and if it relies solely on the existence of the `promise` prop, it wouldn't be able to determine whether it should render its children or not and the SuspendMe component will stay suspended forever and the RootProvider never gets the chance to not pass the promise to it. You can check it for yourself if you want.
But something like this would work:

```js
const SuspendMe = ({ promiseRef, children }) => {
  if (promiseRef.current) {
    throw promiseRef.current
  }
  return children
}

const RootProvider = ({ children }) => {
  const [root, setRoot] = React.useState<TRootModel>(() => {
    return RootModel.create()
  })
  const initPromise = React.useRef()
  
  React.useEffect(() => {
    initPromise.current = root.init().then(() => {
      initPromise.current = undefined
    })
  }, [root])
  
  return (
    <SuspendMe promiseRef={initPromise}>
      <context.Provider value={root}>
        {children}
      </context.Provider>
    </SuspendMe>
  )
}
```

So by passing the ref directly, you will be able to query the latest value of the current field, without the need for the RootProvider component to re-render.
But there is still one more problem in this example. Because you are setting the `initPromise.current` in the useEffect, it will be `undefined` in the first render pass. So the SuspendMe component will return its children without suspending the first time it renders, and then after the React executing the `passive effects,` the initPromise ref will get its correct value, and the SuspendMe component will suspend correctly. But the problem is that if any of the children of the SuspendMe component needs the promise to resolve before getting rendered, it will break in the first render pass.
So I will favor something like this over your implementation of the SuspendMe component:

```js
const useSuspendable = (refInitializer, deps) => {
  const memoizedRefInitializer = React.useCallback(refInitializer, deps);
  const previousRefInitializer = React.usePrev(memoizedRefInitializer);
  const ref = React.useRef(null);
  if(memoizedRefInitializer !== previousRefInitializer) {
    ref.current = memoizedRefInitializer();
    ref.current.__IS_SUSPENDABLE__ = true;
  }
  return ref;
}

const SuspendMe = ({ suspendable, children }) => {
  if (suspendable.current && suspendable.current.__IS_SUSPENDABLE__) {
    throw suspendable.current.then((result) => {
      suspendable.current = {
        __IS_SUSPENDABLE_RESULT__ = true,
        result
      }
    });
  } else if(suspendable.current.__IS_SUSPENDABLE_RESULT__) {
    return children(result);
  } else {
    throw new Error("The suspendable prop passed to the SuspendMe component is not of type Suspendable");
  }
}

const RootProvider = ({ children }) => {
  const [root, setRoot] = React.useState<TRootModel>(() => {
    return RootModel.create()
  })
  const initPromise = React.useSuspendable(() => {
    return root.init();
  }, [root]);
  
  return (
    <SuspendMe suspendable={initPromise}>
      {result => <context.Provider value={root}>
        {children}
      </context.Provider>}
    </SuspendMe>
  )
}
```

It's just a quick mockup, and I haven't tested it yet.
Also, it seems a bit tricky for me. So I would love to hear the opinion of some of the core team members about this. Maybe @sebmarkbage or @gaearon, If they have time for it.

But about the other thing you said:
>	I suppose I have to move this whole thing somewhere outside the component? Set up some sort of "super global Context."`

There is no problem with having `state` in a suspended component by itself. The problem is when the component relies on the state value to determine whether to throw a promise or not. Like when you are storing a boolean in the state, and trying to set it's value to false when the request finishes so you know that in the next render pass you shouldn't throw the promise again. This wouldn't work.
But for example, in the `SuspendMe` component with render props, you can easily pass the result to the `ContextProvider` as it's value.
