### ISSUE TITLE
Suspense: Ability to leave existing children mounted after successfully rendering once

### ISSUE THREAD

**Issue by JonDum** [facebook/react#17231]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently Suspense will completely replace children when a promise is thrown. This leads to ugly UX when `fallback` is flashed on every prop change.

Demo: https://codesandbox.io/s/jovial-dew-x8u5p

Notice how many flashes of `fallback` you get by typing and deleting text into the input. This problem is exacerbated further by no delayMs anymore.

**What is the proposed behavior?**

After successfully rendering without catching any promises or errors, provide the previous children to `fallback` so the children can remain mounted but the developer has control of how to show a loading indicator. For example, say you had a component that would mask over the children and show a loading spinner centered over them:

```
<Suspense fallback={(staleChildren) => <LoadingWrapper>{staleChildren}</LoadingWrapper>}>
  <Component id={id}/>
</Suspense>
```
Just having a reference to the previous successfully rendered children would be huge. Is this possible to do in userland? If not is this something that can be done in core?

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React@experimental

**Comment by Eddie-CooRo** [comment]
Why don't you use the `useDeferredValue` hook? I think it's designed specifically for these kinds of situations.
Demo: https://codesandbox.io/s/usedeferredvalue-issue-demo-f76r4
Also, it is not considered a good practice to throw the promise at the same time as firing the request anymore. Because it may cause waterfall in network requests.
You would probably want to take a look at the new concurrent mode docs [here](http://reactjs.org/concurrent).

**Comment by threepointone** [comment]
@Eddie-CooRo is right, that's what useDeferredValue is for. Closing this issue.

**Comment by JonDum** [comment]
@Eddie-CooRo Oh, that's brilliant! Thanks so much for the demo. That made it all "click" for me now! Great stuff.
