### ISSUE TITLE
DevTools component filter does not work with location

### ISSUE THREAD

**Issue by Shayan-To** [facebook/react#17248]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
In DevTools when a component filter is added with field set to `location` and regex set to `.*`, nothing is filtered out. (BTW, no documentation in this subject is available anywhere.)

**What is the expected behavior?**
At least some components be filtered out.
It would also be awesome if the `location` was shown somewhere for the selected component, so that users can know what kind of Regex they should put together.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React DevTools 4.2.0 on Firefox 69.0.3.

**Comment by bvaughn** [comment]
Location filter only works when the file location information is available to filter on:
https://github.com/facebook/react/blob/f4148b2561d468c292f184fb35b186efbc5dd758/packages/react-devtools-shared/src/backend/renderer.js#L674-L682

Otherwise that information is ignored, since any filter would effective hide *all* components.

This information gets added by a plugin like [`@babel/plugin-transform-react-jsx-source
`](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-source)

> It would also be awesome if the `location` was shown somewhere for the selected component, so that users can know what kind of Regex they should put together.

You can view this info in the console, actually:
https://twitter.com/brian_d_vaughn/status/1167100034338426880

Hope this info helps!
