### ISSUE TITLE
event handler attached on button triggered later than the one attached on document?

### ISSUE THREAD

**Issue by kinglywork** [facebook/react#17300]
I create a demo like this:
render a button and add onclick event handler on it, then add click event handler on document, when I click the button, click handler added on document triggered before the one added on toggle button.

I thought the expected behaviour is trigger click handler on toggle button first since all the event handler is on bubble propagation stage, not in capture stage.

here is the demo code: https://codepen.io/royliu/pen/WNNJOQd?editors=0010

React version: 16.10.2
Browse: Chrome 78
OS: MacOS

**Comment by eps1lon** [comment]
The one you attach on the document fires during capture phase (since the third argument is true) while the react event handlers fire during bubble phase by default.

If you want to handle click events on the document after you handled them on a specific element use `addEventListener(event, fn)` or `addEventListener(event, fn, false)`

**Comment by threepointone** [comment]
Exactly as @eps1lon said.
