### ISSUE TITLE
[Lib author question] using batched updates with support for different renderers (react-dom, react-native)

### ISSUE THREAD

**Issue by pie6k** [facebook/react#17406]
Right now there is different way of batching updates in `react-dom` (`ReactDOM.unstable_batchedUpdates(() => { ... })` and eg. `react-native`.

Let's say I'm creating a library that can be used both on the web and in react-native. Let's say, I want to take advantage of using batched updates on both platforms.

However, implementing batched updates works differently on each platform.

On DOM it's `ReactDOM.unstable_batchedUpdates(() => { ... })`

On RN it's a bit hacky but seems to work. I've implemented it like

```tsx
function getBatchedUpdateFunction() {
  try {
    const renderer = __DEV__
      ? require('react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev')
      : require('react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod');

    if (!renderer) {
      return null;
    }

    if (!renderer.unstable_batchedUpdates) {
      return null;
    }

    return renderer.unstable_batchedUpdates;
  } catch (error) {
    return null;
  }
}

export function batchedUpdates(callback: () => void) {
  const batchedUpdatesFunction = getBatchedUpdateFunction();

  if (!batchedUpdatesFunction) {
    // we're not able to call batch function. Let's fallback to call callback normally without batching
    callback();
    return;
  }

  batchedUpdatesFunction(() => {
    callback();
  });
}
```

I also have to check in runtime, what platform is used to call proper batch function type

Is there any way to make it cleaner if I want to batch on any react-powered platform?

I assume there might be many 'env-agnostic', react based libs that use batching eg redux, mobx. Each of those should be usable on each react-based platform

**Comment by pie6k** [comment]
I think it's still important use-case issue

**Comment by eps1lon** [comment]
@pie6k react-redux supports react-dom and react-native while using batched updates. You might want to look at how they solved this. I don't think this should be solved in the core since not every renderer lives here.

**Comment by markerikson** [comment]
Yeah, we had to implement a somewhat hacky approach.

In our codebase, we have [a folder with both `reactBatchedUpdates.js` and `reactBatchedUpdates.native.js`](https://github.com/reduxjs/react-redux/tree/e64b6108a727a18a8c9ed097ba9018ebe08e8fbc/src/utils).  Each just re-exports `unstable_batchedUpdates` from the appropriate renderer.  We assume that React Native will pick up the second file due to the `.native.js` extension.

It works, but it results in some weird package behavior:

- We _do_ depend on either ReactDOM or React Native at runtime, but we can't declare either of them as an actual dependency (or, really, even a peer dependency)
- We have to dependency-inject the right version of `batchedUpdates` into a central file
- In order to support all other renderers, we have a separate `"react-redux/alternate-renderers"` entry point file that has all the same exports, but does _not_ try to initialize importing `batchedUpdates`.

I wish there were a better option, but it's the best we could come up with.
