### ISSUE TITLE
useEffect executes return block before the main one

### ISSUE THREAD

**Issue by agonqorolli** [facebook/react#17434]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When there is a time consuming activity in main block of useEffect, return block gets executed first, then the main block. This is an anti-pattern.

**Steps to reproduce.**
https://codesandbox.io/s/react-hooks-playground-ych47

**What is the expected behavior?**
In useEffect hook, return block should always be executed last, and nothing after it, right? It doesn't make sense to do a cleanup before actually doing some activity first.

**Comment by eps1lon** [comment]
Couple of issues:
1. You immediately invoke `alert` at the return statement. You probably meant to return `() => alert('return')`
2. React does not know when an async call in `useEffect` finished. You would need to track this yourself e.g.
  ```js
  useEffect(() => {
    let current = true;
    setTimeout(() => {
      if (current) alert("Executed main block");
    }, 2000);

    return () => {
      current = false;
      alert("Executed retrun block")
    };
  }, [trigger]);
  ```

**Comment by markjaquith** [comment]
@agonqorolli What you did in the main block WAS executed first. i.e. `setTimeout()` was called. And you didn't **return** a function in the "return block"... you **invoked** a function, and returned its result.

This is all expected behavior. This is an old-but-good read on `setTimeout()`: https://johnresig.com/blog/how-javascript-timers-work/
