### ISSUE TITLE
Popups opened from `onClick` handlers get blocked by browsers

### ISSUE THREAD

**Issue by fiatjaf** [facebook/react#1745]
Which doesn't happen when I use `addEventListener` to bind `'click'` to a function that opens a popup.

**Comment by rricard** [comment]
Hi, just to say I still have the issue, I can find a way around it using listeners and the react lifecycle though. I'll try to get a snippet there.

**Comment by rricard** [comment]
Never mind I had the popup launched from an async action 😉

**Comment by DannyLeiton** [comment]
@rricard: How did you do it man?

**Comment by rricard** [comment]
@DannyLeiton: Just get a breakpoint where you want to start the popup. Then, observe the stack: if the stack goes back to your original click, then you should fill a bug report because this is not normal! However, in my case (and probably in your case) my stack was stopping at the return of an async action (graphql query with apollo in my case). What I finally did is find a way to prefetch the query before showing the clickable button so the button could hit the apollo cache and get the result in the same stack...

**Comment by rricard** [comment]
In a more concise manner: avoid networks (or other async) calls between the click event and the popup creation!

**Comment by franciscop-invast** [comment]
I was getting the url from the back-end, which made the new tab opening
 being blocked. Switching the source of the URL to the front-end or doing a `window.location.href = url;` (open in same window) seems to do the trick.

**Comment by dancherb** [comment]
in my case I want to download a file (by opening the URL in a new tab) after requesting the URL from the back-end, so it's async and same window wouldn't work - any ideas?

**Comment by sompylasar** [comment]
> in my case I want to download a file (by opening the URL in a new tab) after requesting the URL from the back-end, so it's async and same window wouldn't work - any ideas? 

@dancherb Make a backend endpoint that HTTP-redirects (if URL is quick to get) or JS-redirects (print the JS at the end of the body, flush some spinner from the server immediately so that the "downloading" page doesn't feel empty) to the correct URL after the URL is ready. Open that endpoint in a new tab immediately, let it hang there.

**Comment by azzadrood** [comment]
If this is still relevant, but i have find a method to open pop-up with async api call.

You can try to initiate the windows before making the async call and then set the location with the data you get from server response


```
  const onMouseClick = async () => {
    var windowReference = window.open()
    try {
      const apiResponse = await getFacturaPdfByNrFac(nrFactura.replace("/", ""))
      if (apiResponse.type) {
        var url = createObjectURL(apiResponse)
        windowReference.location = url
      }
    } catch (error) {
      console.error(error)
    }
  }

export function createObjectURL(file) {
  if (window.webkitURL) {
    return window.webkitURL.createObjectURL(file)
  } else if (window.URL && window.URL.createObjectURL) {
    return window.URL.createObjectURL(file)
  } else {
    return null
  }
}
```
