### ISSUE TITLE
Is there any reason why React.version is still stuck in 16.8.6 ?

### ISSUE THREAD

**Issue by le-du6** [facebook/react#17467]
In 16.12.0 and in some previous versions, React.version still return 16.8.6

**Comment by Sonic12040** [comment]
It looks like, because of rate limiting, it prefers to use session storage when available, so perhaps the session has persisted?
See: https://github.com/facebook/react/blob/master/fixtures/dom/src/tags.js

Manually calling the API in that file did return 16.12.0 as the latest tag.

Testing with a fresh run of create-react-app also returned 16.12.0 for React.version.

**Comment by le-du6** [comment]
Indeed, I see and I understand.
Finally, fully rebuild the App did the job.
Merci beaucoup.
