### ISSUE TITLE
[useReducer] Inconsistent behavior of `dispatch` on first call and laters

### ISSUE THREAD

**Issue by liyuanqiu** [facebook/react#17460]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug

**What is the current behavior?**
```javascript
function reducer(state, action) {
  console.log("run reducer");
  switch (action.type) {
    case "INCREMENT": {
      return state + 1;
    }
    default:
      return state;
  }
}

function increase() {
  dispatch({
    type: "INCREMENT"
  });
  console.log("after dispatch");
}
```
**The output of the first time calling `increase`:**
```
run reducer
after dispatch
```
**The output of the later times calling `increase`:**
```
after dispatch
run reducer
```

https://codesandbox.io/s/infallible-bassi-r0k3w
(open this link of reproduction, and see the console logs)
---

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
The sequence of output should keep same.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
^16.8.0

**Comment by KPowroznik** [comment]
Hey, it probably depends on console.log behavior.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jmlavoier** [comment]
Why are you trying to console after dispatching an action? It smells that you're trying to do something wrong. Using redux you must follow the sequence of the control flow, taking into consideration the javascript's event looping. So, never add any logic after dispatching some action.

It's the flow expected to be implemented using redux. 
```
call action -> dispatch -> change state (reducer returns new state) -> some logic after all (console.log). 
```

You're creating a new branch to the control flow like this.
```
call action -> dispatch -> change state (reducer returns new state) -> some logic after all . 
            \-> console.log
```
If you're using React with Redux in the right way, it's expected a rerendering after state changing. So you can do something after that.  Or if you're trying to handle some side-effects, I encourage you to take a look at redux-saga ou redux-thunk, those are libraries that help manage side-effects on your application.

**Comment by aweary** [comment]
You shouldn't rely on the `reducer` being called synchronously or asynchronously. That is an implementation detail and your code shouldn't rely on the timing at all.

The reason that it's different here is because `useReducer` has an optimization where it can attempt to eagerly bailout of an update if React knows that it is the only update in the queue. This heuristic works for the first time you call `dispatch`, so React calls `reducer` earlier than usual, but it doesn't work for subsequent updates.

I believe the bailout is expected here, but maybe @acdlite or @gaearon can confirm. In either case, the ordering and timing of when `reducer` gets called is guaranteed so this is generally expected behavior.
