### ISSUE TITLE
PWA react prodution build?

### ISSUE THREAD

**Issue by IDONTSUDO** [facebook/react#17491]
My application is located at.
https://crm-svarom.web.app/

My React application does not deploy to me, the thing is that I use Service worker.js and PWA functionality.

It works fine on the local host. But after writing npm, building and deploying on the localhost, this also does not work.

I looked at similar issues on SrackOwerflou. And it was said that the creators of React have already solved this problem for me. But this does not work, I do not understand what is the matter.

console logs

![снимок_9](https://user-images.githubusercontent.com/44754773/69876200-0e432380-12d0-11ea-9275-68e2d866e088.png)

and file system
![снимок_8](https://user-images.githubusercontent.com/44754773/69876238-2450e400-12d0-11ea-9442-d345718314bc.png)
sorry for my bad english i'm from Russia(

**Comment by pavinthan** [comment]
Hi @IDONTSUDO seems have issue with your build tool, normaly `PUBLIC_URL` replaced with your envirement configration when your build for production if your use [create-react-app](https://github.com/facebook/create-react-app) It will do all required things for your you may need to get support from create-react-app because It's related to https://github.com/facebook/create-react-app if you are using `create-react-app`

You can get support from https://reactjs.org/community/support.html

**Comment by IDONTSUDO** [comment]
thx!
