### ISSUE TITLE
question about this.state and this.setState

### ISSUE THREAD

**Issue by FlankMiao** [facebook/react#17498]
Here is my question:
There is a multiselect child component, the  value is maintained in its parent component [this.state.values] like this:

Parent {
 state={
  values:[]
 }
  render(){
    return(
     Multiselect value={this.state.values}
    )
  }
}

in the multiselect 's [onChange] function I control the multiselect value in two ways and two different render results:

First:
  onChange= ()=>{
    this.setState({ values:this.handleValue(this.state.values)});
  }

  handleValues = (values)=>{
    //here to add or splice, eg:
    values.push('treeNode1');
    return values
  }

  when I print this.state.values in the render() function, the 'treeNode1' is added, however ths multiselect component's 'treeNode1' option wasn,t selected;

but if change the onChange() function like this, it works right:
  onChange= ()=>{
    this.setState({ values:this.handleValue(Object.assign([],this.state.values))});
  }

I pass the copy of the [this.state.values] rather than [this.state.values].

I,m confused.

I know that we can,t change varibles in the state directly, however in the first way, [this.state.values] in the render() function is added by 'treeNode1', it looks correctly .

Here is my guess :  React maintains a real state.  When React renders it can get the 'real' state of [this.state.values] which works actually rather than the [this.state.values] that I changed directly in the onChange function by adding 'treeNode1'. The state value[this.state.values] printed in the render() function looks correct ,because the directly change in the handleValues () function rather than changed by this.setState().

I wonder how and why this happens and is my guess right? :)

**Comment by bvaughn** [comment]
Partial code examples aren't very useful. In the future, I'd suggest sharing a full example somewhere like Code Sandbox.

In the first example you show, you are mutating the array in state (`.push()` mutates the array) which we recommend you never do. In the second example, you are creating a new Array and updating state to hold it. I'm guessing that your component perhaps extends `PureComponent`? In which case, the first example would not trigger a re-render, since the Array you're storing in state has not changed.

The docs cover this specific scenario: https://reactjs.org/docs/optimizing-performance.html#examples

Probably worth reading through this section! Hope this helped :)

**Comment by FlankMiao** [comment]
@bvaughn Thanks. Here is the code:

[confused.zip](https://github.com/facebook/react/files/3911853/confused.zip)

as 
![confused](https://user-images.githubusercontent.com/19262116/69969878-36dd4e80-1558-11ea-8396-6eb38b3175e4.png)

I learnd that we should mutate the state directly, but  I have a question:
in way1, I mutate the state: [values],  when I print it in the render() function:
![print](https://user-images.githubusercontent.com/19262116/69970505-57f26f00-1559-11ea-83af-9cf5ebca2a78.png), it seems to be right as way2.  
You said "the first example would not trigger a re-render, since the Array you're storing in state has not changed.". So is the react hold the state that we can,t see which is the right state value, even if it seems changed in the console.log() function?

**Comment by bvaughn** [comment]
Ah, let me revise my previous guess- the thing that's extends `PureComponent` is perhaps `TreeSelect`. In your first example, you are _modifying the previous array_ (by pushing values directly). That means when you re-render, you're passing _the same array_ to `TreeSelect`. It may think it's okay not to re-render, since nothing has changed.

This is one of the reasons I suggest you avoid mutating arrays and objects, and instead clone them on update (like your second approach above).

**Comment by FlankMiao** [comment]
@bvaughn thanks :)
