### ISSUE TITLE
variable declaration is not working in eval

### ISSUE THREAD

**Issue by mayank-kansal15** [facebook/react#17598]
eval(var a = 10); console.log(b)
this works in normal javascript code and variable is declared in outer scope.

But when I do the same in the render function, it doesn't work.

Some react Guru please help.

**Comment by embeddedt** [comment]
"Doesn't work" is a very vague description of what the problem is.

I think this is not a React issue, but rather simply the way modern JavaScript works when operating in the mode React uses. If you want to be declaring variables in outer scope and accessing them in React functions, you should declare them as properties of the window object (`window.a = 3;`). That way the `eval` statement and your code are both accessing the same object.

`eval` is evil in 2019, though :wink:; there are probably much cleaner and safer ways of structuring your code.

**Comment by aweary** [comment]
This doesn't really have anything to do with React. I also recommend avoiding `eval` at all costs.

**Comment by mayank-kansal15** [comment]
@embeddedt Thank you for your reply. I am using windows.x solution for time being. I am aware that eval is evil but there are cases where you can't avoid eval like creating variables at run time which I am facing issue in. There is another IIFE approach to this but it will create variables in function scope.
