### ISSUE TITLE
Why svg can't display , but the svg is OK when opened in chrome alone!

### ISSUE THREAD

**Issue by i-fuyun** [facebook/react#17615]
"react": "16.12.0",
   "react-dom": "16.12.0",
   "react-inlinesvg": "1.2.0",
   "react-scripts": "3.0.1",
   "react-svg": "11.0.3"

Why svg can't display in React?
https://codesandbox.io/s/distracted-galois-jlwjp?fontsize=14&hidenavigation=1&theme=dark

But, the svg is OK when opened in chrome alone.
http://bmw.jingge.com/fault-diagnosis-WebGL/static/media/multimeter.svg
![image](https://user-images.githubusercontent.com/5111701/70876581-0fc15b00-1ff5-11ea-8e5e-4f3ba05676cd.png)

**Comment by bvaughn** [comment]
The Code Sandbox you linked has a runtime error:
> TypeError: Cannot set property 'svgDiv' of undefined

Looks like that's because you have a lot of `this` references in a function component.

I'm not sure what your sandbox is trying to do, but in its current form-it looks like you've got some mistakes and errors in your code 😄 I'm going to close this. If you can share another Code Sandbox that addresses the errors I mentioned above, we can take another look and possibly reopen.
