### ISSUE TITLE
React DevTools might retain references to unmounted DOM elements (and their Fibers)

### ISSUE THREAD

**Issue by bgirard** [facebook/react#17624]
![Screenshot 2019-12-16 10 51 05](https://user-images.githubusercontent.com/793565/70934095-fd91ed80-1ff1-11ea-93b5-746e816585ec.png)
There's seems to be circumstances where unmounted DOM/Fibers are kept alive by React DevTools. They're kept alive in `primaryFibers`:
https://github.com/facebook/react/blob/34527063083195558f98108cde10b5d6ad0d6865/packages/react-devtools-shared/src/backend/renderer.js#L772

It seems like a WeakSet would be appropriate and would remove the leak. Otherwise we'd need to understand why recordUnmount isn't called.

CC @bvaughn

**Comment by bvaughn** [comment]
I'm not necessarily convinced that the above screenshot is showing what this issue suggests. I believe it's possible that this indicates that component rendered `null` where it previously rendered a DOM element, and the "alternate" Fiber still has a reference to the (now unmounted) DOM element. In this case both DevTools and React itself would have references to both Fibers as well as the unmounted DOM element.

**Comment by bvaughn** [comment]
Quick update about this issue and PR #17666

The thing that caused the above temporarily "leak" is the alternate pointer- which will be cleared during the next render. That being said, the reason the temporary "leak" retains so much (the whole subtree) is because we weren't nulling out the `stateNode` field. PR #17666 changes this behavior so that we now *will* null that field. This should make our memory snapshot comparisons less noisy in the future.

**Comment by piecyk** [comment]
Looks like there is a memory leak in DevTools, was noticed in https://github.com/tannerlinsley/react-virtual/issues/196

Created small demo, it can be observer while scrolling a list, memory increase because of detached fiber and dom elements 

https://github.com/piecyk/react-devtools-memory-leak-17092021

It happens also in production build, noticed that elements aren't removed from `fiberToIDMap` after they are unmounted, something fishy there 🤔

**Comment by bvaughn** [comment]
Thanks for sharing a repro, @piecyk. I'll take a look.

**Comment by bvaughn** [comment]
It does look like DevTools isn't recording unmounts for list-item Fibers in this repro, which causes it to retain them after they've been unmounted.

I thinks a _React bug_ though. (React is supposed to explicitly notify DevTools of unmounts and it doesn't seem to be.)

I wonder what it is about `react-virtual` that triggers this behavior that doesn't repro with a library like `react-window`.

**Comment by bvaughn** [comment]
Another interesting thing I'm seeing is that _sometimes list items do get unmounted_, but not often. I wonder what's different about the cases that do vs the ones that don't.

**Comment by piecyk** [comment]
Also as side note, i would expect to see similar behaviour in react-window, as in windowing nature there is lot of mounting/unmounting, only difference to react-virtual is, that it's hook based and react-window on classes.

**Comment by bvaughn** [comment]
This fix will go out with the next DevTools release.

**Comment by piecyk** [comment]
Thanks @bvaughn 👍
