### ISSUE TITLE
React Developer Tools not showing correct components

### ISSUE THREAD

**Issue by Borumer** [facebook/react#17683]
**Do you want to request a *feature* or report a *bug*?**
Report a Bug

**What is the current behavior?**
The React Developer Tools, when I deploy a React App to GitHub Pages, do not show the React components. The Components tab instead displays
![image](https://user-images.githubusercontent.com/31084854/71300980-0f63ef80-2368-11ea-9fbe-63cddea97bc0.png)

https://github.com/facebook/react/issues/16840 told me to use that extension but that doesn't work

**Update:** 
I uninstalled and reinstalled React and now I get a blank screen. Additionally, when run on localhost (development build) it shows the right components. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
The React Developer Tools should show the components. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
on Google Chrome, React v4.2.1

**Comment by bvaughn** [comment]
> The React Developer Tools, when I deploy a React App to GitHub Pages, do not show the React components.

I think this is a misunderstanding :smile: From that screenshot, it looks like React DevTools **is** showing your components. The component names have just been **minified**.

This is because the "name" of your component is just the name of the function. Most JavaScript projects are configured to minify the names of functions and variables as part of the production build process- so that the resulting code is smaller and downloads faster. This means that a component named `MyComponent` might get be shortened to something like `a` or `t`.

For example- assuming you're using create-react-app (just a guess) it's [configured](https://github.com/facebook/create-react-app/blob/3f2037bb2ab33f7eebe95934625280f35d2dd5aa/packages/react-scripts/config/webpack.config.js#L244-L246) to preserve display names only in development mode.

**Comment by Borumer** [comment]
How do I undo this configuration?

**Comment by bvaughn** [comment]
Can't say, since I don't know anything about your app. I would recommend against doing this in production mode though. It's generally a good idea to minify your JavaScript :smile:

**Comment by iraqwarvet31** [comment]
Looks like your webpack is in production mode. You can fix this by changing your webpack.config.js,

from:
`mode: 'production',`
to:
`mode: 'development',`

**Comment by BentonFraizer** [comment]
Hello everyone. 
In my case (using webpack 5.75.0) I just deleted the row `devtool: 'source-map'`
from configudation file `webpack.config.js`
