### ISSUE TITLE
componentDidUpdate inexplicably not firing after render in a single component

### ISSUE THREAD

**Issue by Slapbox** [facebook/react#17691]
**Do you want to request a *feature* or report a *bug*?**

**Bug**

**What is the current behavior?**

`componentDidUpdate` not firing after `render` in one lone component. No idea how to recreate in a sandbox.

**What is the expected behavior?**

`componentDidUpdate` fires after _every_ `render`

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

`React@16.11` & `React@16.12` affected in `Electron@6`

----

I'm tracking when `componentDidUpdate` and `render` are firing with log statements. 

**The log statements in `componentDidUpdate` do not fire after `render`. I have used breakpoints to confirm this isn't a timing issue.** 

My code (stripped down) is below. This is the output of the logging. Sometimes I'll get `componentDidUpdate` to fire, but inconsistently and it's never the final thing, a `RENDER` always shows up in my logs last, never `UPDATE`.

![image](https://user-images.githubusercontent.com/6835891/71326857-887d5700-24ce-11ea-9862-ac3b28010f2a.png)

```js
class MyWrapper extends React.PureComponent {
  render() {
  const { buttonDefinitions } = this.props;
    return (
      <InfoProvider
        render={infoProps => {
          return (
            <MyMenu
              {...{ buttonDefinitions, infoProps }}
            />
          );
        }}
      />
    );
  }
}
```

```js
class MyMenu extends React.Component {
  componentDidUpdate() {
    log.warn('UPDATE');
  }

  render() {
    log.warn('RENDER');
    const { buttonDefinitions } = this.props;
    return (
      <MenuWrapper>
        {buttonDefinitions.map(buttonDef => (
          <MyButton {...buttonDef} />
        ))}
      </MenuWrapper>
    );
  }
}
```

**Comment by bvaughn** [comment]
> **What is the expected behavior?**
> `componentDidUpdate` fires after *every* `render`

This expectation sounds flawed. `render` might be called multiple times before `componentDidUpdate` is called (if it's even called). The reason for this has to deal with how React separates work.

Conceptually, React does work in two phases:
* The "render" phase determines what changes need to be made to e.g. the DOM. During this phase, React calls `render` and then compares the result to the previous render.
* The "commit" phase is when React applies any changes. (In the case of React DOM, this is when React inserts, updates, and removes DOM nodes.) React also calls lifecycles like `componentDidMount` and `componentDidUpdate` during this phase.

React may throw away render work for a variety of reasons (e.g. it has something higher priority to work on, or an error occurred during render). In other words, if you're keeping count for "render" and "commit" phases- it's not expected that the counts will always be equal.

If you are confident you've identified a *bug*, I have to ask that you provide a repro case so that myself or someone else can take a look. Repro cases are very important with bugs. Often times, putting together a repro case reveals the cause of the bug is in application code.

> No idea how to recreate in a sandbox.

I suggest starting with an app that triggers the problem, then start removing things until you've trimmed it down to the smallest amount of code that still shows the unexpected behavior :smile: Even though this can take a bit of time, it's probably less effort than it would be to speculate about what might be going on in an unknown codebase.

**Comment by Slapbox** [comment]
Hey @bvaughn thanks a lot for your response. I am definitely not confident that this is a bug because React is so heavily used and tested that what are the odds? But I cannot find any other explanation.

I scoured the docs and the issue tracker for exactly when users should expect `componentDidUpdate` to be called. I could not find any answer, but I did find several threads that ended with the uncontested assumption that `componentDidUpdate` will fire even if the DOM has not been modified. Is this the case? 

**If `render` is called one or more times, `componentDidUpdate` should call at least once, right?**

 In any event, the DOM _is_ being modified in this case, adding to my confusion.

The profound weirdness of this issue has me hesitant to dive straight into trying to create a repro since I haven't the faintest clue why this is the only component out of several hundred that I'm seeing this behavior with. Originally we were doing the work in the `render` instead of `componentDidUpdate` (conditional window resize), which worked great in `development`, but React silently fails to mount the root element, in `production`,

**Comment by bvaughn** [comment]
> If render is called one or more times, componentDidUpdate should call at least once, right?

Not necessarily true, although if the DOM is being modified then the commit phase has run and it should definitely be called in that case.

> The profound weirdness of this issue has me hesitant to dive straight into trying to create a repro since I haven't the faintest clue why this is the only component out of several hundred that I'm seeing this behavior with.

I'd say this is a necessary next step in order for someone to actually look into the issue 🙂 It's probably going to be easier for you to start stripping things out of your app than it would be for us to speculate about all of the things that could be inside an app we've never seen.

**Comment by Slapbox** [comment]
Thanks for your help with this.

It turns out the component is re-mounting far more often than it's updating, which I didn't expect and which I was too dumb to rule out before opening this issue.

**Comment by bvaughn** [comment]
Ah, interesting! :smile: Thanks for the follow up. Glad you got it sorted out.
