### ISSUE TITLE
why not the useMemo/useCallback  Multiple Memory

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#17717]
```jsx
  const [value, valueSetState] = useState(0)
  const obj ={}
  const valueMemo = useMemo(() => obj, [value])
  if (!window.array) window.array = []
  window.array.push(valueMemo)
  return (
    <>
      <button onClick={() => valueSetState(1)}>A</button>
      <button onClick={() => valueSetState(2)}>B</button>
      <button onClick={() => valueSetState(1)}>C</button>
    </>
  )
function someExpensive(arg){
//do some expensive with arg
return {}
}
```
after we click A,B,C button
i think window.array[1] === window.array[3] is true, but now is false

**Comment by bvaughn** [comment]
I don't think you've provided enough info for us to answer this question.
1. What is `someExpensive` and what calls it?
2. Why would you expect `window.array[3]` to have true in it? Your example only shows you pushing an empty object. (Pushing to a global array during render is a [side effect](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) and you should probably not do it except for debugging by the way.)

I think this type of question should be asked somewhere like [Stack Overflow](https://stackoverflow.com/questions/tagged/reactjs) or [Reddit](https://www.reddit.com/r/reactjs) rather than the React GitHub repo. It's important to provide complete code when you ask the question too, so people can run your code and look for things you may have missed. For this reason, I suggest using [Code Sandbox](https://codesandbox.io/) to create a runnable example that you can link to. :smile:

**Comment by vkurchatkin** [comment]
@zhangenming `useMemo` caches only the most recent value, not all observed values

**Comment by zhangenming** [comment]
> @zhangenming `useMemo` caches only the most recent value, not all observed values

thanks, I know it, 
i just want to know WHY it just caches only the most recent value, BUT not all observed values
thanks

**Comment by zhangenming** [comment]
> I don't think you've provided enough info for us to answer this question.
> 
> 1. What is `someExpensive` and what calls it?
> 2. Why would you expect `window.array[3]` to have true in it? Your example only shows you pushing an empty object. (Pushing to a global array during render is a [side effect](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) and you should probably not do it except for debugging by the way.)
> 
> I think this type of question should be asked somewhere like [Stack Overflow](https://stackoverflow.com/questions/tagged/reactjs) or [Reddit](https://www.reddit.com/r/reactjs) rather than the React GitHub repo. It's important to provide complete code when you ask the question too, so people can run your code and look for things you may have missed. For this reason, I suggest using [Code Sandbox](https://codesandbox.io/) to create a runnable example that you can link to. 😄
> 
> I'm going to close this issue since it's not actionable. If you respond with more info I can take another look, but I think it's probably better to ask one of the places I mentioned above 😄 Cheers!


**SOOOOORRY** 

https://codesandbox.io/s/determined-villani-8iu10

1. someExpensive just a useless function that i forget to delete
2. yes, i use window.array just want to debug

3. Tell me about my point of view:
when we click all the button after,
window.array[1] is value that provide when we click button A
window.array[3] is value that provide when we click button C
i think this two value should be same, because it depend on same state value
so i want to know**i just want to know WHY it just caches only the most recent value, BUT not all observed values**(now just return a simple object {value}, but if it was create by a someExpensive function?)
bad english

**Comment by bvaughn** [comment]
>Tell me about my point of view:
when we click all the button after,
window.array[1] is value that provide when we click button A
window.array[4] is value that provide when we click button C
i think this two value should be same, because it depend on same state value

This is not how `useMemo` works. It does not maintain a cache of input-value-to-output-value like some memoization libraries do. It only caches the *most recent* value. This is a design choice to minimize the memory impact of `useMemo` hooks usage.

Hope this helps clear up remaining uncertainty.

**Comment by zhangenming** [comment]
> > Tell me about my point of view:
> > when we click all the button after,
> > window.array[1] is value that provide when we click button A
> > window.array[4] is value that provide when we click button C
> > i think this two value should be same, because it depend on same state value
> 
> This is not how `useMemo` works. It does not maintain a cache of input-value-to-output-value like some memoization libraries do. It only caches the _most recent_ value. This is a design choice to minimize the memory impact of `useMemo` hooks usage.
> 
> Hope this helps clear up remaining uncertainty.

so why not provide a another hook to let developer choise between minimize the memory or optimization of time?

**Comment by vkurchatkin** [comment]
> so why not provide a another hook to let developer choise between minimize the memory or optimization of time?

You can do it! But would be probably be too opinionated to be included in React itself. Something like this could work for you:

```
function useMyMemo(fn, deps) {
  const cacheRef = React.useRef();

  if (!cacheRef.current) {
      cacheRef.current = new MyCoolCache();
   }

  const cachedValue = cacheRef.current.get(deps);

  if (cachedValue !== undefined) {
    return cachedValue;
  }

 const value = fn();
 cacheRef.current.set(deps, value);
 return value;
}
```
