### ISSUE TITLE
Add colors to component's name ( in Component tree ) for visual feedback about type of Component or Node

### ISSUE THREAD

**Issue by AnilSonix** [facebook/react#17738]
**What is the current behavior?**

All the components name  in the Component tree are of the same color

**What is the expected behavior?**

It would be helpful if they have different colors indicating the type of Component (whether its native HTML node or Contexts or simple react component) I know we can filter it, but visual indication will be helpful too.

**Comment by bvaughn** [comment]
I don't think this would work, given the number of different types of components React has. Too many colors would just be visually distracting in my opinion. React DevTools follows the precedent set by the browser's built-in tools and uses a consistent color for all types of elements.

**Comment by bvaughn** [comment]
Thanks for sharing this suggestion! :smile:

As the primary designer for DevTools, I've thought a lot about the coloring and style of the Components tab. I don't think this particular suggested change would be feasible, given the number of different types of components React has. There are just too many- and so many colors would be visually distracting in my opinion.

In this case, React DevTools is following the precedent set by Chrome's built-in Elements panel (which uses a consistent color for all types of elements).

Because I don't have any plans at the current time to make this change, I'm going to close the issue. We may reopen and reevaluate it in the future though! :smile:
