### ISSUE TITLE
read props of element

### ISSUE THREAD

**Issue by maifeeulasad** [facebook/react#17756]
**Do you want to request a *feature* or report a *bug*?**

I want to request a **feature**

**What is the current behavior?**

[This](https://codesandbox.io/embed/competent-sunset-8xcvp?fontsize=14&hidenavigation=1&theme=dark) is the current behavior. 

**What is the expected behavior?**

Expected behavior is to access all it's attribute, using props or something.

![](https://i.stack.imgur.com/R9Ziy.png)

Like in the image instead of writing `active={this.state.navState==='expired'}` and `active={this.state.navState==='todo'}` or anything. I can directly write `active={this.state.navState===this.props.name}`
 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Environment:**
 - react Version ^16.12.0
 - OS: Win 10
 - Browser: Chrome
 - Browser Version  :79.0.3945.88 (Official Build) (64-bit)

As far as I know, NO

**Comment by bvaughn** [comment]
I don't know what this is asking. Can you provide a small code example of what you currently do and what you *want* to do instead, along with an explanation of why you can't do that? (What error happens when you try?)

**Comment by maifeeulasad** [comment]
@bvaughn Please checkout [this](https://codesandbox.io/embed/vibrant-grass-6bd7v?fontsize=14&hidenavigation=1&theme=dark) one.

Here for every nev.link component I'm using `active={this.state.click === "admin"}`  this. And for every line it's right side changes.  So is there more dynamic way to do this ?

Something like `active={this.state.click === this.props.name}`

**Comment by bvaughn** [comment]
~~I saw that link, but I still don't really understand what it is that you're asking for 😅~~

~~Are you asking for a change to `Nav.Link` to require less redundant props? This wouldn't be the right place to ask for that.~~

Oh. I think I realize what you're asking. I think you essentially want `this.state.click` to refer to the `App`'s `state.click` but `this.props.name` to refer to the `Nav.Link`'s `props.name`. In which case- no. It is not possible for `this` to refer to two different things.

**Comment by maifeeulasad** [comment]
Is there anyway to access those names...

Actually I'm looking for `document.getElementsByName("some_name")`'s alternative

**Comment by bvaughn** [comment]
I think what you're asking boils down to something that's not a React question, but a JavaScript question: Is there a way to access the same string value in two places without repeating it? Yeah, you could assign it to a variable. Alternately you could redesign the `Nav.Link` component to accept two props (e.g. `name` and `activeName`) and it it do it's own check internally.

I don't think there's anything React itself can, or should, do here though :smile: I think it just boils down to a matter of component design.

I'm going to close this issue, since I don't think it's actionable, but we can keep chatting.
