### ISSUE TITLE
 Warning: An update to SearchPage inside a test was not wrapped in act(...).

### ISSUE THREAD

**Issue by SarpongAbasimi** [facebook/react#17763]
Using Jest and Enzyme.

<img width="1025" alt="Screenshot 2020-01-02 at 17 10 58" src="https://user-images.githubusercontent.com/37377831/71716992-8096ae80-2e0e-11ea-9a2b-a39ac04ea53e.png">

The Bug is happening for this test.

![Screenshot 2020-01-03 at 09 52 39](https://user-images.githubusercontent.com/37377831/71717086-cfdcdf00-2e0e-11ea-8432-a4f770476e4c.png)

**Comment by SarpongAbasimi** [comment]
@threepointone @gaearon 
Please any input into why this is the case. Thank you.

**Comment by bvaughn** [comment]
@SarpongAbasimi Did you try wrapping the thing that causes the update (`form.simulate('submit')`) in `act` like the warning message says?

**Comment by SarpongAbasimi** [comment]
Yes, I tried, but that didn't work.

**Comment by bvaughn** [comment]
Share your test code so one of us can run it? Screenshots of code are of limited use :smile:

**Comment by GasimGasimzada** [comment]
When you use synchronous act function, because the API call is asynchronous, the submit handler is completed; however, that doesn't mean that the API call is finished within a single execution cycle. So, if you set state after the API response, it is going to be executed outside the `act` call. This is still the case when you mock your API calls because the function itself is asynchronous. I think you need to use asynchronous version of `act`:

```js
it(..., async() => {
  // mock implementation etc
  await act(async () => {
    form.simulate('submit');
  });
}
```

**Comment by SarpongAbasimi** [comment]
Thank you @GasimGasimzada you are a legend 👑.
And thanks for explaining it to me, really helpful.
