### ISSUE TITLE
Bug: Component state resets inconsistently with Suspense for data fetching

### ISSUE THREAD

**Issue by pupudu** [facebook/react#17762]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Here is the codesandbox example: https://codesandbox.io/s/blissful-wilbur-xz8dy

##### Background
In the sandbox, there are two main components; `<Parent />` and `<Child />`. `Parent` is rendered as a child of React.Suspense. `Child` is rendered as a child of `Parent`. `Parent` has a count variables coming from a useState hook.

There is a fake fetch function, which gets data from a `Map`. We pass the count as the key to the fetch call. If data is not found, it throws a promise which will set the data on the map after one second.

##### Issue
The `count` state gets reset to its initial state when we call the `fetch()` function from the `Parent` component. However, it preserves the last state if we call the `fetch()` only from the `Child` component.

This behaviour change can be observed by looking at the console.log. With the fetch call in the Parent component, it fires the fetch() call as many times until the same count is received twice. With the fetch call only in the Child component, it renders correctly the first time.

**What is the expected behavior?**
I suppose the behaviour of the `count` state should be consistent despite of from where we call the `fetch()` function. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.12, React-DOM 16.12

**Comment by bvaughn** [comment]
> state resets inconsistently

I assume this is referring to the fact that `count` may be different values if `Parent` renders more than once. _Initializing_ the `count` state to a random value is probably causing some confusion.

When an error is thrown, or when a component suspends, React may throw away the work-in-progress state. In the case of your sandbox, this means that the `count` state will likely get initialized to different values each time the component renders. (Typically state would be initialized to some known stable value *or* a property passed in from higher up- that would itself be stable- so this wouldn't be a problem.)

Combine that with the fact that you're using the random `count` to key your suspense data (the `fetch`) is causing your component to re-suspend unnecessarily- because the first thing that's fetched resolves, and then your component likely ends up asking for something *different* on the re-render. (This is why the number of times your component renders changes based on the random sequence.)

Looking at the Sandbox you linked, it also looks like your `fetch` function is not caching the in-flight promise, so if you call it twice with the same key in less than 1 second, you'll get _different_ promises (when you really should get the same).

Here is an updated, annotated Sandbox that hopefully helps clear things up a bit:
https://codesandbox.io/s/zen-cori-i7dof

I'll add that counting renders the way you are doing with `rerenderCount` looks like a misunderstanding. React is *expected* to render more than once in the example you've shown if only because of your throwing a `Promise` via `fetch`. It will render once, "suspend", and then render again when data finishes loading. (You were seeing more renders than that because of the random key issue mentioned above.)

Hope this helps! :)

**Comment by pupudu** [comment]
>React may throw away the work-in-progress state. In the case of your sandbox, this means that the count state will likely get initialized to different values each time the component renders. 

Thanks for clearing things up @bvaughn . My original intention was actually to create a random variable (and attach it to the state) to use that as a unique ID for the fetch call. Based on your comment, it seems not possible at this stage 😢 

Anyways, I highly appreciate you for taking the time to review the sandbox and even going to the hights of updating it to give more insights. You guys are legends! ❤️
