### ISSUE TITLE
useCallback doesn't update the scope of function

### ISSUE THREAD

**Issue by alirezavalizade** [facebook/react#17783]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
https://codesandbox.io/s/wizardly-surf-qd9s1
I'm trying to add an eventListener to an element based on a condition, But something weird is happening. I used useCallback(fn, [deps]), but on changing dependencies, it doesn't update the scope of function.

**What is the expected behavior?**
Accessing to most updated values in state from callback.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest.

**Comment by bvaughn** [comment]
I believe you are mistaken.

You create a new `handleMouseMove` function each time your component renders. It closes over the current value of `fullscreen` *for that render*.

In an effect, you attach a "mousemove" event listener if `fullscreen` is `true` for that render. If it's false, you *try* to remove the previous listener- except the thing you are now removing is the most recent listener, which means you're leaking.

This suggests, to me, two potential misunderstandings:
1. You're only attaching listeners when `fullscreen` is `true`, so you're always going to see if logging `true`.
2. You're never actually removing the listeners you attach, because you're using different functions each time.

To avoid leaking, you should be removing any listener you attach in the `useEffect` cleanup function, as shown in the docs: https://reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect

Here is an updated Code Sandbox:
https://codesandbox.io/s/tender-mahavira-sbf6w

**Comment by alirezavalizade** [comment]
ah my mistake, I thought the unsubscribe will be called when component will unmount, I got it now, thank you.
