### ISSUE TITLE
How to close the current browser window/tab in React?

### ISSUE THREAD

**Issue by hsluoyz** [facebook/react#17801]
I want to close the current tab or window when the user clicks "Close" button.

```js
onClose() {
    window.opener = null;
    window.open('', '_self');
    window.close();
  }
```

I tried the above code, but it's not working. My env is:

```
Windows 10 x64
Chrome 79.0.3945.88
React 16.12.0
```

Is it supported?

**Comment by Tevinthuku** [comment]
Yes it's supported, I got a tiny example running with what you require and it works from my end 

https://mmvcr.csb.app/

Here is the main sandbox for the implementation details https://codesandbox.io/s/close-on-button-click-mmvcr

Maybe there's an issue with how you are calling the onClose function. If this doesn't work you can create a sandbox so that we can get a better illustration of the problem you are facing.

**Comment by threepointone** [comment]
Feel free to continue the discussion, but I"m closing this issue since it isn't a bug or feature request (and doesn't have anything to do with React per se)

**Comment by mkhoussid** [comment]
The [Codesandbox] example doesn't work.

User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**Comment by jason-shen** [comment]
> https://mmvcr.csb.app/

i try it it works, you must done something more than just 
onClose() {
    window.opener = null;
    window.open('', '_self');
    window.close();
  }

**Comment by niklasgrewe** [comment]
@jason-shen for me it doesn't work in any browser:

```
macOS Catalina
x Chrome v.85
x Safari 13
```

**Comment by vidukapoor** [comment]
hi @Tevinthuku don't know how u tried,
just try to  go to `https://mmvcr.csb.app/` directly by copying it to the browser, i am here attaching the warning received.

![image](https://user-images.githubusercontent.com/14005853/94517631-fa48b500-0245-11eb-8234-331fb13822fe.png)

**Comment by vincent714** [comment]
that's right. it didn't work

**Comment by vincent714** [comment]
> hi @Tevinthuku don't know how u tried,
> just try to go to `https://mmvcr.csb.app/` directly by copying it to the browser, i am here attaching the warning received.
> 
> ![image](https://user-images.githubusercontent.com/14005853/94517631-fa48b500-0245-11eb-8234-331fb13822fe.png)

Hi @vidukapoor 
I found that you can't go to the web directly by copying it to the browser, just click the link provided here. https://mmvcr.csb.app/

it will work.

**Comment by daweimau** [comment]
> https://mmvcr.csb.app/

This script only works if the user has opened the page by ctrl+clicking into a new tab. If you copy paste the link into navbar, then it doesn't work. 

It's because this behaviour (closing a window that the user opened, via script) [generally isn't allowed by modern browsers ](https://www.thesitewizard.com/javascripts/close-browser-tab-or-window.shtml), although there seemingly still edge cases and workaround attempt, with varying success, as seen here.

**Comment by cfphpflex** [comment]
same result as above:  " Scripts may close only the windows that were opened by them."
looking for fix

**Comment by pagella42** [comment]
http://localhost:3000/mail_validate/pagella42%40gmail.com/6YAAB4

**Comment by albertosacbe** [comment]
could you fix this problem=

**Comment by Akki90skid** [comment]
Is there any solution for modern browser versions?

**Comment by inova-bilal** [comment]
I am using these currently. It will not close the tab though but it make tab blank
  window.open("about:blank", "_self").close();
  window.close();
