### ISSUE TITLE
React documentation is the worst documentation I have ever seen. I couldn't even create the app while going through documentation. Take some learning from documentation of Django, Flutter, Vue, Angular, etc

### ISSUE THREAD

**Issue by dev-akshat** [facebook/react#17850]
👉 Please follow one of these issue templates:
- https://github.com/facebook/react/issues/new/choose

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by ecreeth** [comment]
:-1:  nani.... :rofl:

**Comment by gaearon** [comment]
Sorry to hear you feel this way!

Our documentation is mostly oriented towards teaching you how to use *React itself* — not how to build web apps in general. If you were a bit more concrete about which topics you'd like to hear about (e.g. what kind of app you're building), maybe I could suggest some links.

In either case, https://github.com/reactjs/reactjs.org/issues/new would be the right place to file this issue, since it's about the documentation website rather than React itself.

I'll close this one because it's frustratingly vague, not very actionable, and is filed in the wrong repo.
