### ISSUE TITLE
Bug: useState and useReducer dispatcher should return the same reference.

### ISSUE THREAD

**Issue by LXSMNSYC** [facebook/react#17870]
Not really a bug but something that bothered/concerned me when writing hooks. Initially, I thought the dispatcher functions for `useState` and `useReducer` retained the same reference, but it wasn't until today when the dispatcher functions caused my `useEffect` hooks to re-run.

I was expecting this:

```js
const [myState, setState] = React.useState(myInitialValue);

React.useEffect(() => {
  console.log("Dispatcher changed!");
}, [setState]);

React.useEffect(() => {
  // Trigger an update on mount
  setState(newValue);
}, []);
```
Not to log "Dispatcher changed!"

I think these dispatcher functions should really retain its references across updates and re-renders (since old dispatcher references can still update the state), or is there any motivation as to why the reference isn't kept?

**Comment by bvaughn** [comment]
Both dispatch and state updater functions are stable. 😄 They do not change between renders.

Your above code would log "Dispatcher changed!" once, because that's how the dependencies array works. (Your effect is run with the *initial* value, then not run again unless one of the dependencies change.)

If you think you're seeing something different, please provide a full repro that we can run and confirm. Feel free to fork this one: https://codesandbox.io/s/condescending-hill-n4u90

**Comment by LXSMNSYC** [comment]
Oh right, sorry, I thought I am a bit off yesterday and I forgot that it works that way 😅, thanks for taking the time to reply 😅
