### ISSUE TITLE
Bug: ReturnType<EffectCallback> prevents optional chaining sugar

### ISSUE THREAD

**Issue by patrickroberts** [facebook/react#17884]
React version: 16.12.0

## Steps To Reproduce

```ts
import { EffectCallback, RefObject, useLayoutEffect, useRef } from 'react';

interface RenderingContextMap {
  '2d': CanvasRenderingContext2D;
  'bitmaprenderer': ImageBitmapRenderingContext;
  'webgl': WebGLRenderingContext;
  'webgl2': WebGL2RenderingContext;
}

function useDraw<Id extends keyof RenderingContextMap>(
  contextId: Id,
  create?: (
    ctx: RenderingContextMap[Id],
    isStale: () => boolean
  ) => ReturnType<EffectCallback>
): RefObject<HTMLCanvasElement> {
  const ref = useRef<HTMLCanvasElement>(null);

  useLayoutEffect(
    () => {
      const ctx = ref.current?.getContext(contextId) as RenderingContextMap[Id] | null;

      if (create && ctx) {
        let stale = false;
        const destroy = create(ctx, () => stale);

        return () => {
          stale = true;
          destroy?.();
//        ^^^^^^^ ts(2349)
        };
      }
    },
    [create, ref.current]
  );

  return ref;
}
```

## The current behavior

> This expression is not callable.
  Not all constituents of type 'void | (() => void | undefined)' are callable.
    Type 'void' has no call signatures.

The error makes sense, because `void` does not mean `undefined`, it means the type could be anything, and should not be observed. However, it is inconvenient because this is contrary to the contract explained below.

## The expected behavior

`ReturnType<EffectCallback>` _should_ be `undefined | (() => void)` instead, so optional chaining on the teardown function will be allowed.

The contract for this interface, as noted by the [latest relevant commit](https://github.com/facebook/react/commit/66eb29374239945c3a512a88aa2480637f62e5cc):

> Assume Effect hook returns either a function or undefined

On the contrary, `void` type signifies that the return type of the function will not be observed<sup>[1](#user-content-source-1) [2](#user-content-source-2)</sup>, allowing a function implementing the interface to return _anything_ with the assurance that its return value will be ignored by the caller. It is _not_ interchangeable with `undefined`.

The reason I request `undefined | (() => void)` instead of `undefined | (() => void | undefined)` goes along the same logic; the return value of the teardown function _should_ be ignored,

Currently, my work-around is to use `if (destroy) destroy();` instead of `destroy?.();`.

#### Sources: 

1. <a id="source-1" href="https://github.com/Microsoft/TypeScript/issues/25481">void is not assignable to undefined with function types</a>
2. <a id="source-2" href="https://stackoverflow.com/a/58885486/1541563">Why does TypeScript have both `void` and `undefined`?</a>

**Comment by bvaughn** [comment]
This issue looks to be entirely TypeScript related. The React team doesn't maintain the React TypeScript definitions. Those live in the DefinitelyTyped repo and are managed by the community.

The React source uses Flow for type checking, so our syntax (the commit you linked to) has a lot of subtle differences with TypeScript. I think that with Flow, `void` and `undefined` are the same thing as far as a function's return type are concerned ([source](https://flow.org/en/docs/types/primitives/)).

I'm going to close this issue since I don't think there's any change to be made on the React side. You may want to file an issue on the TypeScript repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react
