### ISSUE TITLE
Bug: useEffect async try catch block with state updater from useReducer.

### ISSUE THREAD

**Issue by davidalekna** [facebook/react#17924]
I'm not sure if this is a bug, but it's an unexpected behaviour to me. I have an async function in useEffect, that function has try catch block. Before try catch state updater function is not being called. If I call state updater function within try {} with 2 different parameters only last one gets called.

React version: 16.12

## Steps To Reproduce

1.
2.

Link to code example: https://codesandbox.io/s/falling-grass-ihod9

## The current behavior

In the console networkStatus: 2 is not being logged. State is not being updated. 

## The expected behavior

Should log 1, 2 and 7.

**Comment by bvaughn** [comment]
> Before try catch state updater function is not being called. If I call state updater function within try {} with 2 different parameters only last one gets called.

This looks like some confusion. Your reducer does get run with both values (2 and 7) but your component only re-renders once with the latest value (7) because React batches the two updates scheduled during the passive effect together into a single render pass for better performance.

You can see this if you add some additional logging:
https://codesandbox.io/s/nameless-leftpad-cxzt1

**Comment by davidalekna** [comment]
Thanks mate. I was trying to replicate my problem, in the end I found out that I had to use `useLayoutEffect` as my dispatcher is not being send on the first load. 😄
