### ISSUE TITLE
Bug: DevTools failed to parse SourceMap of extensions

### ISSUE THREAD

**Issue by sashasochka** [facebook/react#17954]
I am getting a lot of these errors/warnings in my console. Why is DevTools trying to get source maps for extensions?
Using the latest React Dev Tools extension (2.17.0) and React (16.9.12)
![image](https://user-images.githubusercontent.com/822771/73592378-62ea6100-4502-11ea-8b43-d82e8d2c054c.png)

## The current behavior
Getting lots of unrelated warnings

## The expected behavior
No warnings related to extension source maps should be created.

**Comment by bvaughn** [comment]
I don't know why you're seeing that 🙂but it doesn't have anything to do with React or the React DevTools (since our extension's id is [fmkadmapgofadopljbjfkapdkoienihi](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)). 

From your screenshot, it looks like the extensions you're getting errors for are [Ad Block (gighmmpiobklfepjocnamgkkbiglidom)](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom) and [Meta Mask (nkbihfbeogaeaoehlefnkodbefgpgknn)](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn).

**Comment by robtry** [comment]
Same bug, I do not have the extensions you said.
This warning started yesterday, after a Google Chrome update.
![bug](https://user-images.githubusercontent.com/21108496/73870830-57ed4480-4812-11ea-9c89-a312250d32bb.png)

**Comment by robtry** [comment]
It is about extensions, for me it started yesterday after a Google Chrome update. You can uninstall the extensions or just disable soruce maps:
https://stackoverflow.com/questions/36051891/esri-failed-to-parse-source-map

It solved the problem for me. No more warnings about that.

**Comment by sashasochka** [comment]
Disable source maps fully? It would cause the dev project's source map to not work either which is not good

**Comment by tornikenats** [comment]
@sashasochka I sometimes get this error if I serve the app over https.

**Comment by capan** [comment]
I'm started to getting this as warning. The problem is I can successfully run app using `npm start` but when I build using `npm run build --nomaps` and serve using `serve -s build -l tcp://0.0.0.0:3000` the app is looking for map files and some styles are broken.
![image](https://user-images.githubusercontent.com/7265736/77850044-97179080-71d8-11ea-8775-829c7980676c.png)

**Comment by yutsuo** [comment]
Isn't there a way to tell DevTools that it can ignore the extension its warning about?

**Comment by cri5ti** [comment]
@yutsuo: In the Console tab > Console settings (little cog on the right side) > tick Selected context only.

**Comment by sadhruva** [comment]
> @yutsuo: In the Console tab > Console settings (little cog on the right side) > tick Selected context only
it worked, 
is it ok if i just hide it?
