### ISSUE TITLE
Question: can I lie to useEffect about its dependencies in this case?

### ISSUE THREAD

**Issue by lsnch** [facebook/react#17987]
You [frequently][1] [see][2] warnings that you shouldn't lie to `useEffect` and `useMemo` about their dependencies.

I'm wondering about this special case, which I see throughout the codebase at work:
```
useEffect(() => {
  // We want effect to run when a changes, but not b
  doStuff(a, b)
, [a])
```

Let's say `a` changes every 10 seconds, and `b` changes every second, and we want to `doStuff` whenever `a` changes.

This works, is simple and elegant. Yet all guides discourage this, suggesting to do this instead:
```
let bRef = useRef()
useEffect(() => {
  bRef.current = b
})

useEffect(() => {
  doStuff(a, bRef.current)
}, [a])
```
Why? Aren't those equivalent?

I could see a potential issue with `useMemo(() => compute(a, b), [a])`. It can be accessed in the entire component, and sometimes it will be stale, which contradicts the meaning of memoization.

But what about that useEffect case?

  [1]: https://overreacted.io/a-complete-guide-to-useeffect/#dont-lie-to-react-about-dependencies
  [2]: https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies

**Comment by bvaughn** [comment]
I'm skeptical of this assertion:
```js
// We want effect to run when a changes, but not b
```
I suspect you *do* care about the value of `b` or else you would not be passing it along to `doStuff` in the first place. Perhaps a better solution here would be figuring out how to memoize `b` so that its changes are *meaningful* and not just noise.

That being said, if you want to implement this behavior without "lying to" the hook, you could just use a ref:
```js
const prevValuesRef = useRef({});

useEffect(() => {
  if (prevValuesRef.current.a !== a) {
    doStuff(a, b);
  }

  prevValuesRef.current.a = a;
  prevValuesRef.current.b = b;
}, [a, b]);

```
