### ISSUE TITLE
Bug: React component with 'overflow-wrap: break-word' property not wrapping properly.

### ISSUE THREAD

**Issue by asifuran2019** [facebook/react#17989]
I am wrapping a large amount of text under the CSS property 'overflow-wrap: break-word; width: 100%;'. This is working properly with plain html(without any js) but when I put that text under a React component, the wrapping seems to break.

React version: 16.12 (Latest as of today)
Chrome: 79

## Steps To Reproduce

1. Wrap a large amount of text under 'overflow-wrap: break-word; width: 100%;' with and without React and see the results.
2. I have created two `<p>` tags styled under overflow-wrap.
3. First is under public/index.html. Second under src/App.js
4. Compare the appearance. I have also posted screenshot of <p> overflowing under src/App.js

Link to code example: https://codesandbox.io/s/gifted-goldberg-7u5q5?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/55647986/73937848-f8735f80-490b-11ea-9ece-f09249ebb9e2.png)

**Comment by aweary** [comment]
Hey @asifuran2019. React doesn't do anything special for styles like `overflow-wrap`. It just renders the markup and styles you provide to the DOM. If you're seeing a strange style inconsistency issue like this, chances are it's due to an issue with the DOM APIs.

[Here's an example using those DOM APIs directly](https://codesandbox.io/s/elastic-http-jopgb?file=/src/index.js:720022-720279) that reproduces the inconsistent behavior. This tells us it's not a React-specific issue.
