### ISSUE TITLE
Bug: Strange situation when I create react element outside react class

### ISSUE THREAD

**Issue by giorgi-m** [facebook/react#17981]
Here is link for reproduction:https://codesandbox.io/s/friendly-wind-oli5k

My question is can code below

```
import React, { Component } from "react";

import BorderCrossDetails from "./BorderCrossDetails";

let config = {
  detailsComponent: <BorderCrossDetails />
};

class PersonCrossesGrid extends Component {
  render() {
    console.log(
      "From config",
      config,
      "From render",
      <BorderCrossDetails test />
    );
    return <div>test</div>;
  }
}

export default PersonCrossesGrid;
```

produce this screenshot??

![Screenshot from 2020-02-05 17-02-06](https://user-images.githubusercontent.com/41240312/73843906-00ae9a80-4839-11ea-8a74-7f6375897744.jpg)

**See how in one case type is undefined, and in another case type is BorderCrossDetails.**

Strange thing is in my project if I use such line in the code above:

`   detailsComponent: <PersonDetails/>,`

e.g. some different component in the config, the type is resolved correctly.

**Comment by threepointone** [comment]
My guess is there's a circular dependency at play here, resulting in an undefined import before all the modules have had a chance to settle. That said, it's hard to comment without a code sample, either as a codesandbox link, or as a git repo. Further, this doesn't seem like a React bug/feature request, so I'm going to close the issue, but I'm happy to have a look if if you have a reproducible example. Alternately, I suggest using a community resource like STack overflow (but with a running code sample, or you'll get a similar asnswer)

**Comment by giorgi-m** [comment]
@threepointone The reproducible example was in the question, sandbox link

**Comment by threepointone** [comment]
I missed that sorry! As I suspected, BorderCrossDetails depends on PersonCrossesGrid which depends on BorderCrossDetails. That seems wrong. 

In general, you shouldn't have to hoist element trees like this, there isn't much of a win to be had, and React is efficient about rendering these trees. So you could keep `config` inside the component definition. Hard for me to say further because I'm not sure what you're building.

**Comment by giorgi-m** [comment]
> So you could keep config inside the component definition

So you suggest I use this.config?
Can you explain why that would work?

I will try that, but it is also strange similar thing works in my project see Note 2 on my question.

**Comment by threepointone** [comment]
either on this.config, or as a local variable in render() should be fine. Because it evaluates it "late", the import would have resolved correctly, and it'll use the right definition. 

I don't know what elsewhere in your project looks like, but I assume you don't have a circular dependency  like this there. 

Consider your example again. If you do render BorderCrossDetails inside PersonCrossesGrid, you'll get an infinite depth tree, because PersonCrossesGrid is inside BorderCrossDetails too. I'd reexamine your code, it probably means you haven't structured something right.

**Comment by giorgi-m** [comment]
> Consider your example again. If you do render BorderCrossDetails inside PersonCrossesGrid, you'll get an infinite depth tree, because PersonCrossesGrid is inside BorderCrossDetails too. I'd reexamine your code, it probably means you haven't structured something right.

It works fine it's not that I am rendering them straightaway, when user clicks a row in PersonCrossesGrid I open BorderCrossDetails in a separate class where I have some modal dialogs.

Anyway, yeah I know that sounds strange but believe me I have almost same situation in my project with other classes where I don't have such a problem. Because I have similar structure everywhere some grid gets a details component which is opened on row click. **But it maybe not so easily evident what is different there that makes this circular dependency not an issue there.**
