### ISSUE TITLE
Bug: React Dev Tools Firefox extension fails to detect React

### ISSUE THREAD

**Issue by Kein** [facebook/react#17997]
React extension version: 4.4.0

## Steps To Reproduce

1. Install Firefox 72.0.2x64
2. Go to Discordapp.com

## The current behavior
Extension reports: _"This page does not appears to be using React"_

## The expected behavior
React is detected (just like it is currently in Chrome/Chromium)

**Comment by hristo-kanchev** [comment]
It's happening because the page is explicitly blocking our script that gets injected in the page. 
We are using that to detect if React is there or not.

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).` in `injectGlobalHook.js`

**Comment by Kein** [comment]
What are my options here?

**Comment by ruslan-shuster** [comment]
Can I take this issue?

**Comment by threepointone** [comment]
@ruslan-shuster sure! assigning to you.

**Comment by ineggapps** [comment]
Chrome Too...

**Comment by ruslan-shuster** [comment]
@ineggapps may I ask what is the url you were trying to access?

**Comment by Kein** [comment]
For me it works just fine in Chromium[ungoogled] 79.0.3945.88

**Comment by ruslan-shuster** [comment]
@Kein the problem which you described is now more or less understood
1) Your backend returns `content-security-policy` header which forbids injecting inline scripts to the page
2) `react-devtools` does inject some `<script>` tag to register window hooks, because Chrome content scripts cannot directly modify the `window` object, and `react-devtools` needs to install some hooks to the window.

So, what I'm going to do (if react core team agrees with this solution), is to implement some dedicated solution for `firefox`, which allows to install window hooks without injecting `<script>` tags. 

You can see more discussion of the problem & solutions [here](https://stackoverflow.com/questions/12395722/can-the-window-object-be-modified-from-a-chrome-extension).

**Comment by ruslan-shuster** [comment]
@threepointone I had some time investigating this issue, and in order to solve it some decisions should be taken which I, as the first-time contributor, don't feel empowered to take. I'd like to hear your opinion, and also opinion of @bvaughn, if possible. So, here is what happens:

1) There is a `content-security-policy` `script-src` directive, which specifies from which sources the scripts for the web page may come. On the issue reported, this directive was used to allow only specified origins and scripts with particular `nonce`.

2) Global hook(`__REACT_DEVTOOLS_GLOBAL_HOOK__`) is being injected using inline `<script>` tag, as well as `react_devtools_backend`, which are crucial for the `react-devtools` execution, and, as a consequence, for recognising `React` on the page.

The reason for such injection is that both Chrome and Firefox make some restriction for communication with the `window`. As far as I know, this is the only way you can run the code communicating with the `window` in Chrome.

 If `Firefox `, you can use [sharing objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts), but you need either to use cloneInto() all the time to export objects to the page script context, or use constructors defined on the window pretty much all the time when you want to make some object from extension be accessible from the page script content. Not only `__REACT_DEVTOOLS_GLOBAL_HOOK__` should be exported in this way, but also all of the internals of the event emitter, because the closures will still hold them in the captured scope.

The ideal solution for `Firefox` would be to re-implement all the mechanisms that need to run in the context of the user page to use mechanisms [described here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts), but it will make most of the code `Firefox`-specific, so we'll end up having and supporting two separate devtools frontend implementations. Since this issue was marked as `good first issue` and the effort would be quite large, I assume this is not what you aimed for.

Another solution would be to use hashes to whitelist `<script>`s which we're going to install as described [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script), and inform users to include those scripts as exceptions to their `content-security-policy` headers. This is small effort, and does not split extension functionality between browsers, but any time we change the scripts we inject the user will need to update the `content-security-policy` header. 

The third solution is to notify the user when we did not succeed to install hooks. Here is another problem: we cannot for sure identify that it happened because of the `content-security-policy`, though some hacks to do it [described here. ](https://stackoverflow.com/questions/19140169/how-to-detect-content-security-policy-csp).

So, I'd like to know what you think about it and what direction the solution should take?

**Comment by bvaughn** [comment]
This is a very helpful writeup, @ruslan-shuster. Thank you!

I agree with you that the first solution is not ideal.

The second one sounds promising, although I wonder how often the hash would change. (I guess the [hook source changes pretty infrequently](https://github.com/facebook/react/commits/master/packages/react-devtools-shared/src/hook.js).)

Maybe we could even combine solutions two and three, so if the insert fails- and we think it's likely CSP related- we log the exact CSC sha hash string that would need to be used to enable *the current* version of DevTools tow ork?

**Comment by ruslan-shuster** [comment]
@bvaughn sounds good, thanks for your help! Now I know which direction to take. Working on it...

**Comment by nightpool** [comment]
One thing to note—this is a Firefox-specific bug, because the Content Script Policy spec says that add-ons and other user customizations should not be subject to content security policy, and Chrome implements this correctly.

https://bugzilla.mozilla.org/show_bug.cgi?id=1267027 is the Firefox tracking bug to fix this issue.

**Comment by bvaughn** [comment]
Thanks for that link, @nightpool

**Comment by nightpool** [comment]
bump

**Comment by kimsey0** [comment]
bump

**Comment by chijin44** [comment]
bump

**Comment by MateusWagnitz** [comment]
bump

**Comment by MeanManMachineMan** [comment]
The same issue exists while visiting Github(this page in fact) and DIscord(www.discord.com).  I'm using Firefox 85.0.1x64 on Manjaro. ```Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).``` and ```Error walking your react tree``` are the two main errors I see in my console upon visiting Discord. I'm currently on React Dev Tools ```4.10.1```.

**Comment by Alef5750** [comment]
Hi - I'm new to open source. Is this issue already being dealt with or can I take a shot at it?

**Comment by Alef5750** [comment]
Will do! Thanks!

**Comment by colegillespie** [comment]
@bvaughn thanks for adding https://github.com/facebook/react/blob/main/packages/react-devtools/CONTRIBUTING.md I am going to see if I can duplicate this issue in firefox

**Comment by bvaughn** [comment]
@colegillespie Yes. You can replace "chrome" with either "firefox" or "edge" if you wanted to test other browsers 👍🏼

**Comment by colegillespie** [comment]
@bvaughn confirmed, was able to repro the error with the tests 
![image](https://user-images.githubusercontent.com/745064/128776389-eee6b5a5-e9a4-4de2-baca-448762e6d9d7.png)

will see if i can fix now

**Comment by colegillespie** [comment]
@bvaughn I was able to get this working and tests passing. Quite a drastic change in the way the global hook is inserted so please check the PR and make sure I am not doing anything too aggregious.

**Comment by garykhong** [comment]
Hello,
Can I lend a hand with this issue, or is it being looked after?  I don't mind testing the PR as well.

**Comment by bvaughn** [comment]
@garykhong Feel free to take a look!

**Comment by garykhong** [comment]
Thanks Brian.  Something came up, and I will try to look at this on the weekend.  Do you have a guide on how I can debug the react dev tools?

**Comment by bvaughn** [comment]
Just the contributing guide:
https://github.com/facebook/react/blob/main/packages/react-devtools/CONTRIBUTING.md

**Comment by garykhong** [comment]
Hi Brian,

I was able to get discord.com to load the react developer tools by setting the correct nonce on the injectGlobalHook.js script variable on line 8.

Is the ideal solution still to hash this script variable and to 'Add the hash to DevTools setting UI'?

**Comment by MeanManMachineMan** [comment]
Hey @bvaughn @garykhong , is anyone looking at this or can I take a crack at it as a first-time contributor? :D

**Comment by garykhong** [comment]
> Hey @bvaughn @garykhong , is anyone looking at this or can I take a crack at it as a first-time contributor? :D

Go for it Vidur

**Comment by hauntingEcho** [comment]
I'm seeing this issue as well.  It looks like uBlock Origin was able to work around this by just [shoving the script into a Blob URL](https://github.com/uBlockOrigin/uBlock-issues/issues/235)

**Comment by hauntingEcho** [comment]
bump
