### ISSUE TITLE
Bug: Derived value does not update in StrictMode

### ISSUE THREAD

**Issue by amanmahajan7** [facebook/react#18003]
React version:
16.12.0

## Steps To Reproduce

1. Enter a valid number in the textbox that uses strict mode. Notice the value changes in the textbox that does not use strict mode
2. Enter a valid number in the textbox that does not use strict mode. Notice the value does not change in the textbox that uses strict mode

Link to code example:
https://codesandbox.io/s/elated-mendeleev-1m5tm

![React App](https://user-images.githubusercontent.com/1452717/74093877-d1e52e00-4a9d-11ea-9911-ade6338642ae.gif)

## The current behavior
Derived value does not update in strict mode

## The expected behavior
Derived value should update in strict mode

**Comment by nstepien** [comment]
FWIW it works fine with the production build of react-dom, change the import in codesandbox to test it:
```js
import ReactDOM from "react-dom/cjs/react-dom.production.min";
```

**Comment by bvaughn** [comment]
When `StrictMode` triggers different behavior, it's usually a sign of a side effect or an unsafe pattern that maybe just happens to work in most cases. [`StrictMode` intentionally tests for things like this by double-invoking render methods](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects).

In your particular case, mutating a ref during render is a side effect. The way this plays out in practice is like so:
1. "loose" input changes e.g. 1 -> 2
1. "strict" input renders for the first time
   1. It changes `prevValue` ref from 1 -> 2, and calls `setInternalValue("")`
   1. It immediately re-renders with the newer state value (`internalValue` 1 -> 2)
1. "strict" input renders for the second time (remember [`StrictMode`](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects))
   1. Component state has been reset (including the update `setInternalValue("")`)
   1. However since the ref was mutated during the first render, the code you expect to update the tracked state doesn't get called, and things break.

Sort of unrelated, but maybe also worth pointing out- this Code Sandbox also looks like [one of the derived state anti-patterns described in a blog](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-unconditionally-copying-props-to-state) post a while back. Maybe worth a read?

However if you want to keep using this derived state approach, the "fix" here would be to get rid of the render-phase side effect by moving your ref update to an effect:
```js
if (prevValue.current !== value && internalValue !== "") {
  setInternalValue("");
}

useEffect(() => {
  prevValue.current = value;
});
```

**Comment by amanmahajan7** [comment]
Thanks you @bvaughn for the quick reply and detailed explanation.

**Comment by gmoniava** [comment]
@bvaughn in my question if you rendered it **without** strict mode, you would see Paul on screen. If you rendered it **with** strict mode, you'd see Nick. We explained this because it was due to using `firstRender` external variable. `firstRender `gets modified during first render, and on next strict render, it has different value, hence the second timeout doesn't fire- and always Nick is printed. Do you agree with this?

If yes, then I found out that by replacing `firstRender ` with a `ref`, even in strict mode, the output would be now the expected Paul. @ray suggested this could be because unlike `firstRender` variable, the `ref ` was reinitialized on the second strict render. Hence on the second render the timeout was trigerred.

**Comment by gmoniava** [comment]
@bvaughn That's a general guideline, I see.

But if you could answer more precisely, whether you agree with the explanation (which I summarized in previous comment) and which @ray came up with, would be nice. Otherwise what can we do.

Because like I said we had the impression during second strict render the ref value was discarded. But in this thread it seemed you claimed ref value was retained on second strict render, and that contradiction confused me.

**Comment by bvaughn** [comment]
I think this is going to be my last response. I don't think this conversation is super helpful, since you seem to be ignoring the fact that the example code you posted has side-effects and so is known/expected to be broken. (This is the purpose of StrictMode double rendering, as the link I shared above explains.)

> Isn't throw away and resetting kind of similar? I thought it could throw away a ref too.

Refs are mutable values. React initializes them _once_ and then returns the same object/wrapper every time your component renders (including strict mode).
