### ISSUE TITLE
DevTools Profiler: "Could not find commit data for root …"

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#18010]
The DevTools Profiler occasionally encounters the error:
> Could not find commit data for root "..." and commit ...

This issue is intermittent and we do not currently know hot to reproduce it. **If you can reproduce it** we would love to get any of the following information from you:
* Info about how you reproduce it. (Share your code or site with us?)
* An exported Profiler JSON that contains the bug. (This may be less useful, since the bug likely happens pre-export- but may still be helpful.)

**Comment by esvyridov** [comment]
@bvaughn Hi. During my investigation I reproduced the issue a couple of times using storybook.
Here is a link to sandbox https://codesandbox.io/s/react-devtools-profiler-error-7q1ml

Steps to reproduce:
1. Open codesandbox browser window in a separate tab (https://7q1ml.sse.codesandbox.io/?path=/story/button--with-text)
2. Start to record in Profiler
3. Select Button with text
4. Select Button with emoji
5. Stop recording
6. Select the lowest row in the Profiler
7. Select **button** instead of **Root** in Profiler

Please check a gif:
![ezgif-3-56a7e856f928](https://user-images.githubusercontent.com/46542370/74540623-29c5de00-4f51-11ea-84c1-49e8c0c5554e.gif)

And json:
[profiling-data.02-14-2020.17-37-05.json.zip](https://github.com/facebook/react/files/4204905/profiling-data.02-14-2020.17-37-05.json.zip)

**Comment by bvaughn** [comment]
Thanks for the info, @esvyridov!

**Comment by peanutenthusiast** [comment]
Hi @bvaughn , I'm interested in working on this.

**Comment by bvaughn** [comment]
Dive on in then, @peanutenthusiast. :smile:

**Comment by bvaughn** [comment]
Dive on in then, @peanutenthusiast. 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by peanutenthusiast** [comment]
Cheers! 🎊

**Comment by peanutenthusiast** [comment]
heads up was a little sick the past couple of weeks but will be looking into getting a pr in by end of week

**Comment by bvaughn** [comment]
Hi @peanutenthusiast!

Just checking in to see if you're still interested in working on this. If not, that's okay! Just let us know though so we can update the labels if needed.

**Comment by peanutenthusiast** [comment]
YES I AM.

**Comment by bvaughn** [comment]
Okay 😄 I suggest rebasing on `master` so you'll get the change from bd57819. It will rule out one potential source of error.

**Comment by peanutenthusiast** [comment]
excellent. will do.
