### ISSUE TITLE
DevTools: Search does not list components by useDebugValue inside custom hooks

### ISSUE THREAD

**Issue by kachkaev** [facebook/react#18088]
React version: 16.12.0
DevTools version in Chrome: 4.4.0-f749045a5

It'd be useful to be able to find a component by the value present in [`useDebugValue()`](https://reactjs.org/docs/hooks-reference.html#usedebugvalue). Here is an example test case:

## Steps To Reproduce

1.  Create a custom hook that relies on `useDebugValue`. E.g.

    ```js
    const useQuery = (query, options) => {
      const queryId = useMemo(() => generateUniqueId(), []);
      useDebugValue(`queryId = ${queryId}`)

      // + register query is some shared pool on mount,
      // unregister it on unmount, 
      // inform the pool about changes in query on re-renders, etc.
    }

1. Use this hook in a component, open React DevTools, navigate to that component and observe `Query: queryId = [someUniqueId]` in the list of used hooks. So far so good.

1. Use this hook inside a few components, log all queries currently registered inside a pool, see their ids.

1. Open React DevTools and try searching for one of the query ids, hoping to see the corresponding component.

## The current behavior

No search results shown (none of the components are highlighted)

## The expected behavior

Components with a corresponding search term in `useDebugValue()` are highlighted and I can flip between them. Perhaps, the same could apply to values in useMemo / useState etc. This advanced behaviour could be placed behind some search term keyword to avoid mixed results if someone wants to just filter by component names.

**Comment by bvaughn** [comment]
Searching by debug hook value is not something we could support without significant performance issues, since it would require DevTools re-rendering **every** function component in the tree to read the current debug value to process the search. (A little more background information on why this is [here](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks).) 

It's not an unreasonable feature request, but it's not something we'll be able to support. Sorry! 🙇
