### ISSUE TITLE
Bug: component re-rendered in concurrent mode when useState initialiser uses console.log

### ISSUE THREAD

**Issue by joefreeman** [facebook/react#18117]
React version:
```json
"react": "^0.0.0-experimental-5de5b6150",
"react-dom": "^0.0.0-experimental-5de5b6150",
```

## Steps To Reproduce

```javascript
function App() {
  console.log('1');
  const [state, setState] = useState(() => {
    // console.log('2');
    return 'state';
  });
  return (<p>{state}</p>);
}

ReactDOM
  .createRoot(document.getElementById('root'))
  .render(<App />);
```

This outputs: "1". With the `console.log` uncommented, this outputs: "1 2 1 2" (i.e., `App` is re-rendered, and the `useState` initialiser is run twice).

Link to code example:

https://codesandbox.io/s/practical-pond-u527l

## The current behavior

Output:

```
1
2
1
2
```

## The expected behavior

```
1
2
```

**Comment by bvaughn** [comment]
> This outputs: "1". With the console.log uncommented, this outputs: "1 2 1 2" (i.e., App is re-rendered, and the useState initialiser is run twice).

This isn't quite right. :smile: If you comment out the `console.log("2")` line, you'll still see "1" logged twice.

That's because this demo app is using the (experimental) concurrent mode API and it double renders in DEV mode to help detect side effects:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

The double rendering is expected, and will only happen in DEV mode. :smile:

**Comment by joefreeman** [comment]
Ah, sorry, I completely missed that the console was collapsing the repeated log line :weary: - thank you.

**Comment by bvaughn** [comment]
No worries :)
