### ISSUE TITLE
Bug: hook return setter losts  its effect when assign it to some obj after click its dom node in react-dev-tool

### ISSUE THREAD

**Issue by fantasticsoul** [facebook/react#18177]
React version: 16.12.0

## description
hook return setter to lost its effect when assign it to some obj after click its dom node in react-dev-tool. [prev closed issue](https://github.com/facebook/react/issues/16519)

## Steps To Reproduce
1. open react-dev-tool
2. click the dom node in the panel
3. input content at input box1 or input box2
[here is online demo](https://codesandbox.io/s/test-react-dev-tool-bug-kpb1y)

Link to code example:
```js
import React, { useState, useCallback, useRef } from "react";

const fnWrapper = { setCount: () => {} };

export default function DemoCounter() {
  console.log("render DemoCounter");
  const m = useState(0);
  const f = useRef(null);

  // this is not ok
  // fnWrapper.setCount = s => {
  //   console.log('fnWrapper.setCount');
  //   m[1](s);
  // }

  // this is not ok also
  // fnWrapper.setCount = useCallback((s)=>{
  //   m[1](s)
  // }, [m]);

  fnWrapper.setCount = m[1];//not ok

  f.current = m[1];//not ok

  console.log(fnWrapper.setCount === m[1]);

  if (
    typeof fnWrapper.setCount !== "function" ||
    typeof f.current !== "function"
  ) {
    console.log(typeof fnWrapper.setCount);
    console.log(fnWrapper.setCount);
    alert("wow");
  }

  return (
    <div style={{ border: "1px solid blue", margin: "8px" }}>
      count: {m[0]} <br />
      <h3>1 and 2 become bad after click the dom node in react-dev-tool</h3>
      {/* this does not work if I open react-dev-tool and click the dom node */}
      <input
        value={m[0]}
        onChange={e => fnWrapper.setCount(e.currentTarget.value)}
      />
      1 not ok
      <br />
      {/* this does not work if I open react-dev-tool and click the dom node */}
      <input value={m[0]} onChange={e => f.current(e.currentTarget.value)} />
      2 not ok
      <br />
      {/* this always works not matter I open react-dev-tool and click the dom node or not */}
      <input value={m[0]} onChange={e => m[1](e.currentTarget.value)} />3 ok!
    </div>
  );
}
```

## The current behavior
input 1 and input 2 's onChange event doesn't work any more after I clicked the dom node in react-dev-tool panel .

## The expected behavior
The onChange event works well no matter I clicked the dom node in react-dev-tool panel or not.

**Comment by fantasticsoul** [comment]
I just assign the latest setter to fnWrapper.setCount in every render period but I don't know why it does's work as I imagine.

**Comment by bvaughn** [comment]
What you're doing in the hook above - setting properties on an external object `fnWrapper` during render, or mutating a ref like `f` during render - is a **side effect** and [**is not safe to do**](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects). Side effects belong inside of an effect hook like [`useEffect`](https://reactjs.org/docs/hooks-reference.html#useeffect).

[As I mentioned on the previous issue about this](https://github.com/facebook/react/issues/16519#issuecomment-538059486):
> DevTools shallowly re-renders components that use hooks in order to build up the map of hook-to-value to show in the selected properties panel. ([Read more about this here if you're interested.](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks))

> When it does this re-rendering, it temporarily overrides the React's built-in hooks with [a version that collects this metadata](https://github.com/facebook/react/blob/master/packages/react-debug-tools/src/ReactDebugHooks.js). In your case, since you're mutating a prototype function every render, the more recent render (by DevTools) causes you to override it with the injected no-op value so that future calls don't actually update state.

**Comment by vkurchatkin** [comment]
@bvaughn documentation clearly says:

> React guarantees that setState function identity is stable and won’t change on re-renders.

And it seems that it is Dev Tools break this guarantee

**Comment by bvaughn** [comment]
I think that's a misunderstanding of the quoted documentation. That quote means that the `setState` function is stable between renders, so it won't break e.g. `React.pure` memoization and it won't cause e.g. `useMemo` hooks to be invalidated. In other words, the documentation is a comment on the general performance characteristics.

DevTools shallowly re-renders a component [as mentioned before on this issue and the previous one](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks). It does not run any effects callbacks, so no side effects will be run. It does not re-run `useMemo` or `useCallback` functions, so a temporary change in the dispatch won't impact them.

If you're using a non-hooks based memoization (e.g. `memoize-one`) it *would* invalidate it, but I would argue this is okay for a few reasons:
* Using developer tools (whether React DevTools or e.g. browser's built-in profiling tools) typically adds some additional overhead. This is acceptable because the scope is limited and end users won't experience it.
* So long as you don't break the rules of React and have side effects in render, what DevTools does should, at worst, cause a little extra CPU work. It won't be persisted anywhere. (DevTools rendering is shallow, so any temporarily invalidated calculations won't be passed further down the tree.)

DevTools *could* pass the actual `setState` function during the shallow render, but if the component being rendered called it- it would schedule actual work with React and cause a potentially observable change in application behavior. DevTool's current approach is unobservable to the larger app, **provided you don't have side effects** which would [already be problematic for other reasons, not counting DevTools](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects).

**Comment by vkurchatkin** [comment]
Documentation explicitly allows assigning to ref.current for lazy initialisation which makes it possible to observe invalid setState

**Comment by bvaughn** [comment]
> Documentation explicitly allows assigning to ref.current for lazy initialisation which makes it possible to observe invalid setState

No, it does not- because the ref will **always** already be assigned in that case. (DevTools will **never** render a component for the first time.)

**Comment by vkurchatkin** [comment]
Yes, that’s probably the case in practice, but it is never said in the docs that you MUST assign ref value during the first render. In theory it is possible that is for some reason assigned during DevTools render. That would probably require reading some external mutable value, which is not recommended, but people do it all the time

**Comment by bvaughn** [comment]
> but it is never said in the docs that you MUST assign ref value during the first render

Maybe. The docs only suggest writing to the ref during render for lazy initialization. I would argue that there's no reason to store a stable function like `dispatch`/`setState` in a ref to begin with though.

Reading from an external, mutable value is also an impure/unsafe thing to do. I'm not sure what pointer you're making when you say that "people do it all the time". Okay?

**Comment by vkurchatkin** [comment]
The point is that people (myself included) often break React rules thinking that they know what they are doing. 

Side effects in render is a good example. You are clearly discouraged to do so, but React says that setState is guaranteed to not changed, so you would assume that is ok to do that. Except it is not, and figuring out why can be difficult. The fact that DevTools disable console to hide this render makes it even more confusing. 

All I’m saying that docs should mention that fact that you might observe alternative setState functions if you break React rules, or something like this.

**Comment by bvaughn** [comment]
> The point is that people (myself included) often break React rules thinking that they know what they are doing.

Don't break the rules. They exist for a reason.

We (React team) do spend a lot of time trying to highlight why breaking the rules is bad- (including responding to GitHub issues like this) but it's not realistic for us to highlight **all** of the things can go wrong.

The docs are open source. If you think this is a case where the warnings could be improved, please feel free to submit a PR: http://github.com/reactjs/reactjs.org

I think this discussion has probably ran full course now :smile: I'm going to bow out.
