### ISSUE TITLE
Bug: In DevTools useCallback doesn't keep a stable value

### ISSUE THREAD

**Issue by ignas-sedunovas** [facebook/react#18191]
React version: 16.13.0

## Steps To Reproduce
1. Create a callback with `useCallback` and empty deps array
2. Create a value with `useMemo` and empty deps array
3. Create a sanity check to throw an error when callback doesn't change together with value
4. Inspect the component in React DevTools

Link to code example:
https://codesandbox.io/s/usecallback-result-is-not-stable-in-react-devtools-x9wl7

## The current behavior
Every time I inspect the component in React DevTools, `useCallback` (with empty deps array) creates a new callback and `useMemo` (with empty deps array) doesn't create a new value. This results in my sanity check throwing an error.
(Inspect `MemoAndCallback` component in given code sandbox)

## The expected behavior
Every time I inspect the component in React DevTools, the return value of  `useCallback` stays the same and my sanity check passes.

## My current workaround
Given that:
> `useCallback(fn, deps)` is equivalent to `useMemo(() => fn, deps)`.
https://reactjs.org/docs/hooks-reference.html#usecallback

I changed my code to use `useMemo` in those places and the sanity check passes.
(Inspect `MemoAndMemo` component in given code sandbox)

Could this maybe be an issue in my code?

**Comment by bvaughn** [comment]
This relates to the discussion on #18177 (and #18190).

### Why does this have anything to do with DevTools?

DevTools shallowly re-renders components that use hooks in order to build up the map of hook-to-value to show in the selected properties panel. ([Read more about this here if you're interested.](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks))

When it does this re-rendering, it temporarily overrides the React's built-in hooks with [a version that collects this metadata about which hooks (and custom hooks) the component is using](https://github.com/facebook/react/blob/master/packages/react-debug-tools/src/ReactDebugHooks.js). 

1. This re-render is **shallow**. (No children are rendered)
2. The results are not retained or committed (e.g. no DOM update).
3. It does not run any effects callbacks, so no side effects will be run.
4. It does not re-run `useMemo` or `useCallback` functions either (because that would be doing unnecessary "work" - since the results are thrown away).

As your sandbox shows, the re-render is **detectable** but should not cause any problems, so long as you follow the rules of React (no side effects in render).

**Comment by bvaughn** [comment]
I'm going to close this issue now since I think it's just a question which has now been answered. Let's talk more if there's still concern though!

**Comment by joelmoss** [comment]
While I understand the reasons for this, it can be annoying and lead to false negatives when debugging and testing performance of components.

Just the other day, I was banging my head against a brick wall, trying to figure out why a component was always being rendered twice, until I figure out that it was devtools doing its thing.

My component didn't have any side effects in the render, but I still didn't want to it re-render.

Would it be possible to somehow indicate that a component has been re-rendered by devtools?

**Comment by bvaughn** [comment]
> Would it be possible to somehow indicate that a component has been re-rendered by devtools?

Indicate...how?

**Comment by joelmoss** [comment]
lol, no idea 🤷‍♂️

I was kinda hoping you'd have a magic trick up your sleeve 😜

... just thinking out loud, sorry

**Comment by bvaughn** [comment]
No worries. It's okay.

I don't know of a better way of doing this, after putting a good amount of thought into the current approach. There may one though.

**Comment by ignas-sedunovas** [comment]
Hi @bvaughn. Thanks for looking into it.

>As your sandbox shows, the re-render is detectable but should not cause any problems, so long as you follow the rules of React (no side effects in render).

I understand this. And I'm not trying to detect a _re-render_ here.

To me it _seems_ there's an inconsistency between `useMemo` and `useCallback` inside React DevTools.

I think my initial sandbox had too much code to display what I'm suspicious about.
Could you take a look at this simplified sandbox?

Both `useMemo` and `useCallback` have an empty deps array. Because of this, I would expect none (or both) of them to generate a new value during a shallow re-render by React DevTools. But for some reason `useCallback` generates a new value and `useMemo` returns the old value. To me it seems that `useCallback` loses its memoized

https://codesandbox.io/s/usecallback-vs-usememo-simple-child-0wc1r
![ZErRZw3cG7](https://user-images.githubusercontent.com/3921290/76160292-3a6d0c80-6129-11ea-93b8-31c5d91b9cb7.gif)

### I did some debugging of React DevTools ###
I assume the issue is here: https://github.com/facebook/react/blob/master/packages/react-debug-tools/src/ReactDebugHooks.js#L214
`useCallback` always returns the latest `callback` value instead of returning `hook !== null ? hook.memoizedState[0] : callback` as it is done in `useMemo` few lines bellow.

![image](https://user-images.githubusercontent.com/3921290/76161525-84a7bb00-6134-11ea-9e8c-f7b5d8dde586.png)

What do you think?

**Comment by bvaughn** [comment]
> To me it seems that `useCallback` loses its memoized value.

It doesn't *lose* the memoized value. That value is still around for the next *real* render.

While you're right that there's a discrepancy between the debug tools implementation of `useMemo` and `useCallback`, I don't think it actually matters. The value returned for the shallow render *doesn't matter* because nothing will actually call that method. (It won't be passed to any child components.)

**Comment by bvaughn** [comment]
I don't object if you'd like to submit a PR that makes the two hook implementations "match" in that sense. I also don't think it's that important either way though :smile:
