### ISSUE TITLE
Bug: Switching between two different input type elements clobbers their default value

### ISSUE THREAD

**Issue by cincospenguinos** [facebook/react#18283]
React version: 16.8.0

## Steps To Reproduce

1. Create an app that toggles between rendering a text input and a date input.
2. Set the`defaultValue` of each to some arbitrary input, valid for either one
3. Ensure toggling occurs `onFocus`
4. Observe that the value of the date input is not preserved upon toggle

[Here is an example](https://codesandbox.io/s/loving-framework-z2eku)

## The current behavior

The date input's value is not preserved

## The expected behavior

The date input's value should be preserved

## Workaround

We discovered a simple workaround--add a unique `key` property to each input, and the value will be respected.

**Comment by kunukn** [comment]
It seems to be the default correct behaviour. 

You can read more about how `defaultValue` works here. <br/>
https://reactjs.org/docs/uncontrolled-components.html#default-values

The reason it seems to work by adding the key prop is because the component gets re-rendered from scratch and therefore the `defaultValue` "works".

I think what you want to achieve is pretty date display when not in edit mode.
Maybe something like this.

Demo
https://codesandbox.io/s/fervent-khayyam-qk4ic

Prototype code
```jsx 
const calculateDateDisplay = date => {
  if (!date) return "No date";

  const d = new Date(date);
  const year = new Intl.DateTimeFormat("en", { year: "numeric" }).format(d);
  const month = new Intl.DateTimeFormat("en", { month: "short" }).format(d);
  const day = new Intl.DateTimeFormat("en", { day: "2-digit" }).format(d);

  return `${day} ${month} ${year}`;
};

export default function App() {
  const [isEditing, setIsEditing] = React.useState(false);
  const [date, setDate] = React.useState("2020-01-01");
  const [dateDisplay, setDateDisplay] = React.useState("");

  const onFocus = () => {
    setIsEditing(true);
  };

  const onBlur = () => {
    setIsEditing(false);
  };

  React.useEffect(() => {
    setDateDisplay(calculateDateDisplay(date));
  }, [date]);

  if (isEditing) {
    return (
      <input
        onChange={event => setDate(event.target.value)}
        type="date"
        onBlur={onBlur}
        value={date}
      />
    );
  }

  return <input type="text" onFocus={onFocus} value={dateDisplay} readOnly />;
}
```
