### ISSUE TITLE
DevTools: Information of Hooks called in loop is merged under first hook

### ISSUE THREAD

**Issue by urrri** [facebook/react#18327]
My library receives from user array of hooks to run. It uses hooks as plugins. Array is statically declared by customer (it is unchangeable during lifetime of component and passed not via props). My code runs these hooks in loop. When I look at Hooks debug info in DevTools, I see that information from the all executed hooks is placed under the first hook name.

React version: 16.13.0

## Steps To Reproduce

1. Create 2 or more different custom hooks (use different system hooks inside to have internal info)
2. Add them into array.
3. Use functional component to call hooks from the array in a loop (any way for/forEach/etc.)
4. Open appropriated information in DevTools
5. Information from all hooks is under the first hook

Link to code example:

https://codesandbox.io/s/dev-tools-merges-info-of-hooks-in-loop-uv6ew

## The current behavior

All debug info is merged under first hook

## The expected behavior

Each hook should contains its own debug info no matter it called directly or from loop.

**Comment by bvaughn** [comment]
This is, unfortunately, the result of running hooks in a loop- which breaks the very first ["rule of hooks"](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level):
> **Don’t call Hooks inside loops, conditions, or nested functions.**

DevTools (really the [`react-debug-tools` package](https://github.com/facebook/react/blob/master/packages/react-debug-tools/src/ReactDebugHooks.js)) analyzes hook by [looking at the call stack](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks). Calling a hook from within a loop breaks this approach.

I realize that you say your users hooks are static, but I don't think we are going to fix what you've pointed out- since calling hooks from within a loop breaks one of the constraints.

**Comment by urrri** [comment]
Very strange attitude to the problem. "There is a bug, but we will not fix it, because it is in the area that is not recommended". The rules are created to prevent mistakes of those who do not understand what is hidden behind these rules. If you understand what you are doing, then the system will work even contrary to the rules. "But we will not repair the bug. Suffer, if you are too smart." A lot of thanks.

**Comment by bvaughn** [comment]
There are rules to using hooks which the React website clearly defines. The code you have shared breaks the very first rule. Because of this, the resulting behavior of DevTools may not be ideal.

Beyond that, more importantly, because of how [`react-debug-tools` is implemented](https://github.com/facebook/react/blob/master/packages/react-debug-tools/src/ReactDebugHooks.js), **there's not really an alternate design that we could use here that would also support [custom hooks](https://reactjs.org/docs/hooks-custom.html#using-a-custom-hook)**.

If you can think of one, please feel free to propose it though.

**Comment by urrri** [comment]
I dont know, how it is implemented, but I don't understand what is the difference in call stack when you use
`useHook1(); useHook2(); useHook3();`
and 
```var hooks = [useHook1(); useHook2(); useHook3()];
for(var i = 0; i < hooks.length;i++){
  var useHook = hooks[i];
  useHook();
}
```
Each hook function has it's own name or displayName property to differentiate them.

**Comment by bvaughn** [comment]
I've linked to the implementation with both of my previous comments. You're welcome to look.

I also linked [to this overview of how it works](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#inspecting-hooks). I'll copy paste it here:
> Hooks present a unique challenge for the DevTools because of the concept of custom hooks. (A custom hook is essentially any function that calls at least one of the built-in hooks. By convention custom hooks also have names that begin with "use".)
>
> So how does DevTools identify custom functions called from within third party components? It does this by temporarily overriding React's built-in hooks and shallow rendering the component in question. **Whenever one of the (overridden) built-in hooks are called, it parses the call stack to spot potential custom hooks (functions between the component itself and the built-in hook).** This approach enables it to build a tree structure describing all of the calls to both the built-in and custom hooks, along with the values passed to those hooks. (If you're interested in learning more about this, here is the source code.)

Calling hooks in a loop means that the call stack (at least the top frame) is the same for all of the hooks called. Apparently `react-debug-tools` assumes that the location calling them is a "custom hook" then.

If you'd be interested in digging in, and you can come up with an alternate approach or a fix, please feel free to tag me on a PR.
