### ISSUE TITLE
Error when running the react-native run-android command

### ISSUE THREAD

**Issue by Yuri-Tiofilo** [facebook/react#18337]
{
  "name": "testeFlatListInput",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.1.0",
    "@react-navigation/drawer": "^5.1.0",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.0",
    "axios": "^0.19.2",
    "immer": "^5.3.6",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-native-svg": "^9.11.1",
    "react-redux": "^7.2.0",
    "reactotron-react-native": "^4.0.3",
    "reactotron-redux": "^3.1.2",
    "reactotron-redux-saga": "^4.2.3",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "styled-components": "^5.0.1",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.18.3",
    "eslint-plugin-react-hooks": "^2.5.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^1.19.1",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by bvaughn** [comment]
Hi @Yuri-Tiofilo.

Issues for React Native should be filed in the React Native repository: https://github.com/facebook/react-native

Before filing an issue there though, please be sure to provide a minimal code example that reproduces the problem. (The description of this issue is not detailed enough for anyone to be able to help.) Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
