### ISSUE TITLE
Unhelpful propTypes warning: Invalid prop `0` supplied to `Component`

### ISSUE THREAD

**Issue by gaearon** [facebook/react#1833]
I use this pattern often:

```javascript
/** @jsx React.DOM */

var Hello = React.createClass({
    propTypes: {
        modifiers: React.PropTypes.arrayOf(
            React.PropTypes.oneOf(['large', 'colored', 'fill'])
        )
    },
    render: function() {
        return <div>Hello {this.props.name}</div>;
    }
});
 ```

It's useful for flags that change too often and go straight to CSS without imposing any logic onto the component.

Say I pass an unsupported modifier:

```javascript
React.renderComponent(<Hello name="World" modifiers={['other']} />, document.body);
```

React spits out an unhelpful warning:

```
Warning: Invalid prop `0` supplied to `Hello`, expected one of ["fill","colored","large"].
```

It's unhelpful because I have no idea what string `0` index corresponds to until I look it up in the code. It would save me a lot of time and hassle to see the actual array value that failed the check.

It there any reason why we don't show the value? Is it because it may not be serializable? Any workarounds?

**Comment by spicyj** [comment]
yeah, @petehunt where's this change? :)

**Comment by chenglou** [comment]
`createEnumTypeChecker` (and others) uses the format `props[propName]` to get the prop value. So `createArrayOfTypeChecker` has no choice but to pass the index as the prop name. I think the correct way to do this is to pass the prop value explicitly.

**Comment by brigand** [comment]
@chenglou any way we could have the index and name?  Not a huge deal, but it does help narrow down the search space when working with inconsistent apis <sub><sup>\*cough\* bidInfo</sup></sub>.

**Comment by chenglou** [comment]
@brigand possible but that might require an API change? I'm not sure whether it's worth it at this point

**Comment by mouthy75ks** [comment]
Leave a commentits worth it

**Comment by brigand** [comment]
@chenglou probably not, nevermind.

**Comment by jimfb** [comment]
Looks like this might have been fixed in https://github.com/facebook/react/pull/3737

Either way, we aren't actively working on the proptypes feature anymore (everything is moving to static analysis tools like Flow), so proptypes are on their way out. I'm not sure if we'd accept a PR, but I don't think this is something we'd actively develop internally at this point.

**Comment by jesstelford** [comment]
@jimfb Do you have an example of how you would use Flow to define the types for props? I can't quite connect the dots of where you'd do that.

It's disappointing to hear `propTypes` is going away - I've found it very useful for dynamically creating type-checking, such as in [`falcor-shapes-prop-types`](https://github.com/jesstelford/falcor-shapes-prop-types).

**Comment by luisrudge** [comment]
please don't remove proptypes.

**Comment by ajwhite** [comment]
> Do you have an example of how you would use Flow to define the types for props? I can't quite connect the dots of where you'd do that.

Curious to this point as well. I assume this might be pretty 1-to-1 with [type aliases](http://flowtype.org/docs/type-aliases.html)?

**Comment by zpao** [comment]
Since people have been coming in from Reddit… PropTypes are not being removed anytime soon.

**Comment by cpsubrian** [comment]
FWIW, one of the best uses of proptypes for me, personally, is that my eslint config (via standard) points out props I use that aren't defined. This helps spot and fix countless typos before they cause a real problem, especially during refactors. I suspect/hope Sublime has equally useful integration with however Flow defines proptypes.

**Comment by ljharb** [comment]
Until flow runs as a command line tool with no server, and no boilerplate comment in a file I want to run Flow on, it's just not an option. I hope propTypes continue to be developed until such time as Facebook considers Flow type notation useful enough to legitimately propose to TC39 to be part of the JS standard.

**Comment by eriklharper** [comment]
Because PropTypes ships with React, production apps will log console warnings for invalid propTypes, which is pretty useful.  Since Flow is for local development only, will React still log these kinds of warning when PropTypes is removed?

**Comment by zpao** [comment]
Please read my earlier comment. PropTypes are not being removed anytime soon. PropTypes do not log in production applications either, only in development mode. Flow in its current form would only log in CI or on explicit execution (they are static checks after all). The idea of Flow gaining support for a development transform which would embed runtime typechecks has been discussed but we're not there yet.

**Comment by imcnally** [comment]
Wanted to chime in with a great use case for PropTypes, should it help inform any future discussions on the topic.

On a project I was on, the CMS would render React components directly, on the server. There was an implicit data contract between the two. By adding PropTypes that matched the shape of the incoming data from the CMS, the web team able to debug data problems very quickly. We also got rid of the excuse "oh, the front end broke it" :wink:, which was a sweet relief.

**Comment by sebmarkbage** [comment]
Let me also clarify: There is an idea to unify the type system semantics with Flow so that there are equivalent concepts in either direction. In case people prefer early adoption of the syntax extension that Flow provides (which is being unified with other similar systems so that it can eventually end up on the standardization track) then they could compile those into development time runtime warnings. However, there would likely be a runtime only alternative without syntax sugar available too. Although it might be less convenient. Compare something like `async/await` to `Promise`. If you don't want to use the syntax extension you don't have to. There won't be a requirement to use language extensions to use React. However, all of these are hypothetical ideas and until this becomes real and adopted.

PropTypes will remain and be maintained. It is unlikely that it will evolve in a direction that is incompatible with Flow-unification that is all. If a new unified system does evolve, there will be a suitable upgrade plan.
