### ISSUE TITLE
Bug: cursor jumps to end of controlled <input> tag when value is modified

### ISSUE THREAD

**Issue by iain-merrick-fanduel** [facebook/react#18404]
React version: 16.13.1

## Steps To Reproduce

1. Make an `<input>` tag controlled, by setting its `value` in response to `onChange`
2. Apply a transformation to the value (for example, replace spaces with underscores)
3. Move cursor to the middle of the text and edit it

Link to code example:

https://gist.github.com/iain-merrick-fanduel/b9cea57baa9f20a5d288a0fcd6e7ee5e

Adapted from CodePen example (https://codepen.io/gaearon/pen/VmmPgp?editors=0010) on https://reactjs.org/docs/forms.html

## The current behavior

If the transformation changes the value, the cursor is moved to the end of the input.

## The expected behavior

Cursor should remain at the original position if possible (this is the behaviour of the `TextInput` component in React Native).

**Comment by iain-merrick-fanduel** [comment]
This is very similar to https://github.com/facebook/react/issues/14904, but doesn't look quite the same:
- I'm updating the value locally, in the same component
- I'm modifying the value

In case this is browser-specific, I'm using Chrome 80 on OS X 10.14.6.

**Comment by iain-merrick-fanduel** [comment]
As far as I know, this is the intended usage, as the docs specifically give this example:
```
handleChange(event) {
  this.setState({value: event.target.value.toUpperCase()});
}
```
That example exhibits the same bug — you can't edit the text field in the middle.

**Comment by vkurchatkin** [comment]
This has nothing to do with React, that's normal browser behaviour

**Comment by iain-merrick-fanduel** [comment]
In hand-written HTML, you'd normally fix this by saving the cursor position before changing the text, and restoring it afterwards. But React doesn't provide that low-level access (by design).

Maybe React could manage the cursor position automatically? This would bring parity with React Native, where the `TextInput` component behaves as expected.

**Comment by vkurchatkin** [comment]
> But React doesn't provide that low-level access (by design).

Well, that's where you are wrong. It's not that hard to implement this in React. Here is a demo: https://codesandbox.io/s/boring-dirac-utq82

**Comment by iain-merrick-fanduel** [comment]
Oho, neat! I can probably use this, thanks!

Is this something that could/should be added as default behavior for the `<input>` component? I can't think of scenarios where you would _not_ want this, and even if you want something different you could override it anyway. The examples in React documentation could all benefit from this.

Alternatively, the documentation could be updated, but it seems like a lot of boilerplate for a simple task.

**Comment by ryanstan1ey** [comment]
It's actually a little strange that the example docs use this approach. I've read that since React uses `event pooling` one needs to capture the event and pass the captured event to the setState function.

If you modify your handleChange to the following, it should work as expected.
`
handleChange(event) {
    let value = event.target.value.replace('/ /g','_');
    this.setState({value});
  }
`

Event pooling allows reuse of the event and because the setState is asynchronous, there is no guarantee on when it will be called and what value it holds at that instance.

**Comment by vkurchatkin** [comment]
> Is this something that could/should be added as default behavior for the <input> component?

I think it is a bit against React philosophy. React is about making DOM transformations declarative, not about changing how it works. If you need such behaviour, you can make your own `<Input/>` component which does just that (or more).

> The example in the documentation would benefit from this.

I agree, there probably should be a warning in the docs explaining that it's not as _ straightforward_ to modify input this way.

> If you modify your handleChange function to the following, it should work as expected.

No, your modified code is strictly equivalent to original code. What you can't do is use the event object asynchronously, including `setState(() => ...)` form, without calling `e.persist()`.

**Comment by gaearon** [comment]
>As far as I know, this is the intended usage, as the docs specifically give this example

Woah. This advice in docs seems pretty bad. I don't think this is supported in that sense.

This behavior is expected (React can't know where to put the selection after you've modified it).

I'll remove the misleading docs section.

**Comment by cefn** [comment]
> React can't know where to put the selection after you've modified it

I don't agree with @gaearon for a very common case. This is perhaps the most common case, and almost certainly what people are complaining about.

Where editing in the control caused the state change, the contents of the control are exactly suited to preserving the selection. The value held in the control is _already_ the value react is attempting to set. It originated in the control and is just taking the long way round. For this case, preserving the selection is a perfectly well-defined behaviour, and the selection change may be considered an artefact of the [recommended 'controlled' component binding approach](https://reactjs.org/docs/forms.html#controlled-components) combined with current react reconciliation behaviour.

One of two alternative strategies seem reasonable for reconciling an already-identical DOM value: 
a) Don't set the value at all, the selection (cursor) will be implicitly preserved.
b) DO restore the selection (cursor) after redundantly setting the value and therefore 'breaking' the selection. This is guaranteed to be a well-defined behaviour (and probably what was intended).

The approach I propose assumes that state changes originated from a controlled component can't 'back up'. In other words, it's not going to try and set the component to a state it was in three keypresses ago, then two keypresses ago, then one keypress ago, since the dom value will already be from the future. I don't know if react can be relied upon to skip stale state changes in this way.

For discussion the workaround below embodies selection-preserving strategy b) in the form of a hook (because I don't expect to monkey patch reconciliation internals). It worked for my state engine in simple interactive testing. It has a lot of guards because of rulesOfHooks (useLayoutEffect can't be in a conditional). I'd be curious if it works for others.

This workaround can be used like...

```
<input type="text" {...useBinding(label)} />
```

```typescript
import { useLayoutEffect, useRef } from "react";

export function useBinding<E extends HTMLInputElement | HTMLTextAreaElement>(
  value?: string
) {
  // ref for the (eventually) bound DOM element
  const ref = useRef<E>(null);

  // inspect value and selection before dom change
  const { value: domValue, selectionStart, selectionEnd } = ref.current || {};

  // consider restoring selection after dom change
  useLayoutEffect(() => {
    if (domValue === value) {
      // domValue was already aligned.
      // Suggests change originated from this control
      // Preserve selection
      if (ref.current) {
        if (typeof selectionStart !== "undefined") {
          ref.current.selectionStart = selectionStart;
        }
        if (typeof selectionEnd !== "undefined") {
          ref.current.selectionEnd = selectionEnd;
        }
      }
    }
  }, [value]);

  // props for the bound control
  return {
    ref,
    value,
  };
}
```

**Comment by tantaman** [comment]
The proposed solutions seem a bit convoluted, special cased and still have visual artifacts (such as the cursor jumping to the end and back over two frames).

Copying the state into a synchronous variable to act as a cache for the async store seems more straightforward and general:

```js
export function useCachedState<T>(propValue: T): [T, (value: T) => void] {
  const [lastValue, setLastValue] = useState(propValue);
  const [currValue, setCurrValue] = useState(propValue);
  if (propValue !== lastValue) {
    setLastValue(propValue);
    setCurrValue(propValue);
  }

  return [
    currValue,
    (value: T) => {
      setCurrValue(value);
    },
  ];
}

function EditableItem({
  id,
  value,
}: {
  id: string;
  value: string;
}) {
  const [cachedValue, setCachedValue] = useCachedState(value);
  const onChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    setCachedValue(e.target.value);
    return updateSomeAsyncStore(e.target.value);
  };

  return <input type="text" value={cachedValue} onChange={onChange} />;
}
```

This will make the update synchronous to the component and keep the caret position in the input. If the async store replies back with something that doesn't match the optimistic synchronous update, the async store will override the synchronous state.

This approach is also general and works not just for text inputs but also for draggables or anything else.

Ideally, though, the "someAsyncStore" would have a reactive system that can update synchronously rather than pushing this concern out into components.
