### ISSUE TITLE
Bug: Unexpected react-hooks/rules-of-hooks error when hook is declared as object property

### ISSUE THREAD

**Issue by ElijahKaftanov** [facebook/react#18475]
So I have the eslint error when declaring hook like this:
`const store: any = {}`
`store.useCustom = () => { React.useEffect(() => {}); };`
`export default store;`

The message of the error: 
> React Hook "React.useEffect" is called in function "store.useCustom" which is neither a React function component or a custom React Hook function

This is confusing because code below works fine:
`const useCustom = () => { React.useEffect(() => {}); };`
`export default { useCustom };`

Thanks for your product!

**Comment by bvaughn** [comment]
Can you tell us more about what "store" is and why you're attaching custom hooks to it? This looks a little unusual.

**Comment by gaearon** [comment]
This is an intentional decision.

It is meant to discourage a pattern where you access some sort of mutable state or an object instance from your Hooks. This won’t work and will cause confusing bugs.

As you said, technically you can write a top level plain function and put it on an object later. We can’t forbid you from that. But by convention, we want to strongly encourage Hooks to only be written as top level plain functions.
