### ISSUE TITLE
Bug: 'render' is executed 2 times during initialization

### ISSUE THREAD

**Issue by beilo** [facebook/react#18477]
React version:
```
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "3.4.1"
```
## Steps To Reproduce
1. yarn create-react-app my-app
2. update App.js
```
// App.js
function App() {
  console.log("function"); // Perform one
  return (
    
  );
}
class App extends React.Component {
  render() {
    console.log("render"); // Perform 2 times
    return (
      
    );
  }
}
```

## The expected behavior
Why execute it twice?

**Comment by mirhaCode** [comment]
Hi !

You have start your app in mode dev ?

**Comment by beilo** [comment]
> 嗨！
> 
> 您已经在dev模式下启动了您的应用程序？

yes

**Comment by gaearon** [comment]
This is intentional behavior because your app is [running in Strict Mode](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects). You can check that in `src/index.js`. Eventually, this will be the default because it helps find issues caused by impure renders. We will also double-invoke all functions in the next release.

In production, it will only run once.

**Comment by beilo** [comment]
@gaearon thanks

**Comment by mertxe78** [comment]
[](url)
