### ISSUE TITLE
Bug: invalid url in react courses

### ISSUE THREAD

**Issue by matlae-ugly** [facebook/react#18492]
Hi! On page (https://reactjs.org/community/courses.html) free course named "Glitch: React Starter Kit" href is wrong. It is "https://glitch.com/glimmer/episode/react-starter-kit/" but it should be "https://glitch.com/glimmer/post/react-starter-kit". 

P.S. Sorry for my potato English.

**Comment by bvaughn** [comment]
Hi @matlae-ugly

The code for this page is here: https://github.com/reactjs/reactjs.org/blob/master/content/community/courses.md

Want to send us a pull request with a fixed link? :smile: Tag me as a reviewer and I'd be happy to merge it.


I'm going to close this issue since our docs live in a [different repository](https://github.com/reactjs/reactjs.org/) but I look forward to a pull request from you :smile:
