### ISSUE TITLE
DevTools: Memo(ForwardRef()) and "Rendered By" List

### ISSUE THREAD

**Issue by gaearon** [facebook/react#18571]
If you have `memo(forwardRef(X))`, then the inner component won't have a "rendered by" list. This is because it technically doesn't have an owner. It is artificial.

I think we should ideally set up `_debugOwner` for these Fibers in DEV just so existing tooling can find them. Or special case them in DevTools.

**Comment by gaearon** [comment]
It's especially bad because it breaks the "rendered by" chain for inner trees. They "stop" at the inner memo() content (unless it's SimpleMemo).

I think this might also be why RN inspector sometimes shows trees that stop abruptly without going all the way up to the root.

**Comment by hanq08** [comment]
I think this not only happens in forwardRef, any non simple component wrapped in memo will have this issue. for example memo(class Component).

I'd like to work on this. I think the issue lies here potentially https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberBeginWork.new.js#L421  Let me know if that's ok thanks.

**Comment by bvaughn** [comment]
@hanq08 If you're interested in working on this, we'd welcome a PR.

**Comment by eps1lon** [comment]
bump

**Comment by bvaughn** [comment]
This issue has already been fixed in master. I confirmed it a few minutes ago by running a test on a local build.
