### ISSUE TITLE
Bug: Failed state update with useTransition with different timeouts

### ISSUE THREAD

**Issue by subhero24** [facebook/react#18599]
React version: 0.0.0-experimental-e5d06e34b

I have a sandbox of the bug here: https://codesandbox.io/s/frosty-bassi-0utfp?file=/src/App.js

The component schedules a state update when a transition starts. When the timeoutMs of the transition is high, everythings works as expected. When the timeoutMs is lowered, but still at a time that is never reached, the state update is never executed.

1. Open de codesandbox and click the button. You see
- pending set to true immediately
- delayedpending set to true after 2000ms
- pending and delayedpending set to false once after 4000ms when the transition completes

2. Change the timeoutMs from 8000 to 7000. Delayedpending is never set to true, even though it should.

**Comment by gaearon** [comment]
Can you reproduce this with a build from master?

**Comment by subhero24** [comment]
The problem also occurs with a build from master

**Comment by gaearon** [comment]
Looked into it. This is the same problem as https://github.com/facebook/react/issues/17332#issuecomment-609994238.

Currently, we infer a setState's priority based on where it was called. E.g. by default they get a "normal" priority. Inside React event handlers, the priority may be higher (e.g. "user blocking"). The priority of setState determines which other setStates it will be batched together.

In your case, if the transition timeout is not large enough, *both* the transition `setState` and the `setState` in your effect get the same priority. So they get processed together. When we try to render the result of the effect `setState`, we suspend, and are unable to finish rendering. That's why this `setState` gets "blocked" by the transition's `setState`.

Making the transition timeout higher accidentally fixes this because now the transition's `setState` gets a lower priority than "normal". So it doesn't block normal priority `setState`s. They are processed independently.

This is indeed very confusing, which is why we're planning some changes to this model. There is a large refactoring in place to switch us to a model where `setState`s can be processed on individual "lanes", of which there are more than priority levels today. Note this won't solve the problem in all cases, but should make it less common.

In the meantime, you can work around it by explicitly "bumping" the priority of your `setState`. Here's a sandbox that shows how to do it: https://codesandbox.io/s/hungry-architecture-fg5he?file=/src/App.js

**Comment by gaearon** [comment]
This appears to have been fixed on master.
https://codesandbox.io/s/elegant-khorana-gv9qr?file=/src/App.js
