### ISSUE TITLE
Bug: index.d.ts(1713, 9): The expected type comes from property 'contentEditable' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'

### ISSUE THREAD

**Issue by HerbertHe** [facebook/react#18603]
When I want to use contentEditable attribute as `plaintext-only`, `vscode` showed me that I can not assign `plaintext-only` to contentEditable.

React version: 16.7.0

## Steps To Reproduce

1. add a element `div`
2. assign `plaintext-only` to contentEditable

Link to code example:

## The current behavior

index.d.ts(1713, 9): The expected type comes from property 'contentEditable' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'

## The expected behavior

Support `plaintext-only` for contentEditable

**Comment by eps1lon** [comment]
This issue should've been filed over at DefinitelyTyped though it'll be closed over there anyway because we don't support non-standard attributes.

> Support plaintext-only for contentEditable

This value is currently not part of the living standard. We only type attributes that are part of [the living HTML standard](https://html.spec.whatwg.org/multipage/interaction.html#attr-contenteditable).

**Comment by gaearon** [comment]
Going to close since this relates to TypeScript typings of React, which are not maintained in this repository.
