### ISSUE TITLE
Bug: useContext returns default instead of passed value

### ISSUE THREAD

**Issue by codebling** [facebook/react#18629]
Given the following code:
```
const TestContext = React.createContext('default');

export default () => (
  <TestContext.Provider value='not default'>
    <span>{React.useContext(TestContext)}</span>
  </TestContext.Provider>
);
```
The resulting value in `<span>` is "default". 

React version: 
`react@16.13.1` (`@latest`)
`react@0.0.0-d7382b6c4` (`@next`)

## Steps To Reproduce
A [repo illustrating the issue](https://github.com/codebling/react-context-test) is available.

## The current behavior
`React.useContext()` returns the default (the string "default"), despite the presence of a `value` prop with another string. 

## The expected behavior
`React.useContext()` should return the string "not default" ***or*** throw an error/warning.

## Discussion

A slightly modified version of the above code
```
const TestContext = React.createContext('default');

const Inner = () => (
  <span>{React.useContext(TestContext)}</span>
);

export default () => (
  <TestContext.Provider value='not default'>
    <Inner />
  </TestContext.Provider>
);
```
Renders the string "not default", as one might expect.

I'm guessing that this has to do with the rendering order of the components and is maybe unavoidable, but perhaps an error or warning should be thrown if a corresponding Context Provider isn't available when `useContext()` is called. This would force everyone to actually wrap all code in a Context Provider.

**Comment by gaearon** [comment]
This is expected because

```js
  <Test1Context.Provider value='not default'>
    <span>{React.useContext(Test1Context)}</span>
  </Test1Context.Provider>
```

is the same as 

```js
  const ctx = React.useContext(Test1Context)

  <Test1Context.Provider value='not default'>
    <span>{ctx}</span>
  </Test1Context.Provider>
```

In other words, *components themselves* are boundaries for context. Where you put a Hook call doesn't play a difference.

**Comment by worc** [comment]
it's a confusing design. i think i just lost an hour there chasing this one. you can't instantiate `useContext` in the component where it will be used? you have to instantiate in a separate component and then use that component in the original component?

```jsx
import ComponentWhereUserProviderIsSetAndModified, { User } from './some-module'

const DebugDiv = () => {
  const { name } = useContext(User)
  return <div>{ name }</div>
};

const Demo = () => {
  const { name } = useContext(User);

  return (
    <>
      <ComponentWhereUserProviderIsSetAndModified>
        <DebugDiv/> // picks up on changes in the provider
        <div>{ name }</div> // is stuck with the default value and never looks up the Provider directly above it in the tree
      </ComponentWhereUserProviderIsSetAndModified>
    </>
  );
};
```

it still seems like a bug

**Comment by codebling** [comment]
Intuitively, it doesn't make sense to have a Context consumed in the same component as it was provided. 

Unfortunately, that's also the most intuitive way to try out `useContext`.

**Comment by worc** [comment]
in my case, you're not consuming the context in the same component that it's provided. the provider and its value modifications are in another module and in another component. but you do arrange them so that the provider is an ancestor of the consumer.

i have a faint idea why you have to separate things out, but not a clear one.

my assumption was that consumers traverse up through the tree looking for an instance of a matching provider. but that doesn't seem to be the case

**Comment by BanwaraPapiha** [comment]
### Solution: You are using Context in a place where it is not needed, in the immediate descendant you can use props, otherwise react will surely throw errors
The same issue can be faced if you are new to the React Framework and don't actually understand the reasons why we use React Context and useContext API. As @gaearon pointed out very beautifully and @worc demonstrated very beautifully, they were right in their sense but I think it is not a Bug actually. Because if you are using useContext hook in the immediate descendant component, it doesn't make sense and does not need to use Context API because in the immediate Ancestor we already have the props. 
So in the one final line to conclude, **"in the immediate descendant component of an ancestor component we already have the props to use and we don't actually need Context, and if we does it is definitely the deviation from React terms and it throws errors "**
