### ISSUE TITLE
[react-hooks/exhaustive-deps] inconsistant object and object.key

### ISSUE THREAD

**Issue by alex-cory** [facebook/react#18724]
React version: 16.13.1

## Steps To Reproduce

1. run the code in this [Codesandbox](https://codesandbox.io/s/usefetch-getter-exhaustive-deps-bug-1zic7?file=/src/index.js)

## The current behavior

I have a `response` object that I am using between various `useCallback` functions. I would like to mention that `response.ok` is a getter so we can get the correct value of the response from within the callback.

You can see that when I don't have it in my dependency array it suggests adding `response.ok` to the dependency array.

![image](https://user-images.githubusercontent.com/5455859/80160331-3afb1e80-8582-11ea-8e4d-d7a9f22209f5.png)

When I do this, because the `response.ok` changes values, it fires the request twice (which obviously is not what we want).

Now, when I put just `response` in the dependency array, the linting error goes away and we get the desired result.

![image](https://user-images.githubusercontent.com/5455859/80160709-1f444800-8583-11ea-9a13-5782c2207f8d.png)

## The expected behavior
I'm assuming the expected behavior for react is to require `response.ok`, but since it's allowing `response` I'm curious if that is okay too?

Will future react that has compilers handling dependencies allow `response` or is this what I'm assuming, a bug and they will require `response.ok`? I guess will `getter`'s be defined in the dependencies as a function or a field value?

**Comment by bvaughn** [comment]
> I'm assuming the expected behavior for react is to require `response.ok`, but since it's allowing `response` I'm curious if that is okay too?

Generally speaking, the answer would be no. The dependencies array exists to avoid stale values in the callback function you pass to `useEffect`. (You can find stale dependencies and the problems they cause mentioned on other issues, like [this one](https://github.com/facebook/react/issues/18065#issuecomment-590152262), as well as [in the docs](https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function)).

That being said, the specific Sandbox you linked to is doing some other unusual things. The `useFetch` hook looks pretty unusual at a glance; calling `fetch` twice could yield unpredictable results, since it mutates a shared response object. I would suggest something less clever, that just uses React's built in state, e.g.
```js
const useFetch = (urlOrPath) => {
  const [state, dispatch] = useReducer(reducer, initialArg, init);

  const get = useCallback(
    async (route = "") => {
      dispatch({ type: "start" });
      const data = await res.current.clone().json();
      dispatch({ type: "complete", data });
    },
    [urlOrPath]
  );

  return {
    get,
    loading: state.loading,
    response: state.response,
  };
};
```

**Comment by alex-cory** [comment]
@bvaughn I'm currently building [use-http](https://github.com/ava/use-http). This is a pretty decent sized breaking change, but if you are advising me to change this, I will.

**Comment by bvaughn** [comment]
@alex-cory I don't know much about `use-http` so I don't mean to make a sweeping statement about it, but in general- I think the mutation pattern your example showed looks problematic. (In ways like we're discussing now, for example.) I would advise using React state instead :smile
