### ISSUE TITLE
Multiple ReactDOM.render() calls - Site Mirroring.

### ISSUE THREAD

**Issue by Cryptonex7** [facebook/react#18916]
## I am trying to twin my app on the same screen as follows:
![image](https://user-images.githubusercontent.com/34197902/81883554-21625b00-95b3-11ea-8345-fb15ae4e14d3.png)

## I want to achieve this using a separate ReactDOM like so:
![image](https://user-images.githubusercontent.com/34197902/81883631-5c648e80-95b3-11ea-9765-8b5880a5de44.png)

**But since they are 2 independent virtual DOMs, I am not able to link them.**
___

## To simulate the problem, I defined a state to change the theme like so:
![image](https://user-images.githubusercontent.com/34197902/81883709-8c139680-95b3-11ea-852c-59d3d748990c.png)

## Which results in a theme-change onClick: 
![image](https://user-images.githubusercontent.com/34197902/81883742-a5b4de00-95b3-11ea-8436-84e5bc583e63.png)
___

**What I want is to link the DOMs in a way that the state change reflects in the other DOM instance too, i.e. a mirror effect!**

I know it can be achieved in the same ReactDOM element. But for my specific purpose I have to create multiple ReactDOMs. 
- I want to have multiple mini apps on the same Html body sharing one single state store. 
- I don't want to stuff all of them in a single ReactDOM instance as they are totally unrelated, yet share a state, thus will cause unnecessary clutter.
- The app is too simple else I would've created a Realtime pub/sub service (Ably.js?) - but currently, it's intended to be a front-end only serverless app.
___
## What I expect in the replies:
- A way to link independent ReactDOM instances,
- Isn't it appropriate for React to merge all ReactDOM instances to one single virtual DOM? I myself felt that more intuitive than having independent DOM instances.
- What is the performance overhead of having multiple ReactDOM instances?

**Comment by kunukn** [comment]
I can give some answers. From my point of view :)

<br/>

> A way to link independent ReactDOM instances.

My approach would be store the state externally. Instead of using `useState` we could use a store. All DOM updates must be driven from update in the store.
`UI interaction -> update store -> update all ReactDOM instances.`

But what is the purpose to have multiple ReactDOM instances and then link them?
There is also `ReactDOM.createPortal` which can be used if the React nodes needs to exists in different places in the DOM.

<br/>

>Isn't it appropriate for React to merge all ReactDOM instances to one single virtual DOM? I myself felt that more intuitive than having independent DOM instances.

From performance point of view. Probably not.
The diffing is on the whole graph. If you are diffing 100 ReactDOM instances because you change something in one ReactDOM instance. That might be expensive?
Besides, the intent of having multiple ReactDOM instances is probably because you want multiple independent mini-apps.

<br/>

>What is the performance overhead of having multiple ReactDOM instances?

Maybe we could test and measure? 
I can see benefits of having multiple ReactDOM instances. If there are isolated and independent from each other. Then the cost of update is reduced to that one ReactDOM instance instead of the whole graph.

**Comment by illuminist** [comment]
Use redux to store app state. As long as redux store Provider is using the same redux store instance  it will be same state on both DOM tree.

**Comment by Cryptonex7** [comment]
> Use redux to store app state. As long as redux store Provider is using the same redux store instance  it will be same state on both DOM tree.

Absolutely thats an option and theoriticaly, it should work like a charm.

But since it is a very simple application, I was trying to avoid a redux setup - which is exactly why i have put this issue on React's repository because it involves an internal feature enquiry of React itself.

**Comment by illuminist** [comment]
I wouldn't say it's a very simple one if it's somewhat not something intended for usual app. Usually react app rely on single render tree or instance. I believe having react manage multiple instance will make its internal job more complicated and probably harder to reason with. Having each instance isolated from each other makes thing much simpler.

**Comment by kunukn** [comment]
>But since it is a very simple application, I was trying to avoid a redux setup

If it is a simple application and we want to avoid complex setup, then maybe using something like this could help?

Replace `useState` with `useGlobalState`

Here is a simple demo.
https://codesandbox.io/s/multiple-reactdom-instances-and-react-hooks-global-state-5g80b?file=/src/App.js

_This is based on some random library I found `react-hooks-global-state`_
