### ISSUE TITLE
Make mandatory to pass initial state in React.useState

### ISSUE THREAD

**Issue by acagastya** [facebook/react#18936]
Right now, it is possible to use hooks in order to set state for functional components as follows:
```js
function Foo() {
  const [state, setState] = React.useState();
}
```
There is no parameter passed to `useState` above.  If it is blank, React assumes it is `undefined`.  I think it would be an improvement to make it compulsory to pass a parameter to `useState`.  If it is supposed to be undefined, one should pass `undefined`.  Or at least, there should be a warning if one does not manually set initial state.

This will make the developers be aware of what initial state they have set.  And also the blunders like `const [state = initial, setState] = React.useState()`.

## Proposed way of doing 
```js
function Foo() {
  const [state, setState] = React.useState(initial);
}
```

**Comment by TodorTotev** [comment]
I don't think mandatory would be proper. Warning feels like okay though.

**Comment by acagastya** [comment]
@TodorTotev if it is not explicitly stated, it is taken as `undefined`.  Developers can manually set `undefined`.  But it would be a breaking change.  Other than that, I don't see a reason why that should be a problem -- But I welcome the opportunity to learn why you think otherwise.

But at the very least, warnings will be helpful.

**Comment by TodorTotev** [comment]
@acagastya I believe that the "beauty" of React is that its possible to do things in your own way, so "obliging" people to do something, at least from my perspective wouldn't be comfortable.

However, I am absolutely on your side about warnings, because when you are using something new and you are learning, warnings are really helpful telling you "this is the right way" or "that's how it should be done" so you can choose either to follow the "convention" route or do it as you wish and accept the consequences.

**Comment by irohitb** [comment]
Ahh. use typescript?

**Comment by illuminist** [comment]
Creating ESLint rules for this should do the job. But I'm kinda against it in general case. Except for when detecting `const [state = initial, setState] = React.useState()`

**Comment by acagastya** [comment]
I think an in-house warning should be good.  Not every developer is going to use ESLint or TypeScript and this could come handy.

**Comment by illuminist** [comment]
There are already dozens of issue that can be avoided by using ESLint, but not all of them are essential. Requiring `useState` initial state shouldn't be mandatory either if you know what you're doing. So that should be developer's choice to enable ESLint rules to detect if they're doing wrong, not to force them to follow such a minor detail.

**Comment by acagastya** [comment]
React has always added developer-friendly warnings to point out before devs would otherwise notice it.  And I think this is one of those instances.
