### ISSUE TITLE
Bug: parent will mount earlier than its suspending child 

### ISSUE THREAD

**Issue by MHA15** [facebook/react#18947]
React version: 16.3.1

## Steps To Reproduce

1. use data fetching with suspense in latest release version (not concurrent mode)
2. render a simple wrapper around SuspendingComponent as child of SuspenseBoundary 

[Link to code example](https://codesandbox.io/embed/react-suspense-before-concurrent-9854s?fontsize=14&hidenavigation=1&theme=dark)

## The current behavior
parent (wrapper around SuspendingComponent) will mount before child 

## The expected behavior
parent an child should mount after data received

**Comment by sophiebits** [comment]
I believe this is intended behavior for legacy (non-concurrent) mode, in order to preserve the invariant that if a render function completes successfully, then effects will run as well – the parent component is immediately hidden afterwards. In concurrent mode you'd see that the parent never completes mounting, which will be the future behavior, and it will be encouraged for anyone using data fetching with suspense to use concurrent mode or at least blocking mode: https://reactjs.org/docs/concurrent-mode-adoption.html#migration-step-blocking-mode.

(I'll remind you also that data fetching with suspense isn't officially supported yet.)

**Comment by Eddie-CooRo** [comment]
the @sophiebits
Why is this considered intentional?

If I understood correctly, the default behavior when we are not suspending anything is that the child hook runs before the parent. ([codesandbox](https://codesandbox.io/s/react-hooks-order-without-suspense-wex6y))

Also, when we throw an error in the child component, React never calls the effects of the parent component. ([codesandbox](https://codesandbox.io/s/react-hooks-order-with-error-7lpl7))

And the behavior with the suspense is also the same in the blocking mode, as you mentioned.

But the only case in which the effects execution order doesn't work this way is when we are suspending our component in legacy mode. Why do we consider the parent of a suspended component as if its rendered successfully?
I think the expected behavior is doing the same as what the ErrorBoundry does.

(I know that data fetching with suspense is not supported in legacy mode, and the API is subject to significant changes as well. I'm just trying to understand why the current behavior is intentional/more acceptable, even though we don't see it anywhere else in the legacy mode. and what sort of problems solving the issue would cause)
