### ISSUE TITLE
Bug: Input.Group select和input高度不一致

### ISSUE THREAD

**Issue by aiyudeleng** [facebook/react#18999]
![image](https://user-images.githubusercontent.com/31436484/82850456-0edf0e80-9f2f-11ea-84b1-a658149bd858.png)

antd 更新到 4.2.5，react 更新到 16.12.0后，发现Input.Group 高度不一致；并且Menu菜单项文字没有对齐

**Comment by bvaughn** [comment]
This does not look like a React bug. Maybe something with antd? Maybe something with your app? Hard to say since you didn't include any repro.

Looks like your query selector criteria is incorrect (not finding a match). You might try posting on Stack Overflow (or a similar site) but you'll want to include more information than you did here (like a complete runnable repro).
