### ISSUE TITLE
React.renderComponent fails on svg nodes (Firefox, IE)

### ISSUE THREAD

**Issue by ivo-** [facebook/react#1900]
When trying to mount component into `<svg>` node, React does nothing on Internet Explorer. On FireFox it appends the elements without the proper SVG namespace.

http://jsfiddle.net/z3BQS/1/

**Comment by gaearon** [comment]
React now uses `createElement` instead of `innerHTML` for the initial mount, and also respects the SVG namespace for any elements inside `svg` so it should be solved now.

The original fiddle, updated for React 15 API, now works correctly in IE for me with React 15 RC2: http://jsfiddle.net/z3BQS/1/

<img width="975" alt="screen shot 2016-03-18 at 20 57 51" src="https://cloud.githubusercontent.com/assets/810438/13891964/4811054e-ed4c-11e5-9fb7-47fadbc46739.png">

I’m closing but please let me know if I missed something.
