### ISSUE TITLE
Bug: document.querySelector('#meterListTableContent .ant-table-body').scrollTop = (num !== undefined ? num : 0);

### ISSUE THREAD

**Issue by aiyudeleng** [facebook/react#19000]
![image](https://user-images.githubusercontent.com/31436484/82856056-a2204000-9f3f-11ea-961f-2a500f91f44f.png)

升级antd 和react 之前，table的scrollTop是这样写的，`document.querySelector('#meterListTableContent .ant-table-body').scrollTop = (num !== undefined ? num : 0);`

后来antd 升级到 4.2.5，react升级到16.12.0，启动报错。`Unhandled Rejection (TypeError): Cannot set property 'scrollTop' of null`

修改成 `document.querySelector('#meterListTableContent .ant-table-tbody').scrollTop = (num !== undefined ? num : 0);` 后可以正常运行

是什么原因造成的？

**Comment by bvaughn** [comment]
This does not look like a React bug. Maybe something with antd? Maybe something with your app? Hard to say since you didn't include any repro.

Looks like your query selector criteria is incorrect (not finding a match). You might try posting on Stack Overflow (or a similar site) but you'll want to include more information than you did here (like a complete runnable repro).

**Comment by bvaughn** [comment]
Note looks like an issue was also filed against antd

https://github.com/ant-design/ant-design/issues/24442

**Comment by aiyudeleng** [comment]
Sorry，i don't notice  that i asked in react. I fixed it by setting input's height 'auto', so it maybe a Antd bug, but i still don't why it happened
