### ISSUE TITLE
[eslint-plugin-react-hooks] Add whitelist for functions that are not to be considered as callbacks

### ISSUE THREAD

**Issue by xaviergonz** [facebook/react#19056]
I have a library to hook mobx with react: https://github.com/xaviergonz/mobx-react-component

Hooking is usually done via a wrapper method named "mobxObserver" and is used like this:

```ts
export const MyComponent = memo(
    mobxObserver(
        (props: IMyComponentProps) => {
          // React.useLayoutEffect(...) // will warn
        }
))
```

however as soon as a hook is used inside the component the eslint rule-of-hooks will warn with:
```
React Hook "React.useLayoutEffect" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.
```

If a named function is used it works, but it is far from ideal (e.g. name repetition):

```ts
export const MyComponent = memo(
    mobxObserver(
        function MyComponent(props: IMyComponentProps) {
          // React.useLayoutEffect(...) // won't warn
        }
))
```

Would it be possible to have a custom whitelist of methods that are allowed to wrap the functional component without raising this warning? (same as React.memo is whitelisted right now)

E.g. something like:
```
allowedWrappers: [ "mobxObserver" ] 
```

Or even better, do not consider a callback something that is just wrapping the functional component, but I'm not sure if that's feasible.

Thanks.

**Comment by OliverJAsh** [comment]
As a workaround to the problem of not being able to call a hook conditionally, I am using the following workaround which wraps the hook into a conditional component call via a render prop:

```tsx
const RenderFunction = ({ children }) => children();

const MyComponent = ({ someBoolean }) => {
  const commonProps = {
    children: <span>Hello, World</span>,
  };
  return someBoolean ? (
    <RenderFunction>
      {() => {
        const onClick = React.useCallback(() => {
          console.log('clicked!');
        }, []);
        return <div {...commonProps} onClick={onClick} />;
      }}
    </RenderFunction>
  ) : (
    <div {...commonProps} />
  );
};
```

IIUC, this is perfectly safe because the `children` render prop callback is called every time the `RenderFunction` component is called, yet the ESLint rule throws an error.

It would be great if there was a way to tell the ESLint rules that this is safe.

**Comment by xaviergonz** [comment]
Bump

**Comment by frabbit** [comment]
Using `function _ ()` instead of `() =>` seems to be fine with eslint.
```js
const RenderFunction = ({ children }) => children();

const MyComponent = ({ shouldRenderHook }) =>
  shouldRenderHook ? (
    <RenderFunction>
      {function _ () {
        const [state, setState] = React.useState(0);
        return (
          <div>
            State: {state}
            <button onClick={() => setState(currentState => currentState + 1)}>
              Increment
            </button>
          </div>
        );
      }}
    </RenderFunction>
  ) : (
    <div>Rendering the hook shortly…</div>
  );
```

**Comment by eps1lon** [comment]
> If a named function is used it works, but it is far from ideal (e.g. name repetition):

I'd argue that this is good nudging behavior since it will result in better display names in devtools. `someHoC(() => <div />)` will not have a display name. Error messages, component trees in devtools etc will always list it as "Unknown" or "Anonymous". 

So if you spell it out with `someHoC(function MyFancyComponent() {})` you'll be able to find it in devtools again under `MyFancyComponent`.

With the same reason you should call `forwardRef` with a named function expression instead of an arrow function.

**Comment by Lucienest** [comment]
What's the status of this Issue?
