### ISSUE TITLE
Bug: React Function getting called for no Reason

### ISSUE THREAD

**Issue by aman-singal** [facebook/react#19065]
React version: ^16.13.1

## Steps To Reproduce

1. Click on Task 1
2. Check the dsdfdsf tab,and check it
3. Click on Create a new Task 
4. create a new task

Link to code example:

 https://github.com/aman-singal/Recact_todoList
-->

## The current behavior
When adding a new task, The last used function of a different component gets called for no reason. The milestone of the list gets cleared when adding a new Task

##  The expected behavior
The Function shouldn't be called, the already existing List shouldn't be cleared

**Comment by illuminist** [comment]
Your code already has a dozen of other problem already and they chain up to multiple issue in your app, what you reported is also one of them.

The main reason is you mutated an object in your reducers. Reducer supposed to not return the original object if some of its property inside is changed. Also applies to deeper object as well. Better use `immer` or `redux-toolkit` to help properly mutating the object.

**Comment by aman-singal** [comment]
@illuminist There is no as such error in the code, there are some use case warning which can be ignored. Also, I am not mutating any state inside the reducer. I think you misunderstood it.  I have tried using the debugger to find out the source of the problem and it traces back to react-development.js every time

**Comment by illuminist** [comment]
There is no error, but doesn't mean it works as intended. I understand about using `debugger`. The main reason is what I describe before: **you broke the rule about using reducer to change your data** and that is.

**Comment by aman-singal** [comment]
I didn't understand what do you mean by "### using a reducer to change your data" I think that react reducer main purpose is to change the state and also I am not mutating the state directly, I am creating a new object which I am returning to the reducer. Moreover, that has nothing to do with the current problem. I request you to please stop confusing or create a diversion from the issue if you fail to understand the issue that doesn't mean that there is no issue.

**Comment by bvaughn** [comment]
Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

##### Coding Questions

If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

[https://stackoverflow.com/questions/tagged/react](https://stackoverflow.com/questions/tagged/react)

##### Talk to other React developers

There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

[https://reactjs.org/community/support.html](https://reactjs.org/community/support.html#popular-discussion-forums)

**Comment by illuminist** [comment]
@aman-singal That IS the issue.
```js
let newState = state
```
You wasn't creating a new object, you assigned the same object into a new variable. When you return the `newState` it will be the same object as the previous state and react will not recognized the change because they are the same object, by reference.

The actual creating new object is
```
let exampleState1 = {...state}
let exampleState2 = Object.assign({}, state)
```
which still works on one level deep object where deeper objects are still the same reference. If you want to mutate then you have to clone an entire object with lodash's cloneDeep or use `immer` to help mutating an object.

What make it worse is [src/index.js#L138](https://github.com/aman-singal/Recact_todoList/blob/853ad75a568ad4c04fc9f35a14db6b6c3f88c4e2/src/index.js#L138) is calling side effect inside of reducer so that is the SECOND rule breaker in your reducer.

When you do this, it created an unexpected behavior on react internal that it will try to dispatch again because your reducer has also changed its instance. Usually react will dispatch the action against previous state when reducer change instance and it try to reinitialize `useReducer` which it will be fine in normal circumstance. **This is where you see the issue and you report this to this github issue.** But the root of problem isn't what you saw, your current state and previous state are the same object with mutation so things started to go wrong from there.
