### ISSUE TITLE
Bug: Error loading hook component dynamically

### ISSUE THREAD

**Issue by liaokeweip** [facebook/react#19098]
```javascript
function Placeholder(props: Record<string, any>) {
    const { path, impl,  ...arg  } = props;
    const [Component, setComponent] = useState('div');
    useEffect(() => {
        const url = `${path}/${impl}`;
        import(`@/pages${path}/${impl}`).then((res) => {
            let { default: component } = res;
            setComponent(component);
        }).catch((e)=>{
            console.log(`not find ${path}/${impl}`);
        });
    }, []);
    return Component ? <Component {...arg} /> : null;
};

export default Placeholder
```
Referencing this component into the hook component will report an error

**Comment by kunukn** [comment]
This version works. 

```jsx
import React, { useState, useEffect } from "react";

function Placeholder({ path, impl, ...arg }) {
  const [State, setState] = useState({ Component: "div" });
  useEffect(() => {
    let filepath = `${path}/${impl}`;
    import(filepath )
      .then(res => {
        let { default: component } = res;
        setState({ Component: component });
      })
      .catch(error => {
         console.log(`could not find ${filepath }`);
      });
  }, [path, impl]);
  return State.Component ? <State.Component {...arg} /> : null;
}

export default Placeholder;
```

Demo:
https://codesandbox.io/s/reactjs-lazy-load-dynamically-components-emwve?file=/src/App.js

**Comment by samcooke98** [comment]
FWIW - "report an error" is very vague..

---

When I make a repo case, and log the error, I get the following; 
![image](https://user-images.githubusercontent.com/787007/87864656-393ccd80-c9ae-11ea-92bb-60c27ffe36d0.png)

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <div />. Did you accidentally export a JSX literal instead of a component?
```

Remember that React components are just functions. So when the following line run;
`setComponent(component)` component is called, and the result of that is stored.

This is because `setState` can be in the form of; `setState(someValue)` or `setState(currentState => newState)`
In this second case, the argument is a function. In your "buggy" code, React calls `component` and stores the result of `component`... which is a react node, which can't be passed. 

---

You have a few options to fix this. As you've noticed, you can store an object, which causes react to store the object. Alternatively, you could do; 
`setComponent(() => component);`


https://codesandbox.io/s/reactjs-lazy-load-dynamically-components-d34p5?file=/src/Placeholder.js:1035-1074



So this isn't a bug. Let me know if any of this isn't clear.

**Comment by kunukn** [comment]
Related issue: 
https://github.com/facebook/react/issues/17539

I should have included this reference earlier. 
I had time to post a version that work, but I didn't had the time to give an explanation. 

This seems to be one of the "gotchas" developers has to be aware of when putting components in a state.

I am not sure whether this error message helps when this error happens.
>Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <div />. Did you accidentally export a JSX literal instead of a component?

Maybe we could add something more?
>Did you accidentally put a component in a state as a function?

**Comment by eps1lon** [comment]
It sounds like you put a function component into state. The issue is that `useState` considers a function as a ["lazy initializer"](https://reactjs.org/docs/hooks-reference.html#lazy-initial-state),  calls this function and uses the returnvalue as the initial state. The state setter considers function as ["functional updates"](https://reactjs.org/docs/hooks-reference.html#functional-updates) so you'd have to wrap that in a function as well as [@samcooke98  suggested](https://github.com/facebook/react/issues/19098#issuecomment-660566029).

> Maybe we could add something more?

>>Did you accidentally put a component in a state as a function?

Considering the age of this issue and its activity it sounds like this is a very rare case. The warning would probably be distracting. Especially since React.lazy is the recommended way of lazy loading components.

An extra warning in https://reactjs.org/docs/hooks-reference.html#usestate about function in state might be more appropriate. But then again: If this is a very rare use case it might be distracting. Let's continue this discussion about better docs in https://github.com/reactjs/reactjs.org/issues/3216 since React can't know the semantics of a function.
