### ISSUE TITLE
Feature Request: linter for hook order like sort-comp

### ISSUE THREAD

**Issue by daveisfera** [facebook/react#19149]
[`sort-comp`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md) is really nice for making the ordering of a component be consistent. Something similar for ordering hooks would be nice to have as well, so this is requesting such a feature be added

**Comment by vkurchatkin** [comment]
You can't generally sort hooks since they can depend on each other.

**Comment by daveisfera** [comment]
Ya, but that dependency is "defined by the code" isn't and doing something as simple as sorting them "alphabetically by variable" shouldn't change anything, should it?

**Comment by bvaughn** [comment]
The React repo probably isn't the place for this type of request. With the exception of the the ESLint hooks plug-in to warn against common mistakes in hooks usage, we don't really maintain ESLint rules- and we don't maintain anything to do with the formatting of code.

I also agree with @vkurchatkin's observations that any variable usage (including variables that store values returned by hooks) can't really be "sorted" in the way you describe, because of dependencies between variables.

**Comment by daveisfera** [comment]
Ya, I just made it hear because of the eslint plugin for hooks living here. Is there somewhere that you'd recommend something like this to be considered?

**Comment by bvaughn** [comment]
No idea, really. 😅  Just wanted to clarify that this is not something the React team should own.

I'm going to close this issue since it's not really actionable in this repo.
