### ISSUE TITLE
Bug: ESLint react-hooks/exhaustive-deps rule does not catch missing dependency for useCallback without a lambda

### ISSUE THREAD

**Issue by mradamczyk** [facebook/react#19173]
React version: 16.3.1

## Steps To Reproduce

In code like below:
```
export interface IFooBarProps {
    fn: (a: string) => (b: string) => void;
    foo: string;
}

const FooBar: React.FC<IFooBarProps> = ({ fn, foo }) => {
    /* ... */
    const callback = React.useCallback(fn(foo), [foo]);
    /* ... */
}
```

the rule does not catch missing `fn` dependency. Such missing dependency is found properly, when `useCallback` is rewritten with a lambda:

```
const callback = React.useCallback((bar: string) => fn(foo)(bar), [foo]);
// error  React Hook React.useCallback has a missing dependency: 'fn'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

## The current behavior

Rule does not find missing dependency.

## The expected behavior

Rule should find missing dependency.

**Comment by georeith** [comment]
```js
React.useCallback(fn(foo), [foo]);
```
and

**Comment by georeith** [comment]
```js
React.useCallback(fn(foo), [foo]);
```
and 
```js
 React.useCallback((bar: string) => fn(foo)(bar), [foo]);
```
are not equivalent.

In the first case you are immediately invoking `fn(foo)` and passing its return value to `useCallback`, thus neither `fn` or `foo` are dependencies of the `useCallback` unless you are returning a function from `fn(foo)` which uses them (the linter won't catch that case as it is likely unable to statically determine what the return of `fn(foo)` will be).

In the second case you are passing in a function which uses them and thus they are dependencies.

`fn(foo)` will be called every render in the first example.

**Comment by rachelnabors** [comment]
Hey hey, so when I tried this out, I got a message: `React Hook useCallback received a function whose dependencies are unknown. Pass an inline function instead. (react-hooks/exhaustive-deps)` as you can see in [this CodeSandbox](https://codesandbox.io/s/cranky-wave-o32l8?file=/src/App.js). It sounds like you're using an older version of the plugin. If you use Create React App, you'll need to wait till the next major version otherwise update the plugin manually.

If this is not the case, please file a new issue with more version information (and even better, a reproducing project). Thank you :)
