### ISSUE TITLE
Bug: Objects are not valid as a React child

### ISSUE THREAD

**Issue by photocherkaoui** [facebook/react#19231]
I use the latest React version on Windows 10.

I followed a tutorial where I was introduced to props but unfortunately, I get an error in the h1 tag regarding React child:

```js
function Welcome (props) {
        
        return <h1> {props.name} </h1>;
        Welcome.propTypes = {
            name: PropTypes.string.isRequired
          }
       
      }
```

Thank you for your recommandations

**Comment by Peeja** [comment]
Hmm, I wouldn't expect the error you're seeing, but it does look to me like the code's not quite right. But the formatting is a little off, so it's hard to be sure. Let me confirm. It looks like this is the code you're running:

```js
function Welcome (props) {
    return <h1> {props.name} </h1>;
    Welcome.propTypes = {
        name: PropTypes.string.isRequired
    }
}
```

I would expect that to run without errors, but the `propTypes` won't work. That's because you've got that inside your function definition, and after the `return`, so it will never run (and if it did, it would set the `propTypes` as the component is rendering, which is far too late). What I think you're actually after is this:

```js
function Welcome (props) {
    return <h1> {props.name} </h1>;
}

Welcome.propTypes = {
    name: PropTypes.string.isRequired
}
```

That is, you define a function `Welcome`, and then set the property `propTypes` of that function. I don't know if that will solve the problem you're seeing, because I'm surprised it was reporting the error you saw, but it will at least solve a different problem you haven't hit yet. :)

**Comment by gaearon** [comment]
@Peeja Thanks for responding! That looks right.
