### ISSUE TITLE
Feature proposal: Hook equivalent to createSlice from Redux Toolkit?

### ISSUE THREAD

**Issue by pdcribeiro** [facebook/react#19256]
Would this be useful?

> A function that accepts an initial state, an object full of reducer functions, and a "slice name", and automatically generates action creators and action types that correspond to the reducers and state.

From [createSlice](https://redux-toolkit.js.org/api/createSlice).

**Comment by rickhanlonii** [comment]
Hey @pdcribeiro thanks for the idea!

Is there a reason you think this should be in core instead of a separate package?

**Comment by pdcribeiro** [comment]
Hey @rickhanlonii thanks for the feedback :)

I'm a beginner so this is quite an uninformed suggestion but it would avoid the boilerplate code associated with using useReducer().

I'm thinking it would make sense to include it in core if useReducer() is frequently used along with code similar to the one abstracted by createSlice(). However, I don't know if this is the case or if this hook is commonly used in a different way.

**Comment by pdcribeiro** [comment]
Hey @rickhanlonii thanks for the feedback :)

I'm a beginner so this is quite an uninformed suggestion but it would avoid the boilerplate code associated with using useReducer().

I'm thinking it would make sense to include it in core if useReducer() is frequently used along with code similar to the one abstracted by createSlice(). However, I don't know if this is the case or if this hook is commonly used in a different way.

**Comment by rickhanlonii** [comment]
@pdcribeiro thanks again for the idea!

There are a couple reasons I don't think this makes sense to live in core. One, I think that the concepts of action creators and action types are redux specific and are not common in vanilla React apps (though they could be). Two, `createSlice` could be created in userland, so there's no requirement that they live in core.

I'd encourage you to create and publish a vanilla React `createSlice` package and see if the community adopts it!

**Comment by markerikson** [comment]
As the author of RTK and `createSlice`, I agree that this doesn't need to be in React at all, for multiple reasons:

- There are many ways to write reducer functions
- Unlike Redux, `useReducer` doesn't require that the "action" you dispatch is a Redux-style action object (or even an object at all)
- Action creators are an abstraction layer that isn't necessary even with Redux, although it's one we recommend for Redux usage
- RTK's `createSlice` specifically depends on Immer, and while Immer's great, it's not something that React should depend on

Having said all that, you can absolutely use RTK's `createSlice` to generate reducers that can be passed to `useReducer`, because a reducer is _just_ a function and has no actual dependency on a Redux store (and use of `createSlice` by itself should tree-shake the other RTK APIs you aren't using from your bundle).

**Comment by pdcribeiro** [comment]
Thank you both for the clarification :)
