### ISSUE TITLE
Which approach is better for getting data from state ?

### ISSUE THREAD

**Issue by NeerajNegi** [facebook/react#19298]
Let's say our state is as follows:
```
state: {
    user: {
        name: 'Dave',
        email: 'Dave@gmail.com'
    }
}
```

so while getting the user property from the state which one of the following should I do?

**Case 1:**

```
const user = this.state.user

this way following is valid
user == this.state.user //true
user.name = 'Manny';
console.log(this.state.user.name) //Manny
```
though it won't cause re-render until we use setState() but basically the value of the state variable has changed.

**Case 2:**

```
const user = { ...this.state.user};

this way
user == this.state.user //false
user.name = 'Manny';
console.log(this.state.user.name) //Dave
```

Which approach is better or are there any side effects of any of them?

**Comment by bvaughn** [comment]
Neither approach shown above is recommended, because both are mutations- and React data (props/state) [should not be mutated](https://reactjs.org/docs/react-component.html#state).

The second example is "better" then, in that you're shallowing cloning the user object, but it's still dangerous because:
1. The cloning is only shallow so any nested objects would be mutated.
2. Mutations won't trigger re-renders, so it's unclear what the purpose of this is.

The recommended approach is:
```js
const user = this.state.user;
this.setState({
  user: {
    ...user,
    name: "Manny",
  },
});
```
