### ISSUE TITLE
Bug: Unexpected debugger statement in DevTools (solved)

### ISSUE THREAD

**Issue by eiamei** [facebook/react#19308]
Looks like you forgot about the debugger inside the react_devtools_backend.js. 

React dev tools version: 4.8.0

## Steps To Reproduce

1. Update (or install) the latest version of devtools
2. Open devtools
3. The code will be stopped on the debugger inside react_devtools_backend.js

![IMAGE 2020-07-10 13:43:52](https://user-images.githubusercontent.com/20472264/87146286-6523c900-c2b3-11ea-892f-92c01d0a2412.jpg)

## The current behavior
If I open devtools with react dev tools extension it will stop every time on debugger inside react_devtools_backend.js

## The expected behavior
It doesn't seem like it should be happening 😃

**Comment by JakubRimal** [comment]
Same here, I've had to disable the extension because of this... :smile:

**Comment by martinhorsky** [comment]
Same for me.

**Comment by gaearon** [comment]
Looks bad.

**Comment by antislash21** [comment]
Same here

**Comment by Lukortech** [comment]
https://github.com/facebook/react/blob/14084be286d09df49d5410c751bc28f0180a54b2/packages/react-devtools-shared/src/backend/console.js#L173

That's the guy you're looking for :D

**Comment by gaearon** [comment]
Yes, but see the comment above it. :-) It is intentional, but this option should have been off by default.

**Comment by przemuh** [comment]
As a temporary solution you can "blackbox" script in Chrome Dev Tools:

![image](https://user-images.githubusercontent.com/3865478/87158097-7e327700-c2bf-11ea-86ea-68013efcbd5c.png)

**Comment by gasparsigma** [comment]
Temporary workaround if you don't want to disable the extension is to directly edit the src of the extension:
C:\Users\[Your User]\AppData\Local\Google\Chrome\User Data\Default\Extensions\fmkadmapgofadopljbjfkapdkoienihi\4.8.0_0\build\react_devtools_backend.js
You can just remove the debugger for that line

**Comment by gaearon** [comment]
You should also be able to go to Components tab, press Settings gear, add checkbox to Break on Warning, then do this again, and remove the checkbox as a temporary workaround.

**Comment by gaearon** [comment]
I'll keep it open until we cut a release

**Comment by eiamei** [comment]
Thanks 🙌

**Comment by gaearon** [comment]
I've submitted a fix to Chrome addons. It should appear there in a few hours. If it doesn't work after updating to 4.8.1, try to clear your local storage (`localStorage.clear()`).

I can't figure out how to submit it to FF store because something in our process has changed. So @bvaughn will be able to help us out there when he wakes up. :-)

**Comment by gaearon** [comment]
Here's a step-by-step instruction for how to work around it while the fix is pending review:

1. Press the Settings gear icon in the upper right corner

<img width="1161" alt="Screenshot 2020-07-10 at 14 39 06" src="https://user-images.githubusercontent.com/810438/87160653-37db1900-c2bb-11ea-9806-07cea49660ed.png">

2. Open the Debugging tab

<img width="1275" alt="Screenshot 2020-07-10 at 14 39 13" src="https://user-images.githubusercontent.com/810438/87160687-432e4480-c2bb-11ea-8b06-2444ade200e8.png">

3. Put the checkmark next to **Break on Warnings**
<img width="1273" alt="Screenshot 2020-07-10 at 14 39 20" src="https://user-images.githubusercontent.com/810438/87160706-4a555280-c2bb-11ea-91ab-8dd887a67150.png">

4. Remove the checkmark next to **Break on Warnings**

<img width="1286" alt="Screenshot 2020-07-10 at 14 39 25" src="https://user-images.githubusercontent.com/810438/87160738-57724180-c2bb-11ea-9bac-d181daf6ab8b.png">


Now reload the page and you shouldn't be bothered by it.

**Comment by raphaellopes** [comment]
Same here

**Comment by gaearon** [comment]
Please refrain from "same" comments unless you have something new to say. They are not helpful and obscure the solution (https://github.com/facebook/react/issues/19308#issuecomment-656682924).

**Comment by bvaughn** [comment]
Update:
* The fix has been published to NPM as 4.81
* The updated extension (with fix) is live for Firefox
* The updated extension is pending for Chrome
* Edge is still providing the previous version 4.7 (but an updated 4.8.1 is also pending for review)

**Comment by RenatoParker** [comment]
Same problem here!

**Comment by bvaughn** [comment]
We'll keep this issue open until the fix has been deployed on Chrome, but I'm going to lock it to prevent +1 😄

**Comment by bvaughn** [comment]
4.8.1 is live in Chrome store now too, so I'm going to close this.
