### ISSUE TITLE
Bug: componentDidMount not called when components are swapped

### ISSUE THREAD

**Issue by paulmand3l** [facebook/react#19304]
React version: ^16.12.0

## Steps To Reproduce

1. Initialize app with npx create-react-app
2. Write code that swaps two elements (see code example)
3. Observe log and note that componentDidMount is only called on the first element

Link to code example: https://repl.it/repls/FrizzyUnnaturalValue#src/App.js

## The current behavior

componentDidMount is not executed for the new element when elements are swapped

## The expected behavior

componentDidMount should be executed on the new element when the elements are swapped

**Comment by bvaughn** [comment]
The repro link doesn't run because of warnings that stop the build process.

**Comment by bvaughn** [comment]
This looks like a misunderstanding.

React sees the two `Image` components as the same component because in both cases the `Swapper` component renders a single child, `Image`. So all React does after the "swap" is update the props passed in. Generally *this would be a good thing* because it's faster to update something than to recreate it.

If you want to make React see them as separate, you can [use a `key`](https://reactjs.org/docs/lists-and-keys.html#keys):
```js
function App() {
  return (
    <div className="App">
      <Swapper>
      { swap => ([
        <Image 
        key="1"
        src='http://static.mand3l.com/project-thumbs/solidus.png' onClick={swap} />,
        <Image 
        key="2"
        src='http://static.mand3l.com/project-thumbs/touchstone.png' onClick={swap} />,
      ]) }
      </Swapper>
    </div>
  );
}
```

I wrote about a related issue some time ago on the React blog that you might find interesting:
https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#anti-pattern-erasing-state-when-props-change
