### ISSUE TITLE
React DevTool isn't working on both Chrome and Firefox

### ISSUE THREAD

**Issue by itsbek** [facebook/react#19382]
I have added on the extension on my windows 10pro to Firefox 78.0.2 (32-bit) browser. However, it didn't worked even on the Facebook page itself. I tried uninstalling the extension clear cache and reinstall it, but it didn't help either.

Then I added on my Chrome 84.0.4147.89 (Official Build) (64-bit) browser and allow access to URLs - but nah, it didn't helped, too.

Last, I deleted the extension from both browsers and installed from terminal through # NPM
npm install -g react-devtools command - it didn't work too

I am a newbie to coding, all I  did was a research on the web but couldn't find a solution to this yet. I would appreciate any help on this perhaps Ive missed smth important

**Comment by sesifer** [comment]
I've got the same problem.
React DevTool info says that the tool is running >>This page is using the production build of React. ✅
Open the developer tools, and "Components" and "Profiler" tabs will appear to the right.

But "Components" and "Profiler" are not presented. I tried to reinstall it, restart, everything. Sometimes it works for few minutes and then the tools are gone again.

Chrome Version 83.0.4103.116 (Official Build) (64-bit)
Win 10
React DevTools v 4.8.2 (7/15/2020)

**Comment by bvaughn** [comment]
Latest Chrome stable version is 83.0.4103.116. There's a known Chromium bug ([1085215](https://bugs.chromium.org/p/chromium/issues/detail?id=1085215)) that causes extensions (including React DevTools) to sometimes not appear in the developer tools console (see #19002). The fix for this is in Chrome and [will be released in v84](https://bugs.chromium.org/p/chromium/issues/detail?id=1093731#c17). (You can verify the fix in Chromium in the meanwhile if you'd like.)

I have not heard of any reports of problems with the Firefox extension though, nor can I reproduce the behavior you describe by installing in Firefox myself.

**Comment by bvaughn** [comment]
>Last, I deleted the extension from both browsers and installed from terminal through # NPM
npm install -g react-devtools command - it didn't work too

I'm not sure I see how this connects to the browser extensions. What do you mean by "didn't work"? I assume the DevTools opened, but didn't connect to the React app running in your browser- which would be expected unless you also [added a `<script>` tag to your app](https://github.com/facebook/react/tree/master/packages/react-devtools#usage-with-react-dom).

**Comment by itsbek** [comment]
The issue was resolved!!! Thanks everyone!

I don't know how does node affects the extension but i tried to uninstall the node.js 12.18.2LTS > removed the React devTools extension > clear files from temp and %temp% on the command line,  and reinstall the same version (12.18.2LTS) and added back the React DevTool extension which worked out this time for both browsers.
