### ISSUE TITLE
Running two copies of React on a page can give errors because both use ID '.0'

### ISSUE THREAD

**Issue by spicyj** [facebook/react#1939]
Maybe we can do something smarter with the root index generation on the client side? Seems like this should work.

**Comment by danvk** [comment]
@ryanseddon this solution no longer seems to work. It _does_ change the attribute, but I get the following error:

`Uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.2): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID.`

I'd love a workaround for this—it makes it impossible to distribute a JS library which uses React.

**Comment by goofballLogic** [comment]
+1 this is a critical use case in a company i am working with.

**Comment by ryanseddon** [comment]
I just tried this out, you need to update the attribute __before__ you require react and it doesn't throw and works as expected.

```js
require('react/lib/DOMProperty').ID_ATTRIBUTE_NAME = 'data-myproductid';
var React = require('react');
```

**Comment by danvk** [comment]
@ryanseddon :+1: that did the trick. Note that you really have to make sure to do the monkey-patching before any of your code does `require('react')`, or else things will break. The first place may not be where you expect.

I wound up making a little shim:

```javascript
// react-shim.js
// See https://github.com/facebook/react/issues/1939
require('react/lib/DOMProperty').ID_ATTRIBUTE_NAME = 'data-myid';
var react = require('react/addons');
module.exports = react;
```

and replaced all `require('react')` statements with `require('./react-shim')`.

**Comment by charltoons** [comment]
@ryanseddon 's solution works if you are looking to create multiple top level entry points, basically multiple React.render()s. My use case was a pastiche site where some sections were written in React, some were another legacy framework. I wanted each section to be modularly responsible for its own React.render so that they could be removed or swapped around at will. So far, its working well, even the event system.

**Comment by dvdplm** [comment]
Maybe I'm thick, but it seems like @ryanseddon's solution to this requires using requirejs and a non-production (non-minified) version of react? What if I load react from `https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.min.js`, how do I go about poking in the bowels of `DOMProperty`? Is that even possible?

Given how many of us there are experiencing pain caused by this, and the relative difficulty of a definitive fix, would a PR exposing a way to set the id attribute name be welcome? Something along the lines of `React.setIdAttributeName("flowers-and-peace");`

**Comment by jeberly** [comment]
+1 to @dvdplm

**Comment by dvdplm** [comment]
I added two PRs (one from 0.13.3, the other off current tip) to make the ID_ATTRIBUTE_NAME configurable with `React.setIdAttributeName("data-my-own-private-reactid");`. This must be called before any rendering occurs naturally.
PR for 0.13.3: https://github.com/facebook/react/pull/4668
PR for master: https://github.com/facebook/react/pull/4669

**Comment by dlopuch** [comment]
+1

Major vendors are now starting to package embeddable widgets built on React.  We've encountered the `Invariant Violation: ReactMount: Two valid but unequal nodes with the same 'data-reactid'` error using Zendesk's embeddable widget -- their React packaging's DOM was interfering with our React packaging's DOM (via an event handler, if that helps).

It's completely valid to package your own distro of React if you're building a browser extension or an embeddable widget imho.  With more and more adoption of React, there should be an easy `React.setIdAttributeName()` so different vendors can play nice with each other on the same site.

**Comment by dvdplm** [comment]
@dlopuch that is very similar to our situation and I agree wholeheartedly. :)

**Comment by spicyj** [comment]
I understand this is a problem. Are your DOM trees nested within each other or completely separate?

**Comment by dlopuch** [comment]
Separate in my embeddable widget case (these things often ask you to put a script in your head which bootstraps their own app and injects a new div into your body).

The ID_ATTRIBUTE_NAME workaround fixed it, but it should be easier to do with some docs telling embeddable and extension developers how/why to use it.

**Comment by spicyj** [comment]
Off the top of my head I'm not sure how that causes problems. Do you know when that error is triggered? (In response to some event handler or something else?)

**Comment by dlopuch** [comment]
Happens in response to a mouseover.

We have two React's on our site -- the embedded widget's react and our react.  There are two elements that have `data-reactid=".2"` in the DOM, one created by the embedded widget's react and one created by our react.

The full stacktrace is:

```
Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .2
    at invariant (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:20302:15)
    at Object.getID (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:12433:43)
    at Object.ReactMount.isRenderedByReact (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:13024:25)
    at ReactMount.getFirstReactDOM (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:13039:22)
    at Object.EnterLeaveEventPlugin.extractEvents (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:2442:9)
    at Object.EventPluginHub.extractEvents (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:2863:46)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:11236:33)
    at handleTopLevelImpl (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:11329:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:18402:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (https://local.datahero.com/js/lib/react-with-addons-0.13.3.js:9669:19)
```

Error happens when we mouseover on the embedded widget's element.  `react-with-addons-0.13.3.js:12433:43` (the `getID()` function) is a bit weird -- it's in our React's context, `cached` resolves to our reactid=.2 element, but `node` is a node from the other React, the one we're mousing over.  

If it matters, the other React's node that we're mousing over is an iframe.

Hope this helps.

**Comment by ryanseddon** [comment]
@dlopuch this is a small world, I'm the tech lead on the Zendesk widget. I created a [test case](https://jsfiddle.net/69z2wepo/14953/) reproducing the error. It definitely seems related to the fact that our widget creates an iframe and shares a `data-reactid` with the host page. We'd love the exposed api to namespace the data attribute react uses.

**Comment by Halama** [comment]
I have exactly the same issue with Zendesk widget. Thanks for suggesting `ID_ATTRIBUTE_NAME` trick! it worked for me. 

I wasn't able to make it work with React Hot loader because it requires `react` at the beginning. So I inject it only for production https://github.com/keboola/kbc-ui/commit/756b9ddd1c820d1ca3ee08b8143922cd9db1d7c3

**Comment by gisenberg** [comment]
Hey folks,

Hate to resurrect an old issue, but the `ID_ATTRIBUTE_NAME` trick only seems to work in some cases. If you add an onClick to an element in the render method of a React class after using `ID_ATTRIBUTE_NAME = 'data-foo'`, you'll end up with an 'Unable to find element' error at runtime. Directly modifying `DOMProperty.js`'s assignment of `ID_ATTRIBUTE_NAME` resolves the issue.

This scenario is important because it's impossible to use a shared React component in a large multi-tenant system where different versions of React might already have been included on the page. I'm left wondering if I missed something or if there isn't a better way to solve this, since it seems that the only way to solve it right now is to fork React to change `DOMProperty`.

**Comment by dvdplm** [comment]
> the only way to solve it right now is to fork React to change DOMProperty.

This is what we are doing and we've had no issues since. It is very far from ideal but so far it has been the only workable solution.

**Comment by johanneslumpe** [comment]
Still seeing this issue, this time related to the Grammarly plugin. Tried to change `ID_ATTRIBUTE_NAME` in our build of react, but it didn't help at all. Still getting an invariant error about two valid but unequal nodes. Not sure if this is the correct thread to report this, but I feel it's related. The original bug report around Grammarly was done here: https://discuss.reactjs.org/t/invariant-failures-due-to-chrome-extensions-that-also-use-react/1765

**Comment by hakunin** [comment]
@spicyj This issue is just horrible, but so easy to fix as @dvdplm pointed out! I spent all day trying to figure this out, trying to compile React at the moment and I can't even install the dependencies :(
