### ISSUE TITLE
Bug:  this.refs isn't updating when the DOM element it refers to updates

### ISSUE THREAD

**Issue by yaswanthmangalagiri** [facebook/react#19429]
React version:

## Steps To Reproduce

1.  Creat a React App. 
2, Create a `Task.js` file and use the following code and import it in the `App.js` . 
```
 import React from 'react';
class Task extends React.Component{

	changeClassName =  () => {
		console.log("Before", this.refs.classList)
		if(this.refs.dropdown.classList.contains("none"))
		{
			this.refs.dropdown.classList.remove("none")
		}
		else{
			this.refs.dropdown.classList.add("none")
		}
		console.log("After", this.refs.dropdown.classList)
	}

	render(){
		return( 
			<div>
				<img src="x" onClick = {() =>this.changeClassName()} />
				<div ref = "dropdown" className = "task none">
			</div>
		)
	}
}

export default Task;
```

2.  After the page renders Click on the img,  now the div tag changes the class name by removing the "none".
3.  Again click on the img tag, It is observed that The class name of the div tag doesn't change.
4. Observe the Console log. The output printed starting with "Before" remains constant

Link to code example:

## The current behavior
The ref isn't updating.
On clicking on the img rendered on the page, the div tag class name changes only for the first time the img is clicked, but after subsequent clicks the div tag class name doesn't change.

## The expected behavior
The ref needs to update
The div tag class name should change everytime the img is clicked.

**Comment by bvaughn** [comment]
You have a typo in your code:
```js
console.log("Before", this.refs.classList); // should be this.refs.dropdown.classList
```
Fix that and the "bug" will be fixed.

That being said, this is a problematic approach, because if anything causes your component to re-render, you have a hard-coded "task none" class for the div being rendered. (You'll lose the changes you made to the ref directly.)

A more robust way of doing this would be to manage the class list using React state. Something like [this](https://codesandbox.io/s/reverent-tesla-jpk7r?file=/src/App.js).

**Comment by yaswanthmangalagiri** [comment]
Hi,
Thanks for the code you updated.
Sorry for the typo.
If the error actually happened because one of the div class names also contains the same name that of ref.
