### ISSUE TITLE
Bug: Passing valid and then empty style value doesn't remove prior value

### ISSUE THREAD

**Issue by alecmolloy** [facebook/react#19477]
React version: 16.13.1

## Steps To Reproduce

1. Give element a valid backgroundColor: `style={{backgroundColor: 'blue'}}`
2. Update component so that on the next render you have a commented-out value: `style={{backgroundColor: '/*blue*/'}}`, or any value deemed "invalid" by React.

Link to code example:

A code sandbox that toggles with the two above examples, and a toggle on click is provided here: https://codesandbox.io/s/adoring-currying-z4x2r?file=/src/App.tsx:316-320

## The current behavior
If I pass a valid string to an element's style property, e.g. `style={{border: '20px solid rebeccapurple'}}`, and then update that value to e.g., `'nonsense'`, the new invalid value is not pushed to the DOM. However the old value is kept on the DOM.

Furthermore, updating a valid value, e.g. `style={{backgroundColor: 'blue'}}` with a valid empty value, e.g. `style={{backgroundColor: '/*blue*/'}}` does the same: the old value is kept on the DOM.

## The expected behavior
An invalid value or an empty valid value would at least either remove the previous value from the DOM, or be pushed through. (I've not understood why invalid values weren't pushed through and am genuinely curious to hear if there is a good reason, would love to learn.)

**Comment by aweary** [comment]
Hey @alecmolloy, this is expected behavior and not something controlled by React. [Here's an example showing the same thing with just the DOM APIs](https://codesandbox.io/s/holy-monad-u2y8x?file=/src/index.js). If you set a style property to an invalid value the DOM will just ignore it.

> Furthermore, updating a valid value, e.g. style={{backgroundColor: 'blue'}} with a valid empty value, e.g. style={{backgroundColor: '/*blue*/'}} does the same: the old value is kept on the DOM.

Values like `"/*blue*/"` aren't considered empty. The DOM APIs don't understand that those are meant to be commented out values, it just sees a string with some content. Something like `<div style="background-color: /* blue */">` does work in HTML, but React's JSX compiles to JavaScript not HTML so it's one of the nuanced differences.

If you want to unset a value you can use `""` or `null`. Hope that helps!

**Comment by alecmolloy** [comment]
Thanks very much @aweary for the explanation and especially the example! didn't know this was the behavior of the DOM APIs. will be figuring out a workaround for this.
