### ISSUE TITLE
Bug: Context doesn't work when exported from a package with multiple entrypoints

### ISSUE THREAD

**Issue by ROODAY** [facebook/react#19541]
React version: **^16.13.1**

I had some code in my React app that handled loading Firebase and getting an AuthUser. Both the Firebase object and the AuthUser object were stored in their own contexts so they could be used throughout my app, and this worked fine. I then wanted to abstract this functionality into a component library so that I could reuse it easily between projects, and that's where this issue cropped up. I made my library using Neutrino,js since it was recommended on the React docs site, and the "react-components" preset for making component libraries creates a separate entrypoint for every file/directory in `src/components`. 

So in my case, my build directory contained `Firebase.js` and `Session.js`, each of which exported their respective context, However, importing these contexts back into my original React app wouldn't work, as any changes to the value in the context provider (inside the library) would not propagate to the context consumers (outside the library/in my app). I confirmed this by checking the Component tree in dev tools (screenshots [here](https://stackoverflow.com/questions/63267934/react-context-from-library-not-updating-in-consumer)).

I eventually got around this issue by following [this answer](https://stackoverflow.com/a/60655639/3325942) from SO. Basically just make an index.js that imports/re-exports everything so that it's all considered one module. This made it work, but now my imports went from
```
import AuthuserContext, {withAuthentication} from "my-library/Session";
import Firebase, {withFirebase} from "my-library/Firebase";
```
to
```
import {AuthuserContext, withAuthentication, Firebase, withFirebase} from "my-library";
```
which feels a lot messier. Is there a fix for this or is this expected behavior for Contexts? And if so, can that change in the future?

## Steps To Reproduce

1. Bootstrap a Neutrino.js react-components preset.
2. Create a file that exports a context and updates the value asynchronously (in my case loads firebase, but you could probably even do a setTimeout).
3. Create a file that uses that contexts provider.
4. Create an HOC that wraps an element with contexts consumer.
5. Build the Neutrino.js project and import the HOC into another project and wrap a component with it. Notice that the consumer won't ever update.

The buggy context code is available on [this commit](https://github.com/BUUPE/React-Components/tree/a34cfd58c00dface71031c3ba551cc778c1b8e83) of my component library.

## The current behavior
Context can be used within the module/library it was defined in, but consumers won't update if they are defined outside the library.

## The expected behavior
Context would update anywhere the consumer is,

**Comment by vkurchatkin** [comment]
It is most likely the problem with your build setup, not React. You need to ensure that context that is used by provider is the same this is used by consumer. If your configuration is incorrect, it could happen that the file that creates the context is bundled twice, which essentially makes two different contexts.

**Comment by ROODAY** [comment]
So the way I had it setup was like this (I'll focus on just the context for Firebase since if I can fix that I can apply it to the other context). Here's the file structure of my component library.
```
./src
--/components
----/Firebase
------context.js
------index.js
----Layout.js
```

Inside `Firebase/context.js`
```
import React from "react";

const FirebaseContext = React.createContext(null);

export const withFirebase = (Component) => (props) => (
  <FirebaseContext.Consumer>
    {(firebase) => <Component {...props} firebase={firebase} />}
  </FirebaseContext.Consumer>
);

export default FirebaseContext;
```

Inside `Layout.js`
```
  
import React, { Component } from "react";
import { FirebaseContext, getFirebase, withFirebase } from "./Firebase";

const TestFirebase = withFirebase(({firebase}) => {
  console.log(firebase);

  return <h1>I'm inside the library</h1>
})

class Layout extends Component {
  state = {
    firebase: null,
  };

  componentDidMount() {
    const app = import("firebase/app");
    const auth = import("firebase/auth");
    const firestore = import("firebase/firestore");
    const storage = import("firebase/storage");
    const functions = import("firebase/functions");

    Promise.all([app, auth, firestore, storage, functions]).then((values) => {
      const firebase = getFirebase(values[0]);

      this.setState({ firebase });
    });
  }
  render() {
    return (
      <FirebaseContext.Provider value={this.state.firebase}>
        <TestFirebase />
        {this.children}
      </FirebaseContext.Provider>
    );
  }
}

export default Layout;
```

So inside the component library, Layout imports its sibling, Firebase. This gets built with Neutrino.js/webpack and I get
```
./build
--Firebase.js
--Layout.js
```
The content of the build folder gets pushed to my component library's repo on GitHub, specifically a `dist` branch, so I can add it to my project with `yarn add user/my-library#dist`. I then import Layout and withFirebase into my project and use them like so:
```
import { FirebaseContext, withFirebase } from "my-library/Firebase";
import Layout from "my-library/Layout";

const ComponentWithFirebase = withFirebase(({firebase}) => {
  console.log(firebase);

  return <h1>I'm outside the library</h1>;
});

const Page = () => (
  <Layout>
    <ComponentWithFirebase  />
  </Layout>
);
```
This is where the issues arise, as I'll see in Dev Tools that the Provider gets a new value, as does the consumer that wraps TestFirebase inside Layout. However, the consumer that wraps ComponentWithFirebase doesn't get the new value. 

So to get at what you mentioned, is `import {FirebaseContext} from "my-library/Firebase"` a different `FirebaseContext` than in `import { FirebaseContext} from "./Firebase"`? My build process is the basic Neutrino.js React-Components preset (I didn't modify any of it at this stage), so I'm not sure what in the build process could have created separate contexts.

**Comment by ROODAY** [comment]
Followup question to help debug (I'm trying a few different methods to see what works), does React provide a way to check if two instances of a context are the same? E.g. If I have 1 provider and 2 consumers but one of them isn't updating, is there a way to see what reference they're pointing to so I can see where it's going wrong?

**Comment by Andarist** [comment]
No - React has no such thing, but JS and devtools have 😉 to check for equality just assign to two globals and do a `===` check. They have to be different to result in what you are experiencing - I would track from what files on the disk both are imported and that should lead you to two distinct locations.

**Comment by TeknoFiend** [comment]
This problem came up for us too in a slightly different way. When a leaf dependency is used by more than one intermediate dependencies there can be multiple instances of the leaf dependency's context object and there's not a lot the app can do about it.

As an example we are using `storybook` and `theme-ui`, both of which depend on `emotion`.  Emotion has its own sub-libs and the context object is created in `@emotion/core`. The relevant paths to the installed modules looks like this:

```
node_modules/@storybook/node_modules/@emotion/core
node_modules/@theme-ui/core/node_modules/@emotion/core
node_modules/@theme-ui/components/node_modules/@emotion/core
```

Even though the *version* of `core` installed inside of `@theme-ui/core` and `@theme-ui/components` are the same, there are two context objects.  The app never has direct access to the context because it's used as an abstraction for theming information.  Further complicating matters (but not shown) is the fact that `emotion` uses the context from its `@emotion/styled` sub-lib.

We were fortunately able to resolve this using Yarn's "resolutions" because the versions needed by `storybook` and `theme-ui` were compatible. But that feels like a narrow miss (and a ticking time bomb).

Library writers can solve this by letting the apps create their *own* context and passing them in. But as a library writer and sometimes-app-dev myself I would rather not have that complication.

It seems like React should have a less involved solution. Perhaps a registry of contexts that library writers can use w/ a key:

```
const myContext = React.createContext( {}, '@emotion/core' );
```

This wouldn't work for all cases but would, I think, alleviate the potentially huge problem that an app may not be able to escape.

**Comment by Andarist** [comment]
As the Emotion maintainer I think that with the proposed solution people would land (again) with different set of problems - React already had key-based contexts in the legacy context API and there are reasons why this has been changed.

We recommend using @emotion/react as a peer dependency, exactly because of the issue you are mentioning. 

Note that problem is not exclusive to React context, a lot of different things would not work in the modules layout like this - e.g. shared state and instanceof

**Comment by TeknoFiend** [comment]
Ah I see.  Thanks for the quick history and suggestion.

**Comment by andreawyss** [comment]
I had the same issue.  
Exporting everything from the library root worked for me too.
