### ISSUE TITLE
Bug: relatedTarget is undefined in firefox

### ISSUE THREAD

**Issue by zoltan-mihalyi** [facebook/react#19572]
React.MouseEvent#relatedTarget is undefined in firefox on windows (should be null)

React version: 16.12.0

## Steps To Reproduce

1. create an onMouseOut event listener on a html element
2. move the mouse to the element
3. move the mouse outside the window (the mouse should not enter other html elements in the process)

Link to code example: https://codesandbox.io/s/strange-wiles-c4ku2
In the example, if you move the mouse from the blue box to the top, you see the types of `event.relatedTarget` and `event.nativeEvent.relatedTarget`, you see "undefined, object".

## The current behavior
when event.nativeEvent.relatedTarget is null, event.relatedTarget is undefined.

## The expected behavior
event.relatedTarget should be null

**Comment by claytercek** [comment]
looks like this is due to the fact that mozilla doesn't support the `fromElement` or `toElement`event property, which is what the fallback uses when relatedTarget doesn't exist. 

https://github.com/facebook/react/blob/dab0854c5e66ca74ca0591fd312d6a654e5aaaf1/packages/react-dom/src/events/SyntheticEvent.js#L172-L179
