### ISSUE TITLE
Bug: SVG foreignObject misplaced on browser zoom in React app

### ISSUE THREAD

**Issue by maazadeeb** [facebook/react#19589]
React version: 16.13.1
User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36`

## Steps To Reproduce

1. Hover over the red circle in the codesandbox. Notice that the Popover comes up above the circle
2. Now, use `CMD/Ctrl` + `+` to zoom the sandbox. Notice how the Popover is displaced
3. Find the red circle in the browser devtools and the React devtools and notice the difference in the position of the red circle. Interestingly enough, the Popover seems to render at the position that the React devtools show it

Note: Refreshing the page after zooming does not solve the problem.
Note: The problem is reproducible without the `antd` Popover as well, but it's hard to notice visually as nothing looks misplaced

### Browser devtools

![Browser devtools](https://i.stack.imgur.com/yFLqS.png)

### React devtools

![React devtools](https://i.stack.imgur.com/Pvl2z.png)

I found this problem when trying to add a popover to a [custom node](https://danielcaldas.github.io/react-d3-graph/docs/#node-view-generator) in [react-d3-graph](https://danielcaldas.github.io/react-d3-graph/). I've removed all other dependencies in order to create this minimal reproducible example.

I asked this on [SO](https://stackoverflow.com/q/62622105/2950032) and after receiving no response and no success in solving it myself, decided to report it here.

Link to code example: [Sandbox](https://codesandbox.io/s/nameless-sunset-ld78l) and [running app](https://ld78l.csb.app/) from the sandbox

## The current behavior

The `foreignObject` is misplaced on zoom

## The expected behavior

I would expect that the `foreignObject` gets a proper position, in sync with the DOM's position

**Comment by bvaughn** [comment]
What makes you suspect that this bug is caused by React and not the browser itself or antd?

For what it's worth, antd is a third party UI library. It's not something owned or maintained by the React team, so removing it from your minimal repro would probably be a good first step. (Reducing the number of potential things that could be causing this bug *other than React*).

Looking at the repro shared, this surely looks to me like an antd tooltip positioning issue. (The absolute coordinates are wrong– I assume because they aren't handling the zoom correctly).

**Comment by maazadeeb** [comment]
@bvaughn I understand your concerns. I've been trying to find a concrete reason that this is a React bug. I haven't been able to. Even when I remove antd from the project, the screenshots of the two devtools that I've shared look the same.

I've made no other headway, so I would request you to point me to how I can debug the React devtools functionality that does the highlighting of the DOM node when selecting it. Maybe I can find something there.

**Comment by eps1lon** [comment]
Repro without any 3rd part dependencies: https://codesandbox.io/s/react-devtools-foreignobject-zoom-u02qx

Looks like this is specific to `foreignObject`. All screenshots taken with 150% zoom.

Hovering `foreignObject` (unexpected behavior):
react-devtools component view:
![zoom-devtools-react-foreignObject](https://user-images.githubusercontent.com/12292047/91805530-008a4800-ec2c-11ea-8309-a002a85c9867.png)


vs

chrome elements view:

![zoom-devtools-chrome-foreignObject](https://user-images.githubusercontent.com/12292047/91805565-03853880-ec2c-11ea-97a9-1ebdd2b550fa.png)


Hovering `circle` (expected behavior):
react-devtools component view:
![zoom-devtools-react-circle](https://user-images.githubusercontent.com/12292047/91806008-23b4f780-ec2c-11ea-8292-e8fc627a107d.png)

vs

chrome elements view:
![zoom-devtools-chrome-circle](https://user-images.githubusercontent.com/12292047/91806083-2879ab80-ec2c-11ea-8a78-2fc8944ae29e.png)

**Comment by piotrzarycki** [comment]
Can i take it?

**Comment by maazadeeb** [comment]
@piotrzarycki I'm not sure about the process. Please check with @eps1lon or @bvaughn. I'm going to remove my name from the assignment for now.

**Comment by eps1lon** [comment]
> Can i take it?

Sure, go for it :+1:

**Comment by puddi** [comment]
@maazadeeb could this be a chromium issue instead of a react issue? it seems like the example isn't reproducable in firefox, which makes me think that this is a chromium issue with the rects that it's returning.

(sorry for necroposting, was doing some debugging and searching on the same issue which led here)

**Comment by maazadeeb** [comment]
> @maazadeeb could this be a chromium issue instead of a react issue? it seems like the example isn't reproducable in firefox, which makes me think that this is a chromium issue with the rects that it's returning.

It's possible. I did find an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=510819) on Chromium that is marked as fixed now. But I couldn't find anything further. So we just used a different UX where this problem wasn't possible. 🤷🏼‍♂️

**Comment by gaearon** [comment]
React doesn't do anything special for `foreignObject` so I don't see how it could be React's bug.

**Comment by mgprieto-soincon** [comment]
Maybe it's a problem with the browser? On Safari I have the same issue

**Comment by oleksandr-danylchenko** [comment]
I was able to replicate this issue with a minimal setup - https://stackblitz.com/edit/stackblitz-starters-jh33b2?file=src%2FApp.tsx

The `getBoundingClientRect` reports wrong position values for the elements located within the `foreignObject` on zoom: 
![image](https://github.com/facebook/react/assets/68850090/70e22d83-5f86-4055-be57-246ac84a0b8f)

Here's the zooming behavior example in Chrome. The teal block takes the orange block's `x` and `bottom` properties to position itself. Works perfectly fine and those properties stay the same throughout the zooming:

https://github.com/facebook/react/assets/68850090/ed0f93e3-cd21-4077-ac0c-2d423aba03fa

On the other hand, in Safari, the teal block gets mispositioned because the reported values don't match the actual position of the orange block: 

https://github.com/facebook/react/assets/68850090/55b5a51d-3604-40c7-9c85-6da08cf02bc7
