### ISSUE TITLE
Bug: Infinite loop in react should be short circuited, at least in dev

### ISSUE THREAD

**Issue by joshribakoff** [facebook/react#19624]
React version:
16.13.1

## Steps To Reproduce

```tsx
function App() {
  return (
    <App />
  );
}
```

## The current behavior
Infinite loop, 100% CPU browser lock up

## The expected behavior
```tsx
function App(): any {
  return App()
}
App()
```

I get this basically instantly, with a helpful stack trace:
> RangeError: Maximum call stack size exceeded

Compare this to the circular React situation, where it locks up the browser & it can be difficult to debug.

**Comment by pvrpv** [comment]
Yes, I tested the same. facing the same issue.

**Comment by gaearon** [comment]
The reason is that React doesn't execute components recursively. It is lazy. Instead you can think of it as:

```js
while (nextComponent) {
  nextComponent = render()
}
```

So if you have a recursive tree, you get an infinite loop, just like you would with any infinite looping function.

In languages that support tail recursive optimization, you'd have the same exact problem. (For what it's worth, JavaScript engines never implemented TCO *because* some existing code on the web relied on this throwing, as far as I know.)

I don't think this is very clear cut that React should throw here. What is an acceptable depth? Is the proposal that we simply throw if your component tree gets deep enough? There is no way we can detect that there is an infinite recursion beforehand, so that seems like the only solution.

This doesn't seem like it comes up in practice *a lot* so I'm inclined to close. If this were a more common problem I think it might make sense to add a stack limit but I'm not convinced for now.

**Comment by joshribakoff** [comment]
> Is the proposal that we simply throw if your component tree gets deep enough?

I'd make a mutable property that configures the max size of the "stack" and throw if the depth exceeds this [user configurable value].

It would likely be very simple to add, would fix something that make React very difficult to debug, and would make "react components are just functions" more of a true statement. Just because people aren't opening issues for it doesn't mean it doesn't come up in practice...

**Comment by gaearon** [comment]
>FWIW I also see similar things where due to weird edge cases componentDidUpdate goes into an infinite loop, and locks up the browser

We do have a breaker error for this. But it's easier because 25 nested updates is obviously a mistake, whereas a tree may just happen to be very deep.

>would make "react components are just functions" more of a true statement

They are plain functions, but like any plain functions, they may be called in a loop. It's actually pretty important for semantics that JSX calls are lazy, and I don't think we need to pretend that they're not. If anything, any docs saying "JSX is just function calls" are wrong and should be clarified if you see that.

**Comment by joshribakoff** [comment]
I'd actually disagree, and would content it's reasonable to assume that if a dev would intentionally nest a component 10,000 times they may also intentionally nest 25 updates (I've seen some crazy stuff).

Anyway, bottom line its not great DX to lock up the app, even with 5+ years of React experience it still trips me up, which is why I opened the issue. Not sure how other frameworks handle it.

Thanks for the response, I totally understand the hesitation to turn it on by default, but I'm not sure I see any downside to being able to turn this on in dev mode to debug.
