### ISSUE TITLE
Create react app throwing the following error

### ISSUE THREAD

**Issue by I-GiM** [facebook/react#19635]
npx create-react-app does not complete because of the following error
How do I solve this?
![react error](https://user-images.githubusercontent.com/61995586/90494054-fbf96600-e13a-11ea-880e-05be2d694519.PNG)

**Comment by bvaughn** [comment]
The error you've posted isn't a React error, so this isn't the right place to report it.

As the error text itself says:
> This is related to npm not being able to find a file.

I'd suggest checking out the error log that's printed in the error message (`2020-08-18T08_54_43_533Z-debug.log`) to see if it says more.

Going to close this issue here. There's nothing we can do to troubleshoot NPM install problems like this from our end. :bow:
