### ISSUE TITLE
Deepcode.ai found 67 issues, 4 of which are critical ( security and defects )

### ISSUE THREAD

**Issue by Spoor2709** [facebook/react#19645]
After running react through [deepcode.ai] (https://www.deepcode.ai/app/gh/facebook/react/d7feeb25ac8cc23133c294fa01932658023130c0/_/dashboard) 67 issues were found, I think integrating deepcode into the pipeline and into pull requests would be a good idea. Should I create a separate issue for each issue?

**Comment by gaearon** [comment]
Please don’t create 67 issues. :-)

It looks like a bunch are coming from `fixtures` and `scripts`. For the most part, except for build scripts, we don’t care about those. They are intentionally not production grade because they’re only used for our own testing.

Please feel free to file issues for things outside of these folders if they actually look legit to you.
