### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by jiang-zhong-xi** [facebook/react#19650]
React version: 16.6.1

## Steps To Reproduce

1. open source code（src\react\packages\react-dom\src\client\ReactDOMComponent.js）

`
if (namespaceURI === HTML_NAMESPACE) {
    namespaceURI = getIntrinsicNamespace(type);
  }
  if (namespaceURI === HTML_NAMESPACE) {
    if (__DEV__) {
      isCustomComponentTag = isCustomComponent(type, props);
      // Should this check be gated by parent namespace? Not sure we want to
      // allow <SVG> or <mATH>.
      warning(
        isCustomComponentTag || type === type.toLowerCase(),
        '<%s /> is using incorrect casing. ' +
          'Use PascalCase for React components, ' +
          'or lowercase for HTML elements.',
        type,
      );
    }
`
## The current behavior
  Why repeat the same if statement

## The expected behavior
merge

**Comment by bvaughn** [comment]
I believe this issue is referring to the following lines:

https://github.com/facebook/react/blob/87b3e2d257e49b6d2c8e662830fc8f3c7d62f85f/packages/react-dom/src/client/ReactDOMComponent.js#L412-L415

https://github.com/facebook/react/blob/87b3e2d257e49b6d2c8e662830fc8f3c7d62f85f/packages/react-dom/src/client/ReactDOMComponent.js#L1133-L1136

Feel free to update a PR that merges these statements if you'd like.

**Comment by bvaughn** [comment]
This repetition is valid. See the discussion on #19652
