### ISSUE TITLE
Bug: Running "yarn run build" failed due to missing java environment (Windows 10)

### ISSUE THREAD

**Issue by adibiton** [facebook/react#19656]
React version:
16.13.1
## Steps To Reproduce

1. Clone the repo to a machine without JRE installed
2. After running yarn, run "yarn run build"

## The current behavior
The build stops with the error: "process spawn error. is java in the path spawn java enoent"
(PLUGIN_ERROR (scripts/rollup/plugins/closure-plugin))

## The expected behavior
Maybe document that installing JRE is a pre-requisite to the build script

**Comment by bvaughn** [comment]
Java is required because we use the Java version of the Google closure compiler to optimize our production bundles. We used to use the JavaScript version, but it was **very slow** and also required a lot of system resources to run (>16GB of RAM).

The [contributing guide](https://reactjs.org/docs/how-to-contribute.html#contribution-prerequisites) lists Java as one of the prerequisites:
> # Contribution Prerequisites
> * You have Node installed at v8.0.0+ and Yarn at v1.2.0+.
> * You have JDK installed.
> * You have gcc installed or are comfortable installing a compiler if needed. Some of our dependencies may require a compilation step. On OS X, the Xcode Command Line Tools will cover this. On Ubuntu, apt-get install build-essential will install the required packages. Similar commands should work on other Linux distros. Windows will require some additional steps, see the node-gyp installation instructions for details.
> * You are familiar with Git.
