### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by Timothy-sserunjogi** [facebook/react#19688]
The 'manifest_version' key must be present and set to 2 (without quotes). See developer.chrome.com/extensions/manifestVersion.html for details.
Could not load manifest.

I am getting that error when i try to load my react development tool. any assistance i can be given will be grateful.

**Comment by bvaughn** [comment]
Not sure why you are seeing this. The `manifest_version` key is present and set to `2`:
https://github.com/facebook/react/blob/1396e4a8f5646f35929883cbb449d2c83e7cbc79/packages/react-devtools-extensions/chrome/manifest.json#L2

Try restarting your browser?

**Comment by bvaughn** [comment]
I'm going to close this issue because I don't believe it's actionable on our side. (The manifest is already correct, according to the Chrome store and submission process.)

Please keep us posted if you're still seeing this issue though. If nothing else, this may help others in the future who encounter the same message.
