### ISSUE TITLE
Bug: development StrictMode double-rendering does not pass backing hook state to the second render pass

### ISSUE THREAD

**Issue by probablyup** [facebook/react#19721]
React version: 16.13.1

## Steps To Reproduce

1. Create a component that uses `useRef` and assigns a value to the ref during the SFC body
2. Wrap it in `StrictMode`, `useRef` will have its initial value in both cases even though the second render is called after the first instead of the value assigned to `ref.current`

Link to code example:

https://github.com/styled-components/styled-components/pull/3237/commits/62690d473c94179d1d31ad4b705144ef802c9391 (https://github.com/styled-components/styled-components/pull/3237)

## The current behavior

The `useRef` hook on the second pass is empty (initial value.)

## The expected behavior

The `useRef` hook on the second pass has the value set during the first render pass.

The `createGlobalStyle` component in styled-components fully removes and re-adds the styles each time the component is called, which is why it is wrapped in `React.memo` to prevent unnecessary renders. The double-render without forwarding the hook state makes for a very poor development experience since there will be flickering from styles being added and removed unnecessarily.

**Comment by vkurchatkin** [comment]
It seems like double rendering is doing exactly what it is designed for: detects side-effects in render. 

> The createGlobalStyle component in styled-components fully removes and re-adds the styles each time the component is called,

This should be done in `useEffect`

**Comment by probablyup** [comment]
`useEffect` happens too late and would suffer from the same issue

**Comment by vkurchatkin** [comment]
> useEffect happens too late

you can use `useLayoutEffect` then

> would suffer from the same issue

how so? effects are not invoked twice

>  it's also important that this behavior happens during SSR as it loads up an array of CSS that is used elsewhere

I guess during SSR you can do what you are doing. It still violates the rules, but shouldn't be an issue.

**Comment by eps1lon** [comment]
Note that this is not necessarily part of StrictMode but also how concurrent mode works right now. If a component is rendered but not committed <sup>1</sup>, any value assigned to the ref (`useRef`), initial state (`useState(() => state)`) and memoized computations (`useMemo`) is discarded: https://codesandbox.io/s/concurrent-mode-suspended-component-commit-lnndy?file=/src/index.js

StrictMode is simulating a scenario where a component is rendered but not committed, and then rendered again due to another component "unsuspending".

<sup>1</sup> For example another component in the same Suspense boundary supsends.

**Comment by probablyup** [comment]
@vkurchatkin I think I got this working, thanks for the suggestion
