### ISSUE TITLE
Bug: renderToString renders srcSet instead of srcset

### ISSUE THREAD

**Issue by vasimi** [facebook/react#19799]
React version: 16.12.0

## Steps To Reproduce

1. Use `renderToString` to render `<source>` element with `srcset` attribute

Link to code example: https://codesandbox.io/s/react-dom-camelcase-bug-1rnxt

## The current behavior
`srcSet` isn't transformed to `srcset`

## The expected behavior
`srcSet` becomes `srcset`

**Comment by eps1lon** [comment]
This applies to all camel-cased attributes in React e.g. `defaultValue` or `autoPlay`. This issue came up in the past in https://github.com/facebook/react/issues/13162 and was closed since it didn't seem to have any actual impact and the living standard doesn't enforce them to be case-sensitivity.

It was also brought up in https://github.com/facebook/react/issues/12403 and closed with the following explanation:

> HTML is case-insensitive. I agree it can be a bit surprising but there is no practical difference to the browser, and it might be a bit faster for us to avoid lowercasing it.

-- https://github.com/facebook/react/issues/12403#issuecomment-374342250

Please ping me if there is any actual impact.

Other duplicates: https://github.com/facebook/react/issues/11160 and https://github.com/facebook/react/issues/10863

**Comment by vasimi** [comment]
@eps1lon Firefox ignores the `srcSets` with uppercase letter, not sure about other attributes. I can file a bug in Mozilla's BugZilla, but it would be nice if this was fixed in React, too.

**Comment by eps1lon** [comment]
> I can file a bug in Mozilla's BugZilla,

That's be nice so that we can confirm where the issue originates.

> but it would be nice if this was fixed in React, too.

It's not clear if this is actually an issue with React. As said previously: HTML tag names and attribute names are not case-sensitive. User agents should treat `srcset` and `sRcSET` equal.

**Comment by coreyward** [comment]
> It's not clear if this is actually an issue with React. As said previously: HTML tag names and attribute names are not case-sensitive. User agents should treat `srcset` and `sRcSET` equal.

There's a long history of adapting to what user agents _actually do_ rather than hiding behind what they _should do_. I'm a bit confused why React would be continuing to ignore this concern for years. Is there _any reason at all whatsoever_ for the current behavior? It's bizarre that React would both 1) complain about me using a lowercase attribute and 2) tell me I shouldn't care about the casing of the attribute, but here we are.

**Comment by edkimmel** [comment]
Chrome appears to also be ignoring srcSet and is loading the src attribute instead off of SSR.  When the client re-renders it as srcset it then picks the appropriate size.
