### ISSUE TITLE
Bug: Super gets strikethrought in react 

### ISSUE THREAD

**Issue by shahab570** [facebook/react#19842]
React version:16.13.1
 I was wriitng code like this; 

import React, { Component } from "react";
import { Message } from "./Message";
import ActionButton from "./ActionButton";

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      counter: 0
    };
  }
}

But " super(props) " keyword get strikethrough automatically. I don't know why?

**Comment by AndrewPomorski** [comment]
is the error coming from your code editor or linter?

**Comment by eps1lon** [comment]
This is probably coming from your editor since TypeScript started supporting the `@deprecated` tag. `@types/react` marks constructors using legacy context as deprecated. Your editor seems to think this constructor uses legacy context which is a bug in your editor.

It's debatable whether `@types/react` should mark this as deprecated for v16 types considering v17 will continue to support legacy context. @gaearon Should the default TS typings reflect warnings from StrictMode?

**Comment by shahab570** [comment]
> is the error coming from your code editor or linter?

Its from the editor
