### ISSUE TITLE
Bug: getDerivedStateFromProps being called twice with more than 1 line of code

### ISSUE THREAD

**Issue by JoshuaUwuseba** [facebook/react#19884]
React version:

## Steps To Reproduce

1. Create the getDerivedStateFromProps method in a class component
2. Create the following 2 lines of code: console.log("He is Lord"); console.log("He is King");
3. Run npm start and open console in browser

Link to code example:

## The current behavior
getDerivedStateFromProps runs twice with more than one line of code

## The expected behavior
getDerivedStateFromProps should run once

**Comment by bvaughn** [comment]
It is expected that `getDerivedStateFromProps` will be called twice in DEV in `StrictMode`, which is what I assume you are reporting. (Since there is no actual repro attached, I can't be sure.) You can read more about it here: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

Going to close this issue as it seems to be a misunderstanding. If you think this is incorrect, we can reopen it but please include a link to a Code Sandbox repro in that case.
