### ISSUE TITLE
Bug: Race Condition on React Contexts

### ISSUE THREAD

**Issue by dhyegocalota** [facebook/react#19903]
If two async context changers are executed in parallel to partially modify an object attribute, the last resolved context changer will override the first resolved change with an outdated value.

React version: 16^

Link to code example:

https://codesandbox.io/s/race-condition-on-react-contexts-forked-bqh5z?file=/src/Cosmic.js

**Comment by bvaughn** [comment]
I don't think this is context-specific, is it?

It looks like a combo of an async function closing over a stale value which then overrides/conflicts with a more recent update. The solution to this ([as shown in the docs](https://reactjs.org/docs/hooks-reference.html#functional-updates)) is to use the callback form of set-state so that accumulated changes aren't lost.

Did I misunderstand something?

**Comment by dhyegocalota** [comment]
@bvaughn the solution and the docs make sense, yes. Still, I'm not really sure, is it an expected behavior? If yes, please ignore and close this thread.

**Comment by bvaughn** [comment]
Yes. It's expected behavior. :smile: What's happening is basically this:

1. The `context` object gets initialized to e.g. `{ name: "foo", age: 123 }`
2. The two React components, `ChangeCosmicAge` and `ChangeCosmicName`, render and their two click handler functions close over that `context` object value.
3. The two asynchronous click handlers get called. (Remember, they both have references to the same `{ name: "foo", age: 123 }` value.)
4. One of them completes, let's say the one in `ChangeCosmicAge`. It updates state to a new object: `setCosmic({...context, age: 456})`.
5. State is now `{ name: "foo", age: 456 }`.
6. The other completes, and updates state as well: `setCosmic({...context, name: "bar" })`. But remember, this second one started with a value of `{ name: "foo", age: 123 }`. That means the updated state is now `{name: "bar", age: 123}`.

The way to avoid this is to let React always pass you the latest state (using the callback pattern I mentioned above) :smile:.
