### ISSUE TITLE
Better support <template> tags

### ISSUE THREAD

**Issue by manuel-mauky** [facebook/react#19932]
HTML [`<template>` tag]() is used to pass reusable templates to web components.
However, at the moment this doesn't work with React in a way that is useful to users.

### Context: Basic usage of `<template>`

If you have HTML like this:

```html
<template>
	<p>Some Text</p>
</template>
```

You can then use this template with pure JS like this:

```js
const template = document.querySelector("template")

const node = template.content.cloneNode(true)

document.append(node)
```
The important part here is the `content` property of the template.

### Whats the problem?

Writing the template code in HTML is OK. However, if you create the template DOM nodes with JS like this, it won't work:

```js
const template = document.createElement("template")
const p = document.createElement("p")
p.textContent = "Some Text"
template.appendChild(p)
```

In this case, the `content` property of the template will be empty. Instead, one would have to do either of these:

```js
const template = document.createElement("template")
template.innerHTML = "<p>Some Text</p>"
```

or

```js
const template = document.createElement("template")
const p = document.createElement("p")
p.textContent = "Some Text"
template.content.appendChild(p) // notice `content`
```

The first does work because there is a special case in `innerHTML` for template tags (see [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#Operational_details)).
The second example works because the `<p>` DOM node is added directly to the `content` of the template.

### What does this has to do with React?

When using React to create the template, React is appending the generated DOM nodes directly to the template node and not to the `content` property of the template node. For this reason at the moment you can't really use template tags in React apps.

I have the impression that this is not the fault of React as the same problem exists for angular and most likely other spa frameworks too. Instead this looks like a misconception of the `template` tag to me (mayby I'm wrong on this and there is a good reason for this behavior). 
However, maybe React could do something to make this usecase less anoying? A possible solution could be to detect if the parent node is a `template` and to add the child nodes to the `content` property instead of the node itself. But I'm not sure if there would be any negative side-effects of this.

**Comment by strattonbrazil** [comment]
I'm pretty new to react, but this seems contrary to react's philosophy. Is the goal to allow react to create some DOM template that can be handed off off to something? 

This has some suggestions on how to do that with template, but like it says in the answer seems like the wrong use case. 
https://stackoverflow.com/questions/42845195/how-can-i-render-a-template-tag-with-react

Instead of using template, could you instead make the component and after it's rendered, copy it with React.cloneElement() or do a copy on the actual DOM node?

**Comment by BasixKOR** [comment]
I've encountered this problem while trying to use `template[shadowroot]` and got hydration error. I think the usefulness of the tag will grow over time and it would be great for React to consider handling `content` correctly.

**Comment by BasixKOR** [comment]
So I just worked on a simple yet working library for this: https://github.com/BasixKOR/react-template-tag/

I confirmed it works well but on React 18 with Streaming SSR enabled it fails to do the job. I'm unsure there's an possible way to extend the streaming SSR feature.

**Comment by scottrippey** [comment]
I've also been experiencing this issue.  The browser's native HTML parser constructs the `<template>` tag differently than regular DOM nodes.  Natively, the browser appends all children to the template's `content` fragment, instead of the template's actual children.  A template's `children.length` should always be 0.

It would be ideal if `react-dom` would copy this behavior when constructing `<template>` tags.

Here's an example of native parsing versus React parsing:
https://codesandbox.io/s/new-sun-8l62o?file=/src/App.tsx:1056-1118

**Comment by scottrippey** [comment]
Currently, the only workaround is to use `dangerouslySetInnerHTML` like so:
```
<template dangerouslySetInnerHTML={{ __html: `
  <p> Some text </p>
` }} />
```

**Comment by scottrippey** [comment]
According to #23277 this will probably not be fixed.  The best workaround is to use `dangerouslySetInnerHTML` like above.

**Comment by BasixKOR** [comment]
As a workaround, you can patch some HTMLTemplateElement methods since those methods aren't supposed to be called anyway (see the note of [the HTML standard](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element))

```javascript
HTMLTemplateElement.prototype.appendChild = function (child) {
  return this.content.appendChild(child);
}

HTMLTemplateElement.prototype.removeChild = function (child) {
  return this.content.removeChild(child);
}

Object.defineProperty(HTMLTemplateElement.prototype, "firstChild", {
  get() {
    return this.content.firstChild;
  }
})
```
