### ISSUE TITLE
Bug: This is re-render bug or anticipated behavior?

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#20009]
React version:  16.13.1

## Steps To Reproduce

1.click btn2
2.click btn1, will re-render, that is a bug? then click again, will not re-render again..just once...

Link to code example:
https://codesandbox.io/s/black-frog-d0klh?file=/src/App.js

## The current behavior
re-render

## The expected behavior
not re-render

```

**Comment by razh** [comment]
> If you update a State Hook to the same value as the current state, React will bail out without rendering the children or firing effects. (React uses the Object.is comparison algorithm.)

https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update

> 调用 State Hook 的更新函数并传入当前的 state 时，React 将跳过子组件的渲染及 effect 的执行。（React 使用 Object.is 比较算法 来比较 state。

https://zh-hans.reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update

Note that **btn2** will re-render twice because React renders twice in development to catch unexpected side-effects:

https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
