### ISSUE TITLE
Bug: useRef forget '()'

### ISSUE THREAD

**Issue by zhangenming** [facebook/react#20022]
React version:

## Steps To Reproduce

1.
2.

Link to code example:
https://codesandbox.io/s/dazzling-heyrovsky-18u9w?file=/src/App.js

## The current behavior
correct execution
## The expected behavior
not correct execution

should we do something, such as a warning?To remind us that we forgot about this Brackets

**Comment by bvaughn** [comment]
To be clear, you're not seeing the "correct execution" in this Sandbox :smile: You're mutating the (global) `useRef` function to add a `current` property to it– which may appear to work if you only have one component and it never gets interrupted between render and commit, but it's no different than writing your ref value to a global value on window :smile:

I'm going to close this issue because I'm pretty confident it's not a change that we'd make. Syntax mistakes are not the sort of thing we typically add warnings for. We *could* add a warning for this, but I don't think it's a common enough use case to warrant that.
