### ISSUE TITLE
Versions are all over the place

### ISSUE THREAD

**Issue by onzag** [facebook/react#20049]
I am trying to access v16.14.0 so I did

"git checkout v16.14.0"

In package.json of react dom I find 17.0.0-alpha.0

So I try v16.13.1

And in package.json of react dom I find

16.12.0

so then I try v16.12.0 at this point I am being random and just randomly testing versions

package.json says 16.11.0

**Comment by gaearon** [comment]
What are you trying to accomplish by checking out a tag? React 16.14 was cut as a special release that was not built from source but instead was exactly based on the previous release, with a checked-in JSX runtime bundle. You can find the archived package that was published in a folder: https://github.com/facebook/react/tree/old-majors/old_major_packages/16. This is the commit that was tagged. The versions you’re seeing in the source are not relevant because 16.14 was built from 16.13 rather than from the source directly. Hope that helps.

**Comment by onzag** [comment]
I was simply following the contributing guides, where it claims the usage of semantic versioning, because I am making modifications for a custom react-dom build with custom functionality and I try to keep the same version so that they can work together.

I already made my own react-dom with an extra lifecycle method for static markup, but I honestly have no idea about the versions, overall seems to work, but it's very frustrating.
