### ISSUE TITLE
Bug: Usage of "React.forwardRef" in "React.memo" distorts profiling report

### ISSUE THREAD

**Issue by vasilii-kovalev** [facebook/react#20139]
Hello!

When I was working with [this workshop](https://github.com/kentcdodds/react-performance), especially with [this exercise part](https://github.com/kentcdodds/react-performance/blob/main/src/final/06.extra-3.js#L108-L117) (the goal there is to create a convenient, reusable HOC), I found that wrapping a component in `React.forwardRef` and then in `React.memo` distorts profiling report (when using `Profiler` tab of React Developer Tools).

For demonstration purposes I removed unrelated stuff and now the application looks like this:
![image](https://user-images.githubusercontent.com/10310491/97773045-b6571180-1b5d-11eb-9025-8f1dcd26f821.png)
When you click on a cell, the number inside changes to another one.

React version: 17.0.0
React Developer Tools: 4.9.0

## Steps To Reproduce
1. Start profiling the app (using `Profiler` tab of React Developer Tools).
2. Click on a cell.
3. Stop profiling the app and check re-rendered components.
4. Wrap `Wrapper` component in `forwardRef` (see the code in the repo below) and repeat steps 1-3.

Link to code example: https://codesandbox.io/s/usage-of-reacforwardref-in-reactmemo-81cuh?file=/src/App.js

## The current behavior
Without `forwardRef`: according to the profiling report, all the cells re-render.
![image](https://user-images.githubusercontent.com/10310491/97772842-c4a42e00-1b5b-11eb-9b49-8d2bd6f122aa.png)
![image](https://user-images.githubusercontent.com/10310491/97772848-d4bc0d80-1b5b-11eb-8f41-9378bc7418ba.png)

With `forwardRef`: according to the profiling report, only the changed cell re-renders.
![image](https://user-images.githubusercontent.com/10310491/97772866-fcab7100-1b5b-11eb-9de9-c4aa34b48299.png)
![image](https://user-images.githubusercontent.com/10310491/97772876-07fe9c80-1b5c-11eb-8038-aa9a0ffce473.png)

## The expected behavior
There should be no difference in the reports. I added some `console.log`-s and they demonstrate that adding `forwardRef` doesn't improve performance/reduce re-renders, which seems correct.

CC @kentcdodds

**Comment by kentcdodds** [comment]
To be clear, I'm also at a total loss as to why this is happening. Would love to understand.

**Comment by MaxBittker** [comment]
This manifested in a slightly different way for me - 

In my application, I had this structure inside my "CardList" component"):
``` 
return (
<>
    <ForwardRefElement> 
    {cards.map(c => (<Card data={c}/>))}
    </ForwardRefElement>
   </>
    )

```

My card components were each rendering, and the profiler told me their reason was "**hooks changed**". (very confusing)

After removing the wrapping ForwardRefElement, the cards were still re-rendering, but the reason changed to "**parent rendered**" (more helpful, and I was able to fix my real problem by wrapping Card in a `React.memo`)

I might guess that the underlying issue is connected - forwardRef throwing off the profiler

In case this helps people to find this issue, in my case, ForwardRefElement was a styled component from the stitches library.
