### ISSUE TITLE
Bug: useEffect is not firing when an stated array is emptied and then reset back to state

### ISSUE THREAD

**Issue by normanzb** [facebook/react#20143]
React version: 16.14.0

## Steps To Reproduce

1. Open https://codesandbox.io/s/react-playground-forked-kde0y and follow the instruction

Link to code example: 
web: https://codesandbox.io/s/react-playground-forked-kde0y
react-native: https://snack.expo.io/@normanzb/surprised-cake

## The current behavior

When `firstItem` is equal to 2, the `useEffect` that watches `firstItem` never gets called

## The expected behavior

When `firstItem` is equal to 2, the `useEffect` that watches `firstItem` will be called

**Comment by bvaughn** [comment]
Looks like you're **mutating** a state value and then updating state to re-set the same value. Mutating state (or props or context) values isn't supported and can cause React to skip updates. (In this case, React seems to be bailing out without updating the `queue` state since `oldState === newState`.)

I'm not super clear on why your Sandbox is doing all of what it's doing, but if you replace the mutation with a (shallow) clone of the `queue` array, the state update should work for you, e.g.:
https://codesandbox.io/s/react-playground-forked-31n0h?file=/UseEffectFailure.js:675-680

**Comment by normanzb** [comment]
hi @bvaughn , thanks for replying, I understand that we shouldn't mutating the state but that's not what this ticket is about.
What this ticket is trying to point out are:

1. `useMemo()` gets called while the `useEffect()` doesn't, even tho, they are using same deps array. IMO if they are using the same deps array then the behavior should be the same. 
1. The only dep in the deps array `firstItem` is a string, there is no such mutating an object and then 'oldState === newState' issue when it is a primitive type. IMO, if `firstItem` changed, there is no reason that `useEffect(..., [firstItem])` doesn't get triggered.
2. If you look into the logs, react does trigger re-render after when an empty array is set back to the state, e.g `array = useState([1]); ....;  array.shift(); setArray(array)` , while for a non-empty array it doesn't trigger re-render, this is inconsistent, and it feels like react somehow treat that empty array differently, perhaps because it is falsy value.

**Comment by bvaughn** [comment]
> We ran into this issue accidently and it confused us because `useEffect(..., [firstItem])` doesn't get triggered while `useMemo(..., [firstItem])` get triggered. 

`useMemo` runs during render; `useEffect` runs during commit phase. React may render many times without committing– if the output of the render didn't produce a change.

Maybe you can make a less convoluted example (without multiple effects and callbacks– preferably also without mutation, which is specifically **not supported**) showing what you want me to comment on?
