### ISSUE TITLE
Bug: react-hooks/exhaustive-deps false positive on additionalHooks' definition

### ISSUE THREAD

**Issue by tranvansang** [facebook/react#20160]
React version: 17.0.1

## Steps To Reproduce

1. in `.eslintrc` add the following configuration

```
	"rules": {
		"react-hooks/exhaustive-deps": [
			"warn", {
				"additionalHooks": "(useAsyncEffect)"
			}
		]
	}
```

2. Type the following code

```
export const useAsyncEffect = (effect, deps) => useEffect(
	() => void (async () => {
		try {
			await effect()
		} catch (e) {
			// report error
			console.error(e)
		}
	})(),
	deps
)
```

Link to code example: https://github.com/tranvansang/exhaustive-deps-bug

## The current behavior

- The following errors are printed

```
  10:2  warning  React Hook useEffect was passed a dependency list that is not an array literal. This means we can't statically verify whether you've passed the correct dependencies                                                         react-hooks/exhaustive-deps
  10:2  warning  React Hook useEffect has a missing dependency: 'effect'. Either include it or remove the dependency array. If 'effect' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps

✖ 2 problems (0 errors, 2 warnings)
```

## The expected behavior

In the additional hooks' definition, the following patterns should be accepted as the dependence for the `effect` function (i.e., the first argument of the additional hook).

- Pattern 1: `useEffect(() => {effect()}, deps)`
- Pattern 2: `useEffect(() => {effect()}, [...deps])`

**Comment by jordyvandomselaar** [comment]
Hi,

I've made a sandbox with your code: https://codesandbox.io/s/thirsty-beaver-5qp86?file=/src/App.js

By spreading deps into an array eslint understands that it's an array. Make sure to memoize it though because else you'll keep creating new arrays.

As for `effect`, one of the rule of hooks is that any variable you access inside a hook should be added to the dependency array. This make sure React always calls the latest version of `effect` when it runs & this ensures the hook runs every time the reference to `effect` changes.

Because your hook stays in sync with the `effect` anyway, I think you don't even need the `deps`. Memoizing `effect` is up to the consumer of your hook and then whenever `effect` changes because it received new deps your hook runs again.
