### ISSUE TITLE
Feature request: shortcut to passing props to component

### ISSUE THREAD

**Issue by yigalirani** [facebook/react#20164]
can we have this syntax?
`<div [onClick,className]>clicker 1</div>`

would be shorter version to
`<div {...{onClick,className}}>clicker 1</div>`

relevant: https://stackoverflow.com/questions/64700558/most-concise-way-to-pass-props-to-a-react-component

**Comment by eps1lon** [comment]
Thanks for the suggestion. 

Since this relates to JSX syntax it's better to discuss this in the [relevant repository for JSX](https://github.com/facebook/jsx). You might want to check out https://github.com/facebook/jsx/pull/121 first since that RFC is also concerned with shorthand syntax for props.

**Comment by yigalirani** [comment]
great. the jsx#121 is even shorter and already waiting to be merged.
looking forward to use it!
