### ISSUE TITLE
Bug: react-hook: value of useState doesn't change in function that passes to render props that passes to context 

### ISSUE THREAD

**Issue by Kyi-Moe-Min** [facebook/react#20257]
value of useState doesn't change in inner function that passes to props of render props component but change in DOM and normal call. (it is working fine with the class component)

React version: 17.0.0

## Steps To Reproduce

context.js

```js
import { createContext } from "react";

export const Context = createContext({ showModal: (func) => {} });
```

FunctionalChild.js

```js
import React, { useCallback, useContext, useEffect, useState } from "react";
import { Context } from "../context";

export function FunctionalChild() {
  const { showModal } = useContext(Context);
  const [count, setCount] = useState(0);

  const increaseCount = useCallback(
    function () {
      console.log("functional child", count);
      setCount((c) => c + 1);
    },
    [count]
  );

  useEffect(() => {
    showModal(() => {
      return <button onClick={increaseCount}>+</button>;
    });
  }, [increaseCount, showModal]);
  return <div>current count{count}</div>;
}

```

Parent.js

```js
import React, { useState } from "react";
import { Context } from "../context";
import { FunctionalChild } from "./FunctionalChild";

let modalComponent;

export default function ParentComponent() {
  const [visible, setVisible] = useState(false);

  function close() {
    setVisible(false);
  }

  function showModal(func) {
    modalComponent = func(close);
    setVisible(true);
  }

  return (
    <Context.Provider value={{ showModal }}>
      <FunctionalChild />
      {visible && <div className="modal">{modalComponent}</div>}
    </Context.Provider>
  );
}
```

as above codes, the value of `count` in `increaseCount` function is always showing initial value `0` and doesn't change at all. but got updated value at `console.log("count:", count)` normal call and it's also got updated value in DOM.

Link to code example: https://codesandbox.io/s/usestate-hook-odw3e  
you can check the behavior of both class and functional component in this link

## The current behavior

value of useState doesn't get update value in the function that passes to render props component

## The expected behavior

to get the correct updated value of useState in the function that passes to render props component

**Comment by bvaughn** [comment]
Looks like this ultimately boils down to a [stale closure problem](https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function).

In your example, clicking the "+" button does not cause `ParentComponent` to re-render. This means that each time the button is clicked and your component re-renders, it calls a stale version of `showModal` that closes over the initial (also stale) version of `increaseCount` (when `count` was 0).

You can confirm this using the DevTools Profiler:
![Screen Shot of Profiler showing that `ParentComponent` did not render](https://user-images.githubusercontent.com/29597/99187141-c573bd00-2722-11eb-98c0-be8a6c2182e9.png)

This doesn't happen with `ClassChild` because the callback passed to it (`this.increaseCount`) is bound to the instance of the class component and so it can always read the latest version of `this.state.count`.

Here's an updated sandbox that may make it a little clearer?
https://codesandbox.io/s/usestate-hook-forked-79jxy?file=/src/Example.js

1. Click on the "+" button a few times
2. Note that each time you click it, `showModal` is called but `Parent` doesn't re-render (so it's a stale closure).
3. Then click on the "x" button to *close* the modal (which will cause `Parent` to re-render since that callback updates component state).
4. Now click "+" again and you'll see a new value has been closed over (which will also become stale for the same reason).

Hope this explanation helps clear things up a bit. In addition to [our docs](https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function) you might find more examples by searching "React stale closure" on GitHub or Google.

**Comment by Kyi-Moe-Min** [comment]
@bvaughn thanks for the explanation and example, Now I see it is because of the stale closure problem.
