### ISSUE TITLE
Bug: React.js state detached ?

### ISSUE THREAD

**Issue by maifeeulasad** [facebook/react#20276]
React version: _**16.14.0**_

## Steps To Reproduce

**Code can't be shared at this time, I'll try to share the same type of code by trying to replicate the problem**

Link to code example:

## The current behavior

I don't know why, but my state in React.js is behaving unexpectedly.

![Screenshot from 2020-11-17 17-21-28](https://user-images.githubusercontent.com/29339330/99385282-f575b880-28fa-11eb-9f4d-bcbe8785c93c.png)

## The expected behavior

Sometimes, when I put nested JSON it appears. how can I resolve this or is anyone facing the same issue, or it's just me ? Shouldn't it show the same value.

**Comment by eps1lon** [comment]
Objects logged into chrome devtools are "live". So what you see in  devtools when expanding objects is not the value at the time you called `console.log` but the value when chrome expanded the object. 

This is similar to 

```js
const obj = {children: [1]};
console.log(obj); // {children: Array(1)

obj.children = []
console.log(obj); // {children: Array(0)
```

-- https://fwtk3.csb.app/

But expanding the both objects will display `children: []`.

So this is not something caused by React nor can React do something about it. If you're interested in the value of `obj.children` then you have to log that instead of just `obj`.

Further reading:
- [Google Chrome console.log() inconsistency with objects and arrays](https://stackoverflow.com/questions/24175017/google-chrome-console-log-inconsistency-with-objects-and-arrays)
- [What gets logged in the console when you’re mutating objects](https://www.freecodecamp.org/news/mutating-objects-what-will-be-logged-in-the-console-ffb24e241e07/)
