### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by constantinpojoga** [facebook/react#20282]
React version: **16.10.1** (but was able to reproduce it in 17.0.0)

## Steps To Reproduce

1. focus the input field.
2. Click the "Second" button.

Link to code example: https://codesandbox.io/s/serverless-silence-yei0x?file=/src/App.js

## The current behavior
Not getting the alert (onClick event). 

## The expected behavior
Should trigger the alert, similar to the "First" button.

- First we are focusing the field
- When clicking the button, `onBlur` event triggers first. It will trigger a layout update, and it happens that the new content will be rendered in place of the actual button. The button will be moved down 
- Even if the button is visually there while clicking it, it will not trigger the onClick event.
- Tried to resize the button to 200px height. Will be able to reproduce the issue only for the upper part of the button.
- Wrapping the onBlur event in a `setTimout` with 0 ms will make it work.

**Comment by eps1lon** [comment]
Thanks for the detailed reproduction! This helped a lot identifying the issue.

Unfortunately, this is intended behavior of the web. 

There are two parts to this:

1. In chrome `mousedown` on a button will focus that button. If you previously focused another element, that element will receive the `blur` event. With your repro this means that the `<p>` will get rendered on `mousedown` of the second `button`.
2. Simplified: A `click` is dispatched on the same target where the `mouseup` succeeded.

Since your `<p>` will move the second button down `mouseup` is not registered on the second `<button>` and therefore no `click` event is dispatched. You can observe this better by only pressing your mouse button but not releasing it: The second button will no longer be "under the mouse" when releasing. This is why "Wrapping the onBlur event in a setTimout with 0 ms will make it work." works.

**Comment by constantinpojoga** [comment]
@eps1lon Thanks for the quick response! Can you suggest any other approach other than setTimeout? Since this codesandbox is really light, the setState and the UI update happens instantly, so setTimeout with 0ms works fine. Unfortunately, in my case, I'm working on a pretty heavy application and the setTimeout + UI update may be delayed up to 0 to 60ms, depending on the page and API payload.

**Comment by eps1lon** [comment]
That heavily depends on the actual UI. Generally I would try to avoid moving pointer targets when the user is interacting with them. Can't help you much beyond that, sorry.

**Comment by constantinpojoga** [comment]
I will use `onTouchStart` and `onMouseDown` for now and will discuss a different approach with the design team. Thanks a lot!
