### ISSUE TITLE
Bug: error TS2694: Namespace '"react"' has no exported member 'ReactNode', 'DetailedHTMLProps', 'HTMLAttributes', 'SyntheticEvent', 'HTMLProps'

### ISSUE THREAD

**Issue by raphael10-collab** [facebook/react#20335]
In my react-typescript-electron project I have:

    "devDependencies": {
      "@types/react": "^17.0.0",
      "@types/react-dom": "^17.0.0"
     },
    "dependencies": {
      "react": "^17.0.1",
       "react-dom": "^17.0.1"
     }

I'm getting these error messages:

For this code:

    import React from 'react';
    type Props = React.HTMLProps<HTMLDivElement, HTMLDivElement>

I'm getting this error:

    error TS2694: Namespace '"react"' has no exported member 'HTMLProps'.
    type Props = React.HTMLProps<HTMLDivElement, HTMLDivElement>

For this code:

    import React, { useState } from 'react';
    interface Props {
    summary: React.ReactNode;
      children: () => React.ReactNode;
    }

I'm getting these errors:

     error TS2694: Namespace '"react"' has no exported member 'ReactNode'
     summary: React.ReactNode;

     error TS2694: Namespace '"react"' has no exported member 'ReactNode'
     children: () => React.ReactNode;

For this code:

     import React from 'react'
     type Value = React.ReactElement

I'm getting this error:

     error TS2694: Namespace '"react"' has no exported member 
    'ReactElement'
    

For this code:

    import React, { useState } from 'react';
    const onToggle = (e: React.SyntheticEvent) => {

I'm getting this error:

    error TS2694: Namespace '"react"' has no exported member 
    'SyntheticEvent'

For this code:

    import React from 'react';
    type Props =  
    React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, 
    HTMLDivElement>

I get these errors:

    error TS2694: Namespace '"react"' has no exported member  
    'DetailedHTMLProps'

For this code:

    import React, { Fragment } from 'react';
    export default function LogLink({ v, children }: Props) {
      function onClick(e: React.SyntheticEvent) {

I get this error:

    error TS2694: Namespace '"react"' has no exported member 
    'SyntheticEvent'

**Comment by eps1lon** [comment]
Sorry you're having issues.

However, this issue is a result of `@types/react` or rather TypeScript which is not released from this repository.

In the TypeScript playground your code is working fine (https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoGATzCTgAUcwBnOAXjjnOXRgDoAIkhgpgAGyQATABIAVALIAZRhBYAeHhj5ylAQRgwowAEYBXGEmZqdigcABuAUQkgkAOxgA+ADRcbdpxd3LyA) so this is likely an issue with your build setup.

You'll find better help by asking on stackoverflow or the [TypeScript discord server](https://discord.com/invite/typescript).
