### ISSUE TITLE
[eslint-plugin-react-hooks]: Can't use hooks in static class methods

### ISSUE THREAD

**Issue by d07RiV** [facebook/react#20342]
As title implies, eslint believes that using a react hook in a static method of a class not derived from anything is an attempt to call it in a class component.

    class Foo {
      // this is in fact a custom react hook
      static useSomething() {
        const [value, setValue] = React.useState(); // error: React Hook "React.useState" cannot be called in a class component. React Hooks must be called in a React function component or a custom React Hook
        // ... some logic
      }
    }

## The expected behavior

There are no class components involved, so the error makes no sense.

**Comment by kachkaev** [comment]
From the error message that you’ve been shown:

> React Hooks must be called in a React function component or a custom React Hook

What is the confusion about?

**Comment by Andarist** [comment]
I believe that OP would like to have this treated as a custom hook - which it technically can be used as a custom hook. I dont know though why one would like to define a custom hook like this. This would raise eyebrows in most codebases

**Comment by d07RiV** [comment]
I have multiple redux stores so I have a class wrapper over them that exposes store hooks as static methods and individual stores can derive from that class.. I could go more in depth why I chose that approach but this is hardly the place.

Maybe I misunderstand the purpose of eslint but it seems odd to enforce certain coding practices - after all, this is still a valid use of hooks.

**Comment by Andarist** [comment]
I've looked through tests of the `eslint-plugin-react-hooks` and it seems that your situation is pretty much equivalent to one of the test cases that are considered to be valid:
https://github.com/facebook/react/blob/e6a0f276307fcb2f1c5bc41d630c5e4c9e95a037/packages/eslint-plugin-react-hooks/__tests__/ESLintRulesOfHooks-test.js#L109

**Comment by VsevolodGolovanov** [comment]
I'm getting the error here:

```
export class Auth {

	static UI(props: PropsWithChildren<{}>): ReactElement<any> | null {
		const [authDataInited, setAuthDataInited] = useState(false);

		if (!authDataInited)
			Auth.init().then(() => setAuthDataInited(true));

		if (!authDataInited)
			return <p>Authenticating...</p>;
		else
			return <>{props.children}</>;
	}
```
But this IS a function component. It's just implemented as a static member function of a class.

**Comment by Ryszard-Trojnacki** [comment]
I have same issue when upgraded to 17.0.2 from 16.13.1.
I have class component (class Form, with context provider) and within this class I have functional subcomponents, that are only working with this context:
```javascript
export class Form extends React.Component {
  ...
  render() {
        return <FormContext.Provider value={this.context}>....</FormContext.Provider>;
  }

  static Control=({children, ...props}) => { ... }
  static Check = ({id, children, ...props}) => { ... }
  static Text = Form.Control;
  static Password = ({...props}) => <Form.Control type="password" {...props}/>
  static Email = ({...props}) => <Form.Control type="email" {...props}/>
}
```
so adding them as static of Form was logic for me. Also there are components from other library with those name, therefore it was better for me to write Form.Control, Form.Text etc.

Now this convention is not working.

**Comment by rdehuyss** [comment]
I also was able to use this before and it offered me a nice way to subscribe on ServerSentEvents using only one connection:

```
import React from 'react';

class StatsState {
    constructor() {
        this._listeners = new Map();
        this._data = {};
        this._data.stats = {estimation: {}};
    }

    setStats(stats) {
        this._data.stats = stats;
        this._listeners.forEach(listener => listener(stats));
    }

    getStats() {
        return this._data.stats;
    }

    useStatsState(obj) {
        const [stats, setStats] = React.useState(statsState.getStats());
        const cleanup = () => this.removeListener(obj);
        React.useEffect(() => {
            this.addListener(obj, setStats);
            return () => cleanup
            // eslint-disable-next-line react-hooks/exhaustive-deps
        }, []);
        return stats;
    }

    addListener(obj, listener) {
        this._listeners.set(obj, listener);
    }

    removeListener(obj) {
        this._listeners.delete(obj);
    }
}

const statsState = new StatsState();
Object.freeze(statsState);

const eventSource = new EventSource(process.env.REACT_APP_SSE_URL + "/jobstats")
eventSource.onmessage = e => {
    statsState.setStats(JSON.parse(e.data));
};

export default statsState;
```

In my components, I then just did the following:
` const stats = statsState.useStatsState(Sidebar);`

Is there a better way to do this?

**Comment by godmar** [comment]
Ditto here. The following sample (derived from the create-react-app starter demonstrates this:)
```js
import { useEffect } from 'react';
import './App.css';

// a regular class, not a React.Component 
class MyClass {
    render() {
      //
      // the useEffect call here appears in a function component,
      // that happens to call a method of a class that's unrelated
      // to React, not a class component.
      // eslint-disable-next-line react-hooks/rules-of-hooks
      useEffect(() => {
        console.log("calling useEffect");
      });
      return (
        <div className="App">
          Learn React
        </div>
      );
    }
}

function App() {
  const myClass = new MyClass();
  return myClass.render();
  // also not working:
  // return myClass.render.bind(myClass)();
}

export default App
```

without the `eslint-disable-next-line` the error message that's displayed is:
```
ERROR in src/App.js
  Line 12:7:  React Hook "useEffect" cannot be called in a class component. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
```
which is incorrect - it's not called in a class component.

This is important to address.  Are the rules of hooks that prescribe calling the hooks from the top-level render function there only to ensure that hooks are called deterministically on each call to the render function, or is there some deeper, unknown to us reason or semantics involved?

If this is merely a style issue, then it's safe to suppress, but with React as complex as it is I'm afraid there could be more to it.
I also believe that there are legitimate use cases where hooks can be called in nested functions (including static or non-static methods of classes) and this warning seems like an overly conservative restriction on the control flow pattern used in an application. The posts in this thread show some - I'm porting an application that was written using class components and extensively used a programming-by-difference style that I'd like to keep.  This would necessitate the calling of class methods from the a functional component's render function.

**Comment by louiszen** [comment]
Have you tried this instead? 
```
const NameSpace = {
   useSomething: () => {
       ....
   }
};
export default NameSpace;
```

I hate hooks for limiting coding styles and false claiming their stateful functions as FP and stateless, 
destroying the fundamental programming concepts, 
injecting side effects to pure functions, 
but still saying it can do "seperate of concerns" better than class.

React is forcing people to drop class components.
I am wondering how well they know JS, they even don't know JS class is used as namespace to orangize functions.
They just want people to drop Class components, even they lies that they are still willing to support class.

They don't know JS. JS is moving from functions to ES6 class, 
I once can see well organized coding instead of bundles of unmanaged global functions.
React is doing well to against it.
No hierarchical sense, no management and no organization, only magic left.

**Comment by gaearon** [comment]
This is an intentional choice.

Conceptually, Hooks are close to syntax. If they were syntax, we would only allow them in top-level functions. Once you put them in classes, it becomes too confusing what is safe to do and what’s not. (E.g. you can’t read mutable fields from the class itself but it’s not obvious.) It is difficult to audit a class with a bunch of Hooks inside for whether it works or has subtle bugs. Yes, static methods are safer, but in that case what are you gaining over using a function?

You may disagree with that choice and ignore the error. However, we suggest to only use Hooks in top-level plain functions, and we do not recommend using them inside any kind of a class. Even though it may (or may) not work correctly.

**Comment by LaGregance** [comment]
Hi,

I came 3 years after the battle, but I think there can be good use cases of having static class function that acts as a hook. In my case, I want each of my models to have a hook `Model.useModelInfo()` in order to return frontend specific stuff (translations for the model and his fields, utility functions to return JSX for fields to render them in a generic way...).

I understand the global choice to forbid this syntax by default to promote the standard usage in top-level function (who is better in 99% of case). But I think having a separate rule in the linter for this use case should be nice (because I don't want to disable `react-hooks/rules-of-hooks` for the whole project).

What do you think of this proposal to have a specific rule like `react-hooks/no-static-hook` that will be on by default and can be disabled?
