### ISSUE TITLE
[eslint-plugin-react-hooks] Bug: ESLint crashes if there's a `useEffect` / `useLayoutEffect` invocation without any arguments.

### ISSUE THREAD

**Issue by latin-1** [facebook/react#20343]
eslint-plugin-react-hooks version: 4.2.0

## Steps To Reproduce

I know it shouldn't exist in production code, but it's annoying while editing some files.

```js
import React, { useEffect } from "react";

const App = () => {
  useEffect(); // <-
  return null;
};

export default App;
```

Link to code example: https://codesandbox.io/s/polished-sun-3wr27?file=/src/App.js

## The current behavior

ESLint crashed.

```
TypeError: Cannot read property 'type' of undefined
```

## The expected behavior

ESLint doesn't crash but reports an error instead.

**Comment by dcastil** [comment]
I have the same issue, too. It's very annoying to get this warning any time I type `useEffect()` in VS Code.

<img width="478" alt="Screenshot 2021-01-11 at 17 23 36" src="https://user-images.githubusercontent.com/31006608/104209254-bf077600-5431-11eb-8c2c-03677c5001a4.png">

Thanks for fixing this! 🙏

**Comment by rickhanlonii** [comment]
Thanks @ChrisRu for the fix!

**Comment by Alecell** [comment]
I'm currently facing that error too and the case is the same that when the hook is empty, am I doing something wrong?

 "eslint": "^7.27.0",
 "eslint-plugin-react": "^7.24.0",
 "eslint-plugin-react-hooks": "^4.2.0",

**Comment by dcastil** [comment]
@Alecell eslint-plugin-react-hooks did not release a new version since this PR was merged. We need to wait until a new version of it gets releases (I'm waiting for the release too 😄).

You can use the same workaround as me in the meantime, a code snippet for `useEffect`:

```json
{
    "React useEffect": {
        "scope": "javascript,javascriptreact,typescript,typescriptreact",
        "prefix": "use effect",
        "body": ["useEffect(() => {$0})"]
    }
}
```

Then you can create effects by typing `ue` in a js/ts file.

You can read more about how to create snippets in VS Code here: https://code.visualstudio.com/docs/editor/userdefinedsnippets
