### ISSUE TITLE
Feature Proposal: Have stateTypes similiar to propTypes 

### ISSUE THREAD

**Issue by sktguha** [facebook/react#20365]
So it would be great if we could validate the types of state also at runtime similiar to propTypes. The added typechecking would definitely help in building more robust applications, for those who are not using typescript.

So it has already been discussed on SO, https://stackoverflow.com/questions/31220201/why-does-react-js-not-have-statetypes
The accepted answer does make some good points, but I feel it still misses out on some benefits , as mentioned in the comments 
1) https://stackoverflow.com/questions/31220201/why-does-react-js-not-have-statetypes#comments-31221006:~:text=It%20would%20still%20be%20nice%20to%20be%20warned%20when%20you%20set%20a and 

2) https://stackoverflow.com/questions/31220201/why-does-react-js-not-have-statetypes#comments-31221006:~:text=I%20disagree%20with%20the%20first%20sentence.%20Having%20experience%20with%20Typescript

also I see there is an old project which does this, don't think it works anymore ( https://github.com/tgriesser/state-types-react), but having it as part of React core would be better as it is beneficial for building robust applications.

I know React docs recommends flow or typescript for large projects but flow and typescript are both static type checkers. So having run time type checking can prove valuable IMO because it is entirely possible for complex and dynamic code that flow or typescript can miss some cases.

I also searched existing issues but didn't find this anywhere so creating this issue. I apologise in advance if this has already been discussed before here.

Also on an related note, maybe it is better to add a Feature Request template, for when creating a new issue in this repo for React feature requests.

Thanks
Saikat Guha ( sktguha@gmail.com )

**Comment by sktguha** [comment]
To the downvoter : care to explain the downvote ?

**Comment by bvaughn** [comment]
Thank you for this suggestion and proposal, but [we recommend using static type checking tools like Flow and TypeScript rather than `propTypes`.](https://reactjs.org/docs/static-type-checking.html) They can identify certain types of problems before you even run your code and they can improve developer workflow by adding features like auto-completion.

The same recommendation applies to the proposed `stateTypes`.

The React team does not currently plan to expand the class component API beyond some small additions to help with concurrent mode compatibility (like the recent static lifecycles).
