### ISSUE TITLE
Bug: simple useState and prop-passing is not working

### ISSUE THREAD

**Issue by Ardeshir81** [facebook/react#20381]
React version: 17.0.1

## Steps To Reproduce

1. create an array state.
2. update the array state through a callback and a setTimeout

Link to code example: https://codesandbox.io/s/dazzling-dirac-7lo7o?file=/src/HomePage.js (try filling in inputs at top of the page and clicking on save)

## The current behavior
nothing changes until another state change occurs (for example typing another thing in inputs)

## The expected behavior
I expected the new addition was added to the table immediately

![test1](https://user-images.githubusercontent.com/5755214/101222302-bbe4d180-369e-11eb-9ff4-c6e2564dbad7.gif)

**Comment by radunemerenco** [comment]
You're mutating the state with data.push(item).
Try this one: 
data = [...data, item];

Oh, and don't forget to use let data, instead of cost here.

![23F518EB-4B96-4046-BB9E-ED31E19C3FFE](https://user-images.githubusercontent.com/8158211/101224186-a5d31300-3696-11eb-9740-37d7d38bd263.png)

Pay attention to lines 1 and 3.

One last thing. Before opening an issue here, try posting a question on StackOverflow.

I propose to close this issue.
