### ISSUE TITLE
[React DevTools] Bug: irrelevant "Cannot update a component from inside the function body of a different component"

### ISSUE THREAD

**Issue by jsamr** [facebook/react#20418]
There are situations where the warning  "Cannot update a component from inside the function body of a different component" seems irrelevant.

1. Consider a third party component which has a `renderStuff` prop to customize the rendering of sub-views.
2. This `renderStuff` prop passes arguments that are relevant for the parent component.
3. The warning "Cannot update a component from inside the function body of a different component" will trigger because the parent sets a cached value of this interesting argument with a `setXXX` call.

React version: 16.13.1

## Steps To Reproduce

See minimal demo: https://codesandbox.io/s/irrelevant-warning-khe6r

## Details

In my use-case, I need to cache an animated object (from React Native).

**Comment by bvaughn** [comment]
The warning you're complaining about has been discussed on several other issues, like #19070 and #18178.

We warn about it because it doesn't have predictable, consistent behavior. In your example, what happens if `ThirdPartyComponent` is rendered more than once? Which "cached value" will end up being used?

To quote [Dan's comment from another issue](https://github.com/facebook/react/issues/19070#issuecomment-651880928):
> It doesn't have a consistent behavior that you can confidently reason about. What if you render two <PanelTitle>s? Which one of them wins? The first one? By the order in the tree or by the order of insertion? What if initially there are no <PanelTitle>s but later they get inserted? What if the last <PanelTitle> gets deleted? What if it changes over time? What if the child component becomes lazy-loaded and isn't available immediately? How would this work with server rendering? How would this work with streaming server rendering?
>
> Aside from all of these semantic issues, there are also significant performance implications to rendering a tree only to find out that actually, it needs to be re-rendered from the top because we have new information once we reach a leaf. Maybe okay in a few cases but this doesn't really scale.
Aside from all of these semantic issues, there are also significant performance implications to rendering a tree only to find out that actually, it needs to be re-rendered from the top because we have new information once we reach a leaf. Maybe okay in a few cases but this doesn't really scale.

I don't think the example code highlights anything that wasn't already discussed in those other issues, so I'm going to close this.

A note though: React DevTools doesn't have anything to do with this warning. If you mention it because of the location of the console log, that's an artifact of DevTools [overriding the console to append "component stacks"](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#component-stacks). Unfortunately browsers do not provide an API for us to do this in a less observable way. 😞
