### ISSUE TITLE
Bug: BigInt does not get toString()'d when rendered

### ISSUE THREAD

**Issue by andyboyne** [facebook/react#20492]
<div>{1n}</div> should render 1. Instead it renders ''.  

It looks like 'bigint' just needs adding here: https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ToStringValue.js#L26. 

Happy to raise a PR or take guidance on a better approach.

React version: all

## Steps To Reproduce
Link to code example: https://codepen.io/boyne/pen/vYXJWVr

## The current behavior
Renders ""

## The expected behavior
Renders 1

**Comment by eps1lon** [comment]
> Happy to raise a PR or take guidance on a better approach.

You've already identified a possible solution on the client. But I think the server might also need adjustment.

In any case, this feature needs some test. I believe you would need to add tests to:
- `packages/react-dom/src/__tests__/ReactDOMServerIntegrationBasic-test.js` (for server side rendering)
- `packages/react-dom/src/__tests__/ReactServerRenderingHydration-test.js` (for hydrating)
- `packages/react-dom/src/__tests__/ReactDOM-test.js` (for client side rendering)

Though there might be some stress cases for using BigInt with the newly proposed Server Components since not all BigInts are serializeable. 

You could start working on it and open a PR with your latest progress. But please be aware that I'm not not a maintainer and can't decide if your work is going to be accepted or not. However, I do believe that the work would be appreciated.

**Comment by HSchmale16** [comment]
This also affects me too. Is there any word of resolution?

I can confirm that it is still happening with React 17.0.2.

Working on building a numerical simulation and would prefer not to have `toString` on all my outputs.
