### ISSUE TITLE
“Visible” property.

### ISSUE THREAD

**Issue by ciglsias** [facebook/react#20508]
Hiding Components is a so used case, maybe a “Visible” property would be good. It would get a cleaner code a think.

**Comment by bonoldie** [comment]
There are several other methods to conditionally render or hide(CSS display,opacity...) an Element. A visible property would be redundant.
If you need this feature you can think about an HOC.

**Comment by robertpiosik** [comment]
Putting it in another words, you just create a component, which receives `isVisible` prop and renders children if passed expression evaluates to true.

```ts
import React from 'react';

type ConditionalWrapperProps = {
  isVisible: boolean;
  children: React.ReactNode;
};

const ConditionalWrapper = (props: ConditionalWrapperProps) => (props.isVisible ? <>{props.children}</> : <></>);

export default ConditionalWrapper;
```

**Comment by eps1lon** [comment]
The previous response should give you a good direction what you might want to do. I'll just add some more general community resources and close this since this issue isn't actionable otherwise.

Coding Questions
If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

stackoverflow.com/questions/tagged/react

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html

**Comment by ciglsias** [comment]
> There are several other methods to conditionally render or hide(CSS display,opacity...) an Element. A visible property would be redundant.
> If you need this feature you can think about an HOC.


If I create a new Component, it does not have a Display property. It requires extra job. Small, but extra. And it is very a often common case.
React created a “key” property for components. It is also redundant with Html Id. 😁

**Comment by ciglsias** [comment]
> The previous response should give you a good direction what you might want to do. I'll just add some more general community resources and close this since this issue isn't actionable otherwise.
> 
> Coding Questions
> If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.
> 
> stackoverflow.com/questions/tagged/react
> 
> Talk to other React developers
> There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.
> 
> https://reactjs.org/community/support.html

It was a suggestion to React, as a product. Not a question.

**Comment by robertpiosik** [comment]
Key is not redundant with html id because id is renderend to the DOM and key is used internally by the framework.
