### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by ilteoood** [facebook/react#20520]
Hi guys,
I would really like to join you in order to help with the maintenance of React.

My change proposal is to apply the clean code rules to React codebase; for example:
- better name to variables
- single point of return
- have short functions with a single purpose
- ...

In order to avoid a long code review process, I would like to make 1 PR for each package that I'm going to edit.

I've already signed the CLA. 

Hope you'll be interested in this,

Matteo

**Comment by robertpiosik** [comment]
I believe that everyone is free to contribute and PRs are welcome but I would avoid major refactors as those could waste your time in case of being rejected.

**Comment by bvaughn** [comment]
Matteo,

Robert's right that anyone can propose changes by creating a pull request. I appreciate you reaching out and asking in advance about the types of changes you're considering. It's difficult to say since the things you listed are still pretty vague, but I would anticipate that you'd have a difficult time landing many of those types of changes. There's always room for improvement, but the code in this repository is often written in a certain way for performance reasons (or other considerations, not arbitrary).

Hope this response helps answer your question. I'm going to close this issue. See you in a future PR.
