### ISSUE TITLE
Update docs to reference @babel/cli

### ISSUE THREAD

**Issue by drazisil** [facebook/react#20535]
On https://reactjs.org/docs/add-react-to-a-website.html#add-jsx-to-a-project I believe that step 2, `npm install babel-cli@6 babel-preset-react-app@3` should be changed to `npm install @babel/cli babel-preset-react-app@3`

This will allow users to upgrade to a version that does not use a very outdated version of micromatch. https://www.npmjs.com/advisories/786

Micromatch is no longer used in babel https://github.com/babel/babel/commit/6d177ba4c554136e9d6175b4162d6d84fbc85c52

**Comment by eps1lon** [comment]
That's a good point. 

That whole page is still using class components though. I strongly suspect this part will be obsolete after https://github.com/reactjs/reactjs.org/issues/3308. Especially because we can't just update the used packages but also have to make sure subsequent steps are still valid

I'm closing this issue in favor of https://github.com/reactjs/reactjs.org/issues/3308 since we'll likely forget this issue here.
