### ISSUE TITLE
UncaughtException detected: java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by fjdpaul** [facebook/react#20545]

**Comment by eps1lon** [comment]
Looks like this is unrelated to React and even JavaScript since the error message comes from Java.

Please provide a CodeSandbox (https://react.new/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. 

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
