### ISSUE TITLE
Bug: Opacity Reduces to 1% When Adding a Background Image with a defined Opacity

### ISSUE THREAD

**Issue by Jackmt9** [facebook/react#20569]
React version: 16.13.1

## Steps To Reproduce

1. Set a css property `background-image: url(...)`
2. Deploy the project (BUG ONLY VISIBLE ON PRODUCTION BUILD)

Link to code example: https://github.com/Jackmt9/portfolio_site/tree/9f6b1f53f33f22386cf473bdc956774027059035
(See about and home page - there should be an image there.)

## The current behavior
Opacity of the image reduces to 1%

## The expected behavior
Opacity should be as defined, not 1%

##Workaround
Set the opacity value as a decimal instead of a percentage (90% => 0.9)

**Comment by Jackmt9** [comment]
Also see: https://github.com/facebook/create-react-app/issues/7980

**Comment by eps1lon** [comment]
Thanks for the report.

As you already discovered, this issue was already reported in create-react-app where it was identified that the issue is with https://github.com/NMFR/optimize-css-assets-webpack-plugin (https://github.com/facebook/create-react-app/issues/7980#issuecomment-559534896).


I recommend opening an issue in https://github.com/NMFR/optimize-css-assets-webpack-plugin as this issue  is not actionable from within the React repository. A fix or workaround is only viable from the create-react-app or optimize-css-assets-webpack-plugin repository.
