### ISSUE TITLE
Bug: Setting an object variable using a useState hook inside an img onLoad function triggers an infinite loop

### ISSUE THREAD

**Issue by AndrewF5543** [facebook/react#20592]
React version: 17.0.0

## Steps To Reproduce

1. Initialize an object variable with the useState hook:  `const [testObject, setTestObject] = useState({})`
2. Create a function which returns an <img> that includes an onLoad function: `<img onLoad={handleLoad} src={logo} />`
3. Within the onLoad function, set the object variable:
```
const handleLoad = () => {
  setTestObject({test: 'This triggers an infinite loop'})
};
```

Link to code example: https://codesandbox.io/s/usestate-object-infinite-loop-8mde0?file=/src/App.js

## The current behavior
When setting an object variable using a useState hook inside an img onLoad function, an infinite loop is triggered. This same issue isn't triggered when setting a string variable.

## The expected behavior
Setting an object variable with a useState hook inside an img onLoad function sets the variable, and no further actions are triggered

**Comment by eps1lon** [comment]
Thanks for the report.

The problem is that you're re-creating the `img` DOM element on every render so after every render the `onLoad` effect will be fire. Since you cause a re-render with your `onLoad`, the component re-renders indefinitely.

The reason for that is [how React reconciles two UI trees](https://reactjs.org/docs/reconciliation.html#elements-of-different-types). If it finds two elements with a different type it throws a way the whole tree of the old element.

In your `App` you're returning `<RenderLogo />`. When React compares the old element with the new element it'll find that the component types are different and throws away the old tree created by the element. That old tree contains the `img` element so it mounts a new `img` element and a new `onLoad` event is fired. The element type changes because you create it inside the render function:

```js
const RenderLogo = () => {
  console.log("Rendering logo!");
  return <img onLoad={handleLoad} src={logo} />;
};

return <RenderLogo />; 
```

What you can do to avoid this, is move the `RenderLogo` outside of the `App` component and pass props to it instead:

```jsx
const RenderLogo = ({ logo, onLoad }) => {
  console.log("Rendering logo!");
  return <img onLoad={onLoad} src={logo} />;
};

export default function App() {
  ...
  return <RenderLogo logo={logo} onLoad={handleLoad} />
}
```

I hope that helps. Please let me know if anything is unclear.

**Comment by AndrewF5543** [comment]
Hello,
Your explanation, for the most part, makes total sense. I definitely understand in principle now that I set myself up for an infinite loop with the way that I structured RenderLogo.

That said, I do have one final question at this point. Why does setting a variable in the way that I did trigger a re-render of the screen? That's ultimately my biggest source of confusion at this point.

Thanks again for your help!

**Comment by eps1lon** [comment]
> Why does setting a variable in the way that I did trigger a re-render of the screen? 

It triggers a re-render if the received value in `setState(value)` is not equal (`Object.is` equality but "referential equality" is the relevant part here) to the current state. Since you call it with `setTestObject({test: 'This triggers an infinite loop'});` the received value is always different compared to the current value (`Object.is({test: 'This triggers an infinite loop'}, {test: 'This triggers an infinite loop'}); // returns false`). 

You can think of it in another way:
`setState` always triggers a re-render. However, in some scenarios it does not (it "bails out") which are described in [Hooks reference: Bailing out of a state update](https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update)

About referential equality: https://dmitripavlutin.com/how-to-compare-objects-in-javascript/#1-referential-equality
About equality comparisons in JS: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness

**Comment by AndrewF5543** [comment]
Ah, okay. That makes total sense. Thanks for the detailed explanation!
