### ISSUE TITLE
React state is updated still getting outdated state in the function

### ISSUE THREAD

**Issue by GauravKatariya** [facebook/react#20619]
I have a sample application. It has a breadcrumb and a button. On click of button the breadcrumb should add a folder and on click of breadcrumb item, the breadcrumb should remove the items next of clicked item.

React version:
17.0.1

## Steps To Reproduce

1. Click on "click" button, twice.
2. Click on "folder_0" breadcrumb item.
3. removeFromBreadCrumb is not able to access the current state.

Link to code example:

https://codesandbox.io/s/usestate-object-infinite-loop-forked-17tkv?fontsize=14&hidenavigation=1&theme=dark

## The current behavior
On click of breadcrumb item, the invoked function is not able to access the current state.

## The expected behavior
Invoked function should access the current state

**Comment by eps1lon** [comment]
Thanks for the report.

Whenever you want to update state based on the current state, you should use [functional state updates](https://reactjs.org/docs/hooks-reference.html#functional-updates).

I applied this pattern to your codesandbox and it seems to result in the expected behavior: https://codesandbox.io/s/usestate-object-infinite-loop-forked-dk7vv

Does this solve your problem?

**Comment by GauravKatariya** [comment]
Awesome!! yeah it will work for me. Thanks alot.
