### ISSUE TITLE
sucrase support for react-fast-refresh

### ISSUE THREAD

**Issue by zcaudate** [facebook/react#20637]
I've filed an issue here:

https://github.com/alangpierce/sucrase/issues/590

But I'm hoping to get `official` support from the react team. I'm really hoping that `react-fast-refresh` can add support for [sucrase](https://github.com/alangpierce/sucrase) in addition to babel. 

Babel is about 4 to 5 times slower than sucrase. On the current app I'm working on:

- With `Babel` + `react-fast-refresh`
  - Initial Compile (with Caching): 50 secs
  - Compilation Time: 6-8 secs 
  - Refresh: 0.5 secs

- With `Sucrase` + `react-hot-loader` + `code that sets state`
  - Initial Compile (without Caching): 15 secs (with Caching): 11 secs.  -> (4 - 5x)
  - Compilation Time: 1-2 secs -> (5 - 7x)
  - Hot Load: 0.5 secs
  - Set State: 0.2 secs 

I thought that my sucrase setup could be faster so I changed to the babel/fast-refresh for the last couple of days. I have since changed back and will not even consider using `react-fast-refresh` unless it can be used without babel. As much as I don't like writing the code to change state, it was just infuriatingly slow - and mostly due to babel.

I'd really hope that the team can consider adding sucrase support because it would make everything much much faster and the experience a lot better.

**Comment by rickhanlonii** [comment]
Hey @zcaudate, thanks for submitting the request.

Since we're a small team and there's a huge community of transforms and bundlers, we're not able to own creating integrations for every library. Our approach is to document the API, provide an example plugin via Babel, and help the community implement Fast Refresh into their own ecosystem. If it meets the API spec and covers all supported use cases, then it is considered "officially" supported.

For that reason, the issue you created in Sucrase is best to track this work. To do the integration, please see the docs [here](https://github.com/facebook/react/issues/16604#issuecomment-528663101) and reference the Babel plugin [here](https://github.com/alangpierce/sucrase/blob/master/src/transformers/ReactHotLoaderTransformer.ts).

**Comment by zcaudate** [comment]
@rickhanlonii: Is the link to the issue the only place where integration for fast-refresh is documented?

**Comment by rickhanlonii** [comment]
There's also docs [here](https://reactnative.dev/docs/fast-refresh).
