### ISSUE TITLE
propagateContextChange visits all child fibers

### ISSUE THREAD

**Issue by intellild** [facebook/react#20661]
`propagateContextChange` in the current context implementation visits all child fibers rather than fibers that have dependency on the context.
In my case, there may be thousands of child components and 99% of them don't have dependency on the context, which causes `propagateContextChange` spends a lot of scripting time but eventually does 'nothing'.

**Comment by gaearon** [comment]
It visits all fibers because that's its purpose — to find the ones that depend on context. There are some ways we're planning to optimize the algorithm but they'll need significant refactors so don't count on them happening soon. 

*However*, it is possible that there might be some ways to optimize the function itself. It could very well be possible that it has become slower since the initial implementation due to some accidental deopt or compiler behaivor. So if you want to make a synthetic benchmark to stress-test it, and look for optimization opportunities, that would be appreciated.

**Comment by intellild** [comment]
@gaearon I can have a try. There are two versions of files in react-resonciler(old.js and new.js). Which should I modify?

**Comment by gaearon** [comment]
Not sure which ones you'll get on build.. Try changing both and see which gets used?

**Comment by intellild** [comment]
I opened a draft pull request #20786 
Improvements are significant. I use [https://github.com/intellild/react-context-performance](url) for profiling.
This implementation uses a 32bit number as a bitset. If there are more than 32 contexts, it falls back to the current logic.
Choices are:
* Keep the 32bit number, only 32 contexts optimized
* Implement a Hash Array Mapped Trie style "HashSet" which can be highly optimized for this scenario.
* Use bigint
If using a HashSet or bigint, it is possible to remove the propagateContextChange. Instead, we can check contexts while reconciler walking down the tree.

## before
![屏幕截图 2021-02-10 211229](https://user-images.githubusercontent.com/8379858/107516019-c2d01900-6be6-11eb-8a2f-d04314d35667.png) 
## after
![屏幕截图 2021-02-10 211602](https://user-images.githubusercontent.com/8379858/107516026-c5327300-6be6-11eb-8e6d-64823f24b353.png)

**Comment by intellild** [comment]
I noticed that the `bubbleProperties` spent a lot of time on my branch. It seems that I missed something related to bailouts.

**Comment by gaearon** [comment]
Thanks for the PR! I don't think this approach would work for us because then you have a performance cliff as soon as you have more than 32 contexts. We generally prefer predictable performance over fast in all cases, because otherwise seemingly small changes can have disproportionate impact on the whole application, and it becomes very difficult to debug perf problems.

**Comment by intellild** [comment]
After some rethinking, it seems a number array is good enough, since there won't be large number of contexts. I will have a try later

**Comment by gaearon** [comment]
>since there won't be large number of contexts

This is not correct; we should expect that a large app (which is where this optimization is most needed) _will_ have a large number of contexts.

**Comment by gaearon** [comment]
By the way, originally I referred to optimizing in terms of optimizing the brute force traversal itself. It's quite likely that there might be some engine deopts there, e.g. due to how GCC compiles code. So it would be good to look into the compile output and if there are ways to optimize it.

**Comment by intellild** [comment]
> large number of contexts
I mean thousands of contexts. One number supports 32 contexts and a number array with length 32 supports 32 * 32 contexts. That's 1024 contexts and 32 is only one tree node size of a hash tree. Thus I believe this is quite enough to optimize the scenario and a hash tree is not necessary.

**Comment by intellild** [comment]
I checked the output of production build and closure compiler did a great job.

I tried the array method and it works fine although the implementation is not correct. Will this get merged ? I will finish it if it would get merged

**Comment by markerikson** [comment]
@intellild my guess is probably not, given that Andrew is already working on https://github.com/facebook/react/pull/20646 and https://github.com/facebook/react/pull/20890 .

**Comment by intellild** [comment]
@markerikson Thanks. I read the PR and it seems they are not conflicting

**Comment by markerikson** [comment]
Hmm. Well, if it doesn't conflict there might be a chance, but that'd really be an @acdlite kind of question.

**Comment by windmaomao** [comment]
Just out of curiosity, i wonder how this finding child fiber can be optimized. A fiber can be very deep deep down the branch, the official version traces from the origin of the context to each child, because each fiber has a `dependencies` to hold all contexts. 

If we go the opposite way, suppose we store all fibers referencing the context in the context fiber's `contextChilds`. In `readContext`, we do this

```
function useContext(context) {
  // go find the context fiber in currentlyRenderingFiber's ancestors 
  // and then add the currentlyRenderingFiber into `contextChilds`
  markUpdateContextFiber(context, currentlyRenderingFiber)
  
  return context._currentValue
}
```

Then maybe this will save work in `propagateContextChange`. Of course i don't know how this happens to the nested Providers, maybe just going up till it hits the first context that matches. Anyway just an idea.

**Comment by intellild** [comment]
> If we go the opposite way, suppose we store all fibers referencing the context in the context fiber's contextChilds. In readContext, we do this

@windmaomao  I'm afraid there are some concurrent issues that are very hard to resolve
