### ISSUE TITLE
The final argument passed to useEffect changed size between renders. The order and size of this array must remain constantBug: 

### ISSUE THREAD

**Issue by duuliy** [facebook/react#20674]
React version: 16.14.0

## Steps To Reproduce

When I write a complex component, each small function in it uses a lot of useeffect, and returns different numbers according to different types. When I change the number of returned functions due to parameters, I report an error.
"The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant."

## The current behavior
But when I change the code,bring into correspondence with
 useEffect(() => {

    }, [null, null),null])
Still can't solve the problem

## The expected behavior
Should I prompt you like this "Rendered fewer hooks than expected..."

**Comment by eps1lon** [comment]
Thanks for the report.

Without seeing the actual code I'm suspecting you return early in a function violating the [rules of hooks](https://reactjs.org/docs/hooks-rules.html). Something like

```jsx
export default function App() {
  const [count, increment] = useReducer((n) => n + 1, 0);

  if (count === 0) {
    useEffect(() => {}, [count, count]);
  } else {
    useEffect(() => {}, [count]);
    useEffect(() => {}, []);
  }

  return <button onClick={increment}>click me</button>;
}
```
-- https://codesandbox.io/s/gracious-beaver-9uu20?file=/src/App.js

Is your issue with too many error messages or that there is an error at all?

It would help a lot if you can share the code so that we can better identify what kind of error message would help you solve the problem.

**Comment by bvaughn** [comment]
Closing due to lack of info.

**Comment by Madhuri-Dodla123** [comment]
Hi @bvaughn 
I encounter the same issue mentioned above , 

**Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.
Previous: []
Incoming: [true, A.R.T]**

I am using useEffect, with mutliple dependencies array .
This is how my useEffect looks:
![image](https://user-images.githubusercontent.com/94153013/186093526-e2eed14b-e4f6-440e-8acd-4c5b1a4fd784.png)

Ref Screenshot for Error:
![image](https://user-images.githubusercontent.com/94153013/186093144-fdb12b94-1c60-4207-bb00-8f0f2abc8ee9.png)

Can anyone helps me with this error ?
Let me know if more details needed.

Thanks

**Comment by duuliy** [comment]
> 



> Hi @bvaughn I encounter the same issue mentioned above ,
> 
> **Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant. Previous: [] Incoming: [true, A.R.T]**
> 
> I am using useEffect, with mutliple dependencies array . This is how my useEffect looks: ![image](https://user-images.githubusercontent.com/94153013/186093526-e2eed14b-e4f6-440e-8acd-4c5b1a4fd784.png)
> 
> Ref Screenshot for Error: ![image](https://user-images.githubusercontent.com/94153013/186093144-fdb12b94-1c60-4207-bb00-8f0f2abc8ee9.png)
> 
> Can anyone helps me with this error ? Let me know if more details needed.
> 
> Thanks

Look at this https://reactjs.org/docs/hooks-rules.html

**Comment by Madhuri-Dodla123** [comment]
Thanks @duuliy for quick reply
I have gone through the above link, seems like i dont understand the issue in my code.
1. I didnt write useEffect in condition, inside useEffect wrote conditional calling method beacuse on changing of every dependency and the condition statisfies then i need to call the function to get data. Correct me if this does not make sense.
2.Is it causing because of calling the method **fetchInitialPage** on conditional rendering ?
