### ISSUE TITLE
Reset password link is not working

### ISSUE THREAD

**Issue by Linawho** [facebook/react#20679]
Hi, I have added a link on my reactjs website for users, who forgot their login passwords, to click on the link so that a reset password link will be sent to each of them. But after I (assuming I am the user) clicked on the link, I didn't get an email (which has a link to reset my login password) even though my mongodb database gets updated with a reset password link data added to my mongodb database each time a user click on the reset password link. Thank you.

**Comment by tq963hnmt** [comment]
Have you used CORS on your Nodejs server?

**Comment by bvaughn** [comment]
This does not sound like an issue caused by React.

Regardless, support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

##### Coding Questions

If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

[https://stackoverflow.com/questions/tagged/react](https://stackoverflow.com/questions/tagged/react)

##### Talk to other React developers

There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

[https://reactjs.org/community/support.html](https://reactjs.org/community/support.html#popular-discussion-forums)
