### ISSUE TITLE
Powerful Feature - SSR async fetching for resources via lifecycle method

### ISSUE THREAD

**Issue by onzag** [facebook/react#20701]
When doing SSR it's very hard to fetch resources that are dynamic, and while you have been trying to introduce the quite complex suspense API, I had to come with a simpler solution for my use case.

Simply adding a lifecycle method that executes only during SSR via react-dom, that is async (which makes the whole renderToString) method async indeed; which allows to update the initial state, it's extremely simple, and it works (I have tested it).

Let me make an example to illustrate this further suppose we have a component named `ResourceFetcher` which does what it claims and fetches a resource, now let's suppose our react developer simply would use it like this.

```
<ResourceFetcher resource="data.json">
  {(data) => (
    <ResourceFetcher resource={data.secondaryResource}>
       {(secondaryData) => (
          <div>HERE I DISPLAY THE DATA</div>
       )}
    </ResourceFetcher>
  )}
</ResourceFetcher>
```

Imagine the nightmare that it would be to setup this with SSR, specially when the resource fetcher can be used arbitrarily, we would have to duplicate the logic to collect the data when we know we are at the right url where that would be rendered; it can simply be quite hard and it has to be done with each page, and with routes on the mix, dynamic paths, query strings that affect what is required, the server side logic becomes overwhelming.

Now let's imagine we now have a `<ResolverContext>` that sits above all our app, this provides an instance into our resource fetcher that specifies how it is to resolve using the resource fetcher, it also contains a cache that the resource fetcher can use.

So what the resouce fetcher is doing is on the `constructor` it will try to load a value from the cache and on `componentDidMount` if it is not loaded (because it was not found in the cache) it will run a fetch request.

Now imagine we have a method called `beforeServerSideRender` that is async and executes right before render on server side only, and it prepares the state on this case, on constructor our cache is indeed empty, but then `beforeServerSideRender` triggers, and we can "resolve" these resources that we need, in the case of the server side, the resolver is not fetch, it simply reads from disk; the server can then have a form of collector, and sets the variable `window.CACHE = ` so that the client can setup its initial cache in the context.

The result is that you have a very easy to setup SSR that can work with basically anything that requires no configuration once your environment is dialed, I managed to create extremely rich dinamically loaded SSR pages with that method with very little fuzz, I don't need to make a list per page of what I need, it is just done on the fly.

What I did was the following:

```
react-dom/src/server/ReactDOMNodeStreamRenderer.js

-  _read(size) {
+  async _read(size) {

-      this.push(this.partialRenderer.read(size));
+      this.push(await this.partialRenderer.read(size));

react-dom/src/server/ReactDOMStringRenderer.js

-export function renderToString(element, options?: ServerOptions) {
+export async function renderToString(element, options?: ServerOptions) {

-    const markup = renderer.read(Infinity);
+    const markup = await renderer.read(Infinity);

-export function renderToStaticMarkup(element, options?: ServerOptions) {
+export async function renderToStaticMarkup(element, options?: ServerOptions) {

-    const markup = renderer.read(Infinity);
+    const markup = await renderer.read(Infinity);

react-dom/src/server/ReactPartialRenderer.js

-function resolve(
+async function resolve(

-    processChild(element, Component);
+    await processChild(element, Component);

-  function processChild(element, Component) {
+  async function processChild(element, Component) {

+
+    if (inst.beforeServerSideRender) {
+      await inst.beforeServerSideRender();
+    }
     child = inst.render();

-  read(bytes: number): string | null {
+  async read(bytes: number): string | null {

-          outBuffer += this.render(child, frame.context, frame.domNamespace);
+          outBuffer += await this.render(child, frame.context, frame.domNamespace);

-  render(
+  async render(

-      ({child: nextChild, context} = resolve(child, context, this.threadID));
+      ({child: nextChild, context} = await resolve(child, context, this.threadID));
```

And that was it, with that I had given superpowers to SSR, no longer I needed lists to specify what resources I needed ahead of time, I could just get that when react was rendering; it did not affect anything else than the server side if they had that lifecycle function, but everything worked normally.

Not just that but with this method, if the SSR crashed for some reason, it still worked!... I'd just be served the default version with an empty cache since the collection failed, and the resources will be fetched on mount; just that the initial page will be, without proper SSR, but no fuzz, it still worked; so it is crash resistant.

There seem to be a problem with the development mode, it works but doesn't take much pressure as it cannot overlap renders in the async mode, but works in production builds. This is why I make this issue and not a PR.

Just that simple lifecycle function adds way too much power and it's a very simple change, I think it should be implemented, specially because we don't have suspense, and some people don't feel comfortable with the idea of suspense; this solution is extremely simple, but it works.

https://www.npmjs.com/package/@onzag/react-dom

**Comment by mariusrak** [comment]
If this works, maybe we could use currently available lifecycle methods. Methods would return true if they requested some data and rerender would be required. SSR then could work this way:

1. The `componentDidMount` method will be called first - before render - instead of `beforeServerSideRender`.
2. If method call is resolved with `true` it means, it fetched some data, some `setState` was called and based on new state it will be updated again. If method returns false, Proceed with step 4.
3. The `componentDidUpdate` method will be called in a loop with condition by it`s return - proceed with step 2.
4. When methods return false, no more "rerenders" are needed so we can do final render - really call `inst.render()` and finish.

So the code could be like this:
```js
const needUpdate = inst.componentDidMount && await inst.componentDidMount();
if(inst.componentDidUpdate)
{
    while(await inst.componentDidUpdate(/* not sure how to get prevProps, prevState*/));
}
child = inst.render();
```

It might nicely solve a giant problem with SSR.

**Comment by mariusrak** [comment]
@onzag, what do You think? Would you try it? I'm not experienced in editing code of such a big project as react.

**Comment by onzag** [comment]
@mariusrak sorry for the late reply, I don't think the componentDidMount method is better because that means it has to rerender again, if anything the `getDerivedStateFromProps` would be more suitable for that but `getDerived` isn't async and runs in any context.

Modifying the did mount could actually break existing projects, same for the getDerived, whereas a new lifecycle function simply not affect anything, old projects would still work just fine with whatever they were doing, new projects could use that function, it's 100% backwards compatible.

It has a big of different thinking on the way you have to do thing using this new function, but it works; and it's a simple change on react itself, as I have tested it and I run that on my own projects.

There are however two issues with what I have proposed.

1. There is no hook eg. `useServerSideRender` in fact I don't think it would work with a hook at all, just like you don't have a hook for getDerived.
2. On development builds if you stress test a server it sometimes fail to render due to the way react development debugging works, with an async method the render becomes async.
3. Stream rendering does not seem to work.

But the benefit is huge, and the way this works is extremely simple; The suspense API is rather complex.

**Comment by mariusrak** [comment]
> 
> 
> @mariusrak sorry for the late reply, I don't think the componentDidMount nor DidUpdate method is better because that means it has to rerender again, if anything the `getDerivedStateFromProps` would be more suitable for that but `getDerived` isn't async and runs in any context.

`render` should be pure function. It should not change any state nor have any effects. Therefore it does not matter on server side if component is rendered or not. That's why I propose only calling `componentDidUpdate` in a loop. And after no more of it is needed to be called, redner can happen. So no rerendering. (There would be some edge cases which should be also solved, like calling method provided from parent, but I think It is possible to solve).

> 
> You are wondering where are you going to get the props, well, that is exactly from the render itself that passes the props at the end of the day, so when updating the state, those props will have to be passed, it's a logistical nightmare, and a huge change to react-dom in that case, whereas a separate function, is a small change.

Yeah, but once all the props are ready, just after that they are passed to children. Then they can be picked up in children's `DidUpdate`. Also, with state - state can not be changed in render. State is changed in `DidMount`, `DidUpdate` or some event. On server, there are no DOM events, so only data fetching events can happen and they can be wrapped in async/await. It is not clear to me where you see the logistical nightmare. But that can be because of my insufficient knowledge of rendering process.

> 
> Modifying the did mount could actually break existing projects, same for the getDerived, whereas a new lifecycle function simply not affect anything, old projects would still work just fine with whatever they were doing, new projects could use that function, it's 100% backwards compatible.

Currently it is possible to make `DidMout` and `DidUpdate` async and it doesn't matter to anything where they are sync or async. So there is no change. Further, currently those method does not return anything. And they would still not be required to retrun anything to preserve compatibility. But if they return, it would control SSR.

Currently, for client-side - browser code, those two functions are extensively used. They provide some sort of logic and usefulness. This logic should be preserved on SSR. Adding a new method, which is dedicated only to SSR reduces possibility to write isomorphic code. That's why I propose to use almost same API for client as for server. With `beforeServerSideRender·we would have to do data fetching in two methods. With my proposal, we can do data fetching only in one. So it will not only enhance izomorphism and provide backward compatibility, but also allow SSR with older projects. Maybe with some minor changes required.

> 
> It has a big of different thinking on the way you have to do thing using this new function, but it works; and it's a simple change on react itself, as I have tested it and I run that on my own projects.

Using already introduced method would reduce this "different thinking" and I believe it would also work.

> 
> There are however two issues with what I have proposed.
> 
>     1. There is no hook eg. `useServerSideRender` in fact I don't think it would work with a hook at all, just like you don't have a hook for getDerived.

I have no idea how are hooks implemented, but I believe we would be able to similarly adapt hooks as I propose adapting `DidUpdate`/˙DidMount`.

> 
>     2. On development builds if you stress test a server it sometimes fail to render due to the way react development debugging works, with an async method the render becomes async.

Is this issue only with dev. debugging? It seems like an issue with fiber engine and that could be giant issue with any asynchronicity.

> 
>     3. Stream rendering does not seem to work.

I'm afraid it would not be possible to enable full streaming of server-side rendered react app, since it should be able to update "upper" components (e.g. helmet). But beside that I see no problem in streaming with your proposal.

> 
> 
> But the benefit is huge, and the way this works is extremely simple; The suspense API is rather complex.

I see the benefits and I would love to see it in prod. I also believe using current API provide much more benefits, so we could maybe try it this was.

**Comment by onzag** [comment]
Let me start by saying that some people might return stuff from did mount; mistakenly or not, which means there's potential for breaks.

Imagine this code:

```
<ResourceFetcher resource="data.json">
  {(data) => (
    data ? <ResourceFetcher resource={data.secondaryResource}>
       {(secondaryData) => (
          secondaryData ? <div>{secondaryData}</div> : null
       )}
    </ResourceFetcher> : null
  )}
</ResourceFetcher>
```

It goes this way in the standard form.

1. Constructor for ResourceFetcher gets called.
2. Render gets called.
3. data is null so returns null.
4. Tree ended HTML can be extracted.

The form I proposed.

1. Constructor for ResourceFetcher gets called.
2. beforeServerSideRender gets called and setups the state.
3. data is specified so it creates the second ResourceFetcher node.
4. Constructor for ResourceFetcher gets called.
5. beforeServerSideRender gets called and setups the state.
6. secondaryData is specified so it creates the the div node.
7. div gets created and populated with the data.
8. Tree ended HTML can be extracted.

Now the form you have specified goes more like this

1. Constructor for ResourceFetcher gets called.
2. Render gets called.
3. data is null so returns null.
4. DidMount gets called.
5. All the parent interactions need to be specified, say side effects that affect the parents.
6. Parents need to be rechecked for side effects during the did mount of the children, we need to traverse the tree backwards.
7. shouldComponentUpdate needs to trigger.
8. getDerived needs to be executed again.
9. render needs to be executed again as many times as the async didmount specifies with each setState.

... The process is in fact so long, involved and so convoluted I can't keep going.

At this rate, there's something that does this job, and that is "react" itself, so you might as well use the DOM itself, eg. using puppeteer to do SSR, and execute your code, then grab the resulting DOM; you can do that.

The proposal I am giving is extremely simple, it's like an async constructor that only executes in SSR and causes asymmetric execution that you really need to take care of to ensure the result is the same; for the react side, it's a super simple change, however it can be tricky to use for SSR, since you really need to use a context for this to work and learn how to use contexts, so it requires setup to execute this SSR, but once you dial the setup, your app basically SSRs itself without other dependencies.

**Comment by mariusrak** [comment]
> 
> Now the form you have specified goes more like this
> 
>     1. Constructor for ResourceFetcher gets called.
> 
>     2. Render gets called.

Why? No need to call render on server side. Why would we call it? I wrote a code where the lifecycle methods are called and render not until all is ready. So no, render does not get called.

> ...
> 
>     5. All the parent interactions need to be specified, say side effects that affect the parents.

If this would not be possible, it is still better experience of SSR than current, where no lifecycles methods are available. With your proposal it is also not possible/available. All further steps are also not correct with my proposal.

> 
>     6. Parents need to be rechecked for side effects during the did mount of the children, we need to traverse the tree backwards.
> 
>     7. shouldComponentUpdate needs to trigger.
> 
>     8. getDerived needs to be executed again.
> 
>     9. render needs to be executed again as many times as the async didmount specifies with each setState.
> 


> 
> At this rate, there's something that does this job, and that is "react" itself, so you might as well use the DOM itself, eg. using puppeteer to do SSR, and execute your code, then grab the resulting DOM; you can do that.

This is not that simple. You need to know when to stop executing and grab the DOM. That's why this should be implemented in react core directly. Even if it would require more logic to handle cases like backward updating of parents, it is still more easily and clean-y done with react core than by custom handling of this when-to-stop logic. (I've just implemented it so I know and it is not that good) 

React knows when some renderer is acting and with using of async/await it would always wait until everything is resolved and every render is finished.

> 
> The proposal I am giving is extremely simple ...

Simple, but requires rewriting/duplicating logic of every component which would like to be SSR-ed. This is against DRY and KISS principle
