### ISSUE TITLE
Feature request: Allow setting ReactCurrentDispatcher.current for testing

### ISSUE THREAD

**Issue by davidmfoley** [facebook/react#20709]
Howdy. 

I built a [tool that allows testing hooks](https://github.com/davidmfoley/isolate-hooks) in isolation. It accomplishes this by setting `ReactDispatcher.current` on `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED`. Although amusing, this is not great for a number of reasons -- the main one is that the name of that export could change in the future.

Allowing the dispatcher to be set would make testing react hooks and react components that use hooks a lot easier and less prone to future potential breakage.

**Comment by bvaughn** [comment]
The dispatcher is an internal data structure and overriding it externally is something we would intentionally discourage. The `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` shouldn't be thought of as an "export", but as an internal field that isn't safe to use externally because it may change in ways that are not semver compatible.

Our suggestion for testing custom hooks is to test them by rendering a React component. Taking [the main example](https://github.com/davidmfoley/isolate-hooks#api) on the GitHub project

**Comment by davidmfoley** [comment]
The problem with that approach is that it requires 1) a virtual dom and 2) to create extra components for testing -- that's a lot of heavy machinery to require just to test a hook-based state machine that itself doesn't have any knowledge of a DOM. The dispatcher is effectively the handler for the various react hooks `useXxx` functions. Providing a way to inject an alternate dispatcher implementation (or providing another way to intercept calls to those hook functions) would make react hooks more testable.

**Comment by bvaughn** [comment]
> it requires 1) a virtual dom 

We publish a test renderer package as well, if you'd like to avoid using something like JSdom.
https://reactjs.org/docs/test-renderer.html
