### ISSUE TITLE
Change default branch name to “main”. Currently is “master”

### ISSUE THREAD

**Issue by samarmohan** [facebook/react#20754]
The word main is more inclusive than master. Master refers to slavery and makes some people feel lesser. Changing the branch name is a small but important gesture.

**Comment by gaearon** [comment]
There was already a thread tracking this but I can’t find it. Maybe the author got blocked by GitHub. We do plan to switch to `main` but there were some tooling updates that needed to be rolled out first for the transition to be smooth. I think that’s mostly done now but would need to double-check. In the meantime I’ll lock this thread because unfortunately threads like this often attract trolls, and we don’t want to spam people watching the repo.

**Comment by eps1lon** [comment]
Work on this has been completed. The default branch is `main` now.
