### ISSUE TITLE
Bug: Line break error

### ISSUE THREAD

**Issue by jaissugam** [facebook/react#20758]
Break 'br' tag doesn't provide the line break instead, the code fails to execute and it throws an error at 'br'
React version: 17.0.1

## Steps To Reproduce

1. Use 'br' tag in any reactjs file

Link to code example:

## The current behavior
Currently, Babble doesn't convert JSX br into HTML br

**Comment by tsairinius** [comment]
I have also had trouble using the `br` tag in the past in React. To elaborate on the issue, using `br` in JSX requires that you provide a closing tag for it:
```
<br></br>
```
Otherwise, I would receive the syntax error `Expected corresponding JSX closing tag for <br>`. 

Was that also your experience @jaissugam?

**Comment by jaissugam** [comment]
Hey @tsairinius , thanks for resolving the issue for me. The closing tag did fix the issue but I was wondering if this rule was some JSX development negligence or if there's a particular reason to have a rule like that?

**Comment by tsairinius** [comment]
@jaissugam Someone can correct me on this if I'm wrong, but from what I understand, JSX expects elements with no children (eg. br, input, img) to either be written as: 
```
<br /> 
```
or 
```
<br></br>
```

It's more favorable to actually use the former version since it's more concise. I should have used that in my previous comment. 

Details can be found in this discussion :https://stackoverflow.com/questions/48991212/react-component-closing-tag
