### ISSUE TITLE
Bug: setState(x=>x) will re render component

### ISSUE THREAD

**Issue by amsterdamharu** [facebook/react#20817]
First of all, thank you for giving us React.

I have a [custom hook](https://codesandbox.io/s/react-usestate-issue-ixymo?file=/src/index.js:455-795) that uses `setState(primitiveValue)` that will re render the component when `primitiveValue` did not change
React version: 17.0.1

## The current behavior
[code sandbox](https://codesandbox.io/s/react-usestate-issue-ixymo?file=/src/index.js) when pressing `+1` it will render counter as `value` state changes in useObservable but when clicking `no change` it will render again even though the state was set with the same primitive. Click `no change` again will not re render Counter, this happens only the first time after a change.

## The expected behavior
I expect Counter not to re create jsx since `value` did not change, I know [setState](https://codesandbox.io/s/react-usestate-issue-ixymo?file=/src/index.js:630-755) sets `value` but with the same primitive so there was no state change.

## Steps To Reproduce

When pressing `+1` it will render counter as `value` state changes in useObservable but when clicking `no change` it will render again even though the state was set with the same primitive. Click `no change` again will not re render Counter, this happens only the first time after a change. If for some reason code is not available on the sandbox then here is the code:

```
import * as React from 'react';
import ReactDOM from 'react-dom';

const observable = (() => {
  let listeners = [];
  let value = 0;
  return {
    getValue() {
      return value;
    },
    setValue(newValue) {
      value = newValue;
      listeners.forEach((listener) => listener(newValue));
    },
    addListener(listener) {
      listeners.push(listener);
      return () =>
        (listeners = listeners.filter(
          (l) => l !== listener
        ));
    },
  };
})();
const useObservable = () => {
  const [value, setValue] = React.useState(() =>
    observable.getValue()
  );
  React.useEffect(
    () =>
      observable.addListener((newValue) =>
        setValue(
          (current) =>
            console.log(
              'current and new',
              current,
              newValue
            ) || newValue
        )
      ),
    []
  );
  return value;
};
const Counter = React.memo(function Counter() {
  const count = useObservable();
  console.log('rendering counter', count);
  return <div>{count}</div>;
});
const App = () => {
  return (
    <div>
      <button
        onClick={() =>
          observable.setValue(observable.getValue())
        }
      >
        no change
      </button>
      <button
        onClick={() =>
          observable.setValue(observable.getValue() + 1)
        }
      >
        +1
      </button>
      <Counter />
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById('root'));
```

Link to code example: [code sandbox](https://codesandbox.io/s/react-usestate-issue-ixymo?file=/src/index.js)

**Comment by markerikson** [comment]
When you do `setState()` in a function component, it _always_ forces a re-render.  The question is what React does with the render output.

When you call `setState()`, React does not check _at that time_ whether the new value is the same as the old value.  That's because React doesn't even run the update until later, and you also might be using the functional updater form or a `useReducer` dispatch (same thing here).  

React always runs state updates during the render phase.  For function components, that requires actually rendering your component and running its hooks, at which time it will apply the state updates you queued.

So, yes, queuing a state update that results in an identical value _will_ force React to re-render your component.  However, if the resulting value is `===` identical, _and_ there are no other queued state updates or components that need to re-render, React will then throw away the entire render pass and do nothing else.

See my post [A (Mostly) Complete Guide to React Rendering Behavior](https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/) for details on how all this behaves.

**Comment by amsterdamharu** [comment]
The reason I didn't expect the re render is because this part in the [documentation](https://reactjs.org/docs/hooks-reference.html#functional-updates)

> If your update function returns the exact same value as the current state, the subsequent rerender will be skipped completely.

However, it does not skip it the first time local state doesn't change.

You say:

> if the resulting value is === identical, and there are no other queued state updates or components that need to re-render

So maybe there is another queued state update but I can't find it in the code provided.

**Comment by vkurchatkin** [comment]
@amsterdamharu quoting the same page of documentation:

> If you update a State Hook to the same value as the current state, React will bail out without rendering the children or firing effects. (React uses the Object.is comparison algorithm.)

> Note that React may still need to render that specific component again before bailing out. That shouldn’t be a concern because React won’t unnecessarily go “deeper” into the tree

**Comment by rickhanlonii** [comment]
Closing as @markerikson's explanation and the docs both explain this well.

**Comment by tjcrowder** [comment]
@markerikson -

> When you do `setState()` in a function component, it *always* forces a re-render.

With respect, that doesn't seem to be correct, and the documentation claims otherwise [here][functional-updates]. Apologies in advance if I'm missing or misinterpreting something. :-)

In [this sandbox][codesandbox] (code below) the `Set Same Value` button does `setValue((v) => v);`. If you click it immediately after the initial render or more than once in a row, no rerender occurs **at all**. A rerender only occurs the first time you click `Set Same Value` after having previously clicked `Set Different Value`. That rerender is pointless (and is the reason @amsterdamharu raised this issue, if I'm reading right); the commit phase won't have anything to do. (This happens both in v17 and v18.) It's problematic, because returning the same value is the only way to say "no changes" when doing a functional update using `useState` state members; we don't (understandably) have the option of returning `null` as in a `class` component's `setState` callback.

If you'll indulge me, what part of that blog post would help me (and others running into this) understand why that unnecessary rerender is correct, but then skipping renders afterward is also correct? The unnecesssary rerender looks like a bug to me, but I respect the limits of my knowledge.

Here's what the ["functional updates" section][functional-updates] of the `useState` documentation I referred to above says:

> If your update function returns the exact same value as the current state, the subsequent rerender will be skipped completely.

That's an unqualified statement that a rerender will not occur for the same value. And yet it does&nbsp;&mdash; the first time.

I was **very** surprised to see this when helping someone on Stack Overflow after having confidently pointed to the documentation above. :-)

Thanks in advance.

Here's that sandbox code:

```
let renderCounter = 0;
export const App = () => {
    const [value, setValue] = useState(0);

    console.log(`Render #${++renderCounter}, value = ${value}`);
    const setSameValue = () => {
        // Call `setValue`, but have it return the same value
        setValue((v) => v);
    };
    const setDifferentValue = () => {
        // Call `setValue`, have it return a different value
        setValue((v) => v + 1);
    };
    return (
        <div>
            Value: {value}
            <div>
                <input type="button" value="Set Same Value" onClick={setSameValue} />
                <input type="button" value="Set Different Value" onClick={setDifferentValue} />
            </div>
        </div>
    );
};
```

*(No `StrictMode` in use, and I can't see how there could be stale closures, etc.)*

  [functional-updates]: https://reactjs.org/docs/hooks-reference.html#functional-updates
  [codesandbox]: https://codesandbox.io/s/charming-wind-desvjw?file=/src/App.js

**Comment by markerikson** [comment]
@tjcrowder : you're hitting a specific React bailout behavior that I talked about here:

- https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#immutability-and-rerendering

> Every time I call `setCounter()` or `dispatch()`, React will queue up a re-render. However, React requires that any hook state updates must pass in / return a new reference as the new state value, whether it be a new object/array reference, or a new primitive (string/number/etc).
> 
> React applies all state updates during the render phase. When React tries to apply a state update from a hook, it checks to see if the new value is the same reference. React will always finish rendering the component that queued the update. However, if the value is the same reference as before, and there are no other reasons to continue rendering (such as the parent having rendered), React will then throw away the render results for the component and bail out of the render pass completely.

The actual implementation details are slightly more complex.  

By default, React _does_ absolutely schedule a re-render, because _by default_ all state updates are queued up and then evaluated in the render phase.  So, React has to actually start the render, work its way down to this component, apply the queued state updates and render it, and then realize that the state after applying the queued updates was identical to last time so it will bail out (assuming no other components were queued for updates as well).

However, this is an exception to this.  Specifically, you're running into the "fast bailout" mechanism that I linked in that section, which I'll link here for reference:

- https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L2234-L2259

So, there's a bit of difference in behavior between the _first_ attempt to set an identical state value, and _later_ attempts to set that same state value.


The docs page you linked, with the phrase "the subsequent rerender will be skipped completely", is simplifying the description.

From the point of view of the actual user and the overall app behavior, there wasn't a render.  Either way, React did not execute a complete render pass, and did not get to the commit phase.  It's just that in one case it _does_ have to _start_ the render pass to figure out it can quit early, and in the other case it has additional info saved internally and can skip queueing up a render entirely.

**Comment by tjcrowder** [comment]
@markerikson - Thanks for that! I really appreciate it. Exactly the kind of reply I'd hoped for.

I'm struggling with what's different about the first time vs. others. I tried stepping through the code but not having any grounding in that codebase, I'm a bit at sea. :-) I can see that `fiber.lanes` is `1` the first time (so we don't go into the fast bail out), but `0` the subsequent times (as is `alternate.lanes`, so we do). The code comments suggest that `0` means "the queue" is empty. But...why is it not empty the first time? (**If** it can be explained briefly, I'm mindful of your time.) I just don't see a reason for a distinction between those two states of the code; they both start from a place where there's a completed state update, React has the current state information (`value = X`), and the component does a state update setting the exact same value that React already has.

If it *can't* be explained briefly, please don't hesitate to say so and I'll just live with my ignorance or read the code enough to figure it out. :-)

Separately:

> So, React has to actually start the render, work its way down to this component, apply the queued state updates and render it, and then realize that the state after applying the queued updates was identical to last time so it will bail out (assuming no other components were queued for updates as well).

Am I reading that right that the non-fast bail out (if you will) means that child component functions won't be called (even if un-memoized), even the first time you set the same state? [This sandbox](https://codesandbox.io/s/bitter-hill-kyo9oi?file=/src/App.js) seems to confirm that understanding, but I wanted to double-check.

Thanks again!

**Comment by markerikson** [comment]
@tjcrowder : yeah, I've identified that as the main relevant area of the code, but I haven't tried to trace the _exact_ execution path.  At this point I settle for describing the observable behavior then the exact implementation details.

> the non-fast bail out (if you will) means that child component functions won't be called (even if un-memoized), even the first time you set the same state

Exactly, yes.  

If you really want to figure out exactly what the difference in internal behavior is, I'd suggest using the tool I build as my day job, Replay ( https://replay.io ).  

`<SalesPitch mode="on">`
It's a true "time traveling debugger" for JS.  Our app is meant to help simplify debugging scenarios by making it easy to record, reproduce and investigate your code. 
The basic idea of Replay: Use our special browser to make a recording of your app, load the recording in our debugger, and you can pause at _any_ point in the recording.  In fact, you can add print statements to any line of code, and it will show you what it _would_ have printed _every time that line of code ran_!

From there, you can jump to any of those print statement hits, and do typical step debugging and inspection of variables. So, it's the best of both worlds - you can use print statements *and* step debugging, together, at any point in time in the recording. 

See https://replay.io/record-bugs for the getting started steps to use Replay.
`</SalesPitch>`

**Comment by tjcrowder** [comment]
@markerikson - Thanks again!

I find the documentation's "simplified" statement sufficiently misleading that I've filed a [bug report for it](https://github.com/reactjs/reactjs.org/issues/5215) suggesting qualifying the statement slightly, so people like @amsterdamharu and I don't get the wrong end of the stick. :-)
