### ISSUE TITLE
Bug: Strict Mode Quirk?

### ISSUE THREAD

**Issue by kmurph73** [facebook/react#20826]
[useComponentId](https://gist.github.com/sqren/fc897c1629979e669714893df966b1b7) produces a different value on the re-render in Strict Mode.  Not sure if `useComponentId` is safe to use otherwise.

React version: 17.0.1

## Steps To Reproduce

1. Go to https://codesandbox.io/s/k4bph
2. Open up Console and type `hold`

You'll see that `useComponentId` (in Test.js) produced two values. 

Link to code example: https://codesandbox.io/s/k4bph

## The current behavior

`useComponentId` produces two values in Strict Mode

## The expected behavior

It should produce one?  I'm not sure if `useComponentId` is fundamentally flawed, or if the fault lies with Strict Mode.  I've used `useComponentId` in production w/o apparent issue.  In the meantime I've just stopped using Strict Mode.

Thank you!

**Comment by markerikson** [comment]
This appears to be a question about a third-party piece of code, and not anything to do with React itself.  As such, it probably is better suited for Stack Overflow instead of the React issues.

Looking at the implementation:

```js
import { useRef } from 'react';

let uniqueId = 0;
const getUniqueId = () => uniqueId++;

export function useComponentId() {
  const idRef = useRef(getUniqueId());
  return idRef.current;
}
```

That clearly mutates an external variable every time the hook runs.  That is a side effect while rendering, which you're not supposed to do in React.

For the `StrictMode` question specifically: yes, React will completely render this component once the first time, throw that render result away, and then render the component again.  In fact, the reason to do that _is_ to help you catch things like side effects during rendering.  In this case, it's a trivial side effect that won't actually break anything, but this shows how that's a bad pattern that should be avoided.

You _should_ still be using `StrictMode` to continue catching issues like this.

**Comment by kmurph73** [comment]
@markerikson gotcha, thank you.  I just thought it could have surfaced something that perhaps SM wanted to accommodate, which is why I posted it here.  I've found that hook highly useful, but perhaps I should find a work around that avoids such side effects entirely.

**Comment by kmurph73** [comment]
I realized that I asked the wrong question.  The issue was that StrictMode wasn't calling `useEffect`'s cleanup function, which cleaned up a side effect (involving `useComponentId`).  However, I realize that this is also intended, in anticipation of Concurrent Mode, which can't guarantee that the cleanup function is called (among other things).  Updated the CodeSandbox accordingly.

In case anyone stumbles upon this thread in the future...

**Comment by eps1lon** [comment]
> However, I realize that this is also intended, in anticipation of Concurrent Mode, which can't guarantee that the cleanup function is called (among other things).

@kmurph73  I don't think this is true. If an effect is run (i.e. its `create` function) then its corresponding cleanup function (i.e. `destroy` function) is run. It's just the timing that is (already) async. Though it is guaranteed that a `destroy` of an effect is run before the next `create`.

**Comment by kmurph73** [comment]
Ok _now_ I get it.  I just have to ensure that any side effects are run inside of `useEffect` (shocker).  Which means I still can't use `useComponentId`, but it's clear to me what StrictMode is doing now.  

Previously, I had side effects outside of `useEffect`, but could still rely on `useEffect`'s cleanup function to clean them up, so it "worked" outside of StrictMode.

@eps1lon  Thank you for MUI and your help!
