### ISSUE TITLE
Bug: conditionally using suspense with a fallback on server side causes hydration warnings

### ISSUE THREAD

**Issue by Mathspy** [facebook/react#20825]
Conditionally using `Suspense` with a fallback on the server side causes incorrect hydration warnings

React version: 17.0.1

## Steps to reproduce
1. Try to hydrate a `<Suspense>` component with a fallback

Link to code example:
https://codesandbox.io/s/vibrant-heisenberg-f3wsj?file=/src/index.js

## The current behavior
It produces incorrect hydration warnings
<img width="474" alt="Warning: Did not expect server HTML to contain a <p> in <div>." src="https://user-images.githubusercontent.com/5855663/107914198-9e6b9800-6f6a-11eb-9dd3-82000e254ee6.png">

## The expected behavior
It should not produce hydration warnings...? Maybe...? I know it's a bit of a whacky use of suspense but the reason we're doing that is because it's pretty trivial to have all the data preloaded on the server in such a way where we are guaranteed to not suspend on the server side.

## Interesting behavior
[Removing `fallback="Loading..."` causes the warning to go away](https://codesandbox.io/s/laughing-bassi-qwnef?file=/src/index.js)

**Comment by eps1lon** [comment]
Thanks for the report.

For SSR+hydration you have to render the same elements on the Client and the Server. The warning is not really helpful in this case though.

However, Suspense is currently not supported for server-side rendering. You could try the `experimental` release channel and concurrent mode. That might support Suspense for server-side rendering already.

**Comment by Mathspy** [comment]
> For SSR+hydration you have to render the same elements on the Client and the Server. The warning is not really helpful in this case though.

This is only relevant in regards to the leaf nodes though, correct? For example something like this so long so long as `SSRComponent` and `Component` match the leaf behaviour
```js
function SSRComponent() {
  // Do things here
  return <p>Test</p>;
}
function Component() {
  // Do other things here but end with same result
  return <p>Test</p>;
}
function App() {
  return typeof window === "undefined" ? <SSRComponent /> : <Component />;
} 
```
is sound, right?

> However, Suspense is currently not supported for server-side rendering. You could try the `experimental` release channel and concurrent mode. That might support Suspense for server-side rendering already.

Yep, I am aware. This is a bit of a special case though as the server is able to predict ahead of time all the requirements for suspense's cache so I'd expect to be able to substitute the `<Suspense>` boundary with anything that just renders its children (i.e: `<Fragment>`) and for it to work.

I should note: _**it does work**_. Especially when `<Suspense>` has no `fallback`, it works even without the warning. With `fallback` it produces that error though

**Comment by eps1lon** [comment]
> This is only relevant in regards to the leaf nodes though, correct? 

It's relevant for anything that must be hydrated. And suspense boundaries need to be hydrated.

So while `return typeof window === "undefined" ? <SSRComponent /> : <Component />;` might be (incidentally) ok, you cannot guarantee it over time since the implementation of `SSRComponent` and `Component` might diverge over time.

Anytime you branch depending on whether you are on the server or not you're risking a mismatch. 

Let's approach this from a different angle: How are you using `ServerSideSuspense`? Right now you don't need it since you never pass it a component that suspends. How would you use it most of the time and what would you expect the server markup to look like?

**Comment by Mathspy** [comment]
> It's relevant for anything that must be hydrated. And suspense boundaries need to be hydrated.

Oh I see! That makes sense

> So while `return typeof window === "undefined" ? <SSRComponent /> : <Component />;` might be (incidentally) ok, you cannot guarantee it over time since the implementation of `SSRComponent` and `Component` might diverge over time.
>
> Anytime you branch depending on whether you are on the server or not you're risking a mismatch. 

Yep agreed. That was a bit of an extreme example, I do think there are a couple of valid use cases that doesn't use a whole different component though

> Let's approach this from a different angle: How are you using `ServerSideSuspense`? Right now you don't need it since you never pass it a component that suspends. How would you use it most of the time and what would you expect the server markup to look like?

The implementation simplified is something akin to this
```js
// dataFromServer is passed to client side and used while hydrating App there too
// so it's identical on both server and client and there's no potential for mismatch
function App({ dataFromServer }) {
  const [data, updateData] = useState(dataFromServer);
  return (
    <Context.Provider value={{ data, updateData }}>
      <SomeComponent />
    </Context.Provider>
  );
}

function SomeComponent() {
  const [something, setSomething] = useState("default");
  // This relies on data from the context and can update the context if it
  // needs to. It might suspend but the server knows exactly what the "default"
  // that it needs is, same for all other instances of it in a page, so the server
  // can ahead of time prepare the data and pass it in `dataFromServer`
  // But the rest of its usages are going to be dynamic and can't be predicted
  // ahead of time
  const someData = useMightSuspend(something);

  return (
    <ServerSideSuspense>
      { /* clicking the below button should suspend */ }
      <button onClick={() => setSomething("not-default")}>
        Click me to start fetching some data!
      </button>
    </ServerSideSuspense>
  );
}
```

The server markup would just be identical to if the `<Suspense>` boundary was just a `<Fragment>`, it's when some action is taken that `<Suspense>` becomes relevant.

I am also aware that it's possible to rewrite `<ServerSideSuspense>` with a `useEffect` to only transform to a `<Suspense>` after the first render and that's what I am going to be doing, but was curious about the hydration mismatch warning and thought it was worth reporting since it doesn't even have a component stack

**Comment by gaearon** [comment]
The original example is not supported — it's exactly the kind of case that hydration warning is meant to catch. Even if this code accidentally works, you'll likely run into issues in the future when we change the behavior for how a Suspense boundary hydrates. It's hard for me to say what _will_ accidentally work and what won't because that depends on implementation details. But generally saying, if you want to be on the safe side, the whole three should be identical during the hydration. Like you said, you can always `useEffect` to do something else later.

In the `experimental` releases, Suspending on the server emits a `fallback` instead of throwing. The server can also emit content (if it's preloaded). In both of these cases, the `experimental` version of the client is able to handle that. E.g. if you emit fallback, the client version will hydrate the fallback. But if the server emits content while the client Suspends, the client version will **not** replace content with fallback (!) and instead will wait for the missing code/data to load. This is only enabled in Concurrent Mode.

By the way, keep in mind that updating context during hydration is usually a bad idea. So try to avoid baking that into your architecture. That will actually disable the optimization I just described in the future, causing client to show a fallback.

**Comment by Mathspy** [comment]
> The original example is not supported — it's exactly the kind of case that hydration warning is meant to catch. Even if this code accidentally works, you'll likely run into issues in the future when we change the behavior for how a Suspense boundary hydrates. It's hard for me to say what _will_ accidentally work and what won't because that depends on implementation details. But generally saying, if you want to be on the safe side, the whole three should be identical during the hydration. Like you said, you can always `useEffect` to do something else later.

Okay that does indeed make sense! My understanding was lacking of what hydration is, I thought it only related to the output HTML elements and had nothing to do with the React tree

> In the `experimental` releases, Suspending on the server emits a `fallback` instead of throwing. The server can also emit content (if it's preloaded). In both of these cases, the `experimental` version of the client is able to handle that. E.g. if you emit fallback, the client version will hydrate the fallback. But if the server emits content while the client Suspends, the client version will **not** replace content with fallback (!) and instead will wait for the missing code/data to load. This is only enabled in Concurrent Mode.

This is _really_ cool and exciting me to get back to a project I was working on that experiments with React experimental

> By the way, keep in mind that updating context during hydration is usually a bad idea. So try to avoid baking that into your architecture. That will actually disable the optimization I just described in the future, causing client to show a fallback.

Aha, thanks for the future tip!
And thank you both very much for helping me understand hydration much better ❤️

**Comment by tranvansang** [comment]
I use this hack. At least, It can suppress the warning.

```javascript
export default function IsoSuspense(
	{
		fallback = <TimeoutSpinner/>,
		children,
	}: {
		fallback?: ReactNode
		children: ReactNode
	}
) {
	const [mounted, setMounted] = useState(false)
	useEffect(() => setMounted(true), [])
	return isBrowser ? <Suspense fallback={mounted ? fallback : undefined}>{children}</Suspense> : <>{children}</>
}

```

**Comment by gaearon** [comment]
This hack is bad because you are returning children on the server. So the initial HTML contains them. Then, after hydration on the client, you replace them with a fallback. So, potentially, and entire screen disappears before the user. And then Suspense resolves on the client, showing content again. This is very disruptive and usually not the right user experience.

In that case I suggest returning some kind of fallback from the server. Such as even your Suspense fallback. (Although it’ll be remounted on hydration, I think.) At least then the user doesn’t see the content at all. Though that does negate the benefits of a server render.

**Comment by tranvansang** [comment]
> Then, after hydration on the client, you replace them with a fallback

I carefully inject SSR data before the hydration occurs. The fallback is never rendered/hydrated if the server has content.

**Comment by llezhava** [comment]
@gaearon 

With `typeof window === undefined`, you know earlier, that you are on server, than with `useState` effect. (To show client only content after user is mounted). When we are using `useState` for this, we will have splash screens or have to provide fallback content.

I understand, but `typeof window === undefined` will produce mismatches and is not recommended to use, but maybe you could add this support to react somehow? I.e we could provide some attribute to the node `data-expect-mismatch`, where instead of rehydration, react would just replace nodes with client-generated node.

What do you think?

**Comment by gaearon** [comment]
@llezhava Can you please clarify what exact behavior you're trying to achieve, rather than describe the API you'd like to use for it? I'd like to understand what you want to happen from the user's perspective. What UI do you want the server to show and what do you want the client to show during hydration? If you describe it I can try to recommend a solution.
