### ISSUE TITLE
[Regression] Bug: Non react event handlers are not triggered in the correct order

### ISSUE THREAD

**Issue by sag-tobias-frey** [facebook/react#20848]
Triggering an event handler on an inner div, seems to bubble the event up to other react handlers and misses non-react event handlers. This was not the case in v16.x

React version: 17.0.1

## Steps To Reproduce

1. Open https://stackblitz.com/edit/ag-grid-react-hello-world-8vrumq?devtoolsheight=33&file=index.js
2. Click on a row in the table
3. Only the react click andlers on the inner / outer div are triggered

Link to code example:

https://stackblitz.com/edit/ag-grid-react-hello-world-8vrumq?devtoolsheight=33&file=index.js

## The current behavior
Only the click handlers of the inner / outer div are triggered.

## The expected behavior
On version 16.X also the onCellClicked() was triggered; this listener is attached to an element between the inner and outer div.

**Comment by gaearon** [comment]
Can you please provide an example with no third-party libraries?

**Comment by sag-tobias-frey** [comment]
I have tracked it down to probably something like that:

-> https://stackblitz.com/edit/ag-grid-react-hello-world-fgjf4j?devtoolsheight=33&file=index.js

This works with 16.x, not with 17.x; is this an intended change with the new event delegation?

**Comment by sag-tobias-frey** [comment]
Even the following (placing the portal inside the non-react event handler) is no longer working:

-> https://stackblitz.com/edit/ag-grid-react-hello-world-scgnrt?devtoolsheight=33&file=index.js

This has the same behavior as before.

**Comment by sag-tobias-frey** [comment]
@gaearon Is this example enough or do you need more?

**Comment by gaearon** [comment]
Thanks for further reducing! Yeah this is an intentional change, and exactly what 17 fixes.

Your React handler stops propagation of the event:

```js
    <div className="ag-theme-alpine" style={{ height: 400, width: 600 }} onClick={(event) => { console.log('test'); event.stopPropagation(); }}>
```

In React 16 and earlier, this **was not enough to actually stop the native propagation to the document** because the event was _already_ at the document level by the time this code runs. So your document handler fired.

In React 17 and onwards, `stopPropagation` actually stops propagation at the React root. So your event doesn't reach the document. This is important because it lets you nest React app in a non-React app and have confidence that `e.stopPropagation()` doesn't let the event leak outside the React tree.

If you really want to still receive the document event, you can either:

- Subscribe to this event lower in the tree than the React root, or
- Pass `true` as the third argument to `document.addEventListener` to catch the event in the capture phase, before it reaches the React tree, or
- Not stop propagation in the first place

See also: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues

Hope this helps.

**Comment by sag-tobias-frey** [comment]
@gaearon But he eventhandler is attached to the element and not on the document; did you see that?

document.getElementById('table').addEventListener('click', () => {
      console.log('Clicked!');
    });

**Comment by sag-tobias-frey** [comment]
Additionally, this works correctly when not using portals; so my guess would be that this is in fact a react bug.

-> https://stackblitz.com/edit/ag-grid-react-hello-world-8arud3?devtoolsheight=33&file=index.js

@gaearon

**Comment by sag-tobias-frey** [comment]
Why does this work then without portals? I'm not adding an event listener directly on document but on an element which should get the event. @gaearon

**Comment by muhammad-bilal-ali-khokhar** [comment]
not working :(
