### ISSUE TITLE
Why does reducer implement another interpreter?

### ISSUE THREAD

**Issue by fxdave** [facebook/react#20907]
Here is an example of the current reducer:
```jsx
const initialState = {count: 0};

function reducer(state, action) {
  switch (action.type) {
    case 'increment':
      return {count: state.count + 1};
    case 'decrement':
      return {count: state.count - 1};
    default:
      throw new Error();
  }
}

function Counter() {
  const [state, dispatch] = useReducer(reducer, initialState);
  return (
    <>
      Count: {state.count}
      <button onClick={() => dispatch({type: 'decrement'})}>-</button>
      <button onClick={() => dispatch({type: 'increment'})}>+</button>
    </>
  );
}
```

Which is overcomplicated, and it computes with strings instead of well-defined language elements.

Here is a more preferable one:
```jsx
function useCount(start) {
  const [count, setCount] = useState(start);
  const increment = () => setCount(count + 1);
  const decrement = () => setCount(count - 1);
  return { count, increment, decrement };
}

function Counter() {
  const { count, increment, decrement } = useCount(0);
  return (
    <>
      Count: {count}
      <button onClick={increment}>-</button>
      <button onClick={decrement}>+</button>
    </>
  );
}
```

I see this preference on Redux too, which I cannot understand, this is clearly a better method of doing this in every way:
 - It is easier for typing
 - It defines language symbols instead of writing its own language
 - It is more manageable for developers (KISS)
 
So why does useReducer exist in the framework, why does redux use this too?

**Comment by ludofischer** [comment]
I believe you're right that in your example the reducer is useless. I find reducers are useful when the state has multiple fields  and a single action must trigger multiple updates in different parts of the state. For example, when two state variables depend on each other. I think this article presents an interesting example of where a reducer becomes useful: https://overreacted.io/a-complete-guide-to-useeffect/#decoupling-updates-from-actions

**Comment by fxdave** [comment]
As I can see, useReducer is a dirty hack here where react guarantees that dispatch will not change. It's not used because the author wanted to write an action interpreter. It is used because there is no way to do this with separate states currently. So the author merged the state. 

At this point, this also could be implemented with custom hooks (https://codesandbox.io/s/flamboyant-pond-m2u3r?file=/src/index.js), but that's worse than a reducer because react doesn't let us refactor that code properly. 

But I think reducer is not the solution. Because if I could do this for example:
```js
function useStepper() {
    const [value, setValue] = useState(0)
    const [stepAmount, setStepAmount] = useState(1)
    
    const step = () => setValue(value + stepAmount)
    
    return { count, step, stepAmount, setStepAmount }
}

function useCounter() {
    const { count, step, stepAmount, setStepAmount } = useStepper()
    
    useEffect(() => {
        const id = setInterval(step, 1000)
        return () => {
             clearInterval(id)
        }
    }, 
     [step], 
     [step] // Somehow marking that it is dependent on step, but don't update on step change
    )
    
    return { count, stepAmount, setStepAmount }
}
```
Then this could be better again.

Reducer would fit well into other languages like rust, where we have proper enum types, so we don't have to use unpredictable dynamic values, but javascript is not ready for this kind of code.

**Comment by renatoalencar** [comment]
useReducer is good cases where you need the previous state to create the next, which is the example you used. And your example won't work if you call increment or decrement from the same render.

The way the documentation describes the use of useReducer is probably meant to be familiar to React developers, because it uses the same idiom as Redux.

And your right about being possible to write it shorter.

```
function useCounter() {
  const [count, dispatch] = useReducer((count, step) => count + step, 0)

  const increment = () => dispatch(1)
  const decrement = () => dispatch(-1)

  return { count, increment, decrement }
}
```

And useState actually uses useReducer, but returns the action (kind of) in the reducer.

**Comment by markerikson** [comment]
There are many reasons to write your logic as a reducer instead of a `useState` hook:

- Complex calculations are easier
- You can pull the logic out and test it separately
- You can update multiple fields in the reducer's state in one operation, which can be a benefit in scenarios where you only want one re-render instead of multiple individual renders from setting multiple individual states

There's even some neat tricks you can use specifically with `useReducer` that you can't do with `useState` or with Redux:

https://overreacted.io/a-complete-guide-to-useeffect/#why-usereducer-is-the-cheat-mode-of-hooks

But frankly, your complaints are all entirely subjective, and the fact that you're dismissing `useReducer` on the basis of a trivial code sample means you really don't understand it.

**Comment by eps1lon** [comment]
Having the discussion is totally valid. But this issue tracker is not the right place for it. 

Coding Questions
If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

stackoverflow.com/questions/tagged/react

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html

**Comment by fxdave** [comment]
Ok, so useReducer is useful. Could we make it better?
For e.g:
```ts


function reducer(state: number) {
    return {
         increment(): number {
            return state + 1
         }
         decrement(): number {
            return state - 1
         }
    }
}

const [state, { increment, decrement }] = useReducer(reducer)
```

**Comment by markerikson** [comment]
Nothing needs to be built into `useReducer` to do that.  In fact, you can do exactly that kind of logic with something like [Redux Toolkit's `createSlice` API](https://redux-toolkit.js.org/api/createSlice), which generates action creators for you based on the case reducers you've defined.  Since reducers are _just_ plain functions, you can use RTK and `createSlice` to generate reducers that are only used with the `useReducer` hook even if you're not using a Redux store in your app.
