### ISSUE TITLE
What's the difference between Suspense and Promise.all

### ISSUE THREAD

**Issue by yisar** [facebook/react#20934]
I'm sorry I have to raise this question. I'd like to know about suspend and Promise.all What's the biggest difference.

as far as I am concerned, Promise.all It's also concurrent, and they're similar in this respect.

**Comment by gaearon** [comment]
Promise.all is a mechanism to produce a single Promise out of multiple Promises, with the aggregate Promise resolving when all of the inner Promises resolve.

Suspense is a mechanism that lets a component declare that it's not yet ready to render. It combines a Promise (which signals that it's ready for a retry) and a cache (to ensure that retrying succeeds).

I'm not sure a direct comparison makes sense because these mechanisms serve two different purposes. One is a way to produce a Promise, another is a contract between a React component and React.
