### ISSUE TITLE
Bug: Can't build react-devtools-extensions

### ISSUE THREAD

**Issue by hecerinc** [facebook/react#20997]
I've just cloned the repo, ran `yarn`, and then `yarn build-for-devtools` as explained in the [README](https://github.com/facebook/react/blob/master/packages/react-devtools-extensions/README.md) but when trying to run `yarn build:firefox:dev` it can't find the packages I just built.

![image](https://user-images.githubusercontent.com/7988472/111039185-9d028380-83e1-11eb-8b45-8e459ec5eaa5.png)

I think I'm following all the instructions here.

**Comment by bvaughn** [comment]
Does it work if you download the latest React build rather than building it locally? The README also [shows how to do that](https://github.com/facebook/react/blob/master/packages/react-devtools-extensions/README.md#download-from-ci).

I don't have a Windows machine so this isn't something I'll be likely to troubleshoot. If you'd like to dig in and submit a PR though, happy to review.

**Comment by hecerinc** [comment]
No, actually trying to fetch the build fails with a different error: 
![image](https://user-images.githubusercontent.com/7988472/111083248-cdbde800-84c9-11eb-99d0-4ff42061ce1a.png)

> I don't have a Windows machine so this isn't something I'll be likely to troubleshoot. If you'd like to dig in and submit a PR though, happy to review.

I understand. I'll try to take a look at it more in depth if I get the time later today. 

Thanks

**Comment by satish-rajnale** [comment]
Can't you just go on chrome and add extension provided there..?
