### ISSUE TITLE
Bug: Unsupported HTML entities

### ISSUE THREAD

**Issue by fast-reflexes** [facebook/react#21002]
Many of the HTML entities presented at https://dev.w3.org/html5/html-author/charref are not supported by React, why is this?

## Steps To Reproduce

Check https://codesandbox.io/s/react-unsupported-html-entities-yr9rj

## The current behavior

React recognizes some entities as string literals which may cause problems when the browser in question in fact supports the entity but React tricks the browser into thinking that it is a string, just because React doesn't seem to recognize it.

## The expected behavior

The symbol that the entity should yield.

**Comment by mvskiren** [comment]
It seems React Dom has backlisted some HTML entities due to XSS attacks. Even I came across this issue and read the documents and by using dom parser I can achieve those unsupported ones, you can have a look I have used dom parser and it outputs unsupported entities.
[](https://codesandbox.io/s/react-unsupported-html-entities-forked-q3t9t?file=/src/App.js:0-2305)

https://medium.com/@Jam3/how-to-prevent-xss-attacks-when-using-dangerouslysetinnerhtml-in-react-f669f778cebb

**Comment by fast-reflexes** [comment]
@mvskiren Yeah I noticed `setDangerouslyInnerHtml` can be used and thanks for showing that `DOMParser` can be used as well. 

This is typically not a problem when using React on its own since there are multiple alternatives for most entities but when using React with other libraries, some very confusing results may occur if one does not know all of this. Do you have a source on the backlisting of entities and why some entities would be more susceptible to XSS attacks than others?

**Comment by bryanian01** [comment]
yes i tried too this one 
https://codesandbox.io/s/html-react-parser-forked-hrqm1?file=/src/index.tsx
the scripts tags not work properly but when i put in html everything is smooth
