### ISSUE TITLE
Bug:  react hooks gets executed two times

### ISSUE THREAD

**Issue by kambleaa007** [facebook/react#21048]
as i clicked on button only once,
![image](https://user-images.githubusercontent.com/19818679/111965030-48ff4980-8b1b-11eb-9a7e-dec919d105eb.png)
call stack
![image](https://user-images.githubusercontent.com/19818679/111965088-59afbf80-8b1b-11eb-913d-b18ec839d252.png)
 after continue, it gets called again without clicking on button

gets called again
![image](https://user-images.githubusercontent.com/19818679/111965182-78ae5180-8b1b-11eb-8f2a-387c7f79f270.png)
so updating value not once but twice
here 
![image](https://user-images.githubusercontent.com/19818679/111965249-8a8ff480-8b1b-11eb-87f4-995de2f04c20.png)
you can see value 7 instead of 6

reproduction steps:
goto url http://localhost:3000/myApp
code url https://github.com/kambleaa007/TrainingReactJS

the same code works for first time, not from second time onwards
trying for first time this works,
![image](https://user-images.githubusercontent.com/19818679/111965586-e5c1e700-8b1b-11eb-99a6-6e98b1cf4442.png)
then
in debug
![image](https://user-images.githubusercontent.com/19818679/111965634-f5413000-8b1b-11eb-879e-3295768d9641.png)
here worked
![image](https://user-images.githubusercontent.com/19818679/111965685-04c07900-8b1c-11eb-8b68-504a12084831.png)

for first time
not problem in my code logic as it works first time second time onwards error persist

React version:

## Steps To Reproduce

1. npm start
2. goto url http://localhost:3000/myApp
3. clonning repo code url https://github.com/kambleaa007/TrainingReactJS

Link to code example:

## The current behavior
gets called twice

## The expected behavior
should called once

**Comment by eps1lon** [comment]
Could you point to the particular hook that gets called twice?

Though I suspect this is expected behavior considering [your app is rendered in StrictMode](https://github.com/kambleaa007/TrainingReactJS/blob/0a5ccd1fe9590467adf1d8f0477fa5fc636cd897/src/index.js#L8-L10).

`React.StrictMode` executes certain functions twice in development to [detect problematic side-effects](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects).

**Comment by kambleaa007** [comment]
how do i overcome this problem? is there any special technique will do that?

**Comment by eps1lon** [comment]
> As per the stack trace useReducer is gets called automatically for second time onwards,

`useReducer` is one of the methods that must be side-effect free. But it's hard to give general advise where to move side-effects. That is usually specific to a particular type of problem.

I suggest checking out https://reactjs.org/community/support.html and choosing one of the support platforms of your preference. The react issue tracker is not the right place since these type of questions stay unanswered.
