### ISSUE TITLE
Bug:  This may not be a bug: eslint(react-hooks/exhaustive-deps) complaining doest make sense.

### ISSUE THREAD

**Issue by nadeeravista** [facebook/react#21053]
This is related to react-hook Eslint. Kindly note following code is an example code.
I just need to listen to `gross` and set the `net` value using `setValue`. The Eslint forcing me to add both `getValue` and `setValue`. 

In the aspect of clean code, if we force, isn't this linter makes the code more confusing. it's about clarity. When I look at the function, I want to easily understand when it should fire. If I see only the `gross` in the array, it's crystal clear that Im listening to `gross`.

## Code
```
import React, { useEffect, Input } from 'react';

import { useForm } from 'react-hook-form';

const MyComponent = (aFunction) => {
  const { register, getValues, watch, setValue } = useForm();

  let gross = watch('gross');

  useEffect(() => {
    let gross = getValues('gross');

    setValue('net', gross + 10);
  }, [gross]);  // Eslint forcing me to add [getValues, gross, setValue]

  return (
    <>
          <Input ref={register('gross')} label="Gross" id="gross" name="gross" />
          <Input ref={register('net')} value={null} label="Net" id="net" name="gross" />
    </>
  );
};

export default MyComponent;
```
![Screen Shot 2021-03-23 at 9 12 31 AM](https://user-images.githubusercontent.com/29170666/112062311-a1d6ec80-8bc4-11eb-912a-141884244094.png)

**Comment by bvaughn** [comment]
> I just need to listen to `gross` and set the `net` value using `setValue`. The Eslint forcing me to add both `getValue` and `setValue`. 

The lint rule is getting tripped up because you've defined `gross` in out the outer scope and the inner scope. This might be something you want to avoid since it can be confusing.

As for `getValue` and `setValue`, you are calling both from within your effect so you need to specify both as dependencies. Otherwise if one changes and the other does not, your effect may behave in a way you do not expect.

If `getValue` and `setValue` happen to be "stable" (meaning that they do not change between renders) then specifying them as dependencies won't cause any change in observable behavior and so it should be okay.

**Comment by gaearon** [comment]
The linter is doing the right thing here.

If any of the functions you use close over some state or props from some parent component (which they likely do), your code will be buggy if you don't include them as dependencies because it will only reference the initial state/props. Read https://github.com/facebook/react/issues/14920 for some concrete examples and fixes.

On a broader note, I don't recommend writing an effect like what you wrote. Effects are a last measure, you shouldn't use them for application data flow. For example, instead of rendering a component, only to learn that some value is different, and then setting another value, it would be better to restructure the code so that both values are set at the same time. You shouldn't need to run a "render loop" to realize that your data needs to change.

**Comment by gaearon** [comment]
Another signal that you're doing something non-idiomatic is that you have `register(...)` calls during render which are likely side-effects or mutations.

**Comment by nadeeravista** [comment]
> > I just need to listen to `gross` and set the `net` value using `setValue`. The Eslint forcing me to add both `getValue` and `setValue`.
> 
> The lint rule may be getting tripped up because you've defined `gross` in out the outer scope and the inner scope. This might be something you want to avoid since it can be confusing.
> 
> As for `getValue` and `setValue`, you are calling both from within your effect so you need to specify both as dependencies. Otherwise if one changes and the other does not, your effect may behave in a way you do not expect.
> 
> If `getValue` and `setValue` happen to be "stable" (meaning that they do not change between renders) then specifying them as dependencies won't cause any change in observable behavior and so it should be okay.


Yes, correct It does not cause any issue by adding(`setValue`, `getValue`), and also it seems not adding also not giving any error.   If that the case why adding something which is neutral to the code and makes the code lengthy or confusing. Moreover, If I don't wanna worry about any changes that happened in the other hierarchy/associations/world (setValue or getValue).

In another language aspect (Java, .Net) we add event listeners to buttons or inputs but we don't again add event listeners to all other method calls within the handler. If I don't really care about the changes of those `setValue`, `getValue` why it force to add.

**Comment by nadeeravista** [comment]
> The linter is doing the right thing here.
> 
> If any of the functions you use close over some state or props from some parent component (which they likely do), your code will be buggy if you don't include them as dependencies because it will only reference the initial state/props. Read #14920 for some concrete examples and fixes.
> 
> On a broader note, I don't recommend writing an effect like what you wrote. Effects are a last measure, you shouldn't use them for application data flow. For example, instead of rendering a component, only to learn that some value is different, and then setting another value, it would be better to restructure the code so that both values are set at the same time. You shouldn't need to run a "render loop" to realize that your data needs to change.

As I mention kindly note the above example is just a sample code to raise my concern. 

Yes in a very abstract perspective `functions` or `data/state` inside `useEffect` which is declared outside  `useEffect` scope can change. So it makes sense Linter asking to add to the dependency array in general. 

But If I know exactly what's going on in my  `useEffect` and what change I need to observe. Do I still need to add something I don't wanna listen to the dependency array and add an unwanted risk or make code confusing. Isn't that make my code more buggy.

**Comment by nadeeravista** [comment]
Seems it still not correct for me. Kindly correct me. Justify me what serious damages can have due to not adding `setValue, getValue ` in the above EXAMPLE ASPECT only. I agree there can be situations its safe to add all the dpendancies. but clarify in the above example context.
