### ISSUE TITLE
Bug: The invalid value warning was showed when adding functions to object prototype

### ISSUE THREAD

**Issue by virtuous-code** [facebook/react#21091]
While adding a function to Object.prototype in React project anywhere, react while showing the Warning: Invalid value for prop \`xxx\` on tag. And an uncaught TypeError.

React version: 17.0.2

## Steps To Reproduce

1. Create a react project with create-react-app
2. Put the following code anywhere in the project: `Object.prototype.test = function () {}`
<img width="876" alt="图片" src="https://user-images.githubusercontent.com/9192537/112427671-f02aed80-8d74-11eb-8b23-8f5fa9683d2d.png">

## The current behavior
Getting the warning
![图片](https://user-images.githubusercontent.com/9192537/112427330-64b15c80-8d74-11eb-9c24-5b7eff138ca9.png)
Also the Uncaught TypeError: renderer.setTraceUpdatesEnabled is not a function.
![图片](https://user-images.githubusercontent.com/9192537/112429126-35501f00-8d77-11eb-8361-28ac8db8a7fe.png)

## The expected behavior
Expected nether warning nor error.

**Comment by nmain** [comment]
> `Object.prototype.test = function () {}`

This adds an __enumerable__ property to every object in your entire JS context.  In a normal JS environment, this is not the case; for instance, `{ a: 3, b: 4 }` has exactly two enumerable properties normally, "a", and "b".

You probably shouldn't make this change.  Even if the React team is willing to support it, many other libraries will assume you haven't mucked up `Object.prototype` with extra enumerable junk.  `for .. in` loops oftentimes don't have own property guards on them because in a regular JS environment, you don't need them.

If you absolutely have to do this, you should make the property non-enumerable.

**Comment by Sinieghi** [comment]
Thanks for the that save me a lot of time!

**Comment by rickhanlonii** [comment]
Yeah patching the object prototype isn't supported.

**Comment by QuixThe2nd** [comment]
Was the cause of `renderer.setTraceUpdatesEnabled is not a function` found?
