### ISSUE TITLE
Bug: `React.useState(new ...())` generates a new instance at each render

### ISSUE THREAD

**Issue by matthieujabbour** [facebook/react#21116]
I don't think this is the expected behaviour, but I let you confirm that.

React version: 17.0.2

## Steps To Reproduce

1. Declare a very simple component and use `React.useState` hook along with a new class instance declaration

Link to code example: https://codesandbox.io/s/weathered-sea-6r40u

## The current behavior

The class constructor is called at each render, which generates a new instance each time and stores it as the new state. Most of the time, this is not what we want.

## The expected behavior

The new instance is created once, at first render. Any subsequent render doesn't trigger a new instance creation. This way, we always deal with the same object instance and we avoid side-effects or memory leaks.

Please note that using `React.useState(() => new ...())` (lazy initial state) provides the correct behaviour. But IMO it should also work with the "classic" way.

**Comment by bvaughn** [comment]
```js
const [test, setTest] = React.useState(new Test());
```

This code creates a new instance of `Test` before `useState` is even called. React can't prevent that. It's how JavaScript works

Put another way, this is what the above code is telling a browser to do:
1. Create a new instance of `Test`
2. Pass that value to `useState`
3. Assign the return value of `useState` to `test` and `setTest` variables.

> The new instance is created once, at first render. Any subsequent render doesn't trigger a new instance creation. This way, we always deal with the same object instance and we avoid side-effects or memory leaks.

To be clear, React will only keep the _first_ instance of `Test` in state. Subsequent renders we re-instantiate `Test` unnecessarily though (and so you should use the lazy initialization pattern).

Also note that your Code Sandbox is running in ["strict mode"](https://reactjs.org/docs/strict-mode.html) because the index file wraps the app in `<React.StrictMode>` so you'll see a double render initially (in DEV mode). That's expected and I suggest reading the "strict mode" docs briefly to better understand why. 😄

**Comment by matthieujabbour** [comment]
> This code creates a new instance of Test before useState is even called. React can't prevent that. It's how JavaScript works

It actually makes totally sense indeed! So sorry for this false alarm, and thanks for your quick reply.
