### ISSUE TITLE
Switch the Context to use the Parent tree instead of the Owner tree

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#2112]
I'm pretty convinced at this point that Contexts are more useful in the Parent tree than the Owner tree. It also opens up new use cases for parent->child communication that wasn't possible before.

**Comment by jwietelmann** [comment]
Any updates on when this might be blessed to go into master? I have a bucketful of potential use cases, and I'd love to be able start playing around to see what I can do with it (with the understanding that it's still unstable).

**Comment by natew** [comment]
Agreed, I have a use case for an animation library that for now has bugs because I'm having to roll a shoddy version of it myself. Would be nice just to know current thoughts on release schedule.

**Comment by telkomsel666** [comment]
#1

**Comment by brigand** [comment]
> On the server-side, I see no reason that everyone can't share a single flux store. 

@jsfb everything I've seen points to stores being fully synchronous, and that you actually do the asynchronous action in the action creator (which eventually triggers another action, which causes the store to update).  Without all of the pieces instanced per request, it appears you'd have to 

- have all stores act like they're serving every user at once, 
- find a way to determine 'done' in this environment,
- ensure stores aren't holding references to data after 'done', while ensuring they do hold it on the client, 
- use an alternative mechanism to 'change' events (getting the data to the source of the request)

Could you clarify how you get around these?  Are you thinking of simple service modules (export functions, communicate by callbacks/promises) rather than flux?

**Comment by jsfb** [comment]
@brigand  Yes, singletons are not without their drawbacks.  Thus the motivation to pass flux stores as context variables => thus our desire to implement context variables.

Your interpretation is correct: If you use a singleton store server side, you will need to have stores act like they're serving every user at once.  You may likely end up with a different server-side store implementation (conforming to the same interface) that is backed directly by the database (since the cost tradeoffs are entirely different on the server side, your security enforcement policy is inherently different, etc).  If you are backed by the database, you are by definition the source of truth (can go straight to the database), and you therefore don't need to worry about tracking a 'done' state nor worry about 'change' events.  You sacrifice a little isomorphism, to gain simplicity in your implementation (ie. you don't need to track done state because you aren't dealing with 'change' events server-side), which you may have wanted to do anyway for security/perf reasons.

It was not my intent to hijack this thread, merely to point out that there are alternatives for flux stores.  You can use a singleton model as long as your store implementations conform to a multi-user interface instead of a single-user interface.  That said, we are implementing context variables because we think they may be valuable in these situations.  I'm not advocating one solution over the other, and both solutions have their tradeoffs.

@natew Even after we switch to parent based contexts, there are a number of design decisions surrounding contexts that we'll still need to figure out.  It will likely take us some time before we feel comfortable publishing them as a supported feature.

**Comment by brigand** [comment]
Thank you for the clarification, that makes a lot of sense and I can see how it'd simplify things now.

**Comment by jamesknelson** [comment]
@jwietelmann @natew If you're using react 0.13 beta 1, and building with Webpack (or similar), you can use [react-parent-context-patch.js](https://gist.github.com/jamesknelson/1481521444e1529d59aa#file-react-parent-context-patch-js) to play around with parent contexts for the moment. I assume it'll break pretty quickly though, so don't build anything which relies on it.

Make sure you require it before you `require('react')`.

**Comment by natew** [comment]
@jamesknelson thanks. I'll be hacking on that this week and let you how how it goes.

**Comment by natew** [comment]
@jamesknelson Just added this in and I'm getting:

Uncaught TypeError: Can't add property _pendingStateQueue, object is not extensible
ContextPatch:58

**Comment by jamesknelson** [comment]
@natew, I've been using my patch since I posted it, but don't believe I've gotten that issue. Are you using 0.13.0-beta.1?

**Comment by natew** [comment]
Yea using beta-1, and loading before anything. It seems to load alright but error later. I didn't dig in too deep just to see if you had an ideas up front. It's not super high up my priority for now but I'll revisit again soon.

**Comment by natew** [comment]
@jamesknelson is this enabled in RC2 or would it be worth updating and trying the patch there?

**Comment by zenlambda** [comment]
Is there any chance that we might get some documentation on how contexts work? I've seen a vague mention of this feature on the React blog. I've seen it in use in other projects such as React-router and perhaps also Reapp. There is code in those projects that throws warnings and needs migrating. I'd love to contribute but I feel unable to help make the situation better because I'm still in the dark about how contexts are supposed to work.

**Comment by epeli** [comment]
@zenlambda maybe this will help https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html

**Comment by natew** [comment]
Just as a heads up to anyone using the contextPatch and running into `type.toUpperCase() is undefined` errors, this just bug bit me and drove me mad for the last couple hours.

If your child Class is attempting to use an undefined component this happens. In my case I was trying to import "Textarea" rather than "TextArea".

I was certain the error was due to how I was mounting routes (in the parent class) and funny enough both children routes I tried had this same Textarea bug, so I spent forever changing the parents until I got this. :skull:

**Comment by 1st1** [comment]
Any chance this will land to 0.14?

**Comment by spicyj** [comment]
@1st1 That's the plan.

**Comment by danscan** [comment]
Does React Native use parent context now as well?  Seems like it still uses owner context.

**Comment by spicyj** [comment]
React Native is still on React 0.13.2. We'll update after the 0.14 final release.

**Comment by jedwards1211** [comment]
Cool, glad to know this is on the way!  I've also used context to pass down stores, out of a desire to avoid singletons.  I've used them in a few other cases as well.
