### ISSUE TITLE
Bug: exhaustive-deps tells me to add state to deps but it shouldn't be the case

### ISSUE THREAD

**Issue by Ignalion** [facebook/react#21120]
I have Add/Edit form with dynamic fields for it. So, I have two parts of the form: shape (fields itself) and data to populate those fields initially (in edit case). Thus, I propagate shape to initialState of form and update data in useEffect if needed.

However I have to copy the state in useEffect because otherwise setState won't trigger re-render sometimes. But exhaustive-deps linter rule tells me I have to add state variable to deps as well as data from props. If I do that I'll run into infinite re-render of course.

React version: 16.14.0

## Steps To Reproduce

1.
2.

Link to code example:
```
import React, { useState, useEffect } from 'react';

const AddEditForm = ({ fields, editData }) => {
  const initialState = Object.fromEntries(fields.map(([key]) => [key, '']));
  const [formData, setFormData] = useState(initialState);

  useEffect(() => {
    if (editData) {
      const newState = { ...formData };
      Object.entries(editData)
        .forEach(([key, value]) => {
          newState[key] = value;
        });
      setFormData(newState);
    }
  }, [editData]);

  return (
    <form>
      {Object.entries(formData).map(([key, value]) => (
        <>
          <label htmlFor={key}>
            {key}
            <input
              id={key}
              type="text"
              value={value}
              onChange={
                (event) => setFormData({ ...formData, [key]: event.target.value })
}
            />
          </label>
        </>
      ))}
    </form>
  );
};

export default AddEditForm;


```

## The current behavior
![image](https://user-images.githubusercontent.com/3126341/112751366-52cef400-8fd6-11eb-8c89-4b84e5a201a8.png)

## The expected behavior
I think rule should not suggest to add state to deps

**Comment by gaearon** [comment]
Something’s wrong with the approach here. It is very rare that setState directly in useEffect is the right solution to anything. (The only legit reason I can think of to do it is to exclude some parts from server rendering).

I suggest to restructure the code so that you don’t rely on effect at all. Generally, you should either:

* Derive data during render, or
* Set all state you need during an event.

**Comment by Ignalion** [comment]
> Something’s wrong with the approach here. It is very rare that setState directly in useEffect is the right solution to anything. (The only legit reason I can think of to do it is to exclude some parts from server rendering).
> 
> I suggest to restructure the code so that you don’t rely on effect at all. Generally, you should either:
> 
> * Derive data during render, or
> * Set all state you need during an event.

Well, partially I agree. Of course it's simplified example, in real case editData comes from Redux, not from component props. So that I think justifies the need of useEffect, because data simply isn't accessible on first render. I think I could try get rid of setting state in useEffect anyway, it just complicates the already complicated solution hardly :)

Anyway, I think it's just weird that rule suggest to put state in deps, it just can't be good idea in any case, can it?

**Comment by bvaughn** [comment]
> Anyway, I think it's just weird that rule suggest to put state in deps, it just can't be good idea in any case, can it?

The lint rule suggests you include any variables referenced from inside of the effect as dependencies. Because `formData` is referenced, the lint rule includes it.

If you're just looking to remove the dependency, you could use the functional update form of set state, e.g.:
```js
useEffect(() => {
  if (editData) {
    setFormData(prevFormData => {
      const newFormData = { ...prevFormData };
      Object.entries(editData).forEach(([key, value]) => {
        newFormData[key] = value;
      });
    });
    return newFormData;
  }
}, [editData]);
```

But I agree with Dan that this overall pattern looks fishy. Unless something is _mutating_ the `editData` prop between render and effects (which would also be problematic) then the effect seems unnecessary here.

I'm not sure I understand why you can't just use the [lazy initialization pattern for your state](https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily):
```js
const [formData, setFormData] = useState(() => {
  const state = Object.fromEntries(fields.map(([key]) => [key, ""]));
  Object.entries(editData).forEach(([key, value]) => {
    state[key] = value;
  });
  return state;
});
```

**Comment by bvaughn** [comment]
I think this issue can be closed now but we can keep talking on it if the answers above are unclear :)
