### ISSUE TITLE
useCallback memoization

### ISSUE THREAD

**Issue by ramonfritsch** [facebook/react#21191]
I want to continue a discussion about the `useCallback` that started on twitter (https://twitter.com/ramon_fritsch/status/1379569928454303749) here, following @gaearon's suggestion.

It's about `useCallback` returning a new reference when dependencies change. I always wondered if that's what we usually want.

Take this example: https://codesandbox.io/s/sipxs

I understand `useCallback` is intended to use on event handlers and regular callback props, thus we need to make it as flexible as possible. But the case for event handlers, I'd suggest to have a new hook `useEventCallback` that would memoize the callback function forever and never return a new reference, helping in not causing a re-render down the chain.

The folks from Formium solved this with https://github.com/formium/formik/blob/2d613c11a67b1c1f5189e21b8d61a9dd8a2d0a2e/packages/formik/src/Formik.tsx#L1193-L1205

Isn't it important enough to become a core hook in the React ecosystem? Or at least have a clear statement in the documentation about this behavior and best practices for event handlers?

**Comment by gaearon** [comment]
So, the initial question was about a Hook that does `ref.current = ...` during render. This isn't great. The reason is that for a bunch of future features we'd like to introduce (for example, built-in exit animations, or coordinating loading state reveal order with SuspenseList), rendering is speculative. We might start rendering something, but then not end up putting it in the DOM. So if you update your ref during rendering, it disagrees with what's on the screen. In many cases this is probably fine, but it's not ideal.

The solution with doing it during a layout effect avoids that problem. It's actually what `useCallback` was in the initial design, as far as I remember. However, it's still kind of tricky. If someone calls it _during_ render, then the result is not what you expected. If you call it from another effect, whether it's updated or not depends on subtle ordering. So, even though it prevents "unnecessary" rendering in some cases, I'd limit its usage only to cases where you really have no other way. The default behavior of `useCallback` is rather naïve but it is very easy to predict, and you always know that you're gonna "see" fresh values there. Not the case here.

Does this answer your question?

**Comment by ramonfritsch** [comment]
Yeah, I guess it's one of those cases where it's better to have a [works-everywhere] approach to a default hook and suggest approaches for such cases. Thanks for clearing that out.
