### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by dmitrii-khr** [facebook/react#21209]
Fresh application, made by create-react-app (4.0.3)
Launching DevServer via npm run start.
White screen, and error at
react-refresh/cjs/react-refresh-runtime.development.js
line number 465:
  hook.renderers.forEach

hook.renderers is undefined. 
hook object has only "_renderers" empty object property

If write this line with hook.renderers&&hook.renderers.forEach, page appears, live reload works.

React version:
17.0.2
react-refresh version:
0.8.3 / 0.10.0
Chrome version:
89.0.4389.114

## Steps To Reproduce
just run dev server via "npm run start."

I can reproduce it only at my enterprice workstation.
At my home pc, this works without issue.

## The current behavior
White screen

## The expected behavior
Working dev server

**Comment by bvaughn** [comment]
This generally means either that you've got an old version of React DevTools installed _or_ some other extension is defining an invalid `window.__REACT_DEVTOOLS_GLOBAL_HOOK__`.

Check out the related issues here:

https://github.com/facebook/react/issues/21047#issuecomment-804246683

https://github.com/facebook/react/issues/19072#issuecomment-639884030

Going to close this as a duplicate but please ask follow up questions if you have them.

**Comment by dmitrii-khr** [comment]
Thank you!

**Comment by gretchelin** [comment]
Can you reopen this issue @bvaughn ?

I'm laso facing this problem. I use NextJS, but this happens both in new CRA and NextJS project I created since the beginning of this year. It just shows white screen and an error in console (attached). Fresh project from CRA will show this problem.

I don't have React Devtool installed anywhere, and this problem happened both in incognito-mode and normal, in numerous browser with or without any browser extension installed. Production is fine, only dev mode shows this issue.

It works fine if I installed React Devtool v4 extension, though.

_This issue (#20117) said that a fix has been merged to detect when devtool hook is disabled, but I don't see any releases that mention this fix, which could be why I still have the problem._ 

![Screenshot 2021-06-09 132114](https://user-images.githubusercontent.com/53071794/121304107-1ef14280-c926-11eb-8da5-9257b74099e3.png)
