### ISSUE TITLE
Adding the ability to add `setState` to stack

### ISSUE THREAD

**Issue by oriSomething** [facebook/react#2130]
i found i have many times where i get errors when there is a "smart widget" that i'm trying to unmount during its retrieving information from the server to render itself. errors which i can prevent if `setState` would execute after another `setState`.
using a callback of setState to inform the parents when it can unmount can be tedious

**Comment by gaearon** [comment]
If I understand the problem correctly, you are unmounting a component that later calls `setState` after the data is fetched, and this causes an error.

It should no longer cause an error in v14 as it has been replaced with a warning in #4091. Additionally, we advise you to use an async primitive that supports cancellation (e.g. Observables), so that you can cancel those requests and their callbacks in `componentWillUnmount`. This way you can unmount children safely without worrying about the warnings when their requests complete.

I hope this helps! Please let me know if I misunderstood, and we should reopen. Thanks!
