### ISSUE TITLE
Bug: Unable to "force update" children if not wrapped into a custom Component

### ISSUE THREAD

**Issue by ErnestBrandi** [facebook/react#21423]
React version: 17.0.2

## The current behavior

I am working on a component that would wrap a React Element in order to be able to update it at will.
```
<Wrapper>
   {/* JSX */}
</Wrapper>

const Wrapper = ({ children }) => {
  // force update by changing state or so
  return React.cloneElement(children);
};
```
What I have noticed is : 

- if the "children", passed down as a props to the wrapper, is a custom component it behaves the way I expect to
```
function Child() {
  return <div>{new Date().toString()}</div>;
}

<Wrapper>
  <Child />
</Wrapper>
```
- if instead it is a simple "html style" element it doesn't get updated
```
<Wrapper>
  <div>{new Date().toString()}</div>
</Wrapper>
```
I've played around with this quite a bit, for example using `React.createElement` on the children and switching between two different types (`div` and `span` for instance), as it says in the [documentation](https://reactjs.org/docs/reconciliation.html#elements-of-different-types) that

> Any components below the root will also get unmounted and have their state destroyed.

but it did not help.
## The expected behavior
I would expect the two options to behave the same way.
## Example
[![Edit react-update-element](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-update-element-l6qz4?fontsize=14&hidenavigation=1&theme=dark)

**Comment by iamhegdesuhas** [comment]
In the sandbox example you provided, If you check the "type" of children being passed to Parent, it will be clear. 

In first case where you are passing Child component, its a function that is passed and it will be called every time Parent component renders which is why the value is getting updated.

In second case html element(div) is passed with its value props set to new Date().toString(). So on every "Update" button click even though its causing Parent to re render, its displaying same value.

In first scenario, instead of calculating the value in Child, if you actually pass  new Date().toString() as props, it will behave the same way as second scenario. (Because value is created when App.js was rendered)

 "Any components below the root will also get unmounted and have their state destroyed." ----> this is actually happening in the example you provided. But as I mentioned above, in first scenario the new Date().toString() is called on every rerender and new node is created with div with new updated value. In second scenario, new node is created with the div passed from app.js.

I am not sure if I am able to convey it properly, but I think its working as expected.

**Comment by ErnestBrandi** [comment]
I didn't think React was working that way but that kind of make sense now. Thanks for clarifying :)
