### ISSUE TITLE
DevTools: Standalone should support multiple connected clients

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#21499]
The standalone DevTools uses a `WebSocket` to communicate with the backend (which is embedded within an application like a React Native app or a webpage running in Safari). It was reported that currently only one application can connect to the standalone DevTools at a time, but this limitation is unnecessary. A Node `Server` server can accept connections from multiple clients, and the DevTools architecture (and "store") support multiple connected renderers as well (for the case of multiple React DOM apps running on a page). So the Standalone DevTools should also be able to support multiple connected apps.

**Comment by mweststrate** [comment]
Currently the unconfirmed but observed behavior is that a newer connection will replace the old connection and reset the state of the devtools, but they do keep working correctly as far as I could tell. 

An MVP would probably have a dropdown to select one of the connections. Do the devtools backend know the identifier of the application? (I can imagine that is quite context dependent, thinking primarily about RN in this case).

For the Flipper specific use case we wouldn't really need the dropdown if we could specify which application we are currently interested in (since device / application selection is ideally made in our chrome). Obviously for standalone devtools that is different.

To add to the complexity a valid scenario is the same app being connected multiple times, while it is deployed to different devices (e.g. a iOS simulator, Android emulator and physical phone). So beyond the identifier the most optimal scenario would also provide the device serial. However, IIRC, (RN) apps do not know the serial of the device it runs on for security reasons. The Flipper SDK embedded in the app does know it as it is provided during certificate exchange, so in principle we could configure the DevTools backend and tell it the device serial + application name from the Flipper SDK, to make the loop work.

**Comment by bvaughn** [comment]
I think the way we would do this would be...to establish a unique id per client connection on the server, then send that id back and forth when communicating (kind of like the "renderer id" works already). Then when a connection closes for a given id, we'd need to clear out its store entries.

**Comment by mweststrate** [comment]
Yeah my comment was mostly wondering how to represent the id meaningfully to the user? If he has connections a34b, 4fs5 and c34d available in the devtools, (or even "facebook - 1", "facebook - 2", "facebook - 3") how to tell which one belongs to which running app/device? If we'd communicate the id as known on the app back through the Flipper SDK to Flipper, we'd solve it in the Flipper case, but still not in the general standalone case I guess.

**Comment by gabrieltrompiz** [comment]
Sorry that I haven't been able to give updates on this issue. I have been a little tight on time. 

I was able to assign the connectionIDs to the Bridge instances inside the Store and attach/remove the listeners of each one of them on connect/disconnect, but still the changes to the Store are really extensive and would take some time to get it done. 

I'll try to pick this up again when I get some free time, but anyone should feel free to take it.
