### ISSUE TITLE
Bug: HTML snippet with spans is rendered vastly different in React than in plain HTML

### ISSUE THREAD

**Issue by mindreframer** [facebook/react#21543]
A list of span elements in combination with Tailwind.css styles (any version, CDN / NPM / etc) is rendered very differently in plain HTML vs. React.js code. 

## Links to code examples:

- https://github.com/mindreframer/select-text-react-bug
- https://codesandbox.io/s/trusting-tdd-f0qbi?file=/public/index.html

## The current behavior
There are no spaces, the word-wrapping is broken and selecting + copying text results in mangeled text in the clipboard. 

## The expected behavior
It should behave similarly to the plain HTML version: have spaces, render without strange word-wraps and be properly selectable. 

Screenshot: 
<img width="847" alt="Screenshot-span-react-bug" src="https://user-images.githubusercontent.com/1232/119066447-1325f680-b9e0-11eb-9880-65c83d89345f.png">

**Comment by eps1lon** [comment]
Thanks for the report.

This is intentional behavior of JSX. Though in your particular case undesired. https://github.com/facebook/react/issues/1643 and https://github.com/facebook/react/issues/4134 should give you an overview on why this is intended by React.

Ultimately, you can reproduce the HTML behavior with

```diff
 <span>In</span>
+{"\n"}
 <span>PARADISE</span>
```

**Comment by mindreframer** [comment]
@eps1lon Interesting... Thanks for the quick response and the provided workaround!
