### ISSUE TITLE
Bug: e+-. as first character of numeric input results in uncontrolled state.

### ISSUE THREAD

**Issue by josemorista** [facebook/react#21544]
Scenario: Creating a input with type numeric; assigning a value using a react state with an initial empty string value; assigning onChange event to modify the state;
Typing the following characters 'e+-.,' first, results in an uncontrolled state scenario where the onChange function is never called.

```
import { useState } from 'react';

function App() {
  const [value, setValue] = useState('');

  return (
    <div className="App">
      <input type='number' value={value} onChange={(e) => {
        if (/^\d{0,11}$/.test(e.target.value)) {
          setValue(e.target.value);
        }
      }}></input>
    </div>
  );
}

export default App;
```

Sample form input to reproduce the bug:

"e1111111111111111111111"

Obs: My workaround was to add an onKeyPress function to the numeric input that prevents the default behavior of those keys.

**Comment by idnoble33** [comment]
The reason you are getting e or R is because input accepts floating point numbers , including negative symbols and e or E character(where the exponential is the number after the e or E.

Floating point number comprise of the following order:

  1st  is " - " character
  2nd  range " 0-9 " which is one or more characters
 3rd  character is optionally is in exactly following order:
        1.  " e " character or " E " character 
        2.  optionally, " - " character or " + " character
        3. one or more character which range " 0 - 9"


You could add pattern="[0-9\.]+"  and set input  type=text" as shown below:

**https://codesandbox.io/s/polished-sun-vzqq5**

import React, { useState } from "react";
import ReactDOM from "react-dom";

function App() {
  const [value, setValue] = useState("");

  return (
    <div className="App" style={{ textAlign: "center" }}>
      <h2>Accept number only</h2>
      <input
        type="text"
        pattern="[0-9\.]+ "
        value={value}
        onChange={(e) => {
          if (/^\d{0,11}$/.test(e.target.value)) {
            setValue(e.target.value);
          }
        }}
      ></input>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by josemorista** [comment]
Hi, thanks for the reply, I know that is because floating points and exponential function; here I solved the issue by adding onKeyPress change event and blocking events coming from those keys. But the major reason to open this issue was because by starting to type e, + or - results in a bug that my onChange function was not updating the state. The reason is that event.target.value is sent as an empty string for those keys.

Obs: The input of type number was required by the task so it can open only the numeric keyboard at mobile browsers.
