### ISSUE TITLE
Bug: hooks 

### ISSUE THREAD

**Issue by 18613109040** [facebook/react#21569]
```js
const [value, setValue] = useState();
const handleChangeValue = () => {
  setValue(Math.random().toString(36).slice(-8));
};
const RenderText = () => {
  useEffect(() => {
    return () => {
      console.dir("destory RenderText");
    };
  }, []);
  console.dir("render text");
  return <div>{value}</div>;
};

return (
  <div>
    <RenderText />
    {RenderText()}
    <button onClick={handleChangeValue}>change value</button>
  </div>
);
```

After changing the value, the `<RenderText/>` writing method will execute the destruction function, and `RenderText()` will not.

**Edited** by @bvaughn to fix formatting/syntax.

**Comment by daniloab** [comment]
please, provide a better code and information about your possible bug

**Comment by bvaughn** [comment]
Calling `RenderText` directly as a regular function (e.g. `{RenderText()}`) is not supported. It will often cause errors to be thrown when those components use hooks. **Components must only be called by React itself** (e.g. `<RenderText />`).

**Comment by 18613109040** [comment]
I don't understand why I use <RenderText /> every time the value changes, the <RenderText /> component will be destroyed and then created

**Comment by 18613109040** [comment]
I don't understand why I use every time the value changes, the component will be destroyed and then created

**Comment by 18613109040** [comment]
I don't understand why I use <RenderText /> every time the value changes, the <RenderText /> component will be destroyed and then created

**Comment by 18613109040** [comment]
I don't understand why I use ``` <RenderText />``` every time the value changes, the``` <RenderText />``` component will be destroyed and then created

**Comment by bvaughn** [comment]
The code shown above has two problems:

### Don't call a React component as a function
Calling `RenderText` directly as a regular function (e.g. `{RenderText()}`) will often cause errors when those components use hooks. **Components must only be called by React itself** (e.g. `<RenderText />`).

### Don't define a React component inline
Defining a component (like `RenderText`) within the body of another component is not encouraged. Because the "type" of this inline component (the function itself) gets recreated each time the parent component renders, React deeply unmounts and remounts the component (and everything below it). This includes destroying and recreating effects.

### Proposed solution
Do this instead
```js
function SomeComponent() {
  const [value, setValue] = useState();
  const handleChangeValue = () => {
    setValue(Math.random().toString(36).slice(-8));
  };

  return (
    <div>
      <RenderText value={value} />
      <button onClick={handleChangeValue}>change value</button>
    </div>
  );
}

function RenderText({ value }) {
  useEffect(() => {
    return () => {
      console.dir("destory RenderText");
    };
  }, []);
  console.dir("render text");
  return <div>{value}</div>;
}
```
