### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by knolcoder** [facebook/react#21586]
npm update check failed                    │
│             Try running with sudo or get access              │
│             to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Windows\.config

React version: Latest Version

**Comment by bvaughn** [comment]
Not sure what this issue is about. There's not enough info here though for one of us to help.

**Comment by knolcoder** [comment]
When i command to create-react-app and then after this error comes ,
npm update check failed │
│ Try running with sudo or get access │
│ to the local update config store via │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Windows.config

React version: Latest Version

**Comment by bvaughn** [comment]
This error is unrelated to react. Sounds like your NPM client is trying to update itself but was installed in such a way so that you are not running it with the correct permissions.

I suggest posting about this somewhere like Stack Overflow. (You can probably find existing posts about this already though to be honest.)
