### ISSUE TITLE
Error: "Commit tree already contains fiber "480". This is a bug in React DevTools."

### ISSUE THREAD

**Issue by 447166939** [facebook/react#21614]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.12.3-8f202a7c8d

Component stack: CommitFlamegraphAutoSizer@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:38393:34
div
div
div
SettingsModalContextController@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:29446:40
Profiler_Profiler@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:40191:34
ErrorBoundary_ErrorBoundary@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:33093:5
PortaledContent@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:33172:34
div
div
ProfilerContextController@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:37211:35
TreeContextController@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:25674:31
SettingsContextController@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:26288:35
ModalDialogContextController@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:33315:38
DevTools_DevTools@moz-extension://4e6aa136-7cd8-4b97-8dff-0f154b4e34f0/build/main.js:40586:27

**Comment by bvaughn** [comment]
Hi @447166939. For some reason, you're running an older version of DevTools (4.12.3)

Please update to the [latest version in the Firefox store](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/) which is ([4.13.5](https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#4135-may-25-2021)). This issue should have been fixed in either 4.13.3 or 4.13.4.
