### ISSUE TITLE
Bug: Context is not working well in Lazy Load Class-Based Components.

### ISSUE THREAD

**Issue by boy-techy** [facebook/react#21620]
Context is not working well in Lazy Load Class-Based Components.

React version: 17.0.2

## Steps To Reproduce

1. Create Context in Lazy Load Component for e.g. UsersList Component
2. Attach the Context where you want to access that by User.contextType = UserContext
3. Try to access this.context in User component, it will be a blank Object. And if you just console UserContext also it will give you undefined also.

Link to code example:
https://codesandbox.io/s/context-is-not-working-well-in-lazy-load-class-based-components-vksor

## The current behavior
this.context is blank in class bases component

## The expected behavior
this.context should be actual values that it have been passed

**Comment by LXSMNSYC** [comment]
It must be because of circular dependency:

![image](https://user-images.githubusercontent.com/4783372/120890756-51095880-c637-11eb-87dd-34628443c7e3.png)

I moved `UserContext` into a separate file: https://codesandbox.io/s/context-is-not-working-well-in-lazy-load-class-based-components-forked-06g9h and it worked.

Take note that the problem isn't React-centric but rather how modules work in general.

**Comment by boy-techy** [comment]
Thank you @LXSMNSYC. It was because of circular dependency. Actually, on my machine, there was no hint like yours so I missed that.
