### ISSUE TITLE
Request for Package Release

### ISSUE THREAD

**Issue by LandonSchropp** [facebook/react#21644]
I'm sorry if this is the wrong place to file this, but I wasn't sure how else to get ahold of the React team. The #21392 by @bvaughn fixes an issue that was causing MobX components to display components in stack traces as `wrappedComponent`, making it very hard to debug issues. This PR was merged back in April, but there hasn't been a React release since March. Is there any chance you guys would be willing to release React 17.0.3 with this fix?

Thanks!

**Comment by bvaughn** [comment]
I'm going to close this issue since it's a question and Dan has answered it. As Dan mentioned, we probably aren't going to put out a 17 patch release just for this fix because those require a lot of testing and extra processes. If we need to do one for other reasons (bug fixes) we will consider this as well though.

**Comment by LandonSchropp** [comment]
That's understandable. I didn't think about using the `@next` flag. That should meet my debugging needs. Thanks for the response!
