### ISSUE TITLE
Feedback on startTransition/useTransition syntax

### ISSUE THREAD

**Issue by stefanhamburger** [facebook/react#21664]
As recommended on the React 18 blog post, I'd like to give feedback on [startTransition](https://github.com/reactwg/react-18/discussions/41) as I don't have access to the working group.

I have two concerns regarding the `startTransition` callback syntax:
1. If I want to dynamically use or not use the transition behavior, I'd have to use complicated code like:
   ```tsx
   if (canBeDelayed) {
     startTransition(() => {
       setState(newValue);
     });
   } else {
     setState(newValue);
   }
   ```
2. It is not intuitive that `startTransition` only affects `setState` calls when I can wrap arbitrary code inside it.

Have you considered an alternative syntax, e.g. by adding another parameter to the `setState` callback? This makes it easy to subscribe to the feature dynamically, and avoids nesting the code.

```tsx
setState(newValue, { isTransition: true });
```

Instead of the new `useTransition` hook, you could expand the return values of `useState`:

```tsx
const [state, setState, isPending] = React.useState(startValue);
```

In my opinion, this results in a cleaner syntax that is more idiomatic with the existing hooks.

Where can I find previous discussion on why you settled for the `startTransition` syntax? And is the syntax set in stone or are you still willing to make changes like these?

**Comment by gaearon** [comment]
>If I want to dynamically use or not use the transition behavior, I'd have to use complicated code like

Can you clarify the use case for this? We use this feature quite a bit and haven't seen a pattern like this.

>It is not intuitive that startTransition only affects setState calls when I can wrap arbitrary code inside it.

Yes, it's something you'd learn when you get familiar with the feature. However, it is a very important capability. In particular, it lets you do something like this:

```js
startTransition(() => {
  props.onClick()
})
```

or:

```js
startTransition(() => {
  router.navigate('/')
});
```

This is especially useful for `useTransition` because it lets a button deep in the tree provide visual feedback for a state update that may be "several abstractions away" somewhere at the top level of your app.

>Have you considered an alternative syntax, e.g. by adding another parameter to the setState callback? This makes it easy to subscribe to the feature dynamically, and avoids nesting the code.

Yes, this was our first guess at what the API would look like in 2018, but it became clear pretty quickly that there's a bunch of cases where threading this option explicitly through all the layers is just too annoying and not ergonomic. 

>Where can I find previous discussion on why you settled for the startTransition syntax? And is the syntax set in stone or are you still willing to make changes like these?

I don't think we have a formal writeup anywhere as the research on this was spread through a few years, and we didn't describe each intermediate step. In short, the feature is very similar to `unstable_batchedUpdates` which also works by wrapping. This approach has proven valuable for libraries to be able to wrap arbitrary code. In general we are open to make changes when there is a significant flaw discovered, but this particular distinction was very intentional.
