### ISSUE TITLE
Bug: Layout effects don't re-fire in 18 on Suspense re-showing

### ISSUE THREAD

**Issue by gaearon** [facebook/react#21676]
Intended behavior: https://github.com/reactwg/react-18/discussions/31

Sandbox: https://codesandbox.io/s/react-18-layouteffect-semantics-forked-m02w5

Expected: when suspended content is hidden and then shown, we get layout cleanup followed by layout setup.
Actual: only layout cleanup happens.

**Comment by bvaughn** [comment]
I think this is a `subtreeFlags` issue. In commit work, where we check the Offscreen tree `fiber.subtreeFlags & LayoutMask`, the test you added shows no layout flags so we skip the subtree.

We intentionally removed the `subtreeFlags` checks for most places, since the values aren't 100% reliable and the check is just an optimization, but it looks like @acdlite added this one in #21386.
