### ISSUE TITLE
[DevTools Bug]: Indentation broken for Components tab

### ISSUE THREAD

**Issue by thany** [facebook/react#21717]
### Website or app

https://www.enexis.nl/

### Repro steps

1. Make sure the devtools is narrow, but still wide enough that its panels remain side by side.
2. Drag the splitter between the panels
3. Observe the indentation changing with the width of the components tree panel

The effect is not super effective on the given website, but on the development version, the component names are quite a bit longer, and so it seems to depend on the length of component names how far the indentation is. This is weird and unneccesary.

Please change it so that the indentation is fixed.

### How often does this bug happen?

Every time

**Comment by thany** [comment]
Pretty sure this has been done intentionally, to "make it fit" even for narrow inspectors, but for (like I said) long enough component names, and a narrow enough devtools, this can actually **cause indentation to become 0**, making it unneccesarily difficult to find my way around the component tree.

**Comment by bvaughn** [comment]
I realize this feature is not ideal for every width and component name combination, but it's an intentional decision / trade off:
https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#no-more-horizontal-scrolling

Going to close this since it's not a feature I have intentions of changing for the time being. Thanks for understanding!

**Comment by thany** [comment]
Make it an option then, or force a minimum amount of indentation. Because frankly, for something so unimportant as "no horizontal scrolling", having no identation is a horrible trade-off.
