### ISSUE TITLE
React 18  Feature request

### ISSUE THREAD

**Issue by cybercoder** [facebook/react#21791]
Make native component's property types importable for developer to be able to extend his/hers components.

e.g

```javascript
const MyInputComponent = (props) => {
   return (
       <>
          // my other things
          <input {...props}/>
      </>
   )
}

MyInputComponent.propTypes = {
     ....nativeReactJSXInputProps, // importable from react core
     myProp1: PropTypes.string
}
```
The goal is to assist IDE(s) to find all correct prop types of my component.

**Comment by bvaughn** [comment]
There isn't a single set of "native component types". It varies, based on the native component type (e.g. `HTMLButtonElement` would have different supported attributes than `HTMLInputElement` or `HTMLDivElement`). In addition to that, `propTypes` as a concept are deprecated (and have been moved out of React into a separate package). Our recommendation instead is to use static type checking (e.g. Flow or TypeScript).

Using TypeScript as an example, since it seems to be more commonly used outside of Facebook, you can declare prop types for a specific native component (e.g. [`HTMLDivElement` types](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.htmldivelement.html)).

Hope this helps!
