### ISSUE TITLE
useEffect in React 18 (StrictMode) gets called twice.

### ISSUE THREAD

**Issue by kuzn5298** [facebook/react#21808]
Why is useEffect called twice in React 18 with StrictMode (if I set deps to be an empty array)?

Expected behavior: 
![image](https://user-images.githubusercontent.com/84848052/124736513-bfd01f00-df1f-11eb-9212-847d74acdf18.png)

Strange behavior:
![image](https://user-images.githubusercontent.com/84848052/124736688-eb530980-df1f-11eb-9e7d-fe17d91d8a98.png)

Examples:
Expected behavior in React 17: https://codesandbox.io/s/react-17-useeffect-mud1l
Expected behavior in React 18 without StrictMode: https://codesandbox.io/s/react-18-useeffect-without-strict-mode-g788s
Strange behavior in React 18 with StrictMode: https://codesandbox.io/s/react-18-useeffect-2d14y

**Comment by albseb511** [comment]
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

```
Note:

This only applies to development mode. Lifecycles will not be double-invoked in production mode.
```

**Comment by dimooze** [comment]
Yes that's what the doc are pointing out and specially : 
```
Starting with React 17, React automatically modifies the console methods like console.log() 
to silence the logs in the second call to lifecycle functions. 
However, it may cause undesired behavior in certain cases where a workaround can be used.
```

**Comment by gaearon** [comment]
The comments above are a bit misleading so let me clarify. The behavior _is_ new in React 18 specifically. **In React 18, Strict Mode also includes Strict Effects.** This means that React will simulate mount->unmount->mount during mount in order to test that your code is resilient to that sequence. This will help you check compatibility with upcoming features that let you preserve state of the tree while it’s unmounted (or, rather, not visible).

For details, read https://github.com/reactwg/react-18/discussions/19 and the linked pages from it. They explain the motivation and how to fix code that relies on existing behavior. If this is too much of a burden, you can remove StrictMode from your app. In general, we’ve found that we were able to switch thousands of components to new behavior with only a few manual changes, so we expect that this shouldn’t be *too* disruptive. In production they would still fire once (unless you use the upcoming opt-in features for preserving state).

Happy to answer any questions but please be sure to read the link first! It has many of possible questions already answered.

**Comment by kuzn5298** [comment]
Thanks for the answer.
