### ISSUE TITLE
[Devtools] Make link style value clickable

### ISSUE THREAD

**Issue by otakustay** [facebook/react#21827]
I didn't find a suitable place to open feature request of react devtools.

We're developing a babel plugin to inject a `useDebugValue` into every component so that developers can immediately see the source file path of inspecting component like:

![image](https://user-images.githubusercontent.com/639549/124860336-0f781e80-dfe4-11eb-875f-d8715b625dba.png)

We are expecting this `file://` url clickable and open the default code editor on clicked, like those image urls in DOM panel:

![image](https://user-images.githubusercontent.com/639549/124860429-3a627280-dfe4-11eb-805d-fb99ad783f00.png)

This can be a helpful feature to help developers quickly location source files, stackoverflow questions and more

**Comment by kkragoth** [comment]
Hello,

I am very interested in starting to contribute to this project and I would like to grab this issue since it seems quite easy to start but I've never set up this devtools project so I am little nervous. If I could be pointed in right direction with docs (I saw architecture and dev workflow from issue Combine view highlighting code but all links would be useful!) and starting place for this issue I'd be happy to try this as a first issue

**Comment by bvaughn** [comment]
@kkragoth Feel free to work on this issue!

To get started, run the following:
```sh
git clone git@github.com:facebook/react.git

cd react

# Install React dependencies
yarn install

# Install build script dependencies
cd scripts/release
yarn install
cd ../../

# Checkout DevTools dependencies
scripts/release/download-experimental-build.js --commit=main
```

Now open two terminals to run DevTools in DEV watch mode:
```sh
cd packages/react-devtools-inline
yarn start
```
```sh
cd packages/react-devtools-shell
yarn start
```

Now any changes you make to DevTools will automatically reload in the test app at http://localhost:8080

**Comment by bvaughn** [comment]
Please also keep in mind that links should not be clickable when props are editable, (since this would interfere with editing), only when they're read-only

**Comment by PrinceRajRoy** [comment]
@bvaughn I was trying this out, any suggestion how to use/open the default code editor? It works fine with vscode


https://user-images.githubusercontent.com/47452572/125105072-af749b80-e0fb-11eb-8e2f-a1a5490ed4e3.mp4

**Comment by otakustay** [comment]
Default editor should be registered system wide, I think it is enough to just open the `file://` protocol url and leave OS to decide which app to handle this

**Comment by kkragoth** [comment]
@otakustay I thought the same but I started working in parallel and file:/// seems to be intercepted by Chrome and that's the issue that @PrinceRajRoy might be talking about...

https://user-images.githubusercontent.com/6214896/125112263-379c7600-e0e7-11eb-94c3-92723372b8a2.mov

**Comment by PrinceRajRoy** [comment]
@kkragoth indeed, I tried with firefox too, same security issue.

**Comment by otakustay** [comment]
This is not a problem, the displayed string is fully controlled by developers, they can change it to `vscode://` if their default editor is vscode, for devtools it just renders a link and all behavior should comply with browser.

**Comment by rainealexander** [comment]
It looks like it may be possible to use `process.env.EDITOR` to check the user's default text editor, but it's not guaranteed to be a coding environment

**Comment by anushaNemilidinne** [comment]
Hello! is anyone working on this issue? Been using React for almost 2 years and I always wanted to contribute to this open source project.

**Comment by bvaughn** [comment]
So far as I know, there is no open PR for this so it's still up for grabs.

**Comment by kkragoth** [comment]
I'm little nervous to start PR, but I found out I have some questions that maybe other joining contributors and someone later assigned to issue might ask.

I'v very new to this project so I thought the best place to start is with KeyValue file (edited in PR).

I have some questions that I think will be useful for anyone starting work with this issue being new to project
- is this the correct place I'm trying to do changes?
- How can I set in devtools to disallow editing values? Right now for testing I simply set specific booleans (isReadOnly/canEdit...) to appropriate values in code.
- this issue feels nice to add 'http'/'https' support, not really sure if needed.
-  how one should approach adding tests for this issue? 

Also I believe this issue was started as a way for developers to get quickly to source file. Devtools sometimes render 'source' in panel for component. This could be made to be a clickable link instead of copying to clipboard

**Comment by bvaughn** [comment]
> How can I set in devtools to disallow editing values? Right now for testing I simply set specific booleans (isReadOnly/canEdit...) to appropriate values in code.

DevTools already has this feature built-in. Sometimes props can be edited (e.g. if you're using a DEV build of React) and sometimes not. We shouldn't _change_ that for this feature. My point was just that links should not be clickable _when props are editable_ because that would break the editing experience.

**Comment by kkragoth** [comment]
> > How can I set in devtools to disallow editing values? Right now for testing I simply set specific booleans (isReadOnly/canEdit...) to appropriate values in code.
> 
> DevTools already has this feature built-in. Sometimes props can be edited (e.g. if you're using a DEV build of React) and sometimes not. We shouldn't _change_ that for this feature. My point was just that links should not be clickable _when props are editable_ because that would break the editing experience.

I understand and never broke editing experience.

I only had no idea how to start devtools where props can't be modified since I've been only using DEV builds, and now after your comment I know I should've been using production builds. The code I supplied works if props can't be modified then display it as link but if it's editable then nothing changes.

**Comment by bvaughn** [comment]
That seems right then. (Though I suggest using `color: var(--color-link);` for those styled links to make them fit the theme right.
