### ISSUE TITLE
Bug: [eslint-plugin-react-hooks] Functions returning new dates should be flagged as missing dependencies 

### ISSUE THREAD

**Issue by amanmahajan7** [facebook/react#21830]
React version: 17.0.1

## Steps To Reproduce

 ```
import "./styles.css";
import { useMemo, useState } from "react";

export default function App() {
  const [, rerender] = useState({});
  function getCurrentDate() {
    return new Date();
  }

  const currentTime = useMemo(() => {
    return getCurrentDate().toISOString();
  }, []);

  return (
    <div className="App">
      {currentTime}
      <button onClick={() => rerender({})}>Rerender</button>
    </div>
  );
}

```
Link to code example:
https://codesandbox.io/s/unruffled-wiles-cfiig?file=/src/App.js

## The current behavior
No warning appears for `getCurrentDate`. It returns a new date everytime it is called

## The expected behavior
Should flag `getCurrentDate` as missing dependency. 

I am not sure if this a limitation.

**Comment by vkurchatkin** [comment]
> Should flag getCurrentDate as missing dependency

And what that dependency would be?

**Comment by amanmahajan7** [comment]
`getCurrentDate` as it used inside `useMemo`

**Comment by vkurchatkin** [comment]
Well, `getCurrentDate` doesn't actually capture any local variables, hence this behaviour. What you propose would basically disable `useMemo` in this case (since `getCurrentDate` is a new reference in every render). But what should be done if `new Date` is used in `useMemo` directly?

```js
 const currentTime = useMemo(() => {
   return new Date().toISOString(); 
 }, []);
```

Behaviour is exactly the same, but there is nothing you can add to dependencies.

**Comment by amanmahajan7** [comment]
That makes sense. I wanted to confirm if this a bug or expected behavior or if it is a limitation.
