### ISSUE TITLE
Bug: (hooks, ts) useEffect return type

### ISSUE THREAD

**Issue by y-nk** [facebook/react#21858]
React version: 17

## Steps To Reproduce

```
useEffect(
  () => !bool && funcThatReturnDestroyerFunc(dep),
  [dep],
)
```

## The current behavior

Breaks because type returned by the create function must be of `void | () => void` 

## The expected behavior

We should relax and allow `type Destroyer = () => void | undefined | null | false` since i expect there's something _in the vibe of_

```
const destroyer = create()
if (destroyer) /* ... */
```

...although the codebase is so thick i couldn't even find the line where that's supposed to happen.

**Comment by eps1lon** [comment]
Thanks for the feedback.

The types aren't hosted in this repo. For TypeScript you want to file this against https://github.com/DefinitelyTyped/DefinitelyTyped/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc.

Though I don't think we do want to relax the types since I suspect that most returns would be a mistake. In the end you can always rewrite the effect so that you're sure you only return a destroy function. Especially because the flow types used by React itself are as strict as the TypeScript types: https://github.com/facebook/react/blob/a632f7de3bd35eaf6d5082054af4da92dd37cf20/packages/react/src/ReactHooks.js#L95-L98
