### ISSUE TITLE
Bug: Transactions with React Context data store are aggregated when called within same function

### ISSUE THREAD

**Issue by l-monninger** [facebook/react#21899]
I've made a SO post about this [here](https://stackoverflow.com/questions/68412614/react-context-updates-in-same-function-body-are-aggregated-as-a-single-transacti). I'm not sure that this is a bug, as it is something I can work around. I am more interested in understanding why this should or shouldn't be expected behavior.

React version: 17.0.2

## Steps To Reproduce

1. Open Sandbox.

The example provided does depend on shortid.

Link to sandbox here: https://codesandbox.io/s/vigorous-butterfly-8nlns?file=/src/App.js

## The current behavior
Context updates are not propagated between the first and second dispatch call.

## The expected behavior
It would be nice if there was a way to force these updates to propagate.

**Comment by markerikson** [comment]
The code in the PasteBin is formatted a bit awkwardly.  But as far as I can tell, this is entirely standard React batching behavior.  Multiple state updates queued in a single event handler will all be batched into one render pass:

https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#render-batching-and-timing

That said, your code also looks like it's structured in a rather unusual way. It appears to be putting some functions like `dispatch` _into_ a `state` object and then using that inside of the `makeCapiProcess` function.

FWIW, a couple suggestions for this specific example:

- it would be easier to read and try this if it were in a CodeSandbox.  Ideally it would be runnable, but even if it's _not_ runnable, having the formatting and syntax highlighting would help.
- I'd recommend rethinking the logic structure.  Putting `dispatch` into a "state" value is very confusing and not a good pattern to follow.

**Comment by l-monninger** [comment]
Hi, @markerikson ! Thanks for the response and the link on batching! Could you possibly point me to where the batching that's affecting my method is in the React source?

On the pattern: I'll try to provide a code sandbox sometime tomorrow. I don't really see the difference between adding dispatch to state and making setters that use the dispatch (or similar) which is a pretty widely used pattern as far as I can tell. To me it seems like this is the functional equivalent of an assignment operator. But, would love to know more about what vulnerabilities there might be. May this is better for an SO post, if it's not a bug. Should I make one?

**Comment by l-monninger** [comment]
@markerikson One thing I would be curious about is whether you think some kind forceUpdate called in between should ideally trigger a render sequence that respects the order of the pre-compiled calls. I've also included this in the sandbox: https://codesandbox.io/s/vigorous-butterfly-8nlns?file=/src/Example.tsx

While I get that this a rather imperative pattern for react. In my eyes, forcing an update like this should be possible. 

I get that the way I'm doing it, there is no difference between the dispatch and the forceUpdate as far as renders are concerned. But, it would be nice if there were some imperative

**Comment by markerikson** [comment]
Okay, so best as I can tell from that sandbox, you're calling `makeCapiProcess` inside of a `useEffect`.

As I understand it, React handles state updates queued in `useEffects` by batching them together and running them all at the end of the "passive effect" phase, ie, after all `useEffect`s are done executing, per that post I linked earlier.

The "dispatch in a state object" thing is really about code understandability.  I have literally never seen anyone do that before, and I never would have expected to see a `dispatch` function from a `useReducer` hook put back into a `useState` state value.

Note that per your comment about "moving this to a `setTimeout` lets the intermediate update propagate", that won't even work in React 18 because React will batch _all_ updates by default, even across event loop ticks.

Is there a reason why you're trying to get that intermediate value to render, instead of the final result?

**Comment by l-monninger** [comment]
@markerikson makeCapiProcess doesn't actually run the logic of the function, it just makes a function with the updated value of the state; it's a factory pattern. In this case, the most relevant updated value is that of dispatch. Glad I could be a little unique haha. But, yeah, I can see how it would negatively affect understandability.

Very good to know about the setTimeout. Still would love to know where this is implemented in the React source--more of a learning thing for me.

In the actual use case, I was experimenting with a process progress tracker that uses function points. I wanted to update the function points after each stage of the process had been completed.

**Comment by markerikson** [comment]
Ah, you're right - I misread the signature of that function, and thought it was running the body of that logic immediately instead of returning a function. My bad.

Re-reading the source, it looks like `runCapiProcess` does still get called in a `useEffect`, though, so my prior comment about how the state updates will get batched still stands.

Really, there's two aspects happening here:

- You've got a continuous synchronous function executing, and you're trying to get React to update in the middle of that synchronous logic. If you called `runCapiProcess` in a `setTimeout`, React would at least synchronously execute a render pass when you call `dispatch()` (as of React 17), but even then the browser can't paint until your own logic is done executing and the JS event loop is free.
- Because it _is_ running in a `useEffect`, all the updates get batched at the end of the effect phase.

if I understand what you're trying to do here, you'd need to switch to something like having this be an `async` function and briefly yielding back to the browser after each `dispatch` in order to let React render and the browser repaint, in order to have the in-progress updates actually show up.
