### ISSUE TITLE
Can we hide data-reactid from DOM?

### ISSUE THREAD

**Issue by tiye** [facebook/react#2190]
I mean the `data-reactid` generated from `key` prop. I some cases we may use ids like UUID of MongoDB, which are quite long. After putting into the DOM, the properties look quite ugly and messy.
Is there a chance that `data-reactid` becomes invisible in the Elements panel in debugging?

**Comment by dschinkel** [comment]
this cased me problems while trying to test my view with Casper.  For example having the data-reactid in my <h3> tag caused this test to blow up:

```
    describe('Scenario 1: No Companies are Listed', function () {
        it('should see that no companies are listed', function () {
            casper.then(function () {
                expect(this.fetchText('h3')).to.equal('test');
            });
        });
    });
```

**Comment by Aweary** [comment]
@dschinkel React v15 has removed the `data-reactid` attribute.

[document.createElement is in and data-reactid is out](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html#document.createelement-is-in-and-data-reactid-is-out)

**Comment by jimfb** [comment]
@Aweary Only for client-side rendering, SSR still has them :/

**Comment by dschinkel** [comment]
cool thanks @Aweary didn't upgrade yet!  perfect.

@jimfb what is SSR?

**Comment by dschinkel** [comment]
Plus lets say I go to some existing React code that's < 15.0 say at another client or job, or whatever, I'd need to know how to resolve this anyway via Casper or get it working so I'd like to continue to pursue talking about how I could do so.

**Comment by jimfb** [comment]
@dschinkel SSR = Server Side Rendering

**Comment by zpao** [comment]
I'm not sure how `data-reactid` would be impacting Casper. `fetchText` takes a selector and `'h3'` should still select an `<h3 data-reactid=...>test</h3>` (I would assume this should be the same as `document.querySelector/All`).

Anyway, I think commenting on an old issue isn't an appropriate place to discuss this though. If you think this is a specific issue with React, please open a new issue with a test case we can run. Otherwise, this seems to me like potentially an issue with Casper or your usage of it (maybe querying the DOM before your component has rendered) and would be better discussed on stack overflow or potentially in the Casper repository.

**Comment by dschinkel** [comment]
it does cause problems but I'm looking into seeing how I can get Casper to play friendly.  fair enough.
