### ISSUE TITLE
After the component is unmounted, the component node in the react devtools panel is not removed

### ISSUE THREAD

**Issue by mrdulin** [facebook/react#21933]
The component node in react devtools is **NOT** removed, but in the DOM, the DOM node corresponding to the component is removed.

A minimal, reproducible example:

`App.tsx`:
```tsx
import React from 'react';
import { Message } from './components/Message';

function App() {
  return (
    <div className="App">
      <Message />
    </div>
  );
}

export default App;
```

`./components/Message.tsx`:
```tsx
import React, { useState } from 'react';

export const Message = React.forwardRef<HTMLDivElement>((props, ref) => {
  const [visible, setVisible] = useState(true);

  if (!visible) return null;
  const rootRef = ref || React.createRef();

  return (
    <div ref={rootRef} className="message">
      <button type="button" onClick={() => setVisible(false)}>
        close
      </button>
    </div>
  );
});

Message.displayName = 'Message';
```

`Message` component in react devtools panel:

[![enter image description here][1]][1]

`Message` component in DOM:

[![enter image description here][2]][2]

Now, when I click the close button, I expect the `Message` component in react devtools panel should be removed as same as DOM. But it does NOT.

[![enter image description here][3]][3]

Environment: React Developer Tools 4.14.0 (7/16/2021)

  [1]: https://i.stack.imgur.com/vxfkA.png
  [2]: https://i.stack.imgur.com/K3tpV.png
  [3]: https://i.stack.imgur.com/Y5uAo.png

**Comment by kaputadali** [comment]
I think setVisible not fully defined

**Comment by bvaughn** [comment]
> The component node in react devtools is NOT removed, but in the DOM, the DOM node corresponding to the component is removed.

DevTools isn't showing the DOM elements. (Those are hidden because of the ["component filters" setting](https://github.com/facebook/react/blob/main/packages/react-devtools/CHANGELOG.md#component-filters).) It's showing the `Message` component, which is always mounted in the example code you provided.

I'm going to simplify the example a little more to make it clearer:
```js
function Message({visible}) {
  if (!visible) return null;
  return <div>hi</div>;
}
```

The component above sometimes renders an `HTMLDivElement` and sometimes it renders `null`. Regardless, as long as the _component itself_ is still rendered and mounted in the tree, React DevTools will show it.

If your `App` component didn't render the `Message` component, _then_ DevTools would remove it.

**Comment by mrdulin** [comment]
@bvaughn Thanks for the reply. Can I understand that React needs to maintain a kind of "virtual" node to maintain the relationship between the component tree nodes, but reflected on the DOM node, the removed node must not exist on the DOM tree .
