### ISSUE TITLE
Bug: additional outline is added to SVG nodes when used as root node in React 17

### ISSUE THREAD

**Issue by Ayc0** [facebook/react#21943]
React version: 17.0.2

## Steps To Reproduce

1. Use an SVG as a root node for ReactDOM.render (I managed to reproduce when `<svg>` and `<g>` where used as the root node)
2. Click on the rendered SVG and you'll see that an outline is added to the root node in React 17
3. Try the same thing in React 16 and you won't see any outline

Link to code example with React 17: https://mtpqc.csb.app/
Link to code example with React 16: https://y8lot.csb.app/

## The current behavior

And outline is added on click

## The expected behavior

I noticed that when updating an app from v16 to v17. So I'd have expected the previous behavior to be kept (as I didn't spot this change in the changelog)

**Comment by eps1lon** [comment]
Thanks for the report.

The outline on click is added because the `svg` is focused on click. This only happens if the browser considers the `svg` focusable. It seems like Chrome considers an `svg` focusable if it has a `focus` handler which is allowed by spec:

> [...] and may allow focus to reach elements which have been assigned listeners for mouse, pointer, or focus events.

-- https://svgwg.org/svg2-draft/single-page.html#interact-Focus

This is an expected change in React 17 where event handlers are now attached to the root element (the `svg` here) instead of the document. It seems like `focusable="false"` does not prevent that from happening (seems like a bug to me). The only workaround I'm aware of right now is not using `svg` as a root element.

@gaearon Should we add a warning to the docs (I don't expect that to be read) or even a runtime warning if `svg` is a root element? We could skip the warning if `focusable="true"` is set on the root `svg`.

**Comment by Ayc0** [comment]
> is not using svg as a root element

I cannot change this in the codebase I'm working on 😅 

As a workaround, I added `outline: none` to the SVG / SVG node used as the root (it doesn't avoid the element being focusable but it hides the outline)

**Comment by Ayc0** [comment]
I did some other researches and setting both `focusable="false"` and `tabindex="-1"` seems to fix the fact that the element is focusable, but it doesn't remove the outline on click: https://if7q2.csb.app/

**Comment by eps1lon** [comment]
> I did some other researches and setting both focusable="false" and tabindex="-1" seems to fix the fact that the element is focusable,

`tabIndex="-1"` removes it from the tab order. It's still focusable though which is why you see the outline:
![Screenshot from 2021-07-23 10-18-33](https://user-images.githubusercontent.com/12292047/126755341-5c1a77a4-4f44-4e83-9864-b0cd57fd376d.png)

(Notice that `document.activeElement` in the console points to `svg#root`)

**Comment by Ayc0** [comment]
Indeed

**Comment by Ayc0** [comment]
Bump
