### ISSUE TITLE
DevTools: Scheduling Profiler: Better error message when no marks

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#22106]
The scheduling profiler currently shows "unsupported version" message if you import a performance trace with no marks.

It incorrectly assumes the lack of an explicit version mark indicates an earlier version of the data which didn't include marks, but in the event that there are _no marks at all_ we should infer that a production version of React DOM was being used instead and show a different error.

**Comment by byronluk** [comment]
Hi @bvaughn, mind if I pick this up?

**Comment by bvaughn** [comment]
Sure thing, @byronluk.

**Comment by byronluk** [comment]
Thanks!

Regarding your comment-
> but in the event that there are no marks at all

do you mean no marks that were generated by React? (just want to double check since I'm not too familiar with the devtools profiling 😅).

If so, I'm thinking the best way to check for this is to see if any React-related profiling data was generated in `profilerData`-
https://github.com/facebook/react/blob/f51579fffeac46a783f765786f5287644b1fa7eb/packages/react-devtools-scheduling-profiler/src/import-worker/preprocessData.js#L853

Specifically checking if any these fields were populated - `batchUIDToMeasuresMap`, `componentMeasures`, `schedulingEvents`, `suspenseEvents`.

Does this sound like a sound approach?

**Comment by bvaughn** [comment]
> do you mean no marks that were generated by React? 

Yes. So a browser performance trace was recorded from a site running the React production bundle (no profiling features enabled) or even a website that wasn't using React at all.

**Comment by byronluk** [comment]
Thanks for the guidance!

Since `laneToReactMeasureMap` gets pre-initialized with values here:

https://github.com/facebook/react/blob/045156ca6c13cc421f7991a55cdfeb9c1bca6762/packages/react-devtools-scheduling-profiler/src/import-worker/preprocessData.js#L848-L851

I ended up checking `batchUIDToMeasuresMap` instead. It was simpler this way and I figured it has the same effect since both maps end up being populated under the same scenario in the `markWorkStarted` function:

https://github.com/facebook/react/blob/045156ca6c13cc421f7991a55cdfeb9c1bca6762/packages/react-devtools-scheduling-profiler/src/import-worker/preprocessData.js#L154-L167

Hopefully that's okay. I submitted a PR here: https://github.com/facebook/react/pull/22157

**Comment by bvaughn** [comment]
> Since `laneToReactMeasureMap` gets pre-initialized with values here...I ended up checking `batchUIDToMeasuresMap` instead.

Good call
