### ISSUE TITLE
React 18  - object-assign must be removed dependency

### ISSUE THREAD

**Issue by meftunca** [facebook/react#22111]
object-assign must be removed dependency

**Comment by eps1lon** [comment]
Thanks for the feedback.

Could you clarify why the dependency must be removed? It has been a dependency since [15.x](https://www.npmjs.com/package/react/v/15.0.0).

**Comment by bvaughn** [comment]
As @eps1lon mentions, `object-assign` has been a `react-dom` dependency since 15.4.0 (released in November of 2016). It's a [very small](https://unpkg.com/object-assign@4.1.1/index.js) [ponyfill](https://ponyfoo.com/articles/polyfills-or-ponyfills) for [browsers that don't yet support `Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#browser_compatibility) (aka IE). When React drops out-of-the-box support for IE 11, this polyfill can be removed. (Not sure when that will be yet.)

**Comment by meftunca** [comment]
Thanks for the feedback.  The reason for removing the plugin is that now object.assign support is supported in all browsers so it doesn't need an additional plugin

**Comment by bvaughn** [comment]
As mentioned in my comment above (https://github.com/facebook/react/issues/22111#issuecomment-900343677) it's not supported by all browsers React supports (IE 11, Hermes) and so it's still around. We will likely remove this as part of the version 19 release, but probably not before then because we want to minimize unnecessary breaking changes.

I'm going to close this issue since there's no action for now. 😄

**Comment by Pranav127** [comment]
bug issuse
