### ISSUE TITLE
DevTools: Better Bundle Names for Dynamically Imported Modules

### ISSUE THREAD

**Issue by lunaruan** [facebook/react#22115]
In the DevTools extension, webpack currently uses an automatically assigned ID as the chunk name for dynamically imported modules (ie. `parseHookNames` and associated code will get bundled into `6.js`).

We've tried adding `chunkFilename: '[name].js'` to `output` in `webpack.config.js` and  magic comments (ie.`/* webpackChunkName: "parseHookNames" */`) to the dynamic import to fix, but neither works.

**Comment by aditianshu** [comment]
hey @bvaughn would like to work on this issue.

**Comment by bvaughn** [comment]
@aditianshu This issue is all yours! 😄

I've added the **"good first issue (taken)"** label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by aditianshu** [comment]
Hey @bvaughn 
I've read up on this issue and seems like a recurring problem with Webpack. Some people have solved it in by removing the plugin "dynamic-import-webpack" from Babel and the magic comments work after that.

**Comment by akgupta0777** [comment]
I think this is fixed already and no longer needed.

**Comment by bvaughn** [comment]
> I think this is fixed already and no longer needed.

Why do you think that?

**Comment by akgupta0777** [comment]
Because I build the src for devtools extension and there are already names for bundles dynamically according to [name].js in build directory.

Maybe I am understanding the issue wrong.do You want to rename chunks file according to bundle name ? In issue title it says better bundle names.

Maybe I am confused.

Another thing about webpack chunk names that I know is they are named after chunkIDs generated by webpack. You can surely change the name of chunks but only for dynamically imported modules using magic comments.

If you help me a little bit I can fix this issue.

**Comment by bvaughn** [comment]
```sh
$ rm -rf chrome/build
$ yarn build:chrome
$ ls -l chrome/build/unpacked/build
  45105038a85b36076aef.worker.js
  6.chunk.js
  7.chunk.js
  background.js
  contentScript.js
  f40dbc4e6418466df4e5.worker.js
  injectGlobalHook.js
  main.js
  panel.js
  react_devtools_backend.js
  renderer.js
```

The `6.chunk` and `7.chunk` files are what this issue is referring to. The `45105038a85b36076aef.worker.js` and `f40dbc4e6418466df4e5.worker.js` files aren't good either.

**Comment by akgupta0777** [comment]
Can I try this issue ?

**Comment by akgupta0777** [comment]
Its 2 weeks now, I will wait a little more.

**Comment by akgupta0777** [comment]
@aditianshu still working on it ?. Can I try this.

**Comment by aditianshu** [comment]
Hey @akgupta0777, 
Although I've researched a bit on this issue and tried to come up with a solution, I have some interviews and OAs so I would be take more time in picking it up and closing it. You can go ahead and try it out..
@bvaughn please assign it to him as there would be a delay with me

**Comment by akgupta0777** [comment]
@aditianshu Thanks for replying. I got filled with enthusiasm to solve this issue. By the way, Good luck for your interviews and OAs.
