### ISSUE TITLE
[DevTools Bug]:  Context & useContext，some child component don‘t rerender，but highlight！

### ISSUE THREAD

**Issue by bigbigDreamer** [facebook/react#22135]
### Website or app

https://codesandbox.io/embed/confident-kare-lzzko?fontsize=14&hidenavigation=1&theme=dark

### Repro steps

# Bug Desc: Context & useContext，some child component don‘t rerender，but highlight！

1. Open React Devtools
2. 
![image](https://user-images.githubusercontent.com/39019913/130096406-39d5e903-b08c-48a0-ae3d-0cbd72ddb83d.png)
open highlight
3. click app button and watch highlight
![image](https://user-images.githubusercontent.com/39019913/130099128-c10bcd9c-e06d-473d-a4a5-1c5935b1a215.png)

4. The child1 component don’t useContext and don‘t rerender，but highlight，when child2 update context.
![image](https://user-images.githubusercontent.com/39019913/130099202-cdf3c85d-8e26-47de-af9b-6175a39cabbd.png)

### How often does this bug happen?

Every time

**Comment by lunaruan** [comment]
Hey! Thanks for reporting!

 What you're seeing is not actually a bug. In your app, `AppProvider` rerenders in response to count updating as a result of the button click, and it is the parent of `child1` and `child2`, which is why you are seeing both highlighted. Closing this issue but feel free to reopen if that doesn't answer your question!

**Comment by bigbigDreamer** [comment]
> Hey! Thanks for reporting!
> 
> What you're seeing is not actually a bug. In your app, `AppProvider` rerenders in response to count updating as a result of the button click, and it is the parent of `child1` and `child2`, which is why you are seeing both highlighted. Closing this issue but feel free to reopen if that doesn't answer your question!

no！no！no！It‘s really a bug， @sunny @henrik @wvl @lunaruan 
![image](https://user-images.githubusercontent.com/39019913/130149196-3e7442b2-936b-4b73-88ac-a76e8c924bf1.png)

I understand how React Context works. You can watch the changes to the component variable A, the child component A is really not updated, and render. For ContextProvider, props. The same as ever! Your explanation does not convince me.

Please See demo：https://codesandbox.io/embed/confident-kare-lzzko?fontsize=14&hidenavigation=1&theme=dark @

**Comment by bigbigDreamer** [comment]
@bvaughn Can you take a look or explain

**Comment by bvaughn** [comment]
> no！no！no！It‘s really a bug

> The same as ever! Your explanation does not convince me.

Please be respectful. Luna's explanation was correct.

DevTools highlights which parts of the page that re-rendered. If only one of he child components re-rendered, only that component would be highlighted. Since the _parent component_ re-rendered, the DOM it (and its descendants) output gets highlighted. (This _includes_ the child components.)

The same is true if you select the parent component in DevTools- it highlights the DOM produced by that component (and its descendants).

**Comment by bigbigDreamer** [comment]
> > no！no！no！It‘s really a bug
> 
> > The same as ever! Your explanation does not convince me.
> 
> Please be respectful. Luna's explanation was correct.
> 
> DevTools highlights which parts of the page that re-rendered. If only one of he child components re-rendered, only that component would be highlighted. Since the _parent component_ re-rendered, the DOM it (and its descendants) output gets highlighted. (This _includes_ the child components.)
> 
> The same is true if you select the parent component in DevTools- it highlights the DOM produced by that component (and its descendants).

I'm sorry. I was a little overreacting,

But I'm using context to wrap it, and the context rule skips updates, so for Child A, there's no rendering, even if the parent is updated. Can you take a minute to look at my source code on the Code Sandbox

**Comment by bvaughn** [comment]
I've looked at your source code. I think you're misunderstanding my explanation though.

Select the `ContextProvider` component in DevTools. You will see this:
<img width="811" alt="Screen Shot 2021-08-19 at 3 11 49 PM" src="https://user-images.githubusercontent.com/29597/130151082-fb176e32-2267-4ba0-b27b-2596192eaf2f.png">

Notice that DOM elements created by both `Child1` and `Child2` are highlighted? That's because `ContextProvider` renders `children` (which contains `Child1` and `Child2`). The "highlight updates" feature works the same way.

I understand why this might be confusing at first, but if DevTools didn't highlight DOM rendered by children, there would be nothing to highlight in many cases.

**Comment by bigbigDreamer** [comment]
> 我看过你的源代码。我认为你误解了我的解释。
> 
> `ContextProvider`在 DevTools 中选择组件。你会看到这个：
> <img alt="屏幕截图 2021-08-19 at 3 11 49 PM" width="811" src="https://user-images.githubusercontent.com/29597/130151082-fb176e32-2267-4ba0-b27b-2596192eaf2f.png">
> 
> 请注意，DOM元素都通过创建`Child1`和`Child2`突出？那是因为`ContextProvider`渲染`children`（其中包含`Child1`和`Child2`）。“突出显示更新”功能的工作方式相同。
> 
> 我理解为什么一开始这可能会令人困惑，但是如果 DevTools 没有突出显示由儿童渲染的 DOM，那么在许多情况下就没有什么可突出显示的了。

I probably understand your explanation and thank you for your answer, but this behavior is really confusing because it does seem weird (or confusing) to be doing some recent performance tuning to determine if a component is being rerendered based on highlighting.

**Comment by bigbigDreamer** [comment]
> I've looked at your source code. I think you're misunderstanding my explanation though.
> 
> Select the `ContextProvider` component in DevTools. You will see this:
> <img alt="Screen Shot 2021-08-19 at 3 11 49 PM" width="811" src="https://user-images.githubusercontent.com/29597/130151082-fb176e32-2267-4ba0-b27b-2596192eaf2f.png">
> 
> Notice that DOM elements created by both `Child1` and `Child2` are highlighted? That's because `ContextProvider` renders `children` (which contains `Child1` and `Child2`). The "highlight updates" feature works the same way.
> 
> I understand why this might be confusing at first, but if DevTools didn't highlight DOM rendered by children, there would be nothing to highlight in many cases.

I probably understand your explanation and thank you for your answer, but this behavior is really confusing because it does seem weird (or confusing) to be doing some recent performance tuning to determine if a component is being rerendered based on highlighting.

**Comment by bvaughn** [comment]
To my knowledge, this is how the feature has worked since it was added originally. So it's not a _bug_, although I understand your POV about it being confusing.

I'd be happy to look at a PR that changes this behavior. Would you be interested in working on one?

We have a pretty good getting started guide:
https://github.com/facebook/react/blob/main/packages/react-devtools/CONTRIBUTING.md

**Comment by bigbigDreamer** [comment]
> To my knowledge, this is how the feature has worked since it was added originally. So it's not a _bug_, although I understand your POV about it being confusing.
> 
> I'd be happy to look at a PR that changes this behavior. Would you be interested in working on one?
> 
> We have a pretty good getting started guide:
> https://github.com/facebook/react/blob/main/packages/react-devtools/CONTRIBUTING.md

I guess I can give it a try.

Although originally designed this way, the value of the tool is really confusing for the way it works, because the presentation and the reality are really different, which inevitably leads to some misdirection

**Comment by bvaughn** [comment]
One thing to keep in mind is that even components that don't _directly_ render DOM elements _can be slow_. If we didn't show any highlight for such a component, then it might be confusing in the opposite way. (An app rendered but no highlight was shown.)

**Comment by bigbigDreamer** [comment]
> One thing to keep in mind is that even components that don't _directly_ render DOM elements _can be slow_. If we didn't show any highlight for such a component, then it might be confusing in the opposite way. (An app rendered but no highlight was shown.)

Yes, I agree with your point of view, I think this kind of scene of mine should belong to the minority, and it is correct to meet the needs of most scenes. This problem should be defined as a need for optimization, and it really does not belong to the category of bugs.

**Comment by bigbigDreamer** [comment]
> > no！no！no！It‘s really a bug
> 
> > The same as ever! Your explanation does not convince me.
> 
> Please be respectful. Luna's explanation was correct.
> 
> DevTools highlights which parts of the page that re-rendered. If only one of he child components re-rendered, only that component would be highlighted. Since the _parent component_ re-rendered, the DOM it (and its descendants) output gets highlighted. (This _includes_ the child components.)
> 
> The same is true if you select the parent component in DevTools- it highlights the DOM produced by that component (and its descendants).

I need to explain that "as always" here refers to component updates, not your answer. My English level is indeed a bit poor, please don't misunderstand, I don't fully understand Luna's answer.

Even so, it is necessary to say sorry to Luna. @lunaruan 

At the same time, I am very grateful to both of you for answering in your busy schedule.

**Comment by bvaughn** [comment]
🙇🏼

**Comment by a896853205** [comment]
Hello, I have a similar confuse.
I think that the component highlighting is equivalent to the component's render function being called.
But the above example is not the case.
Then I would like to ask if my understanding is wrong, or the design should be like this.
