### ISSUE TITLE
Bug:  The onChange synthesis event is not propagation when the child node is added through dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by iwfan** [facebook/react#22287]
The onChange synthesis event is not propagation when the child node is added through dangerouslySetInnerHTML.

React version: v17.0.2

Link to code example:

https://codesandbox.io/s/restless-rain-otyzx?file=/src/App.js

## Steps To Reproduce

1. click the radio input element
2. see logging in console

## The current behavior
1. ✅  onClick event is propagation
2. ❌ onChange event is not propagation

## The expected behavior

1. onClick event is propagation
2. onChange event is propagation

**Comment by cyntler** [comment]
@iwfan You added onChange event listener (`onChange={handleSyntheticChangeEvent}`) to the `<div>` element.
Read more about `change` event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event.

> The change event is fired for `<input>`, `<select>`, and `<textarea>`.

I don't think it works for divs.

**Comment by iwfan** [comment]
Hi @cyntler, I know that change event are triggered for `<input>`, `<select>`, and `<textarea>`,  but the change event can be propagated through bubbles. 

```jsx
<div 
  onChange={handleSyntheticChangeEvent} // It's not working!
```

As you can see, if I add a change event on react element, the change event can no longer bubble.

```jsx
useEffect(() => {
  containerRef.current.addEventListener("change", handleNativeChangeEvent);
}, [containerRef]);
```
But if I add the change event through native javascript way(addEventListener), the change event can bubble normally.

And why does the change composition event not bubble when the child are added through `dangerouslySetInnerHTML`?

**Comment by anc95** [comment]
I have looked into react source code and found out the reason.

Here is the key code https://github.com/facebook/react/blob/9c8161ba81220143e7f87bd901697e46b14d8968/packages/react-dom/src/events/plugins/ChangeEventPlugin.js#L293-L305

The overall logic is like this.
1. when the click event is triggered, the nearest React Node (targetNode) to the node that triggered the event is found
2. determine if the targetNode is an `input` `radio` or`checkbox` element, and if so, compare the values before and after to see if they have changed, and if so, derive the onChange event

But if the element that triggers the click event is rendered by dangerouslySetInnerHTML element, as in the example above, the latest React Node node `div` will be found, then the `shouldUseClickEvent(targetNode)` returns false, making it impossible to synthesize the onChange event.

@gaearon Is this a bug or is it intentional, if it is a bug I'm happy to raise a PR to fix it
