### ISSUE TITLE
RFC: Parsing hook names should display better error messages

### ISSUE THREAD

**Issue by jstejada** [facebook/react#22339]
## Proposal

When attempting to extract hook names for an inspected element, if source maps aren't available or they fail to load for some reason, the UI doesn't show any indication of that happening, and instead silently "succeeds", but without showing any actual hook names.

When this happens, we should probably handle it differently:

- If we can detect that the source code wasn't actually transformed at build time, continue attempting to extract hook names from the original source code.
- If we can detect that the source code /was/ transformed at build time, but we don't have source maps available, show an error to the user

**Comment by bvaughn** [comment]
> When attempting to extract hook names for an inspected element, if source maps aren't available or they fail to load for some reason, the UI doesn't show any indication of that happening, and instead silently "succeeds", but without showing any actual hook names.

My understanding of what happens/should happen (although maybe we are missing some edge cases) is this:

1. If a source file or source map fails to load, the Suspense cache should resolve a `RejectedRecord` and return `null` - which should cause an error tooltip to be displayed:
![Screen Shot 2021-09-17 at 9 31 25 AM](https://user-images.githubusercontent.com/29597/133790819-5cf3ef09-4a47-4414-b4dc-8bbb7739993e.png)

2. If source and source maps load and we parse them and still can't infer names for hooks, for some reason, the cache will return an array of `null` entries, which will look like this:
![Screen Shot 2021-09-17 at 9 32 57 AM](https://user-images.githubusercontent.com/29597/133791036-9c9c0773-ee91-4ad0-bb31-87e6a642114d.png)

This second case might be confusing.

> If we can detect that the source code wasn't actually transformed at build time, continue attempting to extract hook names from the original source code.

We should already be doing this. We have a lot of tests that verify this (`// original source (uncompiled)`)

> If we can detect that the source code /was/ transformed at build time, but we don't have source maps available, show an error to the user

This would be an improvement over the generic error we're currently showing. I've thought a little about how we might handle this. Maybe return a string (error message) rather than `null` for the `RejectedRecord` case?

**Comment by Hyperion101010** [comment]
Hi, I am a young FS developer.  I would like to work on this issue.
