### ISSUE TITLE
Bug: Wrong warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

### ISSUE THREAD

**Issue by amorphousDj** [facebook/react#22343]
React version: 17.0.2

## Steps To Reproduce

1. click show button
2. click close button

Link to code example:
https://codesandbox.io/s/nodewarning-9fu7n

## The current behavior
The console will print “Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.”
![image](https://user-images.githubusercontent.com/31609229/133753965-7e3c198a-2b75-44c2-820b-42e839e7f163.png)

## The expected behavior
The console will not print this warning.

I studied the test case for this warning. The Dialog component was rendered and unmounted by the same ReactDOM. This is a false warning.

**Comment by Noah670** [comment]
Have you tried updating React?

**Comment by akgupta0777** [comment]
I need more info
What does **another copy of react** mean ?

**Comment by eps1lon** [comment]
I think the problem is that `ReactDOM.render` handles the `container` but then your `Dialog` manually inserts element into this `container` via `appendChild`.  I don't think that's generally supported.

And once you call `ReactDOM.unmountComponentAtNode(container)` React tries to unmount something that was  was rendered via `ReactDOM.createPortal`. So it may just be a misleading warning since it's not another copy of React but rather a node that can't be unmounted via `unmountComponentAtNode`.

What's odd is that your specific example doesn't even need `createPortal`. `Dialog` could just as well be implemented as 
```js
  render() {
    return (
      <div>
        <div>
          dialog
          <button onClick={closeDialog}>close</button>
        </div>
      </div>
    );
  } 
```
Your implementation creates the outer `div` with DOM API + `createPortal`.

The warning is issued because we call `getInstanceFromNode(container.firstChild)` (remember that `container.firstChild` was the target of `createPortal`).  `getInstanceFromNode` returns `null` for nodes that were the target of `createPortal`. That's why we assume it's a different copy of React. But it's not really a different copy but a node that we didn't expect there.

What we could do in `unmountComponentAtNode` is to check if that element is handled by this copy of React by checking all of the `internal*Key` properties:

```diff
-const renderedByDifferentReact = rootEl && !getInstanceFromNode(rootEl);
+const isUnmountable = rootEl && !getInstanceFromNode(rootEl);
+const renderedByThisReact = rootEl && (
+  (node: any)[internalInstanceKey] ||
+  (node: any)[internalContainerInstanceKey] ||
+  (node: any)[internalEventHandlersKey] ||
+  (node: any)[internalEventHandlerListenersKey] ||
+  (node: any)[internalEventHandlesSetKey]
+)
```
and then adjust the warning. But this is a lot of work for this specific case.

**Comment by eps1lon** [comment]
To further elaborate: The same warning appears with

```js
const container = document.createElement("div");
document.body.appendChild(container);

class Dialog extends React.Component {
  constructor(props) {
    super(props);
    const dom = document.createElement("div");
    this.dom = dom;
  }
  componentDidMount() {
    container.appendChild(this.dom);
  }

  componentWillUnmount() {
    container.removeChild(this.dom);
  }
  render() {
    return null
  }
}

ReactDOM.render(<Dialog />, container);
ReactDOM.unmountComponentAtNode(container);
```

I don't think it's worth it to explain every single possible scenario if almost all issues are caused by a different copy of React.
