### ISSUE TITLE
[DevTools Bug]: Emoji as visual helper produce strange symbole

### ISSUE THREAD

**Issue by djmisterjon** [facebook/react#22422]
### Website or app

https://codesandbox.io/s/react-playground-forked-j4niq

### Repro steps

Emoji seem supported but produce strange symbole

![image](https://user-images.githubusercontent.com/24865815/133793744-55a55582-90ad-425f-8a40-4c061a3c1d80.png)

To test emoji on Window Os, use `[win]+[.]` 🟩

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment]
This is interesting!

DevTools sends component names as encoded characters, [because the components tree is just a typed numeric array](https://github.com/facebook/react/blob/main/packages/react-devtools/OVERVIEW.md#serializing-the-tree) for performance reasons.

So a component name gets encoded like so:
```js
const encoded = new Array(string.length);
for (let i = 0; i < string.length; i++) {
  encoded[i] = string.codePointAt(i);
}
```

I think "🟩" is a [multi-byte character](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/unicode-and-multibyte-character-set-mbcs-support?view=msvc-160) because it has a length of 2 (code points `[129001, 57321]`). When we decode those points on the other side though, the resulting string is `"🟩\uDFE9"`.

Our string table needs to be updated to handle multibyte characters? Maybe we could use something like [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) for this? I'm not very experienced/familiar with this area.

**Comment by bvaughn** [comment]
> Maybe we could use something like [`TextEncoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) and [`TextDecoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) for this? I wonder what the performance impact of this would be?

Yes, this does work:
<img width="721" alt="Screen Shot 2021-09-24 at 4 56 24 PM" src="https://user-images.githubusercontent.com/29597/134738813-1f8b9929-4df2-4497-b80b-7039b8a64210.png">

Not sure what the performance impact is though.

**Comment by djmisterjon** [comment]
Is performance in a development environment are so important?, are we talking about `micro optimization`  for this specific case ??
Am also not familiar with this, but i let you take decision :)

**Comment by bvaughn** [comment]
Yes. This code is a hot path and very performance sensitive. I don't expect this would be a deal breaker though. :)

**Comment by djmisterjon** [comment]
ok, i can live with that, it's not that big issue for me. :) feel free to close if you think is there not more solution.

**Comment by bvaughn** [comment]
Based on a few benchmarks, the `TextEncoder`/`TextDecoder` approach _is slower_ (~85% slower), but it's unclear how much of an overall impact this will have on actual DevTools performance (as we don't encode long strings often).

* https://jsbench.me/boktzulhew/1
* https://jsben.ch/5tnt1

We could also break the benchmarks down further to compare how much the slowness is from _encoding_ vs _decoding_. We cache names when _encoding_ so we might be able to limit the impact in that case. If it's overhead from e.g. creating new typed arrays when decoding (or decoding itself) then we may have less flexibility.

**Comment by djmisterjon** [comment]
ho ! 85% is really big!
it would be a shame to add such a load for so little. 

A other suggest can be maybe add a options? 

 if people have good machine they can check this ! and bad machine, unchek ? 
![image](https://user-images.githubusercontent.com/24865815/134788985-8ddc9d2e-5d6b-49c8-9975-386eb89c23ac.png)

**Comment by bvaughn** [comment]
No worries. Good news is that I've found an alternate approach that's actually _slightly faster_ (based on benchmarking at least) so we'll move forward with it.
