### ISSUE TITLE
Bug: React Component is getting rendered twice if it has error

### ISSUE THREAD

**Issue by nishantatgit** [facebook/react#22487]
React Component is getting rendered twice if it has error

React version: 17.0.2

## Steps To Reproduce

1. Navigate to https://codesandbox.io/s/long-night-kn9zj?file=/src/App.js 
2. Click on increase counter button 6 times. Clicking each time will increase the count value by 1. When the count is greater than 5 component will throw error.
3. Check the console for log. count 6 is being printed twice, indicating that the component is getting rendered twice.

## The current behavior

When the button is clicked 6th time the compoenent is throwing error and getting rerndered twice.

## The expected behavior

It should get rendered only once when the button is clicked 6th time (when it throws error).

**Comment by bvaughn** [comment]
This is intentional behavior on React's part. If a component throws while rendering, React will try it once more (in case the error was a transient issue). If it works the second time, React will resume rendering where it left off. If it throws again, React will fallback to the nearest [error boundary](https://reactjs.org/docs/error-boundaries.html#gatsby-focus-wrapper).

Because rendering should [never have side effects](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects), the retry render should not cause any problems (other than potentially confusing someone like yourself who happens to notice it).
