### ISSUE TITLE
Bug: rules-of-hooks violation not caught by eslint plugin

### ISSUE THREAD

**Issue by pke** [facebook/react#22520]
Given the following code:

```ts
const createHandler = () => (event) => {
  const { t } = useTranslation()

  Alert.alert(t("title"), t("message"))
}

function MyComponent() {
  return <Button onPress={createHandler()}/>
}
```

the `rules-of-hooks` linter rule is not triggered for the `createHandler` as it should.
The linter rule should detect its not a react component, since it does not return any `ReactElement` or `null`.

**Comment by dcheng1290** [comment]
@pke did you resolve this issue by any chance?

**Comment by pke** [comment]
No

**Comment by eps1lon** [comment]
This may have been an intentional case that's missed so existing code isn't falsely flagged. Assuming that any `use*` function is a hook, the plugin would trigger some false-positives in the ecosystem. So the plugin is probably assuming here that `useTranslate` is not a hook because it's neither called in another hook nor directly during render. Tracking `createHandler` usage would be really hard to accomplish.

Consider e.g. `useFakeTimers` in `sinon`. If this would be considered a hook by the plugin, people would probably disable it due to the noise it creates.

Maybe @gaearon can confirm this is intentional.

Does the plugin flag usage of built-in hooks inside `createHandler`?

**Comment by dcheng1290** [comment]
Makes sense regarding existing code getting falsely flagged. I was wondering if the plugin currently has a rule for us to enable in order to capture this case. Thanks!

**Comment by eduardodallmann** [comment]
I simply import like this: `import { useTranslation as translation } from 'react-i18next';`

**Comment by pke** [comment]
How is that helping solving the bug shown in this issue?

**Comment by eduardodallmann** [comment]
Sorry, I understood the problem to be an eslint warning in the "react-hooks/rules-of-hooks" rule for using a `use*` hook outside of a react component. Then I tricked eslint by renaming the import. My mistake.
