### ISSUE TITLE
[ESLint]: react-hooks/exhaustive-deps feedback/bug?

### ISSUE THREAD

**Issue by jaymzh** [facebook/react#22581]
First, let me note I did read https://github.com/facebook/react/issues/14920 and several of the linked issues there. I ... didn't see a case that I could tell mapped to mine, but I apologize in advance if I missed something.

I have a case where if I add what eslint wants me to add, it'll break the `useEffect`.

I have a Component, `StatusBox`. All it does is pop up a little overlay to tell you that, for example, something was submitted. If there's a timeout, after a timeout, it fades away, otherwise it stays until someone clicks on it. It's pretty simple:

```javascript
const StatusBox = ({content, setContent, timeout, type}) => {
    const div = useRef(null)
    const [opacity, setOpacity] = useState(0)

    const handleClick = e => {
        e.preventDefault()
        clear()
    }

    const clear = (e) => {
        console.debug("StatusBox: Clearing opacity, currently:", opacity)
        setOpacity(0)
        /*
         * If we remove the class now, it'll cut short the fade-out.
         * If we remove the text now, it'll disappear abruptly before the
         * fade-out.
         *
         * HOWEVER, if we DON'T clear the text, then the overlay is still
         * there, blocking the page (in the case of a bigger status), so
         * we need to clear it after the transition. So get the timing of
         * that, and add 50ms just to be safe. And while we're at it,
         * we can clear the classes...
         */
        let t = window.getComputedStyle(div.current).transitionDuration
        console.debug("StatusBox: computed transition", t)
        // that's something like 0.4s, we need to drop the 's', convert
        // to a number, and the turn into milliseconds. Trying to use a
        // string in a math equation causes JS to cast it for you
        t = t.replace('s', '') * 1000
        t += 50
        console.debug("StatusBox: Setting timeout to clear type/content in", t)
        innerTimeout = window.setTimeout(() => {
            setContent(null)
        }, t)
    }

    useEffect(() => {
        console.debug(
            `StatusBox: in useEffect, timeout ${timeout}`
        )
        // If we're setting content to null, we've already set the opacity
        // so we can return null to not re-render
        if (content === null) {
            return null
        }

        // otherwise, we need to appear!
        console.debug("StatusBox: setting opacity to 1")
        setOpacity(1)

        // if we have no timeout, we're done
        if (timeout === null) {
            return
        }

        // otherwise, set the timeout
        console.debug('StatusBox: setting timeout for', timeout)
        // nuke any timeout already there
        if (innerTimeout) {
            console.debug("clearing inner:", innerTimeout)
            window.clearTimeout(innerTimeout)
        }
        if (outerTimeout) {
            console.debug("clearing outer:", innerTimeout)
            window.clearTimeout(outerTimeout)
        }
        outerTimeout = window.setTimeout(clear, timeout)
    }, [content])

    return <div
        className={type}
        ref={div}
        id='status'
        style={{opacity:opacity}}
        onClick={handleClick}
    >{content}</div>
}
```
And a tiny bit of CSS

```css
#status {
    z-index: 99;
    transition: opacity 0.4s linear;
    opacity: 0;
}
```

The usage of this is simple. You throw the box somewhere, it doesn't matter...

```javascript
const [statusText, setStatusText] = useState(null)
...
<StatusBox content={statusText} setContent={setStatusText} timeout={3000} type='lowstatus' />
```
In my case I throw a bit of style on this specific statusbox (lowstatus):

```css
.lowstatus {
    position: fixed;
    bottom: 15px;
    left: 50%;
    margin-left: -500px;
    width: 1000px;
    height: 30px;
    background-color: green;
    border: 1px solid white;
    border-radius: 8px;
    box-sizing: border-box;
    padding: 6px;
    text-align: center;
}
```

Then when you want to pop up the status you just `setStatusText("It worked!")`.

We can then pass `setStatusText` around, setting it will do the right thing. (`type` simply gives an `id` so that we can style it, that's about it.)

The problem is `react-hooks/exhaustive-deps` wants `clear` to be in the deps. It'd be common to put `clear()` inside of the effect to bypass this, but we also call it from the click handler (`handleClick()`) so we want it at the top-level of the component. It is declared `const`. I had *thought* from this text in the aforementioned bug:

```
First of all, if it's constant and hoisted to top level scope then the linter won't complain. But that doesn't help with things coming from props or context.
```

... that `clear` wouldn't trigger this rule, but in fact it does. I *think* that's a bug?

I'm also open to "there's a better way to do all this" - I'm quite new to React and still fairly new to JS too.

(Relatedly, it wants me to add `timeout`. Doing so breaks nothing (especially in my case, it's static), but if it were ever to be dynamic, I *think* it means that when someone sets a timeout and then sets the content, as we expect them to, it can trigger a double-render? Not sure, maybe it'll collapse those as long as both are done within a single rendering if the setting component? I'm still quite new to React.)

**Comment by keanemind** [comment]
My understanding is that the quote "constant and hoisted to top level scope" is referring to the very top level of your file (outside of your function component), not the top level of your component. So I don't think it's a bug that the rule is popping up here.

Regarding the `clear` dependency, yes, I believe you may run into trouble if you add `clear` to the dependencies array without making any other changes, because your effect would run more frequently than you want; you are creating a new `clear` function during every render and so your effect would always run again. You can deal with this by applying `useCallback`, and ESLint will tell you to put `setContent` in the dependencies array of that `useCallback`.

The ESlint rule is trying to help you with a possible bug in your component's current implementation: if the `setContent` prop changes _after you set `outerTimeout` but before the timeout triggers_, the `clear` function that will run as a result of that timeout will be stale; its closure captured the old `setContent` function, so it will use that old `setContent` in its final statement where you set another timeout. 

To fix the stale `clear` problem, you can put `clear` into the dependencies array and then have your effect clean up by cancelling the outertimeout. Now, when `clear` changes, the timeout with the stale `clear` will be cancelled, and then the effect will run again. And by using `useCallback` on `clear`, you can have `clear` change only when `setContent` changes.

Now your problem would be that when the effect re-runs with a fresh `clear`, the timeout will be reset even if the old timeout that got cancelled was halfway through its lifetime. You can deal with that however you want, but I just wanted to point it out.

Any of the props can change at any time; even in the middle of your transition. That's where the complexity comes from.

By the way, is there a reason you don't unmount the overlay after the animation is over, rather than setting the content to null? That part is a little odd to me.

**Comment by eps1lon** [comment]
This seems to have been properly answered above.

You might be interested in [RFC: useEvent](https://github.com/reactjs/rfcs/pull/220) as well which could help with this issue.

**Comment by jaymzh** [comment]
Hi, sorry for the delayed response here, I missed the initial reply.

Thanks @keanemind  for the detailed response. I ... don't think I followed it very well though.

> Regarding the clear dependency, yes, I believe you may run into trouble if you add clear to the dependencies array without making any other changes, because your effect would run more frequently than you want; you are creating a new clear function during every render and so your effect would always run again. You can deal with this by applying useCallback, and ESLint will tell you to put setContent in the dependencies array of that useCallback.

OK, so turn `clear` into a `useCallback`. I think I get that.

When I do that, it wants both `opacity` and `setContent` in the deps list of the `useCallback`, and then `content`, `clear`, and `timeout`, in the deps list of `useEffect`. That leads to an incinite loop in the clearing of the box and it never clears.

Which I think is what you were trying to address here:

> To fix the stale clear problem, you can put clear into the dependencies array and then have your effect clean up by cancelling the outerTimeout. Now, when clear changes, the timeout with the stale clear will be cancelled, and then the effect will run again. And by using useCallback on clear, you can have clear change only when setContent changes.

But I don't follow, I... do clear `outerTimeout` in the `useEffect` already. I tried moving the clear to the very top of the `useEffect` in case you meant I might not clear it in some cases, but that didn't fix it.

> By the way, is there a reason you don't unmount the overlay after the animation is over, rather than setting the content to null? That part is a little odd to me.

I briefly used class components when I was learning React, but quickly found that the recommendation was to use function components, and in function components I ... don't know how to unmount things.

But also, if I unmounted it, wouldn't that `<StatusBox>` not be there the next time `setContent` was called?

And thanks @eps1lon, yeah `useEvent` seems like it would make this all simpler, when it lands.
