### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by cikay** [facebook/react#22655]
I am curious why you do not define the components like the following instead. You have to invoke the component and its returned value for the first time and to re-render the only thing that needs to be done is invoke the returned value which is a function as well.

## The expected definitation

```js

function Component(){
  const [count, setCount] = useState(0)
  //other states
  
  return (props) => {
    const incerement = () =>{
      setState((oldState) => oldState + 1)
    }
    return (
      <div>{count}</div>
      <button onClick={increment}>Increment</button>
    )
  }

}

```

**Comment by alk-mandrianarijaona** [comment]
Hi @cikay, did you encounter any particular issue on component render that made you think of this solution? I am curious to understand the root issue you want to solve here

**Comment by bvaughn** [comment]
In the example above, any primitive value (like `count`) would be forever closed over as the initial value (e.g. 0) when the inner "component" re-rendered. To update the value, you'd need to re-render the outer `Component` (_and_ the inner one) which I think would defeat the purpose?

Going to close this "bug" since it's a question :) Can chat more here though.
