### ISSUE TITLE
The tutorial is broken a bit

### ISSUE THREAD

**Issue by GyanendraSingh-2003** [facebook/react#22729]
on this url
https://reactjs.org/tutorial/tutorial.html
under section lift state up,

class Square extends React.Component {
  render() {
    return (
      <button
        className="square"
        onClick={() => this.props.onClick()}
      >
        {this.props.value}
      </button>
    );
  }
}

but it will give you an error, the () should be removed from this.props.onClick()

**Comment by bvaughn** [comment]
> but it will give you an error, the () should be removed from this.props.onClick()

I don't think that sounds correct. What error are you seeing?

**Comment by bvaughn** [comment]
I think this issue was opened by misunderstanding, so I'm going to close it. If you think it's not a misunderstanding though, please file a bug here:
[https://github.com/reactjs/reactjs.org](https://github.com/reactjs/reactjs.org/issues/new) 

The documentation and source for [reactjs.org](https://reactjs.org/) are in a different GitHub repository. It's maintained  by different people.

**Comment by GyanendraSingh-2003** [comment]
![unknown](https://user-images.githubusercontent.com/63923409/141052413-b61f55bf-c134-4cb4-ba6e-ebb0307201dd.png)

the error you get

**Comment by bvaughn** [comment]
That error likely means that something in your `onClick` prop is causing an update cycle. It has nothing to do with removing the `()` though. All that change would do would be to _not call the `onClick` prop_ which would technically "fix" the bug but also break your component.
