### ISSUE TITLE
Bug: React links to a NSFW site

### ISSUE THREAD

**Issue by vndre** [facebook/react#22732]
Running react in development mode in a browser with no extensions prints this warning on the console:

![Screenshot 2021-11-09 171938](https://user-images.githubusercontent.com/13294924/141021160-30dfe0b7-087f-4226-a65f-6dfbfe281928.png)

But `extension.remotedev.io` is currently redirecting to `rvzqo.facebookteens.com` which seems to be some sort of NSFW adult/pishing related site, or maybe it's geniune porn. Anyways, this could be used a way to trick people into downloading viruses disguised as the real devtools.

React version: 17.0.2

## Steps To Reproduce

1. go to https://pay.h4b.dev/ in a browser without Redux devtools extension.
2. open console
3. [NSFW WARNING] click suggested link in warning about Redux devtools

## The current behavior

the url `extension.remotedev.io` is not the correct link to download Redux devtools.

**Comment by bvaughn** [comment]
Please note that the development message you are seeing is coming from Redux, not React.

Looks like this issue was already reported and resolved on their end:
https://github.com/zalmoxisus/redux-devtools-extension/issues/810

If you're still seeing it, my guess is that you're using an older version of Redux? You'll want to take it up with them, regardless.

**Comment by vndre** [comment]
I see now, I wasn't using Redux so I couldn't find the source of the message, looking at the code I see one of my deps is using an old implementation of the devtools.
