### ISSUE TITLE
How can I optimise and speed up react js app with multiple tabs

### ISSUE THREAD

**Issue by samounaz** [facebook/react#22742]
Hello,
I have a react application with multiple tabs, in each tab we can add one or multiple highcharts. Once we reach the third tab, the application becomes very slow, took more than 15 seconds to do actions like adding new tab, delete tab, adding or removing highcharts. I'm already using functions of optimisation like memo, useMemo, useCallback, ... So I'm wondering if there is a possibility to unmount or kill the already visited tabs without hiding them in order to save the memory for the active tab. If you have any idea of how I can modify the architecture in order to speed up the application, because, I'm wondering how big applications for example handle multiple tabs without decreasing the performance. Tech : react js, redux, highcharts

**Comment by ELBEQQAL94** [comment]
Hi samounaz,

I read your post, I have had a similar problem before with our app. What I did to save the problem is create high order component in our case TabsRenderComponent and render data once and then each tab can have already data so if you re-visit the tab the data for the tab is already there. And this solution can increase performance on your application. Also i think high carts slow as well and take time to render SVG stuff on your tabs

**Comment by samounaz** [comment]
Hi ELBEQQAL94,

Thank you so much for your response. Can you explain to me why you had to create a custom higher order component rather than just using a memo which is a HOC made for boosting the optimisation of the component ? Also, how can you render the data once and save it for each tab ? Is it by handling the state in the HOC or do you have another technique ?

**Comment by ELBEQQAL94** [comment]
Hi samounaz,

Q: Can you explain to me why you had to create a custom higher-order component rather than just using a memo which is a HOC made for boosting the optimization of the component? 

A: useMemo is a good option too but for my example, I had to get data from the server once and send it as props to my components who live in the Tab Render component.

Imagine if you send a request from the component itself each click on the tab you have to send the request again and render data again again and that can affect on performance.

Conclusion

You have to render all your data once from the parent component When you can re-visit the tab you don't have to re-render the component again.

Q: How can you render the data once and save it for each tab ?

Each tab have a component on the tab body and that component you have to receive data as props from HOC, If you do this you don't have to re-render component when you re-visit a specific tab

Conclusion

Always, We have container and presentational components. Container sends requests and does the business and representational who care about display data. That's it

Any details about this topic you are welcome

**Comment by samounaz** [comment]
Hi ELBEQQAL94,

Thank you for all the explanations.
In my code, I have tabsGroup component which is handling tabs children components by  functions like addTab(), renameTab(), deleteAllTabs(), ...
So in my case,  I should turn the parent component tabsGroup into a higher order component and then pass the data to the tabs children in order to resolve the problem of re-rendering the tabs components unnecessarily in order to improve the app performance. Is that what I should do ? If, yes, I'll test it and let you know if it's working for me.

**Comment by ELBEQQAL94** [comment]
Good :+1:

**Comment by jeremy-deutsch** [comment]
I know it's a few days late, but have you tried doing performance profiling with the official [React devtools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)? That way, you can see what component subtrees are slow to updare, instead of just guessing. (Maybe try it with just 1 tab open at first.)

**Comment by samounaz** [comment]
Hi Jeremy,
Thanks for your message. Yes, I used react dev tools and also lighthouse and performance tabs when I was inspecting the problem in Chrome.

**Comment by samounaz** [comment]
Hi ELBEQQAL94,
Just to give you an update about the performance issue. I finally resolved the problem by removing some elements from the Dom. For example, when I select a tab the content of all other created tabs is removed from the dom. Also, I applied your advice related to creating a Higher order component for my tabs. Thanks again :)

**Comment by bvaughn** [comment]
Looks like this discussion has wrapped up 👍🏼  Going to close out this issue 😄  Thanks everyone who participated.
