### ISSUE TITLE
Can't edit a editable div in facebook post field(Keys not working)

### ISSUE THREAD

**Issue by azman63** [facebook/react#22823]
I am trying to make a extension like grammarly.When i want to make it work on facebook and twitter post field it doesn't work.When i write something in facebook post field and want to replace a suggestion of a existing wrong word by DOM modification using javascript,replacing suggestion does occur nicely.But after that no key including backspace,delete seems to stop working.This happens only in case of facebook and twitter.I wonder how grammarly manage this.Can anyone show me the path to solve this?

I think react dom of facebook does not permit these type of dom manipulation.What could be the ways to solve this problem from facebook react side.
`document.activeElement.innerText="hello, world"`

**Comment by jstejada** [comment]
hey @azman63, thanks for posting your question. maybe this article might be helpful? https://reactjs.org/docs/integrating-with-other-libraries.html

other than that i don't think i can provide a ton of guidance, and it's something that probably will require some research. since this feels pretty unrelated to React itself, i'm going to go ahead and close this issue
