### ISSUE TITLE
Bug: Parent Component already rendered, But Child Component can not rerender in StrictMode

### ISSUE THREAD

**Issue by janryWang** [facebook/react#22827]
React version: 17.x or 18@beta

## Steps To Reproduce

1. Just click the button
2. look the log infomations

Link to code example:

https://codesandbox.io/s/strictmode-v1emy?file=/src/App.js

## The current behavior

Child Component not rerender

## The expected behavior

Child Component need rerender

**Comment by jstejada** [comment]
hey @janryWang thanks for creating the issue. 

so if i'm understanding correctly, based on the behavior i'm seeing in the sandbox, you're saying that the first time we try to click the button to  update the value the Button component isn't updating despite the parent being re-rendered, and that this only happens when we're using a `StrictMode` tree?

it's interesting that it only happens the first time I click, and subsequent updates do go through.

I wonder if it has something to do with the `@formily/reactive-react`  libraries you are using? can you still reproduce this issue without using those libraries?

**Comment by janryWang** [comment]
> hey @janryWang thanks for creating the issue.
> 
> so if i'm understanding correctly, based on the behavior i'm seeing in the sandbox, you're saying that the first time we try to click the button to update the value the Button component isn't updating despite the parent being re-rendered, and that this only happens when we're using a `StrictMode` tree?
> 
> it's interesting that it only happens the first time I click, and subsequent updates do go through.
> 
> I wonder if it has something to do with the `@formily/reactive-react` libraries you are using? can you still reproduce this issue without using those libraries?

This library is mine, but I just can't find anything that affects React. The only thing I can be sure of is that the parent component has been rendered, but the child component has not been rendered. It should be noted that it will be worked if setTimeout is removed.
