### ISSUE TITLE
Drop upper-casing of ReactDOMComponent.tagName

### ISSUE THREAD

**Issue by syranide** [facebook/react#2288]
https://github.com/facebook/react/blob/master/src/browser/ui/ReactDOMComponent.js#L113

It works well for visually highlighting HTML tags in print, but it's somewhat weird for SVG and web components. Also because it's a public property that could be used for other purposes. This would also mean that we can drop the internal `_tagName` and just use `tag` unless there are other considerations.

**Comment by jsfb** [comment]
Looks like `tagName` isn't really being used for much, we may be able to remove it completely.

**Comment by jsfb** [comment]
A little history for the next person who investigates, since the original link no longer points to a meaningful target:

Looks like tagName was taken off ReactDOMComponent and put onto the wrapper in: https://github.com/sebmarkbage/react/commit/9c3e2d833d339eb885f1a1549e0043e768bdb209

Then it got moved to ReactDefaultInjection in:
https://github.com/sebmarkbage/react/commit/e3f95ea2936f06bb5986920c7f896f5c74d1a015

TagName appears on the wrappers of DOM elements, which mimics the tagName that already exists on the native dom elements.  These wrappers are temporary and will be going away.  When that happens, users will get the native dom elements, which have the native tagName property with the same semantics.  So, since these are scheduled for deletion and will happen naturally as part of that future commit, I'm going to close out this issue.
