### ISSUE TITLE
Bug: Image source takes a string, but not a variable with the same string

### ISSUE THREAD

**Issue by xMxster** [facebook/react#22997]
I'm using create-react-app

In my App.js, (the standard file created automatically) 

```
//This one works 
function Image(){
    return  <img src={require("./image.png").default}/>
}

//This doesn't work
function Image2(){
    let src = "./image.png";
    return <img src={require(src).default}/> 
}
```

Seems odd, since src has the same value as the string. Is it maybe a compiler error?

Complete file would be like this

```
import React from 'react';

//This work 
function Image(){
    return  <img src={require("./image.png").default}/>
}

//This doesn't work 
/*
function Image2(){
    let src = "./image.png";
    return <img src={require(src).default}/> 
}
*/

function App(){
     return <Image/>
     //return <Image2/>
}

export default App;
```

I'm researching, and it might be due to webpack and not react.

Anyway, I'm too inexperienced, I'll leave this, it might be useful somehow.

**Comment by bvaughn** [comment]
This does not look like an issue caused by React.

Have you tried moving the `require(src).default` bit outside of the `src` attribute and logging what you get? That could illustrate that React isn't involved in the loading of your module.

I suggest scanning Stack Overflow for issues like this with Webpack!

**Comment by vkurchatkin** [comment]
That is normal behaviour for bundlers, such as Webpack and completely unrelated to React. Bundlers look for expressions like `require("./image.png")` to figure out, that `image.png` should be a part of your application build. It works if the arguments is static (i.e. a literal), but otherwise Weback just doesn't know what you are requiring and doesn't include the image in the output.

**Comment by lucasliao0403** [comment]
What should we do instead then? Or is there no workaround?

**Comment by ademmeral** [comment]
const src = new URL("./image.png", import.meta.url).href

The best way =))
