### ISSUE TITLE
eslint-plugin-react-hooks: exhaustive-deps nagging behaviour

### ISSUE THREAD

**Issue by adm-sglm** [facebook/react#23026]
In some situations like the following, I can't find an elegant way to deal with exhaustive-deps error. I don't want to disable it just because of that maybe there is room to improve the linter rule here?

```js
const { firstName, lastName, middleName, email, ...(list goes on) } = someData;

const cb = useCallback(() => {
  ...
  someFn({
    firstName,
    lastName,
    middleName,
    ...,
    //(basically a subset of someData with other properties from component context)
  })
}, [someData] // => here I have to list all the variables I destructed from that object instead of just putting someData as dependency. When we assume that we use that destructed variables all over in the component context and they are numberous; dependency list grows long and maybe not so efficient.
```

**Comment by enigma1** [comment]
Same goes on for other hooks like useEffect. I get erroneous warnings like 
_"Mutable values like 'refreshTrigger.current' aren't valid dependencies because mutating them doesn't re-render the component"_

Now it's not good practice to place unused dependencies or not place in the hook parameters used. However the warning is misleading and should point to best practices, because the hook can be activated if there is a state render phase elsewhere within the component or parent component, props, context etc. In which case the dependency change will be processed at that point. In fact it can be used as a method to reduce the number of render phases and control hook activation. A basic example:

https://codesandbox.io/s/happy-joana-ll3my

**Comment by philting** [comment]
> In some situations like the following, I can't find an elegant way to deal with exhaustive-deps error. I don't want to disable it just because of that maybe there is room to improve the linter rule here?

This will cause your hook to run if something outside of your subset has changed. e.g. if `someData.email` changes and your `useCallback` is not dependent on it.

Is there a reason that you can't just get rid of the dependency array altogether?

**Comment by philting** [comment]
> Same goes on for other hooks like useEffect. I get erroneous warnings like _"Mutable values like 'refreshTrigger.current' aren't valid dependencies because mutating them doesn't re-render the component"_

Thanks for creating that example. Very interesting.

Per the [React docs](https://reactjs.org/docs/hooks-reference.html#useref):

> Keep in mind that `useRef` doesn’t notify you when its content changes. Mutating the `.current` property doesn’t cause a re-render. If you want to run some code when React attaches or detaches a ref to a DOM node, you may want to use a callback ref instead.

Sounds like the linting rules are just reiterating what the docs are saying.

**Comment by philting** [comment]
#21903 

Same issue brought up in another thread:

> To be clear, the issue is not that a change in ref value won't re-run an effect. It's that a change in ref value won't re-render a component. (If something else happens to re-render the component, and a ref value is passed in as a dependency– the effect would re-run. The reason we advise against using refs in the dependencies array is that changes to refs don't cause a component to re-render in the first place, as dependencies coming from state do.)

I think in general what you've said and what was mentioned in that thread needs to be in the React documentation.

As for the ESLint rule, perhaps something like `Mutable values like 'refreshTrigger.current' aren't valid dependencies because the effect is not guaranteed to run. Dependencies should be values that will re-render the component when they are changed, such as props and state.`

**Comment by enigma1** [comment]
Yeah I think it's all about linting. I have experimented using a ref instead of state and so far I have not seen difference in terms of functionality. What I did and an experiment, created a custom reducer that renders when called, even when no arguments passed in, it forces a render phase and then a I use a ref as a wrapper around this reducer to handle component state the same way as the original. You can even extend it with APIs, promises, callbacks etc.

**Comment by philting** [comment]
@enigma1 , if you comment out line 11 in your example, the behavior does change. I think in most cases it's not an issue, but the whole point of the linting rule is to ensure we don't run into edge cases.

I think we are in agreement here though. The rule is fine, but the error copy is confusing, and needs to be updated. Perhaps this deserves a new issue? It's different from OP's concern.

**Comment by adm-sglm** [comment]
> 



> #21903
> 
> Same issue brought up in another thread:
> 
> > To be clear, the issue is not that a change in ref value won't re-run an effect. It's that a change in ref value won't re-render a component. (If something else happens to re-render the component, and a ref value is passed in as a dependency– the effect would re-run. The reason we advise against using refs in the dependencies array is that changes to refs don't cause a component to re-render in the first place, as dependencies coming from state do.)
> 
> I think in general what you've said and what was mentioned in that thread needs to be in the React documentation.
> 
> As for the ESLint rule, perhaps something like `The effect is not guaranteed to run when mutable values like 'refreshTrigger.current' are changed. Use dependencies that will re-render the component when they are changed, such as props and state.`

Well I didn't try yet but what if I used `object.freeze` is the linter smart enough to interpret that as a guarantee to object immutability?

**Comment by enigma1** [comment]
The whole point of that line-11 in the demo was to show how update state in a controlled manner is possible using a ref and therefore that "deps error" is not an error. So I couldn't show it without that line but yea the documentation certainly needs to be corrected.

**Comment by eps1lon** [comment]
This is intended behavior. 

`someData` might not change referential equality, thus not firing the effect while `someData.someProperty` might have changed.

The solution is to destructure the properties and list them in the dependency array explicity.
