### ISSUE TITLE
Bug: always need to force reload on deployment

### ISSUE THREAD

**Issue by Shyam268** [facebook/react#23039]
Using react version 17
on every UI changes we deploy the latest changes to azure app service . it always shows old ui. if we force reload then it loads the latest ui. how to avoid this force reload on react for every deployment

**Comment by ludofischer** [comment]
In my view, the problem with the old UI still appearing after a reload has nothing to do with React. It's more likely that the browser is caching the old version of the UI because the cache has not expired yet. You could try tweaking the [`Cache-Control` headers](https://www.cloudflare.com/learning/cdn/glossary/what-is-cache-control/) the server is sending and using cache-busting techniques (i.e. changing the file names on every new versions, you can do this with build tools like webpack).

**Comment by italosantana** [comment]
@Shyam268 try to see this doc about [local cache azure](https://docs.microsoft.com/en-us/azure/app-service/overview-local-cache), maybe this help with local caching using azure.

**Comment by Shyam268** [comment]
thanks i will try this

**Comment by eps1lon** [comment]
Please use the support channels for the framework you're using to build React applications. 

Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

Coding Questions
If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

https://stackoverflow.com/questions/tagged/react

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html
