### ISSUE TITLE
How to disable this warning message whenever the page is loaded with warning ?

### ISSUE THREAD

**Issue by lakshits11** [facebook/react#23058]
React version: 17.0.2

## The current behavior
![image](https://user-images.githubusercontent.com/54276661/147885059-e434b13d-c30c-4d33-8ad6-551112a1d043.png)

How to disbale these warning messages only (not error messages) whenever I reload the page and I have to again and again click the cross button. I know I have unused-vars but I dont wanna see these warnings in browser, my vscode is already showing them and that's enough.

## Steps To Reproduce

1. Create a basic as usual react app.
2. Create a components folder in src. Create a file in it and use some unused vars.
3. Like I created a basic  Login.jsx file (not completed yet) below:

```
import { FcGoogle } from "react-icons/fc";
import shareVideo from "../assets/share.mp4";
import logo from "../assets/logowhite.png";

const Login = () => {
  return (
    <div className="login-component">
      <div className="video-component">
        <h2>My Name</h2>
        <video src={shareVideo}></video>
      </div>
    </div>
  );
};

export default Login;
```

Other files are basic. Just import above file in App.jsx file.

My package.json file:

```
{
  "name": "myname",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@sanity/client": "^2.23.2",
    "@sanity/image-url": "^1.0.1",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-google-login": "^5.2.2",
    "react-icons": "^4.3.1",
    "react-loader-spinner": "^4.0.0",
    "react-masonry-css": "^1.0.16",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0",
    "uuid": "^8.3.2",
    "web-vitals": "^2.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "^8.6.0",
    "eslint-plugin-react": "^7.28.0",
    }
}

```

Here `FcGoogle` and `logo` are unused vars and I know it.

## The expected behavior
Please suggest a way so that this warning message don't show up whenever I reload the page. 
_In my previous projects, it didn't showed up on whole page for such small warnings and annoyed me._

**Comment by harish-sethuraman** [comment]
Ideally these `no-unused-vars` should be warnings (I get warnings only 🤔 ) but not sure how it is showing as errors. Check if you have configured ESlint rules somewhere else in your project if so change it from error to warning. 

If you don't find any external ESlint configuration in the project you can edit the eslint configuration in `package.json` to the following to show warnings for `no-unused-vars` rather than errors.

```json
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "rules": {
      "no-unused-vars": 1
    }
  },
```

**Comment by eps1lon** [comment]
As @harish-sethuraman already mentioned these are caused by your ESLint configuration and not by React itself. Closing in favor of using other support channels.

Coding Questions
If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

https://stackoverflow.com/questions/tagged/react

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html
