### ISSUE TITLE
Bug: function property in useEffect dependency array doesn't remove it from exhaustive-deps check but should

### ISSUE THREAD

**Issue by frfancha** [facebook/react#23069]
Basic app from create-react-app typescript.
This code complains about missing dependency s:
```
const App = () => {
  const [, setState] = useState(0);
  const s = { setState };
  useEffect(() => {
    s.setState(1);
  }, [s.setState]);
  return null;
};
```
This one doesn't:
```
const App = () => {
  const [, setState] = useState(0);
  const s = { setState };
  useEffect(() => {
    const f = s.setState;
    f(1);
  }, [s.setState]);
  return null;
};
```

React version: 17.0.2
Expected behaviour: the first version shouldn't complain about missing dependency "s"

This a very very simplified version of an issue we have a lot of times in our code making that the team doesn't even bother to look at dependency warnings, which is of course a bad idea :-(

**Comment by vkurchatkin** [comment]
This looks very much intentional.

`s.setState(1)` can be rewritten as `s.setState.call(s, 1)`, while ` const f = s.setState; f(1);` can be rewritten as `s.setState.call(undefined, 1)` (assuming strict mode).  Compare these two expressions side-by-side:

`s.setState.call(s, 1)`
`s.setState.call(undefined, 1)`

The first one actually does depend on the values of `s` (it is passed as `this` argument), the second doesn't.

**Comment by eps1lon** [comment]
Closing since this is intentional. Great explanation by @vkurchatkin in https://github.com/facebook/react/issues/23069#issuecomment-1007608586

**Comment by frfancha** [comment]
Perfectly explained and makes sense, thanks for your time.
