### ISSUE TITLE
Bug: StrictMode print Math.random() are inconsistent

### ISSUE THREAD

**Issue by hxse** [facebook/react#23091]
React version:
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.0"
## Steps To Reproduce
```
import React, { useState, useRef, useEffect, StrictMode } from "react";
import ReactDOM from "react-dom";

import "./styles.css";

function App() {
  const [state, setState] = useState(Math.random());
  const [state2, setState2] = useState(Math.random());
  const state3 = useRef(Math.random());
  console.log("in: ", state, state2, state3.current);
  useEffect(() => {
    console.log("out:", state, state2, state3.current);
  });
  return (
    <div className="App">
      {state}
      <br />
      {state2}
      <br />
      {state3.current}
      <br />
      <button onClick={() => setState(state + 1)}>click</button>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(
  <StrictMode>
    <App />
  </StrictMode>,
  rootElement
);
```

Link to code example:

https://codesandbox.io/s/sharp-panini-udb6j?file=/package.json:174-253

## The current behavior
![image](https://user-images.githubusercontent.com/22582226/148887248-a8dca4ec-3109-4402-bdde-be46a36ad452.png)
The values of printed before and after are inconsistent.

## The expected behavior
In this case, remove the StrictMode, the behavior is expected.
https://codesandbox.io/s/laughing-rain-li9ku?file=/src/index.js
![image](https://user-images.githubusercontent.com/22582226/148888015-38335a8c-ae77-41c7-8bb7-ac4db8d5e03f.png)

**Comment by bvaughn** [comment]
Strict mode exists to help tease out things that aren't _safe_ to do or rely on because of the fact that React might render without committing, or it may render more than once before committing. ([Read more here.](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects))

In this case, you're initializing the values in your component's state to _something random_, which means if React renders once– then tosses away the result and re-renders later, those initial values will be _different_. Strict mode simulates a scenario like this (in DEV only) by rendering twice during mount (and throwing away the result of one of the renders).

Removing strict mode removes this behavior and so it "fixes" the issue you're reporting, but that issue can still occur in a production.

I'm going to close this issue as a misunderstanding rather than a bug. I hope my above explanation helps! I definitely recommend [reading the strict mode docs](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) as they explain the motivation for the way strict mode behaves.

**Comment by gaearon** [comment]
>One final thing that might be confusing you is that React used to disable console logging during the second strict render to avoid confusing people. That changed with React 17 and now DevTools can be used to disable the console (or not) during that render (#21783).

I'm a bit confused by this... Didn't we _introduce_ disabling in 17? And then changing this again in 18.

**Comment by bvaughn** [comment]
> I'm a bit confused by this... Didn't we introduce console disabling by default in 17? And then I thought 18 rolls that back and makes it configurable via DevTools (with the default of greyed out logs for second render).

You're right. I misremembered the timeline.

**Comment by hxse** [comment]
@bvaughn
I really hope that debugger breakpoint trigger can also be disable, logic like `console.log and console.trace`, it is very useful.

**Comment by gaearon** [comment]
React 18 is out, and double logs are no longer suppressed by default.
(But they're slightly dimmed if you have DevTools installed.)

See https://github.com/facebook/react/issues/21783#issuecomment-1083412766.
