### ISSUE TITLE
Bug: react-test-renderer: promise returned from `findByProps` query must be handled

### ISSUE THREAD

**Issue by josias-r** [facebook/react#23093]
React (and react-test-renderer) version: 17.0.2
Eslint version: 8.6.0

## Steps To Reproduce

1. create a `ReactTestInstance` using `create` from `react-test-renderer`
2. Try to run access `findByProps` of the root of `ReactTestInstance`
3. Eslint(`testing-library/await-async-query`) will show an error 

code example:
```jsx
// simulate nav toggle click event
create(<Nav onToggle={mockFunction} items={[]}></Nav>)
  .root.findByProps({
    className: "app__nav-toggler",
  })
  .props.onClick();
```

## The current behavior

Eslint(testing-library/await-async-query) will show an error:

<img width="416" alt="Screenshot 2022-01-11 at 11 57 52" src="https://user-images.githubusercontent.com/11424820/148930814-dd143b6b-60b4-4690-b633-da17b0f33780.png">
<img width="642" alt="Screenshot 2022-01-11 at 12 00 31" src="https://user-images.githubusercontent.com/11424820/148930866-c6898b22-fb56-415b-bb52-237040e6ad13.png">

## The expected behavior
Since the return type of `findByProps` is not actually a promise, the error should not appear. `findByProps` appears to be synchronous.

**Comment by bvaughn** [comment]
The lint rule in your bug report (`testing-library/await-async-query`) is for another project, [testing-library](https://github.com/testing-library). That library (and lint rule) are not related to the [`findByProps`](https://reactjs.org/docs/test-renderer.html#testinstancefindbyprops) method of [`react-test-renderer`](https://reactjs.org/docs/test-renderer.html). I think the lint rule, in this case, is just a false positive because the method name starts with "findBy".
