### ISSUE TITLE
Bug: Variables that begin with use will throw an error when used inside a hook. 

### ISSUE THREAD

**Issue by MANTENN** [facebook/react#23221]
React version:

## Steps To Reproduce

1.
```
let useNotaHook = () => {};
useEffect(() => {
useNotaHook()
}, [])

```
2.

Link to code example: https://codesandbox.io/s/serene-ramanujan-bsyu8?file=/src/App.js:247-346

## The expected behavior

Error not to be thrown

**Comment by vkurchatkin** [comment]
Just to clarify: no errors are thrown here, it is a linter warning/error. That said, as far as linter concerned, all functions starting with `use` are hooks. Your options are:

- rename or alias this function before calling it
- disable linter rule for this line

**Comment by rohitmultani** [comment]
As a rule of using react hooks, hooks cannot be used in nested function. But will always be used inside component function and that too at  the top.

**Comment by aymanxdev** [comment]
Firstly, I would suggest using a different name for your function. `use` tells React that it's a hook either built-in or custom hook. This convention is very important. Without it, React wouldn’t be able to automatically check for violations of [rules of Hooks](https://reactjs.org/docs/hooks-rules.html) because it couldn’t tell if a certain function contains calls to Hooks inside of it according to React documentation. Another nothing to note that always call hooks at the top level of your component function.

**Comment by MANTENN** [comment]
> As a rule of using react hooks, hooks cannot be used in nested function. But will always be used inside component function and that too at the top.

Yup, I'm aware. I didn't realize it was the linter before I opened it. So its probs a better suggestion for the linter to have a message that would say make sure you don't sue any function named(whether its restructured) useSomething.
