### ISSUE TITLE
Bug: equal object variable in useState and const variable returns false using strict equality

### ISSUE THREAD

**Issue by dcvdiego** [facebook/react#23233]
While working on a client project I was trying to use conditional rendering for some components. At first I tried to store an object in a useState and check whether it matched the object coming through a CMS, and it did not work. So I checked whether an entry in an object was equal and it was. 

I tried to look into the source code but I cannot find why this is only a problem when you use objects but not other types. I do not think this is a misuse of React Hooks and, although there are workarounds, I wanted to raise this bug. 

React version: 17.0.2

I have recreated the scenario using a basic example shown below:

## Steps To Reproduce

1. Add these 4 lines of code to any component (respecting Rules of Hooks):
```  
  const [obj, setObj] = useState([{ a: 1 }]);
  const realObj = [{ a: 1 }];
  console.log(realObj === obj ? true : false);
  console.log(realObj.a === obj.a ? true : false);
```

## The current behavior

This is the result of the logs in the console:
```
false
true
```
## The expected behavior
You would expect this in the console instead:
```
true
true
```

**Comment by gaearon** [comment]
In JavaScript (and some other languages as well), the notion of equality is about comparing the identity of the object rather than its contents. When you write `{ }`, you instruct the JavaScript object to *create* an object. Then, when you compare `obj1 === obj2`, you’re asking: “are these two variables pointing at the _same_ object?” Since each `{ a: 1 }` _creates_ a new object, a comparison like `{ a: 1 } === { a: 1 }` will always be `false` — these are not the _same_ objects — which is essentially what you are comparing.

If you want to check the objects' contents, you have a few options. This depends on how deep you want to go. If it's not nested, you can get by with a “shallow comparison” (iterating over each object’s properties) or even hardcode specific properties to compare. If it is deeper, you might want to compare using deep equality. There are libraries that do this, or you can write code for this manually. There are also options like `JSON.stringify(obj1) === JSON.stringify(obj2)` but they’re not efficient for large objects, and also can’t deal with cyclical objects.
