### ISSUE TITLE
Bug: eslint-plugin-react-hooks makes a suggestion that will lead to bugs

### ISSUE THREAD

**Issue by mgummelt** [facebook/react#23246]
React version: Current

## Steps To Reproduce

1. Enable eslint-plugin-react-hooks
2. Write a `useEffect` call with a dependency array containing members with unstable object identities.  See this blog post: https://www.benmvp.com/blog/object-array-dependencies-react-useEffect-hook/#option-2---recreate-the-object-within

## The current behavior

The following message is displayed.

```
The 'team' object makes the dependencies of useEffect Hook
change on every render. To fix this, wrap the initialization
of 'team' in its own useMemo() Hook.
```

## The expected behavior

`useMemo` does not guarantee a stable object identity: https://reactjs.org/docs/hooks-reference.html#usememo

eslint-plugin-react-hooks shouldn't suggest using it, since it may result in unexpected invocations of `useEffect`.

**Comment by sammy-SC** [comment]
Hey @mgummelt,

What is the bug that you encounter with this?

I don't think `useMemo` guarantees stable object identity to leave opportunities for future optimisations, like offscreen components. The docs specifically mention to use it for performance optimisations but not as semantic guarantees.

**Comment by vkurchatkin** [comment]
>  The docs specifically mention to use it for performance optimisations but not as semantic guarantees.

I think that is the point. There are no guarantees about `useMemo`, meaning that `useMemo` being a noop would be valid behaviour.

But in this case you actually need a guarantee that `useMemo` works as expected, otherwise you get an infinite loop. So, I would agree that this warning contradicts documentation:

> The 'team' object makes the dependencies of useEffect Hook
change on every render. To fix this, wrap the initialization
of 'team' in its own useMemo() Hook.

Fixing this issue can hardly be called "performance optimization".

**Comment by mgummelt** [comment]
@sammy-SC One possible bug is that `useMemo` is used on a dependency to `useEffect`, which makes a non-idempotent call to the backend that is called multiple times.
