### ISSUE TITLE
Bug: React Context consumers not consuming through windowed portal

### ISSUE THREAD

**Issue by NoMaillard** [facebook/react#23268]
Using React Portals to render React components in an external window doesn't respect context hierarchy 
in the example the hierachy is like this: 
```jsx
<PortalWindowContextProvider>
      <AppContextProvider>
        <App>
            <div className="App">
              <h1>Hello CodeSandbox</h1>
              <h2>Start editing to see some magic happen!</h2>
              <Language />
              <PortalWindow>
                  <h1>PORTAL</h1>
                  <PortalComponent>
                    <Language />
                  </PortalComponent>
              </PortalWindow>
          </div>
        </App>
      </AppContextProvider>
    </PortalWindowContextProvider>
```
the `Language` component consumes the context

the 'react dom' would look like this
```jsx
<PortalWindowContextProvider>
      <AppContextProvider>
        <App>
            <div className="App">
              <h1>Hello CodeSandbox</h1>
              <h2>Start editing to see some magic happen!</h2>
              <Language />
          </div>
        </App>
      </AppContextProvider>
    </PortalWindowContextProvider>

<-- popup window --!>
              <PortalWindow>
                  <h1>PORTAL</h1>
                  <PortalComponent>
                    <Language />
                  </PortalComponent>
              </PortalWindow>
```

React version: 17.0.2

## Steps To Reproduce

1. Run the example
2. Allow popups to open
3. Lang should be shown in the popup window

Link to code example: https://codesandbox.io/s/fast-cherry-28tpc

## The current behavior

Context is not consumed correctly, the initial value of the context is shown, but when the value is updated, the context value is not updated 

## The expected behavior

the context is consumed and kept up to date

**Comment by guillaumebrunerie** [comment]
The portal window is being created in `PortalWindowContextProvider`, therefore outside `AppContextProvider` which is the context provider for `lang`. You can easily check in the React Dev Tools that the portal is not a descendent of the provider for `lang`, which explains why it doesn’t get the updated value.
You can easily fix it by simply swapping `PortalWindowContextProvider` and `AppContextProvider`, so that the portal is created inside the provider for `lang`.

You could also simply render the portal directly inside `PortalWindow`. I’m not sure why you have this pretty complicated setup with sending it to a provider at the root of your app and rendering it over there. It is perfectly fine to call `ReactDOM.createPortal` deep inside your tree, this way it would get access to the expected contexts.
