### ISSUE TITLE
Bug: rapid successive renders produce wrong output

### ISSUE THREAD

**Issue by ysulyma** [facebook/react#23282]
I have a component which listens to updates on a store. When the store is updated twice, the component is re-run with a new value, but doesn't get re-rendered with the new value.

React version: 17.0.2

Link to code example:

https://codesandbox.io/s/cranky-danilo-iw1g7?file=/src/App.js

## The current behavior

Console logs `0` then `2`, but component displays 0

## The expected behavior

Component should display the last value that was logged, in this case 2

**Comment by guillaumebrunerie** [comment]
Works fine when changing the implementation of `useForcedUpdate` to `useReducer(c => c+1, 0)[1]`.
This is most likely due to the fact that React batches calls to `useState`/`useReducer` within a `useEffect`, and therefore having a `useForcedUpdate` that simply negates a boolean being called exactly twice will make React think that nothing changed.

**Comment by ysulyma** [comment]
Ahhh of course, thanks!
