### ISSUE TITLE
Bug: Invalid hook call with systemjs

### ISSUE THREAD

**Issue by ytudt** [facebook/react#23296]
I use systemJs to load a system module in a react project, the module include some react function component use react hooks。
and react project get Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons

React version: 17.0.2

## Steps To Reproduce

1. git clone git@github.com:ytudt/react-systemjs.git
2. cd base-components  npm install && npm run start
3. cd base-projects   npm install && npm run start
4. open http://localhost:3000/ in the default browser

Link to code example:

https://github.com/ytudt/react-systemjs

## The current behavior

Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

## The expected behavior

expected run ok

**Comment by sammy-SC** [comment]
It would be helpful to isolate the issue. Sounds like the problem could be coming from systemJS. Do you think it would be possible to reproduce this in CodeSandbox?

**Comment by Inrmanish** [comment]
see my pull req,
gd or not

**Comment by sammy-SC** [comment]
> see my pull req, gd or not

What pull request?

**Comment by eps1lon** [comment]
This is very likely caused by duplicate versions of React. You have a `base-project` and `base-components` folder each with their own version of React installed. You need to tell your bundler to ensure a single version of React is installed.

Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html
