### ISSUE TITLE
[DevTools Bug] Unsupported Bridge operation "0"

### ISSUE THREAD

**Issue by gitrthanki1** [facebook/react#23307]
### Website or app

local app development

### Repro steps

just install react devtools and downgrade to 4.11.0 

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.23.0-e28a0db22

### Error message (automated)

Unsupported Bridge operation "0"

### Error call stack (automated)

```text
at /Users/softwaremac/Desktop/Users/JigneshJani/RNProjects/WifiSwitch/WifiSwitchV2_29_5/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:333837
    at c.emit (/Users/softwaremac/Desktop/Users/JigneshJani/RNProjects/WifiSwitch/WifiSwitchV2_29_5/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:277732)
    at /Users/softwaremac/Desktop/Users/JigneshJani/RNProjects/WifiSwitch/WifiSwitchV2_29_5/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:279273
    at /Users/softwaremac/Desktop/Users/JigneshJani/RNProjects/WifiSwitch/WifiSwitchV2_29_5/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:659742
    at Array.forEach (<anonymous>)
    at A.e.onmessage (/Users/softwaremac/Desktop/Users/JigneshJani/RNProjects/WifiSwitch/WifiSwitchV2_29_5/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:659726)
    at A.t (/Users/softwaremac/Desktop/Users/JigneshJani/RNProjects/WifiSwitch/WifiSwitchV2_29_5/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:44:3009)
    at A.emit (events.js:315:20)
    at e.exports.L (/Users/softwaremac/Desktop/Users/JigneshJani/RNProjects/WifiSwitch/WifiSwitchV2_29_5/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:8:13567)
    at e.exports.emit (events.js:315:20)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Unsupported Bridge operation  in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by Mike2l8** [comment]
Wtf

**Comment by sanjeevyadavIT** [comment]
Facing same issue
<img width="944" alt="Screenshot 2022-02-18 at 10 20 25 AM" src="https://user-images.githubusercontent.com/13250741/154619631-9695c7ff-8b26-4fad-af7b-b2d40541f7bb.png">

I even tried toggling the "Use globally installed DevTools" and I have devtools installed globally but it didnt work

**Comment by MuhammedKpln** [comment]
Same issue here as well.

**Comment by lunaruan** [comment]
Hi, thanks everyone for commenting! Are any of you experiencing this issue with the most recent release of DevTools? If so, could you provide a codesandbox or a github repro? Unfortunately, we're not able to debug this issue without proper repro steps. Thanks!

**Comment by kyle-ssg** [comment]
I can confirm replicating this on a vanilla react-native app using flipper (where I believe this issue was created from), the issue also persists on 4.22 as well as 4.23, however using ❯ npm i -g react-devtools@4.21.0 

![image](https://user-images.githubusercontent.com/8608314/154794658-4c13870e-ad2c-4c15-aaab-7948974042d6.png)

**Comment by lunaruan** [comment]
Hey! I just created a vanilla react native app using create-react-native app and tested React DevTools, and I couldn't repro the error. Could you give me an exact repro?

**Comment by DrOverbuild** [comment]
I ran into the same issue on a new React Native 0.67.3 app generated with `react-native init`

Clicking dismiss on the *Unsupported Bridge operation "0"* message removes that message but then I am presented with this error:

![Screen Shot 2022-02-25 at 11 58 30 AM](https://user-images.githubusercontent.com/3422979/155764281-3079768a-6d84-4bb0-b30e-d750f4a0cbd6.png)

I checked which version of react-devtools-core that the Metro server is using:

```
$ npm explain react-devtools-core
  react-devtools-core@4.19.1
  node_modules/react-native/node_modules/react-devtools-core
    react-devtools-core@"4.19.1" from react-native@0.67.3
  ...
```

So React Native uses react-devtools-core 4.19.1, not too far behind the latest. So it should be compatible right?

Well by downgrading to use the exact version that React Native uses, it is now working for me. So I guess 4.19.1 and 4.23.0 are not compatible

```
npm remove -g react-devtools
npm install -g react-devtools@4.19.1
```

**Comment by bvaughn** [comment]
> So React Native uses react-devtools-core 4.19.1, not too far behind the latest. So it should be compatible right?

No. This is why the dialog suggests downgrading the frontend.

We know this is not ideal, but the architecture of react-devtools and react-native has been around for a long time (predating those of us now working on the tooling side). For the browser extensions (most common use case) or even packages like `react-devtools-inline` – the frontend and backend are shipped together. For React Native, a backend version is *embedded* into the app (in DEV mode) so any mismatches between frontend and backend will break things. This is why there's a protocol check and a dialog like the one shown above.

>  Well by downgrading to use the exact version that React Native uses, it is now working for me. So I guess 4.19.1 and 4.23.0 are not compatible

That's correct.

**Comment by DrOverbuild** [comment]
The dialog suggests downgrading to a version prior to v4.11.0, but because the backend is running 4.19.1, following the directions in the dialog does not work. We are presented with a similar message, but instead the dialog suggests upgrading to `^4.13.0`.

![Screen Shot 2022-03-02 at 1 27 13 PM](https://user-images.githubusercontent.com/3422979/156434596-c138aff3-29da-4c8f-b6c1-efd37c7fbb8e.png)

With the given semver notation, version 4.23.0 satisfies `^4.13.0`, and that's what NPM installs. 

It looks like the backend of 4.19.1 (presumably using bridge protocol version 1) communicates an incorrect bridge protocol version. Either that or the frontend of 4.23.0, which expects version 2, reads an incorrect bridge protocol version from the backend. Ether way, the dialog suggests a misleading downgrade command.

At any rate, the main point is if you're getting either _Unsupported Bridge operation "0"_ or _Unsupported DevTools backend version_, check the backend version you're using (which, with React Native, it's currently 4.19.1) and make sure you have that exact version of the frontend.

**Comment by bvaughn** [comment]
The dialog's suggestion is based on which version of the backend React Native has embedded. If the frontend version you are currently using requires a newer protocol, you will be prompted to downgrade (to match). If the frontend version requires an older protocol version, you will be required to upgrade (to match).

At least, that is how it is supposed to work. Given this issue, it sounds like some combination(s) of backend and frontend version aren't working as designed.

@DrOverbuild Any chance you could give me a list of exactly which versions (backend and frontend) you used that showed that series of dialogs? I'd like to repro and dig into where things went wrong.

**Comment by DrOverbuild** [comment]
With not being able to respond due to the lockdown last week, I had some extra time to investigate the issue.

> @DrOverbuild Any chance you could give me a list of exactly which versions (backend and frontend) you used that showed that series of dialogs? I'd like to repro and dig into where things went wrong.

To answer your question, the only backend I've tried is 4.19.1, bundled with React Native.
* Frontend v4.10.3 suggests to upgrade to `^4.13.0`. It sees the correct bridge protocol version from the backend.
* Frontend versions up to 4.21.0 work (as that is the last version supporting bridge protocol v1).
* Frontend versions after 4.22.1 will suggest to downgrade to `<4.11.0`.

Looking at [source code](https://github.com/facebook/react/blob/72a933d2892dac9e5327678b6bd37af8d589bb22/packages/react-devtools-shared/src/devtools/store.js#L264-L267) I see the front end assumes bridge protocol version 0 if it doesn't get a response within 10 seconds (because old versions of DevTools don't know about bridge protocol versioning). This timeout is further confirmed by the fact that I'm getting that downgrade message only after 10 seconds of staring at a blank inspector.

However, the manner through which I get the RN app to connect to devtools matters. If the app is already running and I open the debug menu in the RN app, devtools will timeout. If I terminate the app and run it again, devtools will timeout. But if I just reload the app, devtools does not timeout and shows that the backend is using bridge protocol 1.

I want to say this is more an issue with react-devtools-core in React Native than with the frontend.

**Comment by bvaughn** [comment]
Thank you for the extra context!

> * Frontend versions after 4.22.1 will suggest to downgrade to `<4.11.0`.

This seems broken. I'm guessing the timeout is firing when it shouldn't, maybe b'c something isn't forwarding the protocol check message (or not forwarding it fast enough?)

**Comment by DrOverbuild** [comment]
Ok I downloaded this entire repo and set up a dev environment so I could debug what's going on here. 

We're getting `Unsupported Bridge operation "0"` due to the incompatibility with version 1 and 2 of the bridge protocol. That's expected.

When that happens, `Store.onBridgeOperations` [throws](https://github.com/facebook/react/blob/581f0c42ed4baa07309dbda296dc93a101bd922b/packages/react-devtools-shared/src/devtools/store.js#L1239) an error that gets bubbled up the call stack [above](https://github.com/facebook/react/blob/581f0c42ed4baa07309dbda296dc93a101bd922b/packages/react-devtools-shared/src/events.js#L56) the event emitter. I can't quite tell how the error gets handled above that, but my guess is that it's causing the bridge to stop listening for events?

I added a console.log [here](https://github.com/facebook/react/blob/581f0c42ed4baa07309dbda296dc93a101bd922b/packages/react-devtools-shared/src/bridge.js#L292), and this is the output when connecting with an unsupported back end version:

```
Received message from backend: overrideComponentFilters
Received message from backend: isBackendStorageAPISupported
Received message from backend: isSynchronousXHRSupported
Received message from backend: operations
[React DevTools] Error calling listener {event: "operations", payload: Array(2580)}
    ...
Uncaught Error: Unsupported Bridge operation "0"
    ...
```

The bridge receives no message after processing the `operations` message. There's no `bridgeProtocol` message, so the timeout is fired.

After commenting out the throw statement [here](https://github.com/facebook/react/blob/581f0c42ed4baa07309dbda296dc93a101bd922b/packages/react-devtools-shared/src/events.js#L56) we see `bridgeProtocol` is sent in some cases after the first `operations` message:

```
Received message from backend: overrideComponentFilters
Received message from backend: isBackendStorageAPISupported
Received message from backend: isSynchronousXHRSupported
Received message from backend: operations
Received message from backend: isNativeStyleEditorSupported
Received message from backend: profilingStatus
Received message from backend: bridgeProtocol
```

Again I didn't have enough time this afternoon to investigate how errors are handled above the event emitter. Are you intentionally ignoring incoming bridge messages after an error like this happens? Either way I think the root of this problem is incomplete error handling or simply timing of the bridge messages.

**Comment by bvaughn** [comment]
This is helpful! Thank you.

So the repro steps basically sound like...
* An app with DevTools backend version 4.19.1
* DevTools frontend version 4.22.1

Is that right? Let me see if I can repro too.

**Comment by bvaughn** [comment]
> I couldn't reproduce it in a web app. 

Right, that makes sense, because the backend and frontend are bundled along with each other in the case of the web extension and inline packages. Even with the standalone, the webpage loads the backend script via an HTTP server the frontend runs.

React Native is the odd one out.

**Comment by bvaughn** [comment]
As a workaround for anyone reading this, you could use an approach like Resolutions to work around the backend version mismatch, e.g.
```json
  "resolutions": {
    "react-native/react-devtools-core": "4.24.0"
  },
```
I used a similar resolution in my test React Native project to force downgrade the backend to 4.19.1.

**Comment by bvaughn** [comment]
Okay, after digging into this– I can repro it. I'm not sure there's a great workaround or "fix" for it though. The underlying issue (explained in #21326) still needs to be handled.

Maybe React Native could do a better job of prompting/matching backend and frontend versions during installation? I'm not sure how React DevTools (the frontend UI) could do this _other_ than via some protocol version check like we are already doing. (Although if anyone has ideas I'd love to talk about them.)

In hindsight, I should have made the very first parameter in the operations array a protocol version number. Then the frontend could treat messages different based on their _known_ protocol. But it's too late to make this change and so here we are.

**Comment by bvaughn** [comment]
Looking at the history of the Bridge protocol stuff, we basically have the following changes:
* Protocol changed from 0 to 1: 4.10.1 -> 4.11.0
* Protocol changed from 1 to 2: 4.21.0 -> 4.22.0

The source revisions for the above versions are:
* 4.10.1: f160547f47cb271bff09c639a6dae8f1b169bc14
* 4.11.0: d4cae99f2a59e0380871134960d29ec5ce2c4fd9
* 4.21.0: 6c7ef3fce5547da5db3d400ccf95a5023f8891f4
* 4.22.0: 0229baee21e8e6ecef04d4d76c41af84dfcca8bc

Exporting and comparing these revisions...
```sh
# Export
git archive -o ~/Desktop/DevTools/4.10.1.zip f160547f47cb271bff09c639a6dae8f1b169bc14
git archive -o ~/Desktop/DevTools/4.11.0.zip d4cae99f2a59e0380871134960d29ec5ce2c4fd9
git archive -o ~/Desktop/DevTools/4.21.0.zip 6c7ef3fce5547da5db3d400ccf95a5023f8891f4
git archive -o ~/Desktop/DevTools/4.22.0.zip 0229baee21e8e6ecef04d4d76c41af84dfcca8bc

# Extract...

# Diff:
diff \
  ./4.10.1/packages/react-devtools-shared/src/devtools/store.js \
  ./4.11.0/packages/react-devtools-shared/src/devtools/store.js \
  > 4.11.diff

diff \
  ./4.11.0/packages/react-devtools-shared/src/devtools/store.js \
  ./4.21.0/packages/react-devtools-shared/src/devtools/store.js \
  > 4.21.diff

diff \
  ./4.21.0/packages/react-devtools-shared/src/devtools/store.js \
  ./4.22.0/packages/react-devtools-shared/src/devtools/store.js \
  > 4.22.diff
```

Looking at the store diffs, I see the following changes between protocol changes::
* 0 to 1: Added `TREE_OPERATION_REMOVE_ROOT` and `TREE_OPERATION_UPDATE_ERRORS_OR_WARNINGS` messages. I think, maybe, this isn't technically a breaking change since both operations are _new_.
* 1 to 2: Added two extra bits to the `TREE_OPERATION_ADD` message for new root nodes. These bits specified strict mode compatibility and owner metadata properties.

If I had thought to design the operations array up front to include its protocol version as the first bit, then we could easily support backwards compat in cases like this. Really bad oversight on my part, in hindsight. As it is now, we could _try_ to do this (if we already have the protocol version) but there would be cases we can't handle (e.g. the backend is too old to report its protocol and the frontend times out).

Maybe we could queue up operations until we know (or infer) the backend version? I'm not sure how hard this would be to implement in practice, especially when considering cases like reload and profile. Probably hard.

**Comment by usrbowe** [comment]
@bvaughn can I just check, for Flipper, when I bumped the React Devtools to `4.24.1` like this (just for reference from older change):
https://github.com/facebook/flipper/commit/a916bf4c58d3c4e0f742cf99703d8bcfc6648b92

But this mean, we can now only use the latest `4.24.1` in Flipper, and also need to force React Native app via yarn resolution to use `4.24.1`.

Would there be any other solution to this?

**Comment by bvaughn** [comment]
@usrbowe Bumping the version of the React DevTools (frontend) used in Flipper sounds like a good idea. 4.24.1 is more "compatible" with older backend versions.

**Comment by Sakura-echos** [comment]
![image](https://user-images.githubusercontent.com/59500387/196835416-ebb1435a-8fa8-4a14-9362-6fe7edb321dc.png)
any one help?

**Comment by roykoper** [comment]
> ![image](https://user-images.githubusercontent.com/59500387/196835416-ebb1435a-8fa8-4a14-9362-6fe7edb321dc.png) any one help?

I had the same issue, downgrading to 12.1 worked for me.
