### ISSUE TITLE
Bug: event target typed as EventTarget & T prevent usage without `as`

### ISSUE THREAD

**Issue by y-nk** [facebook/react#23341]
React version: 17.0.2

## Steps To Reproduce

1. create a form with a submit handler
2. type the submit handler as `onSubmit = (event: React.SyntheticEvent<HTMLFormEvent>)
3. add `new FormData(event.target)`

Link to code example: https://codesandbox.io/s/cra-forked-m8pyd5?file=/src/app.tsx

## The current behavior

We must use `as` because `e.target` is typed as `EventTarget & T` rather than `T`

## The expected behavior

The event target should rather be `T`

**Comment by eps1lon** [comment]
Thanks for the issue.

The TypeScript types are published from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/53cfd160dff8cce414121dca05c4f7d9c0f7a0d9/types/react/index.d.ts.

However, this issue has come up a lot and `target` being typed as `T` would not be sound due to event bubbling. For more context please consider https://github.com/DefinitelyTyped/DefinitelyTyped/blob/53cfd160dff8cce414121dca05c4f7d9c0f7a0d9/types/react/index.d.ts#L1156-L1162 before opening a [new issue on DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/new/choose).

**Comment by y-nk** [comment]
@eps1lon thank you for the kind 1 liner explanation even tho i was creating my issue in the wrong place. Your behavior is what the general open source world should look like. 🙏 🙏 🙏
