### ISSUE TITLE
Bug: `eslint-plugin-react-hooks` cannot detect `useRef` dependencies.

### ISSUE THREAD

**Issue by ouweiya** [facebook/react#23392]
From the following sources I understand that `useRef` does not need to be added to the `useEffect` and `useCallback` dependencies.

>React Hook useEffect has an unnecessary dependency: 'ref.current'. Either exclude it or remove the dependency array. Mutable values like 'ref.current' aren't valid dependencies because mutating them doesn't re-render the component. (react-hooks/exhaustive-deps)

https://stackoverflow.com/a/60476525/9854149
https://stackoverflow.com/a/63353582/9854149
https://reactjs.org/docs/hooks-reference.html#useref

But when useRef is used as props, eslint always warns about hook missing dependencies?

```jsx
import { useCallback, useEffect, useRef } from 'react';

const One = ({ refEl }) => {
  const clickHandler = useCallback(e => {
    refEl.current = 1111;
  }, []); //⚠️ React Hook useCallback has a missing dependency: 'refEl'. Either include it or remove the dependency array.

  useEffect(() => {
    refEl.current = 2222;
  }, []); //⚠️ React Hook useCallback has a missing dependency: 'refEl'. Either include it or remove the dependency array.

  return (
    <div onClick={clickHandler} ref={refEl}>
      One
    </div>
  );
};

function App() {
  const el = useRef('');
  return <One refEl={el} />;
}

export default App;
```

**Comment by eps1lon** [comment]
It doesn't need to be added if React knows that a specific value comes from `useRef`.

In your case however it is passed from a parent component so the plugin wouldn't know if it comes from `useRef`. The plugin could detected some cases but it would be harder to explain when it breaks down so the plugin only works with values that are declared in the same scope.

I hope this helps explain why this is currently, unfortunately, expected behavior that'll unlikely change.
