### ISSUE TITLE
The onPointerDown event does not work to prevent bubbling

### ISSUE THREAD

**Issue by coderyyx** [facebook/react#23391]
Register the onclick event in the parent component, register the onpointerdown event in the child component, and prevent the event from bubbling in the onpointerdown event but the onclick event will still fire。

When I register the onpointerdown event in the parent component, it works。

React version: 17.0.2

[cosandbox](https://codesandbox.io/s/broken-darkness-uq4i0h?file=/src/App.js)

## The current behavior
onclick event fire。

## The expected behavior
onclick event not fire

**Comment by ouweiya** [comment]
Because they are not the same type of events, it is impossible to prevent the broadcast. You can register `onPointerDown` or `onMouseDown` in the parent component to prevent the broadcast.

[most user agents will fire a mousedown event](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onpointerdown#:~:text=most%20user%20agents%20will%20fire%20a%20mousedown%20event)

**Comment by eps1lon** [comment]
> Register the onclick event in the parent component, register the onpointerdown event in the child component, and prevent the event from bubbling in the onpointerdown event but the onclick event will still fire。

Neither `preventDefault()` nor `stopPropagation()` (on both `down` and `up` events) will not prevent a click event.

This behavior is not exclusive to React but how these events work in the DOM: https://codesandbox.io/s/down-up-cant-prevent-click-j6t2ly?file=/src/App.js

**Comment by coderyyx** [comment]
> 

thx~
