### ISSUE TITLE
Internal API terminology/naming

### ISSUE THREAD

**Issue by syranide** [facebook/react#2354]
`receiveComponent => receiveElement` actually takes an element.

The following are also named as if they mount *another* component, but perhaps it's "necessary" as they are inherited and exposed by user classes (to go with `componentWillMount` etc)? ... or is it just for clarity at call-sites perhaps. If that's true I guess the justification loops back to `receiveComponent` actually intended as being just `receive`.

`mountComponent => mount`
`mountComponentIntoNode => mountIntoNode`
`updateComponent => update`
`unmountComponent => unmount`

cc @sebmarkbage @zpao

**Comment by jimfb** [comment]
Over a year with no comments.  I think that means people don't really feel strongly about changing the names of stuff in the internal API, and we all forgot about the issue.  Having `component` as part of the name is at least consistent with the lifecycle methods, FWIW.

Anyway, I'm going to close this out because I don't think it's worth keeping the issue open indefinitely.  If you were to submit a PR, I know I wouldn't block it.  If someone feels strongly, speak now, or forever hold your peace :P.

**Comment by sebmarkbage** [comment]
This is basically just legacy because it is a hassle to deal with various other renderers safely and in different repos. As we refactor, like our recent changes, we should try to make sure we make renames at the same time.
