### ISSUE TITLE
Warn when two versions of React are used alongside

### ISSUE THREAD

**Issue by gaearon** [facebook/react#2402]
People lose hours of work debugging a simple issue: two versions of React being loaded at the same time.

https://github.com/gaearon/react-hot-loader/issues/32#issuecomment-60043061
https://github.com/KyleAMathews/coffee-react-quickstart/issues/10#issuecomment-50655116
https://github.com/gaearon/react-document-title/issues/1#issuecomment-60241045
https://github.com/clayallsopp/react.backbone/issues/26

Because there is no warning right away when this happens, they usually discover the problem through invariant violations. Some of them are descriptive (e.g. `Uncaught Error: Invariant Violation: The handler for Route "hello" must be a valid React component`) and I think I even saw warning that said something like "check if two copies of React are loaded", but some are really cryptic: `Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs...`.

Is there a reason why we don't want to warn *right away* when two copies of React are loaded?

**Comment by joaomilho** [comment]
Just my 2cents: I had the same issue today and my problem was using browserify 8.1.3 instead of 8.1.1

Hope it helps

**Comment by charypar** [comment]
The other issue with this is you can't reliably use the dependency injection mechanism, e.g. to change the batching strategy, while using components from multiple modules where each has it's own instance of React as a dependency. Even if they are the *same version* of React.

**Comment by christopherbalz** [comment]
+1 ; thanks gaearon

**Comment by sedge** [comment]
@charypar said: "The other issue with this is you can't reliably use the dependency injection mechanism, e.g. to change the batching strategy, while using components from multiple modules where each has it's own instance of React as a dependency. Even if they are the same version of React."

This.

**Comment by aearly** [comment]
The main workaround many modular React components are using is to specify React as a `peerDependency` -- the parent module must provide React to prevent multiple copies.  This is problematic because `peerDependencies` are on track to [become deprecated](https://github.com/npm/npm/issues/6565) because they introduce [dependency hell](https://github.com/npm/npm/issues/5080#issuecomment-40551620).

**Comment by JedWatson** [comment]
I've seen this a lot as well, and had lots of requests to switch React to a `peerDependency` (+`devDependency`) in my packages which I'm currently resisting for reasons @aearly mentioned.

The most common frustration I've seen is when npm subtly installs two versions of React, and Browserify (correctly) includes both in the build. It can happen unexpectedly w/ package updates and breakage ensues. A warning from React that "hey, there is more than one of me on the page" seems like the most elegant way to warn developers early and direct them to an explanation of what's gone wrong / how to fix it.

It's a side-effect of npm's dependency rules and node's `require` behaviour that I end up with two Reacts when I just want one. Looks like things will get better with `npm@3` (see npm/npm#6565) but in the meantime I agree with @gaearon about adding a "lesser evil" hack:

```
if (__DEV__) {
  var ExecutionEnvironment = require('ExecutionEnvironment');
  if (ExecutionEnvironment.canUseDOM) {
    if (window.__REACT_INITIALISED__) console.warn("Warning: more than one instance of React has been initialised. This may cause unexpected behaviour; see {url}");
    window. __REACT_INITIALISED__ = true;
  }
}
```

... there's a good argument to be made that this isn't React's problem to solve, but since it's a common problem and React _can_ solve it, I think it would be great if it did.

**Comment by sedge** [comment]
@JedWatson A solution I found with `browserify` was to alias all `require()` calls like so (example shown with grunt)

```js
    browserify: {
      dev: {
        files: {
          'public/app.js': ['react/index.jsx']
        },
        options: {
          alias: [
            "react:react", "React:react"
          ],
          transform: [babelify,reactify]
        }
      }
    },
```

so it isn't impossible to fix, but I'd make the argument that since this is such a common issue it needs to be highlighted more clearly in the React docs.

**Comment by gaearon** [comment]
+ https://github.com/rackt/react-router/issues/1028

**Comment by robertknight** [comment]
> I guess the cases here are when nesting elements from different versions inside each other?

@spicyj when using browserify it can happen just when requiring two different versions of React because of the way it handles deduplication. Requires with the same path and code between the two versions can end up getting de-duped. Modules where the code/require path was changed between versions get deduplicated and others don't.

So I encountered this:
1. ReactDOMSelect (from React v1) is evaluated and it mixes in ReactBrowserComponentMixin as part of its spec
2. ReactInjection.Class.injectMixin(ReactBrowserComponentMixin) is evaluated and it adds ReactBrowserComponentMixin to all classes subsequently created by ReactClass.createClass (shared between React v1 and v2 because it didn't change between the two versions of React)
3. ReactDOMSelect (from React v2) is evaluated and it tries to mix in ReactBrowserComponentMixin twice, once from ReactDOMSelect's own spec and once from the global injected mixin list.

As long as modules can be stateful, this approach to deduplication seems horrifically unsafe. But I think it would make sense to warn.

**Comment by spicyj** [comment]
Reverting #3580 for now (in #3646) as we sort out some problems.

**Comment by mike360** [comment]
THANK YOU for this discussion. I was battling with an Invariant Violation bug for half the day yesterday and then came across this ticket this morning. My setup was using a browserify-shimmed version of React and react-router loaded from CDN. After reading this discussion I just opted to use the npm versions of these libs and the error went away.

This is my first React project so debugging this problem was a pretty big headache. Thanks again for this discussion as it lead me to figure out the problem and move forward.

**Comment by olavk** [comment]
Leaving details of my case for future searchers:
I got the error "Invariant Violation: Could not find the drag and drop manager in the context of Card. Make sure to wrap the top-level component of your app with configureDragDropContext"
Also turned out I had two React versions loaded.
The problem was Webpack. I was using "npm link \<folder\>" for one of my packages, which also depends on React. Seems webpack has problems handling symbolic links, or it's my fault configuring it improperly. Anyway, the problem was fixed by installing the package into my local node_modules directory.

**Comment by gaearon** [comment]
@olavk Thanks for this, I'm gonna add it to the relevant explanation gist for React DnD.

**Comment by mathieumg** [comment]
Would like to have this too. Haven't figured out a way to get GitHub cc'd (rather than bcc'd) without explicitly participating, sorry for the noise.

**Comment by joeybaker** [comment]
@mathieumg There's a button :)

![](https://cloudup.com/cYAkZKuziTV+)

**Comment by mathieumg** [comment]
@joeybaker I think that still doesn't CC you but only BCC, sadly. Moreover, I'm watching the `react` repo already, but I have a different inbox for when GitHub CCs me.

**Comment by chrisirhc** [comment]
Fyi: Ongoing PR #3332

**Comment by spicyj** [comment]
Fixed by #3332, hopefully.

**Comment by gaearon** [comment]
If it helps the next person googling,

```
"Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined" "checkAndWarnForMutatedProps @ ReactElementValidator.js"
```

is yet another sign of this problem.

**Comment by ameensol** [comment]
``HOURS_SPENT_HERE+=4`` and counting...
I've got this one:
```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
```
I'm looking everywhere for the sneaky react twin, but no luck.

``find ./ -name 'react'`` doesn't show any duplicates

The other possibilities I've read about are double-loading the react script, webpack double-bundling, or react/addons causing trouble, so those are what I'm working on now. 

Insidious.

**Comment by syranide** [comment]
@ameensol As you've hopefully set up package.json correctly, then simply remove `node_modules` and reinstall everything, that usually fixes it unless there's some incorrectly configured module.

**Comment by ameensol** [comment]
@syranide I tried to git clone the repo and reinstall, but that wasn't the issue. Eventually I noticed that the error was only happening after the first navigation (similar to this [other issue](https://github.com/facebook/react/issues/3474)) and started taking apart my navigation menu. Turns out that for some reason putting a ``<Link/>`` from react-router inside a ``<MenuItem/>`` from react-boostrap was causing react to go nuts. I posted my findings on [Stack Overflow](http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined).

**Comment by ameensol** [comment]
I think it also might have had something to do with my not using the ``<Root/>`` generated from react-router as the root of my component hierarchy. I was wrapping it in a higher level-component that accepts my flux instance and passes it on as context. 

Isolating the issue into [this repo](https://github.com/ameensol/fluxette-react-router/tree/router%400.13.3) gave me the following error:
```
Uncaught Error: Invariant Violation: ReactMount: Root element ID differed from reactRootID.
```

**Comment by spicyj** [comment]
The nested links thing is due to invalid HTML and we have a new warning for that in 0.14.

**Comment by gaearon** [comment]
>The nested links thing is due to invalid HTML and we have a new warning for that in 0.14.

By the way I got that new warning a few days ago and it's beautiful, great work. :+1:

**Comment by tnrich** [comment]
I'm getting this error: 

```Uncaught TypeError: Cannot read property '_currentElement' of null```

when using npm link to require a module I'm working on. I can't be 100% sure that it's caused by having multiple versions of React, but the error does  go away when I just paste the npm module directly into my app instead of using it via npm link. 

I don't get this error when using my npm module the normal way (react is a dev dependency so I don't think it gets installed in node modules). Has anyone else run into this issue and come up with a fix?

Thanks!

**Comment by globexdesigns** [comment]
I got this error while running 0.14-rc1 and 0.14-beta3 together

```
Uncaught TypeError: Cannot read property 'MUST_USE_ATTRIBUTE' of undefined
(anonymous function)	@	HTMLDOMPropertyConfig.js:17
```

**Comment by zpao** [comment]
Please do not report random problems in this issue. File new issues.

**Comment by aphillipo** [comment]
Seriously.  This has taken me 3 days to figure out that my random error about Scrollbar.js unmounting the _mouseMoveTracker twice in fixed-data-table is caused by two reacts... 

https://github.com/facebook/fixed-data-table/issues/302

This is not good that this bug seemingly can't be fixed?  Why can React not just put the version number on the window object and never add itself again if it's there already?  This is better than the hours and hours wasted by many people with this!

**Comment by jimfb** [comment]
@aphillipo Is it not fixed in 0.14?  https://github.com/facebook/react/pull/3332

**Comment by aphillipo** [comment]
Yep, I just upgraded to 0.14.2 everywhere (including inside the module) and somehow deleting react from node_modules/react-datatable/node_modules/ fixed my bug! (see here https://github.com/aphillipo/react-datatable).

Maybe there is something wrong with my webpack config?  It's weird that this fixed it.  Is this having two of the identical version included a subtle variant on this bug?

**Comment by syranide** [comment]
@aphillipo Part of the problem is react-datatable having `react` as a non-peer dependency (cc @pieterv) which can cause NPM to fetch a separate react installation for just that module.

**Comment by aphillipo** [comment]
Okay - thanks @syranide - I'll try adding this as a peer dep, however when I want to run the build for my module if developing the datatable from within my main project, what is the best way to accomplish this without issues?

**Comment by ericsoco** [comment]
@aphillipo you might try upgrading to `npm@3`, then `rm -rf node_modules; npm install`. `npm@3` has improvements in how it handles dependencies and is better about avoiding multiple instances of a given package, since it installs with a flat structure instead of nesting dependencies within packages.

This, along with moving `react` from `dependencies` to `peerDependencies` in a library I am writing, solved my similar problems.

**Comment by Diokuz** [comment]
Another 4 hours lost.

My webpack config now is:
```js
  externals: {
        'react-dom': 'React.__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED',
        react: 'React',
        backbone: 'Backbone',
        underscore: '_',
        jquery: 'jQuery'
  },
```

**Comment by spicyj** [comment]
@Diokuz Can you say what symptom you experienced?

Also, if you are using the prebuilt react.js I would recommend using the prebuilt react-dom.js as well and using `'ReactDOM'` in your webpack config since the secret property is unstable and will change in the next version (hence its name).

**Comment by Diokuz** [comment]
Yes, the problem was in prebuild version of React. The second instance of React came from require('react'). It did work somehow until React 0.14 migration. And even more: It work after partial code removal! This lead me to wrong way of long debugging.

I agree, this is my fault. But I still expect something like:
```js
throw new Error('You are using two React instances simultaneously!!!11 The most common mistakes here: 1) using prebuild React 2) misconfiguring webpack 3) ... etc');
```
every time, instead of rare warning:
```js
console.error('Only a ReactOwner can have refs');
```
after which I spent hours to find out whats wrong with my refs...

It seems like it is very common problem, and it is have to be more detailed and have better documentation.

**Comment by JohnnyZhao** [comment]
same issue with webpack and react.js loading manually.

**Comment by mnquintana** [comment]
@gaearon @spicyj Is it still an issue to load more than one version of React on a page, even if those instances are managing totally separate DOM trees and aren't being explicitly instantiated as globals? Like if, say, I had a package with `ComponentA` and `ComponentB` as dependencies, and they both depended on different versions of React, with npm as the dependency manager, could they be used together on one page?

**Comment by spicyj** [comment]
@mnquintana No, that should work now if both are on a recent version of React.

**Comment by idhard** [comment]
>  if both are on a recent version of 

Could you please point me out what would be the behavior of React if , let say , we want to introduce a widget including React in a host page that has an older version of it and the possible workaround to make it work? 
Thanks

**Comment by spicyj** [comment]
Old versions of React are probably only tripped up by data-reactid IDs in the DOM that it didn't generate. If you're doing only client-side rendering with your widget, it should only have a data-reactroot attribute and no data-reactid so there shouldn't be any conflict.

**Comment by jedwards1211** [comment]
Just ran into this error again today when I accidentally had 16.4.2 and 16.5.0 installed in a project, no warning from React.

**Comment by OliverRadini** [comment]
Was there any resolution as to whether or not this is possible and/or a good idea? It seems like it'd provide developers with useful information.

**Comment by prasanthLalapeta** [comment]
Project A uses React 16 wherein Project B uses React 15, Lets say Project A is package got used in Project B - can that work?

**Comment by dgreene1** [comment]
Would Preact and React have the same issue described here?

I’m asking because I’m using single-spa for a platform play at a large company of distributed teams.

**Comment by robertknight** [comment]
> Would Preact and React have the same issue described here?

It sounds to me like there are two separate issues here:

1. Can you have two different copies of the library loaded and in use anywhere on a page in separate components that don't interact with each other?
2. Can you have components from two different bundles, each with their own copy of the library, interact with each other (eg. the `render` function from one library receiving an element created with `createElement` from the other library)

I don't know about the status with modern versions of React. In the case of Preact (1) should be fine but since it does have some global state you could run into problems in situation (2). Please file an issue in the [Preact](https://github.com/preactjs/preact) repository if you'd like to discuss further.

**Comment by dkeesey** [comment]
> I think that in the future, this will actually just work. In the meantime we can warn here: https://github.com/facebook/react/blob/master/src/core/ReactElement.js#L230

This appears to be a bad link.

**Comment by IPWright83** [comment]
For someone encountering this at the moment - does anyone have any tips on identifying the cause and debugging the issue? I've used the check from the hooks page (how I discovered this) which confirms I've got 2 instances loaded:

```
// Add this in node_modules/react-dom/index.js
window.React1 = require('react');

// Add this in your component file
require('react-dom');
window.React2 = require('react');
console.log(window.React1 === window.React2);
```

I believe I'm doing things by the book, in a monorepo react, react-dom etc are all always `peerDependencies`. What steps would you recommend after this?

**Comment by fcano-ut** [comment]
I believe that as long as you're using React 17+, it is now possible to use more than one version at once. I gather that from the React 17 release notes.

> React 17 enables gradual React upgrades. When you upgrade from React 15 to 16 (or, this time, from React 16 to 17), you would usually upgrade your whole app at once. This works well for many apps. But it can get increasingly challenging if the codebase was written more than a few years ago and isn’t actively maintained. And while it’s possible to use two versions of React on the page, until React 17 this has been fragile and caused problems with events.
>
> We’re fixing many of those problems with React 17. This means that when React 18 and the next future versions come out, you will now have more options. The first option will be to upgrade your whole app at once, like you might have done before. But you will also have an option to upgrade your app piece by piece. For example, you might decide to migrate most of your app to React 18, but keep some lazy-loaded dialog or a subroute on React 17.
> – [React 17 release notes](https://arc.net/l/quote/efrhuppp)
