### ISSUE TITLE
Adding and then removing "background" from style attribute creates unwanted styles

### ISSUE THREAD

**Issue by WickyNilliams** [facebook/react#2407]
I have an element and depending on some condition, may set it's background. If the condition is first true, and later false the element is left with some "residual" styles that were never set in code.

Output looks like:
```html
<!-- condition true -->
<div style="background: #ff0000"></div>

<!-- then when condition is false -->
<div style="background-attachment: initial; background-size: initial; background-origin: initial; background-clip: initial;"></div>
```

These styles were never set by user code, and are interfering with styles in my CSS. 

Here's a fiddle showing the issue: http://jsfiddle.net/tfKYJ/78/

**Comment by spicyj** [comment]
The issue here is that we only unset background image, position, repeat, and color and not attachment, clip, origin, or size. Not sure where I came up with that original list. I think the best course of action here is to make sure we unset all the properties that IE8 supports, then take your #1953. These shorthand properties are kind of a pain. :)
