### ISSUE TITLE
Bug: Not attaching ref before effect on React 18

### ISSUE THREAD

**Issue by m4theushw** [facebook/react#24102]
React version: 18.0.0-rc.2

## Steps To Reproduce

1. Open one of the examples
2. Look at the console (`otherRef.current = ?`)
3. You might need to reload the page to see the wrong behavior

Link to code example:

React 17: https://codesandbox.io/s/ref-defined-with-react-17-vu7kh5?file=/src/App.js
React 18: https://codesandbox.io/s/ref-null-with-react-18-uem22w?file=/src/App.js

## The current behavior

The ref inside the effect is `undefined`.

## The expected behavior

The ref should be already attached when the effect is called. React 17 works that way.

Adding a breakpoint in `commitAttachRef` I noticed that in React 18 it's called after the effect, which explains the `undefined`. Why it works that way now? I can fix the example by also checking if `isSSR=false` inside the effect but I want to understand so I can justify this change.

**Comment by sebmarkbage** [comment]
Thanks for the report!

The issue is that the focus can happen faster than the useEffect that turns isSSR to true. This is the same as if you were to use `autoFocus` prop that happens slightly faster than useEffect. The same issue will also happen if the parent uses useLayoutEffect or a ref callback.

We're still debating whether it should deopt in the useEffect case. There could be an easy fix to preserve backwards compat in this exact case.

You could switch the isSSR flag to use useLayoutEffect but that's probably not better since it's better to prioritize interactivity than progressive hydration. So it'd recommend just being resilient to this case by ignoring the focus if isSSR is not yet false.

There's another issue in your example which is what happens if you get focus on the button before you hydrate? That's kind of the same.

What you could do is when isSSR turns false is check if `document.activeElement === ref.current` that way you can handle both the case where focus was set before hydration or if it was set earlier during the hydration passes.

**Comment by m4theushw** [comment]
@sebmarkbage Thanks for the great explanation. I went with "ignoring the focus if isSSR is not yet false".
