### ISSUE TITLE
React 18 - typescript gives an error when reproducing official Upgrade Guide

### ISSUE THREAD

**Issue by flppv** [facebook/react#24208]
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/6984143/160765911-c2c7704c-c4d6-4f2b-a6a8-6f36ef0bbfac.png">

Looks like a type mismatch when recreating switch from `render` to `createRoot` way with typescript code base

**Comment by Coding-Maniac** [comment]
Just stated this issue yesterday: [https://github.com/facebook/react/issues/24196](https://github.com/facebook/react/issues/24196)

This needs to updated in [https://github.com/DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by eps1lon** [comment]
The issue here is that `container` is potentially null. [`createRoot(null)` would throw at runtime](https://codesandbox.io/s/container-cant-be-null-yvx57v?file=/src/index.js) and therefore rightfully does not compile. If you're sure it's not nullable then you can use the `!` operator: `createRoot(container!)`.

**Comment by MattOfficial** [comment]
> The issue here is that `container` is potentially null. [`createRoot(null)` would throw at runtime](https://codesandbox.io/s/container-cant-be-null-yvx57v?file=/src/index.js) and therefore rightfully does not compile. If you're sure it's not nullable then you can use the `!` operator: `createRoot(container!)`.

Thanks. This helped.
