### ISSUE TITLE
Bug: Lazy components recreates all Suspense content when using createRoot

### ISSUE THREAD

**Issue by roblan** [facebook/react#24201]
React version: 18.0.0

## Steps To Reproduce

1. Open https://codesandbox.io/s/romantic-mopsa-0zxehy?file=/src/App.js
2. Open console

Link to code example:
https://codesandbox.io/s/romantic-mopsa-0zxehy?file=/src/App.js

## The current behavior
When using `ReactDOM.createRoot`, all `Suspense` content seems to be rendered as 'new' (with clean slate) when `LazyComponent` promise finishes, as if it's `key` prop has changed.

## The expected behavior
`Suspense` content should be updated (retain id/refs/useMemo/initial state) not 'clean rendered', just like with 'old' `ReactDOM.render` root

**Comment by gaearon** [comment]
This is behavior is expected. It fixes a number of other issues and is described here: https://github.com/reactjs/rfcs/blob/main/text/0213-suspense-in-react-18.md#behavior-change-committed-trees-are-always-consistent

Why is this a problem in practice for your case? What state is there that you want to retain? I suspect there's more to it but the example doesn't show that.

**Comment by roblan** [comment]
It becomes a problem when `LazyComponent` is created in some component inside `Suspense` - saving it using ref/state/useMemo does not work (as they are not retained) and content will never render - it is stuck in the loading/rerendering loop (as `LazyComponent` is recreated every time as different component).

https://codesandbox.io/s/elated-mayer-6pjxey?file=/src/App.js

**Comment by gaearon** [comment]
I see. I don’t think we intend to support this pattern. (Though I agree it’s confusing the loop doesn’t warn.)

You should be able to fix this code by caching the `lazy` references outside of your component. Is this enough to work around the issue?

**Comment by roblan** [comment]
Yes caching it outside does work and should be enough. I was just hoping that no workaround from my app would be needed 🙂

Warning or some info in docs that this pattern is unsupported would be helpful though.

**Comment by andres-kovalev** [comment]
> This is behavior is expected. It fixes a number of other issues and is described here: https://github.com/reactjs/rfcs/blob/main/text/0213-suspense-in-react-18.md#behavior-change-committed-trees-are-always-consistent

This doc explains that react won't commit the tree with holes to the DOM, but it's not clear why the state should not be retained. Why we need to create a separate "temporary" instance of the component, and then create another one when promise resolves.

> Why is this a problem in practice for your case? What state is there that you want to retain? I suspect there's more to it but the example doesn't show that. Since the components weren't shown to the user, there should be no reason for their state to update at all until they've shown for the first time. So it shouldn't matter whether that state is recreated or not.

I think I have another case when It becomes a problem: when there is a need to bind lifecycle of an external entity to component's lifecycle.

> You should be able to fix this code by caching the `lazy` references outside of your component. Is this enough to work around the issue?

Caching outside of component works for static refs, but not for **dynamic** ones. Let's say I need to create a dynamic store instance when the component appears on the screen and then perform a cleanup when the component gets unmounted to avoid memory leaks with subscriptions and timers.

[useSyncExternalStore()](https://react.dev/reference/react/useSyncExternalStore) allows me to sync with an external storage, but it works only for static/global ones.

```jsx
// global/static store
import { todosStore } from './todoStore.js';

function TodosApp() {
  const todos = useSyncExternalStore(todosStore.subscribe, todosStore.getSnapshot);
  // ...
```

What if I need to render several independent todo-lists on the screen?

1. The need for cleanup indicates that some effects might occur when the storage is created. So, it sound pretty natural to create a store in effect:

```jsx
let todos;

useEffect(() => {
  todos = new TodoStore();

  return () => todos.release();
}, [])
```

But in this case it's not clear what to return during first render when the store is not created yet. We can return null, but it makes out component useless for SSR because effects are not triggered on the server. Also, react won't be able to trigger nested lazy components loading.

2. Another options is to create an instance during the first render using `useState()` with `initialState` callback and then release the instance in an effect:

```jsx
const todos = useState(() => new TodoStore());

useEffect(() => () => {
   todos.release();
}, []);
```

But effects are not triggered during SSR and for the "temporary" instance of the component inside `<Suspense />` while waiting for the promise to resolve. So our stores gonna leak.

Am I missing something?
