### ISSUE TITLE
[DevTools Bug] Cannot add child "2" to parent "1" because parent node was not found in the Store.

### ISSUE THREAD

**Issue by Sam-Apostel** [facebook/react#24267]
### Website or app

https://github.com/Sam-Apostel/3d-browser/tree/f124285a55930bb78e42099e33047827919cb800

### Repro steps

clone the repo at the linked commit
- npm install
- npm run dev
- open localhost:3000
- open react devtools
- refresh the page

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.23.0-e28a0db22

### Error message (automated)

Cannot add child "2" to parent "1" because parent node was not found in the Store.

### Error call stack (automated)

```text
at /usr/local/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:330974
    at c.emit (/usr/local/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:277732)
    at /usr/local/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:279273
    at /usr/local/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:659742
    at Array.forEach (<anonymous>)
    at A.e.onmessage (/usr/local/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:53:659726)
    at A.t (/usr/local/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:44:3009)
    at A.emit (events.js:315:20)
    at e.exports.L (/usr/local/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:8:13567)
    at e.exports.emit (events.js:315:20)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add child  to parent  because parent node was not found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by jakejarvis** [comment]
Also getting this error running Next.js 12.1.4 locally via `next dev`. Chrome 100.0.4896.60 on macOS, with dev tools extension 4.24.0-82762bea5. Started appearing right after updating to React 18.

```
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26395:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24400:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24566:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:54300:39)
```

[Here's the repo](https://github.com/jakejarvis/jarv.is/tree/react-18), but let me know if any more specific info would be helpful since the error above probably isn't!

**Comment by jakejarvis** [comment]
FWIW, I can reproduce this intermittently in a CodeSandbox... which is strange since the error appears 100% of the time on my repo, but refreshing this untouched Next.js template a few times (or clicking around on the links) with dev tools open triggers it eventually for me.

https://codesandbox.io/s/react-issue-24267-0hl5th
https://0hl5th.sse.codesandbox.io/

<img width="1003" alt="Screen Shot 2022-04-04 at 12 08 02 PM" src="https://user-images.githubusercontent.com/1703673/161586144-9bfe6a80-655c-40be-a8b6-5859966ab92b.png">

**Comment by lunaruan** [comment]
Hey @jakejarvis and @Sam-Apostel! Thanks so much for reporting this issue. I see that you are using DevTools v4.24.0 and v4.23.0 respectively. I tried reproducing with our most recent DevTools version (with several bug fixes related to the store) in v4.24.3. We've already released this version to NPM and we're publishing it to Chrome/Firefox today. I tried reproducing the issue with the most recent version and I couldn't. Could you let us know if you still see this issue when you upgrade to the most recent version (as soon as it's released?) Thanks!

**Comment by Sam-Apostel** [comment]
thanks for looking into this @lunaruan 
I can confirm that `react-devtools@4.24.3` fixed this issue.

In the process of updating my `react-devtools` npm installation on macos I kept getting the `2.23.0` version.
I had to manually remove the `react-devtools` folder at `usr/local/lib/node_modules/react-devtools`.

**Comment by jakejarvis** [comment]
Fixed for me as well! Just had to press update from the Chrome extensions page to force it. Thanks so much @lunaruan!!
