### ISSUE TITLE
[eslint-plugin-react-hooks] exhaustive-deps incorrect handling of ...rest params in dependency lists

### ISSUE THREAD

**Issue by ehahn9** [facebook/react#24349]
`exhaustive-deps` seems to have the wrong behavior for rest parameters and rest destructing. The follow will *never* memoize because rest values are new array instances on each call:
```
function useExpensive(...values: number[]) {
  return useMemo(() => expensive(...values), [values]); //  BAD: "values" will be a new instance each time
}
```

although likely correct, `exhaustive-deps` complains about this:
```
function useExpensive(...values: number[]) {
  return useMemo(() => expensive(...values), [....values]); // GOOD: "...values" provides individual values as deps
}
```

similarly, destructing rest also has questionable behavior:
```
function useExpensive2(values: number[]) {
  const [first, ...rest] = values;
  return useMemo(() => expensive(...rest), [rest]); // BAD: same as above, should likely be [...rest]
}
```

**Comment by vkurchatkin** [comment]
`exhaustive-deps` simply doesn't support deps with potentially dynamic length, since it's most likely a mistake in a normally situation. There are obviously  use cases for this, for example when you want your hook to have its own deps:

```js
function useMyCoolEffect(fn, deps) {
   React.useEffect(fn, deps);
}
```

`exhaustive-deps` won't allow this, but it is perfectly fine to disable this rule locally. Such cases should be very rare in practice, though.

In your case I would recommend a couple of things. 

1. Just don't do this:

```js
function useExpensive(...values: number[]) { 
```

do this instead: 

```js
function useExpensive(values: number[]) { 
```

Assuming you want to make things more efficient, it just makes more sense to memoize the whole `values` array on the top level and not to use `values` that potentially contains a lot of elements as deps.

2. The same thing here, just use `values` as a single dep:

```js
function useExpensive2(values: number[]) {
  return useMemo(() => {
    const [first, ...rest] = values;
    return expensive(...rest);
  }), [values]); 
}
```

**Comment by ehahn9** [comment]
Thanks. @vkurchatkin ! I hadn't considered the dynamic-length deps problem (in my case, the args *happened* to be fixed length). Makes perfect sense. Much appreciated!

ps: I wonder if eslint might warn us about using rest params in deps arrays, since the "auto-fix" seems bogus, too?
