### ISSUE TITLE
Bug: Possible solution to: unstable_flushDiscreteUpdates

### ISSUE THREAD

**Issue by dapabe** [facebook/react#24374]
This is the exact message: 
_Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering._

Being relatively new to ReactJS I've encountered this warning when I was using **focus** events, people say there is no problem on _production_ to. This comment offers a possible solution https://github.com/Availity/react-block-ui/issues/40#issuecomment-595438654 and so I reproduced his solution.

React version: 17.0.2

## Steps To Reproduce
Here I did the replicate of the bug on codesandbox
1. Click on the page, press F and watch the console.
2.Uncomment the useEffect on content.jsx, and repeat step 1.
![image](https://user-images.githubusercontent.com/65568682/163298830-4a69a9b8-743a-4445-b03f-700c556c0e40.png)

Link to code example: https://codesandbox.io/s/react-bug-unstable-flushdiscreteupdates-3bvmhl?file=/src/content.js

## My opinion
Please, feel free to correct any of my comments from here.

I think this issue is happening because you are trying directly manipulate a component by external means[1], meanwhile that **Component** is unchanged during it's current life cycle since it was mounted.

[1] I initialized a function(event listener) outside the component i'm directly manipulating, in **App.js**, _useKeyboard()_

## My solution
For my case, I wrapped the specific function causing this issue with an **useEffect**, so that _.focus()_ is applied when the component is finally mounted.

**Comment by rickhanlonii** [comment]
Yeah, you should not be calling focus in render so using `useEffect` is correct. There are many reasons for this, but the most practical is that the DOM element may not have committed to the screen yet, so there's no way to focus it on a new mount. It's also a side-effect in render, which is problematic to depend on because if the tree suspends we will re-run that side effect when we retry rendering.

The reason you see the warning "Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering." is because `focus` dispatches a discrete update to focus, but you're already inside a discrete update from the keyboard event, so the warning is correct even if somewhat obscure.

Closing because this seems like a questions and/or unrelated to React but hopefully this explanation helps!

**Comment by gaearon** [comment]
I also believe that the warning itself is gone in 18.
