### ISSUE TITLE
when to use useCallback and useMemo

### ISSUE THREAD

**Issue by Luncher** [facebook/react#24397]
I am a fan of React/hooks. As the usage scenarios in business projects gradually increase, I find the useCallback/useMemo hooks are a bit annoying. Whenever I use components developed by others, when I need to pass function props, I will wrap it with useCallback first. But it might work fine without the wrapping.

This can be divided into two cases, one is to avoid unnecessary re-render, and the other is to ensure the correctness of the logic. For example, useEffect depends on the incoming function props. Using too many useCallback/useMemo will make the code look bloated, and if you don't use it, you may be worried about bugs.

I learned what some developers in the community think:

> MOST OF THE TIME YOU SHOULD NOT BOTHER OPTIMIZING UNNECESSARY RERENDERS. React is VERY fast and there are so many things I can think of for you to do with your time that would be better than optimizing things like this. from kent C. Dodds.

I would like to ask the community if there are any suggestions for using useCallback/useMemo. It can reduce the mental burden when writing code. For example, is it possible to agree that useCallback/useMemo is usually not needed in the code? If it needs to be used, the component should be clearly stated, such as adding comments to props and so on.

**Comment by shamilovtim** [comment]
It depends on the codebase and how large the app is but in general if something is passed into props and is referentially unstable it needs useCallback and useMemo. React bloggers who advise against stabilizing props because "React is fast" and therefore "why not just let it rerender?" work on hobby apps and don't understand the performance problems that large React and React Native apps experience. When you're mounting thousands of components and animating them you will find that you can no longer "just let everything rerender" because "React is fast." You never hear about C programmers advising to use the largest variable type for everything and not bothering to GC because "C is fast so why bother with any optimizations" but it is common to encounter many of these strange opinions in the Javascript community.

**Comment by Luncher** [comment]
> I can only assume they must work on hobby apps and not understand the performance problems that large React and React Native apps experience

If performance problems are caused by re-render, some optimizations must be considered. What I want to express is whether we can consider delaying the packaging (optimization) process. In the development process, an effective convention can effectively improve the development experience and reduce the mental burden.
