### ISSUE TITLE
Bug: nested react instances failed in Safari

### ISSUE THREAD

**Issue by Holybasil** [facebook/react#24395]
In a nutshell, I need to have a nested tertiary structure, like:
```js
<div id="root"> 

// App.js
function App(){
  ...
  return (
    <div>
      ...
      <div id="parent" />
      ...
    </div>
  )
}

// Parent.js
function Parent(){
  return (
    <div>
       ...
       <div id="child" />
       ...
    </div>
  )
}

// Child.js
function Child(){
  return (
    <div>I am child</div>
  )
}
```
Then, mount them in order.
As stated [here](https://github.com/reactwg/react-18/discussions/5), 
```js
const apps = [
  { source: App, mountId: "root" },
  { source: Parent, mountId: "parent" },
  { source: Child, mountId: "child" }
];
function render(app) {
  const parentElement = document.getElementById(app.mountId);
  const root = createRoot(parentElement);
  const Source = app.source;
  root.render(<Source />);
  return new Promise((resolve) => {
     // requestIdleCallback is not allowed in Safari
    setTimeout(() => { 
      resolve();
    }, 0);
  });
}
...
for (const app of apps) {
    await render(app);
}
```
It is ok in Chrome but failed in Safari. I thought ChannelMessage and setTimeout work differently between Chrome and Safari after debugging. Has anyone had the same problem？
 
React version: 18.0.0

## Steps To Reproduce

1. just open in Safari. Note that because my example is so simple, it is less likely to fail, try as many times as you can.

Link to code example:
https://codesandbox.io/s/parent-child-react-v8u7oj

## The current behavior
![CleanShot 2022-04-18 at 20 47 56](https://user-images.githubusercontent.com/21138718/163813891-0b1c1b6e-49c7-48bb-afb2-a2963ee98d64.png)

## The expected behavior
render successfully just like in Chrome.

**Comment by gaearon** [comment]
As a workaround, you can use `flushSync` to force the element to be available immediately:

https://codesandbox.io/s/parent-child-react-forked-hezlbp?file=/index.js

In general, this is a non-idiomatic way to create a React tree. Idiomatically, you would pass the child components as props to the parent (or put them into context) so that they're rendered naturally as a single tree instead of imperatively.

**Comment by russellfoster** [comment]
> As a workaround, you can use `flushSync` to force the element to be available immediately:
> 
> https://codesandbox.io/s/parent-child-react-forked-hezlbp?file=/index.js
> 
> In general, this is a non-idiomatic way to create a React tree. Idiomatically, you would pass the child components as props to the parent (or put them into context) so that they're rendered naturally as a single tree instead of imperatively.

Question:

By "non-idiomatic", does this mean that nested instances set up using createRoot() are not officially supported? Reason I ask is because we are looking at creating and loading micro front-ends dynamically, and one way we can make this work would be to use nested createRoot() calls. Everything works OK but I would only seriously consider it if this is officially supported.
