### ISSUE TITLE
Bug: Using Strict mode outside Router breaks my app

### ISSUE THREAD

**Issue by BiancaArtola** [facebook/react#24451]
React version:
```
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^5.2.0",
```

## Steps To Reproduce

I am trying to add the StrictMode on my code to avoid issues, but when I put it outside the <Router history={history}> tag the routes changes as expected but the component does not render. When I moved the StrictMode tag inside the Router tag, the application works as expected. 

## Code example:

If I put the `StrictMode` outside the Router, the components does not render:

```
return (
    <StrictMode>
      <Router history={history}>
        <Route exact path="/">
                ....
      </Router>
    </StrictMode>
  );
};

```
If I put it inside the Router, the components renders as expected:

```
return (
   <Router history={history}>
     <StrictMode>
        <Route exact path="/">
                ....
     </StrictMode>
   </Router>
  );
};
```

## The current behavior
When the URL changes, the expected component is not being rendered on the UI.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/21174759/165537591-e882e4b2-fa3e-41e7-a043-39276eff46ab.gif)

## The expected behavior
When the URL changes, the expected component should be rendered on the UI.

Any idea of why this problem can be happening? Any ideas on how to fix this?

**Comment by gaearon** [comment]
We'd need a reproducing example (sandbox or a GH project) to know what's happening. It's hard to guess otherwise.

**Comment by BiancaArtola** [comment]
It's related to this issue: https://stackoverflow.com/questions/71832720/link-tag-inside-browserrouter-changes-only-the-url-but-doesnt-render-the-compo

Looks like the strict mode on _React v18_ is not compatible with _react-router-dom v5_. Is this a known issue? Are you going to fix that or you expected users to have react-router-dom on version 6 to use strict mode?

**Comment by gaearon** [comment]
The new behavior of Strict Mode in React 18 is intentional. As always with behavior changes, it is documented in the release notes: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

If the previous version of React Router is not compatible with the Strict Mode in React 18, then indeed, you’d need to upgrade React Router.

> Are you going to fix that 

I don’t see what is there to fix. If you can demonstrate a bug in React where the behavior doesn’t match what’s described in the upgrade post, please provide an example. Otherwise I think it’s safe to assume that the issue was on the React Router side and that it got fixed in v6.
