### ISSUE TITLE
Bug: Updaters are NOT called twice for the first time when in Strict Mode 

### ISSUE THREAD

**Issue by ssmkhrj** [facebook/react#24493]
React version: v18 & v17

## Steps To Reproduce

Consider the `App` component below that runs in **Strict Mode**:

```jsx
import * as React from "react";

export default function App() {
  const [count, setCount] = React.useState(0);

  const handleClick = () => {
    setCount((count) => {
      console.log("Clicked");
      return count + 1;
    });
  };

  return <button onClick={handleClick}>{count}</button>;
}
```
Link to codesandbox: https://codesandbox.io/s/react-bug-24493-snippet-1-6mrnyg?file=/src/App.js

Following things to note from the above example (_Similar behavior with both React 17 & 18_):
- Click the button once, `Clicked` log is only printed once--which means the updater ran only once.
- Click the button again, `Clicked` log is printed twice--which means the updater ran twice.
- And from second click onwards the log is always printed twice.

Now, consider another example, here the `reducer` (_which is another type of updater in React_) shows a similar bug where it runs only once the first time but from second run onwards it runs twice. And even more weird is that this time it only happens with React 17, with React 18 it always runs twice.

```jsx
import * as React from "react";
const log = console.log;

const reducer = (count, incrementor) => {
  log("Reducer ran");
  return count + incrementor;
};

export default function App() {
  const [count, setCount] = React.useReducer(reducer, 0);

  return <button onClick={() => setCount(1)}>{count}</button>;
}
```

Link to codesandbox: https://codesandbox.io/s/react-bug-24493-snippet-2-ulkvu4?file=/src/App.js

## The expected behavior
Expected behavior is that updaters should always be invoked twice (_even for the first time_) in both React 17 & 18 when in Strict Mode.

**Comment by Andrei0872** [comment]
Hi @ssmkhrj,

I'd like to share my perspective as to why those behaviours take place. In all cases, I've simply added a `debugger;` statement and then opened the _Sources_ tab in the Dev Tools. Note that all the following links to CodeSandbox are forked versions with a `debugger;` added.

---

Let's see what happens in the first [CodeSandbox app](https://codesandbox.io/s/react-bug-24493-snippet-1-forked-eiwwkt?file=/src/App.js)(`useState` + React 18):

```jsx
const handleClick = () => {
    setCount((count) => {
      debugger;
      console.log("Clicked");
      return count + 1;
    });
  };
```

Looking at the call stack, we can see `dispatchSetState` being called:
![image](https://user-images.githubusercontent.com/36248290/166821046-69164bc3-0353-4f28-9458-87ec28342fd9.png)

A few things worth mentioning:

* `fiber` is the current `FiberNode` associated with a React element(in this case, it's the `App` component)
* `fiber.alternate` points to another `FiberNode` and, based on my understanding, it's also the gist of how React's Virtual DOM is implemented; I also wrote about this in a [recent article](https://indepth.dev/posts/1501/exploring-how-virtual-dom-is-implemented-in-react)
* `scheduleUpdateOnFiber` will trigger an update on the `FiberTree` - in other words, the diffing algorithm will come into play; this means React will determine what changed and will commit everything at once on the real DOM

From the above image, notice that `fiber.alternate` is `null` and, based on my understanding, this indicates that React rendered **only once**. `fiber.alternate` is not `null` starting from the second render onwards. I went detail about these concepts in the linked article from above. 

So, since `fiber.alternate` is `null`, React will try to **compute the _eager state_**. Notice how  calling `lastRenderedReducer` will lead to calling the function from `setCount()`. So , here is why the console shows _Clicked_ once. **The reason this happens** is that React is trying to avoid an **unnecessary re-render** if the new value is that same as the old value.

Next, when React eventually determines the new value to be displayed, it will check first [if `eagerState` has been set before](https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L855-L858):

```jsx
        if (update.hasEagerState) {
          // If this update is a state update (not a reducer) and was processed eagerly,
          // we can use the eagerly computed state
          newState = ((update.eagerState: any): S);
        } else {
          const action = update.action;
          newState = reducer(newState, action);
        }
```

and if that's the case, it won't invoke the function provided to `setCount()`. And this is what happens indeed when one clicks the button for the first time. 

On subsequent times, because `fiber.alternate` is not longer `null`, `update.hasEagerState` will not be `true`, so the `reducer` function(i.e. `setCount()`'s argument) will be invoked. And since _Strict Mode_ is used, the `App` function will be invoked twice, meaning that the `reducer` function will be called once more.

My take on this is that React works properly - the `App` function will be invoked twice as a result of using _Strict Mode_, but it will use the eagerly computed state if the button is clicked for the first time.

---

Let's now see the [second example, which uses React 18 + `useReducer`](https://codesandbox.io/s/react-bug-24493-snippet-2-forked-xx44e1?file=/src/App.js):

```jsx
const reducer = (count, incrementor) => {
  debugger;
  log("Reducer ran");
  return count + incrementor;
};
```

From the call stack

![image](https://user-images.githubusercontent.com/36248290/166827408-980bfa94-39ff-4d38-9288-082f3274550d.png)

we can see that [`dispatchReducerAction`](https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L2160-L2194) is called **instead of** `dispatchSetState`. As shown there, `dispatchReducerAction` does not handle the _eager state_ case, as opposed to [`dispatchSetState`](https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L2199-L2277). 

However, an interesting fact is that both hooks(`useState` and `useReducer`) use the same function(i.e. [`updateReducer`](https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L754)) to determine the new state:

* [`useState`](https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L2466) - notice that it [uses `updateReducer` internally](https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L1529-L1533)
* [`useReducer`](https://github.com/facebook/react/blob/v18.0.0/packages/react-reconciler/src/ReactFiberHooks.new.js#L2464)

But, since `dispatchReducerAction` does not take into account the _eager state_ part, **only the second branch will be chosen every time**:

```jsx
        if (update.hasEagerState) {
          // If this update is a state update (not a reducer) and was processed eagerly,
          // we can use the eagerly computed state
          newState = ((update.eagerState: any): S);
        } else {
          const action = update.action;
          newState = reducer(newState, action);
        }
```

and this why the console logs twice on each click.

---

[The `useReducer` example with React 17](https://codesandbox.io/s/react-bug-24493-snippet-2-forked-teors9?file=/src/App.js):

![image](https://user-images.githubusercontent.com/36248290/166829600-67d4d9f5-c00f-41b5-9001-64727c366e49.png)

As you can see, there is no `dispatchSetState` nor `dispatchReducerAction`, but [`dispatchAction`](https://github.com/facebook/react/blob/v17.0.2/packages/react-reconciler/src/ReactFiberHooks.new.js#L1686), which is used in both [`useState`](https://github.com/facebook/react/blob/v17.0.2/packages/react-reconciler/src/ReactFiberHooks.new.js#L1143) and [`useReducer`](https://github.com/facebook/react/blob/v17.0.2/packages/react-reconciler/src/ReactFiberHooks.new.js#L656).

`dispatchAction` takes into account the possible _eager state_, so that's why the console logs only once when the button is clicked for the first time.

---

I'd say things work as expected since the `App` function is still called twice when using _Strict Mode_. The fact that the `reducer` function is not called multiple times is due to the eagerly computed state.

I don't know if the fact that `useReducer` does not handle the _eager state_ should be considered a bug, but if it is, I'd gladly try to work on it :).

**Comment by gaearon** [comment]
Wow, nice investigation! Thanks @Andrei0872.

Maybe it would make sense to make the "eager" update run twice in Strict Mode. (We removed eager bailouts from `useReducer` in 18, which is why it doesn't repro there.) Though if it doesn't bail out, then you have three renders which feels a tad much.

**Comment by Andrei0872** [comment]
Thank you, @gaearon!

I'm not sure why that would lead to three renders :thinking:, wouldn't there be only two unnecessary renders([in case it doesn't bail out, when it actually should](https://codesandbox.io/s/react-bug-24493-snippet-2-forked-qb2sde?file=/src/App.js))?
