### ISSUE TITLE
[DevTools Bug]: I believe that UI and UX from React DevTools is a big bug

### ISSUE THREAD

**Issue by ComaBerenices** [facebook/react#24511]
### Website or app

https://all.apllications.com

### Repro steps

Hello, community! ✌

I have an big question about the React DevTools, why is so different in comparasion with Vue DevTools ? all is more hard...

See the context, indentify the state's, the components.... 😒

In comparasion with Vue DevTools, the React DevToosl don't have a pretty and functional UI and UX. The context's, state's and components don't have a UI ogarnized  to easy indentification. On Vue DevTools there tabs to components, store (context's), events and some other features, see below:

![image](https://user-images.githubusercontent.com/92554215/167229861-13410a8e-74dd-4d6a-9b65-772e1beedbd0.png)

The vuex (context's in React environment)

![image](https://user-images.githubusercontent.com/92554215/167230399-5c5e7cfd-6431-4205-bec8-97a09191e84c.png)

Timeline of events 😍👍👍

![image](https://user-images.githubusercontent.com/92554215/167230442-44e2bbdf-00f6-42f8-aaa8-872c83fab05b.png)

### How often does this bug happen?

Every time

**Comment by bvaughn** [comment]
This isn't really actionable feedback. The React DevTools UI looks different from Vue DevTools UI because they are built to support different frameworks. There is not really any React equivalent for Vue's routing and data management libraries, so it doesn't make sense for dedicated routing or Vuex tabs.

Going to close this issue because it isn't actionable.
