### ISSUE TITLE
Bug: useEffect destory/cleanup section called on component render time

### ISSUE THREAD

**Issue by hupptechnologies** [facebook/react#24521]
- When component render that time it's executing useEffect clean code section also. It should be called on the page/component destroy time.  On the react v17* working fine. But after upgrade to v18.1.0 it's not working correctly.  

React version: 18.1.0

## Steps To Reproduce

1. npx create-react-app
2. Add below code snippet in any component
```
useEffect(() => {
    return () => {
      console.log('DESTROY CALLED');
    }
  }, []);
```
4. Run the application and check the log.
5. `DESTROY CALLED` log visible on the page load.

Code link: https://codesandbox.io/s/competent-bush-3hbdrm

## The current behavior
- `DESTORY CALLED` is calling from the component destroy lifecycle part on page/component load.

## The expected behavior
- `DESTORY CALLED` should  not trigger on the page/component load.

**Comment by cucunber** [comment]
Hi @hupptechnologies,
as I know, this issue comes from `<StrictMode />` component, which double-invoke functions that are expected to be idempotent [link to info](https://reactjs.org/blog/2022/03/29/react-v18.html#gradually-adopting-concurrent-features)

if you remove it from  **index.tsx** file, all will work as you expected

**Comment by xiaozhang119** [comment]
Don't use StrictMode

**Comment by gaearon** [comment]
This development-only behavior is expected in Strict Mode. See more about the extra checks:

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode
