### ISSUE TITLE
<input type="range" onChange /> fire too often

### ISSUE THREAD

**Issue by MoOx** [facebook/react#2454]
Like it's the case for input text, onChange should be triggered when user have finished interaction, don't you think ?
Right now, whenever I touch the range, I'm getting multiple change event (like window resize, it's crazy).
I think to be coherent with onChange behavior on input text, range onChange should be fired when user release the slider.

**Comment by spicyj** [comment]
Our plan here is to make onChange consistently fire on every change in all browsers; see #554. You can use `onBlur` or maybe `onMouseUp` if that's the behavior you're looking for, but the native onChange event varies widely across browsers even if we don't do anything special in React so that's probably not what you want.

**Comment by aldendaniels** [comment]
A quick test in recent versions of FF, Chrome, and Safari shows that Chrome, FireFox and Safari now have matching behavior: onInput fires while dragging the slider, onChange fires on release. I suspect it'd now make sense for React to also match this behavior.

Code pen: https://codepen.io/alden/pen/MWjMmyZ?editors=1111.

GIF: 
![Screen Recording 2021-01-24 at 10 25 23 PM](https://user-images.githubusercontent.com/4658558/105664929-188c8d80-5e93-11eb-856d-064696ea5be0.gif)
