### ISSUE TITLE
[DevTools Bug]: Chrome Devtools missing from Chrome extensions Webstore - 404 response

### ISSUE THREAD

**Issue by minaelee** [facebook/react#24549]
### Website or app

https://chrome.google.com/webstore/detail/react-developer-tools/

### Repro steps

The download page for the Chrome React Devtools extension returns 404. I checked the Firefox developer tools download page and that's still up.

### How often does this bug happen?

Every time

**Comment by stonedauwg** [comment]
Edge page is also still up, only affecting Chrome Web Store it seems

**Comment by WiLuX-Source** [comment]
> Edge page is also still up, only affecting Chrome Web Store it seems

Thank you!

**Comment by mondaychen** [comment]
We took it down because we discovered a bug (##24543) in a recent version. Unfortunately un-publishing it seems to be the only way to stop the bugged version from being automatically pushed to people, and the entire page disappeared from the chrome web store.
(I wish chrome web store could allow us to revert to an older version, but it doesn't)
We've submitted a new version with the bugfix to the Chrome Web Store, and the extension will come back online once the review process is done.

**Comment by mondaychen** [comment]
It's up again: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

**Comment by stonedauwg** [comment]
yes it is.  thanks for the help @mondaychen!

**Comment by minaelee** [comment]
Thanks @mondaychen!
