### ISSUE TITLE
Bug: Automatic batching not working unless I remove React.StrictMode

### ISSUE THREAD

**Issue by martinnajjar12** [facebook/react#24570]
Automatic batching is not working when the React.StrictMode component is there. If you remove it, Automatic batching will work as expected.
Even when not using any asynchronous event the component is still being re-rendered twice instead of only once.

React version: 18.1.0

## Steps To Reproduce

1. Create a new React app using create-react-app.
2. Create a component with 2 states inside of it.
3. Create a button that updates both states at the same time.

Link to code example: https://codesandbox.io/s/black-hooks-ri25xi?file=/src/App.js

## The current behavior
The component is being re-rendered twice

## The expected behavior
Automatic batching should take a place here and the component should only be re-rendered once.
If you remove React.StrictMode component from `index.js` file, it will work as expected.

**Comment by hamlim** [comment]
Batching is still happening, if you update your `console.log` call to also log out `clicked` and `count` you'll notice that they are both the new expected values after clicking the button, e.g.:

```js
console.log('Rendered!', { clicked, count });
// logs: 'Rendered! { clicked: true, count: 1 } twice
```

The reason you're seeing two logs happening though is because of strict mode, I'd refer to the release notes in this blog post for more details: https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

**Comment by martinnajjar12** [comment]
I understand now, thank you @hamlim :)

Closing this issue :)
