### ISSUE TITLE
Report problems from classes component in react version > 18.0

### ISSUE THREAD

**Issue by quangvinh0708** [facebook/react#24588]
When I build an app just for fun and testing something, and of course like a title, I build it with a class component with a full declaration of lifecycle methods, two of those caused problems are componentDidMount, and the component will unmount.

When the first-time component is mounted to DOM in the browser. Normally, componentDidMount will call after that and just once.
I tested it in React version > 16, it's still working above. But here now with React version > 18. I have found problems is componentDidMount run two times and even it call componentWillUnmount @@ ???. 
The order is: 
componentDidMount (1) 
componentWillUnmount ( just one time )
componentDidMount (2)

Thanks,
Vinh Do

**Comment by gaearon** [comment]
This is expected behavior (in development only) with Strict Mode on. Strict Mode is stricter in 18 and verifies your component is resilient to remounting with existing state. Normally, if your componentDidMount and componentWillUnmount calls are symmetrical, this shouldn’t cause observable issues.

https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

You can opt out of Strict Mode, but it’s recommended to keep it on.
