### ISSUE TITLE
Bug: React 18 + TypeScript upgrade, using renderProps now throws a TS error

### ISSUE THREAD

**Issue by GrossDesignCo** [facebook/react#24604]
After upgrading to React 18 (specifically, `@types/react`), we noticed that renderProps stopped working as they did in 17, now throwing TS errors, although it continues to work if we ignore them.

This could certainly be an issue with how I'm constructing our components, but it seems like a fairly common/workable pattern.

React version: 18.x

## Steps To Reproduce

1. Create a component that takes `children` as either a node or a function
   2. Component should be using `React.DetailedHTMLProps` for its types.
3. Attempt to pass a function into the component's children slot

Link to code example:

Barebones reproduction: https://codesandbox.io/s/react-typescript-forked-2hxp5o?file=/src/App.tsx

## The current behavior

Currently TS throws the type errors:
`This expression is not callable. Type 'never' has no call signatures.ts(2349)`

![CleanShot 2022-05-23 at 15 18 50](https://user-images.githubusercontent.com/5007574/169914237-72dfcf43-8a26-4fd1-a03c-13fa55984e06.png)

`Type '({ dummyProp }: renderProps) => JSX.Element' is not assignable to type 'ReactNode'.`

![CleanShot 2022-05-23 at 15 19 11](https://user-images.githubusercontent.com/5007574/169914240-c399c9af-f979-46d8-a5fe-0a3403b6b161.png)

## The expected behavior

TS should allow the developer to pass a function as a child.

**Comment by gaearon** [comment]
This is intentional behavior and fixes an issue: https://solverfox.dev/writing/no-implicit-children/

In your example, the `children` prop does not actually get checked. For example, here I'm passing a number as `dummyProp` with 17, and the compiler accepts it: https://codesandbox.io/s/react-typescript-forked-8q4hbc?file=/src/App.tsx

With 18 typings (and a fixed definition in your code), the compiler would flag the error: https://codesandbox.io/s/react-typescript-forked-rd5zkx?file=/src/App.tsx

As a side note, I would not recommend using FunctionComponent at all. You can type props directly instead like you would with any other function: https://codesandbox.io/s/react-typescript-forked-d08csy?file=/src/App.tsx

**Comment by GrossDesignCo** [comment]
Awesome, thanks @gaearon!
