### ISSUE TITLE
Is using a ReactFC's props.children.type to call it as a function has any unintended consequences? And if so why 

### ISSUE THREAD

**Issue by Alexandros84new** [facebook/react#24639]
Are there any negative consequences on rendering a functional component as a function (props.child can be any component), like so and if yes why?

```
import React from 'react';

interface Props {
  selected: number;
  index: number;
  child: React.FC;
  handleSelect: (index: number) => void;
}

const CarouselItem: React.FC<Props> = (props) => {
  console.log('props.child', props.child);
  return (
    <li onClick={() => props.handleSelect(props.index)}>
      {props.child.props.children.type({
        isSelected: props.selected == props.index,
        ...props.child.props.children.props
      })}
    </li>
  );
};

export default CarouselItem;
```

The code in question is:

```
     {props.child.props.children.type({
        isSelected: props.selected == props.index,
        ...props.child.props.children.props
      })}
```

Not only it works, but it allows me to pass isSelected as an additional prop to **any** child component, bypassing the React clone element [unknown prop warning issue](https://reactjs.org/warnings/unknown-prop.html).

I took the inspiration from [this stackoverflow question](https://stackoverflow.com/questions/69978496/react-functional-component-is-it-possible-to-pass-props-to-children).

I also opened [this issue](https://stackoverflow.com/questions/72404098/problems-with-react-cloneelement) on stackoverflow before deciding to ask for clarifications here, but to no avail.

Please let me know if this is sabotaging virtual DOM or its bad practice and why. It feels dirty yet it works.

**Comment by nmain** [comment]
The child component won't be considered as its own component, and instead will be rendered as part of the current component.

That is, the behavior will be similar to this:

```jsx
function helperFunctionMakesSomeVDOM() {
  return <div />;
}

function MyComponent() {
  return <div>
    {helperFunctionMakesSomeVDOM()}
  </div>;
}
```

...which is perfectly legal.

But, if this child function thinks it's its own component, it might call hooks, which will be handled as part of the parent component's hook set and so might run into conditional call or hook order problems.  And it won't show up in devtools as a separate component, because it isn't.

You should never do this with arbitrary components, as the creator might expect they'll actually be used as components and might sub out a hookless FC or a hooked FC or class component in the future.  I would recommend not doing it with your components as well, as it may surprise other authors:  Usually, the expectation is that when I write `React.createElement(MyComponent)`, then React is eventually going to render `MyComponent`; not that I'm going to "side-call" the `MyComponent` function later.

**Comment by gaearon** [comment]
We recommend to treat React elements as opaque wherever possible. So, reaching into `children.props.*` is not great.

The pattern you discovered is often referred to as "render props" and is best expressed as an explicit function as a prop rather than an element. E.g.

```js
const CarouselItem = (props) => {
  return (
    <li onClick={() => props.handleSelect(props.index)}>
      {props.renderItem({
        isSelected: props.selected == props.index,
      })}
    </li>
  );
};
```

Then you do `<CarouselItem renderItem={isSelected => ... } />`.
