### ISSUE TITLE
[react dev tools] errors + unresponsive to clicks

### ISSUE THREAD

**Issue by roy-s** [facebook/react#24638]
1) There are ofter errors relating to the addition of nodes to the store. Could this failure be more silent, and not completely hide the display?

2) When opening the react dev tools in a separate window, it does not respond to clicks or hover in the tree section. I can still click a component in the "rendered by" section. Note that this does not happen when the dev tools are opened in the same window. Update: it also didn't happen when I tried to put the two windows side by side in the same screen for a recording...

Please see the attached screen capture for both issues.

https://user-images.githubusercontent.com/10762244/170987263-73f45c4d-485a-4431-b01a-21de1fd4fbbf.mov

Thanks

**Comment by leidegre** [comment]
I noticed this today to. At first I thought it was due to high cpu usage or some infinite loop stuff but it happens as soon as you try to scroll the tree view. This makes it difficult to navigate up in the component tree.

(not sure if this matters but...) I'm on React 16.13.1 and the issue is consistent between dev and prod builds.

**Comment by Mathias-S** [comment]
Can confirm. When inspecting the devtools itself, I noticed that the div that lists the elements has `pointer-events:none`. When I remove that, it starts working as expected again.

* React 17.0.2
* Devtools version 4.24.6-ca7a38ae4
* Chrome 102.0.5005.61

**Comment by petermarkovich** [comment]
Confirm. After "Seelct element to inspect", sometimes clicking on the component tree does not working. Only restart chrome dev tools help me.
Chrome: 102.0.5005.63
React: 16.9.0
React dev tools: 4.24.6 (5/12/2022)
it refers to [№24626](https://github.com/facebook/react/issues/24626)

**Comment by rmartineztcti** [comment]
The proposed solution is about a flag that doesn't exist anymore in chrome://flags/

I'm having exactly this issue. All the React app is working well, I can see a certain React state changing but the menu that should react to that state doesn't open/close.

This only happens when dev tools is openend.
