### ISSUE TITLE
Bug: Support `Iterable | AsyncIterable` in `ReactDOMServerReadableStream`

### ISSUE THREAD

**Issue by tzachbon** [facebook/react#24675]
React version: 18.1.0

The new and cool `ReactDOMServerReadableStream` does not support any way to iterate over its values.
It makes converting it to a readable stream problematic when using Typescript.
Regardless, it became common to use streams and iterate them over the `on` method, which returns `AsyncIterableIterator`.

## current behavior

```tsx
import { Stream } from 'stream';
import ReactDOMServer from 'react-dom/server';

const reactStream = await ReactDOMServer.renderToReadableStream(<Component />);
const steam = Stream.Readable.from(reactStream); // Error - Argument of type 'ReactDOMServerReadableStream' is not assignable to parameter of type 'Iterable<any> | AsyncIterable<any>'.
```

**Comment by gaearon** [comment]
I'm a bit confused. (Sorry, I don't know streams very well, so bear with me.) Isn't `renderToReadableStream` for W3C streams? Whereas you seem to be using `stream` which is Node.js streams. I believe `renderToPipeableStream` would give you a Node.js stream.

**Comment by Jarred-Sumner** [comment]
The error you're seeing is that `ReadableStream` is not iterable, which is not specific to `ReactDOMServerReadableStream`

This is mostly an implementation issue for host environments (browsers, Node, Bun, etc). ReactDOM could subclass `ReadableStream` to add an async iterator implementation to work around it, but it'd be better for the host environment to fix it than React because they have more tools to make it performant

**Comment by polkovnikov-ph** [comment]
At the moment DX is garbage: I have a `vite.transformIndexHtml` (_because, well, why would you want a stream? isn't memory infinite?_), so I have to convert a stream (_because, well, who needs to have a consistent API that generates same stuff as a string and as a stream?_) from React into a string first, and it turns out that, unlike all the "modern" streams it's not even `AsyncIterable` (_because, well, who cares about TC39 and their stupid proposals that are in production since 2017?_)
