### ISSUE TITLE
Bug: SetState Async Unpredictability

### ISSUE THREAD

**Issue by john-larson** [facebook/react#24696]
It is known that by design, `setState()` call changes the actual state object in an async manner. And this causes an inconsistency in the state for a short while until the DOM is updated. So, accessing the state during this time will yield the old value. While it is possible to get the new state in an updater function or a callback, this seems counterintuitive, especially for the beginners. And it may cause latent bugs which are hard to debug.

Is there a reason why the state object is not updated by React beforehand? And if that is absolutely necessary (e.g. for diffing purposes etc.), wouldn't it be much cleaner to be able to access the latest state via may be a clone state such as `"this.targetState"` that is updated as soon as `setState()` is callled?

**Comment by markerikson** [comment]
There's no "inconsistency in the state".  An update has been _queued_, but the update does not get _applied_ until the actual render pass.

One reason for this is that it's possible that if we set state in component A, other state updates may also get queued that could result in component A's parent no longer rendering A any more.  In that case, component A needs to be unmounted, not updated, and there's no point in trying to update its state.

(Also, the way you're describing some of these aspects makes it sound like you're still using class components, rather than function components.  While the same basic answer I gave also applies to function components, note that there isn't any `this` in a function component, and it's also not necessarily a "state object".)

**Comment by huperniketes** [comment]
Is there any harm in decoupling the state update from the re-rendering logic? That is, move the code which updates state from the asynchronous function to setState()'s, and let the rest of the behavior remain as-is?

Would there be a significant performance drop as a result of decoupling when state is updated from when the DOM is? Negative performance from immediate state updates would be offset by current workarounds implemented to manage next state values and aggregating multiple sub-states into a single state change. Or perhaps there is some other impact this decoupling causes?
