### ISSUE TITLE
Bug: Script included multiple times on this page (Google maps API)

### ISSUE THREAD

**Issue by martyjg** [facebook/react#24721]
Hi, 
I'm trying to update react-dom from 17 to the latest (18.1.0). I used [use-places-autocomplete](https://github.com/wellyshen/use-places-autocomplete) previously to autocomplete addresses on a form. Using this package also involves loading a script as follows:

```
const GOOGLE_MAPS_URL = `https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_PLACES_API_KEY}&libraries=places&callback=initMap`
```

The script is then loaded in a useEffect:
```
  useEffect(() => {
    if (window.initMap) {
      load(GOOGLE_MAPS_URL, function (error) {
        if (error) {
          setIsError(true)
        }
      })
    }
  }, [])
```

And produces the following errors when visiting the page with the form:

> You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.

> TypeError: Cannot read properties of undefined (reading 'Iv')

And the form field autocomplete now does not work. Does anyone know why this might be?

React version: "18.1.0"

**Comment by martyjg** [comment]
It's related to StrictMode being on.

**Comment by ritwaldev** [comment]
This could be the billionth time this question is asked :)

This is expected behavior and only happens in dev mode (not in production build).

StrictMode will render component twice to make it easier to detect issues with impurity. 

See: https://beta.reactjs.org/learn/keeping-components-pure#side-effects-unintended-consequences
