### ISSUE TITLE
ContentEditable warning appears even without children

### ISSUE THREAD

**Issue by mczepiel** [facebook/react#2477]
When rendering:

```
render: function() {
    <span contentEditable={this.state.isEditing}>{this.state.value}</span>
}
```

Output:

```
<span contenteditable="true" data-reactid=".1msoq843u9s.1.$49.1.0">Hello World</span>
```

There is only a text node as a child of this span, no react components and yet I still receive the 

"A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional."

Is this expected?

**Comment by halt-hammerzeit** [comment]
@zpao No, you can't just ignore it because it's shouting it in your face by outputting an error in the console.

**Comment by jimfb** [comment]
@halt-hammerzeit You can rope it off from React (render an empty tag using React, attach a ref, and add a content-editable child in `componentDidMount`).

FWIW, my recommendation is to build (or use) a React component which implements the editable semantics you want.  It's unfortunate to be forced to implement what the browsers already have builtin, but you'll have a better end experience in the end, because you'll have an editable component that plays nice with a declarative framework like React.  Worth reading: https://medium.com/medium-eng/why-contenteditable-is-terrible-122d8a40e480#.aq2xacp42

**Comment by halt-hammerzeit** [comment]
@jimfb Oh, thanks, good thoughts, I'll have a read.

**Comment by MadebyAe** [comment]
@jimfb That post is so confusing... What about DraftJS? drops the same Warning.

**Comment by brickspert** [comment]
this work for me

```
render: function() {
    <span contentEditable={this.state.isEditing} 
       dangerouslySetInnerHTML={{__html: this.state.value}}
       onBlur={(e)=>{
            this.setState({
                 value:e.target.innerHTML
            });
      }} ></span>
}
```
