### ISSUE TITLE
Bug: React converts boolean data-attributes to `"true"` but leaves boolean attributes as `""`

### ISSUE THREAD

**Issue by franciscop** [facebook/react#24812]
React converts boolean data-attributes to `"true"`, while leaving boolean attributes as `""` (empty string). This is inconsistent with the way Javascript works and _also_ it's inconsistent from the way React treats attributes.

React version: 18.0.0

## Steps To Reproduce

1. Run [this CodeSandbox](https://codesandbox.io/s/fragrant-thunder-3dsi62?file=/src/App.js)

```js
import { useEffect } from "react";

export default function App() {
  useEffect(() => {
    // The React way:
    const input = document.querySelector("input");
    console.log("=== React ===");
    console.log("1", input.getAttribute("disabled"));  // ""
    console.log("2", input.getAttribute("data-disabled"));  // "true"

    // The Javascript way:
    document.querySelector(".base").innerHTML +=
      '<input class="injected" disabled data-disabled />';
    const injected = document.querySelector(".injected");
    console.log("=== Javascript ===");
    console.log("3", injected.getAttribute("disabled"));  // ""
    console.log("4", injected.getAttribute("data-disabled"));  // ""

    return () => injected.remove();
  }, []);
  return (
    <div className="base">
      <input disabled data-disabled />
    </div>
  );
}
```

2. Look at the console. This is what it returns:

```
=== React === 
1  "" 
2  true 
=== Javascript === 
3  "" 
4  "" 
```

This is what is expected:

```
=== React === 
1  "" 
2  ""    // <= different
=== Javascript === 
3  "" 
4  "" 
```

Link to code example:

https://codesandbox.io/s/fragrant-thunder-3dsi62?file=/src/App.js

## The current behavior

The `data-X` attribute, when it doesn't have a value, is coerced to `"true"`, a behavior that is not observed in plain Javascript (stays as `""`) and is also not observed with the way React treats plain boolean attributes (also stays as `""`).

## The expected behavior

The boolean attributes, both for plain attributes or data-attributes, behave in the same way. I don't know which one is "the right way", but surely treating them vastly different seems to be the wrong way.

Alternative: maybe this is the expected behavior? But I couldn't find any mention to anything related to this in the official documentation, please let me know if I missed it somehow or if this needs to be documented otherwise.

**Comment by franciscop** [comment]
The raw component tree (virtual DOM?) looks like this, so at this level the `selected` and `data-selected` look the same (this is from a different example):

```
pendingProps: {
  'data-id': '25',
  'data-selected': true,
  selected: true,
  children: 'Card'
},
memoizedProps: {
  'data-id': '25',
  'data-selected': true,
  selected: true,
  children: 'Card'
},
```

With a [forked CodeSandbox](https://codesandbox.io/s/eager-euler-8gr4di?file=/src/App.js), we can see the rendered HTML looks different from the parsed HTML from the string by the browser:

```
=== React === 
<INPUT disabled="" data-disabled="true"></INPUT>
1 "" 
2 true 
=== Javascript === 
<INPUT class="injected" disabled="" data-disabled=""></INPUT>
3 "" 
4 ""
```

**Comment by DuffyWang926** [comment]
I try to find the answer of first question：
<img width="768" alt="企业微信截图_1cbd0dd5-2320-4129-8beb-9c6b093e92ad" src="https://user-images.githubusercontent.com/31502024/176855188-7d62923a-707b-4358-9c44-f39251eee51c.png">
Because you don't set the value of ‘data-disabled’，so the react give the value ‘true’。
when react try to set property of Dom：
<img width="769" alt="企业微信截图_3d226130-36ce-4bd1-b42f-f029ffc51b11" src="https://user-images.githubusercontent.com/31502024/176855681-61f65a43-4172-4cb1-b525-fc58933c0e66.png">
Because ‘ disabled’ is the property of Dom，react reset the value to ‘’。
<img width="776" alt="企业微信截图_33370183-fd73-4c7d-80c3-230ea241deb9" src="https://user-images.githubusercontent.com/31502024/176855947-35414964-f53d-4b04-96cc-aa357b14881a.png">
Because ‘data-disabled’ is not the property of Dom，react set the value to ‘’ + rawValue。
That is the difference of react and javascript in your first question。

**Comment by ziavii** [comment]
I agree with the above clarification.

**Comment by savannah-yahsuanlin** [comment]
Sincerely,

*Savannah(Zi-Yuan) Lin*
*Software engineer*
Email:   ***@***.***>***@***.***
***@***.***>
LinkedIn: https://www.linkedin.com/in/zi-yuan lingered/
<https://www.linkedin.com/in/zi-yuanlin/>

**Comment by otomad** [comment]
Sorry, but this is bothering me.

I have to use `data-disabled={disabled ? "" : undefined}` to keep the functionality up and running.

Since I'm using `[data-disabled]` selector in CSS, if that's the case now, I'd have to write `[data-disabled="true"]`, which would be more cumbersome.

If I really need to convert to a string, I should manually call `disabled.toString()`, instead of automatically implicitly converting like this.
