### ISSUE TITLE
Possible Suspense bug

### ISSUE THREAD

**Issue by bvaughn** [facebook/react#24864]
I think I've trapped a bug where– after React suspends and the data has resolved, React bails out before re-rendered some of the Suspended components. (It's possible the bug is in my Suspense cache logic. I realize I'm working with un-finalized APIs.)

Here is a Loom walk through of the code in question:
https://www.loom.com/share/e356cf5d261e49f4b9f724a123349db9

Here is a Replay recording of the bug with annotations from myself and @Andarist:
https://app.replay.io/recording/cffed6a1-297e-428c-83a6-3a86451d0128

To reproduce the bug directly:
1. Checkout Replay commit [`22a07dbb294e0381d371cb744ac1ea2031edf9d6`](https://github.com/replayio/devtools/commit/22a07dbb294e0381d371cb744ac1ea2031edf9d6)
1. In the main directory run `yarn install`
1. In `packages/bvaughn-architecture-demo` run `yarn dev`
1. Open localhost:3000/tests/object-inspector and scroll down until you see "Loading..." (below the entry containing "htmlElementWithAttributes")

cc @acdlite who seemed interested in looking into this sometime (obviously no hurry) 😄

**Comment by Andarist** [comment]
You mentioned during this latest loom that we've previously got to `bailoutOnAlreadyFinishedWork` - I realized later that this particular bailout could have been unrelated. I only checked that the first `workInProgress`/`current` (?) that is being worked on after the "ping" was bailed out like this *but* that unit of work could have been something entirely else, after all, React doesn't have to immediately work on our "pinged" work. That bailed-out work was related to some Suspense component though. I have trouble navigating those structures and correlating them between concrete instances of components though so I couldn't easily read through it to check which component in the hierarchy this was related to.

One thing worth noticing is that on both recordings we have a somewhat similar situation - the same component suspends again after being resumed in response to a suspense "ping" (so it resuspends itself).

**Comment by Andarist** [comment]
Ok, so I've cracked this case 🎉 

1. we throw wakeable in a component
2. React has to unwind the work, and in the process sets `DidCapture` on the fiber that represents this `Suspense` **and** sets this fiber as `workInProgress` (so it will be worked on next, presumably to work on the fallback UI)
3. we get back to `workLoopConcurrent` but it turns out that **it's time to yield**
4. the wakeable resolves and pings the `Suspense`
5. we get back to `workLoopConcurrent`, working on that `workInProgress` for this `Suspense` - it sees `DidCapture` and thus it computes `didSuspend` as `true` and goes into a conditional block that sets `showFallback` to `true` and that removes `DidCapture` from the workInProgress ([here](https://github.com/facebook/react/blob/82e9e9909876591dbe808cdac7110610e63c3896/packages/react-reconciler/src/ReactFiberBeginWork.new.js#L2094-L2104))
6. and we never get back working on this `Suspense`, to work on its primary children. The additional important bit is that in this case `then` method of the wakeable **doesn't** resolve call the received callbacks in its resolved state. If it did then the work would be retried based on retry listeners attached from `finishConcurrentWork`->`commitRoot`->`commitMutationEffects`->`commitWork`->`attachSuspenseRetryListeners ` ([here](https://github.com/facebook/react/blob/8e35b5060875c875f468878f94bc3c0d7d45c52d/packages/react-reconciler/src/ReactFiberCommitWork.new.js#L2012))

So the question is if it's even a bug in the first place - this particular wakeable doesn't fully behave in the "standard" way when it comes to the behavior implemented in its `.then` method. OTOH, it did ping successfully React but React failed to process this ping correctly due to a race condition.

**Comment by bvaughn** [comment]
Great detective work, @Andarist!
