### ISSUE TITLE
 Why imperative code using refs should be avoided?

### ISSUE THREAD

**Issue by dante01yoon** [facebook/react#25017]
Hi, in few weeks, I found `useImperativeHandle` is quiet handy for 
 - encapsulation how child component state changing logic  implemented, no event handler needs to pass down to child component when using this hook.
 - ref can be defined using typescript interface in child component , which that's all parent component should know.
- in the same manner of first one, parent component doesn't filled with complex logic functions, which gives parent component more readability nonetheless it can still use tens of child components.

but [document](https://reactjs.org/docs/hooks-reference.html#useimperativehandle) says using `useImperativeHandle` should be avoided in most cases?
I can't find reason

**Comment by vkurchatkin** [comment]
React is built with declarative reactive approach to UI. Thus imperative approach using refs is in many cases is simply not idiomatic React. It is included as an "escape hatch" and should be used if declarative approach fails completely or is somehow unreasonable.

For example, using imperative API for focus is acceptable because focus is managed by the browser and building declarative solution for focus management seems unreasonably complicated:

```js
const ref = useRef();

return <>
  <MyInput ref={ref} .../>
 <MyButton onClick={() => { ref.current?.focus() } } ...>
</>
```

On the other hand, doing the exact same thing for showing a modal dialog is not idiomatic and should be avoided:

```js
const ref = useRef();

return <>
  <MyModal ref={ref} ...>{content}</MyModal>
 <MyButton onClick={() => { ref.current?.show() } } ...>
</>
```

Why? Because declarative solution is simple:

```js
const [isModalVisible, setIsModalVisible] = useState();

return <>
  <MyModal isVisible={isModalVisible}>{content}</MyModal>
 <MyButton onClick={() => { setIsModalVisible(true) } } ...>
</>
```

**Comment by dante01yoon** [comment]
@vkurchatkin thank you for your comments. I agree declarative is suitable for react, and that is what react  aiming for.
So it's all about coding styles, not a performance issues ?

**Comment by mattoracz** [comment]
Hi @dante01yoon, @vkurchatkin Do you currently have any additional thoughts since then?

I still disagree with the last point of the new documentation regarding the use of "useImperativeHandle" as inappropriate.

I found a [valuable article](https://dev.to/teetotum/modalopen-imperative-component-api-in-react-3inc) that is close to my thoughts. I would especially like to highlight the fact:
* no state redundancy, component stores the state and allows read and write by parent.
* encapsulation
* independent - no need to add duplicate state to parent each time. (we can easily imagine it with inputs) (useRef value - may be a solution, but it will be adding child's logic to the parent.
* parent component can only contain own logic and control the subordinate ones
* can be fully reusable
* less state updates - less rerenders
* all dependent logic is inside component
* minus: It is "imperative", which contradicts the main react assumptions.

Using props is perfectly fine, but referring to this example from the beta documentation, why adding the state to the parent is better than storing that value inside?
<img width="932" alt="Zrzut ekranu 2023-01-27 o 12 25 28" src="https://user-images.githubusercontent.com/76013983/215075196-d4d12ef7-1c06-47d0-b258-a8e351857f15.png">
source: https://beta.reactjs.org/reference/react/useImperativeHandle
change my mind.

**Comment by dante01yoon** [comment]
@mattoracz thank you for comment! I'm happy to find someone can share this topic at last.
Among you mention the pros of `useImperativeHandle`, I think `encapsulation` is the big one. 

while passing props or handler to child from parent component should be managed from parent component, which can be verbose in some situation, also it doesn't feel intuitive when you  just need some of child state changed or not. In reactive way, you should always write some logic or state manage things from outside and inject through props which child component allowed. This is not quiet handy. 

I think useImerativeHandle is quiet underrated among the hooks.

**Comment by dante01yoon** [comment]
@mattoracz  Did you remove your comment in https://github.com/reactjs/reactjs.org/issues/3308

**Comment by QuietNoise** [comment]
In 99% cases I've found imperative handle avoidable and if anything props passing and useContext can solve much of the parent <-> child communication that your app might need. This will make your app to be always deterministic.

However, in rare cases you might find child components to be so disjointed from the app - yet their state in need to be influenced or determined by unspecified parent that imperative approach is the only sensible way.

**Comment by rooneyhoi** [comment]
`useImperativeHandle `is useful when you want to build UI animation with multiple step, ie. the user's walkthrough steps. If you have 4-5 small component and try to show/hide, then moving fast and slow base on step by step, then using state/props will be a disaster. That's why it was born for purpose.

**Comment by teetotum** [comment]
@mattoracz Thank you for linking to my article. Yes, I believe `useImperativeHandle` is quite a useful thing to have and I still consider it suitable for modals and such. But I had a little journey of further insight during one of my last projects that made me better understand the warning and the general advise to use declarative.

I had to implement a feature that would open a popup when something was clicked.
The click would only act as a trigger to open the popup, so there was no further state involved (nothing to connect clicked thing and open popup).
I implemented it using the imperative approach.
Some time went by and requirements changed. Now the clicked thing should be highlighted as long as the popup is open.
The imperative approach was not suitable anymore because now there was state for `selectedThing` and `show popup as long as thing is selected` and `de-select thing when popup is dismissed`, so I had to change it to declarative which was now better suited.

It made me realize that it depends on the circumstances of the usage of a component whether imperative or declarative is better suited for things like the `open` state of a modal. And a component author usually has no crystal ball to predict which approach will be needed in the future.
So it makes sense to offer declarative props for anything that can be expressed declaratively - to cater to those circumstances of usage when declarative is more suitable.
And additionally offer an imperative approach - to cater to those circumstances of usage when imperative is more suitable.

So maybe the best of both worlds is reached with a dual approach - I believe that's called `controlled` and `uncontrolled`.
In the `controlled` case the parent manages the state for the component.
In the `uncontrolled` case the component manages its own state internally.
The component can check for certain properties to be present or absent on the `props` object to determine whether it is rendered in the controlled or in the uncontrolled cased: `const isUncontrolled = props.isOpen === undefined;`

**Comment by bogdanudrescu** [comment]
@mattoracz, @teetotum Thank you so much to both of you. I can not be that objective because most of my experience is with oop, however if I may, an imperative solution for the button selection state in synch with the open state of a modal may be a callback. What I'm trying to achieve now is exactly the Modal show but with dismiss from inside, thus if I use a state created by parent I need to pass the full state object, i.e. state and setState, to the Modal. I find this very awkward, unless someone can clear it up.

But there is still a question which @dante01yoon kind of asked: is there "a performance issues" in using useImperativeHandle? This I'd be very much interested in.

**Comment by rickhanlonii** [comment]
There's no notable performance issue. The note to avoid overusing refs is because as an app scales it makes it difficult to reason about where changes are coming from. Sticking to props allows you to reason about your app in a unidirection top-down declarative way, which is easier to reason about. That is what makes React, React.

Here's a good article on it: https://blog.logrocket.com/why-you-should-use-refs-sparingly-in-production/

That being said, it's just a pitfall we've seen that we think is worth warning about. If it works for you, do it!
