### ISSUE TITLE
Bug: Error: Should have a queue. This is likely a bug in React. Please file an issue.

### ISSUE THREAD

**Issue by hawkyre** [facebook/react#25012]
React version: 17.0,2

## Steps To Reproduce

I'm rendering a useMemo that takes its value from a function that contains a hook (the hook uses recoil to manage global state) and switches its input to generate the component, then I have a useState that handles a boolean value. If I invert the order, another different error is thrown, saying that the number of rendered hooks is fewer than expected.

Link to code example:
https://pastebin.com/K134AmZ2

![image](https://user-images.githubusercontent.com/50209142/181905787-12e33f66-6397-4015-adcf-854ecff86a91.png)

## The current behavior
Throws an error

## The expected behavior
Handles the useMemo and useState properly

**Comment by eps1lon** [comment]
Thanks for the repro.

I took the liberty and reduced it further so that we can reproduce without 3rd party dependencies: https://codesandbox.io/s/intelligent-joliot-qz4xfo

However, this is expected behavior. You can't call hoks from within other hooks. You should see a warning in your console similar to "Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks. " before that error is throw.

The error message is a bit unfortunate though I can't reproduce it specifically. Could you expand on the linked codesandbox so that we can reproduce this specific message?
