### ISSUE TITLE
Bug: "Destroy is not a function" doesn't get caught by Error Boundary 

### ISSUE THREAD

**Issue by melissarofman** [facebook/react#25050]
Framer is a site builder where users can write and put third-party React components on their pages. Those components can have incorrect implementations, including incorrect usage of `useEffect`. When we upgraded to React 18, we started running into crashes which turned out to be due to incorrect returns in useEffects. 

Since we know these components can have errors, we've implemented an error boundary around them. But this change in how React 18 handles incorrect returns in useEffect (E.g. returning a number instead of a function) doesn't get caught by the Error Boundary. Instead, React fails internally and stops rendering.

We've created a Sandbox with a small reproduction case: https://codesandbox.io/s/serene-cloud-j665f0?file=/src/App.js. There you can find: 
1. An example of a component with a traditional user error -> Caught by the error boundary
2. An example of a component with a mis-implemented useEffect -> Not caught by the error boundary

React version: 18

## Steps To Reproduce

1. Create a component with a useEffect that returns a number and a dependency on local state
2. Wrap it with an Error Boundary
3. Update the local state so the useEffect runs again
4. See the crash and it skipping the error boundary
Or use the sandbox I linked above :) 

Link to code example: https://codesandbox.io/s/serene-cloud-j665f0?file=/src/App.js

## The current behavior
Error is not caught by Error Boundary

## The expected behavior
Error is caught by Error Boundary

**Comment by blixt** [comment]
I dug into workarounds for this issue and found a few more interesting behaviors that may be relevant to other people running into this. (Note: I do still think the breakage from React 17 to React 18 is a regression worth looking into fixing, especially since it happens when using legacy `ReactDOM.render` which "behaves as React 17".)

* Some cases of the crash and unmount of React can be prevented by having the error boundary implement `getDerivedStateFromError` to update state before the boundary re-renders, giving it a chance to not crash a second time (which unmounts React), but this means giving up a lot of information
* There's no way that I've found so far to catch a `useEffect`'s destroy crash before a full re-render meaning that if the error boundary is unmounted together with the crashing component (for example, it could be a `CustomModal` component that's the error boundary, with a bunch of `children` inside of it that can crash, so closing the modal would crash and unmount React)
* The only way to reasonably catch these errors seems to be to have error boundaries that linger in the React tree, but return `null` (so they exist in the tree and can catch the error when it finally bubbles up), meaning the developer of the React app needs to track unmounts themselves, and clean up these "ghost" components over time

This all stems from things seemingly happening roughly in this order during a render pass:
1. Run render functions, mounting new components
2. Unmount old components no longer in tree
3. Run `useEffect` destroy functions of old components
4. If a crash is caught, bubble it up to the closest (still mounted) class component with error boundary

Because (2) happens earlier than (4) instanced error boundaries aren't really possible without the workaround described above.
