### ISSUE TITLE
using startTransition for textarea => ctrl+z not working and typing jumps to end

### ISSUE THREAD

**Issue by mp3846** [facebook/react#25099]
[CodeSandBox](https://codesandbox.io/s/goofy-hooks-kdh9g7?file=/src/App.js)

write some text and try to undo using ctrl+z, it does not work
go to middle of sentence and start typing, it will jump to end after typing one character!

**Comment by gaearon** [comment]
This is expected because controlled components must update the state that drives them synchronously. So using a transition for the controlled value would not work. You can, however, set two separate states, and use transition for the other one (eg to drive a list of items or similar). Another pattern you can use is useDeferredValue which lets you do the same thing with a prop received from a parent component.
