### ISSUE TITLE
Bug: createRoot with DocumentFragment does not render to dom

### ISSUE THREAD

**Issue by whatwg6** [facebook/react#25101]
React version: 18.2.0

## Steps To Reproduce
```js
import { createRoot } from "react-dom/client";

const root = document.getElementById("root");
const fragment = document.createDocumentFragment();
root.appendChild(fragment);

const browsers = ["Firefox", "Chrome", "Opera", "Safari", "Internet Explorer"];

const App = () => browsers.map((browser) => <div key={browser}>{browser}</div>);

createRoot(fragment).render(<App />);

```

Link to code example:

https://codesandbox.io/s/react18-createroot-documentfragment-qhoxog

## The current behavior

does not render UI

## The expected behavior

render UI

**Comment by eps1lon** [comment]
This is expected behavior as in this is how `DocumentFragment` is supposed to behave.

Once appended to the document you cannot add more children to the fragment. 

> Doing this moves the fragment's nodes into the DOM, leaving behind an empty DocumentFragment.

-- https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment#usage_notes

So you were moving the current (i.e. none) children of the fragment into the DOM and only **after** that was React rendering into the fragment.

You have to render into the fragment first, and then append it:

```diff
+// Need to render syncronously so that the fragment is appended AFTER the initial render
+flushSync(() => {
+  createRoot(fragment).render(<App />);
+});

 root.appendChild(fragment);
-createRoot(fragment).render(<App />);
```

Does that make sense?

**Comment by eps1lon** [comment]
> Thanks. It is different from react 17.

React 17 has the exact same issue: https://codesandbox.io/s/react17-render-documentfragment-forked-3o5jdx

It's not an issue with React but the order of "rendering React App into DocumentFragment" and "append DocumentFragment to DOM".
