### ISSUE TITLE
SetState breaks ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/react#2522]
If `setState` is called during a transition, the transition breaks with a flash.

**Comment by miklschmidt** [comment]
I currently have the same problem. It happens even if there's no subtree modifications. My totally uninformed guess is that there's some kind of state in the CSSTransitionGroup that goes wonky.

**Comment by miklschmidt** [comment]
i thought i had the same problem. Turns out i had a container that removed the animating node and reinserted it into the DOM. Try breaking on subtree modifications or node removal, if you can find the right node that get's removed. I do several setState during my transitions, and it works fine as long as the new state doesn't modify the DOM tree of the animating node. If this is in fact what's happening, and the state shouldn't require any dom modifications to that specific part of the tree, try adding a key to the element containing your transition group.

Hope it helps.

**Comment by gaearon** [comment]
>Try breaking on subtree modifications (or node removal, if you can find the right node that get's removed)

+1, it's very useful tool when debugging reconciliation weirdness.

**Comment by spicyj** [comment]
This isn't actionable as-is; if you're still having trouble please post a minimal repro.
