### ISSUE TITLE
Removing tabIndex from component's attributes does not remove tabIndex once set

### ISSUE THREAD

**Issue by mczepiel** [facebook/react#2528]
Once a tab index has been put in place "removing" by the method seen below only ever sets it to -1, which does what I'd expect in that the element isn't focused when tabbing, but it is still focusable by clicking directly on the element.

```
var attributes = {}
if (this.props.focusable) {
  attributes.tabIndex = 0;
}

return React.createElement("div", attributes, "test");
```

**Comment by globexdesigns** [comment]
I am having a very similar issue with the `pattern` attributes as well. The code is something like this:

`<Input pattern={this.state.hasPattern ? '^((?!@).)*$' : undefined} />`

When I disable the `hasPattern` state, the pattern is set the "undefined" string instead of removing the `pattern` attribute from the DOM element. This results in a broken input field.

Similarly, I tried this approach. It didn't work either:

```
var inputProps = {};
if (this.state.hasPattern) inputProps.pattern = '^((?!@).)*$';
<Input {...inputProps}/>
```

Still -- the `pattern` attribute is not removed from the DOM element.

**Comment by kidwm** [comment]
I have the same problem with `pattern` attribute not be removed after DOM updated.

**Comment by formula349** [comment]
This is frustrating. I have a <table> that can have editable cells. Once a <td /> element has a tabIndex prop set to 0 so it can be focused, removing the tabIndex doesn't remove it from the DOM but sets it to -1. This does remove it from the tab order, but still allows focus with the mouse.

Is there any way to remove the tabIndex attribute once it's been set?

**Comment by syranide** [comment]
@formula349 `key` can be used for now... and possibly should be in your case (hard to say without more info). Anyway, there's some movement now on #1510.

**Comment by formula349** [comment]
Yes, thank you I will use that for now

**Comment by loganfuller** [comment]
@syranide I'm running into the same tabIndex issue. What do you mean by "```key``` can be used for now"? 

On 0.13.3 the corresponding DOM node for a component which once had the tabIndex prop set but later had it removed will have its tabindex attribute set to -1. Setting a unique key on the component doesn't seem to change anything.

**Comment by syranide** [comment]
@loganfuller Something like `<a tabIndex={tabIndex} key={'foobar:' + tabIndex} />`

**Comment by loganfuller** [comment]
@syranide Ah, I see, to force the creation of a new DOM element.

That would work, but I integrate with a third-party library on mount that would be expensive to re-initialize any time the associated DOM component is changed.

I can add an extra wrapper with a static key to handle the integration, but wouldn't it be more performant to manually ```removeAttribute``` on the DOM element when the component updates rather than forcing the creation of a new one?

**Comment by kidwm** [comment]
@loganfuller You can try https://github.com/Olical/react-faux-dom with that third-party library, maybe it helps.

**Comment by syranide** [comment]
> I can add an extra wrapper with a static key to handle the integration, but wouldn't it be more performant to manually removeAttribute on the DOM element when the component updates rather than forcing the creation of a new one?

That requires a bit more manual work, but that is the best workaround yes.

**Comment by danez** [comment]
Maybe this changed recently, but I just tried this and it worked perfectly fine. tabindex was either there and set to '0' or in the other case it was not there.
```
tabIndex={selected ? '0' : null}
```

**Comment by syranide** [comment]
Which version of React are you using? Should be fixed in v15

Andreas Svensson, CTO, Cetrez
M: +46 736 80 83 28

Sent from iPhone

On 27 Jun 2016, at 09:10, Daniel Tschinder <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe this changed recently, but I just tried this and it worked perfectly fine. tabindex was either there and set to '0' or in the other case it was not there.

tabIndex={selected ? '0' : null}


-

**Comment by gaearon** [comment]
My understanding is this has been fixed.
If not please raise a new issue.
