### ISSUE TITLE
idea : support object literal property value shorthand in jsx syntax

### ISSUE THREAD

**Issue by bloodyowl** [facebook/react#2536]
the idea would be to be able to do : 

``` javascript
{this.state.list.map((item, key) => <MyComponent {item, key} />)}
```

what would you think of it ?

**Comment by nojvek** [comment]
https://github.com/facebook/jsx/pull/118

^ A proposal for the object expression syntax as discussed here.

> I think that the difference between <Foo {item} />, <Foo {...item} /> and <Foo item /> might be too confusing. 

Confusion might be relative. <Foo item /> is not very useful since it always evaluates to {item: true}. In hindsight it feels very limited, but I can understand it's behavior from it's html genes. I personally haven't found a use for it.

<Foo {item} /> and <Foo {...item} /> aren't confusing if you look at it from ES8 object notation perspective. `{item}` is shorthand for `{item: item}`.  `{...item}` is shorthand for flatten / shallow copy/ spread into a new object.

once someone understands that jsx transpiles to `h(name: string | Component, props: {[name]: any}, ...children)`. ObjectExpression falls in naturally.

It's confusing that `<Foo {x} />` is not supported but `<Foo {...x} />` is supported. The workaround is
`<Foo {...{x}} />`  which is a lot more confusing.
