### ISSUE TITLE
Throw error on wrong input to dangerouslySetInnerHTML / dangerousInnerHTML

### ISSUE THREAD

**Issue by xixixao** [facebook/react#2542]
Not passing in __html fails silently (checked on the website). That makes its use incredibly hard to debug (if you forget the __html). It should throw an error instead.

**Comment by spicyj** [comment]
We might make warnings louder in general, but we're moving more towards warnings so that the prod build can skip unnecessary checks, so I'm closing this.

**Comment by appsforartists** [comment]
@spicyj - could we keep it open and change the request to a warning?

**Comment by spicyj** [comment]
Sorry, I actually misunderstood this and thought from the description that there already was a warning. I actually just checked and there was an error added at about the same time this issue was filed, so this is actually fixed:

https://github.com/facebook/react/commit/aef7c4d1a16133f2f6d3ae3bfd18f01f8fc1403b
