### ISSUE TITLE
Bug: Concurrent mode does not improve page jank

### ISSUE THREAD

**Issue by jeremies** [facebook/react#25562]
React version: 18.0.0

## Steps To Reproduce

1. Open web page https://9bzvbl.csb.app/
2. Enter number 2 on the input

## The current behavior

Look how the FPS at top left corner decrease to a low number (depending on your CPU, you can increase the list length if you don't see low FPS)

## The expected behavior

The FPS remain stable on 60 FPS because rendering of the long list is wrapped in startTransition so React should give preference to not produce page jank. And do the rendering with less priority.

Web page is based on this code: https://codesandbox.io/s/react18-usetransition-forked-9bzvbl?file=/src/useTransition/UseTransition.jsx

I know that using react-virtualized, for example, you can overcome performance problems on long lists. But if you have low tech hardware like smart tvs the performance of the web page is a priority and simple rendering of short lists produce page jank.

**Comment by hawx1993** [comment]
a good solution to splitting UI and business logic, see: https://github.com/hawx1993/hooks-view-model

**Comment by jeremies** [comment]
> a good solution to splitting UI and business logic, see: https://github.com/hawx1993/hooks-view-model

@hawx1993 Shall you fork the codesandbox using your hooks-view-model package to see the improvements on performance?

**Comment by sarimarton** [comment]
> a good solution to splitting UI and business logic, see: https://github.com/hawx1993/hooks-view-model

This is off-topic. The React team released concurrent rendering with no actual capability of Dan Abramov's [clock demo](https://youtu.be/nLF0n9SACd4?t=444). The docs [mention](https://beta.reactjs.org/reference/react/startTransition#caveats) that lo-prio updates are batched for now, which means there's no way to flush out stale components, which is the point of the whole thing. 

> If there are multiple ongoing transitions, React currently batches them together. This is a limitation that will likely be removed in a future release.

which effectively means that the current state of concurrency in react is officially barely more than a debounce. But it's not even that, because de-prioritization doesn't even work at all. That demo was 4 years ago, React 18 was released a year ago or so, and people don't realize that the released API _doesn't do anything_. This is, sorry to say, but pretty hilarious.

**Comment by sarimarton** [comment]
Another test:

https://codesandbox.io/s/concurrency-clock-demo-stgk78?file=/src/App.js

**Comment by jeremies** [comment]
>Dan Abramov's [clock demo](https://youtu.be/nLF0n9SACd4?t=444).

Thank you for your answer @sarimarton it was pretty clear to understand the current state of concurrency on react 18

**Comment by sarimarton** [comment]
bump
