### ISSUE TITLE
Extend nested default props instead of overwriting

### ISSUE THREAD

**Issue by jmullo** [facebook/react#2568]
It's very convenient to have props in a nested structure. However...

Let's assume I have some default props:
```
getDefaultProps: function() {
    return {
        aaa: true,
        bbb: true,
        ccc: {
            first: false,
            second: false,
            third: false
        }
    };
}
```

Now, if I initialize the component giving it these props:
```
{
    ccc: {
        first: true
    }
}
```

...the component won't get ccc.second or ccc.third at all. The preferred result would of course be:
```
{
    aaa: true,
    bbb: true,
    ccc: {
        first: true,
        second: false,
        third: false
    }
}
```

Or perhaps make the behaviour selectable by adding a PropTypes option, like:
```
.isRequired.useDefault
```

**Comment by spicyj** [comment]
Your proposed alternative with the CustomButton as a wrapper is good. In general we don't want to do deep merges because your props could look like anything – they're not necessarily plain JS objects that can be automatically merged. As such, I'm closing this out.

**Comment by aug-riedinger** [comment]
I know the issue has been closed, but I'd like to discuss this a little bit more.

I just asked about it: http://stackoverflow.com/questions/29194997/react-nested-defaultprops-deep-merge

I understand your reasons for not to make a deep merge. But I reckon there could be few other possible behaviors:
- passing DeepMerge as an option to component, or to component props behavior options.
- making an exception when the proptype is a `React.PropTypes.shape` with the matching attributes (like the `track` props in my [SO question](http://stackoverflow.com/questions/29194997/react-nested-defaultprops-deep-merge)). In that case, we could expect the prop to behave expectingly, right?

What do you think?

**Comment by renet** [comment]
Sorry for the late reply, hope this is accepted here. 

@aug-riedinger I agree with you on the 2nd behavior. Using shape as a PropType, I'd assume that a deep merge for this very prop is expected. But I can also imagine cases, where a deep merge is explicitly not wanted (for example, if you have two props depending on each other - I already came across that case).

Maybe a solution would be an additional argument like
```javascript
/**
 * @param {Object} shape
 * @param {Boolean} doMerge
 */
PropTypes.shape(shape, doMerge) // ...
```

What do you say?

**Comment by betalb** [comment]
Considering that props are passed to ES6 constructors, you could do merging there before calling `super` and apply whatever logic is desirable.

If relying on PropTypes looks good approach, implementing this functionality separate library looks more reasonable than putting this into core.

**Comment by bigfish** [comment]
I tried that, but the props passed to constructor are immutable.. and passing another object with merged props triggers warning about not passing same props to super().

**Comment by MarcCoet** [comment]
Hi, I landed here because I was looking for a way to extend my `defaultProps`. I use CSS in JS (Emotion) and I think `defaultProps` are an elegant way of defining default styling. Then let's say I want to extend my style depending on the props, I either have to drop the elegant Emotion API and define a 'classic' React Component rendering my Emotion component so I can mess with the props in there, or use some other workaround in the parent of my Emotion component.

My 2 cents idea: why not pass the current props to function props...?
Example
```javascript
const Component = ({ style }) => <div style={style}>Hello</div>
Component.defaultProps = {
  style: {
    color: 'red',
  },
}
const Parent = ({ parentStyle }) => {
  return <Component style={props => ({ ...props.style, ...parentStyle })} />
}
Parent.defaultProps = {
  parentStyle: {
    backgroundColor: 'blue'
  }
}
```
so the idea would be to pass the current component's props as the last argument of any function prop we define.
Alternatively we could send current props when using the spread operator like so
```javascript
const Parent = ({ parentStyle }) => {
  return <Component {...props => ({style: { ...props.style, ...parentStyle }})} />
}
```
I think this would make an elegant way of 'Transfering props' without having to go through the whole definition of the component all over again.
I didn't think this all the way through but maybe some smart people can tell me if the idea is good or bad!?
