### ISSUE TITLE
Bug: Input of type radio component can't be controlled with an internal state

### ISSUE THREAD

**Issue by MahdiMajdian** [facebook/react#25726]
I've seen this approach to make a controlled radio input:

```javascript
function SomeForm() {
  const [gender, setGender] = useState('male');

  const handleChange = (event) => {
    setGender(event.target.value)
  }
  return (
    <form>
        <input type="radio" value="male" checked={gender === 'male'} onChange={handleChange} />
        <input type="radio" value="female" checked={gender === 'female'} onChange={handleChange} />
        <input type="radio" value="transgender" checked={gender === 'transgender'} onChange={handleChange} />
    </form>
  )
}
```
but I need to create a radio component that manages its state internally and independently:

```javascript
function Radio({ id, name, value }) {
  const [isChecked, setIsChecked] = useState(false);

  const handleChange = useCallback((event) => {
    setIsChecked(event.target.checked);
  }, []);

  return (
    <input
      type="radio"
      name={name}
      value={value}
      id={id}
      autoComplete="off"
      checked={isChecked}
      onChange={handleChange}
    />
  );
}
```
but the components get out of sync after a few clicks:

[behavior](https://user-images.githubusercontent.com/19470034/203246125-f42f4c24-c414-4192-802a-4e38b27e1430.mp4)

I think the onChange event is not firing correctly in this case and a rerender simply doesn't happen since we don't pass the calculated checked value as a prop.

also the checked attribute doesn't update in the DOM and it's problematic since I can't get the checked value and test my component with Testing library. (The main reason is that I can't make a testable radio component without an internal state, it's surely because of my lack of knowledge and any suggestions would be appreciated)

React version: 18.2.0

## Steps To Reproduce

1. click on the first radio input
2. click on the second radio input
3. click on the third radio input

Link to code example: https://codesandbox.io/s/nifty-dust-g47gg3?file=/src/App.js

## The current behavior

radio states gets out of sync

## The expected behavior

radios should remain controlled

**Comment by mateusmtoledo** [comment]
This is probably expected behavior. When a radio component gets checked, every other with the same name value should be marked as unchecked.

The implementation you have provided, on the other hand, sets the clicked Radio instance's isChecked state to true, but does not update the state on the other instances. This eventually leads to multiple Radio components having a isChecked state of true, which should not happen.

After clicking on each radio, from left to right, the browser correctly keep track of checked and unchecked radios, leading to something like [false, false, true], but your React implementation enforces every radio to remain checked ([true, true, true]) and, because "change" events are not fired when the user clicks on a checked radio, React won't fire any change events anymore, but native browser events are still fired as expected.
