### ISSUE TITLE
Bug: Class component is mounted/unmounted when a parent suspend

### ISSUE THREAD

**Issue by artola** [facebook/react#25732]
React version: 18.2.0

## Steps To Reproduce

1. Start the app and check console, both (class and function) component were mounted.
2. Click the button to make a parent component to suspend (uses react-freeze).
3. Check the console, class component has been unmounted.

Link to code example:

https://codesandbox.io/s/freeze-lyxqd6?file=/src/App.js

## The current behavior

When the parent component suspend, the children Class component are "mounted" and "unmounted", while Function components are not triggering the similar "useEffect" and its "cleanup".

## The expected behavior

Suspended children should not fire "mount" and "unmount".

**Comment by artola** [comment]
Using `Offscreen` it behaves a bit different, either class or function component trigger the "same" lifecycle methods/hooks.

https://codesandbox.io/s/offscreen-kjfyji?file=/src/App.js

But, if  am looking to this thing it is because I would like to implement some stack routing navigation, where the covered layers in the stack should be kinda detached to avoid unnecessary computation while not visible to the user and re-attached just later when needed.
For such reason it would be better if the lifecycle methods are not fired at all when going in or out of suspend mode.

**Comment by gaearon** [comment]
This is expected behavior.

`useLayoutEffect` *does* get remounted because it often does something with DOM (e.g. reading layout) so it's important to do again if you previously did it while the element was hidden from the DOM (and had empty layout). https://codesandbox.io/s/freeze-forked-hq0jvv?file=/src/App.js

Class component lifecycles are closer to `useLayoutEffect` so they do the same.
