### ISSUE TITLE
Bug: Hooks are not working properly in react 18 when passing them as props to child

### ISSUE THREAD

**Issue by anisamirouche** [facebook/react#25913]
I'm trying to do a very basic thing in react which is wroking in previous versions properly but not in react 18. i'm only trying to pass setState function to child component but it's always undefiend. this is my code

React version: 18.1.0

## Code Example

Parent component

   ```
 import React from "react";
import { Child } from "./child";
export function Parent() {
  const [data, setData] = React.useState("");

  React.useEffect(() => {
    console.log("data in parent", data);
  }, [data]);

  return (
    <div>
      <div> state value in parent component: </div>
      <div>{data} </div>
      <Child setData={setData} data={data} />
    </div>
  );
```
Child Component

```
export function Child({ data, setData }) {
  const handlePress = (value) => {
    setData(value);
    console.log("value checking", value);
    console.log("data in child", data);
  };

  return (
    <div>
      <button onClick={() => handlePress("1")}>Change state in Child</button>
      <div> state value in child component: </div>
      <div>{data} </div>
    </div>
  );
}

```

But i'm having the following error

`TypeError: setData is not a function
`
I checked but setData is always undefined, I tested this code in another project and it's working fine.

## Link to the code Sandbox

https://codesandbox.io/s/shy-fire-6lq8hl?file=/src/child.js:0-379

## The current behavior
`TypeError: setData is not a function
`

## The expected behavior
without any errors

**Comment by Othmane-aoubid** [comment]
they are  working perfectly ,  you must have done something wrong , check again your code

**Comment by maoxiaodun** [comment]
this code works correctly

**Comment by KEM-CONSOLATION** [comment]
hello guys
I'm pretty new to contributing to open source projects, and I saw this and thought it would be a good way to start.
From the above comments Its clear it has been resolved.

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

The provided Codesandbox does not reproduce the error for me. Could you add explicit instructions on how to reproduce this bug with the provided repro?

**Comment by NeoSithole** [comment]
> hello guys I'm pretty new to contributing to open source projects, and I saw this and thought it would be a good way to start. From the above comments Its clear it has been resolved.

Grand entrance.

**Comment by mahmodlte** [comment]
Hey man it looks like there is no error and it works well on codesandbox there are no errors and it set the data to "1"

**Comment by priyank-svmx** [comment]
check 
https://codesandbox.io/s/broken-resonance-x42lzs
console logged the function itself

**Comment by eps1lon** [comment]
Assuming your issue is with 
```js
setData(value);
console.log("value checking", value);
console.log("data in child", data);
```

When you call `setData(newData)` the corresponding state value isn't immediately updated. `setState` only schedules a state update. This is explained in more detail in the [troubleshooting section for `useState`](https://beta.reactjs.org/reference/react/useState#ive-updated-the-state-but-logging-gives-me-the-old-value).

Otherwise I don't understand what the issue is. Could you elaborate what the expected behavior is, what is actually happening and how to get to that point?

**Comment by liuxiaoyou1** [comment]
find the problem?

**Comment by SoumyadeepOSD** [comment]
> I'm trying to do a very basic thing in react which is wroking in previous versions properly but not in react 18. i'm only trying to pass setState function to child component but it's always undefiend. this is my code
> 
> React version: 18.1.0
> 
> ## Code Example
> Parent component
> 
> ```
> import React from "react";
> import { Child } from "./child";
> export function Parent() {
> const [data, setData] = React.useState("");
> 
> React.useEffect(() => {
>  console.log("data in parent", data);
> }, [data]);
> 
> return (
>  <div>
>    <div> state value in parent component: </div>
>    <div>{data} </div>
>    <Child setData={setData} data={data} />
>  </div>
> );
> ```
> 
> Child Component
> 
> ```
> export function Child({ data, setData }) {
>   const handlePress = (value) => {
>     setData(value);
>     console.log("value checking", value);
>     console.log("data in child", data);
>   };
> 
>   return (
>     <div>
>       <button onClick={() => handlePress("1")}>Change state in Child</button>
>       <div> state value in child component: </div>
>       <div>{data} </div>
>     </div>
>   );
> }
> ```
> 
> But i'm having the following error
> 
> `TypeError: setData is not a function ` I checked but setData is always undefined, I tested this code in another project and it's working fine.
> 
> ## Link to the code Sandbox
> https://codesandbox.io/s/shy-fire-6lq8hl?file=/src/child.js:0-379
> 
> ## The current behavior
> `TypeError: setData is not a function `
> 
> ## The expected behavior
> without any errors

Hey @anisamirouche , I think you've forgot to put the ' } ' of Parent function

**Comment by anisamirouche** [comment]
I'm coming today to explain what was thr problem, after days of debugging, the problem was that the state was shared with two childrens and they are both on the same component, so everything was confusing, my advice is to debug every state separately and if a state should be used in more than one child better use redux or context. the code provided as example isn't the code causing the error. it's a big project company code base and couldn't pose the code. it was only an example
Thanks for everyone who tried to help. everything is working fine in hooks
I'm gonna close this issue

**Comment by EbenFergy** [comment]
Two things are wrong with your code:

1. The reason why you're getting an `undefined` output is because: the `useState` hook is asynchronous so you shouldn't try to use a state in the same block or scope at which you're setting it. If you take the console log outside of that blocked scope, then you should get the required output.

` const handlePress = (value) => {
    setData(value);
    console.log("value checking", value);
  };

  console.log("data in child", data);
`


2. As much as the above code would work however, you should not pass down a setState function the way you did. If you must set a state in a parent component from a child component, you can do so by passing a call back function that sets the state when called in the child component. For example:

The ```handlePress``` function should have been created in the parent function and passed down as a prop to the child component. So that way the state is still set from the child component.

Parent Component
`import React from "react";
import { Child } from "./child";
export function Parent() {
const [data, setData] = React.useState("");

React.useEffect(() => {
 console.log("data in parent", data);
}, [data]);


const handlePress = (value) => {
    setData(value);
    console.log("value checking", value);
  };

return (
 <div>
   <div> state value in parent component: </div>
   <div>{data} </div>
   <Child  handlePress={handlePress} data={data} />
 </div>
);`


Child Component
`export function Child({ data, handlePress }) {
    console.log("data in child", data);
  return (
    <div>
      <button onClick={() => handlePress("1")}>Change state in Child</button>
      <div> state value in child component: </div>
      <div>{data} </div>
    </div>
  );
}`


Furthermore, you can also explore options like Context Api and Redux to solve more complex situations like this.

**Comment by iyunusov** [comment]
> Two things are wrong with your code:
> 
> 1. The reason why you're getting an `undefined` output is because: the `useState` hook is asynchronous so you shouldn't try to use a state in the same block or scope at which you're setting it. If you take the console log outside of that blocked scope, then you should get the required output.
> 
> ` const handlePress = (value) => { setData(value); console.log("value checking", value); };
> 
> console.log("data in child", data); `
> 
> 2. As much as the above code would work however, you should not pass down a setState function the way you did. If you must set a state in a parent component from a child component, you can do so by passing a call back function that sets the state when called in the child component. For example:
> 
> The `handlePress` function should have been created in the parent function and passed down as a prop to the child component. So that way the state is still set from the child component.
> 
> Parent Component
> 
> ```
> import React from "react";
> import { Child } from "./child";
> 
> export function Parent() {
>    const [data, setData] = React.useState("");
> 
>     React.useEffect(() => {
>          console.log("data in parent", data);
>     }, [data]);
> 
>     const handlePress = (value) => {
>         setData(value);
>         console.log("value checking", value);
>       };
> 
>     return (
>          <div>
>                <div> state value in parent component: </div>
>                <div>{data} </div>
>                <Child  handlePress={handlePress} data={data} />
>          </div>
>     )
> }
> ```
> 
> Child Component
> 
> ```
> export function Child({ data, handlePress }) {
>     console.log("data in child", data);
>   return (
>     <div>
>       <button onClick={() => handlePress("1")}>Change state in Child</button>
>       <div> state value in child component: </div>
>       <div>{data} </div>
>     </div>
>   );
> }
> ```
> 
> Furthermore, you can also explore options like Context Api and Redux to solve more complex situations like this.

What's wrong with passing down the `setData` the way he did, from parent to child component without the use of a callback?
