### ISSUE TITLE
custom hook does not work in the new version of react dom

### ISSUE THREAD

**Issue by Sinevik** [facebook/react#25957]
In my projects, I very often use a custom hook to emulate the behavior of componentDidUpdate

const [lesson, setLesson] = useState('');
  const ref = useRef();
  useEffect(() => {
      if (!ref.current) {
         ref.current = true;
      } else {
         do something
       }
   }, [lesson]);

With this combination, the custom hook stopped working

"react": "^18.2.0",
"react-dom": "^18.2.0",

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
    <React.StrictMode>
      <App/>
    </React.StrictMode>,
);

What is the problem?

**Comment by vardhanreddy27** [comment]
It looks like the issue may be caused by the fact that you are using the createRoot method from react-dom/client to render your app, rather than the render method from react-dom.

The createRoot method is used to create a root container that can be used to render a React element tree to the DOM. It is different from the render method in that it enables concurrent rendering, where multiple components can be rendered asynchronously without blocking the main thread.

However, one of the side effects of using createRoot is that it can cause certain lifecycle methods, such as componentDidUpdate, to behave differently. This may be why your custom hook is not working as expected.

One possible solution is to switch back to using the render method from react-dom to render your app. This will allow you to use your custom hook as you intended.

Here is an example of how you could modify your code to use the render method:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/63119222/210738934-f317cf93-b7cb-4df9-9dd6-3d577070c108.png">

**Comment by Sinevik** [comment]
Thank you very much. This is the configuration created by create-react-app. Perhaps we should let the owners of this package know.

**Comment by govind15496** [comment]
Hey I am a newcomer in this project and I would like to contribute

**Comment by sunderls** [comment]
Could you repro it in a codesandbox for people to debug right away,
and explains what is expected VS actual?

**Comment by frfancha** [comment]
I don't get the link between didUpdate and a useEffect on lesson... What role plays this "lesson"??
And what do you mean by stop working??
Anyway custom hooks still work perfectly well.
To emulate properly didUpdate you need a useEffect on [], and you also need to clean your reference value detecting first the mount évent, otherwise component reuse will be detected as update by your hook

**Comment by pranshu05** [comment]
I was also stuck here
You should call a render method in the code
here's updated code
```js
import React, { useState, useRef, useEffect } from 'react';
import ReactDOM from 'react-dom';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));

function CustomHookExample() {
  const [lesson, setLesson] = useState('');
  const ref = useRef();

  useEffect(() => {
    if (!ref.current) {
      ref.current = true;
    } else {
      console.log('Custom hook is working!');
    }
  }, [lesson]);

  return (
    <div>
      <input
        type="text"
        value={lesson}
        onChange={(e) => setLesson(e.target.value)}
      />
    </div>
  );
}

root.render(
  <React.StrictMode>
    <App />
    <CustomHookExample />
  </React.StrictMode>
);
```
