### ISSUE TITLE
Bug: React.StrictMode causes AbortController to cancel

### ISSUE THREAD

**Issue by v3rron** [facebook/react#25962]
React version: 18.2

## Steps To Reproduce

1. I have multiple async methods that fetch data from API on demand.
2. This data needs to be loaded initially on page load and also in case of refresh button pressed by the user
4. Without React.StrictMode the abort controller aborted = false
5. With React.StrictMode the abort controller gets set to aborted = true

## Example code:
```javascript
import { useEffect, useState } from "react";
import axios from "axios";

export default function App() {
  const [data, setData] = useState([]);
  const [dataLoading, setDataLoading] = useState(false);

  const controller = new AbortController();
  const { signal } = controller;

  const getData = async () => {
    console.log("getData API call");
    setDataLoading(true);
    return axios
      .get(`/api/v1/health`, {
        signal
      })
      .then((res) => {
        setData(["data: ", "loaded", " successfully"]);
      })
      .catch((err) => {
        console.log("getData caught error");
        console.log({ err });
      })
      .finally(() => setDataLoading(false));
  };

  useEffect(() => {
    getData();

    return () => {
      console.log("CONTROLLER ABORT");
      controller.abort();
    };
  }, []);

  const refreshData = async () => {
    await getData();
  };

  return (
    <div>
      {data.length ? (
        data.map((val) => val)
      ) : (
        <div>{dataLoading ? "Loading..." : "Data not found."}</div>
      )}
      <Actions onRefresh={refreshData} />
    </div>
  );
}

function Actions({ onRefresh }) {
  return (
    <div style={{ marginTop: "20px" }}>
      <button onClick={onRefresh}>Refresh</button>
    </div>
  );
}
```

Console log produces the following result:
```console
getData API call
CONTROLLER ABORT
getData API call
getData caught error
{err: CanceledError}
getData caught error
{err: CanceledError}
```

## Link to code example:
https://codesandbox.io/s/react-18-abort-controller-bug-v3v4oi

## The current behavior
The second rendering of the component causes the controller to go from aborted false -> true.

## The expected behavior
Please suggest how else can we use AbortController without duplicating logic and what are the best practices for doing so going forward.

PS: I'm aware of the React.StrictMode [changes in React 18](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state), but I can't seem to find another solution to this problem other than move all the fetch logic inside useEffect, which solves the problem, but cannot be isolated for reuse.

**Comment by sunderls** [comment]
Maybe you can try to create sth like `useQueryData()`

```
const [data, refresh] = useQueryData(() => axios.get('''))
```

And inside of `useQueryData()`, you can nicely avoid the double rendering by just checking if request is ongoing or not.

Or better, use [swr](https://swr.vercel.app/) instead

**Comment by vardhanreddy27** [comment]
It looks like the issue you are experiencing is that the AbortController is being reset to an "aborted" state on the second rendering of the component, causing the getData API call to throw a CancelledError error.

One option to avoid this issue could be to move the creation of the AbortController and the signal object outside of the component, so that they are not reset on every rendering of the component.

You could create a custom hook to handle the logic for making the API call and passing in the signal object to the call, like this:

import { useState, useEffect } from 'react';

function useQueryData(url, signal) {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await axios.get(url, { signal });
        setData(response.data);
      } catch (err) {
        if (err.name !== 'AbortError') {
          setError(err);
        }
      } finally {
        setIsLoading(false);
      }
    }
    fetchData();
  }, [url, signal]);

  return [data, error, isLoading];
}
Then, in your component, you can create the AbortController and the signal object and pass them to the useQueryData hook:

import { useEffect, useState } from 'react';

function MyComponent() {
  const controller = new AbortController();
  const signal = controller.signal;
  const [data, error, isLoading] = useQueryData('https://my-api.com/data', signal);

  useEffect(() => {
    return () => {
      controller.abort();
    };
  }, []);

  if (error) {
    return <div>Error: {error.message}</div>;
  }
  if (isLoading) {
    return <div>Loading...</div>;
  }
  return <div>Data: {data}</div>;
}
This way, the AbortController and signal objects are only created once, and the useQueryData hook will be able to cancel the ongoing request if the component is unmounted.

Another option to consider could be using a library like swr (https://github.com/zeit/swr) to handle the logic for making the API calls and caching the data. This library provides a hook-based API that makes it easy to fetch and cache data in your React components.

**Comment by sunderls** [comment]
```ts
  const controller = new AbortController();
  const { signal } = controller;

  useEffect(() => {
    getData();

    return () => {
      console.log("CONTROLLER ABORT");
      controller.abort();
    };
  }, []);
```
There is an issue in your above code under DEV. 

In StrictMode React will mount the effect > clean up > mount again ([source code](https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberWorkLoop.js#L3645-L3664))

This means that the same exact effect creator function(the first arg of useEffect) is triggered twice, because of closure, the exact function holds reference to exact getData, which mean it holds to same signal.

This results in

1. in the first effect mount, request inited with the signal
2. in the clean up, aborted
3. in the second effect mount, request inited again with the same signal. But it is already aborted. 

This why you see too error logs but not the same error type.

<img width="1064" alt="Screen Shot 2023-01-05 at 22 05 29" src="https://user-images.githubusercontent.com/2394070/210786878-c2b1f57d-638a-4dc8-b380-f88d46fe3e29.png">


## Solution

To avoid this, you need to make sure **the signals are different in extra renders**, meaning it's better to generate different singal on each request, so you can do something like this


```
  const getData = () => {
    const controller = new AbortController();
    const { signal } = controller;
    ...
    return {abort: () => controller.abort()}
  }

  useEffect(() => {
    const {abort} = getData();

    return () => {
      console.log("CONTROLLER ABORT");
      abort()
    };
  }, []);
```

**Comment by v3rron** [comment]
@sunderls thanks for your response. While your solution works, it's requiring to drop the `async` from `getData`. 
Also, I initially simplified the example without any conditions. What if useEffect was relying on `isLoggedIn` boolean value?

```javascript
const [isLoggedIn, setIsLoggedIn] = useState(false);

// this is just an example, in real world isLoggedIn is getting set by context API
useEffect(() => {
  const timer = setTimeout(() => setIsLoggedIn(true), 1000);
  return () => clearTimeout(timer);
}, []);

useEffect(() => {
  if (isLoggedIn) {
    // this won't work
    const { controller } = getData();
  }

  return () => {
    console.log("CONTROLLER ABORT");
    // controller is undefined
    controller.abort()
  };
}, [isLoggedIn]);

const getData = async () => {
  const controller = new AbortController();
  const { signal } = controller;
  const request = axios.get('...', { signal })
  return { controller, request }
}
```

I forked the initial code with more real world example:
https://codesandbox.io/s/react-18-abort-controller-bug-forked-l0jcfj

**Comment by vardhanreddy27** [comment]
To make this work, you could move the getData function inside the useEffect and only call it if isLoggedIn is true. That way, the controller and request will be defined when you try to use them in the cleanup function.
useEffect(() => {
  if (isLoggedIn) {
    const getData = async () => {
      const controller = new AbortController();
      const { signal } = controller;
      const request = axios.get('...', { signal })
      return { controller, request }
    }
    const { controller } = getData();

    return () => {
      console.log("CONTROLLER ABORT");
      controller.abort()
    };
  }
}, [isLoggedIn]);

Alternatively, you could define controller and request as refs and update their values inside the useEffect:
const controller = useRef();
const request = useRef();

useEffect(() => {
  if (isLoggedIn) {
    controller.current = new AbortController();
    request.current = axios.get('...', { signal: controller.current.signal });
  }

  return () => {
    console.log("CONTROLLER ABORT");
    if (controller.current) {
      controller.current.abort();
    }
  };
}, [isLoggedIn]);

**Comment by sunderls** [comment]
@v3rron right, I just explained why your code didn't work, and the direction to fix. 
It really depends what you want to achieve and your code structure. 

If you want to keep async, sth like below would work.

```ts
const fetcher = () => {
    const controller = new AbortController();
    const { signal } = controller;
    ...
    return {abort: () => controller.abort(), request: () => { return some promise }}
}

const getData = (request) => {
   request().request().then(() => setState(...))
}
 
useEffect(() => {
    const {abort, request} = fetcher();
    getData(request).
    return () => {
      console.log("CONTROLLER ABORT");
      abort()
    };
 }, []);
```

For isLoggedIn

```
useEffect(() => {
    const {abort, request} = fetcher();
     if (isLoggedIn) {
         getData(request)
     }
    ....
 }, []);
```

You can already see how this is messy, the best choice for you is to use library like swr.

Also since this is not React bug, I guess React repo is not a place to discuss such questions. Better you move it to stackoverflow or other communities

**Comment by v3rron** [comment]
@sunderls thanks for your comment. I was able to make it work with useRef outside of useEffect. While it is a bit more messy architecture wise than React 17, I can see how it benefits the development environment. And yes, it's not a React bug like I initially thought, therefore closing the issue.
