### ISSUE TITLE
RSC version

### ISSUE THREAD

**Issue by Ivorfason** [facebook/react#26013]
When will we have a release version within RSC?

**Comment by Ivorfason** [comment]
react server component

**Comment by tony1658** [comment]
See: https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md#adoption-strategy

It is already available in https://nextjs.org/blog/next-13-4

**Comment by gaearon** [comment]
Hi!

We consider RSC stable, but we can't include them into a semver-stable release of React yet due to other related projects being in a half-finished state. We've just posted about the new officially way to consume React (via Canaries) which has RSC support turned on: https://react.dev/blog/2023/05/03/react-canaries#example-react-server-components
