### ISSUE TITLE
React keeps old states in memory which increases app memory footprint

### ISSUE THREAD

**Issue by milantomic6** [facebook/react#26033]
our app is using react 17.0.2, it also uses redux store - as we navigate through app store state gets replaced with new state - I see that old state objects are still kept in memory - these get removed from memory, but only after some more usage of the app - I am thinking they should be eligible for removal from memory as soon as they are not needed, however I see there are references through it coming from HTMLElement.__reactFiberxyz object - in heap snapshot I don't see any reference to our code, it is all in vendor.js (we bundle react code in that file)

is this expected behavior? - that we keep certain number of old states in memory.
to be clear, this is not a memory leak type of issue, its just that it appears app is using more memory that it needs.

here is heap snapshot, and code reference in snapshot that points to some react (or redux) code.

![heapsnapshot_codereference](https://user-images.githubusercontent.com/6414041/213961268-2e358d5d-8cb4-4ab0-8cc1-a1da21ceffb0.png)
![heapsnapshot](https://user-images.githubusercontent.com/6414041/213961270-6faac3dc-459c-42a7-9089-0552d47605e5.png)

**Comment by Skand17** [comment]
It is expected that old states will be kept in memory as long as there are references to them. This is because JavaScript's garbage collector does not immediately remove objects from memory when they are no longer in use, but instead waits until the next garbage collection cycle to determine which objects are eligible for removal.

In this case, it sounds like the references to the old states are coming from the HTMLElement.__reactFiberxyz object, which is likely related to React's internal representation of the component tree. These objects are used by React to keep track of the component hierarchy and update the DOM efficiently.

It is possible that these references are preventing the garbage collector from removing the old states from memory. However, this behavior is likely intended by React and is not a memory leak.

It is important to note that JavaScript's garbage collector is a complex system that can be difficult to predict. It may not always behave in the way we expect it to. Therefore, it's important to monitor your app's memory usage and performance, and investigate if you notice any issues. You could use tools like chrome dev tools or profiler to investigate the memory usage and see if you find any problems.

It's also worth noting that you're running on a very old version of React (17.0.2) which has been end-of-lifed, you may want to consider upgrading to a more recent version to ensure you have access to all the latest performance improvements and bug fixes.

**Comment by milantomic6** [comment]
@Skand17  - are you responding to this thread as a member of react team?

I don't expect memory to be cleaned up right away, I understand that it will be cleared once GC kicks in - problem is that there are still references to the old states so even if GC runs it won't be able to remove it. The only way these get removed is after app is used for some more time and more states are created - as if there is states queue with certain capacity that are preserved.

So the app is working with an suboptimal memory footprint, in browser it works fine but in web view on ios devices it happens that occasionally os decides to shut down web view process (probably due to excessive memory usage) which is very annoying to out app users - I am hoping if we were to reduce memory footprint this would happen less frequently.

**Comment by abhishek20111** [comment]
Don't you think that , we can use a different method to store data, which is more efficient than this.

**Comment by milantomic6** [comment]
@abhishek20111 - not sure I quite follow you, can you explain what you meant? - if your questions is whether we can optimize app to use less memory, there is no easy way to do that.
