### ISSUE TITLE
Bug: onTransitionStart

### ISSUE THREAD

**Issue by m1gu3l** [facebook/react#26065]
React version: any

## Steps To Reproduce

Add onTransitionStart and onTransitionEnd handlers to element with styles that contain transition declaration

Link to code:
https://github.com/facebook/react/blob/0b4f443020af386f2b48c47c074cb504ed672dc8/packages/react-dom-bindings/src/events/DOMEventProperties.js#L119

Link to docs:
https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionstart_event

## The current behavior
onTransitionEnd fires, onTransitionStart doesn't

## The expected behavior
Both handlers should fire

**Comment by yulafezmesi** [comment]
t

**Comment by greatSumini** [comment]
I'd like to take this one 😄

**Comment by eps1lon** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://react.new), or a link to a repository on GitHub.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by m1gu3l** [comment]
https://codesandbox.io/s/stoic-tu-kle13g?file=/src/App.js

**Comment by eps1lon** [comment]
When we do this, we should also add cancel and run for consistency. Seems like these weren't added because they didn't exist when that particular code was written.

Not sure how much work is required to get this into the current synthetic event system. But then there are also plans to drop the synthetic event system at which point `onTransitionStart` will just start working automatically.

**Comment by gaearon** [comment]
Should be easy to add to the list, I think.

**Comment by pauldraper** [comment]
This has been supported by every major browser since March 2020. https://caniuse.com/mdn-api_element_transitionstart_event

(Is this project still active?)
