### ISSUE TITLE
Why is react so slow rendering 900 items? (with jsfiddle)

### ISSUE THREAD

**Issue by VascoPessanha** [facebook/react#2608]
Hi guys,
I'm evaluating react.js (considering using it in some projects) but I'm having trouble rendering a simple list with 910 elements, since it takes almost 4 seconds.
This is not a complex markup (just a couple of div tags), actually it's an existing app simplification.
I tried this using just underscore.js and it took 500ms!!

Jsfiddle:
- using JSX: http://jsfiddle.net/4TpnG/459/
- without JSX: http://jsfiddle.net/VkebS/925/

What am I doing wrong?

Cheers,
Vasco Pessanha

**Comment by wzup** [comment]
I confirm that react is VERY slow when there are many elements. It is drastically slow. It has nothing to do between its name and real-life usage. It is definitely not reactive.

**Comment by gaearon** [comment]
>I confirm that react is VERY slow when there are many elements. It is drastically slow. It has nothing to do between its name and real-life usage.

Hi, we’d love to help you but this is very vague. How many elements? If you render more than a thousand elements in a page, you probably can’t show them all at once anyway. In this case it is better to used [virtualized lists](https://bvaughn.github.io/react-virtualized/) so that you can render as many items as you need and stay performant. You can also use something like [MobX](https://github.com/mobxjs/mobx) for automatic granular subscriptions if you’re hitting performance limits with thousands of items with traditional React data flow.

That said, it is equally likely that React can be fast in your case if you:

* use production build instead of development build (they can have 3x-5x difference in perf);
* provide React with some [performance optimization hints](https://facebook.github.io/react/docs/advanced-performance.html).

This is a [good guide](http://benchling.engineering/performance-engineering-with-react/) to optimizing performance of React apps. Please check it out if you’re interested!

>It is definitely not reactive.

“Reactive” refers to the fact that when you update the state, the DOM is updated automatically, “reacting” to the state change. It doesn’t mean React claims to be the fastest library possible. However it is definitely used very widely at Facebook, including React Native where performance is very important, so it enjoys a ton of real-world usage.

**Comment by VascoPessanha** [comment]
Agree, I've been using virtualized lists and reducing the number of DOM
elements in the lists and you can get performant lists!

Vasco Pessanha
Senior Software Engineer
OutSystems

www.outsystems.com

**Comment by mqliutie** [comment]
When I use Ipod render time only one second.But when I use Android it takes seven seconds.

Android configuration is : 

RAM : 2GB

CPU frequency : 2.0GHz
GPU : Imagination PowerVR G6200

 Can I enhance the user experience?

 Virtualized lists  or MobX can solve it?

**Comment by flexicious** [comment]
The solution to rendering a lot of items at once on the screen is virtualization - this is not a React specific problem - we've done this in other frameworks as well -  and did this for our react datagrid component http://reactdatagrid.com

Although this depends on the structure of each row of data, beyond a certain number of rows you simply cannot achieve decent performance without virtualization - with or without react. 

There is a library https://github.com/bvaughn/react-virtualized that implements virtualization that you may wish to investigate.

**Comment by cpobleteolmedo** [comment]
react vitualized Is for to show data in case of editions and filters that recommend?

**Comment by argonavt11** [comment]
@mqliutie Clean console.log in Android. He will load the application.

**Comment by smithaitufe** [comment]
I know this is an old issue. I am also having an issue rendering list of countries. It is very slow, although my case is react native. How can I increase the speed?
```js
    const countriesMap = countries && countries.map(country => (
        <TouchableOpacity key={country.code} onPress={() => this.onCountrySelected(country)} >
            <View style={{ borderBottomWidth: 1, borderBottomColor: "#CCC", flexDirection: "row", paddingVertical: 10 }}><Text style={{ width: 50, paddingHorizontal: 10, borderRightWidth: 1, borderRightColor: "#CCC", marginRight: 20 }}>{country.code}</Text><Text>{country.name}</Text></View>
        </TouchableOpacity>
    ))

<Modal 
                        isVisible={this.state.visibleModal === 2}
                        onBackdropPress={this.closeModal} 
                        animationIn={'slideInLeft'}
                        animationOut={'slideOutRight'}
                        animationInTiming={800}
                        animationOutTiming={800}
                        backdropTransitionInTiming={2000}
                        backdropTransitionOutTiming={2000}
                        style={{ margin: 0, marginTop: 50 }}
                    >
                        <ScrollView style={{ flex: 1, backgroundColor: '#FFF' }}>
                            {countriesMap}
                        </ScrollView>
                    </Modal>
```

**Comment by allanlaal** [comment]
@smithaitufe https://github.com/bvaughn/react-virtualized will recycle rows not in view, when scrolling a massive list - this will lessen DOM size and result in faster UI speeds
