### ISSUE TITLE
Bug: useSyncExternalStore will cause hydration missmatch in `StrictMode` if `serverSnapshot` is different from `snapshot`

### ISSUE THREAD

**Issue by promer94** [facebook/react#26095]
## React version
React version: 18.3.0-next-b0671f9ea-20230130

## Problem
In `StrictMode`,  when using hydrateRoot to render a component that using `useSyncExternalStore` it seems that useSES will do hydration twice. 

But in second hydration process,  useSES does not use the result of `getServerSnapshot` as initial state, which will cause hydration error.

This problem will only happen in `development` mode, 

## Reproduce
Link to code example:
https://codesandbox.io/s/useses-18-3-rojznv

It works well in react 18.2
https://codesandbox.io/s/useses-18-2-13iskc

**Comment by eps1lon** [comment]
Can confirm. I reduced the repros a bit more so that it's easier to comprehend what's going on:

next (with StrictMode) broken: https://codesandbox.io/s/useses-18-3-forked-co9ix3
next (without StrictMode) passing: https://codesandbox.io/s/useses-18-3-forked-1x8ivp
18.2 passing: https://codesandbox.io/s/useses-18-2-forked-23vufs
