### ISSUE TITLE
Bug: setState doesn't bail on re-render when called with unchanged value during render

### ISSUE THREAD

**Issue by juzerzarif** [facebook/react#26188]
When using the `setState` function from the state hook to update state based on prop changes like mentioned [here](https://beta.reactjs.org/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state), if `setState` is called with the same value as the current state (or a callback that returns the same value as the current state), React still re-renders the component unlike its behavior when `setState` is called outside a render. 
Is this intended behavior? If so, I think it might be helpful to put this in the docs somewhere around here https://beta.reactjs.org/reference/react/useState#setstate-caveats?

React version: 18.1.0

## Steps To Reproduce

The specific pattern that I was trying to use was something like this:

```js
function MyComponent() {
  const [state, setState] = useState(0);

  // referentially stable callback that might be used as a prop to a child
  const updateStateIfNeeded = useCallback((newState) => {
    setState(currentState => newState == currentState ? currentState : newState);
  }, []);

  // Infinite re-renders
  updateStateIfNeeded(newState);
  // I would need to duplicate the bit inside updateStateIfNeeded that checks against
  // currentState here to guard the setState call to avoid re-renders
  if (newState !== state) { setState(newState) }

  // Only re-renders when state is changed
  useEffect(() => updateStateIfNeeded(newState));

  return (...);
}
```

**Comment by YankovWeb** [comment]
this is the intended behavior of React. When using the useState hook to manage state, calling the setState function with the same value as the current state (or a callback that returns the same value) will still trigger a re-render. This is because React needs to run its reconciliation process to determine whether any other parts of the component tree need to be updated.

One possible solution to avoid the infinite re-renders in your example code is to use the useEffect hook to update the state only when the newState value changes. You can also use the useMemo hook to memoize the updateStateIfNeeded function, so that it's only recreated when state or setState changes:

scss
Copy code
function MyComponent() {
  const [state, setState] = useState(0);

  // memoize updateStateIfNeeded so that it's only recreated when state or setState changes
  const updateStateIfNeeded = useMemo(() => {
    return (newState) => {
      if (newState !== state) {
        setState(newState);
      }
    };
  }, [state, setState]);

  // Only call updateStateIfNeeded when newState changes
  useEffect(() => {
    updateStateIfNeeded(newState);
  }, [newState, updateStateIfNeeded]);

  return (...);
}
You can also use the useRef hook to store the previous value of newState, and compare it with the current value in the useEffect hook:


function MyComponent() {
  const [state, setState] = useState(0);

  const prevNewStateRef = useRef(new Date()); // initialize with a dummy value

  const updateStateIfNeeded = useCallback((newState) => {
    if (newState !== state) {
      setState(newState);
    }
  }, [state]);

  useEffect(() => {
    if (newState !== prevNewStateRef.current) {
      updateStateIfNeeded(newState);
      prevNewStateRef.current = newState;
    }
  }, [newState, updateStateIfNeeded]);

  return (...);
}

**Comment by gaearon** [comment]
I believe it *does* say this in caveats (see the bolded part):

>If the new value you provide is identical to the current state, as determined by an [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) comparison, React will skip re-rendering the component and its children. This is an optimization. **Although in some cases React may still need to call your component before skipping the children, it shouldn’t affect your code.**

However, in any case, the pattern you're trying to do (setting state of a parent component while rendering a child) is very slow and recommended against. Whether you do it during render or with an effect. Whenever possible, fix the data flow instead so that it flows from top to the bottom, not from top to the bottom to the top to the bottom again.
