### ISSUE TITLE
Bug: eslint-plugin-react-hooks doesn't consider `throw` to be an early return

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [facebook/react#26201]
React 18.2.0, react-scripts 5.0.1, eslint-plugin-react-hooks 4.6.0

## Steps To Reproduce
```jsx
function App(props: {}) {
  if ("abc" in props) {
    return <>x</>
  }
  useState(); // React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render.
  return <>test</>
}

function App2(props: {}) {
  if ("abc" in props) {
    throw new Error();
  }
  useState(); // No lint warning
  return <>test</>
}
```

## The current behavior
There is no lint warning in App2.

## The expected behavior
There should be a lint warning in App2 because the throw is an early return and violates the rules of hooks.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
Maybe related: #20514.

**Comment by eps1lon** [comment]
This is fine since React will be able deal with the hooks that were run until that point. Throwing is not equivalent to an early return since it's detectable by React whereas an early return is not without implementation introspection.

Otherwise we'd have to consider every statement an "early return" since those could throw as well.
