### ISSUE TITLE
Slow state update with long list of data

### ISSUE THREAD

**Issue by ghost** [facebook/react#26215]
![218817450-0e876a54-5af7-4b8c-a821-feaea1dbc08d](https://user-images.githubusercontent.com/86713661/220406519-9c0ba689-057f-4f23-9a83-bc21a1a61b14.gif)

React version: 18.2.0

## Steps To Reproduce

Live example:
[CodeSandbox](https://codesandbox.io/s/fervent-architecture-meewni?file=/src/App.js)

## The current behavior

Checkbox works very slow

## The expected behavior

Checkbox works instantly

**Comment by sohaibMan** [comment]
I think the problem is just the large complexity of your algorithms and the cost of unnecessary recalculations.
Here is an example of an optimzed version of your app with same features .
Live example:
[sandbox](https://codesandbox.io/s/solitary-rain-gvw2wg)

**Comment by alexander-vashchuk** [comment]
@sohaibMan 
"the large complexity"
I'm not sure there's much complexity to it, as this bug is not visible at fairly smaller list of players like `100`, for example

I was able to eliminate it by refactoring `useState` into `useRef` using kind of your `no useState` approach
[CodeSanbdox useRef version](https://codesandbox.io/s/hungry-goldwasser-odoi3k?file=/src/App.js)

But, I'm still curious
1) Why useState hooks seems to slow things down
2) Is there a way to display this large data set, and use useState hook while having a quick performance?
(The trade off with the `useRef` hook is that it goes out of the component lifecycle, so **useEffect** does not track it which can be a bummer in certain cases)

**Comment by kalp2525** [comment]
For my app this feature work great

**Comment by alexander-vashchuk** [comment]
@hhkk28 Then why it works fast when I use `useRef` instead of `useState`?
Seems like React virtual DOM is not very smart about it

**Comment by hhkk28** [comment]
@alexander-vashchuk React re-renders only when a state or props is changed. In case of updating refs, react re-render any nodes. That is the intended behavior. In react developer tools, enable the toggle `Highlight updates when components render.` to see the components that are re-rendered. In the case of the checkbox with useRef, only the checkbox is re-rendered due to the internal state change of material ui, whereas in the case of the checkbox with useState, the entire table is re-rendered.
![image](https://user-images.githubusercontent.com/85559412/221574044-793bcd9a-a35a-4646-9911-43e8bdf39f63.png)

Please check this well written blog on react rendering behaviour to understand when react triggers re renders and when it does not - [Why React Re-Renders](https://www.joshwcomeau.com/react/why-react-re-renders/)

**Comment by Seven-Y-Q-Guo** [comment]
> @hhkk28 Then why it works fast when I use `useRef` instead of `useState`?
> Seems like React virtual DOM is not very smart about it
You can use this tool to help you figure out why some components are rerendering and how to resolve them on your side to avoid unnecessary rerenders.
https://github.com/welldone-software/why-did-you-render

**Comment by LaiZhou** [comment]
I think the state comparision for the long list also takes long time.
