### ISSUE TITLE
Bug: react[18]: There is no expected closure problem in useEffect.

### ISSUE THREAD

**Issue by vaynevayne** [facebook/react#26223]
https://codesandbox.io/s/admiring-bartik-uzzz46?file=/src/App.tsx

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/124666577/220837241-695102f5-5f28-4155-a8b8-7bba2d771391.png">

log title should always be the default value if title does not appear in useEffect's dependency array.
But in this case,title always gets the latest value

**Comment by vaynevayne** [comment]
https://zh-hans.reactjs.org/docs/hooks-reference.html#useeffect

**Comment by davidmccabe** [comment]
Whenever the effect runs, for any reason — for example if `page` is updated — then the effect will get _all_ of the latest values, whether or not they're in the dependency array. This is because they are captured from the surrounding scope (the most recent rendering of the component), just as with any function. This is a good explainer for how this works: https://overreacted.io/a-complete-guide-to-useeffect/

It's not a good idea to leave things out of the dependency array, it almost always creates a latent bug in your component. 

Please describe your high-level goal and it might be possible to suggest another approach.

**Comment by gaearon** [comment]
I'll close as expected behavior. But we encourage you to consider dependency array warnings as compiler errors — it's easier to follow the rules than speculate about which particular semantics the code would have.
