### ISSUE TITLE
Supporting `Date` objects in `value` for `type=date` input tags

### ISSUE THREAD

**Issue by naveen521kk** [facebook/react#26306]
Currently, when passing `Date` objects as the `value` parameter, the `Date` object is implicitly converted into a string and the browser can't understand the format. This doesn't set the value in the date picker because of that. See https://codesandbox.io/s/objective-turing-zk9bc1?file=/src/App.js

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value), the date value should be specially formatted. While this format is the only way in HTML, I think it would be better if react supported passing `Date` objects directly for the `value` parameter instead of the application developer manually converting the `Date` object to a string (which is error prone without a date library). I'm asking this because here `value` is an object and doesn't always need to be a string (unless I'm wrong).

PS: I came across this when I was trying to load the date from a saved state and had to convert it to string and faced a weird bug, where the previous day was picked because of time zones. See https://codesandbox.io/s/aged-dawn-j084iv?file=/src/App.js

**Comment by egonSchiele** [comment]
The HTML spec says the value has to be a string (see [here](https://html.spec.whatwg.org/multipage/input.html#date-state-(type=date))), and it looks like React strongly wants all values to be strings to comply with this spec.

[There's a check to make sure the value attribute is a string](https://github.com/facebook/react/blob/main/packages/shared/CheckStringCoercion.js#L150).

[Values get coerced to strings here](https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/ToStringValue.js#L26). 

`@types/react` says the type of value is:

```ts
value?: string | ReadonlyArray<string> | number | undefined
```

**Comment by naveen521kk** [comment]
> The HTML spec says the value has to be a string (see [here](https://html.spec.whatwg.org/multipage/input.html#date-state-(type=date))), and it looks like React strongly wants all values to be strings to comply with this spec.

I thought it would be better if react supported doing so, could avoid some issues. Is there any reason why React wants all values to be string?

**Comment by krishchha** [comment]
import "./styles.css";
import React,{useState} from "react";

export default function App() {
  const [a, setA] = useState();
  return (
    <input
      type="date"
      value={a}
      onChange={(e) => {
        setA(e.target.value);
      }}
    />
  );
}

**Comment by Almas456** [comment]
You are correct that passing a Date object directly to the value prop of a date picker component in React can be problematic. This is because the value prop expects a string in a specific format, and passing a Date object directly will result in an incorrect format that the browser cannot understand.

To avoid this issue, you can use a library like moment.js or date-fns to format the Date object into a string that can be understood by the date picker component. These libraries provide functions to format dates in a variety of formats, including the format required by the date picker.

Alternatively, if you don't want to use a library, you can manually format the Date object using the built-in Date methods. For example, you could use the getFullYear(), getMonth(), and getDate() methods to get the year, month, and day of the Date object, and then concatenate them into a string in the format required by the date picker.

It would be nice if React had built-in support for passing Date objects directly to the value prop of a date picker component, but at the moment, manual conversion is still required to ensure that the date is displayed correctly.

**Comment by naveen521kk** [comment]
> It would be nice if React had built-in support for passing Date objects directly to the value prop of a date picker component

That's why I opened this issue 🙂

**Comment by YantD729** [comment]
I feel like it is kind of simple, may I have a try? I would like to be the asignee.
