### ISSUE TITLE
Bug: useRef cleanup in StrictMode refers to second ref twice

### ISSUE THREAD

**Issue by MaciejNiklasinski** [facebook/react#26315]
I'm trying to create a handle object, add it to the map and use it as ref. All that should happen on component first render when ref.current === null which according to what I read here is the only exception when directly writing to ref from render function is allowed: https://beta.reactjs.org/reference/react/useRef#avoiding-recreating-the-ref-contents

`Normally, writing or reading ref.current during render is not allowed. However, it’s fine in this case because the result is always the same, and the condition only executes during initialization so it’s fully predictable.`

Then I want to cleanup that handle object (remove it from the map) on component unmount.

Obviously, in StrictMode render function is called twice followed immediately by a single execution of the cleanup function. However, cleanup doesn't seem to work correctly as both the cleanup function executed immediately after the component has mounted and the cleanup function executed on actual component unmount are operating on the second ref.

I've tried [], [ref], and [ref.current] as useEffect dependency but none of that makes any difference and both cleanups are always operating only on the second ref.

React version: 18.2.0

## Steps To Reproduce
Link to code example: https://codesandbox.io/s/distracted-marco-hn2rpv?file=/src/index.js

## The current behavior
Both useEffect cleanup functions are operating on the second ref.

## The expected behavior
The first useEffect cleanup function which is executed straight after the component is mounted to operate on the first ref, while the second cleanup function which is executed when the component is actually getting unmounted to operate on the second ref. 

Or perhaps not duplicating ref with useRef in StrictMode ?

**Comment by Werter12** [comment]
@MaciejNiklasinski I think you could add these block inside the `useEffect` function and it will work as you expect:
```
  if (ref.current === null) {
    const id = map.size; //Symbol();
    const handle = { id };
    console.log(`Adding Symbol ${id} to map`);
    map.set(id, handle);
    ref.current = handle;
  }
```
I also noticed that in the component before first mount the mentioned code gets triggered twice. And both time `ref.current` is `null` and map add two elements. Actually, the same behavior as you mentioned. Yeah, and only in the `Strict Mode`

**Comment by MaciejNiklasinski** [comment]
@Werter12 Thank you for your suggestion, unfortunately in my real use case it won't work.

I need the handle object to be created and added to the map before the function returns the first time.

```
export const useSubscribction = () => {
  const ref = useRef(null);
  if (ref.current === null) {
    const id = Symbol();
    const handle = { id };
    map.set(id, handle);
    ref.current = handle;
  }

  useEffect(() => () => { map.delete(ref.current.id); }, [] );
  
  // At this point before the function returns the first time I need a handle object to already exist.
  // If it is moved to the useEffect (componentDidMount equivalent part) that will not be the case.
};
```

**Comment by catamphetamine** [comment]
I've also encountered this bug: in strict mode, `this` inside a class component will point to the second instance in both cases of `componentDidMount()` / `componentWIllUnmount()`.

* Component instance A is created
* Component instance B is created
* `componentDidMount()` is called with `this` being `B`
* `componentWillUnmount()` is called with `this` being `B`
* `componentDidMount()` is called with `this` being `B`

Because of that, clean-up is not possible and various "stale props" bugs occur because `componentWillUnmount()` performs a clean-up of the instance `B` which is the one that React keeps while the instance `A` is what React disposes of but that instance `A` remains "uncleaned" and its event listeners still operate.

**Comment by catamphetamine** [comment]
@MaciejNiklasinski Have a look at my bug report: https://github.com/facebook/react/issues/26467
Is it the same issue? If yes then I guess the "weird" behavior is an intentional one to reveal the components that rely on doing stuff during render ("side effects").

**Comment by BlackGlory** [comment]
This should not be the expected behavior, see this example.

```js
import { useMemo, useLayoutEffect, useEffect } from 'react'

let count = 0

export default function App() {
  const obj = useMemo(() => ({ id: count++ }), [])
  console.log(`render ${obj.id}`)

  useLayoutEffect(() => {
    console.log(`useLayoutEffect ${obj.id}`)
    return () => console.log(`useLayoutEffect(cleanup) ${obj.id}`)
  }, [obj])

  useEffect(() => {
    console.log(`useEffect ${obj.id}`)
    return () => console.log(`useEffect(cleanup) ${obj.id}`)
  }, [obj])

  return <></>
}
```

The current behavior:
```
render 0
render 1
useLayoutEffect 1
useEffect 1
useLayoutEffect(cleanup) 1
useEffect(cleanup) 1
useLayoutEffect 1
useEffect 1
```

The expected behavior:
```
render 0
render 1
useLayoutEffect 0
useEffect 0
useLayoutEffect(cleanup) 0
useEffect(cleanup) 0
useLayoutEffect 1
useEffect 1
```

This is very bad.
If your `useMemo` returns an `AbortController` whose cleanup function is `controller.abort()`,
then your `controller.signal` will be aborted at the beginning because it actually performs the cleanup function on the second controller.

**Comment by hogan** [comment]
I have same problem, described it in different issue https://github.com/facebook/react/issues/25284#issuecomment-1663618966.

**Comment by rickhanlonii** [comment]
@MaciejNiklasinski this is showing a real bug in your app. 

To see the bug:
- Turn off StrictMode
- Click "setShowComponent" to show it
- Change the code to trigger Fast Refresh
- Click "setShowComponent" again to hide it
- See "Unable to delete Symbol  0 - NOT present in map" in the console

Fast Refresh isn't working in your sandbox for me, but I repro'd it here: https://codesandbox.io/p/sandbox/pedantic-neumann-3ln5gl

To fix, you must also include the setup code in the effect, so if the effect is unmounted, the ref is set up again when it's mounted, since React may choose to unmount and remount an effect without resetting the state of the component.

**Comment by ajwootto** [comment]
@rickhanlonii perhaps you can explain a similar issue that I'm having trying to make a Provider that initializes some SDK client and properly cleans it up on unmount:

```
/ Create a context for the SDK client
const SDKClientContext = createContext(null);

// Define a provider component
export const SDKClientProvider = ({ children }) => {
  const [client] = useState(() => {
    // Synchronously initialize the SDK client here
    return new SDK();
  });

  // Cleanup on unmount
  useEffect(() => {
   client.someSetup()
    return () => {
      if (client) {
        // Cleanup logic for the SDK client
        client.cleanup();
      }
    };
  }, [client]);

  return (
    <SDKClientContext.Provider value={client}>
      {children}
    </SDKClientContext.Provider>
  );
};

// Hook to use the SDK client in components
export const useSDKClient = () => {
  return useContext(SDKClientContext);
};
```

In this code there's a problem where Strict mode seems to cause the cleanup function to run against the SDK client instance that is ultimately provided to the "final" rendering tree, resulting in that provided client being in a "closed" state. My original assumption was that Strict mode would simulate a full unmount and remount of the component such that the client being stored in state would be created again on the second execution, thus the cleanup function that runs on the first pass cleans up the client that is created on the first pass. However, it seems that the cleanup ends up affecting the same client that is "provided" after everything is finished.

How can I write this in a way where:
- the Context always has an instance of client, even on the first render pass before the `useEffect` setup function is executed
- the client is properly cleaned up if the component is legitimately unmounted
- Strict mode doesn't cause the client to be closed and also provided to the final rendering tree
