### ISSUE TITLE
[DevTools Bug]: provide an icon to Edge devtools?

### ISSUE THREAD

**Issue by yanlingwang23** [facebook/react#26352]
### Website or app

Website: https://reactjs.org/

### Repro steps

1. open developer tools in Edge
2. go to settings -> experiment -> enable Focus Mode -> reload DevTools
3. we can see the react extension is loaded as below in devtools:
![image](https://user-images.githubusercontent.com/108438266/223870494-509d7658-220c-45e5-8399-05a0fa1e6171.png)

4. since the react extension doesn't provide the icon when it's created, devtools fallback to use the default icon to represent the extension. However, we've received couple of requests from users that they'd like to see the icon in the panel.
for instance:
![image](https://user-images.githubusercontent.com/108438266/223870622-a68fa934-4ba0-450b-aa02-96c66ccab1cb.png)

Wondering if it's possible to provide an icon to Edge in the `chrome.devtools.panels.create()`?
Thank you for your support.

### How often does this bug happen?

Every time

**Comment by captainbrosset** [comment]
I was looking at the code a little bit yesterdayand, as Yanling said, the React extension does not include an icon when calling `chrome.devtools.panels.create()` ([source](https://github.com/facebook/react/blob/3706edb81c84ea01e68bfb477537ba9908e1bd70/packages/react-devtools-extensions/src/main.js#L465)).

The icon was probably omitted from this line of code because Firefox was, so far, the only browser to support DevTools panel icons, but also supported using the icon defined in the manifest file if the panel icon was missing.

Now, Edge DevTools also supports icons on DevTools panels (only when [Focus Mode](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/experimental-features/focus-mode) is enabled), but does so only if the icon is passed in the `create()` function call.

So it'd be great if React would pass an icon there, and remove the emoji in the panel title. This way, both Firefox and Edge (Focus Mode) would have the nice icon on the DevTools panel.

**Comment by harrygz889** [comment]
Hi! I'm interested in working on this as a first contribution. Is the intention to only pass the icon to `create()` when focus mode is enabled, or to unconditionally pass the icon if the browser `isEdge`?

**Comment by DiegoCascavita** [comment]
After looking into the issue, I found that the reason the icon was omitted is because Firefox was the only browser to support DevTools panel icons, but also supported using the icon defined in the manifest file if the panel icon was missing. However, Edge DevTools now also supports icons on DevTools panels (only when Focus Mode is enabled), but does so only if the icon is passed in the `create()` function call.

To solve this issue, I propose that we add an icon URL as the second argument to the `chrome.devtools.panels.create()` function and replace the emoji in the panel title with the desired text

**Comment by yanlingwang23** [comment]
Hi Diego, thanks for looking into this. Yes, you are right about the icon. But we're good with the current panel title since we still have the default UI that does not support the icon. I think Harry is working on this and has a PR out, I've left a few comments there. Thank you all for looking into this issue.

**Comment by shubham-singh-748** [comment]
is it still open if yes i want to work on this

**Comment by harryzumwalt-wk** [comment]
@yanlingwang23 Thanks for the feedback. I have updated the PR.

**Comment by chaithraramesh31** [comment]
@harryzumwalt-wk Would it be possible for you to show me how you are working on this issue? I'm new to open source contributions and would like to learn more about the process.

**Comment by itsnoa04** [comment]
if this is taken can you guys change the tag to good-first-issue (taken)

**Comment by mondaychen** [comment]
Resolved with #26543 
Thanks for the contribution @harrygz889
