### ISSUE TITLE
High Security Vulnerability found in the dependency Minimist

### ISSUE THREAD

**Issue by kvaithin** [facebook/react#26483]
The latest version of React is using `"minimist": "^1.2.3"`.

This is identified to have a High level security vulnerability. 

More information found here. 
https://devhub.checkmarx.com/cve-details/CVE-2021-44906/?utm_source=jetbrains&utm_medium=referral&utm_campaign=rider&utm_term=nuget

Would we wanna update the version? Happy to look into making the change.

**Comment by OldManMeta** [comment]
@kvaithin - can't believe you don't have any response here.

**Comment by gaearon** [comment]
React does not depend on `minimist`.

https://unpkg.com/browse/react@18.2.0/package.json
https://unpkg.com/browse/react-dom@18.2.0/package.json
https://unpkg.com/browse/scheduler@0.23.0/package.json

It's used by some dev-only dependencies that we use for development of React, but that does not affect you as a user. Additionally, the attack vector is network and requires passing untrusted user input, which is not how it's being used here.

Unfortunately most JavaScript vulnerability tools are [broken by design](https://overreacted.io/npm-audit-broken-by-design/) because they fail to distinguish how dependencies are being used. What you see here is security theater, not an actual issue.

There is no vulnerability in React, and this can be closed and ignored.
