### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by SuperEnderSlayerr** [facebook/react#26485]
https://react.dev/learn/tutorial-tic-tac-toe#declaring-a-winner

This section of the tutorial starts with: "Now that you show which player’s turn is next, you should also show when the game is won and there are no more turns to make."
We add the "status" line during this section of the tutorial, so we have not yet shown which player's turn is next.

I'm pretty sure this was just left over from the last version of the tutorial.

**Comment by eps1lon** [comment]
Makes sense. The demo right above doesn't show the next player. Though it's not clear whether we need to adjust the sentence or implement showing who's next earlier. Can you open this on https://github.com/reactjs/react.dev instead so that we get the right eyes on this issue? 

The repo you opened the issue on is for React the library not the docs.

**Comment by aliasgar55** [comment]
Created a issue on the react docs repo 
[https://github.com/reactjs/react.dev/issues/5854](https://github.com/reactjs/react.dev/issues/5854)

**Comment by aliasgar55** [comment]
We can close this issue

**Comment by SuperEnderSlayerr** [comment]
Oop, sorry I didn't see this for awhile, thanks for moving the issue to the correct library!
