### ISSUE TITLE
help! React useSelector returns undefined first, then object

### ISSUE THREAD

**Issue by litchi-iconfont** [facebook/react#26564]
Guys on github, you have encountered this kind of problem. Getting data from redux is executed twice. The first time is undefined, and the second time you can get the complete data, but the program will use the first one to operate by default, so the program Is to get undefined to operate

redux：

```
import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { getHomeGoodPriceData } from "../../service";

export const fetchHomeDataAction = createAsyncThunk("fecthdata", async () => {
  const result = await getHomeGoodPriceData()
  return result
})


const homeSlice = createSlice({
  name: "home",
  initialState: {
    goodPriceInfo: {
      
    }
  },
  reducers: {
    changeGoodPriceInfoAction(state, { payload }) {
      state.goodPriceInfo = payload
    }
  },
  extraReducers: {
    [fetchHomeDataAction.fulfilled](state, { payload }) {
      state.goodPriceInfo = payload
    }
  }

});

export const { changeGoodPriceInfoAction } = homeSlice.reducer

export default homeSlice.reducer;

```

views:

```
import React, { memo, useEffect, useState } from 'react'
import { shallowEqual, useDispatch, useSelector } from 'react-redux'
import AppCarousel from '../../conptonents/app-carousel'
import RoomItem from '../../conptonents/room-item'
import SectionHeader from '../../conptonents/section-header'
import { fetchHomeDataAction } from '../../store/modules/home'
import { HomeWrapper } from './style'

const Home = memo(() => {

  // 从state获取数据
  const { goodPriceInfo } = useSelector((state) => {
    return {
      goodPriceInfo: state.home.goodPriceInfo
    }
  }, shallowEqual)

  // 派发异步事件，发送网络请求
  const dispath = useDispatch()

  useEffect(() => {
    dispath(fetchHomeDataAction())
  }, [dispath])



  return (
    <HomeWrapper>
      <AppCarousel></AppCarousel>
      <div className="content-wrap">
        <div className="sectionHeader">
          <SectionHeader title={goodPriceInfo.title} subtitle={goodPriceInfo.subtitle}></SectionHeader>
        </div>
        <div className="section-main">
          {
            console.log(goodPriceInfo)}
        </div>
      </div>
    </HomeWrapper>
  )
})

export default Home
```

```

```
![90107810244684711e43d0031c46318](https://user-images.githubusercontent.com/76797435/230577027-4d6f5843-b31c-4ba1-a3c4-a9fd1faff082.png)

The code is output twice!

**Comment by alicioromoli** [comment]
I might need more context, however, maybe this issue could be fix adding an useEffect with a condition where if "goodPriceInfo" is true (which means there's data) you can set a new state and then use this new state to render the component below. Don't forget to add the "goodPriceInfo" as dependency to useEffect. Example:

`
const [newPriceInfo, setNewPriceInfo] = useState(null)

useEffect(() => {
    if(goodPriceInfo) {
        setNewPriceInfo(goodPriceInfo)
    }
  }, [goodPriceInfo])

...

<SectionHeader title={newPriceInfo.title} subtitle={newPriceInfo.subtitle}></SectionHeader>
`

**Comment by alicioromoli** [comment]
I might need more context, however, maybe this issue could be fix adding an useEffect with a condition where if "goodPriceInfo" is true (which means there's data) you can set a new state and then use this new state to render the component below. Don't forget to add the "goodPriceInfo" as dependency to useEffect. Example:

`const [newPriceInfo, setNewPriceInfo] = useState(null)

useEffect(() => {
    if(goodPriceInfo) {
        setNewPriceInfo(goodPriceInfo)
    }
  }, [goodPriceInfo])

...

<SectionHeader title={newPriceInfo.title} subtitle={newPriceInfo.subtitle}></SectionHeader>`

**Comment by alicioromoli** [comment]
I might need more context, however, maybe this issue could be fix adding an useEffect with a condition where if "goodPriceInfo" is true (which means there's data) you can set a new state and then use this new state to render the component below. Don't forget to add the "goodPriceInfo" as dependency to useEffect. Example:

```const [newPriceInfo, setNewPriceInfo] = useState(null)

useEffect(() => {
    if(goodPriceInfo) {
        setNewPriceInfo(goodPriceInfo)
    }
  }, [goodPriceInfo])

...

<SectionHeader title={newPriceInfo.title} subtitle={newPriceInfo.subtitle}></SectionHeader>

**Comment by TheHunter597** [comment]
I think what you want is for react application to boot with the values of goodPriceInfo be defined for instace rather than being  undefiend when the application starts  it should be 15 

the problem here is that useEffect get invoked(get called) after react page has rendered, which means it wait untill every thing (html,css,js) has been presented to you then it get invoked 

if we go to your slice file we find the you made the inital state as next 
```
initialState: {
    goodPriceInfo: {
      
    }
  }
```
which mean that the first time react has loaded it found the value of goodpriceinfo to be {}(empty object) as you can see in the image you have attached to first time its empty object 

then useEffect get invoked it runs the async function you provided redux detected that and tells react hey buddy a new state has been made i think you need to do something with it, react says oh yeah i need to log it to the developer using me so he serves you the newly fetched data

 there is two solution the i though of for you problem
1- the easy one is to use server side rendering framework like next js which is going to invoke the function fetchHomeDataAction before the page load tells react about it then serves it to you
2- set the initial state value to undefined like this
```
initialState: {
    goodPriceInfo: undefined
  }

```
then l would assume you want to put the title in the div that have section-main as class name 

```
<div className="section-main">
          {goodPriceInfo && goodPriceInfo.title}
</div>
```
this means if goodPriceInfo is not defined then do nothing, but if is is defined but the value of title in there 
its also equivalent to (if the previous syntax is hard to wrap you head around ):
```
<div className="section-main">
goodPriceInfo !== undefined ? goodPriceInfo : ""
</div>
```

another note check the spelling of the words you write ,if you are not sure google it , i have done it my self thousands of times

have a great day :)

**Comment by litchi-iconfont** [comment]
Thank you guys, this is indeed a good suggestion, but the problem lies in the deconstruction of an object. When useSelector gets the data, it is deconstructed. goodPriceInfo is an empty object at the beginning, and the deconstruction of the empty object is undefined. Change the deconstruction to a definition. This problem is solved.

**Comment by eps1lon** [comment]
Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

Coding Questions
If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

https://stackoverflow.com/questions/tagged/react

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html
