### ISSUE TITLE
Split out internal react properties from the user supplied props

### ISSUE THREAD

**Issue by wereHamster** [facebook/react#2656]
By internal react properties I mean `ref` and `key`. The current API design forces users to mix those two  into a single object. This is unfortunate in the case that the user wants to have props with the same name.

The `ReactElement` solves that problem nicely because it takes the `key`, `ref` and `props` as separate arguments. I understand that the current API is designed around a single props object, and the rest is treated as children. But I believe making explicit distinction between user supplied props and those used for internal purposes will lead to less confusion.

**Comment by chrislaughlin** [comment]
@wereHamster how would this translate into JSX, using the `createElement` does allow you to break things up but now sure how this would be achieved via JSX unless to passed the props as an attribute e.g.  `<Test ref='test' props={myProps} />`

**Comment by jimfb** [comment]
I agree with @chrislaughlin, supporting the use of those two props as valid user-defined props would be detrimental to anyone using JSX (since there is currently no way of specifying them).  For this reason, we probably aren't going to support it in the near future.  Feel free to continue the discussion on this thread, and we can re-open if our thinking on this matter changes substantially.
