### ISSUE TITLE
[DevTools Bug]: components tree not loaded in Microsoft Edge

### ISSUE THREAD

**Issue by HadarZ** [facebook/react#26709]
### Website or app

https://react.dev/

### Repro steps

1. Load react app in Microsoft Edge
2. Open dev tools and go to components tree 
3. The tree is not loaded: 
4. This is the message I get: Loading React Element Tree... If this seems stuck, please follow the [troubleshooting instructions](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#the-react-tab-shows-no-components).

Edge version - latest: Microsoft Edge
Version 112.0.1722.58 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/16520016/233919983-66f889b5-4f53-416f-8609-e6f8b9cc205c.png)

### How often does this bug happen?

Every time

**Comment by hoxyq** [comment]
Hey @HadarZ,

Thanks for reporting this. We have recently published version 4.27.6 for Edge browser with a possible fix for this issue. Could you please try it out?

**Comment by HadarZ** [comment]
@hoxyq Thank you so much! I removed the extension and installed the new version, it's working now.

**Comment by krotovic** [comment]
@hoxyq Since I posted here the comment I tried to investigate a little further and found that the console error is probably not related to the issue as the comment in the related code says [here](https://github.com/facebook/react/blob/main/packages/react-devtools-extensions/src/background.js#L34).

Also after I updated the extension everything works and no error in the console as well.
