### ISSUE TITLE
Bug: React Native Web blocking request

### ISSUE THREAD

**Issue by PracticasSlope9** [facebook/react#26875]
I have an app working without problems with react-native but the same app when I use it with react-native-web the request gives me this problem:

Access to XMLHttpRequest at '...' from origin 'http://localhost:19006' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
re

The server I make the requests to is configured correctly, the calls work in react native but not in react native web

**Comment by MeenuyD** [comment]
Hello @PracticasSlope9, This is not an issue with the react native this because when we call the API then it is blocked by the browser and CORS policy. Because it is calling from one origin to another origin if any is mismatched then the browser will block it. You can Install a CORS browser extension that allows you to override CORS restrictions during development. These extensions modify the headers in your browser to bypass CORS restrictions temporarily by toggling the CORS.
