### ISSUE TITLE
Bug: Radio button onChange not called in current React Canary

### ISSUE THREAD

**Issue by robrichard** [facebook/react#26876]
React version: 18.3.0-canary-a1f97589f-20230526

## Steps To Reproduce

1. Create radio buttons that toggle `disabled` in `onChange`
2. After selecting each radio button, `onChange` is no longer called

Link to code example:

The following CodeSandbox demonstrates the issue with the current react canary version. The issue is not present when react & react-dom versions are changed to stable 18.2.0

https://codesandbox.io/s/react-canary-radio-buttons-deiqb3?file=/src/App.js

## The current behavior
`<input type="radio" />`'s `onChange` prop is not called on subsequent clicks of the input

## The expected behavior
`<input type="radio" />`'s `onChange` prop should be called on subsequent clicks of the input

**Comment by eps1lon** [comment]
As far as I an tell this also repros without toggling `disabled`: https://codesandbox.io/s/react-canary-radio-buttons-forked-ydjdlp?file=/src/App.js

So it's just about changing the controlled `checked` delayed.

**Comment by mohdanss** [comment]
I noticed a potential issue with the radio buttons in the code. Although the `checked` attribute is based on the `value` state, it appears that the `value` is not being updated correctly inside the `handleChange` event handler. As a result, the `checked` attribute doesn't reflect the actual selected radio button. Because change is called, based on change in the value of input, not toggle.

To fix this issue, you can update the `value` inside the `handleChange` event handler. Here's the code that should be added inside the event handler to ensure the `value` state is updated correctly:

```jsx
setValue(e.target.value);
```

With this line of code, the `value` state will be set to the value of the selected radio button, ensuring that the `checked` attribute is updated accordingly.

Additionally, if you want to toggle between "one" and "two" values in the `value` state, you can use the following code instead:

```jsx
setValue(value === "one" ? "two" : "one");
```

This line of code checks if the `value` is currently "one". If it is, it sets the `value` to "two". Otherwise, if the `value` is "two", it sets the `value` to "one". This will ensure that the `value` state is updated correctly and the radio buttons' `checked` attribute reflects the selected option.

By applying these changes, the radio buttons should now update their `checked` attribute correctly when a different option is selected, and on change will be called.

I hope this helps! Let me know if you have any further questions.

**Comment by Luk-z** [comment]
The problems was introduced with `18.3.0-next-1f248bdd7-20230419`. The previous version `18.3.0-next-d962f35ca-20230418` works.

**Comment by robrichard** [comment]
It looks like it was this change that introduced this bug: https://github.com/facebook/react/pull/26667

**Comment by kambleaa007** [comment]
what are ways to fix this issue?

**Comment by zhengjitf** [comment]
FYI, I find something by investigating, as below:

`extractEvents`:
https://github.com/facebook/react/blob/6aacd3fa1567ed35c7ae4a69627ec1a1543df760/packages/react-dom-bindings/src/events/plugins/ChangeEventPlugin.js#L322-L331

`onChange` isn't called because `inst` here is falsy in that process. PS: In our case, `getTargetInstFunc` should be equal to `getTargetInstForClickEvent`. 

Diving into the inner functions as the followings.

`getTargetInstForClickEvent`:
https://github.com/facebook/react/blob/6aacd3fa1567ed35c7ae4a69627ec1a1543df760/packages/react-dom-bindings/src/events/plugins/ChangeEventPlugin.js#L117-L122

`updateValueIfChanged`:
https://github.com/facebook/react/blob/6aacd3fa1567ed35c7ae4a69627ec1a1543df760/packages/react-dom-bindings/src/client/inputValueTracking.js#L141-L147

`tracker`:
https://github.com/facebook/react/blob/6aacd3fa1567ed35c7ae4a69627ec1a1543df760/packages/react-dom-bindings/src/client/inputValueTracking.js#L103-L111

We can find the key is that the tracked value should be different from the value get from `node` (`getValueFromNode(node)`) in our case. We can believe the tracked value was not updated after the delayed state change, which cause the issue.

**Analysis by reproduction steps** (Please visit [this demo](https://codesandbox.io/s/react-canary-radio-buttons-forked-vjsfd2?file=/src/App.js), which can print the tracked values):
1. Initially: 
    - One: checked (`getValueFromNode(node)` is `'true'`), and the tracked value is `'true'`
    - Two: unchecked, and the tracked value is `'false'`
2. Click 'Two', and wait for delayed `setValue`: `onChange` is called 
    - One: unchecked, and the tracked value is `'false'`
    - Two: checked, and the tracked value is `'true'`
3. Click 'One', and wait for the delayed `setValue`: `onChange` is called 
    - One: checked, and the tracked value is `'true'`
    - Two: unchecked, and the tracked value is `'true'`
4. Click 'Two', won't call `onChange` again

PS: The tracked value can be updated at the end of the event handler (by `restoreControlledInputState`), so Step 2 will result in the correct tracked values.

So, I think one solution is to update the tracked value (at the end of the commit mutation phase) when the checked prop changes.

**I'd like to submit a PR to fix it. Any corrections or suggestions will be appreciated, (for I'm not sure if I miss anything important).**
