### ISSUE TITLE
Bug: React run cleanup for zero dependency `useEffect` for the first time

### ISSUE THREAD

**Issue by hkar19** [facebook/react#26912]
I encounter some confusing bug(?) as cleanup will run once when a component load.
is this intentional behavior? i thought if there is no deps for this `useEffect`, cleanup will only run when the component dismount.

React version: 18.2

## Steps To Reproduce

1. use `useEffect` with zero deps
2. at first load, cleanup ran once

Link to code example: https://codesandbox.io/s/peaceful-sea-fk1llt?file=/src/App.js

## The current behavior

cleanup run once at first start

## The expected behavior

cleanup run only when the component did unmount (as there is zero deps)

**Comment by kiljag** [comment]
That is the default behavior of react strict mode. react renders each component twice in development mode.

check out this. https://react.dev/reference/react/StrictMode

**Comment by MeenuyD** [comment]
Hello yes react in strict render the component twice and when using the useEffect hook with an empty dependency array ([]), the effect is meant to run only once, similar to the componentDidMount lifecycle method in class components.

The cleanup function specified in the effect will be invoked when the component is unmounted, regardless of whether there are dependencies or not. However, in the case of an empty dependency array, the effect will not be re-triggered on subsequent re-renders of the component. I think so this behavior is intentional and follows React's rules for managing effects.

**Comment by stephanemalho** [comment]
here is the order for the render & re-render: 
• APP read his component but bypass useEffect 
• than he go to the children component 
• he read the children file and bypass useEffect
• Now he read the useEffect inside the children
• he Do a re-render of the children (bypassing useEffect duh)
• return to App to read if there is a useEffect 
• re-rend APP

import "./styles.css";
import { useEffect } from "react";

export default function App() {
  console.log("first read")
  return (
    <div className="App">
      <User />
    </div>
  );
}

const User = (props) => {
  console.log("second read")
  useEffect(() => {
    console.log("user effect fourth read", props);
    return () => {
      console.log("user cleanup fifth read or first read of all if the componentWillUnmount()  ", props);
    };
  }, []);
  console.log("thirth read")
  return <h1>user</h1>;
};

`

**Comment by PurpleMonkey729** [comment]
@stephanemalho
Thanks for your answer.
At 2th step "• than he go to the children component", 'than" is right?
Is it "then", isn't it?

**Comment by stephanemalho** [comment]
> @stephanemalho
> 
> Thanks for your answer.
> 
> At 2th step "• than he go to the children component", 'than" is right?
> 
> Is it "then", isn't it?

Yes it is you right ☺️
