### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Karim-Muhammad** [facebook/react#26988]
React version: 18.2.0

Link to code example: https://codesandbox.io/s/wizardly-jepsen-yvx6zq?file=/src/App.js:0-910

Screenshot for Bug which shown when i ran this code
![image](https://github.com/facebook/react/assets/40609142/d940dc91-73e4-427b-ae43-d6e1c16fcc8c)
```js
import { createSlice } from "@reduxjs/toolkit";

const postsSlicer = createSlice({
    name: 'posts',
    initialState: [
        { id: 1, title: 'Learning Redux', content: "I've heard Good things", },
        { id: 2, title: 'Slices...', content: 'the more i say slice, the more i want pizza' },
    ],
    reducers: {},
})


export default postsSlicer.reducer;

export const selectAllPosts = (store) => store.posts;

export const actions = postsSlicer.actions;
```
```js
import {useSelector} from 'react-redux';
import { selectAllPosts } from '../../app/features/posts/slicer';

const PostsList = (props) => {
    const posts = useSelector(selectAllPosts);
    const postsListjsx = posts.map(post => (
        <article key={post.id}>
            <h3>{post.title}</h3>
            <p>{post.content.substring(0, 100)}</p>
        </article>
    ))

    // console.log(posts) // Array of Posts
    // console.log("JSX ",postsListjsx) // Array of JSX

    return (
        {postsListjsx}
    )
}
```

## The current behavior
Here it gives me an Error for rendering an Object instead of Array in my code, and i'm not render an Object!

## The expected behavior
actually in my code return multiple root elements, thus, I think it should throw an Error for
![image](https://github.com/facebook/react/assets/40609142/bd2929b1-9475-4bdb-9d93-e8aed5cfab33)

trying fixing error by this error message make me tired, i don't know if it is intentionally or not.

**Comment by animesh9893** [comment]
Hii @Karim-Muhammad, can you please checkout this. [https://codesandbox.io/s/falling-snow-2kn7hk?file=/src/App.js](https://codesandbox.io/s/falling-snow-2kn7hk?file=/src/App.js)

That map of authors code is returning an array which is type of object.

So and as you can see in error 
![image](https://github.com/facebook/react/assets/54549306/8f493312-13fc-45a3-b989-50534696de74)
Objects can't be render as child.

**Comment by mr07s** [comment]
@Karim-Muhammad  I think I have solved your issue please check it out 

https://codesandbox.io/s/dazzling-dust-tx2qwm?file=/src/App.js
![Screenshot (365)](https://github.com/facebook/react/assets/106861707/b00c5379-0331-47bd-9b3a-a77f5d2b78aa)

**Comment by Karim-Muhammad** [comment]
> That map of authors code is returning an array which is type of object.

the message error says use `array` instead of `object`, and i really return `authors.map()`(array), so message error doesn't clarify the problem enough, actually it make confusion, that's my point

yeah, I know type of array is object, but we actually can render an Array(Object) in JSX in case it is child not parent to <div> for example, by this example if we did that
```js
<div> {array} </div> //Correct
```
that's OK, but if `array` is a parent (without a container <div>)
```js
return {array} // Wrong
```
it throw an Error (not meaningful message) says as I mentioned above "cannot render object" instead of "cannot have multiple root elements"

the Error message you have shown above, says what i did already in my code, i'm trying to render an Array, and avoid using "Object"

I don't know if you got my point, I apologize for any confusion.

**Comment by Karim-Muhammad** [comment]
Thanks for your time, I appreciate that

my point is that error message doesn't clarify my problem precisely

**Comment by pcha07** [comment]
Based on the error message you provided, it seems that the issue lies in how you are rendering the postsList.jsx array in your PostsList component. The error suggests that you are trying to render an object instead of an array.

To resolve this issue, you need to wrap the postsList.jsx array in a parent element when returning it from the component. One way to achieve this is by using a React fragment (<>...</>) as suggested in the error message. Here's an updated version of your PostsList component: 

import { useSelector } from 'react-redux';
import { selectAllPosts } from '../../app/features/posts/slicer';

const PostsList = (props) => {
  const posts = useSelector(selectAllPosts);
  const postsListjsx = posts.map(post => (
    <article key={post.id}>
      <h3>{post.title}</h3>
      <p>{post.content.substring(0, 100)}</p>
    </article>
  ));

  return (
    <>
      {postsListjsx}
    </>
  );
}

export default PostsList;

By wrapping the postsListjsx array in <>...</>, you create a parent element that contains the array elements. This allows you to return multiple elements without encountering the "Adjacent JSX elements must be wrapped in an enclosing tag" error.

After making this change, the error you mentioned should be resolved, and the PostsList component should render the list of posts correctly.
