### ISSUE TITLE
Bug: Resetting the value comes from dynamic `defaultValue` of `<input type="search" />` won't trigger `onChange`

### ISSUE THREAD

**Issue by SukkaW** [facebook/react#26998]
React version: 18.2.0

## Steps To Reproduce

1. Open the reproduction below.
2. Waiting for `Hello, World` to show up in the input.
3. Do not input/delete anything in the input. Just click the `X` button of the `<input type="search" />`:

<img width="433" alt="image" src="https://github.com/facebook/react/assets/40715044/8605002f-b0b0-489e-a16e-b56d3658948e">

Link to code example: https://stackblitz.com/edit/stackblitz-starters-qedxnn?file=src%2FApp.tsx

## The current behavior

When clicking the `X` button of the `<input type="search" />`, `onChange` should still trigger, even if the value if from `defaultValue`. 

## The expected behavior

When clicking the `X` button of the `<input type="search" />`, `onChange` is not triggered.

## Additional Information

The related source code might be this: https://github.com/facebook/react/blob/8ec962d825fc948ffda5ab863e639cd4158935ba/packages/react-dom-bindings/src/client/ReactDOMInput.js

I don't know if this is intended behavior. And if it is, what should I do to track when the user resets the value from `defaultValue`?

**Comment by SukkaW** [comment]
My current workaround is, add the `key` to the `<input />`:

```tsx
<input
  type="search"
  key={defaultValue}
  defaultValue={defaultValue}
/>
```

This can make React reset `<input />` when the `defaultValue` changes.

**Comment by SukkaW** [comment]
> https://stackoverflow.com/questions/30727837/react-change-input-defaultvalue-by-passing-props

It is not related at all.

The issue **is not** the React DOM can't apply "asynchronous" `defaultValue`. As you can see in my reproduction, though the new `defaultValue` is only loaded after more than 1 second, React DOM still correctly applies it.

The issue is that after React DOM applies `defaultValue`, "reset" the input won't trigger `onChange`.

**Comment by zhenmang** [comment]
[defaultValue is uncontrolled inputs](https://zh-hans.react.dev/reference/react-dom/components/input).
Consider using value instead, it will become normal.

**Comment by SukkaW** [comment]
> [defaultValue is uncontrolled inputs](https://zh-hans.react.dev/reference/react-dom/components/input). Consider using value instead, it will become normal.

I AM creating uncontrolled input. That's why I need the `onChange` to fire normally even with dynamic `defaultValue`.

**Comment by rothsandro** [comment]
The problem is not related to the search input or its clear button but can be reproduced with a normal text input by selecting the whole text and clearing it at once.

---

React tracks the value of the input and emits the onChange event only if the value has actually changed. In this scenario, React initially sets the `defaultValue` but not the `value` property as it's already empty. When the default value is changed, React updates the `defaultValue` but not the `value` property (which is correct) - the value tracker doesn't notice that the value of the input has changed (but it has changed because the value has not yet been set so the browser uses the new defaultValue). When you now clear the input, both, the previous value (hold by the value tracker) and the new value of the input, are an empty string. For React it looks like nothing has changed and it doesn't emit the event.

If a non-empty string is initially provided as default value (and later updated), React initially sets both, the `defaultValue` and the `value` property. The latter is captured by the value tracker and when clearing the input it detects an actual change and emits the event.

Maybe React could update the tracker value (to the current node value) when it updates the `defaultValue` property. This way the tracker would be aware of the new value.

**Comment by SukkaW** [comment]
> The problem is not related to the search input or its clear button but can be reproduced with a normal text input by selecting the whole text and clearing it at once ... React tracks the value of the input and emits the onChange event only if the value has actually changed ... This way the tracker would be aware of the new value.

Thanks for your detailed explanation!

**Comment by parth-bhadra** [comment]
While going through this thread, I opened up react code for the first time.
[](https://github.com/facebook/react/blob/8ec962d825fc948ffda5ab863e639cd4158935ba/packages/react-dom-bindings/src/client/ReactDOMInput.js)

Why do function parameters have data types written along side them even though it is a .js file?

**Comment by SukkaW** [comment]
> While going through this thread, I opened up react code for the first time. https://github.com/facebook/react/blob/8ec962d825fc948ffda5ab863e639cd4158935ba/packages/react-dom-bindings/src/client/ReactDOMInput.js
> 
> Why do function parameters have data types written along side them even though it is a .js file?

Off-topic though. Let me answer this for you. The React source code was written in [flow](https://github.com/facebook/flow).
