### ISSUE TITLE
Are Effect Events really necessary? 

### ISSUE THREAD

**Issue by cuiyangam** [facebook/react#27075]
In the following official example, I use plain JS functions instead of Effect Events, isn't this more concise?

https://codesandbox.io/s/elegant-chaum-cwnyr9

before:
<img width="591" alt="image" src="https://github.com/facebook/react/assets/73875927/11359d1c-04a8-44b8-aac7-99f63b9a5716">
after:
<img width="591" alt="image" src="https://github.com/facebook/react/assets/73875927/07648582-eea4-4c17-8405-0cd6e7781553">

**Comment by josephearl** [comment]
The after is incorrect because all reactive values (like props) should be declared as a dependency of useEffect, but theme is not declared as a dependency
This should give you a lint error
https://react.dev/learn/lifecycle-of-reactive-effects#react-verifies-that-you-specified-every-reactive-value-as-a-dependency

**Comment by atomiks** [comment]
Yes they are, due to closures. In your example, it's not an issue because the event only fires once when `roomId` changes, which means the `theme` will be the latest value as well.

But there are cases where events fire more than once after the effect runs, e.g event listeners or async code, as shown on the docs:

```js
const [canMove, setCanMove] = useState(true);

function handleMove(e) {
  if (canMove) {
    setPosition({ x: e.clientX, y: e.clientY });
  }
}

useEffect(() => {
  window.addEventListener('pointermove', handleMove);
  return () => window.removeEventListener('pointermove', handleMove);
}, []);
```

When `canMove` changes, the `handleMove` function is not aware of the new state, because it's referencing a stale `canMove` value for the last render (when the event listener first got registered). 

By using an Effect Event, it will see the latest `canMove` state, even though the effect never re-runs.

**Comment by cuiyangam** [comment]
@atomiks 
Perfect answer! It seems that useEffect is a necessary feature in react if you need to get the latest value in the event listening function.
