### ISSUE TITLE
Bug: `useId` generates a new different ID on second render of Strict Mode before un-mount

### ISSUE THREAD

**Issue by ernestostifano** [facebook/react#27103]
React version: `v18.2.0`

## Steps To Reproduce

1. Create a component with `useId` and log the generated ID inside the component body.
2. Use an `useEffect` to log when the component mounts/un-mounts
3. Mount the component in Strict Mode.
4. Note how first and second render have different IDs (all of this before the component even un-mounts).

Link to code example: https://codesandbox.io/s/modern-currying-nqqn68

## The current behavior
`useId` is returning different IDs across renders of the same component instance without un-mounting.

I know that Strict Mode does a lot of weird things to make sure components are pure and I understand the double-render idea and even skipping deps checks for some hooks, but I hope returning different IDs between two renders of the same component instance is not the expected behaviour.

As you can see in the linked sandbox, the following code:

```js
  const id = useId();

  console.log("RENDER", id);

  useMemo(() => {
    console.log("MEMO");
  }, []);

  useEffect(() => {
    console.log("MOUNT");

    return () => {
      console.log("UN-MOUNT");
    };
  }, []);
```

Produces the following output:

```bash
RENDER :r0: 
MEMO 
RENDER :r1: 
MEMO 
MOUNT 
UN-MOUNT 
MOUNT 
```

Which makes absolutely no sense to me.

## The expected behavior
`useId` should provide the same ID during the entire life of a component instance. It should only change if the component mounts again.

**Comment by TamashiiD** [comment]
I see the same issue and I think it has something to do with the useEffect. I'm not sure but for me useEffect always makes everything run 2 times for me instead of the 1 time that it's supposed to. Like not only is it rendering a different ID but it is also mounting twice. Is it supposed to Mount twice? I'm a beginner and just looking into these things. please tell me what you think. thank you.

**Comment by icyJoseph** [comment]
Not sure if related, but https://codesandbox.io/p/sandbox/empty-butterfly-y36f8d?file=%2Fapp%2Flayout.tsx%3A1%2C1 in Next.js App Dir pages, a similar issue is happening.

- https://github.com/vercel/next.js/issues/53110

**Comment by JSerZANP** [comment]
I guess this is expected behavior.

1. under `<StrictMode/>`, component is rendered twice https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberHooks.js#L597-L610

2. and for `useId()`, it falls back to a global counter if it is no in hydration.https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberHooks.js#L2613-L2632

In your demo, you are NOT doing hydration and also under `<StrictMode/>` so you get different ids.

This is not about `useId()`, if you switch to `const [id] = useState(() => performance.now())`, you still get the unstable ids.
I'm not React maintainer, but I don't think this has an easy fix because of what StrictMode does. Also this usually should not cause trouble.

**Comment by ernestostifano** [comment]
> I'm not React maintainer, but I don't think this has an easy fix because of what StrictMode does. Also this usually should not cause trouble.

@JSerZANP I am aware of what `StrictMode` does. The problem is the order in which everything is happening. Each instance of a component should have its own unique and persistent ID. So, it makes sense that the ID changes after the component un-mount and mounts again, but not across re-renders of the same instance (before un-mount happens).

Now, I am also aware that having `useId` working as described above (which is the only way it should work to make sense) opens the possibility of bypassing other hooks strict controls (like `useMemo` that will be called twice and `useRef` that will reset its value after the second render). For example, by keeping an external reference using the instance ID.

But, if this is in fact on purpose, then I really think it is an exaggeration. If people want to consciously do strange things and go agains the `StrictMode` rules, so be it. We cannot make `useId` useless.

Like this it could only be reliably used for input/label HTML IDs... so at least, change the hook name right? So people will not get confused thinking that ID actually remains constant through the entire life of the instance.

I've been working with React for years and I cannot wrap my head about this.

**Comment by nvie** [comment]
I also ran into this issue! One workaround I found that respects React’s rules and StrictMode rules is to move the generation of such IDs to _outside_ of the component—if that’s an option for you.

For example:

```jsx
function Outer() {
  const id = useId()
  return <Inner id={id} />
}

function Inner() {
  const id = props.id;  // Read stable ID from props instead

  console.log("RENDER", id);

  useMemo(() => {
    console.log("MEMO");
  }, []);

  useEffect(() => {
    console.log("MOUNT");

    return () => {
      console.log("UN-MOUNT");
    };
  }, []);
}
```

This way, each component behaves correctly in its own “strict mode” context.

I hated this solution as it definitely feels like a workaround / fighting the system, though. But maybe this sparks a new branch of thoughts. I’m still open to finding a better solution for this too.

**Comment by ernestostifano** [comment]
bump
