### ISSUE TITLE
Feat request: addition of use client in a specific component

### ISSUE THREAD

**Issue by revogabe** [facebook/react#27153]
I came across a question, I would like to create 3 components in the same file, 2 client files and 1 server file

example:

```tsx
export function DialogServer() {
'use server'
return (
// component
)}

export function Button() {
'use client'
return (
// component
)}

export function Dialog() {
'use client'
return (
// component
)}
```

**Comment by prabh1234assla** [comment]
I would like to work on this issue.

**Comment by abhi152003** [comment]
Creating three components in the same file, with two of them being client-side components and one being a server-side component, is possible with the use of the @react/bridge pragma. This pragma is used to differentiate between client and server components in a single file. However, please note that the @react/bridge pragma is a fictional annotation used for illustrative purposes and is not a standard or built-in feature of React.

Here's how you can structure your file:

```
// MyComponent.js

export function DialogServer() {
  'use server';
  return (
    // Server-side component
  );
}

export function Button() {
  'use client';
  return (
    // Client-side component
  );
}

export function Dialog() {
  'use client';
  return (
    // Client-side component
  );
}

```

In this example, DialogServer is intended to be used on the server-side, while Button and Dialog are intended to be used on the client-side. When using server-side rendering, components with the 'use server' pragma will be rendered on the server, and components with the 'use client' pragma will be rendered on the client.

Please note that the @react/bridge pragma is not a real feature of React, and you cannot use it directly as shown in the example. Instead, you would need to use a server-side rendering library or framework that supports this kind of component separation for client and server rendering. Examples of such libraries include Next.js for React or Nuxt.js for Vue.js. These frameworks provide ways to create separate client and server entry points for your components.

If you intend to create components for server-side rendering, you should consider using a framework or library that provides server-side rendering capabilities. Otherwise, you can structure your components in separate files, with a convention to indicate whether they are intended for server or client use.

**Comment by revogabe** [comment]
this feature would be great, and I would like to discuss this already having it in react by default, it would be something good and optional for anyone who wants to use it, I would like to know if there is such a possibility
