### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by bappyasif** [facebook/react#27154]
React version: 18.2*

## Steps To Reproduce

1. on page load its not throwing any error
2. im working with typescript and redux toolkit
3. when working on editor and saving it, specifically when i started working on a "custom hook", you will find that in "/hooks/forComponent.ts"
4. in console it keeps showing "uncaught error, should have a queue"
5. react-dom.development.js:16572 Uncaught Error: Should have a queue. This is likely a bug in React. Please file an issue.
![image](https://github.com/facebook/react/assets/19854521/1c2f0490-ab7b-4493-a6af-118a1a0de97f)

Link to code example: [https://github.com/bappyasif/varius-hooks-and-toolkits/blob/for-react-bug-report/src/features/ingredients/MostPopularIngredients.tsx](https://github.com/bappyasif/varius-hooks-and-toolkits/blob/for-react-bug-report/src/features/ingredients/MostPopularIngredients.tsx)

https://github.com/bappyasif/varius-hooks-and-toolkits/tree/for-react-bug-report

## The current behavior
whenever im working on this [custom hook](https://github.com/bappyasif/varius-hooks-and-toolkits/blob/53278a30f4ec5b9cc6455fd433259b9f3a9a0146/src/hooks/forComponents.ts#L171C14-L171C38)
its throwing error and crashes app

## The expected behavior
should update code without crashing app

**Comment by abhinav-nav** [comment]
I've reviewed your code and I think I've found the cause of the error. The useEffect hook in your custom hook is calling useState inside of a conditional statement. This is not allowed, because useState can only be called once per render. When you save your code, React will re-render the component, and the useEffect hook will be called again. However, the conditional statement will now have a different value, so useState will be called again, even though it's already been called once. This is what's causing the error.

To fix this, you need to move the useState call outside of the conditional statement. Here's the corrected code:

const useForComponent = () => {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // This code will only be run once, when the component mounts.
    setIsLoading(false);
  }, []);

  if (isLoading) {
    return <Loading />;
  } else {
    return <SomeComponent />;
  }
};
This code will only call useState once, when the component mounts. This will prevent the error from occurring.

I hope this helps! Let me know if you have any other questions.
am open to collaborate and work

**Comment by bappyasif** [comment]
> I hope this helps! Let me know if you have any other questions.

thanks a lot, it gives me some insight about this problem that i was having, but im not sure or rather dont recall which one of these were causing this problem specifically (useToGetFourPopularItems / useToGetFourRandomItems ) 

fyi i later on refactored it and made it work just fine though :)

> open to collaborate and work
sounds like a very good idea, i would be very much willing to do that as well :)

**Comment by abhinav-nav** [comment]
> sounds like a very good idea, i would be very much willing to do that as well :)

>> sure
