### ISSUE TITLE
Bug: performance.mark is not a function

### ISSUE THREAD

**Issue by miniminivan** [facebook/react#27171]
After our pipeline upgraded to node 16, some unit tests were beginning to fail, with the error message below. These tests previously passed with node 14, and the call to performance.mark is within a file in react-dom. I've read some issues with node 16 changing the behavior of performance, so I am not sure if that could be a possible issue. I've also created an issue with the enzyme team below: 
[https://github.com/enzymejs/enzyme/issues/2599](https://github.com/enzymejs/enzyme/issues/2599).
This is preventing us from merging our code and moving on with development.

React version: "16.14.0"

## Steps To Reproduce

1. Can't provide code to rerun, but here is the package.json
```
{
  "name": "test-ui",
  "version": "0.8.0",
  "description": "Valkyrie",
  "main": "dist/index.js",
  "dependencies": {
    "@babel/runtime": "^7.8.4",
    "classnames": "^2.2.6",
    "core-js": "^3.6.4",
    "dotenv-webpack": "^8.0.0",
    "es6-promise": "^4.2.8",
    "flux": "3.1.3",
    "history": "^4.9.0",
    "immutability-helper": "^3.0.1",
    "intl": "^1.2.5",
    "isomorphic-fetch": "^2.2.1",
    "match-all": "^1.2.6",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "solutions-eventbus-library": "^1.0.5",
    "superagent": "^5.0.5",
    "underscore": "^1.9.1",
    "url-loader": "^1.1.2"
  },
  "scripts": {
    "test": "node node_modules/mocha/bin/mocha --require @babel/register --require ignore-styles --require test-setup.js --reporter min \"./test/**/*-test.js\"",
    "integration-tests": "jest --env=jsdom --config ./integration-test-setup.js",
    "coverage": "cross-env NODE_ENV=test node ./node_modules/nyc/bin/nyc.js npm test report --reporter=lcov --reporter=html",
    "build": "npm run lint && npm run builddev",
    "builddev": "node node_modules/webpack/bin/webpack -d --env.box=dev",
    "buildci": "node node_modules/webpack/bin/webpack -p --env.box=ci",
    "buildg1": "node node_modules/webpack/bin/webpack -p --env.box=g1",
    "buildg2": "node node_modules/webpack/bin/webpack -p --env.box=g2",
    "buildg3": "node node_modules/webpack/bin/webpack -p --env.box=g3",
    "buildg4": "node node_modules/webpack/bin/webpack -p --env.box=g4",
    "buildperf": "node node_modules/webpack/bin/webpack -p --env.box=perf",
    "buildprod": "node node_modules/webpack/bin/webpack -p --env.box=prod",
    "lint": "eslint .",
    "watch": "webpack --watch",
    "fix": "eslint . --fix",
    "clean": ""
  },
  "author": {
    "name": "Pivotal Lab"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@babel/plugin-transform-async-to-generator": "^7.8.3",
    "@babel/plugin-transform-react-jsx": "^7.3.0",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@babel/plugin-transform-template-literals": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.4.4",
    "@babel/runtime-corejs3": "^7.8.4",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-istanbul": "^5.1.4",
    "babel-plugin-rewire": "^1.2.0",
    "babel-plugin-webpack-alias": "^2.1.2",
    "chai": "^4.2.0",
    "cheerio": "1.0.0-rc.10",
    "cross-env": "^5.2.0",
    "css-loader": "^2.1.1",
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.12.1",
    "eslint": "^5.16.0",
    "eslint-plugin-react": "^7.13.0",
    "file-loader": "^3.0.1",
    "global-jsdom": "^8.1.0",
    "html-webpack-plugin": "^3.2.0",
    "ignore-styles": "^5.0.1",
    "jest": "^27.0.6",
    "jsdom": "^15.2.1",
    "keymirror": "^0.1.1",
    "mocha": "^6.1.4",
    "nyc": "^14.1.0",
    "react-test-renderer": "^16.8.6",
    "rosie": "^2.0.1",
    "sinon": "^7.3.2",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.1",
    "webpack-merge": "^4.2.2"
  },
  "publishConfig": {
    "registry": "https:/.../api/npm/npm-local/"
  }
}
```

## The current behavior
Here is a snippet, I can only share a limited amount of code. But we do this set up in each of our test files.
```
    const setupComponent = (InputProps) => {

        const props = Object.assign({}, InputProps);
        const component = mount(<Header {...props} />);
        return component;
    };

    beforeEach(() => {
        header = setupComponent(defaultProps);
    });
```
here is the stack trace:
```
  2) TestFileName
       "before each" hook for "should render":
     TypeError: performance.mark is not a function
      at beginMark (node_modules\react-dom\cjs\react-dom.development.js:10238:15)
      at startWorkLoopTimer (node_modules\react-dom\cjs\react-dom.development.js:10493:5)
      at performSyncWorkOnRoot (node_modules\react-dom\cjs\react-dom.development.js:21752:5)
      at scheduleUpdateOnFiber (node_modules\react-dom\cjs\react-dom.development.js:21188:7)
      at updateContainer (node_modules\react-dom\cjs\react-dom.development.js:24373:3)
      at C:\...\node_modules\react-dom\cjs\react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules\react-dom\cjs\react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules\react-dom\cjs\react-dom.development.js:24757:5)
      at Object.render (node_modules\react-dom\cjs\react-dom.development.js:24840:10)
      at fn (node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:488:26)
      at C:\...\node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:405:37
      at batchedUpdates$1 (node_modules\react-dom\cjs\react-dom.development.js:21856:12)
      at Object.act (node_modules\react-dom\cjs\react-dom-test-utils.development.js:929:14)
      at wrapAct (node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:405:13)
      at Object.render (node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:474:16)
      at new ReactWrapper (node_modules\enzyme\src\ReactWrapper.js:115:16)
      at mount (node_modules\enzyme\src\mount.js:10:10)
      at setupComponent (test\Components\Header\/file-test.js:50:27)
      at Context.<anonymous> (test\Components\Header\/file-test.js:75:22)
      at processImmediate (node:internal/timers:466:21)
```

**Comment by Abdullah-Web-D** [comment]
The error message you are encountering indicates that the function performance.mark is not available or not a function in the environment where the test is running. This issue seems to be related to the upgrade to Node 16, as you suspected, because Node 16 introduced changes to the behavior of the performance object in certain environments.

The error is occurring in the React library (react-dom.development.js), which suggests that the issue might be with the testing setup or the testing library you are using (e.g., Jest or Enzyme) rather than the React version itself.

Here are some steps you can take to troubleshoot and resolve the issue:

Check Testing Dependencies Compatibility: Ensure that all your testing dependencies (Jest, Enzyme, etc.) are compatible with Node 16 and React 16. Sometimes, certain testing libraries might have issues with newer Node versions.

Update Testing Libraries: Make sure you have the latest versions of testing libraries installed. Newer versions often contain bug fixes and compatibility improvements.

Check Jest Configuration: If you are using Jest as your testing framework, check the Jest configuration file (jest.config.js or jest.config.json) to see if there are any specific settings or transforms that might be affecting the behavior of performance.mark.

Check Enzyme Configuration: Similarly, check your Enzyme configuration. Ensure that the Enzyme adapter for React 16 is compatible with the Node 16 environment.

Verify Babel Configuration: The error might also be related to Babel configuration. Ensure that Babel presets and plugins are up to date and compatible with Node 16.

Check Performance Polyfills: Some libraries or polyfills used in your project might affect the behavior of the performance object. Ensure that there are no conflicting polyfills or that they are correctly configured for Node 16.

Review React-Related Code: Double-check the relevant parts of your React code that use the performance.mark function. Make sure there are no issues with how this function is called or any potential side effects.

Debugging: If the issue persists, you can try debugging the test execution with Node 16 and see if you can pinpoint the exact location where the error is occurring.

Temporary Downgrade: As a temporary solution, you might consider downgrading Node back to version 14 or any other version where the tests were passing until the issue with Node 16 is resolved.

Keep in mind that it's challenging to provide an exact solution without access to the complete codebase and the ability to run the tests directly. If none of the above steps help, it's worth checking the issue you've created on the enzyme GitHub repository (enzymejs/enzyme#2599) regularly to see if there are any updates or solutions from the Enzyme team. Additionally, you can also seek help from the React community and other developers who might have encountered similar issues after upgrading to Node 16.
