### ISSUE TITLE
Bug: fixtures/packaging/babel-standalone/dev.html Gives 'ReactDOM.render is no longer supported' Error

### ISSUE THREAD

**Issue by MattEvanoff** [facebook/react#27196]
I have already opened a PR for this, but am adding this issue to follow the How to Contribute documentation.
PR with fix: https://github.com/facebook/react/pull/27195

Following the process in the How to Contribute documentation, after the first build, to test it says to open the file: `fixtures/packaging/babel-standalone/dev.html`

Opening it, the console gives this error:

`react-dom.development.js:81 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

![image](https://github.com/facebook/react/assets/479664/3c876261-94e9-4082-a994-6eebb9094ef0)

React version: Main branch

## Steps To Reproduce

1. Clone fresh copy of repo
2. Follow How to Contribute documentation
3. Run `yarn build react/index,react-dom/index --type=UMD`
4. Open `fixtures/packaging/babel-standalone/dev.html`
5. Open console, see error

## The current behavior

Shows error

## The expected behavior

Should not show error

**Comment by MattEvanoff** [comment]
As to not confuse someone into picking this up unnecessarily, I have created a PR with a fix for this: https://github.com/facebook/react/pull/27195

**Comment by harrygz889** [comment]
I experience the same behavior, and wasn't able to detect the reason on loose inspection. The fix from https://github.com/facebook/react/pull/27195 does not fix the issue for me on current master though. 

Seems like an important one to fix up though, or at least update the contribution docs to not be misleading. 

Most recent commit there was https://github.com/facebook/react/commit/db5e6250d4bbb70c5085c58694a2e9c78c3f6371, so maybe a regression from @sebmarkbage's PR?

**Comment by eugenetree** [comment]
Based on the commit https://github.com/facebook/react/commit/da6ba53b10d8240fc251ba14a3e5878604d3dc7d
> In React 19 React will finally stop publishing UMD builds.
There are some fixtures that still have references to UMD builds however many of them already do not work (for instance they are using legacy features like ReactDOM.render) and rather than block the removal on these fixtures being brought up to date we'll just move forward and fix or removes fixtures as necessary in the future.

And that's the reason why now we're not able to follow that flow with running `yarn build --type=UMD_DEV react/index,react-dom` 

I'm not sure how it can be fixed and what the current way to "play" with react is, but I'll investigate how it can be temporarily achieved.
