### ISSUE TITLE
Request: Add a LICENSE file to the `client-only` package

### ISSUE THREAD

**Issue by nus3** [facebook/react#27242]
I am checking this link in the bugs section of the [client-only package.json](https://www.npmjs.com/package/client-only?activeTab=code).
Sorry if I created the issue in the wrong place.

The [client-only package](https://www.npmjs.com/package/client-only?activeTab=code) does not have a license file like `LICENSE.txt`, but package.json says MIT.
Is it possible to have a license file added to indicate that this package is MIT licensed?

**Comment by DanielRuf** [comment]
I see `"license": "MIT"` there: https://unpkg.com/browse/client-only@0.0.1/package.json

**Comment by 386jp** [comment]
In my opinion, one of the purposes of using LICENSE.txt is to check the copyright owner of this package. Currently, we cannot verify the ownership since it does not have a LICENSE.txt.

**Comment by DanielRuf** [comment]
The issue description implies something else:

>  Is it possible to have a license file added to indicate that this package is MIT licensed?

Tools like npm, pnpm, yarn, ORT and so on all detect this via package.json parser.

**Comment by rschristian** [comment]
> I see `"license": "MIT"` there: https://unpkg.com/browse/client-only@0.0.1/package.json

This is mostly NPM to blame, but `"license"` should be `"licenseType"` or similar; regardless, this is just meta data, not the document itself.

Listing the type of the license alone is not legally binding or enforceable in any manner as license types are not legally recognized. Unless a license is provided, the package is essentially unlicensed.

**Comment by DanielRuf** [comment]
> This is mostly NPM to blame, but `"license"` should be `"licenseType"` or similar; regardless, this is just meta data, not the document itself.

I can not really follow. npm has this field since the early beginnings. package.json is a standardized document which is used and supported by all major JS / Node package managers.

You don't need the full license document when you use one of the many (F)OSS licenses. Please also see SPDX and the license identifiers:
* https://spdx.dev/licenses/
* https://spdx.org/licenses/

All big SBOM tools (like [ORT](https://github.com/oss-review-toolkit/ort)) and license check tools like [licensee](https://www.npmjs.com/package/licensee) understand and support this way of defining the license.

Well, the scancode tool used by ORT even parses `license: MIT` lines from sourcecode file headers. You don't paste the full copyright text in there.

Custom modifications or additions of these standardized license texts make not much sense. Because then these are not valid (F)OSS licenses in many cases (some BSD-3-Clause and BSD-2-Clause licenses with additional clauses and text or dual-licensed software projects face this issue - you may not remember but Facebook tried to use such a BSD license with extra clause in the past which caused some big backslash in the community and they finally moved to MIT - that was years ago).

**Comment by rschristian** [comment]
> I can not really follow. npm has this field since the early beginnings. package.json is a standardized document which is used and supported by all major JS / Node package managers.
>
> You don't need the full license document

It doesn't matter that NPM allows you to set this meta data, it is not by itself legally binding.

Yes, you do always need a License file.

**Comment by DanielRuf** [comment]
> It doesn't matter that NPM allows you to set this meta data, it is not by itself legally binding. It also doesn't matter what some code scanning tools use.

> Yes, you do always need a dedicated License somewhere.

That would be really new to me. It's not npm. Please take a look at the current `license` field in the package.json file. You don't need the full license text for this, I can assure that. `MIT` is an official documented and standardized license.

**Comment by DanielRuf** [comment]
I suggest reading https://opensource.stackexchange.com/a/8122 and other resources, a license txt file is not required if the license itself is mentioned in the headers of source files or in the package metadata.

**Comment by DanielRuf** [comment]
I suggest reading https://opensource.stackexchange.com/a/8122 and https://opensource.stackexchange.com/a/7808 and other resources, a license txt file is not required if the license itself is mentioned in the headers of source files or in the package metadata.

From the second link:

> You can absolutely do that and it is fairly common. A file called LICENSE has no special legal significance. It is the responsibility of a user of the software to obtain necessary licenses, so the absence of a particular file doesn't give them any special permissions – if they don't find the license in the Readme, they cannot use the software.

IANAL, but tools like ORT and licensee can generate needed `LICENSE` files by extracting the used license from headers and metadata files.

**Comment by DanielRuf** [comment]
The license file of React is there: https://github.com/facebook/react/blob/main/LICENSE and applies to all packages under https://github.com/facebook/react/tree/main/packages

**Comment by Tricade** [comment]
Hi, this still affects `client-only@0.0.1`. I'm putting together third-party notices for a Docker image; the npm package says MIT but has no LICENSE file or copyright notice. Could a maintainer point me to the original notice that applies to this release, or confirm which copyright line to use? Thanks!
