### ISSUE TITLE
Bug: input onChange function not firing after dispatchEvent

### ISSUE THREAD

**Issue by jonathatargino** [facebook/react#27283]
React version: 18.2.0

## Steps To Reproduce

1. Create a input component using forwardRef
2. Call the import component and pass to it a ref and one onChange function.
3. Create a button to set imperatively input's value and dispatch the event.
4. Look how the onChange function will not be trigged

![image](https://github.com/facebook/react/assets/102263444/bb2cdc68-dbd1-4fbd-b542-1ea997f8500a)

codesandbox example:
https://codesandbox.io/p/sandbox/dreamy-fog-htzwhf?file=/src/App.tsx:18,22-18,39

vanilla javascript example (functional):
https://codepen.io/pen/?editors=1111

## The current behavior
After click the button, the input will receive a new value, but onChange is not triggered.

## The expected behavior
I was expecting that dispatchEvent could trigger change event.

**Comment by MarceloSpessoto** [comment]
Hi Jonatha,

I'm sorry if I am too late. However, I will let an explanation for anyone who comes across this problem.

The reason onChange is not being fired is because inputRef.current is not exactly a reference to the Input component, but a DOM Node associated with it. A DOM Node has no "onClick" attribute, but a "onclick".
You could solve the problem by setting the inputRef.current.onchange = (e) => {console.log(e.target.value)} and then dispatching the event as usual.
Here's my fix code:

```js

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);

  function handleClick() {
    if (inputRef.current) {
      inputRef.current.value = "input new value";
      inputRef.current.dispatchEvent(new Event("change"));
    }
  }


  // Using use Effect to set onchange on startup.
  useEffect(() => {
    inputRef.current.onchange = (e) => {console.log(e.target.value)}
  }, [])

  return (
    <>
      <Input
        ref={inputRef}
        placeholder={"Write your name"}
        name="myInput"
      />
      <button onClick={handleClick}>Click me!</button>
    </>
  );
}

```

**Comment by sophiebits** [comment]
Unfortunately due to how React's event bubbling is implemented it's not possible to simulate onChange with a simple dispatchEvent. 

If this is for testing purposes you can perhaps use React Testing Library's fireEvent: https://testing-library.com/docs/react-testing-library/faq

Otherwise I would recommend refactoring your code.
