### ISSUE TITLE
Bug: Incorrect  'removeChild' on 'Node'

### ISSUE THREAD

**Issue by liuhuakawaii** [facebook/react#27280]
React version: 18

## Steps To Reproduce

1.  There is a span dom on the page that switches based on the mouseenter event  
2. After entering the page, use Google Translate
3. Trigger the mouseenter event to switch span dom

Link to code example:

                                       <span
                                            onMouseEnter={() => setIsHover(true)}
                                            className={`${isHover ? style.spanhover : ''} ${style.textspan}`}
                                        >
                                            {isHover ? <span className={style.hoverText}>Recommended style reference</span>
                                                : chatLang === 'Chinese'
                                                    ? (
                                                        <>
                                                            请尽量提供
                                                            <span>光线明亮</span>
                                                            、
                                                            <span>不带阴影</span>
                                                            的清晰人像。
                                                        </>
                                                    )
                                                    : (
                                                        <>
                                                            {' '}
                                                            Please provide a clear portrait
                                                            with
                                                            {' '}
                                                            <span>bright lighting</span>
                                                            {' '}
                                                            and
                                                            {' '}
                                                            <span>no shadows.</span>
                                                        </>
                                                    )}
                                        </span>

## The current behavior

  Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by mvaibhav77** [comment]
Hello @liuhuakawaii ,

I appreciate your effort in bringing this issue to attention. I've taken a look at the provided code snippet, but it seems that the error you're encountering might not directly stem from the code you've shared. React can sometimes exhibit unexpected behaviors that might be tied to different parts of your application.

In order to assist you better, could you kindly provide us with more context and details? This would help us gain a clearer understanding of the situation. If you could provide the following information, it would be immensely helpful:

1. Additional Code Samples: If feasible, could you share any relevant sections of your code that are related to the "mouseenter" event and the manipulation of the <span> element?

2. Complete Error Message: Sharing the complete error message you're receiving, along with any associated stack trace or logs, would provide us with valuable insights into the nature of the issue.

3. Steps to Reproduce: Could you please describe the precise sequence of actions that lead to the error? This will allow us to recreate the problem on our end and better understand the context.
