### ISSUE TITLE
Cannot use input element in node-webkit?

### ISSUE THREAD

**Issue by QingYun** [facebook/react#2730]
I'm trying to use React in a node-webkit project, but there is a problem with `input` element. If a module exports a component containing a `input`, a "TypeError: Cannot read property 'firstChild' of undefined" error will be thrown when using it.

code:

```
# @cjsx React.DOM

React = require "react"

module.exports = React.createClass {
	render: ->
      <input type="text" value="Hello!" />
}
```

```
Test= require "./js/components/test"

App = React.createClass {
  render: ->
    <Test />
}

React.render <App />, document.body
```

This piece of code works fine if I replace `input` with `textarea` or other elements or just write `Test` and `App` in the same file.

**Comment by ghuser123** [comment]
The solution suggested by @QingYun  did not work for me . When I used the following snippet

```
<script type="text/javascript"  >
	require("/scripts/react/bundle.js");
</script>
 ```

The browser showed: 

```
SyntaxError: expected expression, got '&'
	require(&quot;/scripts/react/bundle.js&quot;);
```
With the following code in my App.jsx file :

```
  <form action="#" method="POST" >
          Email : <input type="text" value="hhhh"  /><br/>
   </form>
```

I got the following warning in windows console :

**Warning: You provided a `value` prop to a form field without an `onChange` handl
er. This will render a read-only field. If the field should be mutable use    `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `App`.**


So using 'defaultValue' instead of value is the solution,However when I used 'placeholder' instead of  'value', it also worked.

Actually in my App.jsx file I used , ```react-router-component``` from https://github.com/STRML/react-router-component. The routing was in the following way :
```

PostList = require('./components/PostList.jsx');
    <Locations path={this.props.path}>
             <Location path="/" handler={PostList} />
             <Location path="/admin" handler={Admin} />
             <Location path="/post/:id" handler={PostView} />
      </Locations>
                        
                        <form action="javascript:void(0)" method="POST" >
                        Email : <input type="text" value="hhhh"  /><br/>

                        </form>
```

In the command prompt I got the warning message from the Email input element above. However if I use any ```input text``` with the ```value``` attribute inside PostList.jsx, I do not get any such warning message but those ```input``` fields become readonly.

**Comment by QingYun** [comment]
@ghuser123 maybe you want to try `require("app.js")` directly in the `<script>` tag. The files loaded by `<script>` tag and by `require` are running in different contexts and I guess the problem is caused by this difference of context. And using `require` to load all js files works for me.

**Comment by ghuser123** [comment]
@QingYun , Below goes what you said :
"
So what I need to do is just replace <script src="js/app.js"></script> with

```<script type="text/javascript">
    require("./js/app.js")
</script>```

"  
So what is  wrong with I did and got an error?

**Comment by QingYun** [comment]
@ghuser123 In a plain html file? The error message shows `"` is replaced by a `&quot;`, did you put it in a jsx file?

**Comment by ghuser123** [comment]
@QingYun , yes in a ```jsx``` file. I used ```react-async``` from https://github.com/andreypopp/react-async and all the ```jsx``` files have been browserified into ```bundle.js```.

**Comment by QingYun** [comment]
@ghuser123 So why not just use `require` directly as js code. It seems the jsx compiler will escape js code in the `<script>` tag, just as what it will do to the text inside a `<p>`. What I mean about using `require` in `<script>` is to use it to load the root js file which will load other js files use `require` as well, by doing so, all js files are loaded by `require` and so they are all running in the same context (node, instead webkit)

**Comment by ghuser123** [comment]
@QingYun , my React files are ```.jsx``` ones. They have been browserified into ```bundles.js```. And client side code is in ```custom.js```. So how should I use the ```require``` here ? Do you ask to write all the ```.jsx``` files as ```.js``` files and avoid browserifying ?

**Comment by QingYun** [comment]
@ghuser123 This problem is caused by using `require` in different contexts and it should work fine if you don't use `require` at all. Could you show me the original error message? I guess maybe it's a different problem from mine.

**Comment by ghuser123** [comment]
@QingYun , I have already shown. ```don't use require at all``` - which require - the one inside ```<script/>``` tag ? I just wish to use your solution.

**Comment by QingYun** [comment]
@ghuser123 I think we are talking about two different problems. If all your jsx files are packed into one single file then you don't need to use `require` at all and of course you don't need to face my problem which is caused by using `require` in two different contexts. 

As for your problem, I don't know why you don't load your `bundle.js` directly in the main html file (like `index.html`), but if you really want to write js code into a `<script>` tag which will be rendered by React, I think [`dangerouslySetInnerHTML`](http://facebook.github.io/react/docs/special-non-dom-attributes.html) is what you want

**Comment by zpao** [comment]
Ok, I see now - it sounds like there were some more uses of `window.document` instead of just `document` so it wasn't failing hard before. However I think it's pretty reasonable for us to make that assumption (all uses of `document` should be protect by our `canUseDOM` check). If you're mimicking a browser environment with something like node-webkit and using a library that is made to run in the browser, then having to add globals that I would expect you to have to do. I'm actually a little bit surprised node-webkit doesn't do that for you.

You can see our check here: https://github.com/facebook/react/blob/master/src/vendor/core/ExecutionEnvironment.js

We could perhaps be a bit more restrictive (maybe add a `window.document === document` check), but I don't think it's really worth protecting against every potentially different environment.
