### ISSUE TITLE
Bug: Ternary operator shows unusual behavior 

### ISSUE THREAD

**Issue by tajpuriya27** [facebook/react#27326]
Although both code logically seems the same, React Application behaves differently while using the `ternary` and `&&` operators. 

React version: 18.2.0

## Steps To Reproduce

Try to render the same component on different conditions using `ternary` operator. The rendered component must have a Boolean useState in it.

`Hint`: Rendering the same component with the same condition using `&&` operator in two different lines will give an expected behavior.

Link to code example:
- [visit](https://codesandbox.io/p/github/tajpuriya27/react-bug/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clm0udgt3000j3568kdzbdv5r%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clm0udgt3000e3568ktzhxi3c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clm0udgt3000i3568f1ylvssm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clm0udgt3000g35687kihl2ag%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clm0udgt3000e3568ktzhxi3c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clm0udgt3000d3568kq1q2jcx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clm0udgt3000e3568ktzhxi3c%2522%252C%2522activeTabId%2522%253A%2522clm0udgt3000d3568kq1q2jcx%2522%257D%252C%2522clm0udgt3000g35687kihl2ag%2522%253A%257B%2522id%2522%253A%2522clm0udgt3000g35687kihl2ag%2522%252C%2522activeTabId%2522%253A%2522clm0ue1qp00wh35683gum3rwl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clm0ue1qp00wh35683gum3rwl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clm0udgt3000i3568f1ylvssm%2522%253A%257B%2522id%2522%253A%2522clm0udgt3000i3568f1ylvssm%2522%252C%2522activeTabId%2522%253A%2522clm0udyr300lk3568yybcdw7u%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clm0udgt3000h3568iv4dmyp7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clm0udgzb000je7ic3kwv9eux%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clm0udyr300lk3568yybcdw7u%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) - Online version in CodeSandbox  

OR
- [GitHub](https://github.com/tajpuriya27/react-bug) repository link.

## The current behavior
After the user log-in to the application- `user` useState is updated. The application renders the second `div` from `togglable` component and shows `<h2>create....</h2>` from `NoteForm` component.
![image](https://github.com/facebook/react/assets/86508931/5e95bebe-b40d-45c2-b522-29851f9bfbd2)

## The expected behavior
After the user log-in to the application- `user` useState is updated. The application must render the first `div` from the `togglable` component and show `<button>Show Note Form</button>` from `NoteForm` component.
![image](https://github.com/facebook/react/assets/86508931/1ccf07d3-612c-422a-b5c8-49a5e2ae497a)

## Additional Findings:
If we use the `&&` operator with the same condition to render the components, it works as expected.

**Comment by VladyslavKochetkov** [comment]
# Why it works how it does

This isn't actually a bug with the ternary operator, but rather how invoking functions works in React. When you create function such as "loginForm()" and "noteForm()" they are evaluated outside of Reacts context and whatever was returned is inserted into the JSX, without Reacts knowledge. Your functions in this case both return a `Togglable` component, which is stateful. Since the decision making of which component to render happened outside of React - it's almost as if you did the following

```jsx
<div>
      <h1>Notes</h1>

      {user === null ? loginForm() : noteForm()}

    <Togglable buttonLabel={user === null ? "Show Login Form" : "Show Note Form"}>
        {user === null ? <LoginForm {/* Whatever Props */} /> : <NoteForm {/* Whatever Props */} />}
    </Togglable>
    </div>
```

# Solution 1

Don't use functions to return JSX elements inside of a Render - create a component. 

```jsx
// imports

const App = () => {
  // Other Stuff

  const TLoginForm = () => {
    return (
      <Togglable buttonLabel="Show Login Form">
        <LoginForm
          username={username}
          handleUsernameChange={({ target }) => setUsername(target.value)}
          handleSubmit={(event) => {
            event.preventDefault();
            setUser(username);
          }}
        />
      </Togglable>
    );
  };

  const TNoteForm = () => {
    return (
      <Togglable buttonLabel="Show Note Form">
        <NoteForm />
      </Togglable>
    );
  };

  return (
    <div>
      <h1>Notes</h1>

      {user === null ? <TLoginForm /> : <TNoteForm/>}
    </div>
  );
};

export default App;
```

You can see this solution here https://codesandbox.io/p/github/tajpuriya27/react-bug/csb-fhvdw8/draft/wizardly-breeze

# Solution 2 (Easier)

An easier solution is to simply add the `key` prop to each of your functions - React will read this and know that these are different instances of the component - and the state will no longer be shared. You can see this below

```jsx
const loginForm = () => {
    return (
      <Togglable buttonLabel="Show Login Form" key="login">
        <LoginForm
          username={username}
          handleUsernameChange={({ target }) => setUsername(target.value)}
          handleSubmit={(event) => {
            event.preventDefault();
            setUser(username);
          }}
        />
      </Togglable>
    );
  };

  const noteForm = () => {
    return (
      <Togglable buttonLabel="Show Note Form" key="note">
        <NoteForm />
      </Togglable>
    );
  };
```

link here https://codesandbox.io/p/github/tajpuriya27/react-bug/csb-j6nkk2/draft/brave-feather

# Why does && work?

To understand why && works you have to understand how React handles &&. If the && condition isn't met it doesn't just "not do anything". The value is evaluated to `false` - and false doesn't get mounted in React. So by having two && statements you code switches between

```jsx
[
  // other components
  <Toggleable label="Show Login Form">...</Toggleable>,
  false,
    // other components
]
```

and

```jsx
[
  // other components
  false,
  <Toggleable label="Show Note Form">...</Toggleable>,
   // other components
]
```

Notice how the order in the array changes - which is enough for React to internally pick up it is a different instance of Toggleable.

**Comment by sophiebits** [comment]
Note that nesting component definitions inside each other as in @VladyslavKochetkov's Solution 1 is not supported and not recommended, it can lead to performance and correctness issues because React will see it as a new type of component on every rerender of the outer component.

But otherwise the advice to split into components is correct. Please see the docs website at react.dev for more about how to structure your code.
