### ISSUE TITLE
Bug: react-dom/server.bun in `@canary` hangs without flushing or terminating the connection on long class names(?)

### ISSUE THREAD

**Issue by Jarred-Sumner** [facebook/react#27389]
React version: canary

## Steps To Reproduce

See https://github.com/oven-sh/bun/issues/5664

1.  Run `bun ./server.tsx`:
```tsx
import { type Server as BunServer } from "bun";
import { renderToReadableStream } from "react-dom/server";

Bun.serve({
  hostname: "0.0.0.0",
  port: 3000,
  fetch: async (request: Request, server: BunServer) => {
    return new Response(
      await renderToReadableStream(
<div className="w-[40rem] a b c d e f g h i j k l m n o pc d e f g h i j k l m n o pc d e f g h i j k l m n o p a b  c d e f g h i j k l m n o pc d e f g h i j k l m n o pc d e f g h i j k l m n o p a b  c d e f g h i j k l m n o pc d e f g h i j k l m n o pc d e f g h i j k l m n o p a b  c d e f g h i j k l m n o pc d e f g h i j k l m n o pc d e f g h i j k l m n o p a b  c d e f g h i j k l m n o pc d e f g h i j k l m n o pc d e f g h i j k l m n o p"></div>
      ),
      {
        headers: {
          "Content-Type": "text/html",
        },
      }
    );
  },
});
```
2. In another terminal, run `oha http://localhost:3000` (`oha` can be installed with `cargo install oha`, or you can use bombardier, wrk, or most other HTTP benchmarking tools)

This started sometime in the last few days on a recent `@canary` build of react-dom/server.

## The current behavior

The connections never close until timeout, which eventually leads to resource exhaustion

```
[2596] Can't assign requested address (os error 49)
```

This does not happen when the request is suffiiciently small. It doesn't reproduce, for example, on Bun's homepage benchmark. It happens in a larger request/response. My current guess is there is some chunking/batching logic in react-dom/server that needs to flush and it is not flushing in the bun version.

## The expected behavior

It should work. I tried going back quite far in Bun versions and the behavior is the same. I suspect this is caused by a recent change in react-dom. But I'm not sure. It's also entirely possible that this is a bug in Bun. But I wanted to make sure to file an issue so your team knows before 18.3 is released non-canary.

**Comment by sophiebits** [comment]
Hmm. Our Node logic for long strings is a bit involved for performance

https://github.com/facebook/react/blob/9617d39eca1fbac58afe73a23580d781ea20211d/packages/react-server/src/ReactServerStreamConfigNode.js#L50

but in the Bun version it's very simple so that's probably not it.

https://github.com/facebook/react/blob/9617d39eca1fbac58afe73a23580d781ea20211d/packages/react-server/src/ReactServerStreamConfigBun.js#L34

And we call .end() in the close method. So at a first glance this seems right. I don't have Bun installed at the moment so can't investigate more. 

This is the version mentioned in your issue – https://github.com/facebook/react/commits/d6dcad6a8beaeec0513a9851d1e0fe1181932360 – but would be helpful to know the last working version. 18.2.0 stable unfortunately was quite a while ago.
