### ISSUE TITLE
Is react abandoned?

### ISSUE THREAD

**Issue by sebolio** [facebook/react#27392]
It's been over a year without a single release, not even minor or patch, over 1,000 unresolved issues... I'm starting a new project soon and would like to know if it's a good idea to use this, since other frameworks are updating very frequently (like Vue and Svelte)

React Native seems abandoned as well, since most devs have switched to Flutter (157k over RN's 112k in very little time)

**Comment by alii** [comment]
React is in a very stable state. There's no need to release new minors/patches.

I would assume that the features that have been worked on since the 18.2.0 release will come out in version 19, whenever that will be. You can see what has changed by clicking this: https://github.com/facebook/react/compare/v18.2.0...main

You can see that the last commit was today, indicating that React is absolutely not abandoned - https://github.com/facebook/react/commit/2807d781a08db8e9873687fccc25c0f12b4fb3d4

**Comment by zhangenming** [comment]
> since other frameworks are updating very frequently (like Vue and Svelte)
https://github.com/vuejs/core/discussions/9138

**Comment by Xachiey** [comment]
Just saying it casually, but this topic isn't related to an issue, and it should be in the discussion area. wait..., there been no DISCUSSIONS zone?

**Comment by boiboif** [comment]
Not just react, front-end is dying. lol

**Comment by sidharth8338** [comment]
**`React was far from abandoned`**; instead, it continued to thrive as a widely adopted and actively maintained JavaScript library for developing user interfaces.

**Comment by sebolio** [comment]
> Not just react, front-end is dying. lol

how so? i only see frontend-oriented startups

**Comment by TheSavior** [comment]
React and React Native have more people working on them than at any time in the past, there is lots in flight. 

Re: releases, there are lots of features that are intertwined that we hope to get out in the next release, which takes a while for all of them to be stabilized together. Many of these features you can see in frameworks that are shipping against the canary channel, like Next.JS.
