### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by iradukundairenee** [facebook/react#27469]
Title: Too many re-renders

Description:

I am using React version 18.2.0, and I am getting the following error message:

Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.

To create an issue on GitHub for the "Too many re-renders" issue in React, follow these steps:

Go to the React repository: https://create-react-app.dev/.
Click on the Issues tab.
Click on the New issue button.
Select the Bug report template.
Fill in the title and description of the issue.
Optionally, you can also add labels and assign the issue to a specific person or team.
Click on the Create new issue button.
Here is an example of a bug report issue:

Title: Too many re-renders

Description:

I am using React version 18.2.0, and I am getting the following error message:

Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.
This error is happening in my MyComponent component. The component is rendering a list of items, and I am using the useState hook to manage the state of the list.

I have attached a minimal example of my code to this issue.

Steps to reproduce:

Open the attached code in a web browser.
View the page in the console.
Expected behavior:

The list of items should render correctly.

Actual behavior:

The list of items renders correctly, but I get the "Too many re-renders" error message in the console.

Environment:

React version: 18.2.0
Browser: Chrome
Operating system: macOS
Additional information:

I have tried to debug the issue, but I have not been able to identify the cause.

Thank you for your time and assistance.

**Comment by pwbriggs** [comment]
Hi @iradukundairenee!

In my experience, this error occurs when you unconditionally change the state inside a component, like this:

```jsx
export function MyComponent() {
  let [myState, setMyState] = useState(1);
  setMyState(2);    // 🔴 Setting the state unconditionally
  return (
    <span>MyComponent is at state {myState}</span>
  );
}
```

Of course, it could be more subtle, for example inside an element attribute:

```jsx
export function MyComponent() {
  let [myState, setMyState] = useState(1);
  return (
    <div>
      <span>MyComponent is at state {myState}</span>
      <button onClick={setMyState(myState + 1)}>Increment state</button>
    </div>
  );
}
```

In this example, the code sets the state unconditionally in `onClick={setMyState(myState + 1)}` because that code is evaluated immediately. To fix this particular case, you would need to wrap it in a function like `onClick={() => {setMyState(myState + 1)}}`.

Hope this helps!

By the way, it looks like you forgot to attach the code that's causing your issue, can you please do that? (That's fine, I forget to attach things all the time too.)
