### ISSUE TITLE
Bug: Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#:r1a:' is not a valid selector.

### ISSUE THREAD

**Issue by vaynevayne** [facebook/react#27553]
```jsx
import {
  useId,
} from "react"
  const tableId = useId()

return <table id={tableId}></table>
```

<img width="824" alt="image" src="https://github.com/facebook/react/assets/124666577/6c0f95eb-410c-47f6-868f-ed934d3ca4a4">

**Comment by MarceloSpessoto** [comment]
Hello @vaynevayne , the problem is in the use of querySelector receiving an id with a reserved character ( : ).
I don't have context in how you are using the querySelector method, but I think these links may be useful:
[Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document'](https://stackoverflow.com/questions/37270787/uncaught-syntaxerror-failed-to-execute-queryselector-on-document)
[querySelector doesn't work if the ID contains a colon (:)](https://bugzilla.mozilla.org/show_bug.cgi?id=883044)

**Comment by sophiebits** [comment]
This might be an issue with clipboard.js. It's perfectly valid to use a colon in an HTML ID but when used in a CSS selector it must be escaped, such as with a backslash:

```
'#' + CSS.escape(':r1a:')
// '#\\:r1a\\:'
```
