### ISSUE TITLE
Ability to turn off ‘Download DevTools’ console message

### ISSUE THREAD

**Issue by rmschindler** [facebook/react#27602]
## The current behavior

The “Download the React DevTools for a better development experience” message appears in the console for development builds. There is no apparent way to stop this message from appearing.

## The expected behavior

The option to keep this message from printing in the console.

**Comment by pwbriggs** [comment]
@rmschindler how would this be configured? As far as I know, React doesn't have a config file, so you would have to add an extra call in the code. In my opinion, adding a line of code to stop a console message is worse than just ignoring the message.

**Comment by rmschindler** [comment]
I agree that adding a line of code to prevent the console message feels superfluous. How about removing the printing of the message in the first place? —Perhaps this is too much to ask for; perhaps my view that this message is a ‘faux pas’ is only my own view.

**Comment by pwbriggs** [comment]
@rmschindler No, I completely agree with you. I'm not sure printing a message to the console is helpful to many, because I imagine almost all new users will be reading React's documentation. Because of that, most users are probably already aware that React DevTools exist, and if they aren't using it, they probably have a reason.

Of course, I've made assumptions here. Maybe someone on the React Core team could provide us with some data on how many times `https://reactjs.org/link/react-devtools` is requested (the URL the console message links to). That would give us a rough idea of how effective the message actually is.
