### ISSUE TITLE
"componentDidMount" executes in wrong order

### ISSUE THREAD

**Issue by thheller** [facebook/react#2763]
http://jsfiddle.net/h2pc9103/

The order is: child 1, child 2, child 3, parent

Technically though a child cannot be mounted in the DOM if the parent is not yet mounted.

I'd expect to see: parent, child 1, child 2, child 3

If I understand the docs correctly "componentDidMount" is meant for client-side only "state". I therefore use this to setup some "state", I have some child components which would need access to this "state" but can't cause it isn't initialized yet. I'm using "state" in quotes since it is not the React component state rather something external (websocket connection).

I could of course use other lifecycle callbacks to trigger the init but that would then execute on the server if I ever choose to use this feature.

**Comment by prasannavl** [comment]
@thheller +1, 

I agree that the order of execution has to be parent first. This is old, but I do think its quite relevant. 

@sebmarkbage, A very common and very acceptable use case, is animations. (Note, I absolutely do not want to use the react-style libraries for that since it gets inefficient for complex animations - and you do want to squeeze the maximum performance out of the devices when it comes to mobile devices.)

So, consider the case below:

`<Parent><Child/></Parent>`

And parent's has `componenDidMount` which, say strips the DOM elements, to place an artifical scroll bar. Now, I expect all my DOM elements to be rendered at this point, so I'm free to mutate my children as long as it doesn't affect my next render. And now, waking down the chain, I would expect the same thing in my children. But alas, the child will not see the changes in its `componentDidMount` because it gets executed the other way. 

I have to jump through hoops and set up events to make this sane. This is highly intuitive. One would assume that the lifecycle hook `ComponentDidMount` exists to interoperate with the DOM. (Since, speaking purely in an academic manner you wouldn't actually need it in a hypothetically world where everything is done the react way). And this order makes it unintuitive to do just that, so I'd highly recommend that this be considered as a bug, and the design choices re-evaluated. 

PS: I'm only talking about the order of execution of the event, like @thheller mentioned before, not how the render happens, since the only logical way is to go from child to parent anyway there.

**Comment by cScarlson** [comment]
Similar issue:

// Items.jsx
...
componentDidMount () { eventHub.fire('trigger'); }
...

// Patent.jsx
...
componentDidMount () { eventHub.on('trigger'); }
...

I know some will tell me I've completely the wrong idea & I need 'to think in React', but the above is a very cropped example -- I shouldn't give up my soul just to have my Patent component mount before my Items component does.

This is surely a bug.

**Comment by notahat** [comment]
I think `componentDidMount` runs bottom-up, but `componentWillMount` runs top-down.

So execution order goes:

1. `parent.componentWillMount`
2. `child.componentWillMount`
3. `child.componentDidMount`
4. `parent.componentDidMount`

I'm not sure if that helps.

**Comment by lubelski** [comment]
I just wandered into this thread looking for info about lifecycle fire order in order to manage some obnoxious focus stuff.  

// Items.jsx
...
componentDidMount () { this.refs.input_1.focus() }
...

// Patent.jsx
...
componentDidMount () { this.refs.input_2.focus() }
...

what's focused right now?  ¯\_(ツ)_/¯

In my case I am including a 3rd party child component that does its own focus chicanery on didMount.  My solution will probably involve an _.defer in the parent and work just fine, but it does illustrate a fun times fuzzy edge between react and the browser.  First guess had been that mount order would be somehow deterministic.

**Comment by joshjung** [comment]
Need to add to this here. We are using a framework that relies on bubbling events to communicate from children to parents.

Unfortunately, since a child's `componentDidMount` gets called before a parent's, you cannot dispatch a bubbling event at that point and expect a parent to catch it.

So even if we cannot change `componentDidMount` in the lifecycle, it would be nice to have a lifecycle method like "componentAttachedtoDOM` or something similar to indicate that the dom node has been fully attached to the DOM tree.

**Comment by matijaSos** [comment]
Hi, I am using Navigator and having the problem that `componentDidMount`() is executed before ref on Navigator is executed, thus I can't access `this._navigator` in `componentDidMount()`.

I found the same [issue](https://stackoverflow.com/questions/44074747/componentdidmount-called-before-ref-callback) on SO, but no answers so far. If you have an idea how to address this, it would be highly appreciated. Thank you!
