### ISSUE TITLE
React developer tools messes with Smartermail

### ISSUE THREAD

**Issue by richardoptibrium** [facebook/react#27638]
When I try to login to smartermail, whatever I type gets deleted (as if backspaced over). I tried it in incognito and it was fine, so finally I narrowed it down to React Developer Tools extension version 4.28.5 (10/25/2023) . When I switched it off, all was well. I can supply a video of this happening if it helps?

**Comment by hoxyq** [comment]
I don't know how SmarterMail is implemented, but I think that the root cause here is `window.postMessage` calls. The  extension use it to exchange messages between different entities, primarily to identify when React is loaded on the page. I am assuming that SmarterMail listens to `message` events and doesn't filter them based on `data` and `source`.

We don't have any plans to change this behaviour, I would suggest updating it on SmarterMail's side, because any extension could possibly inject a script, which uses `window.postMessage` API.
