### ISSUE TITLE
DefaultValue is empty :( 

### ISSUE THREAD

**Issue by kevenjesus** [facebook/react#2764]
Hello everybody okay?

I have quite a strange problem, when seto a value in the "defaultValue" nothing appears, however if I set a value using "value" appears, the props is coming with the data correctly, I have no idea what it is

my react conde http://jsbin.com/losugiqoje/2/edit?html,js,output

**Comment by HarishBalagoni** [comment]
use componentWillMount(){ this.setState({key:this.props.defaultvalue});}
then render with <
defaultValue={this.key}>

**Comment by dpz3579** [comment]
@kevenjesus..
Hi it will be very helpful if you can provide a code snippet for the same, as how you achieved it.

Since we are also using the _modal_,
it loads **defaultValue** in _First run_, and in _Second time_ opening modal it does not set the value.
As the **defaultValue** binding works default.

I did understand that we have to use _ref_ for my input type to bind values.

but how will **_componentDidUpdate_** work.
what handling you did in that function.

Appreciate your help.
