### ISSUE TITLE
Bug: react-hooks/exhaustive-deps doesn't detect unnecessary dependencies

### ISSUE THREAD

**Issue by mramirarab** [facebook/react#27660]
I have [created a sandbox](https://codesandbox.io/s/react-typescript-playground-forked-l2wf4z) that demonstrates that having an unnecessary dependency is not detected by the eslint rule exhaustive-deps. This can cause very serious problems in large applications.

**Comment by taoliujun** [comment]
Same issue, when removed codes in the useEffect body, can it detect the unnecessary dependency that should be removed?

**Comment by tagnm** [comment]
Same issue. Started to notice it fairly often now.

Here is an example of the linting rule showing the message, as it detected `banana` is not used by the `useEffect`:

![image](https://github.com/facebook/react/assets/141848572/ed1a2944-068b-4bbc-a3f0-0e7df3f92c41)

And if I remove `banana`, the message goes away...but it should not :) because `timelineDateRange` is also not used in the `useEffect`. For exposition, `timelineDateRange` comes from a Zustand store and is imported in the same scope as the example `useEffect`.

![image](https://github.com/facebook/react/assets/141848572/26c205a6-9720-4c32-87a1-b3e912251202)

**Comment by rickhanlonii** [comment]
It is valid for effects to over-specify their deps. Follow https://github.com/facebook/react/issues/26981 for requests to add a feature to disallow over-specifying.
