### ISSUE TITLE
Bug: One unnecessary re-rendering occurs when entering the same value in useState.

### ISSUE THREAD

**Issue by yoonminsang** [facebook/react#27690]
React version: 18.2.0

## Steps To Reproduce

1. Define count 0 in useState. 
2. Create a useInterval hook.
3. Link useInterval with a callback function that changes the count to 1 in the component.
4. Take console.log
5. The log should be 0, 1, but the log is 0, 1, 1. In other words, when the same value is entered into setState, rerendering occurs once. (state is a raw value)

Link to code example: https://codesandbox.io/p/sandbox/vigorous-raman-zd4cp2?file=%2Fsrc%2FApp.tsx%3A14%2C1

## The current behavior

Re-rendering should not occur when updating to the same state. However, re-rendering occurs the first time. Occurs in both event handlers and useEffect. However, if it is changed to the same value as initialState, re-rendering does not occur.

## The expected behavior

Re-rendering should not occur when you enter the same value as before in setState.

**Comment by zoran995** [comment]
Hi @yoonminsang,
that is expected behaviour and is described in the caveats section of docs https://react.dev/reference/react/useState#setstate-returns

> If the new value you provide is identical to the current state, as determined by an [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) comparison, React will skip re-rendering the component and its children. This is an optimization. Although in some cases React may still need to call your component before skipping the children, it shouldn’t affect your code.


You can check an example [here](https://stackblitz.com/edit/stackblitz-starters-2fsovi?file=src%2FApp.tsx), react won't run effects and won't rerender children but will run other parts of code in the component (I believe this is to verify there is no additional side effects in component)

**Comment by yoonminsang** [comment]
@zoran995 Thank you~
