### ISSUE TITLE
Bug: States not mainted in the page

### ISSUE THREAD

**Issue by SamarthKadam** [facebook/react#27723]
When I use react router and Im in one page and I made some changes in the state. in the current page Then I navigate to different page. The state of the previous state is not mainted? is this the workflow of react?

**Comment by ayushkumarbhadani** [comment]
@SamarthKadam, This must be because of the working of the React router. When you navigate to a different page in react-router, it just removes the current page (say page 1) and renders a new one (say page 2). When a component is removed then its child states are also destroyed. 

If you want to maintain the state of that page then you can either move the state to its parent or use a global state store like redux or context API.
