### ISSUE TITLE
Bug: `use()` yields incorrect value during first SSR

### ISSUE THREAD

**Issue by ziir** [facebook/react#27731]
During the first server-side streamed rendering attempt of a RSC tree including a component that is wrapped in `<Suspense>` & leverages `use()`, the owner component does not suspend, and its `use()` yields an unexpected value.

Subsequent requests / SSR attempts result in the wrapped component suspending as expected, and `use()` yielding the expected value.

```jsx
// server-root.jsx
function ServerRoot({ flightResponse }) {
  return (
    <html>
      <body>
        {/* use(flightResponse) exhibits same issue */}
        {flightResponse}
      </body>
    </html>
  );
}
```
```jsx
// react-html.js
const flightResponse = createFromNodeStream(...);

const renderStream = renderToPipeableStream(
  <ServerRoot flightResponse={flightResponse} />,
  options
  }
);
```

```jsx
// app.js server component
import { Suspense } from "react";

import { ClientConsumer } from "./client-consumer";

export function App() {
  const promise = new Promise((resolve) =>
    setTimeout(() => resolve(["foo", "bar"]), 1_000)
  );

  return (
    <Suspense fallback="loading ...">
      <ClientConsumer promise={promise}>hello world</ClientConsumer>
    </Suspense>
  );
}
```

```jsx
// client-consumer.js client component
"use client";
import { use } from "react";

export function ClientConsumer({ promise, children }) {
  console.log("ClientConsumer before the use()");
  const value = use(promise);
  console.log("ClientConsumer after the use()", value);

  return children;
}
```

React version:
- react: "18.3.0-canary-bbb9cb116-20231117",
- react-dom: "18.3.0-canary-bbb9cb116-20231117",
- react-server-dom-webpack: "18.3.0-canary-bbb9cb116-20231117",

## Steps To Reproduce

Link to code example: https://github.com/ziir/rsc-bug-repro

1. Clone, set-up & start minimal reproduction
2. Navigate to http://localhost:3000

## The current behavior

On the **first SSR attempt only**:
- The `ClientConsumer` component owning the `use(promise)` hook **does not suspend** while the `promise` is pending.
- `use(promise)` yields an unexpected value: a JSX element matching the `App` parent server component.

![Screenshot from 2023-11-21 00-24-26](https://github.com/facebook/react/assets/2394128/4041a766-2c04-4413-923a-fcd6dccbc307)

## The expected behavior

As in the subsequent SSR requests:
- The `ClientConsumer` component owning the `use(promise)` hook suspends while the `promise` is pending.
- `use(promise)` yields the expected fulfilled promise value: `['foo', 'bar']`

![Screenshot from 2023-11-21 00-25-42](https://github.com/facebook/react/assets/2394128/cae9b13f-06d4-4dd2-b4b0-b270d8e1e056)

**Comment by lubieowoce** [comment]
I've managed to whittle this down to a much smaller repro that doesn't involve RSC at all, just a `Thenable<ReactNode>` that contains a lazy component with a use() call inside.

https://codesandbox.io/p/sandbox/fizz-promise-leak-between-components-in-use-in-a-lazy-component-ppy4v8?file=%2Fsrc%2Findex.tsx%3A16%2C1-17%2C1

Expected output:
<img width="499" alt="Screenshot 2023-11-21 at 03 12 47" src="https://github.com/facebook/react/assets/13698226/b6f31e1f-22a7-4419-842e-d0b17fa16c37">

Actual output:
<img width="501" alt="Screenshot 2023-11-21 at 03 13 12" src="https://github.com/facebook/react/assets/13698226/86cc3558-0c2c-4159-a1b0-b586c35b923c">

"A nested promise for Use" is what's in the promise being `use()`-ed. But it receives a whole chunk of other stuff instead.

I believe this is related to `lazy()` components, because uncommenting this bit here actually stops the issue from appearing:
```js
const LazyUse = lazy(() => sleep(20).then(() => ({ default: Use })));
// const LazyUse = Use; // fixes the issue!
```

In short, the issue seems to go like this:
1. Render a promise (`promise1`) of JSX as a child of the shell
2. Have a lazy component in that JSX
3. call `use(promise2)` within that lazy component. use will act as if `use(promise1)` was called instead, so it returns the wrong thing.

Notably, this only seems to happen on the first request. The codesandbox caches the response so that it's easily viewable (also their preview does two requests, so it's not visible.)

---

Based on some poking around in the react internals, the issue seems to come from an incorrectly restored `thenableState`. when the `Use` component runs, `thenableState` is set to an array containing the promise returned from `getAsyncContent` instead of null, so `use` just returns that (via [this line in `trackUsedThenable`](https://github.com/facebook/react/blob/bbb9cb116dbf7b6247721aa0c4bcb6ec249aa8af/packages/react-server/src/ReactFizzThenable.js/#L61)). My guess is that this is somehow related to `lazy()` using the legacy suspense implementation, but that's as far as i've gotten.

**Comment by marcusdarmstrong** [comment]
Bump
