### ISSUE TITLE
Security issue: React is vulnerable to supply chain attacks

### ISSUE THREAD

**Issue by paulmillr** [facebook/react#27748]
`react` depends on `"loose-envify": "^1.1.0"`, a package which owned by one person. Last update of it was 5 years ago.

If the persons NPM credentials or token are leaked, and a new *malwared* version of loose-envify is published, **all** react users will instantly receive malware.

Moreover, same can happen to envify's dependency: `js-tokens`.

Ways to mitigate:

- Lock version to `1.1.0`
- Better: ask person (fb employee) to release new loose-envify with **locked-down** version of js-tokens, then lock envify version in react
- Is it even needed in dependencies (not devDeps)? Maybe remove altogether

**Comment by markerikson** [comment]
I have mixed feelings about this:

- It seems like a pretty big stretch to claim that React is "vulnerable to supply chain attacks" because of the existence of one particular dependency. Why wouldn't that be the case for _every_ dependency on NPM ever?  That's an awfully hypothetical situation.
- Agreed that the fact that the package hasn't been updated for a number of years is in one sense something to think about, but it's also a tooling-related package that has no reason to change at all anyway
- That said, we dropped `loose-envify` from Redux a while back, per https://github.com/reduxjs/redux/issues/3567 (although we are just _now_ getting ready to release that in a new major version). It was designed for Browserify users to help that tool do search-and-replace on `process.env.NODE_ENV` when used to build an app that used a given library like React.  Browserify is rarely used today, and that should really be an app-level configuration concern.

So, I disagree with the security reasoning, but I agree that React shouldn't list `loose-envify` as a dependency because it's not useful any more.

**Comment by paulmillr** [comment]
>Why wouldn't that be the case for every dependency on NPM ever

it is the case. That’s why there are lockfiles and other solutions. Unfortunately supply chain attacks are so effective in js because of popularity of version ranges and the fact ppl blindly update their dependencies to every new version.

**Comment by markerikson** [comment]
@paulmillr : yeah, I follow that. My question is more about why it's worth singling out one dep here in this repo specifically.  What makes this situation special?

again, to be clear, I do support removing `loose-envify` as a dep entirely, but for non-security related reasons. I just don't understand the urgency for filing an issue about one random dep.

**Comment by phryneas** [comment]
Also, since [npm has started to require two-factor auth for publishing popular packages](https://github.blog/2022-02-01-top-100-npm-package-maintainers-require-2fa-additional-security/), a token stolen by a virus does not pose a significant threat of a supply-chain attack.

**Comment by paulmillr** [comment]
@markerikson a person in other repo randomly told me “even react does this”, then i’ve did the researched and while it seemed like the dep is not really up-to-date, or “not devdep”, i’ve opened the issue.

**Comment by paulmillr** [comment]
@phryneas 

>Also, since [npm has started to require two-factor auth for publishing popular packages](https://github.blog/2022-02-01-top-100-npm-package-maintainers-require-2fa-additional-security/), a token stolen by a virus does not pose a significant threat of a supply-chain attack.

I don’t believe this mitigates the risk. They just enforced 2fa for auth. Not for publish — otherwise CI publish tokens would have stopped working. Tokens can still be stolen.

**Comment by markerikson** [comment]
@oliviertassinari not sure what you mean with the "`react-is` would need this" comment. That's the exact same dev-vs-prod import idiom that `react` and `react-dom` already use:

- https://unpkg.com/browse/react@18.2.0/index.js

and bundlers already handle `NODE_ENV` as an idiom indicating dev vs prod.

**Comment by oliviertassinari** [comment]
@markerikson I would expect `react-is` to reproduce the loose-envify setup than react has:

```json
  "browserify": {
    "transform": [
      "loose-envify"
    ]
  }
```

Otherwise, the benefit is limited to have it in react in the first place.

**Comment by eps1lon** [comment]
Closed in https://github.com/facebook/react/pull/28480
