### ISSUE TITLE
No reason to prohibit use of JS keywords in JSX?

### ISSUE THREAD

**Issue by taoeffect** [facebook/react#2781]
So my understanding based on the docs is that `class` is prohibited as an HTML attribute in JSX, but I see no reason for this.

One example given in the guide of using `className` instead of `class` shows that the transformation results in this JS:

``` javascript
var root = React.createElement('ul', { className: 'my-list' }, child);
```

But this is easily fixed by quoting `className` as `'class'`:

``` javascript
var root = React.createElement('ul', { 'class': 'my-list' }, child);
```

So, unless I'm missing something obvious, can we please have our normal HTML back? ^_^

**Comment by TheSavior** [comment]
The online react compiler seems to use `class` instead of `className`

**Comment by rapilabs** [comment]
https://github.com/rapilabs/jsx-classnameify-loader

**Comment by AndreKR** [comment]
I got here wondering the same thing as @taoeffect, and from the conversation I think this is a documentation issue.

On http://facebook.github.io/react/docs/jsx-in-depth.html it says (emphasis mine):
> **Since JSX is JavaScript**, identifiers such as class and for are discouraged as XML attribute names.

In my opinion this suggests that valid JSX is valid JavaScript and therefore I cannot use "class".

It should be changed to something like "Since JSX expressions are evaluated into DOM nodes, their properties should follow the same naming conventions, i.e. `className` instead of `class`."

Because that's the point, isn't it?
