### ISSUE TITLE
Bug: Should have an queue. This is likely to bug in react. Please file an issue

### ISSUE THREAD

**Issue by mahabubsaki** [facebook/react#27845]
React version:

## Steps To Reproduce

Please I cannot identify where is the issue
![Screenshot 2023-12-10 112033](https://github.com/facebook/react/assets/96987600/ff324dc1-4d47-44cd-9747-814e04a72c45)

Link to code example:

**Comment by junqqqz** [comment]
Under what circumstances would this error occur?

**Comment by mahabubsaki** [comment]
> Under what circumstances would this error occur?

I have a state, by which I am mapping and rendering input field. There is a button, by clicking that I am adding an element to that array. Every input field has a onchange, which helps me to keep track of all of the input fields value.If I write something any of input or tries to add input by clicking the button.It throws me this error

**Comment by jhaase1** [comment]
I just encountered this issue also

**Comment by acidfernando** [comment]
I'm having the same issue. It happens when I update the state with the dispatcher of the useState hook.

I'm using NextJS, this only happens when compiling the app AND when the root of the component I'm using is within the RootLayout of the application. If I move the root to a page, it works fine.

It also works if my RootLayout is a client component.

I've tried creating a repro, but with no success.
