### ISSUE TITLE
Bug: React package does not support Role=”table”

### ISSUE THREAD

**Issue by msftedad** [facebook/react#27856]
React package does not support Role=”table”

React version: 0.73

## Steps To Reproduce

1. Open [Accessibility · React Native](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2freactnative.dev%2fdocs%2faccessibility%23role&data=05%7c02%7cv-prajadhav%40microsoft.com%7cc2d7484e89a742ec86c808dc0250e258%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638387793626236656%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=5ozNuibDMiYkczkkCc24tZfXjKRPRLXdKDDRgBCYH8o%3D&reserved=0)
2. Observe that Role="table" is not supported by React pakage.

## The current behavior
React package does not support Role=”table”

## The expected behavior
React package should support Role=”table”

**Comment by QuinVon** [comment]
Native here: https://github.com/facebook/react-native/issues

**Comment by rickhanlonii** [comment]
Looks like this is specific to React Native, because React supports this. Here's the [W3C table example](https://www.w3.org/WAI/ARIA/apg/patterns/table/examples/table/) working in React: https://codesandbox.io/p/sandbox/sharp-shamir-drn3t4?file=%2Fsrc%2FApp.js%3A47%2C11

<img width="847" alt="Screenshot 2024-01-06 at 3 49 07 PM" src="https://github.com/facebook/react/assets/2440089/bc371413-a0f3-4642-89f1-48a0f493b11f">


Here's the related RN issue: https://github.com/facebook/react-native/issues/40759
