### ISSUE TITLE
[DevTools Bug]: React instrumentation encountered an error: TypeError: e.hasOwnProperty is not a function.

### ISSUE THREAD

**Issue by molnard1** [facebook/react#27851]
### Website or app

https://github.com/molnard1/react-template/tree/devtools-bug

### Repro steps

1. Clone the above repo (the `devtools-bug` branch should be used), install dependencies (`npm i`)
2. Build/start it in **development** mode (`npm run watch`)
3. Observe the following error in console, along with devtools not working:
![image](https://github.com/facebook/react/assets/101341428/c90e9b13-9ff0-41d7-854c-9c7038c7c5e2)
![image](https://github.com/facebook/react/assets/101341428/96c2ca50-2929-4e4b-ae5b-d3fe5dc36b7e)

As far as I can tell, this appears to be caused by Axios, as this error does not happen before adding it to the project.

### How often does this bug happen?

Every time

**Comment by Kartikkittad** [comment]
Looks like e is not a object, it's a variable
Error is occured due to this:
`const e = "some string name";`
`const prop = e.hasOwnPropery();`
This is how your code should be:
`const e = { name: "xyz" };`
`const prop = e.hasOwnProperty("name");`
`console.log(prop); // output will be true because name is property of e`

**Comment by Kartikkittad** [comment]
e should be object not variable,
Error is due to the:
`const e = "some string"; // this is a variable not obejct`
`var hasProperty = e.hasOwnProperty("someProperty");`
This is how your code should look like:
`const e = { name: "xyz" };`
`const prop = e.hasOwnProperty("name");`
`console.log(prop); // output will be true because name is property of e`

**Comment by ananuness** [comment]
> e should be object not variable
There's no `e` in their code. At least not in the branch they provided.

**Comment by molnard1** [comment]
I've had a bit of time to look over this again, and it seems that the issue is actually caused by `esbuild`, specifically, the development build command:
`esbuild src/js/index.js --bundle --loader:.js=jsx --format=cjs --outfile=public/dist/bundle.js --watch`
changing `--format=cjs` (or `--format=esm`, which also triggers the same error) to `--format=iife` fixes the issue.
The reason this doesn't happen in the production build is because `--minify` seems to remove the code that's causing the DevTools error in `cjs`/`esm` mode.

**Comment by taronsarkisyan** [comment]
Thanks @molnard1 ,

This error occurs when using React + ESBuild.
This works for me:

Development mode: --format=iife and minify=false

Production: --format=cjs and minify=true
