### ISSUE TITLE
Bug:  React component rendered with createPortal with state controlled by parents will not rerender on state change

### ISSUE THREAD

**Issue by joaopedrocoelho** [facebook/react#27926]
React version: 18.2.0

## Steps To Reproduce

1.Download the project from https://stackblitz.com/edit/stackblitz-starters-qcvjsz
2. npm i && npm run dev

Link to code example: https://stackblitz.com/edit/stackblitz-starters-qcvjsz

## The current behavior

My issue is explained on this live example : https://stackblitz.com/edit/stackblitz-starters-qcvjsz?file=src%2FApp.tsx

Basically I'm passing a list of options to a radio button list, with the state and setter to a child component rendered with createPortal, however when the options are clicked in the child the parent component updates it's state, but not the child, so the radio never showthe checked status.

## The expected behavior

The radios in the dialog show the checked status and different radio lists don't get updated at the same time

**Comment by rickhanlonii** [comment]
The problem is unrelated to `createPortal`, if you replace `createPortal(modal, document.body)` with `{modal}` the issue is the same. The problem is `setContext(<Component />)`, like you have in this code:

```js
const { setModal } = useContext(ModalContext);
  const onClick = () => {
    setModal(
      <SelectYearModal
        years={years}
        selectedYearIdx={selectedYearIdx}
        setSelectedYearIdx={setSelectedYearIdx}
      />
    );
  };
```

This creates the component outside of render, so React doesn't know what component owns it, which is why this pattern isn't supported. To fix, you could do: `setModal(SelectYearModal)` (no brackets) then render it with brackets, but the better way IMO is to `setModal(type)` and then in the modal render do a switch for the right form based on the string type.

**Comment by joaopedrocoelho** [comment]
@rickhanlonii Thanks for the reply. Is there a way that would still allow me to pass props to the modal component?

**Comment by rickhanlonii** [comment]
Yeah, you can just pass props to the component rendered by `createPortal` as in

```js
createPortal(<Component onClose={handleClose} />, portalDiv);
```

You can even pass children, which is what I would probably do here:

```js
createPortal(
  <Modal onClose={handleClose}>
    <YearForm value={year} onChange={handleYearChange} />
  </Modal>
  );
```

See the example here: https://react.dev/reference/react-dom/createPortal#rendering-a-modal-dialog-with-a-portal
