### ISSUE TITLE
svg <animate> tag prevents transpilation of jsx to js

### ISSUE THREAD

**Issue by zeusdeux** [facebook/react#2798]
Steps to reproduce:

1. Create a React component that renders an svg which contains <animate>. For example, [puff.svg](https://raw.githubusercontent.com/SamHerbert/SVG-Loaders/master/svg-loaders/puff.svg).

2. Save component as a `.jsx` file
3. Try to compile the `.jsx` file to `.js`

I get the following error when I use the `reactify` transform with `browserify`: 

![jidivnu](https://cloud.githubusercontent.com/assets/635512/5594806/222452a2-9283-11e4-9ba4-914bc64a17fe.png)

I get an error when I use `jsx` from `react-tools` too, though I didn't take a screenshot of that.

For those who might have a similar issue with any tag, I worked around the error by building a custom component, building a `string` out of the svg code and setting it using `dangerousSetInnerHtml` in that component.

**Comment by jsfb** [comment]
Yeah, I think that error is too aggressive in catching things.  I loosened the restriction a bit in https://github.com/facebook/react/pull/2774 but it's probably still too tight, and that commit isn't going to be merged for a while anyway.  The workaround I've been using is to directly invoke React.createElement(), which bypasses the JSX transformations (since it's standard javascript, just put it between the squiggly brackets in jsx), but it's admittedly not ideal.  That error is going to be removed soon anyway, it was a temporary migration hack.

cc @sebmarkbage

**Comment by zeusdeux** [comment]
Using `React.createElement()` makes sense. I just took the quicker way out since in my case, it's just a static (in terms of code) svg.
Any idea when that error will be removed though? Also, any idea if we'll have a `React.SVG.*` like `React.DOM.*` namespace we have now?

**Comment by gaearon** [comment]
>Any idea when that error will be removed though?

I think in 0.13 (deprecations are usually kept for one version), and a birdie whispered in my ear 0.13 might come around early February but no guarantees :-)

**Comment by zeusdeux** [comment]
@gaearon That's cool. I can wait. Thanks :)

@jsfb Should I keep this issue open till the required code is merged and released?

**Comment by sebmarkbage** [comment]
This needed to be an error for one version, since it used to work but have a different semantic meaning. We don't want to silently swap semantics between versions. So we break it for one, and then reenable it with different semantics in 0.13.

**Comment by sebmarkbage** [comment]
Let's leave it open until @jsfb lands his PR in master to fix it.

**Comment by zeusdeux** [comment]
:+1:

**Comment by spicyj** [comment]
This happened.

**Comment by zeusdeux** [comment]
@spicyj ty :)
