### ISSUE TITLE
Bug: Infinite loop with useState and useEffect hooks

### ISSUE THREAD

**Issue by mkozachok** [facebook/react#28109]
I am using default pattern for updating state if props changes.

React version: 18.2.0

## Steps To Reproduce

1. Create component with useState and useEffect and some prop with array
2. Update state value on prop changes in useEffect
3. Add default value for prop as empty array
4. Do not pass value via prop in the component

Link to code example: [https://codesandbox.io/p/sandbox/beautiful-http-n4c3p5](https://codesandbox.io/p/sandbox/beautiful-http-n4c3p5)

```jsx
export default function App() {
  return (
    <div className="App">
       <List />
    </div>
  );
}
```

```jsx
export function List({ items = [] }) {
  const [itemsState, setItemState] = useState([]);

  useEffect(() => {
    setItemState(items); // this line starts infinite loop
  }, [items]);

  return <div>Length: {itemsState.length}</div>;
}
```

## The current behavior
infinite loop

## The expected behavior
set value to state if prop `items` changes

**Comment by mkozachok** [comment]
but this code works correct

```jsx
const defaultEmptyArray = []; 

export function List({ items = defaultEmptyArray }) {
  const [itemsState, setItemState] = useState([]);

  useEffect(() => {
    setItemState(items); // this line starts infinite loop
  }, [items]);

  return <div>Length: {itemsState.length}</div>;
}
```

**Comment by chirag-droid** [comment]
I don't think this is a bug. This happens because you are triggering an update via useEffect which depends on `items`. But this items is recreated on each render because of default args.

https://react.dev/learn/you-might-not-need-an-effect
https://react.dev/learn/keeping-components-pure

```js
export function List({ items = [] }) {
  const [itemsState, setItemState] = useState(items);
  return <div>Length: {itemsState.length}</div>;
}
```
or

```js
export function List({ items = [] }) {
  return <div>Length: {items.length}</div>;
}
```

**Comment by alulamoke** [comment]
actually you don't have to use hooks, it works perfectly like this 👇.

export function List({ items = [] }) {
  return <div>Length: {items.length}</div>;
}

**Comment by alulamoke** [comment]
actually you don't have to use hooks, it works perfectly like this 👇.

`export function List({ items = [] }) {
  return <div>Length: {items.length}</div>;
}`

**Comment by bk7312** [comment]
I think the issue is that `[] !== []` but `defaultEmptyArray === defaultEmptyArray`.

When you call `<List />` without specifying the `items` prop, react will set `items = []`, which will trigger `useEffect` to run since the value of `items` is *clearly different* from its previous value, i.e. `[] !== []`. 

Meanwhile, if you use set `items = defaultEmptyArray`, `items` has clearly not changed since it's still referencing the same empty array, so the `useEffect` will not run.

**Comment by mkozachok** [comment]
> I don't think this is a bug. This happens because you are triggering an update via useEffect which depends on `items`. But this items is recreated on each rerender. Either set `defaultProps` property or use const.
> 
> https://react.dev/learn/you-might-not-need-an-effect
> 
> ```js
> export function List({ items = defaultEmptyArray }) {
>   const [itemsState, setItemState] = useState(items);
>   return <div>Length: {itemsState.length}</div>;
> }
> ```
> 
> or
> 
> ```js
> export function List({ items = defaultEmptyArray }) {
>   return <div>Length: {items.length}</div>;
> }
> ```

I have more complex code in my project. It's just simple representation of issue.
I do not see any warning about this in docs. So if is bad practise or limitation - it must be mentioned.

**Comment by chirag-droid** [comment]
Yeah, i think the documentation is lacking about use of defaultProps or const.

And this is confusing for people because of how javascript works.

**Comment by Pratish10** [comment]
This set updating state is causing infinite loop because it is taking reference of the array. 

In JavaScript, when you create a new array, even if the content is the same, it results in a new reference. React uses reference comparison to determine whether the state or props have changed, and if the references are different, it assumes a change has occurred.

By using JSON.stringify to compare the contents, you are checking for changes at the content level, not just the reference level.

The below code solves the problem

`import { useEffect, useState } from "react";

export function List({ items = [] }) {
  const [itemsState, setItemState] = useState([]);

  useEffect(() => {
    if (JSON.stringify(items) !== JSON.stringify(itemsState)) {
      setItemState(items);
    } // this line starts infinite loop
  }, [items]);

  return <div>Length: {itemsState.length}</div>;
}`

**Comment by Pratish10** [comment]
The set updating state is causing infinite loop because it is taking reference of the array.

In JavaScript, when you create a new array, even if the content is the same, it results in a new reference. React uses reference comparison to determine whether the state or props have changed, and if the references are different, it assumes a change has occurred.

So items coming from props is not equal to items in useEffect

By using JSON.stringify to compare the contents, you are checking for changes at the content level, not just the reference level.

```
import { useEffect, useState } from "react";

export function List({ items = [] }) {
  const [itemsState, setItemState] = useState([]);

  useEffect(() => {
    if (JSON.stringify(items) !== JSON.stringify(itemsState)) {
      setItemState(items);
    }
  }, [items]);

  return <div>Length: {itemsState.length}</div>;
}

```

**Comment by chirag-droid** [comment]
using `JSON.stringify` is very expensive and bad.

Simplify specify defaultProps for your components or reference a const variable.

**Comment by rickhanlonii** [comment]
As others said, the reason for the loop is that `items = []` creates a new array for `items` every render. Because the array is new, the effect thinks it's different, and the effect is triggered. The short fix is to move the default value to a module level definition, so it's the same array for every render that uses the default value, as @mkozachok said.

However, this pattern is an example of when you don't need to use an effect. Instead of an effect, to sync props to state, you can call `setState` in render using the pattern described in [Adjusting Some State When a Prop Changes](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes).
