### ISSUE TITLE
Bug: onKeyUp Handler fired out of order

### ISSUE THREAD

**Issue by arch-user-france1** [facebook/react#28158]
React version:
Initially found in version `18.2.0`

## Steps To Reproduce

1. Set up a react environment and create a simple DOM with one input element.
2. Add a reference and a state
```javascript
const textRef = useRef("");
const [typedText, setTypedText] = useState("");
```
3. Set up a div to display `typedText` on your website.
4. Add a KeyUp Event Listener to the input element:
```javascript
<input onBlur={() => setFocused(false)} onFocus={() => setFocused(true)} onKeyUp={(event) => {
        if (event.key.length === 1) {
          console.log(event.key)
          textRef.current += event.key;
          setTypedText(textRef.current);
        }
})>
```
5. Focus the input element, start typing a text with more than 80 WPM

Link to code example:
https://codesandbox.io/p/sandbox/nervous-surf-vk68ck

<img width="538" alt="image" src="https://github.com/facebook/react/assets/72965843/e3b421c6-d99c-440d-bf1d-c633d557b0f1">

The first letter S is not upper case, the letters e, l in example were confused.
Platform: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0`

## The current behavior
The order is not correct. The shift key often does not work for the first letter immediately afterwards when typing quickly.
It is very likely that the same result occurs again after reloading the page. React seems to be prone to only get certain combinations wrong.

## The expected behavior
```textRef.current == content of input element```

**Comment by gsathya** [comment]
Thanks for adding a repro with sandbox, that was very useful. I dug into this a bit, but it's unclear if it's a React issue. I re-created the sandbox without React (just vanilla js) here: 
https://jsfiddle.net/gsathya/afxqdgL6/1/ 

<img width="301" alt="Screenshot 2024-01-30 at 17 35 55" src="https://github.com/facebook/react/assets/565765/a87b3516-175a-4459-82e7-53b7e169b3ce">

In the jsfiddle, I still see the behaviour described here, which means the browser is maybe(?) doing some sort of batching, causing the issue. In any case, it's clearly not an issue that's caused by React.

**Comment by arch-user-france1** [comment]
Thank you for your assistance. I'm sorry I didn't consider the browser as a source of the bug. It seems to happen on chromium based browsers, including Firefox, especially with letters like `ng`.
