### ISSUE TITLE
Bug: typescript can't determine well useMemo value

### ISSUE THREAD

**Issue by ballonura** [facebook/react#28185]
React version: `18.2.0`
TypeScript version: `5.0.2`

## The expected behavior
```js
  const shouldNotRender = useMemo(() => !organization || !ehrUser, [organization, ehrUser]);
  // if (!organization || !ehrUser) return null;

  if (shouldNotRender) return null;

  return (
    <UserManagement
      showNotification={showUserManagementNotification}
      user={{ ...ehrUser, organization }}
      onRolesChanged={onRolesChanged}
    />
  );
```
### Error
<img width="758" alt="Screenshot 2024-02-01 at 14 42 59" src="https://github.com/facebook/react/assets/22234568/503d5d0c-f2d6-4646-bd24-da61e6686502">

## The current behavior
```js
  // const shouldNotRender = useMemo(() => !organization || !ehrUser, [organization, ehrUser]);
  if (!organization || !ehrUser) return null;

  // if (shouldNotRender) return null;

  return (
    <UserManagement
      showNotification={showUserManagementNotification}
      user={{ ...ehrUser, organization }}
      onRolesChanged={onRolesChanged}
    />
  );
```
### No error
<img width="714" alt="Screenshot 2024-02-01 at 14 43 32" src="https://github.com/facebook/react/assets/22234568/b3615f5c-3195-4a32-9617-6165b92d5c8e">

**Comment by eps1lon** [comment]
This is a TypeScript limitation I believe. TS would also not refine the type if you put the condition in an function call which is was useMemo basically is.

**Comment by ballonura** [comment]
Should be fixed on TypeScript version 5.4

[Preserved Narrowing in Closures Following Last Assignments](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4-beta/#preserved-narrowing-in-closures-following-last-assignments)
https://www.youtube.com/watch?v=O6VbrLR6ro8&t=256s&ab_channel=Joshtriedcoding

**Comment by HermanBide** [comment]
are you still experiencing the same issues?

**Comment by yhekim** [comment]
The error occurs because TypeScript indicates that the organization variable can be of type Organization or undefined. This is inferred from its usage within the useMemo hook, where it is listed as a dependency along with ehrUser.

When you try to pass organization directly as part of the user object, TypeScript raises an error because organization might be undefined, and therefore cannot be directly assigned to a variable of type Organization.

To resolve this error, you need to check if organization is defined before attempting to use it. You can modify your code to conditionally render the UserManagement component only if organization is defined. For example:

if (shouldNotRender || !organization) return null;

return (
  <UserManagement
    showNotification={showUserManagementNotification}
    user={{ ...ehrUser, organization }}
    onRolesChanged={onRolesChanged}
  />
);
In this way, if the organization is undefined, UserManagement will not work and in this way the application will not show errors.

**Comment by josephsavona** [comment]
Thanks for posting and thanks everyone for suggestions on how to resolve. Since this isn’t an issue with React I’m going to close.
