### ISSUE TITLE
Explicitly bound setState call fails if no callback argument is passed in

### ISSUE THREAD

**Issue by jgebhardt** [facebook/react#2823]
In 0.12.1, passing `this.setState.bind(this, {key: val})` as an `onClick` prop value will not actually trigger a state change. However, when passing a function or falsey value as the 3rd argument, it seems to work.

```javascript
this.setState.bind(this, {key: val}); // setState does not get called
this.setState.bind(this, {key: val}, {}); // does not work
this.setState.bind(this, {key: val}, null); //works
this.setState.bind(this, {key: val}, undefined); //works
this.setState.bind(this, {key: val}, function(){}); //works
this.setState.bind(this, {key: val}, 0); //works

// From my fiddle:
this.setState.bind(this, {a: this.state.a + 1}); // 1 change gets queued up, but is not realized until calling setState with a third argument
this.setState.bind(this, {b: this.state.b + 1}, null); // works
this.setState.bind(this, {c: this.state.c + 1}, undefined); // works
```

Demo: http://jsfiddle.net/jxg/b3o9svtx/

**Comment by gaearon** [comment]
`bind` leaves the rest of arguments to be filled by caller.
If you assign bound `setState` to event handler, you get `e` as second argument to `setState` and it fails.

This is also an anti-pattern because `bind`ing is not performant and `render` can be called at any time, so you may be doing a lot of unnecessary function allocations.

**Comment by zpao** [comment]
There is an error in the console explaining :)

> Error: Invariant Violation: enqueueUpdate(...): You called `setProps`, `replaceProps`, `setState`, `replaceState`, or `forceUpdate` with a callback that isn't callable.

I'm not sure what else we can really do. As @gaearon mentioned you've passed a function that gets called with the event as the "callback" which isn't callable. You hit this invariant https://github.com/facebook/react/blob/master/src/core/ReactUpdates.js#L194-L199. Because we're doing truthy check, that's why the invariant isn't hit for 0, null, undefined. And then we don't add the callback to the queue if it's falsey. (though a couple lines lower we do send it off to `batchingStrategy.batchedUpdates` without a falsey check so *that* should be throwing as well later. cc @spicyj - should we handle that?)

**Comment by spicyj** [comment]
Looking at the code I can't figure out why it doesn't *always* throw in batchedUpdates when a callback isn't specified. I'm probably just too tired right now.
