### ISSUE TITLE
Input value leak in chrome browser heap memory

### ISSUE THREAD

**Issue by 18wh1a1219** [facebook/react#28234]
Whatever you type in the last focused input, that is getting stored in the chrome browsers heap memory in regex_last_match_info. Even the password is getting stored in plain text. How can I prevent it from storing ?

**Comment by pwbriggs** [comment]
Hey there @18wh1a1219! 👋

Thanks for opening this issue! To help us fix the problem you're experiencing, could you please do two things for me:

1. Try to determine if this issue is specific to Chrome or chromium-based browsers like Edge. Can it be reproduced on Firefox?
2. If so, please create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) demonstrating this bug. Send it (or a link to it) and, if applicable, a screen recording.

Thanks! ❤️
