### ISSUE TITLE
The facebook CDN link for react is a 301 to an http:// location. This breaks CSP on https:// sites

### ISSUE THREAD

**Issue by Pomax** [facebook/react#2829]
If you try to load the HTTPS CDN location for react, `https://fb.me/react-0.12.2.min.js`, the browser gets 301 redirected to `http://dragon.ak.fbcdn.net/hphotos-ak-xfp1/t39.3284-6/10574693_1499509230337635_2056748217_n.js` which is an HTTP resource, which is then rejected by browsers because of "https everywhere" requirements. Additionally, sites with explicit CSP won't let this redirect through even if the browser was told to ignore https-everywhere enforcement.

**Comment by zpao** [comment]
Yea, we know. The fb.me "CDN" is not really set up to be a real CDN. We suggest you host the files yourself in a production environment or use one of the real CDNs we link to - http://cdnjs.com/libraries/react or http://www.jsdelivr.com/#!react

We should probably change the wording around the fb.me links to make it clear about the limitations.

We do plan on eventually have a better supported official CDN but in the mean time I'm going to close this out because the fb.me limitation isn't something we can fix. fb.me is a redirect service that doesn't support https.

**Comment by Pomax** [comment]
yeah, I'm currently running it through a browserify/gulp-concat bundling to keep everything in a single file atm - the alternative I was running with while I was sorting that out was the https://cdnjs.com/ version of the latest react, which might be a location to point to in the docs instead of fb.me?
