### ISSUE TITLE
Bug: Adding StrictMode component leads to cases that can't happen in concurrent mode. 

### ISSUE THREAD

**Issue by Szymon20000** [facebook/react#28347]
I'm currently preparing my app for the new react 18 features and turned on the new StrictMode component. 
According to the docs it's a good way to make sure our apps are ready for concurrent mode and avoids side effects. 
https://react.dev/blog/2022/03/08/react-18-upgrade-guide
I know that all useEffects are called twice. It does makes sense and helps to catch some side effects. 
It turned out that some libraries are not ready for it though. For instance useEffect with empty dep array is also called twice. 
That means that we can't really treat returned callback of such useEffect as willUnmount method. 
From what I understand it will prepare us for the future  offscreen API and open new doors for future performance improvement. 
That's great. But At the moment I want to just make sure my app supports concurrent mode as a lot of libraries are not ready for missing willUnmount (I know that if useEffect would be symmetrical that wouldn't be an issue but it is in a lot of libs :D ).

**Is it really possible that useEffect with empty array can be called twice with reserving the component state in concurrent mode? 
(Without the offscreen API)?**

One of the libs I use has a ref (const wasUnmountedAndCancelledAllFetchCalls = useRef(false)) and that flag is changed in willMount (return callback of the useEffect with empty dep array). It seems to be safe for the concurrent mode as if we drop a render progress due to more important update (or a new transition) we won't call willUnmount unless we actually unmounted the component as it happened in the commit phase which is synchronous. Am I wrong here?

I would really really appreciate all responses 🥹. 
React version: latest

## Steps To Reproduce

1. Add StrictMode Component 
2. UseEffect with empty deps array is called twice in Concurrent mode

Link to code example:

## The current behavior

UseEffect called twice

## The expected behavior

UseEffect called twice if that scenario is actually possible in concurrent mode or StrictMode having a flag that tells if he should test against offscreen rendering.

**Comment by zhangshichun** [comment]
LGTM

**Comment by rickhanlonii** [comment]
> Is it really possible that useEffect with empty array can be called twice with reserving the component state in concurrent mode? (Without the offscreen API)?

Yes, this happens today with Fast Refresh. And it also happens today with layout effects when you re-suspend a tree on update. In that case we move the existing content "offscreen" (unmounting the layout effects), and when the content is ready to commit again re-mount it using the same state and re-creating the layout effects. This is important for performance of re-committing suspended trees (so we don't need to destroy and re-create all of the state like DOM elements). Since the content may have changed, it means we need to re-run layout side-effects, like setting the hight of a tooltip, so it's not out of date.

Even outside of these cases, if you don't clean up the resources like websockets or subscriptions during unmount, then you'll leak resources or connections, with Strict Mode helps you find (as described in the docs for this behavior [here](https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development)).

**Comment by Szymon20000** [comment]
@rickhanlonii Thanks for taking the time and responding!
