### ISSUE TITLE
[Q] Transfer state from server

### ISSUE THREAD

**Issue by ColCh** [facebook/react#2834]
I wonder if it's possible to transfer state and\or props from server to client. I imagine ways like stringify\parse JSON to achieve it, how to do that properly? Or I should use AJAX for initial state even in isomorphic webapp?

**Comment by pspeter3** [comment]
You could stringify the state in a meta tag in the document.

**Comment by zpao** [comment]
People are doing this in a couple different ways. Stringifying the initial props and making sure those are part of the initial call to `React.render` in some way is the typical route. Some are just injecting a global variable with that data in a script tag. Using meta tags is an interesting way to go, I could see that working pretty well too.

Requesting that data again is a way to go but obviously has drawbacks. That might end up being the least complicated way for your application so if it works for you then great but it does have its drawbacks.

I'm going to close this out just because it's not really an issue with React. The mailing list and stack overflow are probably better places to continue this discussion but feel free to keep going here.
