### ISSUE TITLE
Bug: Hydration error due to <button> 

### ISSUE THREAD

**Issue by JAGADEESHWARAN20** [facebook/react#28545]
React version:

## is there any way to fix this issue
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

In HTML, <button> cannot be a descendant of <button>.
This will cause a hydration error.

                              <button>
                              ^^^^^^^^
                                <_c>
                                  <button>
                                  ^^^^^^^^

Link to code example:

https://github.com/JAGADEESHWARAN20/Shopwithdashboard/blob/main/app/(dashboard)/%5BstoreId%5D/(routes)/settings/components/SettingsForm.tsx

**Comment by JAGADEESHWARAN20** [comment]
i tried So many time to find this issue , but I don't get it ....

## screenshot:
![image](https://github.com/facebook/react/assets/66456490/29d3dedc-3bcd-4fbf-ac6d-707a1d78b3e9)


## how to remove this also
![image](https://github.com/facebook/react/assets/66456490/3aa59811-e8af-45be-a9dd-758feaa3d73a)

**Comment by muskan2622** [comment]
@JAGADEESHWARAN20 How did you run this project? using yarn test?

**Comment by JAGADEESHWARAN20** [comment]
Using npm run dev

**Comment by dmx1254** [comment]
The error is present because you have nested two buttons because the generated html code will render two buttons side by side whereas during hydration the buttons are nested.

**Comment by rickhanlonii** [comment]
Yeah nesting buttons is [invalid HTML](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element).

**Comment by Divyanshucod** [comment]
Title: Next.js + Shadcn UI: Hydration Error & Invalid Nested <button> Element

I’m working on my first Next.js project with Shadcn UI and encountering two issues:

Error 1: Hydration Error with <Router>
I’m seeing the following in the console:


<Router actionQueue={{state:{...}, ...}} assetPrefix="">
    <HistoryUpdater>
      <RuntimeStyles>
        <HotReload assetPrefix="">
          <ReactDevOverlay state={{nextId:1, ...}} dispatcher={{...}}>
            <DevRootNotFoundBoundary>
              <NotFoundBoundary notFound={<NotAllowedRootNotFoundError>}>
                <NotFoundErrorBoundary pathname="/friends" notFound={<NotAllowedRootNotFoundError>} ...>
                  <RedirectBoundary>
                    <RedirectErrorBoundary router={{...}}>
                      <Head>
                        <link>
                          <script>...</script>
                                          <RootLayout>
                                            <html lang="en">
                                              ...
-                                                className="light"
-                                                style={{color-scheme:"light"}}
It seems like a hydration issue, where server-side and client-side rendered HTML do not match. I've tried checking for inconsistencies in the state and asset prefix but the issue persists.

Error 2: Nested <button> Elements
I’m getting this error:


In HTML, <button> cannot be a descendant of <button>. This will cause a hydration error.
The issue is caused by nested <button> elements, as seen in this code:

<li className="relative">
  <LinkComponent href="/conversat...">
    <a onClick={...}>
      <Tooltip>
        <PopperProvider>
          <TooltipProvider>
            <TooltipTrigger>
              <PopperAnchor asChild={true}>
                <Primitive.div asChild={true}>
                  <Primitive.button>
                    <button>...</button>
                  </Primitive.button>
                </Primitive.div>
              </PopperAnchor>
            </TooltipTrigger>
          </TooltipProvider>
        </PopperProvider>
      </Tooltip>
    </a>
  </LinkComponent>
</li>
I’ve tried replacing the <button> with other elements but still face issues.

Any advice on resolving these errors.

**Comment by pwbriggs** [comment]
Hey @JAGADEESHWARAN20! 👋

Can you check if this an issue with React or with Next.js? Since this issue is closed, please open a new issue either [in this repo][react-issue] or at the [vercel/next.js repo][next-issue], after confirming that one doesn't already exist matching your issue. Please remember to include a minimal reproducible example with any issue you open (see [Stack Overflow's guide for writing an MCVE][so-mcve]).

Thanks! ❤️ 

[react-issue]: https://github.com/facebook/react/issues/new/choose
[next-issue]: https://github.com/vercel/next.js/issues/new/choose
[so-mcve]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nitinkumar2003** [comment]
use suppressHydrationWarning in html tag 
 <html lang="en" suppressHydrationWarning>

**Comment by not-AdityaRawat** [comment]
I stumbled across the same problem but using ShadCn **SidebarMenuButton**. I guess their is no way around this problem, you just have to use a div instead and style it to give Button look.
like...

```
<SidebarMenuButton>
<div role="button" tabIndex={0} aria-pressed onClick={handleclick}>Save changes</div>
</SidebarMenuButton>
```

**Comment by nkaewam** [comment]
@not-AdityaRawat, you can use Button component in shadcn and add `asChild` property to the button. It'll convert button to div and keep all the button properties intact.

```tsx
<SidebarMenuButton>
<Button onClick={handleclick} asChild>Save changes</Button>
</SidebarMenuButton>
```

**Comment by Jkhall81** [comment]
I put the asChild on the parent button component, and it got rid of the error.  Putting the asChild on the nested button was messing up styling on the nested button for me.

` return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button className="size-9 relative overflow-hidden bg-[#ababad] hover:bg-[#ababad]/80 text-slate-800 font-semibold text-xl">
          {workspaceLoading ? (
            <Loader className="size-5 animate-spin shrink-0" />
          ) : (
            workspace?.name.charAt(0).toUpperCase()
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent side="bottom" align="start" className="w-64">
        <DropdownMenuItem
          onClick={() => router.push(`/workspace/${workspaceId}`)}
          className="cursor-pointer flex-col justify-start items-start capitalize"
        >
          {workspace?.name}
          <span className="text-xs text-muted-foreground">
            Active workspace
          </span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};`
