### ISSUE TITLE
Bug: Using the hook useDeferredValue - Suspense fallback didn't show the contents

### ISSUE THREAD

**Issue by lovizotto** [facebook/react#28605]
React version: 18.2.0

## Steps To Reproduce

1. Go to [useDeferredValue](https://react.dev/reference/react/useDeferredValue)
2. See the second example of code in the documentation

**Comment by IuriPires** [comment]
@lovizotto Yeah. The suspense fallback is not being displayed. @eps1lon  I think the documentation itself as exposed by @lovizotto is a good example.

**Comment by eps1lon** [comment]
That is the intended behavior though. This is explained in the deep dive section:
> In the background, React tries to re-render with both query and deferredQuery updated to "ab". If this re-render completes, React will show it on the screen. However, if it suspends (the results for "ab" have not loaded yet), React will abandon this rendering attempt, and retry this re-render again after the data has loaded. **The user will keep seeing the stale deferred value until the data is ready.**


I emphasized the important bit that the user keeps seeing stale data instead of the Suspense fallback. 

The [Suspense docs](https://react.dev/reference/react/Suspense) also say this:

> If Suspense was displaying content for the tree, but then it suspended again, the fallback will be shown again unless the update causing it was caused by [startTransition](https://react.dev/reference/react/startTransition) or [useDeferredValue](https://react.dev/reference/react/useDeferredValue).

Since the update was caused by `useDeferredValue`, we don't display the fallback again.

Did you assume that a suspended component implies that a Suspense fallback is shown?

**Comment by rickhanlonii** [comment]
Yeah as @eps1lon said, this it expected, and one of the main features of `useDeferredValue`. If you wanted to force the fallback (not recommended) you wouldn't use `useDeferredValue`
