### ISSUE TITLE
Removing object from array inside the state of component not refresh all DOM

### ISSUE THREAD

**Issue by frais-sinpo** [facebook/react#2885]
I suppose that may be not a bug but my fault in code, when I filter an array in the state of component. 
Here is the question and description of my problem on SO: http://stackoverflow.com/questions/28021573/removing-object-from-array-inside-the-state-of-react-js-component-not-refresh-al
and plnkr: http://plnkr.co/edit/5zLSClQYCGj3OcbYjVWh?p=preview

**Comment by syranide** [comment]
This is by design. React does not poll state, only `setState(...)`, `forceUpdate()` and `React.render` triggers re-renders..

You really should not bypass `setState` and mutate state directly. But if you are, then you'll need to `forceUpdate` or make dummy call to `setState`, but I don't really recommend either of those... but they do work.
