### ISSUE TITLE
Missing closing brace gives misleading warning...

### ISSUE THREAD

**Issue by Dakuan** [facebook/react#2886]
heres some `jsx` code:

``` html
		return (
			<div className="form-group">
				<label className={"control-label " + this.props.labelClass}>
					{this.props.label || this.props.name}
				</label>
				<div className={this.props.inputClass>
					<select name={this.props.name} className="form-control">
						{this.props.options.map(this._renderOption)}
					</select>
				</div>
			</div>
		)
```

which gives the following error:

```
Line 19: Adjacent XJS elements must be wrapped in an enclosing tag
```

Spent a bit of time wondering which tag wasn't closed or some such before noticing that this line wasn't right:

``` html
<div className={this.props.inputClass>
```
It's missing the closing brace. I wonder if the error could be more descriptive in this case, as when I have had this error before its been the pointy rather than curly brackets that have been the problem.

**Comment by brigand** [comment]
So.. the problem is that `this.props.inputClass>` is a valid start of an expression in JS, and the > is interpreted as the greater than operator.  The code isn't actually invalid until the first `</div>` – and if you replaced that with `}/>` it'd compile.

It's a bit of a tricky problem to solve and get the correct line number.


<sub>Side note: you forgot the curlies around `this.props.options.map(...`</sub>

**Comment by Dakuan** [comment]
@brigand Indeed, didn't think it was going to be an easy one. Maybe worth adding to a list of gotchas? It's the sort of silly thing that's easy to lose quite a bit of time to!

**Comment by gpbl** [comment]
@Dakuan you could use a lint tool like jsxhint or islint, they help a lot for catching such errors.

**Comment by brigand** [comment]
@gpbl you'd get the same error with jsxhint.  All it does is `jsx -> js` and give the resulting js to jshint.

**Comment by zpao** [comment]
I'm going to send you over to https://github.com/facebook/esprima/issues/34 since that's where this error is actually coming from, it's part of the parse step. This specific message is different than the one mentioned in that issue but it's in the same class of problems. I think we're definitely up for making the messages as helpful as possible, just want to make sure we solve the problem in the right way.
