### ISSUE TITLE
[React 19] Async transitions race condition handling

### ISSUE THREAD

**Issue by tom-sherman** [facebook/react#28914]
## Summary

Repro: https://stackblitz.com/edit/vitejs-vite-ymbqrc?file=src%2FApp.tsx

How do we handle async transitions that resolve out of order? In the above reproduction the search for "a" can resolve after "ab", leading to the input containing "ab" but the results pertaining to "a". In other words, the most recent transition isn't the one that wins.

In other discussions it's [been mentioned](https://twitter.com/acdlite/status/1768780638767788501) that this is caused by React losing the context that the setState happens inside a transition as it happens after `await`. But I'm not sure how to work around this today

**Comment by schimi-dev** [comment]
At the moment, state updates that are done after an `await` statement inside a transition are not part of the transition. To make them happen inside a transition, they need to be explicitly wrapped with `startTransition`.

The following React Conf talk briefly mentiones this:
https://www.youtube.com/watch?v=T8TZQ6k4SLE&t=8880s

So, for now explicitely wrap the state update in another transition like this:

```ts
startTransition(async () => {
  const results = await getResults(newSearch)
  startTransition(() => {
    setResults(results) // for now explicitely wrap the state update done via `useState` in a transition
  })
})
```

**Comment by tom-sherman** [comment]
@schimi-dev That solution doesn't work.

**Comment by acdlite** [comment]
You can force the actions to run in sequence with useActionState, but that's not what you should do for this particular UI because if the user types faster than the network (which is nearly always the case), you don't want to block on anything except the last network request. The request needs to initiate immediately.

The solution in this case is to remove the `await` and instead pass the promise to `setState` and unwrap with `use` inside your component:

```js
startTransition(() => setResultsPromise(getResults(newSearch)));

// ...

const results = use(resultsPromise);
```

That gets rid of the race condition because you're adding the promise to the state queue immediately inside the search event.

Then React will only block on whatever is the most recent request.

**Comment by acdlite** [comment]
Going to close the issue but if you have more questions let us know

**Comment by tom-sherman** [comment]
@acdlite sorry, I only just got around to trying this out!

I tried to implement your changes and while it solves the trace condition, `isPending` never returns to the `true` state. Is this a bug or am I holding it wrong?

https://stackblitz.com/edit/vitejs-vite-xo3prr?file=src/App.tsx,src/main.tsx

**Comment by tom-sherman** [comment]
Also when trying to integrate your changes I had to wrap the component in suspense otherwise there was a confusing error message. I've raised a separate issue for that #30709

**Comment by tom-sherman** [comment]
@acdlite any ideas on the above where isPending gets stuck?

**Comment by tom-sherman** [comment]
Ah, this issue appears to be fixed on canary.
