### ISSUE TITLE
request: [compiler] `react-compiler-healthcheck` display the list of compiled files.

### ISSUE THREAD

**Issue by Fausto95** [facebook/react#29078]
## Summary

I think it would make much more sense if `react-compiler-healthcheck` actually displayed more info about the compiled components. This would help a lot with refactors.

I think showing the component name would already be helpful.

**Comment by dospore** [comment]
On this, I know it mentions some configuration where you can skip files, is this true for healthcheck as well? and if so where does it get placed?
`const ReactCompilerConfig = {
  sources: (filename) => {
    return filename.indexOf('src/path/to/dir') !== -1;
  },
};`

**Comment by Maxou44** [comment]
And list the components that are not compiled with the reason why :)

**Comment by Fausto95** [comment]
> And list the components that are not compiled with the reason why :)

Yes, have also taken that into account.
You can check the PR here  #29080

**Comment by ilarramendi** [comment]
+1 to this

**Comment by enriquerecor** [comment]
Also +1 on this

**Comment by maddada** [comment]
Thank you for the PR @Fausto95

I also needed this since I had some components not being compiled even though I followed the rules of react/hooks and there aren't any ESLint errors.s

Now the issue is I don't know why they're not being compiled but at least I can memorize them manually if needed.

Here are the steps to patch the dist file:

1. run "npm i --save-dev react-compiler-healthcheck"
2. In your codebase's node_modules folder, go to react-compiler-healthcheck/dist
3. Replace the file in the index.js file with the content of this gist: https://gist.github.com/maddada/8e064cf31e5dce26cb5166f0af24ca3c
4. Run `npx react-compiler-healthcheck --verbose` and you should see which components weren't compiled.

5. You can also use patch package to save the changes if you want that so you can have this shared with others (instructions are on their npm page)

Now you can use react dev tools & react scan (separately) to check if this component needs to be memoized.
You'll see a lot of needless re-renders if it does. Also you can set a lower CPU profile and check if the FPS is dropping with react-scan when the re-renders are happening.

**Comment by hmadhsan** [comment]
Hi, so I've already built an npm package few days ago to help with it. It scans your whole project for legacy code, bad hooks, and other common problems, then suggests fixes. https://www.npmjs.com/package/react-compiler-check

**Comment by zeorin** [comment]
Another option is to configure the `react-hooks/react-compiler` ESLint rule as follows:

```js
        'react-hooks/react-compiler': [
          'error',
          {
            reportableLevels: new Set([
              'InvalidJS',
              'InvalidReact',
              'InvalidConfig',
              'CannotPreserveMemoization',
              'Todo',
              'Invariant',
            ]),
          },
        ],
```

EDIT: Just switched to ESLint v9 and flat config (:slowpoke:, I know), and now I'm configuring the rule as `'react-hooks/react-compiler': 'error'`, without extra options, but I also added the following config object further on, so that I can have warnings instead of errors for the "silent" bail-outs.

```js
  // Warn instead of bailing out of compilation silently
  {
    plugins: {
      'react-hooks-warn':
        reactHooks.configs['recommended-latest'].plugins['react-hooks'],
    },
    rules: {
      'react-hooks-warn/react-compiler': [
        'warn',
        {
          reportableLevels: new Set([
            // 'InvalidJS',
            // 'InvalidReact',
            'InvalidConfig',
            'CannotPreserveMemoization',
            'Todo',
            'Invariant',
          ]),
        },
      ],
    },
  },
```
