### ISSUE TITLE
 findDOMNode has been deprecated and removed from react-dom in the latest versions, including the React 19.0.0 beta. 

### ISSUE THREAD

**Issue by krishnagptamcs** [facebook/react#29123]
## [React 19] [Bug] , i am using an library  called react-virtualised , i am getting this error  "Attempted import error: 'findDOMNode' is not exported from 'react-dom' (imported as 'findDOMNode')."  it means "that findDOMNode has been deprecated and removed from react-dom in the latest versions, including the React 19.0.0 beta." 

CodeSandbox : https://codesandbox.io/p/sandbox/react-dom-error-2mdwjd

**Comment by eps1lon** [comment]
The removal was intentional. For discussion around this topic, please check out https://github.com/facebook/react/issues/28926

**Comment by krishnagptamcs** [comment]
I am using react-virtulisastion library ! , i am getting in this library only , suggest me another library , which does not throw this error , for react 19 @eps1lon

**Comment by BykovDenis** [comment]
@krishnagptamcs i have the same problem. I'm using virtualized React library but it's not compatible with React 19 😔.

**Comment by waheedrafiq** [comment]
I have just upgraded from React 16 to React 19 and upon npm run build I am getting the Attempted import error: 'findDOMNode' is not exported from 'react-dom' (imported as 'ReactDOM').  build error , what is the fix for this , I have tried removing react-dom and that does not seem to work within the package.json file.  so I am on Node version 22.14 and npm version 11.2 and React 19 typescript
