### ISSUE TITLE
componentDidUpdate prevState is not previous state

### ISSUE THREAD

**Issue by kevzettler** [facebook/react#2914]
http://facebook.github.io/react/docs/component-specs.html#updating-componentdidupdate

```javascript
componentDidUpdate: function(prevProps, prevState){
	        debugger;
                //...
}
```
```shell
this.state.tags.length
2
prevState.tags.length
2
```

**Comment by zpao** [comment]
Presumably `this.state.tags` is an array and you have pushed into it, then called `setState` with it again.

Something like this:

```js
update: function() {
  var tags = this.state.tags;
  tags.push('new tag');
  this.setState({tags: tags});
}
```

That will keep the reference to the same array instance, which is why prevState and state are the same.

However if you actually cloned the array you wouldn't run into this reference issue (unless you looked at further nested objects)

```js
update: function() {
  var tags = this.state.tags.slice();
  tags.push('new tag');
  this.setState({tags: tags});
}
```

I don't think that we want to make this work properly. It would require deep cloning current state on every transition which can get expensive. Other libraries are better at this, things like Immutable.js and Mori are good examples.

cc @sebmarkbage do you're aware. Reopen if you think we should do anything about this ourselves.
