### ISSUE TITLE
[Compiler Bug]: Error Invalid hook call

### ISSUE THREAD

**Issue by Facug03** [facebook/react#29202]
### What kind of issue is this?

- [X] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [X] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Link to repro
https://codesandbox.io/p/devbox/objective-spence-zrxvd7

### Repro steps

I am trying the new React 19 beta and the compiler throws an error when using the new `useActionState` hook and setting the `formAction` to the action of a form. When clicking a button, it throws this error:

![imagen](https://github.com/facebook/react/assets/107658697/855c9936-1c69-4693-b0bc-5ba5a5882f88)

Disabling the compiler, this works just fine.

If i create the function `changeInput` in the useActionState hook the error disappears

![imagen](https://github.com/facebook/react/assets/107658697/78e6d03f-f322-44ec-bf53-b52a6b6e2863)

![imagen](https://github.com/facebook/react/assets/107658697/0863d5eb-5ee9-4639-80fd-ec9b78ff8d5b)

### How often does this bug happen?

Every time

### What version of React are you using?

19.0.0-beta-26f2496093-20240514

**Comment by sanjogR** [comment]
Read the error message carefully. You can ONLY use Hooks inside the <b> BODY </b> of a <b>FUNCTIONAL COMPONENT</b>. 

<b>Question:</b> 
Would you consider useCalculate a Hook or a BODY OF A FUNCTIONAL COMPONENT?  

I think this is issue with your implementation of Hook rather than issue with useAction hook itself. Please refer to the generated error for explanation. You cannot use useAction hook inside another hook as it is by design to be used inside BODY of a FUNCTIONAL COMPONENT.

**Comment by SanjogRijal** [comment]
Read the error message carefully. You can ONLY use Hooks inside the <b> BODY </b> of a <b>FUNCTIONAL COMPONENT</b>. 

<b>Question:</b> 
Would you consider useCalculate a Hook or a BODY OF A FUNCTIONAL COMPONENT?  

I think this is issue with your implementation of Hook rather than issue with useActionState hook itself. Please refer to the generated error for explanation. You cannot use useActionState hook inside another hook as it is by design to be used inside BODY of a FUNCTIONAL COMPONENT.

**Comment by Facug03** [comment]
No, that's not the issue, even if i move the hook inside a component the error still happens and useCalculate is being used in a component too, it's the same as defining it at the component, the only diferrence is i am separating a little the logic from the ui. And this is not an error of the useActionState hook is an error of the compiler.

**Comment by josephsavona** [comment]
Thanks for posting, this is a legit bug. What's happening is that `changeInput` is getting compiled even though it's not a hook, i'm debugging why.

**Comment by josephsavona** [comment]
OHHHH you have `compilationMode: "all"` set in your vite.config.js. We strongly recommend using the default configuration, many of the flags are things we are using for experimentation and not recommended to change. The default compilation mode is that the compiler infers which functions are components and hooks, and this mode correctly skips `changeInput`.

I'm going to close since this bug only occurs when changing the configuration in a way we don't recommend.

**Comment by Facug03** [comment]
I thought that was the default mode, deleting that configuration works perfectly fine!

**Comment by josephsavona** [comment]
@Facug03 Just curious, where did you read about compilationMode: "all"? I'm wondering if our docs need to be updated.

**Comment by Facug03** [comment]
Honestly, i don't even know where i find it.

**Comment by josephsavona** [comment]
That's cool! Just curious. Thanks again for posting!
