### ISSUE TITLE
Idea: Official nightly edge build on NPM

### ISSUE THREAD

**Issue by tgriesser** [facebook/react#2924]
Working against master isn't as straightforward in React as it is in other JS libraries. Typically, it's possible to just point to a SHA commit in your NPM and have it `npm install` and work against that version of the codebase. Since this doesn't happen in React due to the compile step, it'd be nice if there were an official nightly dev-build of React available on NPM.

One main benefit of this would be for library authors, making it easier to check their projects against changes going into master and potentially weigh in on issues - one example that comes to mind is the warnings which now are around in [react-router](https://github.com/rackt/react-router/issues/638) in 0.13 due to some of the context changes.

**Comment by spicyj** [comment]
I think the current plan is that we're going to push a tag each week so you can `npm install react@latest`. Hopefully this will be more stable than master but still up-to-date enough to test the latest changes. @zpao can elaborate.

There's also automatic builds here triggered by Travis which should always be up to date:

http://react.zpao.com/builds/master/latest/

You can `npm install http://react.zpao.com/builds/master/latest/react.tgz` for that.

**Comment by brigand** [comment]
There's also http://react.zpao.com/builds/master/latest/react.min.js which is good if you want to play with the latest in a fiddle/jsbin (my [default jsbin][1] has it in a comment).

@zpao `latest` is what's installed when you do `npm install react` <sup>[docs][2]</sup>.  You want to ensure that `latest` points to the latest stable, and publish tags like `0.13.0-alpha.2`.

[1]: http://jsbin.com/fijewitehe/1/edit
[2]: https://docs.npmjs.com/cli/install

**Comment by zpao** [comment]
Yea, I don't want to push to npm nightly. There are often points where we know something is broken so it would be irresponsible. But we have been pushing pre-release checkpoints to npm for 0.13. These are generally (but not always) the same checkpoints that we bring in and use at Facebook.

If you want to make use of that you can `npm install react@next` and that will always bring in the next pre-release build. That's currently `0.13.0-alpha.2`, published last Friday. Or you can install directly from the `tgz` on our builds server as @spicyj mentioned. One day we'll clean that up so it looks more official :)

@brigand - "latest" on the builds server is simply a symlink to the most recent build on a given branch. It's not a corollary to npm tags. On npm I do keep "latest" pointing at stable and use "next" as the pre-release channel. You can't actually publish tags that look like semver versions anymore (I used to for RCs), so that's why we use "next", to match what npm itself does.

I've only tagged our "officially announced / supported" builds in the git repo. In other words, RCs and final builds. I haven't tagged alphas. 

So to answer the overall request, we have nightlies. But we won't publish them to npm. So I'm going to close this out.

**Comment by spicyj** [comment]
(@brigand sorry, I did mean `next`.)

**Comment by tgriesser** [comment]
Sounds good, thanks for the info!
