### ISSUE TITLE
Arrow functions don't properly bind in JSX transform with harmony option

### ISSUE THREAD

**Issue by zgotsch** [facebook/react#2927]
It seems that when the JSX transform can't find a use of `this` in an ES6 arrow function, it don't bind the function to this (probably since `Function.prototype.bind`) is slow. Unfortunately, when `this` only appears in the namespacing of a JSX element, the JSX transform doesn't realize that it needs to bind the resulting function. 

Example:
```
var MyDemoClass = React.createClass({
    subcomponent: React.createClass({
        render: function() { return null; }
    }),

    render: function() {
        var myUnboundFn = () => {
            <this.subcomponent />;
        };

        var myBoundFunction = () => {
            var self = this;
            <self.subcomponent />;
        };

        return <div/>;
    }
});
```
transforms to:
```
var MyDemoClass = React.createClass({displayName: "MyDemoClass",
    subcomponent: React.createClass({displayName: "subcomponent",
        render: function() { return null; }
    }),

    render: function() {
        var myUnboundFn = function()  {
            React.createElement(this.subcomponent, null);
        };

        var myBoundFunction = function()  {
            var self = this;
            React.createElement(self.subcomponent, null);
        }.bind(this);

        return React.createElement("div", null);
    }
});
```

**Comment by zgotsch** [comment]
The example is using the jsx executable from react-tools 0.12.2.

**Comment by spicyj** [comment]
cc @jeffmo @DmitrySoshnikov – `() => <this />` doesn't bind `this` properly because the `this` is a XJSIdentifier instead of a ThisExpression.

cc @sebmck too – 6to5 seems to have the same issue.

**Comment by sebmck** [comment]
This is probably something that needs to be solved on the parser side. It potentially seems like a bug in the [JSX spec](https://github.com/facebook/jsx) since it's following the correct grammar.

On a partially related note: Does `react-tools` really transform arrow functions into function binds?

**Comment by sebmck** [comment]
cc @RReverser for [acorn-jsx](https://github.com/RReverser/acorn-jsx)

**Comment by spicyj** [comment]
It's not obvious to me that this is a JSX spec bug – for example, you could imagine that `<this />` could compile into something that doesn't use a `this` in the result, and conversely, `<div />` could compile into something that does use `this`. Seems like the transforms need to cooperate somehow. I guess that's hard when the transforms output strings.

**Comment by sebmck** [comment]
@spicyj Ah right, that's true. This is an easy fix anyway, was just investigating to see if it's a larger issue. I'll push out a fix shortly.

**Comment by sebmck** [comment]
Fixed in 6to5 3.1.1

**Comment by RReverser** [comment]
> It's not obvious to me that this is a JSX spec bug – for example, you could imagine that `<this />` could compile into something that doesn't use a `this` in the result

@spicyj I tend to agree that it *is* a spec bug - when we wrote it, we didn't think about using any expressions incl. `this` inside element names. If we do want to treat `this` not as regular `JSXIdentifier` but as `ThisExpression`, then we should add `ThisExpression` to the spec explicitly.

**Comment by spicyj** [comment]
@RReverser I mean that different transforms may want to do different things with the characters `this`. In some cases it might mean the JS concept but I could imagine others where it doesn't.

**Comment by sebmck** [comment]
Since JSX is just an extension of JavaScript it seems pretty safe to always assume it's a `ThisExpression`.

**Comment by RReverser** [comment]
@spicyj I might be wrong, but IMO it's exactly one of those things that should be actually standardized by spec, if we want people to feel safe when using it and to assume that it will work in the same way everywhere (so they don't catch weird runtime bugs).

@sebmck Agree.

**Comment by sebmck** [comment]
Any resolution on this? Current 6to5 solution is to turn a `JSXIdentifier` with a `name` of `this` into a `ThisExpression`. Not comfortable with keeping it this way if it's different in core.

**Comment by zpao** [comment]
cc @sebmarkbage

**Comment by sebmarkbage** [comment]
The JSX spec doesn't make any claims to scoping rules of variables including their semantic meaning. Including the scope of the expressions contained in attributes. This is obviously a limitation because you can't reason about things like unused variables etc. This is also a feature.

If we want to implement semantic meaning, then we should move forward with a full semantic spec but we're not ready to do that since different implementations have different requirements. We're also actively changing the semantics.

If there was a `"this"` tag in HTML (which there very well might be in the future) or if I have that concept in my XML, then I'd like to use `<this />` to create such elements. That's why we went with the lower-case convention for React.

We added `JSXMemberExpression` as a compromise to allow a subset of valid identifiers in that scope. However, we didn't make it extend `MemberExpression`. It extends `Expression` in the AST.

Therefore, just adding the `ThisExpression` within it isn't enough to make it seamlessly work. You have to still reason about the `JSXMemberExpression` around it. Once you do that, you might as well special case the `JSXIdentifier` too.

Also, remember that `this` isn't the only reserved keyword. `arguments` already have the same issues (even though it is only reserved in strict mode). Seems strange that `ThisExpression` is special cased.

There is already talk about using more reserved keywords to include reflective syntax sugar like `new.target` and more.

Therefore, I don't think it makes sense to special case `ThisExpression` unless you also want to do that with every other possible reserved or partially reserved identifier/expression.

**Comment by sebmarkbage** [comment]
If we instead used the wrapper braces we could make it a full `AssignmentExpression` and then you're free to put whatever in there.

`<{this.foo} />`

Ofc, this has the problem of closing tags looking weird.

`<{this.foo}>...</{this.foo}>`

**Comment by sebmck** [comment]
@sebmarkbage Do you not think it's confusing for `JSXMemberExpression` to output like a regular `MemberExpression` but not behave like one? It'd be extremely confusing and surprising to any React/JSX developer to see it behave this way.

**Comment by sebmarkbage** [comment]
@sebmck This issue is still a bug, however, it is a bug in the transpilers, not the JSX spec.

Just like `var x = () => arguments;` is also a bug in JSTransform, or `var x = () => <arguments.length />` for that matter.

**Comment by sebmck** [comment]
@sebmarkbage Ah thanks for the explanation, completely agree with you that it shouldn't be handled by the JSX spec. Happy to adapt to whatever changes you deem necessary.

**Comment by jeffmo** [comment]
Super delayed response:

Regardless of whether this is a bug in a spec or whatever, the decision to avoid doing a `.bind` in the arrow function desugaring is purely an optimization and could easily be considered heuristic given this use case.

As such, it should not be a problem to just look for XJSIdentifier('this') in the arrow function transform and "accidentally" do an unnecessary bind in the edge case where this occurs *and* doesn't actually mean `this`

**Comment by jeffmo** [comment]
(I'll hack together a bugfix for jstransform here, btw)

**Comment by jeffmo** [comment]
Fixed in jstransform here: https://github.com/facebook/jstransform/commit/b370c99706f075c6dfea134db5049d0f5e1669a7

**Comment by jimfb** [comment]
Also JSX Transform has been replaced by https://babeljs.io/
