### ISSUE TITLE
Broken componentWill(Did)Update

### ISSUE THREAD

**Issue by LKay** [facebook/react#2974]
When updating state of the component the corresponding method from lifecycle get called but every time for any component the ``prevState`` or ``nextState`` is in fact always the same with the current state. So comparing them always return true. Mentioned methods should return correct objects for previous, next state.

```
getInitialState: function () {
    return {
        test: false
    };
}
```

```
someMethod: function () {
    this.setState({
        test: true
    });
}
```

```
componentDidUpdate: function (prevProps, prevState) {
    console.log(prevState.test === this.state.test); // Always true!
},
```

**Comment by syranide** [comment]
Your example correctly yields `false` for me (http://jsfiddle.net/xgdm73a3/).

However, I'm pretty sure the issue you're seeing has to do with mutating objects in state/props. React does not clone objects passed in to state/props, hence, both `this.state.foo` and `prevState.foo` will reference the same object. This is why React advocates sticking to "immutable data", i.e. always create a new object instead of mutating an existing.

**Comment by LKay** [comment]
Oh, yeah the problem occurs with objects, you are right, the example was not entirely complete. Anyway I do clone the object on assigning from props to component state either by doing ``JSON.parse(JSON.stringify(obj))`` or using Underscore.js ``_.clone()``. Problem still exists.

**Comment by syranide** [comment]
Line 8, you're mutating the object.

**Comment by hzoo** [comment]
```js
this.state.test.state = true;
this.setState({
    test: this.state.test
});
```

Not sure why you need to manually set the state and then call setState - you should be able to do

```
this.setState({
    test: true
});
```

(http://jsfiddle.net/xgdm73a3/2/)

**Comment by zpao** [comment]
As noted, you're modifying `this.state` directly, which is what's used for `prevState`.
