### ISSUE TITLE
allow string arguments to classSet

### ISSUE THREAD

**Issue by flying-sheep** [facebook/react#2983]
Hi, sometimes we want statical classes and toggled classes, e.g.

```js
(this.state.hidden) ? 'my-component hidden' : 'my-component'
// or
this.props.componentClass + (this.state.hidden) ? ' hidden' : ''
```

with `classSet`, this looks like

```js
classSet({ 'my-component': true, hidden: this.state.hidden })
// or
this.props.componentClass + ' ' + classSet({ hidden: this.state.hidden })
// tbh, with ECMA 2015, this is
classSet({ [this.props.componentClass]: true, hidden: this.state.hidden })
```

this gets ugly fast. let’s allow

```js
classSet('my-component', {hidden: this.state.hidden })
// or
classSet(this.props.componentClass, { hidden: this.state.hidden })
```

idk how flexible this needs to be. the most simple to implement version would be

```js
classSet(<object-of-optionals>, ...<0-∞ static strings>)
// e.g.
classSet({foo: bar}, 'baz', barf)
classSet({foo: bar})
```

the most flexible would be

```js
classSet(...<0-∞ static strings and objects of optionals>)
// e.g.
classSet(barf, {foo: bar}, 'baz', {a: b})
```

**Comment by bloodyowl** [comment]
you can easily implement your own `classSet`

```javascript
function classSet(...args) {
  var className = {}
  args.forEach(function(item){
    if(typeof item == "string") {
      className[item] = true
      return
    }
    Object.assign(className, item)
  })
  return Object.keys(className)
    .filter((key) => className[key])
    .join(" ")
}
```

**Comment by flying-sheep** [comment]
of course. but the react addons exist for being useful, and this would make `classSet` more useful.

**Comment by syranide** [comment]
@flying-sheep Everyone has different opinions on what is useful/necessary/meaningful though, React.addons.* is mostly useful for getting started. `classSet` was originally designed to be compatible with CSS class name mangling, meaning it has to be simple so that each class name is easily discoverable.

**Comment by flying-sheep** [comment]
don’t you agree that the usual case is a combination of fixed classnames (`'disabled'` / `'active'`), dynamic classnames (`this.props.fooClass`), and optionally applied classnames (what `classList` is for)?

**Comment by zpao** [comment]
We're going to get rid of our helper (see #2910). I've said it in a few issues - it's implementation is stuck because it's tied to how we at Facebook statically transform class names. So we can't change the implementation. And since this really is a common request, I'm going to get rid of ours and tell people to use another one. @jedwatson's https://github.com/JedWatson/classnames is what I plan to point at.

**Comment by Aetet** [comment]
What about that:
https://github.com/azproduction/b_

**Comment by flying-sheep** [comment]
ok, great. the first one does exactly what i had as idea anyway :)

**Comment by brigand** [comment]
+1 @Aetet.  BEM and React work very well together; I think that should be linked to in addition to something designed to work with 'normal' class name strings (i.e. classnames).
