### ISSUE TITLE
Checked attribute not realizing in DOM

### ISSUE THREAD

**Issue by colindresj** [facebook/react#3005]
Recently updated to 0.12.2 and a checkbox element hooked up to `this.props` is dynamically updating in the browser. Using the React inspector for Chrome, `this.props.item.isActive` seems to be toggling fine, but for some reason the changes don't propagate into the DOM. Not sure if this is specific to the update, or I've messed something up that I don't realize.

Here's my render function:
```js
render: function() {
  let className = '';
  if (this.props.item.isActive) className = 'is-active';

  return (
    <li className={className}>
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={this.props.item.isActive}
          onChange={this.toggleActive}
        />
        <span>{this.props.item.text}</span>
        <button className="destroy-item" onClick={this.destroyItem}></button>
      </div>
    </li>
  );
}
```

**Comment by cody** [comment]
Your `<input>` is a controlled component that gets the value for `checked` from the props. But the `onChange` event calls a function within the component itself, which usually means it does not alter the props. My guess is using `defaultChecked` will solve your problem:
```javascript
defaultChecked={this.props.item.isActive}
```
I hope this helps, otherwise please give more information. Usually the best way for this is to make a minimal repo case on jsfiddle: http://jsfiddle.net/reactjs/69z2wepo/

**Comment by colindresj** [comment]
I read up on the docs for controlled components and tried using `defaultChecked`, but didn't seem to fix the issue for me. Here's a fiddle: http://jsfiddle.net/wwgfrj6g/

**Comment by cody** [comment]
Thanks for the fiddle. Here I made some changes: http://jsfiddle.net/wwgfrj6g/2/

The main fix was to remove `preventDefault()` from the event handler. Maybe one of the devs can explain why `preventDefault()` breaks it?

**Comment by colindresj** [comment]
Really interesting find @cody. Thanks for the help

**Comment by zpao** [comment]
This is because we actually use the `click` event for checkboxes in our attempt to normalize the change handling. `preventDefault` actually makes the browser not visually update, even if it is actually toggling `checked`. You may actually want to use `stopPropagation` instead, depending on what you're trying to achieve.

Here's the minimal example duplicating what's happening, in pure JS: http://jsbin.com/ludogufaqu/1/edit?js,console,output (fun fact, putting the `node.checked` toggle in a `setTimeout` will make this work).

Now about *why* the browser acts like this, I don't know :/

**Comment by colindresj** [comment]
Very interesting @zpao, thanks for the insight. Good to know that `onChange` for checkboxes actually fires a click event. Is that documented anywhere?

**Comment by zpao** [comment]
No, its an implementation detail that you shouldn't have to worry about, but sometimes it becomes slightly relevant.

**Comment by colindresj** [comment]
Sounds good, thanks for the help

**Comment by jlous** [comment]
I see all these getting closed, yet the problem is real: preventDefault is an established pattern used in many docs, it is legitimate to want the control to remain untouched until the code pushes new state, and people keep hitting this and wasting time on it.  
Couldn't the timeout trick for setting "checked" be internalised in react's input-wrapper?

**Comment by bill-revcascade** [comment]
Yeah, this is pretty annoying. 

If nothing else, this should be added to the documentation. I spent countless time trying to figure out what was going on with my checkboxes, only to finally type the correct phrase into Google to arrive at this issue. I could have saved hours if this had just been mentioned in the docs.

**Comment by willopez** [comment]
I spent almost an hour trying to figure out what the problem was. @zpao I Agree with others on this thread that this should be documented somewhere. Perhaps in a "Gotchas" section of the documentation.

**Comment by bessey** [comment]
Adding my name to the list of developers who wasted an hour debugging this problem!

**Comment by bcmertz** [comment]
Saaammmeeeeee

**Comment by Havret** [comment]
Is it still true that under the hood React uses onClick to trigger onChange event? I'm struggling with checkbox implementation for edge and it seems it does not fire onChange event if checkbox in in indeterminate mode. I have made a workaround using using onClick event handler but it shouldn't be necessary.

**Comment by gaearon** [comment]
Yes I think that's still true.

**Comment by nhunzaker** [comment]
Yep! It's using a click event:
https://github.com/facebook/react/blob/master/packages/react-dom/src/events/ChangeEventPlugin.js#L201-L211

Maybe we should revisit this. Looks like this is for IE8. That might also eliminate some issues with #11541 (but not all).

I'll make an issue for it.

**Comment by Havret** [comment]
It's kind of strange, that this does not fix the issue with checkboxes in indeterminate mode.

**Comment by sstern6** [comment]
Ran into this problem today, just a checkbox in a form.  Had to wrap the setState in a setTimeout to make the toggle work.  Thanks @zpao for recommending that.  Should we open another issue to change the onChange from an onClick and start the discussion?

**Comment by ThorrStevens** [comment]
Having this problem as well:

<img width="1670" alt="screenshot 2019-02-13 at 16 11 16" src="https://user-images.githubusercontent.com/5967956/52722109-48df0800-2fab-11e9-87a3-721c53470fdd.png">

<img width="391" alt="screenshot 2019-02-13 at 16 11 02" src="https://user-images.githubusercontent.com/5967956/52722127-50061600-2fab-11e9-9d54-8a3a2f7130b2.png">

(I'd describe it as`checked` being out of sync in react dom vs. native dom)

My problem only seems to happen for radio buttons though.

React v16.8.1
React-Dom v16.8.1

**Comment by gargantuan** [comment]
For the life of me, I can't understand why this doesn't merit a mention in the docs.

**Comment by nonparibus** [comment]
+1 for a docs reference

**Comment by jedwards1211** [comment]
"what you render is what you get" is the fundamental expectation you get used to when working with React, so it's a catastrophe when it doesn't work out that way...
