### ISSUE TITLE
Make <audio /> and <video /> controllable

### ISSUE THREAD

**Issue by syranide** [facebook/react#3010]
`audio.muted` and `video.muted` can be affected by user interaction when `controls` is enabled. So it makes sense that `muted` should be controlled and an uncontrolled `defaultMuted` should be introduced.

`ReactDOMAudio` and `ReactDOMVideo` needs to be introduced for this.

@zpao Sounds good? Could be a good first bug...

**Comment by spicyj** [comment]
There's a lot of stuff with audio/video which changes due to user interaction; we probably need a real plan here to make something that works well…

**Comment by syranide** [comment]
For posterity, `muted` is the only attribute which can be affected by user interaction. While I agree that it might make sense to make `volume` and other *properties* controllable, it will always pose a problem with server-rendering and is probably not something that React should provide out-of-the-box but should be left to 3rd party components instead.

**Comment by sebmarkbage** [comment]
`play()` `stop()` etc. can also become controllable. Just because they don't have a standard declarative API doesn't mean we can't make one up.

I think the action here is to create completely controllable implementations of `audio` and `video` and see what the surface area is. If it is way too big, we probably wouldn't want to bundle it by default. If it is small and perhaps can have some logic unified with forms in a generic way, it might be worth while.

**Comment by gaearon** [comment]
I remember having a declarative wrapper around audio. One problem I didn't expect was that prop changes wouldn't get reflected on iOS in some cases. Turned out, iOS ignores `play()` calls outside of click/touch event handlers. Something to keep in mind.

**Comment by gaearon** [comment]
Closing as stale. Seeing that ReactDOM size has already become a concern to the community, this should probably stay in userland unless somebody suggests a really compelling/compact implementation.
