### ISSUE TITLE
False warnings for controlled components

### ISSUE THREAD

**Issue by RileyTomasek** [facebook/react#3070]
If you have a controlled component that doesn't have an `onChange` listener, but is being listened to by a parent component, the following warning should not be logged, but currently is: 

'Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `Input`.'

Here is an example: http://jsfiddle.net/cgj0haLc/

**Comment by jsfb** [comment]
In your case, that makes sense.  But suppose someone attaches an onChange listener to the root of their document (for hotkey navigation, or whatever).  It would be easy for a developer to create a form under that top-level component and forget to attach an onChange handler.  Also, in your example, the form is an immediate parent, but if you have formatting code in there, it might be a lot less obvious where the event is being handled.  For these reasons, the warning makes sense.  (It is a dev warning, not a fatal).

There is an easy workaround.  Just attach a no-op change handler that documents what you're doing.  Example:  ` onChange={function(){/* no-op, change handled by the parent component (Form) */}}`

Because the warning is still useful even when the change event is being handled by the parent, and there is an easy workaround that also helps give the developer a nice place to document what they're doing.  Closing issue.

**Comment by RileyTomasek** [comment]
That makes sense. Thanks for suggesting a workaround. I just have a really big form and the warnings were drowning out any real warnings.
