### ISSUE TITLE
this.forceUpdate(); crashes when a component is not mounted

### ISSUE THREAD

**Issue by janpaul123** [facebook/react#3071]
Not sure if it is a bug or just general confusion. Tried only with 0.12.2, not with master.

`this.forceUpdate();` crashes when a component is not mounted, which in itself makes sense, I'd say. However, if you call `this.forceUpdate()` directly in `componentWillMount`, it *doesn't* crash, which suggests that it's OK to do (just as `setState` is OK to call there).

This happens if you use a Flux-like architecture but don't use the `componentDidMount `/`setState` combination (as Flux suggests) but `componentWillMount`/`forceUpdate`.

The error that you get is "Invariant Violation: receiveComponent(...): Can only update a mounted component."

This example shows the problem: http://jsfiddle.net/8s9we7gj/3/

**Comment by kylewiedman** [comment]
I think this is because you are binding the parent to forceUpdate() in your props which doesn't have a representation yet because the all of it's children may not be rendered and doesn't have a lifecycle state (_compositeLifeCycleState: null).  Notice that if you just pass the parent in as a prop you also can't use setState() on the parent either for the same reasons.  It is strange that if you do this that this.props.parent.isMounted() is considered true, when it's actually not. --> http://jsfiddle.net/7ne3ewq5/2/

Where as when you call forceUpdate() on the component itself within componentWillMount() it has already run the lifecycle methods on the children and has a representation. (_compositeLifeCycleState: "Mounting").  Pretty sure calling this.forceUpdate() here does nothing because it's not rendered yet; you can still manipulate the state and props and have them rendered correctly.

**Comment by janpaul123** [comment]
Well, but the `componentWillMount` callback of `Outer` is called before the one of `Inner`, which you can easily verify with some alerts or so. So it doesn't make sense that first you can call the outer `forceUpdate` in the outer `componentWillMount`, but a few moments later not any more, in the inner `componentWillMount`.

**Comment by jsfb** [comment]
Take a look at https://github.com/facebook/react/issues/2787

The TLDR: Calling setState() or forceUpdate() on an not-mounted component is a code smell that strongly indicates you are leaking objects prematurely or are not cleaning up your references after they've been removed.  This throws an invariant violation in an attempt to force you to clean up your code.  In practice, this is probably too aggressive.  There is discussion of downgrading this invariant to a warning or maybe even a no-op.

While not technically identical, I think this issue is sufficiently related to https://github.com/facebook/react/issues/2787 to mark it as a duplicate.

**Comment by janpaul123** [comment]
Yes, I'd agree to solving this problem by not allowing `forceUpdate` to be called in `componentWillMount` *at all*. :+1: Thanks!
