### ISSUE TITLE
Test Utils clicking on submit button does not trigger form onSubmit

### ISSUE THREAD

**Issue by DelvarWorld** [facebook/react#3141]
See:

http://jsfiddle.net/kb3gN/9630/

    <form onSubmit={ this.onSubmit } ...
        <input type="submit"

   ...

    TestUtils.Simulate.click( view.refs.submit.getDOMNode() );

Calling the click function will trigger the button's onClick, but not the form submit action.

Only the [undocumented](http://facebook.github.io/react/docs/test-utils.html) `Simulate.submit` will trigger the form.

Is this a bug in the onSubmit implementation in React, or the test utils?

**Comment by sdemjanenko** [comment]
+1

**Comment by zpao** [comment]
This is actually just a disconnect between expectations and the reality of working in the browser :/.

Unfortunately simulating events is not quite the same as what a browser does when you click on a submit button.

Simulating click is essentially the same as this:

```js
var view = React.render(<Hello/>, document.body);
var button = view.refs.submit.getDOMNode();
var evt = new Event('click', {bubbles:true, cancelable:false});
button.dispatchEvent(evt);
// "  ... onclick called"
```

This creates a native `click` event and dispatches it to the button. However, no `submit` event is fired.

If you wanted to test this *exactly* like a browser would behave, with trusted events and everything, then you need to run your tests in a browser and probably use something like selenium or webdriver to more accurately get results. Otherwise you'll want to simulate click and submit separately.

**Comment by iamdustan** [comment]
Agreed. I think it is fair to expect that something named ReactTestUtils event simulation would tie into reacts (potentially browser-environment aware) event model and that this would work.

Though considering doing so adds a *lot* of complexity to ReactTestUtils. E.g. Simulating a [Return] key press on an input element would also trigger a parent form’s onSubmit handler.

Is this worth adding to the ReactTestUtils docs?

**Comment by henrik** [comment]
In Chrome, I could work around this with `$(".my-submit-button").click()`, but in Firefox that didn't cause the form to submit.

And as described above, simulating the click with React doesn't cause the form to submit in either browser.

**Comment by paulief** [comment]
+1
