### ISSUE TITLE
Changelog for beta releases

### ISSUE THREAD

**Issue by paglias** [facebook/react#3155]
Actually the conly information i could find on version 0.13 was this blog post http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

Could you add release notes in the Changelog for development releases?

**Comment by RnbWd** [comment]
I just spend 5 minutes looking through the git-repo-tree, so take what I say with a grain of salt, but it looks like they removed a few internals (merge, for example), which had been marked as deprecated in v0.12. Changed the license verbage, maybe added / removed a few warnings that appear in development mode. Documentation, lots of that, and maybe some build-system optimizations for the repo itself? Personally, I speculate that it'll be released very soon and somebody's writing a blog post as we speak explaining wtf will happen when these major changes take place. I'm an outsider, just speculating. I literally have no idea when it'll be released officially, but it doesn't look like they're making any significant changes.

**Comment by rickbeerendonk** [comment]
@paglias I am sure you'll find the "Umbrella 0.13" issue interesting: https://github.com/facebook/react/issues/2809

**Comment by RnbWd** [comment]
I concur with @rickbeerendonk , and I actually just went through all the files up to when beta-1 was released, and it's quite a bit more than I had realized. Only 3/12 umbrellas have been checked, so it might not be released immediately. It depends on how important those issues are and how fast it'll take to patch them

**Comment by joshbedo** [comment]
I also think this would also be great! I started this project [React.Upgrade](https://github.com/joshbedo/React.Upgrade) which is a python script built off of codemod which goes through old properties/methods and asks the user if they want to replace it with the new property/method. It would be good if i knew all of the updates so users could seamlessly upgrade without worries. I'm still working on the `createFactory` update and open to contributions :) 

I think the warnings are a good idea but they're very ambiguous.. it tells you something is wrong but not specifically where... I know as i transition to the new version of React (0.10 - 0.12) that i need to use `createFactory` for exporting classes but it's not indicative of where that change needs to happen.

**Comment by jsfb** [comment]
@RnbWd Sorry, there was some sort of github glitch that caused only 3/12 boxes to be checked.  We've fixed the umbrella issue to accurately reflect our progress to date.  You are correct that the majority of the changes are to the internals rather than public API (we try really hard to minimize public-api churn).  The biggest changes to public API refs (still figuring them out) and es6 classes documented here: http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html

@joshbedo Runtime error messages generally suck, but such is life when you're working with a dynamic language like javascript; we try to have them be as useful/detailed as possible!  With regards to createFactory... it's not that we "introduced" createFactory so much as we "exposed" createFactory, which was previously bundled into createClass.  This change has several advantages including a simpler API for ES6 classes (which are the future), better support for static methods, better support for auto-mocking, and better language interoperability.  We thought long-and-hard about this change, and documented the decision/ramifications here: https://gist.github.com/sebmarkbage/d7bce729f38730399d28  Hope that clears up any misgivings you may have had about the factory change :).

**Comment by RnbWd** [comment]
I'm anxious about this release because I'm in the process building some new components that are rather complex. I'm already using es6 (babel) for the flux implementation ([alt](https://github.com/goatslacker/alt)), and I know that [fixed-table-component](https://github.com/facebook/fixed-data-table) is capable of handling the upgrade. It seems logical to embrace the next es6 class syntax of React, its fits well with my current work flow. I'm hesitant to start writing it in v0.12, especially if it'll be depreciated, and it's hard to use v0.13 until it's officially released due to peer dependencies in other libraries. So... I'm just wondering, is it worth the process of migrating now? I know it's experimental beta, but I recall previous beta's lasting for 2-3 days without much change between beta / official, but this release seems like a more ambitious endeavor, probably the most substantial release in terms of modifying API's I've seen since using React.

**Comment by zpao** [comment]
We're not going to do a changelog for betas this time around but we'll consider it moving forward.

@RnbWd to answer the timeline question - we're approaching RC very soon (which is where we've gone very short time between RC and final, we haven't actually done betas in the past). The other part of this is that you don't need to start using ES6 classes so you could write something for 0.12 that is forward compatible very easily.
