### ISSUE TITLE
Warning for: PropTypes.object.isRequired when prop is `null`

### ISSUE THREAD

**Issue by TrySpace** [facebook/react#3163]
As `PropTypes` is about the 'type' of prop, `null` is an empty object, but still a type of object, practically.

But still it warns: 

     Warning: Required prop `profile` was not specified in `Element`. Check the render method of `OtherElement`.

I don't think this is supposed to happen.

It stops warning after it is not `null` anymore. I'm pretty sure it should only warn when it is `undefined` ?

**Comment by syranide** [comment]
`null` is the equivalent of no value and not an object (empty or otherwise). If you don't want it to warn for `null` then don't make it required, it has the same effect. Testing for the presence of a key is not something I would recommend.

**Comment by jsfb** [comment]
I agree.  I can't think of very many use cases where you would want to force a user to specify a value, but would be willing to accept null as a valid value.  For practical purposes, the isRequired warning for null is sensible and expected behavior.

**Comment by ptim** [comment]
related: https://github.com/facebook/react/issues/2166
(this issue still shows up prominently in search results)

**Comment by wardpenney** [comment]
A common use case I see is React rendering a component before an API call for data has finished. The first render would render, for example, a list of items (`items: null`). Then the API call finishes, and now `items` is populated with an array.

**Comment by patrick-ivers** [comment]
If React warns when a required prop is set to `null`, why don't defaultProps override the `null` like they do for `undefined`? Surely the behaviour should be consistent.

**Comment by Noitidart** [comment]
I am trying to do `PropTypes.oneOfType([null, PropTypes.object]).isRequired`, so either null or an object, is this not possible right now?

**Comment by GabrielDelepine** [comment]
According to the [CHANGELOG](https://github.com/facebook/react/blob/master/CHANGELOG.md#1540-november-16-2016), since `15.4.0` it's suppose to be possible

**Comment by misantronic** [comment]
Actually, it's the opposite in 15.4.0: `Required PropTypes now fail with specific messages for null and undefined.`

I am also facing this issue.
@Noitidart 's workaround is not working for me. It throws an error saying:
`Failed prop type: The prop `value` is marked as required in `Select`, but its value is `null`.`

I find it really useful to require a property but also allow null values.

**Comment by farzer** [comment]
yeah, i met this issue. and i try this:

```
PropTypes.oneOfType([
  PropTypes.oneOf([null])
])
```

to solve temporarily

**Comment by jharris4** [comment]
+1 for allowing `null` somehow.

We have a use case where our configuration is loaded via JSON, and there are several label configuration options that specify a string that should be displayed, something like this:

```
{
  "title": "my title"
}
```

So when no title should be displayed, we use `null` to denote that case:

```
{
  "title": null
}
```

(Adding parallel `hasTitle: false` would be prohibitive as we have dozens of these settings.)

For JSON content, using null is a very useful way to distinguish between not defined (`undefined`) versus deliberately omitted (`null`).

**Comment by hzhu** [comment]
I'm not sure of the pros and cons of React allowing `null` in the propType checks, but like @jharris4 , I have a component that is backed directly from data loaded from an API. For one of the keys, the value is a `string` or `null`.

I wanted to do 
```
propTypes = {
  delivery: oneOfType([string, null]),
}
```

How should one handle this case when React propType does not allow for `null`? Shall I just leave this particular prop unchecked?

**Comment by jquense** [comment]
you can allow null, set the propType to not be required, since it's not required :P

**Comment by hzhu** [comment]
@jquense thanks that's super helpful! I had deleted my previous comment because this SO [answer](https://stackoverflow.com/questions/37842868/how-can-i-declare-a-proptype-corresponding-to-a-nullable-number) said the same thing.

**Comment by jharris4** [comment]
@jquense you can allow null AND undefined, but not one or the other.

That's the whole problem! Javascript provided these 2 different constructs for a reason, so forcing everyone to treat `null === undefined` for PropTypes is an artificial limitation.

Just because I want a PropType to explicitly allow null does not mean that I should have to allow undefined as well. They are two distinct cases, and the language designed them that way on purpose.

I have a PR to work around this oversight here: https://github.com/facebook/prop-types/pull/90

**Comment by binki** [comment]
I want to disallow `undefined` because that means there is a typo and allow `null` because that means that the caller explicitly passed in `null`. That’s the point of this issue. I understand that this issue is closed because it is recommended to just switch to flow, which I will look into.

**Comment by puiu91** [comment]
@binki One way to allow `null` but not `undefined` is to use your own PropType validator function. 

In the example below, only  `null` or `string` is permitted. The PropTypes library uses `typeof` internally to check for strings, so I did the same. One benefit is that you can move this function outside your component and call it as needed. 

```jsx
static propTypes = {
  id: PropTypes.number.isRequired,
  email: function(props, propName, componentName) {
    const propValue = props[propName] // the actual value of `email` prop
    if (propValue === null) return
    if (typeof propValue === 'string') return
    return new Error(`${componentName} only accepts null or string`)
  }
}
```

I guess this solution deviates from the intent of the PropTypes library - the reason I say this is due to the code below from the PropTypes library at https://github.com/facebook/prop-types/blob/master/factoryWithTypeCheckers.js#L189.

Before actually validating, a quick check is performed wherein properties set with isRequired automatically throws an error if the property value is `null`. In other words they believe that a required property being null is erroneous whereas I consider it a valid use case to have have required nulls.

```js
if (props[propName] == null) {
  if (isRequired) {
    if (props[propName] === null) {
      return new PropTypeError('The ' + location + ' `' + propFullName + '` is marked as required ' + ('in `' + componentName + '`, but its value is `null`.'));
    }
    return new PropTypeError('The ' + location + ' `' + propFullName + '` is marked as required in ' + ('`' + componentName + '`, but its value is `undefined`.'));
  }
  return null;
} else {
  return validate(props, propName, componentName, location, propFullName);
}
```

**Comment by Findiglay** [comment]
I agree with @jharris4 for the reasons stated. `null` is not the same as `undefined`. It is standard to use it as a placeholder.

From Mozilla Developer Network:
> The value null represents the intentional absence of any object value.

> The value null is written with a literal: null. null is not an identifier for a property of the global object, like undefined can be. Instead, null expresses a lack of identification, indicating that a variable points to no object. In APIs, null is often retrieved in a place where an object can be expected but no object is relevant. 

null should be allowed, at least through `PropTypes.oneOfType(null, PropTypes.string)`.

**Comment by brandondurham** [comment]
@jquense — Removing `isRequired` means you should probably set a default. Does this mean you’d now be setting a default for the initial value in the component _and_ in the reducer, all to avoid allowing `null` as a value for a prop?

**Comment by erfanio** [comment]
I have a bunch of `value || ''` in my reducers cause they _can_ be null but that completely intentional... and apparently empty string makes the problem go away...
@puiu91 has a good work around for now... since the core react team seems to not care about how the community feels about this.

**Comment by ianmartorell** [comment]
I also agree there should be a standard way to accept `null` as a value, for the same reasons @jharris4 and @Findiglay stated, but this is not the place to continue the discussion anymore. Not only is this issue closed, but it belongs to [facebook/prop-types](github.com/facebook/prop-types). I'm following the pull request here facebook/prop-types#90.

**Comment by rbeer** [comment]
+1 for adding null, at least as its own prop-type, so one can do:

```js
static propTypes = {
  canBeNull: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.null
  ])
}
```
`null` is also from my understanding not equal to undefined. Reasoning has been stated. `null` tells you that there eventually will be an Object, in place of that `null`.
Let's take the simple usecase of determining whether to show some "Login" Button. You might have a simple `user` object in your state or store. If `user` is `null`, the user hasn't logged in yet. Once he has, the `user` field is an Object with that user's data.

`null` is different.

**Comment by Keltin42** [comment]
Bump.  Still running into this today.  Would be great to have builtin support for something like:

myObj: PropType.object.isRequiredOrNull   :)

**Comment by Noitidart** [comment]
I think the priority on this is super low. Flow is the recommended way tog go. http://flow.org/

**Comment by Marujah** [comment]
PropTypes.oneOfType([() => {return null}, PropTypes.string]).isRequired works for me

**Comment by jharris4** [comment]
@Marujah your snippet is not correct.

Try passing null to the component, and you'll see you'll get the warning:

```Warning: Failed prop type: The prop 'theProp' is marked as required in 'TheComponent', but its value is null.```

The touble is that the isRequired gets evaluated FIRST and it will never let null or undefined values through.

The PR to prop-types to fix the issue is linked above if you're interested.

**Comment by Marujah** [comment]
Oh indeed! retested again you'r right

**Comment by pushitreal** [comment]
Requiring that a value or null must be specifically provided should absolutely be allowed via PropTypes.

Here is the use case I'm running into. We have some callbacks that are required by 90% of our selectors. The few that don't need them are very specific use cases. We have some new developers that are constantly forgetting to provide all of the usual callbacks. 

I want to force all uses of these Components to make the *conscious* decision to not include specific callbacks, rather than someone just forgetting a few props.

Yes, we can hack in our own more specific checks via flow, but that splits our props validation into two places, and is rather unintuitive for someone glancing at the propTypes definitions.

**Comment by ShepherdJerred** [comment]
Just wanted to add my use case here. I have a redux store with data along with when that data was fetched, if there was an error, etc. My component requires an 'error' prop (so it can display the error to the user if data couldn't be fetched), which is null when the data loaded successfully, but populated when there is an error.

**Comment by Aliance** [comment]
I was implementing InputNumber component (wrapper for `<input type="number">`), so I had `propTypes` for my prop `value` – `PropTypes.number.isRequired`, and when I used my component, I always passed it property. But today I need to pass there a nullable by default link to value, and my component adds a warning. The only decision I could imagine is to change `propTypes` for my prop `value` to `PropTypes.oneOfType([PropTypes.number, PropTypes.string])` and set the `defaultProps` as null. But I feel it's not the correct one because input type=number should work with numbers only.

**Comment by scottjason** [comment]
Bumping this thread for the same exact use case as @MrToph .

Also, @jharris4 is absolutely correct in that `undefined` and `null` should not be treated equally- it creates a constraint on what we can do with Proptypes.

**Comment by wbednarski** [comment]
> I am trying to do `PropTypes.oneOfType([null, PropTypes.object]).isRequired`, so either null or an object, is this not possible right now?

It expects a function:`Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received null at index 1.`

So, you should supply a function, like:

```
PropTypes.oneOfType([
  () => null,
  PropTypes.object
]).isRequired
```

**Comment by davidje13** [comment]
Having just encountered this bug, I've written a convenience function to work around it:

```javascript
function nullable(subRequirement) {
  const check = (required, props, key, ...rest) => {
    if (props[key] === null) {
      return null;
    }
    let sub = required ? subRequirement.isRequired : subRequirement;
    return sub(props, key, ...rest);
  };
  const fn = check.bind(null, false);
  fn.isRequired = check.bind(null, true);
  return fn;
}
```

Usage:

```javascript
static propTypes = {
  someCallbackFunction: nullable(PropTypes.func).isRequired,
};
```

It's possible (but rather pointless) to use `nullable` without `isRequired`. The reason I make it compatible with `isRequired` is so that it will work with the `react/require-default-props` eslint rule.

My use-case is a series of components conforming to a common API, wrapped by a single component which handles callbacks. `null` callbacks mean 'read only', so the wrapper component sometimes intentionally passes `null`s. At the same time, it's important that every property is passed to the subcomponents to ensure that if a new property is added, it doesn't get missed. I also don't want to provide `defaultProps` of null for every component which conforms to this API; as far as they are aware, the caller must have specified a value.

**Comment by davidje13** [comment]
I took the helper I wrote before and put it in a package along with a bunch of tests to prove correctness:

```
npm install --save git+https://github.com/davidje13/prop-types-nullable.git#semver:^1.0.0
```

Usage:

```javascript
import PropTypes from 'prop-types';
import nullable from 'prop-types-nullable';

[...]

static propTypes = {
  thing: nullable(PropTypes.string).isRequired,
};
```

**Comment by raviindorey** [comment]
This warning is not a bad thing if you really want to enforce the right shape of your property.
However, if you really want to use `null` in beginning then my workaround is to not use `isRequired`.
If you have initial value as `null` which transforms into some shape then its better to use `defaultProps` and drop `isRequired`. This will get rid of the warning.

```javascript
MyComponent.defaultProps = {
  thisChanges: null,
};

MyComponent.proptypes = {
  thisChanges: Proptypes.shape({
    oneProp: PropTypes.string,
    twoProp: PropTypes.string,
  }),
};
```

**Comment by LukaGiorgadze** [comment]
New solution: ``PropTypes.oneOfType([PropTypes.object]).isRequired``

**Comment by gangeshRoy** [comment]
I am getting  error.
 how to fix.



 WARNING in ./~/prop-types/prop-types.js                                                                                 Critical dependencies:                                                                                                  1:482-489 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.                                                                                 @ ./~/prop-types/prop-types.js 1:482-489

**Comment by gugol2** [comment]
> > I am trying to do `PropTypes.oneOfType([null, PropTypes.object]).isRequired`, so either null or an object, is this not possible right now?
> 
> It expects a function:`Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received null at index 1.`
> 
> So, you should supply a function, like:
> 
> ```
> PropTypes.oneOfType([
>   () => null,
>   PropTypes.object
> ]).isRequired
> ```

Actually I had a error because of that 'isRequired' at the end, being null and required at the same time is not compatible...
This is what worked for me:

```
PropTypes.oneOfType([ 
	PropTypes.string.isRequired, 
	() => null 
])
```

**Comment by davidje13** [comment]
@gugol2 please note that what you have written will just disable type checking entirely (you can now pass a number to that prop, or `undefined`, or anything); the function you provide should return `null` if validation succeeds and non-`null` if it fails.

If you want to go that route you would need something more like:

```js
PropTypes.oneOfType([
  PropTypes.string.isRequired,
  (props, key) => props[key] === null ? null : 'Not null'
])
```

Of course you could pre-define the nasty-looking helper function:
```js
const nullable = (props, key) => props[key] === null ? null : 'Not null'

// ...

PropTypes.oneOfType([PropTypes.string.isRequired, nullable])
```

But I'd recommend using the [package I created](https://github.com/davidje13/prop-types-nullable) (or the [code behind it](https://github.com/facebook/react/issues/3163#issuecomment-470307646)) because that way you get to put `.isRequired` at the end of the line, which makes it compatible with linting rules.

**Comment by benatkin** [comment]
IMHO this is correct behavior but it ought to be documented.

**Comment by adil-waqar** [comment]
> A common use case I see is React rendering a component before an API call for data has finished. The first render would render, for example, a list of items (`items: null`). Then the API call finishes, and now `items` is populated with an array.

Any best way to handle this? I want this prop required BUT it's null before I get it back from the API.

**Comment by gugol2** [comment]
> ```js
> PropTypes.oneOfType([
>   PropTypes.string.isRequired,
>   (props, key) => props[key] === null ? null : 'Not null'
> ])
> ```

@davidje13 I encounter a little problem with this approach. Coverage testing has 1/4 case that is never covered.

Let's say I have a component Login that only has one prop 'name' that can be null or a string required:
```
const Login = ({name}) => {
  return <div>{name}</div>
} 
```
So its proptypes are:

```
Login.propTypes = {
  name: PropTypes.oneOfType([
    PropTypes.string.isRequired,
    (props, key) => (props[key] === null ? null : 'Not null'),
  ]),
};
```
When I test this component I really only have 2 scenarios, null OR a required string.
```
render(<Login name={null} />
render(<Login name={'anyName'} />
```
But coverage tells me my test has only 75% coverage.
I wonder what will be the official approach for this.

**Comment by davidje13** [comment]
It sounds like your missing test case is the one where it fails the prop check? i.e. if you pass a number or undefined or something else it shouldn't have.

**Comment by gugol2** [comment]
> It sounds like your missing test case is the one where it fails the prop check? i.e. if you pass a number or undefined or something else it shouldn't have.

No, it is not that. 

Passing undefined does not expand the coverage.
And I can't pass a number anyway, it is not an allowed value.

I am not able to cover that case.

**Comment by LaxmanPache123** [comment]
![image](https://user-images.githubusercontent.com/97151206/201030900-ccf795e4-a845-48bb-8003-7b8ca130a4ac.png)
 i validated this proptype but still getting error
![image](https://user-images.githubusercontent.com/97151206/201031357-7a349367-0cf9-44bb-8ede-c8de309e0753.png)

**Comment by mahawar0709** [comment]
Do we have any way for adding null and isRequired  to propTypes?
activeProject: PropTypes.oneOfType([PropTypes.object]).isRequired   <-----I want to add null too as one of the type

**Comment by LaxmanPache123** [comment]
> Do we have any way for adding null and isRequired to propTypes? activeProject: PropTypes.oneOfType([PropTypes.object]).isRequired <-----I want to add null too as one of the type
you can try using -

activeProject: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.oneOf([null])  // Allow null
  ]).isRequired,

**Comment by LaxmanPache123** [comment]
> ![image](https://user-images.githubusercontent.com/97151206/201030900-ccf795e4-a845-48bb-8003-7b8ca130a4ac.png) i validated this proptype but still getting warning ![image](https://user-images.githubusercontent.com/97151206/201031357-7a349367-0cf9-44bb-8ede-c8de309e0753.png)

This issue is resolved . in data i am getting Array of objects
allOverview: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.object])) .isRequired

**Comment by benatkin** [comment]
I think the problem is nicely defined here: https://github.com/facebook/prop-types/issues/57#issuecomment-315094153

**Comment by benatkin** [comment]
Looks like it was close to a solution but it didn't quite make it: https://github.com/facebook/prop-types/pull/90#pullrequestreview-838856928
