### ISSUE TITLE
[Compiler Bug]: wrong check with all `props` object (`$[0] !== props`) when accessing the function from the `props` object and calls it, e.g. `props.reportBug()`

### ISSUE THREAD

**Issue by dimaMachina** [facebook/react#31763]
### What kind of issue is this?

- [ ] React Compiler core (the JS output is incorrect, or your app works incorrectly after optimization)
- [ ] babel-plugin-react-compiler (build issue installing or using the Babel plugin)
- [ ] eslint-plugin-react-compiler (build issue installing or using the eslint plugin)
- [ ] react-compiler-healthcheck (build issue installing or using the healthcheck script)

### Repro steps

I found an issue with react-compiler, which makes fails this test https://github.com/graphql/graphiql/blob/8092f100ae62710bece1666589eda0455dc04009/packages/graphiql/src/GraphiQL.spec.tsx#L76-L84

As you can see function `introspect` contains reference to `props.schema`, `props.fetcher` and `props.onSchemaChange` but the react-compiler simplified it to `$[13] !== props` which is wrong!

For now, I fixed this with this commit: https://github.com/graphql/graphiql/pull/3821/commits/3ecae05a0472494fa05f45632edb63de89a2a4fe by avoid having `props.something...` inside body of `introspect` function

I hope this will be prioritized and fixed soon, friendly ping [gsathya](https://github.com/gsathya)

### How often does this bug happen?

Every time

### What version of React are you using?

from playground

### What version of React Compiler are you using?

from playground

**Comment by dimaMachina** [comment]
and here is minimal reproduction https://playground.react.dev/#N4Igzg9grgTgxgUxALhASwLYAcIwC4AEwBUYCAogGaUJyEC+BlMEGBAOiDAgIZ2cBudgDsRCAB458TKMLpoIwggGU4ACwQYeAYUV4JeAAosAbmgAmCGAAosLLGACUREQQJxFYQsFduCaYTwWMCxaPAVhAEUoKwBPABpfNwCgiBCwiOi4gDkeDAREpT8U4ND5RSyYWOUeYTBlKAAjMDgYNCxwz0K3RgBeEjIASUDSjIqYqutHISKPOsIStLLCfqmCXoA+FyLkygJbezAAOhaNLXXe-uEoABsb5x8dv248WGEZvwJ6JIIeMFi5DI5J0lDQ8Ophql0uVhAARHh4HhrR6fNxzLxMBDgtTrTHYqwAJSxbwAKhBjKw0GRrD9PnYIA4jmD1FZrCjUZ8AI4TWLIfwjJZjKI87ocvwMqwIiK5fJ8xbQkGVWIygq0vz0Ryiz7TERqtB7awAQipFIwVIQ1mZakcDzVbhebw+qO+oiebhuWII3DAtxWvwA7jw0IQrTM9Qbvb6LldbvdtmL3J4Q1j1AAmXFWwnEmDCMmm800t2o+mMzM2dkJtzcuJygUKzI8mp1BrNVrtEFgLWViUwKWKFW1qHLBs5PKqoufDVd7VOjn6-bGsD56lW1M2+OVvBqFj+gjCBC78gwFg2O2ozgAMRTGhgBHMFj3EEIDpzvwIy4QTFw-KHQqOnGnVEdQnL4z0jG4-R4QNgzxNNZ3VcN9nAvAjnMBEeFtECXyUZDUPQ+CejVdFnwQEJPAQZQggCABzdYzzwWJQggPZkOjDhwCo4RqM4AgAH4vVIqM+UoXAtDwIkfQg6xkOAyddSeK1IVGGF4URKYji3BBhGsax5WHRRVIw9YtgrYoDRLY5FFUM4dDUWpqIQTCEwso4rJZLRtDsriLX3f1rM0DCCNAp4NSdegnVIChqDCHTnE2DdkjrZYpjC+ICAAbT0sIAF1gN8bD9h+AAefyPL0AwjgpMxLFvEweBuGJemAOqGoQegNjVYAXPUNAbnMbhhBdT4ioAelKnRyvEFCqosKwOqKYCXRAeggA

**Comment by dimaMachina** [comment]
[I think even this is wrong](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAKgmDgBQAOME1YAlEcADrFEbb6FEBGAQxiVmbDkSK16YAHQBbAJ4AlBGgQxsCAMoALaABsAJgCEEAYR0I4AawSGRAbnYSAvk44wEOWMQA8fKBwcXkIzfTwbAF5gQRgXIgB6AD53F3YQFyA)

```js
function Test(props) {
  function bar() {
    props.myRefernceShouldBeChecked();
  };
  return <button onClick={bar} />;
}

```

compiled to `if ($[0] !== props) {` but should `if ($[0] !== props.myRefernceShouldBeChecked) {`

I think this is an issue when you have `props.someFunction()`, [because is right](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAKgmDgBQAOME1YAlEcADrFEbb6FEBGAQxiVmbDkSJxCkADYIAdDIgBzGnQbyAtgE8ASgjQIY2BAGUAFtBkATAEIIAwuYRwA1gmuN2EgL4BubyIYBBxYYgAePigcHF5CBxk8NwBeYEEYHyIAegA+AMwfdhAfIA)

```js
function Test(props) {
  function bar() {
    console.log(props.myRefernceShouldBeChecked)
  };
  return <button onClick={bar} />;
}
```

compiled to `if ($[0] !== props.myRefernceShouldBeChecked) {`

**Comment by dimaMachina** [comment]
[Deep access of `props`](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEUYCAKgmDgBQAOMEdYAlEcADrFEwI6zEabALwA+dlyJSiDJmAB0aCBHkAjAIYx5AYQASAUW0BpAPoBZfUMlEAvgG4uNriBtA) should be fixed as well:

```js
function useTest(props) {
  return () => {
    props.foo.bar.CHECK_ME()
  };
}
```

compiled to `if ($[0] !== props.foo.bar) {` but should `if ($[0] !== props.foo.bar.CHECK_ME) {`

**Comment by dimaMachina** [comment]
> [!note]
>
> For anybody who wants to prevent this bug until react-compiler is fixed, here is ESLint selector for [no-restricted-syntax](https://eslint.org/docs/latest/rules/no-restricted-syntax) rule `CallExpression Identifier[name=props]`. And[ ESLint playground](https://eslint.org/play/#eyJ0ZXh0IjoicHJvcHMub2hOb28oKVxucHJvcHMuZm9vLm9oTm9vKCkiLCJvcHRpb25zIjp7InJ1bGVzIjp7Im5vLXJlc3RyaWN0ZWQtc3ludGF4IjpbImVycm9yIix7InNlbGVjdG9yIjoiQ2FsbEV4cHJlc3Npb24gSWRlbnRpZmllcltuYW1lPXByb3BzXSIsIm1lc3NhZ2UiOiJEbyBub3QgY2FsbCBmdW5jdGlvbnMgb24gcHJvcHMgb2JqZWN0IHdpdGggZG90IG5vdGF0aW9uIn1dfSwibGFuZ3VhZ2VPcHRpb25zIjp7InNvdXJjZVR5cGUiOiJtb2R1bGUiLCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19) with it

**Comment by josephsavona** [comment]
Thanks for posting! What's happening here is that the compiler is aware of prototypes, and has to assume that if code accesses only `object.method()`, that `obj.method` may not always change when `object` does. Consider:

```js
const array1 = [];
const array2 = [];
array1 === array2; // false
array1.push === array2.push; // true!
```

This is because `array1.push` and `array2.push` both evaluate to `Array.prototype.push`, ie the same function. 

Thus, in some of the examples you provided it is not safe to take the more precise dependency. Consider your last example:

```js
function useTest(props) {
  return () => {
    props.foo.bar.CHECK_ME()
  };
}
```

Here, `props.foo.bar` is the receiver, and this will look up `CHECK_ME` on the prototype chain. Per the above example with array push, there's no guarantee that `props.foo.bar.CHECK_ME` will change when `props.foo.bar` changes — the compiler is correctly taking `props.foo.bar` as the dependency. A few of the other examples you provided fall into this category.

Note that if you know that the function is not a method (doesn't depend on the `this` receiver), you can manually rewrite to 

```js
function useTest(props) {
  return () => {
    const CHECK_ME = props.foo.bar.CHECK_ME; // now the compiler will depend on this full path
    CHECK_ME();
  };
}
```

However, there's still a catch here because inside a function expression, the compiler can't know that `props.foo.bar` is non-nullable, so we may have to be pessimistic and take a less precise dependency. We do a bunch of analysis (courtesy of @mofeiZ) to infer non-null paths and take the most precise dependency that is safe though.

That brings us to the first example, which we _can_ optimize. In the general case we don't know which methods are prototype methods that won't change w the object. But `props` is an object that the user cannot construct themselves — we know that `props.method()` is _not_ looking up something on the prototype, because that makes no sense! So specifically when props is the receiver, we can safely rewrite `props.method()` to just `const temp = props.method; temp()`, allowing us to take a dependency on `props.method`. I've implemented that specific optimization in #31771.

**Comment by dimaMachina** [comment]
@josephsavona Huge thanks for the explanation, reactive fix and your amazing work on the react compiler.

For my side, I am always happy to share the reproduction of issues which I find why optimizing React app 👍

**Comment by josephsavona** [comment]
We appreciate the concise examples, this made it really easy to narrow down. I’m going to close since we’ve landed the fix.
