### ISSUE TITLE
Looking for a good way to test React

### ISSUE THREAD

**Issue by joshbedo** [facebook/react#3178]
Hey all! So i'm currently looking into different solutions for testing React and exploring `jsdom` with `mocha` does anyone have any good suggestions or repos? I've read quite a few articles and everyone seems to have a different way of doing it. I'm wondering if there is a good solid way that will be compatible with newer releases of React. 

Thanks!

**Comment by iamdustan** [comment]
http://facebook.github.io/jest/ is probably your best bet. It’s built on top of `jasmine`. I’m pretty sure it uses `jsdom`.

It’s what facebook and react itself uses so you can expect it to continue working with react in the future.

**Comment by swapwarick** [comment]
Sure it is.

On Wed, Feb 18, 2015 at 9:14 PM, Dustan Kasten <notifications@github.com>
wrote:

> http://facebook.github.io/jest/ is probably your best bet. It’s built on
> top of jasmine. I’m pretty sure it uses jsdom.
>
> It’s what facebook and react itself uses so you can expect it to continue
> working with react in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react/issues/3178#issuecomment-74886093>.
>



-- 
Swapnil Netankar

**Comment by sairion** [comment]
I am currently using Karma + mocha + webpack + sinon to building tests. The result is (still working on tho) not that bad and using Karma plugins I can actually test on browsers and is easily debuggable compared to Jest. However, since I am using a lot of libs and tools, sometimes it makes me wrap head around when Karma or webpack causes unknown problem (most of problems come from webpack or webpack loaders; For instance, I am not currently able to use `eval` devtools mode because test fail with an unknown message)

**Comment by jsfb** [comment]
Correct, we use jest, which is built on top of jasmine.  Our jest configuration calls jsdom for simple tests and phantomjs for more complex tests.  Obviously your best bet is to run inside a real browser, but that's also the most difficult to setup.  We are not strongly opinionated about which testing environment you should use; go with whatever best meets your needs.

Closing this issue since it isn't a 'bug in react', which basically takes it off our radar.  Feel free to continue the conversation on this thread, or move the discussion to StackOverflow.

**Comment by zpao** [comment]
Jest always uses jsdom, never phantomjs. Our React testing runs the same set of tests in both environments though (as well as in a browser for local debugging and sauce labs). That's obviously more work than one would want. At FB we primarily rely on jest (with some webdriver and other tests) so that's our strongest suggestion.
