### ISSUE TITLE
Changing an array in a state does not update component

### ISSUE THREAD

**Issue by binarykitchen** [facebook/react#3204]
```coffee

  ...

  getInitialState: ->
    selected: []

  _renderSelect: (cellData, cellDataKey, rowData, index) ->
    <input
      type='checkbox'
      checked={@state.selected[index]}
    />

  _onRowSingleClick: (target, index) ->
    selected = @state.selected.slice()
    selected[index] = !selected[index]
    @setState(selected: selected)
```

Here you go. When I alter the selected state of a certain row (negate it), the checkbox is not being updated. Why? Is this a bug or am I doing something wrong here?

**Comment by zpao** [comment]
Can you give a bit more context, perhaps in a jsfiddle?

Are you calling `event.preventDefault()` in the event handler? That's one case where we've seen this before.

**Comment by binarykitchen** [comment]
Should I be calling `event.preventDefault()`? Will try a jsfiddle now ...

**Comment by zpao** [comment]
You shouldn't call preventDefault unless you intend to prevent the default behavior of the browser (which because of how we make the change event work means we're actually handling the click event. preventDefault of that on checkboxes prevents them from being visually updated). If you don't know why you're calling preventDefault, don't do it.

**Comment by binarykitchen** [comment]
Ok ... here is a fiddle (I forked part of that code from someone else and added my problem):
https://jsfiddle.net/michaelheuberger/4jg2z343/5/

When you click anywhere on the row, I expect the checkbox to be inverted. But it's not happening.

Hope you find the cause. Thanks!

**Comment by zpao** [comment]
There isn't anything wrong with React here. You're using your event handler incorrectly.

MovieList#_onClick should look like this: `_onClick: function(index, e) {` (index needs to be first so that when you bind, the arguments come in the right order.

render in MovieList, when looping over the movies, should look like this: `return <Movie onClick={self._onClick.bind(null, i)} ...` - you need to create a new function bound to the index so when it's called `index` is not `undefined`

**Comment by binarykitchen** [comment]
Ah, my bad. Thanks heaps! Learning here ...

**Comment by binarykitchen** [comment]
Ummm, @zpao, I wrote a better test case and still have the issue. Here http://jsbin.com/jonimu/3/edit?html,js,output

Any clues?

**Comment by spicyj** [comment]
@binarykitchen Event handlers receive an event object, not just the new value, so you want `event.target.checked` or similar. I've fixed it here:

http://jsbin.com/huranakovi/2/edit

I also added a `.slice()` which clones the array so you're creating a new copy instead of modifying the old one in place, which tends to be easier to reason about (though isn't strictly necessary).

**Comment by binarykitchen** [comment]
@spicyj Oh I see, thanks.

Now I have added few more code and there is another problem:
http://jsbin.com/rupumi/2/edit?html,js,console,output

There is a `onRowClick` event handler which also modifies the `selected[]` state. Somehow there is now an error thrown when I click on the checkbox directly. And the selected state on a row click is not reflected with the checkbox. Why?

**Comment by browniefed** [comment]
@balanceiskey onChange apparently also passes the value of the particular field as the first param, so the synthetic event is the 3rd arg.

Your handleChange is being called with `index, true( or false if you uncheck), event`. So you're calling `e.event.value` which is obviously an error.

**Comment by binarykitchen** [comment]
@browniefed I'm sorry, I can't follow you. Don't understand what you mean with synthetic event. Do you think you could update the code there?

**Comment by browniefed** [comment]
@binarykitchen sorry I just meant event. The argument is of type SyntheticEvent which is a cobbled together event by React.
To make it obvious about what is happening, put a debugger in the top of your `_onSelectChange` and checkout the `arguments` that are passed.

**Comment by binarykitchen** [comment]
Oh I see.  Just fixed that. But still, the code is not working:
http://jsbin.com/rupumi/4/edit

When I click on the checkbox or on the row, the component is not rerendered.

**Comment by zpao** [comment]
I would look into what Table and the other components are doing. As is your setState is getting called and bound to the right thing. Your render is getting called again with the right state. You're _renderCheckbox isn't getting called again though. Perhaps it's because your rowGetter is returning the same data so those components decided to treat that as a reason not to re-render. Perhaps moving selected state into the row data would resolve this (regardless it seems that it's outside of React's hands and the issue is with components we don't control).

**Comment by binarykitchen** [comment]
I see. How can I tell the checkbox to watch for changes inside the selected state? Should I (ab)use `shouldComponentUpdate()` here?

I do not want to move the selected state into the row data because IMO the whole table shouldn't be rerendered when only one checkbox has changed (performance).

**Comment by zpao** [comment]
I'm guessing somebody is already trying to make performance optimizations for you, which is why your cellrenderer isn't getting called. That's my guess anyway. I would look there and not try to prematurely optimize - make it work before you try to make it faster.

**Comment by binarykitchen** [comment]
I'd agree with you about that but I have a table with over 1000 rows here ...

**Comment by zpao** [comment]
Which will be worthless if you don't make it work first. AFAICT there is nothing directly related to React here. Dig into those other components and find out why they aren't updating.

**Comment by binarykitchen** [comment]
Ok, fair enough. It works now for me. All good now.
