### ISSUE TITLE
Warn when rendering to <body>

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#3207]
From @gaearon https://twitter.com/dan_abramov/status/568566795004723201

This has come up before. We should warn when rendering directly to document.body because that list of children is often manipulated by third party scripts and browser extensions. Leading to subtle reconciliation issues.

**Comment by jsfb** [comment]
Wow, #thewebworldsucks.

I didn't think about this before, but there are many plugins that go in and do crazy stuff.  For instance, I have a Google extension that rewrites anything that looks like a phone number to be a link that I can click to dial via voip.  That's not in the body, but it's likely to confuse React.

I'm not sure what we can do other than warn for render-to-body and hope plugins aren't modifying other parts of the DOM, but I think it's worth thinking about the possibility of having a more graceful solution that handles this in a more general way (even if that's just overwriting the plugin's dom changes) rather than just warning in dev and "hoping for the best".  Not sure if there is a solution, but food for thought.

**Comment by banderson** [comment]
@sebmarkbage I took a stab at adding in the warning, with wording very close to your original comment above. Let me know if missed anything!

**Comment by gaearon** [comment]
I was actually wondering if it's possible to run a mutation observer in dev mode that warns if nodes without data-reactid are inserted. There are valid cases for these insertions, but this would have helped me catch the issue much earlier.

**Comment by banderson** [comment]
@gaearon the big difference between the two approaches is that the mutation observer would only catch the offending scripts/extensions that _you_ run, not the unknowable combination of extensions users of your app have installed. Using a warning like this helps you think about that before the problem arises.

**Comment by gaearon** [comment]
I meant it as a complementary approach. But it's true most offense happens at the `body` level.

**Comment by banderson** [comment]
Agreed, that would definitely be cool!

**Comment by jsfb** [comment]
Tracking the mutation observer solution as a separate issue.

**Comment by berkerpeksag** [comment]
This is already fixed in https://github.com/facebook/react/commit/75a8bc96b10ef364c751bbc7a0594dbdb7e8663c (see PR #3211), so it can be closed now.
