### ISSUE TITLE
JSXTransformer breaks when creating source maps and defineProperty not available

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#3225]
If JSXTransformer is called with `sourceMap: true` as an option but the JavaScript environment does not have `Object.defineProperty`, the transformation dies here with an "Object doesn't support property or method 'defineProperty'" exception:
```
  /**
   * The list of original sources.
   */
  Object.defineProperty(SourceMapConsumer.prototype, 'sources', { 
```
This should degrade more gracefully and simply turn off source maps if not available. If I pass `sourceMap: false` rather than true, everything works fine, so it just seems like some code needs to be gated with an environment check. There does appear to be some logic in JSXTransformer to try and detect this, but it seems like this check is either incomplete or some other code also needs to be wrapped in this check:
```
// The source-map library relies on Object.defineProperty, but IE8 doesn't
// support it fully even with es5-sham. Indeed, es5-sham's defineProperty
// throws when Object.prototype.__defineGetter__ is missing, so we skip building
// the source map in that case.
var supportsAccessors = Object.prototype.hasOwnProperty('__defineGetter__');
```

Also see https://github.com/reactjs/React.NET/issues/89

**Comment by sebmarkbage** [comment]
Not sure this need a graceful degradation. It is better that it throws if you try to get sourceMaps out of it and you can't. At best we can throw with a nicer error.

Note that even the default output of ES6 classes will use defineProperty so it is quickly becoming unmanageable to support these old environments.

Maybe future .NET tooling will have nicer node/iojs integration? :)

**Comment by Daniel15** [comment]
ReactJS.NET already supports V8, but it uses MSIE as a fallback if V8 is
not available. Perhaps I should just enforce usage of V8 or newer MSIE
engines.

For now I've just modified it to retry without source map generation if it
throws an exception.

**Comment by zpao** [comment]
We do protect against this in JSXTransformer. In 0.12 it looks like we don't protect right if you use `stripTypes` (but otherwise we should). In master we don't have that extra branch.

We should maybe throw in reality but that ship has sailed so oh well. Perhaps we'll get a fresh start with whatever we make next.

On Feb 21, 2015, at 6:39 PM, Daniel Lo Nigro <notifications@github.com<mailto:notifications@github.com>> wrote:

ReactJS.NET<http://ReactJS.NET> already supports V8, but it uses MSIE as a fallback if V8 is
not available. Perhaps I should just enforce usage of V8 or newer MSIE
engines.

For now I've just modified it to retry without source map generation if it
throws an exception.

**Comment by zpao** [comment]
We're deprecating JSXTransformer, so closing this out.
