### ISSUE TITLE
eventData passed to Simulate methods should deep merge

### ISSUE THREAD

**Issue by Fauntleroy** [facebook/react#3229]
When using `Simulate` for a change event, I ran into a simple (but extremely agitating) problem: if you supply an object as one of the properties of `eventData`, your object will completely replace the existing one on the same key. Here's a quick example:

```js
TestUtils.Simulate.change( input_text_element, {
    target: {
        value: '0:01'
    }
});
```

This will correctly fire the `change` event, but it will completely overwrite `target`. In my case, my event handler was using `target.value` and `target.name`, only one of which I needed to supply for my test. Ideally, when supplying `eventData` to `Simulate`, it should do a deep merge instead of replacing things outright.

**Comment by spicyj** [comment]
Deep merging is always tricky because you need to assume things about the shape of arbitrary objects. In this case, would you actually want a deep merge? The `.target` value is the actual DOM node that you passed in; it would be surprising to me if passing args to Simulate would end up mutating that node directly. In the React tests, we mutate the target's value directly before simulating the change event, like:

```
input_text_element.value = '0:01';
TestUtils.Simulate.change(input_text_element);
```

and that's the approach I'd recommend here.

**Comment by roman01la** [comment]
Does `TestUtils.Simulate.change( input_text_element, { target: { value: 'val' }});` work with mock function? For me `mockFn.mock.calls[0][0].target` is always `null`, but when I supply an object without nested objects, it will merge it correctly:

```js
TestUtils.Simulate.change( input_text_element, { value: 'val' });
mockFn.mock.calls[0][0].value === 'val' // true
```
