### ISSUE TITLE
Autofocus should warn like for attribute.

### ISSUE THREAD

**Issue by steida** [facebook/react#3248]
If user writes for instead of htmlFor, warning is shown. I suppose autofocus instead of autoFocus should warn too.

**Comment by jonhester** [comment]
Just submitted a pull request for this.

**Comment by Dashed** [comment]
Just ran into this issue re. `autofocus` vs `autoFocus`.

@jonhester Are you still fleshing out your PR? https://github.com/facebook/react/pull/3269

**Comment by hkal** [comment]
Got tripped up by this today. #3269 is closed, so I'll give this a shot.

**Comment by zpao** [comment]
Had to revert the fix so reopening.

**Comment by Aweary** [comment]
Moving the discussion here instead of the closed PR

@hkal 
> @Aweary I'm pretty confident we can still get the warning without any unintentional side affects if we go back to pre-defining the autofocus property in `getPossibleStandardName`. Aside from attribute injection, the only call to it is for [producing warnings](https://github.com/facebook/react/blob/178cb7d3392505cd393b68e4e061c6ef860344a1/src/renderers/dom/shared/hooks/ReactDOMUnknownPropertyHook.js#L57).

@zpao are there any other properties like this that we're unable to validate right now because of how we inject values used in validateProperty based on a whitelist?

If not @hkal I think providing autoFocus as a default in getPossibleStandardName is a decent solution for now. IMO ideally validating a property would be independent of any whitelist, but if there aren't many other cases like this it's probably not worth addressing now since the whitelist is on its way out.

**Comment by zpao** [comment]
I think just inserting a default (with a comment explaining why) is probably the best way forward. I'm pretty sure this is the only one.

FWIW we do something similar for events and have a 1-off special case there too (though needs to be done differently) - https://github.com/facebook/react/blob/master/src/renderers/shared/stack/event/EventPluginRegistry.js#L155-L164

**Comment by Aweary** [comment]
@hkal do you want to get another PR open adding the default + explanation?
