### ISSUE TITLE
Mutating state inside shouldComponentUpdate

### ISSUE THREAD

**Issue by magalhas** [facebook/react#3262]
Is it an anti-pattern to mutate `nextState` or call `@setState` inside `@shouldComponentUpdate`? If it's, where should I listen to `@state` changes in order to change something on that same `@state`?

**Comment by yaycmyk** [comment]
@magalhas http://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops is the right place to do this AFAIK

**Comment by magalhas** [comment]
The use case is being able to filter the state when it's set.

**Comment by chenglou** [comment]
@yaycmyk `componentWillReceiveProps` is for update from owner, not from the component itself's state change.

You can do it in `componentDidUpdate`, but that'll easily create an infinite loop (since your filter update triggers `didUpdate` again) if you don't know what you're doing. Alternatively, you could pass a callback as the second argument to `setState` if that fits your use-case. Maybe there's a better way to achieve what you want to do. And yeah, don't mutate state in `shouldComponentUpdate`.

Closing for now unless you have more questions =) (btw, Stackoverflow helps).
