### ISSUE TITLE
Proposal for this.subscribe - auto disposing during componentWillUnmount.

### ISSUE THREAD

**Issue by prabirshrestha** [facebook/react#3314]
I find that this is common enough to be part of core react either as a mixin or as a method for a component.

There are lot of cases when we subscribe during `componentWillMount` and unsubscribe during `componentWillUnmount`. What if we had a pattern for this.

```js
let ListenerMixin = {
    componentWillMount() {
        this._subscriptions = [];
    },
    subscribe(subscription) {
        this._subscriptions.push(subscription);
    },
    componentWillUnmount() {
        this._subscriptions.forEach(unsubscribe => unsubscribe());
        this._subscriptions = [];
    }
};
```

I can then call it as. 

```js
componentDidMount() {
        this.subscribe(TodoStore.getState(state => this.setState({ todos: state.todos })));
}
```

This discussion original started from this discussion https://github.com/jesseskinner/hoverboard/issues/8. https://github.com/spoike/refluxjs has `this.listenTo`.

//cc @jesseskinner

**Comment by jsfb** [comment]
A style like this is already being considered.  See react-future's observe function (https://github.com/reactjs/react-future/blob/2534efc1e731fe46a87e5bdc71bb549e56360409/09%20-%20Reduce%20State/01%20-%20Declarative%20Component%20Module.js)

There are a couple of considerations:  This would increase the API surface (and thus learning curve) for React, so we need to be sure this pattern is common enough to justify the additional weight.  We also need to decide if this pattern is a legitimate/recommended design pattern (there are questions around this, since you are effectively side-loading data when data should probably be passed down as props from your parent).

Anyway, this is being tracked in React-future (still needs more baking), so I'm going to close it out here.
