### ISSUE TITLE
State object property change not triggered

### ISSUE THREAD

**Issue by ionutcirja** [facebook/react#3342]
Hi,

This might be a stupid question, but I couldn't find any good solution.
I have an array of objects in the state of a list component and every object is mapped to an item component. On item mouse over, I trigger something into parent list and then I'm updating the rest of the state objects with a new property and I expect the rest of the item components to be updated but this is happening just if I do a force update.
Is this a react issue or something that I'm doing wrong maybe?

Thanks

**Comment by jsfb** [comment]
React will re-render a component when that component's setState method is called.  If you are manually mutating the data, there is no way for React to know the data has changed and thus no way to re-render.  Calling setState or forceUpdate are both appropriate ways of notifying a component of a data change.

For future reference, questions like this are better asked on StackOverflow.  Closing issue, since it's not a "bug in react".  Feel free to continue the conversation here or take the issue to StackOverflow.

**Comment by ionutcirja** [comment]
Thank you and my apologies for adding this as an issue.
