### ISSUE TITLE
Tutorial example tries to POST to .json file

### ISSUE THREAD

**Issue by mikefrancis** [facebook/react#3391]
Just had a go at the tutorial (which is great btw) and got right to the end and realised that the `handleCommentSubmit()` method in `CommentBox` tries to POST the form data to the same `comments.json` file.

I understand that in the real-world this would be sent to some sort of RESTful service but newcomers might wonder why it's not working.

I realise I could have a go at editing the tutorial but figured it might be better coming from the people who wrote it?

**Comment by danmartinez101** [comment]
The beginning of the tutorial actually makes reference to the need for a server in order to complete the portion of the tutorial that updates the server side data, but it could probably be mentioned again closer to the implementation of the POSTing code. 

I think the reason this server side code is simply overwriting a flat json file is to keep the focus of the tutorial on the React side of things.

**Comment by mikefrancis** [comment]
Ah ok. Just thought I'd bring it to the attention of the repo, sounds like you're on it.

**Comment by zpao** [comment]
Chances are we'll tweak the tutorial a little bit so you're obviously interacting withe an API and not a file. See https://github.com/reactjs/react-tutorial/issues/39 if you're interested in helping out :)
