### ISSUE TITLE
Performance regression in 0.13.0 for dev

### ISSUE THREAD

**Issue by jlfwong** [facebook/react#3406]
When trying to debug performance locally, I was seeing really poor performance while using 0.13.0 for a fairly small dataset.

I wrote up a quick benchmark, and it looks like that while 0.13.0 is around the same speed as 0.12.1 for prod, it's 2.5x slower in dev.

Benchmark: http://jsperf.com/react-0-12-0-to-0-13-1-perf-regression

Relevant screenshot:
![image](https://cloud.githubusercontent.com/assets/150329/6646478/7e7fa58e-c99b-11e4-9420-8a8131261cc8.png)

**Comment by zpao** [comment]
Yes, we knew there was a perf regression in dev. That's the cost of doing business here to add more warnings and do things like "freeze" props, setting up getters and all that.

As we remove some deprecated patterns we'll see some speedups since we'll have less code for warnings.

I'll leave this open for now but I'm not sure how much we can really do at this point, if we even want to.

**Comment by spicyj** [comment]
I just did some profiling here and there aren't big, obvious, easy wins to be had so we're probably going to leave it like this for now. Hopefully next release will be faster…

**Comment by jordwalke** [comment]
Was there a consistent regression across various VMs in prod?

**Comment by gaearon** [comment]
Closing as this has been inactive for a while, and it doesn’t appear that we have any specific plan to improve perf in dev. If the problem keeps getting worse (I’m not sure what the situation in 15 is?) we might want to revisit.
