### ISSUE TITLE
Making render() pure

### ISSUE THREAD

**Issue by grav** [facebook/react#3449]
I saw a mixing which implemented render something like this:
```
render: function(){
  return this.pureRender(this.props, this.state);
}
```

The user then had to implement a `pureRender(props, state)` function.
To me, it seems like a nice hack and I'm wondering why this isn't the default way of React? Any thoughts?

**Comment by syranide** [comment]
@grav Because `shouldComponentUpdate`; by reading props/state from arguments you're unable to access updated props/state if `shouldComponentUpdate` ever returns false when a prop/state actually changed. This is a problem if you have inline closures in your render as they will be reading outdated props/state.

**Comment by tcoopman** [comment]
@syranide Can you give an example of that? `shouldComponentUpdate -> false` means no render, so how does this differ from using `render()`?

**Comment by syranide** [comment]
```
function(props) {
  return <div onClick={function() { console.log(props) }} />
}
```

Will always output the props it was last rendered with, not necessarily the up-to-date props. Whereas if you put `this.props` in there it will always output the up-to-date props.

**Comment by tcoopman** [comment]
@syranide thanks!

I didn't think of the case where you don't want to rerender, but still want up-to-date props, but it seems like it could be used.

Should this be explicit in the docs? Something about `shouldComponentUpdate` will still update `this.props` and `this.state` even when you return false?

**Comment by zpao** [comment]
There's a bunch of discussion in #1387, which is about the same thing.

It's not the default of React because we're in a somewhat functional, somewhat OO world. What we're enabling moving forward is something like this where any function with the right signature can be a component.

I'm going to close this out because of the overloap, but feel free to read some more of the thoughts over there.
