### ISSUE TITLE
Immutable data - Differences in production and development builds (possible bug)

### ISSUE THREAD

**Issue by narkeeso** [facebook/react#3469]
I am noticing strange behavior with the development build vs the production build.

Please see bin: http://jsbin.com/pikokuboza/1/edit?html,js,output

I have included two links to the React library (production/development). The production build works as expected and renders the Immutable.Set(). However, the development build breaks and returns this error:

```Uncaught Error: Non-extensible objects are not allowed as keys.```

Also, another strange thing is that on the development build the Set() works as long as the size is under 9. Try removing 2 elements from the array so the size is 8 and it will render fine on both development and production.

**Comment by cody** [comment]
Just a bump after 5 days of silence.
cc @leebyron The error comes from immutable.js.
cc @sebmarkbage It is a bit unclear which immutable data structures React supports.

**Comment by zpao** [comment]
The problem I think is that Immutable is using the return value of the map to create a new Set. That's legit. However in order to do that when objects are the values, it needs to shim weak maps. And in order to do that it actually needs to set a property on the object (in this case a ReactElement). In `__DEV__` in React we freeze the element when creating it, thus making it non-extensible.

Your best bet is probably to turn your Set into an array and map over that.

```js
    var nodes = Immutable.Set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).toArray().map(function(item) {
      return (<span>{item}</span>);
    });
```

As to why this works with array of size 8, that's an implementation detail of the Trie library (`MAX_ARRAY_MAP_SIZE = 1 << 5 / 4 // => 32 / 4 = 8`).

I'm not sure there's much we can really do on React's end at the moment. We want to freeze elements in dev to prevent user error and establish best practices. Perhaps we can add some fancy interop so Immutable knows it's dealing with a React element.

**Comment by narkeeso** [comment]
Thanks for the explanation @zpao, I was trying to avoid having to convert Immutable objects. However, for my use case I switched to using Immutable.List() and it's been fine. I was originally exploring usage for List() Set() OrderedSet() Map() etc and how they might interact with my React components.

Is it not recommended to pass Immutable objects to react components?

**Comment by sebmarkbage** [comment]
The recommended way is to turn it into a sequence (Iterable) first using toSeq() and then mapping over that.

**Comment by zpao** [comment]
Going to close out since the immediate issue is solved. We can figure out interop later.
