### ISSUE TITLE
Why is a rendered ReactElement not a ReactElement anymore?

### ISSUE THREAD

**Issue by dmatteo** [facebook/react#3479]
According to your tests https://github.com/facebook/react/blob/21a9e8b6e821ac67d542dcc91b559a1a0dfc52f5/src/modern/element/__tests__/ReactJSXElement-test.js#L149, once a ReactElement gets rendered then it is not recognised as a ReactElement anymore.

How come?

How can we test that a rendered element is actually a ReactElement without getting hacky?

**Comment by syranide** [comment]
`Component` is the class, `<Component />` is an element.

**Comment by dmatteo** [comment]
I realise that, although I find it a bit confusing that a class that is used to create ReactElements cannot be considered an element itself.

Is there a clean way to check if an object is a class that creates ReactElements (a factory, if I am not mistaken)?

**Comment by syranide** [comment]
@dmatteo It's the equivalent of `Class` vs `new Class`. Factories are helpers for non-JSX users only, React consumes classes as-is. I'm not sure if there's a way to definitively check whether a given "function" is a valid component class or not. cc @spicyj

**Comment by dmatteo** [comment]
@syranide I understand the difficulty, but the problem is not only related to non-JSX users.
Take this use case:

```javascript
      var NewComponent = React.createClass({
        displayName: 'NewComponent',

        getInitialState() {
          return {
            status: 'working'
          }
        },

        render: function() {
          return (
            <p>Check this out, I am a component</p>
          );
        }
      });

      var component = React.render(<NewComponent value={data.value} label={data.label} />, document.body);
      console.log(React.isValidElement(component));
```
The result, as you know already, is false... which is very confusing

On the other hand, the real component is in that same object, and can be tested with 

```javascript
    console.log(React.isValidElement(component._currentElement));
```

How about testing also for that?
I can submit a PR if you like the idea.

**Comment by dmatteo** [comment]
I just realised that you guys moved `_currentElement` down to one level in 0.13

So this is actually what outputs `true`
```javascript
var component = React.render(<NewComponent value={data.value} label={data.label} />, document.body);
console.log(React.isValidElement(component._reactInternalInstance._currentElement));
```

**Comment by zpao** [comment]
To clear up some of the terminology:

Elements are lightweight objects. They can be reused. An element is what is returned from `render`.

A component class is pretty much any "class" that has a render function the returns an element. These may have constructors but they should not be called directly. React will do the instantiation. Here's the simplest ES6 example:

```js
class Foo {
  render() { return <div/>; }
}
```

A class can also be created with `React.createClass`.

A factory is a actually a function that wraps up the creation of an element of the specified type. These can be called directly (but if you're writing JSX you should never have to think about factories). Honestly factories are really unexciting but they get confusing. Basically it's just this:

```js
React.createFactory = function(type) {
  return function() {
    return React.createElement.apply(React, [type].concat(arguments));
  }
}
```

Rendered components have state associated with them. They are the return value of `React.render`. Also, `refs`. There are very few methods and properties on these objects. Anything with an underscore is "private" and you really shouldn't be accessing it because we will break it (as you noticed). This will never be an element. And it shouldn't be.

I'm not sure what idea you're proposing. Can you clarify?

**Comment by dmatteo** [comment]
@zpao Thanks for the clarification, but I still don't get why render components should be recognised as an element. This could be very much useful in testing the components.

I am writing an extension for the assertion library called unexpected (https://github.com/unexpectedjs/unexpected) that will take into account that the tested element is in fact a React element.

Anyway, I've put up a very rough version of what I will like to test for.
It needs some polish, but it serves as a proof of concept.

You can see the commit here https://github.com/dmatteo/react/commit/48cd996aa70723a8df0b4dd0b65020e305350a9e

Please let me know what you think about the idea

**Comment by zpao** [comment]
Rendered components simply aren't elements. They are very different. If you took a rendered component and used it like an element (eg pass it to React.render) you would not get what the same thing.

**Comment by dmatteo** [comment]
I see.
Given that for obvious reasons I can't test for "private" properties, is there a way to identify a rendered ReactElement as a React component or not at all?

**Comment by zpao** [comment]
Can I turn it around. Why do you need to know? There may be another way to achieve what you're working toward.

I don't think we have any `instanceof` checks for component instances. cc @sebmarkbage

**Comment by syranide** [comment]
A rendered element is an instance of your component class, so you can always check if there is a `render`-method (I believe that's the only guarantee there is) and if there is one then it's *valid*, but not necessarily instantiated by React.

**Comment by dmatteo** [comment]
@zpao My use case: I'm trying to create a plugin for the [unexpected](https://github.com/unexpectedjs/unexpected) assertion library called [unexpected-react](https://github.com/podio/unexpected-react) in order to achieve some extra ease of testing on React components.

One of the most interesting features of `unexpected` is that we can define a Type of the element passed as an input, and react accordingly

This is an error example 
```
  The assertion "to have props" is not defined for the type "object",
  but it is defined for the type "ReactElement"
```

Now, if I can't tell if the difference between a Class and a ReactComponent, all this awesomeness go to waste, and I will simply have to check for the props property.

Another cool usage is to have multiple functionalities for the equality operator.

E.g. 
```
expect('string', 'to equal', 'String')
expect('ReactComponent1, 'to equal', ReactComponent2)
```
While the first comparison is pretty straight forward, the second one can be custom defined in the plugin, without the need of extra complexity for the user

@syranide checking for the `render()` function is a sub-optimal solution that I would love to avoid.

**Comment by dmatteo** [comment]
up?

**Comment by jsfb** [comment]
A valid render() function is literally the only requirement, as demonstrated in @zpao's really simple ES6 example.  So your checks can't really rely on anything more than that.

We use github issues to track bugs in React.  Since this isn't a bug, I'm going to close out the issue.  Feel free to continue the discussion here, or continue the discussion on a mailing list or StackOverflow.
