### ISSUE TITLE
Is there a way to enforce `propTypes` for components?

### ISSUE THREAD

**Issue by dmitriiabramov** [facebook/react#3514]
for example, throw a warning if i pass a prop to a component and it's not defined using `propTypes`?

**Comment by zpao** [comment]
We've had this requested before, so I'll point you to #1587. We won't be able to really do this as long as the pattern of passing along extra props is a thing. Eg `<FancyButton>` which renders a regular `<button>` with a specific class but otherwise lets users specify any other props that would get passed down to the DOM node.

```js
FancyButton = React.createClass {
  propTypes: {
    color: React.PropTypes.string
  },
  render: function() {
    return <button {...this.props} style={color: this.props.color} />;
  }
}
React.render(<FancyButton color="blue" value="foo" />, ...)
```

Anyway, follow along in the other issue for updates.
