### ISSUE TITLE
Improve error for createElement(undefined)

### ISSUE THREAD

**Issue by spicyj** [facebook/react#3565]
https://github.com/facebook/react-native/issues/600#issuecomment-88673022

**Comment by unphased** [comment]
Hi, 

I just lost like an hour or so (and it is mostly my fault, but still...) because of this. 

Basically if you send undefined to createElement, and you happen to never consider the possibility that what you sent in is undefined, React will just drop dead as if being hit by an anvil. 

Eventually you find out that the debugger lets you get right up until the offending createElement call, but that still isnt exactly enough if you're *really* not considering the possibility that undefined is sent in.

Anyway, the point is.... `undefined` is really common, `createElement` calls can really proliferate when rendering something sophisticated, and so it really should be checked and a warning thrown. Please.

**Comment by fkling** [comment]
@unphased, this issue is not closed. The linked one is.

**Comment by spicyj** [comment]
Pretty sure this has been fixed in master. Also improved the error message at mount time: 642323e5a8ad814e372b67bd76ded2d6d5bd383d.

**Comment by unphased** [comment]
Awesome, thanks

**Comment by unphased** [comment]
I just ran into a very similar issue where React just doesn't say a peep when a string is provided to a style={stringvar} JSX attribute. 

I figured if simply setting the plain old style attribute with a string is *for some reason* not supported that there would at least be a big red warning...

**Comment by cody** [comment]
@unphased 
I tried to reproduce your problem, but React wouldn't let me use style={stringvar}. The fiddle https://jsfiddle.net/nqup8wsj gives me this error:
> Uncaught Error: Invariant Violation: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.

This is how it should be. Can you give a code example that repros your problem?

**Comment by unphased** [comment]
Hmm. I checked my codebase and it does appear that my react version has this logic inside it: 

```
$ ack 'mapping from style prop'
public/js/vendor/react.js
8006:    'The `style` prop expects a mapping from style properties to values, ' + 
```

So something is happening here...

I don't have a minimal reproducing example on hand, sorry. Will post back if I can come up with one.
