### ISSUE TITLE
jsx --watch Error: watch ENOSPC 

### ISSUE THREAD

**Issue by faizalpribadi** [facebook/react#3637]
Sometimes i dont know with my react-tools a.k.a`jsx`
*. i try to compile my js with this command: 
```js
$ jsx --no-cache-dir --watch resources/public/static/internal/js resources/public/static/internal/assets/js
```
and this is result:
```js
evalmachine.<anonymous>:1172
    throw errnoException(err, 'watch');
          ^
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (evalmachine.<anonymous>:1172:11)
    at Object.fs.watch (evalmachine.<anonymous>:1198:11)
    at DirWatcher.DWp.add (/usr/local/lib/node_modules/react-tools/node_modules/commoner/lib/watcher.js:137:36)
    at /usr/local/lib/node_modules/react-tools/node_modules/commoner/lib/watcher.js:123:14
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```
*. well, working done with no flag option `--watch` : 
```js
$  jsx --no-cache-dir resources/public/static/internal/js/ resources/public/static/internal/assets/js/  
```
and i try to add `fs.inotify.max_user_watches=524288` to my `/etc/sysctl.conf` and no result :confused:

# Environment:
*. `ElementaryOS Freya Based On Ubuntu 14.04`
*. `Node Version 0.12.2`

**Comment by zpao** [comment]
Based on other threads around the internet, that seems to be the thing to do (presumably you found the same things I did) along with `sudo sysctl -p` (to reload sysctl.conf). I don't know that there's much else to do (except maybe gracefully handle that error). It's really a problem with [commoner](https://github.com/reactjs/commoner) since the jsx command is really just a wrapper for that & applying the transform - would you mind filing there for posterity.

**Comment by faizalpribadi** [comment]
Thanks for feedback @zpao 
I research about error `ENOSPC` its means about no disk space available  
when my `/tmp` clearing , `jsx` work back to normally :+1:
