### ISSUE TITLE
getDefaultProps not working

### ISSUE THREAD

**Issue by tjwudi** [facebook/react#3655]
I am working on a very simple component with default props.

```
// React component
class Navigation extends React.Component {
  getDefaultProps() {
    return {
      user: {a:1}
    }
  }

  render() {
    console.log(this.props);
    if (this.props.user) {
      // User has been logged in
      return (
        ...
      );
    }
    else {
      // User not logged in
      return (
        ...
      );
    }
  }
}

Navigation.propTypes = {
  user: React.PropTypes.object
};

return Navigation;
```

And I simply render it without any props (`<Navigation />`). But I got an empty object from console output.

I am using react **0.13.1**, chrome 41, OSX 10.10.

Any idea what is going wrong?

**Comment by iamdustan** [comment]
Es6 classes need defaultProps as a static property.

Navigation.defaultProps = {...}

**Comment by tjwudi** [comment]
Thanks. Maybe update this in documentation :) ? @iamdustan I will be happy to send in a PR

**Comment by zpao** [comment]
http://facebook.github.io/react/docs/reusable-components.html#es6-classes does reference this. It might be good to also put some documentation in http://facebook.github.io/react/docs/component-specs.html#getdefaultprops to make it a bit easier to find. I'm going to close this out since it's invalid but I'd love to see a PR with more docs :)

**Comment by spicyj** [comment]
I think you should have also seen a runtime warning for this?

**Comment by tjwudi** [comment]
@spicyj not really, though

**Comment by spicyj** [comment]
@tjwudi Thanks, looks like an oversight. Fix incoming…
