### ISSUE TITLE
Member variables in react class are “shared” by reference

### ISSUE THREAD

**Issue by delijah** [facebook/react#3681]
When i create several instances of a react class (by using React.createElement on the same class), some member variables are shared between the instances (arrays and objects are shared, strings and booleans etc. not).

For me this feels horrible and scary and wrong. Is this a bug or is there another way to do what i want to do?

Please have a look: http://jsbin.com/kanayiguxu/1/edit?html,js,console,output

A second, more real-world, example: http://jsbin.com/guwipeyubu/1/edit?html,js,console,output

**Comment by fkling** [comment]
To me it seems to work the same as if you assigned an object to the prototype of a class, so that's not really surprising? Those values should probably be part of the component's state instead.

**Comment by zpao** [comment]
This is just how JS works with objects, they're effectively always passed by reference. You would see the same thing if you use typical JS protoypes. http://jsbin.com/rujutijaku/1/edit?js,console

We explicitly don't clone everything from the object you pass us (that becomes a pretty unscalable solution). Because we autobind functions, we do create new functions for each instance due to the binding. As Felix said, you should probably use state. Since you're returning a new object from the `getInitialState` function, you don't have the reference issue.
