### ISSUE TITLE
Detect if component has invalid props?

### ISSUE THREAD

**Issue by joshfrench** [facebook/react#3686]
Is there a way to check if an existing component has valid props _after_ it's been instantiated? In addition to the existing console warning it would be great to have a check I could run later, i.e. prior to rendering or when the component is receiving new props.

**Comment by jsfb** [comment]
The proptypes are just functions that you can call to manually verify the props.  You could always iterate over your props and manually call the proptype function to verify their type.

**Comment by zpao** [comment]
As much as that's true, it's not really super useful.

@joshfrench I believe you should get warning when receiving new props (or actually before) - we're running the validations when creating a new element (which we then use to update an instance). As for prior to rendering, props should be immutable and we warn on mutations so you should get those too :)

We talked about these a bit before we launched 0.13 (http://facebook.github.io/react/blog/2015/02/24/streamlining-react-elements.html#immutable-props) precisely because validation is important and there are lots of places it can happen. If you haven't updated to 0.13.x yet I would encourage you to.

Otherwise I don't think we're going to expose anything to check proptypes at any given point.

**Comment by joshfrench** [comment]
All makes sense, I just needed a nudge in the obvious direction :) My question was less about props being mutated after the fact and more about implementing stricter validation than just a warning, e.g. rendering `null` if we know ahead of time the component was passed invalid props from some upstream data source. Thanks!
