### ISSUE TITLE
Add Method for enabling full invariant warnings in production

### ISSUE THREAD

**Issue by francoislaberge** [facebook/react#3698]
hi,

We're using react to build out views in the atom editor. Because atom is an app running production mode, react won't give us proper invariant errors. Looking through the code there were hundreds of checks to see if the code was running the production environment, so it didn't look trivial to add a pull request for this. I did a search replace for "production" -> "development" and started to get the errors I wanted. 

I know we're a special case, but this will come up for any system where you use react in a plugin when the surrounding app is in production mode.

I will look at seeing if I can make atom not run in production mode, but it this feels like something react should support rather than atom to support running a production app in development mode.

Thanks for your time,
Francois

**Comment by francoislaberge** [comment]
To be clear, we're building views for our plugin. Which is why we don't have control over the runtime development mode.

**Comment by zpao** [comment]
cc @bolinfest - have you guys done anything to work around this? Sounds like something that should be possible to force Atom to do.

@francoislaberge I'm not really sure how this would work, especially since our prod build actually strips out the friendly messages entirely. Our npm package (which is basically what Atom is using) is already after a build step which makes it possible to get that dev OR prod build (that's the switching you did, but now that I think about it…).

But actually I may have misunderstood and there might be a way to make this work… are you installing your own React or using the one that ships with Atom (if it still does)?

**Comment by francoislaberge** [comment]
@zpao I'm installing my own react. Is there one that I can access within react, how do I get access to that?

**Comment by zpao** [comment]
`require('react/dist/react')` will give you the precompiled dev build (the same one we ship to CDNs). The other pre-built files are in `dist` as well.

There are downsides… if you're using anything from `React.addons`, make sure you *always* use `require('react/dist/react-with-addons')` (otherwise you'll hit problems with multiple Reacts). If you're using any 3rd party components they won't interact well (same reason of multiple Reacts).

**Comment by francoislaberge** [comment]
@zpao Hmmm, yeah that's going to get messy quickly as we will be reusing third-party components much. Thanks for the info though!

**Comment by gaearon** [comment]
We added error codes in 15.3.x so you can inspect full errors in production.
