### ISSUE TITLE
Can't make checkbox work in a modal

### ISSUE THREAD

**Issue by wwayne** [facebook/react#3731]
#### Info
The modal is hidden in the beginning, and control its state by changing class of it, in previous code, after I click the checkbox inside the modal, it makes no changes, but the state has changed, so it's just not rendering.

.modal {
  visibility: visible;
 opacity: 1
}
.modal.hide {
 visibility: none;
 opacity: 0
}

#### Previous code ( checkbox doesn't work )
```
...

getInitialState() {
   items:[
      {id:1, checked:true},
      {id:2, checked:true},
      {id:3, checked:true},
  ]
},

_onChange(id) {
    let items = this.state.items;
    items.every((item, index) => {
       if(item.id === id) {
           item.checked = ! item.checked
           return false; 
       }
       return true;
    })
   this.setState({
       items: items
   })
},

render() {
  checkboxList = this.state.items.map((item, index) => {
       return( <div key={index}>
                       <input type="checkbox checked={item.checked} onChange={this._onChange.bind(this, item.id)} />
                 </div> )
  })
  return (
      <section className={this.state.showModal ? "modal" : "modal hide"}>
         {checkboxList}
       </section>
  )

}

...
```

#### Current code( funny,  it works )
```
 // keep others same
...
render() {
 return (
    {this.state.showModal && 
       <section className= "modal">
         {checkboxList}
       </section>
    }
 )
}

...
```

I can get it works, but I don't know the reason......

**Comment by jsfb** [comment]
@wwayne I don't see any bug in React; it appears to be rendering exactly as expected.

You never set the showModal button, so it is always undefined, so it always goes into "modal hide" and you never see the checkboxes.  The checkboxes, if you force them to be visible (I did this by changing the style to red/green instead of invisible/visible), all check and uncheck as expected.

My fiddle, with a few fixes since your code didn't run in jsfiddle as-is: https://jsfiddle.net/edn4evb2/

Can you provide a fiddle that demonstrates the issue you're having?

**Comment by wwayne** [comment]
@jsfb restored the same situation in jsfiddle, the bug never shows again. 
I'm thinking if it is caused by our develop environment or the converter(babel.js), I will check them in another way.
Really thanks for your help and patience， have a good day : )

**Comment by GabrielPartida10** [comment]
Yo tenia ese mismo problema pero lo arregle quitando un prevent default en el modal pruebalo podria servirte c:
