### ISSUE TITLE
npm install fails on linux without g++ installed

### ISSUE THREAD

**Issue by sejoker** [facebook/react#3744]
I have a fresh installation of Ubuntu 14.04 and installed compiled version of node.js 10.38. 

`npm install` failed on `node-gyp rebuild` step with error 'make: g++: Command not found'.

`apt-get install g++` solves the problem. It make sense put g++ dependency into README.md Prerequisites section.

**Comment by zpao** [comment]
That's kind of annoying but yea, we might need to do something like that. Compilers are a dependency for any binary npm module (which one of our dependencies depends on). Even contextify itself doesn't call out the need for g**. When you install node / npm via `apt` does it not install `build-basic` as well? It seems like it should since that's a requirement for many modules.

**Comment by sejoker** [comment]
I used the recommended approach for [Debian and Ubuntu based distributions ](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions). `build-essential` is not a part of installation. But I see your point, contextify setup on Windows even more [complicated](https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide).

**Comment by GeraldScott** [comment]
The installation of build-essential is not 'optional'. It is a pre-requisite for `npm install`

**Comment by yaswanthsvist** [comment]
for installing g++ in fedora and other linux os use 

sudo yum install /usr/bin/g++
or
sudo dnf install gcc-c++

**Comment by uluhonolulu** [comment]
`sudo apt-get install build-essential checkinstall` fixed it for me (Ubuntu)

**Comment by cnscorpions** [comment]
`sudo yum install /usr/bin/g++` works for CentOS7, too. :)

**Comment by jokerham** [comment]
What about Mac?
