### ISSUE TITLE
Recognize DOM Changes?

### ISSUE THREAD

**Issue by ChiefORZ** [facebook/react#3764]
Hey.

Im using React to render a Treeview. Since i haven't found a good replacement for my Native Javascript Drag 'N Drop Sorting Script, i sticked with it.

So, react renders and everything is fine. The DOM looks like it should be: 
data-reactid: .0 > .0.1 + .0.2 + .0.3

but since I am using the reordering these elements, the DOM is manipulated directly. and it looks like:
data-reactid: .0 > .0.1 + .0.3 + .0.2	(2 and 3 got mixed up)

I realized really fast, that it is anything but good. For example: when i remove the .0.3 after i reordered my list... the item with ref .0.2 doesn't work as it should be... no onClick Events is working and the render is displaying data from another element!

So i have to figure out a way to force React to completely re-render the complete Component. I've already tried the forceUpdate() method within the Component, but it doesn't seem to recognize changes to the DOM.

Does someone know a better on way how to tackle this problem?

**Edit:**

http://jsfiddle.net/utLrm52g/
As you can see in this example: I remove a Node from the rendered list and update the item-array. React doesn't recognize that data-reactid: .0.1:$three is removed from the dom...

**Comment by gaearon** [comment]
React won't work if you're manipulating its DOM on your own. This only works for very simple cases like adding something to React leaf nodes. For any moderately complex case like you described, it will not work by design.

Instead, you should change your drag and drop code to manipulate *data*, not DOM, and use React to re-render the DOM. I wrote a [drag and drop library](https://github.com/gaearon/react-dnd) for that, you might want to check it out.

**Comment by spicyj** [comment]
As @gaearon said, React never reads from the DOM and mutating React-rendered DOM from outside of React isn't supported.

**Comment by yaycmyk** [comment]
@ChiefORZ I would recommend exploring flexbox's `order` [property](https://developer.mozilla.org/en-US/docs/Web/CSS/order). Might work well for you since you don't have to physically move the nodes.
