### ISSUE TITLE
npm update broke something relating to react-tools

### ISSUE THREAD

**Issue by jbhatab** [facebook/react#3774]
I just ran npm update react-native and it broke my project. Got this error,

Cannot find package main file for package: /Users/blaine/dev/native/evueIOS/node_modules/react-native/node_modules/react-tools/src

It could be something just related to me but thought I'd post it up.

**Comment by jsfb** [comment]
Thanks for the bug report!

I think you're probably looking for the react native repository, which is located here: https://github.com/facebook/react-native

If you post the issue in that repository, I think they'll be better able to handle the bug report.  This repository is actually for tracking react-core and the web-version of react.

Since this issue probably isn't related to react-core, I think it makes sense to close this issue in this repository.  But I encourage you to post in react-native.

cc @zpao and @spicyj in case something jumps out at them related to react-tools or npm bundling.

**Comment by jbhatab** [comment]
My bad. you can delete this.
