### ISSUE TITLE
Server side rendering example question.

### ISSUE THREAD

**Issue by pyeek** [facebook/react#3827]
In the server side rendering example, the initial startup js function calling `React.render` is being generated dynamically via PHP. In the comment it says I really should be using webpack instead of browserify. It isn't immediately clear what that means.

    // index.php
    // Generate the code required to run the component on the client
    // We assume that the Browserify bundle is loaded in the page already
    // and that you used -r to get a global require() function that provides
    // every $module you may request as well as React.
    // Note that this solution is simple but I don't think it scales to
    // multiple large pages very well. For that you'd be better off using
    // webpack.
    $startup_code = <<<SCRIPT
    <script>
    (function() {
        var React = require('react');
        var Component = require($module_for_js);
        React.render(
          React.createElement(Component, $props_json),
          document.getElementById($container_id_for_js)
        );
      })();
    </script>
    SCRIPT;

Can someone elaborate on this? In what way do I use webpack instead of browserify? Thanks.

**Comment by abritinthebay** [comment]
You don't. It's an example of poor documentation. They are talking about pure bundles that browserify does (and ignoring it's ability to factor bundles into multiple files) vs webpacks hotloading capability.

It doesn't belong in the documentation, it's irrelevant (and also opinion, one that I'd argue is pretty wrong)

**Comment by zpao** [comment]
Yea, it's not the best example. It actually doesn't have anything to do with hotloading, just wasn't well informed (plus is ~2 years old and at that point generating multiple bundles with browserify wasn't super easy).

The point of this bit is just to show that a generic solution where you don't have an entry point to your app in a main.js or something that has the things it needs bundled, then you need *some way* of accessing React and Component.

I'm going to close out since this was just a question but feel free to continue discussing.

**Comment by abritinthebay** [comment]
Ah, well.. yeah, 2 years ago Browserify was a LOT more janky... then again so was Webpack ;) 

Interesting that it wasn't about hotloading tho. I guess it just reads that way now ;) 

re the "generic" entry point. I actually have that with Browserify now due to the `factor-bundle` plugin. I just create a generic "reactSetup" include that is included anywhere I want to use React code and browserify will factor that out to a common bundle. In that setup file I just have `global.React = React;` and... tada ;)

**Comment by pyeek** [comment]
ok so I'm just going to re-iterate my understanding of some of the points and the example in general. @zpao and @abritinthebay would really appreciate if you guys could verify what I am saying since I'm fairly new to a lot of the JS eco system:

1. Browserify is actually perfectly fine to be used to bundle all the necessary dependencies and whether you use browserify vs webpack is up to you.
2. The components rendered as markup is returned directly via $server_markup in the case js is not present.
3. The $startup_script is just a replacement for something like a main.js and is used to kickstart the component on the client side. What it actually does when the page loads if js is present is render the Component into the given container (and clobbers the static markup from $server_markup). In reality we don't even need to render this script tag here directly we could have the right script tag loaded on the page to do the rendering. This was just done to simplify the demo.

So overall, we are just trying to make sure we get the rendered components from the react server and return it, and make sure we start up react component on the client side as well.

**Comment by abritinthebay** [comment]
That... seems right. Certainly the 1st point is correct - that's just a tech choice on your end.

It doesn't even clobber the static markup btw - if the content is rendered by React originally (on the server) then it will have all the react data-id attributes (etc) and React will just attach itself to the right places. No DOM rewrites at all if the props/state of the React code is the same on the client as it was on the server.
