### ISSUE TITLE
Links within SVGs

### ISSUE THREAD

**Issue by shyamsalimkumar** [facebook/react#3845]
Clicking `<a>` within SVGs cause issues, in my case missing `<rect>`s. 
On initial load you ought to see 5 boxes(light brown, red, blue, brown and orange).

1. Click 1. Now its 3 boxes (blue, brown and orange).
2. Click 2. Now its 2 boxes (light brown and red).
3. Again click on 1. 2 boxes :worried: (blue and brown)

Where does the orange box disappear to??? :confused: Please note this entire thing is SVG and that the link is actually present in the DOM. It just decided not to show itself.

On Firefox, clicking the link, `TypeError: setting a property that has only a getter` is thrown from  react.js:2059:10 version `0.13.2`.

I initially thought it was a [react-router](https://github.com/rackt/react-router) specific issue. 
[Issue w/ React-router](https://jsfiddle.net/LLv2tfm3/)

Wrong!!! The same issue exists without the library.
[Issue w/o React-router](https://jsfiddle.net/69z2wepo/7889/)

But it doesn't when using a normal SVG element.
[No issue w/o React](https://jsfiddle.net/25jt11qm/1/)

> SVG elements
The following SVG elements are supported:
circle defs ellipse g line linearGradient mask path pattern polygon polyline
radialGradient rect stop svg text tspan

[Source](https://facebook.github.io/react/docs/tags-and-attributes.html)

Although if React doesn't support `<a>` within SVGs it ought to throw an error or something.

Whats the cause of this issue? I'm guessing going with `onClick` would be the viable option right now.

**Comment by piglovesyou** [comment]
This is caused because the current React library does not handle [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString) properly. Right now we should avoid using `a` in `svg` because it's not supported yet.

~Below is Extra information~

The error is easily reproduced by these plain html and JavaScript.

```html
<svg id="mine">
  <a href="original">
    <rect x="10" y="10" width="10" height="10" fill="red"></rect>
  </a>
</svg>
```

```javascript
const a = document.querySelector('svg#mine a');
a.href = 'modifying'; // Uncaught TypeError: Cannot set property href of #<SVGAElement> which has only a getter
```

As long as I know, we should do this when you want to change "href" value of an existing SVGAElement.

```javascript
a.href.baseVal = 'modifying';
```

I can reproduce the same error with React version `0.14.7`. For the record, `v0.15.0-alpha.1` doesn't produce the error because `setAttribute()` is called inside of the library. However it's not enough to set a value of `href`, which means we still should not use `a` in `svg` in `v0.15.0-alpha.1`.

**Comment by piglovesyou** [comment]
This is caused because the current React library does not handle `SVGAnimatedString` properly. Right now we should avoid using `a` in `svg` because it's not supported yet.

~Below is Extra information~

The error is [easily reproduced by these plain html and JavaScript](https://jsfiddle.net/piglovesyou/s7nvq1z0/).

As long as I know, we should do this when you want to change "href" value of an existing SVGAElement.

```javascript
a.href.baseVal = 'modifying';
```

I can reproduce the same error with React version `0.14.7`. For the record, `v0.15.0-alpha.1` doesn't produce the error because `setAttribute()` is called inside of the library. However it's not enough to set a value of href, which means we still should not use `a` in `svg` in `v0.15.0-alpha.1`.

**Comment by jimfb** [comment]
> However it's not enough to set a value of href, which means we still should not use a in svg in v0.15.0-alpha.1.

Sorry, I'm not super familiar with SVG, can you elaborate?  What are we doing wrong in v15?  What should we be doing?

**Comment by piglovesyou** [comment]
You do nothing wrong, React just does not support `<a>` in `<svg>` so nobody should use it and that's all.

What I tried to explain is why the error occurs in `0.13.2` and `0.14.7`. That is because React runs `anchorEl.href = 'newValue'` and fails because `href` of `<a>` in `<svg>` is a getter property.

And I also tried that in `v0.15.0-alpha.1`. Instead of assigning, `v0.15` seems to run `anchorEl.setAttribute('href', 'newValue')` inside of the library. It doesn't throw an error this time. But it **still** fails to update `href`'s value, because all we have to do is `anchorEl.href.baseVal = 'newValue'` when we are in `<svg>`.

Do you want to support `<a>` in `<svg>`, by any chance? I guess it would be hard, because the current architecture cannot distinguish `<a>` and `<a>` in `<svg>`.

**Comment by jimfb** [comment]
@piglovesyou I'm not sure it's true that the current architecture can not distinguish.  We already do things in 0.15 like enable all tags/attributes when within an `svg` tag.  So I would speculate that handling this would be technically possible.  cc @spicyj 

I think the bigger question is: How many of the SVG tags/attributes use getters like this?  is this a singular special case, or are we going to see this type of thing cropping up in dozens of situations with SVG?

**Comment by spicyj** [comment]
It is surprising to me that setting the attribute doesn't work. So writing `<a href="...">` in the HTML works but calling `.setAttribute` does not?

**Comment by piglovesyou** [comment]
Here is my quick research: https://jsfiddle.net/f60pe1aj/3/ and it sais only `anchorEl.href.baseVal` updates its value and expected behavior (others become not clickable links) in Chrome 48.0.2564.116 and Firefox 44.0.2.

> How many of the SVG tags/attributes use getters like this?

Not sure but at least worth to see [one they organize](http://html5index.org/SVG%20-%20SVGAnimatedString.html). I need more study because properties w/ baseVal/animVal interface is [not only SVGAnimatedString](https://www.w3.org/TR/SVG/single-page.html#types-InterfaceSVGAnimatedString).

>  We already do things in 0.15 like enable all tags/attributes when within an svg tag

I didn't know that. Of cource I hope React achieves the bigger support ;)

**Comment by piglovesyou** [comment]
Maybe I was wrong. I think that supporting namespace attribute (at least within SVG) is good. [In SVG1.1](https://www.w3.org/TR/SVG/linking.html#AElementXLinkHrefAttribute) we should use `xlink:href` instead of `href`. In that case `setAttribute`/`getAttribute` just works [as I tried](https://jsfiddle.net/46pf0bss/1/).

**Comment by spicyj** [comment]
Okay, thanks for the followup. xlinkHref in React does that.

**Comment by piglovesyou** [comment]
I see.
