### ISSUE TITLE
How do I extend HTML element

### ISSUE THREAD

**Issue by dexbol** [facebook/react#3853]
For 300ms click delay problem, I need attach four events to a element (onClick onTouchStart onTouchMove onTouchEnd) .It makes a bit tedious that there are so many elements to be clickable.

I can create a element, maybe named `<Tap />`, and receive property ontap and attache four events to the element to implement tap event. But I think it is bad for semantic, tap is a action.

So, the question is how I can extend HTML tag like div, a, em to support tap event, do you have any other ideas for this problem?

Thanks.

**Comment by alitavector** [comment]
Have you tried adding the libraries that remove 300ms delay?

**Comment by alitavector** [comment]
FastClick libraries

**Comment by dexbol** [comment]
@alitavector Thank you. I considered the library. It is my alternative.

**Comment by sebmarkbage** [comment]
We don't have an exposed way to extend the built-in event system. Essentially the problem is that these extensions wouldn't be scoped to a component. It is a global set up and different components with different event systems.

This makes it difficult to share your components with the community. Different event systems may conflict in the same namespace. It will only work in your own controlled environment. We want to make it easy to share and reuse components without conflicts.

So to support this we would need to build it in a way that supports isolation.

This is the major benefit of a wrapper like `<Tap />` since it does support component isolation by default.

**Comment by dexbol** [comment]
@sebmarkbage Thanks for your explanation.

**Comment by kevinSuttle** [comment]
@sebmarkage: Forgive my need for clarity, but by "extend" are you also inferring "override" or "add new" events?

I saw a perfect candidate for this today.
https://twitter.com/rikarends/status/680005032641753088

**Comment by kevinSuttle** [comment]
Sorry, I meant @sebmarkbage.

_Ugh @github mobile. No way to edit a comment, even in "desktop view", whatever that is._

**Comment by kevinSuttle** [comment]
@sebmarkbage Could/should the Sythentic Event System be modified to (what's the opposite of "hoist") scope? https://facebook.github.io/react/docs/events.html

**Comment by kevinSuttle** [comment]
cc: @gaearon @petehunt

**Comment by nhunzaker** [comment]
I think @sebmarkbage's suggestion is valid: make a react component for the behavior and isolate it to that specific use case.
