### ISSUE TITLE
Documentation for controlled components seems contradictory

### ISSUE THREAD

**Issue by jedwards1211** [facebook/react#3860]
In the documentation for [controlled components](https://facebook.github.io/react/docs/forms.html#controlled-components), it says:

```
Form components allow listening for changes by setting a callback to the onChange prop. The onChange prop works across browsers to fire in response to user interactions when:

The value of <input> or <textarea> changes.
The checked state of <input> changes.
```

However my checkbox's onChange handler is getting called even though its checked state dosen't actually change, because it's controlled.  I think the documentation should be changed to state that onChange is fired in response to user input on the component, even if React leaves the component state as it is.

**Comment by syranide** [comment]
That's a bug with checkboxes, but it applies to text inputs too due to browser bugs which have not yet been normalized (and might not be strictly possible). So if you need to explicitly detect only when a change is made then simply test it yourself for now.

**Comment by jedwards1211** [comment]
Now I'm more confused.  As far as I understood, if a `<textarea>` is controlled, but has no `onChange` handler, its `value` (even as shown on screen) shouldn't change when the user types into it.  But if there is an `onChange` handler it gets called with an `event` whose `value` *does* reflect the changes from the user, even though the actual `value` of the `<textarea>` isn't going to change unless the `onChange` handler triggers a `render()` with a different `value` property on the React element.

And as far as I understood checkboxes are supposed to behave the same way.

Have I misunderstood?

Thanks!

**Comment by syranide** [comment]
@jedwards1211 Correct.

**Comment by tbroadley** [comment]
@syranide I'm sorry to bring this back from the dead. Do you know if there is an issue or other existing documentation for the checkbox/text input bug you mentioned?

**Comment by zpao** [comment]
I'm not sure what these bugs are… (unless it's about us having to use other events to simulate `change`).

Everything with checkboxes appears to be working as expected to me and checkboxes are behaving the same way (eg, logging `e.target.checked` in an `onChange` callback tells me the right value, even if I don't call `setState`).

**Comment by syranide** [comment]
@zpao Yeah, my initial answer seems a bit wrong, textinputs are affected by noop change events that I know. But not checkboxes to my knowledge. It also seems to me that this issue is not an issue at all, onChange should always fire when a change is initiated, it can't be any other way, discarding the new value happens *after* onChange.

**Comment by tbroadley** [comment]
I asked because I had a problem where, whenever I changed the application state, every <input> tag in my application would receive an "update attribute" DOM change, even (especially) the inputs that did not change. Now that I think about it more, it's probably a bug in my application, not in React.

Still, I'll try to produce a small example of this problem, and open another issue if I can.

**Comment by tbroadley** [comment]
Issue posted at #5295.
