### ISSUE TITLE
HTML Tag in component props

### ISSUE THREAD

**Issue by JbRezidu** [facebook/react#3868]
Hi,

I'm new in React development and i'm not english so i have some difficulty to understand all things which are possible in react.
Well here, i would like to use some HTML tags in props for a component.

For example : if I have this component :

	var Card=React.createClass({
		render:function(){
			return(
				<Container className="card">
					<Container className="card-content">
						<span className="card-title grey-text">{this.props.title}</span>
						{this.props.children}
					</Container>
				</Container>
			);
		}
	});

I would like to use it like that : 

	<Card title="<div>Mes informations d'identification</div>">
		Content
	</Card>

But the title "div Mes infor... div" still be the same, whereas i would like to have a div with inside the real title.

So I don't know how to use the props of component to have my result...

/Sorry for my poor English/

**Comment by zpao** [comment]
```js
<Card title={<div>Mes informations d'identification</div>}>
    Content
</Card>
```

Note the brackets instead of the quotes. Quotes will always be strings. The brackets will get evaluated, which in this case will give you a new ReactElement. You can then render that exactly like you already have in `Card` (though beware of putting divs in spans!).


You could also assign to a variable first:

```js
var title = <div>Mes informations d'identification</div>;
<Card title={title}>
    Content
</Card>
```

No need to apologize fore your English. In the future though, this is a question best asked on the mailing list or stack overflow (since it's much more about doing a very specific thing in React vs a problem with React).
