### ISSUE TITLE
Formalize a standard Facebook Style Guide

### ISSUE THREAD

**Issue by bhamodi** [facebook/react#3875]
The current "style guide" that is in the contributing docs doesn't cover everything that should be covered. I would like to see that section have a bit more content.

I actually couldn't find a Facebook style guide online publicly anywhere, so this could be a pretty big initiative to have this kind of documentation publicly available. I'm willing to help in this process.

If the above sounds too ambiguous, we could just add more content to the CONTRIBUTING file.

**Comment by Nithyakumaran** [comment]
Hi Bhamodi,

I am computer science graduate student from University of Cincinnaiti. I would like to work on this as my first contribution. Please let me know if this is fine. I have already downloaded the source and searching for build instructions. 

Thank you very much in advance.

Regards,
Nithya

**Comment by zpao** [comment]
I started work on a more formal guide some time ago and haven't had the time to finish. We haven't updated that part of the contributing doc in a while but we've since introduced a bit more tooling to help enforce a lot of our style. Linting now catches many issues and the remaining are hard to define anyway (like what to do when the test of an if statement is too long). For the most part, following https://github.com/airbnb/javascript will get you 90% of the way there.

I think all we need to do at this point is update CONTRIBUTING with some version of what I just said. If somebody is interested in doing that then great.

**Comment by bhamodi** [comment]
@zpao - I can take on this initiative. :+1:

**Comment by bhamodi** [comment]
Addressed in #3894. :smile:

**Comment by marissajasso** [comment]
@bhamodi Hey was this ever completed?

**Comment by bhamodi** [comment]
@marissajasso - yes, this has been done for a while. Check out the style guide here: https://reactjs.org/docs/how-to-contribute.html#style-guide
