### ISSUE TITLE
Get to 0 warnings in tests

### ISSUE THREAD

**Issue by zpao** [facebook/react#3890]
We have some unhandled warnings in our tests, which isn't great. We should clean those up and then we can make it so that any unhandled warnings are test failures.

**Comment by lili21** [comment]
more information about those warnings?

**Comment by zpao** [comment]
When you run the tests (`npm test` may be best for seeing the colored output), it should be fairly obvious what I'm talking about. The warnings are logged to the console between passing test lines.

**Comment by d4rkr00t** [comment]
I get just 2 warnings, and fix first is easy (`ReactChildren should treat single child in array as expected.`). But in the second one `ReactES6Class throws if no render function is defined.` I think it's expected, because there isn't a render method in a Foo class, because it's exactly what test checks. So, is there any way to suppress warnings in a single line, or may be stubbing console is a good way? But i think the second warning should not be fixed.

**Comment by lili21** [comment]
These are some tests , which are meant to test warnings to be thrown. Should I catch it manually or what ? any suggestion ?

**Comment by lili21** [comment]
@d4rkr00t how did you fix the ReactChildren test warnings?  Like this `var simpleKid = <span key="whatever" />` ?

**Comment by d4rkr00t** [comment]
Almost like you mentioned in your not edited comment `simpleKid = <span key="simple" /> `, and i use "simple" as key, because it's used in other similar cases.

**Comment by lili21** [comment]
@d4rkr00t There is a similar spec in `traverseAllChildren-test.js`. Maybe there is another way to fix this ? without add key attribute ? Otherwise How would you test the `should be called for each child in an iterable without keys` spec in the same file ? and of cause, those specs would throw warnings. I don't know how you just got two warnings .

**Comment by d4rkr00t** [comment]
May be i missed something, i'll recheck it later today :)

**Comment by lili21** [comment]
I think I get the key point now. We should spyOn the `console.error` function,
