### ISSUE TITLE
React "Child keys must be unique" warning

### ISSUE THREAD

**Issue by sahanDissanayake** [facebook/react#3893]
Hi All,

Please see the jsfiddle > check the console for the warning

https://jsfiddle.net/n47gckhr/217/

https://fiddle.jshell.net/n47gckhr/217/show/

**Comment by sahanDissanayake** [comment]
Also is the sluggish behaviour expected ?? Thanks

**Comment by zpao** [comment]
What's the issue? You're getting a warning that says child keys must be unique. You have multiple siblings with the same key since you're using `category` (your data isn't sorted by category so you end up with multiple `ProductCategoryRow`s for the same category. Also, you're `ProductRow` is using name for its key, but there are multiple items with the same name, so you'll get the same warning for that.

And last but not least, perf - you're adding / removing thousands of nodes per keystroke. There are a bunch of optimizations you could do, the easiest is to simply toggle a CSS property on rows that shouldn't be shown. By doing that you'll have the exact same DOM nodes no matter what the filter is, you'll just be toggling a single property which is much cheaper than adding/removing nodes. And then using the prod build will be much faster, since there is a lot of code in there for debugging purposes.
