### ISSUE TITLE
question about react.js file in the src folder

### ISSUE THREAD

**Issue by dejour** [facebook/react#3903]
in the react.js file of src folder,is it right not to specifying the path to module in the require statement,or it is just showing dependency on which file,not caring about the path.maybe this is a stupid question for seasoned developer.but i can't figure it out.hope someone can help me understand this.

**Comment by zpao** [comment]
React has a custom module system which needs a build system. This is why none of the `require`s inside `src/` use relative paths. The module system right now is one used internally at FB such that the name of the module is defined inside with `@providesModule Foo` and then resolved with `require('Foo')`. All the modules are globally unique. In order to work with CommonJS we move files and rewrite the require statements such that they are relative. The result of this build step is what is used when we ship to NPM.
