### ISSUE TITLE
Textarea holds old value when prop updated to null

### ISSUE THREAD

**Issue by dyyylan** [facebook/react#3936]
Textarea values can be set with the "value" prop. If this prop is set to null or undefined (such as when resetting an object to clear the form), it will retain the old value. 

Looking at the source, it looks like there is some intentional null behavior written in, but it does behave differently from other form elements.

jsfiddle demo of the problem: https://jsfiddle.net/0saj7ww7/2/

**Comment by syranide** [comment]
#2533 has an in-depth hard-to-follow (partial) discussion on the subject.

The truly proper way to reset values is to set to an empty string, not null. The reason inputs reset is because they reset internally due to becoming uncontrolled, whereas textareas keep the last value (both should have the same behavior, but it's not behavior you should rely on like this).

**Comment by dyyylan** [comment]
I see. Looks like that issue is still open, closing this one.
