### ISSUE TITLE
Server-Side Rendering Help

### ISSUE THREAD

**Issue by weyfarere** [facebook/react#3939]
I'm having a bit of trouble finding a reasonable way to handle server-side rendering while still allowing for SEO. There are three approaches I can think of:

1. Send a bare bones HTML skeleton to the client. After the JavaScript has loaded, make an AJAX request to get the data and render it out.

2. Send a bare bones HTML skeleton to the client bundled with the JSON data necessary to render the page. Once the JavaScript loads, the page is rendered immediately using the JSON.

3. Send the fully rendered HTML page and bundled JSON data together. Once the JavaScript has loaded, React will "rerender" the page using the JSON data.

The first option is the worst. The second option fixes the need for a round trip back to the server to retrieve data, which is a step in the right direction. The third option seems to be the best, but I'm having trouble figuring out an approach.

During the talks at React Conf, there was a suggestion to make two separate components for each piece of functionality, a data-fetching component and a pure UI component. This would allow the server to render markup using the pure UI components without including client-side logic via the data-fetching components.

I'm concerned this will lead to two separate versions of a page's structure to exist, one which the server uses to render the markup and one which is wrapped in "containers" on the client. The UI components used will be the same, but the structure will need to be separately maintained, resulting in changes requiring two updates. Am I mistaken?

For example, let's say we have a `Foo` component and a `Bar` component. The server might look like:

```
React.createClass({
    render: function () {
        return (
            <Column>
                <Foo />
                <Bar />
            </Column>
        );
    }
});
```

However, on the client, the `Foo` and `Bar` components might need to fetch data from the server. The recommendation is to wrap them in containers, so the client-side code might look like:

```
React.createClass({
    render: function () {
        return (
            <Column>
                <FooContainer />
                <BarContainer />
            </Column>
        );
    }
});
```

The idea behind each is the same, but the children of the `Column` component change depending on the environment.  Does this mean I'll have to keep the two versions synchronized anytime I want to add, remove, or update the structure? Is there an established pattern to avoid this?

I'm dipping my toes into React, but I want to make sure I'm structuring it correctly and following best practices. I'm not interested in running Flux on my server, which is why I want to keep the client's "data-fetching" components and their dependencies on the client side.

Are there any recommendations? Have I missed anything?

**Comment by JoshuaGross** [comment]
Hi @weyfarere, I would recommend checking out fluxible.io to start out. AFAICT there are no isomorphic frameworks that are *really* easy to grok, but fluxible comes close: http://fluxible.io/api/bringing-flux-to-the-server.html

Is there a reason you're not interested in running Flux on the server? Regardless, there's no reason to have 2 separate copies of a component - even if you don't want to make API calls on the server, you could wrap the API calls in `if (browser) { ... }` though I wouldn't recommend it.

**Comment by novacrazy** [comment]
I'm currently using your third option. It's not so bad. 

I created a system that can use the exact same component code on the server and then merge and minify it automatically to be loaded all as one as an 'app' on the client side. So it renders a complete web page with data already inserted, then adds code for initializing the app (the initial props), and a bit of mounting code, then it loads up the app separately in a secondary request.

Pretty awesome, really. If the user doesn't have javascript enabled, it doesn't load the app, but still displays the static page, which is fine in most cases, as all my validation is also done on the server side and so forth. And of course having any page work without Javascript plays nicely with SEO as well.

For top-level stuff like \<html\> and \<head\>, I just wrote a small doT template for those and then only render the \<body\> with React. 

I spent quite a while looking for a better solution, but that seemed to be the best way at the time. I'm not too sure about the fluxible.io stuff @JoshuaGross mentioned, but I'm certainly going to look into it.

So for server side rendering using React, I'd definitely recommend the third option. At some point I'll probably end up open-sourcing my solution, but right now it's tied in too closely to my company to do that. However, I can help troubleshoot solutions for you if you want.

The key to rendering on the server side I've found is to collect ALL data needed to initially render it, potentially asynchronously, before you render and then pass those to your top component (though hopefully in the form of a component factory), and then have it pass those props down to however deep they need to be. Do not try to gather information from the server within a component (like in componentWillMount). You'd be limited to synchronous retrieval and you'd need to account for server/client differences.

Additionally, for components that do need to contact the server after they've been loaded on the client, I start up that code in componentDidMount since it's not called on the server, only the client. It can then start making ajax requests and so forth from there without that code ever having to be run on the server. 

As for getting server code to work the same on the client, I use ES6/7 and Babel on all my server code, but using ES6 import/export I can wrap all component files in AMD syntax and merge those together to form nice dependencies and so forth, then use Almond.js to provide define/require on the client. I also have a quite large pre-processing stage that formats all the define statements with module ids, relative to their file location and everything, and ensure any external dependencies (like React, lodash, jQuery, etc) are included as well. I have an older version of that code in my repositories.

Anything I can say more would depend on what you want to do now. As for your concern about React rerendering on the client, it would do that anyway. Funny story, I actually once forgot to re-enable server side rendering from testing some bug and so the contents of the html body were "[Object object]", not the webpage, and I never saw it for a week because React rerendered so fast on the client I wouldn't see the blank page.

**Comment by weyfarere** [comment]
@JoshuaGross I don't want to use Flux on the server because it would introduce needless complexity. The server takes a request with a set of parameters, fetches data from a persistent store, and returns HTML/JSON. It doesn't need to worry about state or multidirectional data flow. It's already dead simple.

@novacrazy When I mentioned two updates, I meant in the sense of altering two separate files. I understand how React handles rendering and re-rendering. I was hoping there would be a solution that would allow me to share *structure* between the client and server. Simply put, I want the structure of a page would be decoupled from the data source. I can decouple singular UI components, but can I compose a section out of those components while keeping it decoupled?

Options two and three have different sets of pros and cons. If I were to render the markup on the server, there's a risk that the JavaScript might take a while to load. This could be due to circumstances out of my control (e.g. - spotty mobile connections), but the user wouldn't be able to interact with certain parts of the interface. While they could still click links and submit forms, it would appear as though everything else is broken.

On the other hand, if I skipped rendering markup on the server and sent a "skeleton" page made up of components in their loading state (along with the JSON embedded in the HTML), it would at least let the user know the page still isn't ready to use. Once the JavaScript loads, it will replace the "skeleton" with components full of data. I believe this is better from a usability standpoint, but it comes with a cost. The perception would be that the page is loading slower (you can't beat the speed of rendering out HTML immediately) and you lose the ability to be indexed by search engines that can't run JavaScript.

Since my website needs to be indexed, I have to render the HTML on the server for each page. I wanted to try React out on a small section of my website to see if it's worth switching over to. While it wouldn't be the end of the world, I would like to decouple a page's structure from how it's given data. This would allow sharing between the client and server.

My site already compiles all the data needed to render a page into a singular JSON object. This allows me to send back HTML or JSON depending on what the client's need. Using Handlebars, I can share the templates between server and client since they're completely decoupled from the data fetching. However, it's a huge hassle when it comes to keeping track of state and doing partial renders on the client. I was hoping React would give me the best of both worlds -- shared structure between server and client while keeping state/rendering simple on the client.

I've spent a fair amount of time reading articles and watching videos about React, but I haven't come across a solution. I was hoping someone here would have a better idea. However, it seems like I'd be trading one set of problems for another at this point. The question would be, which is the more difficult set of problems to maintain? It seems as though simplifying the amount of energy it takes to reason about components may be worth the cost of having to keep two structures in sync.

**Comment by fkling** [comment]
Since this topic doesn't seem to be about a problem with React itself, https://discuss.reactjs.org/ seems to be more appropriate to have this discussion.

**Comment by weyfarere** [comment]
I'll move the discussion to that site. Sorry.
