### ISSUE TITLE
ReactTestUtils: rename find*/scry* pairs to findOne*/findAll* or similar?

### ISSUE THREAD

**Issue by jamesmanning** [facebook/react#3951]
Outside of the [relatively unknown word "scry"](https://twitter.com/angustweets/status/590659867926462465) being used, it's difficult for someone to tell just by name how these differ.  

The current names seem to be based on the original JX.DOM.scry api usage based on #3278 so likely made more sense internally, but as with the person that filed #2301 it would be much more discoverable and easier to use with names that were more obvious for what they do.

For back compat reasons, renaming them and then adding the existing names as pointers with comments/jsdoc saying they're deprecated probably makes more sense, IMHO.

Thanks!

**Comment by blainekasten** [comment]
I would be more in favor of creating a generic query method that takes query stringing using all css selectors + some custom syntax for finding non generic query stringing items (ie refs).

Ideal syntax:
```js
ReactTestUtils.querySelector('.Component__peice > span:last-child *ref="actionButton"')
```

**Comment by jimfb** [comment]
Back in the day, we had a bunch of D&D fans on the team.

For reference:
http://www.dandwiki.com/wiki/SRD:Scrying
http://www.dandwiki.com/wiki/SRD3e:Scry_Skill
https://en.wikipedia.org/wiki/Scrying

Historically, we've used scry to indicate a helper that finds a set of results.  As the framework matures, we should start choosing function names based on what the functions actually do instead of fantasy words that have very little meaning to the typical developer.

**Comment by thenickcox** [comment]
@jimfb @jamesmanning I just wanted to chime in here. As a developer (and native English speaker) with no mental model for scry, this was confusing to me. [Here](http://stackoverflow.com/q/33742899/931934) is my StackOverflow post explaining my confusion. Its upvotes suggest I'm not alone.

**Comment by gaearon** [comment]
I think we should do it, but while we're at it, we might as well consider converging with [the test renderer API](https://reactjs.org/docs/test-renderer.html#testinstance).
