### ISSUE TITLE
reconciliation jsFiddle example not working.

### ISSUE THREAD

**Issue by Alwayswithme** [facebook/react#3978]
The Post [Why did we build React?](https://facebook.github.io/react/blog/2013/06/05/why-react.html) gave an example of **reconciliation** by this [jsFiddle](https://jsfiddle.net/fv6RD/3/).
but It's not working,

If I understand correctly, it should be something like [this](https://jsfiddle.net/vv99ky0g/).

Should I create a PR by change the url to fix it?

**Comment by cody** [comment]
The problem is that it is a https link for a fiddle that only supports http. There are actually more links with the same bug. Updating the fiddles would be one way to fix it, but that is a lot of work. And since the fiddles are part of old blog posts, it would be kind of like rewriting history. In my opinion the best way to fix it is reverting the links back to http. See #3980 for my proposed solution.

**Comment by Alwayswithme** [comment]
@cody I see, thank u

**Comment by jimfb** [comment]
I feel like the more 'correct' solution is to have the fiddle authors update their fiddles.  That said, I don't feel too strongly, and will let @zpao make the decision on this.
