### ISSUE TITLE
`React.cloneElement` doesn't preserve context while deprecated `React.addons.cloneWithProps` does

### ISSUE THREAD

**Issue by rpominov** [facebook/react#4008]
Is this intentional, and what is the right way of cloning elements with `context` passed to them correctly?

Thanks!

**Comment by jimfb** [comment]
I'm not sure if it was intentional, but either way, we aren't going to change this behavior in a point release because it would break things for more people than it would fix.  Sounds like the workaround is to use cloneWIthProps instead, which apparently does preserve context.

Starting with React 0.14, context is parent based anyway, so context will no longer be attached to the element and therefore not impacted by cloneElement / cloneWithProps.

**Comment by rpominov** [comment]
I see, so before 0.14 we can use `cloneWIthProps` and after 0.14 `cloneElement` will just work — sounds good for me. Thank you.

**Comment by mcmar** [comment]
Hi there. It looks like the resolution here is incorrect. This bug is still present in React 15.3.2. I think we should re-open this issue since this is still a problem.
