### ISSUE TITLE
Event is null onPaste event

### ISSUE THREAD

**Issue by message** [facebook/react#4057]
```js
handlePaste: function(event) {
	event.clipboardData.items[0].getAsString(function(string) {
		if (true) {
			event.preventDefault(); // event is null here
		}
	});

	// event.preventDefault(); // event can be prevented here
}
```

Raises Uncaught TypeError: Cannot read property 'preventDefault' of null

**Comment by iamdustan** [comment]
Events are pooled to and recycled to save on memory/GC overhead.

**Comment by zpao** [comment]
Can you preventDefault in an async callback? I would imagine not.

BUT if you do want to persist outside of the event handler then you can just call `event.persist()` and it will get pulled out of the pooled class list.

**Comment by message** [comment]
i want to prevent event based on clipboard data. How the hell i can get it synchronously?

**Comment by zpao** [comment]
If you can't get clipboard data synchronously, then I don't know. You could try persisting as I mentioned and see if calling preventDefault later does anything.

**Comment by fkling** [comment]
You have to prevent the default action immediately. You cannot wait for an async operation, because in the meantime the event will continue to bubble up the tree and be processed.

Your only option would be to always prevent the default action and manually create / trigger a new event if it should not have been prevented. I don't know if this is possible with clipboard data though.

Note that this is not a React issue, that's simply how events work in the DOM / browser.

**Comment by message** [comment]
@fkling that makes sense. Thanks. preventDefault, and then setState;
