### ISSUE TITLE
using the same mixin object twice fails

### ISSUE THREAD

**Issue by yoel-zeldes** [facebook/react#4066]
Lets take the following use case:
There's a utilMixin with a function utilFunc, which is used by mixinA and mixinB.
If I have a class which uses both mixinA and mixinB, it will fail (because react thinks I define utilFunc twice).
Here's a (non-)working jsfiddle: http://jsfiddle.net/csavmegz

In my opinion, react should allow this case of function redefinition, as the new definition === the old definition.
Any thoughts?

**Comment by zpao** [comment]
I actually think we made a mistake ever allowing mixins to be be able to specify other mixins but that's beside the point since this could happen without that.

We've never allowed method redefinition as a blanket statement, with the exception of some lifecycle methods as they can stack. With userspace methods, the intent isn't clear so we don't allow it and I don't know that we'll change our minds there.

cc @spicyj @sebmarkbage

**Comment by sebmarkbage** [comment]
The point of the 0.13 release is that you no longer have to rely on the `React.createClass` abstraction. You can use whatever class system you want.

We probably won't add new features to it, instead we'll defer to the standard class system or third-party class systems that has mixin abstractions.
