### ISSUE TITLE
ReactJS component not rendering textarea with state variable

### ISSUE THREAD

**Issue by MayasHaddad** [facebook/react#4076]
I faced this [issue](http://stackoverflow.com/questions/30730369/reactjs-component-not-rendering-textarea-with-state-variable) recently.

I solved it by using jQuery.

Please run this [app](https://github.com/MayasHaddad/react-flux-textarea-bug) to reproduce.

If it's I who missed up something, my appologies. 

Either way, please, share some wisdom on that thread

**Comment by sebmarkbage** [comment]
Please try to reproduce in a jsfiddle or similar that makes it easier to reproduce. It seems like you got some help switching to `defaultValue` but you didn't explain what the problem was after you applied that fix. We can follow up on StackOverflow.

**Comment by MayasHaddad** [comment]
Thanks, I added this [jsfiddle](https://jsfiddle.net/kr316206/1/).

**Comment by zpao** [comment]
defaultValue doesn't update after initial render. That makes a component "uncontrolled" so that the user interactions are not feeding back into state and the changes the user makes are visible. Controlled components use `value` and `onChange` to explicitly handle user data on each change.

In your example, adding `value={this.state.defaut}` will make the text area update.

**Comment by MayasHaddad** [comment]
Yes, that's the workaround I implemented (value + onChange).
I hoped there was a more elegant way to do so.
I had the answear to my question.
Many thanks!

**Comment by spicyj** [comment]
This is not a workaround; it is the suggested way to build forms for most use cases.

**Comment by MayasHaddad** [comment]
I agree, it's I who didn't understand quite well how `textarea` is specified.

**Comment by MayasHaddad** [comment]
Sorry for wasting your time, I know you guys are doing some great job :+1:
