### ISSUE TITLE
Error running react when NODE_ENV=production

### ISSUE THREAD

**Issue by emptyemail** [facebook/react#4094]
Getting `Cannot set property 'props' of undefined` when running in production. Tried this with versions 12.2 and 13.3

to reproduce
```
process.env.NODE_ENV = 'production';
var clazz = React.createClass({
  render: function() {
    return React.DOM.span({}, this.props.value);
  }
});
var Factory = React.createFactory(clazz);
Factory({
  value: "hello"
});
```

Looking at the code in ReactElement it seems that _store is not initialized in production mode.

**Comment by zpao** [comment]
Unfortunately setting `process.env.NODE_ENV` at runtime isn't going to work. We do some initialization work based on the environment when you require React. I would guess you could set the env before requiring React and it would work but otherwise, we're not going to support dynamically changing environment.
