### ISSUE TITLE
New function getValueLink to accompany valueLink

### ISSUE THREAD

**Issue by kevinsimper** [facebook/react#4106]
When you are building components, you often want to support both valueLink and value/onChange, which means you need a function like this:
```
getValueLink: function(props) {
  return props.valueLink || {
    value: props.value,
    requestChange: props.onChange
  };
},
```

This easily end up being duplicated between components. Would it be an idea to include it in the LinkedState mixin?

**Comment by jimfb** [comment]
As per https://github.com/facebook/react/issues/2302 we're probably dropping valueLink in controlled components.  The LinkedState mixin really isn't used much, and even less so now that people are moving towards ES6 classes.  Also there have been no replies on this thread, which indicates a lack of interest in this topic.  Since LinkedState appears to be on its way out, my guess is that we won't invest a lot of effort in enhancing the mixin and it is mostly legacy at this point.  If you find it useful, feel free to create your own LinkedState mixin for your apps and/or publish it for others to use.
