### ISSUE TITLE
Omit anchors for headers in feed?

### ISSUE THREAD

**Issue by Daniel15** [facebook/react#4124]
The RSS feed (http://facebook.github.io/react/feed.xml) has anchors and "#" links after headings:

```
<a class="anchor" name="migrating-to-babel"></a>Migrating to Babel <a class="hash-link" href="#migrating-to-babel">#</a>
```

This looks kinda ugly in feed readers, and doesn't really serve a purpose:
![screen shot 2015-06-14 at 11 55 35 am](https://cloud.githubusercontent.com/assets/91933/8146715/4f573ecc-128c-11e5-8b36-dad447b7450b.png)

Most feed readers modify links so they're relative to the feed URL, so these links are actually becoming `http://facebook.github.io/react/feed.xml#migrating-to-babel` which doesn't do anything useful.

Can we remove these from the feed?

**Comment by zpao** [comment]
Not super easily right now since that's baked into the markdown processing (https://github.com/facebook/react/blob/master/docs/_plugins/header_links.rb)

**Comment by bryanbraun** [comment]
One option is to render them clientside, using a utility like [AnchorJS](http://bryanbraun.github.io/anchorjs). Anchors wouldn't appear in RSS since the feed content would leave the JS behind. It looks like all the same IDs would be generated, (it uses similar regex code to convert the titles to lowercase hyphen-delimited words).

Let me know if you're interested in that approach and I'll put together a pull request.

**Comment by spicyj** [comment]
@bryanbraun Seems reasonable, though let's just inline the logic instead of pulling in a third-party library (and let's make sure the regex is equivalent in order to preserve existing links). Should only be a few lines of JS.

**Comment by bryanbraun** [comment]
See the approach at https://github.com/facebook/react/pull/4165. It uses the same regex patterns, so the links are backwards compatible.
