### ISSUE TITLE
JSX Compiler broken when pass into anonymous function and one more args

### ISSUE THREAD

**Issue by Huxpro** [facebook/react#4175]
```javascript
React.render(
    <div onClick={
            (function(){
              alert('hey it works')
            })
        } data-test = "test"
    > some text.. </div>,
    document.body
);

```

After compile:

```javascript
React.render(
    React.createElement("div", {onClick: 
            (function(){
              alert('hey it works')
            }, )
        "data-test": "test"
    }, " some text.. "),
    document.body
);
```

in jstransform, which is wrong.

**Comment by spicyj** [comment]
tl;dr

```
<div a={(2)} b={3} />
```

compiles to

```
React.createElement("div", {a: (2, )b: 3})
```

in jstransform, which is wrong. 

@Huxpro You can work around this by removing the parentheses around the function. Please note that react-tools is now deprecated per http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html, but maybe we can fix this anyway.

**Comment by Huxpro** [comment]
@spicyj 

Thank u very much. 
I think the official website should update ;)

**Comment by zpao** [comment]
FWIW, this was fixed in newer versions of JSTransform but there were other changes which resulted in us not shipping an updated react-tools. Both of these projects are deprecated but you can switch to using Babel or the latest jstransform (which now does JSX itself - https://github.com/facebook/jstransform#migration-guide)
