### ISSUE TITLE
ES6: getInitialState as static function

### ISSUE THREAD

**Issue by wereHamster** [facebook/react#4197]
I understand that the old `getInitialState` API design was not ideal. But I disagree that assigning the  `state` instance property in the constructor is any better.

The `getInitialState` function, conceptually, has the type signature `Props -> State`, ie. a pure function converting props to state. Because the old `getInitialState` was defined on the instance, it also had access to `this`. However we can make that function static, therefore making it as pure as JS allows.

In practice a stateful component would look like the code just below.

```javascript
class Counter extends React.Component {

  static propTypes = { initialCount: React.PropTypes.number };
  static defaultProps = { initialCount: 0 };

  static initialState(props) {
    return { count: props.initalCount };
  }

  tick() {
    this.setState({count: this.state.count + 1});
  }

  render() {
    return (
      <div onClick={this.tick.bind(this)}>
        Clicks: {this.state.count}
      </div>
    );
  }
} 
```

Another advantage is that with this construction I don't have to override the component constructor. And the `initialState` function is defined declaratively, in a very straightforward and easy to understand way. Unlike the example from your React v0.13.0 Beta1 blog post which feels like much more magic, and gives the (implicit) `getInitialState` function access to the full instance instead of just the props. For illustration, this is what you proposed in the blog post:

```javascript
export class Counter extends React.Component {
  state = { count: this.props.initialCount };
}
```

**Comment by mridgway** [comment]
`context` can also be important for getting the initial state (for instance with side-loading architectures like Flux), which leads right back to the constructor's signature. I don't see much of a difference whether you do `this.state = { ... }` vs. having the base component call `this.state = MyComponent.getInitialState(props, context)`. You can always implement the static method yourself though.

**Comment by sebmarkbage** [comment]
I'm going to have to quote Allen Wirfs-Brock here:

> this is an OO concept. FP people, this is not for you; don't use it, don't try to "fix it".
> https://esdiscuss.org/topic/named-this-and-this-destructuring#content-3

OO is already broken. Don't try to fix it to be more functional. The current design is there to be natural for someone familiar with building an object-oriented class or using their own JS class system, or something like TypeScript. There are also type inference benefits to doing that since the type of `this.state` can be immediately inferred.

However, React is at its core a FP library so we will definitely add a more functional alternative API that doesn't use instances nor `this` at all.

See this draft for example:

https://github.com/reactjs/react-future/blob/master/07%20-%20Returning%20State/03%20-%20Default%20Props%20and%20Initial%20State.js#L30

I'm not sure it makes sense to combine the two worlds into one. IMO its clearer if you use one style or the other rather than trying to combine them.

**Comment by jimfb** [comment]
No discussion for six months, and I don't see anything actionable here, so I'm going to close this out.
