### ISSUE TITLE
Forward refs / Support getPublicInstance

### ISSUE THREAD

**Issue by cpojer** [facebook/react#4213]
For 0.14 we'd like a feature that allows us to forward refs or define what the public instance of a component should be. That way we can make higher order components that are completely transparent.

**Comment by spicyj** [comment]
@sebmarkbage I told @cpojer this probably wouldn't be hard to implement if we can agree on the semantics. Does findDOMNode (etc) work on the ref you get if you implement getPublicInstance? If not, this might be really easy.

**Comment by sebmarkbage** [comment]
Rant: Yea I've been thinking about this. This feature smells really wrong to me, since the whole point of moving refs off props was to make them an outside-concept that the framework controlled. It seems like if you want to control it, we should just make them props. That way you have the ability to fully control them and the timing. However, you don't always want to have to resolve them yourself. Also, you don't want to accidentally transfer a ref by using the property spread. Although if refs finally become less common, they should probably become manually invoked functions. So I'm torn.

Non-rant: I'm not sure the `getPublicInstance` API is going to be sufficient for other use cases. It doesn't provide the capability to refire.

```js
class Container {
  state = { toggle: false };
  tick = () => {
    this.setState({ toggle: !this.state.toggle });
  }
  componentDidMount() {
    setInterval(this.tick, 100);
  }
  render() {
    return <div>{this.state.toggle ? this.props.children : <Pause />}</div>;
  }
}

class Wrapper {
  getPublicInstance() {
    return this.refs.myComponent;
  }
  render() {
    return <Container><Component ref="myComponent" /></Container>;
  }
}
```

In this example, there is nothing that binds the unmount/remount scenario to the Wrapper. We can't recall getPublicInstance to get the fresh component. We will keep having a stale version.

Something like this might be better:

```js
class Wrapper {
  render() {
    return <Container><Component ref={this.ref} /></Container>;
  }
}
```

However, how do we know that a ref was transferred? Maybe if the function fires before this component's didMount, but that is very subtle and breaks down for the case above where it doesn't fire until later.

Maybe we add something like `getControlledRef` but that's an extra API and would be an side-effectful which is not ideal.

Suggestions?

**Comment by jimfb** [comment]
Personally, I'm a fan of refs becoming manually invoked functions, and so that probably influences my solution...

Make component manually invoke the ref, wrappers can forward the ref.  For now, call it `myref` to avoid the autoinvoking that React does.  Then the wrapper becomes:

```
class Wrapper {
  render() {
    return <Container><Component myref={this.props.myref} /></Container>;
  }
}
```

It's not "completely transparent", since the base component must expose a manually invoked ref instead of relying on the one provided automatically by React, but assuming you're in control of the base component, this works, right?  Or maybe I'm totally miss-understanding the request :P.

**Comment by sebmarkbage** [comment]
The request is to provide a seamless API that is natural to use with React so that HoC can be unobservable.

**Comment by jimfb** [comment]
Could we have a flag on the class that says "I'm a high level component, don't resolve my ref, I'll manually invoke it and/or pass it to someone else"?  That would make the high level completely transparent and also enable a clean migration path for making all refs manually invoked (if we decide to do that someday; migration path is that every component that takes in a ref must have that flag set).

So the new code looks like:
```js
class Wrapper {
  constructor() {
    this.manualRefs = true;
  }
  render() {
    return <Container><Component ref={this.props.ref} /></Container>;
  }
}
```

**Comment by jimfb** [comment]
Or we could just define a getter on props.ref and if it gets accessed then we know it's a HOC.  Getters have performance implications, but if this only gets invoked for HOCs, maybe it's ok?  That would avoid a flag.

**Comment by sebmarkbage** [comment]
We already use static flags for things like context types etc. We might want to use flag to indicate that a component's state is pure too. That seems natural. Could potentially work for stateless functions too.

However, that brings up an interesting point. Should stateless functions automatically transfer the ref since they don't have instances?

**Comment by jimfb** [comment]
My vote would be to have refs be illegal on stateless functions, since there is no component for them to reference.  That allows us to punt on the decision until a future date.  It also gives us a reasonable opportunity to warn if someone tries to attach a ref to a stateless function (since, in all likelihood, the implementor of the stateless function will have forgotten to properly handle the ref, which will lead to user confusion unless we can reject at the time the ref is attached).

Even if refs are illegal on stateless functions, a user of the component can always create their own HOC that wraps the stateless function, so they can always regain any potentially lost functionality, including the ability to attach a ref and use findDOMNode.

**Comment by spicyj** [comment]
> My vote would be to have refs be illegal on stateless functions, since there is no component for them to reference.

Seems like a rather arbitrary restriction to me. findDOMNode is as useful on a stateless function as it is on any other component. (I'm fine with introducing a way to restrict use of findDOMNode but this seems unrelated.)

**Comment by sebmarkbage** [comment]
The use case for stateless functions is basically to A) provide syntax sugar for another component and/or  B) lock down the API by excluding configuration of some props.

For A it would be a nice convenience to forward the ref, but for B it would be detrimental to locking down the API. So I don't know. In cases like that I tend to error on the side of the easiest to change from, which is the more restrictive form - i.e. making refs not work and possibly warn on these.

**Comment by jimfb** [comment]
:+1:

**Comment by gaearon** [comment]
Just bumped into this a few days ago. React now warns when we put a ref onto a stateless component, but I do it from HOC because the user *might* want to have a ref: https://github.com/facebook/react/pull/4943#issuecomment-146434117 

I'm thinking of introducing a prop like `wrappedRef` to my HOC and doing something like `return <WrappedComponent ref={this.props.wrappedRef}`.

**Comment by sebmarkbage** [comment]
...or just use a class for your HoC.

**Comment by gaearon** [comment]
@sebmarkbage 

My HOC is a class, the problem is when the consumer wraps a stateless component.

Pseudocode:

```js
// my library
function connect(WrappedComponent) {
  return class Connected {
    getWrappedInstance() { // people really asked for this method
     return this.refs.instance;
    }

    render() {
      return <WrappedComponent ref='instance' {...this.props} />
    }
  }
}

// user code
connect(class Stuff { }) // good
connect(function StatelessStuff() { }) // emits warning although technically ref isn't even used
```

**Comment by sebmarkbage** [comment]
Ah, yes. That's the same problem that @yungsters have.

What methods are you expecting to forward on that ref? If you use a heuristic such as scanning the `prototype`, then if there is nothing on the prototype then you don't need to attach a ref because you don't have any methods to wrap.

**Comment by sebmarkbage** [comment]
Oh I see, I didn't read properly. You use `getWrappedInstance()` instead of seamlessly exposing the methods like Relay does. In that case, it's not a seamless HoC anyway.

**Comment by gaearon** [comment]
I didn't know Relay forwards instance methods. I'll take a look, thanks!

**Comment by cpojer** [comment]
Relay doesn't forward instance methods in open source. We did this internally so the mixin -> container codemod would be safe. We didn't want to support this pattern externally however and we are hoping for a resolution to this issue inside of React.

**Comment by gaearon** [comment]
I solved my problem by making the ref opt-in on the HOC.
https://github.com/rackt/react-redux/commit/2d3d0beade55477b3af65534ceb793db18b25705

**Comment by gaearon** [comment]
Posted some thoughts on this in #6974.

**Comment by slorber** [comment]
Hey,

Just want to say that also got this problem when using ReactIntl. Like Redux connect() it did provide a {withRef: true} option to pass to HOC: https://github.com/yahoo/react-intl/wiki/API#injectintl

Sometimes we have to espace from declarative programming for some reasons and provide component imperative API (in my case an image cropper component). It's quite annoying when someone just add some component i18n that it actually leads to a serious bug :)

**Comment by the-spyke** [comment]
I'm not sure that forwarding a ref is a comprehensive solution. For relatively simple HOCs it makes sense. But what if a HOC wants to add another instance method or maybe serve as an adapter/decorator? I think I need to:

1. Choose some ref to get instance methods from
2. Have an ability to filter out some of those methods
3. Add my own or override some instance methods

Actually, there're lots of cases, when HOC should be indistinguishable from it's wrapped component for users. This reminds me inheritance in OOP, but for HOCs (what is a little bit dull knowing about OOP unpopularity these days).

**Comment by bradennapier** [comment]
Hmm - not sure if this is possible with javascript directly -- but is it possible to have something somewhat similar in kin to `componentDidCatch` which would allow a HOC to "catch" accesses on undefined properties and choose how it wants to handle such a case?

I may be breaking a thousand javascript laws with this concept but it seems to help with these types of situations with other languages.

Perhaps something as simple as expecting a returned prop to either call or provider to the caller -- or expecting the method calls the function itself and returns the value, otherwise throwing the standard error(s)?

```js
class ForwardUnknown extends Component {

  unknownPropAccessed(prop) {
    if (this._wrapped  && this._wrapped[prop]) {
      return this._wrapped[prop]
    }
  }

  render() {
    return <WrappedComponent ref={ref => {this._wrapped = ref}} {...this.props} />
  }
}
```

**Comment by ThomasRooney** [comment]
I ended up writing the below to solve my problem. This will arbitrarily proxy methods not defined on this class to the wrapped element. I feel dirty but it works. This is inside a HOC that wraps a native element like 'input'.

    elementRef = (node) => {
      this.childNode = node;
      const oldProto = this.__proto__;
      this.__proto__ = new Proxy({}, {
        get(object, key, value) {
          if (oldProto[key]) {
            return oldProto[key];
          }
          if (node[key]) {
            if (typeof node[key] === 'function') {
              return node[key].bind(node);
            }
            return node[key];
          }
          return undefined;
        }
      });
    }

    render() {
      return React.createElement(nativeElement, {...this.props, ref: this.elementRef});
    }

**Comment by bvaughn** [comment]
Still a work-in-progress, but I'm drafting an RFC for this here https://github.com/reactjs/rfcs/pull/30

**Comment by sophiebits** [comment]
An API for this has been added in React 16.3 released today: https://reactjs.org/blog/2018/03/29/react-v-16-3.html#forwardref-api.
