### ISSUE TITLE
Expose SpecPolicy on user defined methods

### ISSUE THREAD

**Issue by sdemjanenko** [facebook/react#4236]
I'm using `Fluxxor` and it sets up Flux event listeners using a `StoreWatchMixin`.  Unfortunately one cannot add a `StoreWatchMixin` to their own mixin and then add that mixin to a component which is already using `StoreWatchMixin`.

What I really want here would be to set `DEFINE_MANY_MERGED` for StoreWatchMixin's `_setStateFromFlux` method.

**Comment by jimfb** [comment]
Can't they use Object.assign to pull in the other mixin into their mixin, and subsequently do anything they want?  Specifically, you can override `_setStateFromFlux` and have the new function call the old one.

We're drifting away from mixins anyway, so I'm going to close this issue, because I don't think we're making further changes to mixins.
