### ISSUE TITLE
Jade?

### ISSUE THREAD

**Issue by Charuru** [facebook/react#424]
All my DOM code is written in jade. Any easy way to use jade in react?

**Comment by d2tstudio** [comment]
Somebody please solve this - I need Coffee and Jade .....

**Comment by crapthings** [comment]
meteor + coffeescript + react + jade
+1

**Comment by rodriced** [comment]
:+1:

**Comment by jiku** [comment]
Haven't tried it yet, but [this](https://github.com/weareoffsider/react-jade-transformer) could be of interest.

**Comment by lamuertepeluda** [comment]
:+1: +1

**Comment by LestaD** [comment]
@zpao open issue, please

**Comment by gaearon** [comment]
React team has no plans to implement template engine integrations, whether Jade or any other system.

As communicated above, we see plain JS (or in case of JSX, superset of JS) nature of React components as an advantage rather than a downside. If you feel strongly about it you are welcome to create a Jade-to-createElement transform but we will not be working on this.

Adding +1’s to this issue doesn’t help anyone and has an unfortunate side effect of clobbering everyone’s notifications. Please don’t do this.

**Comment by sferoze** [comment]
meteor + coffeescript + react + jade
+1
