### ISSUE TITLE
How to bind(this, event, arg1, arg2) in render function

### ISSUE THREAD

**Issue by lovedota** [facebook/react#4247]
Hi friends

``` js
class Test {
   handleChange(event, type) {
      console.log(event); // this shows undefined
   }
   render() {
      return (
         <div>
             <input onChange={this.handleChange.bind(this, event, 'title')}/>
         </div>
      )
   }
} 
```
When I console.log(event); // this shows undefined
How can i access the event thanks !

**Comment by jimfb** [comment]
Unless I'm miss-understanding something, this is a javascript question not a React one.  Also, general usage questions are better located on StackOverflow, as we use github issues to track bugs in React.

Have you tried something like:
```
class Test {
   handleChange(type, event) {
      console.log(event);
   }
   render() {
      return (
         <div>
             <input onChange={this.handleChange.bind(this, 'title')}/>
         </div>
      )
   }
} 
```

I'm going to close this issue, since it's not technically a bug in React.  Feel free to continue the discussion here or on StackOverflow.
