### ISSUE TITLE
What's the best way to properly render <time> tags from a javascript Date object?

### ISSUE THREAD

**Issue by bigblind** [facebook/react#4255]
rendering `<time dateTime={new Date()}>now</date>` renders as `<time datetime="Thu, 28 May 2015 21:30:00 -0000">now</time>`, but that's not [the format that should be used for the `<time>` element](Thu, 28 May 2015 21:30:00 -0000) See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) for more info.

I'm willing to build a custom `<Time>` component, but I want to make sure that one does not already exist, or that there's an existing way to do this that I'm not aware of.

**Comment by Aetet** [comment]
I think Date must be represented as string. At our project we use "YYYY-MM-DDThh:mm:ss[.mmm]"  format. It solves many issues with timezones. As for widget I think you must use existing one, but if you need some customization compose <time> with issue you would like. 

Here is an interesting article about composability in components: https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

**Comment by brigand** [comment]
React could do `.toISOString()` on date objects here, but considering there's no dom property representation of the datetime attribute, the implicit string conversion is expected.

However because it's rare that the date down to the millisecond is valuable information, and the specificity varies a lot, a wrapper would be useful, e.g. `<Time date={new Date()} hours minutes seconds>now</Time>`. That's just string formatting so you could have a reusable function `toISOTimeString(new Date(), ['hours', 'minutes', 'seconds'])`, which could be used to implement `<Time />`  or directly in a dateTime attribute.

**Comment by zpao** [comment]
Great question for the discussion group (discuss.reactjs.com) but it's not an issue with React itself, so I'm going to close out.
