### ISSUE TITLE
Mount new page component after unmounting transition of old one has finished

### ISSUE THREAD

**Issue by gonsfx** [facebook/react#4260]
I was wondering if anyone could provide some insight about how to achieve an animated component/page switch with React.js.

What i'd like to achieve is a component/page transition like the one on http://www.semplicelabs.com/ - a header that transitions opacity and margin-top and a content that transitions opacity.

When a new component/page is shown, the currently shown component/page should transition out before the new component/page transitioning in.

Some code to play around with:
https://jsfiddle.net/gonsfx/xva2g6oo/

**Comment by jimfb** [comment]
This is a perfectly valid question, but since it's not a "bug" in the React core, I'm going to close the issue to take it off our radar, but feel free to continue the discussion here or on StackOverflow.

Animations are super hard.  The best animation library I'm aware of is Ryan Florence's library ( see this great video: https://www.youtube.com/watch?v=z5e7kWSHWTg ).  If I were digging into this, that's where I'd start, because his stuff is awesome.  MagicMove might be exactly what you're looking for.

I know that @vjeux has also been working on animation stuff.

It's probably also worth asking on StackOverflow, because other people might have other great ideas.

**Comment by gonsfx** [comment]
I asked on SO, Twitter, here and was thinking about the React forums at https://discuss.reactjs.org/ where i didn't ask yet.

Just in case anyone is interested to follow along or post a solution:
http://stackoverflow.com/questions/31159787/react-animating-a-page-switch
