### ISSUE TITLE
getting-started.md jsx --watch doesn't work

### ISSUE THREAD

**Issue by amitmtrn** [facebook/react#4269]
The cli command `jsx --watch src/ build/` doesn't work in windows. 

after digging for a while i've found:
http://stackoverflow.com/questions/22739672/react-jsx-watch-does-nothing-after-first-conversion

tried:
```
jsx --watch -x jsx src/ build/
```

and everything works fine now.
Is it doc problem or I miss something in the cli?

I'm running on:
* windows 7
* node v0.10.33
* npm 1.4.28
* react-tools 0.13.3

**Comment by jimfb** [comment]
Do your files have a `.jsx` suffix or a `.js` suffix?  The command in the docs correctly states that it will translate the `.js` file.  It says nothing about `.jsx` files.  Am I correct in assuming that's the problem?

**Comment by amitmtrn** [comment]
@jimfb that's right, didn't notice the suffix in the example *(problem solved)* but,
why is the default suffix is `.js`? if I write `html` inside the `.js` it's not a valid javascript file.
I think that it should be changed to `.jsx` as default.

**Comment by jimfb** [comment]
@amitmtrn Yeah, Sebastian wrote a long rant about this somewhere.  Basically, it's a side effect of the fact that using transforms is now a fairly standard thing to do in javascript.  For instance, if you're using es6 classes, you have to use a transform, but that's technically part of the javascript language now.  What if you're using es7 features?  What if you are using speculative features that haven't reached consensus at TC39?  What if you are using multiple language extensions?  mycomponent.es6.jsx.flow.coffee.whatever?  How do you decide on the order of the suffixes?  It starts to become a mess.  Since transformations are a part of the javascript build/deploy process nowadays, and are here to stay, the decision was made to just call everything javascript.

**Comment by jimfb** [comment]
Update: I found Sebastian's original post I was talking about: https://github.com/facebook/react/issues/3582#issuecomment-90964457

On another note, I think the jsx command is provided by react-tools, which is being sunsetted.  See: https://github.com/facebook/jstransform/pull/81

For this reason, I'm going to go ahead and close this issue.
