### ISSUE TITLE
Getting Started is confused to new starter

### ISSUE THREAD

**Issue by ysihaoy** [facebook/react#4361]
https://facebook.github.io/react/docs/getting-started.html

I followed the step on this page and not working and need to figure out myself.

Should Add some steps about how to start a local server and run the hello world example.

Compared with AngularJS getting started doc, this one is too bad and waste time.

**Comment by jimfb** [comment]
Anyone who doesn't know how to start their preferred webserver is going to have a really hard time making a website using any framework.  We don't specify because it is orthogonal to the framework, and we are agnostic to what web server configuration people use.

I'm going to close out this issue because the only actionable comment is that we don't specify how to start a webserver, but I don't see that as a blocking point.  We need to assume some threshold of prior knowledge.  If you have other actionable feedback as to how we could make the getting started guide more amenable to new users, we can re-examine this issue.

**Comment by zpao** [comment]
Eh, I think this is pretty much the same as #4354 and we'll add something to the docs (#4357).

@ysihaoy - Sorry you had a bad experience. The server piece for compiling JSX files is annoying and not well documented (it also doesn't apply to all browsers). We'll make this a bit better.
