### ISSUE TITLE
Chromium chokes on SVG path element

### ISSUE THREAD

**Issue by kulicuu** [facebook/react#4364]
This is a "Danger: Discarding unexpected node" error in Chromium which breaks render destroying app.  In Firefox no problems.  It's with SVG path command.

```
[...]
    render: ->
        rayy_000 = for i in [0 .. 7]
            i = [0,0,0,0,0,0,0,0]

        svg
            width: '100%'
            height: '100%'
            ,
            mb = @main_board_001()
            path
                d: "M30 40 L40 50"
                stroke: 'black'
[...]
```

In Firefox this renders fine, in Chromium I get a "Danger: Discarding unexpected node" warning and no render.

```
Danger: Discarding unexpected node: <span data-reactid=​".0.0.0">​…​</span>​
Danger: Discarding unexpected node: <path d=​"M30 40 L40 50" stroke=​"black" data-reactid=​".0.0.1">​</path>​
```

full file and project for context at [test.coffee](https://github.com/Terebinth/Vickers/blob/chromium_bug/lib/chromium_testing/test.coffee)

**Comment by syranide** [comment]
React currently generate spans (which is incompatible with SVG) when you supply multiple text children. You'll need to concatenate your strings `<s>{'a' + 'b'}</s>` as opposed to `<s>{'a'}{'b'}</s>`.

**Comment by zpao** [comment]
Sounds like the likely culprit. Feel free to reopen if that's not it.

**Comment by kulicuu** [comment]
Awesome. Thankyou I will try it.

**Comment by kulicuu** [comment]
Okay, I've cleared some things up.  It's happening when in some cases I'm running some functions to establish values from within `render` function.

**Comment by kulicuu** [comment]
Another day of development, have run into more Chromium problems. (Firefox still working fine)
https://github.com/Terebinth/Vickers (MineSweeper)
It renders okay but gameplay graphics behaviour is unpredictable and doing strange things in Chromium.  Like revealing /clicking on a mine turns every other tile black, repeatedly toggling flags with right-click causes tiles to go transparent.  etc

**Comment by zpao** [comment]
If you can reduce that example to something simple then we can try to help you. As is, it's too complex to determine if it's something going wrong with React or SVG or Chrome. You could try reproducing an identical DOM and behavior with vanilla JS and see if the problem persists to help narrow it down.

**Comment by kulicuu** [comment]
I don't understand your reasoning.  If I compile the CoffeeScript to Vanilla, and then submit the bug report again, this will be less complex ?

**Comment by kulicuu** [comment]
I realise also this last is a technically distinct issue from the one that opened this ticket. 

Only relation is that both involve SVG, and both appear in Chrome exclusive of Firefox. 

So I think I should open a different issue altogether.

**Comment by zpao** [comment]
You're giving us an app where something goes wrong but it's several layers deep. I don't really care what language it's in but the fact that I need to look at several components spread across several files with a bunch of state and interactions makes it much more difficult to diagnose and debug. I'm asking you for a [reduced test case](https://www.google.com/search?q=reduced+test+case) so we don't have to spend a ton of time figuring out the real problem from app code. Can you make this happen with a single component? I bet it doesn't only happen with 16 nodes and a whole bunch of minesweeper logic.

> A major clue we have though, in that Firefox is not experiencing any problems whatsoever.
> So it would seem to be some combination of React and Chrome that is the problem.

That's why I said you could try reproducing it with vanilla JS (again, a reduced test case means you don't have to write a ton of code). If you can show that the same DOM works in Chrome but still doesn't work with React then I could say it's React. Right now I could say you've found a bug in Chrome's SVG implementation. There's a non-trivial chance you're right and something that's happening in React is upsetting Chrome but can't prove that right now.

> I realise also this last is a technically distinct issue from the one that opened this ticket.
> So I think I should open a different issue altogether.

It's fine. Once we have it reduced to a test case we can do that.

**Comment by kulicuu** [comment]
Cool cool, thanks for the explanation (what I was looking for).  I'll work on that.  Thanks.

**Comment by kulicuu** [comment]
Not exacly my first attempt at an RTC (have done them a lot from necessity without knowing the term), but in this situation it was hard to reduce very much, as the bug involves user-interaction and visual detail.

Report and such at:
#4398 

Thanks very much for your kind explanation and helpful pointers.

**Comment by kulicuu** [comment]
+1 This is still an issue.  React needs to get good comprehensive cross-browser SVG support.
