### ISSUE TITLE
TestUtils.Simulate.[change/keyDown/keyPress] is not working on a normal input field

### ISSUE THREAD

**Issue by dmatteo** [facebook/react#4375]
I'm having a hard time with `TestUtils.Simulate`, which are definitely not behaving as expected.

Basically I have an input field of type text and I try to change it's content, click it and press some keys.
No rocket science, but all the "editing" stuff fails miserably.

I wrote a small JSBin to showcase what the component I'm testing should do:
https://jsbin.com/hutujemoku/13/edit?html,js,output

And I've also wrote a small repo to showcase the failing tests:
https://github.com/dmatteo/simulate-test

What's going on?

p.s. the bin is running on 0.13.1 while the repo is running on 0.12.2, because that is what I'm using still. Nevertheless, I've also tried with 0.13.3 and it keeps failing

**Comment by dmatteo** [comment]
bump?

**Comment by jimfb** [comment]
Take a look at the uses of `TestUtils.Simulate.change` in https://github.com/facebook/react/blob/master/src/renderers/dom/client/wrappers/__tests__/ReactDOMInput-test.js

Specifically, we call something like `node.value = 'giraffe';` or `React.findDOMNode(instance).value = 'test';` simulating the event.  Similarly, you are going to need to set `inputNode.value = 'whatever'` before firing the event.  I suspect that'll solve your problem.

For future reference, we are using TestUtils.Simulate in our tests/codebase, so if the entire class of events is not working for you, it's likely to be a support question rather than a bug in React.  Support questions are better addressed on StackOverflow rather than in a Github issue.  We try to use Github issues to track bugs in React.  For tracking purposes, I'm going to close out this bug, since I believe it's not actually a bug in React; that will take it off our radar from a bug-tracking perspective.  If the idea of specifying the value before firing the event doesn't solve your problem, feel free to continue discussing on this thread.

**Comment by dmatteo** [comment]
Alright, thanks,
I'll try it asap.

Do you mind if I also update your doc since it's telling something quite different?

**Comment by jimfb** [comment]
Yep, we'd be happy to review a pull request on the docs.  That would be great!

I'd recommend you try to get it working locally before updating the docs, just so you can see how it's working, etc.

**Comment by dmatteo** [comment]
Yes, of course.

Then... I'll be back! [cit.]
