### ISSUE TITLE
Passing callback to setState when using React.addons.LinkedStateMixin

### ISSUE THREAD

**Issue by dmitry-vsl** [facebook/react#4389]
I think linkState should accept the second argument - callback for passing to setState.

Consider [this example](http://jsfiddle.net/89ov1for/). I have a widget that includes a couple of inputs. Whenever any of inputs changes the widget calls this.props.onChange based on values of the inputs. Currently I have to implement my own mixin that passes down callback to setState. 

I think it would be reasonable if arguments for linkState were consistent with setState.

**Comment by brigand** [comment]
In this example wouldn't you want to call `props.onChange` before `DistanceInput` is rerendered? Otherwise if `props.onChange` causes a `setState`, it'll update in the next batch and cause `DistanceInput` to render again. The setState callback (and componentDidMount and componentDidUpdate) are for causing side effects (dom, timers, ajax, etc.).

For the feature request, I feel like LinkedStateMixin has a very finite purpose: trading flexibility for terse two-way binding. If you need flexibility, don't use it in that situation. If you want a different tradeoff, use/make a different tool. That's not to say there's any harm in the change, just that I don't see any value.

**Comment by jimfb** [comment]
Realistically, we probably aren't going to do this.  In fact, we're pulling all the ReactLink stuff out of the core because it's not really a beneficial pattern (https://github.com/facebook/react/issues/2302).  We threw some of the ReactLink stuff into an addon (https://github.com/facebook/react/pull/5718) for now, and will try to pull it out even further later, in an effort to make it easier for the community to fork it and provide their own utilities (if the community finds them useful) or let them die (if the community doesn't find them useful.
