### ISSUE TITLE
Checksum validation only in dev mode

### ISSUE THREAD

**Issue by jimfb** [facebook/react#4401]
Validating checksums is surprisingly expensive.  For a reasonable render, we're wasting 10ms+ generating an adler32.  Double that, because the checksum needs to be generated twice (once on the server, once on the client).

I'm creating this bug more to test the waters than anything else... how do we feel about only doing this check in dev mode?  And failing harder in dev mode if we fail the check (since it would become a very serious problem in production because we would no longer be validating the checksum and thus the expected markup could differ from actual).

It's hard to justify spending so many valuable milliseconds generating a sanity check that we fully expect to pass if developers write their code correctly.

**Comment by jimfb** [comment]
cc @mridgway

**Comment by brigand** [comment]
This is especially felt in small deployments of standard nodejs projects because it blocks the event loop for this time; which adds latency to other active requests (request A is rendering and computing the checksum, request B and C received data from the database but are blocked until this completes; request A gets 10ms extra latency, request B gets 20ms, request C gets 30ms). Perhaps this is more of an architectural problem and extension of renderToString being synchronous, but making the situation worse should be avoided.

+1 for failing hard. It'd be good to add a method of telling react to assume the checksum is invalid and to preserve the current behavior.

**Comment by syranide** [comment]
> And failing harder in dev mode if we fail the check

:+1: It should be a show-stopper, not a slap on the wrist.

I'm curious how significant the impact of the checksum is (relative), and whether or not my suggestion in #4400 to use a much simpler algorithm could make it insignificant. Dropping the checksum entirely means that there is no way to detect a failed resume and a sporadic inconsistency will start spewing unintelligible errors only once the user starts interacting, can be very confusing to debug. Personally I still think "immediate traversal" of the DOM on render is the right way to go, if so, it would provide the necessary safety net (immediate errors if the DOM deviates) without the checksum in production.

**Comment by gaearon** [comment]
We don't validate checksums anymore.
