### ISSUE TITLE
How to implement custom life-cycle hooks?

### ISSUE THREAD

**Issue by tinganho** [facebook/react#4423]
I'm just wondering how I implement custom life-cycle hooks? I want to add a fetch hook for fetch data related to the component. And another hook. I know the former use case will be dealt with Relay.

**Comment by brigand** [comment]
@tinganho the life-cycle methods are just the ones react calls. You can call your own methods in response to any event in your code.

This issue tracker is for issues with react itself, you can ask on stackoverflow and get more detailed answers.

**Comment by tinganho** [comment]
But the problem is that I need to define them as static methods. Is that the recommended approach?

**Comment by jimfb** [comment]
@tinganho I'm not entirely sure what you mean by "I need to define them as static methods".  Lifecycle hooks are defined on the class and invoked on the instances.  Can you elaborate on your concern?

Also, @brigand is correct; we use github issues to track bugs in React, rather than support issues.  I'm going to close the issue in order to take it off our bug-tracking radar; feel free to continue this discussion here, but in the future, StackOverflow is a better place for posts like this.

**Comment by tinganho** [comment]
@jimfb I want to define a custom life cycle hook where I invoke fetching data before mounting. Right now, I can't do it as an instance method. Because I want to do it before it being mounted. And as I see it I can only define a static method `Component.fetch()` and then pass the data as props to my component. If I define it as an instance method then I can't access it because I need to instantiate it.

**Comment by jimfb** [comment]
https://facebook.github.io/react/docs/component-specs.html#mounting-componentwillmount is an instance method that gets called before mounting the component.
