### ISSUE TITLE
update data from rest api 

### ISSUE THREAD

**Issue by n704** [facebook/react#4442]
```jsx

var app = React.createClass({
  getInitialState: function() {
    return {data: 1};
  },
  updateData: function(){
    this.setState(function(state){
        this.getData1(state,function(state,data){
          return data
      })
    })
  },
  getData1: function(state,cb){
      $.get("http://api.openweathermap.org/data/2.5/weather?q=London,uk",function(result){
        data = { data : result};
  // state.data = result
        cb(state,data)
   });
 },
  render : function(){
   return <a onClick={this.updateData} > {this.state.data}</a>
  }
})

```
I have tried this to update state but this is not working. 
only way to update was manully (commented portion) even then it only render on second click  Can you tell me proper way to update state using REST api calls

**Comment by jimfb** [comment]
The primary issue with the code above is that you are trying to mutate `state.data` directly in the ajax callback function.  You will want to move the `$.get` call into your `updateData` function and call setState from within the callback that you pass to `$.get`.  For example usage, I recommend reading through the updating data section in the tutorial: http://facebook.github.io/react/docs/tutorial.html#updating-state

This is more of a question rather than a bug in React.  We use github issues to track bugs in React, so I'm going to close out the issue for tracking purposes.  Feel free to ask questions like this on StackOverflow or discuss.reactjs.org

**Comment by kiki-le-singe** [comment]
@jimfb +1
@n704 you should try something like this:

```javascript
  updateData: function(){
    $.get( "http://api.openweathermap.org/data/2.5/weather?q=London,uk", function(result) {
      this.setState({data: result});
    }.bind(this));
  }
```

**Comment by spicyj** [comment]
(Ideally Stack Overflow. discuss.reactjs.org is better for architecture questions and other high-level discussion.)
