### ISSUE TITLE
Deferred componentDidMount inside Component Tree

### ISSUE THREAD

**Issue by aleskafka** [facebook/react#4448]
**Problem:** I have DOM Elements outside of main DOM Document, where I want to render my React components. When done, some of the original elements will be mounted into main DOM Document. I need to delay `componentDidMount` and schedule it after components are inside main DOM Document.

**Reason:** Mainly because I have some logic inside `componentDidMount` that works with offsets of Element (e.g. controls lazy loading of images). When invoked in seperate DOM, component have wrong idea about where it is on screen.

Is it possible with current version of React (or 0.14) to achieve behaviour, where componentDidMount transaction is invoked later, after I give a signal to root Component? Or will future refactoring allow this use case?

**Comment by jimfb** [comment]
You can't delay componentDidMount; it will be executed immediately after Render.  What you can do is avoid doing the initial render (the call to `React.render()`)until your components are mounted into the DOM.

This sounds like a usage question rather than an issue with the React codebase.  I'm going to close the issue to take it off our bug-tracking radar.  I would recommend asking on StackOverflow or discuss.reactjs.org

**Comment by aleskafka** [comment]
Thanks, I will ask there if my possible solution won't work.

Just for the record, I do not want to delay whole render, because it's the slowest part and I want to have original DOM intact until its done. But looking to source code, I could inject modify ReactReconcileTransaction that will delay notifyAll + destructor until nextTick. Not sure if it will influence other parts of rendering new Root Component, but it seems not.

**Comment by jimfb** [comment]
You might consider `renderToString`, inserting that markup, and then doing a `React.render()`.  That will allow you to have the markup and insert the markup, and the second render (delayed) should be fairly fast.

**Comment by sebmarkbage** [comment]
This is a known issue with the DOM's CSS model. The preferred solution is to always render into a node that is already attached to the document. However, depending on the scenario it is a legit use case to want to create your DOM tree ahead of time, only to later add it into view.

We couldn't automatically detect when something gets attached to the DOM. So we couldn't make any solid guarantees of `componentDidMount` firing. I guess that's not reason to disallow the use case if you can guarantee to call it. We would do it ourselves if we had to DOM hooks, so if your framework around React has those hooks, it might be viable. For example, web components does have that hook.

It's also interesting if what you want is to actually generate the nodes ahead of time or not. E.g. we could generate the HTML string but not apply it until later.

@aleskafka Could you elaborate on your use case and why you're not rendering into the existing document immediately?

Another related scenario that I've considered is temporarily adding a node to the document for measurement and then ripping it back out. For example, this would allow you to measure a subtree (assuming your CSS doesn't rely on position in the document) and then generating the parent wrapper/position after you know the size of the children.

This would cause React to temporarily insert the tree, calculate the layout, fire the componentDidMount callbacks etc. and then rip it back out. Would something like that be interesting to your use case?

@jimfb I'm going to reopen because it's not a question about how to use React. It's pointing out timing issues that can't be solved any other way.

**Comment by jimfb** [comment]
@sebmarkbage If web components have the hook, could we inject a webcomponent into the markup and use that to trigger the `componentDidMount`?

**Comment by aleskafka** [comment]
@sebmarkbage It's still pretty much work in progress, but I will elaborate on my use case. Note, that my applications are server-bound (as I want to use server frameworks and solve non-javascript rendering as well). That's reason for following plugin model.

When javascript is detected, responses from server are pretty light-weight as follows (when not, full markup is rendered):

```html
<html>
  <head>
  </head>
  <body>
    <header></header>
    <div id="sidebar"></div>
    <div id="content">
      <h1>Title</h1>
      <script>var p_12345 = {items: [{id: 1}]}</script>
      <div data-plugin="items:p_12345;"></div>
    </div>
  </body>
</html>
```

Plugin Loader queries all elements with [data-plugin] and handles loading of these plugins by calling e.g. `plugins['items'].load($element, p_12345)`. Plugin `items` is basically React Component `ViewItems` that renders provided `props` from unique variable.

So far so good, because it happens in main Document.

There are some heavy rendered components (Sidebar, etc.), so I want to use ajax and render only `#content` element.

It happens like this:
1. HTTP Request
2. Parse response to DOM fragment
3. Resolve plugins in `fragment#content`
4. unload plugins in `document#content`
5. Replace `document#content` with `fragment#content`.

Rendering itself takes time, so I want to done it in separate Document and mount it right after it's. I have good reasons for this:
1. Better UX
2. When replaced immediatelly into Document, there would be blank element (usually equals to whole page content)
3. Always rendering with `_renderNewRootComponent`
4. When next request is invoked, I can just throw away not mounted elements and not confuse user

> if your framework around React has those hooks, it might be viable.

Yes, I have hooks. I synchroniously parse DOM, load plugins, render React Components (here componentDidMount happens) and mount element. 
Looking at ReactMount.batchedMountComponentIntoNode(), if transaction would be called in nextTick, it would solve everything. It'd be as follows: load plugins, render Components, mount element, trigger componentDidMount, finish DOM ops.

Handling componentDidMount can sometimes take time, so it wouldn't be bad thing to split one synchronous block to two.

> Temporarily adding a node to the document for measurement and then ripping it back out

This could work, but it's trickier than deferred transaction. There might be elements with same id, it's not accurate for detecting position of element, etc.

@jimfb If I renderToString Component, mount it into DOM and render it again. Does it render whole component tree or does it somehow reuse markup and just creates Components objects?

**Comment by jimfb** [comment]
@aleskafka The latter.  It attempts to re-use the markup and just creates the backing component instances.

**Comment by aleskafka** [comment]
@sebmarkbage fyi, I did use modifing ReactReconcileTransaction to achieve this kind of behaviour. The result is module `reactAtomic` with code like this:

```javascript
import CallbackQueue from "react/lib/CallbackQueue"
import ReactReconcileTransaction from "react/lib/ReactReconcileTransaction"

var defer;
export default function reactAtomic(fn) {
  defer = [];

  fn();

  defer.forEach(function(reactMountReady) {
  	reactMountReady.notifyAll();
  	CallbackQueue.release(reactMountReady);
  });

  defer = undefined;
};

ReactReconcileTransaction.prototype.destructor = function() {
	defer ? defer.push(this.reactMountReady) : CallbackQueue.release(this.reactMountReady)
	this.reactMountReady = null;
}

ReactReconcileTransaction.prototype.getTransactionWrappers()[2].close = function() {
	!defer && this.reactMountReady.notifyAll();
}
```

It's probably not 100% percent compatible with original (I assume all of destructed Transaction were closed), but it seems to have no side-effects and works like charm.

I now just call:

```javascript
reactAtomic(function() {
	load($dom);
	unload($into);
	$into.parentNode.replaceChild($dom, $into);
});
```

And it executes `componentDidMount` code after executing code of provided function in `reactAtomic`.
