### ISSUE TITLE
validateDOMNesting warns when optional tags are missing

### ISSUE THREAD

**Issue by joshdmiller** [facebook/react#4464]
According to the HTML 5 spec, [certain tags are optional](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags) in specific circumstances because their presence is implied. However, I'm getting warnings for these cases.

I imagine this complexity is not something worth accounting for within `validateDOMNesting`, but I wanted to call it out just the same.

**Comment by jimfb** [comment]
If a node's presence is implied, it does seem like React could add it without violating the spec, just as the browser does now.  That might be a cute way to get around the fact that browsers add these elements.  Save some engineers a little headache/confusion.

**Comment by syranide** [comment]
@jimfb It's a problem because browsers do add them to the DOM though, we currently allow omitting `tbody` but it can lead to invariant violations in some cases (and it seems unavoidable) so that seems like a really bad idea to continue with... if React could fill them in and not let the browser do it then it should be fine though, but I'm not sure how realistic that is.

**Comment by jimfb** [comment]
Well, if they're part of the spec, then it's well-defined, which means we could fill them in.  I'm not saying it would be easy, but it's an interesting idea.  Especially since we're likely to move away from markup on initial render and use createElement instead, this could be the perfect time to add such logic (or not).

**Comment by syranide** [comment]
@jimfb I'm not sure how solvable it is in practice though, and also, consider the following:

```html
<!-- ok -->
<table>
  <tbody></tbody>
</table>
```

```html
<!-- implicit tbody -->
<table>
  <td></td>
</table>
```


```html
<!-- ??? -->
<table>
  <td></td>
  <tbody></tbody>
</table>
```

What should that last one generate? Especially if you consider it in-terms of being dynamically generated.

**Comment by zpao** [comment]
I don't think it's worth the complexity. We already don't allow optional end tags in JSX. The handful of optional start tags (is `colgroup`, `tbody` really it?) doesn't seem worth supporting, especially since we'd then have to do a bunch of additional tracking in prod.

**Comment by joshdmiller** [comment]
@zpao Adding `html`, `head`, and `body` would complete the list, as far as I know.

**Comment by spicyj** [comment]
If we can add tbody and colgroup implicitly without a lot of extra work, I think that would be nice. I don't care much about any of the other cases since I think they're all invalid when omitted.

**Comment by spicyj** [comment]
@joshdmiller To be clear, validateDOMNesting warns you about cases that are currently problematic in React. If you don't have a tbody (for example), you'll run into problems during reconciliation.

**Comment by syranide** [comment]
@spicyj Ok, another example :)

```html
<table>
  <td key="cell"></td>
</table>
```

```html
<table>
  <td key="cell"></td>
  <td></td>
</table>
```

```html
<table>
  <thead>
    <td></td>
  </thead>
  <td key="cell"></td>
</table>
```

Consider transition from 1 to 2 and 1 to 3. 1 gets an implicit `tbody`, but in example 2 another `td` needs to be added inside the `tbody`, in example 3 the `thead` needs to be added outside the `tbody`.

It can certainly be done, but I assume `table` becomes forced to always pre-process its children before rendering which adds additional cost. Personally I'm curious how meaningful this really is, in HTML is makes sense because it becomes tedious to repeat the same code over and over, but in React you almost exclusively work with components and loops so it's unlikely to ever be a burden.

**Comment by joshdmiller** [comment]
@spicyj Thanks for the clarification - that's helpfjul. In my case, the warnings are actually on neither `tbody` nor `colgroup`. When rendering server-side, the app uses a fairly truncated `Html` component that when thrown to `renderToStaticMarkup` produces errors like the following:

```
Warning: validateDOMNesting(...): <title> cannot appear as a child of <html>. See Html > html > title.
```

However, the following passes the w3's validator and is rendered correctly because the `head` tag can be omitted here:

```
<!DOCTYPE html>
<html>
<title>Test</title>
<p></p>
</html>
```

So far, I'm only encountering a few warnings - and I'm ignoring them. Are you aware of problems this can cause in the React world?

**Comment by spicyj** [comment]
If you try to update the `<p>` tag, React will expect to find it as a child of `<html>` and will be confused to find a `<body>` tag there. It's better to write `<head>` and `<body>` explicitly.

**Comment by jimfb** [comment]
@joshdmiller Also, if you're running React client-side, full page rendering is discouraged because it's so common for extensions and other code on your page to add elements to the body of your page, thereby breaking React reconciliation.

**Comment by joshdmiller** [comment]
@spicy Gotcha. In my case, the update-able components are drawn within a `div` by ID, so that problem *shouldn't* occur because the direct parent will always be the same (unless I'm mistaken about React's internals). However, it definitely explains the necessity of the warning.

@jimfb Good tip. The server renders the HTML as static markup, inclusive of a `<div id="my-app"></div>` that renders the isomorphic components. The client will only ever update that one div.

**Comment by gaearon** [comment]
I think we’ll close this. It’s not hard to type extra `tbody` by hand, and doing this implicitly can lead to surprises.
