### ISSUE TITLE
Automatically add type="button" to buttons without a type?

### ISSUE THREAD

**Issue by kentor** [facebook/react#4516]
It is a well known issue in ie9/10 where pressing Enter on an input can trigger the click handler of an unrelated button somewhere else in the dom, if the button doesn't have a `type`.

I was wondering if React should automatically add `type="button"` when creating `button` elements if `type` isn't already in the props. Or should this be left to userland?

Currently I am monkey-patching `React.createElement` to automatically add the `type="button"`:

```javascript
React.originalCreateElement = React.createElement;
React.createElement = function(type, _props, ...args) {
  let props = _props;
  if (type === 'button') {
    if (!_props) {
      props = { type: 'button' };
    } else if (!_props.hasOwnProperty('type')) {
      props = Object.assign({ type: 'button' }, _props);
    }
  }
  return React.originalCreateElement(type, props, ...args);
};
```

Also wondering if there's a better way to do this.

**Comment by jimfb** [comment]
If we're going to add such a thing, it should probably be added to ReactDOMButton.js rather than to createElement.

Having said that, the default behavior for a button is, I believe, 'submit'.  Defaulting to 'button' sounds like the wrong behavior to me.  I'm assuming that IE 9/10 is finding the next button of type `submit` and emitting an event on that button, in which case, specifying the default value explicitly wouldn't change that behavior.

I would think the best practice is to always specify a type for button.  I think the best we could do is warn if a user doesn't specify the type.  cc @spicyj

**Comment by spicyj** [comment]
Yes, this is in the HTML spec and not an IE bug. Buttons default to `type="submit"`. I recommend you create your own `<Button />` component that has the behavior you want and use it instead. Though I agree that the spec is a little stupid here, this isn't really React's place to change it.

**Comment by kentor** [comment]
Great thanks. You're right, we shouldn't mess with the spec. It's more inconsistent browser behavior where pressing enter would trigger unrelated buttons in IE9/10 but not in Chrome. I'll continue using my patch.
