### ISSUE TITLE
creating Element without React.createFactory /React.createElement / JSX

### ISSUE THREAD

**Issue by chandu0101** [facebook/react#4519]
Hi ,
I am trying to interface with react from scala.js.

```scala
class Hello extends React.Component {
   def render() = {
    React.createElement("div")
  }
}

React.render( new Hello() , dom node) // Invariant Violation: React.render(): Invalid component element
```

To make it work : 
1) Hello is a scala class ,its not available for js world , we can make it available for js world by @JSExport  ing it and then 
2 ) React.createElemnt(js.Dynamic.global.packagepath.Hello,props,..)  / React.createFactory(s.Dynamic.global.packagepath.Hello)(props, .. ) 

its more work for languages that compiles to js and interact with react .. 

is it possible to remove these restrictions! , just allow us to  use default class constructors to  create Elements..

**Comment by jimfb** [comment]
We can't just create an instance of the class using the constructor and use that as an element because a single element can be inserted into the DOM in several places.  We need to create an instance of that class for each insertion point of the element.  This is why elements are not instances of the class.

It's worth reading Sebastian's post on the motivation for the factory pattern: https://gist.github.com/sebmarkbage/d7bce729f38730399d28

I'm not particularly familiar with scala.js, but rather than using the @JSExport annotation (I'm assuming that's an annotation) you might be able to create your own annotation that automatically wraps the output in a call to createFactory before exporting.  That would basically get you what you want.

Short of that, we've tried to keep the burden as low as possible.  Calling a single function (createElement) is about as low as we know how to make it.  If you're looking for something even lower friction (like jsx for scala.js), my guess is that you would need to implement a transformation/extension of some kind for your language.

Since this was/is the best design decision we know of to date and isn't actually a bug in React, I'm going to go ahead and close out the issue.  Feel free to continue the discussion in this thread.

**Comment by chandu0101** [comment]
Fair enough , thank you for detailed answer :) . l'll start search from the other way ..

**Comment by matthewmueller** [comment]
+1 I'd like to be able to separate `createElement` from the rest of the library as well. It's overkill that I need to include all of React in my libraries just to dump out some virtual dom elements.

**Comment by gaearon** [comment]
>It's overkill that I need to include all of React in my libraries

What do you mean by “include React”?

If your library exports a CommonJS module, just `require('react')` and specify it as a `peerDependency`. The user will have to install it themselves.

If you mean a browser build, you don’t need to _include_ React with it. Just make sure your library works if `window.React` (or similar) is defined, and doesn't work if not. A good way to ensure this is to [make UMD builds with Webpack and define React as an external](https://github.com/rackt/react-router/blob/ba36fb8f96adfd2fcb7c2b85286cfffabe37be03/webpack.config.js#L5-L19).

Either way, React should never be included *with* component libraries.

**Comment by matthewmueller** [comment]
Thanks for the response @gaearon. I spent a lot of time evaluating redux this weekend.

> What do you mean by “include React”?

Sorry this comment was a bit vague. Instead of:

```js
React.createElement('div', { className: 'box' }, 'hi')
```

I think you should be able to something like:

```
return {
  type: 'div',
  attributes: {
    className: 'box'
  },
  children: [ { type: 'text', value: 'hi' } ]
}
```

I **think** this is what people are talking about when they say inlining elements, but I haven't dug deep enough in the issues yet. 

Really what I'd like to see is react elements provide the **standard** interface for virtual dom nodes. 

In my case, I'm making a UI library where I could really use React's virtual elements, diff and patch operations, but I don't need the rest of the component lifecycle functionality that comes with React.
