### ISSUE TITLE
Warn if checkbox element has child text/markup

### ISSUE THREAD

**Issue by lyptt** [facebook/react#4520]
It seems that if you're conditionally rendering between two elements then they can't have a different root node, for example switching between an input and a div. In order to get around the issue you have to wrap everything in a common container element for React to be able to handle it.

Sample plunkr is [here](http://plnkr.co/edit/uXXZCctefi4IH22SCtPA?p=preview) which demonstrates the behavior. I'd expect in this case it to switch between showing 'Test' and 'Test 2' when activating the checkbox, instead it ends up duplicating the node.

Interestingly I don't get any errors in this simplified test case, in a more complex app React complains about two unrelated nodes sharing the same React id after activating the checkbox.

**Comment by jimfb** [comment]
You can't put a text node inside a checkbox node.  Browsers will change that for you on the fly (specifically, they will pull the text out of the checkbox), which is what is confusing React.  To solve your test case, pull the text out of the input, where it belongs: http://plnkr.co/edit/j8dM7af9RWgrpUztPkjk?p=preview

I'm going to leave this bug open because we should warn in this case.  Issue is to add a warning when a checkbox contains markup.

**Comment by syranide** [comment]
@jimfb #2266 (warning, not throw) we should already emit warnings for it, unless something broke.

**Comment by jimfb** [comment]
Yeah, I didn't see a warning in the plunkr, which appears to be using React 0.13.3

**Comment by syranide** [comment]
https://github.com/facebook/react/blob/cc98f83b5319f2b4e88792ec0d4ade3d221c9eef/src/renderers/dom/shared/ReactDOMComponent.js#L417 weird

**Comment by spicyj** [comment]
The warning wasn't in 0.13; it will be in 0.14.
