### ISSUE TITLE
ReactMount - refactor to not rely on the DOM

### ISSUE THREAD

**Issue by madjam002** [facebook/react#4523]
As seen here (https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/ReactNativeMount.js#L86)

"As soon as `ReactMount` is refactored to not rely on the DOM, we can share code between the two. For now, we'll hard code the ID logic."

Is this still wanted? I'm working on a project where it would help if ReactMount was not dependant on the DOM as it has a different render target. I don't mind taking a look at doing this, but I just want to check if it's a wanted feature or whether in cases like mine I should just go about writing a completely new renderer.

I think it would be useful as it would make it easier to use React for projects which aren't DOM related.

**Comment by zpao** [comment]
Yes, this is still a goal and a lot of the work in 0.14 is a setup for this. You can read through the 0.14 beta blog post for some more info (though we didn't explicitly call out react-native) - https://facebook.github.io/react/blog/2015/07/03/react-v0.14-beta-1.html#two-packages.

I think the more likely scenario at this point is probably that we'll have a react-native package with its own ReactMount-like implementation. And in fact it's likely that each renderer package will ship its own ReactMount. One of our upcoming goals is to spec out this renderer stuff so that we can give you a more definitive answer.

So I think at this point actually changing ReactMount in react-dom might not be worth it. But let's loop in @sebmarkbage and @spicyj who might have some more context.

**Comment by madjam002** [comment]
Okay cool, thanks for the information. I think it would be cool to see if some of the stuff in ReactMount could be taken out to allow for custom renderers to be a bit more manageable instead of sharing similar code. I need to investigate it more but from what I've seen there is a lot of shared code between ReactMount in react and react-native.

For my project, all I care about is having react components "mounted" in memory as it's all custom components which mixin `ReactMultiChild` or implement `mountComponent` etc.

**Comment by madjam002** [comment]
@zpao So I've gone ahead and written my own ReactMount for my library, however I'm now running into issues with `ReactDefaultInjection` which injects `SelectEventPlugin` which depends on the DOM. When importing React, it looks like it's importing `ReactDOM` which calls `ReactDefaultInjection.inject` and I can't find a way of stopping it.

Do you think it's a good idea to move `ReactDefaultInjection.inject` into the `react-dom` package?

**Comment by sebmarkbage** [comment]
@madjam002 This is the plan yes. We need to keep it in the `react` package for now to avoid breaking everyone using it. However, in 0.14 it is marked as deprecated.

The plan is to get rid of all the dynamic injection completely and only rely on static dependency injection. E.g. overridable module resolution.

You'll probably see a lot of changes in this area the next few months since our goal is to clarify the API for what the "official" way to make renderers should be.

**Comment by madjam002** [comment]
@sebmarkbage Okay thanks for clarifying that. So 0.14 for the time being will be dependant on the DOM then? It would be cool if the injection could be called somewhere else other than when the react package is loaded, maybe in the render function because then other renderers could inject their own plugins? (For now at least until it's all done statically)

**Comment by gaearon** [comment]
We're changing all internals and this will no longer be relevant after a while.
