### ISSUE TITLE
Question: Dynamic Context

### ISSUE THREAD

**Issue by chapinkapa** [facebook/react#4555]
I am trying to have locality specified throughout my app. I thought that using context could be a good solution for this. To achieve this, I need to let the user dynamically change their locale.

Should dynamically changing the context have any negative consequences? I have tested it, and it works, but want to make sure there will not be any negative consequences.

**Comment by jimfb** [comment]
Locale is one of the intended use cases of context, and dynamically changing it (occasionally) is expected (and supported to the extent that context is supported).  Keep in mind that changing context may be somewhat expensive, so avoid setting it every frame or whatever, but yeah.

Only known bug that you might run into is: https://github.com/facebook/react/pull/4344

Closing this out, since we use github issues to track bugs in React, and this is a question rather than a bug.  A better place for questions like this would be discuss.reactjs.org or StackOverflow.

**Comment by chapinkapa** [comment]
Got it. Thanks for the help!
