### ISSUE TITLE
React with Facebook's comments

### ISSUE THREAD

**Issue by honzabrecka** [facebook/react#4563]
Hi, I have a page completely written in React, so in html template is only a `<div id="app"></div>`, and I have to use comments widget from Facebook. I came up with:

```js
React.render(
  <App/>,// creates <div id="fb-root"></div>
  document.getElementById('app'),
  function() {
    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  }
);
```

But, the code above mutates the DOM, which is against React's philosophy. And let's assume that Facebook rewrites this plugin to React, so there would be two React apps - React inside React. Is it OK to include Facebook's comments like this or am I completely on a wrong path? Is it OK to have one React app inside another one (e. g. a video player inside a page)?

**Comment by syranide** [comment]
This assumes 0.14 (to get the DOM node), you're free to do whatever *inside* the safe-div. I've just included the outer div for showcase, it's not necessary.

```js
class Wrapper {
  componentDidMount() {
    doWhateverInside(this.refs.safe);
  }

  render() {
    return (
      <div>
        blabla
        <div ref="safe" />
      </div>
    );
  }
}
```

**Comment by jimfb** [comment]
@syranide is correct.  You can do whatever you want within the children of a leaf node of a React render tree.  React does not prohibit you from using mutative APIs, as long as you don't interfere with nodes that were rendered by React (that is to say, don't mutate a node that was rendered by React, because that would confuse React's reconciliation algorithm).  You can add/mutate children to a leaf node, but don't modify the children to a non-leaf.

We're trying to use github issues to track bugs in React, rather than questions.  For this reason, I'm going to close out this bug.  Feel free to continue the discussion on this thread.  For future reference, questions like this are better answered on StackOverflow.
