### ISSUE TITLE
What is the differ between parent-based context and child-based context,why the child-based context will be lost

### ISSUE THREAD

**Issue by wenshiqi0** [facebook/react#4571]
I want to use the material-ui for my react app.I do the same as material -ui says here is my code 

## index.js
<pre>
<code>
var React = require('react'),
    mui = require('material-ui'),
    ThemeManager = new mui.Styles.ThemeManager(),
    RaisedButton = mui.RaisedButton;
var Index = React.createClass({
    childContextTypes: {
        muiTheme: React.PropTypes.object
    },

    getChildContext: function() {
        return {
            muiTheme: ThemeManager.getCurrentTheme()
        };
    },
    render: function() {
        return (
            &lt;div&gt;
                &lt;RaisedButton label="Default" /&gt;
            &lt;/div&gt;
        );
    }
});
module.exports = Index;
</code>
</pre>

## reactapp.js
<pre>
<code>
(function(){
    var React = require('react/addons')
    var Index = require('./component/index.js')
    var injectTapEventPlugin = require('react-tap-event-plugin');

    window.React = React;

    injectTapEventPlugin();

    React.render(&lt;Index /&gt; , document.body)
})()
</code>
</pre>

First I use the jsx tool to compile this two files and then I use browserify to browserify the reactapp.js to main.js and add it to my pages index.html but it reported this
<pre>
<code>
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (muiTheme) while mounting Paper (see: http://fb.me/react-context-by-parent)

Uncaught TypeError: Cannot read property 'component' of undefined

backgroundColor: this.context.muiTheme.component.paper.backgroundColor,
</code>
</pre>

I did get to the http://fb.me/react-context-by-parent but did not make any sense so how do I solve this?

**Comment by jimfb** [comment]
I'm a little surprised the code above doesn't work.  Are you sure that's the only code in your app?  Specifically, the error message seems to reference a "Paper" component, which I don't see used here, though maybe it's part of RaisedButton.  If you could create a simple jsfiddle that demonstrates your issue, we can investigate further.

We're trying to use github to track bugs in React.  Questions like this are better addressed on StackOverflow.  Since this is not a bug in the current version of React (master has switched to parent context and so this warning is gone), and since this appears to be a question rather than a bug, I'm going to close out for tracking purposes.  Feel free to continue the discussion on this thread, or move to StackOverflow.

**Comment by spicyj** [comment]
In addition, context is not and has never been documented or supported. Please don't file issues asking how to use it.

**Comment by wenshiqi0** [comment]
It works todat,while I still have no point,but it is ok.In fact I do not like the context,but the MaterialUI use this

**Comment by spicyj** [comment]
They shouldn't use it either.
