### ISSUE TITLE
Dont rerender check-box and radiobox

### ISSUE THREAD

**Issue by trquoccuong** [facebook/react#4583]
I make a quiz app with React. When I use logic nextQuiz , all state is ok but this dont change checked info( I dont use any state or props for manage this).
![screen shot 2015-08-07 at 18 05 06](https://cloud.githubusercontent.com/assets/7078282/9134513/f2543f2c-3d2e-11e5-9b60-b3622cc820ac.png)
![screen shot 2015-08-07 at 18 05 11 1](https://cloud.githubusercontent.com/assets/7078282/9134514/f25830d2-3d2e-11e5-9b18-dc1cec8443f4.png)

**Comment by jimfb** [comment]
Calling `setState` on a component should cause it to re-render.  You can force a re-render by using the `forceUpdate` function.

This sounds like a usage question rather than a bug in React.  We use github issues to track bugs in React, so I'm going to close this out.  Feel free to continue the discussion on this thread, or take such discussions to StackOverflow.

**Comment by trquoccuong** [comment]
This not prolem with setState. It rerender but the checked info dont render

**Comment by zpao** [comment]
@trquoccuong take a look at the documentation on controlled components (http://facebook.github.io/react/docs/forms.html#controlled-components). You will likely want to handle the user checking a box so you can set the `checked` prop.

**Comment by trquoccuong** [comment]
I update  new version for easy to debug. Everything rerender but the checked status isn't remove. I can set checked prop to it but I think it not need here. Change question all answer changed but status dont

**Comment by trquoccuong** [comment]
Now I have solution for that http://stackoverflow.com/questions/31881266/reactjs-rerender-input-but-dont-change-checked-status But I think it should be an improvement
