### ISSUE TITLE
Should I set "key" for conditional components?

### ISSUE THREAD

**Issue by baodang** [facebook/react#4605]
For example, if I have two conditional children like

```javascript
<div>
  {showA && <A/>}
  {showB && <B/>}
</div>
```

then should I set "key" for the children?

Without keys, when diff between ```<A/><B/>``` and ```<B/>```, will the result be [remove A, remove B, insert B]?

What if I have many conditional children like that?

I had a look at https://facebook.github.io/react/docs/reconciliation.html but could not figure out the answer. Thanks for help.

**Comment by jimfb** [comment]
If `<A />` and `<B />` are of different types, React will be able to figure it out and do the right thing.  If they are of the same type, you will need to specify keys (otherwise, React has a 50/50 chance of guessing correctly).  cc'ing @spicyj on the off chance I'm wrong, since he is the expert on this stuff.

For future reference, questions like this are better answered on StackOverflow.

**Comment by spicyj** [comment]
No, they get different keys in this case since they are in different slots – a null placeholder exists when the components are not shown so A essentially has a key of 0 and B has a key of 1. If you had something like

```
var children = [];
if (showA) children.push(<A />);
if (showB) children.push(<B />);
return <div>{children}</div>;
```

then you would need keys. 

In the future, please only use this issue tracker for bugs in React.
