### ISSUE TITLE
Links to translated docs

### ISSUE THREAD

**Issue by kohei-takata** [facebook/react#4614]
Now, I've translated some docs into Japanese.
And there are Korean and Chinese docs, but there is no links to them.
How about add links to these translated doc in [Getting Started](https://facebook.github.io/react/docs/getting-started.html)?
If the links is added, we will get more React.js users and feedbacks by them.

**Comment by jimfb** [comment]
cc @zpao since he is the one who manages this stuff.

Our pages are mostly static (maybe with the exception of a little javascript), but...  Seems like the ideal thing would be to detect the user's preferred language from the browser headers, and if it's one of the translated languages, let them know that the translated docs are available and nudge them in that direction (put up a notice banner or something with a link to the appropriate translation).  This way, users see the translated docs regardless of how they reach the site (search engine results, links from forums, etc).

**Comment by zpao** [comment]
This is definitely high on my list of things to do for the docs. I've actually been looking into this recently. Right now the situation isn't awesome and I'd like to get us to a slightly better place before we do this. My biggest problem is that even if you get to the Japanese/Korean/Chinese docs, it's hard to stay there. The sidebar only links to the English docs. It works if you click through the next buttons but that's fragile. #2876 started to solve this but never got got traction, and it's also really fragile (design changes need to be made in 4 places!)

So I'm looking into alternatives and will keep you updated.

**Comment by gaearon** [comment]
Let's continue the discussion in #8063.

**Comment by gaearon** [comment]
We've launched our first translations, and many need more contributors.

https://reactjs.org/blog/2019/02/23/is-react-translated-yet.html
