### ISSUE TITLE
Update WebcomponentsJS to latest version

### ISSUE THREAD

**Issue by Simek** [facebook/react#4630]
Current used version of webpomponents is 0.5.1 from nov 12, 2014. It's a bit of time, change log is quite long: https://github.com/webcomponents/webcomponentsjs/compare/0.5.1...v0.7.11

I'm posting this as enchancement request, because I cannot now test the bump by myself and prepare PR. Also I'm not sure if it's good idea to push this into react 0.14.

**Comment by jimfb** [comment]
Is there something wrong with the old version / is there any motivation for us to upgrade?  (other than just generally good to be up-to-date?)

**Comment by Simek** [comment]
There is no strong motivation IMO. Changes are generaly focused around bug fixing and simplification/efficiency.

**Comment by jimfb** [comment]
Ok, I'm going to go ahead and close this bug out.  Not because we don't want to stay up-to-date, but because there isn't currently a "bug" that results from us being slightly out of date.  We don't ship the webcomponents polyfill to users (it's just for our own testing).  Since we won't get much value from updating, the return on investment is low, so it's probably not worth fixing at the moment.  When there is a new version that has changes which affect us, we can go ahead and update.
