### ISSUE TITLE
Incorrect handling of prefixed styles

### ISSUE THREAD

**Issue by leebyron** [facebook/react#4714]
When rendering a react DOM element with style, the properties of each style object are treated special - e.g. adding px to most numbers, but not to particular styles such as  `flex`.

However, if provided a prefixed style like `webkitFlex` this blacklist of styles is not used.

It would be pretty awesome if any style prefixed with `webkit` or `moz` or the like are first converted to their non-prefixed kind before doing a lookup in that blacklist.

**Comment by zpao** [comment]
They are (or rather we add all the prefixed versions to our lookup table first) - https://github.com/facebook/react/blob/master/src/renderers/dom/shared/CSSProperty.js#L58-L70.

However we're using `WebkitFlex` and `MozFlex` to be JS property compatible (thought it appears `webkitFlex` might be the thing we need to support now too - see #4557). So quick fix (presumably for GraphiQL) is to just use the PascalCase version)

**Comment by leebyron** [comment]
Ah, gotcha. The props described by safari (console typeahead) are camel case, so I didn't think to do that. Maybe toLowerCase() first?

Thanks for the info :dancer:

**Comment by zpao** [comment]
Years ago `WebkitFoo` was the way to do this and showed up in the autocomplete, style object inspection. Everybody thought IE was the special case with `msFoo` (there was `MozFoo`, `OFoo`). There was a "standard" and only IE broke it. But now Opera is gone, `webkitFoo` is what the browsers seem to want, and so `MozFoo` is the odd one out :(

PascalCase was awesome because it made the conversion to stylesheet rule easy - replace capital letter with `-` + lowercase version. Done. But oh well. /rant

**Comment by leebyron** [comment]
Browsers suck
