### ISSUE TITLE
It seems React doesn't allow to render script tag with inline code.

### ISSUE THREAD

**Issue by steida** [facebook/react#4801]
Which is sometimes very useful. As far I know, the only way how to render inline JavaScript is script with dangerouslySetInnerHTML, but innerHTML does not evaluate script. Any solution?

**Comment by syranide** [comment]
@steida `dangerouslySetInnerHTML` is correct, but the mentioned `script` handling is simply how browsers work when setting `innerHTML`, React makes no attempt to change that behavior. Other than for some specific server-side rendering magic (AFAIK) there should never be a need to do this, and it would also be detrimental due to parsing overhead.

**Comment by steida** [comment]
Ok. Thank you for answer.

**Comment by mqliutie** [comment]
I think the code is not evaluated is correct, but I want  to know how did that. 

When I create script element and set innerText of script and appendChild to body, the code was evaluated. So I am very curious about how to achieve the script code are not evaluated in react.
