### ISSUE TITLE
Modding ReactTransitionGroup to work with a wrapped component

### ISSUE THREAD

**Issue by duro** [facebook/react#4831]
I'm not sure if this is the right repo to ask this question in, but I figured I'd start somewhere.

I am working on an app that uses react-router and redux. Using a library called react-redux which exposes a decorator to wrap the component and pass in data from the store as props. So the component that gets passed to ReactTransitionGroup is actually a class called Connect, which has a property called WrappedComponent where the actual component lives. Since all the ReactTransitionGroup lifecycle methods are inplemented on the WrappedComponent, ReactTransitionGroup is not finding them.

I tired extending ReactTransitionGroup and overriding the perform and _handle methods to also look for the lifecycle methods on WrappedComponent, but I get the following error:

```
Unhandled promise rejection ReferenceError: ReactTransitionChildMapping is not defined
```

Here is a gist of the extended class I created:

https://gist.github.com/duro/c58d21cf3183ae01c786

If anyone could point me in the right direction, I would appreciate it.

Thanks!

**Comment by jimfb** [comment]
This looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.
