### ISSUE TITLE
Shouldn't componentWillMount be called before getInitialState

### ISSUE THREAD

**Issue by gnesher** [facebook/react#4844]
I've noticed this while cleaning up older code in one of my components - I have "cleaning" that needs to happen before it loads. Originally placed it within getInitialState which works fine, but really doesn't feel like the right place to put it in.

componentWillMount sounds like the better alternative, but it seems as thought it's called later in the lifecycle (and in fact there's no hook before getInitialState).

I realise this might be a bit of an edge case, but it feels like these two hooks should either be re-ordered or a different hook added?

**Comment by spicyj** [comment]
Can you provide more info about why componentWillMount doesn't work?

**Comment by gnesher** [comment]
@spicyj, my problem is the call order, componentWillMount does get called, but only after getInitialState. This means that if I want to do any type of initialisation on the component (before the state is set) I need to put it in getInitialState which is counter intuitive

**Comment by dmatteo** [comment]
You do what you need to do with your data and then you put in the state in `getInitialState`.
Why is that counterintuitive? 

You are preparing the initial state of your component after all

**Comment by gnesher** [comment]
ok, lets start this again

Component load cycle is:
getInitialState -> componentWillMount

I've expected the cycle to be:
componentWillMount -> getInitialState

The reason I expected that was that in some cases I want to have some code running during app initialisation before the initial state is set and getInitialState doesn't feel like the right place for it.

**Comment by dmatteo** [comment]
I knew what you meant, but I still don't agree

**Comment by zpao** [comment]
As for changing the order, that's a non-starter. `componentWillMount` is right before render (`componentDidMount` is right after). You can call `setState` in cWM. Generally we've said that other initialization happens there, usually it's the fetching of data from other places (which might be synchronous, which is why setState here affects initial render).

It's not clear what "some code" or "cleanup" is so it's a little hard to understand what use case you're trying to solve.

One option is to use ES6 classes - you can make use of the constructor for anything else in addition to setting of initial state.

**Comment by spicyj** [comment]
Closing until we hear more. If you do want to discuss more, a code sample would help.
