### ISSUE TITLE
Is it possible to use ES6 Symbol as component key?

### ISSUE THREAD

**Issue by coodoo** [facebook/react#4847]
Last time I tried it with 0.14 this still won't work, any reason why? Thanks.

**Comment by spicyj** [comment]
Partly just because no one asked for it. We won't do this for 0.14 but it's possible we could for the next release.

**Comment by coodoo** [comment]
Perfect, very looking forward to it!

**Comment by jimfb** [comment]
@spicyj I'm not sure if this is a good idea, unless we plan to drop keys from SSR, because there is no way to serialize the symbols.  We want components to be as isomorphic as possible, and this would break that.

**Comment by spicyj** [comment]
@jimfb keys don't appear in the DOM so it should be fine.

**Comment by jimfb** [comment]
@spicyj They don't?  Aren't they part of the react-data-id when doing SSR?

**Comment by spicyj** [comment]
Not any more.

**Comment by spicyj** [comment]
We do still use them internally though as strings I guess.

**Comment by jimfb** [comment]
Well :hankey:, that's :fire:

**Comment by gaearon** [comment]
Closing as I'm not aware of a compelling reason to allow it. If you see a good reason please send a PR and let's discuss this.

**Comment by MiLeung** [comment]
Late to the party, but...

At first thought, Symbols would just add unnecessary complexity. But it would be nice to use Symbols rather than Math.random [or shortid](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318) for component keys

**Comment by quanganhtran** [comment]
Flattened composite keys for example?
For example if the key could be `parentName1$childName1` we might end up with
```js
const data = [
  { name: 'abc$def', children: ['gh', 'x'] },
  { name: 'abc', children: ['def$gh', 'y'] }
]
```
We will have key collision at `abc$def$gh`. Sure the example is very specific so I cannot argue how common is this use case, but if the names come for the user then it might happen no matter what delimiter you use

**Comment by Sleepful** [comment]
I don't understand why this was closed? The compelling case is having an ES6 way of defining random keys without having to use a third-party library. Not all rendered arrays have an identifying property and we are forced to use things like UUID because using the index leads to bugs. [StackOverflow related answer](https://stackoverflow.com/questions/52705335/will-using-uuid-to-as-list-keys-cause-unnecessary-re-renders-in-react)

**Comment by floriansimon1** [comment]
Not having this forces us to have global integer counters in the scope of our Redux reducers, because we don't have identifying data. We don't want to introduce a library for something so silly, or do something overly complex like writing a key function that transforms the whole object to a string. Using Symbol is the best thing we could hope for in this case.

**Comment by powelski** [comment]
I'm now creating a feature where I use enums as Symbols and I'm rendering a list of them. I was surprised React doesn't allow Symbols as keys, as they make the best keys possible.
