### ISSUE TITLE
 Stateless function components do not work with native arrow functions

### ISSUE THREAD

**Issue by ntkoopman** [facebook/react#4856]
When you blacklist "es6.arrowFunctions" from Babel, the following will stop working and you will get the error "Uncaught TypeError: not a constructor".

```js
import React from 'react'
import ReactDOM from 'react-dom'

const App = () => <div>Hello world</div>
ReactDOM.render(<App />, document.getElementById('root'))
```

**Comment by zpao** [comment]
Hmm, that doesn't sounds good. It's because we `new` it up before falling back to assuming it's a stateless component. Maybe we can check for `Component.prototype === undefined` before `new`ing in [`ReactCompositeComponent#mountComponent`](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L139-L153) cc @sebmarkbage @spicyj

**Comment by sebmarkbage** [comment]
Babel doesn't polyfill that. In 0.15 we will check that it extends React.Component before newing. We can't do that yet in 0.14 because we didn't warn about not extending until 0.14.

**Comment by sebmarkbage** [comment]
I guess checking for undefined in 0.14 would be reasonable as an intermediate step
