### ISSUE TITLE
Video not fire onEnd event after video end

### ISSUE THREAD

**Issue by ShinyChang** [facebook/react#4905]
I used react@0.14.0-rc1 to test video.

I noticed the onEnd event not fired after video end.

Fiddle: http://react.jsbin.com/nopafa

**Comment by syranide** [comment]
`onPause` is fired though (Chrome, not IE) and since React only mirrors the native video/audio events this is simply mirroring browser behavior I assume (unless you can actually observe `onEnd` with native listeners). I wouldn't be all that surprised if this is actually intended behavior for some reason, but someone needs to dissect the standard to be sure of that.

**Comment by zpao** [comment]
You have a mistake in your code. You have `onEnded={this.onEnd}` but `this.onEnd` doesn't exist, it's `this.onEnded`. When I change that your code is logging fine (Firefox 43, Chrome 46)

**Comment by ShinyChang** [comment]
Wow, thank you.
So big mistake.... :(
