### ISSUE TITLE
ES6 Classes don't bring anything to the table.

### ISSUE THREAD

**Issue by igl** [facebook/react#4937]

**Comment by kmeht** [comment]
At least one reason was to reduce React's API surface area and defer to standard JS conventions when possible (i.e., React is not in the business of providing a class abstraction).

From that, it follows that defining React components is less opinionated, allowing users to use whatever langauge/sugar they like: https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#other-languages

Agreed that manual binding is annoying, but that should be solved with ES7+ Property Initializers: https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es7-property-initializers

**Comment by yaycmyk** [comment]
I'm inclined to agree with @igl. There's a lot of useful automagic that disappears with classes and it becomes very tedious to create an es6 class-compatible flavor of mixin that also implements the shared lifecycle events like `componentDidMount`.

I've been using the new syntax in an internal project for a few months and am toying with the idea of going back to the `createClass` way because it just feels so much better to work with and requires less manual rigging.

**Comment by zpao** [comment]
Feel free to continue using `createClass`, it hasn't been removed nor deprecated.

This is a great topic for the discussion forums but is purely noise in our issue tracker, please move to https://discuss.reactjs.org/ if you'd like to carry on.
