### ISSUE TITLE
React.js requires ReactDOM.js

### ISSUE THREAD

**Issue by steveorsomethin** [facebook/react#4938]
This means that custom React implementations cannot use react-dependent libraries (react-router) without preventing ReactDefaultInjection.inject() from running, and also results in a fair amount of bloat as unnecessary DOM-related files are included in the build.

As I understand it, the react core and react-dom are now separate so as to prevent this issue. Why would react core transitively require react-dom? Wouldn't this also prevent someone from using react-router in react-native?

cc @mjackson @ryanflorence in case I'm missing an obvious solution. Thanks all.

**Comment by zpao** [comment]
These are not truly separate yet. 0.14 is deprecating the DOM APIs but they are still there so that we can do this gracefully. I think the plan is to separate more / entirely for the following release.

As for React Native, there are still some special overrides happening there. We're working on getting that all working well but there are probably issues with using React Router there.

**Comment by steveorsomethin** [comment]
I see, thanks @zpao. I'll talk to the react-router guys. We had previously discussed a hook for parameterizing react-router around a react implementation but that was a couple months ago, and I think they were expecting the separation. I'll link back if anything fruitful comes up.

**Comment by zpao** [comment]
Cool, going to close out in the meantime.
