### ISSUE TITLE
scryRenderedDOMComponentsWithClass for multiple class names in 0.14-rc1

### ISSUE THREAD

**Issue by gpbl** [facebook/react#4952]
Some of my tests are failing in 0.14-rc1 because `scryRenderedDOMComponentsWithClass` does not accept multiple class names [anymore](https://github.com/facebook/react/commit/e704503dc78476076c9f12e5147f26b0725c1e35#commitcomment-13362637). E.g. [testing a node](https://github.com/gpbl/react-day-picker/blob/master/test/DayPicker.js#L137-L139) that does have multiple classes:

```js
const nextButton = TestUtils.findRenderedDOMComponentWithClass(dayPickerEl,
      "DayPicker-NavButton DayPicker-NavButton--next");
expect(nextButton).to.not.be.undefined;
```

giving the result:

```
$ Error: Did not find exactly one match (found: 0) for class:DayPicker-NavButton DayPicker-NavButton--next
```

Is this change in the API necessary? Or: how should I test this kind of nodes?

**Comment by zpao** [comment]
This wasn't the best API before and wouldn't always work then (if the node had another classname in between the 2 you specified, it wouldn't work.

This is unfortunate and I suppose we could make this better. We could also just revert #4058.

@spicyj I'm pretty sure I know your feelings here but should we make this work better since it is a regression?

**Comment by spicyj** [comment]
Wow, I don't know my feelings here. I guess I would probably make it actually work.
