### ISSUE TITLE
Invariant Violation: Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by seekshiva** [facebook/react#4957]
I get this error whenever I try to use any plugin.

References: yuanyan/boron#11, casesandberg/react-bounds#4.

Since others aren't complaining about this issue in those repos, I'm bound to think it might be something with my setup.

Can someone help me resolve this issue?

**Comment by zpao** [comment]
Can you share what your code looks like?

**Comment by seekshiva** [comment]
```
var bounds = require('react-bounds')
class MyComponent extends React.Component{
  render(){
    return <div>some usual stuff...</div>
  }
}

module.exports = bounds.wrap(MyComponent)
```

All other part of my code works fine. All I did was add the require statement on top, and the bounds.wrap in the end.

**Comment by seekshiva** [comment]
I'm unable to reproduce it in a sample app...

Could this be because react is being used as an external dependency? (the react-with-addons script is loaded directly to the DOM, so that every single JSX file doesn't need to manually require it)

Would that be the issue?

**Comment by seekshiva** [comment]
Ok. Got it.

**Comment by seekshiva** [comment]
It happens when the React is being loaded separately in the DOM, and not `require()`-ed directly in the script.

Any idea why?

**Comment by gaearon** [comment]
>It happens when the React is being loaded separately in the DOM, and not require()-ed directly in the script.

Maybe https://github.com/facebook/react/issues/2402? Two different Reacts won’t play together. In this case, your NPM dependencies are dragging NPM React into the build, but you also have a separate global React.

**Comment by zpao** [comment]
Yea, multiple React versions seems the likely culprit.

**Comment by seekshiva** [comment]
Yeah. That was it...


I now do this in my webpack entryPoint:
```
const React = require('react')
window.React = React
```

This way, the rest of my components can continue to directly access window.React, and it won't cause any of the above issues.

**Comment by Zacqary** [comment]
Just wanted to add to this thread for the sake of anyone else who finds it on Google like I did.

We were still running into this error even after using a solution similar to @seekshiva's `window.React` declaration. Turns out, it was because we were building two different webpack bundles: a `plugins.js` file (import third-party plugins, set them to globals), and a `react.js` file (import React components, expose some of them as globals if other parts of the codebase that's not yet Webpack'd needs to refer to them).

The problem is that we were setting `window.React` in the `plugins.js` bundle.

So, if you're dealing with a situation where you're migrating a big codebase to Webpack/modules over time, and some parts of it still need to refer to React as a global: make sure you set up that global in the same Webpack bundle that you're using `require('react')` or `import React from 'react'` in.

**Comment by jimfb** [comment]
@Zacqary Yes, also: https://gist.github.com/jimfb/4faa6cbfb1ef476bd105

**Comment by seekshiva** [comment]
I've moved on to directly importing React into my jsx files when I started linting

**Comment by sunnybogawat** [comment]
If you are using webpack.conf then add the following block there it will solve your issue

   ```
 externals: [{
        'react': {
          root: 'React',
          commonjs2: 'react',
          commonjs: 'react',
          amd: 'react'
        }
      }, {
        'react-dom': {
          root: 'ReactDOM',
          commonjs2: 'react-dom',
          commonjs: 'react-dom',
          amd: 'react-dom'
        }
      }]
```

**Comment by gaearon** [comment]
Externals are only necessary if you're using a UMD build of React from a separate <script> tag.
