### ISSUE TITLE
testing scrolling events with scrollTop + scrollHeight

### ISSUE THREAD

**Issue by alexcurtis** [facebook/react#4971]
I can't seem to set scrollTop or even simulate a scroll for a component within my unit tests.

For example:

```javascript
const component = TestUtils.renderIntoDocument(<.../>);
const node = React.findDOMNode(component);
node.scrollTop = 290;
TestUtils.Simulate.scroll(node, { target: node });
```

Debugging through it seems after scrollTop set, its still 0. Scroll handler does get called, but scrollTop still returns 0. scrollHeight also returns 0. Normally thats because it cant scroll, but the elements seem right to me -- height smaller than the contained object's height, etc.

render function:

```javascript
render(){
    return (
        <div style={...} onScroll={this.onScroll}>
            {this.props.children}
        </div>
    );
}
```

Elements:

```html
<div style="overflow-y:scroll;height:80px;" data-reactid=".0">
    <div style="height:900px;display:block;width:500px;" data-reactid=".0.0">
    </div><span data-reactid=".0.1"></span>
</div>
```

**Comment by zpao** [comment]
`renderIntoDocument` doesn't actually insert the node into the document (it is probably not well named, sorry). Here's exactly what it does:

```js
  renderIntoDocument: function(instance) {
    var div = document.createElement('div');
    return ReactDOM.render(instance, div);
  },
```

As you can see, we don't actually append `div` to document, so positional properties won't be useful.

In your case you can do this yourself. Something like

```js
var div = document.createElement('div');
document.body.appendChild(div)
var component = ReactDOM.render(instance, div);
// test things
ReactDOM.unmountComponentAtNode(div);
```

The reason we don't do this is because we wouldn't be able to unmount reliably and then your tests would be tripping over each other in the DOM. Unmounting is critical in that case. But if we don't actually attach to the DOM then we can just let our test framework cleanup the documents when we're all done.

**Comment by alexcurtis** [comment]
@zpao Brilliant! Thank you so much for clearing that up. Its had me stumped for ages.
