### ISSUE TITLE
Docs/Website request: Performance statistics

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react#4974]
It would be valuable to have React's performance stats documented. 
I mean, [this whole page](https://www.quora.com/Pete-Hunt/Posts/React-Convincing-the-Boss) of @petehunt's content would be great, with callouts to details around performance.

**Comment by jimfb** [comment]
We've discussed this internally before, and while no binding decisions were made, the general consensus was to not do this.

There were a few reasons:
 * Performance benchmarks rarely tell the whole story.  Suppose you measure the cpu runtime of your library, and it's the fastest... does that make you the best?  Maybe.  But maybe not... what about the amount of memory your library uses?  Or the download size of your library?  Or a whole host of other factors that can have substantial impact on the overall quality of your website experience, but aren't measured by cpu runtime alone.  It's virtually impossible to define reasonable benchmarks which correctly incorporate all the variables with the correct importance coefficients.  Indeed, the very definition of importance depends on your use case.
 * Optimizing synthetic benchmarks can actually be detrimental to overall performance.  You can optimize the re-rendering of a single node a million times, but unless that is actually what happens when you render your site (pro tip: it never is) then your benchmark is measuring the wrong thing.  Optimizing that benchmark can actually encourage writing code that performs worse on real sites.
 * Performance is a race to assembler.  You want to choose the right balance of developer productivity, code maintainability, with other variables like performance.  React does so much more than simple templating, but that comes at the cost of performance.  We believe that providing higher-level abstractions which are more maintainable and easier to work with is worth the tiny bit of overhead introduced by these abstractions.  But it's a balance.  You can always do better by removing layers of abstraction, but ultimately computer science is all about controlling complexity.  If you eliminate all abstractions, you end up with something like assembler (asm.js) which is great for machines but which humans can't read.  You're going to have a hard time building a website if you can't read your own code.  Competing on performance would lead us to eliminate abstractions which we believe are worth the cost.
 * Comparing apples and oranges.  There are very few frameworks which do everything React does, and vice versa for every other framework.  A benchmark is only fair if it is comparing equivalent frameworks, but the feature sets of various frameworks varies so widely that it's virtually impossible to find an equivalent framework and thus impossible to create a fair benchmark.
 * Ultimately, the performance metric that matters is: Is it going to be easy for me to build a fast website with React?  We believe the answer is yes.  And our rapid growth across the industry (and internally at Facebook) seems to imply that others agree with us.

Of course, we might change our minds in the future, but the thinking at this point is that we are not going to create a page that tries to compare React performance with other frameworks.  We believe that React is fast for real-world use cases, and we believe you'll like it if you try it.  We can re-open the issue if our thinking dramatically changes on this issue.  Feel free to continue the discussion on this thread.

**Comment by iamdustan** [comment]
One thing that is interesting to myself (and I suspect the community in general) is general React performance characteristics against itself and on real devices over time. While I care quite little about React versus Ember or Angular, I would love to see things like http://samsaffron.github.io/ember-performance/?ember=1.8.0 and https://meta.discourse.org/t/the-state-of-javascript-on-android-in-2015-is-poor/33889 being published with React information.

**Comment by toddparker** [comment]
I agree that performance is a tricky thing to benchmark but it seems that we should try to offer some comparable data other than file size because that's not a good proxy for real-world performance. I think trying to benchmark parse and execution times for the the most minimal, core framework vs. a full build  with all the bells and whistles is helpful, especially if measured on real devices running iOS, Android, etc. is key. What runs smoothly on a desktop system can hang up for many seconds on a less power Android or Windows phone device, or just fail to boot up altogether.

We found that even running a fairly trivial todo app could take an unacceptably long time to download, parse and execute on popular MVC frameworks:
https://www.filamentgroup.com/lab/mv-initial-load-times.html

Sure, you can't directly compare any two frameworks because each has different feature sets and goals, but I think it would be very helpful for developers to know that framework X might not be a suitable choice if it takes 5 seconds to boot up a minimal app. 

Incidentally, we didn't update the article charts but we did add react to the data set and it was quite speedy:
https://docs.google.com/spreadsheets/d/136H3Aof5dDc8pSsGQ1VcCbPnwp_HldEcvnxU-ARd89M/edit?pli=1

**Comment by spicyj** [comment]
@toddparker Am I reading your data right that React was much faster than Angular and Ember in your test, and competitive with Backbone, with these times? 

device | React time
--- | ---
PC, Cable | 0.26 s
PC, 3G | 1.10 s
Nexus 5, 3G | 1.26 s

![image](https://cloud.githubusercontent.com/assets/6820/10210481/46e492fc-679c-11e5-8aea-c4d1e0384552.png)

**Comment by toddparker** [comment]
@spicyj - yeah, React performed quite well compared to Angular and Ember in this particular comparison so it seems promising. Here is an updated chart:

![todo-mvc-performance-summary](https://cloud.githubusercontent.com/assets/359929/10221319/a22a2f3a-681b-11e5-8ea1-16c3813088c1.png)

**Comment by kevinSuttle** [comment]
And Polymer?

**Comment by toddparker** [comment]
Polymer didn't have a TodoMVC example that we could use during testing but from our initial research at the time, Polymer was very heavy with all the polyfills required. I know the team is doing a lot of work on improving that so it may be quite a bit better now.

**Comment by addyosmani** [comment]
@toddparker we just landed an updated Polymer 1.0 TodoMVC implementation in master. Would you like to take a stab at benchmarking that again? Similarly interested in figures :)

**Comment by jonkoops** [comment]
@toddparker Those versions seem kind of out of date, some where released almost a year ago. Here are the release dates of the versions in the infographic and the current stables:

- Ampersand (no release date specified), latest: 3.0.6 (**Sep 22, 2015**)
- Angular 1.3.6 (**Dec 8, 2014**), latest: 1.4.7 (**Sep 29, 2015**)
- Backbone 1.1.2 (**Feb 20, 2014**), latest: 1.2.3 (**Sep 3, 2015.**)
- Ember 1.9.0 (**Dec 9, 2014**), latest: 2.0.2 (**Sep 6, 2015**)
- React 0.12.2 (**Dec 18, 2014**), latest: 0.13.3 (**May 8, 2015**)

Like @addyosmani said, Polymer is missing from this comparison. But I think it's due for an update on the existing listed libraries as well.

**Comment by samccone** [comment]
@toddparker you should be able to test the todo implementation now with ease :)

**Comment by kevinSuttle** [comment]
So, this issue still closed? @sebmarkbage, would appreciate some input from you when you get a moment.

**Comment by toddparker** [comment]
@jonkoops - Yep, that's an old article and we're not planning on being the long-term keepers of these benchmarks since it's actually very time consuming to set these up and run the data. We were mostly hoping to spur some of the libraries like React to take performance seriously and publish some form of benchmarks so developers could compare the performance characteristics of each framework. Sadly, there hasn't been as much movement on this front as we'd hoped.

We picked TodoMVC because it gave us the same functionality implemented in across multiple frameworks. However, these examples are set up for learning, not performance so we had to do a lot of work to concat and compress files to better replicate a realistic production environment. If each of the examples on TodoMVC had a uncompressed and a compressed (production) version up on a server, then it would be a lot easier to run automated testing and tabulate results as each new version is released.

**Comment by kevinSuttle** [comment]
Right, closing the issue so quickly and dismissing it doesn't look great. I kind of don't care about other frameworks in comparison to React. I care about what impact it's going to have in the context of what I'm building. For that, I need numbers.

**Comment by syranide** [comment]
> Right, closing the issue so quickly and dismissing it doesn't look great. I kind of don't care about other frameworks in comparison to React. I care about what impact it's going to have in the context of what I'm building, and more importantly, who I'm building it for. For that, I need numbers.

@kevinSuttle My opinion. Benchmarks are almost universally skewed towards measuring specific synthetic micro tasks, intentionally or not. Micro benchmarks are trivial but also meaningless in this context, benchmarking realistic workloads for frameworks is incredibly hard. There are also meaningful thresholds that benchmarks consistently overlook, 5ms vs 10ms is largely irrelevant, but 50ms vs 100ms is an enormous difference... these are often lumped into the same result, without any consideration to fair weighting either.

Then you also have to consider developer time, manual DOM interaction will always win hands down, but you'll never see someone apply that for large-scale apps. So consider the cost of implementing and maintaining UIs made in different frameworks as well; given too little developer time then you will find React components will always outperform manual DOM interaction, and probably look and feel a lot better too, also be far more maintainable and less error-prone, how do you quantify this in a benchmark?

Take it with a grain of salt, but consider that many Angular projects will at some time encounter problems with performance and will resort to various hacks to get performance back up to acceptable levels. React users may face the same problems but I would argue that these problems are far more intuitive to solve in React and the solutions largely come out much more robust. Developer time is important too, and lack of developer time is usually what causes performance problems to crop up in the first place.

Anyway, if you want to know whether React is a good choice for you I would suggest quickly prototyping various aspects of your UI and *feeling* it, those are the only factually accurate results you're going to get. Personally I will always choose the React model, the advantages for our developers and code base is far more important to me, if we encounter demanding use-cases where React isn't performing well enough we can easily break out of React briefly without degrading the quality of our code.

**Comment by gaearon** [comment]
>Right, closing the issue so quickly and dismissing it doesn't look great. I kind of don't care about other frameworks in comparison to React. I care about what impact it's going to have in the context of what I'm building, and more importantly, who I'm building it for. For that, I need numbers.

Which numbers? [The comment above](https://github.com/facebook/react/issues/4974#issuecomment-143924915) explains why no particular set of number tells the story.
