### ISSUE TITLE
Support Pointer events specification

### ISSUE THREAD

**Issue by plievone** [facebook/react#499]
What is your approach to IE10 touch events?

Hammer.js checks `window.navigator.pointerEnabled || window.navigator.msPointerEnabled` and then switches `touchstart`, `touchmove`, `touchend touchcancel` to `pointerdown MSPointerDown`, `pointermove MSPointerMove`, `pointerup pointercancel MSPointerUp MSPointerCancel`.

**Comment by deepsweet** [comment]
[Pointer Events now in Firefox Nightly](https://hacks.mozilla.org/2015/08/pointer-events-now-in-firefox-nightly/)

**Comment by jfahrenkrug** [comment]
If I understand this correctly, we can only simulate a `pointerDown` event when we have first-class pointer event support in React, correct? I've looked at the source code of https://github.com/zilverline/react-tap-event-plugin/ (and this issue https://github.com/zilverline/react-tap-event-plugin/issues/10) and am very impressed with the sophistication of the React event system. No news on pointerEvent support as of yet, though?

**Comment by aaronshaf** [comment]
Any update on this? I am adding/removing pointer event listeners for in the component lifecycle.

**Comment by KeitIG** [comment]
Same question here, I'd love to see it implemented soon.

**Comment by klimashkin** [comment]
Really needed since pointer events are in Chrome now and going to be shipped in FF

**Comment by MilllerTime** [comment]
I wrote a component that allows declarative pointer event binding, and has been working for me as an easy substitute until React officially supports them.

 [`<Pointable />` component gist (see comment for usage)](https://gist.github.com/MilllerTime/53d67483cc908bdccbcd2a88dbf21838)

I've been wanting to put it on npm but haven't found time to setup a dedicated build for it yet, or extract the tests out of my current project. It's a single dependency free component, so should be easy to drop into your project if you need pointer events.

While it's great Chrome and FF are shipping pointer events, Safari is my biggest worry. To that end, this component plays well with the official [pointer events polyfill](https://github.com/jquery/PEP) project for wide support.

**Comment by chaffeqa** [comment]
I would love to see this... the parody between `onPointerEnter` and `onMouseEnter` is sooooo useful for user experiance

**Comment by anthonybarsotti** [comment]
@spicyj Is this issue still something we'd want to implement?

**Comment by philipp-spiess** [comment]
If we don't provide a polyfill and just add support for it in the [`SimpleEventPlugin`](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/eventPlugins/SimpleEventPlugin.js), the implementation should be relatively straight-forward, right?

This will still allow people to use the popular [polyfill](https://github.com/jquery/PEP) if they need pointer events on different platforms. React would simply handle this as another type of native events (similar to `SyntheticMouseEvent` and `SyntheticTouchEvent`). If this is something you want to implement I'd love to give it a shot 👍

**Comment by MilllerTime** [comment]
@philipp-spiess Even if pointer event support is added to React, integrating with PEP will still require manually setting/removing the [touch-action](https://github.com/jquery/PEP#polyfill-limitations) attribute since it's a non-standard workaround required by PEP. Supporting Safari/iOS seems fairly important and `touch-action` would still be a pain point.

That being said, if pointer events are added to React, I'll update [Pointable](https://www.npmjs.com/package/react-pointable) so it handles `touch-action` and allows React to do the rest.

**Comment by philipp-spiess** [comment]
@MilllerTime Thank you for your input! I agree that the `touch-action` API is inconvenient. My idea was to simply make React understand pointer events and pool them like touch or mouse events.

Since support for Safari and iOS is vital, we could write a small guide somewhere as well where we explain how a user can set this up with the polyfill. Either by using your package or adding the `touch-action` property manually.

If a more out-of-the-box support for this polyfill is desired, we could also whitelist the `touch-action` property on HTML elements [here](https://github.com/facebook/react/blob/b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L176-L204).

**Comment by caub** [comment]
so React still doesn't support `<div onPointerDown={console.log}>foo</div>`

that's quite annoying

**Comment by elijahdorman** [comment]
Firefox 59 just shipped with support for pointer events enabled. There's now mainstream support for every browser except Safari.

**Comment by chaffeqa** [comment]
sounds about right 🙄

**Comment by jquense** [comment]
If anyone would like to add support it's pretty straightforward to add native events. Take a look at `SimpleEventPlugin` and how the other native events are supported.

There is a question about whether React should polyfill the behave for old browsers, but I think it'll be safe to start with just allowing the native events if anyone wants to give it a shot
