### ISSUE TITLE
Custom elements `children` prop gets coerced to string

### ISSUE THREAD

**Issue by helly0d** [facebook/react#5088]
Hello,

In React 0.13.3 HTML5 custom tags were rendered fine. For example:

```javascript
//... render function
  return (
    <my-custom-tag className="active custom-class" >
      <div>Hello World</div>
    </my-custom-tag>
  );
```

would render:
```html
<my-custom-tag class="active custom-class" data-reactid=".1">
  <div>Hello World</div>
</my-custom-tag>
```

Since I am in the process of migrating to v0.14.0 i saw that the above renders like this:
```html
<my-custom-tag classname="active custom-class" children="[object Object]" data-reactid=".1">
  <div>Hello World</div>
</my-custom-tag>
```

I can set in the JSX the property to be `class` instead of `className` and it will render with `class` attribute in the custom tag, but I am afraid this is not the intended behavior. If this is the intended behavior please close the issue and give me some documentation, because I tried to find something related to this for the last 5 hours.

**Comment by andreypopp** [comment]
Dup of #4933

**Comment by jimfb** [comment]
You can use `class` instead of `className`.  This behavior was chosen because we needed to support arbitrary attributes on custom tags.  That's what #4933 is discussing, and we're probably going to keep that behavior unless someone comes up with a better idea.  We'll keep that discussion in that thread other.

The `children` attribute is being set to "[object Object]" - that seems like wrong behavior to me.  We can use this issue to track that regression.

**Comment by jimfb** [comment]
I've wanted to do https://github.com/facebook/react/issues/4694 for a while.  I think this might be another motivation to reconsider that issue.
