### ISSUE TITLE
Custom element can't render `children` and `childNodes` independently

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5090]
Also, it should be possible to specify a component that sets the children attribute and the components child nodes independently.

example:

```
<my-web-component children="2">
    <div>myChild</div>
    <div>myOtherChild</div>
</my-web-component>
```

This is related to (a superset of) https://github.com/facebook/react/issues/5088.  This might be another motivation to reconsider #4694, which I've wanted for a while.

**Comment by syranide** [comment]
I think this is a fundamental problem with "catch-all properties" components. DOM defines a model where all nodes can have accept ANY named attribute and only a single set of children (not set through attributes), this does not apply to most other frontends that may have widgets that accept more sets of children (or none) and not uncommonly through widget-specific APIs and the distinction between children and props may be not nearly as trivial. This is even how some well-designed complex user components are implemented! (I'm sure you have components like this at FB too)

The DOM model makes sense for JSX as it is implemented right now (because it's based on DOM), but it would be detrimental and unnecessarily opinionated for React. There may be alternatives to JSX (or extensions) that make more sense for other frameworks, so I think making sacrifices in React for the sake JSX/DOM to be premature.

---

Theoretically, the API for "catch-all" components really should be:
```js
<my-web-components otherSpecialProp={} props={mapWithArbitraryProperties}>
    ...children...
</my-web-components>
```

Yes, it's horrible and not something I'm advocating for HTML, but that's how you would design any other component that takes arbitrary properties + a fixed set of predefined properties, not by making intrusions into React.

**Comment by jimfb** [comment]
@syranide Yeah, it's not just the DOM though.  Most (all?) layout systems do have the notion of a "more special" value that represents the hierarchy of descendants nodes.  XML (and by association, all XML based layout systems) already have this notion built in.  JSX also already has this notion built in - but we happened to pick a prop name ("children") and conflate the two, though it's not entirely obvious why we've done it or what it solves.  Anyway, I digress, perhaps those points are better made on #4694.
