### ISSUE TITLE
Building with "grunt build" ends up with an error 

### ISSUE THREAD

**Issue by amertak** [facebook/react#5132]
Hi,
I have a problem when trying to build react using the installation manual,
running ```grunt build``` ends up immediately with

```
Running "delete-build-modules" task
Fatal error: spawn node_modules\.bin\gulp ENOENT"
```

I have Windows 10 x64.
Running ```gulp``` creates all the modules in the build folder so I dont know.
Friend of mine has the same issue.

The reason I am trying to build react is adding custom SVG elements and attributes (more https://github.com/facebook/react/issues/1657#issuecomment-47708471)

Thanks

**Comment by edvinerikson** [comment]
What node version are you running? Can you try to run `npm install` again?

**Comment by amertak** [comment]
Node is v4.1.1 

I tried ```npm install``` couple of times. Deleting node_modules folder, installing packages, deleting npm cache and so on :/

**Comment by amertak** [comment]
Just a little update.

I installed Ubuntu into Virtual box and after couple of tries I was able to compile it.

Finally.

**Comment by edvinerikson** [comment]
The problem seems to be in the Grunt config: https://github.com/facebook/react/blob/master/Gruntfile.js#L31.
Switching `cmd: path.join('node_modules', '.bin', 'gulp'),` to `cmd: path.join('node_modules', '.bin', 'gulp.cmd'),` solves the problem. 

This bug seems to have been introduced when we switched some build steps to gulp https://github.com/facebook/react/commit/1d0c1b18170768d71105dee55cb8bbd3674f8251.

**Comment by amertak** [comment]
Thanks, that solves the issue :)

**Comment by zpao** [comment]
Thanks for the heads up by the way. You should be able to build now but let us know if you encounter other issues! Nobody on the team is currently building on Windows so I wouldn't be surprised to see a couple more things like this pop up.
