### ISSUE TITLE
"TypeError: Cannot read property 'toUpperCase' of undefined" in some case instead of "___ component not defined"

### ISSUE THREAD

**Issue by vonwao** [facebook/react#5177]
this happens in meteor, however I'm almost positive I did not have 2 versions of react (not sure how I could check that)

<img width="1247" alt="screenshot 2015-10-14 20 15 15" src="https://cloud.githubusercontent.com/assets/377000/10501609/5fd7e118-72b1-11e5-8abb-6716982f7ed1.png">

**Comment by zpao** [comment]
There's not a lot for anybody to go from here to be helpful. I suggest working this out on stack overflow until you can narrow it down to a case that you think indicates a bug in React. And when you have that, please provide a test case so that we can try to diagnose. I'm going to close out in the meantime.

A quick suggestion: turn on "break on caught exceptions", which will throw you into the debugger on React warnings. Go back up the stack for that createElement warning. That's a big red flag to me. You may be using a factory in JSX, or have a require that failed to resolve.
