### ISSUE TITLE
Confused about performant way of key usage with a list of fixed count

### ISSUE THREAD

**Issue by titoBouzout** [facebook/react#5182]
Hi there! I searched lots, but I'm still confused about what is the best way to get the maximum performance in DOM operations and also CPU and memory usage. I can do lot of assumptions, but I would like to ask please. 

I've a list with an always fixed count of 500 items (lets say 5 to illustrate the example), the list is a stream, new elements frequently get pushed and old elements are removed .  List sample:

    <div>
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
        <div>5</div>
    </div>

```javascript
    var state = [{id:0,t:'A'},{id:1,t:'B'},{id:2,t:'C'},{id:3,t:'D'},{id:4,t:'E'}] 
    // a new element insertion will append for example {id:5,t:'F'} and remove {id:0,t:'A'}
```

1 If I render the list like in the example bellow, react will remove from the dom the first item, and append a new one. Because each element in the list has a unique ID. If I insert 100 elements, react will remove 100 divs and appends 100 divs. 

```javascript
	render: function () {
		return <div>
					{this.state.items.map(function(item, index) {
						return <div key={item.id}>{item.t}</div>
					})}
				</div>
	}
```

1.1 Q: In this example react will create and destroy a new component everytime I push and remove an item? If so, maybe consumes more CPU?  Removing the first div and appending a new one may be less expensive in DOM operations than the next example?

2 If I render the list like this, react will NOT remove the first div, it will update the text content of all the divs. Because the ID is the index of the element in the list, will be always 0 for the first element.

```javascript
	render: function () {
		return <div>
					{this.state.items.map(function(item, index) {
						return <div key={index}>{item.t}</div>
					})}
				</div>
	}
```

2 1 Q: In this example react will reuse the component instead of destroying and creating a new one everytime I push and remove an item? If so, maybe consumes less CPU than the first example?  Updating the context of each div may be more expensive in DOM operations than in the previous example?

So I don't know what is the best way to handle this, to be honest I'm not even sure what reacts really does, and what scare me most is what browser internals do. 

I can image that for a list with very few amount of elements maybe option 2 will be prefered. and with a huge list of elements option 1 is prefered. Im saying non-sense? =c)

I also can guess this will depend of the content of the div, if the content of the divs is always same, the option 2 will be like a "noop" and the option 1 will remove and append a new div every time, 
I'm right?

Thanks in advance! Sorry for asking here

**Comment by jimfb** [comment]
It all depends on the specifics of your application.  Ultimately if performance is an issue, you should run your own perf tests to figure out which option is the fastest for your app.

In general, the first option should be faster.  Additionally, the first option is preferred because it keeps component state attached to the current component.  If you shift IDs as in your second example, not only do you have to update every DOM node... you are also re-mapping existing components (and their internal data) to new values.  Suppose the user inputs text in item D's text box (`{id:3,t:'D'}`), and you push a new item to the end, the text would now appear in item E's text box (`{id:4,t:'E'}`) which is not what you would want.

If you are unsure, you almost certainly want the first option.

This is a usage question, and we try to keep github issues for tracking bugs in the React core, so I'm going to close this out.  Please ask usage questions on StackOverflow in the future.

**Comment by titoBouzout** [comment]
Thanks a lot jim :)
