### ISSUE TITLE
Issue with extended Array<T> as Component.props

### ISSUE THREAD

**Issue by tsiselskyi** [facebook/react#5251]
In component ctor this.props.groupBy function is undefinded. This behavior is correct ?
This is not a problem actually, but it is very strange for me )

![editor](https://cloud.githubusercontent.com/assets/1548409/10683236/6310a3e0-7948-11e5-9824-17f5795ecf99.png)

![console](https://cloud.githubusercontent.com/assets/1548409/10683239/696573ec-7948-11e5-81c1-5639a3731f8d.png)

**Comment by zpao** [comment]
React does a shallow copy of props so you don't maintain the prototype. So `manifests` in your ctor is not `===` what you're passing to createElement. You're better off passing it as a single prop, eg `{manifests: manifests}`.

I've seen this pop up once or twice but can't find an issue where we've answered this before so I guess this might be it. I'm going to close out because I think we intend to continue with this behavior but cc @spicyj who might be able to back me up.

**Comment by spicyj** [comment]
Yes, @zpao's right here. We have to inspect the object you pass to pull off `key` and `ref` if they're provided.

**Comment by tsiselskyi** [comment]
>> React does a shallow copy of props
but it would be useful. If Component is a some kind of View, this.prop is like ViewModel, no?
 
u right, it is not an issue(or problem), just question.
