### ISSUE TITLE
dangerouslySetInnerHTML inside a textarea ?

### ISSUE THREAD

**Issue by andyfenelon** [facebook/react#5303]
is there any way to do this ?

you can see from the example here what i'm trying to achieve
https://jsfiddle.net/bbqscoy1/

so the emoji's render inside the text area, is there any way to dangerouslySetInnerHTML the value of the text area ?

**Comment by fkling** [comment]
Please use the GH issues for bug reports.

Setting `innerHTML` on a textarea doesn't make sense, whether it is React or not, since the current value of the textarea is kept in the `.value` property of the DOM element. Also, textarea's don't render HTML. Maybe you want a `contentEditable` diff instead.
