### ISSUE TITLE
Simplify definition of propTypes default values

### ISSUE THREAD

**Issue by pke** [facebook/react#5314]
Given that a component has defined property types:

```
propTypes: {
	leftAction: React.PropTypes.func,
	leftArrow: React.PropTypes.bool,
	title: React.PropTypes.string
	},
```

if also would have to define the default values for each property 

```
getInitialState () {
  return {
    leftAction: null,
    leftArrow: false,
    title: ""
  }
},
```

I propose an alternative syntax:

```
propTypes: {
	leftAction: [React.PropTypes.func, null],
	leftArrow: [React.PropTypes.bool, false],
	title: [React.PropTypes.string, '']
	},
```

react could also have a reasonable default fallback, if a property value has not been defined. For bool it could be `false` for `func` it could be `null` and for strings it could be an empty string. For required properties you shall not specify the default value.

**Comment by jimfb** [comment]
Proptypes are mostly legacy and in maintenance mode, having been replaced by tools like Flow.  My guess is we aren't going to change this, but @zpao can decide if the issue should be closed.

**Comment by pke** [comment]
What for the users that do not want to put Flow on top of react?

**Comment by jimfb** [comment]
@pke If you don't want to use flow, there are a few options:
 * you can use another static analysis or type checking tool (like typescript).
 * you can check proptypes manually.
 * you can write your own proptype validators as we did for React (as a library, and/or share those validators with others who may also find them valuable).
 * you can continue using proptypes as-is, since we aren't getting rid of them in the immediate future (though they are likely on their way out as other tools like Flow start to become more complete).

**Comment by pke** [comment]
Thanks for your tips! I think there is already a TypeScript `tsx` variant out there, I will try that.
