### ISSUE TITLE
React no longer works with recent versions of es5-sham (4.1.8)  with React 14.1 in IE8

### ISSUE THREAD

**Issue by bitfrost** [facebook/react#5323]
React 14.1 won't load with es5-sham versions greater than 4.1.7  (IE8)    React 14.0 will work with any version of es5-sham up to 4.1.15 (time of this writing).  Not sure of this a bug in es5-sham introduced in 4.1.8  I will dig into root cause and follow up.

**Comment by zpao** [comment]
Did 0.14.0 cause issues? We did make 1 change around the defineProperty usage in 0.14.1 but it shouldn't have resulted in issues.

Let us know what you find!

**Comment by bitfrost** [comment]
React 0.14.0 loads/works with all versions of es5-sham, including latest.  0.14.1 starts breaking with versions of es5-sham after 4.1.7 .   I will follow up when I have time to dig a bit deeper.

**Comment by zpao** [comment]
Related… https://github.com/facebook/react/issues/5324.

I think at least part of the issue is that we changed how we check for the ability to use defineProperty. es5-sham explicitly supports the simple use of defineProperty but throws when trying to set a getter. Previously our try/catch used a getter, so we were treating es5-sham the right way. We simplified some code and removed the getter in 0.14.1. That is almost certainly what's causing this issue, though perhaps there is another.
