### ISSUE TITLE
Suggestion: deprecating jsx

### ISSUE THREAD

**Issue by co-dh** [facebook/react#5325]
I would like to suggest to deprecate jsx format.
- pro:
    - easy to match closing tag with eyes
- fake pro: 
    - Designer friendly?
      No really, designer still have to know everything about javascript to write web page, and even more, they need to know all javascript tools to build.

- cons:
    - It encourage ugly deeply embedded code
    - It create a whole dimension in the ecosystem of javascript. Every editor need to have a syntax highlighter, formatter, linter for it. Every language that compiles to javascript might need to support jsx.  DefinetelyTyped have better support for tsx than ts. ( ReactDOM.div don't check properties in ts)

**Comment by andreasbhansen** [comment]
I'm aware that this isn't Reddit, but...

*grabs popcorn*

**Comment by gyzerok** [comment]
If you don't like jsx just don't use it. It is easy.

**Comment by jimfb** [comment]
We have observed substantial increases in developer happiness+productivity with JSX and believe the benefits outweigh the downsides of extending Javascript.  JSX is optional and you're free to use pure ES5 if that is your preference.

I'm going to close out this bug, since deprecating jsx is not something we're likely to do, but feel free to continue the discussion here.
