### ISSUE TITLE
Inconsistency with "propTypes" and "contextTypes".

### ISSUE THREAD

**Issue by DylanPiercey** [facebook/react#5349]
Although contextTypes are only recently document in react and the api is still unstable I find it odd that these two similar annotations (that accept the same react prop validations) don't work the same way.

With propTypes, if you omit a propType you still receive the property, propTypes simply validate properties. However with contextTypes this is not the case, you only receive the context if you set a validation for the contextType.

I would assume (if I were new to both features) that I would be given context automatically if there is any passed to my component (similar to props). However I am forced to explicitly state which context my component can receive.

What benefit does this have? I certainly understand the need to validate contexts, but If validation isn't needed then whats the point of having to explicitly request the context in such an unintuitive way?

```javascript
React.createElement({
    contextTypes: {
        app_context: React.propTypes.any // This wouldn't be needed with proptypes.
    },
    render: ...
});
```

**Comment by jimfb** [comment]
@DylanPiercey There are a few benefits:
 * when a component is passed props, it is explicitly passed from the owner.  It is very clear what data that component is/might read.  With context, variables are passed implicitly and thus there is no easy way of seeing which variables a component is potentially accessing.  contextTypes provides that visibility to the developer.
 * props come directly from the owner/parent component, whereas context can come from almost anywhere.  Props is easy to get right because it's a direct ancestor, whereas context is indirect and thus easier to screw up.  It is easy to have an ancestor somewhere that has a variable name collision and provides incompatible implementations of a particular context variable.
 * it allows us (the react core) to see what context variables are going to be utilized, which allows internal optimizations.  Context is super tricky to optimize, and these hints will open paths for optimizations in the future where we can see which context variables are updated and not rerender components that don't read from those variables.  Most components will never want to read from most context variables.  With props, a component is likely to read all the props it has access to, so this isn't a concern.

There are perhaps other ways we could have solved this, like my ReactDataTracker proposal, but contextTypes made the most sense at the time (and maybe still does).

**Comment by DylanPiercey** [comment]
@jimfb thanks for the response!

I think performance optimizations are one thing, but I have a hard time swallowing that contexts are harder to track down.

Realistically (at least in most libraries that use context), people have a name space for their context which makes it easy enough to search for that name space. Also typically these contexts come from the top level component somewhere and can be tracked down pretty easily. To me it just seems like react is forcing tooling in this case, I simply think that this should be optional as it is in propTypes.

If I though it was pertinent that I remember where the context I am using comes from, I may document it and validate it in the form of "contextTypes", however truthfully this doesn't help me track down the source easily anyway and just seems to add boilerplate in the common case.

**Comment by jimfb** [comment]
Keep in mind that the community currently uses `context` fairly sparingly (largely because we've aggressively made comments about the `context` feature being unsupported/unstable).  At Facebook, we use React pretty heavily (both in terms of number of components, number of programmers, and number of users) - and we also use the features (like context) long before they're rolled into a public release or publicly documented - so we sometimes see the usability/scalability issues before the outside world does.  I can say with confidence that context is more difficult to reason about than props, which is at least part of the reason we decided to make contextTypes required.

But usability isn't the only advantage of contextTypes.  Allowing the core to make optimizations based on knowledge of a components use of context was also a key factor in our decision.

Anyway, I was just trying to explain our reasoning for making context types required.  If our thinking on this matter changes substantially in the future, or a large number of people agree that it's confusing/inconsistent, we can reconsider.

**Comment by DylanPiercey** [comment]
@jimfb Thanks for the reply. I understand the reasoning, I appreciate you elaborating the internal use and such. Personally I think for small scale apps it makes sense to allow contextTypes to be optional so we can leave this open to see if there is any public opinion in favour of this.

Thanks!

**Comment by gaearon** [comment]
See also https://github.com/facebook/react/issues/2517#issuecomment-106597895, the current API isn't fixed in stone.

**Comment by jimfb** [comment]
The current behavior (required contexttypes, optional proptypes) is currently the expected/desired behavior (for the reasons listed above).  As a result, there isn't anything actionable in this issue at the moment.

Feel free to continue the discussion on this thread, and we can re-open if our thinking on this matter changes substantially.
