### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by ifedorov** [facebook/react#5351]
Can not inject react js on some sites

Example: https://www.victoriassecret.com/

insert in chrome console

```javascript
var e = document.createElement('script');
e.src='https://cdnjs.cloudflare.com/ajax/libs/react/0.14.1/react.js'
document.head.appendChild(e);
```
after couple seconds type:
```javascript
React
```

**Comment by gaearon** [comment]
This is not an issue with React.

On this particular website, there is a `define` global. React global build is a [UMD](https://github.com/umdjs/umd) build, and the existence of `define` makes it switch to AMD mode, so instead of exporting to a global `React`, it calls `define`.

What is your use case for injecting React on a third-party website?

**Comment by ifedorov** [comment]
It's for create UI in chrome extension

**Comment by zpao** [comment]
And mentioned the browser bundle uses UMD so it will work in multiple environments. I would recommend either bundling a version of React that you build yourself from npm or detecting the environment of the page. We won't be changing how our build works.
