### ISSUE TITLE
Should there be a requestUpdate or setState use deep merge?

### ISSUE THREAD

**Issue by mikkoh** [facebook/react#5384]
Currently we have `forceUpdate`. But I think a common case is to have deferred rendering in the same way that `setState` will render after a period of time.

From what I see `forceUpdate` renders immediately. This is an issue if lets say if you wanted to update two css properties and then render. Of course you could use `setState` however since it uses shallow merging updating states would cause overwriting the previous state.

Example:
```
this.setState({
  style: {
    top: 10
  }
});
```
Then before the next render-
```
this.setState({
  style: {
    left: 10
  }
});
```
When render is resolved state would be:
```
{
  style: {
    left: 10
  }
}
```

In order to solve this you could circumvent the `state` object and create a second object which contains computed styles and render requests could happen through a call to a function like `requestUpdate`.

Of course ignoring state and using another object to manage style would create the side effect of state being contained in two objects. (this is not nice) So in the end having deep merge for state would be the best however this obviously is a huge change and may create large performance drawbacks.

**Comment by syranide** [comment]
I'm not entirely sure what you're asking, but the following should solve deep merging for you:

```js
setState(state => {
  styles: myDeepMergeClone(state.styles, newStyles)
});
```

Multiple `setState`/`forceUpdate` are batched/queued if called during an event, you can achieve the same behavior outside of events too by wrapping them as:

```js
ReactDOM.unstable_batchedUpdates(function() {
  setState(...);
  setState(...);
});
```

However, this shouldn't generally be needed and you should design your components so that there is only a single call to setState.

> So in the end having deep merge for state would be the best however this obviously is a huge change and may create large performance drawbacks.

This might make sense for some special use-cases but is most definitely not a desirable default behavior. So managing it yourself like above is how it needs to be done.

**Comment by mikkoh** [comment]
Hmmm... When I ran a simple test of `forceUpdate` it didn't seem that was batched or queued.

The issue with:
```
setState(state => {
  styles: myDeepMergeClone(state.styles, newStyles)
});
```
Lets say you want to transfer props of the component to styles. For instance lets say a prop you could set is x and y. You most likely would have two functions that look like this:
```
function parseX() {
  var newStyle = merge(
    {},
    this.state.style
  );

  newStyle.left = this.prop.x;

  this.setState({
    style: newStyle
  });
}

function parseY() {
  var newStyle = merge(
    {},
    this.state.style
  );

  newStyle.top = this.prop.y;

  this.setState({
    style: newStyle
  });
}
```

In this case I'm merging the same way you suggested however if in one execution frame both functions would be run and `setState` would end up shallow merging in the end.

**Comment by syranide** [comment]
> Lets say you want to transfer props of the component to styles. For instance lets say a prop you could set is x and y. You most likely would have two functions that look like this:

It's definitely arguable and certainly depends on the context, but I would generally recommend a different approach:

```js
var newStyle = Object.assign({}, this.state.style);
parseXInto(newStyle);
parseYInto(newStyle);
this.setState({style: newStyle});
```

This way you can perform batching yourself and you may also find other benefits. Anyway, this is somewhat irrelevant to the problem (`setState` may still be called multiple times for various reasons).

> In this case I'm merging the same way you suggested however if in one execution frame both functions would be run and setState would end up shallow merging in the end.

That's why you need to use the callback-method I showed above, it receives the current state object as mutated by the last `setState`, so multiple pending `setState` are safe.

**Comment by mikkoh** [comment]
Yeah... This is def a hard issue to solve and people will easily continue to do it wrong without proper education but it maybe something that could be solved by react itself. Thanks for the input.

**Comment by syranide** [comment]
@mikkoh Just so that there isn't a misunderstanding, the "`setState` with callback" should solve all your problems. You will still want to avoid multiple calls or batch for performance reasons, but it should not affect behavior.

**Comment by spicyj** [comment]
(Closing since I don't think there's anything actionable here for React. The setState function style should give you the control you need.)
