### ISSUE TITLE
After calling `setState` with an ES6 class instance as its argument , this.state became a plain object.

### ISSUE THREAD

**Issue by lvscar** [facebook/react#5425]
When  React component  getInitialState method returns  an ES6 class instance , everything works fine ,  this.state in render mthod has the right type .

But when I call `setState` with ES6 class instance as its argument  , this.state becomes a plain object .

```javascript
class State{
  constructor(text){
    this.text = text
  }
  get value(){
    return this.text
  }
}

var Main = React.createClass({
  getInitialState(){
    return  new State("es6")
  },
  
  handleClick(){
    var state = new State("react")
    this.setState(state)    // bad case emerged
  },
  render(){
    console.log(`type ok : ${ this.state instanceof State}` )
    return(
      <div>
      {this.state.value}
      <br/>
      <button onClick={this.handleClick}>click</button>
      </div>
    )
  }

})
  
ReactDOM.render(<Main />, document.getElementById("react-wrap"))
```

react  0.14.2
gulp-babel 6.1.0

**Comment by jimfb** [comment]
`setState` takes in an object and does a shallow merge of the properties on that object (it does not completely replace the current state with the state you pass in).  See the docs here: https://facebook.github.io/react/docs/component-api.html#setstate

This looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.

**Comment by ekilah** [comment]
leaving this here for reference: https://stackoverflow.com/a/38481254/2544629 (similar question on SO that didn't get much attention, it took me a while to find any discussion about this so I want to cross-link them)

it's unfortunate that we can't do `instanceof` checks on custom classes stored on React component state. I was using `instanceof` in an `equals` method (to use Ramda's `Ramda.equals`) and that was failing, and it took a while to figure out why. adding this story here so google searchers might find this.
