### ISSUE TITLE
onChange on text input with placeholder fires without modifications in Internet Explorer

### ISSUE THREAD

**Issue by edmellum** [facebook/react#5438]
Using IE 11 if one has an `input` component with a `placeholder` attribute and an `onChange` handler, the onChange handler will be called when clicking the input without typing anything in, just clicking it.

I made a reproducible case in codepen here: http://codepen.io/anon/pen/BoGQyZ If one opens it in IE and look in the console and clicks the input with the placeholder they should see an event from the `onChange` handler.

It seems to be [a known issue](https://connect.microsoft.com/IE/feedback/details/810538/ie-11-fires-input-event-on-focus) that Microsoft is unwilling to fix. However if one of React's goals is to normalize the onChange event as the documentation implies this needs a workaround. One possible solution would be to check if the input that triggered an `input` event is focused at the moment.

**Comment by jimfb** [comment]
@spicyj @syranide I know we intentionally don't/can't normalize everything.  Is this something we care about normalizing?

**Comment by syranide** [comment]
@jimfb I think it makes sense to normalize it, but unless we solve *all* of these problems then it seems fruitless... and last I checked solving entirely in the event system didn't seem realistic. So that leaves solving it inside a wrapper-component which is trivial but would leave out the DOM bubbling (relying on that is a bad idea IMHO, but people do it), but it's trivial and safe to implement this wrapper-component yourself.

That's what it seems like to me at least.

**Comment by jimfb** [comment]
Ok, sounds like we probably won't invest time in solving this at the moment, but if @edmellum wants to file a pull request, it would be considered.

**Comment by spicyj** [comment]
#4051 fixed this and will be in React v15.
