### ISSUE TITLE
Input element can not focus and can not edit

### ISSUE THREAD

**Issue by code-artisan** [facebook/react#5440]
Hi, guys:
I get a problem. I write a react component. When I render the virtual selector to body in bootstrap modal, But I can not edit input or focus. 
Online example: http://code-artisan.github.io/react-virtual-selector/examples/modal.html

**Comment by code-artisan** [comment]
When I copy the static HTML code, It's work, But use react render the component, It's not work. Can not focus and can not edit. Is this a bug?

**Comment by jimfb** [comment]
I'm not entirely sure what this question is asking, but it sounds like a usage question.  I don't see any actionable bug at the moment.  If you suspect a bug in the React core, please provide a simplified case that demonstrates the issue.

Since this looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.

**Comment by code-artisan** [comment]
I am sorry, my English is not good.
