### ISSUE TITLE
adapting docs to react.rb

### ISSUE THREAD

**Issue by catmando** [facebook/react#5446]
I apologize if this is not the best place to ask this but...

We are getting ready to document our ruby react.js adapter (react.rb) and would like to take the current react.js docs as the starting point, and change the examples etc to use the ruby dsl syntax.

I believe that this is within the docs creative-commons license correct?

**Comment by jimfb** [comment]
For legal reasons, an official answer to questions like this could only come from a lawyer; I am not a lawyer.

This is a question which is best posed to your company's legal team - they should know what to do or who to ask.  Because there isn't much that our team (of non-lawyers) can contribute to this discussion, I'm going to close out this issue.

cc @jamesgpearce, who may be able to give a more authoritative answer.

**Comment by zpao** [comment]
CC BY 4.0 allows the modification and redistribution and that is what our documentation is licensed under (just give the license a read over and make sure you comply).

Are you also looking at using the design? I'm not sure where that falls in the scope of things, but I'd be happy to check in with our legal team and clarify if needed.

**Comment by catmando** [comment]
@zpao - yeah to get things rolling and also so people could easily cross compare (its really just react with ruby syntax) I was planning on keeping very close to the current design...We do have a different logo, and might change the color scheme.
