### ISSUE TITLE
componentDidUpdate fires before references are triggered or associated

### ISSUE THREAD

**Issue by MalucoMarinero** [facebook/react#5447]
So, I feel like componentDidUpdate and references are executing in the wrong order.

Background: I'm working on a situation where you're in a list of input fields, with a blank row of fields at the bottom. When you press enter in any field, it moves your focus to the next one by talking to a register which keeps track of all the fields and their positions. Shift+enter goes in reverse as well.

If you press enter on the final field, it kicks off a Flux like action which results in the next blank field being rendered, and then I want to move focus to that row. So I set up a callback that will fire on the next componentDidUpdate, knowing that when that happens, I'll have access to the new Field, which registers itself during componentWillMount. That works just fine, I can access that component just fine, however, if I want to use a method to direct focus to a DOM Element within it, it will be too early to make use of references:

```js
const FieldComponent = React.createClass({
  receiveFocus: function() {
    ReactDOM.findDOMNode(this.refs.input).focus() // error: this.refs.input == undefined
  },
  render: function() {
    return React.DOM.div({},
      React.DOM.label({}, "Some Label"),
      React.DOM.input({ref: "input", type: "text"})
    )
  }
})
``` 

...because the references have not yet been bound, even though we're at the componentDidMount/Update stage of the lifecycle, so this...

```js
  receiveFocus: function() {
    console.log(Object.keys(this.refs)) // log: []
    setTimeout(function() {
      console.log(Object.keys(this.refs)) // log: ["input"]
    },  0)
  },
```

...seems to indicate that reference binding happens synchronously after. Now, I could easily get around this by using ReactDOM.findDOMNode(this) and then using querySelector to find my target, but that isn't a clean `React` way to go about solving the issue, I believe based on what I know of the API that references should be bound/executed before componentDidUpdate/Mount fires. Does this not occur by design, mistake, or incompatibility with other goals?

**Comment by MalucoMarinero** [comment]
Upon thinking further, it may be the fact that this mismatch only occurs because I'm trying to access other components, maybe I'm expecting the React lifecycle to reconcile too quickly for this to be the case, as it seems events are not yet bound on this other component either. I'll leave this open for discussion because I wouldn't mind some clarification on what is/isn't meant to be done by the time componentDidMount/Update fires, but perhaps the ordering issue is set in stone.

**Comment by jimfb** [comment]
I remember @spicyj and @sebmarkbage did a lot of thinking+discussing on this topic.

I don't remember the details (I think it might have been that no matter which order you chose, there were people/reasons to want the other order), but I do recall that the decision was pretty intentional.  For this reason, I'm going to label this as a question regarding the reasoning.

**Comment by spicyj** [comment]
Refs to child components are resolved before a parent's componentDidMount/DidUpdate, which happens before refs to that parent are resolved. For example,

child A did mount
ref to child A resolved
child B did mount
ref to child B resolved
parent did mount
ref to parent resolved

This is the only order that ensures that a component is fully initialized when you receive a ref to it and that it can use its children during its initialization. You should avoid accessing siblings or ancestors in a componentDidMount because they will often not be mounted yet.

**Comment by jimfb** [comment]
Ah, yes, that was it.  Thanks @spicyj!

**Comment by MalucoMarinero** [comment]
Yep, makes sense, cheers for that.

**Comment by jedwards1211** [comment]
I don't understand why this was closed, @MalucoMarinero weren't you saying that you were seeing the parent's `componentDidUpdate` get called before a ref to its child got resolved?  If so that would mean there's a bug and the behavior doesn't match the invariant @spicyj described.

I'm currently debugging an issue where a `componentDidUpdate` gets called before a child's `componentDidMount` gets called (or its ref resolved) and AFTER the child's `componentWillMount`...that would be a bug, correct?

**Comment by jedwards1211** [comment]
Argh...it seems that there is some weird and complex interaction between `react-router` and `react-redux` that is causing the issue for me...an ancestor of the ref parent was dispatching a redux action when it received a new `query` from the router, which causes new props to be passed down from redux state -- all within the same event on the event queue.  What's happening in this case is that `componentWillReceiveProps` is getting called multiple times before `componentDidUpdate`...and then the refs are not resolving until after `componentDidUpdate`.  Wrapping the dispatch in a `setTimeout` prevented this from happening.

Unfortunately, I spent an hour trying to come up with a minimal repro case but failed...

**Comment by spicyj** [comment]
@jedwards1211 I believe @MalucoMarinero was trying to access sibling components in a componentDidMount (via a synchronous callback to the parent) which isn't kosher.
