### ISSUE TITLE
What if setState passed the component state to the provided callback?

### ISSUE THREAD

**Issue by nhunzaker** [facebook/react#5459]
I apologize if this has been discussed before, however I was unable to dig anything up. I'm proposing the following:

```javascript
var Parent = React.createClass({
    onUpdate(state) {
        // state was passed into this function when it was called by 
        // setState in the <Child /> component
        console.log(state) // { clicked: true }
    },
    render() {
        return (<Child onUpdate={ this.onUpdate } />)
    }
})

var Child = React.createClass({
    onClick() {
        this.setState({ clicked: true }, this.props.onUpdate)
    },
    render() {
        return <button onClick={ this.onClick }>Click me</button>
    }
})
```

For a more concrete example, this came up in the following PR on ReactRouter:

https://github.com/rackt/react-router/pull/2507

An `onUpdate` prop can be passed to a Router component, which it will invoke when ever it updates itself with the new Route state. Instead of forwarding along the state in the callback provided to `this.setState`, it must be intentionally provided like `this.setState(state, () => this.props.onUpdate && this.props.onUpdate(state))`

I'm happy with a firm "no" here, but when I investigated to see what it would look like to add this to React it seems like part of the trouble is a that there isn't a great way to "enqueued" callbacks with specific parameters in the queue of callbacks managed by a component's `updater` property. I may have this totally wrong, I am still learning quite a bit about how queued updates happen. 

At any rate, I thought there might be some good conversation around it.

**Comment by mjackson** [comment]
Gonna try to put some words to my thoughts around this. Wish me luck.

The `onUpdate` function you have listed here is like the cousin to `componentWillReceiveProps`, but for state. What I mean by that is that `componentWillReceiveProps` is called when you get new props, and your `onUpdate` function is called when you get new state. There's a parallel.

React calls `componentWillReceiveProps` when you receive props because there's no other way for you to get that info. That's how you find out that your parent's state changed, essentially. But that's not the case with state. Your parent isn't actually able to manipulate your state. Only you are. So this method feels unnecessary.

Besides being unnecessary, this style of programming can actually lead to all kinds of unpredictable behavior. The `onUpdate` method you have here is essentially "observing" your component's state and running arbitrary code in response to a state change. Unless you're extremely careful about what you're doing in that situation you can end up with all sorts of problems including cascading updates and race conditions. You can see this pretty clearly in [Ember's observable docs](http://guides.emberjs.com/v1.10.0/object-model/observers/) where they list several major caveats to their observables implementation. It's just not obvious what's going to happen anymore when you change state. Sorry if that's a bit vague, but it's a programming paradigm that I've learned to avoid if I can.

In the router specifically, you're supposed to get state changes as new props to your route components. Having this other hook where you get the router's state feels like it opens up the possibility for users to do themselves more harm than good.

**Comment by nhunzaker** [comment]
Thank you for the fantastic response. This makes a lot of sense.

**Comment by jimfb** [comment]
Thanks @mjackson!  I agree, that was a fantastic answer!

I'm going to close out this issue as "answered", but feel free to continue the discussion on this thread if you guys so desire.  We can re-open if the thinking on this topic changes dramatically, or if we find anything actionable on React's end.

**Comment by taion** [comment]
I don't think I agree with that - lifecycle-wise the `onUpdate` above is not parallel to `componentWillUpdate` at all. It's a lot more parallel to something like `componentDidUpdate`, except that it's only invoked for the update triggered by that `setState` operation.

Certainly it's very possible to shoot oneself in the foot when using `componentDidUpdate` and get into situations with infinite loops, but nevertheless there's quite a lot that's not easy to write without using something like `componentDidUpdate` hooks, including checking in a centralized way which updates actually happened, and going back and updating the DOM as well.

One place where you can imagine in general reading state in the callback of a `setState` operation might be something like:

```js
this.setState(({foo}) => ({foo: foo + 1}), callback);
```

which seems very legitimate to me, since you don't necessarily know what value you've set the new element to.

That said, I don't see why it's beneficial to be prescriptive about the signature of the update hook that way. If the data are all already available via `this`, it just seems easier to use `this.state`, or to proxy it yourself.
