### ISSUE TITLE
React re-write's DOM in component with no changes

### ISSUE THREAD

**Issue by natew** [facebook/react#5466]
Hard to search for this, wondering if this is intended behavior. I have my root component, which I call `this.setState({ x: 1 })` on. It doesn't change anything in the render. Yet chrome seems to flicker the DOM node, and I can get it to break on subtree changes:

![image](https://cloud.githubusercontent.com/assets/12100/11161217/745aad6e-8a2b-11e5-9177-4c4f79fb8475.png)

Is this intended or am I just doing something strange?

**Comment by jimfb** [comment]
I'm a little surprised you are seeing a flicker if nothing is changing - that shouldn't happen.  My guess is that something is changing in some way, but without a simple example that demonstrates the issue, there isn't much we can do here to investigate.

I'm going to close out the issue because it's not actionable in it's current state.  My guess is that there is a bug somewhere in your code, rather than a bug in the React core.  If you can create a simple example (jsfiddle) that demonstrates a bug in the React core, we'd be happy to re-open and investigate further.

**Comment by zpao** [comment]
Let's keep it open and close if we can't get a test case together or find its nothing. We don't have enough info to confidently close this.

**Comment by natew** [comment]
@zpao thanks. I actually wasn't certain if there was maybe a special case on the root node, or perhaps if calling setState from outside the element somehow triggered this. Can't extract out a simple test case as it's part of a bigger system, so I may just have to step through on my own on this.

I'd venture it is getting a bad state very quickly and then the good one again but at least I can set that breakpoint to see. Could I move up the stack and find out it's state at some point to see what it's trying to render?

**Comment by zpao** [comment]
You should be able to set a breakpoint inside render in your component and see what `state` is there.

> calling setState from outside the element
I don't think that matters but my gut reaction to that is *don't do that*. Expose a method that calls setState maybe but my recommendation is that you should really consider state private.

**Comment by natew** [comment]
Haven't run into this again today, going to close this out as it's almost certainly my bug, if I run into it again I'll set break on changes and see what I can find.
