### ISSUE TITLE
shouldComponentUpdate and child components

### ISSUE THREAD

**Issue by obto** [facebook/react#5483]
I have a couple wrapper components which dynamically calculate the size and position they need to be. Normally this works and performs great with `shouldComponentUpdate`, but as soon as I add children inside these components I can no longer use this method. Why? Because if i return 'false' for the wrapper needing an update... the children never get updated themselves :(

Example JSX:
```html
<ReactWrapper>
  <ChildElement/>
</ReactWrapper>
```

Is there any good way around this? Only idea I have is to add a new method shouldUpdateChildren like this other question detailed: https://discuss.reactjs.org/t/shouldcomponentupdate-and-children/2055

**Comment by jimfb** [comment]
This looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like [discuss.reactjs.org](https://discuss.reactjs.org) or [StackOverflow](http://stackoverflow.com/), as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to one of the previously mentioned sites.

**Comment by tp** [comment]
I just came across a similar issues when profiling a React based app.

An <Overlay> component way re-rendered a lot. The only thing passed into is `isVisible`, the element to render when it's visible (as a prop named "overlay"), and the element it anchors around (as props.chilren).

Is there any recommended way to compare the previous and next children and hopefully even the "overlay" prop to find out whether they are the same component with the same props and therefore a render is not necessary?
