### ISSUE TITLE
Warn when <body> tag rendered by a component

### ISSUE THREAD

**Issue by graue** [facebook/react#5484]
Example that should warn when rendered:

```js
var Foo = React.createClass({
  render: function() {
    return <body><p>Hi there!</p></body>;
  }
});
```

There's no good reason to do this [edit: other than server rendering], and with React 0.14, it seems to cause click handlers placed inside the faux-body to not get called.

**Comment by jimfb** [comment]
As per https://github.com/facebook/react/issues/4948#issuecomment-157237775, I think it is supported for SSR FPR.

**Comment by dwighthouse** [comment]
Trying to implement more semantic html, and having dropped the use of html, head, and body tags (because they are neither required nor useful most of the time in html5), I accidentally added a body tag around a list of divs, forgetting its use and thinking it was a good semantic element for the main body of the app's content (not containing the header/footer, you see). Anyway, the resulting html outputs just a list of divs, with no wrapping tag (of any kind). No errors occurred on initial render, but if you attempt to mutate the DOM after that, you get the Invariant Violation error. There should definitely be Debug warnings for html, head, and body tags.

**Comment by antoaravinth** [comment]
@graue @jimfb Why this is required? `validateDOMNesting` check already does that, so if do something like:

```
var Foo = React.createClass({
  render: function() {
    return <body><p>Hi there!</p></body>;
  }
});
```

I'm getting the following error:

`react.js:19529 Warning: validateDOMNesting(...): <body> cannot appear as a child of <div>.`

**Comment by jimfb** [comment]
Eeh, I think I agree, the bulk of this bug is already handled by dom nesting validation.  Let's close it out until/unless we have a driving use case/need.

**Comment by aurimus** [comment]
So why am I getting this warning when rendering `<body/>` again ?

**Comment by emadbaqeri** [comment]
I'm getting the same error `Warning: validateDOMNesting(...): <body> cannot appear as a child of <div>.`.
I used inspect elements to see if I'm rendering the `body` inside any `div` tags, but everything was fine and in the right way. 
The question is why should I get the error then
