### ISSUE TITLE
Separate website for each release

### ISSUE THREAD

**Issue by udnisap** [facebook/react#5516]
I was working on https://github.com/facebook/react-native/issues/3459 issue in React Native and found out that React is also having this issue in the website. 

from @mkonicek 
>
People often send pull requests which update both code and /docs which makes sense. However, when the PR is merged, the docs go live immediately but the code is only released in up to 4 weeks. This means the docs are inconsistent with the APIs and CLI commands people get when using React Native.

**Comment by zpao** [comment]
We only publish from our latest `-stable` branch. All documentation changes land in `master` and we cherry-pick them over to the stable branch. `gh-pages` is built from that. This avoids the docs + code changes since we'll only get those if we cherry-pick that code change into the stable release.

We care less about having long-lived docs for each version - they aren't well set up for that and I'm not sure there's enough value. But thanks to the cherry-picking the last published markdown is always available for that version. Eg, if I wanted to see the 0.10 API docs, I can do that easily: https://github.com/facebook/react/blob/0.10-stable/docs/docs/ref-01-top-level-api.md.

I personally think this is a pretty good process (cherry-picking can be annoying but it allows the docs to be pretty stable but still receive updates).
