### ISSUE TITLE
React.Children.toArray changes element.key

### ISSUE THREAD

**Issue by azazdeaz** [facebook/react#5541]
React.Children.toArray changing the childrens key property. ex.: ```"foo" => ".$foo"```

In 0.14 sometimes (i dont know exactly when but event without ```toArray```) i got even weirder keys when i parsing children. ex.: "foo" => "foo/.$foo"

I didn't found any mention of these things yet. 
Is it documented somewhere? 
Can i get the original key somehow?

**Comment by liesislukas** [comment]
don't you want to use one of these:
ref="val"
data-var="val"

**Comment by azazdeaz** [comment]
Thanks for your answer @liesislukas but i don't looking for workarounds about this. 

One more question i forgot:
Is element.key a React internal now that we shouldn't even touch?

**Comment by spicyj** [comment]
Yes, key is used to signal to React the identity of an object, and React.Children.toArray changes the key so that the identity semantics can be preserved. For example:

```jsx
<div>
  <span key="header" />
  {items.map((item) => <span key={item.id} />)}
</div>
```

If any item has an `id` of `header`, that's okay – they won't be mixed up with the first element because the keys are scoped to the array that they're in. When you flatten `[<span/>, items]`, each item gets its key prefixed to preserve this behavior.

If you want to read the key back off and have it unchanged (or to read it from within the component in `props`), please use another property name.

**Comment by azazdeaz** [comment]
Okay, thanks @spicyj !

**Comment by tonix-tuft** [comment]
@sophiebits Could you please provide an example showing why React prefixes keys this way when using `React.Children.*` functions? E.g. `React.Children.map`
