### ISSUE TITLE
Disable a specific warning

### ISSUE THREAD

**Issue by bruno12mota** [facebook/react#5545]
Will explain the issue briefly, instead of extending React.component I have a class which gets state from a getInitialState function if exists:

`````
export default class BaseComponent extends React.Component {
  constructor (props, children) {
    super(props, children);
    this.state = this.getInitialState ? this.getInitialState() : {};
  }
}
`````

When using it in a component looks like this:

``````
export default class SomeComponent extends BaseComponent {
    getInitialState () {
        return {
          ...
        };
     }
}
``````

This triggers a warning by react:

Warning: getInitialState was defined on SomeComponent, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

So my question is, is there a way to disable this warning from happening?

Cheers!

**Comment by jimfb** [comment]
Workaround: Use a different name, like `getMyInitialState`.  Get initial state is a reserved function name, and emits a warning in order to avoid confusion with the component lifecycle function defined on ES5 react classes.

This looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.
