### ISSUE TITLE
could ReactCSSTransitionGroup use getComputedStyle to get transition timeouts automatically?

### ISSUE THREAD

**Issue by jedwards1211** [facebook/react#5580]
While reading about the new `transitionEnterTimeout` etc. in `ReactCSSTransitionGroup`, a thought struck me: why not just get the timeout directly from CSS with `getComputedStyle` once the transitioning classes have been applied to a transition group child?  Does anyone foresee a problem with this approach?

**Comment by spicyj** [comment]
It's possible but might be slower if we weren't careful to query it at the appropriate time (due to forced style recalc). Also unclear what to do if there is more than one transition on an element. I think it would take a fair amount of work to make this really bulletproof and I don't think the gains are large enough. You could make your own version of the component that does this.

**Comment by stryju** [comment]
AFAIK, `ng-animate` took that from this element (after adding `.*-enter`/`*-leave`, which would recalc styles anyway, no?) `transition` definition and took the "longest" time period (including `transition-delay` etc.)

the benefit of that was that different elements could have different delays, not one-needs-to-fit-all

**Comment by gaearon** [comment]
FWIW we don’t plan to make more changes to `ReactTransitionGroup`. Our current plan is to hand it over to somebody in the community because we don’t have enough internal users at Facebook to meaningfully evolve its API or spend a lot of time on it.

**Comment by cvle** [comment]
Checkout this project as an alternative: https://github.com/wikiwi/react-css-transition

**Comment by gaearon** [comment]
React's implementation of TransitionGroup has moved here: https://github.com/reactjs/react-transition-group
