### ISSUE TITLE
Rendering a snap svg image

### ISSUE THREAD

**Issue by carlskii** [facebook/react#5604]
Hi I'm new to React. I'm looking use snap svg for rendering some svg images into some views, however I'm not quite sure how best to set this up. I'm using ec6 and the Babel transpiler. Could you explain the best way to add snap svg so that it can render to a view please. 

Really looking for best practise here rather than me doing it completely the wrong way. 

Thanks

**Comment by jimfb** [comment]
This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.
