### ISSUE TITLE
ES6 rules not allowed static properties in classes only method

### ISSUE THREAD

**Issue by Kepro** [facebook/react#5661]
see more https://stackoverflow.com/questions/34125141/mysterious-eslint-parsing-error#

**Comment by jimfb** [comment]
I'm not sure why this issue is being filed against the React repository.  Static property initializers were not approved in ES6, though they may be approved in ES7+.  Either way, the syntax rules are part of Babel not React.

Also afaik, all our documentation uses the following pattern:
```
class MainApp extends Component {
...
}
MainApp.propTypes = ...;
```

Which afaik, is valid/legal ES6.
