### ISSUE TITLE
Changelog: can upcoming release changes be added?

### ISSUE THREAD

**Issue by shouze** [facebook/react#5675]
When I check the diff between the current last stable release and the upcoming one in master branch....

https://github.com/facebook/react/compare/v0.14.3...master

There's a LOT of changes! Could the Changelog file be updated all along the dev process? This way, should be possible to anticipate deprecations for example.

**Comment by jimfb** [comment]
My assumption is that we don't want to do this, because it's easier to generate the changelog all at once just prior to a release (we'd have to go through the history at the end anyway, to ensure we didn't forget something along the way, and it's easier to organize the list when you have a holistic view of the final release).  Until then, that's the whole point of being able to do a git log, as you linked above.

We are generally provide fairly advanced notice for things like deprecations.  For instance, the docs indicate which methods we'd like to deprecate (eg. see: https://facebook.github.io/react/docs/component-api.html).  You can also watch the github issues and the pull requests, either of which would give you a pretty good indication of what's being done.

cc @zpao, who can reopen if he decides this is something we actually want to do.

**Comment by shouze** [comment]
@jimfb for example, from another OSS project we use: https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md

They also make great PR/issues with a great review process, they also work hard on DX (Developper eXperience) aspects with deprecations and so on... but this file exist and it's a very handy starting point when you decide to go for an upgrade.

**Comment by zpao** [comment]
No plans to do this. I understand the desire and I've done it for some other projects, but I think we're mostly happy with generating this by hand after the fact.
