### ISSUE TITLE
style property lineHeight pixels problem

### ISSUE THREAD

**Issue by beharguy** [facebook/react#5678]
Hello,

When I am setting a lineHeight as a number, the value in the DOM is not set in pixels.
It would be great if it will work like height and set the value in the DOM in pixels.

Attached a jsfiddle link:
https://jsfiddle.net/m1e86an9/

Thanks.

**Comment by yangshun** [comment]
I think this is expected behaviour, as in https://github.com/facebook/react/blob/master/src/renderers/dom/shared/CSSProperty.js, `lineHeight` is defined to be a unitless value, and that value means "A number that will be multiplied with the current font size to set the line height".

In your case, doing will get you what you need:
```
var style = {
  border: 'solid 1px #000',
  height: 30,
  lineHeight: '30px'
};
```

**Comment by beharguy** [comment]
Ok.

I didn't know lineHeight is a unitless value.
If that is the case I agree it is expected.

Thanks.

**Comment by goleary** [comment]
Rather strange that this case is handled different on `react-native` from `react`.

In RN if you pass 16, it is interpreted as 16 pixels...in React it's interpreted as ???

This makes sharing a theme between the two more difficult.  Sure we can use `16px` for the field, but this seems quite arbitrary.
