### ISSUE TITLE
Invalid (string) style definition breaks IE 11 and Safari 8

### ISSUE THREAD

**Issue by idris** [facebook/react#5684]
I had a pesky bug that was hard to track down where React was defining the `style` key twice on an element.  I finally discovered that it was because I had defined an element like this:
```
<form style="margin-top" style={{marginTop: 25}}>
```

Clearly a mistake/typo on my part, but in my production code it caused a duplicate `style` entry in the object, which breaks IE 11 and Safari 8.  It would have been nice to see an invariant warning about this or something.

It may be because I'm using `optimisation.react.constantElements`.. not sure

**Comment by zpao** [comment]
Best bet will be to lint against this. Since JSX just gets compiled to objects (either with that constantElements option, otherwise just the props themselves), what you're actually having a problem with is that duplicate keys in objects is a strict mode violation. There's no way at runtime to know that you had duplicate keys (if you didn't get a strict-mode parse error), so React can't protect you. Since this is in JSX, built-in lint rules don't work so you want something like [this rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-duplicate-props.md) from eslint-plugin-react which will warn you.

Sorry we can't do anything, but good luck! In case you can't tell, I *strongly* suggest integrating eslint into your workflow if you haven't already :)
