### ISSUE TITLE
How would one pass LaTeX code into a component?

### ISSUE THREAD

**Issue by Pomax** [facebook/react#5688]
I have the fairly rare, but given the internet by no means unusual, situation where I need to embed LaTeX code that needs to be interpreted later (by a MathJax, or KaTeX, etc). The following code doesn't work due to JSX intepretation of the bits inside `{...}`:
```
<p>\[
  p_1 = some\ point, \\
  p_2 = some\ other\ point, \\
  distance = (p_2 - p_1), \\
  ratio = \frac{percentage}{100}, \\
  new\ point = p_1 + distance \cdot ratio
\]</p>
```
Using ES2015 tempating strings also doesn't work, because then the `\` gets interpreted instead:
```
<p>{`\[
  p_1 = some\ point, \\
  p_2 = some\ other\ point, \\
  distance = (p_2 - p_1), \\
  ratio = \frac{percentage}{100}, \\
  new\ point = p_1 + distance \cdot ratio
\]`}</p>
```
And of coure, double escaping all the `\` works but becomes *impossible* to read or write:
```
<p>{`\\[
  p_1 = some\\ point, \\\\
  p_2 = some\\ other\\ point, \\\\
  distance = (p_2 - p_1), \\\\
  ratio = \\frac{percentage}{100}, \\\\
  new\\ point = p_1 + distance \\cdot ratio
\\]`}</p>
```
So.. .is there a JSX feature that "turns off" interpretation for an element? Something like this, that treats the text inside the element as "untouchable"?
```
<p verbatim>\[
  p_1 = some\ point, \\
  p_2 = some\ other\ point, \\
  distance = (p_2 - p_1), \\
  ratio = \frac{percentage}{100}, \\
  new\ point = p_1 + distance \cdot ratio
\]</p>
```

**Comment by jimfb** [comment]
`dangerouslySetInnerHtml`

**Comment by Pomax** [comment]
That is even worse: how is the legibility maintained? Unless you're seriously suggesting this is easy to read/write:
```
<p dangerouslySetInnerHtml={ html: [
"  p_1 = some\ point, \\",
"  p_2 = some\ other\ point, \\",
"  distance = (p_2 - p_1), \\",
"  ratio = \frac{percentage}{100}, \\",
"  new\ point = p_1 + distance \cdot ratio",
"\]"
].join("\n")}}/>
```

```

**Comment by jimfb** [comment]
To render it with React, you're going to need to get your latex into some sort of javascript form one way or another.  That's entirely outside of React's control.  Depending on your build architecture, you may be able to use macros or file generation of some sort.

Once you get it into javascript, it becomes the domain of React, and `dangerouslySetInnerHtml` should do what you want.

This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, the issue was closed.  You're welcomed to continue the conversation here, but you may want to move it to a site intended for these sort of questions (like StackOverflow).

**Comment by Pomax** [comment]
noted, thanks for the help.
