### ISSUE TITLE
diff/patch with markdown preview

### ISSUE THREAD

**Issue by whisper-bye** [facebook/react#5710]
When I preview huge markdown file with changes, dangerouslySetInnerHTML is very slow,
can I use react to smart innerHTML? I don't know how to do it, thx.

**Comment by yangshun** [comment]
Not exactly a solution, but you can debounce the updating of the preview at a fixed interval (say 500ms). The 500ms delay in updating of the UI is acceptable to most users.

**Comment by whisper-bye** [comment]
I need a real time solution, 500ms is too long for users

**Comment by jimfb** [comment]
If you need a real-time solution, then you probably want to do diffing of some sort.  You may be able to convert the output of your markdown library into JSX elements using some code similar to https://facebook.github.io/react/html-jsx.html  Or you may be able to modify your markdown library to produce JSX elements instead.  Or you may write some code to compare the source markdown, and only pass the changes into your markdown library, and do targeted updates.  Regardless of which solution you choose, this is a usage question rather than a bug in the React core.  Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.
