### ISSUE TITLE
Warn on access of `props.key` and `props.ref`

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5742]
The props `key` and `ref` are reserved by React, and used internally.  Component authors may attempt to access these properties (thinking they could read the value, as per https://github.com/facebook/react/pull/5740).  We could use `Object.defineProperty` (in dev mode) to warn if `props.key` or `props.ref` is accessed, and point the user to a note/discussion somewhere.  That way, users who actually run into the issue will always get a timely message that sends them directly to the relevant explanation/discussion.

This would be a good first bug, if we decide we actually want to do it.

**Comment by gaearon** [comment]
This sounds like a great idea to me!

**Comment by spicyj** [comment]
Yeah this seems reasonable.

**Comment by alayek** [comment]
hi, I am interested on working on this; as I am looking forward to contribute. Kindly show me the way. Thanks in advance!

**Comment by jimfb** [comment]
@alayek Take a look at https://github.com/facebook/react/pull/5744, that should give you a good start and a good idea of what we would be looking for.

**Comment by alayek** [comment]
Thanks @jimfb. Checking it out right away.

**Comment by alayek** [comment]
@jimfb I have taken a look at the pull request, and associated code review comments.

It seems the _warn-once_ policy is required here, as implemented in https://github.com/facebook/react/blob/3b96650e39ddda5ba49245713ef16dbc52d25e9e/src/isomorphic/classic/element/ReactElementValidator.js

I am not sure I fully understand this how this module achieves this, so I am reading it now.

As per the code review comments in #5744 , I am using the `fb.me` URLs instead of StackOverflow URLs. But the comments over there also mentioned that the PR might break some test cases. I am not sure about the edge cases here.

I feel like I could use some help on understanding this. Instead of using GitHub issue comments, is it possible to use some chat-platform such as IRC or slack room or Gitter?

**Comment by jimfb** [comment]
@alayek

 * The module achieves deduplication by setting a boolean if it has already warned.
 * The comments about breaking tests are referring to the failing unit tests.  Just run `npm run test` and `npm run lint` to verify that everything is working before pushing your changes.
 * There are many places where you can discuss, including the IRC channel and/or reactiflux.  There are also github issues (which is what our core team predominantly uses), as well as several other channels.  The community is pretty big, but nothing is quite as good as reading through the code and github issues, IMHO.

**Comment by prometheansacrifice** [comment]
Sorry, I was away. #5744 is ready to be reviewed.
