### ISSUE TITLE
Replace native `bind` to improve performance on Chrome

### ISSUE THREAD

**Issue by netheril96** [facebook/react#5745]
React autobinds the methods of components created with `React.createClass`. But `Function.prototype.bind` is very slow on Chrome and Chromium derived browsers. Here is a post discussing it (http://benediktmeurer.de/2015/12/25/a-new-approach-to-function-prototype-bind/), and here is a adaption of the test code (https://jsfiddle.net/1kavbe7p/8/). One can test it on Google Chrome, finding that calling a bound function has an overhead even larger than heavy math computation.

It will be long before v8 fixes this long standing issue and for the new version to be adopted en masse. Meanwhile, React may improve its performance on Chrome by writing its own `bind`, just as in `lodash` or `underscore`.

**Comment by sohe1l** [comment]
:smiley:

**Comment by sohe1l** [comment]
:smiley:

**Comment by STRML** [comment]
@netheril96 It actually has already hit Chromium: https://chromium.googlesource.com/v8/v8/+/97def8070cbb979419c041c3732d5e11779f79da

**Comment by zpao** [comment]
Any opinions @sebmarkbage? I'm inclined to just live with this a bit longer and let Chrome/V8 versions get out that improve this out of the box (especially since Chrome update uptake is so good)

**Comment by jimfb** [comment]
I agree with @zpao 

When I run the benchmark, looks like native bind is 2x-ish slower than the custom implementations.  On canary, there is no difference (native is 10x faster, custom are 5x faster).  Realistically, by the time we get 0.15 out the door, all the chromes will be fast anyway and it won't matter.

**Comment by sebmarkbage** [comment]
That's a reason for us to use the native implementation because it is incentive for browsers to do this work. We can sacrifice a little perf in the short term to get long term greater wins.

In this case, I don't expect it to matter much since auto-bound methods are mostly there for callbacks which are single action. The only case it matters a lot is if you call a helper a lot but you really should just be using a local module scope function instead. The call to `.bind()` itself is much more interesting to optimize than the call to the produced function.
