### ISSUE TITLE
Deprecate Immutability Helpers

### ISSUE THREAD

**Issue by graue** [facebook/react#5780]
Have we thought about getting rid of these? https://facebook.github.io/react/docs/update.html

The API is pretty complicated, and it's probably a better idea in most cases to either use [Immutable JS](https://github.com/facebook/immutable-js) (more powerful and complete), or the stage-2 proposal for [object spread syntax](https://github.com/sebmarkbage/ecmascript-rest-spread) (simpler, will eventually be built into JS):

```js
const original = {a: 1, b: false, c: 'banana'};
const copy = {...original, b: true};   // copy is like original but with b set to true
```

As long as we continue to have this immutability helper addon in the docs, I feel we'll be steering people new to React towards a solution that we know is a bad tradeoff.

**Comment by zpao** [comment]
Yea, it's come up. I think they have some value to people. It's more powerful than object spread (see $push) and an API people might be more familiar with after working with Mongo. But I agree that for most people, they aren't useful.

They shouldn't be shipped with React though and if somebody came up with a better name I'd split them out tomorrow (I filed #2909 a long time ago but let it sit, but that's why I'm closing this). Or if somebody in OSS wanted to take what we had and ship their own version, that'd be fine too. That came up in another issue but I can't find it atm. We still use this in a few places internally too so we can't just up and kill it completely without some work.

**Comment by jmm** [comment]
@graue 
> or the stage-2 proposal for object spread syntax (simpler, *will eventually be built into JS*):

(Emphasis mine.) *Hopefully*, but until then there's some risk involved in using it and it's worth considering whether that's something you want to encourage users to do. In that case I would suggest that you consider including a note mentioning that.

The helper is mainly useful for nested objects. The cases where object spread is helpful can also just be addressed by `Object.assign()`, albeit more verbosely.

@zpao

> They shouldn't be shipped with React though and if somebody came up with a better name I'd split them out tomorrow (I filed #2909 a long time ago but let it sit, but that's why I'm closing this). Or if somebody in OSS wanted to take what we had and ship their own version, that'd be fine too. 

Sorry if I'm misunderstanding something...aren't they already split out and shipped on their own with better names, e.g.: [react-addons-update](https://www.npmjs.com/package/react-addons-update)? So the remaining issues are things like not bundling them in [react](https://www.npmjs.com/package/react), changing the internal usage, putting them in a separate repo, etc.?

**Comment by jmm** [comment]
Hmm, well I see that `react-addons-update` is just a shell that re-exports from `react`. So by better name I take it you mean something not even referencing React?
