### ISSUE TITLE
pureRender static property

### ISSUE THREAD

**Issue by brigand** [facebook/react#5788]
The majority of components should have PureRenderMixin-like behavior. With es6 classes and function components, there's no easy way to use mixins. Because it's such a common use case I think it should be part of core react.

I think this will encourage more people to use pure render because it's a lot simpler to add. This is a good compromise on the requests to make pure render the default behavior.

``` js
class X extends React.Component {
  static pureRender = true;

  render() {
    ...
  }
}
```

``` js
function X(props) {
   ...
}
X.pureRender = true;
```

``` js
React.createClass({
  pureRender: true,
  render() { 
    ...
  }
});
```

**Comment by jimfb** [comment]
@brigand

 > The majority of components should have PureRenderMixin-like behavior.

That's only true if you assume immutable data.  It's not true in general.

Immutable data is great, and we generally recommend using immutable data when possible (largely because it makes `shouldComponentUpdate` relatively trivial to implement).  Unlike Rust, the javascript language assumes mutability by default.

Anyway, with that said, this idea has been discussed and is being considered.

However, the more I think about it, the more I become convinced the correct solution is to just import/require a pureRender function and use that as your `shouldComponentUpdate`.

Example:
```
React.createClass({
  shouldComponentUpdate: require('pureRender'),
  render() { 
    ...
  }
});
```

That pattern is fully generalizable (could use any function you want, not just pureRender), is already supported today, and isn't "magical".

**Comment by brigand** [comment]
@jimfb any thoughts on the simple function components with regard to this?

**Comment by zpao** [comment]
cc @sebmarkbage - I know we've talked about this in the past but didn't see anything in react-future & not sure where it's come up.

**Comment by jimfb** [comment]
@brigand If we were to take the generalized path, perhaps the simple function would participate in the `shouldComponentUpdate` but not the other lifecycles.  Honestly, it hasn't been at the top of our priority list, because people can always use ES6 classes if they need access to the lifecycles for performance reasons.  For trivial components, pureRender can actually be detrimental to performance because you end up spending time doing the shallow compare (which can be as expensive as the render) and then ultimately update the component anyway.

@zpao It came up in https://github.com/facebook/react/pull/3995#issuecomment-127566694

**Comment by sebmarkbage** [comment]
There are a few alternatives:

a) A flag to the existing behavior. This proposal. The flag wouldn't guarantee a bailout but React is allowed to us a heuristic for when to compare.

The problem with pure render is that it doesn't actually assume anything about your render. All renders should be idempotent. What it says is that the render becomes pure due to the properties of your parent components. Not this component. Which is kind of fragile. Once you start having these in your system, you're effectively subscribing to the notion of immutable data because it is very subtle when it breaks down.

b) An alternative would be to flag the provider of props. I.e. the parent would declare that the output of its render is immutable, and therefore any transitive child can safely bail out on its children. We can track this flag in the reconciliation.

c) Another alternative that I've thought about recently, is to always render everything... eventually. Basically, the idea is that we can always bail out on equality checks, but in spare cycles we keep rendering the branches that were previously cut off. What this means is that immutable data becomes the preferred and fast option. However, mutable data will still automatically eventually be consistent. So, if you do screw it up, it's not such a big deal.

The question now is just how many intermediate APIs do we release before we get there? If we go with A first, we should pick a name for both A and B so that we know that the naming makes sense.

**Comment by syranide** [comment]
@sebmarkbage Flagging props as pure raises another interesting question, components need to know this and be able to pass it down (as they themselves are likely to pass those props on). Without further explicit knowledge of which props are pure, as long as you're passing any of them down all descendants should also assume that have their props are flagged non-pure. Essentially `<Child pureProps={this.hasPureProps} />` should become a recurring pattern (in theory) it seems to me? But perhaps that's what you mean by:

> ...and therefore any transitive child can safely bail out on its children. We can track this flag in the reconciliation.

**Comment by aweary** [comment]
React now has an API for pure components with [React.PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent).
