### ISSUE TITLE
Warn when `value` and `defaultValue` are both specified

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5819]
This should be illegal:
```
ReactDOM.render(
  <input value="foo" defaultValue="foo1" onChange={function(){}} />,
  document.getElementById('container')
);
```
Users need to decide if they are using controlled or uncontrolled inputs.  We should warn if both properties are specified.

**Comment by yaycmyk** [comment]
:+1: I've run into this before and it can trip up new React developers.

**Comment by syranide** [comment]
@jimfb I might be reading #5680 wrong, but doesn't that make it valid to use both? (Although, HTML defaultValue really should be separate from React defaultValue right?)

**Comment by jimfb** [comment]
@syranide No, afaik, https://github.com/facebook/react/pull/5680 is trying to fix https://github.com/facebook/react/issues/4618 when using uncontrolled components.  `defaultValue` is always meaningless for controlled components.  https://github.com/facebook/react/pull/5680 does add a unit test that includes an element with both `value` and `defaultValue`, but I complained about that and hopefully it gets fixed before that gets merged (seeing that PR was the reason I created this issue).

**Comment by syranide** [comment]
@jimfb Ah ok I see now... Hmm, I don't advocate it at all, but if that PR is meant to fix `<input type="reset" />`, wouldn't it make sense to support both `value` + `defaultValue`, `defaultValue` being what it resets to when you hit reset... rather than the value it already has.

Anyway, wrong issue to have this discussion in. :+1:
