### ISSUE TITLE
Tips Documentation on accessing props of the children

### ISSUE THREAD

**Issue by moodysalem** [facebook/react#5850]
e.g.
http://codepen.io/moodysalem/pen/obeWRr?editors=001

Is this something you should avoid doing?

**Comment by jimfb** [comment]
This looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.

**Comment by moodysalem** [comment]
I guess I'm asking more whether this is something that will be supported in future versions, and if it is, maybe there should be a section in the docs to clarify that you can access the props of children. But I haven't found a use case that couldn't be supported by just giving the parent element more props (although this does provide a nice separation of props)

Here's an example question about doing this
http://stackoverflow.com/questions/29670173/accessing-react-component-children-props-from-the-parent

**Comment by jimfb** [comment]
I think we don't want to encourage that pattern by documenting it, but we also don't want to prohibit it because people do use it sometimes (especially when cloning an element).  Personally, I thought that the top stack overflow answer was pretty good.
