### ISSUE TITLE
scryRenderedDOMComponentsWithClass does not allow you to assert props on found components, while scryRenderedComponentsWithType does

### ISSUE THREAD

**Issue by sahiltalwar88** [facebook/react#5852]
As a trivial example, assume this component render code.
```javascript
render () {
  ...
  return (
    <div>
      <SubComponent />
    </div>
  )
}
```

This helper method
```javascript
const getSubComponent = componentProps => {
  const component = TestUtils.renderIntoDocument(<Component {...componentProps} />)
  return TestUtils.scryRenderedComponentsWithType(component, SubComponentType)
}
```

makes this test pass,
```javascript
  it('should initialize a subComponentName with expectedValue', () => {
    const subComponent = getSubComponent(componentProps)
    const expectedValue = value;
    assert.equal(subComponent.props.expectedPropName, expectedValue)
  })
```

while this helper makes it fail (`undefined != expectedValue`)
```javascript
const getSubComponent = componentProps => {
  const component = TestUtils.renderIntoDocument(<Component {...componentProps} />)
  return TestUtils.scryRenderedDOMComponentsWithClass(component,'sub-component-css-class')
}
```

This does not seem like the expected behavior to me. If it IS expected, then I think it should probably be explicitly mentioned in the docs.

**Comment by Ghiblian** [comment]
The current behavior is expected and consistent with my understanding of React.

Prior to React 0.14, scry/find...WithClass would have returned the DOM component. With the release of 0.14, the methods now return the DOM node itself (akin to the change where refs now return the DOM node instead of the wrapper component). In neither of these cases would the props of a custom component by accessible.

A component has no concept of a CSS "class" since it's just another prop that invariably gets placed somewhere in the rendered DOM of the component (it doesn't have to be placed on the root element). Thus, it's unclear how you would even retrieve your custom composite component with a CSS class.

The behavior is, to some extend, self-documented in the method name. If you notice, there is a distinction between scryRenderedDOMComponentsWithClass vs scryRenderedComponentWthType.

**Comment by sahiltalwar88** [comment]
Thanks for the reply, @Ghiblian. If this is expected behavior, I'd suggest that the docs be updated to both specify what the difference is and what the expected behavior is. To someone that's new to React like myself, the difference _itself_ isn't clear, let alone the difference in expected behavior. What do you think?

**Comment by jimfb** [comment]
I think the documentation is pretty clear about what the two functions do.  FWIW, `scryRenderedComponentsWithType` does not allow you to assert props on the found component if the component happens to be a DOM component (thus consistent with `scryRenderedDOMComponentsWithClass`, which only finds DOM components).  Also, FWIW, if we could make props private (ie. not visible to the outside world, including test utils) - we would.

**Comment by sahiltalwar88** [comment]
@jimfb, could you point me to where in the documentation the difference between a DOM component and a regular component is specified? I might have missed that section, and I think that's the source of my confusion. Thanks!

**Comment by jimfb** [comment]
@sahiltalwar88 DOM components are anything built into the browser, composite components are anything you write yourself (or import).

**Comment by sahiltalwar88** [comment]
Gotcha. Thanks!
