### ISSUE TITLE
binding event inside onClick prop

### ISSUE THREAD

**Issue by fritx** [facebook/react#5862]
ref: https://github.com/Lucifier129/react-lite/issues/25

```jsx
<div className="op-btn" onClick={()=>{
                alert(1)
                window.addEventListener('click', () => {
                  alert(2)
                })

                // this.refs.filePanel.toggle()
              }}>发送文件</div>
```

In react, both `1` and `2` are alerted, while in react-lite, only `1` is alerted.
In my case, I have to wrap the second binding with a `setTimeout` to make it work in react.

**Comment by jimfb** [comment]
I don't understand what makes you think that behavior is incorrect.  It seems like a perfectly reasonable behavior to me.

Regardless, React uses a synthetic event system.  The interaction between native events and synthetic events is strictly undefined.  Sebastian wrote a post about this once-upon-a-time, how native and synthetic event systems are, by and large, inherently not interoperable.

I'm going to close this out, because I don't see anything actionable here.

**Comment by fritx** [comment]
Thanks @jimfb 
Will checkout that post.
