### ISSUE TITLE
Render static html client-side

### ISSUE THREAD

**Issue by alfredoreduarte** [facebook/react#5863]
Is there any way to get a string of plain html from a react component, but on the client side?

My app has a design editor that lets you click elements and edit their style, nothing new there, but I'm re-making it from the ground up using react both for the app itself and for the templates that should be edited inside an iframe and then rendered elsewhere.

Attaching click handlers to every editable element conditionally (eg: if the view is being rendered inside an iframe, for the editor) would be a nightmare, and I can't just use jquery $('.is-editable').click() like I used to because of the virtual DOM.

Taking all that in account, it seems that the only solution is rendering the would-be-edited view as plain HTML so I can use the $('.is-editable').click() approach inside my editor.

Any insights or similar experiences?

**Comment by jimfb** [comment]
I'm not entirely sure what you're asking.

If you want to render a React component to a string, you can use `ReactDOMServer.renderToStaticMarkup` on the client, as demonstrated in this fiddle: http://jsfiddle.net/d9ax06as/

If you want to get the `outerHTML` of a component, or otherwise work with the DOM node, you can attach a ref to the component (https://facebook.github.io/react/docs/more-about-refs.html).

Either way, this looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.
