### ISSUE TITLE
onclick change render

### ISSUE THREAD

**Issue by EasonWang01** [facebook/react#5875]
Hi,I'm new to react.If I want to click the button from DOM then change rendered class from CommentBox to CommentText below,how to do it using simple onclick function?Something like

```
if(btnclick){
ReactDOM.render(
  <CommentBox />,
  document.getElementById('content')
);
}else{
ReactDOM.render(
  <CommentText />,
  document.getElementById('content')
);

```

```
<div  id="content"> </div>
<button >  </button>
```
```
var CommentBox = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        <h1>Comments</h1>
       
      </div>
    );
  }
});

var CommentText = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        <h1>TEXT</h1>
       
      </div>
    );
  }
});
```

**Comment by jimfb** [comment]
This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.
