### ISSUE TITLE
Simulate.focus on es6 classes component

### ISSUE THREAD

**Issue by TinOo512** [facebook/react#5876]
Hi, 

I try to use `Simulate.focus()` on an input wrapped inside an es6 class, but it doesn't work. Maybe it's a limitation with `react-addons-test-utils` but I didn't find anything on this subject, ...

You can reproduce the issue here : https://jsfiddle.net/q8zk99n0/7/

**Comment by cody** [comment]
It works if you use `findDOMNode`. Change the last line to this:
```js
React.addons.TestUtils.Simulate.focus(ReactDOM.findDOMNode(instance2));
```

**Comment by jimfb** [comment]
@cody is correct, the Simulate utilities take in a DOM node, not a component.

**Comment by TinOo512** [comment]
@cody @jimfb oops my bad, ... Thx for quick your reply !

But actually my exemple was really bad I just tried to simplify the "real" issue which is, I can't test my `AutofocusTextField`  because when I call `this._ref.focus();` inside `componentDidMount` the `onFocus` callback is not trigger. Any idea why ?

You can reproduce the issue here : https://jsfiddle.net/q8zk99n0/10/

Let me know if I should open or new issue.

**Comment by jimfb** [comment]
@TinOo512 Usage questions like that are better addressed on StackOverflow, as we try to reserve github issues for bugs in the core.  With regards to your specific question: it's because most events don't fire when rendering into a disconnected dom node (like render into document).  I fixed your example here: https://jsfiddle.net/xr1qzttf/
