### ISSUE TITLE
a.toUpperCase is not a function

### ISSUE THREAD

**Issue by Tjorriemorrie** [facebook/react#5881]
Using [SmallGrid](https://github.com/Tjorriemorrie/react-smallgrid):
```
                <SmallGrid
                    rows={this.state.rows}
                    cols={[
                        {'key': 'rating', 'name': 'Rating'},
                        {'key': 'name', 'name': 'Title'},
                        {'key': 'count_albums', 'name': 'Albums'},
                        {'key': 'count_songs', 'name': 'Songs'}
                    ]}
                />
```
gives the error:
> TypeError: a.toUpperCase is not a function
> ...ion d(a){return o.createClass({tagName:a.toUpperCase(),render:function(){return ...

The library is built with grunt babelify and works fine in its examples.

**Comment by jimfb** [comment]
There really isn't much to go on here.  It sounds like you might have one of your dependencies miss-configured (most likely) or (perhaps less likely) there is a bug in SmallGrid or (even less likely) a bug in Babel.  Either way, this looks like it is probably not a bug in the React core, since `a.toUpperCase()` is happening in userland.

**Comment by syranide** [comment]
You get this error if `<MyType />` isn't an actual component. Maybe it's `undefined`, maybe it's an object etc. I believe newer React (or master at least) provides a better warning for this.

**Comment by Tjorriemorrie** [comment]
@syranide you are correct, I was creating my [library incorrectly](http://stackoverflow.com/questions/34878313/cannot-import-es2015-module/34878555#34878555). Sorry for taking up your time.
