### ISSUE TITLE
[Legal] What are the licence of the gh-pages site from facebook open-source

### ISSUE THREAD

**Issue by tychota** [facebook/react#5896]
I'm willing to use the facebook gihub.io templates for an own MIT licensed project.
Are the gh-pages site the same licence as main repository ??

I asked on twitter (https://twitter.com/TychoTa/status/687966716413014016) but no luck so far:
cc @vjeux

**Comment by iamdustan** [comment]
Does this help? (footer of documentation pages)
<img width="298" alt="screen shot 2016-01-21 at 7 26 56 am" src="https://cloud.githubusercontent.com/assets/227879/12480446/609df52c-c010-11e5-8e5e-d333028eecc9.png">

**Comment by jimfb** [comment]
Correct, the text/content of the page is licensed under CC BY 4.0.

We ask that you don't rip the styles (html/css) because we want to allow people to easily see when they are on an official facebook.github.io domain like https://facebook.github.io/flux/docs/overview.html#content or http://facebook.github.io/react/docs/ or http://facebook.github.io/relay/docs/getting-started.html#content

**Comment by tychota** [comment]
@jimfb : that was indeed my fear. I fully understand your reason.

However, this project won't strike the same public and more be headed to maximal 100 peoples.
Can I reuse css + html  as a base and do suffisant modifications (font, color, logo, width of the column ect) so it don't look a facebook project. If it is strictly impossible, don't worry I would serach other ccol template for vitrine site !

Anyway, thanks for answering !
