### ISSUE TITLE
Can i render every element with different render function?

### ISSUE THREAD

**Issue by darkautism** [facebook/react#5902]
I need some element only have html, and do not need data-reactid.

But I don't except i should render two element with different function( e.g. renderToStaticMarkup, renderToString) and combine it because the element could be include by many element. Render split and combine could cause mistake when element is much more.

If i could set an attribute in compoment:
```javascript
class DefaultLayout extends  React.Component{    
    render() {
        return (
            <html></html>
        );
    }
};
DefaultLayout.noNeedDiffCompoment = true;
export default DefaultLayout;
```

or a new pure html Compoment

```javascript

class DefaultLayout extends  React.PureHtmlComponent{    
    render() {
        return (
            <html></html>
        );
    }
};
export default DefaultLayout;
```
If i write as above, the render function can auto swap render function to render elements.

Is there any graceful solution?

**Comment by jimfb** [comment]
What you are looking for is `shouldComponentUpdate`.  If `shouldComponentUpdate` returns false, that tells React that your component doesn't need to rerender.

For future reference, this is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.

**Comment by darkautism** [comment]
Thanks your reply, but the server side render useing renderToString  will not call `shouldComponentUpdate`.
And i will move this topic into StackOverflow, many thanks.
