### ISSUE TITLE
Optional and required values in PropTypes.shape

### ISSUE THREAD

**Issue by silvenon** [facebook/react#5916]
Not sure if there's already a good way to do this, but it would be nice to be able to do this:

```js
PropTypes.shape({
  foo: PropTypes.string.isRequired,
  bar: PropTypes.number,
  baz: PropTypes.bool.isRequired
});
```

instead of having to do this:

```js
PropTypes.oneOfType([
  PropTypes.shape({
    foo: PropTypes.string,
    bar: PropTypes.number,
    baz: PropTypes.bool
  }),
  PropTypes.shape({
    foo: PropTypes.string,
    baz: PropTypes.bool
  })
]);
```

The latter can get quite big if there are multiple optional values.

**Comment by jimfb** [comment]
As per #5080 (comment):
 > propTypes are mostly in a sort of maintenance mode and we're not really planning to add more to them right now.

This would be a breaking change, because we would be inverting the default requiredness of something in `PropTypes.shape`.  Proptypes are being replaced by static analyzers like Flow. For this reason, I'm thinking we probably wouldn't do this.

**Comment by ibrahima** [comment]
Hmm, I realize this issue is old, but it actually seems to me like it does work like the first example in the original post. Did something change? I found this issue because I was trying to figure out whether you can use `isRequired` inside PropTypes.shape and because of this I thought that you can't, but the behavior I'm seeing right now is that if I do something like the first example, only the attributes marked with `isRequired` are actually required, and other props are still optional and don't cause warnings if they're not passed in.

This is on prop-types 15.5.0.

**Comment by silvenon** [comment]
I also remember this working like I wanted when I tried it later on. But I also know I would have tested this before opening the issue… meh, if it works, it works. 😄

**Comment by interactivellama** [comment]
I'm getting the same behavior as https://github.com/airbnb/prop-types 's shape now and it does not require all keys to be present anymore. I remember all keys needing to be present back in 2016, also.
