### ISSUE TITLE
Provide a way to register a last-chance exception handler

### ISSUE THREAD

**Issue by RandScullard** [facebook/react#5941]
React should provide a way for us to register a last-chance exception handler for errors thrown in React event handlers. We have last-chance exception handlers registered for our other event-handling frameworks and this has proved extremely useful for making us aware of unexpected error conditions.

**Comment by jimfb** [comment]
Yeah, I could see this fitting into the error boundaries stuff.

**Comment by RandScullard** [comment]
Just to clarify -- the error boundaries stuff seems to be talking exclusively about errors on the render stack, and I'm talking about errors thrown from an event handler. The reason I'm focused on event handlers is that they tend to be at the root of a whole lot of other code and thus a good place to consider last-chance exception handling.

**Comment by jimfb** [comment]
Actually, now that I've had a couple days to think about it, I'm seeing some issues, and I don't see any real benefit.  Why would you want this feature?  What would this allow you to do beyond what `window.onerror` already allows?

**Comment by RandScullard** [comment]
We've been using try/catch rather than window.onerror so that we can get access to the thrown error object in all the browsers we support, which unfortunately still includes IE 10 and Safari 6. The error object also gives us the stack trace. In IE 10 and Safari 6, window.onerror doesn't give us access to the error object or its stack trace.

If React would call some type of onerror hook in the catch block of its root event handler, then we could get access to all the error information we need. What issues do you see with this?

**Comment by jimfb** [comment]
The biggest issue is performance.  It would require wrapping every event (even mouse-move events, which can fire super frequently) in a try-catch block, which causes the JSVM to deopt.

It also gets complicated because (if we used an error-boundary as the catch point), it's not clear what the semantics should be if the parent of an error boundary passes a callback into the child of an error boundary, and an exception is thrown when the child invokes the grandparent's function.  In that case, the grandparent is the broken component (ie. the one in a potentially erroneous state), but the child is where the exception pops out of the system (thus, we don't know to fatal the grandparent).

Probably the best solution would be to figure out a solution for https://github.com/facebook/react/issues/285 and then smooth out the interface for IE10 and Safari6.

**Comment by RandScullard** [comment]
I must be missing something on your performance point. When I look at the call stack for one of my React event handlers, I see that three React functions on the stack already have try/catch/finally blocks:

    ReactErrorUtils.invokeGuardedCallback
    ReactDefaultBatchingStrategyTransaction.perform
    ReactEventListener.dispatchEvent

The last-chance error handling could be integrated into one of these existing exception handlers with no performance cost. (And anyway, I thought that deoptimization occurs at the function level, so adding a try-catch block to an otherwise trivial dispatcher function has no practical impact -- please correct me if you know otherwise.)

Since what I have in mind is such a simple change, it seems a shame to get it wrapped up in the complications of error boundaries and issue #285. If the React team doesn't see a good fit for this in the core project, I guess we'll go ahead and implement it on our fork to meet the needs of our system.

**Comment by jimfb** [comment]
I think it is a fit:
 > Probably the best solution would be to figure out a solution for #285 and then smooth out the interface for IE10 and Safari6.

It's just not a super high priority for us, since the only upside is the ability to log slightly more detailed error information (specifically stack traces) on legacy browsers.  It doesn't (as far as I can tell) affect the control flow of the program and doesn't affect any of the primary browsers.  Ultimately, I think this is a request for a synthetic version of a very specific global event, which is why https://github.com/facebook/react/issues/285 seems the most relevant.

I don't see any solutions that are cleaner than https://github.com/facebook/react/issues/285, but if I'm missing something, let me know!  If it is a simple change with no performance/api impact, submit a PR and we'd be happy to take a look!

**Comment by RandScullard** [comment]
Please see PR #5973. This meets the needs of our project, and I hope you will find that it fits well with the design of React. If not, I welcome any suggestions to improve it.

**Comment by byronmwong** [comment]
@RandScullard I think this fits your use case: https://engineering.classdojo.com/blog/2016/12/10/catching-react-errors/

**Comment by RandScullard** [comment]
@byronmwong Thanks, but we actually found a good solution -- see the discussion on PR #5973 for details.

**Comment by gaearon** [comment]
For the reference, the solution is in https://github.com/facebook/react/pull/5973#issuecomment-229386429.
