### ISSUE TITLE
envy me

### ISSUE THREAD

**Issue by Maxmaxmaximus** [facebook/react#5950]
envy me and take for themselves something useful
it's my mega framework:
https://www.youtube.com/watch?v=SDzkIIj1zdY

**Comment by gaearon** [comment]
Thank you for sharing your work. It has been an intentional decision to avoid two-way data bindings in React. In fact you can see the new versions of some modern frameworks such as Angular and Ember also using two way data bindings less in favor of explicit updates. Additionally, it was an intentional decision to not use a special template syntax in favor of plain JavaScript (which JSX compiles to). This allows us to run JavaScript tools (for example, linters or optimization transforms) on the source code and avoid any parsing overhead as well as a custom control flow language.

In any case, we use the issue tracker for focused discussions about React features and bugs. If you would like to propose a specific feature that you feel React lacks, please use the search, and if it has not been proposed before, file an issue describing it specifically. I’m closing this issue as overly broad, and not be honest, not very constructive.

**Comment by Maxmaxmaximus** [comment]
Actually, I do not have any special syntax, the fact that the attribute name is available these characters  !()[].#

**Comment by zidein07** [comment]
@Maxmaxmaximus хуйня, иди нахуй!

**Comment by gaearon** [comment]
I’ve removed a comment with personal attack (to clarify, it didn’t come from OP). I’m locking the thread to prevent further derailing. As I said before we are happy to consider specific suggestions to improve React but they have be specific and constructive.
