### ISSUE TITLE
Updates not queued properly when using unstable_renderSubtreeIntoContainer

### ISSUE THREAD

**Issue by jimfb** [facebook/react#5990]
The cursor should not jump to the end of the text field when editing text: https://jsfiddle.net/h89zmzp8/

It's `unstable_`, so it probably doesn't need to be fixed before the v15 milestone, but we should get it fixed at some point.

cc @jquense

**Comment by jquense** [comment]
Thanks for pruning the noise out of my original repo, much clearer now :)

It seems like a more first-class subtree concept would probably address this? That is probably a larger discussion but such a thing would also be helpful for tooling, (thinking about `findInRenderedTree` with modals).

In this particular case: is there likely any way to fix this without a fair amount of work

**Comment by jquense** [comment]
So I've taken some stabs at addressing this, and I've manged to "fix" it, but not in a way I think is architecturally helpful. So before sending over a PR i'd thought I post a rundown of what I've found.

1. All of the updates are being "enqueued" during the same run of the reconcile transaction, which is what we'd want.
2. The __problem__ is that the TopLevelWrapper for the subtree is only being enqueued _during_ the processing of dirty components in: [`runCatchedUpdates`](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactUpdates.js#L167).

Right now, the update queue is fully processed, then in the closure of the transaction if any new components were queued, [it runs again](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactUpdates.js#L43-L50).

I've managed to "fix" the jumping issue by having the runBatchedUpdates loop check if a new component was added, if so [re-sort by mount order](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactUpdates.js#L139) which moves the newly added Subtree TopLevelWrapper above any of it's currently queued children components and so the updates are processed in the correct order.

The main problem here is that deferring newly queued updates makes sense when triggered in `componentDidUpdate` but not when the update renders a subtree. To me it seems like there are two main approaches to addressing this:

1. Make Subtrees a "core" concept for reconcilers and have components track and treat rendered subtrees in the same way as direct children. That way updates in a parent would naturally reconcile the subtree, instead of having this two step process of update -> flush -> re-renderSubtree.

2. (how I hacked a fix) Adjust runBatchedUpdates to process newly enqueued subtree TopLevelWrappers in the same loop. Right now though, there doesn't seem to be any way for the ReactUpdates to tell if a component is a root component, let alone a subtree root in order to pull it out and process it it as compared to other newly queued dirty components.

So option __2__ is easier, but feels leaky. Option __1__ seems like a good idea but would make the current API sort of untenable, and I'm not sure how to translate it...perhaps something like `createFragment`:

```jsx
render() {
  return (
    <div>
      <Foo />
      { createSubtree(<Modal />, mount) }
   </div>
  )
}
```

I haven't looked closely enough at that approach to understand where the concerns might be, but I assume that adding a new special kind of child isn't exactly a simple thing.

**Comment by spicyj** [comment]
I'm too tired to fully understand the problem you laid out, but 1 is probably the correct solution. The fiber reconciler already has partial support for this.

**Comment by jquense** [comment]
I has was thinking about this recently. I'd be happy to help flesh out said partial support, though Ive sort of  renders deferring this sort of things while the new reconciler was in flux. any place in particular to start looking?

**Comment by Kielan** [comment]
it's a bit frustrating nobody has gotten to this, if nobody is going to try to fix the rendering it should be placed on the front page of react website that forms cannot be placed inside of modals realiably.

**Comment by sophiebits** [comment]
Hi @Kielan -- this has not been directly fixed because it is difficult to fix and does not come up for most people. It also helps if people come to (politely) voice their need for a particular bug fixed, which you never did. Otherwise we don't know what to prioritize. Please also remember that this is an open source project that is provided for free and anyone (like you) is free to contribute bug fixes if they're important to you personally.

In React 16 you can use ReactDOM.unstable_createPortal which implements strategy 1 from above and should not have any of these timing problems.

**Comment by Kielan** [comment]
@sophiebits not trying to be rude, I do think this is a really tough bug to track down, in the past I actually found a solution to it but it has come up on yet another project and honestly I'm surprised no one has gotten to it/the pull requests which have been offered have not been accepted and not much feedback was given as to how to improve the pr.

https://github.com/HubSpot/draft-extend/pull/14

**Comment by gaearon** [comment]
The new portal API in 16 addresses this issue. You can try React 16 RC which we released recently. Have you tried it? It’s not documented yet but you can use `ReactDOM.unstable_createPortal(<MyModal />, domNode)` in the `render` method as part of the returned tree.

**Comment by jquense** [comment]
I did the initial debugging work on this with Jim to locate the problem and the consensus was the only real way to fix this is to add real first class portals to React. And as the others have noted that has landed in React v16!  We should make a point to document that, when Portals are documented, but we;ll be able to close this issue :)

**Comment by gaearon** [comment]
Documented now. :-)
https://facebook.github.io/react/docs/portals.html
