### ISSUE TITLE
console shows error: Uncaught Invariant Violation

### ISSUE THREAD

**Issue by purezen** [facebook/react#5995]
I am making an app based on [this](https://github.com/gaearon/react-transform-boilerplate) boilerplate. Ref: [gist](https://gist.github.com/purezen/e421917fca4c05bb2c05)

The app is building fine, but my console shows this error:
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by maartenbusstra** [comment]
Need a return statement there:
https://gist.github.com/purezen/e421917fca4c05bb2c05#file-tasklist-js-L6

**Comment by purezen** [comment]
@maartenbusstra, that doesn't help either. Am updating the gist.

**Comment by maartenbusstra** [comment]
Is your import statement working? `import TaskList from './TaskList';`

**Comment by jimfb** [comment]
This is almost certainly a usage question, rather than a bug in the React core.  Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).

**Comment by purezen** [comment]
@maartenbusstra yes, it is. Also, things were working fine as long as I pass a string as a value in the object, like
'''
this.state = { tasks: "Task 1" }.
I am able to render it in the TaskList component.

**Comment by purezen** [comment]
Hmm.. this seems to be an issue with react-transform-boilerplate since the code is working fine on another setup.

@maartenbusstra should be, since when I pass TaskList an object with a string value instead of the array of objects here.. it is able to render fine.
