### ISSUE TITLE
svg clipPath has wrong namespace

### ISSUE THREAD

**Issue by IL55** [facebook/react#6012]
Hi,
when svg.clipPath created "dynamically" (i.e. via button click) has wrong namespace
more details here https://jsfiddle.net/ceejpt0z/16/
(press button `Add new center`)

For test I use React 0.14.7 (is it latest react ?)
I thought, that it should work, thanks this pull request
https://github.com/facebook/react/pull/5714

I see that `clipPath` added here (and `circle` too):
https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactDOMFactories.js#L155

And `circle` works OK but `clipPath` - no.

**Comment by jimfb** [comment]
Try it in this fiddle: http://jsfiddle.net/9kungxn4/

**Comment by IL55** [comment]
for your fiddle it works ok, so for new react it solved
could you recommend me some patch for 14.7 react (since it is stable react) ?
Here is fiddle for new react: http://jsfiddle.net/om4jjoq2/2/, 
I also updated link in original message (sorry bad fiddle)

**Comment by jimfb** [comment]
Ok, I'm going to close, since it's fixed in master.

You could try cherry-picking some commits over, but honestly, I would recommend just wait for 0.15 to be released.  If you're really in a hurry to play with it, you could try using a future build, but you should be aware that we don't guarantee that it will be stable.

**Comment by IL55** [comment]
Thanks, I found that it can be fixed for 0.14.7 via `dangerouslySetInnerHTML`. So no problem for now and thanks guys for you work.
