### ISSUE TITLE
Setters not preserved with React.createClass

### ISSUE THREAD

**Issue by cauburtin** [facebook/react#6023]
setters in `React.createClass` are ignored http://jsfiddle.net/crl/fu06rxw8/3, 
but they work with class syntax http://jsfiddle.net/crl/fu06rxw8/4/

Wouldn't it be possible to create the component class from the object given and preserve any setters/getters?

**Comment by jimfb** [comment]
Probably not in a remotely performant way.  Performance of module initialization (which directly influences initial load time) would be fatal.  http://jsperf.com/sdfewfgwasd/2

Going to close this out, because...  it's an edge case that people rarely hit, I don't think we can support it in a performant way, and the workaround is to use ES6 classes.

Feel free to continue the discussion on this thread.  We can re-open / re-examine if our thinking on this matter changes dramatically.

That said, I am curious to hear about your use case.  What are you trying to do?

**Comment by zpao** [comment]
There's some other discussion in #4450 & #2575 which should give more background. I don't think we intend to make any fundamental changes to the way createClass works so it's really unlikely we'd make setters work.

**Comment by cauburtin** [comment]
Ah ok thanks guys, performance ok, and even through mixins it's not possible?, I didn't manage as well.

@jimfb I'm doing an html 'wysiwyg' editor, and for a few components, it's a bit dirty because they should be updated by many different events (selectionchange, keydown, mousedown), quite frequently (even if throttled). So sometimes I choose to update the position of popover (div overlay) manually rather, with vanilla js. (Another example of where I can't use react is [this](https://discuss.reactjs.org/t/react-can-be-quite-slow-for-fast-interactions-like-mouseenter-events-in-a-grid/3077/3) http://jsfiddle.net/crl/ckvstvrk/35/ react is too slow for these sort of things)
