### ISSUE TITLE
Dynamic pure components re-initialized despite key attribute when using jsx

### ISSUE THREAD

**Issue by a-s-o** [facebook/react#6035]
Hello,

I am using pure components but am generating them dynamically. Doing so registers as a change in react's diffing algorithm despite having a key attribute, therefore, the components' state (ex: focus) resets on each re-render.

example:
```javascript  
render ({ dispatch, loginState }) {
    const [ Username, Password ] = LoginFields.partiallyApply({ dispatch, state: loginState });
    return (
      <div className={classes.container}>
        <Username key='Username' placeholder='Username/Email address' />
        <Password key='Password' />
      </div>
    );
}
```
I expect this is a weird way of using the components, but in the example above, the `LoginFields.partiallyApply` function does some internal work to assign state and event handlers to some form components and then returns the bound components in an array so that any additional props can be provided (assigned to `Username` and `Password` using de-structuring in this case; these are just functions that return some input controls).

The state/event handling work is a bit repetitive and depending on the number of fields it can be a lot, so I am trying out new ways of extracting it out.

The above components when used as `jsx` elements cannot be diffed, get re-instantiated each time and lose focus on each key stroke.

Alternatively, if I write the view portion as follows, everything works just fine:
```javascript
    return (
      <div className={classes.container}>
        {Username({ key: 'Username', placeholder: 'Username/Email address' })}
        {Password({ key: 'Password' })}
      </div>
    );
```
Since both of those components are just functions, we can do that, but this is a bit odd looking, especially considering the old deprecated component syntax. 

I suspect the issue is in `React.createElement`. Can something be changed or is this way to out there?

Appreciate any help. Thanks.

**Comment by zpao** [comment]
For createElement the generated element has a `type` field which is assigned from the first argument (`Username`). `type` is then used internally to do some optimizations about if we can do an update or if we have to unmount and create a new instance. We just do identity comparison for that so when you are creating a new identity for `Username` on each render, you are making React think it's a teardown & recreate operation, not a simple update. This means tearing out DOM nodes entirely which is especially bad for form elements.

Since you aren't really applying state (in the `this.state` sense) you are really just setting some props. You can use JSX spread to achieve the same thing.

```js
var partial = { dispatch, state: loginState }
return <UsernameComponent {...partial} key="username" placeholder="username/email address" />
```

We're really unlikely to be able to optimize for your case and it would come at other costs so I think we'll likely just maintain our current behavior here. Hopefully the above provides some insight and you can come up with a different pattern.

**Comment by a-s-o** [comment]
Yes, thank you very much for the explanation. I was thinking it was some kind of internal tracking. Appreciate you taking the time to provide details of the mechanism.
