### ISSUE TITLE
Async routes cause server-side checksum invalid error

### ISSUE THREAD

**Issue by Sawtaytoes** [facebook/react#6041]
**NOTE:** This may be an issue for React Router instead. If so, please inform me, and I will notify them.

I'm using Webpack, react-router, and react.

I got this error while using react-router with async routes and server-side rendering:

```shell
bundle.js:1 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <noscript data-reacti
 (server) <div data-reactid=".1
```

My routes.cjsx has this:

```coffee
# Routes
path: 'game'
getComponent: (location, cb) =>
	require.ensure [], (require) =>
		cb null, require './views/game'
```

If I change it to this, I no longer get that error:

```coffee
# Routes
path: 'game'
getComponent: (location, cb) =>
	cb null, require './views/game'
```

Is this a bug or something else?

**Comment by jimfb** [comment]
@Sawtaytoes As I have already mentioned to you on other threads, StackOverflow is the more appropriate place for usage questions.  This is most likely an issue with your code/configuration, rather than a bug in the React core.  For this reason, I'm going to close out the issue.  If you have a simple jsfiddle that demonstrates a bug in the React core, we'd be happy to re-investigate.

**Comment by zp1112** [comment]
I met the same question,do you fix it?

**Comment by Sawtaytoes** [comment]
This is the StackOverflow solution I wrote up to the issue: http://stackoverflow.com/questions/35368285/react-checksum-invalid-server-rendering
