### ISSUE TITLE
ReactDOM not define in "react": "^0.14.7"

### ISSUE THREAD

**Issue by EasonWang01** [facebook/react#6053]
React.render works fine,but not ReactDOM.render

```
{
  "name": "class1webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "dev": "webpack-dev-server --devtool eval --progress --colors --hot --content-base build"
  },
  "author": "Eason",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.2",
    "react": "^0.14.7",
    "webpack": "^1.12.13",
    "webpack-dev-server": "^1.14.1"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0"
  }
}

```

**Comment by satya164** [comment]
You don't have a dependency on the `react-dom` package.

**Comment by EasonWang01** [comment]
If I don't require react-dom and using React.render,is there are any shortcoming rather then using ReactDOM.

**Comment by syranide** [comment]
@EasonWang01 `React.render` is deprecated. React is now a generic library and independent of any specific frontend, i.e. you need to use `ReactDOM` if you want to target the DOM (or `ReactNative`, etc).

**Comment by jimfb** [comment]
@satya164 and @syranide are correct.

This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).
