### ISSUE TITLE
"Dynamic" propTypes

### ISSUE THREAD

**Issue by maqqju** [facebook/react#6066]
Hi,

I am trying to construct a mixin which takes a dev-defined component specification and constructs its prop-types + defaults accordingly. I am trying to do something like this:

`
var _generatePropTypes = function(customData) {
      //do the process here
}
var MyMixin = {
      propTypes : _generatePropTypes(this.getCustomData()),
      getCustomData : function() { return this.customData;}
}
`

The above code does not work. Is there anyway I can do something similar?

Many thanks!

**Comment by jimfb** [comment]
It's a little hard to tell without being able to run your code fragment (especially since you didn't tell us what error message/problem you were getting), but I assume you are failing on the `this.getCustomData()` expression.  Assuming that's the case, you should note that a mixin is just an object, so `this` is not accessible, so you are going to have to restructure your code to avoid using `this` in that context.

Also, we use github to track bugs in the react core, rather than usage questions.  A more appropriate place for usage questions is StackOverflow.  This looks like a usage question, so I'm going to close out this issue, but feel free to continue the conversation on this thread or move the discussion over to StackOverflow.
