### ISSUE TITLE
why this.props.children cannot re-render?

### ISSUE THREAD

**Issue by hufeng** [facebook/react#6072]
for example:
```js

class Parent extends React.Component {
 componentDidMount() {
  setTimeout(() => { this.forceUpdate();}, 1000);
  }

  render() {
   return <div>{this.props.children}</div>;
  }
}

class Child extends React.Component {
  render() { return <div>{this.props.random}</div>}
}

class App extends React.Component {
  render() {
   return (
     <Parent><Child random={Math.random()}/></Parent>
   );
  }
}

```

**Comment by jimfb** [comment]
It is because `Math.random()` is executed when `App` (your `Parent` component's parent, the `Child`'s grandparent) is rerendered.  If you rerender the app in the settimeout, it should do what you want.

Also, we use github to track bugs in the react core, rather than usage questions. A more appropriate place for usage questions is StackOverflow. This is a usage question, so I'm going to close out this issue, but feel free to continue the conversation on this thread or move the discussion over to StackOverflow.
