### ISSUE TITLE
ReactJS setState bug/my fault 

### ISSUE THREAD

**Issue by m6g6a** [facebook/react#6075]
Hello, guys!

I made an exemple here to see exactly what I'm talking about:
http://codepen.io/mga/pen/bEyZox

I used context for the "storeInput" function because in my app it passes through more than one component.

Sorry for the short message but I don't have the best writing english skills and it's more easier for me to show you. If you don't understand something please let me know. Thanks!

**Comment by m6g6a** [comment]
here's a solution:
```
storeInput(inputName, inputValue) {
  const { state } = this

  this.inputs = {
    ...this.inputs,
    [inputName]: inputValue
  }
  
  this.setState({
    ...state,
    form: {
      ...state.form,
      ...this.inputs
    }
  })
}
```

**Comment by jimfb** [comment]
We use github to track bugs in the react core, rather than usage questions. A more appropriate place for usage questions is StackOverflow. This is a usage question, so I'm going to close out this issue, but feel free to continue the conversation on this thread or move the discussion over to StackOverflow.
