### ISSUE TITLE
Frameworks?

### ISSUE THREAD

**Issue by TylerL-uxai** [facebook/react#6078]
Does facebook recommend a good backend to go with react? Maybe something that already has login page features built in?

**Comment by jimfb** [comment]
We use github to track bugs in the react core, rather than usage questions. A more appropriate place for usage questions is StackOverflow. This is a usage question, so I'm going to close out this issue, but feel free to continue the conversation on this thread or move the discussion over to StackOverflow.

Our recommended architecture is [Flux](https://facebook.github.io/flux/).  Facebook uses a backend called [Relay](https://facebook.github.io/relay/).

**Comment by TylerL-uxai** [comment]
Thank you for following through with a detailed response, jimfb. I can't really use stackoverflow because the community would attack everything I say. But I'm glad you were kind enough to answer my question. Thank you.
