### ISSUE TITLE
Issue with native change event on select and valueLink

### ISSUE THREAD

**Issue by iseeyou911** [facebook/react#6079]
Hello, i'm trying to make a validator for forms, and i want to make possible of usage LinkedStateMixin with the validator. So, for inputs validation i use native events (addEventListener), for it, i make following actions (it's just an approximate algorithm)

```
<input valueLink={linkState('input1')}
           ref={(node)=>{this.inputs.push(node)}}/>
<select name="selectValue"
        ref={(node)=>{this.inputs.push(node)}}
        valueLink={this.linkState('selectValue')}>
                {['', '1', '2', '3', '4', '5'].map((item)=> {
                    return <option key={item} value={item}>{item}</option>
                })}
</select>
```
```
componentDidMount(){
    this.inputs.forEach((node)=>{node.addEventListener...});
}
```

In event handlers (change, blur, keyup) code i perform setState method, if valid state is chaged. With _input_ tag it works very fine, value of state.input1 was changed as expected, but for _select_ tag state.selectValue was changed only one time. So, it's the problem. And i think, this is an issue.

Is it possible at all to make such things work, or i am in the wrong way? I have some Jest tests, i can share it, if needed.

**Comment by jimfb** [comment]
I'm not entirely sure what you are asking, but this looks like a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.

With regards to the specifics of your code...

- You mentioned that you are using `addEventListener`, but you should be aware that native events and synthetic events don't play nicely together.  It may work in this case, but the pattern should generally be avoided because you're going to shoot yourself in the foot.
- `valueLink` is going to be deprecated in v15.  My recommendation is that you just set `value` and `onChange` directly.
- I'm not entirely sure what you mean by "for select tag state.selectValue was changed only one time".  If you think you've found a bug in React, please create a simple jsfiddle that demonstrates the issue using an onChange handler, and we can re-investigate.

**Comment by iseeyou911** [comment]
@jimfb, tnx for your answer. I describe my situation just because i did not sure that it is a bug. But if `valueLink` is going to depricated, i don't think that following investigation is needed.
