### ISSUE TITLE
Proposal: bind component to SyntheticEvent

### ISSUE THREAD

**Issue by Pholey** [facebook/react#6105]
The common way to send additional properties to onClick handlers is with `.bind`:
```jsx
<div>
{this.props.items.map(x => <div className="item" onClick={this.handleClick.bind(null, x.val)}>{x}</div>}
</div>
```

[ESLint](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md) Suggests that constant .bind calls in render are no good for performance, and recommends to pass data from the child's onClick handler back to the parent handler:

```jsx
var List = React.createClass({
  render() {
    return (
      <ul>
        {this.props.items.map(item =>
          <ListItem key={item.id} item={item} onItemClick={this.props.onItemClick} />
        )}
      </ul>
    );
  }
});

var ListItem = React.createClass({
  render() {
    return (
      <li onClick={this._onClick}>
        ...
      </li>
    );
  },
  _onClick() {
    this.props.onItemClick(this.props.item.id);
  }
});
```

However, i feel this is a bit detrimental to readability (not to mention, a bit of a pain to write for something as simple as partial functions, which get used everywhere seemingly), because i (as another programmer) now need to go to the child definition (which could very well be in another file) to find out what exactly my child is passing me in my parameter list. Not to mention how complex an onClick handler may become by another developer coming in and modifying the code to handle their own event properly as well. (god help them if they have to propagate & modify their params through multiple layers)

Example:

```jsx
function Foo({text}) {
    return (<li>{text}</li>)
}

class Bar extends React.component {
    handleClick(e) {
        console.log(e.component.props.text)
    }

    render() {
        return (
            <div>
               <Foo text={"baz!"} onClick={this.handleClick}/>
           </div>
        )
    }
}
```

The idea here is to attach the component the event originated from to the synthetic event. Would something like this be possible/feasible/even needed (Does bind really bring that much of an impact)? Is there another, better way to do this without `.bind`?

**Comment by jimfb** [comment]
Creating a `ListItem` component is probably at least as much overhead as using bind.  When choosing between those two options, I'd personally just use bind at that point.

One solution is to define (in the constructor): `this.handleClick = this.handleClick.bind(this);`  Then you aren't re-binding with each render.

The problem with binding the event to the component is that the event might be passed up via the component API:

```jsx
class Bar extends React.component {
    render() {
        return (
            <div>
               <Foo text={"baz!"} onClick={this.props.handleClick}/>
           </div>
        )
    }
}
```

When your app attaches an event handler to Bar, what would be the expected value of `e.component`?  Naturally, you would want it to be an instance of App, but it can't be an instance of App, since React has no way of knowing that App was the ultimate source of the event handler (the handler was just passed along).  Thus, I think the model you proposed is broken in the general case.  You're going to have to use one of the workarounds described above.

**Comment by inomdzhon** [comment]
Hi there 😅

@jimfb What about use `_targetIns` for detect item?

Demo: https://codesandbox.io/s/react-event-handlers-for-list-item-j84li
