### ISSUE TITLE
cloneElement vs createElement

### ISSUE THREAD

**Issue by james4388** [facebook/react#6115]
Can anyone let me know if using cloneElement (on exist element instance) or createElement (on react Element class) which one is better in term of performance?
Sometimes cloning something is faster than create new instance. Please let me know. Thanks

**Comment by jimfb** [comment]
We use github to track bugs in the react core, rather than usage questions. A more appropriate place for usage questions is StackOverflow. This is a usage question, so I'm going to close out this issue, but feel free to continue the conversation on this thread or move the discussion over to StackOverflow.

With regards to your question, they should be roughly the same speed, but if you want super-accurate results, you should do your own benchmarking for your use case and data.
