### ISSUE TITLE
Use static get for propTypes in ES6 classes?

### ISSUE THREAD

**Issue by ffxsam** [facebook/react#6125]
Regarding this:
https://facebook.github.io/react/docs/reusable-components.html#es6-classes

Could we not just do something like this?

```jsx
class Thing extends Component {
  static get propTypes() {
    return {
      name: PropTypes.string.isRequired,
    }
  }

  render() {
    return <div>
      Hello {this.props.name}.
    </div>
  }
}
```

**Comment by zpao** [comment]
Yes, you can technically do that however we don't like static getters if we can avoid them. One reason is that it doesn't match the behavior of static properties. With a getter you could do something mutative AND you'll be allocating for each call. You could return different things each time, which doesn't match the expected behavior. Our preferred syntax will be property initializers but that spec has not reached a point in the standardization process where we're comfortable recommending it in our documentation.
