### ISSUE TITLE
Nesting components

### ISSUE THREAD

**Issue by mariusrak** [facebook/react#6168]
Hello,
I wanted to add two another components under one so I did something like

    React.createClass({
        InsideComponent: React.createClass({ ... })
    });

And used it like this:

    <this.InsideComponent />

Which didn't work and required me to use React.createFactory (message `Something is calling a React component directly. ...`). So I tried something like:

    React.createClass({
        InsideComponent: React.createFactory(React.createClass({ ... }))
    });

Which works fine, however, when I wanted to add children like this:

    <this.InsideComponent>
        <child_a />
        <child_b />
    </this.InsideComponent>

And reference them using `this.props.children` it didn't work. I got message `Objects are not valid as a React child (found: object with keys {}). ...` logged in console they looked like this:

![children](https://cloud.githubusercontent.com/assets/12086263/13463683/be87da34-e08d-11e5-8129-99cb107d5141.png)

So I went through react code and find `autobind`. I set it to false and now everything works correctly, however I guess, there will be problems with that approach in future, because I belive autobinding is useful or, will be useful somewhere else in my outer component.

Is it bug or am I doing something wrong?
Thank you

**Comment by jimfb** [comment]
Sounds like autobinding might be screwing with the factory somehow.  I'm a little surprised that the code you mentioned didn't work, do you have a minimal jsfiddle?

Yeah, we wouldn't recommend disabling autobinding in your copy of React, since that will make your components not interoperable with third party components.  You might try writing your component as an ES6 class, since ES6 classes don't have autobinding.

I'm also curious to hear why you are doing `this.InsideComponent`.  It sounds like some sort of weird nested class logic.  In general, it's probably cleaner to just define another top-level class.

`React.createClass` is mostly legacy at this point, so I don't think we're going to make major changes to the autobinding code at this point.  However, I would be curious to hear what you discover.

**Comment by mariusrak** [comment]
I'm tring to encapsulates parts that logically belongs together. To be more specific I build tabs component. So first 'InsideComponent' would be tabs list and second would be the tab's panel. Since they share some logic it is better to have them together in one file next to each other.

**Comment by jimfb** [comment]
They can live in the same file without having a nested class arrangement.

**Comment by syranide** [comment]
> Sounds like autobinding might be screwing with the factory somehow. I'm a little surprised that the code you mentioned didn't work, do you have a minimal jsfiddle?

I assume because a component looks like a function, which would then be autobound and thus no longer look like a component to React.

Anyway, unless you intend to make `InsideComponent` dynamic (it should be received through props really) then it shouldn't be an instance property at all but rather a static property on the component. Thus `statics: { InsideComponent: ... }` + `<MyClass.InsideComponent />`.

**Comment by mariusrak** [comment]
syrandie, I need them to be dynamic, since they are part of higher component.

**Comment by jimfb** [comment]
> I need them to be dynamic

@mariusrak, you can always store the state in the parent and pass it down explicitly to the child.  In general, anything that can be done with nested classes can be done without nested classes.  I think nested classes (like inheritance) are a bit of an antipattern anyway.  I would recommend finding an alternative structure for your code.

`createClass` is mostly legacy at this point, and we generally aren't making large changes to the way it works.  You're welcomed to submit a PR if you'd like, and we'll take a look and decide if it makes sense to merge based on the scope of the change, but I don't think this is something we'd fix ourselves.  For this reason, I'm going to close it out.

Feel free to continue the discussion on this thread.  In particular, I'm curious to hear if ES6 classes solve your problem (since there is no autobinding) or if you figure out a potential fix to the autobinding code that we could integrate into React.

**Comment by mariusrak** [comment]
I would like to avoid passing everything down to children via props, since it's a lot of code and since those components are tightly coupled,i belive my pattern is fine.

I decided to not use ES6 classes, since they elminiate a lot of things i like about react (like mixins) and require binding every function to the object, which is really annoying and seems redundant, and lot of other code in opposite to `createClass`. As is described in this article https://toddmotto.com/react-create-class-versus-component/

Do you plan to deprecate `createClass` in near future? Would it be possible to find ways to elminate those "problems" in ES6 classes?
Thanks.

**Comment by jimfb** [comment]
@mariusrak No, there are no plans to deprecate `createClass` in the near future.  It's just in maintenance mode, and new development work goes into optimizing ES6 classes and stateless functions.  Most of those "problems" (mixins, autobinding, etc) were intentionally omitted after we gained a lot of experience with those APIs and determined that they were not good patterns.  Mixins make it much more difficult to maintain your code because things get injected sideways, autobinding leads to issues exactly like the one you're describing in addition to many other edge-case issues.  The recommendation is still to upgrade to ES6, since we believe it is better, but `createClass` will continue to work for the foreseeable future.
