### ISSUE TITLE
title tab value rendering using react

### ISSUE THREAD

**Issue by naveensinghdahiya** [facebook/react#6182]
Hello React, 
<pre>
Is their a way to show rendered element's value in title.
like, we have:-

var $title = &lt;span>my title&lt;/span>
&lt;div title={$title}>my value&lt;/div>

OUTPUT should be like this:
&lt;div title='my title'>my value&lt;/div>
</pre>

**Comment by jimfb** [comment]
Yes, http://jsfiddle.net/30sf8Lh3/

This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).
