### ISSUE TITLE
[SVG] Support "focusable" attribute

### ISSUE THREAD

**Issue by Kureev** [facebook/react#6212]
Currently, if I supply a `focusable` attribute to the SVG, it shrinks it out. Seems it happens because there is no `focusable` key in [SVGDOMPropertyConfig.js](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/SVGDOMPropertyConfig.js). 

So is there any chance you merge a PR which adds this property to the list?

**Comment by gaearon** [comment]
React 15 removed whitelisting attributes for SVG completely in #5714. The names left in the [whitelist](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/SVGDOMPropertyConfig.js) are only there to print deprecation warnings. You will find that any arbitrary attribute, including `focused`, should get passed correctly in in any version >= 15 RC1. 

React 15 RC1 was [shipped yesterday](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html) so I would suggest you to check it out. I would expect 15 to arrive shortly within a few weeks.

**Comment by Kureev** [comment]
Thanks :+1:

**Comment by gaearon** [comment]
Seems like we’re going to go back on that change (see #6243).

Are there any browsers that actually support `focusable`?
We can add it if that’s the case but [from a quick look it doesn’t appear to be implemented](http://stackoverflow.com/questions/22671799/svg-focusable-attribute-is-not-working).

**Comment by alexlande** [comment]
IE10, IE11, and Edge support `focusable`, unfortunately. If you don't specify `focusable="false"`, SVG elements are added to the tab order by default in those browsers, with no way of removing them (`tabindex` is ignored).

It's a pretty annoying accessibility issue for keyboard users in those browsers.

**Comment by jimfb** [comment]
cc @tomocchino whitelists... :P

**Comment by HugoGiraudel** [comment]
Hey there. It seems that `focusable` needs to be passed `false` as a string and not a boolean so React (16) renders it in the DOM. Is that expected behaviour?

```diff
<svg
-      focusable={false}
+      focusable="false"
```

I find it rather surprising considering other boolean attributes such as `aria-hidden` appear to behave differently (passing `false` as a boolean properly renders it in the DOM).

Maybe I missed something?

**Comment by nhunzaker** [comment]
Yes. I can't remember if we achieved consensus on the best way to handle boolean attributes but, from what I remember, it follows:

- Attributes that require string html attribute values (like `focusable="true"`) should be passed as strings
- Attributes that should either be present or absent (like `disabled` or `novalidate`) accept `true` and `false`. React adds/removes the attribute based on the boolean

I believe we have some inconsistency to retain backwards compatibility, though I'm not sure if a specific example off-hand.

---

- [Attributes React treats as boolean](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/DOMProperty.js#L269-L295)
-

**Comment by nhunzaker** [comment]
Looks like we have a "boolean-ish" section for some SVG:
https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/DOMProperty.js#L255-L267

Does it make sense to add focusable here?

**Comment by HugoGiraudel** [comment]
> AFAIK it's expected because `focusable` is a string attribute with `"true"`, `"false"` and `"auto"` values per spec, and not a boolean attribute. Yes, the spec is confusing.

That makes sense. I’m not sure accepting both a string or a boolean would be dramatically better. It would certainly make things less confusing from an authoring stand point, but introduces a bit of a code smell (expecting multiple types).

> - Attributes that should either be present or absent (like `disabled` or `novalidate`) accept `true` and `false`. React adds/removes the attribute based on the boolean
> - Attributes that require string html attribute values (like `focusable="true"`) should be passed as strings

This is what confused me: `aria-hidden` doesn’t work this way for instance. As per the specifications, it should be passed as `true` or `false` (string), not just present (like `disabled`). But React is completely fine with it being passed without a value, or with a boolean.

It seems to me that we have the opportunity of making things a bit more consistent? Maybe by making `focusable` behave more like `aria-hidden` and the like (especially since they are usually used together) by accepting a boolean value as well as `"auto"`? But then we’re back to my first comment: 2 different types.

**Comment by gaearon** [comment]
I think we're open to changes to this in case you want to write up a proposal.

**Comment by HugoGiraudel** [comment]
Yes, my colleagues and I can surely come up with something. Is there a specific format you’re expecting for this or shall it just be what we think would be a good improvement on the current implementation?

**Comment by gaearon** [comment]
Just file an issue with a free form description of how it should work and why

**Comment by aweary** [comment]
It's kind of a messy situation, since we're dealing with three separate specifications (HTML, SVG, ARIA) and they don't always use consistent terms when describing attribute behavior.

Ideally, every specification would define the attributes as either [boolean attributes](https://html.spec.whatwg.org/#boolean-attributes) or [enumerated attributes](https://html.spec.whatwg.org/#keywords-and-enumerated-attributes) and we could just conform to those specs and only allow `true`/`false` for boolean attributes.

This would be the easiest approach from an implementation standpoint, but I do think there's value in making it work how the user expects it to. If an attribute is an enumerated attribute with `"true"` and `"false"` as keywords (a really unfortunate design) then taking the pit-of-success approach and making it just work feels like a better user experience.

I don't think having the attributes be polymorphic is _that_ bad of a code smell. It's just results in some simple coercion that React does anyways.

**Comment by HugoGiraudel** [comment]
## Situation

The [`focusable` attribute](https://www.w3.org/TR/SVGTiny12/interact.html#focusable-attr) from the SVG specifications is an [enumerated attribute](https://html.spec.whatwg.org/#keywords-and-enumerated-attributes) accepting values `"true"`, `"false"` and `"auto"`. Because it is technically not a boolean attribute (although it certainly somehow looks like it), React expects the value to be passed as a string. See the following example:

```diff
-<svg focusable>I should be focusable</svg>
-<svg focusable={true}>I should be focusable</svg>
+<svg focusable='true'>I should be focusable</svg>
```

The thing is, the `focusable` attribute is often used in conjunction with elements from the ARIA specification, in which attributes are booleans and not enumerated attributes with `"true"` and `"false"` values. The [`aria-hidden` attribute](https://www.w3.org/TR/wai-aria-1.1/#aria-hidden) is a good example of that.

For instance, [following a good practice for icon-buttons](https://fvsch.com/code/svg-icons/#section-html):

```html
<button type="button">
  <svg aria-hidden="true" focusable="false">
    <use xlink:href="#icon-play"></use>
  </svg>
  <span class="access-label">Start playback</span>
</button>
```

From an authoring perspective, the above snippet would likely be written like this in JSX:

```jsx
<button type='button'>
  <Icon icon='play' aria-hidden={true} focusable={false} />
  <span class='access-label'>Start playback</span>
</button>
```

The problem is that `focusable` **cannot** be authored as a boolean, otherwise it will **not** be printed out in the DOM. On the other hand, `aria-hidden` is perfectly fine being written as a boolean at it gets coerced by React.

## Proposal

Given the default value for the `focusable` attribute is `"auto"`, this is very likely this attribute gets authored to change its value to `true` or `false`. In that regard, it is confusing that it has to be specified as a string, when other attributes accepting booleans can be authored as such.

The suggestion would be to make it possible for `focusable` to be specified as either a boolean or a string, like other similar attributes. In other words, all the following should work:

```jsx
<svg focusable>I should be focusable</svg>
<svg focusable={true}>I should be focusable</svg>
<svg focusable='true'>I should be focusable</svg>
<svg focusable={false}>I should not be focusable</svg>
<svg focusable='false'>I should not be focusable</svg>
<svg focusable='auto'>I should be focusable</svg>
```

From an authoring perspective, I believe this would be the most straightforward and less confusing.
