### ISSUE TITLE
Click event not work correctly

### ISSUE THREAD

**Issue by divined** [facebook/react#6237]
`render: function()
    {
        return (
            <li data-placeid={this.props.suggestion.placeId} data-value={this.props.suggestion.name} onClick={this._onClick}>
                {this.props.suggestion.name} / 
            </li>
        );
    }`
![screenshot-cb dev 2016-03-10 13-45-08](https://cloud.githubusercontent.com/assets/8932160/13668679/fa8b36b8-e6c6-11e5-986d-de83c606d185.png)

**Comment by zpao** [comment]
Can you make a contained repro case with jsfiddle (https://jsfiddle.net/reactjs/69z2wepo/)

**Comment by divined** [comment]
https://jsfiddle.net/69z2wepo/34455/ Done
<li onClick={this._onClick}> {this.props.suggestion.name} / </li> - not work
<li onClick={this._onClick}> {this.props.suggestion.name} </li> - work

**Comment by divined** [comment]
I work with react second day only. If it is my mistake then sorry (

**Comment by eugene1g** [comment]
@divined This is not a bug in React, but rather a nuance in how DOM events travel up the document tree.

In the DOM event system, `e.target` is always the node that *triggers* the event, but that is not necessarily the node that *captures* the event. For example, in plain JS you can setup a `click` handler on `document`, then when click e.g. button on the page then `e.target` will be that button, even though the handler is attached to the document overall. To access the current element which _captured_ the event, you can use `e.currentTarget`.

In the circumstances that you described, what _triggers_ the event is the `<span>` node holding the text label of the option. As that `span` is a child of the `li` node, the onClick event fires on the `li` node as well, and `e.target` is set to the `span` node (which does not have `data-placeid` set). This is also why it works when you click on the whitespace - in that case you are triggering the event on the actual `li` element, which does have your `data-` attributes and thus the app works as expected.

The quick fix is to update the `_onClick` handler in  `AutoCompleteSuggestion` by replacing  `var selected = e.target;` with `var selected = e.currentTarget;`

The long fix is to pass all necessary data to the handler, instead of using the handler to pull those details from DOM with jQuery. For example -
```
var AutoCompleteSuggestion = React.createClass({
    _updateSelection()
    {
        var placeId = this.props.suggestion.placeId;
        var value = this.props.suggestion.name;

        if (value && this.props.selectedLocation)    SetSearchFormState(null, null, null, value, false);
        if (placeId && !this.props.selectedLocation) this._getPlaceDetails(placeId);
    },
    _getPlaceDetails(place_id)
    {
        placeService.getDetails({placeId: place_id}, (place, status) => {
            if (status == google.maps.places.PlacesServiceStatus.OK)
                SetSearchFormState(true, place.geometry.location, place.formatted_address, '', false, []);
        });
    },
    render()
    {
        return (
            <li onClick={this._updateSelection}>
                {this.props.suggestion.name} / {this.props.suggestion.address}
            </li>
        );
    }
});
```

As an aside, using singletons like `SetSearchFormState` like that might create a dataflow that is difficult to trace or predict. The "suggested" React way would be to flip the responsibilities and pass a property e.g. `onSelect` to `AutoCompleteSuggestion` which is a function that does the business changes required to update state in the parent component.

**Comment by divined** [comment]
Thx
