### ISSUE TITLE
Fix coverage testing and enable it again

### ISSUE THREAD

**Issue by gaearon** [facebook/react#6290]
It was introduced in #5713 but I disabled it in d138b286db4fcb7137f9267a30ec64b657d3cfb4 because we consistently got test failures on master. They appear to be caused by processes running out of memory due to coverage instrumentation overhead.

We should figure out a way to add the coverage reporting back. I’ve heard from @cpojer there are potential optimizations to be made in Jest to help mitigate this overhead. We can look into helping Jest deal with this.

If there is a way to increase memory cap for React tests on Travis maybe we could do that too.

One thing I wasn’t sure about is removing `set -e` in d138b286db4fcb7137f9267a30ec64b657d3cfb4. It was only present in `if` branch that used to handle the master so I removed it to be consistent with the `else` branch that handles the PRs. However I’m not sure why it was there in the first place, and maybe we should add it back. I’d love to learn more about this.

Let’s keep this issue open until we have a specific plan to integrate coverage again without being red all the time.

**Comment by cpojer** [comment]
ping!

code coverage was completely rewritten in Jest 15.

You can remove almost all of the complexity in https://github.com/facebook/react/blob/master/grunt/tasks/jest.js – it shouldn't be necessary any more. Just `jest --coverage`. I recommend using `collectCoverageFrom` (see https://github.com/facebook/jest/blob/master/package.json#L47 for any example) to collect coverage from all files, even untested ones. This one might make you look bad though because coverage will undoubtedly go down but it will give you some signal on where you are at :)

cc @vjeux or @zpao (do you wanna do this?) and cc @jdalton who added coverage initially.

**Comment by keyanzhang** [comment]
Related: #6712

**Comment by vjeux** [comment]
It's back!
