### ISSUE TITLE
Accessing params of non-primitive proptypes (shape, oneOf, etc)

### ISSUE THREAD

**Issue by khankuan** [facebook/react#6319]
Hi, I have a use case to read in the proptypes of a component in enhance development process. Is there a way to access arguments for types like `React.PropTypes.shape`?

**Comment by milesj** [comment]
Are you talking about the nested prop types within a `shape`? Then no, there's no way to access those, at least from what I've found looking through the source code.

**Comment by khankuan** [comment]
Ic, perhaps i'll try using this: `https://github.com/reactjs/react-docgen`. Thanks!

**Comment by jimfb** [comment]
Ok, glad you found a solution that works for you!  Let's keep usage questions on StackOverflow.

**Comment by phistuck** [comment]
@jimfb - can you clarify the last sentence? Since the official documentation/tutorial still mentions prop types in one of the first primary pages, that is very surprising.
One use case of PropTypes is to generate test pages for components, that show form fields for all of the props specified in `propTypes`.
Do you have other suggestions for this use case (other than JSDoc, since that involves parsing the script files themselves and nothing that a test can dynamically check reasonably)?
