### ISSUE TITLE
Log warning to console when components written as functions are implemented incorrectly.

### ISSUE THREAD

**Issue by zpenka** [facebook/react#6329]
Example:

```
const MyComponent = (text) => {
  <p>{text}</p>
}
```

That component will not throw any errors, nor will it ever actually render. It's a silly error to make, but I think a warning in cases like these is called for. "WARNING: Incorrect Usage in MyComponent, see return statement of MyComponent"

FWIW: the correct code:
```
const MyComponent = (text) => (
  <p>{text}</p>
)
```

See how easy that is to miss?

Not sure how difficult something like this is to figure out. Going to continue looking myself, but if someone has some idea how to go about creating a warning for this scenario, please feel free to point me in the right direction :smile:

**Comment by jimfb** [comment]
We do output a warning:

 > Warning: MyComponent(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

We detect that the function didn't return a valid return type, and print the warning.  There really isn't much more you could detect in this case.

If you didn't get the warning, please verify that you are using the dev build of React (instead of the production build).  If there are further issues, please provide a simple jsfiddle that demonstrates the issue.

**Comment by zpenka** [comment]
Ah, my bad.. didn't realize this was already in the dev builds. Any idea when that will get to production?

**Comment by jimfb** [comment]
The RC2 is already published.  We will likely do another RC and then a final release.
