### ISSUE TITLE
CSS: values with "!important" in 0.15

### ISSUE THREAD

**Issue by kib357** [facebook/react#6342]
It seems that style values with "!Important" doesnt work in 0.15. Fiddle:
https://jsfiddle.net/beyt1ekz/

**Comment by zpao** [comment]
Yes, this is part of the change to generate elements instead of a markup string. It turns out that `!important` would appear to work before but it only worked for first render, never subsequent renders which would set `node.style.display` directly (where `!important` is ignored). As a result of the inconsitent behavior, this was never a supported feature. Currently you'll need to use CSS (or some inline style library that uses CSS) if you want to use `!important`

**Comment by kib357** [comment]
I know about generating elements, but we also can set !important styles with one line of JS, for example:
`document.body.style.setProperty ("display", "none", "important");`
Is it a problem for performance?

**Comment by rmosolgo** [comment]
Just discovered this as part of a 14.8 => 15 upgrade, I thought I'd leave a note for future googleability. 

Previously, we had a style property `borderBottom` with `!important` like this: 

```js 
{
  // ... 
  borderBottom: "1px solid #e5e5e5 !important"
}
```

`border-bottom` was applied to the element as expected:

![image](https://cloud.githubusercontent.com/assets/2231765/16386773/eaf94c5a-3c5f-11e6-9874-1b795ffed869.png)

(Although perhaps it was subject to bugs as described above, we never saw any.)

After upgrading to 15, the style was not applied at all, `border-bottom` was missing altogether: 

![image](https://cloud.githubusercontent.com/assets/2231765/16386800/08d1b334-3c60-11e6-9793-99c77d6a0520.png)

On a hunch, I removed the `!important`. Now it's applied this way, with `border-bottom-width`, `border-bottom-style`, and `border-bottom-color` applied as separate properties: 

![image](https://cloud.githubusercontent.com/assets/2231765/16386820/1ea84de4-3c60-11e6-9a7f-c2b4f4b0804a.png)

Not a big deal, I'm sure it's an improvement, it just caught me by surprise!

**Comment by gaearon** [comment]
@rmosolgo 

>it just caught me by surprise!

Please see [15.0 release notes](https://facebook.github.io/react/blog/2016/04/07/react-v15.html). The first change there is:

>We are now using `document.createElement` instead of setting `innerHTML` when mounting components.

The fact that `borderBottom: "1px solid #e5e5e5 !important"` was a coincidence. It was never supported, and you wouldn’t find this pattern in the documentation. It worked because we generated HTML on the initial render, so `!important` became part of that HTML.

Any subsequent updates to the property would have failed in 0.14.x because subsequent updates are implemented in React by using `node.style` DOM API instead of setting HTML. So this was broken all along—it just happened to work for the initial render.

As mentioned in the release notes, 15.0 switches to using DOM API for the initial render as well. This is why `!important` inside the value no longer works at all.

**Comment by rmosolgo** [comment]
Cool, thanks for clarifying, that makes sense! It was overkill in this case anyways, thank goodness :)
