### ISSUE TITLE
server is running and I include the export line its not throwing an error

### ISSUE THREAD

**Issue by js08** [facebook/react#6382]
- I am facing a weird error
- when the server is running and I include the export line its not throwing an error and able to see the application...even it shows webpack is valid
 export { SportsTopPortion  };
- but after including this line and start the server again I am facing the error
Error: Invariant Violation:
- i am using webpack,node and react
- since I am using webpack for build I am thinking the error will be due to webpack
- checked React code for errors there is no problem in syntax.
- can you tell me how to fix it..
- the reason I am using export is to write unit test case
- whole code and test code can be seen in gist below
- I am debugging for past four days not able to find out

**Comment by zpao** [comment]
This sounds very much tied to your specific application and is unlikely to be a bug with React, which is what we try to keep GH for. Have you tried posting to stack overflow with more specific information or a link to your project where people can look and see what's going on. As is, you've posted lots of unspecific information for a very specific issue and didn't actually say what invariant is being violated. My best guess is that you need to enable another transform so that the export line is transformed to common js.

I'm going to close out since this isn't a bug with React.

**Comment by js08** [comment]
Hey can you tell me how to transfer to common js

**Comment by zpao** [comment]
Babel.

**Comment by zpao** [comment]
Babel.

**Comment by js08** [comment]
Yeah I am using Babel but still that problem

**Comment by zpao** [comment]
use the es2015 preset.

This is the last response I'll put here. Please use another medium for support.
