### ISSUE TITLE
TestUtils.renderIntoDocument() and lifecycle

### ISSUE THREAD

**Issue by JacquesBonet** [facebook/react#6384]
Hi everybody,

There something I don't understand in the TestUtils library.

I want to test a react component with TestUtils.
The lifecycle of my component is 

getInitialState
componentWillMount
render
componentDidMount
componentWillReceiveProps
shouldComponentUpdate
componentWillUpdate
render
componentDidUpdate
componentWillUnmount

If I use TestUtils.renderIntoDocument, these methods will never be call:

componentWillReceiveProps
shouldComponentUpdate
componentWillUpdate
componentDidUpdate

because a new container is recreated to each call to renderIntoDocument.

renderIntoDocument: function( aReactElement) {
   var div = document.createElement('div');
   return ReactDOM.render( aReactElements, div);
}

See my fiddle: https://jsfiddle.net/JacquesBonet/k0tyztzc/

So I don't understand why you suggest to use renderIntoDocument method to test reacts component?

I think its better to use method likes: 

// create the container
let container = document.createElement('div');
// call render method
let component = ReactDOM.render( reactElement, container);

to test react components.

See fiddle: https://jsfiddle.net/JacquesBonet/k0tyztzc/

Your opinion?

Best regards.

**Comment by jimfb** [comment]
This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).

With regards to the specifics of your question: If you want to test updates, then you can just manually create a div/container and render into it twice, as you mentioned. You don't need to use renderIntoDocument if you don't find it useful for your particular test.

**Comment by JacquesBonet** [comment]
Thks for your reply jimfb,

I think it would be better to have a render method with an optional parameter representing the component's container..
If the value of this parameter is null, a container is created.
If the value is not null, the container is reused.

Less change to do to switch code beetween "recreate a container each time", or "reuse the same container next times".
