### ISSUE TITLE
New PropType: PropTypes.style - would it make sense?

### ISSUE THREAD

**Issue by radubrehar** [facebook/react#6385]
Would implementing a PropTypes.style make sense? I think it should be useful for many scenarios.

Example: One implements a `TabPanel` component, accepting a property `tabStyle`, which should be a valid `style` object.

**Comment by brigand** [comment]
If it doesn't end up in react core, you can use [react-style-proptype][1].

[1]: https://github.com/brigand/react-style-proptype

**Comment by radubrehar** [comment]
Thanks for the quick response. I've looked into it, but there are quite a few style props missing:
 * `flex`
 * `flexGrow`
 * `flexShrink` 
 * etc
I've just instantly noticed the flex related ones, but I suppose the list is larger.

**Comment by gaearon** [comment]
Thank you for the suggestion! We try not to expand the API surface area for PropTypes because they are effectively in maintenance mode and the longer term plan is to use something like Flow instead. Indeed, as @brigand’s project shows, this can be solved in the ecosystem. When and if React gets first-class support for inline styles as the blessed solution to style React apps, we might reconsider this, but for now please use https://github.com/brigand/react-style-proptype and feel free to file issues for supporting more style props there. Cheers!

**Comment by brigand** [comment]
@radubrehar I'll try to find a better list, thanks for pointing that out. Continuing in https://github.com/brigand/react-style-proptype/issues/1

**Comment by radubrehar** [comment]
Thanks Dan @gaearon & @brigand. This seems like a common-sense solution, so I'll go for it. I opened the issue since I wondered if it might be a good idea to get this into React itself, and wanted to hear other opinions as well. Thanks for feedback.
My belief as well is that the small API surface area is what makes React easy to jump in.
