### ISSUE TITLE
Support question - Serverside rendering only, why re-render on client?

### ISSUE THREAD

**Issue by ORESoftware** [facebook/react#6386]
Alright, kind of a React newb but React is not following the principle of least surprises with this one so I have to ask.

Our team only really wants serverside rendering for a particular project. We don't need to do much special on the client.

However, as far as I have learned, you need to have a reference to the same React components on the client as you do on the server in order to actually get dynamic behavior (events are bound etc) on the client.

My question is, if we have a `<div id='react-root'> </div>`

why isn't React setup so that on the front-end we could just call:

```js
ReactDOM.render(document.getElementById('react-root');
```

(without the React component first argument.)

Doesn't / couldn't React have enough info to go off of already, so as to not need an actual reference to the React component on the front-end as well? As long as React on the front-end has a reference to the root DOM node, couldn't / shouldn't that be enough?

The whole thing where you have to re-render on the client is kinda unexpected. I am sure I am missing something, or there must be some good reason why the lib works this way, I just don't know and want to know which is why I am writing this. Thanks.

**Comment by goto-bus-stop** [comment]
> you need to have a reference to the same React components on the client as you do on the server in order to actually get dynamic behavior (events are bound etc) on the client.

The information about which event handlers to add etc. is part of the React component, not of the server-side generated HTML. So for it to know which events to bind, you still need to hand the component to React as well.

**Comment by gaearon** [comment]
Hi @ORESoftware!

We generally prefer that issue tracker is used exclusively for feature requests and bug reports because questions get lost here. [StackOverflow](http://stackoverflow.com) is a better place for specific questions.

>Doesn't / couldn't React have enough info to go off of already, so as to not need an actual reference to the React component on the front-end as well?

No, it doesn’t. The DOM node is just the DOM: it does not contain any JavaScript code related to the component, such as event handlers or its `render()` method. The markup may arrive before the JS is even loaded, which is what makes server rendering useful.

However this means that React can only take over updating that markup after you give it *the code* for your component, which corresponds to the `<MyComponent />` argument in `ReactDOM.render()` call.

If it was possible to just call `ReactDOM.render(document.getElementById('react-root'))` and have React take over the updates on the client, then it would mean loading React alone is enough and this code can run before the JavaScript code for your app is loaded. However this contradicts the fact that React can’t guess how to make your component markup dynamic without having access to your component’s code. This is why it’s necessary to associate the two.

Note that you don’t really “re-render” on the client. If the markup is identical, React will just attach a component instance to the existing DOM. However it can’t do that without access to component’s code on the client side, which is why you have to associate it with markup using that `ReactDOM.render()` call. And if the markup won’t match, it will forcibly re-render your app to use the markup generated by the client side which seems preferable to just silently failing.

I hope this helps! Please try to use StackOverflow next time because questions are much easier to search there. Thanks!

**Comment by ORESoftware** [comment]
Definitely helps, thanks for the info, I asked here because I don't think
it's easy to find the "why" questions online. SO is unfortunately not for
why questions unless you like downvotes LOL?

**Comment by ORESoftware** [comment]
Also, the other thing is that it was sort of hard to find info on the actual need to "re-render" on the client. It took several hours of web searching and unpleasant tinkering before figuring it out. I am not sure there is an easy way of making it obvious that a "re-render" is needed, and maybe I am thicker-headed than the next, but if I am not the only one with this feedback maybe there is a place for a higher level discussion of how React works. The docs are full of details, but I think higher level documentation would help (?)

**Comment by gaearon** [comment]
>SO is unfortunately not for "why" questions unless you like downvotes LOL

I don’t think it’s [necessarily the case](http://stackoverflow.com/search?q=why). StackOverflow community cares that the questions are specific, can be answered objectively, and are carefully formatted, explained, and titled. Your question can satisfy all of these constraints.

As for the docs, they definitely could be better, and contributions are welcome :smile: . If you have specific suggestions for improvement maybe you could give it a try to send pull request? You know better than me which docs you looked at, so you have more context on where that warning would make more sense.

Thanks!

**Comment by ORESoftware** [comment]
Thanks Dan, yeah, I have some ideas for a tutorial but will wait until I have a bit more experience - my last question for you - the REAL reason it is so counter-intuitive to have to re-render on the client is that this seems to suggest that you need the same data on the client as you do on the server and that data need to sent along with the HTML?

For example if I want to render a variable number of child components, do I just cross my fingers that the data on the front-end matches the backend?

 That is so confusing, but is that correct? Where can I see an example of this?

**Comment by ORESoftware** [comment]
If you answer here I may copy question and answer to SO, which may help people.

**Comment by gaearon** [comment]
>For example if I want to render a variable number of child components, do I just cross my fingers that the data on the front-end sent to the parent component matches the data sent to the component when it was rendered on the backend?

Yeah, this is correct. You need to send the data down. So that results in some duplication but on the other hand you have something visible immediately before JS is loaded and picks it up. It’s a tradeoff.

If you use something like Redux to manage your state, you might enjoy reading http://redux.js.org/docs/recipes/ServerRendering.html as I think it answers some of your questions about data hydration.

**Comment by ORESoftware** [comment]
Thanks Dan I was gonna ask another question but your article above answers it, thanks!!
