### ISSUE TITLE
transitionGroup

### ISSUE THREAD

**Issue by rubyisapm** [facebook/react#6412]
```
var ReactTransitionGroup = React.addons.TransitionGroup;

var Content = React.createClass({
    componentWillAppear: function () {
        console.log('componentWillAppear');
    },
    componentDidAppear: function () {
        console.log('componentDidAppear');
    },
    componentWillEnter: function () {
        console.log('MyBox.componentWillEnter');
    },
    componentDidEnter: function () {
        console.log('MyBox.componentDidEnter');
    },
    componentWillLeave: function () {
        console.log('MyBox.componentWillLeave');
    },
    componentDidLeave: function () {
        console.log('MyBox.componentDidLeave');
    },
    render: function () {
        return <div>content</div>;
    }
})
var TodoList = React.createClass({
    getInitialState: function () {
        return {show: false};
    },
    show: function () {
        this.setState({
            show: true
        })
    },
    hide: function () {
        this.setState({
            show: false
        })
    },
    render: function () {
        var items = this.state.show ? <Content key='content'/> : '';
        return (
            <div>
                <button onClick={this.show}>show</button>
                <button onClick={this.hide}>hide</button>
                <ReactTransitionGroup>
                    {items}
                </ReactTransitionGroup>

            </div>
        );
    }
});
```

Could you tell me where the problem is?

**Comment by jimfb** [comment]
This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).

**Comment by gaearon** [comment]
I’m not sure we support putting text (which empty string is) inside a transition group: https://github.com/facebook/react/issues/6365.
Try `null` instead.

**Comment by JoshuaCWebDeveloper** [comment]
The documentation at https://facebook.github.io/react/docs/animation.html#animating-one-or-zero-items doesn't specifically say that it can't be a string, or must be an object (or null). If this is expected behavior, then I'd say this is a "bug" in the docs. 

However, I also created PR #8464 that fixes this issue.
