### ISSUE TITLE
'Warning: ' messages should use console.warn()

### ISSUE THREAD

**Issue by danbernardi** [facebook/react#6414]
Currently they use console.error(), which overestimates their severity and causes devs to react more strongly than the message might imply.

Example:

```
warning.js:45 
Warning: Failed propType: Invalid prop `things` of type `array` supplied to `Item`, expected `object`. Check the render method of `Connect(Item)`.
```

**Comment by zpao** [comment]
Thanks for the feedback but this is intentional. `console.error` provides good stack traces and our treatment of warnings is that they *should* be fixed before they are committed and shipped. With maybe 1 exception, I think they should all be fixable.

One of the things we're working towards is a better way to manage these so that you can silence specific warnings or types of warnings without having to fork React. You can track that in the umbrella issue - https://github.com/facebook/react/issues/5306
