### ISSUE TITLE
Curly brackets (as the first line in return) causes "unexpected token" error

### ISSUE THREAD

**Issue by ducwings** [facebook/react#6437]
Curly brackets (as the first line in return) causes "unexpected token" error

For example:
```
render () {
  return (
      {/* Comment for my component - This line causes "unexpected token" error */}
      <nav>
      </nav>
```

**Comment by zpao** [comment]
Yes, from the JSX spec, that's not a valid syntax. Since JSX isn't a part of JS the `<` ends up putting the parsers into a different mode, which would allow the `{ /* comment */}`. But anything before that is left alone.

If you want a comment there you would need to do it as plain JS or move it inside the `<nav>`.

Sorry that's not obvious. That's one of the downsides of introducing new syntaxes :)

**Comment by keyanzhang** [comment]
Possible duplicate: #5573
