### ISSUE TITLE
render should check input type

### ISSUE THREAD

**Issue by garfieldnate** [facebook/react#6447]
I just updated some code that was using React 0.11, and one of the errors I made was passing in class constructors:

    React.renderComponent(className(), document.body)

The error this gave was `TypeError: this is undefined at react.js:5045`, which gave me no clue as to what was wrong. The problem, of course, is that `React.createElement(className)` needed to be passed in instead. I think this might be an easy error to catch and warn about to help out noobs like me :).

**Comment by jimfb** [comment]
Are you upgrading incrementally?  (ie. from version 0.11 to 0.12 to 0.13 to 0.14 to 15, rather than just jumping to v15)?  The upgrade experience is designed to be done incrementally.

But for versions that old, yes, the upgrade experience might be a little rough.  I think we do better nowadays with the more recent versions.  The new `React.renderComponent` is `ReactDOM.render`, and if you passed a string to that function, the error message would say:

 > Uncaught Invariant Violation: ReactDOM.render(): Invalid component element. Instead of passing a string like 'div', pass React.createElement('div') or `<div />`.

Anyway, there is nothing actionable here, since it is fixed in latest and we are not going to backport that far back.

Sorry the upgrade experience from 0.11 to 15 might be a little tough, but I promise it gets better (especially if you keep your application up-to-date rather than doing huge jumps long after).
