### ISSUE TITLE
multiple children with same key: warning message prepends '.$' to actual key value

### ISSUE THREAD

**Issue by go-oleg** [facebook/react#6475]
If multiple children have the same key, for example ([jsfiddle](https://jsfiddle.net/olegs/p09cweky/1/)):

```javascript
var Hello = React.createClass({
    render: function() {
        return (<ul>
        <li key={"1"}>what</li>
        <li key={"1"}>what</li>
        </ul>
        )
    }
});
```

React prints the following warning to the console:

```
Warning: flattenChildren(...): Encountered two children with the same key, `.$1`. Child keys must be unique; when two children share a key, only the first child will be used.
```

The key referenced in the warning prepends an internal-looking '.$' to the key specified by the user. This is a bit misleading - ideally, it would mention the exact key value set by the user.

**Comment by jimfb** [comment]
User-specified keys undergo an escaping transformation to prevent collisions with automatically-generated keys.  For instance, if your `li` element had the key `1=::=2`, the key in the warning would be `.$1=0=2=2=02`.  This happens during traversal, so `flattenChildren` gets the already-escaped keys and doesn't have access to the original keys.

But yes, auto-generated keys are completely internal (never user visible) and are guaranteed to never conflict (because they are generated, and user keys are escaped), so I don't see a reason why we couldn't report the original key name in warning messages.

Probably the best solution would be to un-escape the key before reporting the error message.

**Comment by hkal** [comment]
If no one minds, I'd like to give this a go.
