### ISSUE TITLE
"Warning: Constructor is changing a uncontrolled input of type search to be controlled" since 15.0.1

### ISSUE THREAD

**Issue by cauburtin** [facebook/react#6494]
I noticed now react 15 complains for something like: https://jsfiddle.net/crl/8c6vngdy/3/ or https://jsfiddle.net/crl/8c6vngdy/1/ (just changing the initial state)

it stops complaining as soon as you put a [string](https://jsfiddle.net/crl/8c6vngdy/2/) instead of undefined, is it intended? because I don't see a big problem and difference with a value being undefined

**Comment by gaearon** [comment]
Yes, this is intentional. `value={undefined}` makes the input uncontrolled. This means, for example, that resetting state to be `undefined` won’t clear it later, and this catches people by surprise. If you want the component to be controlled (and empty), please pass an empty string instead.

More about controlled and uncontrolled inputs: https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by cauburtin** [comment]
Thanks gaeron, good to know,

**Comment by Taakn** [comment]
@gaearon I have the same issue. Wouldn't it make more sense to have a prop that says for instance `controlled={true}` and have the user explicitly set it (or have it by default `true`), instead of trying to infer it implicitly by a combination of some other props (value or onChange or ?)?

I am asking because this is causing some problems in my code. I needed the input to be controlled and have a value of `undefined`.

Thanks so much

**Comment by gaearon** [comment]
>I needed the input to be controlled and have a value of undefined.

What do you mean by “have a value of undefined”? If this is input, using the value of `''` should work great for you.

**Comment by Taakn** [comment]
Hi @gaearon thanks I ended up fixing my issues. I am using React + Meteor + Aldeed Collection2 + Material UI

Without entering too much into the details, Material UI uses components such as textfields, dropdowns, datetime pickers, etc. that sometimes are controlled, sometimes are not and if we're not careful enough we get the following error:

> Warning: TextField is changing a uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

Sorry this issue probably wasn't exactly the best one to piggyback on. Given the various scenarios I am still thinking it might be better to explicitly set whether the component is controlled or not, instead of inferring it from the props.

Thanks again

**Comment by Taakn** [comment]
@gaearon I deleted my previous comment. I think this design choice (of having a component with an `undefined` value to be uncontrolled) is actually causing some issues for a bunch of people (see here https://github.com/facebook/react/issues/6494)

The problem is that using `''` does not work because the input datatype could be a number, a date, or some object. When I'm saving data in my DB, having an empty string for a number/date/etc. datatype does not make sense, but `undefined` does.

**Comment by artyomtrityak** [comment]
It looks ok if `undefined` means uncontrolled input. Any reason doing same for `null` value?
