### ISSUE TITLE
ReactCSSTransitionGroup Animation start issue with low framerates

### ISSUE THREAD

**Issue by xadh00m** [facebook/react#6495]
#### Issue

We run into an animation issue where the _active_ class is added to fast after the child has been added to the ReactCSSTransitionGroup. This happens if the framerate drops below 60 FPS on Chrome Version 49.0.2623.112 (64-bit). 
#### Reason

The reason is the following timeout in ReactCSSTransitionGroupChild.js (line 110):

```
this.timeout = setTimeout(this.flushClassNameQueue, TICK);  // TICK === 17 milliseconds
```

If the framerate is low the animated object appears directly in the animation _active_ state because the browser did not have enough time to process the previously added _enter_ class.
#### Fix

We fixed this internally by queing the function above with two chained `requestAnimationFrame()` calls instead of the `timeout()`.

Has anybody else encountered this issue? Anybody interested in a pull request?

Regards,
Mirko

**Comment by ev1stensberg** [comment]
This could actually be a utility library, if you could make it so. It's great for single-projects with tweaking, but not in overall experiences, which tend not to use low frames by default.

On the functionality part: Consider caching the actual object to avoid this? Also, I think everything that needs a full refresh should not be left by React to handle. You should manage this on your own, which is why this could be a good library.

That's my opinion! Good issue by the way!

**Comment by jimfb** [comment]
@xadh00m Honestly, this code doesn't have a real owner, so it's hard to know who to cc on this issue.  I think @gaearon took a look at a few PRs recently, so he might have some feedback.

If you can demonstrate a bug and have a PR to fix, I think we'd likely take it.

**Comment by gaearon** [comment]
I’m going to close since we don’t plan any more changes to TransitionGroup in React repo. Instead, it now [is maintained by the community](https://github.com/reactjs/react-transition-group), and you can file an issue in the new repository if this is still affecting you. Thanks!
