### ISSUE TITLE
Expose name, and options of propTypes

### ISSUE THREAD

**Issue by jcreamer898** [facebook/react#6507]
I'm looking for a way to iterate over a component's defined propTypes, and determine the type, and the options.

For example...

```js
MyComponent.propTypes = {
  href: React.PropTypes.string,
  rounded: React.PropTypes.bool,
  color: React.PropTypes.oneOf([
    "blue",
    "white",
  ]),
};
```

I'd like to be able to iterate over them and be able to determine the actual type of validator, and the different things that can be passed in as options.

```js
Object.keys(MyComponent.propTypes).map((fn, prop) => {
  MyComponent.propTypes[prop].type; // string, bool, oneOf
  MyComponent.propTypes[prop].options // null, null, ["blue", "white"]
});
```

I'm working on a styleguide, and was hoping to list out all possible options to pass into a component's props.

Please let me know if there's a way to do this already.

Thanks!

**Comment by gaearon** [comment]
This is pretty much the same as https://github.com/facebook/react/issues/5067.

I think we won’t be supporting PropTypes-based introspection because we don’t plan to add new features to them, and eventually plan to phase them out in favor of tools like Flow (which may add runtime checking at some point).

I understand where you’re coming from (styleguides are cool) but I’m afraid we’re just not going to add more to PropTypes API. You can, however, implement custom PropTypes matchers that delegate to React.PropTypes for validation, but also expose the necessary metadata, and have your components use those PropTypes instead.

I hope this helps!

**Comment by jcreamer898** [comment]
Thanks @gaearon! I'll see what I can do. :)

**Comment by abhishiv** [comment]
I wanted to the same, and in the end just ended up using tcomb-react instead of `React.PropTypes`. In case it helps anyone else.
