### ISSUE TITLE
react15 fail to exist as a standalone js

### ISSUE THREAD

**Issue by lcxfs1991** [facebook/react#6512]
I am using react0.14.7 and webpack for my project. It works perfectly fine.

However, when I try to upgrade to react15, I pops up such an error: 
```
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component\'s render method, or you have multiple copies of React loaded.
```
This is a very classic issue (https://gist.github.com/jimfb/4faa6cbfb1ef476bd105).

Why it works in react0.14.7 but fails for react15?

Could any one answer?

**Comment by lcxfs1991** [comment]
I use
```
externals: {
    "react": "React"
}
```
in webpack

**Comment by jimfb** [comment]
This almost certainly means you are including a duplicate copy of React.  This is one of the dangers of using npm; it doesn't handle such dependencies very well and leads to cryptic errors like this.  You can try the things mentioned in the gist, there is some good discussion there.

I'm going to close this out because it's probably due to a duplicate dependency.  If you're able to come up with a simplified repro (eg. in a jsfiddle) that demonstrates a bug in React, we'll be happy to re-investigate.
