### ISSUE TITLE
Language translation with React

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/react#6513]
# Transpiling Language with React

partly relative to React.  This targets mainly Babel, but could be done with React as well. What do you think?

[Gist](https://goo.gl/1OB84V)

**Comment by zpao** [comment]
Overall this is a good question to ask elsewhere while we try to keep GitHub focuses on bugs and specific issues about React itself. Using discuss.reactjs.org or Stack Overflow are generally better places for this.

I'm going to close out since there's nothing directly actionable and it's not something we're going to build into React itself, there are several reasonable approaches to solving this problem and they all involve additional tooling.

Now that said, a bit of insight into what we do at FB - we have a special component that gets transformed with knowledge of the target language and translations. So we would do something like `<h2><fbt>HeyHo</fbt></h2>` (to use your example). The `<fbt>` ends up being a lookup and we have the option to either statically transform to a new string with babel or whatever to the right set of languages (and potentially build separate bundles for each language). Or it could be more complex and do the lookup at runtime and be a real composite component.

At a high level this is similar to what I'm understanding of what you wrote. I'm not a huge fan of your exact proposal with using quote types to differentiate. I think you'd have better luck with something like a unique JSX component (aka "an extra html tag") or something that's also unique. Since you are effectively just doing templating, taking some cues from handlebars and using `{{String}}` wouldn't be too bad either.

**Comment by ev1stensberg** [comment]
I agree, I don't know how you'd use` {{String}}` in JSX without going with the Meteor approach though! Think the method I showed, was bad composed, but it fit its purpose (as an example) I assume. Also,  do you have any examples using `<fbt> `in any projects? Would love to get an insight on that.

About the issue and bug tracker: I know Stack Overflow might be the best approach, but bug tracker in my eyes gives you more quality feedback, as SO answers usually address your issue and not use cases that might be better. (That being said, some do though!)

**Comment by zpao** [comment]
Not sure what the meteor approach means. I used that simply as more unique signal than a double quote, which has lots of uses in natural language which you might want to remain. Eg if you want to translate `<h3>"The following is a quote from Ben Franklin. "JavaScript is great.""</h3>` - the extra parse you do becomes more complex and error prone. But picking out something like `<h3>{% The following is a quote from Ben Franklin. "JavaScript is great." %}</h3>` becomes a bit easier.

We don't have anything using `fbt` publicly. It could be a pretty straightforward step though. A custom babel transform that looks for JSXElement and does something to replace the node. Here's a really basic example: http://astexplorer.net/#/89aJSotOE1

**Comment by ev1stensberg** [comment]
Meteor approach means helpers and templates. Thanks for the example, it was similar to what I was looking for. Do you think this is doable to create as an open source library? If FB doesn't open source(if not this is possible, explain why please!) it I'd be willing to put my brain in action trying to do something relative to fbt!

**Comment by zpao** [comment]
We probably won't open source it, it's very much tied to our infrastructure and way of doing things. I think you'd be better off trying to do something yourself or look more into other ideas built more around existing translation solutions or maybe some combination of approaches.

**Comment by ev1stensberg** [comment]
Cool. I will! Lastly: How would you think language translation would fit to loaders?

**Comment by zpao** [comment]
No idea.

**Comment by ev1stensberg** [comment]
Thanks for the session, Paul! Was great. Even learned some tricks while having this conversation. I love  the work you do. And that's for everyone at FB. Open Source means a lot not only for developers but to engage new ones too.

**Comment by gaearon** [comment]
I think using loaders (Webpack jargon for transforms) for this is not super great because they operate on strings. Paul’s suggestion to use Babel instead sounds easier and more reliable to me.

**Comment by ev1stensberg** [comment]
@gaearon my suggestion was it as a Babel loader (see the gist). Paul suggested doing it as JSX. Which one do you refer to? I agree with you and Paul, it's a messy way, but I'd love translations as a loader of some sort, would mean such a better developer experience.

**Comment by gaearon** [comment]
I’m confused as to what `babel-german` would mean in your example. Since it’s in Webpack configuration, it’s probably supposed to be a Webpack loader, but loaders operate on strings, not on AST.

When you see `babel` in Webpack config, it means the string contents of the file gets parsed by Babel, and its transforms (defined in `.babelrc` or Babel loader options) run on the AST, like [the one you can explore here](http://astexplorer.net/). These are easier to write because operating on AST is generally much safer than on strings, as you don’t have to “think like a parser”.

This is why we suggest writing it **as a Babel transform rather than a separate loader**. If it’s a Babel transform, you can [write a plugin](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md) that detects and transforms special JSX expressions or function calls. It doesn’t matter whether you use JSX or a special function call for this—the important part is doing this on AST level rather than by processing strings, which you’d have to do if you implemented this as a Webpack loader.

I hope this helps!

**Comment by ev1stensberg** [comment]
Certainly did. See, the loader is just the specification, so we could strip down things and get the concept before going crazy in details. Indeed we should use transforms. There's a lot of sketchy writing in the description, some of which you pointed out.

However I think there's a downside using AST. It's not a logic one, but worth of mention. Using loaders would mean a cleaner config file. There's a lot of first-timers that wants to do a cool feature, and copy paste. Would be a lot harder to grasp the content of transformations if we'd do this in the `.babelrc` . So there's the "issue" . **Dev X versus quality code**. That's my opinion though!

**Comment by ev1stensberg** [comment]
@amasad what do you think? This question was meant for you as well!

**Comment by amasad** [comment]
I don't have much to add other than I agree that `<fbt>`-like thing would be a good abstraction for this. Double quote is too generic IMO, but maybe if you write it and promote it as a separate babel plugin then that would provide some validation that this is something people would use.
