### ISSUE TITLE
Stop linking to react-python in docs

### ISSUE THREAD

**Issue by Spacerat** [facebook/react#6518]
Now that react-python is being completely deprecated and will probably cease to function soon with new versions of react ( https://github.com/facebook/react/pull/6444 ) the docs should probably no longer link to it from the _Use React and JSX in Python Applications_ page.

**Comment by jimfb** [comment]
For those following along, I assume @Spacerat is referring to https://facebook.github.io/react/blog/2013/08/19/use-react-and-jsx-in-python-applications.html

It's an old blog post (with a date), not part of the living docs.  We generally don't go back in time and update old posts because things are constantly changing over time and it's hard enough to just keep the main documentation up-to-date.

If someone wants to add a red note box that says "Update: PyReact is now deprecated", I think I would be ok with that and we would likely accept such a PR.  cc @zpao because he feels the strongest about updating historical posts.

Anyway, I'm going to close this out to take it off our radar, because we don't generally track/update historical posts.

**Comment by zpao** [comment]
Meh, If somebody did want to add a note like that, that would be fine. But I don't think we need to change the content of the post. And linking to the actual project is probably good because it has a nice big deprecated notice in the readme.

**Comment by Spacerat** [comment]
Ah, I actually hadn't noticed that it's a blog post. It's the thing that comes up when you google "react python" (or anything similar) and is formatted the same as the rest of React's documentation. But yeah, it seems like a shame to have to keep every old blog post up to date.

(I suppose after JSXTransformer becomes completely nonfunctional it might be worth making PyReact's deprecation notice a bit stronger, but at this point it's really just nitpicking)
