### ISSUE TITLE
React 15+ inline styling is producing concatenated style properties from separate, unique object keys

### ISSUE THREAD

**Issue by nathanmarks** [facebook/react#6524]
Assume the following styles object is provided to a component:
```js
const styles = {
  background: 'none',
  backgroundColor: 'red'
};
```

Prior to v15, this would result in (in the browser's computed styles):
```css
background: none;
background-color: red;
```

In React 15+, this results in (in chrome 49+):
```css
background: none red;
```

In chrome 48 it results in:
```css
background: none;
```

What this means is in chrome 49+, it has a red background, but in chrome 48 it has no background.

I'm not entirely sure who/what is at fault here. Would you be able to shed some light on the change? Is this a bug or an intended feature?

**Comment by oliviertassinari** [comment]
@nathanmarks We already faced a similar issue on the Material-UI Repository, we ended up fixing it with https://github.com/callemall/material-ui/pull/3124.
Chrome had a [buggy](https://bugs.chromium.org/p/v8/issues/detail?can=1&start=0&num=100&q=getOwnPropertyNames&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Area%20Stars&groupby=&sort=&id=4118) implementation of `Object.assign`. It's fixed now with this [commit](https://github.com/callemall/material-ui/pull/2986).
You can follow this thread for more detail https://github.com/callemall/material-ui/pull/2986.

I'm wondering if this isn't the same issue.
A quick fix would be no to use overlapping styles like `background` and `background-color` as suggested here https://github.com/facebook/react/issues/6348.

**Comment by nathanmarks** [comment]
@oliviertassinari I tested with React 0.14 and React 15 with a very simple component:

```jsx
const Example extends React.Component {
  render () {
    const styles = {
      background: 'none',
      backgroundColor: 'red'
    };

    return (
      <div style={styles}>Hello</div>
    );
  }
}
```

And in the chrome dev tools inspect element styles panel, I saw different computed values for React 0.14 and React 15

**Comment by zpao** [comment]
Hmm, it could be that Object.assign is at play here. I didn't think that would matter on initial render at least (I don't think we use a copy of the style object) but I'm just skimming this code path. It would make sense that the order is getting screwed up and red gets set before none.

The computed values are going to be misleading due to the use of createElement. In 14 we generated a string of markup for initial render which would look like `<div style="background: none; background-color: red"></div>`.

In 15 we create a DOM node and then set each style, just like we would do for updates in 14 and below. So `var node = document.createElement('div'); node.style.background = 'none'; node.style.backgroundColor = 'red';` Chrome doesn't report that sequence in the computed value so you only see the final value.

So what would be interesting is if you followed the same steps as React is doing in both versions of Chrome and see what happens. http://jsbin.com/dekiyulane/edit?html,js,output

**Comment by nathanmarks** [comment]
@zpao 

Strangely I'm having difficulty reproducing this again using my simple example component, I wonder if I clicked out of browserstack before it had a chance to finish rendering completely. So @oliviertassinari may well have been correct with the `Object.assign` assertion.

I'm going to do some further testing -- if I end up swinging back around to React again I'll reopen this issue.

**Comment by zpao** [comment]
The Object.assign issue has been pretty random and inconsistent in my experience. Thanks for checking!

**Comment by nathanmarks** [comment]
@zpao 

Figured it out. Object property iteration order is ending up different in [`setValueForStyles()`](https://github.com/facebook/react/blob/eb85b7b2c989faeb6ed8cd787cf67bd5f6d3ec7d/src/renderers/dom/shared/CSSPropertyOperations.js#L194) when touched by a particular script (even though when I iterate over the styles in the `createElement` it still has the original order preserved).

Now, since object property iteration order can't be guaranteed (from what I understand). That means this is definitely something we need to solve when we generate inline styles.
