### ISSUE TITLE
I got React v15 update error. 

### ISSUE THREAD

**Issue by yimankaing** [facebook/react#6530]
I run this command 
npm install --save react@15.0.0-rc.1 react-dom@15.0.0-rc.1
![screenshot from 2016-04-17 14 11 38](https://cloud.githubusercontent.com/assets/16798574/14585668/bcac7660-04a6-11e6-8a07-97a8f9b285a2.png)

**Comment by shinima** [comment]
The current version of React is v15.0.1. You can use v15.0.1 instead of v15.0.0-rc.1.

**Comment by jimfb** [comment]
Yeah, this is an error related to your `npm` configuration, rather than a bug in the React core.  For this reason, I'm going to close out the bug, since we try to keep github issues for tracking bugs in the React core.  Feel free to continue the discussion on this thread or move your question over to StackOverflow.

**Comment by gaearon** [comment]
The issue is due to `react-tap-event-plugin` and `react-mounter` wanting React 0.14.
You should update them if they have new versions compatible with 15.
You can also switch to using `npm@3.x` which doesn’t enforce peer dependencies, and proceed at your own risk.
