### ISSUE TITLE
React 15 regression: controlled select elements with optgroup not displaying value on initial render

### ISSUE THREAD

**Issue by mavisd** [facebook/react#6547]
Using React 15.0.1, controlled select elements with optgroup elements are not displaying (selecting) the value provided on initial render. See the following jsfiddle for a simple test case:

https://jsfiddle.net/Artconnoisseur/eg3j7fam/1/

Here is another fiddle where it is working using React 0.14.8:

https://jsfiddle.net/Artconnoisseur/hfp8rf1j/1/

**Comment by ev1stensberg** [comment]
[SO](http://stackoverflow.com/questions/20377837/how-to-access-custom-attributes-from-event-object-in-react) 

Could you try setting `bind()` in your render method? The SO questions and replies should give you a indication of how you would do that.

**Comment by subblue** [comment]
@mavisd I've been seeing the same behaviour in my React 15.0.1 app too.
For the moment I've been falling back to setting the ```selected``` attribute on the selected option tag (which does trigger the React warning about using the ```defaultValue``` or ```value``` on the select instead)

**Comment by gaearon** [comment]
@ev1stensberg 

`bind()` is not necessary with `React.createClass()` as the methods are autobound. Also the code is identical but behaves differently in different versions, so it’s an indication that it might be React’s fault.

@mavisd 

I think this is the same as #6440 and #6434, and was fixed in #6442. The fix is not out in 15.0.1, but it should get into the next patch release. I can confirm this working with the build from the master:

<img width="175" alt="screen shot 2016-04-19 at 15 32 18" src="https://cloud.githubusercontent.com/assets/810438/14642839/f1e635ca-0643-11e6-83c4-cfa9e116933e.png">

I’m closing for this reason.
