### ISSUE TITLE
Proposal: a component should just "not render" when a required property is missing

### ISSUE THREAD

**Issue by giacomorebonato** [facebook/react#6564]
In a ReactJS application I often repeat the following pattern when a component is relying
on a required property  

```
const MyComponent = props => {
  if (!props.user) {
    return null;
  }
  
  return <div>{user.name}</div>;
};

MyComponent.propTypes = {
    user: PropTypes.object.isRequired
}
```
The same pattern is [present also in Redux](https://github.com/reactjs/redux/blob/master/examples/async/containers/App.js#L60) and it is the same pattern that the [react-only-if](https://github.com/MicheleBertoli/react-only-if) is trying to centralize. 
But wouldn't it be clear if a component would just not render without a required property?
A warning could be still present only in development mode.

**Comment by gaearon** [comment]
Components suddenly disappearing after a refactoring would be frustrating IMO.

**Comment by giacomorebonato** [comment]
The actual behaviour in a production bundle when a required property is missing is:
1 an undefined exception
2 the component doesn't render  

In development: 
1. you still receive the 'missing proptype' warning 
2. the component doesn't render

So the component doesn't render anyway and in development mode you are still completely aware of everything, while in production you wouldn't see any exception.

**Comment by jimfb** [comment]
Proptype checks have a very measurable impact on the performance of your application.  That's why proptypes aren't checked in production.

The runtime behavior of development mode must match the behavior of production mode.  So if the behavior is going to change (ie. don't render the component) then we would be forced to do the proptype checks in production (which we don't want to do, because it's slow).

For this reason, we're probably not going to do this, so I'll close out the issue.  Feel free to continue the discussion on this thread, and we can re-open if our thinking on this matter changes substantially.
