### ISSUE TITLE
Lifecycle Compatibility/Recommendation Table

### ISSUE THREAD

**Issue by jimfb** [facebook/react#6586]
Can you call setState() from within a ref callback?  The answer is "Yes".  (Though it's probably not a good idea).

It's really confusing what is permitted / good / bad / illegal.  Especially because different things are legal at different times in the lifecycles.  Even if something is legal, it might be a bad idea.  We should clarify.

**Comment by gaearon** [comment]
We have some recommendations in [new lifecycle docs](https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle).
It took a lot of effort to get new docs together, so I don't expect us to spend more effort there soon.
Therefore an issue like this is much more likely to be addressed on a case by case basis by reviewing PRs rather than planning.

**Comment by voliva** [comment]
@jimfb @gaearon Sorry to raise this up 2.5 years later - I get that this is discouraged, but is there any alternative when you need to re-render after a ref callback?

Say you need to get a DOM element to render stuff in a portal (by using a component such as https://github.com/tajo/react-portal)

To me, storing the ref by `useRef` and then forcing render by forceUpdate sounds worse....
