### ISSUE TITLE
isNotRequired

### ISSUE THREAD

**Issue by arcanis** [facebook/react#6610]
It happens every once in a while that I want to do something like this:

```js
class MyGenericComponent {
    static propTypes = {
        score: React.PropTypes.number.isRequired,
        text: React.PropTypes.string.isRequired
    };

    render() {
        return <div>({this.props.score}) {this.props.text}</div>;
    }
}

class MyMoreSpecializedComponent {
    static propTypes = {
        score: MyGenericComponent.propTypes.score,
        text: MyGenericComponent.propTypes.text.isRequired
    };

    render() {
        return <MyGenericComponent score={this.props.score || 0} text={this.props.text} />;
    }
}
```

However, despite not looking especially wrong, this code doesn't work as expected for two reasons:

  - The `score` prop from `MyMoreSpecializedComponent` retains the `isRequired` flag from its declaration in `MyGenericComponent`. This issue could be solved by adding a `isNotRequired` flag, that would simply return the non-required version of the validator.

  - The `text` prop from `MyGenericComponent` doesn't have the `isRequired` flag, because it is already required. This issue could be solved by adding a no-op `isRequired` flag that would return the exact same validator.

I feel like those two changes would help to safely forward propTypes, improving the code readability in the process, with a very minimal cost in term of line of code.

Here's what `MyMoreSpecializedComponent` would look like:

```js
class MyMoreSpecializedComponent {
    static propTypes = {
        score: MyGenericComponent.propTypes.score.isNotRequired,
        text: MyGenericComponent.propTypes.text.isRequired
    };

    render() {
        return <MyGenericComponent score={this.props.score || 0} text={this.props.text} />;
    }
}
```

**Comment by jimfb** [comment]
A proptype can, in general, be any validation function (it is not limited to the ones we provide).  This means that you could define your own `isNotRequired` which just returns successfully if the function is null/undefined, and otherwise forwards the value to the previous propType checker for further validation.  This can be done entirely in userland, without changes to the React core.  If you find this useful, I would encourage you to make your `isNotRequired` open source so other people can re-use the same code.

In general, proptypes are mostly legacy at this point, as things move toward static analysis tools like Flow, so we aren't really adding new features to proptypes at the moment.  For this reason, I'm going to close this out.

Feel free to continue the discussion on this thread.  If you end up implementing this and publishing the source code, please do link to your repository from this issue.

**Comment by arcanis** [comment]
I see what you mean, but I think that the issue is that your solution (using custom validators) it would require to either reimplement every native propTypes in an external library (which might not be a bad idea actually, but a bit too out of scope), or use a very bad implementation that would catch the validation errors thrown by native propTypes and ignore them if they match the right regexp - and I feel like it wouldn't reliably work in edge cases. Implementing this into the core would be much reliable and clean.

All in all, I feel like it might be more a "bug" than a feature request (except that it would be an API bug rather the usuals implementation bugs), but I understand your current position.
