### ISSUE TITLE
Ability to hide component from devTools

### ISSUE THREAD

**Issue by blainekasten** [facebook/react#6621]
The React DevTools are great, but get convoluted when using community libraries at times (e.g., react-router, redux, coflux). Could there be a blessed API that allows components to not show in the Dev Tools? Something simple like:

```js
const Component = () => { ... };
Component.devTools = false;
```

When using the React DevTools, I generally just want to see my components and their business logic. Not things like `<RouterContext />` or `<Provider />`.

It is helpful to see those things at times though, so I don't imagine these components become completely opaque. But probably have a checkbox in DevTools (that defaults off), to show all components.

Assuming this is something you guys are too busy to do, if you like the concept, I can work on implementation.

**Comment by jimfb** [comment]
Probably this issue would be better discussed in https://github.com/facebook/react-devtools since an additional attribute on a component would be completely transparent to the React core.  For this reason, I'm going to close out the issue, but feel free to open an issue in the other repository.

With regards to the specifics of your idea, I have no objection to this.  However, I would suggest that if your application is sufficiently complicated that context providers are cluttering up your development experience, your application might be too complex.  I would gently suggest that maybe your application is overly-abstracted or that you aren't being faithful to one-way data flow from parent/owner to child.  Obviously I haven't seen your code, so take that with a grain of salt.  Just food for thought.
