### ISSUE TITLE
How to require a image in server side rendering?

### ISSUE THREAD

**Issue by Lanfei** [facebook/react#6672]
That's my code:

```js
<a href="/"><img src={require('../../img/logo.jpg')}/></a>
```

It works well with webpack in browser side, but in server side:

```
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at render
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext 

Process finished with exit code 1
```

**Comment by RaitoBezarius** [comment]
@Lanfei You might need something like this: https://github.com/halt-hammerzeit/webpack-isomorphic-tools

**Comment by jimfb** [comment]
This is a usage question about webpack/commonjs, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).

**Comment by Lanfei** [comment]
Okay, thanks to @RaitoBezarius @jimfb .
