### ISSUE TITLE
Objects are not valid as a React Child

### ISSUE THREAD

**Issue by zackify** [facebook/react#6708]
I searched for this issue earlier and saw a mention of it, but I think this is different. I am using Immutable.js and have an Immutable.List() as my react children on react v15.0.2. This works fine in modern browsers. 

Inside of IE 11, React will throw an invariant saying that objects are not valid react children. I do have a Symbol.iterator polyfill (using babel-polyfill). 

The current solution is calling .toJS() in the children so that IE doesn't complain, but I am not sure if this is supposed to be happening.

Here is a jsfiddle with what I am doing: https://jsfiddle.net/xehvnmt0/4/

For some reason, in IE 11 with the example it works. But with babel 6 and babel-polyfill it throws the error: 

<img width="1682" alt="screen shot 2016-05-05 at 3 36 50 pm" src="https://cloud.githubusercontent.com/assets/449136/15054785/2aa71592-12d7-11e6-93f2-1dc2acc13904.png">

Not sure why I can't reproduce in the fiddle, but when adding .toJS() onto the end of the list that error goes away on my site.

**Comment by zpao** [comment]
Hmm, if you can't repro a contained case it might be due to that polyfill or when/how it gets loaded. You should only get that warning if we can't find the iterator function that should be on the object (and we look for that fn with this: https://github.com/facebook/react/blob/master/src/shared/utils/getIteratorFn.js#L32-L40). Since this is a pretty particular case, it might be helpful to try to repro outside of jsfiddle (which is using babel 5 right now so probably different from what you're doing). Maybe just a standalone html & js file & then shared in a gist.

**Comment by zackify** [comment]
Okay thanks for the tip I will try to do that tonight.

**Comment by zackify** [comment]
It turns out I had to add this to my webpack entry point instead of having it inside of my entry point. I think this was do to using providePlugin in webpack, either way it's fixed and not a problem with React. Sorry :P

**Comment by bradens** [comment]
@zackify I am having this issue, and I currently have `Immutable` with providePlugin in my app.  Did you have to remove that in order to get it to work?

**Comment by zackify** [comment]
@bradens what I meant was, the polyfill was included incorrectly (I think). I have a terrible memory lol

**Comment by pts-moog16** [comment]
I was seeing the same thing in my app on IE11, where it couldn't render an Immutable.js List. I Googled a bit more and found this github issue: https://github.com/facebook/react/issues/8379. Please see @leondragan comment from Dec 5, 2016. I instead of importing `babel-polyfill` from my main index.js file, I imported it through webpack, and before 'react' and 'react-dom'.
