### ISSUE TITLE
Proposal – getComponentAtNode

### ISSUE THREAD

**Issue by lukehorvat** [facebook/react#6721]
ReactDOM already has the `unmountComponentAtNode` function. I think it would be useful if there was a similar utility function that simply let you *get* the component instance at a particular DOM node.

It would allow you to guard `unmountComponentAtNode` calls, and also help folks who need lots of interop between non-React code and React code. Furthermore, it seems like a good function to have for the sake of ReactDOM API "completeness".

Perhaps could be named `getComponentAtNode`? Or `findComponent` (to be similar to `findDOMNode`)?

Happy to start working on a PR for you if y'all like the idea.

**Comment by jimfb** [comment]
Using component instances is an escape hatch anyway.  It is not a recommended pattern, so we don't want to encourage their usage by providing more helper functions.

You can already get a reference to the instance by attaching a ref to the root node when you mount the component.  Once you have an instance, you could attach it to the container DOM node, or do anything else you'd like (eg. save it somewhere else).  The point is that an additional `getComponentAtNode` doesn't actually allow you to do anything that you couldn't do prior to having that function.  This is the most compelling reason to not increase the API surface area by adding more functions.

Hope that makes sense!

I'm going to close this out, since it's probably not something we'd want to add.  However, feel free to continue the discussion on this thread.  We can re-open if our thinking on this matter changes substantially.
