### ISSUE TITLE
React Router Error Occur

### ISSUE THREAD

**Issue by superchangme** [facebook/react#6766]
When i use react router ，something broken code like ：
~~~

import React, {Component} from 'react'
import ReactDOM from 'react-dom'
import { Router, Route, Link, browserHistory } from 'react-router'

const App = React.createClass({/*...*/})
const About = React.createClass({/*...*/})
// etc.

const Users = React.createClass({
  render() {
    return (
      <div>
        <h1>Users</h1>
        <div className="master">
          <ul>
            {/* use Link to route around the app */}
            {this.state.users.map(user => (
              <li key={user.id}><Link to={`/user/${user.id}`}>{user.name}</Link></li>
            ))}
          </ul>
        </div>
        <div className="detail">
          {this.props.children}
        </div>
      </div>
    )
  }
})

const User = React.createClass({
  componentDidMount() {
    this.setState({
      // route components are rendered with useful information, like URL params
      user: findUserById(this.props.params.userId)
    })
  },

  render() {
    return (
      <div>
        <h2>{this.state.user.name}</h2>
        {/* etc. */}
      </div>
    )
  }
})

// Declarative route configuration (could also load this config lazily
// instead, all you really need is a single root route, you don't need to
// colocate the entire config).
ReactDOM.render((
  <Router history={browserHistory}>
    <Route path="/" component={App}>
      <Route path="about" component={About}/>
      <Route path="users" component={Users}>
        <Route path="/user/:userId" component={User}/>
      </Route>
      <Route path="*" component={NoMatch}/>
    </Route>
  </Router>
), document.body)
~~~

===
Error is like:
**

bundle.js:185 Uncaught Invariant Violation: createClass(...): Class specification must implement a `render` method.

**
===

a

**Comment by GGAlanSmithee** [comment]
I think, because you are using `React.createClass({` you must do `render: function() {`

if you use ES6 classes your syntax is valid

```javascript
class A extends React.Component {
    render() {
        return null
    }
}

// vs

var A = React.createClass({
    render: function() {
        return null
    }
});
```

**Comment by gaearon** [comment]
@GGAlanSmithee 

I don’t believe this is correct. [ES6 object literal shorthand notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) allows `render() { }`.

@superchangme 

We use the issue tracker for bugs and feature requests in React itself. What you’re asking seems like a usage question, and would be more appropriate on StackOverflow.

The error says:

>createClass(...): Class specification must implement a render method.

This means one of your `createClass()` calls misses a `render()` function on the specification object. Since you didn’t post the complete code, I can’t say which exactly. 

When you see an error like this, click on a small arrow next to it:

<img width="709" alt="screen shot 2016-05-13 at 12 54 14" src="https://cloud.githubusercontent.com/assets/810438/15247115/de19ea5e-1909-11e6-95fc-93ab116d5497.png">

This is the stack at the time the error was thrown. The third line should show *where* in your code that `createClass()` call was. Click on it, and you’ll find the component with the missing `render()` method.

I hope it helps! I’m closing as this is unlikely to be a bug in React, but please feel free to continue the discussion.

**Comment by GGAlanSmithee** [comment]
> @GGAlanSmithee
> 
> I don’t believe this is correct. ES6 object literal shorthand notation allows render() { }.

ah, my bad, thanks for informing me
