### ISSUE TITLE
Change expression brackets from {} to [].

### ISSUE THREAD

**Issue by UI-no-cry** [facebook/react#6774]
Feature request.

If we change expression brackets from {} to [], we will be able to render <style> tag in react component.

**Comment by jimfb** [comment]
Not entirely sure what is being requested here, but it's highly unlikely that we're going to change the jsx syntax definition, since it is already being implemented in so many places (babel, typescript, editors, etc).  For this reason, I'm going to close this out.  We can always re-open if our thinking on this matter changes.

However, with regards to your specific feature request... can you elaborate on what you're trying to do?  You can already pass tags as an expression, as demonstrated in http://jsfiddle.net/e3t4jzxj/

**Comment by UI-no-cry** [comment]
@jimfb, I mean, that i want to render component styles in jsx syntax: css in js, like html in js.
But { brakcets not allowed to render style tag in component.

I know about https://github.com/krasimir/cssx, it is good idea, but there is not good realisation.

May be in reactjs will realised this feature, render css in js. I think it is not hard on current jsx core.

example:

`.myClass {
    color: [colorVariable]
}`

**Comment by jimfb** [comment]
We are working on a way to represent styles in javascript, but it is still a work in progress.  However, our solution is not likely to "change expression brackets from {} to []".  The current recommendation for representing styles is: https://facebook.github.io/react/tips/inline-styles.html
