### ISSUE TITLE
[React 15.0.2] Production mode

### ISSUE THREAD

**Issue by menved** [facebook/react#6821]
Is NODE_ENV still required to change between development and production mode?
I can´t find anything about that in the source code for the 15.0.2 version.

**Comment by jimfb** [comment]
Yes, afaik.  Although there is https://github.com/facebook/react/issues/6582 under discussion.

This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).

**Comment by zpao** [comment]
FWIW, the source code on github doesn't contain NODE_ENV checks, those are part of a transform step before shipping to npm (look for __DEV__ in the code - those get transformed)
