### ISSUE TITLE
External javscript in react component

### ISSUE THREAD

**Issue by uragecz** [facebook/react#6907]
Hi, i have problem, i wanna use external javascript - fabric.js in my component during server-side render.. any tips how do it? I still have error message fabric is not defined. Thank you so much

**Comment by jimfb** [comment]
This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, which takes it off our radar, but feel free to continue the conversation here (or move it to StackOverflow).

Also, your message does not contain enough information to be actionable.  Based on what you've said, it sounds like fabric is not correctly being loaded into your server-side environment.  You may need to add it as a project dependency, or dynamically request the file and eval it into the JSVM.  Unfortunately, with only the information you've provided, it's not possible to determine what is going wrong here.  Either way, it doesn't appear to be related to React.
