### ISSUE TITLE
Return `null` from mocked functional components.

### ISSUE THREAD

**Issue by cpojer** [facebook/react#6932]
We do this for classes but not for functional components, see https://github.com/facebook/react/blob/db6ac5c01c4ad669db7ca264bc81ae5b3d6dfa01/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L1042-L1045

This leads to a lot of issues and confusion for people using Jest. I realize this is maybe not the greatest implementation ever, but since we support it for one but not the other, we should align the implementation and add this until we find a better way to deal with this.

This should be easy to add somewhere around here: https://github.com/facebook/react/blob/6b1232aa86415f0573153888a46c4c5cb38974d8/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L210

@spicyj

**Comment by cpb** [comment]
@cpojer what kind of mock functional component do you mean?

- a mock functional component without an implementation
- a mock functional component with an implementation

please see: https://github.com/cpb/react/commit/3675b208cf933a52c5062727f91dea8d0c071dd4

as even the mocked component has a [lil render implementatoin](https://github.com/facebook/react/blob/bef45b0b1a98ea9b472ba664d955a039cf2f8068/mocks/ReactMockedComponentTestComponent.js#L29-L31) (without which the tests don't pass)

**Comment by jimfb** [comment]
Do we even need to use mocks for stateless functions?  It is trivial to just write a quick function that has the expected behaviors (return whatever, make assertions on arguments and/or track number of times called).  I'd be in favor of just rewriting any callsite that is an issue.

**Comment by spicyj** [comment]
The issue is that automocking doesn't work if your module exports a functional component, @jimfb.

**Comment by jimfb** [comment]
@spicyj But I thought we were disabling automocking for React.

**Comment by cpojer** [comment]
This is unrelated to the state of whether React is mocked or not. This is also unrelated to automocking, it just exhibits this problem further.

Example user code:

```js
module.exports = () => <span />;
```
vs.
```js
module.exports = React.createClass({render() { return <span />; });
```

the former will render to undefined and throw, the latter will render to null if that component is mocked using `jest.mock('MyModule')` or when automocking is on. Multiple people have reported that this is annoying and that they have many such components that they'd have to stub out manually. I'd prefer to align React to work well for functional components and any other ways of defining a component.

**Comment by jimfb** [comment]
I think the hack in [ReactCompositeComponent](https://github.com/facebook/react/blob/db6ac5c01c4ad669db7ca264bc81ae5b3d6dfa01/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L1042-L1045) was added to avoid breaking unit tests, but it was always a hack and never intended to be a good/supported pattern.  We would have codemodded the pattern away from www, but there are almost a thousand unit tests depending on that behavior at the moment, and we didn't see an easy fix/codemod.

A workaround (which I think would work) is to just use `()=>null` instead of a mock function.

We could probably just add a warning telling the user to use a lambda function instead of a mock.

**Comment by cpojer** [comment]
I don't think that argument makes sense. We are supporting this hack not just in www, but also in open source. Right now, we are supporting this hack partially. If you want to remove this hack, then that is fine with me too, as long as you have a good upgrade story that isn't going to impact people's developer efficiency.

I don't understand how people would use `() => null` if their function comes from a mock that they may not control. This has primarily come up in open source and people get angry at Jest about it because it used to work fine with React.createClass/ES2015 classes but now it doesn't work for them any more.

**Comment by jimfb** [comment]
> If you want to remove this hack, then that is fine with me too, as long as you have a good upgrade story that isn't going to impact people's developer efficiency.

My concern is that if we support the hack for stateless functions, we will be digging ourselves into a deeper hole.  Rather than adding support, I'd rather we use this as an opportunity to drive people away from a behavior that we'd like to deprecate anyway.  If they want to adopt stateless functions, they need to stop relying on the legacy behavior.

 > I don't understand how people would use () => null if their function comes from a mock that they may not control.

They can use `()=>null` instead of the default function mock.  Presumably Jest provides a hook for people to override the default mock behavior/implementation, right?

**Comment by cpojer** [comment]
Well, the feedback I have received is that they have too many stateless components so that manually mocking all of them is annoying to them, especially when this was handled by "Jest/React" for them previously. Most people don't understand the difference. If I could change this in Jest, btw., I would, but unfortunately I can't know whether something is a functional component upfront.

**Comment by jimfb** [comment]
Yeah, I agree, I'm not sure there is a great solution here.  I'm open to ideas on how we can make the migration path (away from this legacy behavior) easier.

An alternative workaround is to use a real implementation instead of a mock for the SFCs.  Then it becomes a little closer to an integration test instead of a unit test, but the upside is the behavior they're testing is closer to real life.

**Comment by gaearon** [comment]
We never did this, and Jest moved away from automocking so I doubt we'll add more hacks for Jest into the core either.
