### ISSUE TITLE
react-addons-perf doesn't work in IE11

### ISSUE THREAD

**Issue by deser** [facebook/react#6978]
I see error: `Object doesn't support property or method 'table'`. Seems IE doesn't support console.table

**Comment by gaearon** [comment]
While this is unfortunate, I recommend you to profile using Chrome and Firefox. ReactPerf only measures the “own” time of your components so there shouldn’t be a big difference in different browsers. It doesn’t measure the actual painting or DOM operation time. (It’s usually much smaller than time spent in components.)

In the future, we intend to bring ReactPerf into React DevTools. It should be possible to integrate React DevTools into IE if you’re interested (it’s just a webapp), but this is not something we’ll actively be working on.

I’ll probably close because fixing this is not a priority for us. As a reasonable workaround, you can call `ReactPerf.getWasted()` and other `get*()` methods instead of `print*()` methods to read the measurements. You can also polyfill `console.table`.

I hope this helps somewhat. If you have other suggestions, please let us know!

**Comment by deser** [comment]
Thanks! Regarding "big difference": due to different JS engines something which is fast in Chrome could be slow in IE. Therefore results could be different to my mind. Anyway thanks for support!

**Comment by gaearon** [comment]
Yea, could be in practice but I’d argue that if you see the difference, you’re doing too much work inside components 😉 . Anyway, I agree it’s a bit inconvenient. We just don’t want to put too much effort into maintaining the console API, and would rather work on integrating it with DevTools proper. That said `get*()` or `console.table` polyfill should be reasonable solutions.

**Comment by deser** [comment]
Yes, thanks!
