### ISSUE TITLE
Relax validateDOMNesting warning for whitespace in table

### ISSUE THREAD

**Issue by spicyj** [facebook/react#6995]
See https://github.com/facebook/react/issues/5071#issuecomment-224477058 -- since we stopped wrapping text in spans, we should loosen the validation in validateDOMNesting a little. I think it should probably be fine to have whitespace anywhere in the tree?

**Comment by syranide** [comment]
> I think it should probably be fine to have whitespace anywhere in the tree?

Yah. I'm torn, considering we don't really validate for invalid nesting and not to be strict it seems fine to just let it through even though it's useless. However, non-whitespace strings are not allowed there and will break SSR.

**Comment by jimfb** [comment]
@syranide I don't understand, why are you torn?  This issue is only about whitespace, which is always safe, even with SSR, right?

**Comment by syranide** [comment]
@jimfb Yeah, it's safe, but it's also useless and there's virtually no reason for it to exist there. So warning could be a good thing too. It isn't really a big deal though, this is very much an edge-case, but still.

**Comment by mnpenner** [comment]
Thank for opening this ticket for/because of me, but I think the warning is not too bad actually. What if someone tries writing something like:

```jsx
<tr>{someString}</tr>
```

Now the warning would be suppressed if `someString` is an empty/whitespace string, but it will become a legitimate problem as soon as a value is put in there, causing an error only *some* of the time, which is the worst kind of bug.

*However,* empty strings *are* falsey so avoiding the warning in situations such as I had,

```jsx
<tr>{someString && <td/>}</tr>
```

Would actually be beneficial. But it's also not too hard for me to amend that code to make sure `someString` comes out a bool, so I'm leaning towards keeping the warning in.

Also, if it's going to create these `<!-- react-text -->`s, I'd rather avoid that, even if they're invisible.

**Comment by agiron123** [comment]
I'd be interested in taking a stab at fixing this. I'll have a PR up later this week.

**Comment by joshhunt** [comment]
For what it's worth, we saw this error when we had a comment at the end of a line in the `<head>`. For example, this produces an error:

```
return (
  <head>
    <title>React.js</title> {/* title tag! */}
  </head>
)
```

**Comment by syranide** [comment]
@joshhunt Ah, that's part of the JSX parsing rules. If you replace your comment (which is actually an empty expression) with a string it makes a lot more sense, same rules apply.

**Comment by joshhunt** [comment]
Yeah I got that - I figured an extra space char wound up in the generated response, but I figured there's nothing wrong with white space in the head tag and would fall under this issue?

**Comment by hkal** [comment]
Going to give this a go.

**Comment by wallacyyy** [comment]
Is this still active ? I can give a try if not :)

**Comment by Aweary** [comment]
@wallacyyy there's an open PR for this at https://github.com/facebook/react/pull/7081

**Comment by spicyj** [comment]
Fixed in https://github.com/facebook/react/pull/7515.

**Comment by wallacyyy** [comment]
@Aweary I know, just asked because the last interaction was 2 months ago, so maybe the PR could not been active anymore :) Thx for the reply !
