### ISSUE TITLE
React 15.x can not work in IE 8.

### ISSUE THREAD

**Issue by eternalsky** [facebook/react#6999]
https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L248

It seems that createElement method will call `Object.defineProperty` without checking canDefineProperty, and make IE8 crash even with `es5-sham.`
es5-sham throw an error but not catched by react.

**Comment by jimfb** [comment]
If I'm understanding correctly, this will only crash the dev build, not the prod build, fwiw.  So this would affect the developer experience, but not the end-user experience.

I'm going to close this out, since IE8 is not a supported platform, but we would probably accept a PR to fix this if you'd like to write one up.

**Comment by jpdevries** [comment]
In my tests, React 15.x completely breaks IE8. Total white screen of death even when using the prod builds. 😢 This is very alarming because it makes building progressively enhanced web apps cumbersome. All this work to ship initial HTML, and then React destroys it all just by including it on the page.

I can do a separate proof of concept for the issue and would be willing to work on a PR if the issue is confirmed https://github.com/jpdevries/matboard/issues/5

**Comment by zpao** [comment]
We don't actively support IE8 anymore (https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html) so we won't be taking any active measures. If you'd like to fix up some places where just including it on a page breaks things we'd consider that.

**Comment by brigand** [comment]
@jpdevries You might be able to solve your problem by only calling ReactDOM.render on supported browsers, e.g. by checking the user agent or using IE conditional comments.

**Comment by jpdevries** [comment]
@brigand I tried that. Removing my `app.js

**Comment by jpdevries** [comment]
@zpao thanks for the info. I'll see if I can whip something up. I understand not support IE8, but to destroy the page completely seems very aggressive. So far, I've been able to do a feature detection to see if it is an old browser and then I just don't load the scripts at all, but that doesn't seem like a process many web developers would follow

**Comment by brigand** [comment]
@jpdevries not saying it's a good solution or that this behavior is acceptable, but as a quick fix try wrapping all of the scripts in an IE conditional comment. Strangely, there's no way to say "if IE and not IE less than 9" as far as I can tell, so you might need to use document.write.

```js
<script>
(function(){ 
  var myNav = navigator.userAgent.toLowerCase();
  if (!myNav.indexOf('msie') != -1 || parseInt(myNav.split('msie')[1], 10) >= 9) {
    document.write('<script src="react.js"></script>');
    document.write('<script src="react-dom.js"></script>');
    document.write('<script src="app.js"></script>');
  }
})();
</script>
```

**Comment by jpdevries** [comment]
@brigand I would up with something not too much different, but it does use feature detection instead of the userAgent

```html
<script>
    var doEnhancments = document.addEventListener ? true : false; // this is super annoying but react-redux will bork the page, turn it into a blank white screen in IE8 so we have to not even try to load it :(
</script>

  <!-- NOTE: change these to load the .min in production. They are not only smaller filesize but have wildly different performance -->
	<script>if(doEnhancments) document.write('<script defer src="//cdnjs.cloudflare.com/ajax/libs/redux/3.5.2/redux.min.js"><\/script>');</script>
  <script defer>if(doEnhancments) try { Redux } catch (e) { document.write('<script src="assets/js/vendor/redux.min.js"><\/script>') }</script>

	<script>if(doEnhancments) document.write('<script defer src="//cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react.min.js"><\/script>');</script>
  <script defer>if(doEnhancments) try { React } catch (e) { document.write('<script src="assets/js/vendor/react.min.js"><\/script>') }</script>

	<script>if(doEnhancments) document.write('<script defer src="//cdnjs.cloudflare.com/ajax/libs/react/15.0.1/react-dom.min.js"><\/script>');</script>
    <script defer>if(doEnhancments) try { ReactDOM } catch (e) { document.write('<script src="assets/js/vendor/react-dom.min.js"><\/script>') }</script>

	<script>if(doEnhancments) document.write('<script defer src="//cdnjs.cloudflare.com/ajax/libs/react-redux/4.4.5/react-redux.min.js"><\/script>');</script>
	<script defer>if(doEnhancments)try { ReactRedux } catch (e) {  document.write('<script src="assets/js/vendor/react-redux.min.js"><\/script>') }</script>

	<script>if(doEnhancments) document.write('<script defer src="assets/js/app.js?nc=7"><\/script>');</script>
```

I load React and Redux dependencies from CDNs with local fallbacks.

I also tried a trick where you create a global variable, and then use IE conditionals to set that global variable to true (or false). I prefer the feature detection method though.

**Comment by brigand** [comment]
Btw, I wouldn't document.write in a defer script, I think that will wipe out the document.

**Comment by jpdevries** [comment]
Good point @brigand. Ok so for the record, I did some more testing and it seems the local fallback is part of the issue. I haven't been able to reproduce the white screen of death in IE 8 without the local fallbacks. So that's good to know.
