### ISSUE TITLE
Downloading the script files could be easier

### ISSUE THREAD

**Issue by 1j01** [facebook/react#7013]
**Do you want to request a *feature* or report a *bug*?**

A website feature / meta improvement

**What is the current behavior?**

You get a file name like `t39.3284-6/12726956_279572999043766_1590663715_n.js` and have to rename it

**What is the expected behavior?**

It should download with the correct file name, i.e. with `<a download="react-dom-v15.1.0.min.js">`

**Comment by keyanzhang** [comment]
Sounds great to me! Would you like to look into https://github.com/facebook/react/blob/master/docs/downloads.md and send a PR to improve it?

**Comment by jimfb** [comment]
@keyanzhang I don't think it has anything to do with the downloads page.  I think it has to do with the way our CDN works, which is not something that someone outside of facebook could reasonably fix.

**Comment by keyanzhang** [comment]
@jimfb yeah, but that being said, it might be possible to change the link on our end from a markdown link to a HTML <a> tag where we can specify a "download" attribute.

**Comment by tehwalris** [comment]
@keyanzhang (tl;dr: download attribute did not rename the file in any browser)
I tested the download attribute on the react page. It was completely ignored by Firefox (cross-origin download). Chrome downloaded the file instead of displaying it, but did not set the correct name. Edge downloads the file either way and never renames it. IE and Safari generally don't support the attribute. I didn't test Opera. Adding the download attribute will have almost no effect.

**Comment by keyanzhang** [comment]
@tehwalris Thanks for looking into this! Yeah seems like it doesn't work since the link is cross-origin. 😢

**Comment by gaearon** [comment]
We've removed the "starter kit" altogether.
We are also not using `fb.me` CDN anymore.
Closing.
