### ISSUE TITLE
Feature Request: PropTypes.deny

### ISSUE THREAD

**Issue by nbrady-techempower** [facebook/react#7023]
When writing out propTypes to ensure the accuracy of my components it is sometimes necessary that a component _not_ receive a particular prop as it may cause problems with the component receiving props or lead to other confusion. I suggest the following:

```
MyComponent.propTypes = {
  onChange: React.PropTypes.deny
}
```

which would then output a warning like:

`Warning: Failed propType: prop 'onChange' was specified in 'MyComponent' and should not be used. Check the render method of 'MyComponentParent'.`

**Comment by keyanzhang** [comment]
You can make a custom validator as explained in https://facebook.github.io/react/docs/reusable-components.html.

**Comment by nbrady-techempower** [comment]
Yes, I also use custom validations. Which could also be done for most of the other ease-of-use propTypes. This is for more ease-of-use.

**Comment by Aweary** [comment]
@nbrady-techempower I believe PropTypes are basically in maintenance mode, meaning the core team isn't looking to expand the PropType feature set in any way. You're best off using a custom validator as @keyanzhang mentioned.

**Comment by nbrady-techempower** [comment]
I get what you're all saying. And I'm already using custom validations for such. Just a suggestion for an enhancement. If it's in maintenance mode and they're not looking to expand at all that's fine too. Maybe I'll submit a PR to add it in and see if they take it.

**Comment by Aweary** [comment]
@nbrady-techempower there was a similar PR requesting a deprecation message, you see how it turned out here: https://github.com/facebook/react/pull/6357

Per @jimfb 

>Proptypes are mostly legacy and in maintenance mode, having been replaced by tools like Flow, so we've generally shied away from adding new features/functions/api. There is no reason that this functionality needs to be tied into React, so my intuition is that the best strategy here is to just create a third-party library that helps users define deprecated proptypes, and post that on github.

I think the same applies here. Create a library and open source it!

**Comment by nbrady-techempower** [comment]
@Aweary I have never seen anything in the React API documentation that suggested React.PropTypes was a legacy feature, especially since using the same type of model with the new experimental context API. Thanks for the information, if this is the way they are moving then this should probably be an issue about updating the React.PropTypes documentation to suggest such.

**Comment by jimfb** [comment]
@nbrady-techempower Longer term, the plan is to move away from proptypes, in favor of static analysis tools like Flow, as @Aweary mentioned.  The same absolutely does apply here!  We probably won't be adding this to proptypes, since they are mostly legacy and in maintenance mode, but you're welcomed to release `deny` as part of an open source proptype library!

We will update the documentation for proptypes when we're ready to officially deprecate them, but that time has not yet come.  There is nothing actionable at the moment, thus no open issue.

I'm going to close this out for the reasons mentioned above.  Feel free to continue the discussion on this thread.  If you end up releasing this as an open source library, feel free to link to your library in this thread.
