### ISSUE TITLE
How to handle propTypes undefined in production

### ISSUE THREAD

**Issue by gajus** [facebook/react#7031]
I am aware that:

> Note that for performance reasons propTypes is only checked in development mode

https://facebook.github.io/react/docs/reusable-components.html#prop-validation

In development mode, we have "models": collections of `propTypes`, e.g.

```js
import { PropTypes } from 'react';
import Layout from './../../component/Layout';

export const schema = {
    direction: Layout.propTypes.direction.isRequired,
    components: PropTypes.arrayOf(Component)
};
```

`Layout` is React component. I am expecting to access `propTypes.direction` property of `Layout` component. This works in development environment. However, because `propTypes` are stripped in production, I am getting an error:

> Uncaught (in promise) TypeError: Cannot read property 'direction' of undefined(…)

The only fix that I can think of in user land is adding a safe-check that eliminates the dead-code during the build stage, e.g.

```js
export const schema = __DEV__ ? {
    direction: Layout.propTypes.direction.isRequired,
    components: PropTypes.arrayOf(Component)
} : null;
```

This is sub-optimal, because it would require updating each instance where `propTypes` are used to declare data shapes.

* Is there an environment variable that would force to keep `propTypes` but disable validation?
* Can you suggest an alternative approach to this issue?

**Comment by gaearon** [comment]
>However, because propTypes are stripped in production, I am getting an error

PropTypes are not currently stripped in production. There was a proposal for this (#6401) but we haven’t agreed on it, and in any case, it’s not there in 0.14.x or 15.x.

React **does not call** your propTypes in production, but if you defined them, they will stay there. If `propTypes` declarations get stripped from your builds, it’s because you specifically choose to do this (e.g. via a [Babel plugin](https://github.com/thejameskyle/babel-react-optimize#transform-react-remove-prop-types)). This is not the default behavior of React, so I’ll close this as this is unactionable for us.

**Comment by gajus** [comment]
Apologies. My blunder.

I forgot to account for the addition of https://github.com/thejameskyle/babel-react-optimize, which includes `transform-react-remove-prop-types`.
