### ISSUE TITLE
Cannot access "this" or "props"

### ISSUE THREAD

**Issue by Aftabnack** [facebook/react#7052]
**Do you want to request a *feature* or report a *bug*?**
Seems like a bug. Not sure

**What is the current behavior?**
Unable to access props, if the function is defined outside

**If the current behavior is a bug, please provide the steps to reproduce.**
https://jsfiddle.net/69z2wepo/45785/

**What is the expected behavior?**
Expected Behavior is having access to the props

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am working with 15.1.0, though I believe this is present in older versions as well

**Comment by Aftabnack** [comment]
This works
```javascript
var func = function(e){alert(this.props.val)};

var Comp = React.createClass({
	func,
	render: function(){
		return <button onClick={this.func}>Click me</button>;
	}
});

ReactDOM.render(<Comp val="testing"/>,document.getElementById("container"));
```

This doesn't
```javascript
var func = function(e){alert(this.props.val)};
var inner = <button onClick={func}>Click me</button>;

var Comp = React.createClass({
	func,
	render: function(){
		return inner;
	}
});

ReactDOM.render(<Comp val="testing"/>,document.getElementById("container"));
```

This doesn't too
```javascript
var func = function(e){alert(this.props.val)};

var Comp = React.createClass({
	render: function(){
		return <button onClick={func}>Click me</button>;
	}
});

ReactDOM.render(<Comp val="testing"/>,document.getElementById("container"));
```

**Comment by syranide** [comment]
That's simply how `this` works in JavaScript. The only reason the first of your three examples works is because `React.createClass` *auto-binds* all functions defined on the object such that `this` becomes the component instance. In all other cases it's simply a function without an explicit `this` (and thus references `window` or something equally meaningless).

To manually bind it you have to do the following:

```
var func = function(e){alert(this.props.val)};

var Comp = React.createClass({
    render: function(){
        return <button onClick={func.bind(this)}>Click me</button>;
    }
});

ReactDOM.render(<Comp val="testing"/>,document.getElementById("container"));
```

**Comment by Aftabnack** [comment]
What if I want to define my component outside? Like Example 2.

I can't do .bind(this) when defining component outside right? Since it will be pointing to something else.

**Comment by jimfb** [comment]
@syranide is correct, this is just how javascript works.  Is it confusing?  Yes.  Is it something React can fix?  No.  For this reason, I'm going to close out the issue.  Feel free to continue the discussion here, or move it to StackOverflow.

Your last example doesn't work because you are binding the function to the class returned by createClass instead of binding it to the instance of that class which represents your rendered component.  The instance of your class is not available prior to rendering.

**Comment by Aftabnack** [comment]
Is it possible for me to make sure the component will have access to props? Maybe by binding constructor to the function?

**Comment by jimfb** [comment]
The component instance will always have props.  Binding the class/constructor is a non-starter.

**Comment by Aftabnack** [comment]
Sorry I meant the functions that I'm passing to the class. Not the component instance
