### ISSUE TITLE
ReactPerf TotalTime measurement

### ISSUE THREAD

**Issue by KamranAsif** [facebook/react#7055]
We were relying on the total time output from ReactPerf.printWasted to measure performance of our components to prevent degradation.
 This is working in v14 to v15, but in 15.1 there is no more ReactDefaultPerfAnalysis

What is the replacement functionality for this? Is this expected to come back in a future release?

**Comment by zpao** [comment]
cc @gaearon. You've been tracking this, is there a related issue already?

**Comment by gaearon** [comment]
`ReactDefaultPerfAnalysis` was an internal module, its name was not part of public API.

Using `require('react/lib/ReactDefaultPerfAnalysis')` was never supported, you should be using `require('react-addons-react-perf')` instead.

That said, `require('react-addons-react-perf')` is still there, and it includes all old `ReactPerf` methods including some new methods (`getInclusive()`, `getExclusive()`, `getWasted()`, `getOperations()` in addition to the previously existing `print*()` methods).

You should be able to use `ReactPerf.getWasted()` for the same purpose. Is there anything it’s missing that makes it unsuitable for your use case?

>total time output

The algorithm changed and we don’t measure time spent *in React itself* anymore. We just measure the user code (that is, the time it took to run *your components’* code). So I removed “total time” because it was a little misleading. That said you can still sum up all the rows from `getExclusive()` if you find the “total time” valuable. Or you can use lower level `getLastMeasurements()` and do your own calculation any way you like. [`getWasted()` implementation](https://github.com/facebook/react/blob/master/src/renderers/shared/ReactPerf.js#L173-L269) might give an idea of how to calculate specific stats from the measurements.
