### ISSUE TITLE
React and displayName property

### ISSUE THREAD

**Issue by acpower7** [facebook/react#7078]
I have the following piece of code:

     import React from '../src/lib/React'
    
        var TestComponent = React.createClass({
          render: function() {
            return <div />;
          },
        });

In the ReactClass.js of the library:

    var ReactClass = {
    
      /**
       * Creates a composite component class given a class specification.
       *
       * @param {object} spec Class specification (which must define `render`).
       * @return {function} Component constructor function.
       * @public
       */
      createClass: function (spec) {
        var Constructor = function (props, context, updater) { //breakpoint
      
          this.props = props;
          this.context = context;
          this.refs = emptyObject;
          this.updater = updater || ReactNoopUpdateQueue;
          this.state = null;
          ...
        };

        return Constructor;
      }
    
    };

If I inspect the `spec` variable at the breakpoint I get the following object:

    Object
    displayName:"TestComponent"
    render:function render() { … }
    __proto__:Object

Where did the displayName property came from, and how it was assigned "TestComponent"? I've looked everywhere and can't find it.

**Comment by keyanzhang** [comment]
Hey,

`displayName` gets added by the JSX transform (Babel). More information can be found at https://facebook.github.io/react/docs/jsx-in-depth.html and the actual compiler pass is at https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-display-name/src/index.js.

Since this is not technically an issue I'm going to close it first; feel free to comment or reopen if there's stuff missing. Thanks!
