### ISSUE TITLE
wrap state and props with getter and setter 

### ISSUE THREAD

**Issue by yongxu** [facebook/react#7096]
In development, if the `state` or `props` accidentally get directly manipulated,  a warning will pop up.

Though this is a pretty dumb mistake, it does happen occasionally. Some tools like flow can detect this but not every uses them

**Comment by jimfb** [comment]
Props are already frozen in development mode, which is better than wrapping it with getters and setters because throws if you try to add new props in addition to mutating existing props.  We also recently introduced a warning that prevents you from mutating the children array.  Anyway, we already do most of what is practical from your proposal.  We discussed freezing the state object, but state is already conceptually mutable (via setState) and we can't do a deep freeze for obvious reasons, so there isn't much gain from freezing here.

I'm going to close this out, because (assuming I understand your request correctly), what you are asking for is already implemented (at least the valuable/actionable parts).
