### ISSUE TITLE
Documentation : add a schema to illustrate the component lifecycle ?

### ISSUE THREAD

**Issue by fpetitit** [facebook/react#7183]
[Peter Beshai](https://twitter.com/pbesh) has created a very good cheatsheet to illustrate the component lifecycle :

![component lifecycle cheatsheet]
(https://pbs.twimg.com/media/Cj3vEl2WUAAfNnL.png:large)

It could be useful to have a similar schema on the React documentation page about components : 
https://facebook.github.io/react/docs/component-specs.html

**Comment by gaearon** [comment]
We updated [lifecycle docs](https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle) to be in order.

The schema looks cool, but I'm not sure we want to add it because Fiber (#6170) will make the order much less deterministic. So I'll close for now, but thanks for the suggestion.
