### ISSUE TITLE
NPM problem

### ISSUE THREAD

**Issue by manulourdes** [facebook/react#7196]
Hello i am new to react and i am testing it on a project but whne i do the npm install i get this
```

Leals-MacBook-Air:snapchat Manu$ npm install
SnapChat@0.0.1 /Users/Manu/Desktop/SnapChat
└── react@15.0.2 
npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
```

when i do the npm update 
```
Leals-MacBook-Air:snapchat Manu$ npm update
SnapChat@0.0.1 /Users/Manu/Desktop/SnapChat
└── react-native-camera@0.3.8  (git+https://github.com/lwansbrough/react-native-camera.git#d4d1aec581e085e9152e124b69b6aecb117b7378)

npm WARN react-addons-pure-render-mixin@15.2.0 requires a peer of react@^15.2.0 but none was installed.
```

i don't know what to do now about the react 15.2.0 on the package.json

**Comment by zpao** [comment]
I assume you're talking about https://github.com/VctrySam/SnapChat. If you have issues with the setup they have there you'll want to contact them.

Looks like the version dep for React should be ok and will pick up react@15.2.0, though perhaps react-native@0.26 is still looking for a lower version so that's getting used. `npm ls react` should tell you what versions are getting installed as a result of which dependencies.

**Comment by manulourdes** [comment]
Manu$ npm ls react
SnapChat@0.0.1 /Users/Manu/Desktop/SnapChat
└── react@15.0.2 
i only getting this? what should i do?

**Comment by keyanzhang** [comment]
Hey @manulourdes,

We use the React issue tracker for bugs in React. Since this is not a bug, I recommend you to open an issue on that repo or ask on StackOverflow instead -- the repo owner will have more knowledge about its dependencies. Thanks!
