### ISSUE TITLE
Not to expand 'border' style property

### ISSUE THREAD

**Issue by warpig9** [facebook/react#7243]
Current behaviour: passed-in style property
```
{
  border:'1px solid #ccc'
}
```
would be translated to
```
{
  border-top-color: #ccc,
  border-top-width: 1px,
  border-top-style: solid,
  ...the other border-xxx-xxx
}
```
I want the shorthand style property remained unexpanded as [Outlook 2007+ dose not support style properties like border-width, border-color etc.](https://www.campaignmonitor.com/css/) 

Also I found this expanding operation by React is done [here](react/src/renderers/dom/shared/CSSProperty.js) but it's not configurable.
Any ideas? Thanks in advanced!

**Comment by syranide** [comment]
It's expanded because of a bug in IE8 (9 also?) that breaks if you unset unexpanded properties. However, this should not affect rendering to static to markup (unless rendering in an old browser). So is this actually an issue for you?

On another note though, I guess the implementation is actually flawed and will cause checksum mismatch for SSR if resuming on a broken browser? cc @spicyj @jimfb

**Comment by warpig9** [comment]
Thx @syranide. I found the expanded border styles can partially works on some tags and it's no longer a problem for me.

**Comment by spicyj** [comment]
@syranide No, since it doesn't affect createMarkupForStyles.
