### ISSUE TITLE
ReactDOMComponentTree.precacheNode triggers render()?

### ISSUE THREAD

**Issue by tajo** [facebook/react#7289]
**React v15.2.0:**

I'm trying to optimize my application with server-side rendering (using `ReactDOMServer.renderToString`). The problem is that React in browser always triggers render() methods for all components even when the root `data-react-checksum` is the same. Since my page is quite big it results in a few seconds lag when JavaScript arrives (scrolling is frozen - interestingly, it happens in Chrome and Firefox but not in Safari).

I tried to track it down in the React source:
`ReactMarkupChecksum.canReuseMarkup` returns **true** so the mounting jumps to https://github.com/facebook/react/blob/ba9b985406ff56c2dea192b119328b6096895097/src/renderers/dom/client/ReactDOMComponentTree.js#L44 which looks good, but I'm still getting these initial rerenders.

Is this expected behavior? I can't find detailed explanation how this works. I could provide some working example.

Or do you have some tips how to prevent this initial lag?
Thank you.

**Comment by zpao** [comment]
In order to determine if the checksum is the same (as well as instantiate each component and set up internal state), we need to render the whole component tree again (even if we don't take any actions on the DOM). So having your `render` methods called on the client will always happen. It looks like when we will reuse the markup, we'll traverse the DOM to populate the cache.

I haven't looked closely to see if there are some optimizations we can make to do this differently so I'll defer to @spicyj who wrote most of this.

**Comment by spicyj** [comment]
It is expected that all of the components are rendered on the client, yes. That is the only way we can build up the proper data structures so that we can handle events and updates on the client side.
