### ISSUE TITLE
React and Polymer child not properly rendered in <content></content> of web component

### ISSUE THREAD

**Issue by mdedys** [facebook/react#7318]
**Do you want to request a _feature_ or report a _bug_?**
I am looking to report a bug/clarify if the following is a problem. I upgraded to React v15 and found that web components that rely on <content></content> to embed html elements are not working when used in a React Component.

Example: 

```
<template>
    <div id='my-wc'>
        <div id='inner'><content></content></div>
    </div>
</template>
```

Usage in React Component:

```
<div id='react-parent'>
    <my-wc><button>Test</button></my-wc>
</div>
```

**What is the current behavior?**

The resulting DOM looks as followings:

```
<div id='react-parent'>
     <my-wc>
          <div id='my-wc'>
                <div id='inner'></div>
                <button>Test</button>
          </div>
     </my-wc>
</div>
```

The problem is that the button is not getting correctly selected by the web component to be embed in place of `<content></content>`

I had problems getting React and Polymer working in JSFiddle together but I will try and create a demo of the problem and add it on.

**What is the expected behavior?**

In React v0.14.\* the DOM properly rendered and looked like the following:

The resulting DOM looks as followings:

```
<div id='react-parent'>
     <my-wc>
          <div id='my-wc'>
                <div id='inner'>
                    <button>Test</button>
                </div>
          </div>
     </my-wc>
</div>
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

This worked in React v0.14.\* but does not work as expected in React v15. The same polymer version is used for both versions of React.

**Comment by zpao** [comment]
@jimfb - I know you're busy with some other things, but any insight here?

**Comment by jimfb** [comment]
Without having looked into this issue, I assume it is because v0.14 used html markup, so this broke when we switched to createElement.  I expect that `content` is not watching for changes to children, so this was probably always broken/unsupported for updates anyway.

I think the `content` tag was removed from the spec and is deprecated anyway (https://developer.mozilla.org/en-US/docs/Web/API/HTMLContentElement).  Probably not worth the effort to support it.

**Comment by mdedys** [comment]
Thanks for the quick response. Didn't know <content> was deprecated since it is widely used in Polymer Elements.

**Comment by jimfb** [comment]
Looks like `content` may have been replaced by `slot`, which may have the same issue.  So maybe we'd want to fix this anyway.

@mdedys Any chance you are using the shady-dom instead of the shadow-dom? https://www.polymer-project.org/1.0/blog/shadydom

If you experience the same issue `slot` and a full ShadowDOM (not ShadyDOM), an jsfiddle would be the next step toward fixing this.

**Comment by jimfb** [comment]
We would also need to know if the children that get added to a `slot` can be modified via javascript, such that the shadow nodes get updated.

**Comment by mdedys** [comment]
Yes I am using shady-dom instead of the standard shadow-dom. I will experiment with ```slot```.

**Comment by jimfb** [comment]
React is not special-cased to support shady-dom, so you're likely to run into a lot of issues with it.  You should use the shadow-dom when using React.  We should probably warn when someone is using shady dom.  https://github.com/facebook/react/issues/7325

**Comment by Hasanul-Hoque2013** [comment]
Hasanul Hoque

**Comment by alhaag** [comment]
I have the same problem.
I changed the content tag to slot but it did not work.
