### ISSUE TITLE
Warn if someone is using the shady-dom with React

### ISSUE THREAD

**Issue by jimfb** [facebook/react#7325]
We should probably emit a warning if someone is using the shady-dom (instead of the shadow-dom) with React, since that will cause things to break subtly.

https://www.polymer-project.org/1.0/blog/shadydom

**Comment by Aweary** [comment]
I'd be happy to give this a try

**Comment by dantman** [comment]
React is supposed to support multiple renderers; I think it's reasonable for a renderer that extends the react-dom renderer to support ShadyDOM to exist. In fact, one already does:
https://github.com/jscissr/react-polymer

Whatever change is made to add a warning, please make sure it doesn't stop react-polymer from extending react-dom to support ShadyDOM or emit warnings in a way that react-polymer won't be able to negate (since the warnings would no longer be true).

**Comment by gaearon** [comment]
Fixed by https://github.com/facebook/react/pull/7911.

**Comment by gaearon** [comment]
@dantman Creating third party renderers was never advertised as a public API. If you want to be safe from changes in ReactDOM your best course of action is to completely fork it rather than substitute some modules. We don't guarantee we won't break third party renderers in the future, especially given that the new reconciler is being implemented in a completely different way.
