### ISSUE TITLE
Electron webView tag throws unknown property warnings

### ISSUE THREAD

**Issue by paulcbetts** [facebook/react#7357]
[Electron](https://github.com/electron/electron) adds a new HTML tag [`webview`](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md). Since this tag is registered via internal-to-Blink methods, it doesn't follow the standard Web Component rules (i.e. "name must have a `-`").

Is there a good place to add this tag's properties to the list of valid properties? I can do this PR if maintainers would be willing to approve it, we can gate this to Electron so that this won't affect web apps. Without this PR, it's impossible to use the `blinkFeatures` attribute in React

**Comment by MarshallOfSound** [comment]
FWIW even adding those props to an "allowed" object to stop the warnings didn't help the issue.  It appears as through React sets the props after the element is mounted which results in the props not being present when Electron reads them in.

As a hacky workaround I made https://github.com/MarshallOfSound/react-electron-web-view but I would much prefer to see some way to force a react components attributesto be set at mount time rather than slightly later with `setAttribute`

**Comment by gaearon** [comment]
It should "just work" in React 16 with support for unknown attributes.
If not please file a new issue with a minimal reproducing example.
