### ISSUE TITLE
Request: The Top-Level API should allow context passing

### ISSUE THREAD

**Issue by AlexPoirier1** [facebook/react#7367]
Hi,

I know the Context is flagged as an experimental feature hence why it is missing from the Top-Level API but I find myself having to pass context to a legacy-compatible component.

```
ReactDOM.render(React.createElement(DialogComponent, {id: id, component: this.component, childProps: this.props}), document.getElementById(id));
````

`React.createElement()` does not allow for context setting and this is causing me to 'hack' a context in these cases by doing something like 
````
componentWillMount: function() {
        this.context = this.props.context;
    },
````
in a mixin.

Is it something that could be looked into?

Thanks!!

**Comment by benjdlambert** [comment]
Personally, I think that the this would be best placed in `ReactDOM.render` rather than `ReactElement.createElement` as I don't should know anything about the context.  `ReactDOM.render`, deals with passing the context from parent to child, and it would duplicate the logic across the separation of concerns if it was part of the `ReactElement`.

So it would look something like:
```jsx
ReactDOM.render(
    <test />, 
    document.getElementById('container'), 
    { this: 'is my context' }
);
```

As an interim solution, what you have looks to be OK.  you could move this out into some form of higher-level container component/function though, and move the workaround out of your presentational layer and into a container.

That just takes the context and it acts as the first parent to pass the context down.

Something like:
```jsx
ReactDOM.render(
    wrapWithContext(MyComponent, { bob: 'says hello' })
);

//or

ReactDOM.render(
   <ContextWrap context={{ bob: 'says hello' }}>
        <MyComponent />
    </ContextWrap>
);
```

`/blam`

**Comment by jimfb** [comment]
@benjdlambert is exactly correct.  Context is not associated with elements, and therefore, createElement is not the right place for this.

The function that you are looking for is: `unstable_renderSubtreeIntoContainer` https://github.com/facebook/react/search?utf8=%E2%9C%93&q=unstable_renderSubtreeIntoContainer

But please don't rely on it, because we reserve the right to break it at any time and without notice.
