### ISSUE TITLE
How to transform stateless component into stateful harmlessly

### ISSUE THREAD

**Issue by stupidisum** [facebook/react#7401]
I want to request a *feature*.

Now, when I transform a stateless Component into stateful, it's awful to have all those git diffs.

I want a better way to write stateless and statefull Component which can be switched harmlessly with as less diffs as possible. 

Or maybe someone can recommend a better way to construct code?

**Comment by Kovensky** [comment]
Probably the biggest source of diffs is that the `render()` method is indented one stop deeper. Comparing the diffs using `git diff -w` (also supported by both github and gitlab as a `?w=1` query argument in pull requests) should reduce the noise to maybe 3 lines.

**Comment by zpao** [comment]
You can always write stateless components the same way you would write stateful ones today (extending the base class, createClass). In the future, there may be other ways to write stateful components that is more similar to stateless functional components.

Otherwise, we're not planning to optimize our feature sets around reducing git diffs. Commit history is always important so I encourage you to make meaningful commits but ultimately we want the code you read at any given point to be as readable as possible. You might need do a bit more work to trace blame on specific lines but you spend way more time reading your code than looking at history so that's the highest priority.
