### ISSUE TITLE
Freeze classes and defaultProps in DEV mode

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#7415]
To make compiler optimizations around classes and inlining defaultProps we need to know that they don't get mutated. This escape analysis can be difficult to do in a JS compiler so we should start enforce it so we don't have to rely on escape analysis.

``` js
const type = element.type;
if (typeof type === 'function' && !type.wasTaggedReactComponent) {
  Object.defineProperty(type, 'wasTaggedReactComponent', { value: true });
  Object.defineProperty(type, 'defaultProps', { writable: false, configurable: false });
  Object.defineProperty(type.prototype, 'render', { writable: false, configurable: false });
  Object.defineProperty(type.prototype, 'componentDidUpdate', { writable: false, configurable: false });
  ...
  Object.freeze(type);
  Object.freeze(type.defaultProps);
  Object.freeze(type.prototype);
}
```

We can also make them getters/setters so that we can make nice warning messages for sets. Although we should weigh this against slowing down DEV mode.

If a property exists it should preserve its enumerability. If a property doesn't exist it is still ok to attach a getter/setter as long as it is non-enumerable.

**Comment by jamesblight** [comment]
I'm keen to have a look at this.

**Comment by wbrefvem** [comment]
Not sure if @jamesblight is working on this, but I'd be willing to take a crack at it.

@sebmarkbage can you give me an idea where to start? Should this be happening somewhere in [ReactElementValidator](https://github.com/wbrefvem/react/blob/master/src/isomorphic/classic/element/ReactElementValidator.js)?

**Comment by sebmarkbage** [comment]
Yes. `ReactElementValidator` would probably be a good place for it.

Normally we try to not keep too renderer specific things in the element creation phase. Many other warnings don't kick in until `ReactCompositeComponent` but this seems like it would belong in `ReactElementValidator`.

**Comment by jamesblight** [comment]
@wbrefvem Thanks for the reminder, I had a go at this here https://github.com/jamesblight/react/commit/2807b7f2623b635b65802c1a7252d63bf98804df

It's implemented in the `createElement()` method of `ReactElementValidator`.
Non-static properties of the class are made immutable and `type` `type.defaultProps` and `type.prototype` are frozen as suggested.

Freezing `type.prototype` causes lots of tests to fail due to `bindAutoBindMethods()`. This tries to bind methods to the prototype which has already been frozen. 

Jest's `MockConstructor` is causing some tests to fail as well, probably due to attempting to mock the immutable class methods.

I played around with implementing this in the `createClass()` method of `ReactClass` and the tests will pass if `type.prototype` isn't frozen.

Have I interpreted this issue correctly? keen for any feedback.

**Comment by justingreenberg** [comment]
@jamesblight pretty much my exact experience... our solutions are virtually identical, even down to naming: https://github.com/facebook/react/compare/master...justingreenberg:feature/7415-freeze-type-defaultprops i left out the prototype bit for now and added a few assertions

**Comment by kevinSuttle** [comment]
Is this related to #7287?

**Comment by gaearon** [comment]
What's a class?
