### ISSUE TITLE
Can't set caret in setState callback in IE 10, v 15.3.0

### ISSUE THREAD

**Issue by igorushko** [facebook/react#7422]
I have controlled input, on v14 all works fine, on v15 in IE 10 when i press backspace setSelectionRange not works

v14 sample https://jsbin.com/niyejaseto/1/edit?html,js,output
v15 sample https://jsbin.com/hibovefuhe/1/edit?html,js,output

**Comment by syranide** [comment]
Without diving into it at all, I would recommend that you base your component on an uncontrolled input instead. Then you are in control of exact timings and behaviors. It's possible that React may play ball anyway but that's probably never going to be guaranteed. (If I understand your problem correctly)

**Comment by igorushko** [comment]
so... i need controlled input, it's blocks my migration to v15 :(

**Comment by syranide** [comment]
You can reimplement the controlled behavior yourself easily.

**Comment by browniefed** [comment]
@syranide looked into using an uncontrolled input and this is still happening.
Both with `shouldComponentUpdate` set to false, and using `defaultValue` instead of `value`, then `setSelectionRange` inside `componentWillReceiveProps`

Then I added `this.inputElement.addEventListener("change", this.onChange, false);` in `componentDidMount`and popped a debugger into `this.onChange` and `onChange` is only being called when the input blurs.

I'm not sure why but it seems like in latest React v15 that `onChange` even if things are uncontrolled inputs they do not fire `onChange`.
