### ISSUE TITLE
Write documentation for `react-test-renderer`

### ISSUE THREAD

**Issue by KnutHelland** [facebook/react#7431]
This is the first day I've used `react-test-renderer`, and I've already stumbled upon three problems:

* The injectEnvironment called twice bug #7386 
* The fact that refs is just `null` when rendered with `react-test-renderer` #7371
* When setting a ref on a dom element, React erroneously warns about stateless function components cannot be given refs. (also probably related to #7371)

`react-test-renderer` is going to be shipped with `create-react-app` very soon (?) (it's in `react-test-renderer@0.3.0-alpha`), so I think it deserves some more comprehensive documentation as soon as possible. With at least some troubleshooting bulletpoints and some text about how one are supposed to do with refs.

I sometimes use refs from `componentDidMount`. For example for setting focus on an input `this.refs.input.focus()`. But such code will fail with `cannot call focus() on undefined`. Should we always test if a ref isn't undefined before using them? Or do you have some plans for `react-test-renderer` in near future that will solve this issue in some way?

**Comment by LouisStAmour** [comment]
I'm hitting the `injectEnvironment` called twice bug with `react-bootstrap` and considering my options. 

But I suspect some of these bugs stem more from what's now considered legacy ways of writing react code. For instance, the refs thing seems to work for me when I'm using ref as a callback rather than a string: https://facebook.github.io/react/docs/more-about-refs.html

I went through my codebase with https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-string-refs.md and fixed all the warnings, so I didn't see this issue.

Not sure if there's an easier way to do this, but I even use refs callbacks within my test to get a reference to the node I just rendered...
```
const component = renderer.create(
            <MyComponent ref={(x)=> node = x} />
        );
```
which can then be accessed using `node` though I'm still working out if it's useful to me or not. But #7386 hurts and the only thought I've had since as a workaround would be to mock the third party library.

**Comment by gaearon** [comment]
Please see my replies:

https://github.com/facebook/react/issues/7386#issuecomment-238091398
https://github.com/facebook/react/issues/7371#issuecomment-238091530

**Comment by LouisStAmour** [comment]
The inject bug is slightly more complicated than https://github.com/facebook/react/issues/7386#issuecomment-238091398, @gaearon -- I've turned off auto-mocking entirely, and it still happens. Here's some more detail on what's been done/suggested: https://github.com/facebook/jest/issues/1353#issuecomment-238092763

In other news, I switched from `react-test-render` to Enzyme's [Full Rendering API](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md) and it's working flawlessly. Like most things with react, it's probably running less efficiently and doesn't support auto-mocking perhaps, but ... it's good enough for me. I'm using `mount` from Enzyme instead of `renderer.create` and I still get the benefit of Jest's snapshots with `.html()` instead of `.toJSON()`. Yay.

**Comment by gaearon** [comment]
> I've turned off auto-mocking entirely, and it still happens. 

Sorry I wasn’t clear. I’m saying **the solution** to this is to **mock** `react-dom`. This has no relation to automocking. You can turn it off (that’s what I’d recommend), but you still need to mock `react-dom` with an empty mock to get snapshot testing working with `react-dom` references.

**Comment by gaearon** [comment]
Let's track this in #8060.
