### ISSUE TITLE
why not add catch block in function _renderValidatedComponent?

### ISSUE THREAD

**Issue by lianpen** [facebook/react#7439]
like this:

```js
  _renderValidatedComponent: function () {
    var renderedComponent;
    ReactCurrentOwner.current = this;
    try {
      renderedComponent = this._renderValidatedComponentWithoutOwnerOrContext();
    } catch(error) {
		console.log(error);
		 alert(error);
		
	} finally {
      ReactCurrentOwner.current = null;
    }
    !(
    // TODO: An `isValidNode` function would probably be more appropriate
    renderedComponent === null || renderedComponent === false || ReactElement.isValidElement(renderedComponent)) ? "development" !== 'production' ? invariant(false, '%s.render(): A valid ReactComponent must be returned. You may have ' + 'returned undefined, an array or some other invalid object.', this.getName() || 'ReactCompositeComponent') : invariant(false) : undefined;
    return renderedComponent;
  },
```

**Comment by Aweary** [comment]
Hey @lianpen, as far as I know the `try` block is not intended to actually catch and handle errors. Wrapping the `_renderValidatedComponentWithoutOwnerOrContext` call in a `try` block lets use also add `finally` block that we *know* will run even if an error does occur.

That means that `ReactCurrentOwner.current` will always be set to `null`, even if the render errors out. We don't catch errors here since we want them to bubble up and be handled elsewhere.

For future reference, we use this repo to track actual issues with React. If you have a question about usage or implementation, you'd be better served using something like StackOverflow.

**Comment by gaearon** [comment]
In the future we might provide a way to handle rendering errors. However such solution would need to put the `catch` behavior into the hands of the developer rather than just log the error. You can track this issue if you are interested: #2461.
