### ISSUE TITLE
React 15.2+ shows warnings for unknown props on root level components

### ISSUE THREAD

**Issue by mattsfrey** [facebook/react#7445]
Probably not a bug but a very unpleasant change for many

When passing props to root components i.e. div's, a's etc, if it is an unknown prop there is now a large stack trace displayed. For those of us using cljs libs such as om/reagent, we frequently leverage passing props around with &args and (into :div ...) quite a bit to write components that can take open ended markup/content. It would be very painful to go back and refactor many of our components to not do this, and as it is now with 15.2+ we have to deal with massive amounts of obnoxious stack traces that make development extremely unpleasant. 

![screen shot 2016-08-08 at 2 15 57 pm](https://cloud.githubusercontent.com/assets/2801653/17495155/28096928-5d75-11e6-9679-9c921cb657ea.png)

Not to show warnings

15.1 and prior did not display this behavior

**Comment by gaearon** [comment]
In the future versions of React the plan is to just pass attributes through. This has been a long requested feature.

This warning just warns you about this behavior. If you're okay with things like `iconOffset="[object Object]` you can safely ignore that warning. We intend to add a different UI for warnings soon so they will be easier to ignore. But I'm not sure if you'd be OK with "weird" attributes on DOM node so maybe refactoring components to "consume" props instead of blindly passing them down is worthwhile.

**Comment by mattsfrey** [comment]
Given that course of action, yes it seems like we'll have no choice but to refactor at some point. Thanks for the speedy reply.

**Comment by gaearon** [comment]
Yeah, I can understand the frustration but that’s the only (as far as I know) reasonable way forward to solve issues like https://github.com/facebook/react/issues/6798 and https://github.com/facebook/react/issues/140.

**Comment by ashleelynn1202** [comment]
I apologize. I just got done mowing the yard for my grandmother. I wasn't able to pay proper attention to what I was doing.
