### ISSUE TITLE
alternatives to dangerouslySetInnerHTML methods

### ISSUE THREAD

**Issue by demoritik** [facebook/react#7462]
Hi. I have read alot of warnings about dangerouslySetInnerHTML api but what react can suggest instead? on official page https://facebook.github.io/react/docs/jsx-gotchas.html there are examples with simple strings like <div>First &middot; Second</div> . But i don't know how to implement this methods on such wide spread cases like displaying text with inner markup from database like 
`<p><span>text0</span></p>` 
or even more complicated. In my case this is a text created from  tinyMCE editor. How can i display it properly without dangerouslySetInnerHTML ?
p.s. i saw different plugins like htmlparser2 or similar but they are not much popular (stars count is less then 100)

**Comment by vjeux** [comment]
If you have raw html coming from a trusted source, then dangerouslySetInnerHTML is the correct way to render it. The method is named "dangerously" because if the markup contains malicious code like `<img src=x onerror=alert()>` then it can run arbitrary JavaScript code in the context of the logged in user.

**Comment by demoritik** [comment]
ok. i got it. thank u
