### ISSUE TITLE
Chromium fails on inline style 'display'

### ISSUE THREAD

**Issue by sonsyphon** [facebook/react#7521]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using inline style for display:'(relative|absolute|flex|...)' it fails to add it to the DOM.
Every attribute is added except display. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React: 15.1.0
Chromium: 51.0.2704.49
OS: ubuntu 16.04 (64bit)

**Comment by Aweary** [comment]
Hey @sonsyphon, thanks for the report. Can you share a reproducible test case? You can use [this JSFiddle](https://jsfiddle.net/reactjs/69z2wepo/) as a starting point. Can you also test using the latest version of React, which is 15.3.0?

I tested using this [forked JSFiddle](https://jsfiddle.net/2gkaocbt/) in the latest Chromium build for OS X and it worked as expected.

**Comment by alexzherdev** [comment]
FWIW 'relative' and 'absolute' are for the position property, not display. Not sure if it matters here.

**Comment by Aweary** [comment]
Ohh, great catch @alexeyraspopov! That's almost certainly the issue. If you tried to do `display: relative` that would be an invalid value for `display` and subseqently not render. @sonsyphon  check the difference between [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) and [display](https://developer.mozilla.org/en-US/docs/Web/CSS/display)

I'm going to close this for now, since I'm pretty certain this is just a usage error. If not, we can revisit this 👍
