### ISSUE TITLE
dangerouslySetInnerHTML and large amounts of markup

### ISSUE THREAD

**Issue by theduke** [facebook/react#7528]
I have to display a large amount of markup generated on the server inside a Component. 

It's A LOT of markup (around 10.000 `<li><a></a></li>`), and dangerouslySetInnerHTML takes a long time. It stalls the page for several seconds, and sometimes crashes Chrome.

I assume that this happens because react parses the HTML and creates elements for everything.

Is there a way around this behaviour?
(ps: I also tried creating the `<li>` s as you normally would. that takes way to long as well)

**Comment by theduke** [comment]
Disregard, please.

It seems that Chrome currently is just very slow when setting a large amount of content with .innerHTML.

**Comment by buildbreakdo** [comment]
@theduke Likely should be lazy loading instead of pushing 10k list items on a page, user can't process 10k items at a time (studies suggest 4-7 CHUNKS of info at a time).

For comparisons sake, Facebook easily has 10k news feed items they could load when you log in but they only push a few at a time for sake of bandwidth, cpu cycles, and the fact that users would likely never reach past 30 items anyway (most users on google never go past page 3 which is 30 items).
