### ISSUE TITLE
I'm getting 100s of new inapplicable prop warnings; please make this less painful for developers

### ISSUE THREAD

**Issue by jedwards1211** [facebook/react#7604]
Passing userland, non-applicable props to `<div>s`, `<button>s`, <input>s`, etc. is already widespread in my large codebase because:

- I have a lot of components that add on various properties (e.g. for Bootstrap) but I want to pass the rest of the props through in case any are applicable
- I saw no reason to waste CPU time/memory/my own time cloning the props and deleting the component-specific props...until now.

(Example code at the bottom of this post)

I am trying hard to contain my anger about this; now I have to painstakingly change 100s of components to get rid of the slew of new React warnings about inapplicable props!  Did the React team really not expect people to write components this way?  I certainly don't remember seeing thorough explanations why we shouldn't do this in the documentation; even the [Unknown Prop Warning page](https://facebook.github.io/react/warnings/unknown-prop.html) says "You should ensure that your DOM elements do not have spurious props floating around" **without any justification**.

This is unkind to developers.  So, how about providing some kind of global switch or flag prop that makes DOM elements delete all of the inapplicable props?  Or a codemod that wraps all object spread props to DOM elements in a filter function?

Example:
```jsx
/* @flow */

import React, {Component} from 'react'
import classNames from 'classnames'
import addClass from '../wrappers/addClass'
import {getContextClass, getContextContent, getShadeClass} from './bootstrapPropUtils'

import './Alert.sass'

import {errorMessage} from '../utils/reactErrorUtils'

type Props = {
  contextClass?: 'alarm' | 'error' | 'danger' | 'warning' | 'info' | 'success' | 'ok',
  alarm?: ?any,
  error?: ?any,
  danger?: ?any,
  warning?: ?any,
  info?: ?any,
  success?: ?any,
  ok?: ?any,
  shade?: 'darker' | 'brighter',
  darker?: boolean,
  brighter?: boolean,
  className?: string,
  children?: any,
};

export default class Alert extends Component<void, Props, void> {
  static Link = addClass('a', 'alert-link');
  render(): React.Element<any> {
    let {className, children} = this.props
    let contextClass = getContextClass(this.props, 'type')
    let shadeClass = getShadeClass(this.props)
    let content = getContextContent(this.props)

    if (content && (contextClass === 'danger' || contextClass === 'warning' || content instanceof Error)) {
      content = errorMessage(content)
    }

    className = classNames(className, 'alert', contextClass && ('alert-' + contextClass), shadeClass)

    return <div role="alert" {...this.props} className={className}>
      {children}
      {content}
    </div>
  }
```

**Comment by jimfb** [comment]
The old gist included a justification (https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b#gistcomment-1816271).  Unfortunately, comments didn't get copied over when we transitioned to the self-hosted warning pages.

We are not providing a switch/wrapper that strips unknown props, because the whole point is to get rid of the whitelist.  We understand that the React community is large, and we work hard to minimize the burden of migrations for the community.  However, our philosophy is to continuously improve React, rather than letting it stagnate due to legacy codebases.  It is a balance.  We always consider the community burden, and do what we honestly believe is best in the long run.

FWIW, there is an open-source wrapper that may do what you want (https://github.com/tyv/pick-react-known-prop).  For the record, we do NOT recommend this solution; we recommend that you follow one of the patterns we documented on the warning page.  However, if you are looking for a simple shortcut, some people have found it useful, and it appears to match what you were asking for.

To the extent that this is a request to suppress warnings, tracking as https://github.com/facebook/react/issues/6683

**Comment by jimfb** [comment]
Copying the justification here for reference:
 > Historically, React has maintained a whitelist of all valid DOM attributes, and we would strip unrecognized attributes.  This approach has a couple major downsides:
 * Performance: It means we must do a check for every prop on every DOM element, to sanity check that the prop is valid, and strip the prop if it is not legal.  This is silly, because the majority of elements are completely safe (no illegal attributes) and thus the checks are just wasted CPU cycles.
 * The old technique forced us to maintain a huge whitelist of all possible DOM attributes.  This is a pain to maintain, but more importantly, if we accidentally miss one or browser vendors add a new one, it means that prop can't be used until we update our whitelist
 * The old technique is less flexible because it is impossible to render a non-standard attribute.  While rendering non-standard attributes is not recommended (you should use a `data-` attribute instead), sometimes there are situations/frameworks that require it.  It sucks that React previously couldn't support it.

**Comment by jedwards1211** [comment]
@jimfb But why didn't you guys just get rid of the whitelist entirely and render every single prop, whether legal or not?  With that approach couldn't you just warn for unsafe props and provide some alternative way to use unsafe props that doesn't warn?

**Comment by jedwards1211** [comment]
@jimfb and what's so non-recommendable about `react-known-prop`?

**Comment by jimfb** [comment]
> But why didn't you guys just get rid of the whitelist entirely and render every single prop, whether legal or not?

We will.  But we need to warn for a version because otherwise it is too hard for engineers to figure out where the invalid props are being introduced, in order to clean them up.

 > It would not have any problems you mentioned so I assume you're worried about safety. But for safety couldn't you just warn if there are unsafe props, and provide some alternative way to pass unsafe props that doesn't warn?

Not sure I understand the question, but I'll throw some darts and see what sticks...  Passing an unexpected prop to a component is an indication of a bug.  More influential in our decision, however, was the fact that people have massive legacy codebases that blindly forward props (like yours does), and the majority of those people (though it sounds like you may not be one of them) are of the opinion that spewing props into the DOM is a terrible thing; sufficiently bad that we need to provide a migration plan for users so they can clean up their components.  It is too difficult to fix without proper warnings, which is why we warn.  Ultimately, we believe your code will be better and more maintainable if you are explicit and pass only the props that you intend to render and have an effect.

 > what's so non-recommendable about react-known-prop?

I'm less oppose to it than the rest of the team, so maybe I'll let one of them chime in here.  But I think the main arguments are that it is less explicit (being explicit makes your code more maintainable) and that it requires maintaining a whitelist (which will inevitably go out of date).  If it works for you, and that's the solution you want to use, it's probably fine (IMO) - that's why I mentioned it.

**Comment by jedwards1211** [comment]
`react-known-prop` could of course provide an API for users to whitelist additional props in case it falls behind temporarily, so I really don't see it as such a big problem.

I never thought that spewing random props into the DOM is okay; in my mind, React DOM elements behaved just like custom Components: you could add any additional, inapplicabe properties you wanted and those properties would just get ignored, and indeed that's how it was until now.
