### ISSUE TITLE
browser.js:49Warning: [react-router] `Router` no longer defaults the history prop to hash history. Please use the `hashHistory` singleton instead. http://tiny.cc/router-defaulthistory

### ISSUE THREAD

**Issue by ITtong** [facebook/react#7627]
browser.js:49Warning: [react-router] `Router` no longer defaults the history prop to hash history. Please use the `hashHistory` singleton instead. http://tiny.cc/router-defaulthistory

控制台报错，任何尝试都没有解决，已经换长hashHistory，还是不行，我的代码如下：
![d2843af3-b65a-1085-68f8-bb81e24c36dc](https://cloud.githubusercontent.com/assets/19646825/18153211/8517ee34-702e-11e6-8694-ef2e352a18cf.png)
![0394c02c-02a5-8fcb-24ad-53aa9b73aa3d](https://cloud.githubusercontent.com/assets/19646825/18153213/8ab3af7c-702e-11e6-9629-fcc95af5425c.png)
求大神告知！

**Comment by Aweary** [comment]
react-router is not a part of React itself, please direct any issues you have to https://github.com/reactjs/react-router or, better yet, try posting a question on StackOverflow with [the react-router tag](http://stackoverflow.com/questions/tagged/react-router) since it seems to be a usage issue. Thanks!

**Comment by ITtong** [comment]
@Aweary ok！it‘s my mistake. thank you.
