### ISSUE TITLE
Unable to select disabled elements with the :disabled psuedo selector in CSS.

### ISSUE THREAD

**Issue by chrismiceli** [facebook/react#7643]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unable to select disabled form elements in CSS via :disabled psuedo selector. Currently I have to use the disabled attribute selector.

I am creating the disabled form element in JSX as such:
<label disabled><input type='checkbox' disabled/></label>

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
https://jsfiddle.net/69z2wepo/54946/

**What is the expected behavior?**
I expect to be able to select disabled elements via the css :disabled psuedo selector

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I am new to React and have not tested multiple versions against this issue. I have verified it doesn't work on versions:
https://npmcdn.com/react@latest/dist/react-with-addons.js

**Comment by Aweary** [comment]
Thanks for the issue @chrismiceli. This is actually expected behavior and not related to React; the `:disabled`  psuedo-class is for input elements, not `<label>`s. Check out [this example with the same behavior](https://jsfiddle.net/o4x3y4p9/1/) without React.

[Here's a working example](https://jsfiddle.net/yz2ak3z5/) forked from yours that uses the CSS sibling selector to style any `<label />` that is an adjacent sibling of a disabled `<input>`

**Comment by chrismiceli** [comment]
Thanks, I should've tried that before opening an issue. It is just counter intuitive so I did not expect it.
