### ISSUE TITLE
unwanted "focus" event triggered after "blur"

### ISSUE THREAD

**Issue by dongpei021** [facebook/react#7665]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After "blur" event triggered in componentWillUpdate, unwanted "focus" event triggered after render().

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
https://jsfiddle.net/69z2wepo/55308/

**What is the expected behavior?**
When input box is focused and a key is pressed, input box should blur. But it doesn't.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.3.1

**Comment by zpao** [comment]
`componentWillUpdate` is not a good time to touch the DOM yourself (unless its a section you fully own, which isn't the case here). It's a bit tricky since that's in the middle of the update process and React isn't finished doing its work. Part of that work is restoring focus. So while you are blurring, React then restores focus when its done.

You can use `componentDidUpdate` and blur there, which will work - that's after React has finished updating.

I'm going to close out for now and say that's the only way we want to support this, otherwise we're dealing with interrupting updates. Hope that clears it up!
