### ISSUE TITLE
Class Name Manipulation is not native

### ISSUE THREAD

**Issue by graft** [facebook/react#7709]
This page: https://facebook.github.io/react/docs/class-name-manipulation.html currently suggests an external dependency in npm for what should be provided by React. Can we, instead, include these 10 lines of code into React and eliminate this external dependency?

**Comment by Aweary** [comment]
Thanks for the issue @graft! This used to be included in React as `React.addons.classSet` but was deprecated and removed, see https://github.com/facebook/react/issues/2910 for some discussion. Moving it back into the codebase would likely be confusing and keeping `className` monomorphic has its advantages.

I'm going to close this out, as it's unlikely that we'd want to do this, but feel free to ask any clarifying questions here! 👍

**Comment by gaearon** [comment]
Just because something is 10 lines, doesn’t mean hiding it behind a dependency is a bad idea.

We’d like to keep React itself focused on what React *does*. Utilities like `classnames` often change, come and go in popularity, change APIs, etc. We’re happy to point to the one people seem to like the most, but this doesn’t mean it’s somehow “best” for React. As mentioned by @Aweary, we tried that approach before, and it lead to stagnation for these utilities because we don’t use them ourselves, and so can’t meaningfully drive their design, improve them. Their release granularity also doesn’t match that of React.

This is best handled by the community, so that’s why we link to a community package.
