### ISSUE TITLE
Can't isomorphically check propTypes in react-dom-stream SSR without warnings in React 15.2+

### ISSUE THREAD

**Issue by jedwards1211** [facebook/react#7765]
https://github.com/aickin/react-dom-stream/issues/22

`react-dom-stream` helpfully checks `propTypes` while rendering static HTML to a stream.  But of  course React 15.2+ warns (in this case on a user `Html` `Component` with `propTypes.head`):

> Warning: You are manually calling a React.PropTypes validation function for the head prop on Html. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

The page at that link advises 3rd party libraries to use external `PropType` libraries, but that won't work in this case because `react-dom-stream` is trying to call the `propTypes` the user has put on their components, rather than providing helpers like the 3rd party libraries the author of that page seems to be considering (e.g. `ImmutablePropTypes`).  To prevent these errors, the user would have to remove the `propTypes` on their components or replace the usages of `React.PropTypes` in their own code with some other library.  If they were using 3rd party components that declare `propTypes`, they would be out of luck.

Is there an intended solution to this or was this conflict unanticipated?

**Comment by gaearon** [comment]
The warning is a false positive, you can safely ignore it.

It occurs because `react-dom-stream` is a fork of `react-dom@0.14.x` but you’re using `react@15.x` for defining components. So they’re not quite compatible.

There are a few solutions but they’re not on our side:

* Update `react-dom-stream` to fork of a version of React more recent than `15.3.0`.
* Try to cherry-pick https://github.com/facebook/react/pull/7219 into `react-dom-stream`.
* Ignore the warning until `react@16` where it’s going to be removed.
* Stay on `react` < 15.3.x until `react@16` ships.

I hope this helps! `react-dom-stream` is a cool experiment but we don’t officially provide support for it, and things might break once in a while if somebody doesn’t keep it up to date.

**Comment by jedwards1211** [comment]
Okay, I was actually concerned that `react@16` would break `react-dom-stream` entirely, but as long as it remains possible to call the validators in dev mode there's no problem.

I'm confused what you mean about cherry-picking #7219 though?  I was expecting some kind of code change, not a documentation change.

Thanks!

**Comment by gaearon** [comment]
Oops sorry. I meant https://github.com/facebook/react/issues/7132.

**Comment by gaearon** [comment]
>Okay, I was actually concerned that react@16 would break react-dom-stream entirely, but as long as it remains possible to call the validators in dev mode there's no problem.

The warning exists to make it clear for people who *call PropTypes manually* (e.g. to validate their API responses, or for other obscure reasons) that this won’t work in production in 16. We warn in development because that’s where people will see the warnings, as almost nobody looks into production warning logs. But PropTypes will keep working in development for sure, even in 16.
