### ISSUE TITLE
Input elements should not switch from uncontrolled to controlled when disabled / readonly

### ISSUE THREAD

**Issue by Bonuspunkt** [facebook/react#7767]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Input Elements that are readOnly / disabled which are updated with a value after the inital render produce a warning.
*Child is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.*

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://jsfiddle.net/tadgvzna/

**What is the expected behavior?**
no warnings

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
not browser related. its behaving correctly. i just got a warning in my dev console

**Comment by syranide** [comment]
cc @jimfb

**Comment by troydemonbreun** [comment]
@jimfb Is this an acceptable fix? (tests to follow)

**Comment by jimfb** [comment]
At a higher level, I'm not even convinced that the existing behavior is wrong.  It actually seems perfectly consistent to me.  You can fix the fiddle by adding an initial state, as demonstrated here: https://jsfiddle.net/qnea33eg/

The controlledness of a component is defined by the value prop.  If you're using controlled components, the value prop should be specified for the lifetime of the component (even if the value is just the empty string).

I understand why a user might conceptually feel like it would be ok to not set a value on a disabled component (since, in a sense, the browser won't be able to modify it and therefore feels like it isn't controlled by the browser), but I think we want to keep the semantics simple and defined by the value prop.

For this reason, I'm going to close out this issue.  We can continue the discussion in this thread, and reopen if our thinking changes.

**Comment by syranide** [comment]
@jimfb 👍 I thought `value` was actually defined initially.
