### ISSUE TITLE
Unable to add css to react app.

### ISSUE THREAD

**Issue by gauravbhusare** [facebook/react#7860]
I am making a react js app. I am trying to add bootstrap css to my app. following is my code.

webpack.config.js

            var webpack = require('webpack'),
            contextPath = process.cwd();

            module.exports = {
              devtool: 'inline-source-map',
              entry: [
                'webpack-hot-middleware/client',
                './client/client.js'
              ],
              output: {
                path: contextPath + '/dist',
                filename: 'bundle.js',
                publicPath: '/'
              },
              plugins: [
                new webpack.optimize.OccurrenceOrderPlugin(),
                new webpack.HotModuleReplacementPlugin(),
                new webpack.NoErrorsPlugin(),
                new webpack.optimize.UglifyJsPlugin({
                  compress: {warnings: false}
                })
              ],
              module: {
                loaders: [
                  {
                    test: /\.js$/,
                    loader: 'babel-loader',
                    exclude: /node_modules/,
                    query: {
                      presets: ['react', 'es2015', 'react-hmre']
                    }
                  },
                  { test: /\.less$/, loader: 'style!css!less' },
                        { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
                        { test: /\.(jpe|jpg|woff|woff2|eot|ttf|svg)(\?.*$|$)/, loaders: ["file-loader"] },
                ]
              }
            }

index.html

                                <!DOCTYPE html>
				<html>
				<head>
					<meta charset="utf-8">
					<meta name="viewport" content="width=device-width">
					<title>React.js</title>
					<link rel="stylesheet" type="text/css" href="./css/bootstrap.min.css">
				</head>
				<body>
					<div id="react">Learn React</div>
					<script src="bundle.js"></script>
				</body>
				</html>

I checked in network request then my app is getting the file. But styles are not getting applied to my components. Following is my component.

			import React, { Component } from 'react';

			export default class RegistrationForm extends Component {
				constructor(props){
					super(props)
					this.state={
						name : ""
					}
				}
				render(){
					return(
							<div className="col-md-8">
								<form className="form-horizontal">
									<input type="text" placeholder="Enter Name Here" onchange={(text)=>this.setState({name:text})} />
								</form>
							</div>
						);
				}
			}

Please help me solving this issue.

**Comment by gaearon** [comment]
Hi!

Unfortunately this doesn't look like an issue related to React itself, but more like something is wrong with your build setup. It is hard to guess what exactly from these snippets.

We use the bug tracker for bugs in React so I will have to close this issue. If you need help I would encourage you to create and publish a project reproducing your issue so that you can link to it here, on StackOverflow, or from other forums, and hopefully somebody can take a look.

By the way we also offer an [officially supported build setup for React apps](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html). If you have the same problem with it, file an issue there and we will help you.
