### ISSUE TITLE
DOM contents not ready after first update in incognito/private window.

### ISSUE THREAD

**Issue by kjs3** [facebook/react#7889]
**Bug**

**Current behavior:**

I am attempting to load data from an API, display, and then scroll to a URL fragment deep in the document. Window only partially scrolls.

This may have more to do with browser behavior but I can't figure out how to reliably wait for content to be painted before scrolling it into view on the first attempt.

**Here's an example showing the issue:**
1. open a _new_ incognito (Chrome) or private (Firefox) window.
2. paste (or type, sorry FF) this URL - https://jsbin.com/pecuxi/8/edit?js,console,output
- data will be loaded from iTunes and saved to state
- `render` is triggered
- `componentDidUpdate` is triggered
- `window.requestAnimationFrame` is used to let DOM painting occur
- DOM node deep in document is queried and attempted to scroll into view (correct node has a red background)

I've never seen this work with a fresh incognito/private window.

[Here's an issue](https://github.com/facebook/react/issues/2659) where using `requestAnimationFrame` is suggested.
[Here is a SO answer with discussion about this.](http://stackoverflow.com/a/28748160/184532)

**What is the expected behavior?**
DOM node scrolled into view

**Versions of React:** `15.1+`

**Browsers / OS:** `Mac OS X 10.11.6`

**Did not work with previous versions of React**

**Comment by syranide** [comment]
Have you deferred `ReactDOM.render` until `DOMContentLoaded` (may or may not affect)? Otherwise it should work as is AFAIK, when `componentDidMount` is called everything has been flushed to DOM and there's nothing left for React to do. So intuitively it should work. However, you have to remember that images may not have been downloaded then and later increase the size of the rows, throwing it off. Same applies to webfonts. If stylesheets are loaded after your script then that will also throw off measurements.

From the brief flickering I see in your fiddle it seems that it has to do with images not being pre-sized and thus throw off the initial measurements when they begin to load.

**Comment by gaearon** [comment]
The above sounds like the right explanation to me.
