### ISSUE TITLE
React should match w3c syntax for 'autofocus'

### ISSUE THREAD

**Issue by JulianNorton** [facebook/react#7981]
# React should match the w3c syntax for 'autofocus'
Autofocus is an attribute that auto focuses inputs, forms, or buttons. **Autofocus should not have the 'true' or 'false' attributes, nor camel case.**

#### The following are valid, equivalent and true [w3c]
```
<input type="text" autofocus />
<input type="text" autofocus="" />
<input type="text" autofocus="autofocus" />
<input type="text" autofocus="AuToFoCuS" />
```

#### The following are invalid [w3c]
```
<input type="text" autofocus="0" />
<input type="text" autofocus="1" />
<input type="text" autofocus="false" />
<input type="text" autofocus="true" />
```

> A number of attributes are boolean attributes. **The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.**

> If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.
[w3c source](https://html.spec.whatwg.org/multipage/forms.html#attr-fe-autofocus)

## Recommendation
**Update syntax from `autoFocus={true}` to `autofocus` or `autofocus='autofocus'`**
Here's an example of what should be considered valid: https://jsfiddle.net/qfrp4az7/1/

`react: 15.3.2`

**Comment by syranide** [comment]
React runs in JavaScript and can thus considered to naturally map to the corresponding HTMLDOM JS-properties, not the HTML-attributes. `autofocus="autofocus"` is an artifact of HTML attributes, the HTMLDOM JS-property is a boolean. Also, HTML has a lot of this quirky stuff because of its simplistic design and legacy, the same limitations and legacy don't exist for JS and so intentionally bringing the quirks along seems counter-productive.

Note; this is the behavior of the official **ReactDOM** module which is a renderer for React, so it's naturally going to be opinionated.

**Comment by yasirunilan** [comment]
can I work on this?

**Comment by JulianNorton** [comment]
The disabled attribute works as expected in React and matches the w3c. Autofocus should work the same.

```
<input
    type="text"
    placeholder="placeholder"
    disabled
/>
```

https://jsfiddle.net/2drw2gds/2/

**Comment by Aweary** [comment]
These props are not meant to be a 1:1 mapping to HTML attributes. That is why we use the camel-cased version, to make it clear that these are JavaScript properties and not HTML attributes.

> All DOM properties and attributes (including event handlers) should be camelCased to be consistent with standard JavaScript style. We intentionally break with the spec here since the spec is inconsistent.

- [React Docs - Dom Differences](https://facebook.github.io/react/docs/dom-differences.html)

When you have something like:

```jsx
<input type="text" autoFocus={true} />
```

This corresponds more directly to
```jsx
var input = document.createElement('input');
input.autofocus = true;
```

and not:

```jsx
var input = document.createElement('input');
input.setAttribute('autofocus', true);
```

> The disabled attribute works as expected in React and matches the w3c. Autofocus should work the same.

It does work the same, you just need to use the camel-cased attribute name. `<input autoFocus />`  works fine since attributes without values default to `true`.

Since we're explicitly and intentionally breaking from the spec here, I'm going to close this out, but we really appreciate the issue!

**Comment by JulianNorton** [comment]
It's weird that `autoFocus` is camel-case but it's a single word. It's not `placeHolder`. 

<img width="512" alt="screen shot 2016-10-18 at 1 01 52 pm" src="https://cloud.githubusercontent.com/assets/2412992/19488017/0e1f03d8-9533-11e6-8e81-1ac13dfe4090.png">

**Comment by Aweary** [comment]
It's more about consistency than semantics. Making it camel-case makes it consistent with `autoComplete`, `autoPlay`,  `autoCorrect`, and `autoCapitalize` which I think is less confusing.

Either way, at this point it wouldn't be worth introducing a breaking change like this just for semantical reasons.

**Comment by JulianNorton** [comment]
It wouldn't have to be a breaking change, it could just be updated to allow both ways.

**Comment by Aweary** [comment]
That would introduce a new inconsistency since we don't support that for any other attributes currently.
