### ISSUE TITLE
issue with redbox-react

### ISSUE THREAD

**Issue by szare** [facebook/react#7985]
I'm testing react version **15.4.0-rc.3** on one of my projects and during installing packages (which worked with previous version of react), the **redbox-react** has an issue with react-DOM:

ERROR in ./~/redbox-react/~/react-dom/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactDOM' in....

**Comment by gaearon** [comment]
When you update to RCs you need to update both react and react-dom package.

Judging by the error message, redbox-react has its own (old) copy of react-dom in its node_modules. Delete it, and the issue will be fixed. 

You should also bring it up with its maintainers: react-dom needs to be in its peerDependencies rather than dependencies. 

I'm closing because it is not something we can fix in React itself but I hope it helps.

**Comment by gaearon** [comment]
This should be fixed with `redbox-react@1.3.2`. You will need to delete `node_modules/redbox-react/node_modules/react-dom` if it's there after updating.

**Comment by szare** [comment]
This issue solved by updating to redbox-react@1.3.2 .
Thank you gaearon.
