### ISSUE TITLE
Variable refers to new Date() can not be a child element.

### ISSUE THREAD

**Issue by krave1986** [facebook/react#7988]
I am following a code snippet from the book `React Quickly`.
And I can not run the code after being compiled via babel.
My code is like:
```
class DateTimeNow extends React.Component{
	render(){
		let dateTimeNow = new Date();
		return <span>Current date and time is {dateTimeNow}.</span>;
	}
}
ReactDOM.render(
	<DateTimeNow/>,
	document.getElementById('content')
);
```
The error message reported by browser is:
`Uncaught Invariant Violation: Objects are not valid as a React child (found: Mon Oct 17 2016 09:12:00 GMT+0800 (CST)). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `DateTimeNow`.`

Could you please help to answer why it will cause error?
Thank you very much!

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
error message: Uncaught Invariant Violation: Objects are not valid as a React child (found: Mon Oct 17 2016 09:12:00 GMT+0800 (CST)). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `DateTimeNow`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**
span tag displays current time
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 15.3.2

**Comment by colw** [comment]
The short answer is you need to call a `toString()` method on your dateTimeNow variable, as it is a date *object*. i.e. one of the 'Objects' the error message is referring to.

```
return <span>Current date and time is {dateTimeNow.toUTCString()}.</span>;
```

That said, the error message is a little initially confusing since it simply renders the date as a string. If for example you replace `{dateTimeNow}` with an object such as `{ {a: 1} }`, the error message makes a little more sense:

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {a}).
```

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/7988#issuecomment-254148427 is correct.
This is because Dates are objects in JS, but your render output may only contain React elements, strings, and numbers.
Formatting a string with any `toString()`-like method will work.
You can find a list of such methods on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Conversion_getter).

Cheers!

**Comment by ipsips** [comment]
why can't React do calling `.toString()` for us automatically a lá string interpolation? Too much overhead?
