### ISSUE TITLE
[New Docs] Wanted Guides

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8060]
We revamped the docs, but there are a few guides that are missing and that I think are essential.
- [ ] Community section with good resources (e.g. https://github.com/facebook/react/pull/7117)
- [ ] @mrscobbler Glossary (similar to "Virtual DOM Terminology" that is now gone, but more friendly. Check http://redux.js.org/docs/Glossary.html for inspiration.)
- [ ] Troubleshooting (there are ~5 common issues we should explain right away, like wrong element casing, not loaded DOM container, missing React in scope, etc. See http://redux.js.org/docs/Troubleshooting.html for inspiration)
- [ ] Accessibility 
- [ ] @madhug Manipulating Children (Using `cloneElement` and `Children` https://github.com/facebook/react/issues/6942)
- [ ] "Portals" (useful for modals)
- [ ] Animation with React Motion
- [ ] @jamesknelson Routing (no need to use React Router here, just show how to use `setState` with HTML5 history API and point to RR as a component-based API for it once v4 is out)
- [ ] AJAX (just show how to use `fetch()` in lifecycles, mention cancellation issues)
- [x] Integrating with non-React code (show how to wrap jQuery plugin in React, how to expose React component as a Backbone view, and how to consume Backbone models) https://github.com/facebook/react/pull/9316#pullrequestreview-30403084
- [ ] ReactPerf should include a basic usage example, not just reference (https://github.com/facebook/react/issues/6174)
- [ ] Snapshot testing (https://github.com/facebook/react/issues/7431)
- [ ] Publishing a Component (https://github.com/facebook/react/issues/7882)

If somebody wants to work on this please comment here and let's figure out a plan.
Help wanted!

**Comment by gaearon** [comment]
cc @lacker @hramos @ericnakagawa

**Comment by mrscobbler** [comment]
I'll take the glossary sections. Is there a list of terms somewhere I can work of off? Or should I come up with some? I don't remember what the virtual DOM terminology page contained.

**Comment by jamesknelson** [comment]
I can possibly take routing with HTML5 history

**Comment by gaearon** [comment]
Regarding terminology, please assume familiarity with all topics in "Basic Guides". Most of them have relevant terms right in titles (elements, components, props, state, lifecycle, events, keys).

**Comment by jamesknelson** [comment]
Does the routing guide even need to use `setState`? I think it should be possible to do with plain props. Also, will hash-based routing be OK? If not, it'll probably need context to make a `<Link>` component work which seems a little complicated.

**Comment by gaearon** [comment]
If we do plain props we'll have to make top level render inside a change handler right? I'd like to avoid that because people often don't understand how to compose two such handlers.

I think we should teach HTML5 routing right away. Like here: https://vuejs.org/guide/routing.html. Would you really need context? You can have Link listen to history independently.

**Comment by jamesknelson** [comment]
Actually, it shouldn't need context if we're just using plain HTML5 history. I was thinking of using the history package.

**Comment by gaearon** [comment]
I want to keep it package free so people see the simplicity of doing routing with React, and then go to packages when they actually need their features.

**Comment by jamesknelson** [comment]
Yes, that is the definitely ideal. Was a thinking mistake on my part. 

So just to confirm, the idea is to add a listener in `componentWillMount` of a `Router` component, use `setState` based on that, then choose what to render based on that? Then create a `Link` component which captures `onClick` and does `pushState`?

**Comment by gaearon** [comment]
Maybe not even call it Router, just make a top level App component choose the right thing based on state and a URL => component map object or something like that.

**Comment by jamesknelson** [comment]
Ok. Will put a draft together probably this weekend :)

**Comment by rthor** [comment]
I'm writing a guide on using ajax. Is that good with people or is someone already on it?

**Comment by madhug** [comment]
Is anyone working on `Manipulating Children` #6942 or can I take it?

**Comment by gaearon** [comment]
@madhug Assigned to you, thanks!

**Comment by jamesknelson** [comment]
@gaearon I've started putting the routing guide together, but the HTML5 History API is a little less nice than I had imagined. 

First, browser's don't emit the `popstate` event when `pushState` is called. This means `<Link>` components will need some way of notifying the `<App>` component of any changes -- e.g. context or a shared global. Second, Safari doesn't emit `popstate` on page load, while other browsers do.

While I have no problem with explaining these things, it would end up being a guide to HTML5 History instead of a guide to React Routing. Would it be ok to use the `hashchange` event instead, or possibly [history](https://github.com/mjackson/history)?

Also should I create a separate issue for this?

**Comment by gaearon** [comment]
OK, using `history` seems reasonable with a note that it hides browser inconsistencies.

**Comment by laumair** [comment]
Is anyone working on  `AJAX (just show how to use fetch() in lifecycles, mention cancellation issues)`. I'd like to take this on. I might have a few questions though before getting started.

**Comment by rthor** [comment]
Yeah, been working on it (#8098). Just awaiting final review. Any news on getting it merged @gaearon ? :p

**Comment by laumair** [comment]
@rthor Ah, okay. 
Is there any other stuff that's left from the checklist?

**Comment by brillout** [comment]
I maintain [brillout/awesome-react-components](https://github.com/brillout/awesome-react-components) / [devarchy.com/react-components](http://devarchy.com/react-components), are you interested in adding something like that to the doc?

**Comment by laumair** [comment]
@gaearon Is there any item from the checklist that isn't occupied atm?

**Comment by mrscobbler** [comment]
Created a pull request for a glossary of terms: 
https://github.com/facebook/react/pull/8199
Would love some feedback on it.

**Comment by dhyey35** [comment]
Can I take ReactPerf should include a basic usage example, not just reference (#6174) or is anybody already on it ?

**Comment by dhyey35** [comment]
@laumair I think Animation with React Motion and last two ( snapshot and publishing ) are yet to be taken as no comments on them.

**Comment by laumair** [comment]
I think I can take publishing

**Comment by hedgerh** [comment]
I have some thoughts regarding the "community resources section" document.

I think we should compile resources that newcomers aren't going to already come across after a couple of random Google searches.  Rather than "Getting Started With React" tutorials, or React video courses, I'd like to point people to communities like Reactiflux and #reactjs on IRC, which have been invaluable to me.  

I'd like to point people to blog posts/articles that cause light bulbs to go off when they read them.  Dan, your post on smart/dumb containers is pretty quintessential reading for newcomers at this point.  Also, resources that cover things like how it's a better pattern to pass each prop a component needs individually `<Post title={postObject.title} author={postObject.author}/>`, than to pass a whole data object down as a single prop  `<Post post={postObject}/>`. 

Beyond that, I think we should guide them to any other places in the community where they can find good resources on their own.

**Comment by lacker** [comment]
@hedgerh That sounds good overall - although I think we should only really remove stuff that we believe is lower quality than a random Google search and therefore we do not recommend, rather than removing stuff that we theorize newcomers will come across while Googling. It's still helpful to say "we believe this is the best few video courses out there".

**Comment by hedgerh** [comment]
@lacker - good point.  i'm totally cool with that as long as it doesn't become a link dump.

**Comment by Khaledgarbaya** [comment]
Hi There I can take the Animation part, if it is not taken already

**Comment by brigand** [comment]
I'm working on "Publishing a Component". https://github.com/facebook/react/pull/8427

**Comment by vaskort** [comment]
Hello! New to React but I feel I could contribute to the accessibility guide, can you tell me roughly what would you like to see in the accessibility guide @gaearon?

**Comment by ConAntonakos** [comment]
Would love to finally contribute! It seems that portals and snapshot testing are available. I've recently been delving into 'portals', modals, and `react-overlays`, so I'd love to jump on that.

For snapshot testing, do we want to talk about https://facebook.github.io/jest/docs/tutorial-react.html#snapshot-testing?

**Comment by mtomcal** [comment]
Can I work on "Integrating with non-React code (show how to wrap jQuery plugin in React, how to expose React component as a Backbone view, and how to consume Backbone models)" @gaearon ? I've had to do this a few times for jQuery and I used to do Backbone and use it there as well. Doing also how to use React Components with Angular (just the basics) would be fun.

**Comment by markerikson** [comment]
Some interesting points in an HN discussion thread on a desire to have the official React docs either include more "official" info on application-wide topics like routing, or at least point to vetted sources beyond the docs:  https://news.ycombinator.com/item?id=13374170

**Comment by markerikson** [comment]
As a related note, the Reactiflux website is being revamped and should be ready shortly.  As part of that, I did a sweep through my React/Redux links list, picked out the top two or three articles in several key categories, and that shortened list is being added to a "Learning" page on the Reactiflux site.  The current version of that page is at https://github.com/reactiflux/reactiflux.com/blob/master/pages/learning.md .  That would be a good resource to link from the React docs, or maybe even copy over / cherry-pick from?

@gabegreenberg , any thoughts on this topic?

**Comment by bigblind** [comment]
It's still a WIP, but it might be useful to mention [react-a11y](https://github.com/reactjs/react-a11y) in the accessibility guide.

**Comment by neeharv** [comment]
@gaeron should this also include a section for code splitting? Happy to help with that.

**Comment by markerikson** [comment]
So what are the current thoughts on a "Learning Resources" section?  Per the list, @tylermcginnis proposed one over in #7117 , and that was closed due to the docs rewrite.

I know I've seen a lot of people complain that the React docs don't tell you how to build a full-blown app.  I agree that the core of the docs should focus on React itself, especially given the variety of ways that people use React, but at a minimum a pointer to additional resources would be good.

I'm very biased, but my [React/Redux links list](https://github.com/markerikson/react-redux-links) actually covers several of the topics listed here.  For example, it has sections discussing [use of `children](https://github.com/markerikson/react-redux-links/blob/master/react-component-patterns.md#react-component-children), [rendering modals](https://github.com/markerikson/react-redux-links/blob/master/react-component-patterns.md#modal-dialogs), [wrapping non-React code like jQuery plugins](https://github.com/markerikson/react-redux-links/blob/master/react-component-patterns.md#wrapping-non-react-code), [making AJAX calls](https://github.com/markerikson/react-redux-links/blob/master/react-ajax.md), [performance and optimization](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md), and much much more.

Also, per my comment earlier: I put together a "best-of / guided learning" version of my links list for the new Reactiflux site at https://www.reactiflux.com/learning/ , and later updated the front page of my list to show that.

So, while it wouldn't be _bad_ to have some of those topics directly in the docs, there's enough good quality articles out there already that I think the docs could simply point to a couple selected articles on each of these topics, and then maybe point to my list and Tim Arney's React FAQ as sources for further information.

**Comment by pinakdas163** [comment]
I want to work on this doc:
Troubleshooting (there are ~5 common issues we should explain right away, like wrong element casing, not loaded DOM container, missing React in scope, etc. See http://redux.js.org/docs/Troubleshooting.html for inspiration)

Is it still open for contribution?

**Comment by lacker** [comment]
@pinakdas163 I think a "troubleshooting" doc is often not a good idea when the topic is very broad like "everything about React". It's very hard for the core team to keep it up to date, since there's no good way of detecting when particular troubles are later resolved. And it's also hard for people to find, since you rarely are debugging your troubles by searching for a "troubleshooting" doc on the React website. Instead, when there are common issues that lead to people finding a bug and then fixing it, people are more likely to look somewhere like Stack Overflow, or to search and find a heavily-SEO'd site like Stack Overflow. So my suggestion would be when you run into troubleshooting-type troubles, to try to put them in Stack Overflow rather than into the React docs. If there were a more specific troubleshooting section like "troubleshooting when using web components" then it might be very useful to put that in existing guide pages.

**Comment by gaearon** [comment]
I don’t know.. In my experience Troubleshooting doc (at least in Redux) was incredibly helpful in fixing 50% of most commonly asked questions.

I think it would be a huge win to have it in React even if it documents just:

* Promises swallowing errors inside `setState` (solution: use `catch` carefully)
* `this.state` not updating right after `setState` (solution: use `setState` updater overload)
* `this` being `undefined` (solution: use arrows, bind, or property initializers)

**Comment by lacker** [comment]
OK, those sound like a pretty interesting list of things to read through linearly actually.

**Comment by gaearon** [comment]
[This](https://twitter.com/housecor/status/839125277842231298) is also a good candidate for Troubleshooting. Basically, "why doesn't my state update" often comes from data derived in the wrong place (especially from props). This used to be in the old docs but we yanked it.

**Comment by dmitriid** [comment]
> Animation with React Motion

Perhaps, animation in general? This is a broad topic, and many parts are very hard to implement with React (at a first glance).

Some of the problems I've run into:

Due to reconciliation, it's hard/impossible/very-hard-to-control to:
- animate the removal of a component
- animate removal/changing/reordering of list animations
- animate changes in components that reuse underlying DOM structure

There are undoubtedly others. Re-parenting is quite often mentioned on twitter.


Just to give a quick example. I'll keep components stateless for clarity of code. 

```js
// app.jsx

let observableState = 'login'

const LoginForm = () => {
  return <form>
     <label>Login</label> <input name="login" />
     <label>Password</label> <input name="password" />
     <button onClick={login}>Login</button>
     <button onClick={() => observableState = 'signup' }>Sign Up</button>
  </form>
}

const RegisterForm = () => {
  return <form>
     <label>Login</label> <input name="login" />
     <label>Password</label> <input name="password" />
     <label>Access code</label> <input name="code" />
     <button onClick={signup}>Sign Up</button>
     <button onClick={() => observableState = 'login' }>Login</button>
  </form>
}

const App = () => {
  if(observableState === 'login') {
    return <LoginForm />
  } else if(observableState === 'signup') {
    return <Signup />
  }
}

React.render(<App />, ...)
```

When switching between forms, React will only:

- remove/add "Access code"
- update button text and handlers

So, there are quite a few questions about animating all this:

- Animate one form disappearing, another appearing? Rely on `componentWillReceiveProps` and handle this through props?
- Animate `Access Code` disappearing, then appearing when switching forms? There's no controlled `onRemove` to animate the removal of the component. Moreover, if `<Login />` sprouts a third input, `Access Code` will no longer be removed/added, but only updated, like the rest of the elements
- etc. etc.

If anyone figured this stuff out, it would be a great service to the community to describe how to deal with these and other situations in React (an to a larger community as a whole, because this same problem exists in all similar frameworks: snabbdom, virtual-dom, inferno ... )

**Comment by dmitriid** [comment]
> no need to use React Router here, just show how to use setState with HTML5 history API and point to RR as a component-based API for it once v4 is out

This might generate some backlash from the community. The name `React Router` implies it's directly endorsed and/or supported by the React team. However:
- it's not
- by version 4 it's now had 4 major backwards incompatible changes in the API, leaving many developers hanging. (I can't find a big discussion about it right now, it may have been cleaned up to keep it more civil)

**Comment by igolden** [comment]
Is anyone assigned Snapshot testing yet? I think it's a crucial guide to help take new React devs from "Hello World" React and into production,  I'd love to take that doc if no one is on it yet.

After looking at [#7431](https://github.com/facebook/react/issues/7431), my outline is:

 1. Give a  conceptual intro to snapshot testing, followed by a simple react-test-renderer example.  In particular, using components from the React docs ([Forms](https://facebook.github.io/react/docs/forms.html#controlled-components), [Lists](https://facebook.github.io/react/docs/lists-and-keys.html#basic-list-component) for example)

2.  Follow that up with a simple example testing refs with a callback ([issue](https://github.com/facebook/react/issues/7371#issuecomment-260946944)), maybe with the example components above. That seems to be the first thing people hang up on with snapshot tests.

3.  Then illustrate a real-world snapshot test example with mocks using Jest. This would be an area to address the ReactDOM [issue](https://github.com/facebook/react/issues/7386) and also point people in the direction of Jest as a test framework.

4?  I'd be happy to cover shallow-render example too, with Enzyme or ReactTestUtils, but we could point them to the [Jest docs](https://facebook.github.io/jest/docs/tutorial-react.html#dom-testing) for that. My inclination is to include that info in React docs, because shallow-rendering is already documented and Jest is supported by FB.

Am I missing anything?

**Comment by AlmeroSteyn** [comment]
I could also contribute to a section on Accessibility. Is anyone busy with this already? Are there any plans yet?

On that topic, the docs site itself has some accessibility issues that could be corrected easily. For a start, I have submitted #9431

**Comment by thamaranth** [comment]
What's still open?

**Comment by markerikson** [comment]
@thamaranth : based on the activity I've seen, probably anything in the first comment that's not checked off and doesn't have a name next to it.

**Comment by thamaranth** [comment]
I can help out with good resources if it's still open.

**Comment by akoserwal** [comment]
Hi @gaearon: is there anything remaining, which I can pick up?

**Comment by dance2die** [comment]
I'd love to contribute.
Would you assign me an issue I can get started with?
Thank you.

**Comment by markerikson** [comment]
@dance2die : I don't think anyone will "assign" you something - go ahead and pick something that looks good and go for it!  

That said, this issue really should be migrated to the new docs site repo at https://github.com/reactjs/reactjs.org .

**Comment by bvaughn** [comment]
Migrated to reactjs.org/issues/83

**Comment by bvaughn** [comment]
Migrated to reactjs/reactjs.org/issues/83

If you're interested in picking up any of these guides, let's talk on the new issue and I'll make them in-progress for you!
