### ISSUE TITLE
Redirection in docs lead to wrong page

### ISSUE THREAD

**Issue by kevart** [facebook/react#8100]
Search in Google for "react event listener remove".

Click on:

```
DOM Event Listeners in a Component | React
https://facebook.github.io/react/tips/dom-event-listeners.html
DOM Event Listeners in a Component. Note: This entry shows how to attach DOM events not provided by React (check here for more info). This is good for ...

```

Opens this page: https://facebook.github.io/react/docs/react-component.html
which doesn't include any info about event listeners.

This happens for other search results too. It's pretty annoying to not be able to find references in the public docs quickly.

**Comment by gaearon** [comment]
Docs were replaced a week ago, and they're not quite complete yet. I understand it's annoying, but the previous docs were very unfocused and included too many "tips".

@lacker What's the best place for this content now?

**Comment by lacker** [comment]
Hmm, that tip seemed like it hardly had any content to me. See: https://github.com/ivanzotov/react/blob/55da8bb6d23dbc999f575943ceba280f3d30be60/docs/tips/11-dom-event-listeners.md

Basically the only content it has is, when you want to use DOM event listeners, call `window.addEventListener` in `componentDidMount` and `window.removeEventListener` in `componentWillUnmount`. That's why I just redirected to the page about `componentDidMount` and `componentWillUnmount`.

Since we did a bunch of rewriting, my suspicion is that a lot of Google searches will be somewhat annoying when the precise word doesn't show up on the page, until Google gets its index updated. So my suggestion here is that we just leave it as is - I don't think this specific use of `componentDidMount` needs to be in the React docs per se - and then I suspect once the Google index updates these redirects will stop causing annoyance in this case.

**Comment by kevart** [comment]
Thanks guys! I'll keep checking.

**Comment by gaearon** [comment]
>I don't think this specific use of componentDidMount needs to be in the React docs per se

Maybe "refs in the DOM" would be a good place?

**Comment by lacker** [comment]
I thought about that, but this doesn't even use refs, it's using global stuff on `window`, so I got stumped.

**Comment by gaearon** [comment]
It fits into the "and the DOM" part.
