### ISSUE TITLE
Transferring TransitionGroup Maintenance

### ISSUE THREAD

**Issue by gaearon** [facebook/react#8125]
We haven't been good at maintaining [ReactTransitionGroup](https://facebook.github.io/react/docs/animation.html) as we don't use it much at Facebook.

As a result it's stagnating: the bugs don't get fixed, new features don't get added, APIs don't acknowledge changes in React (e.g. fake lifecycle hooks that can't work on functional components), nobody has the time to review PRs to it, and it's like a dead weight on the core team. We all feel guilty about it but there's not much we can do.

There are some great alternatives in the ecosystem such as [React Motion](https://github.com/chenglou/react-motion). However we understand there are a lot of people who are happy with `TransitionGroup` as it is.

This issue is a call for a new maintainer. If you are using `TransitionGroup` widely in your codebase and would be happy maintaining a fork of it and documentation, please let us know here, and we'll deprecate our package in favor of your package.

**Comment by developit** [comment]
I don't use it either, but I wanted to drop a link to a refactored standalone version I put together here because it'd make a pretty compelling starting point for anyone looking to maintain a standalone version of ReactTransitionGroup:
https://github.com/developit/preact-transition-group

It's obviously for Preact, but forking it to work with React again would basically just be changing the imports and dependencies to point to React instead.

It was originally a fork of [this version](https://github.com/react-component/css-transition-group), extracted from the React 0.14 source.

**Comment by fjckls** [comment]
So what do you use at Facebook? React Motion? Does that mean that the end is in sight for < ReactTransitionGroup> and we should start refactoring our code in favor of react motion?

**Comment by gaearon** [comment]
>So what do you use at Facebook? React Motion?

The Facebook product itself doesn't have many insertion/deletion animations so we don't use anything much.

>Does that mean that the end is in sight for < ReactTransitionGroup> and we should start refactoring our code in favor of react motion?

No, why? Even if we completely stop releasing new versions it won't be any worse than it is now: effectively it's already been abandoned for a year or so. You can keep using it, or fork it yourself if you want to improve it. In fact this is what the issue is about.

**Comment by fjckls** [comment]
For us animation itself is not a problem we're using great [GSAP](https://greensock.com/gsap) tweening engine. The problem comes when we have to animate out component on removal. React motion almost solves this problem - there is only one issue with React Motion- there is no `onRest` callback for TransitionMotion.... 
Anyhow there will never be 100% perfect solution out of the box... so will have to invest some too :)

**Comment by jquense** [comment]
me and @taion might be interested, I've copy and pasted and forked this component so many times . It'd be nice to make direct improvements

**Comment by gaearon** [comment]
@jquense This would be amazing, you've made some great work maintaining React libraries.

**Comment by jquense** [comment]
ok 👍  we are are glad to take over maintenance. 

My initial thought is to move it to https://github.com/react-bootstrap/react-overlays since it pairs nicely with the Transition component there, one for single components this for lists. We can also keep it a separate repo if necessary, but I think if folks only want that component requiring it individually from the suite shouldn't cause to much friction.

**Comment by gaearon** [comment]
Would you like to do it under `reactjs` org? My concern with `react-bootstrap` org is people will think it's going to require Bootstrap, or something like this.

**Comment by taion** [comment]
Tangential, but we would prefer to move react-overlays under reactjs – potentially replacing react-modal: https://github.com/reactjs/react-modal/issues/156.

**Comment by jquense** [comment]
under reactjs is 👍  It might make sense to pull Transition out of react-overlays into an anaimation specific package since it doesn't have to do specifically with overlays :p

**Comment by gaearon** [comment]
What would be our next steps? Do you need any help with the forking?

**Comment by beckiechoi** [comment]
Hey guys, not sure if it's too late to mention this, but at Squarespace we have our own version of transition group which uses very similar approach, but is not a fork of ReactTransitionGroup. We're planning on open sourcing the library (we will have to go through appropriate compliance to open source it). It's already something we use pretty heavily on our platform, so all the bugs that were found have already been straightened out. Will you be interested in favoring that?

**Comment by jquense** [comment]
I think there is probably room for both :) 

from my end helping folding would great. Im not sure the best way to split the code out or of there is a feasible solution to keeping the current git history

**Comment by gaearon** [comment]
I wouldn't worry about keeping the history.

**Comment by beckiechoi** [comment]
Sounds good. I'll keep you all updated.

**Comment by jquense** [comment]
@gaearon works for me, if you want to add me to the organization I can move the code or I can bug @taion to do it :P

**Comment by bgnorlov** [comment]
@gaearon, I think if react add ability to return promise in componentWillUnmount hook for delay unmount stuff and then there is no need to use ReactCSSTransitionGroup which uses internal react api anyway

**Comment by gaearon** [comment]
@bgnorlov 

>if react adds ability to return a promise in componentWillUnmount hook for delay unmount stuff

Sure, but this is tangential to this thread. You can discuss deferred unmounting in #6003.

>which uses internal react api anyway

This is not the case as far as I know.

**Comment by jquense** [comment]
starting at: https://github.com/reactjs/react-transition-group

**Comment by taion** [comment]
can someone with access add @jquense to the @reactjs org?

**Comment by gaearon** [comment]
I added @taion, @jquense and @beckiechoi to a new "react addons" team that has admin access to https://github.com/reactjs/react-transition-group.

**Comment by levithomason** [comment]
Should this issue be closed then? Any open issues  regarding maintenance and future TransitionGroup support?

**Comment by gaearon** [comment]
Yep, let’s close. Further issues about TransitionGroup should be filed against https://github.com/reactjs/react-transition-group.

We haven't deprecated ours officially well but we likely will.
