### ISSUE TITLE
React.cloneElement that gives precedence to the Child Component props

### ISSUE THREAD

**Issue by lifehackett** [facebook/react#8205]
**Do you want to request a *feature* or report a *bug*?**
Feature

I would like a version of `React.cloneElement` that gives precedence to the props already on the component being cloned that were PASSED in but ignoring the ones that were provided by default.

Order of precedence
1) Props provided to the Child component
2) Props provided to the parent used to override the child component ones
3) Default props on the Child component (i.e. prop was not provided to parent or child)

Here is an example use case

```
<Button.Group color="blue">
  <Button color="red" />
  <Button />
  <Button />
</Button.Group>
```

The behavior I would like to achieve here is for Button1 to be red and button 2 & 3 to be blue.  The idea is that you can provide a single prop to the parent as the sort of default, but that individual components can override that default if they choose.

I tried manually merging the props, but because the default value have already been supplied, there isn't really a reliable way to do this. 

Thank you.

**Comment by gaearon** [comment]
I don’t think we intend to support this as it seems like a relatively uncommon request. But you can easily work around it by *not* using `defaultProps` at all, and only applying them in `render`:

```js
var color = this.props.hasOwnProperty('color') ? this.props.color : defaultColor;
```

**Comment by InfamousStarFox** [comment]
Adding a solution here because this page is showing up on the front page of Google when searching for "React.cloneElement keep child props"

Let's say you are passing in the new color:

```
React.cloneElement(child, {
	this.props.color
});
```
This will override the color prop for the child element.

So, you need to pass in the child props again **after** passing in the parent's props:

```
React.cloneElement(child, {
	this.props.color,
	...child.props,
});
```

Any props that are set by the child will override the values of the props set by the cloneElement.

If you wanted to create an order of precedence:
1. Props provided to the child component
2. Props provided to the parent
3. Default props on the child component

List the props in reverse order:
```
React.cloneElement(child, {
	...defaultProps,
	this.props.color,
	...child.props,
});
```
