### ISSUE TITLE
Component Model

### ISSUE THREAD

**Issue by christchron** [facebook/react#8246]
React is one of JavaScript libraries that use component-based software engineering approach. In the CBSE, there are some component models such as EJB model, COM model, .NET model, etc. I want to know which component model did React use? Or React is using different kind of component model? I'm doing some research about React behaviour based on its component-based Software Engineering. So, i want to ask for help if there're some documentations about React Component, its model, and anything that can help my research. Thank you before, if you're willing to help please send it to my email: randichil@gmail.com

**Comment by gaearon** [comment]
React has a component model that has no relation to EJB/COM/.NET. "Components" in React sense are stateful pieces of the UI, not arbitrary packages like those systems.

React component model is influenced by functional programming. You can learn more about it by reading [React docs](https://facebook.github.io/react/docs/hello-world.html).

I’m closing because this issue isn’t actionable for us, and we use the issue tracker for bugs and feature requests.
