### ISSUE TITLE
adler32 function returns incorrect checksum on Opera Presto browser

### ISSUE THREAD

**Issue by apsoto** [facebook/react#8264]
I've discovered what seems like a platform bug in the Opera Browser (Presto Engine) which is causing server side rendered components to always be re-rendered because the client's checksum does not match the server rendered checksum.

More than 3 addition assignment expressions in a single statement results in an incorrect checksum when the adler32 function is called.

Here is a test case that can be used to reproduce the bug:

https://jsbin.com/yukefox/1/edit?html,output

Here is a download link for Opera 12.16 for Mac you could install and run the above test and see it fail:

http://www.opera.com/download/guide/?ver=12.16

While it's a very old browser, and a fix for it extremely unlikely, it's still used on many embedded devices (TiVo being one where I'm finding it).  

However, React can work around the bug by splitting this line in the adler32 function into multiple statements:

https://github.com/facebook/react/blob/master/src/renderers/shared/utils/adler32.js#L31

**Comment by apsoto** [comment]
Any suggestions on how to apply a monkey patch or similar work around in my app would be greatly appreciated.  Forking and building my own npm package seems like a PITA.

**Comment by syranide** [comment]
@apsoto I'm curious what you mean when you say that "React can work around the bug by splitting this line in the adler32 function into multiple statements:", can you show me the code you used? Because I see two potential culprits here; one is that Opera may be using 32bit floats instead of 64bit doubles for numbers... incorrectly converting that function would allow the result to fit within 32bit floats and thus become deterministic (but compute a poor checksum). The other being that Opera has a bug with `+=` being executed in the wrong order.

As for monkey-patching, if you're using the non-bundled NPM version you should be able to either substitute the module via your bundler or simply have it physically replace the file before bundling.

**Comment by apsoto** [comment]
WRT multiple statements, here's a diff what I've tried locally and it works:

```
29c29,33
<       b += (a += data.charCodeAt(i)) + (a += data.charCodeAt(i + 1)) + (a += data.charCodeAt(i + 2)) + (a += data.charCodeAt(i + 3));
---
>       var a0 = (a += data.charCodeAt(i));
>       var a1 = (a += data.charCodeAt(i + 1));
>       var a2 = (a += data.charCodeAt(i + 2));
>       var a3 = (a += data.charCodeAt(i + 3));
>       b += (a0 + a1 + a2 + a3);
```

WRT to monkey patching, I've been able to vendor React in my app and use a webpack alias, but having build issues on Heroku.

Can you expand on your comments re: monkey patching?

Thanks

**Comment by bounty2darescue** [comment]
@apsoto @syranide ran into this on Opera.  This is definitely a browser bug.  For more than 3 clauses, every clause is calculated properly but the second clause is always returning the old rather than the new value.  @apsoto to check, try adding more clauses:

```js
a=0
assert.strictEqual( (a += 1,console.log(1,a),a) + (a += 1,console.log(2,a),a) + (a += 1,console.log(3,a),a) + (a += 1,console.log(4,a),a) + (a += 1,console.log(5,a),a),15); // final result is incorrect
assert.strictEqual( (a += 1,console.log(1,a),a) + (a += 0,console.log(2,a),a) + (a += 1,console.log(3,a),a) + (a += 1,console.log(4,a),a) + (a += 1,console.log(5,a),a),11); // works because the second clause doesn't change the value of a
```

If you change the other increments but set the second one to zero, you will see the value agrees with what you get in other engines.  The suggested changes from @apsoto seem reasonable, but I probably would do the increments directly and skip the intermediate variables:

```js
b += (a += data.charCodeAt(i));
b += (a += data.charCodeAt(i + 1));
b += (a += data.charCodeAt(i + 2));
b += (a += data.charCodeAt(i + 3));
```

**Comment by syranide** [comment]
@bounty2darescue Thanks for the debugging. Interesting bug.

The reason it's done this way to begin with is for performance reasons, that specific path is really really hot. I'm not sure how much we really care still as it will probably phased out in the future.

So we have the possibility to feature test and provide a workaround implementation just for the broken browsers. Or we can go with a general workaround, as I understand it the following three should all work, but benchmarking will probably reveal one of them to be faster (if we care that much).

```js
b += (a += data.charCodeAt(i));
b += (a += data.charCodeAt(i + 1));
b += (a += data.charCodeAt(i + 2));
b += (a += data.charCodeAt(i + 3));
```

```js
b += (
  (a += data.charCodeAt(i)) +
  (a += data.charCodeAt(i + 1))
);
b += (
  (a += data.charCodeAt(i + 2)) +
  (a += data.charCodeAt(i + 3))
);
```

```js
b += (
  (a += 0) +
  (a += data.charCodeAt(i)) +
  (a += data.charCodeAt(i + 1)) +
  (a += data.charCodeAt(i + 2)) +
  (a += data.charCodeAt(i + 3))
);
```

cc @jimfb

**Comment by bounty2darescue** [comment]
@syranide the last one should be

```js
b += (
  (a += 0) +
  (a += data.charCodeAt(i)) +
  (a += data.charCodeAt(i + 1)) +
  (a += data.charCodeAt(i + 2)) +
  (a += data.charCodeAt(i + 3))
);
```

The original SheetJS version doesn't suffer from this.  [Their Sauce Labs browser test badge](https://github.com/sheetJS/js-adler32#badges) shows Opera 12 is part of the test suite.  Looking at the original code, they decided not to unroll this part and I have to assume it's because of this bug.

**Comment by syranide** [comment]
@bounty2darescue Is it because of nesting? Because above you said 2nd clause and that's also what it shows in the test... but that may be some quirk of the bug.

I'm pretty sure they just didn't because they pretty much can't due to UTF16 handling. Our version is significantly faster than theirs and was heavily optimized simply because it became apparent that it was contributing significant running time during server rendering. That specific statement also constitutes the majority of the running time of the implementation, so the unrolling is what makes it fast.

Anyway, let's wait and see what the devs feel.

**Comment by bounty2darescue** [comment]
@syranide Splitting up my first comment into lines would help clarify:

```JS
var a = 0;
var b =
    (a += 1) + // old value is 0, value after increment is 1, expression result is 1
    (a += 1) + // old value is 1, value after increment is 2, expression result is 2 in every other browser but 1 in opera
    (a += 1) + // old value is 2, value after increment is 3, expression result is 3
    (a += 1) + // old value is 3, value after increment is 4, expression result is 4
```

If you think the best approach is to unroll and do 4 steps at once, the "fix" is to effectively noop the second block:

```JS
b += (
  (a += data.charCodeAt(i)) +
  (a += 0, 0) + // <-- skip the broken point
  (a += data.charCodeAt(i + 1)) +
  (a += data.charCodeAt(i + 2)) +
  (a += data.charCodeAt(i + 3))
);
```

I'm not sure whether using the dummy step is faster or slower than using 2 increment steps.

> That specific statement also constitutes the majority of the running time of the implementation, so the unrolling is what makes it fast.

Are you sure it isn't because the mask was removed?  Sheetjs picks the low byte of each character code `a += bstr.charCodeAt(i)&0xFF` whereas we don't: `(a += data.charCodeAt(i))`.   I assume it was removed for performance reasons.

N.B.: I don't understand why 4096 was chosen in https://github.com/facebook/react/blob/master/src/renderers/shared/utils/adler32.js#L29 .  Looking back at the root, the sheetjs code [README](https://github.com/SheetJS/js-adler32#magic-number) explains the magic number:

> The magic numbers were chosen so as to not overflow a 31-bit integer:

```mma
F[n_] := Reduce[x*(x + 1)*n/2 + (x + 1)*(65521) < (2^31 - 1) && x > 0, x, Integers]
F[255] (* bstr:  x \[Element] Integers && 1 <= x <= 3854 *)
F[127] (* ascii: x \[Element] Integers && 1 <= x <= 5321 *)
```

> Subtract up to 4 elements for the unicode case.

Since our version doesn't do the UTF8 conversion, the equivalent would be their [bstr version](https://github.com/SheetJS/js-adler32/blob/master/adler32.js#L25-L38) and they use 3850.

**Comment by syranide** [comment]
@bounty2darescue Good point about `(a += 0, 0)`.

> I'm not sure whether using the dummy step is faster or slower than using 2 increment steps.

I'm positive that it's faster, but I'm not sure how much it matters, I did it that way because it benchmarked as being the fastest.

> Are you sure it isn't because the mask was removed?

All of that matters obviously, but 99% of the time is spent in that specific loop, so every little bit has a big impact.

> N.B.: I don't understand why 4096 was chosen in 

I benchmarked every possible combination back then. I did try lower values too to intentionally stay within 31-bit integers but found that it didn't actually improve performance (we also overflow quicker due to not using the mask). In the end 4096 was simply chosen because that seemed to be the sweet-spot when benchmarking (and won't overflow floating point integers), lower or higher generally reduced performance.

**Comment by apsoto** [comment]
I have easy access to Opera 12 on Mac Desktop and on an embedded device if you need me to check anything.  Otherwise, I assume it's in good hands.

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR

**Comment by bounty2darescue** [comment]
Did a bunch of issues just get attacked by @joh1234 ? Probably worth removing the message or pinging @github

**Comment by gaearon** [comment]
React 16 doesn't use checksums anymore.
