### ISSUE TITLE
15.4 minor wasn't supposed to break so much stuff, was it?

### ISSUE THREAD

**Issue by TCMiranda** [facebook/react#8303]
![screenshot from 2016-11-16 14-38-06](https://cloud.githubusercontent.com/assets/10077439/20356782/c1bf72de-ac0c-11e6-84c1-e49ad17e721d.png)

Some packages broke due to missing stuffs on `react/lib/...`
Seems like it shouldn't happen, even my build process broke suddenly due to react 15.4 update (react packages set to ^15.3.2)

Thanks!

**Comment by gaearon** [comment]
Hi, thanks for the report.

If you rely on packages that rely on undocumented or private APIs, consider keeping React version pinned. It is never safe to rely on internal APIs and we never supported this officially. We can't consider private APIs as part of semver because there is no way to tell if any particular change in the internals would break a library reaching into them. This is just an unsupported way of using React.

We asked people to test 15.4 RC for a month: https://github.com/facebook/react/issues/7770#issuecomment-253899837. Unfortunately there is nothing we can do to force libraries using private APIs to stop doing this until we start using flat bundles.

Please reach out to maintainers of https://github.com/zilverline/react-tap-event-plugin and ask them to get https://github.com/zilverline/react-tap-event-plugin/pull/82 merged. But it might break later again because reaching into internal APIs is just not supported, and never has been.

**Comment by spicyj** [comment]
Same with the authors of draft-js-export-html (not a Facebook-owned module).
