### ISSUE TITLE
ReactTestUtils.Simulate no longer works as expected in v15.4.0

### ISSUE THREAD

**Issue by hunthunthunt** [facebook/react#8305]
Firstly, congrats on the release :)

With the  v15.4.0 update, a couple of our projects tests are failing given the changes to `ReactTestUtils.Simulate` as discussed here:
https://github.com/facebook/react/pull/7642#issuecomment-244516991

The work-around was to use `ReactTestUtils.SimulateNative` - however it's still not entirely clear what the difference between `Simulate` and `SimulateNative` are? When and why should one be used over the other?

It feels like these docs should be updated to reflect this change:
https://facebook.github.io/react/docs/test-utils.html#simulate

Finally, is there a reason that `SimulateNative` does not appear in the docs? I'm concerned that others are going to be caught out by this change also.

**Comment by gaearon** [comment]
cc @spicyj

**Comment by grzegorzjudas** [comment]
This is here for 5 months. Is there any reason why firing _simulate()_ on a disabled input/button actually fires the event?

Came here from enzyme repo issue (https://github.com/airbnb/enzyme/issues/386) and it turns out our _shallow()_ rendered components still call _onClick_ even if disabled attribute is there.

**Comment by gaearon** [comment]
There are many issues that are “here for 5 months”. It’s a popular repository, and the team is very small. This is a low priority issue because it’s not actively breaking apps.

If you have specific suggestions about how to fix this, please propose them! Read the past discussions, research the motivation behind previous changes, and present a proposal of how we should handle this instead. Maybe even send a PR 😉 . You are in the best position to do this because you are actively invested in solving this, and you actually have the context to know how it affects apps.

**Comment by grzegorzjudas** [comment]
What I more had in mind, is to just have a clarification whether the problem is actually a bug or is it intended (I can imagine scenarios when you want to have mouse event firing on a disabled input element) - I did not expect the fix to be released immediately.

In short - I wanted an answer, not immediate fix because it's "here for 5 months".

**Comment by gaearon** [comment]
Let’s ask @nhunzaker for context on this.

**Comment by aweary** [comment]
For reference, there were additional changes made to that code path in https://github.com/facebook/react/pull/8387
