### ISSUE TITLE
Reactjs page and android webview communication

### ISSUE THREAD

**Issue by santosh07401** [facebook/react#8325]
**Do you want to request a *feature* or report a *bug*?**
 no

**What is the current behavior?**
I didnt find a good way to communicate  from android webview to reactjs page.
The problem im facing is i have a landing page(written in reactjs and loaded in webview) with the backbutton. i want to close webview activity on click of that backbutton.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
all

**Comment by zpao** [comment]
I don't think there's anything specific to React here and it's a general usage question. I would encourage you to determine how to make this work with any button you had in JS and then see if that works in React.

**Comment by softmarshmallow** [comment]
I understand that it's off topic but it's valid question and I'm having a same problem to.
can you share us how you solved this? @santosh07401

**Comment by HolodTema** [comment]
Yes, this problem is still actual. I have a compilled ReactJS app in local "assets" folder in my app. And I even don't know how to put this local ReactJS app into WebView!
The problem is, ReactJs compilled app requires use "https" or smth kinda that. But in Android file paths begin with "file:///" - ReactJs can't recognize such format of file path. 
I was looking for some information on the Internet, and  there's a solution to launch a local server with reactJS app every time user open the application. But I consider it's not a cool solution...
