### ISSUE TITLE
Turn 'strict' ESLint rule back on

### ISSUE THREAD

**Issue by tomocchino** [facebook/react#8344]
When upgrading ESLint to the latest version I had to turn off the 'strict' rule because it conflicts with 

```json
"parserOptions": {
  "sourceType": "script",
},
```
combined with `import type` Flow statements. Opening this issue to track turning 'strict' back on, either with a change to ESLint, a new custom rule for use strict, or some other means.

**Comment by tomocchino** [comment]
cc @zpao @zertosh

**Comment by zertosh** [comment]
These are legit options that can be passed to `babel-eslint` through `eslint`'s config:

```
  parserOptions: {
    sourceType: 'script',
    allowImportExportEverywhere: true,
  },
```

Babylon will parse the `import type`, and the `Program`'s `body` will have `sourceType: 'script'`. Unfortunately, `escope` craps out because:

`ImportDeclaration should appear when the mode is ES6 and in the module context.`

But this is def a bug. That assert should ignore types. If `escope` worked, you should be able to set `strict: [1, 'global']` to get the effect that you want.

**Comment by gaearon** [comment]
Seems like we don't need this now. We enforce `'use strict'` in ES5 files, and don't need it in files using ESM. This is correctly enforced too.
