### ISSUE TITLE
Error messages swallowed in certain edge cases

### ISSUE THREAD

**Issue by kuba-orlik** [facebook/react#8430]
I would like to report a bug.

Currently in certain cases (like the one reproduced below) critical error messages are not displayed in the developer console. Sometimes the view does not render at all and it's left to our guesswork to identify the culprit.

Here's the relevant jsfiddle: 
https://jsfiddle.net/b1co3uex/10/

You can see that the only error being thrown is the one deliberately put in line 6. It blocks proper rendering of the view, yet no trace of it is show in the developer console.

The expected behaviour would be to catch the error and show it in developer console.

My current workaround is to wrap `setState` calls in `try/catch`, which is ugly - but it works. 

I suppose this is not by design, as React usually has excellent error reporting capabilities. 

I am aware that the issue might be caused by imperfections in my code. If there's a way to improve it while maintaining its functionality, I'm all ears :)

I've been struggling with this issue for quite some time now. In the above jsfiddle you can see the error being reproduced in React 15.3.2.

**Comment by arkadiusz-wieczorek** [comment]
I've also noticed this error. +1

**Comment by gaearon** [comment]
I might be wrong but I think that the problem is in the `qwest` library you are using. It doesn't seem to report unhandled rejections. Maybe it's because it uses [`pinkyswear`](https://github.com/timjansen/PinkySwear.js) under the hood which probably doesn't support this feature.

If you switch to a native Promise implementation, like [in this fiddle](https://jsfiddle.net/b1co3uex/11/) where I wrap pinky's Promise in a native Promise with `Promise.resolve()`, you will see the error in console in browsers that log unhandled rejections.

<img width="564" alt="screen shot 2016-11-27 at 17 25 11" src="https://cloud.githubusercontent.com/assets/810438/20650447/7d690d6c-b4c6-11e6-97f3-d8d880d0ea6b.png">

There is nothing we can do here. My advice is that if you use Promises, pick a library that supports printing unhandled rejections in development, or at least pick a library that uses native Promises when they are available. This is [the one we're using at Facebook](https://github.com/then/promise). It's also included by default in Create React App.

I hope this helps!

**Comment by kuba-orlik** [comment]
I understand. Thank you for your response. It's time to review the way we do ajax requests :)
