### ISSUE TITLE
Cannot read property 'purgeUnmountedComponents' of undefined

### ISSUE THREAD

**Issue by spicyj** [facebook/react#8454]
I'm getting this error when trying to render a component:

> Cannot read property 'purgeUnmountedComponents' of undefined

![image](https://cloud.githubusercontent.com/assets/6820/20721530/f725dea8-b617-11e6-8350-507e0f6652b6.png)

What does it mean and how can I fix it?

**Comment by spicyj** [comment]
If you load the *minified* react.min.js with the *unminified* react-dom.js then you get this error when using version 15.4.

To fix it, you should use the unminified copy of both files or the minified copy of both files – don't mix and match.

We should likely change the behavior here so you don't get a cryptic error.

**Comment by chaotyler** [comment]
I got this problem using both minified react.min.js and minified react-dom.min.js, and here is the log:
![image](https://cloud.githubusercontent.com/assets/4556756/21421782/a03cf418-c86f-11e6-9f34-450ab112d326.png)

**Comment by gaearon** [comment]
@chaotyler 
Please provide a project reproducing the problem.

**Comment by tawseefnabi** [comment]
im new in react js looking for tutorials for it

**Comment by chaotyler** [comment]
@gaearon 
I'm kind of finding out the reason, I'm using server-side rendering and re-render the hole page in the browser-side, here is the simplest example to reproduce this problem:

1. Get the current time in component constructor:

![image](https://cloud.githubusercontent.com/assets/4556756/21446580/d2464c0a-c902-11e6-91b8-eba97a683051.png)

2. Display the current time in the html:

![image](https://cloud.githubusercontent.com/assets/4556756/21446700/a8b00ce4-c904-11e6-834e-35fe88a98042.png)

3. The error comes out because the time differs between the server-side and browser-side, (I was using `now.getSeconds()`, so the error was not showed every time)

It is the coding problem in my component, but the error messages(different using different react libs) are not friendly, for example:

Using react.js and react-dom.js(this is the error message I really need)

![image](https://cloud.githubusercontent.com/assets/4556756/21446851/a53a7df4-c906-11e6-9627-d1178f21ced0.png)

Using react.min.js and react-dom.js:

![image](https://cloud.githubusercontent.com/assets/4556756/21446847/97411294-c906-11e6-90cf-9e9e778e6948.png)


Using react.min.js and react-dom.min.js:

![image](https://cloud.githubusercontent.com/assets/4556756/21446841/81c2b026-c906-11e6-85aa-883b5a7d4e68.png)

Try my demo: https://github.com/chaotyler/mini_react_problem_demo

**Comment by gaearon** [comment]
I’ll close since this error doesn’t happen on master, and there is a clear solution for 15 (don’t mix minified and unminified files).
