### ISSUE TITLE
Using a ref to set the htmlfor prop of an input's label

### ISSUE THREAD

**Issue by joshfarrant** [facebook/react#8483]
I don't know if this is currently possible, but I believe it would be useful to be able to use refs rather than ids when setting the htmlfor prop of a label.

Something along the lines of...

```jsx
<input
  ref={(node) => {
    this.input = node;
  }}
/>
<label
  htmlfor={this.input}
/>
```

Is this something that's previously been considered, or that's currently possible?

**Comment by Aweary** [comment]
@joshfarrant the issue with that is `htmlFor` is meant to reference the `id` attribute of an`input` element. React would have to read the input instance's `id` prop and pass it to the `label`, but what happens when you pass it a node that doesn't have an `id`? At that point, you'd have to add an `id` to the `input` element anyway and there doesn't seem to be a clear advantage over just passing in the `id` in the first place.

**Comment by monicatie** [comment]
You would get the benefit of having React be responsible for generating the unique `id` instead of manually doing it yourself. If there are multiple forms on a page, and in cases where an `id` isn't useful for anything but the `label`, it'd be great if React could take a ref for `htmlFor` and automatically handle the `id`ing.

**Comment by BrodaNoel** [comment]
Absolutely agree with @monicatie.
I'm not sure if there is already some trick to do it, or if we still have to "manually" increase that `id` in the component

**Comment by hoseingp** [comment]
I think Facebook need to handle this and generate GUID under the hood , cause they changed for to htmlFor so it means do it in react way

**Comment by krassowski** [comment]
In many cases this should be now possible now in 2025 given the implementation of aria element reflections in the browser: https://wicg.github.io/aom/aria-reflection-explainer.html such as https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaLabelledByElements
