### ISSUE TITLE
Perf reporting wrong wasted time on connected component

### ISSUE THREAD

**Issue by petarslavnic** [facebook/react#8513]
On each redux state change, Perf reporting wasted time on connected component. Even if props are not changed.

Example from project: https://github.com/petarslavnic/react-todo
<img width="683" alt="example" src="https://cloud.githubusercontent.com/assets/1445754/20966094/0aed4bee-bc79-11e6-86d6-2280ce4dfa49.png">

Using:
react: 15.4.1
react-dom: 15.4.1
react-redux: 4.4.6
redux: 3.6.0
reselect: 2.5.4
immutable: 3.8.1
react-addons-perf: 15.4.1

@gaearon This is a note for you, to check later. Thanks.

**Comment by cbengtson85** [comment]
@gaearon  @petarslavnic This may be a little off topic but I didn't want to start a new thread on this...how do I view the wasted time with the Chrome performance tools?

**Comment by gaearon** [comment]
I'm closing since ReactPerf is not available in React 16. We might resurrect it in the future, but for now it's not clear how it should work with the new algorithm.

>how do I view the wasted time with the Chrome performance tools?

There's no such functionality right now. But you can see from the [performance tab](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) which components are re-rendering. That should give you an idea if something re-renders but it shouldn't. You can also use "Highlight Updates" checkbox in React DevTools to highlight updating components (note it only works correctly in React 16 and higher).
