### ISSUE TITLE
React-DOM Server still generate data-reactid

### ISSUE THREAD

**Issue by rohmanhm** [facebook/react#8537]
https://facebook.github.io/react/blog/2016/04/07/react-v15.html#document.createelement-is-in-and-data-reactid-is-out

I still get the `data-reactid` attribute in my html when using `ReactDOMServer.renderToString(element)`

Here version of my **react** and **react-dom**

```
"react": "^15.4.1"
"react-dom": "^15.4.1"
```

**Comment by koba04** [comment]
Yes, it is mentioned in the post as a Note.

> Note: data-reactid is still present for server-rendered content, however it is much smaller than before and is simply an auto-incrementing counter.

https://facebook.github.io/react/blog/2016/04/07/react-v15.html#document.createelement-is-in-and-data-reactid-is-out

**Comment by rohmanhm** [comment]
Oh, I miss it. 🤔

Thanks before

**Comment by mocheng** [comment]
For server-side-rendering, `renderToString` result never matches browser-side-generated DOM. Even though we can use `renderToStaticMarkup`, I suppose browser-side-generated DOM always replaced the server rendered HTML, since there is no `checksum` attribute at all.

**Comment by gaearon** [comment]
This is not the case. You have a different problem. It's not clear what exactly since you didn't supply the code, but your conclusion is mistaken.

React 15 generates the same markup on the client *when rehydrating* from the server markup. We don't compare the DOM itself, just the strings. The process hasn't changed.
