### ISSUE TITLE
Failed to find a valid digest in the 'integrity'

### ISSUE THREAD

**Issue by BrunoQuaresma** [facebook/react#8549]
When i run the build command and upload my files to server this error appears in mobile browsers:

Failed to find a valid digest in the 'integrity' attribute for resource 'http://facilbardelivery.com.br/static/css/main.33fa5f7d.css' with computed SHA-256 integrity 'fhBe+EZQ6zPH/PQFiIlVZjwvoWQGAWe1s8BEyp2TJ6k='. The resource has been blocked.

**Comment by gaearon** [comment]
If you use Create React App, please file issues about it [in its repository](https://github.com/facebookincubator/create-react-app).
This issue tracker is for React itself.

That said, does [this](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#subresource-integrity-checks-fail) solve your problem?

I'm closing the issue since it's not related to React but you're welcome to reopen it [here](https://github.com/facebookincubator/create-react-app/issues/new) if the link above doesn't help.
Cheers!

**Comment by BrunoQuaresma** [comment]
Ohh, sorry.
