### ISSUE TITLE
Iframe's reinitialise when moving down within a group of components

### ISSUE THREAD

**Issue by pieterv** [facebook/react#858]
When moving a component with an iframe down within a group of components it reinitialises the iframe. The iframe only reinitialises when moving down, moving upward seems to work fine.

Example: http://jsfiddle.net/pieterv/fnkLf/

**Comment by Prinzhorn** [comment]
I have a related issue with iframes which needs a different fix. I have a component using the Twitter API to embed a tweet in `componentDidMount`. This works great, until the component is rearranged by react (it's part of a list and has a key). When this happens, the iframe becomes completely empty. It can't just reload the src because the Twitter API does JavaScript magic directly with the iframe. I would need to clean up the iframe and load a new one using the API when this happens.

So the problem here is that the component has no way of knowing that this just happened. There is no lifecycle method telling it about the DOM manipulation (sth. like `componentDidRemount`?). Since the component also uses the PureRenderMixin literally nothing happens to it when it gets moved in the DOM. It doesn't seem possible for me to fix this outside of react.

**Comment by aduth** [comment]
>Would using CSS Flexbox's box-ordinal-group to rearrange iframes help? That way you don't need to remove either iframe from the DOM. Of course, this would only work on newer browsers, and would be something one would write themselves on top of React.

I was able to find some success in using Flexbox's `order` property:

- Before: https://codepen.io/aduth/pen/QvpxwL
- After: https://codepen.io/aduth/pen/eWvKeW

More a hack than a general solution really, but seems to be working well enough for my purposes.

**Comment by afercia** [comment]
5.4.1. Reordering and Accessibility
https://www.w3.org/TR/css-flexbox-1/#order-accessibility

**Comment by gaearon** [comment]
This problem is both rare and hard enough that it is unlikely we’ll be spending our time on this.

The complexity and increase in the code size this will introduce is probably not worth the effort.
So I’ll close this issue as unsolved.

I’m open to reviving it if somebody comes up with a simple solution to this, but I just don’t see it.

**Comment by flackeryy** [comment]
18.07.2022 this issue still here

**Comment by Vizards** [comment]
Apologies for resurrecting this old issue, but change is coming.

Thanks to the experimental support for [moveBefore](https://developer.chrome.com/blog/movebefore-api?hl=zh-cn) (Chrome 133+) added in React 19 (https://github.com/facebook/react/pull/31596), moving an `iframe` within a list no longer triggers a reload of the iframe! I've created a demo using native HTML Drag and Drop：

https://github.com/user-attachments/assets/19d68cb3-83c8-4664-876c-e624c76f2bf7

In the web page, there are 4 iframes, each embedding a `video`. One of the iframes has a DOM structure like this:

<img width="727" alt="Image" src="https://github.com/user-attachments/assets/70929e04-fdc2-4ea3-bb0d-05a574457638" />

During my movement, the iframe did not reload, and the video did not replay. Everything worked as we expected.
