### ISSUE TITLE
[Feature Request] Support GestureEvent API

### ISSUE THREAD

**Issue by dlindenkreuz** [facebook/react#8600]
The [GestureEvent API](https://developer.mozilla.org/en-US/docs/Web/API/GestureEvent) is a currently non-standard API to target touch events on **non-touchscreen** computers, e.g. pinch gestures on a laptop trackpad.

Safari supports this starting from version 9.1 and is currently the sole browser to do so. Apple uses this API for enhancing Apple Maps widgets with "native gestures". A live example can be seen on the [WWDC page](https://developer.apple.com/wwdc/attending/).

Currently, it seems impossible to attach the event handlers for `gesturestart`, `gesturechange` and `gestureend` declaratively via React elements. The only solution is to attach the event handlers manually in `componentWillMount`, `componentDidMount` or as part of ref callbacks. A proper implementation would be highly appreciated!

NB: Microsoft rolls their own version with `MSGestureEvent`. Its usage seems less straightforward, though. MSDN Links: [Usage](https://msdn.microsoft.com/en-us/library/dn433243(v=vs.85).aspx) · [API](https://msdn.microsoft.com/en-us/library/hh772076(v=vs.85).aspx)

**Comment by aweary** [comment]
I don't think we would want to adopt support for a non-standard API. If a specification is proposed we can consider adoption on the specification has been reviewed, and as long as it can be reliably and performantly polyfilled for all other browsers that React supports.

At this point, I think it's too early to consider supporting this, but we appreciate the issue! I'm going to close this out, since I feel relatively confident that the rest of the React team feels similarly.

cc @gaearon if this is something you guys do want to pursue, let me know.
