### ISSUE TITLE
Dot notation for shape props: <Foo bar.first="something" />

### ISSUE THREAD

**Issue by jukkah** [facebook/react#8601]
**Short**: What about `<Foo bar.first="something" />`?

**Long**:
Lets have a class Foo:
```js
class Foo extends React.Component {
  static propTypes = {
    bar: React.PropTypes.shape({
       first: React.PropTypes.any,
       second: React.PropTypes.any,
    }),
  }
}
```

Is it possible to say `<Foo bar.first="something" />` and it sets only `first` but not `second`? In addition, if saying `<Foo {...defaults} bar.first="something" />`, it wouldn't override `second` (if defined in `defaults`).

If this is not possible (as I think) and you think it should be, please vote this up.

**Comment by gaearon** [comment]
You can already do this explicitly:

```js
<Foo bar={{ first: 'something' }} />
```

or

```jsx
<Foo {...defaults} bar={{ ...defaults.bar, first: 'something }} />
```

It is slightly more verbose but there is no magic and you have full control over how “merging” works. For example, if you used Immutable.js, it could be something like:

```jsx
<Foo {...defaults} bar={defaults.bar.merge({ first: 'something' })} />
```

In general, we prefer having a few generic ways to do something instead of creating “sugar” that requires a lot of learning and has to be “unrolled” whenever you bump into a more complex case.

Therefore I doubt we will implement something like your proposal.

In any case, if you have ideas for improving JSX, please share them in http://github.com/facebook/jsx instead. React just uses JSX but the grammar itself is discussed there.

I hope this helps!
