### ISSUE TITLE
Infinite loop when error is thrown in `render` method.

### ISSUE THREAD

**Issue by roadhump** [facebook/react#8653]
There is an infinite loop when there are components with error on render and with `onMount` callback, which calls update of parent component.

Here is code https://jsfiddle.net/8nh7hobv/

When I run this code, I have unexpected infinite loop. I expect code to stop on thrown error. 

Suddenly, if I change `render` method of `Main` component to 

```
render() {

        return (
            <div>{''} // just add an empty text node here
                {this.state.item ? (
                    <div>
                        {'something'}
                        <WithOnMount
                            onMount={this.handleOnMount}
                        />
                        <WithError />
                    </div>

                ) : 'nothing'}
            </div>
        );

    }
```

it works as expected. Here is code with correct behaviour https://jsfiddle.net/d18jnq0p/

I get this bug with React-ReactDOM 15.4.1, it looks like version 0.14.7 works correct in both cases.

**Comment by devjunkORG** [comment]
@roadhump I can't see `onMount` documented anywhere, could you point that out for me? 

Anyway, at first sight, this seems like a bug in your code, since you're re-rendering the tree with the state change on `this.handleOnMount`, which in turn mounts the component again.

**Comment by KerenChandran** [comment]
Hey so I'm a bit of a newbie to the repo but I'll do my best to help you out.

What I don't understand is why would you want to call an error in the render function? If you're creating a component that will throw an error in render, can't you just use componentDidMount to throw the error and render out the content on error? Otherwise, you'll continuously throw errors every time the component re-renders. Ie.

```JS
class WithError extends Component {
  componentDidMount() {
    console.log('WithError error')
    throw new Error('WithError error');
  }

  render() {        
    return (
      <div>{'WithError'}</div>
    );
  }
};
```

If this is not the best solution for you, can you tell me what you're trying to achieve?

@devjunkORG I believe onMount is a function he created for the main component that will act as a callback to update the state of the parent component to trigger a single re-render. However, I don't think the callback is the issue. As mentioned above, I believe the issue has to do with throwing an error in the render function.

**Comment by gaearon** [comment]
React 16 doesn’t get into an infinite loop with this example.
