### ISSUE TITLE
Bug, Input onChange event

### ISSUE THREAD

**Issue by bORm** [facebook/react#8696]
Hi, i created jsfiddle example for view how work onchange event of native html and react

https://jsfiddle.net/69z2wepo/66844/

React onChange event worked as onInput and consoled every one of keydown or keyup event( i dont know )

See
http://www.w3schools.com/jsref/event_onchange.asp

The onchange event occurs when the value of an element has been changed.

Tip: This event is similar to the oninput event. .... while onchange occurs when the element loses focus, ....

I am try set 1.0 value to both inputs and what i see in console

React input consoled every key press
```
React input value 1
React input value 
React input value 1.0
```

html input consoled only after input loss focus
```
Base input value 1.0
```

**Comment by alanschlindvein** [comment]
This consoles as expected for type="number"

http://w3c.github.io/html-reference/input.number.html
https://bugs.chromium.org/p/chromium/issues/detail?id=74120

**Comment by bORm** [comment]
Okay,
i changed it to type text
https://jsfiddle.net/69z2wepo/66912/

and i don`t see any changes

**Comment by gaearon** [comment]
This is intentional, not a bug. The browser event name is confusing, and many people expect `onChange` to run "on change" rather than on blur. This is especially important for controlled inputs in React. So React just makes `onChange` work "on change", [as documented here](https://facebook.github.io/react/docs/dom-elements.html#onchange). You can find other differences with DOM documented [on the same page](https://facebook.github.io/react/docs/dom-elements.html). I hope this helps!
