### ISSUE TITLE
Broken link in react tutorial

### ISSUE THREAD

**Issue by dyladan** [facebook/react#8699]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

broken link in the first section of https://github.com/facebook/react/blob/master/docs/tutorial/tutorial.md

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

N/A

**What is the expected behavior?**

Link should go to a working version of tic-tac-toe on codepen

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

N/A

**Comment by gaearon** [comment]
Oops.

<img width="746" alt="screen shot 2017-01-06 at 15 47 41" src="https://cloud.githubusercontent.com/assets/810438/21723204/7ecc27a4-d427-11e6-80e0-b9edf9de1fad.png">

@lacker @ericnakagawa Can we get a PRO account?

**Comment by lacker** [comment]
Which link exactly is not working? https://s.codepen.io/ericnakagawa/debug/ALxakj is a working link for me - I dunno if @ericnakagawa fixed something though. AFAICT this one link is the only time we use codepen `/debug/` which is the problem here - if we had to make all codepen links come from a "react" account it would be fairly annoying.

**Comment by gaearon** [comment]
I think @ericnakagawa might have fixed it somehow!

**Comment by andys8** [comment]
@gaearon I'd suggest switching to the `/full/` link instead.

**Comment by gaearon** [comment]
Closing since it appears to work.
¯\\_(ツ)_/¯
