### ISSUE TITLE
Constructor requires 'new' operator

### ISSUE THREAD

**Issue by Sivart-me** [facebook/react#8702]
ReactCompositeComponent.js has two calls to the Component class construction which are missing use of the 'new' operator.

The calls are like this:
Component(publicProps, publicContext, updateQueue)

and are here:
https://github.com/facebook/react/blob/47f92b940fefe4e57b8404c52f5dd32560a78412/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L455

and here:
https://github.com/facebook/react/blob/47f92b940fefe4e57b8404c52f5dd32560a78412/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L460

**Comment by gaearon** [comment]
This is intentional. We check if we *need* to construct [here](https://github.com/facebook/react/blob/47f92b940fefe4e57b8404c52f5dd32560a78412/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L201), and then use it to either call `new` or not.

This lets us support functional components and factory components:

```js
// Functional component
function Foo(props) {
  return <div />;
}

// Factory component
function Bar(props) {
  return {
    render() {
      return <div />;
    }
  }
}
```
