### ISSUE TITLE
separate out reactJS-style-inline-styling --> css-style styling as another npm module

### ISSUE THREAD

**Issue by devdoomari** [facebook/react#8713]
First of all, thanks for making ReactJS, and spreading its core ideas to others.

Anyway, the gist of this issue is : how about separating out 
- https://github.com/facebook/react/blob/master/src/renderers/dom/shared/CSSProperty.js
- https://github.com/facebook/react/blob/master/src/renderers/dom/shared/CSSPropertyOperations.js
- (+ other files for styling?)
into another npm module?

Here's my situation:
I'm using RxJS + React for animation, and I'm using a direct-to-dom method for performance. I did it by creating a 'StyleStreamedComponent' which can be used like this:
```typescript
<StyleStreamedComponent
   tagName="div"
   styleStream={animationStream  // 0 ~ 1. follows timer / scroll / whatever I like.
      .map((x => {
         const opacity: tween.power3(x);
         return {
            transform: `translate(0, ${x * window.innerHeight * 0.5})`,
            opacity, 
         }
      });
   }
>
   <h1> animation here. </h1>
</StyleStreamedComponent>
```

For the StyleStreamedComponent implementation, I'm resorting to a disgusting hack as I'm not very fond of importing a reactJS-internal code:
```typescript
export class StyleStreamedComponent {
    componentDidMount() {
        this.styleSubscription = this.props.styleStream
            .subscribe((newStyle) => 
                // save this.style in case of re-render.
                this.style = Object.assign(this.state.style, newStyle);
                _.forEach(newStyle, (value, key) => {
                     if (_.includes(requirePxStyles, key)) {
                         if (value.constructor == Number) {
                             targetDOM.style[key] = `${value}px`;
                             return;
                         }
                    }
               targetDOM.style[key] = value;
        });
    }
```

ps: separating out those CSS-utility functionalities into a npm module might be helpful to other library-maintainers/authors as well.

**Comment by aweary** [comment]
Hey @devdoomari, thanks for the request. Sorry, it took so long to respond! I don't think this is something we'd want to do. Extracting an internal module into an external one makes it more difficult to iterate on new features and address bug fixes since it requires orchestration with the package's release cycles.

Feel free to use those files as inspiration for your own utilities though! A lot of the stuff in there wouldn't be entirely relevant outside of the context of React internals anyways, so you may be better of defining your own, tailored utility based off the functionality it provides.
