### ISSUE TITLE
Is there anything I should consider if I'm adding to React.Component's prototype?

### ISSUE THREAD

**Issue by Aftabnack** [facebook/react#8813]
I want to have some functions by default in all my components that I am creating. So the best way to do this is to add to the prototype chain of the React.Component.

If I were to add a default implementation to the life cycle hook of the component, will something misbehave??

Example:

```javascript
let defaults = {
	doSomething: function() {
		console.log("I'm added to all components")
	},
	shouldComponentUpdate: function (nextProps) {
		return !deepEqual(nextProps, this.props);
	}
};

React.Component.prototype = Object.assign(React.Component.prototype, defaults);
```

**Comment by gaearon** [comment]
This is not at all recommended because it’s changing behavior of any third party components too (which might break them), and is very surprising to any new developer in your codebase (maybe even to you in a couple of months). Please create a custom base class instead if you think this is important. In general though, we discourage using inheritance with React components.

As for your specific example, a `shouldComponentUpdate` implementation that calls `deepEqual` will make performance *worse* in many cases because deep equality checks can be much more expensive than reconciliation.

I hope this helps!

**Comment by Aftabnack** [comment]
Regarding the specific example, in my usage I could never avoid maintaining references of the root level attributes in the props object, So React.PureComponent is not helping me.

And I've observed deepEqual checks to be cheaper compared to reconciliation since I have huge component structure.

**Comment by gaearon** [comment]
It really depends on a specific example. Your data structures may change in the future, and deep equality comparisons may get more expensive. If it’s “invisible” then it would be very hard for the next developer to figure out what is going wrong. I really suggest explicitly declaring a `shouldComponentUpdate` method in all components that do it, even if it just calls `deepEqual`. At least this way it’s hard to miss.
