### ISSUE TITLE
Feature Request: Binding utils to elements

### ISSUE THREAD

**Issue by Quanthir** [facebook/react#8820]
**Do you want to request a *feature* or report a *bug*?**
feature

First of all, I am not expert on React I am only using it for 2 weeks. So if this is a silly request, please forgive me.

There should be a binding method for elements to prevent code repeating and additional operations on the element / Component.

For example: for binding and updating state for inputs, I need to write same thing for every component that I design. So there should be something like this:

```javascript
import React, { Component } from 'react';
import autoState from './autostate';

export default class LoginForm extends Component {
    constructor(props) {
        super(props);
        this.handleSubmit = this.handleSubmit.bind(this);

        this.state = {
            username: '',
            password: ''
        };
    }

    handleSubmit(e) {
        // Code...
    }

    render() {
        return (
            <form onSubmit={this.handleSubmit}>
                <input type="text" name="username" bind={autoState} />
                <input type="password" name="password" bind={autoState} />
            </form>
        );
    }
}
```

autostate.js
```javascript
export default function autoState(e, attributes, node) {
    this.setState({ [attr.name]:  e.target.value });
}
```
with this, I can create utils to use in elements. I can even use jQuery for some manipulations or add behaviors to the elements that I need without creating too many components.

Renderer just needs to bind `this` to functions that added to bind attribute. (bind should accept array for multiple bindings.)

I know that I can create an input component to do this automaticly but I didn't make any tests but I believe this way will be more fast than creating nested component for everything since React looks components to check if they should update.

Please do not think this example as main purpose of this. This kind of feature will open up many posibilities.

**Comment by aweary** [comment]
Thanks for the issue @Quanthir! Hope these first two weeks have been enjoyable 😃 We actually used to have something very similar to what you're proposing: [`LinkedStateMixin`](https://facebook.github.io/react/docs/two-way-binding-helpers.html) let you use `valueLink` to and `this.linkState` to make two-way bindings easier, similar to your `autoState` function. This was deprecated due to low popularity.

We recommend being explicit about your data bindings instead. It may be a little more verbose, but it makes it easier to reason about what a component is doing (in your example I'd have to go find `autoState` to know that it's using the `name` property for the state property name). It's also unlikely that we'd expand the public component API (special casing the `bind` prop) since this is already doable by just binding the methods yourself.

Hope that helps!
