### ISSUE TITLE
disabled button onClick handler triggered erroneously

### ISSUE THREAD

**Issue by krisyoung** [facebook/react#8826]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
For buttons with children other than text nodes, when the disabled attribute is true, click handlers are still triggered

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
load code pen and check react v 15.4.0, observe button click behaviour for both instances
http://codepen.io/anon/pen/xggoOw

**What is the expected behavior?**
button click should not trigger on click handler

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
bug appears in v15.4.0
behaviour is correct in v15.3.1

**Comment by aweary** [comment]
Thanks for the report @krisyoung. This issue was resolved with the 15.4.1 release. The PR that fixed this was https://github.com/facebook/react/pull/8387.

[Here's a Codepen](http://codepen.io/anon/pen/oBBKBd) running the latest release (15.4.2) showing that the issue no longer occurs. You should be able to safely update to 15.4.2 since they were just patch releases!

Hope that helps.

**Comment by krisyoung** [comment]
Thanks, my bad for not checking there was a 15.4.x
