### ISSUE TITLE
blank page is coming on apache server

### ISSUE THREAD

**Issue by flik** [facebook/react#8844]
**Do you want to request a *feature* or report a *bug*?**
http://localhost/react/examples/jquery-bootstrap/

**What is the current behavior?**
Blank page is coming

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**
there must be running example
**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Comment by aweary** [comment]
@flik thanks for the issue! I believe that example only works when you run a static server in the directory. Check out https://github.com/facebook/react/issues/8664. I'm going to close this out in favor of https://github.com/facebook/react/issues/8664, because I think we should either 1) make it clear in the instructions or 2) get rid of the example all together.
