### ISSUE TITLE
Remove or rewrite examples

### ISSUE THREAD

**Issue by aweary** [facebook/react#8874]
Prompted by https://github.com/facebook/react/pull/6925#issuecomment-275452387. Our examples are really not great examples of how to use React. They are not maintained at all and add little value.

We should consider either:

1. Rewriting all the examples so they are easier to use and represent good practices.
2. Rewrite only a couple and remove all the rest
3. Remove all examples

I'm partial to just removing all of them, or if anything providing a single example that is well built.

cc @gaearon @spicyj @bvaughn

**Comment by bvaughn** [comment]
> I'm partial to just removing all of them, or if anything providing a single example that is well built.

👍 Haven't thought about this much, but my initial reaction is that the "examples" in this repo have been superseded by create-react-app.

A redundant set of poorly-maintained examples is worse than no examples at all. I agree with your sentiment to either remove or do some drastic spring cleaning.

**Comment by gaearon** [comment]
There are some nice community examples like http://andrewhfarmer.com/sample-apps-create-react-app/.
Maybe we could get people to contribute more?

**Comment by nhunzaker** [comment]
Second vote for removing the examples folder. The only times I've used the examples have been for testing DOM behavior. That has been superseded by the DOM fixtures. 

If they were to stay, I'd vote for reworking examples to solve specific problems. That's usually what I look for when I open up an examples folder. Otherwise I go straight to a quick start guide or docs pages.

The sidebar for the new site could be a good source of inspiration for new examples:

<img width="307" alt="screen shot 2017-01-28 at 8 46 08 am" src="https://cloud.githubusercontent.com/assets/590904/22397058/b11eb0f8-e536-11e6-8071-d0e2e0507bc2.png">

Maybe something like:

```
- hello-world
- using-react-without-jsx
- handling-events
- conditional-rendering
- using-keys
- forms
- lifting state
```

**Comment by gaearon** [comment]
I was thinking we should use examples for more holistic apps (e.g. calculator, GitHub repo browser, etc) to show *how to solve problems* instead of just repeating the docs.

**Comment by nhunzaker** [comment]
Ah, I think I have the same motivation (and not to necessarily copy the docs verbatim). If sample apps makes it easier for people to learn, that sounds good to me.

**Comment by aweary** [comment]
Do we want to create our own example applications or just maintain a small list somewhere of external applications that we recommend reviewing?

**Comment by bvaughn** [comment]
+1 for maintaining a list of recommended (external) examples

**Comment by nhunzaker** [comment]
@aweary What is the next step forward here? We've removed the examples folder, do you think the [list here](https://github.com/facebook/react/wiki/Examples) is an adequate start (also linked from the footer of the docs website)

**Comment by gaearon** [comment]
Yea, that's fine for a start. I think we can close this for now.
