### ISSUE TITLE
missing property of props getting respective defaultProps property ref instead of a copy. Is that correct?

### ISSUE THREAD

**Issue by sanjay1909** [facebook/react#8925]
**Do you want to request a *feature* or report a *bug*?**
Bug 
or undocumented behavior of props and defaultProps
or my understanding on defaultProps could be wrong

**What is the current behavior?**
1. props: read-only (not for non-primitive object)
2.  if value not supplied through parents, props missing value expected to make a copy of the respective defaultProps value, instead they hold on to its ref in defaultProps

**minimal demo of the problem**
Link is Self Explanatory
https://sanjay1909.github.io/React-defaultProps/

**What is the expected behavior?**
1. props: read-only 
2. props missing value expected to make a copy of the respective defaultProps value,  if value not supplied through parents.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest version of ReactJS

**Comment by aweary** [comment]
Thanks for the issue @sanjay1909, and for the repo reproducing your issue!

> if value not supplied through parents, props missing value expected to make a copy of the respective defaultProps value, instead they hold on to its ref in defaultProps

React will pass values from `defaultProps` directly to props, not copies of those values. You can see that code here: [ReactElement.js#L232-L239](https://github.com/facebook/react/blob/6810627a91f2020caee7fecf21580187dc6ef0fc/src/isomorphic/classic/element/ReactElement.js#L232-L239). We do [freeze `props` in development mode](https://github.com/jimfb/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L108-L111), but unfortunately that doesn't prevent you from mutating already existing values.

We don't recommend mutating anything coming from `this.props`, regardless of whether its coming from a parent component or `defaultProps`. It's better to pass down methods to update that data in the parent component. For example:

Instead of doing this:
```jsx
    const newCount = this.state.clickCount + 1;
    this.props.defaultArray.push(newCount);
```

You can do:

```js
  const newCount = this.state.clickCount + 1;
  this.props.addNewCount(newCount);
```

So no, React does not make copies of values in `defaultProps` and in general it's a good idea to avoid mutating anything coming from `this.props` in the first place.

I hope that clears things up a bit! Let me know if you have any other questions.

**Comment by sanjay1909** [comment]
Thanks, pointing to code was really helpful, I will change my repo's ReadMe as "bad Practice to avoid while using default props". Thanks a lot.
