### ISSUE TITLE
Use High-resolution time for measuring performance in react-perf

### ISSUE THREAD

**Issue by adamziel** [facebook/react#8929]
React-perf could give sub-millisecond precision using the new performance api:
https://www.w3.org/TR/hr-time/

It seems it is pretty well supported too:
http://caniuse.com/#feat=high-resolution-time

**Comment by gaearon** [comment]
Pretty sure that is what we are using, is it not?

**Comment by adamziel** [comment]
I didn't see any meaningful results when searching by "performance" on github, but maybe it's called in some different way. Is there any way to display sub-milliseconds units in results printed by  `ReactPerf.printExclusive()` etc?

**Comment by gaearon** [comment]
We're using a [polyfill](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/performance/performanceNow.js) from fbjs.

No, there's no way because those numbers are not really actionable. If we displayed them, people would over-obsess with optimizing them when there's very little to optimize.

I think you *can* get the raw measurements if you want to, with `ReactPerf.getLastMeasurements()`.
