### ISSUE TITLE
Disabled attribute ignored on div[role="button"] with onClick when clicked

### ISSUE THREAD

**Issue by joshbroton** [facebook/react#8977]
I'm using ARIA role=button on some div elements. They are disabled at times, but the disabled attribute is being ignored by React and the onClick event is being triggered. 

I've created a fiddle illustrating the issue: https://jsfiddle.net/joshbroton/mr7gn5vv/8/

I'd expect that onClick would not be triggered on elements when disabled={true}, especially if role="button". 

I am using React 15.4.1. JSFiddle is 15.4.2.

**Comment by aweary** [comment]
Hey @joshbroton thanks for the report and the fiddle! This is expected behavior as far as I know. You cannot disable events on a div using the `disabled` attribute. You can see what elements can be disabled in the [HTML spec](https://www.w3.org/TR/html5/disabled-elements.html#disabled-elements)

[Here's a fiddle](https://jsfiddle.net/ckyajq8w/) using plain HTML that demonstrates this. Even though the `disabled` attribute is specified the click handler is still triggered. If possible you should use an actual form element, such as a `button` if you need to be able to disable it.

Hope that helps!

**Comment by joshbroton** [comment]
Thanks! I was under the impression that role="button" made it behave exactly like a button, since screen readers see it as a button. TIL.
