### ISSUE TITLE
Add new typechecking rule for class inherit

### ISSUE THREAD

**Issue by zslucky** [facebook/react#8983]
I'm not sure is it possible or necessary to do this, but I got the trouble here, please see the example code below:
```javascript
class Grandpa extends React.Component {}

class Parent extends Grandpa {}

class ChildOne extends Parent {}
class ChildTwo extends Parent {}
class ChildThree extends Parent {}

class TestComponent extends React.Component {
    render() {
        const CustomComponent = this.props.component;
        return <CustomComponent />
    }
}
TestComponent.propTypes = {
    // component: React.PropTypes.class.inheritOf(Parent)
    // or
    // component: React.PropTypes.class.inheritOf(Grandpa)
};

class Main extends React.Component {
    render() {
      return (
          <TestComponent
            component={ChildOne}
          />
      );
    }
}
```

As I add some common function in `Parent` or `Grandpa` class, so the component passed into `TestComponent` should inherit from these classes. then some component can work correctly.

I tested `ChildOne.prototype instanceof Parent` and `ChildOne.prototype instanceof Grandpa` are both correct, so is it necessary to add this rule?

**Comment by aweary** [comment]
Hey @zslucky, thanks for the idea. We don't encourage using inheritance patterns with React components. Check out [Composition vs Inheritence](https://facebook.github.io/react/docs/composition-vs-inheritance.html) in our docs for more details.

Since it's not a pattern we encourage, it's unlikely we'd want to provide an API in support of it. Hope that helps!

**Comment by zslucky** [comment]
Thanks @aweary.
