### ISSUE TITLE
DoubleClick/Click event not firing 

### ISSUE THREAD

**Issue by emy14** [facebook/react#9022]
Hello,
I am trying to generate a doubleClick with document.getElementById('id').OnDoubleClick() but with no success. I tried the same with onClick here : http://jsfiddle.net/z2hdqw7L/2/
Beside it is working just fine without React : http://jsfiddle.net/mlms13/JfQJE/4/ 
An idea why it's not working ? 
Thank you

**Comment by Jayflux** [comment]
hi @emy14 your first link with react is working fine for me.
What OS/browser and version are you using?

**Comment by emy14** [comment]
You succeed to generate OnDoubleClick with document.getElementById('id').OnDoubleClick() ? without clicking with the mouse? 
I am using XUBUNTU 16.10 with firefox 51 (try also on nightly version)

**Comment by aweary** [comment]
Hey @emy14, thanks for the report. The reason your example doesn't work is because React doesn't attach event listeners directly to each element; it has a single event listener on the `document` and using capturing to implement a synthetic event system.

This means that there is no `onDoubleClick` event handler attached to that element. If you wanted to force the event handler to be called you could just call it (`this._handleDoubleClickitem()` or pass it to another component via `props` to be invoked at another point).

If you must generate an actual event you would have to call `dispatchEvent` with an instance of `MouseEvent`. See [this JSFiddle](https://jsfiddle.net/4z146ate/) with a working example of that.

Hope that helps!

**Comment by Jayflux** [comment]
ahh i misread
