### ISSUE TITLE
DOM is not rendered before componentDidUpdate

### ISSUE THREAD

**Issue by luunam** [facebook/react#9033]
From my understanding componentDidUpdate is called after a component is re-rendered. However, if  I take the code from Facebook React tutorial and add these 2 functions to class Game (its codepen is here https://codepen.io/anon/pen/zNgBQV)
```
sleep(milliseconds) {
    let start = new Date().getTime();
    for (let i = 0; i < 1e7; i++) {
      if ((new Date().getTime() - start) > milliseconds){
        break;
      }
    }
  }
  
  componentDidUpdate() {
    this.sleep(2500);
  }
```
then it takes 2.5 seconds after every click for react to update the page, instead of updating the DOM then sleep for 2 seconds. Is this an expected behavior? If I need a function that only triggers after the page is updated then what should I use?

**Comment by syranide** [comment]
Expected behavior. `componentDidUpdate` is called after rendering to DOM and before yielding to the browser. So the browser has the new DOM but has not yet rendered the new viewport. There has been talks about async versions of these as well, but your solution for now is to defer it somehow, `setTimeout`, `requestAnimationFrame`, etc.

**Comment by luunam** [comment]
Thanks, it would be nice if we have something like `componentDidRender`, but `requestAnimationFrame` works for me.
