### ISSUE TITLE
this.props inside a method no longer works

### ISSUE THREAD

**Issue by cyberhck** [facebook/react#9095]
**Do you want to request a *feature* or report a *bug*?**
I believe this might be a bug, I'm not 100% sure. A little while ago, with `react-scripts: 0.7.0`, I could do something like this:
```
class MyComponent extends React.Component{
    render(){
        return (<div>Hello {this.props.name}</div>
    }
}
```
And It'd work fine

But now, it says

> Cannot read property 'name' of undefined

I can still do
```
class MyComponent extends React.Component{
    constructor(props){
        super(props);
        this.name = props.name;
    }
    render(){
        return (<div>Hello {this.name}</div>
    }
}
```

I've tried to reproduce that in https://github.com/cyberhck/react-test-bare project.
PS:
this [commit](https://github.com/cyberhck/react-test-bare/commit/0d9d8f08f4fe82d265349aae19a0a76eb6dc9b36) results in failure of tests

**What is the expected behavior?**

I was expecting that to work.

It used to work before, but now it won't work.

Or is it the intended behavior? Or am I doing something wrong?

**Comment by gaearon** [comment]
Your first snippet looks perfectly fine to me. I don't see your first snippet of code in the project you provided. Can you clarify *which* of three different code snippets (two in this post, one in the commit you provided) you expect to work but it fails? And can you please update the project to show that failing version so that we could take a look at it and reliably reproduce what confuses you?

**Comment by hfter789** [comment]
@cyberhck You are missing the argument props in the constructor here: https://github.com/cyberhck/react-test-bare/blob/master/src/Hello.js#L4.
And when you try to console log, you can do 
`console.log(props.name)`
instead of 
`console.log(this.props.name)`

**Comment by gaearon** [comment]
Your first example has a compile error. You have an extra `(` that isn’t matched:

```js
class MyComponent extends React.Component{
    render(){
        return (<div>Hello {this.props.name}</div>
    }
}
```

If we fix it to not have extra parens, it works fine:

```js
class MyComponent extends React.Component{
    render(){
        return <div>Hello {this.props.name}</div>;
    }
}
```

https://jsfiddle.net/kroz6mkb/

You definitely **should not** do something like `this.name = this.props.name`. Component props can change over time, so this way you risk having stale props. Always use `this.props` (or `this.state`) in render.

In [this particular commit](https://github.com/cyberhck/react-test-bare/commit/0d9d8f08f4fe82d265349aae19a0a76eb6dc9b36) the problem, as explained by @hfter789, is you’re not passing `props` to `super`, and so `this.props` is undefined until the constructor finishes. If you passed `super(props)` then it would not be a problem. But in any case **you should not write your code this way**: just use `this.props.name` everywhere, and don’t assign it to instance fields.

I’m closing because I don’t see any bugs in React here. I recommend you to [read the official documentation](https://facebook.github.io/react/docs/hello-world.html) to get more comfortable with React. There are many runnable Codepen examples in it.

I hope this helps!

**Comment by cyberhck** [comment]
Ahh, how stupid of me, thanks. This works, looks like I had a faulty constructor, otherwise the first snippet was working fine.

Thanks @gaearon

**Comment by cyberhck** [comment]
@gaearon sorry for bothering you again, I just wanted to ask a follow up on this issue.
I understand why was the confusion when I created this issue.

I created a new repo and tried to reproduce what I did earlier,
on this [line](https://github.com/cyberhck/javascript-props-demo/blob/master/src/App.jsx#L5), I'm calling super without the props,
and on this [line](https://github.com/cyberhck/javascript-props-demo/blob/master/src/App.jsx#L9) I'm using that props to render, I'm passing the props from [index.jsx](https://github.com/cyberhck/javascript-props-demo/blob/master/src/index.jsx#L5) when I do a npm start, and navigate to [localhost:8080](localhost:8080), it just works.

I tried to not accept the props in constructor like: 
```diff
diff --git a/src/App.jsx b/src/App.jsx
index 91e4b71..b16e988 100644
--- a/src/App.jsx
+++ b/src/App.jsx
@@ -1,11 +1,11 @@
 import React from "react";
 
 export default class App extends React.Component {
-	constructor(props){
+	constructor(){
 		super();
 	}
 
 	render() {
 		return <div>{this.props.user}</div>
 	}
}
```

It still works. When I created this issue I was expecting it to work, then when @hfter789 mentioned, I missed the props, I was under the impression that this shouldn't work and it makes sense as we didn't pass react the parameter.

But in the project I showed you, it is working without complaining about anything. Did react just change the way props are passed into? or is it passed during `componentWillReceiveProps` lifecycle hook?

I was surprised that it didn't work that time.

Now I'm kinda curious (and surprised) why this is working now.

**Comment by gaearon** [comment]
As I mentioned above:

>you’re not passing `props` to `super`, and so `this.props` is `undefined` **until the constructor finishes**

While you're *inside* the constructor, `this.props` only works if you pass `props` to `super`. After the constructor finishes running, React will assign `this.props` manually itself, just in case you forgot to do it.

**Comment by cyberhck** [comment]
okay, understood. thanks.
