### ISSUE TITLE
Bad reading number with digit using ReactJS, NVDA and FireFox

### ISSUE THREAD

**Issue by dszymczuk** [facebook/react#9149]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

------

I write application with accessibility using ReactJS.
I have a problem with NVDA and FireFox - NVDA can't read number correctly.
I've found solution (use setTimeout with 0 delay), but I think, that can do it better.

I've created proof of concept to show the problem:
https://jsfiddle.net/IceManSpy/1bxu6aau/

**To reproduce - sad path:**
Run jsfiddle on FireFox
Run NVDA (you can open speech viewer)
Click sometimes on Random me! in Not works example
Check results - first value will be ok, but next not.
Sometimes will be (fe. 345.67):
345
67
but sometimes (it missing first digit):
45
67

**To reproduce - happy path:**
Run jsfiddle on FireFox
Run NVDA (you can open speech viewer)
Click sometimes on Random me! in Works example
Check results - every value will be ok.

**How can I resolve this problem without setTimeout ?**

------

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Windows, FireFox.

**Comment by jddxf** [comment]
I tried the demo with NVDA and firefox and it worked.Could you please provide a non-react version so that we can ensure the issue was caused by react?

**Comment by dszymczuk** [comment]
I've made investigation about this issue and I found problem -  version of ReactJS :)

New jsfiddles:
15.2.0 - https://jsfiddle.net/IceManSpy/9a5nrx4s/1/
15.1.0 - https://jsfiddle.net/IceManSpy/152wccyk/1/

**Comment by grzegorzjudas** [comment]
Can confirm regression in this scenario.

**Comment by jddxf** [comment]
The reason is that the implementation of  `setTextContent` was changed in #7005. I reproduced the issue [here](http://codepen.io/inamessnow/pen/NpgvEb?editors=1010) using plain js. Not sure whether this should be fixed in React though.

**Comment by aweary** [comment]
Yeah, I would recommend seeing if an existing issue exists at [nvaccess/nvda](https://github.com/nvaccess/nvda) and filing one if it doesn't, as this is a scenario they should support if possible. Thanks for bringing it up though @dszymczuk!

**Comment by dszymczuk** [comment]
I mentioned on nvda issue: https://github.com/nvaccess/nvda/issues/6963

**Comment by jcsteh** [comment]
I'm one of the lead NVDA developers.

The reason this occurs is that the entire text isn't removed and then deleted, but rather, it is changed. Thus, if you have the number "1.2" and replace it with "1.3", you'll only hear "3" because that's the only text that's new. Similarly, if you have the number "1.2" and replace it with "3.4", you'll get "3" and then "4" because that is the new text; the "." didn't change. Note that Firefox is calculating changed text, not NVDA; we handle the events Firefox sends us.

This behaviour is not incorrect: we shouldn't be reading content that hasn't changed (and Firefox shouldn't be sending us events covering content which hasn't changed). The controversial issue here is whether Firefox should treat changing nodeValue of a text node as an update or a remove/insert of the entire text. The latter is perhaps the "intuitive" behaviour in this case, but it may not be in all cases. Furthermore, I can see why that wouldn't be so easy internally; text nodes would need to be special cased.

Chrome "misbehaves" here as well, but differently: it causes the information to be spoken multiple times and it seems to strip common characters only at the start of the text. However, the fact that both browsers have issues here should serve to illustrate that this is not a trivial case to get right. Actually, Chrome misbehaves when setting textContent in some cases too.

A solution here is to set aria-atomic="true" to indicate that the entire node should be reported whenever it changes. Unfortunately, this will result in double speaking right now because multiple events are still fired.

More detail in nvaccess/nvda#6963.

**Comment by aweary** [comment]
@jcsteh thanks for chiming in!
