### ISSUE TITLE
[Feature/Issue] Throw Warning when defaultProp is set for a isRequired propType

### ISSUE THREAD

**Issue by Ethan-Arrowood** [facebook/react#9180]
**Do you want to request a *feature* or report a *bug*?**
*Feature*
**What is the current behavior?**
Currently, when you declare 
`TitleBar.propTypes = {
  title: React.PropTypes.string.isRequired
};`

And then declare
`TitleBar.defaultProps = {
  title: 'Default Title'
}`

When you go ahead and use the `<TitleBar/>` component without declaring the title prop no error is thrown (like is supposed to happen when using isRequired). Based on the documentation ([here](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)) it states 

> The propTypes typechecking happens after defaultProps are resolved, so typechecking will also apply to the defaultProps.

So this is expected behavior. I think when a user is using `isRequired` there should at least be a warning to change the propType typechecking to optional. 

Also I'd love to try and fix this myself so if I could get some pointers that would be much appreciated as I've never contributed to React before.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React version 15.4.2, Running Chrome on Mac OS X El Capitan V 10.11.6

**Comment by aweary** [comment]
Thanks for the issue @Ethan-Arrowood! Using `isRequired` and `defaultProps` together is kind of contradictory. If the prop has a default value then the user isn't actually required to provide it, since it already has a valid value. I would recommend either removing  `isRequired` (making it optional since a value is already provided) or removing the prop from `defaultProps` (making it required, since no default exists).

You could provide your own PropType validation function which warns if the prop's value is equal to the defaultValue

```js
SomeComponent.propTypes = {
  name: function(props, propName, componentName) {
   if (props[propName] === SomeComponent.defaultProps[propName]) {
     return new Error('Must provide a name prop')
   }
  }
}
```

But I don't recommend this, as it defeats the purpose of having a default value. Since this is a pattern isn't recommended and it is solvable in user space, I'm going to go ahead and close this out.

Hope that helps!

**Comment by janj** [comment]
Does it make sense to use `isRequired` with `propTypes` if what you want is an error to be thrown if provided a `null` value?
```
class ListOfThings  {}
ListOfThings.propTypes = {
    things: PropTypes.array.isRequired,
};
ListOfThings.defaultProps = {
    things: [],
};

Person.modelName = 'Person';
```
Just trying to clear up the statement `Using isRequired and defaultProps together is kind of contradictory.`
The user is not required to provide a value but they can not provide a `null` value. 
If you take off the `isRequired` and provide the default, like what that statement implies is the correct pattern, you could be left with a `null` value for `things` which could blow up your component if you're assuming `things` will be an array. We're able to pass a `null` value for any prop type that is not required.
If you make it require and provide a default you can still end up with a `null` value in the component but at least you'll get the error warning you.
Does that make sense?
