### ISSUE TITLE
Missing PropTypes warning when calling PropTypes directly with spread operator

### ISSUE THREAD

**Issue by bkozera** [facebook/react#9204]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
According to https://facebook.github.io/react/warnings/dont-call-proptypes.html#dont-call-proptypes-directly React should throw a warning when PropTypes are called directly. However, it doesn't do that when you use spread operator in validation function.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

Minimal demo: https://jsfiddle.net/uxc9pwd9/1/

**What is the expected behavior?**
Both components from them example should throw a warning.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
I see this issue on version 15.3.2 on Chrome. I don't think it's browser related. I don't know if it has worked in the past.

**Comment by aweary** [comment]
Thanks for the report @bkozera! This is expected behavior, you can see it explained in the [Fixing the false positive in third party PropTypes](https://github.com/facebook/react/commit/447e0a12b55f4570f62872e6ce50439704416ee) section on that same doc page.

>If you are an author of a third party PropTypes library and you let consumers wrap existing React PropTypes, they might start seeing this warning coming from your library. This happens because React doesn't see a "secret" last argument that it passes to detect manual PropTypes calls.

Since you're now passing all arguments to `React.PropTypes.string.isRequired` (including the secret) it does not warn. So this is a documented workaround for third-party libs.

Hope that clears things up a bit!

**Comment by bkozera** [comment]
![image](https://cloud.githubusercontent.com/assets/17122365/24053665/10b980d2-0b3a-11e7-9ba3-d82abcb04936.png)
I guess we will have to fire someone :D
@aweary thanks a lot for explanation!
