### ISSUE TITLE
React "value" setter overwrite lib "value" setter

### ISSUE THREAD

**Issue by FireVolkhov** [facebook/react#9206]
**Bug**

React "value" setter (https://github.com/facebook/react/blob/v15.4.2/src/renderers/dom/client/eventPlugins/ChangeEventPlugin.js#L183) overwrite lib "value" setter (https://github.com/RobinHerbots/Inputmask/blob/3.x/js/inputmask.js#L2808) 
And does not save the call to the old setter

**IE 11.0.9600.18538 
https://github.com/RobinHerbots/Inputmask 3.3.4
react 15.4.2**

**Comment by aweary** [comment]
Hey @FireVolkhov! Thanks for the report. If you're using a third party library to control an input's value, you shouldn't be using a controlled input (e.g., providing an `onChange` and `value` prop) since the input's value isn't really being controlled by React. You should be able to integrate with a 3rd party input library using an [uncontrolled component](https://facebook.github.io/react/docs/uncontrolled-components.html).

React expects elements it renders to be managed by React, so it's important to approach 3rd party DOM integrations carefully. 

Hope that helps!
