### ISSUE TITLE
Ref can not replace ReactDOM.findDOMNode

### ISSUE THREAD

**Issue by NE-SmallTown** [facebook/react#9217]
I notice that react will deprecated `ReactDOM.findDOMNode` and encourage developers to use `ref callback` instead.I agree with that in most cases it works fine.But think about something like this:

```
class A extends React.Component {
  render() {
    return (
      <div  id="containerA">
        <B><span>some content...</span></B>
     </div>
    );
  }
}

class B extends React.Component {
  render() {
    return (
      <div id="containerB">
         some cars....

         {this.props.children}
      </div>
    );
  }
}
```

For example,Now I want to know `containerB`'s `clientLeft`,but I can't just add ref such as `<B ref={ele => {this.containerB = ele;}}><span>some content...</span></B>` because the `ele` is instance of `B` **not** the containerB dom node.

But `ReactDOM.findDOMNode` can do that,just use `ReactDOM.findDOMNode(this.containerB ).clientLeft`.

Of course we can add `componentDidMout` in the `B` and use `<div id="containerB" ref={ele => {this.props.getContainerBClientLeft(ele.clientLeft)}}></div>`,and in `A`,add a method called `getContainerBClientLeft` and pass it to `B`.But IMO, this make the app more complex.What's your thoughts?

**Comment by gaearon** [comment]
`findDOMNode` is **not** deprecated. If it was deprecated then you would see a deprecation notice when calling it and in the API reference. 

It is discouraged in most cases (and people often use it unnecessarily), but it is useful exactly for the edge case you describe.

**Comment by NE-SmallTown** [comment]
Sorry,I am careless,[the change log](https://github.com/facebook/react/blob/6b1c86020da4e5f15686134b712fe7c3efa86022/CHANGELOG.md#removed-deprecations) just say that it moved from `react` to `react-dom`.

**Comment by NE-SmallTown** [comment]
@gaearon I notice that react-eslint has a [rule](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220) and link to the [previous discuss](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220),you actually say that "We want to deprecate it eventually (not right now) ".

So you mean that you change your idea now?

**Comment by NE-SmallTown** [comment]
@gaearon Hello?

**Comment by cPu1** [comment]
You can also pass the `ref` callback to `B` via `props`, and attach the reference in `A` when the callback is invoked.

```javascript

class A extends React.Component {
  render() {
    return (
      <div  id="containerA">
        <B bRef={ref => { this.containerB = ref; }}>
          <span>some content...</span>
        </B>
      </div>
    );
  }
}

class B extends React.Component {
  render() {
    return (
      <div id="containerB" ref={this.props.bRef}>
        some cars....
        {this.props.children}
      </div>
    );
  }
}

```
This is slightly better than defining a method on the component. The downside of this approach is having to pass the `ref` callback from the component needing the `ref` to the lowest-level built-in component (native DOM element) where the `ref` is attached.

**Comment by enisdenjo** [comment]
The thing is that when we try using some of the packages and their components which don't implement the flow @cPu1 described then we are left with two options. Recreate the actual component implementing the ref pass-down (which is NOT what you should do) or use the `findDOMNode`. This is the problem I experience a lot...

**Comment by gaearon** [comment]
Well you *can* use `findDOMNode` as an escape hatch. It is still available, just discouraged.

**Comment by catamphetamine** [comment]
Where can one find documentation about which methods other than the `.focus()` one are available on `ref`s?
And in which React versions were they added.

**Comment by estorski** [comment]
I'm looking for a `findDOMNode`-alike method for this use case:
- you are NOT allowed to use class components, only function components with hooks (because of clean code and eslint rules etc);
- you are creating a wrapper component, but you do NOT want to introduce any DOM elements (`div` or alike) within its rendering code, it just renders its `children` (because you normally don't want to deepen the DOM tree without any real need);
- the component you're creating needs to get its hands on the immediate DOM element rendered by its children, to read out some stuff, or manipulate it safely;
- you also want your wrapper component to be as universal as possible, so you don't want to depend on any specific API of the child components;

Is there any solution that meets all the points above?

**Comment by Venryx** [comment]
@kostia1st The only solution I know of atm is the workaround mentioned here: https://github.com/facebook/react/issues/28926#issuecomment-2684332400

Basically, rather than creating an extra "div" container element as the parent of the children, you create an extra _sibling_ of the children, get its dom element, and then traverse to the next sibling(s) using `.nextElementSibling`. If you also need to know where the children end, you could create an equivalent "div" element at the end, and stop iteration once you reach it.

Still kind of ugly (like the "div" container element), but in some cases it might be preferrable. (eg. because you can set those two sibling divs to be `display: none`, which you can't do for a container element)

**Comment by gaearon** [comment]
There’s a longer term first class solution being explored in https://github.com/facebook/react/pull/32465
