### ISSUE TITLE
 ReactComponentTreeHook of undefined

### ISSUE THREAD

**Issue by anyayunli** [facebook/react#9282]
**Do you want to request a *feature* or report a *bug*?**
`Bug`
**What is the current behavior?**
```Uncaught TypeError: Cannot read property 'ReactComponentTreeHook' of undefined
    at Object.132 (react-dom.js:17047)
    at s (react-dom.js:32)
    at react-dom.js:32
    at Object.50.132 (react-dom.js:8398)
    at s (react-dom.js:32)
    at react-dom.js:32
    at Object.64.50 (react-dom.js:9561)
    at s (react-dom.js:32)
    at react-dom.js:32
    at Object.75.157 (react-dom.js:11510)
```
throws error at: `module.exports = ReactInternals.ReactComponentTreeHook;`

all my codes is shown as follows in bundle.js,  which will be used as webpack entry:
```
require("../node_modules/react/react.js");
require("../node_modules/react-dom/dist/react-dom.js");
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
  "react": "^15.4.2",
  "react-dom": "^15.4.2"
```
chrome, macOS

**Comment by anyayunli** [comment]
fixed this error by moving those requires to index.html and replaced by traditional `<script src=""></script>`, any body knows why ?

**Comment by gaearon** [comment]
I think you have missed `/dist/` in React import, importing a CommonJS entry point by mistake? `react/react.js` is an internal file and you probably meant `react/dist/react.js` instead. You can't mix CommonJS-only entry points with UMD entry points. 

I also don't think you can use UMD bundles in a CommonJS environment without making it resolve `react` to the React UMD bundle. Otherwise there's no way for them to communicate.

The easy answer is: use UMD bundles in the browser, and use CommonJS entry points in a CommonJS environment. Don't mix them.
