### ISSUE TITLE
bug:while a value change to null ,the input show value do not change

### ISSUE THREAD

**Issue by jackmiking** [facebook/react#9335]
the demo is:    https://jsfiddle.net/8hgqc6yx/
while i set the value to null  the input only keep the last value rather than show a empty value while it should be.

**Comment by gaearon** [comment]
If you use development version of React (like I did in https://jsfiddle.net/jddt68xt/), you will see the warning:

```
Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
```

The reason is we're planning to change the behavior of `null` to match clearing the field, but it used to mean something else (namely switching component to be uncontrolled), so for now we just warn that we don't recommend setting to `null`.

To clear the input, set the value to an empty string instead: https://jsfiddle.net/7L5oLmva/.
