### ISSUE TITLE
Releases, changelogs, and/or tags for patches

### ISSUE THREAD

**Issue by JayAndCatchFire** [facebook/react#9413]
Currently I only see releases (on github), changelog entries, and tags for major and minor version bumps.  But being a curious developer, I'd also like to see what changes between patch versions on npm.  I don't know how or where to see those.

**Comment by gaearon** [comment]
We've been releasing a flurry of 15.5 versions due to newly discovered bugs with 15.5 deprecations and package split and cut four (for some packages, up to seven) patch versions in a week. We will catch up and push the changelog after we're more confident that they're stable but TLDR is you should use the latest patch version of 15.5 that's available.

**Comment by ignu** [comment]
i'm real curious about the 15.5.2 to 15.5.3 change

![pasted image](http://dl.dropbox.com/s/371sirfpujtpi7q/Screenshot%202017-04-12%2020.40.45.png?dl=0)

**Comment by gaearon** [comment]
There's not much interesting stuff there, it's mostly botched packages and publish mistakes.

**Comment by SavePointSam** [comment]
There's a bit more information about 15.{1,2,3,4} available in #9443 and what is going to be done to deprecate the broken builds.
