### ISSUE TITLE
Please stay PropTypes in lib

### ISSUE THREAD

**Issue by borm** [facebook/react#9418]
Subj,
vary many packages use it and very very many dependencies,
or create symlink in lib to 'prop-types' package

**Comment by gaearon** [comment]
Hi, splitting `prop-types` was an intentional decision. Libraries will have time to migrate before React 16, and this is why we put the move notice out now rather than later. There is also an automated codemod that you can use to update your apps (or libraries). Read more in our blog: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html.

I’m happy to answer specific concerns but this doesn’t look very actionable so I’m closing. I explained the motivation behind the change here in more detail: https://github.com/reactjs/prop-types/issues/21#issuecomment-293380920.
