### ISSUE TITLE
Add the PropTypes docs back

### ISSUE THREAD

**Issue by flarnie** [facebook/react#9467]
Where does proptypes doc live? It's confusing it's still on React object but inaccessible from the website through search or table of contents. Let's either reinstantiate it or move it fully to the standalone repo. Also it's confusing we're deprecating createClass but it still lives in the docs ("React without ES6") whereas we're just "moving" PropTypes but they're gone from the docs.

**Comment by bvaughn** [comment]
> Where does proptypes doc live?
> Let's either reinstantiate it or move it fully to the standalone repo.

Hm, well there's the [prop-types GitHub repo](https://github.com/reactjs/prop-types) which is duplicated on the [NPM module page](https://www.npmjs.com/package/prop-types)- though both also link to a section on the [React docs](https://facebook.github.io/react/docs/typechecking-with-proptypes.html)  as well. That section of the React docs doesn't seem to be picked up by the site search though.

**Comment by gaearon** [comment]
>That section of the React docs doesn't seem to be picked up by the site search though.

Yes, I think it's because it's not linked. We shouldn't have "hidden" sections for stuff that we didn't outright deprecate. Either we should keep it a visible part of React website (IMO a reasonable way to go), or fully split it out. Seeing that this is not a *reference* doc (just a guide), I think we should:

* Reinstantiate the guide in the "Advanced" section of docs
* Add a full API reference to `prop-types` README

Our guide will focus on the using PropTypes in React (just like it does now), and API doc in `prop-types` will focus on API reference (which we should remove from the `React` top-level reference doc in 16 but probably worth keeping a link in the meantime).

**Comment by bvaughn** [comment]
I like that suggested separation.

**Comment by flarnie** [comment]
Sounds good! On it.
