### ISSUE TITLE
Is it possible to alias routes in react-router like the way it is done in VueJs?

### ISSUE THREAD

**Issue by shweta-code** [facebook/react#9507]
I want to request a feature

Cannot alias routes .
For example : 
const router = new VueRouter({
  routes: [
    { path: '/a', component: A, alias: '/b' }
  ]
})

In VueJs, you can say , '/a' is the path which my application understands internally, one will link components using '/a' only. But from browser perspective, one can hit '/b' that resolves to '/a' internally.

Asked for react 15+.

**Comment by aweary** [comment]
Hey @shweta-code! This issue tracker is for React itself, not react-router, which is a [separate project](https://github.com/ReactTraining/react-router) driven by the community.

Since it looks like you're just looking for some support, I recommend checking out one of the great community-driven platforms like [Reactiflux](https://www.reactiflux.com/), [discuss.reactjs.org](https://discuss.reactjs.org/), or StackOverflow.
