### ISSUE TITLE
Doc: State and Lifecycle

### ISSUE THREAD

**Issue by giorgim** [facebook/react#9529]
From doc (https://facebook.github.io/react/docs/state-and-lifecycle.html) about State and Lifecycle there is this class
```

class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  componentDidMount() {
    this.timerID = setInterval(
      () => this.tick(),
      1000
    );
  }

  componentWillUnmount() {
    clearInterval(this.timerID);
  }

  tick() {
    this.setState({
      date: new Date()
    });
  }

  render() {
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
      </div>
    );
  }
}

ReactDOM.render(
  <Clock />,
  document.getElementById('root')
);
```

My question is: since setState is asynch can't it happen that some calls to setState inside tick function get a pending state, and for example for three seconds update won't be applied to the state? In that case, we could get three seconds missing from the UI, isn't it (or applied after delay)? Or I am wrong?

**Comment by TrySound** [comment]
@giorgim If you will use functional setState new date will be set without delays
```js
this.setState(() => ({
  date: new Date()
}));
```

**Comment by giorgim** [comment]
@TrySound Well maybe but if the example in the official doc is flawed maybe someone want to correct it?

**Comment by gaearon** [comment]
React currently batches changes inside event handlers, so if you were inside an event handler and called `setState` on multiple components, the changes would be applied in one pass after event handler has run, rather than on each individual call. So this is an example where `setState` is async. But we're talking about a delay of a couple of milliseconds—not something like three seconds.

In future versions React may batch changes under more conditions, including within intervals. But the goal is always to stay responsive to user input. Definitely you won’t be seeing a three second delay here.

Does this help?

**Comment by giorgim** [comment]
@gaearon It helps so my point was correct just your answer is that in practice the delay won't be so long, correct?

> In other cases there is absolutely no difference between functional and object form. Using functional form has no implications on when React updates the DOM.

Does not this contradict with the statement that functional form gives you fresh copy of state? If there is a pending setState and it has not been applied yet - which state do you get, the pending one? or the old one.


Finally, I think you still didn't address my concerns here:
http://stackoverflow.com/questions/43428456/do-i-need-to-use-setstatefunction-overload-in-this-case
(see last three comments)

**Comment by gaearon** [comment]
I edited my answer to be more precise, does this answer your question?

**Comment by gaearon** [comment]
>Does not this contradict with the statement that functional form gives you fresh copy of state?

I don’t think so.

Using functional form gives you "another chance" at choosing the new state value at the time the update is applied. This solves the problem when your state depends on previous state, and you want to schedule multiple independent updates, but they haven’t been applied yet. So React lets you say “okay, React, I don’t know the current state, but I need it to calculate the next one, so I’ll just give you a function, and you’ll call it when you’re ready”.

That’s all functional form does. The object form is equivalent to using functional form with a constant return value. The functional form doesn’t cause updates to happen earlier or later, it just gives you a chance to adjust the state based on previous state.

**Comment by giorgim** [comment]
@gaearon You mean SO answer? it shows last edit 16 april.

I understood your answer to this thread. But following still not:

> In other cases there is absolutely no difference between functional and object form. Using functional form has no implications on when React updates the DOM.

Does not this contradict with the statement that functional form gives you fresh copy of state? If there is a pending setState and it has not been applied yet - which state do you get as previousState when calling functional setState, the pending one? or the old one?

**Comment by gaearon** [comment]
I also addressed your comment about two event handlers. They still get batched: http://stackoverflow.com/questions/43428456/do-i-need-to-use-setstatefunction-overload-in-this-case#comment74310945_43440790

**Comment by gaearon** [comment]
>If there is a pending setState and it has not been applied yet - which state do you get as previousState when calling functional setState, the pending one? or the old one?

You get the pending one—and you get it *after* it has been applied (but not flushed to the DOM or `this.state` yet). This is the whole reason functional API takes a function: so that React can call it *later* when it *knows* the `prevState`. Think of this as a queue of functions. We’re ready to call the next function when we know the result of the previous one.

>You mean SO answer? it shows last edit 16 april

Sorry, I meant this comment: https://github.com/facebook/react/issues/9529#issuecomment-297329061. I edited it a few time after posting, and I removed the sentence you’re quoting, as it could indeed be confusing. I replaced it with a hopefully clearer explanation.

I also just added this note to the SO answer:

<img width="850" alt="Note: there is also another edge case pointed out in the comments: if you have several onClick handlers, the same pitfall applies: once you call setState() in a child event handler, you can’t rely on this.state being updated by the time the parent event handler runs. In fact it’s the reason this optimization is so useful: all setState() calls from a single browser event are batched, whether they happen in one or different components while the event bubbles.
" src="https://cloud.githubusercontent.com/assets/810438/25430360/407a40f0-2a74-11e7-8bdd-80f49bf9d19e.png">

**Comment by giorgim** [comment]
@gaearon Thanks for all responses, I think things are more clear especially about SO question, but it would do no harm IMO if someone could comprehensively address how setState in functional form works, and put it somewhere on blog maybe etc :).

**Comment by gaearon** [comment]
We’re in a bit of transitional period right now, as this is exactly the aspect we’re working on changing in future releases. So I’d like to avoid diving into details too much before we figure out the plan and see what works best with our product code.

**Comment by giorgim** [comment]
@gaearon OK nice but then this is such a fundamental aspect that it would be nice that it is covered in most details possible, so that people are not confused about it anymore.

**Comment by giorgim** [comment]
@gaearon :( still not sure I understand how setState in functional form works, but I am closing this issue anyway. I'll come back to this issue later maybe.

**Comment by gaearon** [comment]
@giorgim 

I’m happy to answer if you can formulate the question in a specific way. “How it works” is a very vague question, ranging from API to implementation details to practical usage, etc. Since it’s not what *exactly* you’d like to learn, I find it difficult to give you a specific reply.

**Comment by gaearon** [comment]
The API contract is:

* If your next state depends on current state or props (example: incrementing a counter), use the functional form.
* Otherwise it doesn’t matter (you can use either form).

The functional form works by giving you `prevState` and `props` in the callback so that you can use them to calculate the next state and return it.

That’s about it. Now, more specific questions are *implementation details* that may change in the future, and you should not rely on them even today. I think this should give you enough information to use the API, but if not, please ask more specific questions, and I’ll be happy to explain.

**Comment by giorgim** [comment]
@gaearon OK when I come up with more specific question I will get back to this, and tag you and hopefully get response :)

**Comment by gaearon** [comment]
Sounds good! 👍
