### ISSUE TITLE
Marking as an external in Rollup shouldn't include unused modules

### ISSUE THREAD

**Issue by gaearon** [facebook/react#9542]
See https://github.com/facebook/react/pull/9534 for details.

**Comment by trueadm** [comment]
Some context, when we have something like this in our code base:
```js
if (__DEV__) {
   var Foo = require('Foo');
}
```
If the above `Foo` require is an external module, we need to pass `Foo` to Rollup's externals. Although, because of dead-code elimination, the `Foo` module is never actually needed. Rollup doesn't get this and because `Foo` is in externals, adds in the require any way.

The only real way (for now) to fix this, is that we avoid putting things in externals that we know may be stripped later and hack around the warning thrown by Rollup and where something is in the external list, we don't show the warning/error and continue as normal. It means that we're essentially handling externals, rather than Rollup, which hopefully should prevent Rollup from adding in rogue requires.

@Rich-Harris told me another hacky way to get around this before, but given the amount of these we're running into, I feel we should attack this a different direction.

Separately from this but also related, once we migrate from `requires` to ES2015 `import`, we'll no longer be able to wrap these in `__DEV__` blocks. How do we deal with these cases?

**Comment by Rich-Harris** [comment]
> It means that we're essentially handling externals, rather than Rollup, which hopefully should prevent Rollup from adding in rogue requires.

Unfortunately it doesn't work that way — if Rollup doesn't know how to resolve a module ID, it will basically *add* it to the `external` list. The only difference between specifying it in `external` and not doing so is whether or not you get the warning (specifying `external` is your way of saying 'chill out Rollup, I know what I'm doing').

As far as Rollup is concerned, externals are never 'unused', because they might have side-effects — it has to err on the side of caution. Fixing this at the Rollup level would basically entail adding a new option that allowed you to specify which external modules have no side-effects (and can therefore safely be omitted if none of their exports are used in the bundle).

**Comment by trueadm** [comment]
@Rich-Harris Is this something that could be added as a feature? It would massively help us on this last hurdle :)

**Comment by Rich-Harris** [comment]
Could you add an issue please? (The issue tracker is a dumpster fire at the moment, but I'll get to it soon...)

**Comment by gaearon** [comment]
`pureExternalModules` solves this.
