### ISSUE TITLE
Warn when PureComponent renders impure ones as its children

### ISSUE THREAD

**Issue by otakustay** [facebook/react#9559]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When a PureComponent renders an impure one as its child, no warning in console or devtool

**What is the expected behavior?**
It could be better if we get a warning message for such cases

This may be related to https://github.com/facebook/react/pull/9240 since React now disallow PureComponent to have a custom `shouldComponentUpdate` implement, so a "pure" component with customized and more efficient `shouldComponentUpdate` method must inherit from `Component` base class and add a `isPureReactComponent` property themselves in order to prevent the warning message appear

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.5.4

**Comment by Hypnosphi** [comment]
I'm not sure that having a `Component` inside a `PureComponent` couldn't be something that one actually wants. This would mean that you want both parent and child to rerender whenever parent's props or state change.

**Comment by otakustay** [comment]
Let's get rid of the `PureComponent` base class first, a pure component means one "renders the same element given the same props and state", on contrast a impure one means "may render different result even props ant state stays unmodified"

In this case, impure has a characteristic of **spreading**, any component contains an impure component should be impure, a impure component's parent cannot assume its render result to be stable when props and state remains unmodified, that's why I'd rather propose such warning message

By now react can mark a component as pure by setting `isPureReactComponent` property to `true` even it does not extend `PureComponent` base class

One remaining issue is most of current 3rd party component in react ecosystem do not mark themselves as pure, so this warning message may appear unexpected, I think a `isImpureReactComponent` could be a solution with better backward compatibility

**Comment by aweary** [comment]
> By now react can mark a component as pure by setting isPureReactComponent property to true even it does not extend PureComponent base class

You shouldn't ever define `isPureReactComponent` yourself, it's an internal flag. Defining it yourself on components that do not extend from `PureComponent` may lead to unexpected behavior in future releases.

**Comment by otakustay** [comment]
So it's currently no method other than `PurceComponent` to hint a component is pure or impure, it seems weird to me if I decide to include a 3rd party component which does not extends `PureComponent` then I don't know whether it's impure and whether I can use `PuceComponent` on my parent component

**Comment by Hypnosphi** [comment]
>So it's currently no method other than PurceComponent to hint a component is pure or impure

Alternatively, you can write your own implementation of `shouldComponentUpdate` and even share it across your codebase

**Comment by otakustay** [comment]
Probably we are talking about different stories

Imagine you need a `Weather` component and you find a `react-weather` from npm registry, you just include it in your root component:

```js
class App extends PureComponent {
    render() {
        return (
            ...,
            <Weather date={this.state.today} />
        );
    }
}
```

However you don't know whether this 3rd-party component implements its render method like:

```js
render() {
    return <span>{format(new Date(), 'YYYY-MM-dd HH:mm:ss')}</span>
}
```

in this case, this component is **impure** and will change its render result even though `state` and `props` stays the same

Now the problem is, without reading its source code you are unable to tell if it is impure, so it's impossible to make a decision whether to let `App` extends `PureComponent` or just `Component`

Because react does not share a mechanism to explicitly detect a component's purity, as a result almost all components cannot inherit from `PureComponent` and cannot implement their own `shouldComponentUpdate` based on props and state, which finally impacts performance

**Comment by faizah24** [comment]
(Y)

2017-05-02 19:34 GMT+08:00, Gray Zhang <notifications@github.com>:

**Comment by variousauthors** [comment]
I'm new to this and might not know what I'm talking about, but...

```
class Widget extends React.PureComponent {
  render () {
    return (
      <div>
        <h1>Weather for { format(this.props.date) }</h1>
        <Weather date='this.props.date' />
      </div>
    )
  }
}
```

Suppose that the `Weather` component has some state which is set internally using `setState`, and which changes on a timer (maybe it re-queries the weather for the given date periodically). What would be the actual behaviour?

My expectation is:
 - Widget's render method is only called when `this.props.date` changes, when for example the parent component re-renders and passes in a different value for `date`
 - Weather's render method is called whenever the parent re-renders (purely)
 - Weather's render method is called whenever `setState` changes the state of the component, i.e. whenever it refetches the data

Am I wrong? 

(if I'm wrong, then don't read the next paragraph and if you have time please let me know why I'm wrong)

If I'm right, then: weather does render the same thing regardless of what you give it for props. It renders "a div with the date, and a render function". Why does it matter that the child component is changing periodically? Like, to me this feels roughly equivalent to:

```
const weather = R.memoize((date) => {
  return {
    day: format(date),
    weather: {
      render: () => Weather(date),
    }
  }
})

const date = Date.now()
expect(weather(date) === weather(date)).toBe(true)
expect(weather(date).weather.render() === weather(date).weather.render()).toBe(false)
```

The weather function is pure. It doesn't care that Weather is impure, because it is only returning a render function. Right?

Full Disclosure: I have just walked into this conversation, and this is Facebook, and I may be waaaay out of my league here.
