### ISSUE TITLE
Why react changed the behaviour of 'onChange' to behave exactly like 'onInput' when there was already onInput available ?

### ISSUE THREAD

**Issue by nikhilgoyal104** [facebook/react#9567]
Here's what the official docs say about onChange:-

The 'onChange' event behaves as you would expect it to: whenever a form field is changed, this event is fired. We intentionally do not use the existing browser behaviour because 'onChange' is a misnomer for its behaviour and React relies on this event to handle user input in real time.

https://facebook.github.io/react/docs/dom-elements.html#onchange

But there is already an event which fires on every keystroke, i.e. 'onInput'. So I don't understand why react changed the behaviour of 'onChange' to behave as 'onInput'. Also in the docs, everywhere 'onChange' is used. Is there any specific reason for it ? Are the two completely interchangeable in react 
 ? Now there is no event with the behaviour of actual 'onchange' . Does react intend to correct this in future ? 

Here's the code for that :-

https://jsfiddle.net/nikhilgoyal104ah4/69z2wepo/77518/

**Comment by gaearon** [comment]
Maybe @tomocchino can provide some historical context.

I think that at the time this decision was made (~4 years ago?), `onInput` didn’t work consistently between browsers, and was confusing to people coming to the web from other platforms, as they would expect the “change” event to fire on every change. In case of React it is a bigger issue because if you fail to handle change soon enough, the controlled inputs never update, leading people to think React is broken. So the team went with calling it `onChange`.

In retrospect it might have been a better idea to polyfill `onInput` and keep its name rather than change the behavior of another event. But that ship has sailed a long time ago. We might revisit this decision in the future, but I would just encourage you to treat it as a quirk of React DOM (which you’ll get used to pretty quickly).

I hope this helps!

>Now there is no event with the behaviour of actual 'onchange' 

It is not very useful in apps anyway. Quoting [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/change):

>Different browsers do not always agree whether a change event should be fired for certain types of interaction.

Would you want your app to rely on this? As far as alternatives go, `onBlur` in React gives you pretty much the same kind of behavior, so you can use it instead of browser’s `onchange`.

**Comment by Kasopej** [comment]
Other frameworks have solved this without reinventing web events.. because an element is controlled does not mean that the DOM should be blocked from updating its textContent/value via user interaction, hence there would be no need to rely on the callback to do this.. 

the "control" binding should basically be a setter for that input if the control changes.. unfortunately because react weirdly chose to rerender the whole component tree on every update, instead of tracking changed dependencies & their bound nodes, you need to literally break the web standard
