### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by zhuyinjing** [facebook/react#9590]
the error is Uncaught TypeError: Super expression must either be null or a function, not undefined
how should i do?
i really want to know!!!
thanks so much!!!

**Comment by gaearon** [comment]
We can't help if you don't provide the code reproducing the issue. Why did you delete the issue template?

**Comment by aweary** [comment]
Since there's been no response @zhuyinjing I'm going to close this out. I assume it was a usage issue that you've figured out. If you are still having a problem and believe it's an issue with React, please respond with an example reproducing your issue. You can use https://jsfiddle.net/84v837e9/ as a template.
