### ISSUE TITLE
ReactInputSelection TypeError

### ISSUE THREAD

**Issue by maxsalven** [facebook/react#9628]
I got an automated error report from Sentry relating to ReactInputSelection, and thought I would notify you in case this is of interest.

Unfortunately I do not know what the user was doing when this happened. 

Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

react-dom 15.4.2

<img width="1083" alt="screen shot 2017-05-08 at 7 53 22 pm" src="https://cloud.githubusercontent.com/assets/4144910/25831281/a1d1b906-3428-11e7-835a-f4ca248e7018.png">

**Comment by aweary** [comment]
Hey, @maxsalven, sorry we didn't respond to your issue. Sometimes issues fall through the cracks, and it's difficult to prioritize issues that we can't reproduce. Since we don't have any information about how this error occurred, and we haven't received any additional reports, I'm going to assume that it was either resolved or a one-off issue.

If you're still seeing this issue with the latest version of React, please feel free to ping me with an example reproducing the issue.

Thanks!
