### ISSUE TITLE
persistant event

### ISSUE THREAD

**Issue by TrejGun** [facebook/react#9630]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
persistent event is broken
console prints different values before and after async operation
```
["number", "3"]
["number", ""]
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**
http://codepen.io/trejgun/pen/YVYYqO

**What is the expected behavior?**
console should print same value before and after async operation 
```
["number", "3"]
["number", "3"]
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

i'm using
react 15.5.4
chrome 58.0.3029.96 (64-bit)
os mac

**Comment by aweary** [comment]
Hey @TrejGun! Thanks for taking the time to write up your issue.

The problem you're seeing is not due to event persistence, it's because you're never actually updating the `value` passed into your input inside your `Form` component. So when you enter a number, like `3`, the event target has that new number. But since that new value isn't being tracked (`this.props.price` isn't being changed) React reverts it back to the original value, keeping the input _controlled_ as you would expect.

[Here is fork of your example](https://jsfiddle.net/a1gnv17L/) that does track `price` in state and appropriately updates it in your change event handler. You'll see you get the expected behavior in this case.

Hope that helps!

**Comment by TrejGun** [comment]
@aweary thanks for yo answer

you basically say I have to change order of helpers
thanks, that helps
