### ISSUE TITLE
[feature-request] make writing css easy

### ISSUE THREAD

**Issue by ashokkumarsand** [facebook/react#9632]
For react we need some external apis for the write css. that is quite difficult. Like event handling react component should have support for the css with pseudo selectors which is missing.

Like we have static block for style

styles {
 .classname:: pseudo {
  }
}

or @style("./path/to/file.css")
@component
class Component {
}

**Comment by aweary** [comment]
Hey @ashokkumarsand, thanks for taking the time to write up your suggestions. Introducing a new API for handling CSS may provide some value, but it could also introduce significant overhead and affect performance and bundle size. 

There are currently a bunch of community driven projects that implement an API similar to what you're requesting, such as [glamor](https://github.com/threepointone/glamor), [aphrodite](https://github.com/Khan/aphrodite/), [styled-components](https://github.com/styled-components/styled-components), [fela](https://github.com/rofrischmann/fela) and more.

Since this problem is very difficult to solve within React itself, and many highly-performant and stable solutions exist in the community, I'm going to say this is something that won't be included. I recommend checking out [Reactiflux](https://www.reactiflux.com/) or [discuss.reactjs.org](https://discuss.reactjs.org/) for more discussion on the topic.

I hope that helps!

**Comment by ashokkumarsand** [comment]
@aweary There are many third party apis, but they didn't full filled standard. If we have like something  style tags which is like polymer which fulfilled communities need. mostly all things are hack based not like a standard.

**Comment by bvaughn** [comment]
FWIW I've found React + [css-modules](https://github.com/css-modules/css-modules) pretty nice to work with for application code. Can be tricky if you have a mix of dynamic values (eg themes, or props-driven-styles) but otherwise I think the modules approach is pretty nice.
