### ISSUE TITLE
No error when element with ref created in another elements constructor in dev environment.

### ISSUE THREAD

**Issue by monkeyboy64** [facebook/react#9635]
When creating an Element with a ref from inside of a constructor an error is thrown in production mode, but not in dev mode.

Here is a minimal sample:
https://jsfiddle.net/84v837e9/35/

An error, "Only a ReactOwner can have refs", should happen in dev and production modes.

This is happening in React 15.4

**Comment by LemonPi** [comment]
I also encountered the same issue, originally posted in as issue facebookincubator/create-react-app#2460 in the CRA repo.

### Description

According to [the docs](https://facebook.github.io/react/warnings/refs-must-have-owner.html) `ref`s should only be assigned inside a component's `render()` method. I didn't know this and created a composed component inside the constructor, assigning its `ref` there. 

Testing with `npm start` runs without any errors or warnings, but running the production build after 
`npm run build`
`serve -s build` 
Produced an error and the rest of the application stopped working.

### Expected behavior

`npm start` should also give the same error. I expect if the development application works then the production one will as well.

### Actual behavior

No error or warning under `npm start`.

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls react-scripts` (if you haven’t ejected):  react-scripts@1.0.2
2. `node -v`: v6.9.4
3. `npm -v`: 3.10.10
4. react 15.5.4

Then, specify:

1. Operating system: Windows 10 Home Version 1607
2. Browser and version: Google Chrome 58.0.3029.110 (64-bit)

### Reproducible Demo

See project: https://github.com/LemonPi/cra-refs-bug with a readme on what it demonstrates
See deployed version that errors out: https://lemonpi.github.io/cra-refs-bug/ or `npm run build` and `serve -s build`

**Comment by gaearon** [comment]
This likely is a bug. I have a hunch it might be already fixed on master. I'd appreciate if somebody could confirm that by writing a failing test.

**Comment by iansu** [comment]
@gaearon I've been following this thread and would be interested in verifying the bug and attempting to fix it if it does still exist. Unless either of the bug reporters would like to tackle it.

**Comment by gaearon** [comment]
Sure, go ahead! You'll need to look for assignments to ReactCurrentOwner.current which is what seems to deviate in production. I think deviation was intentional but we either didn't consider this case (breaking refs in constructor) or we had some protection against it that got lost at some point.

**Comment by iansu** [comment]
I've added a test to verify that this bug does still exist on master. I'll look into fixing the bug next.

**Comment by aweary** [comment]
This was fixed with https://github.com/facebook/react/issues/9635

**Comment by iansu** [comment]
@aweary I think you mean it was fixed with #10025. 🙂

**Comment by aweary** [comment]
@iansu thanks, copy-paste error 😄
