### ISSUE TITLE
React.Children.map(children, (child, index) => but got child.type.name is undefined on IE browser

### ISSUE THREAD

**Issue by SimonCheung1989** [facebook/react#9803]
as title, i want to get child element's tag name, 

        ```
        const { children, theme } = this.props;
        const { open } = this.state;

        let summary = null;
        const otherChildren = [];
        React.Children.map(children, (child, index) => {
            if (child.type) {
                console.log(`child type.name: ${child.type.name} `);
            }
            if (child.type && child.type.name === 'Summary') {
                summary = cloneElement(child, {
                    children: child.props.children,
                    handleClick: this.handleClick,
                    handleKeyPress: this.handleKeyPress,
                    theme: child.props.theme
                });
            } else {
                otherChildren.push(child);
            }
        });
```
**Success in Chrome browser**

![image](https://cloud.githubusercontent.com/assets/12840387/26545546/91d55f64-4498-11e7-8dfd-ebd4f383b0c0.png)

**Failed in IE browser**

![image](https://cloud.githubusercontent.com/assets/12840387/26545680/1c07cd48-4499-11e7-9a5e-ffe19013e6fa.png)

**Comment by SimonCheung1989** [comment]
**Success in Chrome browser**
![image](https://cloud.githubusercontent.com/assets/12840387/26545718/4bf94ce8-4499-11e7-8aaa-b0ab1242fa58.png)

**Comment by SimonCheung1989** [comment]
**Failed in IE browser**
![image](https://cloud.githubusercontent.com/assets/12840387/26545730/5f7a5794-4499-11e7-8ca5-67d6bb37e118.png)

**Comment by nhunzaker** [comment]
Hey @SimonCheung1989 It's possible that this is failing because `this.type` references the constructor function for the component. `function.name` isn't supported in IE, only Edge+: 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

So, taking this example:

https://jsfiddle.net/84v837e9/

<img width="474" alt="screen shot 2017-05-29 at 7 47 23 am" src="https://cloud.githubusercontent.com/assets/590904/26548622/1244421a-4443-11e7-875e-c58222adbe44.png">

`type` here is a reference to the component constructor. So if you do `child.type.name`, it references the name property on the constructor -- no supported in IE.

**Comment by aweary** [comment]
Sounds like that's the problem. If you control the components that are being rendered as children you can get around this by using a static property like `displayName` instead of relying on the environment to provide the name for you.

```js
Summary.displayName = "Summary"
```

Then you can check for `child.type.displayName` instead!

Since this is just an aspect of the environment that React can't really control, I'm going to close this out, but hopefully, that workaround helps!
