### ISSUE TITLE
Does keys for children really improve performance?

### ISSUE THREAD

**Issue by benweizhu** [facebook/react#9826]
Originally I try to use React Perf tool to prove this theory, So I write code to do an experiment.

https://github.com/benweizhu/react-redux-you-should-know/tree/master/unique-keys-for-children

But then I found out the opposite the result.

![image](https://cloud.githubusercontent.com/assets/5471228/26673026/ffb94f7a-46ed-11e7-9003-78eb6824a218.png)

Can someone explain why or correct me if I am testing it in wrong way?

**Comment by benweizhu** [comment]
Acutually, when I add more, it appears to be right.

![image](https://cloud.githubusercontent.com/assets/5471228/26673917/24c2b27c-46f1-11e7-936e-440d5da66dfb.png)

**Comment by gaearon** [comment]
Keys ensure that when you reorder items, React treats it as a reorder rather than update of each item in the list. This is important not only for reordering, but also for correctness. Because otherwise you might end up with nested state staying "at the same place" while the parents conceptually "moved". Like if you have a reorderable list with input fields inside.
