### ISSUE TITLE
Add an export of html props in react package since React is already using them for validation

### ISSUE THREAD

**Issue by ThomasJuster** [facebook/react#9878]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The react package does not provide a list of acceptable props for html node (div, span, etc.)
Sometimes, other packages pass on other props, like react-redux passing `dispatch` when no `mapDispatchToProps` is provided. This (below) will pop an error saying there's an unknown prop `dispatch` on a `div` tag
```
const { myProp1, myProp2, ...otherProps } = this.props
return <div {...otherProps}>...</div>
 ```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

**What is the expected behavior?**
Since React is using a list of those props for validation, the react package should also provide them to allow react users to make sure they pass on normal props

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
15.5

**Comment by aweary** [comment]
Thanks for taking the time to write up the request @ThomasJuster! Future versions of React will not warn about unknown props on DOM elements. We advise that you avoid spreading props onto DOM nodes in general unless you can guarantee they contain only valid HTML attributes. The warning was put into place to ease the transition, as React will eventually just let all attributes pass through.

Since React will be removing this validation layer, it won't be available to export. You can check out https://github.com/facebook/react/pull/7311, which implements this change.

Hope that helps!

**Comment by aweary** [comment]
As an example, you can use spread to _avoid_ passing down invalid props/attributes

```js
// rest will contain any additional, unknown props
const { className, style, ...rest} = this.props;
return <div className={className} style={style} />
```
