### ISSUE TITLE
[Urgent] Doesn't support the latest builds of React-Native and React

### ISSUE THREAD

**Issue by vadiminc** [facebook/react#9915]
it's not possible to use with latest 2 builds of react-native and react. it's related that react-native works already with 16.0.0-alpha.xx builds. But react-dom doesn't support it and the app is crashes.

**Comment by gaearon** [comment]
React Native depends on an `alpha` version of `react` package because it has a faster release cycle. Please use whatever version of `react` that React Native tells you to.

There *exists* a related `react-dom` version but it’s not ready for public consumption yet.

I’m not sure what the issue is, so I’ll close. It seems intentional to me. If you have problems please describe them in more detail (e.g. why do you need `react-dom` in a React Native project, and what crashes).
