### ISSUE TITLE
String Refs Without An Owner Should Fail Gracefully

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/react#9962]
Occurs in Fiber with multiple instances of the React package (which can't share current owner).

**Comment by flarnie** [comment]
**Context:**

- When users are loading multiple copies of React, it commonly causes this error:
https://facebook.github.io/react/warnings/refs-must-have-owner.html

We theorize that this may be triggered by different versions of React being required for libraries depending on React. As libraries update to support version 16, this may come up more commonly than in the past.

At the very least, it seems common enough now to be worth fixing, with 300+ issues open across various libraries: https://github.com/search?q=%22Refs+must+have%22&type=Issues&utf8=%E2%9C%93

Folks on this issue are helping out with more info about how to reproduce and debug this state: https://github.com/facebook/draft-js/issues/296

**Plan:**
MVP:
- [ ] Add a warning for any time that multiple copies of React are loaded. 
- [ ] Link to documentation about how/why this might happen and how to fix it.

Bonus:
- [ ] Indicate multiple copies of React with the devtools icon
- [ ] (?) Add a work-around in the code itself such that React itself will work ok even when you have loaded multiple copies. -> We might not want to do this, since it allows users to continue in a "broken" state.

**Comment by gaearon** [comment]
>At the very least, it seems common enough now to be worth fixing, with 300+ issues open across various libraries:

To be clear, I think this issue is not about completely fixing this error, but about making the error message comprehensible in Fiber.

Stack produced an error message that linked to the error page. But Fiber just errors a TypeError. I believe this issue was about Fiber parity with Stack in failing gracefully rather than crashing in an internal.

But surely we could make the message better by including debugging instructions, and improve error page. We can also take a stab at, if not fixing, reducing how common it is, by extracting a separate package for shared mutable state. But I think that would be worth extracting into separate issue, and it doesn’t block 16 beta.

**Comment by flarnie** [comment]
Thanks for clarifying this - 
> "But Fiber doesn't show this message at all—it just crashes with a TypeError."
I did notice that, you're right that fixing that is the main blocker.

We can improve that error message to make it on par with the "Refs must have owner" warning. Maybe that's an acceptable first step.

It seems to me that reaching that point is just a symptom of the larger problem. We don't support having two versions of React running, and it's usually done by mistake when it happens. If we add a warning and better docs around that I think that will help even more, but that also is not needed for the 16 beta release so I can open a separate issue for that.

**Comment by gaearon** [comment]
I think adding a warning was discussed before (https://github.com/facebook/react/issues/2402) but there was no clear way of how we’d go about it. There are legitimate cases for independent Reacts on the same page (e.g. third party widget that you have no control over), and it works if they don’t “cross” with each other.

I think doing this in DevTools is a great idea though.

**Comment by flarnie** [comment]
Thanks for linking to that issue - that is great context. Looks like there was a warning, then it was removed, then it was added again, then removed at some point.

Was it a pain point for people to have the warning? I don't open a new issue if we've already decided that we generally support loading two copies of React and are not going to warn for it.

**Comment by gaearon** [comment]
I think the best explanation is in https://github.com/facebook/react/pull/3580#issuecomment-91370469. There are legitimate cases for when you’d want to do it. I agree we need to only warn for patterns that are clearly unsupported. DevTools seems like best of both worlds: it lets you know something is suboptimal, but doesn’t spam your console.

**Comment by nareshbhatia** [comment]
I am running into this issue with my app created with create-react-app. I am pulling in a library that uses react and also using Storybook from tests. I eliminated react from both those and I am down to one copy as indicated by `npm ls react`:

```
myapp@0.1.0 /projects/myrepo/packages/myapp
└── react@16.3.0
```

Is there a way to figure out where react thinks the second copy is being loaded from?

**Comment by nareshbhatia** [comment]
Well, after a full day of trial-and-error, I figured it out. The second copy was coming from Storybook. The moment I removed it, everything started working. Wish React just told me where the second copy was coming from!

**Comment by nareshbhatia** [comment]
To resolve the issue, I tried to restructure my repo and move storybook to a dev dependency - hoping that it will prevent the second copy from being loaded. Unfortunately it did not solve the issue. I have created a reproducible example here: https://github.com/nareshbhatia/react-multiple-copies-issue. It contains my library in one package and an app in another package (created with create-react-app). Would really appreciate if someone could explain what is going on. How is the second copy being loaded?
